### ISSUE TITLE
Get DLL error

### ISSUE THREAD

**Issue by ddiguy** [dashingsoft/pyarmor#1]
I am installing on Mac.

Downloaded code from https://pypi.python.org/pypi/pyarmor

$ python pyarmor.py capsule brian
INFO     Searching pytransform library ...
ERROR    No library /Users/bbullard/Downloads/pyarmor-3.1.3/platforms/macosx_10_12_intel/_pytransform.dll found

Can you advise what I should do?

**Comment by jondy** [comment]
Sorry, macos is not supported by now. I'll try to build a macos version and inform you ASAP.

**Comment by jondy** [comment]
[darwin_x86_64.zip](https://github.com/dashingsoft/pyarmor/files/1346084/darwin_x86_64.zip)

Extract 2 files from attachment:
- _pytransform.dylib  
- pytransform.py

Copy them to source path of pyarmor, then run pyarmor.py in macos.

I have not test this in macos, only cross build dynamic library by this tool 
https://github.com/tpoechtrager/osxcross.git

Hope it works!

**Comment by jondy** [comment]
macos has been supported from [v3.1.5](https://github.com/dashingsoft/pyarmor/releases/tag/v3.1.5)
