### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yuseffathi** [dashingsoft/pyarmor#1001]
hi, I tried many time sence the Pyarmor 8.0.0 to install it in macOS with python 3.11 m1 apple silicon  but same error 
in this screen.
<img width="1036" alt="Screenshot 2023-03-24 at 2 50 35 AM" src="https://user-images.githubusercontent.com/15668446/227396942-33a9920c-2a15-4d73-98e2-a25ed422519d.png">

**Comment by jondy** [comment]
Pyarmor 8.0 doesn't support Apple Silicon, please refer to pin issue #980
