### ISSUE TITLE
[Question] Operation did not complete successfully because the file contains a virus or potentially unwanted software

### ISSUE THREAD

**Issue by Zimaco** [dashingsoft/pyarmor#1002]
**Operation did not complete successfully because the file contains a virus or potentially unwanted software**

pyarmor pack main.py
using latest pyarmor version and convert to exe it flips off the antivirus. Never seen before today and antivirus keeps removing pytransform.pyd because its detected as a virus

**Comment by jondy** [comment]
duplicated of #976
