### ISSUE TITLE
A way to detect whether we are in obfuscate mode

### ISSUE THREAD

**Issue by SinChee** [dashingsoft/pyarmor#1003]
** Problem Faced**
When a script is being obfuscated by pyarmor, certain library is unable to be used, for example scrapy. Throwing the user with an angry error of '''OSError('could not get source code')''' is not helpful and make it hard for error handling.

** Suggested Fix **
1. During obfuscation, can we raise a warning message which function or library might be of error after obfuscation
2. Provide the user with a better error message such as "which library might cause the error"

** Code to replicate **
```python
import torch
import torch.nn as nn


# Define a simple model
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)
    
if __name__ == "__main__":
    simple_model = Model()
    try:
        traced_model = torch.jit.script(simple_model)
        output = traced_model(torch.ones(1))
        print(output)
        print("Exported to TorchScript in obfuscated script")
    except OSError as e:
        print(e)

```

Obfuscate
```
pyarmor obfuscate app.py
```

Run obfuscation
```
python dist/app.py
```

**Comment by jondy** [comment]
It's difficult to tell which library could not be used automatically after obfuscation.

There are countless libraries in Python world, I can't check each library by myself.

One solution is, list the unsupported libraries in the documentation, and append this list by users and Pyarmor Team.

**Comment by SinChee** [comment]
Great, we can create a list to record the list of libraries, such that in the future other users won't be confused by the error messages. Can you suggest a way to make this documentation easily accessible for developers? Preferably with a better way to represent the error, for example, torch.nn itself would not cause this error, but with torch.jit.script, this error occur. Blaming the entire error on torch alone is not fair for all developer.

**Comment by joonis** [comment]
To check if the script is obfuscated, you could do the following:

```
try:
    __pyarmor__
    frozen = True
except:
    frozen = False
```
