### ISSUE TITLE
[BUG] not machine id error with pyarmor 8.0.10

### ISSUE THREAD

**Issue by sergionuc** [dashingsoft/pyarmor#1005]
Hi pyarmor team,

I have run the 'gen' command and got the following error:

INFO     Python 3.9.5
INFO     Pyarmor 8.0.10 (pro), 005000, XXXX
INFO     search inputs ...
INFO     find package at src/XXXX
INFO     find 1 top resources
CRITICAL unknown error, please check pyarmor.error.log
ERROR    not machine id

I am using pyarmor.cli.core version 1.0.4.

I would appreciate any help you can give me. Thx!!

**Comment by jondy** [comment]
Try to register pyarmor with `.zip` again.

**Comment by sergionuc** [comment]
@jondy It is now working with the new version (Pyarmor 8.0.12), thank you so much!

I would like to ask you about the target platform. I have run this command (pyarmor gen --platform windows.x86_64 --platform darwin.x86_64 -O XXXX-r -i src/XXXX ) but I got: target platforms {'linux.x86_64'} without errors and warnings. Consequently, only the pyarmor_runtime.so is generated in the output folder. So, how can I specify other platforms with the gen command? 

I would appreciate any help you can give me. Thx!

**Comment by jondy** [comment]
Yes. `--platform` could be used in `gen` command, but now it may not work. It would work in next minor version `8.1`, and I'd like to do some tests before publish `v8.1`
