### ISSUE TITLE
"charmap" codec can't decode byte 0x81 in position 308

### ISSUE THREAD

**Issue by mridah** [dashingsoft/pyarmor#101]
I tried running PyArmor with python 2.7 and I get this error:

> "charmap" codec can't decode byte 0x81 in position 308

I'm running the following command : 

`pyarmor obfuscate --output "directory-path" "py-file-path"`

How can I resolve this error ??

Is there a version that works with python3 ?

**Comment by mridah** [comment]
The line has to be added in the beginning of my script ?

**Comment by jondy** [comment]
Yes. One exception to the first line rule is when the source code starts with a UNIX “shebang” line. In this case, the encoding declaration should be added as the second line of the file. For example:
```
#!/usr/bin/env python
# -*- coding: cp1252 -*-
```

In the windows, the `pyarmor.py` could be found in the `site-package` of python library path. It maybe in the path like `c:\Python27\Lib\site-packages\pyarmor`.

**Comment by mridah** [comment]
Now I'm getting the following error:

**Comment by jondy** [comment]
Where is the error message? I can see nothing.

**Comment by mridah** [comment]
Sorry my bad...didn't know email messages don't support markdown. This is the error I'm getting :

![image](https://user-images.githubusercontent.com/21169606/61545084-43a74d00-aa64-11e9-96dd-6eab49526fd9.png)

**Comment by jondy** [comment]
Maybe weakref.py is only for Python3, check the line 50.

**Comment by mridah** [comment]
Maybe, but it's even giving me some error when I run it using python 3:

![image](https://user-images.githubusercontent.com/21169606/61546002-4e62e180-aa66-11e9-8bc7-b1117519c51d.png)

**Comment by jondy** [comment]
Please add the right source encoding line at the first begin of the script if it reports codec error.

If you don't know the exact encoding of source, one way is first to convert it to utf-8 without BOM, then add one line `# -*- coding: utf-8 -*-`
