### ISSUE TITLE
[BUG] query machine id failed when register license 

### ISSUE THREAD

**Issue by kr1tx** [dashingsoft/pyarmor#1010]
I get this error after trying to register with `pyarmor reg regfile.zip` any help?

```
INFO     Python 3.11.2
INFO     Pyarmor 8.0.16 (trial), 000000, non-profits
INFO     register "regfile.zip"
INFO     update license token
CRITICAL unknown error, please check pyarmor.error.log
ERROR    query machine id failed
```

**Comment by jondy** [comment]
What's the output of `pyarmor-7 hdinfo`?

**Comment by JohnChedder** [comment]
Hi,
![image](https://user-images.githubusercontent.com/111640405/227759009-92f17e52-2fd1-4a84-889d-77ca6d34c801.png)

**Comment by jondy** [comment]
Fixed in 8.0.17

**Comment by JohnChedder** [comment]
> Fixed in 8.0.17
![image](https://user-images.githubusercontent.com/111640405/227789901-fae3a45c-79b7-479b-b85c-b41e15f91deb.png)
![image](https://user-images.githubusercontent.com/111640405/227789910-bff33b7a-ea6b-4e8b-aeb1-13bcff995425.png)

**Comment by jondy** [comment]
@kr1tx `pyarmor-7` doesn't work in Python 3.11, it's not the problem.

How about `query machine id failed` issue? Is it fixed by 8.0.7?

**Comment by jondy** [comment]
@JohnChedder If you have upgraded license successfully, do  not upgrade it again.

It's better to copy the full console text here, not partly and by snapshot.

**Comment by kr1tx** [comment]
Sadly no sir. @jondy 

```
INFO     Python 3.11.2
INFO     Pyarmor 8.0.17 (trial), 000000, non-profits
INFO     register "regfile.zip"
INFO     update license token
CRITICAL unknown error, please check pyarmor.error.log
ERROR    query machine id failed
```

**Comment by jondy** [comment]
@kr1tx What platform do you use? Pyarmor need query netcard Mac add or hard disk serial number, but it could not get

**Comment by kr1tx** [comment]
Im using Windows 11

**Comment by kr1tx** [comment]
I  have unplugged my ethernet cable and used wifi instead and it worked!

**Comment by kr1tx** [comment]
Could you please tell me how to do the exact same thing with PyArmor 8?
`pyarmor pack --with-license licenses\new\license.lic -x " --advanced 5 --plugin check_ntp_time" -e " --onefile --icon img.ico" Script.py`

**Comment by jondy** [comment]
Refer to #974
It's not interesting in answering same questions many times.

**Comment by kr1tx** [comment]
Could you send me the commands?

**Comment by JohnChedder** [comment]
> @JohnChedder If you have upgraded license successfully, do not upgrade it again.
> 
> It's better to copy the full console text here, not partly and by snapshot.

Hi, I couldn't update my license, I have a trial.
And about the text - I sent only the useful text, the rest of the text as before.

![image](https://user-images.githubusercontent.com/111640405/228028517-d8f76cc3-7109-45c1-940d-ab10b9ece1c8.png)

**Comment by b3n3w** [comment]
Getting the same error when running inside a OCI container. Mac address can be retrieved but not the harddisk information.

```
INFO     Create pyarmor home path: /home/****/.pyarmor
INFO     Create trial license file: /home/****/.pyarmor/license.lic
INFO     Generating public capsule ...
INFO     PyArmor Trial Version 8.0.26
INFO     Python 3.9.14
Hardware informations got by PyArmor:

Failed to get harddisk information.

Default Mac address: "6e:60:**********"

Multiple Mac addresses: "<6e:60:***********>"

Ip address: "10.0.2.100"

Domain name: "(none)"

Change logs

        v6.2.0(r21): Remove trailing dot from harddisk serial number
        v6.4.2(r34): Support binding multiple mac addresses
        v6.5.3(r37): Support binding named harddisk
        v6.7.5(r45): Support mmc/sd card in Linux
```
