### ISSUE TITLE
[Question]Encrypted file --advanced >= 2 Error

### ISSUE THREAD

**Issue by 130347665** [dashingsoft/pyarmor#1014]
I have purchased an encryption license and used the register script.

But when I use the encryption mode --advanced >= 2, it always prompts me with an error
pyarmor obfuscate --advanced 2 foo.py

python 3.8.13 32bit
INFO PyArmor Version 7.7.4
INFO Python 3.8.13
INFO Target platforms: Native
INFO Getting remote file: https://pyarmor.dashingsoft.com/files/r52.6/index.json
ERROR HTTP Error 401: Unauthorized

![image](https://user-images.githubusercontent.com/42213937/227825968-35ff4d51-09c2-45dd-8d47-1fee96be730e.png)

foo.py
print("hello")

**Comment by jondy** [comment]
If you purchase new license, please use Pyarmor 8.0+

Refer to #980

**Comment by 130347665** [comment]
I can't upgrade my pyarmor to 8.0 why?
pip install --upgrade pyarmor
pip install --upgrade pyarmor
Requirements already met: pyarmor is in e:\anaconda3\envs\py32\lib/site-packages (7.6.1).
Collecting pyarmor
  Using cached pyarmor-8.0.17-py2.py3-none-any.whl (2.3 MB)
  Using cached pyarmor-8.0.16-py2.py3-none-any.whl (2.3 MB)
  pyarmor-8.0.15-py2.py3-none-any.whl using cache (2.3 MB)
  pyarmor-8.0.12-py2.py3-none-any.whl using cache (2.3 MB)
  pyarmor-8.0.11-py2.py3-none-any.whl using cache (2.3 MB)
  pyarmor-8.0.10-py2.py3-none-any.whl using cache (2.3 MB)
  pyarmor-8.0.9-py2.py3-none-any.whl using cache (2.3 MB)
  pyarmor-8.0.8-py2.py3-none-any.whl using cache (208 kB)
  pyarmor-8.0.7-py2.py3-none-any.whl using cache (212 kB)
  Using cached pyarmor-8.0.6-py2.py3-none-any.whl (211 kB)
  Using cached pyarmor-8.0.5-py2.py3-none-any.whl (211 kB)
  pyarmor-8.0.4-py2.py3-none-any.whl (211 kB) using cached pyarmor-8.0.4-py2.py3-none-any.whl (211 kB)
  Using cached pyarmor-8.0.3-py2.py3-none-any.whl (211 kB)
  Using cached pyarmor-8.0.2-py2.py3-none-any.whl (211 kB)
  Using cached pyarmor-8.0.1-py2.py3-none-any.whl (207 kB)
  Using cached pyarmor-8.0.post1-py2.py3-none-any.whl (207 kB)
  Using cached pyarmor-8.0-py2.py3-none-any.whl (207 kB)
  pyarmor-7.7.4-py2.py3-none-any.whl using cache (2.3 MB)
Installed collected packages: pyarmor
  Trying to uninstall: pyarmor
    Found existing installation: pyarmor 7.6.1
    Uninstalled pyarmor-7.6.1:
      Successfully uninstalled pyarmor-7.6.1
Successfully installed pyarmor-7.7.4
Always update with 7.7.4

**Comment by 130347665** [comment]
pyarmor obfuscate --advanced 2 foo.py

INFO     PyArmor Version 7.7.4
INFO     Python 3.8.13
INFO     Target platforms: Native
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r52.6/index.json
ERROR    HTTP Error 401: Unauthorized

**Comment by 130347665** [comment]
I tried to install pyarmor in the specified version but he told me ERROR: Invalid requirement: 'pyarmor.cli.core=1.0'
pip install pyarmor==8.0.0
Collecting pyarmor==8.0.0
  Using cached pyarmor-8.0-py2.py3-none-any.whl (207 kB)
ERROR: Could not find a version that satisfies the requirement pyarmor.cli.core~=1.0 (from pyarmor) (from versions: none)
ERROR: No matching distribution found for pyarmor.cli.core~=1.0
pip install pyarmor.cli.core=1.0  
ERROR: Invalid requirement: 'pyarmor.cli.core=1.0'
Hint: = is not a valid operator. Did you mean == ?


---------isntall pyarmor.cli.core=1.0 error---------------
ip install pyarmor.cli.core=1.0  
ERROR: Invalid requirement: 'pyarmor.cli.core=1.0'
Hint: = is not a valid operator. Did you mean == ?

**Comment by 130347665** [comment]
pip install pyarmor.cli.core==1.0    ERROR: Could not find a version that satisfies the requirement pyarmor.cli.core==1.0 (from versions: none)
ERROR: No matching distribution found for pyarmor.cli.core==1.0

**Comment by 130347665** [comment]
pip install pyarmor.cli.core==1.0    
```
ERROR: Could not find a version that satisfies the requirement pyarmor.cli.core==1.0 (from versions: none)
ERROR: No matching distribution found for pyarmor.cli.core==1.0
```

**Comment by 130347665** [comment]
https://pypi.org/project/pyarmor.cli.core/#files

I went here to download manually
pyarmor.cli.core installation package
But I don't see any package built for x86 python. Is python x86 not supported?

pip install pyarmor.cli.core-1.0.7-cp38-none-win_amd64.whl
`ERROR: pyarmor.cli.core-1.0.7-cp38-none-win_amd64.whl is not a supported wheel on this platform.`

**Comment by 130347665** [comment]
Ok, I saw that, I don't know the hold at the moment, but for my current job, I can't upgrade to x64, can I still use this license and use pyarmor7 encryption?
