### ISSUE TITLE
How should we register pyarmor in a different machine ?

### ISSUE THREAD

**Issue by rvadhith** [dashingsoft/pyarmor#1017]
I have used python version 3.8.10 in ubuntu 20.04 to register in the first machine. The pyarmor version used was 7.7.0

After registration I had the following files in ~/.pyarmor directory

1. license.lic
2. .pyarmor_capsule.zip

I tried to register in an azure cloud VM running Ubuntu 20.04 server generation 1. The python version used is 3.8.10 and the pyarmor version is 7.7.0. 

I placed the 2 above mentioned files in a directory by the name 'pyarmor_registration' in home folder and ran the following command:

pyarmor register .pyarmor_capsule.zip

I got the following error message 

INFO     PyArmor Trial Version 7.7.0
INFO     Python 3.8.10
INFO     Start to register keyfile: .pyarmor_capsule.zip
INFO     Save registration data to: /home/azureuser/.pyarmor
INFO     Extracting license.lic
ERROR    There is no item named 'license.lic' in the archive

Please help us register pyarmor in a different machine

**Comment by jondy** [comment]
Please check the activation file `pyarmor_regcode_xxxxx.txt`, also refer to #980
