### ISSUE TITLE
[BUG] RuntimeError: product name has been set to "Pyarmor"

### ISSUE THREAD

**Issue by yahav6893** [dashingsoft/pyarmor#1023]
I've seen similar issues regarding this subject but none helps to solve my case.

when trying to register my new license I'm getting this error:

![image](https://user-images.githubusercontent.com/50764241/227902775-4e4ecc01-1965-487e-8e23-03ff14b7d29a.png)

error log:
![image](https://user-images.githubusercontent.com/50764241/227903606-c51484af-12c8-4afe-b9fd-89b647397d31.png)

checking version afterward return this:
![image](https://user-images.githubusercontent.com/50764241/227903200-ff867b3c-132a-4510-b137-b5525d332676.png)

and of course, no .zip file is created.

I'm running on ubuntu 18.04.

Please help or refer me to a solution.

Thanks!

**Comment by jondy** [comment]
I think you purchased old license. All the new license no is greater than 4000
