### ISSUE TITLE
unknown license type OLD

### ISSUE THREAD

**Issue by Withoutbytes** [dashingsoft/pyarmor#1029]
I recently purchased a license key for Pyarmor, but I am unable to activate it. When I run the command "pyarmor reg" with my registration code, I receive the following error message:

```
CRITICAL unknown error, please check pyarmor.error.log
ERROR    unknown license type OLD
```

I have checked that I am using the latest version of Pyarmor and that my license is still valid. I have also verified that I have correctly entered my registration code. However, I am still unable to activate my license.

Steps to reproduce:

    Purchase a license key for Pyarmor.
    Run the command "pyarmor reg" with the registration code.
    Observe the error message.

Expected result:
The license key should be successfully activated.

Actual result:
The error message "CRITICAL unknown error, please check pyarmor.error.log ERROR unknown license type OLD" is displayed, and the license key is not activated.

Additional information:

    Pyarmor version: 8.0.6 (trial)
    Python version: 3.9.0

I would appreciate any assistance in resolving this issue.

**Comment by jondy** [comment]
You purchase old license for Pyarmor 7.x, here are the latest licenses
http://pyarmor.readthedocs.io/en/stable/licenses.html

Please first read this #980

If you prefer to use Pyarmor 7.x, please use `pyarmor-7` or downgrade pyarmor to 7.7.4
If you prefer to use Pyarmor 8.x, please refund this order if it's still not activated:
1. Email to Ordersupport@mycommerce.com with order information and ask for
     refund.
2. Or click [FindMyOrder page](https://www.findmyorder.com/store?Action=DisplayEmailCustomerServicePage&Env=BASE&Locale=en_US&SiteID=findmyor
) to submit refund request
