### ISSUE TITLE
pyarmor on centos 6.8 and it requires GLIBC_2.14

### ISSUE THREAD

**Issue by frostofmourne** [dashingsoft/pyarmor#103]
Hi guys hello,

I am trying to run my application obfuscated by pyarmor. The python wheel package was built on my ubuntu 18.04 LTS while the target running platform is a centos 6.8 virtual machine.

At first, right on start, it outputs below error:
[2019-08-01 17:53:08 +0800] [43103] [INFO] Worker exiting (pid: 43103)
[2019-08-01 17:53:08 +0800] [43104] [INFO] Booting worker with pid: 43104
Load /opt/test_env/lib/python3.6/site-packages/test_app/_pytransform.so failed:
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/test_env/lib/python3.6/site-packages/test_app/_pytransform.so)

Then according to the error, I manually downloaded glibc-2.14, built it locally and linked it by /lib64/libc.so.6, then when i tried to start it again, below errors showed up:
......
......
File "<frozen superset>", line 50, in <module>
  File "/opt/Python-3.6.8/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/opt/test_env/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 23166: ordinal not in range(128)
[2019-08-01 09:05:02 +0000] [43024] [INFO] Worker exiting (pid: 43024)
[2019-08-01 09:05:02 +0000] [43021] [INFO] Shutting down: Master
[2019-08-01 09:05:02 +0000] [43021] [INFO] Reason: Worker failed to boot.

P.S. I tried and made sure that even without the obfuscation by pyarmor, as long as glibc-2.14 is being pointed and linked, under my centos 6.8 vm the application wouldnt start and it would throw the same error as above.

So my question is, is there a way i can build or get access to a _pytransform.so that can work with GLIBC_2.12 rather than GLIBC_2.14?

So many thanks and sorry for the troubles,

leonL

**Comment by jondy** [comment]
One solution is to mark GLIBC_2.14 as VER_WEAK_FLAG in the `_pytransform.so`.
1. First find `_pytransform.so` in ubuntu 18.04, generally it's in the `/usr/local/lib/python3.6/dist-packages/pyarmor/platforms/linux64/_pytransform.so`
2. Get the location of version flag of GLIBC_2.14
```
$ readelf -V _pytransform.so
...
  1cc:   1 (*global*)

Version needs section '.gnu.version_r' contains 2 entries:
 Addr: 0x00000000000056e8  Offset: 0x0056e8  Link: 4 (.dynstr)
  000000: Version: 1  File: libdl.so.2  Cnt: 1
  0x0010:   Name: GLIBC_2.2.5  Flags: none  Version: 7
  0x0020: Version: 1  File: libc.so.6  Cnt: 6
  0x0030:   Name: GLIBC_2.7  Flags: none  Version: 8
  0x0040:   Name: GLIBC_2.14  Flags: none Version: 6
  0x0050:   Name: GLIBC_2.4  Flags: none  Version: 5
  0x0060:   Name: GLIBC_2.3.4  Flags: none  Version: 4
  0x0070:   Name: GLIBC_2.2.5  Flags: none  Version: 3
  0x0080:   Name: GLIBC_2.3  Flags: none  Version: 2
```
Here it is 0x0056e8 + 0x40 + 4 (offset in structure) = 0x572c

3. Edit `_pytransform.so` by any hex-editor, change the byte at 0x572c to `02`
4. Check the flag is marked as WEAK
```
$ readelf -V _pytransform.so
```

Then obfuscate the scripts again

**Comment by frostofmourne** [comment]
> One solution is to mark GLIBC_2.14 as VER_FLAG_WEAK in the `_pytransform.so`.
> 
> 1. First find `_pytransform.so` in ubuntu 18.04, generally it's in the `/usr/local/lib/python3.6/dist-packages/pyarmor/platforms/linux64/_pytransform.so`
> 2. Get the location of version flag of GLIBC_2.14
> 
> ```
> $ readelf -V _pytransform.so
> ...
>   1cc:   1 (*global*)
> 
> Version needs section '.gnu.version_r' contains 2 entries:
>  Addr: 0x00000000000056e8  Offset: 0x0056e8  Link: 4 (.dynstr)
>   000000: Version: 1  File: libdl.so.2  Cnt: 1
>   0x0010:   Name: GLIBC_2.2.5  Flags: none  Version: 7
>   0x0020: Version: 1  File: libc.so.6  Cnt: 6
>   0x0030:   Name: GLIBC_2.7  Flags: none  Version: 8
>   0x0040:   Name: GLIBC_2.14  Flags: none Version: 6
>   0x0050:   Name: GLIBC_2.4  Flags: none  Version: 5
>   0x0060:   Name: GLIBC_2.3.4  Flags: none  Version: 4
>   0x0070:   Name: GLIBC_2.2.5  Flags: none  Version: 3
>   0x0080:   Name: GLIBC_2.3  Flags: none  Version: 2
> ```
> 
> Here it is 0x0056e8 + 0x40 + 4 (offset in structure) = 0x572c
> 
> 1. Edit `_pytransform.so` by any hex-editor, change the byte at 0x572c to `02`
> 2. Check the flag is marked as WEAK
> 
> ```
> $ readelf -V _pytransform.so
> ```
> 
> Then obfuscate the scripts again

Hey man thanks a lot for the reply!

I tried the steps and now the new error is:

[2019-08-02 13:05:19 +0800] [45342] [INFO] Booting worker with pid: 45342
[2019-08-02 13:05:19 +0800] [45342] [INFO] Worker exiting (pid: 45342)
Load /opt/test_env/lib/python3.6/site-packages/test_app/_pytransform.so failed:
/opt/test_env/lib/python3.6/site-packages/test_app/_pytransform.so: symbol memcpy, version GLIBC_2.14 not defined in file libc.so.6 with link time reference

From the look of it i supposed there isnt too much i can do about running it on 6.8 for now is it?

BTW i tried 7.4 7.5 7.6 all of them are working fine.

So many thanks again,

leonL

**Comment by jondy** [comment]
>I tried the steps and now the new error is:
>[2019-08-02 13:05:19 +0800] [45342] [INFO] Booting worker with pid: 45342
>[2019-08-02 13:05:19 +0800] [45342] [INFO] Worker exiting (pid: 45342)
>Load /opt/test_env/lib/python3.6/site-packages/test_app/_pytransform.so failed:
>/opt/test_env/lib/python3.6/site-packages/test_app/_pytransform.so: symbol memcpy, version GLIBC_2.14 not defined in file libc.so.6 with link time reference
>From the look of it i supposed there isnt too much i can do about running it on 6.8 for now is it?
>BTW i tried 7.4 7.5 7.6 all of them are working fine.
>So many thanks again,

It seems it's not enough to change the flag only.

Try to change GLIBC_2.14 to GLIBC_2.7 in the `_pytransform.so`, there is also the patched one you could download it directly
https://pyarmor.dashingsoft.com/downloads/platforms/linux_x86_64/temp/_pytransform.so

Or patch it by yourself

First check version table
```
$ readelf -V _pytransform.so

...

Version needs section '.gnu.version_r' contains 2 entries:
 Addr: 0x00000000000056e8  Offset: 0x0056e8  Link: 4 (.dynstr)
  000000: Version: 1  File: libdl.so.2  Cnt: 1
  0x0010:   Name: GLIBC_2.2.5  Flags: none  Version: 7
  0x0020: Version: 1  File: libc.so.6  Cnt: 6
  0x0030:   Name: GLIBC_2.7  Flags: none  Version: 8
  0x0040:   Name: GLIBC_2.14  Flags: none Version: 6
  0x0050:   Name: GLIBC_2.4  Flags: none  Version: 5
  0x0060:   Name: GLIBC_2.3.4  Flags: none  Version: 4
  0x0070:   Name: GLIBC_2.2.5  Flags: none  Version: 3
  0x0080:   Name: GLIBC_2.3  Flags: none  Version: 2

```

Then copy some data from GLIBC_2.7, which offset is 0x56e8 + 0x30 = 0x5718:
* Copy 4 bytes at 0x5718 to 0x5728
* Copy 4 bytes at 0x5720 to 0x5730

After that
```
$ readelf -V _pytransform.so

...

Version needs section '.gnu.version_r' contains 2 entries:
 Addr: 0x00000000000056e8  Offset: 0x0056e8  Link: 4 (.dynstr)
  000000: Version: 1  File: libdl.so.2  Cnt: 1
  0x0010:   Name: GLIBC_2.2.5  Flags: none  Version: 7
  0x0020: Version: 1  File: libc.so.6  Cnt: 6
  0x0030:   Name: GLIBC_2.7  Flags: none  Version: 8
  0x0040:   Name: GLIBC_2.7  Flags: none  Version: 6
  0x0050:   Name: GLIBC_2.4  Flags: none  Version: 5
  0x0060:   Name: GLIBC_2.3.4  Flags: none  Version: 4
  0x0070:   Name: GLIBC_2.2.5  Flags: none  Version: 3
  0x0080:   Name: GLIBC_2.3  Flags: none  Version: 2
```

And check `memcpy` which is referenced from GLIBC_2.14 only

```
$ objdump -T _pytransform.so | grep memcpy

0000000000000000      DF *UND*  0000000000000000  GLIBC_2.3.4 __memcpy_chk
0000000000000000      DF *UND*  0000000000000000  GLIBC_2.7   memcpy

```
Hope it works

**Comment by jondy** [comment]
Maybe GLIBC_2.7  should be replaced by GLIBC_2.2.5, it seems there is no `memcpy` defined in the GLIBC_2.7.  
I have updated the patched one,
https://pyarmor.dashingsoft.com/downloads/platforms/linux_x86_64/temp/_pytransform.so
md5sum: 7627705a8037e3a02d203a3f89db978b

**Comment by frostofmourne** [comment]
> Maybe GLIBC_2.7 should be replaced by GLIBC_2.2.5, it seems there is no `memcpy` defined in the GLIBC_2.7.
> I have updated the patched one,
> https://pyarmor.dashingsoft.com/downloads/platforms/linux_x86_64/temp/_pytransform.so
> md5sum: 7627705a8037e3a02d203a3f89db978b

Hey Jondy,


Thanks so much for the quick reply and the solution!

The patch works just fine!


-leonL
