### ISSUE TITLE
SystemError: unknown opcode with --advanced

### ISSUE THREAD

**Issue by RobinFrcd** [dashingsoft/pyarmor#104]
Hi,
I'm trying to use `--advanced` flag to hide some information inside the __code__ attribute.

But when running the script I get: `SystemError: unknown opcode`.

When I run `python -d my_script.py` I get:
```
Debug mode enabled and log to 'pytransform.log'
Warning: patch interpreter failed (1431)
Pytransform Error: The script is obfuscated in advanced mode but the runtime library doesn't support when running
```

I'm on MacOS, Mojave 10.14.6

**Comment by jondy** [comment]
Fix it in v5.5.4
