### ISSUE TITLE
Issues with Pyarmor 8 commands

### ISSUE THREAD

**Issue by ahmedashraf443** [dashingsoft/pyarmor#1048]
ok so i'm having a couple of issues while trying to use pyarmor on my script

the script is basically a gui app and contains for loops and if statements and the usual imports

issue no. 1) when i try to bind the script to my device hard disk serial number, i use this cmd command to get the serial number
wmic diskdrive get model,serialnumber

and when i try to bind using this command  pyarmor gen -b 71KOTFWLT foo.py
I get
ERROR    ('invalid device info "%s"', '71KOTFWLT')

when i get the hard disk serial number and try the command pyarmor gen -b 947564512 foo.py
i get the same error 
ERROR    ('invalid device info "%s"', '947564512')

when i bind it to my mac adress or ip adress it does the binding but then when i try to run the same script on my machine i get that the license is not valid for this machine (i've made sure i am using the correct mac adress or ip adress)

issue number 2) when i try to use rft mode using this command pyarmor gen --enable-rft foo.py
I get this error ERROR    sequence item 1: expected str instance, Attribute found

issue number 3) when i try to use bcc mode using this command line pyarmor gen --enable-bcc foo.py   
i get this error ERROR    c compiler "clang.exe" return error: [WinError 2] The system cannot find the file specified

if i use this command pyarmor gen --enable-jit --mix-str --assert-call foo.py 

it generates the script without errors but when i try to run the script 
it gives me this error 
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen foo>", line 696, in
RuntimeError: protection exception (16777763)

i've tried referring to the documentation but it is very brief and not very clear 

i am using Pyarmor 8.0.22 (pro)

I would really appreciate any help i can get

**Comment by jondy** [comment]
Please use `pyarmor-7 hdinfo` to get hardware information.

Pyarmor 8.0 is new released and there are still issues, and it's quick bug fixed now.

**Comment by jondy** [comment]
If you're urgent, I suggest using `pyarmor-7`, and Pyarmor 7.x documentation, it's stable. 

Please also check project [README.md](http://github.com/dashingsoft/pyarmor/)

**Comment by ahmedashraf443** [comment]
which version of pyarmor-7 do you recommend?

**Comment by jondy** [comment]
In the latest 8.0.x.

**Comment by ddi98** [comment]
I just upgraded but I keep getting the following error:
ERROR c compiler "clang.exe" return error: [WinError 2] The specified file could not be found
