### ISSUE TITLE
Library not loaded: '@rpath/Frameworks/Python.framework/Versions/3.10/Python

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#1058]
Hello, there`s a bug when i try register from zip file.

**Traceback**

> 
> INFO     Python 3.10.5
> INFO     Pyarmor 8.0.26 (trial), 000000, non-profits
> INFO     register "/Users/paulo/desktop/pyarmor-regfile-2324.zip"
> INFO     update license token
> CRITICAL unknown error, please check pyarmor.error.log
> ERROR    dlopen(/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/pytransform3.so, 0x0002): Library not loaded: '@rpath/Frameworks/Python.framework/Versions/3.10/Python'
>   Referenced from: '/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/pytransform3.so'
>   Reason: tried: '/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/../Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/../Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Users/paulo/.pyenv/versions/3.10.5/lib/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Users/paulo/.pyenv/versions/3.10.5/lib/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Users/paulo/.pyenv/versions/3.10.5/lib/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Users/paulo/.pyenv/versions/3.10.5/lib/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file)

**pyarmor.error.log:**

> 
> 15421 MainProcess 2023-03-31 12:34:02,423
> Traceback (most recent call last):
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 629, in main
>     main_entry(sys.argv[1:])
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 617, in main_entry
>     args.func(ctx, args)
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 224, in cmd_reg
>     reg.register_regfile(regfile)
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/register.py", line 156, in register_regfile
>     self.update_token()
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/register.py", line 113, in update_token
>     Pytransform3._update_token(self.ctx)
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/__init__.py", line 72, in _update_token
>     m = Pytransform3.init(ctx)
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/__init__.py", line 39, in init
>     from . import pytransform3 as m
> ImportError: dlopen(/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/pytransform3.so, 0x0002): Library not loaded: '@rpath/Frameworks/Python.framework/Versions/3.10/Python'
>   Referenced from: '/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/pytransform3.so'
>   Reason: tried: '/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/../Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/../Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Users/paulo/.pyenv/versions/3.10.5/lib/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Users/paulo/.pyenv/versions/3.10.5/lib/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Users/paulo/.pyenv/versions/3.10.5/lib/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Users/paulo/.pyenv/versions/3.10.5/lib/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file)

Regards

**Comment by jondy** [comment]
You could search `install_name_tool` in issues to find the solution.

**Comment by pauloswear** [comment]
Ok, I understood that is happening because of paths, so I tried:

> ➜  ~ python3.10-config --ldflags 
> -lintl -ldl -framework CoreFoundation

...

> import sys
> sys.executable
> '/Users/paulo/.pyenv/versions/3.10.5/bin/python'

Assuming that python is installed at /Users/paulo/.pyenv/versions/3.10.5/bin/python', the command should solve, but it not solved.

> install_name_tool -add_rpath /Users/paulo/.pyenv/versions/3.10.5/bin/python pytransform.cpython-310m-darwin.so

Output:

> error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't open file: pytransform.cpython-310m-darwin.so (No such file or directory)

How can I find correct path of pytransform ?

**Comment by jondy** [comment]
Try this
```shell
install_name_tool -add_rpath @executable_path/.. /Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/pytransform3.so
```

**Comment by pauloswear** [comment]
still got error even running this cli

> install_name_tool -add_rpath @executable_path/.. /Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/pytransform3.so

> CRITICAL unknown error, please check pyarmor.error.log
> ERROR    dlopen(/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/pytransform3.so, 0x0002): Library not loaded: '@rpath/Frameworks/Python.framework/Versions/3.10/Python'
>   Referenced from: '/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/core/pytransform3.so'
