### ISSUE TITLE
Obfuscation not working when packed with pyinstaller

### ISSUE THREAD

**Issue by ruky87** [dashingsoft/pyarmor#106]
I have a python script that imports other scripts. I want to obfuscate all the code and pack it to an exe (onefile) to distribute. My clients mus te unable to crack or decompile the source code.
I run the command "pyarmor pack myscript.py"
then I used a pyinstaller extractor script (https://sourceforge.net/projects/pyinstallerextractor/), it extracted also the dependencies (pyc) files (PYZ-00.pyz). If I open these files with an hex editor (like PSpad or other advanced text editors) I can read the source of my code. Every function, every comment. 
So, it's clear that something went wrong: or pyarmor obsuscation can be forced easily or the packed scripts are not the obfuscated ones. I have Pyinstaller 3.4.
I tried also the manual procedure described here https://pyarmor.readthedocs.io/en/latest/pack-obfuscated-scripts.html, same results...

**Comment by jondy** [comment]
First to be sure the version of pyarmor is v5.5.2 or later, if not, upgrade to the latest version.
Second,  where are the other scripts? Do they locate in the sub-path of `myscript.py`? `pyarmor pack` command should automatically obfuscate the scripts in the sub-path of main script recursively.
Finally, try the option `--clean` to remove the cache files:
`pyarmor --clean pack myscript.py`

**Comment by ruky87** [comment]
I run "pip install pyarmor" but it says the version is updated. It is only 5.4.6, do I have to install it manually from github?

I have all the script in a folder:
ProjectFolder/myscript.py
ProjectFolder/import1.py
ProjectFolder/import2.py
I deleted the obf folder and the build folder, only the py files are in the folder. Then I execute the command. If I then exctract the generated executable I can decompile everything. 
I also tried with manual procedure:
- First with pyarmor obfuscate .... (The obfuscated files are generated correctly)
- Then pyintaller and spec file modification. I also inserted some print() to debug the "a" object, all the paths are correct and point to obf folder
- The generate executable still has pyc that I can decompile: import1.pyc for example contains all the source of import1.py without obfuscation

It's like it uses the compiled version of source modules instead of the modules in obf folder, independently of the paths of the "a.pure" in the spec file (that are correct, it seems)

**Comment by jondy** [comment]
This issue has been fixed in the v5.5.2,, and the latest version is v5.5.4. Try this command "pip install --upgrade pyarmor", or download the package from
https://files.pythonhosted.org/packages/85/79/87e2c0e4774337043ee5652f67fd8f5e287aabbea7ba750fc3724fb60737/pyarmor-5.5.4-py2.py3-none-any.whl
then `pip install pyarmor-5.5.4-py2.py3-none-any.whl`

**Comment by jondy** [comment]
When you tried with manual procedure, how about inserting `print` like this
```
            if hasattr(a.pure, '_code_cache'):
                print("%s has been replaced" % x)
                with open(x) as f:
                    a.pure._code_cache[a.pure[i][0]] = compile(f.read(), a.pure[i][1], 'exec')
```
Is the script name iprinted? 

If not, run `pyinstaller` with option `--clean`, to be sure the script name is printed.
```
pyinstaller --clean -y hello.spec
```
It should pack the obfuscated scripts either.

**Comment by ruky87** [comment]
Thank you, now is working!
However could you please change the user guide here https://pyarmor.readthedocs.io/en/latest/pack-obfuscated-scripts.html

The patching code must be changed to:

a.scripts[-1] = 'MyFile', r'dist\obf\MyFile.py', 'PYSOURCE'
for i in range(len(a.pure)):
    if a.pure[i][1].startswith(a.pathex[0]):
        x = a.pure[i][1].replace(a.pathex[0], r'Absolute\path\to\ProjectFolder\dist\obf')
        if os.path.exists(x):
            if hasattr(a.pure, '_code_cache'):
                with open(x) as f:
                    a.pure._code_cache[a.pure[i][0]] = compile(f.read(), a.pure[i][1], 'exec')
            a.pure[i] = a.pure[i][0], x, a.pure[i][2]

**Comment by ruky87** [comment]
The problem was that I did't have this part with the old version

```python
with open(x) as f:
                    a.pure._code_cache[a.pure[i][0]] = compile(f.read(), a.pure[i][1], 'exec')
```

**Comment by jondy** [comment]
I have refined the document but just changed this line
```
        x = a.pure[i][1].replace(a.pathex[0], os.path.normpath(os.path.abspath('dist/obf')))
```
It should fix path separator issue.
