### ISSUE TITLE
[BUG] ERROR ('pyarmor', 'buyurl')

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#1066]
I decide open a different topic for this error. When I try upgrade license (basic to pro) running the command, it fails

> pyarmor reg --buy
> INFO     Python 3.10.5
> INFO     Pyarmor 8.0.26 (basic), ****vax, Paulo
> CRITICAL unknown error, please check pyarmor.error.log
> ERROR    ('pyarmor', 'buyurl')

The pyarmor.error.log is:

> 6148 MainProcess 2023-04-01 12:27:13,479
> Traceback (most recent call last):
>   File "C:\Users\Paulo\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 629, in main
>     main_entry(sys.argv[1:])
>   File "C:\Users\Paulo\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 617, in main_entry
>     args.func(ctx, args)
>   File "C:\Users\Paulo\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 192, in cmd_reg
>     open_new_tab(ctx.cfg['pyarmor', 'buyurl'])
>   File "C:\Users\Paulo\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 964, in __getitem__
>     raise KeyError(key)
> KeyError: ('pyarmor', 'buyurl')

I know of possibility upgrade using link, i am just reporting the bug.

**Comment by jondy** [comment]
Thanks, it has been fixed in dev version `8.1.dev1`.
