### ISSUE TITLE
请问支持docker 环境吗

### ISSUE THREAD

**Issue by xjune123** [dashingsoft/pyarmor#107]
查看了这个 Pyarmor on alpine image #53 并没看到相关内容。
我目前使用的基础镜像是python:3.6.9-slim-stretch ，我在linux和mac操作系统中启动docker 都无法启动，报License is not for this machine ，但直接运行python3  dist/helloworld.py 是可以运行起来的。不确定是不是docker 环境中会不会获取错误的IP。

或者说我必须使用Alpine Linux 这个版本的系统？

**Comment by jondy** [comment]
Docker 环境下获取的 IP 不是真实的物理机器的 IP，而是 docker 虚拟环境下面的 IP,  如果生成的 license.lic 是绑定到 IP 上的话，那需要获取 docker 里面的 IP, 可以使用工具 hdinfo 

https://github.com/dashingsoft/pyarmor-core#hdinfo

然后在 docker 里面运行，获取正确的硬件信息。

**Comment by xjune123** [comment]
我们这里是有个比较奇怪的需求，需要能绑定物理机器的IP。
docker 本次重启的IP都是变化的，如果不能获取到实际物理机器的IP，Pyarmor 应该就会校验不通过。
Pyarmor 只会校验容器内的IP 是么？

**Comment by jondy** [comment]
是的，PyArmor 默认是校验容器内 IP, 但是可以校验容器外的硬盘。如果必须要校验物理机器的IP就需要自己写扩展了，前提是 docker 内部可以获取到宿主机器的物理IP。

**Comment by xjune123** [comment]
另外是否建议如果是docker环境的话，绑定mac地址
