### ISSUE TITLE
[BUG] query machine id failed in docker container

### ISSUE THREAD

**Issue by noahmuney** [dashingsoft/pyarmor#1077]
After purchasing a license and doing initial registration with pyarmor-regcode-5044.txt file, I tried to register inside a docker container using the pyarmor-regfile-5004.zip and received the following error: query machine id failed.

When running pyarmor-7 hdinfo:
Hardware informations got by PyArmor:

Failed to get harddisk information.

Default Mac address: "6e:60:**********"

**Comment by jondy** [comment]
If docker is using Alpine with musl-c, it's not still supported.

**Comment by noahmuney** [comment]
> If docker is using Alpine with musl-c, it's not still supported.

Docker is using Ubuntu 22.04

**Comment by jondy** [comment]
Try it in pyarmor `8.1.dev4`, I fixed a machine id bug in Linux.

**Comment by noahmuney** [comment]
Seems to be working in 8.1.dev4
Thank you!
