### ISSUE TITLE
Lib not found libc.so.6 when building for aarch64/Android

### ISSUE THREAD

**Issue by KaryonixX** [dashingsoft/pyarmor#108]
Im trying to obfuscate scripts to run them on an Android Python (aarch64) and i always get this error: `Load /storage/emulated/0/4.3/_pytransform.so failed:
dlopen failed: library "libc.so.6" not found`

**Comment by jondy** [comment]
If the scripts aren't obfuscated in the aarch64 platform,  the platform should be specified. For example,
```
# Run download command once
pyarmor download --output aarch64 armv8.64-bit
pyarmor obfuscate --platform aarch64 foo.py
```

**Comment by Apeopex** [comment]
We are able to cross platform obfusicate (`pyarmor download armv8.64-bit && pyarmor build --platform armv8.64-bit`) and get a successful build. 

The same build for Windows/Linux works fine.

However while executing on a fairly recent Android phone (via pydroid) does the above error get produced.

**Comment by jondy** [comment]
I'm not sure, you can try it. Could you check the output "uname -a" in the target phone? It should show the arch information

**Comment by Apeopex** [comment]
![image](https://user-images.githubusercontent.com/3247540/63569264-878ee580-c52d-11e9-90b4-b6e2e27949dd.png)

**Comment by Apeopex** [comment]
It might be necessary to have specifics builds against the Android NDK for proper linking.

Is `pytransform` a CMake based build? The Android provided CMake toolchain makes rebuilds simple.

https://developer.android.com/ndk/guides/cmake#the_cmake_toolchain_file

**Comment by jondy** [comment]
Thanks, I'll build `pytransform` by Android NDK. It seems there is only static `libc.a` in the Android system.

**Comment by jondy** [comment]
Here it is, built by android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
https://github.com/dashingsoft/pyarmor-core/raw/master/platforms/android.aarch64/_pytransform.so
