### ISSUE TITLE
[BUG] Latest version of pyarmor causes 'ERROR    string argument without an encoding' on darwin x86_64

### ISSUE THREAD

**Issue by null-routed** [dashingsoft/pyarmor#1081]
Just updated my pyarmor to latest, getting the following error while trying to obfuscate even simple scripts.
```python
# foo.py
def fib(n):
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b

if __name__ == '__main__':
    fib(10)
```
`pyarmor gen foo.py`
pyarmor error log:

    return m.generate_runtime_package(ctx, output, platforms)
    File "maker", line 720, in generate_runtime_package
    File "maker", line 438, in build
    File "maker", line 302, in patch_extension
    TypeError: string argument without an encoding

Python version is 3.9.

**Comment by null-routed** [comment]
Just tested on Windows and it works fine. I believe the issue is just for darwin.

**Comment by jondy** [comment]
Try it in pyarmor 8.1.dev4, or update package `pyarmor.cli.core`
