### ISSUE TITLE
[BUG] inline class definition not working in linux.aarch64

### ISSUE THREAD

**Issue by hiddify1** [dashingsoft/pyarmor#1083]
If we have the following in the code, it will show the following exception:

`class DynamicForm(FlaskForm):pass`

CRITICAL unknown error, please check pyarmor.error.log
ERROR    'NoneType' object has no attribute 'offset'

but if we convert it to 

```
class DynamicForm(FlaskForm):
    pass
```

it will work.

In addition would you please the line number which has a problem in the log?

**Comment by jondy** [comment]
Which python version is used?

**Comment by jondy** [comment]
I also can't reproduce this issue by Python 3.8, 3.10, 3.11

**Comment by hiddify1** [comment]
i tested in ubuntu aarch64 python3.10

**Comment by jondy** [comment]
Got it, I'll check and fix aarch64 platform bug later.

**Comment by jondy** [comment]
Reproduced and will be fixed in next version.

**Comment by jondy** [comment]
Fixed it in `8.1.2`
