### ISSUE TITLE
Pyarmor requires internet when no expiry date set on license | Edit: Actually a multiprocessing issue

### ISSUE THREAD

**Issue by SIVLEOL** [dashingsoft/pyarmor#110]
Recently a customer told us that our Pyarmor protected software would not turn on without internet. I bound their license to only hard disk serial and MAC address, so there shouldn't be a need to check for expiry date.

Is there a real need for Pyarmor to check for an internet connection in this case?

**Comment by jondy** [comment]
No. PyArmor do not check any internet connection in this case.

**Comment by SIVLEOL** [comment]
So since I'm not able to call pyarmor hdinfo function from anywhere but the shell, in the non-obfuscated version of the code I temporarily added a different hardware query I wrote for another purpose into the code run in the subprocesses and had it write the output to disk. This retrieved the harddisk serial and mac address fine. I'm assuming the obfuscated code turned into pyinstaller .exe should still function the same way?

I think we can probably assume that there is no other "license.lic" in the target machine.

I should clarify that both ourselves and customers regularly run the part of the software that the problem appeared in (we regularly test the pyarmor obfuscated code as a pyinstaller .exe), and the problem was only seen once.

Could them pulling out the network cable have temporarily prevented Pyarmor from querying MAC address in the created subprocesses?

Anyways, this problem seems not reproducible, I'll just close this.
