### ISSUE TITLE
[MacOS] Local path 

### ISSUE THREAD

**Issue by Eastkap** [dashingsoft/pyarmor#111]
I'm not able to open local files (same directory ones) with the classic path `./my.file`.

Using latest version and py 3.7

**Comment by jondy** [comment]
Could you show more information? I don't know what's the matter with the obfuscated scripts.

**Comment by Eastkap** [comment]
I'm trying to pack a script with no specific flags. The script reads a local file, that should be placed in the same directory but unfortunately it yields an error

**Comment by jondy** [comment]
Does it work just to pack the script with pyinstaller directly? For example,
```
pyinstaller foo.py
dist/foo/foo
```

**Comment by jondy** [comment]
- I'm trying to pack a script with no specific flags. The script reads a local file, that should be placed in the same directory but unfortunately it yields an error

Please check the document of PyInstaller to be sure the script can be packed by pyinstaller. 
Generally if the python script could be bundle by PyInstaller, it could be packed by pyarmor, just pass the extra options of PyInstaller by -e

**Comment by Eastkap** [comment]
Yes, it's a classic pyinstaller issue actually with relative paths on mac OSX.
The fix is to get the path to the executable, and then change relative paths accordingly.

Closing this, many thanks
