### ISSUE TITLE
import_star_names raises ModuleNotFoundError when  enable `--enable-rft`

### ISSUE THREAD

**Issue by ddi98** [dashingsoft/pyarmor#1111]
this error is returned to me when I use --enable-rft:

`25480 MainProcess 2023-04-08 14:05:14,200 Traceback (most recent call last):   File "<maker>", line 3216, in _import_star_names ModuleNotFoundError: No module named 'routes_generica'  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 627, in main     main_entry(sys.argv[1:])   File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 615, in main_entry     args.func(ctx, args)   File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen     builder.process(options, pack=args.pack)   File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\generate.py", line 145, in process     Pytransform3.pre_build(self.ctx)   File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\core\__init__.py", line 63, in pre_build     return m.pre_build(ctx)   File "<maker>", line 779, in pre_build   File "<maker>", line 666, in build   File "<maker>", line 3308, in process   File "<maker>", line 3222, in _import_star_names RuntimeError: "FormulariTools.app" import * from "routes_generica"`

testing the same problem is also returned using:
--enable-jit
 --assert-call
the only working parameter is --mix-str

**Comment by ddi98** [comment]
@jondy this error is returned to me when i try to fix the cue project i sent you via email is it fixed in .dev9 or should i wait for a new update?

**Comment by jondy** [comment]
I have documented how to use RFT mode, please upgrade to `8.1.0` and check this guide
https://pyarmor.readthedocs.io/en/latest/tutorial/advanced.html#using-rftmode-pro

**Comment by ddi98** [comment]
As reported in the documentation I replaced all the import * with the names of the imported functions and this meant that the obfuscation of the code ended without errors. but when I start the app.py file it doesn't start.
Another strange thing the only option working so far --mix-str after replacing the import * with the names of the functions when I start the app.py file it returns an import error
