### ISSUE TITLE
[BUG]problem with annotations in python 3.11

### ISSUE THREAD

**Issue by noahmuney** [dashingsoft/pyarmor#1116]
I'm trying to obfuscate and run the following script in python 3.11:
![image](https://user-images.githubusercontent.com/98764301/230778701-02d20392-c388-4b8b-a364-a22d0c1d24a9.png)

Unobfuscated returns the following:
{'a': <class 'int'>, 'b': <class 'str'>}

but obfuscated returns:
{ }

script check.py:
![image](https://user-images.githubusercontent.com/98764301/230843067-4cde5ba8-9999-4a48-bfa6-450aa64ee691.png)

running check.py returns:
![image](https://user-images.githubusercontent.com/98764301/230843168-29ba40dc-7f4b-4da2-b01b-d13c1f5d508f.png)

**Comment by noahmuney** [comment]
@jondy 
Works in python 3.10, however I require support for 3.11

**Comment by jondy** [comment]
Reproduced, and will be fixed in the next release.

**Comment by noahmuney** [comment]
@jondy 
Thank you!
Do you have a time estimate?

**Comment by jondy** [comment]
Please try pyarmor `8.1.1a1` with pyarmor.cli.core `2.1.a1`

**Comment by noahmuney** [comment]
@jondy 
It works!
Thanks
