### ISSUE TITLE
MAC address is case sensitive

### ISSUE THREAD

**Issue by peterdroberts** [dashingsoft/pyarmor#112]
I have had issues using pyarmor with `--bind-mac`. I was provided a MAC address in all upper case and attempted to run the pyarmor encrypted script, but got an error that the license was not for the machine. I was able to replicate this issue on a different machine by using an upper-case MAC address. The problem disappeared when I switched to lower-case. This is on an ARM V5 platform. Perhaps the MAC address could be pre-processed to be lower-case before being used to generate a license?

**Comment by jondy** [comment]
It's better to convert it to lower-case in the command line just as you have done. Maybe in some platforms mac-address will include some upper-case chars.
