### ISSUE TITLE
ARM64 Support?

### ISSUE THREAD

**Issue by taka-wang** [dashingsoft/pyarmor#113]
Hello,  do you have any plan to support ARM64 platform? We would like to run it on Nvidia Jetson development board, thanks.

**Comment by jondy** [comment]
ARM64 now is supported, here a list about all supported platforms:
https://pyarmor.readthedocs.io/en/latest/platforms.html

Also refer to 
https://pyarmor.readthedocs.io/en/latest/advanced.html#distributing-obfuscated-scripts-to-other-

**Comment by taka-wang** [comment]
Thank you for your information, I found the `aarch64` shared library in your support list. Nice!
