### ISSUE TITLE
No module named 'pytransform' on Windows 10, Python 3.6.

### ISSUE THREAD

**Issue by tutelarix** [dashingsoft/pyarmor#114]
Python 3.6 installed for all users
Windows 10

Used the guide https://buildmedia.readthedocs.org/media/pdf/pyarmor/latest/pyarmor.pdf

1. Made "pyarmor pack myscript.py" on my own script
2. It was made without warnings
3. Got the resulted script. 
4. On launch got the error:

ModuleNotFoundError: No module named 'pytransform'

Please give any advice to fix the issue.
Thank you.

**Comment by jondy** [comment]
If try to pack the obfuscated scripts, it will raise this error. Do not pack the obfuscated scripts, but plain scripts directly. The command `pack` will obfuscate the scripts automatically.

**Comment by tutelarix** [comment]
Hello @jondy 
It that how I'm doing. I'm not packing obfuscated scripts, I pack plain scripts and get this error.

**Comment by jondy** [comment]
If `myscript.py` is complex, try to a simple helloword script at first.
If it still not work, run `pack` with `--debug`
```
pyarmor pack --debug myscript.py
```
Show the console output here, besides there is a build file `myscript-patched.spec` will be kept in the current path, show it here too.

**Comment by tutelarix** [comment]
Was created a simple "helloword" script pyaroma_test.py

Result of run exe:

_pyaroma_test.exe:_
Traceback (most recent call last):
  File "dist\obf\dist\pyaroma_test.py", line 1, in <module>
ModuleNotFoundError: No module named 'pytransform'
[16420] Failed to execute script pyaroma_test



[test.zip](https://github.com/dashingsoft/pyarmor/files/3814216/test.zip)

**Comment by jondy** [comment]
Try to run pack with option `--clean`:
```
pyarmor pack --clean pyaroma_test.py
```
