### ISSUE TITLE
Couldn't map segment 0 permission denied.

### ISSUE THREAD

**Issue by KaryonixX** [dashingsoft/pyarmor#115]
Hey Devs,

this is a follow up of this problem: https://github.com/dashingsoft/pyarmor/issues/108 
which has partially been resolved by building a new _pytransform.so for android/aarch64. 

The issue i get now is when trying to load up an obfuscated script with a python interpreter on this platform it gives me an error saying it couldnt map file x permission denied.

Screenshot attached 
Any help is appreciated
![Screenshot_20190916-195846_Pydroid 3](https://user-images.githubusercontent.com/50933492/64981878-4932df00-d8bd-11e9-8f11-e7874710cfdc.jpg)

**Comment by jondy** [comment]
I know in some android platforms, the executable files or dynamic libraries only could be run in some folders, they're not allowed from other data folders.  But I'm not sure whether it's the root cause of this issue.

Besides, this `_pytransform.so` is built by `android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang`, is this platform supported by it?

**Comment by KaryonixX** [comment]
Yes. It is an android 64 bit platform thus it should support it without any problems.

**Comment by jondy** [comment]
@KaryonixX  refer to https://github.com/android/ndk/issues/979

Try to put the `_pytransform.so`  in the path `jniLib` other than data folder

**Comment by KaryonixX** [comment]
@jondy I cant find the folder as Im not the app developer. I'm trying to run an obfuscated script on a python emulator on android (PyDroid 3)

Sorry for any lack of knowledge and inconvinience

**Comment by jondy** [comment]
I'm not familiar with android app either.  Only a suggestion, try these commands in PyDroid terminal:
1. Find the path of python site-packages
```
python -c'import sys
 print(sys.path)'
```
2. Move runtime files of pyarmor to site-packages:
```
mv /storage/emulated/0/......../dist/_pytransform.so /path/to/site-packages
mv /storage/emulated/0/......../dist/pytransform.* /path/to/site-packages
mv /storage/emulated/0/......../dist/license.lic /path/to/site-packages
```
