### ISSUE TITLE
Prebuilt libraries (ARMv8 64-bit)

### ISSUE THREAD

**Issue by PidgeyBE** [dashingsoft/pyarmor#116]
Dear

On https://pyarmor.readthedocs.io/en/latest/platforms.html#all-the-others-prebuilt-libraries-for-pyarmor I find a list of prebuilt .so files.
For my use case I need one for ARM v8 64bit, so I've downloaded it, but when I run the pyarmored code, I get the "unknown opcode" error.
With which version of Pyarmor were these libraries built? 
On http://pyarmor.dashingsoft.com/downloads/platforms/, I read it's for Pyarmor 5.1.5, but this release is not available on PyPi anymore...

Would it be possible to rebuild the library for the latest Pyarmor version? (5.5.6)

Thanks! Pidgey

**Comment by jondy** [comment]
Generally this error "unknown opcode"  means that the python version used to obfuscate the scripts is different from the python version to run the obfuscated scripts.

The library is latest, but the document in "http://pyarmor.dashingsoft.com/downloads/platforms/" is out of date.  Here it's the latest build information
https://github.com/dashingsoft/pyarmor-core/blob/master/platforms/index.json
