### ISSUE TITLE
ERROR    cannot import name 'runtime' from 'pyarmor.cli' 

### ISSUE THREAD

**Issue by yunkai-jia** [dashingsoft/pyarmor#1175]
INFO     Python 3.9.13
INFO     Pyarmor 8.1.6 (pro), 005013, non-profits
INFO     Platform darwin.x86_64
CRITICAL unknown error, please check pyarmor.error.log
ERROR    cannot import name 'runtime' from 'pyarmor.cli' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/__init__.py)

**Comment by jondy** [comment]
Please run `pip install pyarmor.cli.runtime` to fix this issue.

**Comment by yunkai-jia** [comment]
Already installed
pyarmor              8.1.6
pyarmor.cli.core     2.1.6
pyarmor.cli.runtime  2.1.6


but still appear：
 pyarmor gen -r --platform windows.x86_64,linux.x86_64,darwin.x86_64  /Users/Desktop/algo/common 
INFO     Python 3.9.13
INFO     Pyarmor 8.1.6 (pro), 005013, non-profits
INFO     Platform darwin.x86_64
CRITICAL unknown error, please check pyarmor.error.log
ERROR    cannot import name 'runtime' from 'pyarmor.cli' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/__init__.py)

**Comment by jondy** [comment]
Is there `/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/runtime`?

And how about import it directly?
```
$ python
>>> from pyarmor.cli import runtime
```

**Comment by yunkai-jia** [comment]
找不到路径：
(base) jiayunkai@jiayunkai-3 cli % cd /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-
packages/pyarmor/cli/runtime
cd: no such file or directory: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/runtime

可以直接导入：
from pyarmor.cli import runtime

**Comment by jondy** [comment]
多个 Python 虚拟环境的问题，请确认 pyarmor 安装的环境可以导入 pyarmor.cli.runtime

**Comment by yunkai-jia** [comment]
如果找不到路径，我该怎么办？目前我已经执行了pip install pyarmor.cli.runtime 
(base) jiayunkai@jiayunkai-3 ~ % pip install pyarmor.cli.runtime
Requirement already satisfied: pyarmor.cli.runtime in /opt/anaconda3/lib/python3.9/site-packages (2.1.6)
(base) jiayunkai@jiayunkai-3 ~ % cd /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-
packages/pyarmor/cli/runtime
cd: no such file or directory: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-
zsh: no such file or directory: packages/pyarmor/cli/runtime

**Comment by yunkai-jia** [comment]
嗯嗯，我在这个环境中执行了pip install pyarmor.cli.runtime，但是发现还是找不到路径，请问这下面该怎么做？
(base) jiayunkai@jiayunkai-3 ~ % pip install pyarmor.cli.runtime
Requirement already satisfied: pyarmor.cli.runtime in /opt/anaconda3/lib/python3.9/site-packages (2.1.6)
(base) jiayunkai@jiayunkai-3 ~ % cd /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-
packages/pyarmor/cli/runtime
cd: no such file or directory: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-
zsh: no such file or directory: packages/pyarmor/cli/runtime

**Comment by jondy** [comment]
请参考 Python 文档或者虚拟环境的文档，这不是 pyarmor 能解决的问题。
