### ISSUE TITLE
PyInstaller when consuming someone else's obfuscated library

### ISSUE THREAD

**Issue by GlennS** [dashingsoft/pyarmor#118]
I am not using pyarmor myself, instead I am consuming someone else's library which has been obfuscated using pyarmor. This is distributed using a private pypi repository.

I found the [instructions for making pyinstaller work with pyarmor](https://pyarmor.readthedocs.io/en/latest/pack-obfuscated-scripts.html).

The first section with the `--add-data` parameters works fine.

However, I haven't been able to work out how to adapt the second section (modifying the `a` object in the pyinstaller spec) to this situation. I do not have a `dist\obf` folder, but rather `venv\lib\site-packages\obfuscated-library-i-depend-on`. I also don't depend on a script, but rather a module.

Can you explain how this snippet finds the obfuscated code's dependencies? Can I adapt it? Or does it depend on having access to the unobfuscated source code?

For now, I shall work around this by writing these dependencies out manually.

**Comment by jondy** [comment]
You need not care about the second section. In your case, just including all the files in the path `venv\lib\site-packages\obfuscated-library-i-depend-on` by `--add-data`

**Comment by GlennS** [comment]
Thanks for the help jondy, much appreciated.

Your comment got me part of the way, and I've figured out the rest by myself. 

I've written it up here in case it helps anybody who stumbles across it in the future.

PyInstaller looks for imports in three ways:

- Parsing your code for `import foo` statements, then following this import statements and parsing those modules for import statements as well. This method fails once we get into obfuscated code
- Getting dependencies from modules imported as _egg_. I don't understand this very well and wasn't able to get it to work. It may be possible to find a simpler solution by figuring this out.
- Running [hooks](https://pythonhosted.org/PyInstaller/hooks.html). PyInstaller comes bundled with some hooks, but we need to add our own custom hook.

## Step-By-Step

### 1- Generate PyInstaller Spec

We need to include a directory structure, but there isn't a command line option to do that. If you try, the directory structure gets flattened.

However, if you generate a PyInstaller spec, there is a `Tree` function which can help.

```
pyi-makespec my_application\__main__.py --name "my-application" --onefile ^
    --additional-hooks-dir "hooks"
```

This creates a file `my-application.spec`.

### 2 - Modify PyInstaller Spec to Include Obfuscated Library

Insert one line into `my-application.spec` after `a = Analysis...` and before `pyz = PYZ(...`:

```
a.datas += Tree('./venv/Lib/site-packages/obfuscated_library', prefix='obfuscated_library, excludes=["*.pyc"])
```

### 3- Create Hook to Include Obfuscated Library's Dependencies

Next we create a file `hooks\hook-my_application.py`. This will compare the modules which have been loaded before and after we import **everything** we need from the obfuscated library we depend on.

```
from textwrap import dedent

from PyInstaller.utils.hooks import eval_statement

statement = dedent("""
    import obfuscated_library.pytransform as pytransform
    pytransform.pyarmor_runtime()
    import sys
    i_before = set(sys.modules.keys())
    from obfuscated_library.a import some_thing
    from obfuscated_library.b import some_other_thing
    i_after = set(sys.modules.keys())
    print(list(i_after - i_before))
""").strip().replace("\n", ";")

hiddenimports = eval_statement(statement)
```

### Build and Run Executable

```
pyinstaller my-application.spec --name "my-application" -y --clean --onefile
```

Now you can run your application at `dist\my-application.exe`.
