### ISSUE TITLE
Display license renewal info when original license expired

### ISSUE THREAD

**Issue by Jules101** [dashingsoft/pyarmor#120]
How is it possible to allow program to open to display license renewal info when original license has expired. Currently it seems that once expired the program will not start at all.

**Comment by jondy** [comment]
It need extend license type by plugin, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#using-plugin-to-extend-license-type

**Comment by Jules101** [comment]
Hi Jondy. Thanks for the quick reply. OK I tried everything I could think of to get it to work and the only way I can get it to work is to set no expiry date and to check the date etc after startup with the plugin mechanism. I tried some encrypted date too but license just crashes unless it recognises the date. So my solution has ended up as a non expiring license with the expiry date, user and module locking all in the code. Not ideal but it seems to work.

**Comment by jondy** [comment]
By this way the scripts need to be obfuscated again when they're expired.  I think you can insert the following code in the main script:
```
def check_expired_date():
    import sys
    from datetime import datetime
    from pytransform import get_license_code
    expired_date = datetime.strptime(get_license_code(), '%Y%m%d')
    delta = expired_date - datetime.now()
    if delta.days < 0:
        print('License has been expired %s days' % -delta.days)
        sys.exit(1)
check_expired_date()        
```

Then obfuscate the scripts and generate a license like this:
```
pyarmor licenses -e 2019-12-20 20191101
```
So the license will be expired on 2019-12-20, but in the obfuscated scripts the last argument "20191101" will take effects.

If this simple case works, you can add more logic in the main script. And after 2019-11-01, just generate another license like this
```
pyarmor licenses -e 2019-12-20 20191201
```

**Comment by Jules101** [comment]
Hi Jondy, Sorry for late reply.
Yes thats the solution I was heading for and have now implemented. Seem to work fine all inside the obfuscated application. 
Just a suggestion. Maybe a payload field (with obviously a max size) that played no part in the automatic licensing would be a good improvement in future. The CODE field acting as a data field means the license file location (based on code for folder names) gets complicated to automate when the code contains the "real" license info.
Thanks for the help
Jules

**Comment by Jules101** [comment]
Or maybe a switch somewhere that allowed the automated validation simply to ignore the mac_info and hd_info if the license is generated with the switch on. That would allow the code field to contain just the real expiry date and still expire via the automated date, but would still allow to run in demo mode on any computer till the license expiry and the validation code in the application would enforce mac addresses is set. That way a user can use a "trial version" for a while even if the mac and hd info do not correspond giving time to issue a real license having obtained a machine code from the user and reissue the full license. That is teh scenario I am facing, where users are testing my application for a trial period (or demo) and when they purchase and supply the machine ids I issue a full license locked to the machine.
Either way its working well now. Excellent utility.
Thanks
Jules
