### ISSUE TITLE
entry-script inside a python package: No module name pytransform

### ISSUE THREAD

**Issue by smedisetti** [dashingsoft/pyarmor#121]
Hi,

I have been trying to use pyarmor to obfuscate pyside gui application and pack with pyinstaller as one folder executable. I followed the pyarmor documentation and did the following steps.

project structure:
.
-- my-project
-- |-- gui-application
-- |-- |--cli
-- |-- |--|--__init__.py
-- |-- |--|--gui.py
-- |-- |--ui
-- |-- |--|-- __init__.py
-- |-- |--|-- window.py
-- |-- __init__.py
--setup.py
--pyinstaller_hooks
-- |-- |---hook-x.py
-- gui.spec

Step 1: Create a pyarmor project
`pyarmor init --src=gui-application/ --entry=cli/gui.py`

Step 2: Obfuscate all the scripts in this project
`pyarmour build`

output:
--my-project
-- |--dist
-- |-- |--gui-application
-- |-- |--|--cli
-- |-- |--|--|--__init.py
-- |-- |--|--|--gui.py
-- |-- |-- |--ui
-- |-- |--|--|-- __init.py
-- |-- |--|--|-- window.py
-- |-- |-- init.py
-- |-- |--pytransform.key
-- |-- |--pytransform.py
-- |-- |--license.lic
-- |-- |--_pytransform.dll

Even though runtime files (pytransform.py, ...) are moved next to the cli/gui.py entry script still cause problem. I replaced bootstrap line in the gui.py by `from .pytransform` to look for import in the current directory. However, Could you please tell me how could I proceed further using our gui.spec by inserting runtime files as datas inside the pyinstaller hook file and efficiently replacing entry file with obsfuscated entry file and all other obfuscated files through the Analysis section of gui.spec file. 

Note: the above project structure is not complete just a subset to show as an example.

**Comment by jondy** [comment]
Refer to this link to change your `gui.spec`
https://pyarmor.readthedocs.io/en/latest/pack-obfuscated-scripts.html

By the way, it's better to run command `pack` to pack the obfuscated scripts:
```
    pyarmor -e " --onefile" --x " --src gui-application/" cli/gui.py
```
Pass any pyinstaller options by `-e`, and pass any obfuscate option by `-x`, more examples refer to https://pyarmor.readthedocs.io/en/latest/man.html#pack

**Comment by smedisetti** [comment]
`pyarmor obfuscate --recursive --src "." cli/main.py

INFO     PyArmor Version 5.7.3
Traceback (most recent call last):
  File "C:\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\anonymous\.virtualenvs\cobagui\Scripts\pyarmor.exe\__main__.py", line 7, in <module>
  File "c:\users\anonymous\.virtualenvs\cobagui\lib\site-packages\pyarmor\pyarmor.py", line 1090, in main_entry
    main(sys.argv[1:])
  File "c:\users\anonymous\.virtualenvs\cobagui\lib\site-packages\pyarmor\pyarmor.py", line 1086, in main
    args.func(args)
  File "c:\users\anonymous\.virtualenvs\cobagui\lib\site-packages\pyarmor\pyarmor.py", line 456, in _obfuscate
    for s in args.scrips:
AttributeError: 'Namespace' object has no attribute 'scrips'
`

PS: Recently purchased license

**Comment by jondy** [comment]
Sorry,it should be typo error. A quick around is just replace `scrips` with `scripts` in line 456 of `c:\users\anonymous.virtualenvs\cobagui\lib\site-packages\pyarmor\pyarmor.py`

I'll release a bug fix version soon.
