### ISSUE TITLE
[BUG] Outer licence file with pyinstaller

### ISSUE THREAD

**Issue by mevaere** [dashingsoft/pyarmor#1226]
It seems there is a problem with outer licence.

Everything works fine **if the licence file is included in the package** but with outer licence pyinstaller is not usable.

- Obfuscating without key
`pyarmor gen -O obfdist main.py fibonacci.py --outer`
- Generating a key
`pyarmor gen key -e 30 --bind-data "Licensed to Rémi" `
- Everything Works FINE !

![image](https://user-images.githubusercontent.com/51992495/236607397-ed4dae34-c54b-4284-9559-21d501e754fc.png)

But after using pyinstaller packing : 
`pyinstaller main.spec`

Copying the key to the directory
Running the app 
```
PS D:\JetBrainsProjects\PyCharm\PyArmorV2\dist\main> .\main.exe
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
RuntimeError: unauthorized use of script (1:10498)
[1592] Failed to execute script 'main' due to unhandled exception!
```

![image](https://user-images.githubusercontent.com/51992495/236607443-a9f088c5-9f7c-44da-b380-c82459483999.png)

This problem doesn't occured if I don't use the parameter `--outer` but I need to provide the licence manually to each user.

Thanks for help
```
$ pyarmor gen -O dist --assert-call foo.py
INFO     Python 3.10.11
INFO     Pyarmor 8.1.9 (pro), 005107
INFO     Platform windows.x86_64

```

**Comment by jondy** [comment]
How about using Pyarmor `8.2.dev2`?

**Comment by mevaere** [comment]
Seems to work on my side !

**Comment by mevaere** [comment]
Seems to work on my side !
