### ISSUE TITLE
Raspberry get_hd_info file not found error

### ISSUE THREAD

**Issue by ruky87** [dashingsoft/pyarmor#123]
I have the following error in pytransform.py
```
  File "/home/......../pytransform.py", line 100, in get_hd_info
    raise PytransformError(_get_error_msg())
pytransform.PytransformError: b'No such file or directory'
```
My code is
```
from pytransform import PytransformError, get_license_info, get_expired_days, get_hd_info, get_license_code, HT_IFMAC, HT_HARDDISK

print('HW Information: {} - MAC="{}" HDD="{}"'.format(pc_model, get_hd_info(HT_IFMAC), get_hd_info(HT_HARDDISK)))
```
If I run pyarmor hdinfo on raspberry in my virtualenv I can get the mac address but not the HDD serial and the IP. For the HDD info, it should be a thing like "cat /sys/block/mmcblk0/device/cid" on the raspberry
```
Faild to get harddisk information.

Mac address: "my mac address"

Faild to get ip address.

Domain name: "(none)"
```

**Comment by jondy** [comment]
Your code must run in the obfuscated scripts. If run it in plain scripts, insert 2 lines before your code
```
from pytransform import pyarmor_init
pyarmor_init()
```

It need root right to query HDD info. If the root user still doesn't work, maybe your HDD isn't support by PyArmor. You need use plugin to extend the license type, refer to this example

https://github.com/dashingsoft/pyarmor/tree/master/plugins#example-2-check-docker-container-id

You could check one of file in the path `/dev/disk/by-id/`

**Comment by ruky87** [comment]
Thanks,
running the script as root is not an option in my case. I will disable the HDD info checking and implement the "cat /sys/block/mmcblk0/device/cid" SD serial check as custom CODE string.
