### ISSUE TITLE
`Error message` 加密后的脚本无法被pyinstaller正确打包其依赖文件

### ISSUE THREAD

**Issue by lingdu0001** [dashingsoft/pyarmor#1230]
Please read this first before report any issue
https://pyarmor.readthedocs.io/en/latest/questions.html

Please copy the whole command line `pyarmor gen` and first 4 lines in the console, do not mask anything, and do not paste snapshot image

```
$ pyarmor gen -O dist --assert-call foo.py
INFO     Python 3.11.3
INFO     Pyarmor 8.1.9 (pro), 005122, non-profits
INFO     Platform windows.x86_64

```
用pyinstaller正常打包（用的spec文件）文件大小为120M。
先用pyarmor  gen -O dist -r src 生成加密文件后
改为用pyinstaller打包加密后的文件，生成的文件大小只有83.1M。
运行文件的时候报错
![image](https://user-images.githubusercontent.com/5213652/237046778-13a35edb-13f4-4314-a709-4bb465ad1a2e.png)

感觉是pyinstaller中少了对应的pip包，用pyinstxtractor反编译以后也发现确实少了pip依赖。

**Comment by jondy** [comment]
请参阅使用文档正确使用 Pyarmor.
