### ISSUE TITLE
Mac Address order invalidate license

### ISSUE THREAD

**Issue by ruky87** [dashingsoft/pyarmor#124]
I have a problem: I want to bind my python code to the raspberry mac address. I have multiple network devices. The problem is that I generate the license with the mac address given by hdinfo, and after a system reboot the mac address changes sometimes and the license is not valid anymore. This because pyarmor takes only the first mac address and, I don't know how or why, the order of network devices sometimes changes and this is a fail...
How to solve?

**Comment by jondy** [comment]
One way is binding `eth0` to mac address, for example, edit `/etc/sysconfig/network-scripts/ifcfg-eth0`
```
HWADDR=00:30:48:7f:b5:ca
```
