### ISSUE TITLE
[BUG] `ERROR: No matching distribution found for pyarmor.cli.core~=2.1.8`

### ISSUE THREAD

**Issue by Soujanya459** [dashingsoft/pyarmor#1251]
pip install pyarmor==8.1.8
Collecting pyarmor==8.1.8
  Downloading pyarmor-8.1.8-py2.py3-none-any.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 478.5 kB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement pyarmor.cli.core~=2.1.8 (from pyarmor) (from versions: none)
ERROR: No matching distribution found for pyarmor.cli.core~=2.1.8

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip

```
python : 3.11.2
OS: FreeBSD amd64
pip:  22.3.1
```

Can you please let me know what is the issue here? is pyarmor not supported in FreeBSD-AMD64 OS ?

**Comment by jondy** [comment]
FreeBSD is not still not supported by Pyarmor8, please check the latest documentation.
