### ISSUE TITLE
Segmentation fault with python 3.8.0

### ISSUE THREAD

**Issue by simonsruggi** [dashingsoft/pyarmor#126]
Getting segmentation fault with python 3.8.0

**Comment by jondy** [comment]
I'll check it

**Comment by simonsruggi** [comment]
Tried to downgrade to 3.7.3 but still same issue.

**Comment by simonsruggi** [comment]
Only on Mac I have this issue, Windows is working fine.

**Comment by jondy** [comment]
In my vm with MacOS11.9, pyarmor works well by python3.7.0. 
How about run pyarmor with PYTHONDEBUG, for example
```
PYTHONDEBUG=y pyarmor -h
```
Is there any extra error message?

**Comment by simonsruggi** [comment]
I don't get any error, but after compiled with pyinstaller i get this:
Segmentation fault: 11

Same files obfuscated by pyarmor and compiled with the same spec file on Windows work good, this is why it' strange.

**Comment by jondy** [comment]
Do the obfuscated scripts work without pyinstaller?

**Comment by simonsruggi** [comment]
Unfortunately no.

**Comment by jondy** [comment]
Do you obfuscate the scripts with some extra options? 
And how about obfuscating a simple script? For example,
```
pyarmor obfuscate foo.py
cd dist/
python foo.py
```

**Comment by jondy** [comment]
I have checked the source of Python3.8.0, I think now pyarmor could not work with it. I'm fixing this issue, and will release new patch version in a few days.

**Comment by simonsruggi** [comment]
Thank you so much, btw in past with python 3.7.3 I have never had any issue. 
I hope you’ll fix it, because I really need it. Thank you so much!

**Comment by simonsruggi** [comment]
Just tried with a simple print('Hello world') and it still shows segmentation fault!

**Comment by jondy** [comment]
Please upgrade to pyarmor v5.6.4, it supports Python3.8

**Comment by simonsruggi** [comment]
Upgrade done, but same error unfortunately. Maybe i'm doing something wrong on my end.

**Comment by jondy** [comment]
I have tested the new version by Python 3.8 in win64 and linux64, but not in MacOS.  Does it work to obfuscate a simple script in windows 64?

**Comment by jondy** [comment]
I have tested the new version by Python 3.8 in win64 and linux64, but not in MacOS.  Does it work to obfuscate a simple script in windows 64?

**Comment by simonsruggi** [comment]
Yeah on Windows i have no problems, btw it's really strange, because i've never had any error in past.

**Comment by jondy** [comment]
It's very strange indeed. The early version of pyarmor should not work with Python 3.8 in any platform, because the structure of code object has been changed a little in Python 3.8. 

Does you obfuscate the scripts with advanced mode in MacOS?

**Comment by simonsruggi** [comment]
I used to obfuscate with pyarmor and python 3.7.3 with no errors. Then i got some errors with python 3.7.3 so i tried 3.8.0 but i get the same errors.  (I tried on 2 different macbook and i have the same issue)
Btw what do you mean for advanced mode?

**Comment by jondy** [comment]
The advanced mode means obfuscating the scripts with `--advanced`.

What's the exact error messages you got with python 3.73 a few days ago? It's segmentation fault or something else.

**Comment by simonsruggi** [comment]
Yeah I always get segmentation fault. 
What I do is:
pyarmor init
pyarmor build
pyarmor obfuscate script.py
cd dist
pyinstaller script.spec

**Comment by jondy** [comment]
Try to run build with `-B` to force obfuscating all the scripts, otherwise only the changed scripts since last build are obfuscated again.  For example,
```
pyarmor build -B
```

In your case, it's possible that some scripts are obfuscated by Python3.7,  some are obfuscated by Python3.8. And maybe it's the problem.

**Comment by simonsruggi** [comment]
Same error, unfortunately. I'm getting mad

**Comment by jondy** [comment]
In which step it raise segmentation fault?  `pyarmor build`, or to run the final executable made by pyinstaller. If that, first run pyinstaller to pack your scripts directly (no obfuscating), to be sure it works.

**Comment by simonsruggi** [comment]
Yeah I tried by running pyinstaller before and it works smoothly. (Without obfuscation)
Sometimes I get segmentation fault on pyarmor build and sometimes I get it when I try to run the obfuscated script.

**Comment by jondy** [comment]
It seems the problem isn't related to Python 3.8, but one of your scripts results in the segmentation fault.

**Comment by simonsruggi** [comment]
Yeah I thought the same, but I have the same error with a simply print(‘hello world’) script.
Tried also to remove all the python installation and reinstalled them but with no success

**Comment by jondy** [comment]
Try to remove the capsule of pyarmor: ``` rm ~/.pyarmor_capsule.zip```

Another suggestion is to update MacOS
```
brew update
brew upgrade
```

**Comment by jondy** [comment]
Besides uninstall pyarmor and delete the installation path of pyarmor to be sure there is no any `_pytransform.dylib`, then resintall pyarmor

BTW what's the output of command `arch` in your MacOS?

**Comment by simonsruggi** [comment]
Tried everything but with no success.
The output of command arch in my MacOS is: i386

**Comment by jondy** [comment]
```
import struct
print('machine bitness is ', struct.calcsize('P'.encode()) * 8)
```
What's the output of this python script? Now the prebuilt `_pytransform.dylib` only works for 64-bit machine, not work for 32-bit machine.

**Comment by simonsruggi** [comment]
machine bitness is  64

**Comment by simonsruggi** [comment]
This is the output when I try to run an obfuscated script:
https://hastebin.com/fayifunetu.xml

**Comment by jondy** [comment]
How about using early version of PyArmor, for example
```
pip install pyarmor=5.5.2
```

**Comment by jondy** [comment]
I got it. This output "fayifunetu.xml" shows useful information. Could you upload the share library of Python 3.7.3 and Python 3.8.0 here? I need check these binary files to fix this issue.

**Comment by jondy** [comment]
A quick workaround for your case is to disable advanced mode by editing the `pytransform.py` which locates in the installed path of pyarmor, uncomment line 222 like this
```
    # Disable advanced mode if required
    m.set_option(5, c_char_p(1))
```

**Comment by simonsruggi** [comment]
Yeah, it's working!
