### ISSUE TITLE
[BUG] ERROR    'Context' object has no attribute 'runtime_package_template'

### ISSUE THREAD

**Issue by jimgibb** [dashingsoft/pyarmor#1273]
Error message: ERROR    'Context' object has no attribute 'runtime_package_template'

The error occurs with `pyarmor.cli.core==3.2.1` but not with `pyarmor.cli.core==3.2.0`
Can avoid by pinning pyarmor.cli.core to 3.2.0

```
$ pyarmor gen -i --recursive ./test
INFO     Python 3.10.10
INFO     Pyarmor 8.2.0 (trial), 000000, non-profits
INFO     Platform linux.x86_64
```

**Comment by jondy** [comment]
Please upgrade pyarmor to 8.2.1
