### ISSUE TITLE
[BUG] `RuntimeError: the format of obfuscated script is incorrect`

### ISSUE THREAD

**Issue by Itakkkkkk** [dashingsoft/pyarmor#1275]
version: 8.2.0
OS: Ubuntu20.04
Command
```
pyarmor gen --platform linux.x86_64 --platform linux.aarch64 -r -O dist dir1 dir2
```
After this command, pyarmor_runtime_xxxxxx/pyarmor_runtime.so, pyarmor_runtime_a1.so are generated.
In runtime, I got the following error.
```
ImportError: pyarmor_runtime_xxxxxx/pyarmor_runtime.so: cannot open shared object file: No such file or directory
```
I replaced ```except ModuleNotFoundError``` with ```except ImportError``` in pyarmor_runtime_xxxxxx/__init__.py.
Then, the script can try to load pyarmor_runtime_a1.so but I got other error as following.
```
RuntimeError: the format of obfuscated script is incorrect (1:5334)
```
According to errors.rst, the cause of the error is 
```1. the obfuscated script is made by other Pyarmor version```
or 
```2. can not get runtime package path```

In my case, pyarmor version of obfuscating and runtime are the same and the script can get runtime package path.

**Comment by jondy** [comment]
Please upgrade pyarmor to 8.2.1, it refines multiple platforms bootstrap script.
