### ISSUE TITLE
How does the license work?

### ISSUE THREAD

**Issue by Silve2611** [dashingsoft/pyarmor#1277]
Hi, 

I do not really understand the license model and I found no email to get in contact. 
How long is the license valid if one is purchased?
Can the license be used on the local machine for test and on azure pipelines for the build? 
What would be the best license for that? 

Sorry I had to make an issue but I saw no other form of contact on the webpage. ordersupport@mycommerce.com could not answer the question.

**Comment by jondy** [comment]
Please check online documentation first.

**Comment by Silve2611** [comment]
I have checked it. But it is not precise enough.

- How long is the license valid if one is purchased?
-- It is only paid once. Good
- What is the exact difference between pro and group. Is pro enough for me to use it on my machine and azure pipelines. Or would pro be needed? 

I do not mind paying for software but I would appreciate some Information. Thx

**Comment by Silve2611** [comment]
I have seen the last paragraph, which I already stated. I could see that the difference between pro and group would probably be the offline possibility. I would have liked to know if there is something else. 

Actually I am not really keen on buying something if the simplest questions cannot be answered. 
I doubt that the hard questions will be able to get resolved if the easy ones make such a problem. A harder question would be if I can use it wherever I want. Azure pipelines in our case. There is nothing about it in the documentation and it seems i have to resolve it myself.

Thank you for your time.

**Comment by jondy** [comment]
Sorry, Pyarmor doesn't support those questions which has been documented. It's a command line tool, and all the functions are well documented.

**Comment by Silve2611** [comment]
I understand. But sometimes people cannot see through a documentation. In general, weather it works with azure pipelines is not documented but ok.

Have a nice day.
