### ISSUE TITLE
[BUG]  no pyarmor_ runtime extension found

### ISSUE THREAD

**Issue by yhak1452** [dashingsoft/pyarmor#1280]
C: users 8b15b Desktop Y angLeGerang Pyqt - ma1n d1st ma1n. Py

Traceback (most recent call last) :

File 'C: Users' 86156 Desktop YangLeGeYang -Pyqt- -mainldist main.py", line 2, in <module>

from pyarmor_ runt ime_ 000000 import_pyarmor

File . 'C: Users 86156Desktop YangLeGeYang -Pyqt -mainldist pyarmor_ runtime_ 000000__ init_. py", line 12, in <moduraise Modul eNotFoundError(' no pyarmor_ runtime extension found' )

Modul eNotFoundError: no pyarmor_ runtime extension found

>>〉

**Comment by jondy** [comment]
Please check Pyarmor online documentation and following the guide to report issue.
