### ISSUE TITLE
[BUG] RuntimeError: Resource temporarily unavailable (1:10850)

### ISSUE THREAD

**Issue by codezillars** [dashingsoft/pyarmor#1283]
Hi Jondy,

Upgraded pyarmor 7 -> 8. 

I'm using an outer license file running in an air-gap environment.
Performed the following command:
  pyarmor gen key -e 365
copied the pyarmor.rkey and paste into pyarmor_runtime_00-020 directory.

Encountered this error re-running my pyspark script.
RuntimeError: Resource temporarily unavailable (1:10850)

Is there any pyarmor runtime log to view more details?

```
INFO     Python 3.10.9
INFO     Pyarmor 8.2.1 (group), 00-020
INFO     Platform linux.x86_64
```

**Comment by jondy** [comment]
Please search "Resource temporarily unavailable" in issues and online documentation to find the reason.

**Comment by codezillars** [comment]
Hi Jondy, 

As mentioned in documentation, understand the error comes from not being able to establish NTP servers, also an alternative method you've prescribed is to use an API call. However the environment is air-gapped and does not support either of these. we are using docker images, will binding to mac be possible for containers?

**Comment by jondy** [comment]
Please check https://pyarmor.readthedocs.io/en/latest/tutorial/customization.html
