### ISSUE TITLE
Error when I use parameters “--platform windows.x86_64” or “--platform linux.x86_64”

### ISSUE THREAD

**Issue by paw-bor** [dashingsoft/pyarmor#1289]
My enviroment
MS Windows 11 pro 64bit, /  Python 3.11.2, asgiref==3.7.2, Django==4.2.1, pyarmor==8.2.2, pyarmor-webui==2.0, pyarmor.cli.core==3.2.2, pyarmor.cli.runtime==3.2.2, pywin32==306, sqlparse==0.4.4, tzdata==2023.3

When I obfuscate my Django project without cross platform parameter “--platform”:
 - on my Windows system – obfuscated app works fine on Windows
 - on Linux Debian 11.7-slim-bullseye / python 3.11-slim (in docker) - obfuscated app works fine on Linux (in docker)

But, when I obfuscate the same project with parameters: 
 - “pyarmor gen --platform windows.x86_64 --platform linux.x86_64 -O .\destination_folder\ -r .\source_folder\” - obfuscated app doesn’t work naither on Windows nor on Linux (in docker)
 - “pyarmor gen --platform windows.x86_64 -O .\destination_folder\ -r .\source_folder\” - obfuscated app doesn’t work on Windows
 - “pyarmor gen --platform windows.x86_64 -O .\destination_folder\ -r .\source_folder\” - obfuscated app doesn’t work on Linux (in docker)

What is interesting, in each mentioned error case, directory “pyarmor_runtime_000000” and all created files look OK, but app doesn't start and system reports an error:

Traceback (most recent call last):
File "/djTest/manage.py", line 2, in <module>
from pyarmor_runtime_000000 import __pyarmor__
File "/djTest/pyarmor_runtime_000000/__init__.py", line 2, in <module>
from .pyarmor_runtime import __pyarmor__
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

**Comment by jondy** [comment]
Got it, thanks. It will be fixed in next release.

**Comment by jondy** [comment]
Fixed it in v8.2.3

**Comment by paw-bor** [comment]
My venv after I upgraded pyarmor:
asgiref==3.7.2; Django==4.2.1; pyarmor==8.2.3; pyarmor-webui==2.0; pyarmor.cli.core==3.2.3; pyarmor.cli.runtime==3.2.2; pywin32==306; sqlparse==0.4.4; tzdata==2023.3

- Command:
pyarmor gen -O .\obf_folder\ -r .\source_folder\ 
works OK

- Cross platform commands:
  pyarmor gen --platform windows.x86_64 --platform linux.x86_64 -O .\obf_folder\ -r .\source_folder\
or
  pyarmor gen --platform windows.x86_64 -O .\obf_folder\ -r .\source_folder\
or
  pyarmor gen --platform linux.x86_64 -O .\obf_folder\ -r .\source_folder\

All of them generate following communicates and error:

  INFO     Python 3.11.2
  INFO     Pyarmor 8.2.3 (trial), 000000, non-profits
  INFO     Platform windows.x86_64
  INFO     use runtime platforms: ['linux.x86_64']
  INFO     search inputs ...
  INFO     find package at djTest
  INFO     find 1 top resources
  INFO     start to generate runtime files
  INFO     target platforms {'linux.x86_64'}
  ERROR    PyarmorRuntime.get() got an unexpected keyword argument 'extra'

Script stops, and there appears in the working directory file pyarmor.error.log with content:

980 MainProcess 2023-06-05 14:14:57,490
Traceback (most recent call last):
  File "C:\projects\venv\Lib\site-packages\pyarmor\cli\__main__.py", line 694, in main
    main_entry(sys.argv[1:])
  File "C:\projects\venv\Lib\site-packages\pyarmor\cli\__main__.py", line 682, in main_entry
    args.func(ctx, args)
  File "C:\projects\venv\Lib\site-packages\pyarmor\cli\__main__.py", line 220, in cmd_gen
    builder.process(options)
  File "C:\projects\venv\Lib\site-packages\pyarmor\cli\generate.py", line 152, in process
    self.generate_runtime_package(self.ctx.outputs[0])
  File "C:\projects\venv\Lib\site-packages\pyarmor\cli\generate.py", line 93, in generate_runtime_package
    Pytransform3.generate_runtime_package(self.ctx, output)
  File "C:\projects\venv\Lib\site-packages\pyarmor\cli\core\__init__.py", line 113, in generate_runtime_package
    return m.generate_runtime_package(ctx, output, platforms)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 857, in generate_runtime_package
  File "<maker>", line 476, in build
  File "<maker>", line 376, in target_file_data
  File "<maker>", line 392, in target_cross_platform
TypeError: PyarmorRuntime.get() got an unexpected keyword argument 'extra'
