### ISSUE TITLE
Wrong dist path using pyarmor.py build

### ISSUE THREAD

**Issue by joonis** [dashingsoft/pyarmor#13]
Using `pyarmor.py build /path/to/project` creates the *dist* folder in the current working directory. Shouldn't the target *dist* be located in the specified project directory?

**Comment by jondy** [comment]
The prefer way to run command build is
```bash
cd /path/to/project
./pyarmor build
```
So it's same as project directory. And if run command build in some other path, save the output here.

**Comment by joonis** [comment]
Maybe you could add an optional argument `--output`, since it is a bit annoying if you have a script to automate thing and you have to cd around the system.

**Comment by joonis** [comment]
By default, the target folder should be `dist/[src_folder_name]` if `src_folder` contains an `__init__.py` file. Because in this case we have a package and we need this extra folder. All runtime files should still go into `dist/` of course.

**Comment by jondy** [comment]
The default output path of project can be changed by command `config`, for example
```bash
cd /path/to/project
./pyarmor config --output=/absolute/path/to/dist/pkgname
./pyarmor build

# or in any other path
pyarmor.py build /path/to/project
```

**Comment by joonis** [comment]
Thanks, that's ok for me - didn't know about the config option.

However a user would expect to get the ready-to-run package in /dist without having to specify an `--output` path.
