### ISSUE TITLE
[BUG] When using `--obf-code=2` raises 'AttributedDict' object has no attribute '__end'`

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#1300]
When using `--obf-code=2` with `8.2.4`

Encounter the following exception `AttributedDict' object has no attribute '__end'` via `dirtyjson`

**Comment by VeNoMouS** [comment]
FWIW, i have merged dirtyjson package into one file

**Comment by VeNoMouS** [comment]
also get `RuntimeError: protection exception (16777924)`  when i use `--assert-import` on dirtyjson

**Comment by jondy** [comment]
No attribute issue is fixed in next release.

**Comment by jondy** [comment]
Fixed it in 8.2.5
