### ISSUE TITLE
[BUG] `[Errno 13] Permission denied` when packing file generated by PyInstaller

### ISSUE THREAD

**Issue by robbMo8** [dashingsoft/pyarmor#1311]
When i try to obfuscate an exe file (built with pyInstaller) using this command:
pyarmor gen --pack .\dist\app.exe app.py

I receive the following output saying that a folder cannot be accessed:
```
INFO Python 3.10.10
INFO Pyarmor 8.2.5 (pro), 005132, non-profits(TBD)
INFO Platform windows.x86_64
INFO implicitly set output to ".pyarmor\pack\dist"
INFO extracting bundle ".\dist\app-v1.0.7.1.exe"
INFO search inputs ...
INFO find script app.py
INFO find 1 top resources
INFO start to generate runtime files
INFO target platforms {'windows.amd64'}
INFO write .pyarmor\pack\dist\pyarmor_runtime_005132\pyarmor_runtime.pyd
INFO patch runtime file
INFO generate runtime files OK
INFO start to obfuscate scripts
INFO process resource "app"
INFO obfuscating file app.py
INFO write .pyarmor\pack\dist\app.py
INFO obfuscate scripts OK
INFO repacking bundle ".\dist\app-v1.0.7.1.exe"
INFO obfuscated scripts at ".pyarmor\pack\dist"
INFO entry script name is "app-v1.0.7.1.py"
INFO repacking "PYZ-00.pyz"
INFO replace item "pyarmor_runtime_005132"
INFO repacking PKG "PKG-patched"
Cannot find ('struct', 'C:\Users\SVIL~1.ABC\AppData\Local\Temp\tmp0m92u5w6', 1, 'x')
ERROR [Errno 13] Permission denied: 'C:\\Users\\SVIL~1.ABC\\AppData\\Local\\Temp\\tmp0m92u5w6'
```

```
pyarmor gen -O dist --assert-call app.py
INFO     Python 3.10.10
INFO     Pyarmor 8.2.5 (pro), 005132, non-profits(TBD)
INFO     Platform windows.x86_64
INFO     search inputs ...
INFO     find script app.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write dist\pyarmor_runtime_005132\pyarmor_runtime.pyd
INFO     patch runtime file
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "app"
INFO     obfuscating file app.py
INFO     write dist\app.py
INFO     obfuscate scripts OK
```

**Comment by jondy** [comment]
Check more log by `pyarmor -d gen --pack .\dist\app.exe app.py`

And what's the content of `pyarmor.error.log`?

**Comment by robbMo8** [comment]
Log from 'pyarmor -d gen --pack .\dist\app.exe app.py'
`INFO     Python 3.10.10
INFO     Pyarmor 8.2.5 (pro), 005132, non-profits(TBD)
INFO     Platform windows.x86_64
DEBUG    native platform windows.amd64
DEBUG    home path: C:\Users\svil.mo\.pyarmor
INFO     implicitly set output to ".pyarmor\pack\dist"
DEBUG    command options: {'no_runtime': False, 'inputs': ['app.py'], 'output': '.pyarmor\\pack\\dist'}
DEBUG    install plugin: CodesignPlugin
INFO     extracting bundle "C:\Progetti\PyOrdersProject\dist\app-v1.0.7.1.exe"
DEBUG    extract struct
DEBUG    extract pyimod01_os_path

...
...		 extract ... (omitted due to comment limit)
...

DEBUG    extract wcwidth\version.json
DEBUG    extract wheel-0.40.0.dist-info\INSTALLER
DEBUG    extract wheel-0.40.0.dist-info\LICENSE.txt
DEBUG    extract wheel-0.40.0.dist-info\METADATA
DEBUG    extract wheel-0.40.0.dist-info\RECORD
DEBUG    extract wheel-0.40.0.dist-info\WHEEL
DEBUG    extract wheel-0.40.0.dist-info\entry_points.txt
DEBUG    extract PYZ-00.pyz
INFO     search inputs ...
INFO     find script app.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write .pyarmor\pack\dist\pyarmor_runtime_005132\pyarmor_runtime.pyd
INFO     patch runtime file
DEBUG    patching runtime data at 514592
DEBUG    patch runtime file OK
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "app"
INFO     obfuscating file app.py
DEBUG    process inline marker
DEBUG    parse script
DEBUG    process co
DEBUG    patch co
INFO     write .pyarmor\pack\dist\app.py
INFO     obfuscate scripts OK
INFO     repacking bundle "C:\Progetti\PyOrdersProject\dist\app-v1.0.7.1.exe"
INFO     obfuscated scripts at ".pyarmor\pack\dist"
INFO     entry script name is "app-v1.0.7.1.py"
INFO     repacking "PYZ-00.pyz"
INFO     replace item "pyarmor_runtime_005132"
INFO     repacking PKG "PKG-patched"
Cannot find ('struct', 'C:\Users\SVIL~1.MOD\AppData\Local\Temp\tmpx7l2ltyi', 1, 'x')
DEBUG    unknown error, please check pyarmor.error.log
ERROR    [Errno 13] Permission denied: 'C:\\Users\\SVIL~1.MOD\\AppData\\Local\\Temp\\tmpx7l2ltyi'
`
pyarmor.error.log content:

`21644 MainProcess 2023-06-13 08:24:20,547
Traceback (most recent call last):
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\pyarmor\cli\__main__.py", line 699, in main
    main_entry(sys.argv[1:])
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\pyarmor\cli\__main__.py", line 687, in main_entry
    args.func(ctx, args)
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\pyarmor\cli\__main__.py", line 222, in cmd_gen
    builder.process(options, packer=packer)
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\pyarmor\cli\generate.py", line 162, in process
    packer.repack(output, self.ctx.runtime_package_name)
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\pyarmor\cli\repack.py", line 381, in repack
    repack_executable(executable, buildpath, obfpath, rtentry, codesign)
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\pyarmor\cli\repack.py", line 257, in repack_executable
    repack_carchive(executable, pkgfile, buildpath, obfpath, rtentry)
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\pyarmor\cli\repack.py", line 249, in repack_carchive
    CArchiveWriter2(pkgarch, pkgfile, logical_toc, pylib_name)
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\pyarmor\cli\repack.py", line 127, in __init__
    super().__init__(archive_path, logical_toc, pylib_name)
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\PyInstaller\archive\writers.py", line 313, in __init__
    super().__init__(archive_path, logical_toc)
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\PyInstaller\archive\writers.py", line 51, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\PyInstaller\archive\writers.py", line 75, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\pyarmor\cli\repack.py", line 150, in add
    self._write_rawdata(name, typecode, compress)
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\pyarmor\cli\repack.py", line 141, in _write_rawdata
    super().add((name, f.name, compress, PKG_ITEM_DATA))
  File "C:\Progetti\PyOrdersProject\.venv\lib\site-packages\PyInstaller\archive\writers.py", line 384, in add
    fh = open(pathnm, 'rb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\SVIL~1.MOD\\AppData\\Local\\Temp\\tmpx7l2ltyi'
`

**Comment by kiskivancsi** [comment]
Any solution this? I get the same error. :(

Cannot find ('struct', 'C:\Users\ami\AppData\Local\Temp\tmp7wtf3i6g', 1, 'x')
ERROR    [Errno 13] Permission denied: 'C:\\Users\\ami\\AppData\\Local\\Temp\\tmp7wtf3i6g'

**Comment by jondy** [comment]
How about use this patch?
4594a1a81b958c0b879bba29d087c55cb7d2ff2a 

```patch
--- a/path/to/pyarmor/cli/repack.py
+++ b/path/to/pyarmor/cli/repack.py
@@ -133,16 +133,17 @@ class CArchiveWriter2(CArchiveWriter):
             self._write_blob(rawdata, name, typecode, compress)
             return
 
-        with tempfile.NamedTemporaryFile() as f:
-            f.write(rawdata)
-            f.flush()
+        with tempfile.TemporaryDirectory() as tmpdir:
+            filename = os.path.join(tmpdir.name, name)
+            with open(filename, 'wb') as f:
+                f.write(rawdata)
             if typecode in (PKG_ITEM_PYSOURCE, PKG_ITEM_PYMODULE,
                             PKG_ITEM_PYPACKAGE):
-                super().add((name, f.name, compress, PKG_ITEM_DATA))
+                super().add((name, filename, compress, PKG_ITEM_DATA))
                 tc = self.toc.data[-1]
                 self.toc.data[-1] = tc[:-2] + (typecode, tc[-1])
             else:
-                super().add((name, f.name, compress, typecode))
+                super().add((name, filename, compress, typecode))
 
     def add(self, entry):
         name, source, compress, typecode = entry[:4]
```

**Comment by jondy** [comment]
Fixed in 8.2.6

**Comment by jondy** [comment]
Sorry, still need this patch 
f41e699eb70c0ea70cf9c5f0e67cb41ea2c01c6d

**Comment by robbMo8** [comment]
Got this error now:
```
...
...
DEBUG    one file mode is True
INFO     search inputs ...
INFO     find script app.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write .pyarmor\pack\dist\pyarmor_runtime_005132\pyarmor_runtime.pyd
INFO     patch runtime file
DEBUG    patching runtime data at 515616
DEBUG    patch runtime file OK
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "app"
INFO     obfuscating file app.py
DEBUG    process inline marker
DEBUG    parse script
DEBUG    process co
DEBUG    patch co
INFO     write .pyarmor\pack\dist\app.py
INFO     obfuscate scripts OK
INFO     repacking bundle ".\dist\app-v1.0.7.1.exe"
INFO     obfuscated scripts at ".pyarmor\pack\dist"
INFO     entry script name is "app-v1.0.7.1.py"
INFO     repacking "PYZ-00.pyz"
INFO     replace item "pyarmor_runtime_005132"
INFO     repacking PKG "PKG-patched"
INFO     replace entry "app"
DEBUG    Compiling .pyarmor\pack\dist\app.py
DEBUG    Compiling .pyarmor\pack\dist\app.py
DEBUG    unknown error, please check pyarmor.error.log
ERROR    [Errno 2] No such file or directory: 'C:\\Users\\ro\AppData\\Local\\Temp\\tmponho4iw0\\PIL\\_imaging.cp310-win_amd64.pyd'
```

**Comment by jondy** [comment]
What's the content of `pyarmor.error.log`?

**Comment by robbMo8** [comment]
```
32524 MainProcess 2023-06-15 10:40:12,906
Traceback (most recent call last):
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\pyarmor\cli\__main__.py", line 699, in main
    main_entry(sys.argv[1:])
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\pyarmor\cli\__main__.py", line 687, in main_entry
    args.func(ctx, args)
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\pyarmor\cli\__main__.py", line 222, in cmd_gen
    builder.process(options, packer=packer)
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\pyarmor\cli\generate.py", line 162, in process
    packer.repack(output, self.ctx.runtime_package_name)
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\pyarmor\cli\repack.py", line 391, in repack
    repack_executable(executable, buildpath, obfpath, rtentry, codesign)
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\pyarmor\cli\repack.py", line 258, in repack_executable
    repack_carchive(executable, pkgfile, buildpath, obfpath, rtentry)
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\pyarmor\cli\repack.py", line 250, in repack_carchive
    CArchiveWriter2(pkgarch, pkgfile, logical_toc, pylib_name)
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\pyarmor\cli\repack.py", line 127, in __init__
    super().__init__(archive_path, logical_toc, pylib_name)
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\PyInstaller\archive\writers.py", line 313, in __init__
    super().__init__(archive_path, logical_toc)
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\PyInstaller\archive\writers.py", line 51, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\PyInstaller\archive\writers.py", line 75, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\pyarmor\cli\repack.py", line 151, in add
    self._write_rawdata(name, typecode, compress)
  File "C:\Workspace\CVS\OPTPulito\.venv\lib\site-packages\pyarmor\cli\repack.py", line 138, in _write_rawdata
    with open(pathname, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ro\\AppData\\Local\\Temp\\tmponho4iw0\\PIL\\_imaging.cp310-win_amd64.pyd'
```

**Comment by jondy** [comment]
Apply this patch
cd109ec23ef8db34c874a63269dc156f8b5b9a8e

**Comment by jondy** [comment]
The obfuscated scripts should be replaced, please enable debug option `-d` and check console log to make sure there is log say the item is replaced.
