### ISSUE TITLE
ImportError: No module named 'Cython.Plex'

### ISSUE THREAD

**Issue by newbieh4cker** [dashingsoft/pyarmor#132]
[pack command]
pyarmor pack -e " -D -F" test.py

[run result]
ImportError: No module named 'Cython.Plex'
[1786] Failed to execute script test

Why is this happening?

**Comment by jondy** [comment]
It seems that the `test.py` in the command line is obfuscated.  Do not pack the obfuscated scripts, but plain scripts directly.

**Comment by newbieh4cker** [comment]
@jondy 
nah.. 'test.py' is plain scripts.
looks like third-party module('fbprophet') is causing problem.

here is source of "test.py"
======
import fbprophet as fp
print(fp.__version__)
======

**Comment by jondy** [comment]
Does it could be packed by pyinstaller directly?
```
pyinstaller -D -F test.py
cd dist/test
./test
```

**Comment by newbieh4cker** [comment]
nah, same error occurs.
it was 'pystan' problem that 'fbprophet' uses internally.

however, i found solution
https://github.com/facebook/prophet/issues/982#issuecomment-545453248

**Comment by jondy** [comment]
I could not visit facebook, :(
If pyinstaller workes, `pyarmor pack` could work by passing extra options by `-e`

**Comment by newbieh4cker** [comment]
oh that's not the facebook link.
it is github address for prophet  (since prophet is made from facebook, that url contains 'facebook' string')
