### ISSUE TITLE
[BUG] `docker pyarmor group license`

### ISSUE THREAD

**Issue by Kathir2023** [dashingsoft/pyarmor#1324]
Hi Team,
I am able to test pyarmor with my application in my ubuntu VM but facing issue with create Dockerfile and build license with container.
i have manually started python:3.9 image with bash and tested  it worked but creating dockerfile doing dockerbuild it's not working 

error:
Step 8/15 : RUN mkdir -p .pyarmor/group
 ---> Running in c22f038e2194
Removing intermediate container c22f038e2194
 ---> b0d950e338e7
Step 9/15 : RUN cp pyarmor-regfile-6033.zip .pyarmor/group/
 ---> Running in eff724a9e2b5
Removing intermediate container eff724a9e2b5
 ---> 231b0c993bab
Step 10/15 : RUN pyarmor reg -g 4
 ---> Running in a4fbe04e560f
INFO     Python 3.9.17
INFO     Pyarmor 8.2.7 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     generating device file ".pyarmor/group/pyarmor-group-device.4"
INFO     device file has been generated successfully
Removing intermediate container a4fbe04e560f
 ---> b5e0b9f1262a
Step 11/15 : RUN ls .pyarmor/group/
 ---> Running in 1d7eed4e510d
pyarmor-group-device.4
pyarmor-regfile-6033.zip
Removing intermediate container 1d7eed4e510d
 ---> ea4b1f7981b6
Step 12/15 : RUN pyarmor reg -g 4 pyarmor-regfile-6033.zip
 ---> Running in 3cd443a6c9d2
INFO     Python 3.9.17
INFO     Pyarmor 8.2.7 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register device file ".pyarmor/group/pyarmor-group-device.4"
INFO     use group license "pyarmor-regfile-6033.zip"
INFO     send request to server
INFO     write registration file "pyarmor-device-regfile-6033.4.zip"
INFO     please copy deivce regfile to offline device and run
INFO         pyarmor reg pyarmor-device-regfile-6033.4.zip
INFO     The device regfile has been generated successfully
Removing intermediate container 3cd443a6c9d2
 ---> 8c9413d78458
Step 13/15 : RUN pyarmor reg pyarmor-device-regfile-6033.4.zip
 ---> Running in d3238e18917a
INFO     Python 3.9.17
INFO     Pyarmor 8.2.7 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "pyarmor-device-regfile-6033.4.zip"
ERROR    this regfile is not for this device
The command '/bin/sh -c pyarmor reg pyarmor-device-regfile-6033.4.zip' returned a non-zero code: 1
(venv) ubuntu@ip-172-31-36-66:~/privagpt-core

**Comment by jondy** [comment]
Group license will support unlimited docker soon, refer to #1305

At this time, try to run docker container with same `--name` and macaddress

**Comment by Kathir2023** [comment]
@jondy  you mean i need to update in dockerfile.
This is my reference dockerfile.please sugest me for chnage where should update macaddress
FROM python:3.9-slim


RUN mkdir priva
WORKDIR ./priva
COPY pyarmor-regfile-6033.zip .


#RUN apt-get install -y git unzip gcc-c++ make
RUN pip3 install pyarmor==8.2.7
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf awscliv2.zip ./aws
RUN pyarmor -v
RUN mkdir -p .pyarmor/group
RUN cp pyarmor-regfile-6033.zip .pyarmor/group/
RUN pyarmor reg -g 4
RUN ls .pyarmor/group/
RUN pyarmor reg -g 4  pyarmor-regfile-6033.zip
RUN pyarmor reg pyarmor-device-regfile-6033.4.zip

**Comment by Kathir2023** [comment]
i have faced multiple issue to get into this stage,if you can guide me to solve this stage .may be we can create document for the people who looking support for the similar case

**Comment by jondy** [comment]
Pyarmor 8.2.8 is released to support unlimited dockers for group license, refer to
https://pyarmor.readthedocs.io/en/v8.2.8/how-to/register.html#run-unlimited-dockers-in-offline-device

**Comment by Kathir2023** [comment]
@jondy  I have couple of questions:
- How this can transfer docker image to different VM 
-  How to deploy docker image into kubernetes cluster

Can you please share what ever you tested  for sample for reference

**Comment by jondy** [comment]
> run docker.py file inside src/cli folder

It doesn't work, it must be run inside package.

I have no idea about kubernetes cluster.

Each VM could taken as one offline device.

I test group licenses in a cloud server (ECS) with docker

**Log in cloud server by ssh**
```
$ ls v8-test
pyarmor-8.2.8.tar.gz
pyarmor.cli.core-3.2.8-cp311-none-manylinux1_x86_64.whl
pyarmor.cli.core-3.2.8-cp38-none-manylinux1_x86_64.whl
pyarmor-regcode-6000.txt

$ python3 --version
Python 3.8.10

$ pip install pyarmor.cli.core-3.2.8-cp38-none-manylinux1_x86_64.whl
$ pip install pyarmor-8.2.8.tar.gz
$ pyarmor reg -p btarmor pyarmor-regcode-6000.txt
...
Please backup regfile "pyarmor-regfile-6000.zip" carefully, and use this file for subsequent registration
...

$ pyarmor reg -g 2 pyarmor-regfile-6000.zip
...
INFO     write registeration file "pyarmor-device-regfile-6000.2.zip"
INFO     please copy deivce regfile to offline device and run
INFO         pyarmor reg pyarmor-device-regfile-6000.2.zip
INFO     The device regfile has been generated successfully

$ python3 -m pyarmor.cli.docker pyarmor-device-regfile-6000.2.zip
2023-06-24 09:43:14,939: work path: /root/.pyarmor/docker
2023-06-24 09:43:14,940: register "pyarmor-device-regfile-6000.2.zip"
2023-06-24 09:43:15,016: listen docker auth request on 172.17.0.1:29092
```

**Log in cloud server by another console to start docker container (official image python)**
```
$ docker run -it --add-host=host.docker.internal:host-gateway python bash

root@86b180b28a50:/# python --version
Python 3.11.4
root@86b180b28a50:/# 
```

**Log in cloud server by third console to copy files to docker container**
```
$ docker cp pyarmor-8.2.8.tar.gz 86b180b28a50:/
$ docker cp pyarmor.cli.core-3.2.8-cp311-none-manylinux1_x86_64.whl 86b180b28a50:/
$ docker cp pyarmor-device-regfile-6000.2.zip 86b180b28a50:/
``` 

**Run the following commands in the docker container (second console)**
```
root@86b180b28a50:/# pip install pyarmor.cli.core-3.2.8-cp311-none-manylinux1_x86_64.whl
root@86b180b28a50:/# pip install pyarmor-8.2.8.tar.gz
root@86b180b28a50:/# pyarmor reg pyarmor-device-regfile-6000.2.zip
root@86b180b28a50:/# echo "print('hello world')" > foo.py
root@86b180b28a50:/# pyarmor gen --enable-rft foo.py
```

The test steps is not for production, it just a guide to understand how it work.

**Comment by Kathir2023** [comment]
@jondy Thanks for the steps 

I have created new ec2 ubuntu instance and tried to test sample.but getting error 

pip3 install pyarmor
pip3 install docker
 pyarmor reg -g 5 pyarmor-regfile-6033.zip 
INFO     Python 3.10.6
INFO     Pyarmor 8.2.8 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register device file ".pyarmor/group/pyarmor-group-device.5"
INFO     use group license "pyarmor-regfile-6033.zip"
INFO     send request to server
INFO     write registration file "pyarmor-device-regfile-6033.5.zip"
INFO     please copy deivce regfile to offline device and run
INFO         pyarmor reg pyarmor-device-regfile-6033.5.zip
INFO     The device regfile has been generated successfully

#error:
python3 -m pyarmor.cli.docker  pyarmor-device-regfile-6033.5.zip 
2023-06-25 01:28:15,803: work path: /home/ubuntu/.pyarmor/docker
2023-06-25 01:28:15,804: register "pyarmor-device-regfile-6033.5.zip"
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/pyarmor/venv/lib/python3.10/site-packages/pyarmor/cli/docker.py", line 153, in <module>
    main()
  File "/home/ubuntu/pyarmor/venv/lib/python3.10/site-packages/pyarmor/cli/docker.py", line 149, in main
    main_entry()
  File "/home/ubuntu/pyarmor/venv/lib/python3.10/site-packages/pyarmor/cli/docker.py", line 136, in main_entry
    host, port = get_docker_gateway(client), args.port
  File "/home/ubuntu/pyarmor/venv/lib/python3.10/site-packages/pyarmor/cli/docker.py", line 23, in get_docker_gateway
    return networks[0].attrs['IPAM']['Config'][0]['Gateway']
KeyError: 'Gateway'

**Comment by jondy** [comment]
Do you have install `apt install docker.io` in Ubuntu, and check all the network interfaces `ifconfig -a`, make sure there is docker bridge interface `docker0`

If there is docker bridge interface, apply this patch to `/home/ubuntu/pyarmor/venv/lib/python3.10/site-packages/pyarmor/cli/docker.py`
```patch
@@ -20,7 +20,12 @@ def get_docker_gateway(client):
         'type': 'builtin'
     }
     networks = client.networks.list(filters=filters)
-    return networks[0].attrs['IPAM']['Config'][0]['Gateway']
+    for iface in networks:
+        try:
+            return iface.attrs['IPAM']['Config'][0]['Gateway']
+        except Exception:
+            pass
+    return '0.0.0.0'
```

**Comment by Kathir2023** [comment]
@jondy updated changes and tried to re-run command
python3 -m pyarmor.cli.docker  pyarmor-device-regfile-6033.5.zip 
2023-06-26 06:08:01,238: work path: /home/ubuntu/.pyarmor/docker
2023-06-26 06:08:01,239: register "pyarmor-device-regfile-6033.5.zip"
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/pyarmor/venv/lib/python3.10/site-packages/pyarmor/cli/docker.py", line 158, in <module>
    main()
  File "/home/ubuntu/pyarmor/venv/lib/python3.10/site-packages/pyarmor/cli/docker.py", line 154, in main
    main_entry()
  File "/home/ubuntu/pyarmor/venv/lib/python3.10/site-packages/pyarmor/cli/docker.py", line 137, in main_entry
    register_pyarmor(ctx, args.regfile[0])
  File "/home/ubuntu/pyarmor/venv/lib/python3.10/site-packages/pyarmor/cli/docker.py", line 109, in register_pyarmor
    reg.register_regfile(regfile)
  File "/home/ubuntu/pyarmor/venv/lib/python3.10/site-packages/pyarmor/cli/register.py", line 160, in register_regfile
    hostname = '/'.join(['tokens', machid])
TypeError: sequence item 1: expected str instance, NoneType found

**Comment by jondy** [comment]
It seems machid is none, I don't know why, could you check it? Since you have generated `pyarmor-device-regfile-6033.5.zip`, it should no problem to get machine id of this machine.

**Comment by rtechencheng** [comment]
I have the similar error when I run the offline device registration `pyarmor reg pyarmor-device-regfile-6022.1.zip`:
```
Traceback (most recent call last):
  File "/home/chencheng/py39venv/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 699, in main
    main_entry(sys.argv[1:])
  File "/home/chencheng/py39venv/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 687, in main_entry
    args.func(ctx, args)
  File "/home/chencheng/py39venv/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 294, in cmd_reg
    reg.register_regfile(regfile)
  File "/home/chencheng/py39venv/lib/python3.9/site-packages/pyarmor/cli/register.py", line 160, in register_regfile
    hostname = '/'.join(['tokens', machid])
TypeError: sequence item 1: expected str instance, NoneType found
```
How to check manually which machine ID I should have?

**Comment by rtechencheng** [comment]
Same in a docker:
```
user@da0deb0f1a56: ~$ pip3 install -U pyarmor
Collecting pyarmor
  Using cached pyarmor-8.2.8-py3-none-any.whl (2.3 MB)
Collecting pyarmor.cli.core~=3.2.8
  Downloading pyarmor.cli.core-3.2.8-cp39-none-manylinux1_x86_64.whl (724 kB)
     |████████████████████████████████| 724 kB 14.1 MB/s
Installing collected packages: pyarmor.cli.core, pyarmor
Successfully installed pyarmor-8.2.8 pyarmor.cli.core-3.2.8
user@da0deb0f1a56: ~$ pyarmor reg pyarmor-device-regfile-6022.1.zip
INFO     Python 3.9.2
INFO     Pyarmor 8.2.8 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "pyarmor-device-regfile-6022.1.zip"
ERROR    sequence item 1: expected str instance, NoneType found
user@da0deb0f1a56: ~$ cat pyarmor.error.log
57 MainProcess 2023-06-27 18:08:03,803
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 699, in main
    main_entry(sys.argv[1:])
  File "/home/user/.local/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 687, in main_entry
    args.func(ctx, args)
  File "/home/user/.local/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 294, in cmd_reg
    reg.register_regfile(regfile)
  File "/home/user/.local/lib/python3.9/site-packages/pyarmor/cli/register.py", line 160, in register_regfile
    hostname = '/'.join(['tokens', machid])
TypeError: sequence item 1: expected str instance, NoneType found
```

**Comment by jondy** [comment]
Got machine id by this script:
```python
from pyarmor.cli.core import Pytransform3
print('machine id is', Pytransform3.get_hd_info(11))
```

But in docker container, it doesn't get local machine id, but send request to host, and get host machine id.

If host doesn't start `python -m pyarmor.cli.docker`, the machine id is None.

**Comment by Kathir2023** [comment]
@jondy  I have tested manual steps what you have mentioned which is working fine. but tried to create image  facing issue.
# docker build steps
Dockerfile
FROM python
RUN pip install pyarmor.cli.core
RUN pip install pyarmor 
WORKDIR /app
COPY . .
RUN pyarmor reg pyarmor-device-regfile-6033.6.zip

## docker build -t base .
Sending build context to Docker daemon  6.656kB
Step 1/6 : FROM python
 ---> 09b1cac8826b
Step 2/6 : RUN pip install pyarmor.cli.core
 ---> Running in 2b197bcc4259
Collecting pyarmor.cli.core
  Downloading pyarmor.cli.core-3.2.8-cp311-none-manylinux1_x86_64.whl (711 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 711.9/711.9 kB 7.3 MB/s eta 0:00:00
Installing collected packages: pyarmor.cli.core
Successfully installed pyarmor.cli.core-3.2.8
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container 2b197bcc4259
 ---> 197a69a11b89
Step 3/6 : RUN pip install pyarmor
 ---> Running in 484d2d3ccefe
Collecting pyarmor
  Downloading pyarmor-8.2.8-py3-none-any.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 10.6 MB/s eta 0:00:00
Requirement already satisfied: pyarmor.cli.core~=3.2.8 in /usr/local/lib/python3.11/site-packages (from pyarmor) (3.2.8)
Installing collected packages: pyarmor
Successfully installed pyarmor-8.2.8
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container 484d2d3ccefe
 ---> dee894b8e51e
Step 4/6 : WORKDIR /app
 ---> Running in 976c2c0b5304
Removing intermediate container 976c2c0b5304
 ---> fac55d9d30cb
Step 5/6 : COPY . .
 ---> 2e59c0fa8549
Step 6/6 : RUN pyarmor reg pyarmor-device-regfile-6033.6.zip
 ---> Running in f75bf26b6060
INFO     Python 3.11.4
INFO     Pyarmor 8.2.8 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "pyarmor-device-regfile-6033.6.zip"
ERROR    sequence item 1: expected str instance, NoneType found
The command '/bin/sh -c pyarmor reg pyarmor-device-regfile-6033.6.zip' returned a non-zero code: 2
ubuntu@ip-172-31-40-30:~/workspace/docker$ ls -la
total 16
drwxrwxr-x 2 ubuntu ubuntu 4096 Jun 30 04:31 .
drwxrwxr-x 5 ubuntu ubuntu 4096 Jun 30 04:31 ..
-rw-rw-r-- 1 ubuntu ubuntu  141 Jun 30 04:32 Dockerfile
-rw-rw-r-- 1 ubuntu ubuntu 4040 Jun 30 03:23 pyarmor-device-regfile-6033.6.zip
ubuntu@ip-172-31-40-30:~/workspace/docker$ 

# Docker cli running  in the background 
python3 -m pyarmor.cli.docker pyarmor-device-regfile-6033.6.zip 
2023-06-30 03:33:06,911: work path: /home/ubuntu/.pyarmor/docker
2023-06-30 03:33:06,912: register "pyarmor-device-regfile-6033.6.zip"
2023-06-30 03:33:06,967: listen docker auth request on 0.0.0.0:29092
2023-06-30 03:37:37,835: receive request from ('172.17.0.2', 33656)
2023-06-30 03:37:37,835: send auth result to ('172.17.0.2', 33656)
2023-06-30 03:38:17,300: receive request from ('172.17.0.2', 57760)
2023-06-30 03:38:17,312: send auth result to ('172.17.0.2', 57760)
2023-06-30 03:38:17,317: receive request from ('172.17.0.2', 57764)
2023-06-30 03:38:17,327: send auth result to ('172.17.0.2', 57764)
2023-06-30 03:38:17,344: receive request from ('172.17.0.2', 57770)
2023-06-30 03:38:17,355: send auth result to ('172.17.0.2', 57770)
2023-06-30 03:38:17,359: receive request from ('172.17.0.2', 57774)
2023-06-30 03:38:17,369: send auth result to ('172.17.0.2', 57774)
2023-06-30 03:38:17,382: receive request from ('172.17.0.2', 57778)
2023-06-30 03:38:17,392: send auth result to ('172.17.0.2', 57778)
2023-06-30 03:38:17,400: receive request from ('172.17.0.2', 57790)
2023-06-30 03:38:17,410: send auth result to ('172.17.0.2', 57790)

**Comment by jondy** [comment]
Could you replace `docker.py` with latest source in the GitHub, and run it with `--debug` to check the server request and response?
```
python -m pyarmor.cli.docker --debug pyarmor-device-regfile-6033.6.zip
```

A little hint, in docker container install `pyarmor.cli` instead `pyarmor` could decrease download size significantly
```
RUN pip install pyarmor.cli
```

**Comment by Kathir2023** [comment]
@jondy  getting error msg but i have file in the path

python3 -m pyarmor.cli.docker --debug pyarmor-device-regfile
-6033.6.zip
2023-06-30 05:42:44,929: work path: /home/ubuntu/.pyarmor/docker
2023-06-30 05:42:44,931: register "pyarmor-device-regfile-6033.6.zip"
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarmor/cli/docker.py", line 148, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarmor/cli/docker.py", line 107, in main
    main_entry()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarmor/cli/docker.py", line 90, in main_entry
    register_pyarmor(ctx, args.regfile[0])
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarmor/cli/docker.py", line 62, in register_pyarmor
    reg.register_regfile(regfile)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarmor/cli/register.py", line 150, in register_regfile
    with ZipFile(regfile, 'r') as f:
  File "/usr/lib/python3.10/zipfile.py", line 1249, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'pyarmor-device-regfile-6033.6.zip'
ubuntu@ip-172-31-40-30:~/workspace$ ls
docker  pyarmor-8.2.8  pyarmor-regfile-6033.zip  v8.2.8.tar.gz

**Comment by Kathir2023** [comment]
@jondy  updated changes in the docker.py executed 
python3 -m pyarmor.cli.docker --debug pyarmor-device-regfile-6033.6.zip
2023-06-30 05:55:58,075: work path: /home/ubuntu/.pyarmor/docker
2023-06-30 05:55:58,077: register "pyarmor-device-regfile-6033.6.zip"
2023-06-30 05:55:58,082: extracting license.lic
2023-06-30 05:55:58,082: extracting .pyarmor_capsule.zip
2023-06-30 05:55:58,127: extracting tokens/b7bf68c77df3e3b4e1635051751afcf14
2023-06-30 05:55:58,128: machine id: b'b7bf68c77df3e3b4e1635051751afcf14'
2023-06-30 05:55:58,128: listen container auth request on 0.0.0.0:29092

# Changed as per suggestion 
docker build -t base .
Sending build context to Docker daemon  6.656kB
Step 1/6 : FROM python
 ---> 09b1cac8826b
Step 2/6 : RUN pip install pyarmor.cli
 ---> Running in decb2dee44b0
Collecting pyarmor.cli
  Downloading pyarmor.cli-8.2.8-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.6/46.6 kB 3.2 MB/s eta 0:00:00
Collecting pyarmor.cli.core~=3.2.8 (from pyarmor.cli)
  Downloading pyarmor.cli.core-3.2.8-cp311-none-manylinux1_x86_64.whl (711 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 711.9/711.9 kB 28.1 MB/s eta 0:00:00
Installing collected packages: pyarmor.cli.core, pyarmor.cli
ERROR: For req: pyarmor.cli. Invalid script entry point: <ExportEntry pyarmor = pyarmor.cli:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
The command '/bin/sh -c pip install pyarmor.cli' returned a non-zero code: 1
# old dockerfile
ubuntu@ip-172-31-40-30:~/workspace/docker$ docker build -t base .
Sending build context to Docker daemon  6.656kB
Step 1/6 : FROM python
 ---> 09b1cac8826b
Step 2/6 : RUN pip install pyarmor.cli.core
 ---> Using cache
 ---> 197a69a11b89
Step 3/6 : RUN pip install pyarmor
 ---> Using cache
 ---> dee894b8e51e
Step 4/6 : WORKDIR /app
 ---> Using cache
 ---> fac55d9d30cb
Step 5/6 : COPY . .
 ---> Using cache
 ---> 2e59c0fa8549
Step 6/6 : RUN pyarmor reg pyarmor-device-regfile-6033.6.zip
 ---> Running in d49eaa7eaed8
INFO     Python 3.11.4
INFO     Pyarmor 8.2.8 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "pyarmor-device-regfile-6033.6.zip"
ERROR    sequence item 1: expected str instance, NoneType found
The command '/bin/sh -c pyarmor reg pyarmor-device-regfile-6033.6.zip' returned a non-zero code: 2

**Comment by jondy** [comment]
After check the docker documentation about [docker build](https://docs.docker.com/engine/reference/commandline/build/), I think the problem is this option `--add-host=host.docker.internal:host-gateway` is missed. 

In a short word, the container must be able to connect to docker host `host.docker.internal` anyway

**Comment by Kathir2023** [comment]
@jondy  how to solve this issue

**Comment by jondy** [comment]
```bash
docker build --add-host=host.docker.internal:host-gateway ...
```
