### ISSUE TITLE
[BUG] `ERROR 'int' object is not subscriptable` when using option `--period`

### ISSUE THREAD

**Issue by 17Reset** [dashingsoft/pyarmor#1340]
If I use this command：--period 1h，it will report the following error:
pyarmor gen: error: argument --period: invalid int value: '1h'.

If I use this command：--period 1，it will report the following error:
INFO     Python 3.11.4
INFO     Pyarmor 8.2.8 (group), 006040, non-profits
INFO     Platform windows.x86_64
INFO     use runtime platforms: ['windows.x86_64']
INFO     search inputs ...
INFO     find package at Test
INFO     find 1 top resources
ERROR    'int' object is not subscriptable

**Comment by jondy** [comment]
Got it, thanks. It will be fixed in next release.

**Comment by jondy** [comment]
Quick workaround by applying the related patch aabf9eccadccd111fd2047c1a7c13dbad8f8ac2e

**Comment by jondy** [comment]
Fixed it in 8.2.9
