### ISSUE TITLE
purchased pyarmor is not private

### ISSUE THREAD

**Issue by newbieh4cker** [dashingsoft/pyarmor#135]
1. purchased license.
with 'pyarmor register' command, I can see license is applied to my system.

2. bundled obfuscated script to executable file following steps from below link.
https://pyarmor.readthedocs.io/en/latest/advanced.html#bundle-obfuscated-scripts-to-one-executable-file

3. created license.lic from another computer(trial version of pyarmor is installed) 

4. copied licensel.lic from (3) to same with executable file from (2)

and it works.

I thought only trial version is private, not purchased.

**Comment by jondy** [comment]
Does the final exe work without any license.lic in the same path?

If it still works, make sure run `pyarmor pack` with option `--without-license`

**Comment by newbieh4cker** [comment]
i did pack without license option.
exe does not work without license.lic

**Comment by jondy** [comment]
How about obfuscating a simple script and run it with license.lic from another computer(trial version of pyarmor is installed)?

**Comment by newbieh4cker** [comment]
thats what i did exactly.
and exe runs good(which should not be)

**Comment by jondy** [comment]
I means obfuscating the script only like this
```
pyarmor obfuscate foo.py
cd dist/
# To be sure there is license.lic in the current path, then copy license.lic from another computer(trial version of pyarmor is installed) here 
python foo.py
```

**Comment by newbieh4cker** [comment]
same.
even obfuscated with purchased version, license from trial version works

**Comment by jondy** [comment]
Could you show the console output of `pyarmor obfuscate foo.py` here?

**Comment by newbieh4cker** [comment]
![image](https://user-images.githubusercontent.com/23703741/68360805-c4e63500-0164-11ea-8496-f62290e4aae8.png)

**Comment by newbieh4cker** [comment]
sorry, solved.

don't know why, but rebooting system fixed it....

**Comment by jondy** [comment]
Is the file `/home/gh0st/.pyarmor_capsulie.zip` same with `.pyarmro_capsule.zip` in the keyfile `pyarmor-regifle-1.zip`?

If they're really same, please send the `license.lic` generated by trial version pyarmor to my email "jondy.zhao@gmail.com".
