### ISSUE TITLE
[BUG] Pyarmor pack error

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#1359]
Hello Jondy. There is an error using pack command as refer https://pyarmor.readthedocs.io/en/stable/topic/repack.html?highlight=pack#insight-into-pack-command

I guess that it happens because i am using x86 along 3.11.x

Command and output:

```
$ C:\Users\Paulo\Desktop\New folder>pyarmor gen --pack dist/foo foo.py
INFO     Python 3.11.4
INFO     Pyarmor 8.2.9 (pro), *, *
INFO     Platform windows.x86
INFO     implicitly set output to ".pyarmor\pack\dist"
ERROR    --pack must be an executable file
```

**Comment by OndrasDEV** [comment]
I have this exact thing, anyone found a fix?

**Comment by chugunovyar** [comment]
the same questing here

```
INFO     Python 3.8.17
INFO     Pyarmor 8.3.4 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     implicitly set output to ".pyarmor/pack/dist"
ERROR    --pack must be an executable file

```

**Comment by zeroalphagit** [comment]
> the same questing here
> 
> ```
> INFO     Python 3.8.17
> INFO     Pyarmor 8.3.4 (trial), 000000, non-profits
> INFO     Platform linux.x86_64
> INFO     implicitly set output to ".pyarmor/pack/dist"
> ERROR    --pack must be an executable file
> ```

You guys aren't using the command correctly. You need to use pyinstaller (version 5 only supported as of this post) first

then you need to tell --pack the path to this .exe file pyinstaller made, so it can unpack it and fill it with the obfuscated files

EG: --pack /dist/main.exe
