### ISSUE TITLE
Unknow opcode on ppc64le

### ISSUE THREAD

**Issue by dani84bs** [dashingsoft/pyarmor#136]
Hello,
using pyarmor 5.7.0 to obfuscate a simple script for ppc64le I keep getting the exception SystemError: unknown opcode.

I'm obfuscating the code on a linux_x86_64 system using the same python interpreter version 3.6.8

Thanks in advance.

**Comment by jondy** [comment]
I got it, there is a bug for this cross platform case. I'll fix it in a few days.
It should no problem obfuscating the scripts in PPC, and run them in PPC.

**Comment by jondy** [comment]
Fix it in v5.7.1, please upgrade to latest version.
