### ISSUE TITLE
get_license_info运行错误

### ISSUE THREAD

**Issue by weblearngit** [dashingsoft/pyarmor#137]
get_license_info方法中 info['CODE'] = info[:i] 运行错误，提示：
TypeError: unhashable type: 'slice'

按逻辑模拟如下，错误一致：
![image](https://user-images.githubusercontent.com/10063515/68522892-30a6da00-02ec-11ea-9918-6150e24c5a23.png)

是否需要修改为：info['CODE'] = info['CODE'][:i]

**Comment by jondy** [comment]
是的，应该修改成为 `info['CODE'] = info['CODE'][:i]` ，已经在 github 上修正

**Comment by jondy** [comment]
Fixed in v5.7.2
