### ISSUE TITLE
plugin中的中文问题

### ISSUE THREAD

**Issue by weblearngit** [dashingsoft/pyarmor#138]
环境：windows10，python368
使用plugin方式加密脚本，plugin.py中设置了coding为utf8，同时有中文注释，
在cmd中使用pyarmor obfuscate进行加密，会出现如下错误：
    'gbk' codec can't decode byte 0x82 in position 590: illegal multibyte sequence
cmd设置字符集为utf8（命令CHCP 65001），也会出现该错误。

**Comment by jondy** [comment]
已经在 github 上修正 
https://github.com/dashingsoft/pyarmor/commit/02c627846aadb8a0d422df02528257210453d8af

**Comment by jondy** [comment]
Fixed in v5.7.2
