### ISSUE TITLE
5.7.1加密文件错误

### ISSUE THREAD

**Issue by weblearngit** [dashingsoft/pyarmor#139]
python虚拟环境安装pyarmor，安装在c:
代码在d:，加密代码时，5.7.0正常，5.7.1错误如下
![image](https://user-images.githubusercontent.com/10063515/68524686-b171d000-0304-11ea-997d-41109a70e12c.png)

**Comment by jondy** [comment]
把 pyarmor 安装目录下面的 `utils.py` 中大约 305 行
`
logging.info('Copying %s', os.path.relpath(libfile))
`
中的 `os.path.relpath` 去掉就可以了。

看来这个函数在 Windows 下面有 bug ，下一个版本会做处理

**Comment by weblearngit** [comment]
windows下指定打包linux平台的加密代码，也会出现同样的错误。
utils.py的309行，logging.info('Copying %s', os.path.relpath(filename)) 同样需要修改

**Comment by jondy** [comment]
唯二的两个地方都被你发现了 ：）昨天已经同时修改过了，晚上会发布 v5.7.2 版本的。

**Comment by jondy** [comment]
Fixed in v5.7.2
