### ISSUE TITLE
Little mistake on the docs

### ISSUE THREAD

**Issue by Tmpod** [dashingsoft/pyarmor#140]
Hey! I was reading the questions section on the docs since I was having trouble with libc.so.6 not being found on Termux and I noticed a little mishap on the last line of that page ;). It's written `payrmor` instead of `pyarmor`. I'd fix this myself but I'm far away from my PC. 
Here's the link: https://pyarmor.readthedocs.io/en/latest/questions.html#no-module-name-pytransform

**Comment by jondy** [comment]
Thank you very much, I have fixed it.

**Comment by jondy** [comment]
@Tmpod
There is no `libc.so.6` on Android platform, only static libc. 
If your android is aarch64, there is available prebuilt library. You need download it manually, refer to 
https://pyarmor.readthedocs.io/en/latest/man.html#download
