### ISSUE TITLE
windows下工程配置文件src路径导致错误

### ISSUE THREAD

**Issue by weblearngit** [dashingsoft/pyarmor#141]
python3.6.8
window环境下，使用工程加密代码，工程配置文件 .pyarmor_config 中，src使用'/'方式，会导致加密代码运行时出现错误“RuntimeError: Check restrict mode failed”。
代码不做修改，src改为“\\”方式分隔路径，加密代码会正常运行。

**Comment by jondy** [comment]
有时候要根据 `src` 来得到脚本的相对路径，而 `/` 的方式会导致得到错误的相对路径。正常情况下， 工程的 `src` 会使用 `os.path.normpath` 转换成为相应平台下面的标准路径格式，如果人工修改配置文件，也要遵循这个规范。

**Comment by jondy** [comment]
在 v5.7.2 中，对 `src` 进行了一些处理，允许是相对路径和各种不规范的格式。
