### ISSUE TITLE
[BUG] Numpy obfuscation with `--enable-bcc` raises ValueError

### ISSUE THREAD

**Issue by jacob-hansen** [dashingsoft/pyarmor#1416]
The following python script runs with no error normally, but when obfuscated, returns a ValueError. 
         pyarmor gen --enable-bcc -O {args.output_folder} -e {args.days_expiration} {temp_folder}
"""
import numpy as np
df_np = np.random.rand(630, 20)  
time_col_index__ = 5  
time_starts = np.random.rand(630)  
df_np_extended = df_np[:, time_col_index__][:, np.newaxis]
print(df_np_extended.shape)
print(time_starts.shape)
print(df_np_extended >= time_starts) # Error occurs on this line when obfuscating!!!
"""
Error: 
    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

This occurred in both pyarmor versions 8.2.7 and 8.3.1
Numpy version 1.25.2 and python 3.11.3 in both pyarmor environment as well as runtime environment. 

Unfortunately I can't even find a work around. Rest of code works great with the obfuscation, but the specific act of '>=' between two arrays does not work anymore after obfuscation. 

Pyarmor 8.3.1 (group)
Platform windows.x86_64

**Comment by jacob-hansen** [comment]
It also occurs with this type of structure of a numpy argument: 
np.array([np.sum(hist[bin_assignments == i]) for i in range(len(peaks))])

**Comment by jondy** [comment]
Does it work without `--enable-bcc`?

**Comment by jacob-hansen** [comment]
It does

**Comment by jondy** [comment]
Please ignore this module or the related functions for bcc mode, refer to
https://pyarmor.readthedocs.io/en/stable/topic/bccmode.html#ignore-module-or-function
