### ISSUE TITLE
build方法，能否增加参数，用于指定工程配置文件的名字

### ISSUE THREAD

**Issue by weblearngit** [dashingsoft/pyarmor#142]
使用工程时，可以在.pyarmor_config中对src和output做自定义修改，如果src和output都使用绝对路径，设置到本目录以外，那为什么还需要一个文件夹来存放.pyarmor_config文件。
可否在build中增加参数，指定使用的配置文件？

**Comment by jondy** [comment]
src 在 3.7.2 中已经可以使用相对路径，output 现在也是支持相对路径的，并且现在 build 也是支持指定配置文件的， 例如，最后的参数可以指定工程所在的路径:
```
pyarmor build /path/to/project
```

**Comment by weblearngit** [comment]
/path/to/project 是文件夹还是文件？我期望的是文件方式 /path/to/project.json

**Comment by jondy** [comment]
是文件夹，还不支持指定配置文件名称，晚上发布的 5.7.2 时候一起加进去。

**Comment by jondy** [comment]
请升级到 5.7.2，这个版本 `build` 命令已经允许最后一个参数是任意的合法工程 `.json` 文件，其他工程命令 `config`, `info` 也同时支持这种方式。
