### ISSUE TITLE
[BUG] can't exclude unsupported node

### ISSUE THREAD

**Issue by kr1tx** [dashingsoft/pyarmor#1421]
**command used** `pyarmor gen -e %after_month% --enable-bcc --enable-rft --enable-themida --enable-jit --mix-str --assert-import --assert-call --obf-code 2 --private --pack dist\Script.exe Script.py`

```
$ pyarmor gen -O dist --assert-call foo.py
INFO     Python 3.11.2
INFO     Pyarmor 8.3.1 (pro), 000000, non-profits(TBD)
INFO     Platform windows.x86_64
INFO     search inputs ...
INFO     find script Script.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write dist\pyarmor_runtime_000000\pyarmor_runtime.pyd
INFO     patch runtime file
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "Script"
INFO     obfuscating file Script.py
INFO     start to generate bcc code ...
```

**pyarmor.trace.log content:** 
```
trace.bcc vSender:4960:pyarmor__7.pyarmor__102 (ignored)
trace.bcc ! Script:4999:pyarmor__7.pyarmor__103 (unsupported node <ast.GeneratorExp object at 0x00000181329776D0>)
```
**Script.ruler content:**
```
[bcc]
excludes = pyarmor__103 pyarmor__102
```
The problem is that I can't exclude `pyarmor__103`, if I tried to exclude it won't be excluded
But if I tried to exclude `pyarmor__102`, it will be be shown as `(ignored)` which means it has been excluded.

Thanks in advance

**Comment by jondy** [comment]
`pyarmor__103` is ignored by bcc mode

>trace.bcc ! Script:4999:pyarmor__7.pyarmor__103 (unsupported node <ast.GeneratorExp object at 0x00000181329776D0>)

`!` means this function is not handled by bcc mode.

**Comment by kr1tx** [comment]
if it is ignored why the function behave differently?

**Comment by kr1tx** [comment]
if it is really is ignored the function does not behave any different

**Comment by kr1tx** [comment]
if i removed --enable-rft, i can exclude a function by its normal name, and it will work just fine

**Comment by jondy** [comment]
If `--enable-rft`, it's not easy to exclude bcc function exactly because the function name may be different each obfuscation.

**Comment by kr1tx** [comment]
actually function names are exactly the same each obfuscation if i did not add or remove a function or a variable. could you take a look?

**Comment by kr1tx** [comment]
Something I forgot to mention, bcc mode says `unsupported node` even tho I'm not using any of these unsupported function.
```
exec
eval
super
locals
sys._getframe
sys.exc_info
```

**Comment by kr1tx** [comment]
hello?!?!?!?!
