### ISSUE TITLE
[BUG] `bcc mode is not excluding`

### ISSUE THREAD

**Issue by Jacobharden03** [dashingsoft/pyarmor#1428]
I have never been able to get bcc mode to work on my script. I rewrote it to be 75% smaller. It crashes when I try to use it. I only need BCC mode for one function in a class. The class has an unsupported super function so I assume it skips over that. Yet it still crashes. 

I tried to exclude several functions, globally and locally and it does not exclude them in the log. Finally, I tried the includes option instead and that to did not work. It sill enabled bcc for everything.

>pyarmor cfg -p bcctest bcc:excludes + "parsedExec.__init__"
>pyarmor cfg bcc:excludes + "parsedExec.__init__"

------------------------------------------------------------
Section: bcc

Current settings
  excludes = parsedExec.__new__ __new__ parsedExec.__init__

Global settings

Local settings
  excludes = parsedExec.__new__ __new__ parsedExec.__init__

Private "bcctest" settings
  excludes = parsedExec.__init__

C:\Users\bharden\.pyarmor>pyarmor cfg -p bcctest bcc:excludes + "parsedExec.__new__"
INFO     Python 3.11.3
INFO     Pyarmor 8.2.2 (pro), 005151, AlphaMicro
INFO     Platform windows.x86_64
INFO     change option "excludes" to new value "parsedExec.__init__ parsedExec.__new__"

\.pyarmor>pyarmor -d gen --mix-str --enable-bcc --pack dist/bcctest.exe bcctest.py

Check logs:
trace.bcc            bcctest:89:buildLogo
trace.bcc            bcctest:113:is_even_hex
trace.bcc            bcctest:122:set_global_variables
trace.bcc            bcctest:138:set_WinReg
trace.bcc            bcctest:150:send_request
trace.bcc            bcctest:223:modify_string
trace.bcc            bcctest:251:ClientThread.__init__
trace.bcc            bcctest:261:ClientThread.run
trace.bcc            ! bcctest:379:parsedExec.__new__ (unsupported function "super")
trace.bcc            bcctest:386:parsedExec.__init__
trace.bcc            bcctest:391:parsedExec.initializeVars
trace.bcc            bcctest:424:parsedExec.resetVars
trace.bcc            bcctest:427:parsedExec.parsedResponse
trace.co             bcctest:1:<module>
trace.co             bcctest:250:ClientThread
trace.co             bcctest:375:parsedExec
trace.co             bcctest:379:__new__

See:
 trace.bcc            ! bcctest:379:parsedExec.__new__ (unsupported function "super")
trace.bcc            bcctest:386:parsedExec.__init__

I even tried just using includes and it always shows the same on new trace log. It will not exclude anything so I can find the problem. 
Thank you!

**Comment by Jacobharden03** [comment]
What options will work with bcc mode. The docs are not clear. I also need to know what I cannot use together. It would be very helpful for the docs to have examples of combinations that are known to work well together, and ones that will never work together or seldom work together. It is a lot of trial and error. Could it be that mix-str is changing the function name and that is why bcc exclude does not work?

**Comment by jondy** [comment]
Sorry, the full configuration options will be documented in a list later.

In current version, `bcc:excludes` only works for function name, for example,
```
pyarmor cfg -p bcctest bcc:excludes + __init__ __new__ 
```

It will exclude any function or method by this name.

In next release (v8.3.4), it will support format `Class.Method` to exclude method

**Comment by jondy** [comment]
`--enable-rft` may rename function name and make `bcc:excludes` doesn't work.

`--mix-str` doesn't matter

**Comment by Jacobharden03** [comment]
Thanks. To be clear, I wanted to exclude function in a class that used super. It would take too long to refactor and test so I may need to wait and use RFT mode for now. That means hunting down what breaks in RFT mode because I lose state in my class. Will retest bcc in later pyarmor versions.

**Comment by jondy** [comment]
Fixed in 8.3.4, refer to change log and https://pyarmor.readthedocs.io/en/v8.3.4/topic/bccmode.html#ignore-module-or-function
