### ISSUE TITLE
obfuscation result not stable/reproducible with python3

### ISSUE THREAD

**Issue by uwydoc** [dashingsoft/pyarmor#143]
it seems that the order of obfuscation affect the final result.
files to be obfuscated is stored in a set, iteration order is not stable amongst different runs in python3. so even with no changed files, fresh build has unstable result(actually almost different on every invocation).

sort the files to be obfuscated solves this issue. suggest to change line 267 of [src/pyarmor.py](https://github.com/dashingsoft/pyarmor/blob/v5.7.2/src/pyarmor.py#L267) (and line 592 as well) from `for x in files` to `for x in sorted(files)`.

**Comment by jondy** [comment]
Got it, thanks

**Comment by uwydoc** [comment]
great, fixed in 5916ceb
