### ISSUE TITLE
windows平台加密Linux平台报错

### ISSUE THREAD

**Issue by GeorgeJunj** [dashingsoft/pyarmor#144]
赵老师，你好，我项目是在windows上开发的，但是需要加密后部署到Linux服务器上，但是我使用文档中的跨平台加密后在Linux服务器上运行依然报错，请问如何解决？非常感谢

**Comment by jondy** [comment]
出错的信息是什么？目标 Linux 服务器的 CPU 架构是什么，是 X86 系列的吗？
如果 PyArmor 的版本不是 5.7.2 ，请首先升级到 5.7.2
如果可能的话，尝试一下直接在服务器上加密看能否运行加密后的脚本

**Comment by jondy** [comment]
还有一个原因可能导致这个问题，如果 PyArmor 进行过升级，而人工下载的其他平台的动态库没有更新的话，会出现这个问题。这种情况目前需要在 Windows 平台下面重新下载一下 Linux 需要的动态库。

**Comment by jondy** [comment]
请升级到最新版本 v5.7.5, 原来的版本里面跨平台发布有个bug，这个版本对跨平台发布进行了重整，对平台名称进行了规范化处理，请参考
https://pyarmor.readthedocs.io/zh/latest/platforms.html#id3
https://pyarmor.readthedocs.io/zh/latest/advanced.html#id4
