### ISSUE TITLE
How to check license info in pyarmor8?

### ISSUE THREAD

**Issue by fgg1991** [dashingsoft/pyarmor#1440]
In pyarmor7, user can use
```
from pytransform import PytransformError, get_license_info, get_expired_days
	print(get_license_info())
```
to check license info.

I did not find same function in pyarmor8 documents.

There is a build-in function __pyarmor__ in 8, but it seems not to be as same as get_license_info()

**Comment by jondy** [comment]
There is no  in pyarmor 8
For expired date and user data, it could be got by  as documented
For other license information, if using outer key, all the license information could be as comments, and then parse outer key file to get license information, refer to https://pyarmor.readthedocs.io/en/stable/tutorial/customization.html#comments-within-outer-key
If not using outer key, one solution is to duplicate hardware information to user data of license, then read user data by   
In future, it may get hardware information by  with extra parameters'
