### ISSUE TITLE
Docker Container  pyarmor reg pyarmor-device-regfile-XXXX.2.zip fails

### ISSUE THREAD

**Issue by camgian** [dashingsoft/pyarmor#1442]
INFO     register "pyarmor-device-regfile-XXXX.2.zip"
ERROR    could not get docker host machine id
Traceback (most recent call last):
  File "/home/camgian/.local/lib/python3.11/site-packages/pyarmor/cli/register.py", line 194, in _get_docker_hostname
    s.connect((host, port))
socket.gaierror: [Errno -2] Name or service not known
ERROR    could not get docker host machine id

**Comment by jondy** [comment]
Refer to
http://pyarmor.readthedocs.io/en/stable/how-to/register.html#run-unlimited-dockers-in-offline-device
