### ISSUE TITLE
BCC mode raises error `not all arguments converted during string formatting`

### ISSUE THREAD

**Issue by mastrolube** [dashingsoft/pyarmor#1443]
Hello,  I was trying the bcc mode with my package.
Unfortunately, I get this error messages:
```
DEBUG    unsupported node <class 'NoneType'> at line -1
DEBUG    unknown error, please check pyarmor.error.log
ERROR    not all arguments converted during string formatting
```
I have the pyarmor.debug.log file but not the pyarmor.error.log so I can't understand what is the problem.
The trace is enabled: enable_trace = 1

Thanks, Dennis

**Comment by jondy** [comment]
It has been fixed in the pre-relese version, try to install it
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.3.5.zip
```

**Comment by mastrolube** [comment]
hello, that fixed it. 
About the pyarmor.error.log I want to say that is not in the pyarmor folder as other log files but in the main. That's why I didn't see it.
I think it should be in the same folder
Thanks
