### ISSUE TITLE
[BUG] `Cannot register pyarmor-basic 8.3.4 license (update license token ERROR)`

### ISSUE THREAD

**Issue by DragsterCZZ** [dashingsoft/pyarmor#1447]
When I try to register my pyarmor 8.3.4 license I bought "pyarmor-basic" I encouter this error
I am running the CMD as admin 
Also I cannot register the txt file since it gives me the same error "ERROR" without any explanation
I am following the guide 1 to 1, I had a pyarmor-7 license before but reinstalled / upgraded pyarmor to upgrade to the newer one
The TXT file / ZIP file is from the file I have recieved in my order confirmation email
Didnt see anybody having this issue how do I fix this?

```
C:\Users\Administrator>pyarmor register C:\Users\Administrator\Desktop\chaintest\pyarmor-regfile-4213.zip
Pyarmor 8.0+ has only 3 commands: gen, reg, cfg
Please replace pyarmor with pyarmor-7 to run old commands

C:\Users\Administrator>pyarmor reg C:\Users\Administrator\Desktop\chaintest\pyarmor-regfile-4213.zip
INFO     Python 3.10.10
INFO     Pyarmor 8.3.4 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     register "C:\Users\Administrator\Desktop\chaintest\pyarmor-regfile-4213.zip"
INFO     update license token
ERROR
```

**Comment by jondy** [comment]
Check these
1. Windows defender doesn't block `pytransform3.pyd`
2. Computer time is correct
3. Run no more than 100 devices/dockers in 24 hours
