### ISSUE TITLE
Error After Pip Install pyarmor

### ISSUE THREAD

**Issue by andizaa** [dashingsoft/pyarmor#1449]
Hi i get this error:
C:\Windows\system32>py -m pyarmor
C:\Program Files\Python\python.exe: No module named pyarmor.__main__; 'pyarmor' is a package and cannot be directly executed
C:\Windows\system32>pyarmor
'pyarmor' is not recognized as an internal or external command,
operable program or batch file.

Right after installation. I install using pip install pyarmor.
How to run pyarmor.
I'm using windows, python 3.10.5

**Comment by RockstarAdvancedGameEngine** [comment]
> Contributor

☝️🤓
