### ISSUE TITLE
[BUG] ImportError: cannot import name 'pyarmor_runtime' from 'GA.pyarmor_runtime_005291' 

### ISSUE THREAD

**Issue by mastrolube** [dashingsoft/pyarmor#1450]
Hello, I've added a hook file to my package and faced up a problem. 

If you have only a platform you can use the `from GA.pyarmor_runtime_005291 import pyarmor_runtime` without any problem, but if the lib is nested inside folders it returns that error `ImportError: cannot import name 'pyarmor_runtime' from 'GA.pyarmor_runtime_005291' `
tried with 8.3.4 and 8.3.5 beta

Thanks

**Comment by jondy** [comment]
The obfuscated scripts are normal scripts, please check the content of obfuscated scripts to fix import issues.

**Comment by mastrolube** [comment]
Hello, probably I didn't explain well the problem (sorry):
```
└───pyarmor_runtime_005291
    │   __init__.py
    │
    ├───darwin_arm64
    │       pyarmor_runtime.so
    │
    └───linux_x86_64
            pyarmor_runtime.so`
```
with more than one platform, the *.so are nested, and the import happens at __init__.py level (which is the same in both cases -one plat/more plats), so that's not the problem.

the \_\_init\_\_.py inside the pyarmor_runtine folder is **not** even obfuscated but in plain text (only when platforms are more than one!) 
So something is not working here, maybe that's related with my problem also?

I used these arguments to reproduce the problem:
`pyarmor -d gen -O dist .\GA\ -i --platform linux.x86_64 --platform darwin.arm64`

Thanks, Dennis
