### ISSUE TITLE
[BUG] Pyarmor 8.3.4 `could not get docker host machine id`

### ISSUE THREAD

**Issue by lmanik** [dashingsoft/pyarmor#1451]
Hi,

after the update I cannot register my device license (we have a group license).  

```
gitlab-runner@builder:~$ pyarmor-8 reg pyarmor-device-regfile-6052.2.zip
INFO     Python 3.11.5
INFO     Pyarmor 8.3.4 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "pyarmor-device-regfile-6052.2.zip"
ERROR    could not get docker host machine id
Traceback (most recent call last):
  File "/var/gitlab-runner/.local/lib/python3.11/site-packages/pyarmor/cli/register.py", line 194, in _get_docker_hostname
    s.connect((host, port))
socket.gaierror: [Errno -2] Name or service not known
ERROR    could not get docker host machine id
gitlab-runner@builder:~$

```

I tried to generate a new device license, but the problem is still the same.

```
ERROR    could not get docker host machine id
Traceback (most recent call last):
  File "/var/gitlab-runner/.local/lib/python3.11/site-packages/pyarmor/cli/register.py", line 194, in _get_docker_hostname
    s.connect((host, port))
socket.gaierror: [Errno -2] Name or service not known
ERROR    could not get docker host machine id
```

**Comment by jondy** [comment]
Duplicated #1446, please following the solution in #1446

But group license may not work in virtual machine.

**Comment by lmanik** [comment]
@jondy 

Thank you very much.

About the group license, if it can't be used for VM, what should I use? I plan to use it in the future in docker builder, that's what I read that goup license is ideal. So how should I proceed? I was using the original pyarmor and there was no problem with it.

**Comment by jondy** [comment]
Group license could be used to run unlimited docker containers only if docker host could work with group license.

Please refer to
https://pyarmor.readthedocs.io/en/latest/licenses.html#check-device-for-group-license

**Comment by lmanik** [comment]
@jondy 

When I was buying the license and choosing which one to use, this passage was unfortunately not there (see the picture with the version when I bought it).

https://pyarmor.readthedocs.io/en/v8.2.9/licenses.html#license-features 

What are my current options? Our build machines are VMs running docker containers. 

So which license is suitable for our use?

![image](https://github.com/dashingsoft/pyarmor/assets/33468/00ce4005-f050-49d8-8a57-e7dbed2dbc1b)

**Comment by jondy** [comment]
Running docker with same node name and mac address should get same machine id in Pyarmor 8.3.5

Besides I'm handling github issue by Github Cli, I can't see the content images.
