### ISSUE TITLE
[Bug And Question] `Custom class inheriting Process can't pickle, reporting error _pickle.PicklingError: Can't pickle <class ProcessEx xxx>: attribute lookup ProcessEx at xxx Failed.  `

### ISSUE THREAD

**Issue by Sakura4036** [dashingsoft/pyarmor#1456]
```
pyarmor gen --enable-jit --assert-call --assert-import --outer --platform windows.x86_64  Med-Pack/ -O dist
INFO     Python 3.7.12
INFO     Pyarmor 8.3.5 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     use runtime platforms: ['windows.x86_64']
```

Custom class inheriting Process can't pickle,  when process object start(`process.start()`) , reporting error: ` _pickle.PicklingError: Can't pickle <class ProcessEx xxx>: attribute lookup ProcessEx at xxx Failed. `

The ProcessEx code is as follows：
```
class ProcessEx(multiprocessing.Process):
    def __init__(self,  *args, **kwargs):
        multiprocessing.Process.__init__(self, *args, **kwargs)
        self._out_conn, self._in_conn = multiprocessing.Pipe()
        self._exception = None

    def run(self):
        try:
            multiprocessing.Process.run(self)
            self._in_conn.send(None)
        except Exception as e:
            tb = traceback.format_exc()
            self._in_conn.send((e, tb))

    @property
    def exception(self):
        if self._out_conn.poll():  # .poll(): return whether there is any data avaliable to read
            self._exception = self._out_conn.recv()
        return self._exception
```

Then I quit using the custom ProcessEx and used the native Process instead, and another Pickle error occurred: `_pickle.PicklingError: Can't pickle <function predict_and_save xx> : attribute lookup predict_and_save on xxx failed`. In this function I pass a `multiprocessing.Queue` object for process communication.  How can I fix this so that the program runs correctly?

These two errors made me realize that there seems to be a problem with pyarmor's support for `multiprocessing`, and I couldn't find an answer in the latest official documentation. So what are the precautions to be taken when using `multiprocessing` for script obfuscating with pyarmor?

**Comment by jondy** [comment]
How about call `multiprocessing.freeze_support()` before call `process`?

**Comment by pnthai88** [comment]
multiprocessing.freeze_support() not working too also tried __spec__ = None before call function.start()
