### ISSUE TITLE
[QUESTION] prevent end user by replacing *.py files with old one

### ISSUE THREAD

**Issue by mastrolube** [dashingsoft/pyarmor#1458]
Imagine I've added a security check inside one of my already existing *.py files which was not present in the old version. How can I deny replacing that file with the old one without the protection, for example? Is there a pyarmor way to bind every file to the same version?
I don't think post_runtime and post_build are the correct way to accomplish that.

I know I can do some fancy tricks in Python way. Any suggestion?
Thanks

**Comment by jondy** [comment]
Good question.

One solution is using `--bind-data` to specify release version.

For example, for first release v1.0

```
pyarmor gen --bind-data "version=1.0" /path/to/myapp
```

In next release v1.2
```
pyarmor gen --bind-data "version=1.1" /path/to/myapp
```

By changing bind data, the old obfuscated scripts can't be restored by new runtime files.

Actually the runtime key is used to restore scripts. If the content of runtime key is changed, the obfuscated scripts aren't exchange.

Please refer to man page `pyarmor gen key` to find all options used by runtime key.

In another use case, if want to replace part of old obfuscated scripts, it must use same runtime key to obfuscate new scripts.
