### ISSUE TITLE
[QUESTION] A proper way to set proxy?

### ISSUE THREAD

**Issue by NonerKao** [dashingsoft/pyarmor#1460]
Hi pyarmor Team,

For the last two weeks, we kept encountering
```
user@host:~$ pyarmor reg pyarmor-regfile-XXXX.zip
INFO     Python 3.8.0
INFO     Pyarmor 8.2.9 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "pyarmor-regfile-XXXX.zip"
INFO     update license token
ERROR    request license token faild (104)
```
and we did report the issue through email. Thanks for your response, we knew that we had to check our own firewall.

After some investigation, **our IT administration confirmed that the `pyarmor` utility did not send its request (to pyarmor.dashingsoft.com:80) to our HTTP proxy properly**. However, this is weird to us: **we already set both `HTTP_PROXY` and `http_proxy`** correctly, and those enviroment variables are used by other programs.

We already search the official documentation but didn't find anything related to proxy settings. Is there any recommendation for a proper proxy settings? Anything that we need to take care of?

Many thanks!

**Comment by jondy** [comment]
Now pyarmor really doesn't support http proxy.

Just for a test, could you verify the following code work?

```c
#include <stdio.h>
#include <stdlib.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <netdb.h>
#include <unistd.h>
#include <string.h>

static const char query_data[] =
    "GET /api/auth2/ HTTP/1.1\r\n"
    "Host: pyarmor.dashingsoft.com\r\n"
    "User-Agent: PYARMOR.Core/%s\r\n"
    "Connection: close\r\n"
    "\r\n";

int
connect_server(char *proxy_host, int proxy_port)
{
  struct sockaddr_in server_addr;
  struct hostent *host;

  host = gethostbyname(proxy_host);
  if (host == NULL) {
    perror("gethostbyname");
    return 1;
  }

  int fd = socket(AF_INET, SOCK_STREAM, 0);
  if (fd < 0) {
    perror("socket");
    return 2;
  }

  server_addr.sin_family = AF_INET;
  server_addr.sin_port = htons(proxy_port);
  server_addr.sin_addr = *(struct in_addr*)host->h_addr;
  if (connect(fd, (struct sockaddr *)&server_addr, sizeof(server_addr))) {
    perror("connect");
    return 3;
  }

  int n_written = send(fd, query_data, strlen(query_data), 0);
  if (n_written <= 0) {
    perror("send");
    close(fd);
    return 4;
  }

  {
    char buf[1024] = {};
    int inlen = recv(fd, (void*)buf, 1024, 0);
    if (inlen == 0) {
      perror("recv 0 byte");
      return 5;
    }
    else if (inlen < 0) {
      perror("recv");
      return 6;
    }
    fprintf(stderr, "Got %d bytes: %s\n", inlen, buf);
  }

  close(fd);
  return 0;
}

int main(int argc, char *argv[])
{
  char *proxy_host;
  int proxy_port;

  if (argc < 3) {
    fprintf(stderr, "missing proxy\nusage: a.out proxy-host proxy-port");
    return 1;
  }

  proxy_host = argv[1];
  proxy_port = atoi(argv[2]);

  return connect_server(proxy_host, proxy_port);
}
```

First store above code to `a.c`, then test it with your proxy
```
gcc a.c
./a.out PROXY-HOST PROXY-PORT
```

If it works, it should print server repsonse with error.

**Comment by NonerKao** [comment]
Thanks for the quick response. To summarize, the result I got was 404 Bad Request from our internal proxy server. Sorry for not disclosing the error message directly, but I am talking with our IT admin if there is any concerns.

How does the experiment help? Does it indicate that, our proxy server does not process the request properly?

**Comment by jondy** [comment]
I'm not sure. I have build a debug version only for Python 3.8 in linux x86_64 to test proxy:

https://pyarmor.dashingsoft.com/downloads/temp/proxy38/pytransform3.so

Replace the old one `/path/to/src/pyarmor/cli/core/pytransform3.so`

Make sure env var `http_proxy` is set, then try `pyarmor reg xxx.zip`, check it works or not

**Comment by jondy** [comment]
After research http proxy, I think the temporary uploaded file may not work with http proxy.

It need extra code to support http proxy (forward).

**Comment by tani-oka** [comment]
If you use a proxy, you will get a 200 OK with the following modification.

static const char query_data[] =
    "GET http://pyarmor.dashingsoft.com/api/auth2/ HTTP/1.1\r\n"
    "Host: pyarmor.dashingsoft.com\r\n"
    "User-Agent: PYARMOR.Core/%s\r\n"
    "Connection: close\r\n"
    "\r\n";

**Comment by jondy** [comment]
@tani-oka

It's great. Thanks, I'll build a debug version soon.

**Comment by jondy** [comment]
I have build a debug version in linux x86_64 to test proxy:                                                  
https://pyarmor.dashingsoft.com/downloads/temp/proxy/cp3.8/pytransform3.so

Change `cp3.8` as the exact Python version.

Replace the old one  /path/to/src/pyarmor/cli/core/pytransform3.so     
                                                                         
Make sure env var `http_proxy` is set, then try `pyarmor reg xxx.zip`, check it works or not

**Comment by NonerKao** [comment]
> I have build a debug version in linux x86_64 to test proxy: https://pyarmor.dashingsoft.com/downloads/temp/proxy/cp3.8/pytransform3.so
> 
> Change `cp3.8` as the exact Python version.
> 
> Replace the old one /path/to/src/pyarmor/cli/core/pytransform3.so
> 
> Make sure env var `http_proxy` is set, then try `pyarmor reg xxx.zip`, check it works or not

The link seems broken. I got 404 Error.

**Comment by phe599** [comment]
After replace the pytransform3.so file in ~/.local/lib/python3.8/site-packages/pyarmor/cli/core
I still got ERROR message, please check it below, thanks.

user@host:~$ pyarmor reg ./pyarmor-regfile-XXXX.zip
INFO     Python 3.8.0
INFO     Pyarmor 8.2.9 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "./pyarmor-regfile-XXXX.zip"
INFO     update license token
ERROR    'Context' object has no attribute 'core_data_1'

**Comment by jondy** [comment]
@phe599

Please upgrade Pyarmor to 8.3.5 too.

**Comment by phe599** [comment]
@jondy 
please help to check the log, thanks.

user@host:~$ pyarmor reg ./pyarmor-regfile-xxxx.zip
INFO     Python 3.8.0
INFO     Pyarmor 8.3.5 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "./pyarmor-regfile-xxxx.zip"
INFO     update license token
ERROR    request license token failed (104): Connection timed out

**Comment by phe599** [comment]
@jondy, please help to check the log, thanks.

user@host:~$ pyarmor reg ./pyarmor-regfile-xxxx.zip
INFO     Python 3.8.0
INFO     Pyarmor 8.3.5 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "./pyarmor-regfile-xxxx.zip"
INFO     update license token
ERROR    request license token failed (101): Resource temporarily unavailable

**Comment by NonerKao** [comment]
Hi,

Thanks for all the support so far. We decided to stop trying these workarounds and do manual firewall settings to make it work. My question is, does allowing 

1. pyarmor.dashingsoft.com:80
2. pyarmor.dashingsoft.com:443

sufficient? Thanks!

**Comment by jondy** [comment]
It should be OK.
