### ISSUE TITLE
[QUESTION] How can I protect my source code before uploading it to a cloud computing service?

### ISSUE THREAD

**Issue by kjl2875** [dashingsoft/pyarmor#1461]
![How can I protect my source code before uploading it to a cloud computing service](https://github.com/dashingsoft/pyarmor/assets/29188361/756252eb-c788-4152-93f0-f696b78f73fa)

I want to use it like this:

1. My source code is ready in 'a.py'.
2. Use PyArmor to create 'ap.py' from 'a.py'.
3. Upload 'ap.py' to a cloud computing service.
4. Run 'ap.py' on the cloud computing service.

Note: The key point is that 'a.py' has not been uploaded to the cloud, and 'ap.py' is a program running in the cloud.

**Comment by jondy** [comment]
Please do step `3.` and `4.` by yourself.

A simple way is shell script, or write pyarmor plugin to upload obfuscated scripts to cloud servie by yourself.

Refer to https://pyarmor.readthedocs.io/en/v8.3.4/tutorial/customization.html
