### ISSUE TITLE
[QUESTION] python call so lib but no core file is generated

### ISSUE THREAD

**Issue by ggandycong** [dashingsoft/pyarmor#1463]
pyarmor version is 6.5.5, no **gen** argument.  

pyarmor info
```shell
pyarmor version :  5.6.6
python version: 3.6.8 
os :  CentOS Linux release 8.2.2004
```

Q:   **python** call **xxx.so** library  but no core file generated when  **xxx.so** occurs  core dumped.

The code snippet is as followed: 

use **pyarmor-regfile-1** obfuscate python code.  
```python
pyarmor_code() {
    pyarmor init
    pyarmor build
}
```
python import **pytransform_bootstrap** to decrypt code.
```python
import pytransform_bootstrap

from run import main

if __name__ == '__main__':
    main()

```

**and I found it can generate core file if  don't pyarmor obfuscate  python code and without  import **pytransform_bootstrap**** 

I write demo verify whether  **import pytransform_bootstrap** can generate a core file.  as a result, the core file can be generated without  **import pytransform_bootstrap**, no core file if  **import pytransform_bootstrap** 

demo as listed follewed。

* libpy_call_c.so
```c
#include <stdlib.h>
 

int add(int a, int b) {
    return a + b;
}
 
int div(int a, int b){
    return a / b ;
}
```

* calculator.py
```python
#!/usr/bin/python
 # -*- coding: utf-8 -*-
 
def main():
    import ctypes

    lib = ctypes.cdll.LoadLibrary(./libpy_call_c.so')
    
   # 
    lib.add.argtypes = (ctypes.c_int, ctypes.c_int)
    lib.add.restype = ctypes.c_int
 
    result = lib.add(1, 2)
    print(result)
 
    #core dump
    result = lib.div(1, 0)
    print(result)
 
if __name__ == '__main__':
    main()
```

**so,  what do you think the problem is, or have any ideas to generate core?  thank you**

**Comment by jondy** [comment]
No idea. It's more likely to check linux documentation to find which configurations is related to core dump.

One possible, the obfuscated scripts may not call `lib = ctypes.cdll.LoadLibrary(./libpy_call_c.so')`

**Comment by 91Eric** [comment]
你好，我也遇到了相似的问题，我想咨询下使用这个库是否会影响生成堆栈，这个是否有做过测试，多谢

**Comment by jondy** [comment]
@91Eric

没有进行过测试，应该不会影响 core dump 的生成。

**Comment by 91Eric** [comment]
您好，您的来信我已收到.

**Comment by jondy** [comment]
Pyarmor has anti-debug for Pyarmor <= 7.7.4, it may block core dump, but i'm not sure.

As a test, obfuscate the scripts with feature `0` which no anti-debug feature, for example, in linux x86_64
```
pyarmor obfuscate --platform linux.x86_64.0 foo.py
```

**Comment by 91Eric** [comment]
十分感谢，我这边按照上述方案测试下或者使用新版本的pyarmor测试下看

**Comment by 91Eric** [comment]
本地验证，将版本升级到最近的几个版本是可以产生堆栈的，
