### ISSUE TITLE
[BUG] `Does pyarmor 8.3.6 supports Python 3.12  in FreeBSD OS? `

### ISSUE THREAD

**Issue by Soujanya459** [dashingsoft/pyarmor#1464]
Hi Jondy,

As we have to upgrade python to 3.12 for our product, we are trying out prerelease version of python 3.12, So wanted to check with you that does the latest version of pyarmor 8.3.6 supports python 3.12 and that to in FreeBSD OS??

ThankYou,
Soujanya

**Comment by jondy** [comment]
Now Python 3.12 is still not supported, it will be supported later

**Comment by Soujanya459** [comment]
As the planned release date for python 3.12 is 2nd Oct 2023, do you have rough idea so when pyarmor release will be to support that version ?

**Comment by jondy** [comment]
Refer to
https://github.com/dashingsoft/pyarmor/tree/master/ReleasePlan.md
