### ISSUE TITLE
[QUESTION] `Can't register group license`

### ISSUE THREAD

**Issue by devXpro** [dashingsoft/pyarmor#1467]
root@b1e02d61479f:/usr/local/python# **pyarmor reg -p '######' pyarmor-regcode-6086.txt** 
INFO     Python 3.11.5
INFO     Pyarmor 8.3.5 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     prepare "pyarmor-regcode-6086.txt"
INFO     query key file from server
This license registration information will be
License Type    : pyarmor-group
License To      :  ######
License Product : ######
This license is about to be used for product "######"
Are you sure to continue? (yes/no) yes
INFO     process activation file "pyarmor-regcode-6086.txt"
INFO     send request to server
INFO     write registration file "pyarmor-regfile-6086.zip"
INFO     write group information
INFO     This group license has been activated sucessfully
INFO     Import Notes:
* Please backup regfile "pyarmor-regfile-6086.zip" carefully, and use this file for subsequent registration
* Do not use "pyarmor-regcode-6086.txt" again
* Please check `pyarmor reg` in Man page for how to register Pyarmor on offline device

root@b1e02d61479f:/usr/local/feedback-api-python# **pyarmor reg -g 4**
INFO     Python 3.11.5
INFO     Pyarmor 8.3.5 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     generating device file ".pyarmor/group/pyarmor-group-device.4"
INFO     device file has been generated successfully

root@b1e02d61479f:/usr/local/feedback-api-python# **pyarmor reg -g 4 pyarmor-regfile-6086.zip** 
INFO     Python 3.11.5
INFO     Pyarmor 8.3.5 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register device file ".pyarmor/group/pyarmor-group-device.4"
INFO     use group license "pyarmor-regfile-6086.zip"
INFO     send request to server
INFO     write registration file "pyarmor-device-regfile-6086.4.zip"
INFO     please copy deivce regfile to offline device and run
INFO         pyarmor reg pyarmor-device-regfile-6086.4.zip
INFO     The device regfile has been generated successfully

root@b1e02d61479f:/usr/local/feedback-api-python# pyarmor reg pyarmor-device-regfile-6086.4.zip
INFO     Python 3.11.5
INFO     Pyarmor 8.3.5 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "pyarmor-device-regfile-6086.5.zip"
ERROR    could not get docker host machine id
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyarmor/cli/register.py", line 194, in _get_docker_hostname
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR    could not get docker host machine id

root@b1e02d61479f:/usr/local/feedback-api-python# pyarmor-auth pyarmor-device-regfile-6086.4.zip
2023-09-06 13:14:47,268: work path: /root/.pyarmor/docker
2023-09-06 13:14:47,280: register "pyarmor-device-regfile-6086.4.zip"
2023-09-06 13:14:47,342: could not get docker host machine id
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyarmor/cli/register.py", line 194, in _get_docker_hostname
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/local/bin/pyarmor-auth", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyarmor/cli/docker.py", line 107, in main
    main_entry()
  File "/usr/local/lib/python3.11/site-packages/pyarmor/cli/docker.py", line 90, in main_entry
    register_pyarmor(ctx, args.regfile[0])
  File "/usr/local/lib/python3.11/site-packages/pyarmor/cli/docker.py", line 62, in register_pyarmor
    reg.register_regfile(regfile)
  File "/usr/local/lib/python3.11/site-packages/pyarmor/cli/register.py", line 167, in register_regfile
    raise CliError('could not get docker host machine id')
pyarmor.cli.CliError: could not get docker host machine id

**Comment by devXpro** [comment]
>>> from pyarmor.cli.core.pytransform3 import get_hd_info
>>> print(get_hd_info(20))
b'ke4d5fe32ee2fbecc0ee97685408cc80b'
>>> print(get_hd_info(20))
b'kcca3cc7fc38a73d49aa513c33dce0946'
>>> print(get_hd_info(20))
b'kd08d898dde6de4ab95b354bcfa340c69'
>>> print(get_hd_info(20))

**Comment by jondy** [comment]
Hi guy, you're using pyarmor in wrong way, please read the full content of this chapter
https://pyarmor.readthedocs.io/en/latest/how-to/register.html#using-group-license

**Comment by devXpro** [comment]
How wrong it is. I do exactly according to this documentation. Exactly as written. I've done this several times without success, so g4. Look what I did above. What doesn't match what's in the documentation?
