### ISSUE TITLE
arm64 on mac require file sign

### ISSUE THREAD

**Issue by mastrolube** [dashingsoft/pyarmor#1469]
Hello! I have some trouble with mac arm64 architecture. 
Looks like that the only way to run the script on arm64 is to force codesign. 
`codesign --force --deep --sign - <Path to  .so file>`
I've tried to disable protections with `sudo spctl --master-disable` but it has no effect.
The problem of signing the so file is that it will change it and the checks in the hooks will fail for that reason.
Mac M1 is also capable of running intel arch code, but in that case you will have an error with gettext which is installed as arm Lib. 
`/usr/lib/libintl.8.dylib' (no such file), '/opt/homebrew/Cellar/gettext/0.21.1/lib/libintl.8.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))`
I didn't go any further with that path.. Maybe you can find the correct file of gettext, but probably you will have other files to change. 

Am I missing something? Any subversion?
Thanks!

**Comment by jondy** [comment]
First of all, please report Pyarmor version as the template.

In the latest version, Pyarmor should sign the .so by default. If there is special requirement, you can write `post_runtime` plugin to sign it by yourself.

If you'd like to use intel binary, use option `--platform darwin.x86_64`

All of these are documentation, please check the documentation in details.

**Comment by mastrolube** [comment]
Sorry, let me add some additional informations.

I am using pyarmor 8.3.5 pro under windows (x86_64).
I compile from here to Linux, Windows and Mac

With mac M1 arm64 I have that problem, maybe the sign you're talking about happens only if you're compiling from the same arch (I don't have a mac)?
I already know about pre post hooks, actually I'm using them for prevent dll injection but if the end user has to sign by himself the .so file, the .so will change and it won't start.

**Comment by jondy** [comment]
It may not work cross-platform obfuscating for darwin arm64.

Pyarmor need command line tool `codesign` which is builtin in MacOS.

If cross-platform, please code sign `pyarmor_runtime.so` for darwin arm64 manually.
