### ISSUE TITLE
Does PyArmor not support the mutilprocessing module?

### ISSUE THREAD

**Issue by 17Reset** [dashingsoft/pyarmor#1471]
When I obfuscate my PyQt6 project with pyarmor, the part of the project that uses multiprocessing will be killed automatically, can this be solved?

**Comment by jondy** [comment]
Try to call `multiprocessing.freeze_support()`  before call `process`

**Comment by 17Reset** [comment]
> Try to call `multiprocessing.freeze_support()` before call `process`

This method will solve the problem of the process starting a new window, but pyarmor's mode will allow the process to terminate itself abruptly.

**Comment by jondy** [comment]
No idea. If possible, please provide a simple script to reproduce it.

**Comment by 17Reset** [comment]
> No idea. If possible, please provide a simple script to reproduce it.

If obfuscation mode is used it is possible to get an error: --enable-,as long as it is not used, there is no error. The project is just using simple mutilprocessing.

**Comment by jondy** [comment]
You're also using third party library PyQt6.

And there is no Pyarmor version, no Python version, no platform reported.

At least in my test environment, there is no problem using the example code
```
from multiprocessing import Process
import os

def info(title):
    print(title)
    print('module name:', __name__)
    print('parent process:', os.getppid())
    print('process id:', os.getpid())

def f(name):
    info('function f')
    print('hello', name)

if __name__ == '__main__':
    info('main line')
    p = Process(target=f, args=('bob',))
    p.start()
    p.join()
```

**Comment by javrasya** [comment]
This becomes a problem when trying to pack an obfuscated script via pyintaller. When I pack without py armor, freezing works. But the obfuscated script disregards it (I guess that freezing should happen right after `if __name__ == '__main__'` line and that is not the case with the obfuscated script.
