### ISSUE TITLE
[BUGS] platform issues on mac silicon

### ISSUE THREAD

**Issue by mastrolube** [dashingsoft/pyarmor#1477]
INFO     Python 3.10.11
INFO     Pyarmor 8.3.6 (pro)
INFO     Platform darwin.aarch64

Hello, I've bought a Mac mini M2 (arm64).
There are a few problems:
1. as you can see it shows darwin.aarch64 instead of darwin.arm64 in the general info (if type `arch` on terminal I get arm64). [platforms supported](https://pyarmor.readthedocs.io/en/latest/reference/environments.html?highlight=aarch64#id14)
that's not a problem when you` pyarmor gen` without specifying any platform, but if you have more than one, the darwin.arm64 can't be found from the __init__.py, it looks for the darwin.aarch64 which doesn't exist.

2. if you specify both darwin platforms (arm64 and x86_64) it generates them as usual (I'm able to make some hook on the so files) but at the end, it deletes them and replaces them with the universal platform so file. At this point, I'm not able to pre-hook on it, cause the script is already obfuscated.

**Comment by jondy** [comment]
1. `darwin.arm64` is alias of `darwin.aarch64`, both of them should work
2. Please use `pyarmor cfg plugins` to check builtins plugin, and remove plugin `DarwinUniversalPlugin` which will create a fat universal `.so`

**Comment by mastrolube** [comment]
Hello,
well as I said it looks for aarch64 folder which doesn't exist (in the case you have more than a platform)
That can be fixed by adding that simple if statement in the init.
```
if plat == 'darwin' and mach == 'aarch64':
    mach = 'arm64'
```
I think that problem should be handled somehow.

About the universalplugin, ok you can disable it.. But don't you think moving it as **post_runtime** instead of **post_build** is a better option? 

Also, handle it in the correct way
```
class RuntimePlugin:
    @staticmethod
    def post_runtime(ctx, source, target, platform):
        example_plugin(target, platform)
```
so the **target** points to the universal plugin? (and maybe, in that case, don't process the arm64 and x86_64 .so files?)

Thanks, Dennis

**Comment by jondy** [comment]
I think both of `darwin.aarch64` and `darwin.arm64` should work, for example

```
pyarmor gen --platform linux.aarch64,darwin.arm64 foo.py
pyarmor gen --platform linux.aarch64,darwin.aarch64 foo.py
```

All the builtin plugins just are examples to show how to use plugins, you can design your own plugins and decide how to use them.
