### ISSUE TITLE
RISC-V support

### ISSUE THREAD

**Issue by Diddy42** [dashingsoft/pyarmor#1480]
Hello, Pyarmor doesn't seem to support the RISC-V architecture.

When I try to obfuscate a script on a RISC-V machine, I get the following crash:
```
pyarmor gen hello.py

INFO     Python 3.10.2
INFO     Pyarmor 8.3.7 (trial), 000000, non-profits
ERROR    local variable 'mach' referenced before assignment
```

Am I doing something wrong or is this expected, and RISC-V is just not supported?

Thanks.

**Comment by jondy** [comment]
It may not be supported, please check documentation to find all supported platforms and arches.
