### ISSUE TITLE
[BUG] `get_hd_info returns different result every time in docker, even without reboot`

### ISSUE THREAD

**Issue by devXpro** [dashingsoft/pyarmor#1481]
I installed Python and Pyarmour in a docker container.
I go inside the container and run
$ python -c"from pyarmor.cli.core.pytransform3 import get_hd_info
  print(get_hd_info(18))"
No matter how many times I run this in a row, a new line is printed every time. What am I doing wrong, I probably need to mount something else to the container to make it work. I bought a group license almost a month ago, tried to use it, made a million attempts to make it work, re-read all the closed problems that had the same errors as mine, all the problems were closed without being resolved (this is normal practice, as I understand it) , but all to no avail. I strictly do everything according to the instructions for a group license, and every time I get an invalid machine ID. I already wanted to return the money for the group license and buy a pro license, but they told me in the letter that I could not return the money for the group license. Our transition to Python 3.11 was frozen due to these problems. How can I make this work? what I should do???

**Comment by jondy** [comment]
You're using group license in wrong way.

Group license could not be used in the docker container directly, please check all the content of `using group license`

https://pyarmor.readthedocs.io/en/latest/how-to/register.html#using-group-license

Especially the section `run unlimited dockers in offline device`
