### ISSUE TITLE
[BUG] `The machine id change caused the license to become a trial version`

### ISSUE THREAD

**Issue by zssyqpgdll** [dashingsoft/pyarmor#1484]
I am using the windows system of a physical device and do not use docker. The machine code change causes the license of the original group version to be changed to the trial version. 
How should I solve this problem?

```
$ pyarmor -d reg pyarmor-device-regfile-6095.1.zip
DEBUG    group license for machines: ['tokens/i6d409f0e5bd1df35ab1c28fe1cb26d86']
DEBUG    got machine id: i41b1f5b538782f9ebcf4ec8e90a8d8e4
DEBUG    got machine id: k9c085e4bd3f718a18dc97d3f94c9a2d5
DEBUG    got machine id: g9c085e4bd3f718a18dc97d3f94c9a2d5
DEBUG    got machine id: b46015f70851edb20cebb3cb47ee0a33e
ERROR    could not get docker host machine id

```

**Comment by zssyqpgdll** [comment]
Why is there more than one machine id and is there a way to clear the machine id?

**Comment by jondy** [comment]
For compatible with old Pyarmor versions, there are many machine ids, the first char is version flag of machine id.

What's your Python version and platform (x86_64 or x86)? I'll build a debug version to print more information to check why machine id is changed.

**Comment by jondy** [comment]
By the way, if there are multiple platforms in one machine, each system should generate its own device file.

Are they same system?

**Comment by zssyqpgdll** [comment]
I'm using windows x86_64, python version 3.7.13.
All actions are implemented in one machine, one platform.

**Comment by jondy** [comment]
If they're same systems, try to download extension with corresponding Python version. For example, if using Python 3.7                                                               
  https://pyarmor.dashingsoft.com/downloads/temp/win64/cp3.7/pytransform3.pyd
                                                                     
Next check the output                                              
```                                                                   
    python3.7                                                       
    >>> from pytransform3 import get_hd_info                         
    >>> get_hd_info(18)                                              
```                                                                   
  Then reboot machine, and run the above commands and check output.  
                                                                     
  Compare the output, and report what's changed.

**Comment by zssyqpgdll** [comment]
After using the extension pack, the id still changed after the reboot, and my license became the trial version again.

![image](https://github.com/dashingsoft/pyarmor/assets/58369486/d735b371-33fd-42fc-a46d-1d943004b548)

`>>> from pyarmor.cli.core.pytransform3 import get_hd_info
>>> print(get_hd_info(18))`

pre:
b'i1c954ce0b7c2948d7d9e26b770a64d23'
after reboot:
b'i41b1f5b538782f9ebcf4ec8e90a8d8e4'

**Comment by funnydev-deanie** [comment]
I think this is a bug because your way to detect machine_id is wrong. My computer still the same, internet is still the same IP, there is no window updates, but MachineID changed? If you want a way to detect right computer identify you could contact us at ceo@funnydev.vn. It is an inconvenience for those who buy the highest package as 100 groups are gradually lost every time the MachineID changes and the created groups cannot even be deleted. The server that enabled the regcode file was even difficult to connect to and frequently had ERROR <urlopen error timed out> errors while other network connections were normal.

> If they're same systems, try to download extension with corresponding Python version. For example, if using Python 3.7 https://pyarmor.dashingsoft.com/downloads/temp/win64/cp3.7/pytransform3.pyd
> 
> Next check the output
> 
> ```
>     python3.7                                                       
>     >>> from pytransform3 import get_hd_info                         
>     >>> get_hd_info(18)                                              
> ```
> 
> Then reboot machine, and run the above commands and check output.
> 
> Compare the output, and report what's changed.

**Comment by zssyqpgdll** [comment]
How to do? I can't activate a new license every time I reboot the device, and the license has a limit on the number of offline devices.

**Comment by jondy** [comment]
Could you report what're changed of the hardware information?

If you use the downloaded `pytransform3.pyd`, it should print more information.

**Comment by jondy** [comment]
Please do not paste snapshot image, it's better to paste text directly.

**Comment by zssyqpgdll** [comment]
I did print some more information when I used the downloaded pytransform3.pyd, but the printed information was confusing.

`
>>> from pyarmor.cli.core.pytransform3 import get_hd_info
>>> print(get_hd_info(18))
01:錘*YQ          : 00ffqa0a9d2
02:,g0W迯*       : hecc5cb1e99
03:,g0W迯*       : jecc5cb1e98
04:W               : hecc5cb1e98
05:錘*YQ          : 00ff!037f.
06:輨YrQ軂迯    : hecc5cb1e9c
07:disk            : WD-WXT1EA7A0YHN
b'i55ddcd6d7cc78b41a35bf383287680d2'
>>>
`

**Comment by jondy** [comment]
It doesn't matter, just paste the output. But at least twice for 2 different machine id

**Comment by jondy** [comment]
I need check which hardware information is changed by comparing the output log.

**Comment by jondy** [comment]
This is a bug, I have found the problem. It will be fixed in next release v8.3.8

**Comment by jondy** [comment]
Fixed in v8.3.8, note that it need generate new device file for this device by Pyarmor 8.3.8

**Comment by jondy** [comment]
@BenjaminYde
Please upgrade Pyarmor to the latest v8.3.8, it fix a group license reboot doesn't work issue (if there are multiple network cards). 

Note that it need generate new device file for this device by Pyarmor 8.3.8

**Comment by BenjaminYde** [comment]
@jondy, tested with pyarmor 8.3.8 with reboot. Seems to be fixed now. Thanks! 👍

Did the following 

```bash
pip install pyarmor==8.3.8
pyarmor --version
```

Did the following twice (with reboot in between)
```bash
pyarmor reg -g 5
pyarmor reg -g 5 ./pyarmor-regfile-6054.zip
cat .pyarmor/group/pyarmor-group-device.5

pyarmor reg ./pyarmor-device-regfile-6054.5.zip
pyarmor-auth pyarmor-device-regfile-6054.5.zip
```

**Comment by BenjaminYde** [comment]
@jondy, Now I have another problem. using pyarmor 8.3.8

# Step 1: Start the pyarmor-auth on the host:

```bash
pyarmor-auth pyarmor-device-regfile-6054.5.zip
```
Works fine.

# Step 2: Activate pyarmor using the device regfile in the container:

- copied pyarmor-group-device in container
- copied pyarmor-device-regfile in container
- activate pyarmor using regfile:

```bash
pyarmor reg pyarmor-device-regfile-6054.5.zip
```

This gives the following error:

```
INFO     Python 3.10.6
INFO     Pyarmor 8.3.8 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "pyarmor-device-regfile-6054.5.zip"
ERROR    could not get docker host machine id
Traceback (most recent call last):
  File "/home/vintecc/.local/lib/python3.10/site-packages/pyarmor/cli/register.py", line 200, in _get_docker_hostname
    machid = (flag + data).decode('utf-8')
UnboundLocalError: local variable 'data' referenced before assignment
ERROR    could not get docker host machine id
```

As you can see on the following picture, the request was received (from container >> host) and send back (host >> container):
![image](https://github.com/dashingsoft/pyarmor/assets/44135938/30b2e133-dde5-40de-ac80-dadb62217158)

**Comment by BenjaminYde** [comment]
@jondy, tested with pyarmor 8.3.9

- Now i can register inside the docker container. It prints everything about the license being successfully activated.
- But now i have the problem that when i run an obfuscation command, the `pyarmor-auth` server on the host is complaining about the license not being valid?

On the host (pyarmor-auth): 
![image](https://github.com/dashingsoft/pyarmor/assets/44135938/9281899e-9481-48ca-9e62-0657830155b4)

In the container (register regfile): 
![image](https://github.com/dashingsoft/pyarmor/assets/44135938/68b177aa-c965-4dc8-bacd-35d0abbfaef5)

In the container (obfuscate pacakge):
![image](https://github.com/dashingsoft/pyarmor/assets/44135938/862ed107-9697-49eb-a799-452be0b27e75)

On the host (pyarmor-auth): 
![image](https://github.com/dashingsoft/pyarmor/assets/44135938/75b18350-8b30-45b9-8b63-500caac36d2a)

**Comment by funnydev-deanie** [comment]
I have just checked and see that it's still normal. May be just a website bug of license server and does not relate to pyarmor 8.3.9.

**Comment by BenjaminYde** [comment]
pyarmor 8.3.9 is released on pypi.org but no release has been made on this repo as well

**Comment by jondy** [comment]
@BenjaminYde

It changed a little, so it did not released in github.com

**Comment by BenjaminYde** [comment]
@jondy, do you have an idea when this would be fixed?
We want to use pyarmor group license for months but cannot because of the license issues.
We really look forward to using it.

**Comment by jondy** [comment]
@BenjaminYde

Please check #1511, maybe they're same issue. I'm researching this.

BTW, it's better to paste the log text instead image, because github cli could not show image.

**Comment by jondy** [comment]
@BenjaminYde

Sorry, it should check #1502, not 1511

**Comment by BenjaminYde** [comment]
Just curious, are there any more updates on this @jondy?

**Comment by jondy** [comment]
@BenjaminYde

Please upgrade Pyarmor to 8.4.0, and generate new device file by 8.4.0

Make sure machine id could keep same

**Comment by jondy** [comment]
@BenjaminYde

Please check issue #1542, it need extra settings if docker host is Windows or MacOS.
