### ISSUE TITLE
[Question] `Python 3.12` Support

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#1487]
Hi @jondy 👋 

With python 3.12 being released in ~12 days, are you going to add runtime support?

**Comment by jondy** [comment]
There is a plan in github home `ReleasePlan.md`

**Comment by VeNoMouS** [comment]
> There is a plan in github home `ReleasePlan.md`
> 
> It will be kicked off next month

ah yup thanks for the update 

`Release schedule: 2023-11-01 (about one month after Python 3.12.0 released)` for anyone else reading
