### ISSUE TITLE
如何动态地增加绑定设备

### ISSUE THREAD

**Issue by xiong3134** [dashingsoft/pyarmor#1489]
你好，我现在想动态地增加绑定MAC 地址，有办法吗，试了gen   -b  参数  会覆盖之前的

**Comment by jondy** [comment]
可以使用自定义的验证方式，编写自己的校验函数。

请参考文档`定制和扩展` 中的实例，绑定许可证到 docker id. 

https://pyarmor.readthedocs.io/zh/latest/tutorial/customization.html#docker

**Comment by xiong3134** [comment]
谢谢，我试试

**Comment by xiong3134** [comment]
> 可以使用自定义的验证方式，编写自己的校验函数。
> 
> 请参考文档`定制和扩展` 中的实例，绑定许可证到 docker id.
> 
> https://pyarmor.readthedocs.io/zh/latest/tutorial/customization.html#docker

谢谢，我试试
