### ISSUE TITLE
Unable to find "license.lic" when adding binary and data files.

### ISSUE THREAD

**Issue by simonsruggi** [dashingsoft/pyarmor#149]
Hello, I have this issue when compiling a .spec file on windows:
Unable to find "license.lic" when adding binary and data files. 
It works on MacOS.

**Comment by jondy** [comment]
How about packing your scripts by command `pyarmor pack` directly on windows.  Refer to
https://pyarmor.readthedocs.io/en/latest/man.html#pack

**Comment by simonsruggi** [comment]
I can't because it has a custom spec file

**Comment by jondy** [comment]
Could you show the keyword parameter `datas` as  creating class `Analysis` in the spec file?

**Comment by simonsruggi** [comment]
datas=[('license.lic', '.'), ('_pytransform.dll', '.'), ('pytransform.key', '.')]

**Comment by jondy** [comment]
Make sure there are `license.lic` in the same path with spec file. From pyarmor 5.7.0, the scripts should be obfuscated with option `--package-runtime=0`, otherwise, the runtime files will be saved in the path `pytransform`. 

Refer to https://github.com/dashingsoft/pyarmor/releases/tag/v5.7.0

**Comment by simonsruggi** [comment]
Oh ok perfect, I added license.lic in the same path with spec file and now it's working.

Btw i would like to tell you another bug I found:  sometimes on: 
pyarmor obfuscate script.py, the obfuscated script misses the 2 first lines: 
from pytransform import pyarmor_runtime
pyarmor_runtime()

so I just add them manually in order to make it work.

**Comment by jondy** [comment]
It's very strange. The first script should have both of lines, but all the others, if more than one scripts list in the command, have no these lines. Because only the first script is taken as entry script.

**Comment by simonsruggi** [comment]
Yeah I obfuscate the script.py which imports some other scripts but in the script.py, as I said, sometimes i need to add these to lines manually (both on MacOS and Windows)

**Comment by jondy** [comment]
What's the pyarmor version and the command options used to obfuscate the script?
