### ISSUE TITLE
The best way to run `python -m unittest discover` over obfuscated code

### ISSUE THREAD

**Issue by sanjok-bless** [dashingsoft/pyarmor#150]
Python 3.6.8
PyArmor Version 5.7.8

I need to run `python -m unittest discover` over obfuscated code, but get error from `__init__.py` files of each package in my project like this:
```
======================================================================
ERROR: prepro (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: prepro
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/vagrant/dist/prepro/__init__.py", line 1, in <module>
    __pyarmor__(__name__, __file__, b'\x50\x59\x41\x52\x4d\x4f\x52\x00\x00\x03\x06\x00\x33\x0d\x0d\x0a\x02\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x40\x00\x00\x00\x56\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x40\x00\x00\x00\x73\x04\x00\x00\x00\x64\x00\x53\x00\x29\x01\x4e\xa9\x00\x72\x01\x00\x00\x00\x72\x01\x00\x00\x00\x72\x01\x00\x00\x00\xfa\x0f\x3c\x66\x72\x6f\x7a\x65\x6e\x20\x70\x72\x65\x70\x72\x6f\x3e\xda\x08\x3c\x6d\x6f\x64\x75\x6c\x65\x3e\x01\x00\x00\x00\x73\x00\x00\x00\x00', 0)
NameError: name '__pyarmor__' is not defined
```

In v5.5.2 I just inserted bootstrap code to each `__init__.py` by my own, but in v5.7.8 I get error:
```
======================================================================
ERROR: prepro (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: prepro
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/vagrant/dist/prepro/__init__.py", line 3, in <module>
    __pyarmor__(__name__, __file__, b'\x50\x59\x41\x52\x4d\x4f\x52\x00\x00\x03\x06\x00\x33\x0d\x0d\x0a\x02\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x40\x00\x00\x00\x56\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x40\x00\x00\x00\x73\x04\x00\x00\x00\x64\x00\x53\x00\x29\x01\x4e\xa9\x00\x72\x01\x00\x00\x00\x72\x01\x00\x00\x00\x72\x01\x00\x00\x00\xfa\x0f\x3c\x66\x72\x6f\x7a\x65\x6e\x20\x70\x72\x65\x70\x72\x6f\x3e\xda\x08\x3c\x6d\x6f\x64\x75\x6c\x65\x3e\x01\x00\x00\x00\x73\x00\x00\x00\x00', 0)
RuntimeError: Check restrict mode failed
```

When I trying to add `prepro/__init__.py` to entry config I get following error:
```
ImportError: Failed to import test module: prepro
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/vagrant/dist/prepro/__init__.py", line 1, in <module>
    from .pytransform import pyarmor_runtime
ModuleNotFoundError: No module named 'prepro.pytransform'
```

Only when I removing the dot before pytransform import `from pytransform import pyarmor_runtime` my tests are running.

But there are few problems:
1. Even if a simple way to insert bootstrap code exists, it's hard enough and unclear in .pyarmor_config to add every `__init__.py` to entry config in case with 15 and more packages
2. Maybe you should add the opportunity to modify unittests module and insert bootstrap code there before tests discovering? The command can be like `pyarmor unittest discover`.

So, what is the best way to run `python -m unittest discover` over obfuscated code?

**Comment by jondy** [comment]
One solution is to insert bootstrap code into each `__init__.py` by this shell command:
```
cd /path/to/src
find . -name __init__.py -exec pyarmor --output /path/to/dist --src "." --no-runtime --package-runtime 2 {} \;
```
It searches all the `__init__.py` in the src path, and insert the right bootstrap code into each one. By option `--package-runtime 2`, there is no leading dot in bootstrap code.

**Comment by sanjok-bless** [comment]
I'm running 
```
find . -name __init__.py -exec pyarmor --output dist --src "." --no-runtime --package-runtime 2 {} \;
```
 and get a lot of errors:
```
usage: pyarmor [-h] [-v] [-q] [-d]  ...
pyarmor: error: argument : invalid choice: 'dist' (choose from 'obfuscate', 'o', 'licenses', 'l', 'pack', 'p', 'init', 'i', 'config', 'c', 'build', 'b', 'info', 'check', 'hdinfo', 'benchmark', 'capsule', 'register', 'download', 'runtime')
usage: pyarmor [-h] [-v] [-q] [-d]  ...
pyarmor: error: argument : invalid choice: 'dist' (choose from 'obfuscate', 'o', 'licenses', 'l', 'pack', 'p', 'init', 'i', 'config', 'c', 'build', 'b', 'info', 'check', 'hdinfo', 'benchmark', 'capsule', 'register', 'download', 'runtime')
...
```

**Comment by jondy** [comment]
Sorry,  the command `obfuscate` is missed:
```
find . -name __init__.py -exec pyarmor obfuscate --output dist --src "." --no-runtime --package-runtime 2 {} \;
```

**Comment by sanjok-bless** [comment]
Can I use my .pyarmor_config with that command? I need to ignore dist folder that is located in src folder and I have another mod's settings.

Anyway I get

**Comment by sanjok-bless** [comment]
Can I use my .pyarmor_config with that command? I need to ignore dist folder that is located in src folder and I have another mod's settings.

Anyway I get bootstrap code in my '__init__.py' files, but tests still don't run with error:
```
RuntimeError: Check restrict mode failed
```

**Comment by jondy** [comment]
First run this shell command, it will print all the `__init__.py` files separated by `,`:
```
cd /path/to/src
find . -name "__init__.py" | gawk '{ printf("%s,", $1) }'
```

Remove the last `,` in the output, then replace `ENTRY_STRING` with it in the following command to configure project:
```
pyarmor config --package-runtime 2 --entry "ENTRY_STRING"
```

Finally build project 
```
pyarmor build --force
```

**Comment by sanjok-bless** [comment]
Okey, I caught the idea and will adapt it to my needs later.

What about my proposal `pyarmor unittest discover`?

**Comment by jondy** [comment]
It suddenly occurred to me there is another solution for this case:
https://pyarmor.readthedocs.io/en/latest/advanced.html#let-python-interpreter-recognize-obfuscated-scripts-automatically

If it works to run unittest, I think it would be a better way.

**Comment by sanjok-bless** [comment]
Sorry for delay answer, I was busy another tasks.

I have problems with 
> Move the Runtime Package dist/pytransform to Python system library. For example:
> ...
> mv dist/pytransform /usr/local/lib/python3.5/dist-packages/

I moved `pytransform` to `/usr/local/lib/python3.6/dist-packages/` and got error while running any python script:
```
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.6/site.py", line 624, in <module>
    import pytransform_bootstrap
  File "/usr/lib/python3.6/pytransform_bootstrap.py", line 1, in <module>
    from pytransform import pyarmor_runtime
ModuleNotFoundError: No module named 'pytransform'
```
Python didn't see `/usr/local/lib/python3.6/dist-packages/pytransform`.

When I moved `pytransform` to `/usr/lib/python3.6/`near by `pytransform_bootstrap.py` I got error while running `pyarmor build --force`:
```
Traceback (most recent call last):
  File "/home/vagrant/venv/bin/pyarmor", line 8, in <module>
    sys.exit(main_entry())
  File "/home/vagrant/venv/lib/python3.6/site-packages/pyarmor/pyarmor.py", line 1119, in main_entry
    main(sys.argv[1:])
  File "/home/vagrant/venv/lib/python3.6/site-packages/pyarmor/pyarmor.py", line 1108, in main
    pytransform_bootstrap(capsule=DEFAULT_CAPSULE)
  File "/home/vagrant/venv/lib/python3.6/site-packages/pyarmor/utils.py", line 118, in pytransform_bootstrap
    pytransform.pyarmor_init(platid=platid)
  File "/usr/lib/python3.6/pytransform/__init__.py", line 263, in pyarmor_init
    _pytransform = _load_library(path, is_runtime, platid)
  File "/usr/lib/python3.6/pytransform/__init__.py", line 234, in _load_library
    raise PytransformError('Could not find "%s"' % filename)
pytransform.PytransformError: Could not find "/usr/lib/python3.6/pytransform/platforms/linux/x86_64/_pytransform.so"
```

When  I moved `pytransform` to my venv site-packages (https://docs.python.org/3.6/library/site.html says about site-packages) I got same error:
```
Traceback (most recent call last):
  File "/home/vagrant/venv/bin/pyarmor", line 8, in <module>
    sys.exit(main_entry())
  File "/home/vagrant/venv/lib/python3.6/site-packages/pyarmor/pyarmor.py", line 1119, in main_entry
    main(sys.argv[1:])
  File "/home/vagrant/venv/lib/python3.6/site-packages/pyarmor/pyarmor.py", line 1108, in main
    pytransform_bootstrap(capsule=DEFAULT_CAPSULE)
  File "/home/vagrant/venv/lib/python3.6/site-packages/pyarmor/utils.py", line 118, in pytransform_bootstrap
    pytransform.pyarmor_init(platid=platid)
  File "/home/vagrant/venv/lib/python3.6/site-packages/pytransform/__init__.py", line 263, in pyarmor_init
    _pytransform = _load_library(path, is_runtime, platid)
  File "/home/vagrant/venv/lib/python3.6/site-packages/pytransform/__init__.py", line 234, in _load_library
    raise PytransformError('Could not find "%s"' % filename)
pytransform.PytransformError: Could not find "/home/vagrant/venv/lib/python3.6/site-packages/pytransform/platforms/linux/x86_64/_pytransform.so"
```

**Comment by jondy** [comment]
1. Remove `pytransform_bootstrap.py` and `pytranform` from `/usr/lib/python3.6`, and obfuscate your scripts in system python.

2. Move `pytransform_bootstrap.py` and `pytransform` to your venv python, and run obfuscated scripts in venv python.

Note that it's only applied to run the obfuscated scripts, the command `pyarmor` doesn't work with it. I'll clarify the document, it's not clear.

**Comment by sanjok-bless** [comment]
Yes, when I moved both `pytranform` and `pytransform_bootstrap.py` to `~/venv/lib/python3.6/site-packages/` it has worked.

But this solution does not suit me much, because it needs root privileges to edit `/usr/lib/python3.6/site.py`

**Comment by jondy** [comment]
Why to edit `/usr/lib/python3.6/site.py`, only the file `~/venv/lib/python3.6/site.py` need to be patched.

**Comment by sanjok-bless** [comment]
I haven't `~/venv/lib/python3.6/site.py` in my venv

**Comment by jondy** [comment]
As my understanding, the scripts are obfuscated by system python `/usr/bin/python3.6`, then run the obfuscated scripts in another virtual python environment, for example, `/path/to/venv`. So it's `/path/to/venv/lib/python3.6/site.py` changed. Is it that?

**Comment by sanjok-bless** [comment]
My way to create obfuscated build more complicated and I need not only to obfuscate scripts, but also do another operations with project files. So I need separate venv for that.

But the main problem is the lack of a file `/path/to/venv/lib/python3.6/site.py`. There is `site.py` only in `/usr/lib/python3.6/`. So, I can't patch `/path/to/venv/lib/python3.6/site.py`, it doesn't exist.

**Comment by sanjok-bless** [comment]
I need to run tests only after create build. After that I remove test files and end user will take build without tests.

**Comment by jondy** [comment]
Do not obfuscate the test scripts, and patch  `/path/to/venv/lib/python3.6/unittest/__init__.py`, insert one line: 
```
import pytransform_bootstrap
```
Just take it as `site.py`, it should work.

**Comment by jondy** [comment]
And it's better to move `pytransform_bootstrap.py and `pytransform` to  `/path/to/venv/lib/python3.6/unittest`, and edit the first line in the `pytransform_bootstrap.py`:
```
from .pytransform import pyarmor_runtime
```
So it's only in the package `unittest`. 

Also patch `/path/to/venv/lib/python3.6/unittest/__init__.py` with relative import by append leading dot:
```
import .pytransform_bootstrap
```

**Comment by sanjok-bless** [comment]
Yes, I don't obfuscate test scripts.

But there is no `/path/to/venv/lib/python3.6/unittest/` as well as `site.py`, only `/usr/lib/python3.6/unittest/`. Maybe it depends of virtual environment manager... But if I just create `/path/to/venv/lib/python3.6/site.py`, python ignores it.

**Comment by jondy** [comment]
I think you may create python venv with option `--system-site-packages`. In this case, the solution is patch each unittest scripts, I document it here
https://pyarmor.readthedocs.io/en/latest/advanced.html#run-unittest-of-obfuscated-scripts

**Comment by sanjok-bless** [comment]
Eventually, I have decided to add `__init__.py` files automatically with `pyarmor config --package-runtime 2 --entry "ENTRY_STRING"`. It's more controlled and reliable way in order to run obfuscation on different workstations and environments.
