### ISSUE TITLE
[BUG] `module 'PySide6' has no attribute 'QtGui'` Why don't you reply to the customer who bought

### ISSUE THREAD

**Issue by sangnguyen09** [dashingsoft/pyarmor#1501]
pyarmor gen -O obfdist --enable-rft --mix-str --enable-jit --obf-code 2 --assert-call -r src\gui

INFO     Python 3.10.10
INFO     Pyarmor 8.3.9 (pro), 005369, NTSAutosub
INFO     Platform windows.x86_64
INFO     search inputs ...
INFO     find package at src\gui
INFO     find 1 top resources
ERROR    module 'PySide6' has no attribute 'QtGui'

Why don't you reply to the customer who bought the package and close the issue without an explanation? If not, ask for a refund.

**Comment by jondy** [comment]
Please first check
http://pyarmor.readthedocs.io/en/latest/questions.html
