### ISSUE TITLE
which file is obfuscated?

### ISSUE THREAD

**Issue by ho2921ho** [dashingsoft/pyarmor#1504]
I tried as below and it works:

" pyarmor gen -O obfdist --pack dist/floor-9 Floor-9.exe Floor-9.py "

Where are the obfuscated things stored?

Which files are obfuscated? Code or dist/floor-9 Floor-9.exe?

How can I check if my Python code has been obfuscated?

**Comment by jondy** [comment]
Please check documentation `Inside pack command`
