### ISSUE TITLE
[BUG] ttk (tkinter) + rft = module 'tkinter' has no attribute 'Style'/'Separator'

### ISSUE THREAD

**Issue by EmberLightVFX** [dashingsoft/pyarmor#1508]
```
INFO     Python 3.9.13
INFO     Pyarmor 8.3.8 (group), 006099, aesl
INFO     Platform windows.x86_64
```

I'm having some problems with using ttk together with rft but with it it seems like pyarmor is messing up tk and ttk some how.
After the obfuscation pyarmor no longer finds ttk.Style or ttk.Separator and gives the error `module 'tkinter' has no attribute 'Style'/'Separator'`.
Most other objects exist in both tk and ttk, that's what makes me suspect the mess up.

Without ttk the theming on my gui doesn't work any longer so this is quite important for me.

If I don't use rft to obfuscate my code the theme works as expected but I really need the rtf obfuscation.

I'm attaching a main.py with the gui and my build.py script so you can test it out fully yourself.
[ttk.zip](https://github.com/dashingsoft/pyarmor/files/12741644/ttk.zip)

**Comment by jondy** [comment]
Please check documentation `Inside rft mode` first to find the solution

**Comment by EmberLightVFX** [comment]
@jondy I have read the `Inside rtf mode` multiple times to try and solve this issue. I have done all the notes written in there but it still doesn't solve my problem.

The issue comes from the import part of ttk:
```
tk = __assert_armored__(b'\x83*\x02\x96\x9d\x8b\x93\xad')
ttk = __assert_armored__(b'\x83*\x02\x96\x9d\x8b\x93\xad:\xf3\xcaL')
```
If I change the `__assert_armored` part with
```
import tkinter as tk
import tkinter.ttk as ttk
```
the script works as intended.

**Comment by jondy** [comment]
It seems issue #1509 explains the reason.

Please check #1509, I'll update the progress in #1509
