### ISSUE TITLE
TypeError: exists() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by newbieh4cker** [dashingsoft/pyarmor#151]
OS : CentOS 6.10 x64
Python : 3.5.1
Pyarmor : 5.7.9

first run of `pyarmor` was good.
but after that (second, third, ~~~) type error occurs.

[first run]
![image](https://user-images.githubusercontent.com/23703741/69686802-35e59080-1104-11ea-8429-5d67613d9a8c.png)

[after first]
![image](https://user-images.githubusercontent.com/23703741/69686807-3da53500-1104-11ea-84bc-d425d7c2a722.png)

**Comment by jondy** [comment]
A quick workaround is replacing this line 68 in `/usr/lib/python3.5/site-packages/pyarmor/utils.py` with:
```
            if os.path.exists(os.path.join(libpath, x, libname)):
```
Sorry for this issue, because this part is not full test.

**Comment by newbieh4cker** [comment]
works fine, thank you
