### ISSUE TITLE
[BUG] RFT mode cast errors when importing variables/Class

### ISSUE THREAD

**Issue by lemonbu5h** [dashingsoft/pyarmor#1513]
When using the '**-enable-rft**' option, I noticed that there is no way to import variables or classes. However, the '--enable-jit' option works well without any errors.

Suppose the project structure is:

```
project/
├── main.py
├── utils/
    ├── __init__.py
    └── settings.py
```

**settings.py**
```
NUM_INTERVAL = 10
```

**main.py**

```
from utils.settings import NUM_INTERVAL

if __name__ == '__main__':
    print(NUM_INTERVAL)
```

**pyarmor command**

```
$ pyarmor gen -O dist --enable-rft .
INFO     Python 3.8.16
INFO     Pyarmor 8.3.10 (group), 006102, XXXXX
INFO     Platform linux.x86_64
INFO     search inputs ...
INFO     find package at .
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'linux.x86_64'}
INFO     write dist/pyarmor_runtime_006102/pyarmor_runtime.so
INFO     patch runtime file
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "."
INFO     obfuscating file main.py
INFO     write dist/./main.py
INFO     obfuscating file settings.py
INFO     write dist/./utils/settings.py
INFO     obfuscating file __init__.py
INFO     write dist/./utils/__init__.py
INFO     obfuscate scripts OK
```

Then run the obfuscated dist/main.py:
```
$ python3 dist/main.py
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen ..main>", line 1, in <module>
ImportError: cannot import name 'NUM_INTERVAL' from 'utils.settings' (/home/dist/utils/settings.py)
```

**Comment by jondy** [comment]
Got it, thanks. It will be fixed in next release.

**Comment by jondy** [comment]
Fixed in 8.3.11

**Comment by Sakura4036** [comment]
**加密使用的选项和命令**
```
$ pyarmor gen -O pack_test_py -r pack_test  --enable-jit --obf-code 1 --outer  --mix-str --enable-rft
```

Suppose the project structure is:

```
project/
├── main.py
├── a/
    ├── __init__.py
    └── aa.py
├── b/
    ├── __init__.py
    └── bb.py
```

aa.py:
```
aaa = "dafagfgasdf" + "⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻"

def say():
    print(aaa)
```

bb.py:
```
from a.aa import say, aaa


def sayb():
    print("bbb")
    print("from a.aa import {}".format(aaa))


def merge():
    print('merge', )
    say()
    sayb()
```

main.py:
```
from b.bb import merge

if __name__ == '__main__':
    merge()
```
---

### Error
```
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen pack_test.main>", line 6, in <module>
  File "<frozen b.bb>", line 3, in <module>
  File "<frozen pack_test.b.bb>", line 5, in <module>
ImportError: cannot import name 'aaa' from 'a'
```
### trace log:
```
trace.co             pack_test.main:1:<module>
trace.co             pack_test.__init__:1:<module>
trace.rft            pack_test.a.aa:5 (aaa->pyarmor__3)
trace.rft            pack_test.a.aa:9 (print->pyarmor__5)
trace.rft            pack_test.a.aa:9 (aaa->pyarmor__3)
trace.mix.str        pack_test.a.aa:5:'dafagfgasdf'
trace.mix.str        pack_test.a.aa:5:'⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻'
trace.co             pack_test.a.aa:1:<module>
trace.co             pack_test.a.aa:8:say
trace.rft            pack_test.b.bb:5 (from a.aa import say, aaa as pyarmor__3)
trace.rft            pack_test.b.bb:8 (sayb->pyarmor__4)
trace.rft            pack_test.b.bb:9 (print->pyarmor__5)
trace.rft            pack_test.b.bb:10 (print->pyarmor__5)
trace.rft            pack_test.b.bb:10 (aaa->pyarmor__3)
trace.rft            pack_test.b.bb:14 (print->pyarmor__5)
trace.rft            pack_test.b.bb:16 (sayb->pyarmor__4)
trace.mix.str        pack_test.b.bb:10:'from a.aa import {}'
trace.co             pack_test.b.bb:1:<module>
trace.co             pack_test.b.bb:8:pyarmor__4
trace.co             pack_test.b.bb:13:merge
```

### When I import `aaa` in the `__init__.py` of the a module:
```
from .aa import aaa, say

__all__ = [
    'aaa',
    'say'
]
```
#### new Error:
```
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen pack_test.main>", line 6, in <module>
  File "<frozen b.bb>", line 3, in <module>
  File "<frozen pack_test.b.bb>", line 5, in <module>
  File "<frozen a>", line 3, in <module>
  File "<frozen pack_test.a>", line 5, in <module>
ImportError: cannot import name 'pyarmor__3' from 'a.aa'
``` 

trace log:
```
trace.co             pack_test.main:1:<module>
trace.co             pack_test.__init__:1:<module>
trace.rft            pack_test.a.aa:9 (print->pyarmor__5)
trace.mix.str        pack_test.a.aa:5:'dafagfgasdf'
trace.mix.str        pack_test.a.aa:5:'⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻'
trace.co             pack_test.a.aa:1:<module>
trace.co             pack_test.a.aa:8:say
trace.co             pack_test.a.__init__:1:<module>
trace.rft            pack_test.b.bb:5 (from a import say, aaa as pyarmor__3)
trace.rft            pack_test.b.bb:8 (sayb->pyarmor__4)
trace.rft            pack_test.b.bb:9 (print->pyarmor__5)
trace.rft            pack_test.b.bb:10 (print->pyarmor__5)
trace.rft            pack_test.b.bb:10 (aaa->pyarmor__3)
trace.rft            pack_test.b.bb:14 (print->pyarmor__5)
trace.rft            pack_test.b.bb:16 (sayb->pyarmor__4)
trace.mix.str        pack_test.b.bb:10:'from a.aa import {}'
trace.co             pack_test.b.bb:1:<module>
trace.co             pack_test.b.bb:8:pyarmor__4
trace.co             pack_test.b.bb:13:merge
```

我查看了 [深入了解RFT](https://pyarmor.readthedocs.io/zh/latest/topic/rftmode.html) , 不是所有在模块`__init__`中定义的属性都会被保留，而不是替换吗？不太理解为什么会出现这样的问题

**Comment by Sakura4036** [comment]
> **加密使用的选项和命令**
> 
> ```
> $ pyarmor gen -O pack_test_py -r pack_test  --enable-jit --obf-code 1 --outer  --mix-str --enable-rft
> ```
> 
> Suppose the project structure is:
> 
> ```
> project/
> ├── main.py
> ├── a/
>     ├── __init__.py
>     └── aa.py
> ├── b/
>     ├── __init__.py
>     └── bb.py
> ```
> 
> aa.py:
> 
> ```
> aaa = "dafagfgasdf" + "⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻"
> 
> def say():
>     print(aaa)
> ```
> 
> bb.py:
> 
> ```
> from a.aa import say, aaa
> 
> 
> def sayb():
>     print("bbb")
>     print("from a.aa import {}".format(aaa))
> 
> 
> def merge():
>     print('merge', )
>     say()
>     sayb()
> ```
> 
> main.py:
> 
> ```
> from b.bb import merge
> 
> if __name__ == '__main__':
>     merge()
> ```
> 
> ### Error
> ```
> Traceback (most recent call last):
>   File "<frozen __main__>", line 3, in <module>
>   File "<frozen pack_test.main>", line 6, in <module>
>   File "<frozen b.bb>", line 3, in <module>
>   File "<frozen pack_test.b.bb>", line 5, in <module>
> ImportError: cannot import name 'aaa' from 'a'
> ```
> 
> ### trace log:
> ```
> trace.co             pack_test.main:1:<module>
> trace.co             pack_test.__init__:1:<module>
> trace.rft            pack_test.a.aa:5 (aaa->pyarmor__3)
> trace.rft            pack_test.a.aa:9 (print->pyarmor__5)
> trace.rft            pack_test.a.aa:9 (aaa->pyarmor__3)
> trace.mix.str        pack_test.a.aa:5:'dafagfgasdf'
> trace.mix.str        pack_test.a.aa:5:'⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻'
> trace.co             pack_test.a.aa:1:<module>
> trace.co             pack_test.a.aa:8:say
> trace.rft            pack_test.b.bb:5 (from a.aa import say, aaa as pyarmor__3)
> trace.rft            pack_test.b.bb:8 (sayb->pyarmor__4)
> trace.rft            pack_test.b.bb:9 (print->pyarmor__5)
> trace.rft            pack_test.b.bb:10 (print->pyarmor__5)
> trace.rft            pack_test.b.bb:10 (aaa->pyarmor__3)
> trace.rft            pack_test.b.bb:14 (print->pyarmor__5)
> trace.rft            pack_test.b.bb:16 (sayb->pyarmor__4)
> trace.mix.str        pack_test.b.bb:10:'from a.aa import {}'
> trace.co             pack_test.b.bb:1:<module>
> trace.co             pack_test.b.bb:8:pyarmor__4
> trace.co             pack_test.b.bb:13:merge
> ```
> 
> ### When I import `aaa` in the `__init__.py` of the a module:
> ```
> from .aa import aaa, say
> 
> __all__ = [
>     'aaa',
>     'say'
> ]
> ```
> 
> #### new Error:
> ```
> Traceback (most recent call last):
>   File "<frozen __main__>", line 3, in <module>
>   File "<frozen pack_test.main>", line 6, in <module>
>   File "<frozen b.bb>", line 3, in <module>
>   File "<frozen pack_test.b.bb>", line 5, in <module>
>   File "<frozen a>", line 3, in <module>
>   File "<frozen pack_test.a>", line 5, in <module>
> ImportError: cannot import name 'pyarmor__3' from 'a.aa'
> ```
> 
> trace log:
> 
> ```
> trace.co             pack_test.main:1:<module>
> trace.co             pack_test.__init__:1:<module>
> trace.rft            pack_test.a.aa:9 (print->pyarmor__5)
> trace.mix.str        pack_test.a.aa:5:'dafagfgasdf'
> trace.mix.str        pack_test.a.aa:5:'⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻'
> trace.co             pack_test.a.aa:1:<module>
> trace.co             pack_test.a.aa:8:say
> trace.co             pack_test.a.__init__:1:<module>
> trace.rft            pack_test.b.bb:5 (from a import say, aaa as pyarmor__3)
> trace.rft            pack_test.b.bb:8 (sayb->pyarmor__4)
> trace.rft            pack_test.b.bb:9 (print->pyarmor__5)
> trace.rft            pack_test.b.bb:10 (print->pyarmor__5)
> trace.rft            pack_test.b.bb:10 (aaa->pyarmor__3)
> trace.rft            pack_test.b.bb:14 (print->pyarmor__5)
> trace.rft            pack_test.b.bb:16 (sayb->pyarmor__4)
> trace.mix.str        pack_test.b.bb:10:'from a.aa import {}'
> trace.co             pack_test.b.bb:1:<module>
> trace.co             pack_test.b.bb:8:pyarmor__4
> trace.co             pack_test.b.bb:13:merge
> ```
> 
> 我查看了 [深入了解RFT](https://pyarmor.readthedocs.io/zh/latest/topic/rftmode.html) , 不是所有在模块`__init__`中定义的属性都会被保留，而不是替换吗？不太理解为什么会出现这样的问题

pyarmor 8.3.11,
python 3.7.12
windows 10
