### ISSUE TITLE
集团版许可证 docker 容器

### ISSUE THREAD

**Issue by hackerxiaobai** [dashingsoft/pyarmor#1518]
我需要将项目里的关键代码加密，然后打包到镜像里，将镜像发送给客户使用。有具体的文档参考吗

**Comment by jondy** [comment]
直接在开发机器上加密，然后像发布正常脚本一样发布到镜像就可以了。

请注意有的镜像可能是平台 alpine.ARCH, 而不是 linux.ARCH

请参考阅读入门文档和跨平台发布的相关内容
