### ISSUE TITLE
只有被加密的主文件可以运行

### ISSUE THREAD

**Issue by ltc1996** [dashingsoft/pyarmor#152]
同一路径有三个python文件
1. a.py
2. b.py
3. main.py

我`pyarmor obfuscate main.py`后生成的dist文件夹内有3个分别被加密的python，但无法运行前两个，显示`name "__pyarmor__" is not defined`，只有`main.py`可以运行。

我想让三个文件都被加密且可单独运行，改怎么修改操作？

**Comment by jondy** [comment]
使用 `obfuscate` 命令分别加密，例如
```
pyarmor obfuscate main.py
pyarmor obfuscate --no-runtime --exact a.py
pyarmor obfuscate --no-runtime --exact b.py
```

或者使用工程，可以指定多个 entry 
···
pyarmor init --src="." --entry "main.py,a.py,b.py"
pyarmor build
···

**Comment by ltc1996** [comment]
第二种指定多个entry的可以实现，多谢；
但第一种方法在main.py加密完后进入dist显示错误![image](https://user-images.githubusercontent.com/47720586/69773960-66dec780-11cf-11ea-8efb-f1af3b4eae74.png)
这是什么问题？

**Comment by jondy** [comment]
可能是你使用的 pyarmor 版本比较低，这个选项是 v5.7.0 里面才新增加的

**Comment by ltc1996** [comment]
> 可能是你使用的 pyarmor 版本比较低，这个选项 --no-runtime 是 v5.7.0 里面才新增加的，把这个选项去了也可以。

确实是的，不加这个选项就好了，谢谢解答

**Comment by ltc1996** [comment]
> 可能是你使用的 pyarmor 版本比较低，这个选项 --no-runtime 是 v5.7.0 里面才新增加的，把这个选项去了也可以。

确实是的，谢谢解答
