### ISSUE TITLE
[BUG] attempted to relative import with no known parent package -i

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#1520]
Hello Jondy. If you run with -i (runtime inside obfuscated scripts), the generated script try to import this as:

from .runtime import pyarmor_runtime

Causing the error:
attempted to relative import with no known parent package

The correct should be:
from runtime import pyarmor_runtime;

I am running this, you can reproduce running this also:
pyarmor gen -O dist -i mypkg

Even using, has the same problem.
pyarmor gen -O dist -i --assert-call mypkg

Following exactly https://pyarmor.readthedocs.io/en/stable/tutorial/getting-started.html?highlight=package#obfuscating-one-package

Python version: 3.11 x64
OS version: Windows 11 x64

**Comment by jondy** [comment]
Do not use `-i` in script, this is only for package.

Please check all the available options and select the right option for your case.
