### ISSUE TITLE
5.7.9第1次运行成功，第2次就不能运行，提示：”TypeError: exists() takes exactly 1 argument (3 given)“

### ISSUE THREAD

**Issue by ryanlycch** [dashingsoft/pyarmor#153]
如题所述，问题应该是utils.py中第68行导致的：
if os.path.exists(libpath, x, libname)

修改成下面的方式就可以了：
 if os.path.exists(os.path.join(libpath, x, libname))

**Comment by jondy** [comment]
github上已经修正了，下一个版本 v5.7.10 中发布。

**Comment by jondy** [comment]
v5.7.10 已经发布，这个问题已经修正。
