### ISSUE TITLE
[BUG] Pyarmor 7 showing as 8

### ISSUE THREAD

**Issue by HangingWithCMM** [dashingsoft/pyarmor#1530]
When running “pyarmor-7 --version” or “pyarmor-7 -v” it says it’s using Pyarmor 8

$ pyarmor-7 --version
PyArmor Trial Version 8.3.10
PyArmor is a command line tool used to obfuscat e python scripts, bind
obfuscated scripts to fixed machine or expire o bfuscated scripts.
For more information, refer to https://pyarmor.readthedocs.io

The bug doesn’t actually affect anything it’s just kinda weird.

**Comment by jondy** [comment]
No.

You can take `pyarmor-7` as `pyarmor-old`, the version for 7.x.x is meaningless I think.

**Comment by jondy** [comment]
And `pyarmor-7` may be removed in some future version.
