### ISSUE TITLE
pyarmor reg is not registering 8.3.11 with NEW pyarmor-regcode-XXXX.txt

### ISSUE THREAD

**Issue by camgian** [dashingsoft/pyarmor#1535]
(pyarmor)camgian@aiml-one:/camgian/etc/pyarmor$ cat README_PYARMOR_INITIAL_REGISTRATION
(pyarmor)camgian@aiml-one:/camgian/etc/pyarmor$ pyarmor reg -p Pyarmor-group pyarmor-regcode-6117.txt
INFO     Python 3.11.4
INFO     Pyarmor 8.3.11 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     prepare "pyarmor-regcode-6117.txt"
INFO     query key file from server
This license registration information will be

License Type    : pyarmor-group
License To      : Camgian Corporation
License Product : Pyarmor-group

This license is about to be used for product "Pyarmor-group"

Are you sure to continue? (yes/no) yes
INFO     process activation file "pyarmor-regcode-6117.txt"
INFO     send request to server
INFO     write registration file "pyarmor-regfile-6117.zip"
INFO     write group information
INFO     This group license has been activated sucessfully
INFO     Import Notes:

* Please backup regfile "pyarmor-regfile-6117.zip" carefully, and use this file for subsequent registration
* Do not use "pyarmor-regcode-6117.txt" again
* Please check `pyarmor reg` in Man page for how to register Pyarmor on offline device

(pyarmor)camgian@aiml-one:/camgian/etc/pyarmor$ ls -alrt
total 12
drwxrwxr-x 1 camgian camgian  164 Oct 12 19:46 ..
-rwxrwxr-x 1 camgian camgian 1794 Oct 16 12:43 pyarmor-regcode-6117.txt
drwxrwxr-x 1 camgian camgian   96 Oct 16 13:04 .
-rw-rw-r-- 1 camgian camgian 4600 Oct 16 13:04 pyarmor-regfile-6117.zip
(pyarmor)camgian@aiml-one:/camgian/etc/pyarmor$ pyarmor reg
INFO     Python 3.11.4
INFO     Pyarmor 8.3.11 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     Current license information:

License Type    : pyarmor-trial
License No.     : pyarmor-vax-000000
License To      :
License Product : non-profits

BCC Mode        : No
RFT Mode        : No

Notes
* Can't obfuscate big script and mix str

**Comment by jondy** [comment]
Please check documentation `how-to` guide about using group license.
