### ISSUE TITLE
[BUG] no found prebuilt runtime extension for platform "darwin.aarch64"

### ISSUE THREAD

**Issue by fdv1** [dashingsoft/pyarmor#1536]
Get the following error running pyarmor on a Mac m1.

```
(.venv3.7) ➜  pyarmor pyarmor gen --platform darwin.aarch64 test.py  
INFO     Python 3.7.9
INFO     Pyarmor 8.3.9 (basic), 004260, reflect
INFO     Platform darwin.x86_64
INFO     use runtime platforms: ['darwin.aarch64']
INFO     search inputs ...
INFO     find script test.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'darwin.aarch64'}
ERROR    please check all supported platforms in documentation "References"
ERROR    no found prebuilt runtime extension for platform "darwin.aarch64"

```

**Comment by fdv1** [comment]
@jondy  Do you mind shedding a bit of light on this issue (might come handy to other)? Even though it might be obvious to you, I would expect this to work according to your documentation.

**Comment by jondy** [comment]
Darwin.aarch64 only supports Python 3.9+, no plan for previous Python versons.

**Comment by fdv1** [comment]
Ah thanks for letting me know. I wish I had known that before, it would have saved a couple of hours of hair tearing!
