### ISSUE TITLE
[BUG] .pyarmor_runtime import __pyarmor__ when using Outer license

### ISSUE THREAD

**Issue by codezillars** [dashingsoft/pyarmor#1538]
Hi,

Had .pyarmor_runtime import \__pyarmor__, RuntimeError: Success (1:10915) when using outer license to run pyspark. Tested without outer license works well.

**Developer server #1** (pyarmor group)
1. pyarmor gen --outer -r src
2. pyarmor gen key -e 365
3. copy dist/pyarmor.rkey to production server.

**Production server** Pyarmor 8.3.11 (trial), NTP server working.
4. copy pyarmor.rkey to /opt/<model>/pyarmor_runtime_0x60xx
5. run spark-submit

```
23/10/18 01:21:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Traceback (most recent call last):
  File "/opt/<model>/app.py", line 1, in <module>
    import <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/opt/<model>/pyfiles/src.zip/<module>.py", line 2, in <module>
  File "/opt/<model>/pyarmor_runtime_0x60xx/__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
RuntimeError: Success (1:10915)
```
Tried placing pyarmor.rkey in runtime package and by global var doesn't work.

Appreciate assistance, thank you.

```
$ pyarmor
INFO     Python 3.9.16
INFO     Pyarmor 8.3.11 (group), 0x60xx
INFO     Platform linux.x86_64
```

**Comment by jondy** [comment]
It need internet connection to visit NTP server if using `-e`, it may be internet error.

Try to `pyarmor gen key -e .365` to generate outer license.

**Comment by jondy** [comment]
I don't think it's outer license issue, so I close it.

**Comment by codezillars** [comment]
Hi Jondy,

Thanks for your prompt reply. 

below is the output on my production server.
```
$ timedatectl
               Local time: Wed 2023-10-18 15:23:25 +08
           Universal time: Wed 2023-10-18 07:23:25 UTC
                 RTC time: Wed 2023-10-18 07:23:25
                Time zone: Asia/** (+08, +0800)
               System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```
also did a curl:

```
curl -v https://google.com
> CONNECT google.com:443 HTTP/1.1
> Host: google.com:443
> User-Agent: curl/7.76.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
```
May I know more about RuntimeError: Success (1:10915)?

Thank you.
