### ISSUE TITLE
[BUG] Can generate outer key with any machine(target machine) and run the encrypted code

### ISSUE THREAD

**Issue by mvanashri** [dashingsoft/pyarmor#1539]
Could you possibly explain this to me? I can generate an outer key on any system. What does it mean to bind a key to system or add an expiration date to one? The client or target system can build and utilize the encrypted code even if I refuse to share my key with them.

**Comment by jondy** [comment]
Please check the documentation first.

**Comment by mvanashri** [comment]
I haven't seen any documentation pertaining to restricting the target machine to generate an outer key. But if it is stated anywhere, do include an index for that.
