### ISSUE TITLE
Failed to load dynlib/dll '/tmp/_MEI6dJ4dg/_pytransform.so'. Most probably this dynlib/dll was not found when the application was frozen.

### ISSUE THREAD

**Issue by newbieh4cker** [dashingsoft/pyarmor#154]
OS : CentOS 6.10 x86
pyamor : 5.7.10
pack option : `-x " --platform centos6.x86_64"`

packing works find, but running packed binary returns error

**Comment by jondy** [comment]
In the build machine, is there this file `~/.pyarmor/platforms/centos6/x86_64/7/_pytransform.so`?

**Comment by newbieh4cker** [comment]
fixed.
I found 2 files with `find` command.
 - `~/.pyarmor/platforms/centos6/x86_64/7/_pytransform.so`
 - `~/usr/lib/python3.5/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so`

I was using second one in `.spec` file and it returned error.
But using first one works fine.
thanks
