### ISSUE TITLE
集团版注册成功后离线加密文件导致注册信息丢失

### ISSUE THREAD

**Issue by xuyingliang** [dashingsoft/pyarmor#1541]
集团版注册成功后，在线加密文件正常，pyarmor -v 显示正确的注册信息。离线加密文件就显示token问题，pyarmor -v 一查，显示没有注册。连续试了两次都这样。请问是什么原因<img width="1027" alt="image" src="https://github.com/dashingsoft/pyarmor/assets/26502558/5f62e80c-0375-40c7-807a-a83ee1e5403c">

**Comment by jondy** [comment]
请升级到 8.4.1，参考 #1542

**Comment by xuyingliang** [comment]
我是pip install pyarmor安装的，现在还是8.2.9
请问在哪里可以升级到8.4.1？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月20日(星期五) 上午6:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] 集团版注册成功后离线加密文件导致注册信息丢失 (Issue #1541)





 
请升级到 8.4.1，参考 #1542

**Comment by xuyingliang** [comment]
我是pip install pyarmor安装的，现在还是8.2.9
请问在哪里可以升级到8.4.1？


找到了，谢谢！




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月20日(星期五) 上午6:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] 集团版注册成功后离线加密文件导致注册信息丢失 (Issue #1541)





 
请升级到 8.4.1，参考 #1542
