### ISSUE TITLE
[QUESTION] SPP mode on PyArmor-7

### ISSUE THREAD

**Issue by HangingWithCMM** [dashingsoft/pyarmor#1546]
In the important notes for Pyarmor 8 it says “To use SPP mode, you must upgrade Pyarmor to version 8.0 or later.”

But I’m able to use Super Plus Mode on Pyarmor-7? 

Does this mean that it’s not actually using Super Plus Mode?

Slightly unrelated, but why is Super Plus Mode referred to as SPP instead of SPM?

**Comment by jondy** [comment]
If you check issue template, the question should be reported in the discussion, not in the issues. 

The SPP mode now still works in Pyarmor 7, because the auth service of Pyarmor for SPP mode is still up. But it may be down in future.
