### ISSUE TITLE
Can I use  -e " -n output_name"  option with  -s "spec file" ??

### ISSUE THREAD

**Issue by newbieh4cker** [dashingsoft/pyarmor#155]
I'm packing my python script to elf binary with spec file.

Here is pack command
`pyarmor pack -e " -n test123" -s "local.spec" -x " --platform centos6.x86_64" test.py`

Here is message shown while packing.
`/usr/bin/python3.5 -m PyInstaller --distpath dist -n test123 -y --add-data dist/obf/dist/pytransform.key:. --add-binary dist/obf/dist/_pytransform.*:. --add-data dist/obf/dist/license.lic:. ./test.py dist/obf/dist/test.py`

By above message, I'm sure command options went through well, but still output binary name is same as  the `name` variable  in `.spec` file.

**Comment by newbieh4cker** [comment]
Below is the part of `.spec` file containing `name` column
![image](https://user-images.githubusercontent.com/23703741/69791351-b0e39f80-1207-11ea-8e39-2381d631a0ed.png)

**Comment by newbieh4cker** [comment]
If I just remove `name=` in `.spec` file, below error occurs
![image](https://user-images.githubusercontent.com/23703741/69791517-03bd5700-1208-11ea-98cf-94bdf70fa288.png)

**Comment by jondy** [comment]
If `local.spec` isn't customized, renaming the output binary by this command:
```
pyarmor pack --clean -e " -n test123" -s "test123.spec" -x " --platform centos6.x86_64" test.py
```

**Comment by newbieh4cker** [comment]
`local.spec` is customized, cause i had to add some extra `datas`, `hiddenimports`, `runtime_hooks`

**Comment by jondy** [comment]
If '-s` is used, all the options specified by `-e` will be ignored. In this case, specify name in the `.spec` file directly. 

The other solution is to customize the spec file in the command line totally, for example,
```
pyarmor --clean -e " -n test123 --hidden-import mymod --hidden-import mymod2 --runtime-hook myhook.py --add-data config.json:. " \
              -s "test123.spec" \
              -x " --platform centos6.x86_64" foo.py
```
Note that the command `pack` will add the runtime files `license.lic`, `_pytransformso`, `pytransform.key` as data files automatically, they need not be specified in these extra options.
