### ISSUE TITLE
 [BUG] Group license / Docker - Cannot obfuscate because pyarmor-auth fails: request license token failed (3): <h1>Server Error (500)</h1>

### ISSUE THREAD

**Issue by BenjaminYde** [dashingsoft/pyarmor#1552]
@jondy, tested with pyarmor==8.3.9 and pyarmor==8.4.1

- Now i can register inside the docker container. It prints everything about the license being successfully activated.
- But now i have the problem that when i run an obfuscation command, the `pyarmor-auth` server on the host is complaining about the license not being valid?

On the host (pyarmor-auth): 
![image](https://github.com/dashingsoft/pyarmor/assets/44135938/9281899e-9481-48ca-9e62-0657830155b4)

In the container (register regfile): 
![image](https://github.com/dashingsoft/pyarmor/assets/44135938/68b177aa-c965-4dc8-bacd-35d0abbfaef5)

In the container (obfuscate pacakge):
![image](https://github.com/dashingsoft/pyarmor/assets/44135938/862ed107-9697-49eb-a799-452be0b27e75)

- The pyarmor license automatically changes to trail version after license failure.

On the host (pyarmor-auth): 
![image](https://github.com/dashingsoft/pyarmor/assets/44135938/75b18350-8b30-45b9-8b63-500caac36d2a)

_Originally posted by @BenjaminYde in https://github.com/dashingsoft/pyarmor/issues/1484#issuecomment-1736951437_

**Comment by jondy** [comment]
Please don't paste image but paste text directly.

First upgrade Pyarmor 8.4.1

And check machine id changed or not as documentation

If machine id is changed by latest version, please report Host information

If machine id keeps same, please report `pyarmor-auth -d ...`

Also please check #1542 if using Window Host

**Comment by jondy** [comment]
Note that you need test machine id in docker host 

If machine id keeps same by Pyarmor 8.4.1, please generate new device file for this docker host, just take it as new machine and do everything by Pyarmor 8.4.1 to register group license in docker host

**Comment by jondy** [comment]
Please also check the log when run `pyarmor -d reg ...`, it may help to solve problem. It's not only for Pyarmor team but also for users.

**Comment by drebbe-intrepid** [comment]
@jondy 

1. Why is this closed? Nothing has been resolved?
2. 8.4.1 resolved 500 HTTP error from version 8.4.0? Its not in the changelogs
3.  `pyarmor-auth -d ...` doesn't work:
```
pyarmor-auth reg -d pyarmor-device-regfile-6009.9.zip  
usage: pyarmor-auth [-h] [-d] regfile
pyarmor-auth: error: unrecognized arguments: pyarmor-device-regfile-6009.9.zip
```

```
yarmor --version
Pyarmor 8.4.1 (group), 006009, redacted

License Type    : pyarmor-group
License No.     : pyarmor-vax-006009
License To      : redacted
License Product : redacted

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Offline obfuscation
```

**Comment by BenjaminYde** [comment]
Nothing has been resolved??

**Comment by jondy** [comment]
> Had to generate a new one.

Just as the documentation but replace device no `1` with new one, for example, `2`. Note that the old device no `1` can't be used again:

2.9.3.2. Group device file

On each offline device, install Pyarmor 8.4+, and generate group device file. For example, on device no. 1, run this command:
```
$ pyarmor reg -g 1
```
It will generate group device file pyarmor-group-device.1.

2.9.3.3. Generating offline device regfile

Generating offline device regfile needs an internet connection, Pyarmor 8.4+, group device file pyarmor-group-device.1 and group license registration file pyarmor-regfile-xxxx.zip.

Copying group device file pyarmor-group-device.1 to initial registration device or any computer which has internet connection and registration file, this file must be saved in the path .pyarmor/group/, then run the following command to generate device regfile pyarmor-device-regfile-xxxx.1.zip:
```
$ pyarmor reg -g 1 /path/to/pyarmor-regfile-xxxx.zip
```

**Comment by BenjaminYde** [comment]
The problem is not in a new group device id.
See the steps:

1. A **new group id** has been generated on the host
2. **Device regfile has been generated** and copied inside the docker container
3. **pyarmor-auth has been started** with the new device regfile
4.1 **Obfuscating packages** inside the docker container gives an error
4.2 The same **error** is in the pyarmor-auth console: 
```
Cannot obfuscate because pyarmor-auth fails: request license token failed (3): <h1>Server Error (500)</h1>
```

**Comment by jondy** [comment]
Could you register group license in docker host and obfuscate a simple script?

Please provide full log and full command options with debug option.

For example, 
```
pyarmor -d reg xxxx.zip

pyarmor -d gen --enable-rft foo.py
```

And could you check and report the machine id is same or not in this docker host?

**Comment by jondy** [comment]
If the group license is registered successfully, it should not raise `request license token`, only non group license need request license token.

**Comment by jondy** [comment]
If you use Pyarmor group license, at least you need understand it's bind to machine id, and machine id should keep same in same machine.                                                           
  Well there are some bugs in previous versions that machine id may  
  be changed in some cases, if you generate device reg file by old   
  version, the machine id in the reg file is old and may not work.   
                                                                     
  So first of all, check whether machine id is same or not after     
  reboot                                                             
                                                                     
  I also suggest you check the issue #1542 and #1551, not only it    
  includes some hints about windows docker host, but also they're    
  good report which provide enough information to find the problem,  
  so they could be fixed quickly.

**Comment by drebbe-intrepid** [comment]
I had regenerate more licenses that were generated in 8.4.0 to 8.4.1 in order for the Server Error (500) to go away. **8.4.0 licenses are NOT compatible with 8.4.1**. This isn't documented anywhere.

**Comment by drebbe-intrepid** [comment]
nevermind... 8.4.1 isn't working either. Still getting the error:

```
INFO     Python 3.11.6
INFO     Pyarmor 8.4.1 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     implicitly set output to ".pyarmor\pack\dist"
INFO     extracting bundle "dist/main/main.exe"
INFO     search inputs ...
INFO     find package at .
INFO     find 1 top resources
ERROR    request license token failed (3): <h1>Server Error (500)</h1>
```

**Comment by drebbe-intrepid** [comment]
@jondy this issue is NOT fixed in 8.4.1

**Comment by drebbe-intrepid** [comment]
debug output:

```
> C:\python311\Scripts\pyarmor -d reg C:\pyarmor-device-regfile-6009.10.zip
INFO     Python 3.11.5
INFO     Pyarmor 8.4.1 (group), 006009, ICS-Tester
INFO     Platform windows.x86_64
DEBUG    native platform windows.amd64
DEBUG    home path: C:\Users\DFTuser\.pyarmor
INFO     register "C:\pyarmor-device-regfile-6009.10.zip"
DEBUG    extracting license.lic
DEBUG    extracting .pyarmor_capsule.zip
INFO     machine id in group license: ***
INFO     got machine id: ***
INFO     this machine id matchs group license
DEBUG    extracting tokens/***
INFO     This license registration information:

License Type    : pyarmor-group
License No.     : pyarmor-vax-006009
License To      : *****
License Product : ICS-Tester

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Offline obfuscation
```

**Comment by drebbe-intrepid** [comment]
I can't reproduce this issue right now, this seems to be time based, it started working around 5:30PM EST which is probably when majority of traffic stops. 

The specific HTML error code is 500 which is:

```The 500 Internal Server Error happens when the server encounters an unexpected condition that prevents it from fulfilling the request. This is a general message indicating that the server knows something is wrong, but can’t be more specific about the exact problem.```

I suspect the server that process the license request is getting overloaded and rejects it.

**Comment by jondy** [comment]
@drebbe-intrepid

Could you report a new issue as #1542? 

First describe all the machines (docker host / docker container) and the network configuration. It's better to paste the command output of `ifconfg` for Linux or `ipconfig` for windows

Then describe all the steps by using shell command and log and in which machine.

Do not paste image, but paste the text directly.

**Comment by jondy** [comment]
@drebbe-intrepid

Do not mask the log, especially machine id

**Comment by jondy** [comment]
Also check #1552, 

It also reports some other information and they're very helpful to fix the problem quickly

> Other things that might be of importance:                          
                                                                     
  • if I redo the registration process and rerun the command it stops
  at exactly the same point of execution                             
  • the same behavior can be observed if I run it inside of a Docker 
  container on this Linux host                                       
  • I've verified that the output of  Pytransform3.get_hd_info(22)   
  remains constant for this VM between reboots                       
  • I can successfully obfuscate this package using the same setup   
  and command from my MacBook laptop

**Comment by jondy** [comment]
Anyway, please read all the content in the section `using group license`, it need no more than 10 minutes, but may save a lot of time to face the problem

https://pyarmor.readthedocs.io/en/latest/how-to/register.html#using-group-license

About 12 hours ago, I updated it with lot of new content, especially for using group license with docker
