### ISSUE TITLE
[BUG] ERROR could not get docker host machine id Each time the PC is rebooted, the license expires and reverts to a traial license

### ISSUE THREAD

**Issue by drebbe-intrepid** [dashingsoft/pyarmor#1553]
Continuation of issue #1446 since it was locked.

```
pyarmor reg "Z:\pyarmor-device-regfile-6009.8.zip"
INFO     Python 3.11.2
INFO     Pyarmor 8.4.0 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     register "Z:\pyarmor-device-regfile-6009.8.zip"
INFO     machine id in group license: l08c249eee39dfce2f17ce4602c19b69c
INFO     got machine id: mefe656b4842405e6f6dd61ccc69ac44d
INFO     got machine id: lefe656b4842405e6f6dd61ccc69ac44d
INFO     got machine id: i311baef684e8a5c490598c4373ec014a
INFO     got machine id: k47d222353b5d193583ab44b0acf3aaf4
INFO     got machine id: g47d222353b5d193583ab44b0acf3aaf4
INFO     got machine id: b30c57db0963086f9ce95827e43261970
INFO     no machine id matchs this group license
INFO     take this machine as docker container, and connect to docker host for authentication...
INFO     could not get docker host machine id
```

**Comment by jondy** [comment]
First please upgrade Pyarmor to 8.4.1

> INFO     machine id in group license: l08c249eee39dfce2f17ce4602c19b69c 

This means you still use old device license, please generate new device license by Pyarmor v8.4.1 in this device:
```
pyarmor reg -g 2
```

Just take this device as a new machine

**Comment by drebbe-intrepid** [comment]
@jondy Where is the documentation for this stuff? I keep on generating new licenses per version since version 8.3.5 and am all over the place now...

1. Which versions need a regeneration?
2. How can I confirm this isn't an issue? I don't have trust this issue is resolved anymore. Lack of documentation doesn't help.
3. Why is this an issue to begin with?
4. Can I pay for a better version that doesn't have this strict licensing scheme? This is wasting company time and at this point I'd pay 10x to have an offline license to remove the headache of everything going on here. I don't really like being a beta tester...

I love what is offered here but the licensing makes me want to bash my head against the wall!

**Comment by jondy** [comment]
Sorry for this unconvience.

But I suggest you first read this section
https://pyarmor.readthedocs.io/en/latest/licenses.html#check-device-for-group-license
https://pyarmor.readthedocs.io/en/latest/how-to/register.html#using-group-license

Some new contents about Windows Docker Host has been added as #1542

I think you need read #1542 also, for Windows Host, it need run `pyarmor-auth` in linux VM and do some extra configuration.

I note that you also comment on #1552, please following some guides in that issue.

**Comment by jondy** [comment]
If you uses Pyarmor group license, at least you need understand it's bind to machine id, and machine id should keep same in same machine.

Well there are some bugs in previous versions that machine id may be changed in some cases, if you generate device reg file by old version, the machine id in the reg file is old and may not work. 

So first of all, check whether machine id is same or not after reboot 

I also suggest you check the issue #1542 and #1551, not only it includes some hints about windows docker host, but also they're good report which provide enough information to find the problem, so they could be fixed quickly.
