### ISSUE TITLE
pyarmor : The term 'pyarmor' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1 + pyarmor gen test.py + ~~~~~~~     + CategoryInfo          : ObjectNotFound: (pyarmor:String) [], CommandNotFoundException     + FullyQualifiedErrorId : CommandNotFoundException

### ISSUE THREAD

**Issue by Celvis-wq** [dashingsoft/pyarmor#1558]
Hello, I have been trying to use pyarmor but it unfortunately is running into an issue that I haven't been able to figure out.

pyarmor : The term 'pyarmor' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pyarmor gen test.py
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (pyarmor:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I have pyarmor installed, yes I ran pip install pyarmor and tested it and it still runs into this issue. Thank you if you could provide a solution.

**Comment by jondy** [comment]
Try to `python -m pyarmor.cli` as `pyarmor`, more information refer to chapter `installation` in the documentation.

**Comment by jondy** [comment]
Also google for solution, i think it may not issue of pyarmor.
