### ISSUE TITLE
[BUG] `RuntimeError: unauthorized use of script`

### ISSUE THREAD

**Issue by kmg5759** [dashingsoft/pyarmor#1559]
I understand that you previously used PyArmor version 6.8.0 to obfuscate your code, and you had no issues with the approach.
However, after purchasing PyArmor 8.4.1 (basic), the same approach is not working for me.
You mentioned that you used the following commands for obfuscation:

# version 6.8.0 with free
pyarmor obfuscate --no-cross-protection --restrict 0 --advanced 2 func_method1.py
/dist/func_method1.py covert to func_method1.pyd
import func_method1(=pyd file)
obfuscated scripts to pyd : no problem

# version 8.4.1 (basic) with charged
pyarmor gen func_method1.py
/dist/func_method1.py covert to func_method1.pyd
import func_method1(=pyd file)
obfuscated scripts to pyd : problem, RuntimeError: unauthorized use of script

# then converting pyarmor to pyd file
#convert_file.py
#!python
#cython: language_level=3
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext
then /dist/func_method1.py 
ext_modules = [  Extension("func_method1",   ["./dist/func_method1.py"]), ]
setup(
    name = 'decr',
    cmdclass = {'build_ext': build_ext},
    ext_modules = ext_modules
)
$python convert_file.py build_ext --inplace
then make func_method1.pyd
I tried the following commands with PyArmor 8.4.1, but encountered the error "RuntimeError: unauthorized use of script":

import func_method1
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
RuntimeError: unauthorized use of script (1:10851)

I aim to use the new version of PyArmor in a similar manner as before, only obfuscating long sections of code.
My native language is not English. I'd appreciate it if you could explain it in detail.
Thank you!

**Comment by jondy** [comment]
I don't know what about converting .py to .pyd, it's not Pyarmor features.

Anyway, `RuntimeError: unauthorized use of script (1:10851)` means something is wrong with outer key.

And try to disable restrict module by this command `pyarmor cfg restrict_module=0`, then run `pyarmor gen xxx.py` again.

Please run `pyarmor gen -h` to list all the available options, and read man page in the online documentation to find the right options for your cases.
