### ISSUE TITLE
How to use the old registration code

### ISSUE THREAD

**Issue by skinnymonkey** [dashingsoft/pyarmor#156]
I reinstalled os on my machine and installed the latest pyarmor 5.8.2.

I have the old registration code and how to use it now?

pyarmor register CODE

does not work anymore

**Comment by jondy** [comment]
What's the registration email? I'll send the regfile to this email.

**Comment by skinnymonkey** [comment]
Hi there, my email is maom@hotmail.com.

Thanks!
________________________________

**Comment by skinnymonkey** [comment]
Got it. Thx.

**Comment by jondy** [comment]
Sent, please check the email.
