### ISSUE TITLE
Business users request support for Python 3.12.

### ISSUE THREAD

**Issue by 17Reset** [dashingsoft/pyarmor#1560]
Hello, I'm Oxygen_Chu, a business user subscriber, how soon will pyarmor support Python312?Our program is in dire need of it.

**Comment by jondy** [comment]
Pyarmor 8.4+ has been supported Python 3.12, please check change logs for latest update.

**Comment by 17Reset** [comment]
But I can't use the bcc mode, is it different from how I used to use it?And it is stated in your official website documentation that this is not available:
![Uploading 307df0f340dcfae872ac091f29097d5.png…]()
![baa48930f28f7f31619eb42ebbcfdc7](https://github.com/dashingsoft/pyarmor/assets/122418720/d2b44b92-524b-4fb1-b45c-3361698ebaee)
