### ISSUE TITLE
[QUESTION] Pyarmor-old & Pyarmor-Group

### ISSUE THREAD

**Issue by HangingWithCMM** [dashingsoft/pyarmor#1561]
Are you able to use a Pyarmor-old and Pyarmor-Group License on the same device at the same time?

**Comment by jondy** [comment]
Yes. In pyarmor 8, use `pyarmor --home /path/to/another` to specify new path, please check Pyarmor 8 man page for more information.

Besides, please ask questions in discussions

**Comment by jondy** [comment]
First try to upgrade Pyarmor to latest version (8.4.6)
