### ISSUE TITLE
The "invalid v8 code" problem still exists.

### ISSUE THREAD

**Issue by 17Reset** [dashingsoft/pyarmor#1563]
My development environment:
Windows 11 Workstation Pro 22H2 x64 and Latest Patch
Python x64 3.12
Issues arising:
invalid v8 code

**Comment by jondy** [comment]
It's better to provide a simple script to reproduce it and with all options used

**Comment by 17Reset** [comment]
He's not always wrong, I can't reproduce it now, but it's still the 'invalid v8 code' prompt with the command: pyarmor gen --enable-bcc --obf-code 2 test.py

**Comment by jondy** [comment]
I have fixed some `invalid v8 code` issues for Python 3.12

Verify it by pre-release version                                   
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.4.3.zip
