### ISSUE TITLE
[BUG] `invalid device info`

### ISSUE THREAD

**Issue by gergo-fazekas-regens** [dashingsoft/pyarmor#1564]
**Summary**
In case of the HDD serial number has a specific format, the `pyarmor gen` command can't handle it properly.

**How to reproduce**
> $ pyarmor gen -b 3635_5A33_5476_5221_2015_3828_0000_0001 foo.py
INFO     Python 3.10.13
INFO     Pyarmor 8.3.10 (pro), ...
INFO     Platform windows.x86_64
INFO     search inputs ...
INFO     find package at .
INFO     find 1 top resources
ERROR    invalid device info "3635_5A33_5476_5221_2015_3828_0000_0001"

(The expected result would be a successful run.)

**Comment by jondy** [comment]
Got it, it will be fixed in next release.

Verify it by pre-release version
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.4.3.zip

**Comment by gergo-fazekas-regens** [comment]
Thank you very much, the given pre-release version indeed works on this type of HDD serial number.
