### ISSUE TITLE
"PyArmor does not work with this core library (reversion < 5)" in version 5.8

### ISSUE THREAD

**Issue by johnlundberg** [dashingsoft/pyarmor#157]
In version 5.8.0, 5.8.1 and 5.8.2 I get the following RuntimeError

RuntimeError: PyArmor does not work with this core library (reversion < 5)

With debug logging turned on I get this:
DEBUG    The version of core library is (5, 3, 0)

Version 5.7.9 seems to be working, and with debug logging turned on I get:
DEBUG    The version of _pyransform is (7, 1, 7)

**Comment by jondy** [comment]
Please do a clean uninstallation first, refer to
https://pyarmor.readthedocs.io/en/latest/installation.html#clean-uninstallation

Then install PyArmor again

**Comment by JHSEhv** [comment]
I have the same issue while evaluating whether this is a way to obfuscate. Works in Python 3.8.0 (32), but fails in Python 3.8.0-64. I did a fresh install on Python and PyArmor).

Debug logging:
DEBUG    PyArmor installation path: c:\python\3.8.0-64\lib\site-packages\pyarmor
DEBUG    PyArmor data path: C:\Users\jhen\.pyarmor
DEBUG    Native platform is windows.x86_64
DEBUG    Search dynamic library in the path: c:\python\3.8.0-64\lib\site-packages\pyarmor\platforms
DEBUG    Loaded dynamic library: c:\python\3.8.0-64\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
DEBUG    The version of core library is (5, 3, 0)
... etc ...
  File "c:\python\3.8.0-64\lib\site-packages\pyarmor\utils.py", line 130, in pytransform_bootstrap
    raise RuntimeError('PyArmor does not work with this core library '
RuntimeError: PyArmor does not work with this core library (reversion < 5)

When I modify the file "utils.py, line 130", the library crashes at the attempt to obfuscate the first python source file:

  File "c:\python\3.8.0-64\lib\site-packages\pyarmor\pytransform.py", line 90, in encrypt_code_object
    return dlfunc(pubkey, co, flags)
OSError: exception: access violation writing 0x0000000000000000

Seems like a NULL pointer dereference here....

**Comment by johnlundberg** [comment]
Doing a clean uninstall did not help me unfortunately

**Comment by jondy** [comment]
Does it work to obfuscate a simple script? If not, obfuscate it by this way:
```
PYTHONDEBUG=y pyarmor -d obfuscate foo.py
```
Show the useful console output and upload log file `pytransform.log` here

**Comment by JHSEhv** [comment]
Same result:
D:\temp\testpyarmor>set PYTHONDEBUG=y

D:\temp\testpyarmor>pyarmor -d obfuscate Source\main.py
DEBUG    PyArmor installation path: c:\python\3.8.0-64\lib\site-packages\pyarmor
DEBUG    PyArmor data path: C:\Users\jhen\.pyarmor
DEBUG    Native platform is windows.x86_64
DEBUG    Search dynamic library in the path: c:\python\3.8.0-64\lib\site-packages\pyarmor\platforms
Debug mode enabled and log to 'pytransform.log'
DEBUG    Loaded dynamic library: c:\python\3.8.0-64\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
DEBUG    The version of core library is (5, 3, 0)
Traceback (most recent call last):
  File "C:\Python\3.8.0-64\Lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\3.8.0-64\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\3.8.0-64\Scripts\pyarmor.exe\__main__.py", line 9, in <module>
  File "c:\python\3.8.0-64\lib\site-packages\pyarmor\pyarmor.py", line 1138, in main_entry
    main(sys.argv[1:])
  File "c:\python\3.8.0-64\lib\site-packages\pyarmor\pyarmor.py", line 1127, in main
    pytransform_bootstrap(capsule=DEFAULT_CAPSULE)
  File "c:\python\3.8.0-64\lib\site-packages\pyarmor\utils.py", line 130, in pytransform_bootstrap
    raise RuntimeError('PyArmor does not work with this core library '
RuntimeError: PyArmor does not work with this core library (reversion < 5)

[pytransform.log](https://github.com/dashingsoft/pyarmor/files/3934901/pytransform.log)

**Comment by wjsbgsnwss** [comment]
I am facing the same issue, though the version I have is 3.7.4-64

**Comment by jondy** [comment]
Sorry, the library for windows.x86_64 is old. I'm building a quick fixed version, it will be released in an hour.

**Comment by jondy** [comment]
Fixed in v5.8.3, please upgrade to latest version.

**Comment by JHSEhv** [comment]
Tested in Python 3.8.0-64 (windows.x86_64). It seems to work now. Thank you.

**Comment by johnlundberg** [comment]
The issue is fixed for me as well, closing this issue.
