### ISSUE TITLE
Not Found Pyarmor-Vax-004295

### ISSUE THREAD

**Issue by apkfer** [dashingsoft/pyarmor#1573]
Dear  @jondy 
![1-1.PNG](https://github.com/dashingsoft/pyarmor/assets/146665127/d87ae8cf-e81b-489c-80ec-d8c05318a974)

![3-1.PNG](https://github.com/dashingsoft/pyarmor/assets/146665127/8882e2d5-1cd8-4048-9132-8c529788d38b)

![2-1.PNG](https://github.com/dashingsoft/pyarmor/assets/146665127/2e99967a-0e79-4d1d-b625-41bf866f0c0b)

I bought pyarmor basic and paid with Paypal. I have complete email and invoice. I have regated the txt file and created a .zip file so I can continue using it on another computer later. I have been using it for 1 day and the product is very good for me. But on the 3rd day, I checked the email that I received and the Invoice was hacked. Yesterday I returned the email through the help of Google and saw that someone wanted to refund this Parmor Basic product (I guarantee that the product will be refunded). The product was purchased by me, it has the same name as in the Invoice "Hoang Nguyen Nhan" Now when I reuse the zip file on my machine I get the error "not found pyarmor -vax-4295" I look forward to receiving your help!

**Comment by apkfer** [comment]
I'm doing a course project for school, I'm just a student and I don't have too much money to pay for the protect code python project. Please help !

**Comment by jondy** [comment]
It's not refund, try it again.

**Comment by apkfer** [comment]
> It's not refund, try it again.
> Should I try with .zip or txt file?

**Comment by jondy** [comment]
No. It can't be upgraded.

**Comment by apkfer** [comment]
Still the same error. I'm so tired of this waiting

![1-1.PNG](https://github.com/dashingsoft/pyarmor/assets/146665127/20f79787-d4c3-4d1e-9252-fdb6a56a4dcd)

**Comment by jondy** [comment]
This order has been refunded, it doesn't work any more.
