### ISSUE TITLE
[BUG] $ flask run  # `pyarmor_runtime.so: undefined symbol: _Py_hashtable_get_entry`

### ISSUE THREAD

**Issue by AFlowOfCode** [dashingsoft/pyarmor#1574]
```
INFO     Python 3.8.10
INFO     Pyarmor 8.4.2 (pro), <redacted>
INFO     Platform linux.x86_64
```

I have a functional Flask app I wanted to test to see if it can run after obfuscating with pyarmor. I immediately ran into an error after trying to run the obfuscated project. Steps to reproduce: 

1. Have basic functioning Flask app & enter project root directory (that which contains `run.py`)
2. `$ pyarmor gen .`  # this successfully obfuscated all files into `/dist`, maintaining folder structure
3. `$ cd dist`
4. `$ flask run`

Result:
```
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'run', an ImportError was raised:

Traceback (most recent call last):
  File "/home/vagrant/.local/share/virtualenvs/flask_project-AeikJMdG/lib/python3.10/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/vagrant/flask_project/dist/run.py", line 2, in <module>
    from pyarmor_runtime_005396 import __pyarmor__
  File "/vagrant/flask_project/dist/pyarmor_runtime_005396/__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
ImportError: /vagrant/flask_project/dist/pyarmor_runtime_005396/pyarmor_runtime.so: undefined symbol: _Py_hashtable_get_entry
```

### Research I conducted prior to creating this issue to try and find a solution on my own.

Github issues:
* https://github.com/dashingsoft/pyarmor/issues/515
  * Possible solution: "It works after using the flask server file as entry script."
  * Problem: I didn't find the term "entry script" or "entry point" anywhere in Pyarmor docs, these phrases doesn't exist anywhere on https://pyarmor.readthedocs.io. User from issue did not clarify how this solved the problem, despite multiple people asking for clarification afterward. No information on how to fix issue.
* https://github.com/dashingsoft/pyarmor/issues/827
  * Possible solution: "Search Flask in the issues and refer to [broken 404 link]". 
  * Problem: I found a similar sounding link on the doc site (https://pyarmor.readthedocs.io/en/latest/topic/obfuscated-script.html) but nothing there seems to have anything to do with my problem. I also don't see searching "Flask" anything helpful.
* I looked at several other issues - none tell me how to fix this problem. "Search flask in the issues" has failed as a solution.

Searching documentation site:
* "undefined symbol"  # zero results on site
* "_Py_hashtable_get_entry"  # zero results on site

Search internet:
* no results with clear answers, just finding other people confused how to do it.

### Conclusions
Pyarmor doesn't have any information about how to use this with Flask. Maybe it is not possible without hacking, and later nobody shares how they hacked it together. In my opinion, pyarmor documentation should:
* provide clear step by step tutorial how to use with Flask, as existing issues and documentation site do not seem to help at all or if so the answers are very hidden and unintuitive.
* make sure there are results on the documentation site for "entry script" with clear explanation how this relates to pyarmor usage, plus have results for searching error terms "undefined symbol", and "_Py_hashtable_get_entry" with explanations why this may happen.

### My expected behavior
Obfuscated flask app runs immediately after obfuscation. 

I want to know step by step how to obfuscate an existing Flask app and ensure that it runs, because these steps are not available anywhere. I have seen not a single place on the internet with any information about how to do this. 

Thank you for your time.

**Comment by jondy** [comment]
You should obfuscate the scripts by Python 3.10 because flash app is executed by Python 3.10

Please refer to
https://pyarmor.readthedocs.io/en/latest/topic/obfuscated-script.html
