### ISSUE TITLE
[BUG] Special hook script (pyarmor_runtime.py) not workable when using `--outer` outer runtime key 

### ISSUE THREAD

**Issue by chwong1pa** [dashingsoft/pyarmor#1578]
I have a `pyarmor_runtime.py` hooks at .pyarmor/hooks
```
def bootstrap(user_data):
    print("@pyarmor_runtime")
    return True
```

script `foo.py`:
```
print("Foo")
```

I run `pyarmor gen foo.py`, then execute `python dist/foo.py`. It shows:
```
@pyarmor_runtime
Foo
```

But, I run `pyarmor gen --outer foo.py`, then execute `python dist/foo.py` with the rkey. It shows:
```
Foo
```

Expected result for generating using outer:
```
@pyarmor_runtime
Foo
```

**Comment by jondy** [comment]
Can't reproduced.

What I tested:
1. First create `.pyarmor/hooks/pyarmor_runtime.py`
2. Then run these commands in current path
```
pyarmor gen --outer foo.py
pyarmor gen key -e .10
mv dist/pyarmor.rkey dist/pyarmor_runtime_000000
python dist/foo.py
```

It prints `@pyarmor_runtime`

**Comment by chwong1pa** [comment]
@jondy 
I regenerate the rkey due to expired. And it works today. Thanks!

**Comment by chwong1pa** [comment]
@jondy 
Finally, I found a pattern to reproduce the problem. Just record this for your information.
Host machine is python version is `3.10.12`
I build the code using docker container with `--outer`, the python version is `3.11.6`.
If the built code is executed with the rkey generated from host machine, it would not print `@pyarmor_runtime`.
If the built code is executed with the rkey generated from docker container, it would print `@pyarmor_runtime`.

Can we generate rkey using device B to use but the built code using device A? Or we need to make sure 1. device key is the same, 2. python version is the same and 3. at the same environment (host/docker container)?

**Comment by chwong1pa** [comment]
@jondy 
Seems the code in `.pyarmor/hooks/pyarmor_runtime.py` is embedded in the rkey rather than in the generated code. Right?

**Comment by jondy** [comment]
Yes. And it will be compiled as byte code, so if using this feature, the outer key may not work with other Python version.
