### ISSUE TITLE
[BUG] Can't register device after pyarmor 8.4.x

### ISSUE THREAD

**Issue by EmberLightVFX** [dashingsoft/pyarmor#1579]
Hi! I'm having some problems activating my group license.
If I install pyarmor 8.3.11 and register my license I get this message:

INFO     Python 3.10.11
INFO     Pyarmor 8.3.11 (group), 006099, aesl
INFO     Platform windows.x86_64
INFO     register "xxx\pyarmor-device-regfile-6099.1.zip"
INFO     machine id in group license: l6bb78ba32acdb4fea75a7a3f027a777b
INFO     got machine id: l6bb78ba32acdb4fea75a7a3f027a777b
INFO     this machine id matchs group license
INFO     This license registration information:

License Type    : pyarmor-group
License No.     : pyarmor-vax-006099
License To      : Aescripts, Inc
License Product : aesl

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Offline obfuscation

As expected. But if I install pyarmor 8.4.x and try to register I get this message:

INFO     Python 3.10.11
INFO     Pyarmor 8.4.0 (group), 006099, aesl
INFO     Platform windows.x86_64
INFO     register "xxx\pyarmor-device-regfile-6099.1.zip"
INFO     machine id in group license: l6bb78ba32acdb4fea75a7a3f027a777b
INFO     got machine id: me5990acfc7bcb03e61b1b63a365bb0aa
INFO     got machine id: le5990acfc7bcb03e61b1b63a365bb0aa
INFO     got machine id: i6bb78ba32acdb4fea75a7a3f027a777b
INFO     got machine id: k714208df2286b548d37781f7354ae160
INFO     got machine id: g714208df2286b548d37781f7354ae160
INFO     got machine id: b667efefa1068fc98ceb3ee0a79115306
INFO     no machine id matchs this group license
INFO     take this machine as docker container, and connect to docker host for authentication...
INFO     could not get docker host machine id

As you can see I get a bunch more machine IDs but the closes it (i6bb78ba32acdb4fea75a7a3f027a777b) has the "l" changed to a "i" as the first character and I can no longer register my device.
Before figuring out that the newer versions of pyarmor caused this problem I tried to register my device with a new device ID (2 instead of 1) but I got the error that my license was invalid so I can't generate new device licenses ether.

I hope this can be fixed as soon as possible.

**Comment by jondy** [comment]
This group license (6099) has been chargebacked and then reactivated.

Please check Pyarmor EULA, once license is chargebacked, it's invalid and never works.

**Comment by EmberLightVFX** [comment]
> This group license (6099) has been chargebacked and then reactivated.
> 
> Please check Pyarmor EULA, once license is chargebacked, it's invalid and never works.

Do you mean that I can re-activate the license or that the pay got reversed? I don't see any chargeback on my end
