### ISSUE TITLE
OpenCV missing configuration file when running the exe file generated from pyarmor pack

### ISSUE THREAD

**Issue by zanazakaryaie** [dashingsoft/pyarmor#158]
**Device: Raspberry Pi
OS: Raspbian Stretch**

I used `pyarmor pack main.py` to obfuscate and generate an executable file. Everything goes fine but when I use `/dist/main` to run the file, it throws the following error:

```
raise ImportError('OpenCV loader: missing configuration file: {}. Check OpenCV installation.'.format(fnames))
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.
```

I searched the forums. They suggested installing OpenCV by `pip install opencv-python`. But, I don't want to do this for some reason. 

I tried to resolve the error by using `pyarmor pack -e " --add-binary ${address of cv2.so}:cv2" main.py`, but the same error occurred when running the executable file.

How should I resolve this error?

**Comment by jondy** [comment]
First find `config.py` in the install path of opencv, try to pack `main.py` by `pyinstaller` directly, for example
```
pyinstaller -p ${path of config.py} --hidden-import config --add-binary ${address of cv2.so}:cv2 ```
Make sure it works.

**Comment by zanazakaryaie** [comment]
I passed these options to `pyarmor pack -e`. Inside the dist folder, I can see a folder named cv2 that contains cv2.so. But when I run the `main` the same error is reproduced. 
config.py is a file in the installation path of OpenCV. In that path, there is a file named __init__.py that tries to load config.py in a path declared by a variable called `fnames`. When I print `fnames`, the directory is wrong for loading config.py
How should I tell the pyinstaller to set `fnames` to its true directory?!

**Comment by jondy** [comment]
> When a bundled app starts up, the bootloader sets the sys.frozen attribute and stores the absolute path to the bundle folder in sys._MEIPASS.

So you may edit `__init__.py` to set `fnames` base on `sys._MEIPASS`

About more pyinstaller runtime information, refer to 
https://pyinstaller.readthedocs.io/en/stable/runtime-information.html
