### ISSUE TITLE
[BUG] Behavior of assert-import, assert-call, private, restrict, and __assert_armored__ appears to be different from Reference

### ISSUE THREAD

**Issue by irreg** [dashingsoft/pyarmor#1580]
### Environment
- Python 3.8.9
- Pyarmor 8.4.3
- Windows 10/11 x64

```
$ pyarmor gen -O dist --assert-call foo.py
INFO     Python 3.8.9
INFO     Pyarmor 8.4.3 (trial), 000000, non-profits
INFO     Platform windows.x86_64
```

## --assert-import, --assert-call, --private option
- When importing and calling encrypted file B from encrypted file A
Replace B with unencrypted file: no error on import (assert-import) or on function call (assert-call)
Replace A with unencrypted file: no error on import (private), but error on function call (restrict)

#### a.py (A)
```py
import b
b.f()
```

#### b.py (B)
```py
def f():
    print("test")
```

1. Execute: pyarmor gen -r --private --assert-call --assert-import --exclude ".\dist" .
2. Move to dist folder
3. Replace either a.py or b.py in the dist folder with the file before encryption
4. Execute: python a.py

## --restrict option
Depending on the file name, neither import, function call, nor direct invocation of the file may result in an error.

#### a.py
```py
import t
t.f()
```

#### t.py
t.py is one of the error-free filenames. There are many other error-free filenames.
```py
def f():
    print("test")
```

1. Execute: pyarmor gen --restrict t.py
2. Move to dist folder
3. Copy a.py into the dist folder
4. Execute: python a.py
5. Execute directly: python t.py

#### a.py
```py
import b

# pyarmor: __assert_armored__(b.C)
```

#### b.py
```py
class C():
    pass
```

1. Execute: pyarmor gen a.py
2. Move to dist folder
3. Copy b.py into the dist folder
4. Execute: python a.py

#### a.py
```py
import b

# pyarmor: __assert_armored__(b)
```

#### b.py
```py
def f():
    pass
```

1. Execute: pyarmor gen .
2. Move to dist folder
4. Execute: python a.py

**Comment by jondy** [comment]
Could you enable trace and check trace log first?
```
pyarmor cfg enable_trace
cat .pyarmor/pyarmor.trace.log
```

There are 2 cases:
1. they're not protected as expected if there is no log in trace log
2. they're protected, but not as expected.

And try to put source to another path, for example `src`

It may not work if use current path '.' as package

**Comment by jondy** [comment]
I think you may misunderstand these options and function `__assert_armored__`, please check man page about each option.

And check tutorials to know how to trace log. For example,
https://pyarmor.readthedocs.io/en/latest/tutorial/obfuscation.html

Function `__assert_armored__` is internal implementation for `--assert-call` and `--assert-import`.  It won't check `Class`, I may update documentation, `callable object` is not exact.

**Comment by jondy** [comment]
I think it's better to report one issue for one option, it's diffucult to handle mass issues.

So I'll not trace this issue, and it's better to understand these options and then report bug, at least, in my view, about `--private` and `__assert_armored__` is not bug, but wrong usage.

**Comment by irreg** [comment]
Thanks for the reply.
After dividing and organizing the contents, we will stand another issue.

**Comment by irreg** [comment]
--assert-import, --assert-call did not work as intended due to the use of "." as path.

I have issued which was reproduced without using "." as path.

**Comment by irreg** [comment]
https://pyarmor.readthedocs.io/en/latest/tutorial/obfuscation.html#more-options-to-protect-script
Also, although minor, it appears that `__assert_call__(fib)` is a misprint of `__assert_armored__(fib)`.
