### ISSUE TITLE
RuntimeError: Resource temporarily unavailable when using outer key

### ISSUE THREAD

**Issue by fadebek** [dashingsoft/pyarmor#1583]
I used pyarmor 8.4.2 to obfuscate my package using `--outer`. I then used `pyarmor gen key -e 1` to generate a runtime license key. I put the runtime key in my path. Then when I go to run my file that uses the obfuscated package, I immediately get `RuntimeError: Resource temporarily unavailable`. I saw on the [docs](https://pyarmor.readthedocs.io/en/v8.2/reference/errors.html?highlight=RuntimeError%3A%20Resource%20temporarily%20unavailable#runtime-errors) that it means my computer cannot connect to NTP. I've tried multiple times without success. What is the solution to fix this? I saw something about using a hook but do I need to make a hook for every single file in my package?

**Comment by jondy** [comment]
Please check pyarmor man page and select the right options by yourself.
