### ISSUE TITLE
[BUG] When "--private" option is specified, error occurs when calling a function, not when importing

### ISSUE THREAD

**Issue by irreg** [dashingsoft/pyarmor#1586]
https://pyarmor.readthedocs.io/en/latest/reference/man.html#cmdoption-pyarmor-gen-private
The page above says "could not be imported by plain script or Python interpreter"

### Environment
- Python 3.8.9
- Pyarmor 8.4.3
- Windows 10/11 x64

```
$ pyarmor gen -O dist --assert-call foo.py
INFO     Python 3.8.9
INFO     Pyarmor 8.4.3 (trial), 000000, non-profits
INFO     Platform windows.x86_64
```

#### a.py
```py
import b
print("imported")
b.f()
```

#### b.py
```py
def f():
    print("test")
```

1. Execute: pyarmor gen --private b.py
2. Copy a.py into the dist folder
3. Execute: python a.py in dist folder 

In step 1, if --assert-call or --assert-import is specified instead of --private, the exact same behavior occurs.
```
pyarmor gen --assert-import b.py
pyarmor gen --assert-call b.py
```

### Result
```
imported
Traceback (most recent call last):
  File "a.py", line 3, in <module>
    b.f()
RuntimeError: unauthorized use of script (1:5174)
```

### Trace Log (pyarmor.trace.log)
```
trace.co             b:1:<module>
trace.co             b:1:f

```

**Comment by jondy** [comment]
Sorry, I don't know what's expected result and what's real result.

**Comment by irreg** [comment]
Expected result: error on import ("imported" won't be printed)
Real result: error on call (No error on import, function call was executed)
