### ISSUE TITLE
[BUG] The __assert_armored__ function does not work correctly without certain options

### ISSUE THREAD

**Issue by irreg** [dashingsoft/pyarmor#1588]
The reference only says "could be used in the obfuscated scripts.", but if certain options are not specified, it does not work correctly.

### Environment
- Python 3.8.9
- Pyarmor 8.4.3
- Windows 10/11 x64

```
$ pyarmor gen -O dist --assert-call foo.py
INFO     Python 3.8.9
INFO     Pyarmor 8.4.3 (trial), 000000, non-profits
INFO     Platform windows.x86_64
```

#### a.py
```py
import b

# pyarmor: __assert_armored__(b)
```

#### b.py
```py
def f():
    pass
```

1. Execute: pyarmor gen b.py a.py
2. Execute at dist folder: python a.py

Expect no error in steps 2, but an error in fact
In step 1, if --assert-call, --assert-import or etc. is specified, no error occurs.

```
pyarmor gen --assert-import b.py a.py
pyarmor gen --assert-call b.py a.py
```

### Result
```
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen a>", line 3, in <module>
RuntimeError: protection exception (16777932)
```

### Trace Log (pyarmor.trace.log)
```
trace.co             b:1:<module>
trace.co             b:1:f
trace.co             a:1:<module>

```

**Comment by jondy** [comment]
Thanks for reporting these protection issues, but I think most of them is that you don't catch the right usage of these options.

I suggest you first read the documentation, then report issues.

I know you spent much time writing these reports, and it could help nothing.

For example, 

> 1. Execute: pyarmor gen b.py a.py                                  
> 2. Execute at dist folder: python a.py                             

> Expect no error in steps 2, but an error in fact

If you have read the section `Patching source by inline marker` in the advanced tutorial, you will know there should be an error.

**Comment by irreg** [comment]
The inline marker is working correctly. Not using them does not affect reproduction.

#### a.py
```py
import b

__assert_armored__(b)
```
The same result can be obtained by encrypting the above file with b.py and running the encrypted a.py in dist in the same way.
