### ISSUE TITLE
Obfuscated scripts getting killed with no error message on M2 Macbook Air

### ISSUE THREAD

**Issue by fadebek** [dashingsoft/pyarmor#1589]
Env:

Macbook Air M2
Pyarmor 8.4.3
Mac OSX Sonoma 14.0
Python 3.10

Hi, when I run an obfuscated script, I get `zsh: killed` with no error message or log. The following steps can reproduce:

1. Create folder `testobf`
2. Create empty `__init__.py`
3. Obfuscate using `pyarmor gen -i -r`
4. Run obfuscated script using `python -m testobf`

This affects any package I try to obfuscate but the above is a simple example. Is there a suggested fix? I cannot find any documented issue.

**Comment by jondy** [comment]
Try to codesign `pyarmor_runtime.so` in the runtime package, search `codesign` in the online documentation to find related contents.

**Comment by fadebek** [comment]
That worked, thanks
