### ISSUE TITLE
如何加密及递归加密？

### ISSUE THREAD

**Issue by ltc1996** [dashingsoft/pyarmor#159]
我的项目文件结构为：
```
test_folder
   folder_in
     __init__.py
     f1.py
   a.py
   b.py
```
如何递归加密此路径内的所有（4个）py?，让这4个都可独立作为entry运行？感谢

**Comment by ltc1996** [comment]
最外层文件夹是test。
我尝试使用`pyarmor obfuscate --recursive --output dist/test test/__init__.py`但提示`__pyarmor__ is not defined`。

**Comment by jondy** [comment]
两种方案，一种是使用 `obfuscate` 多次，例如
```
pyarmor o -r -O dist/test a.py
pyarmor o --exact -O dist/test b.py
pyarmor o --exact -O dist/test/folder_in folder_in/__init__.py
pyarmor o --exact -O dist/test/folder_in folder_in/f1.py
```

另外一种方法就是使用工程
```
pyarmor init --src "." --entry "a.py,b.py,folder_in/__init__.py,folder_in/f1.py"
pyarmor config --package-runtime 2
pyarmor build
```
其中第二条命令 `config` 的主要作用是在 `__init__.py` 中插入引导代码不要使用相对导入的方式

**Comment by ltc1996** [comment]
![image](https://user-images.githubusercontent.com/47720586/70587205-4ddd0a00-1c04-11ea-8a43-0f0831bc0044.png)
我使用您提供的第二种方法加密py2文件，提示这个错，该用什么编码方式？

**Comment by jondy** [comment]
可能的话升级到最新版本 v5.8.3 ，我记得有对文件编码进行处理方面的更新。

**Comment by jondy** [comment]
这个应该是中文路径的问题，保存绝对路径到工程配置文件中的时候出错了，你可以先把中文路径修改一下，把`更新`两个字换成英文，这个问题估计新版本也存在，我后面需要修改一下

**Comment by ltc1996** [comment]
我更新到试用版v583，也把中文路径改掉了，可以bulid，但是运行py时提示
![image](https://user-images.githubusercontent.com/47720586/70596316-8e4a8100-1c20-11ea-8e32-297b83dcdcfb.png)

**Comment by jondy** [comment]
为什么你的Python系统库目录下面有这个文件 `C:/Python27/lib/site-packages/pytransform.py`？运行加密脚步要把这个要删除了，加密后的输出目录下会有一个对应的包 `py transform`，运行加密脚本必须使用那个运行辅助包，两者冲突了。

**Comment by ltc1996** [comment]
删除后可所有entry可独立进入了，万分感谢🙂

**Comment by ltc1996** [comment]
加密后生成的pytransform文件夹是否一样（不同加密脚本能否共用同一个pytransform文件夹）？

**Comment by jondy** [comment]
使用相同 .pyarmor_capsule.zip 生成的是通用的，可以共用。

**Comment by ltc1996** [comment]
怎么判断.pyarmor_capsule.zip是否一样，是按照版本区分的吗？

**Comment by jondy** [comment]
不是的，所有试用版本这个文件都是一样的。购买pyarmor的许可之后，每一个许可对应一个私有的 .pyarmor_capsule.zip

**Comment by nihilee** [comment]
@jondy 请问如果有很多脚本，想要都能作为独立作为entry运行，有没有递归设置--entry的方法呢？就像--manifest一样

**Comment by ltc1996** [comment]
已经收到了您的邮件，我会尽快回复的。

**Comment by XK-0719** [comment]
赵教授您好，我在init项目的时候使用的指令是：
pyarmor init --src ".dist" --entry "main.py,start.py,database.py,pika_client.py,__init__.py,views/data_views.py"
pyarmor版本是7.0.1
遇到了以下的问题：
![QQ截图20240125102635](https://github.com/dashingsoft/pyarmor/assets/84333859/c24cfd35-d8ce-4137-8f06-0562319d074b)
我之前也创建过项目，看报错的意思是是已经存在了项目，请问怎么解决这个问题呢。非常感谢！！

**Comment by XK-0719** [comment]
抱歉赵教授我再第二次运行这个指令的时候忘记了删除之前生成的config文件导致无法init，现在在dist目录下成功生成了项目，但是碰到了一个奇怪的问题：生成的database.py无法被引用。项目目录结构如下：
![mulu](https://github.com/dashingsoft/pyarmor/assets/84333859/221af42e-d095-406a-acdb-931d3d168072)
运行时报错如下：
![prob](https://github.com/dashingsoft/pyarmor/assets/84333859/2ecc7d64-066f-4f12-8d71-07d7e22694f6)
我也参考了文档中的这种方法：
![doc](https://github.com/dashingsoft/pyarmor/assets/84333859/db9f5f99-ea8e-4bf6-95f1-cccae9175e24)
但是出现了相同的报错，是不是我的目录组织结构不对呢？生成的目录结构如下：
![mulu2](https://github.com/dashingsoft/pyarmor/assets/84333859/1e8b0ef3-055f-45a4-b9a3-48c1202da233)
想请问您这种情况该如何解决呢？抱歉打扰您了
