### ISSUE TITLE
The relative import of the exe packaged by pyinstaller fails.

### ISSUE THREAD

**Issue by c469591** [dashingsoft/pyarmor#1593]
Hello, I encountered a problem after using pyinstaller to package. In the original development project folder, there are some .py files and some sub-folders also contain .py files. The .py files in the sub-folders use relative imports to import the .py files in the root directory, like this: "from main import audio". This function is used to import main.py from the root directory.

I have conducted some tests and summarized the issue as follows:

- Running each module directly with Python has no problem.
- Packaging with pyinstaller, whether onefile or onedir, also has no problem.
- Following the instructions in the manual, I modified the spec file for manual packaging. I used this command first to obfuscate .py files:
"pyarmor gen --enable-bcc --mix-str -r game/"
Then placed pyarmor_runtime_005377 into the obfuscated folder. After that, I used this command for packaging:
"pyinstaller main.spec"
The executable can run but when it reaches functionality in a sub-folder's .py file, it throws an error indicating: "Failed to execute script 'main' due to unhandled exception: No module named 'main'".

Please advise me on how to resolve this issue. Thank you!

**Comment by jondy** [comment]
No pack, only obfuscate script, make sure it works.

**Comment by c469591** [comment]
Yes, it was running fine before it was packaged, how do I get it to run fine after it's packaged?

**Comment by DNJ-JINI** [comment]
same issue for me as well. 
I tried to package the pyarmor obfuscated code using pyinstaller and on running the generated exe getting no module found error. The module was already there and it was installed in the environment uisng pip.

**Comment by c469591** [comment]
The issue you're encountering might differ from mine; I had a Python file in a subfolder importing another Python file from the root directory, and when calling the subfolder's Python file, it failed to import the one in the root. Your problem should be fixable by modifying the spec file generated by PyInstaller—whatever is missing, just add it to that spec file.

**Comment by c469591** [comment]
My current issue remains unresolved, and I would greatly appreciate any further guidance or directions for testing you could provide!

**Comment by jondy** [comment]
If the obfuscated scripts work fine, please take the obfuscated scripts as normal Python scripts, refer to
https://pyarmor.readthedocs.io/en/latest/topic/obfuscated-script.html

And check PyInstaller documentation to debug it.
