### ISSUE TITLE
[BUG] RuntimeError: the format of obfuscated script is incorrect

### ISSUE THREAD

**Issue by fadebek** [dashingsoft/pyarmor#1594]
**Env**
Pyarmor 8.4.3
Python 3.10
Generated cross-platform script on M2 Mac for darwin_aarch64 and linux_x86_64. Supporting python versions 3.8-3.12. Also has outer key.

Hi, after obfuscating my script with the above, it runs fine on aarch64 but when I run the same script on linux x86, I get `RuntimeError: the format of obfuscated script is incorrect`. I cant find any information about this in the docs. Is this an issue with Pyarmor? I made sure that the script supports both platforms

I attached the generated code below:
[__init__.py.txt](https://github.com/dashingsoft/pyarmor/files/13370780/__init__.py.txt)

**Comment by jondy** [comment]
Try to test it with a hello work script, if it still doesn't work, report issues by reproduced steps.
