### ISSUE TITLE
Runtime license key only works if PYARMOR_RKEY is set

### ISSUE THREAD

**Issue by fadebek** [dashingsoft/pyarmor#1595]
Env:
Pyarmor 8.4.3
M2 Macbook Air
Python 3.10
Scripts is obfuscated for cross-platform and merges 3.8-3.12 scripts.

Hi, when I run my obfuscated script that needs a runtime license key, I have to explicitly set the PYARMOR_RKEY path to the location if the key. However, in the docs, it says that I should be able to just drop it in the runtime folder, but that doesn't work. Is this expected?

**Comment by jondy** [comment]
Please report issues with reproduced steps, expected results and actual results.
