### ISSUE TITLE
pyarmor_runtime_000000\__init__.py line from .pyarmor_runtime import __pyarmor__ error: Unresolved reference 'pyarmor_runtime' 

### ISSUE THREAD

**Issue by Jarye0612** [dashingsoft/pyarmor#1597]
env:
win10
python-3.10
pyarmor-8.4.3 
pyarmor.cli.core-5.4.0

execute: pyarmor gen -O dist2 src/mypkg
**\dist2\pyarmor_runtime_000000\__init__.py ：from .pyarmor_runtime import __pyarmor__ this line  Unresolved reference 'pyarmor_runtime' ,how to solve?

**Comment by jondy** [comment]
Please read this and fix it by yourself
https://pyarmor.readthedocs.io/en/latest/topic/obfuscated-script.html
