### ISSUE TITLE
[BUG] Runtime License Key not found when using MultiPythonPlugin and Cross-Platform

### ISSUE THREAD

**Issue by fadebek** [dashingsoft/pyarmor#1599]
Hi, when I run my obfuscated script that needs a runtime license key, I have to explicitly set the PYARMOR_RKEY path to the location of the key. However, in the docs, it says that I should be able to just drop it in the runtime folder, but that doesn't work. Is this expected?

Steps to reproduce (using [examples/testpkg](https://github.com/dashingsoft/pyarmor/tree/master/src/examples/testpkg)):

1. `pyarmor cfg plugins=MultiPythonPlugin`
2. `pyarmor gen -i  -r --outer testpkg/mypkg -O obfpkg --platform darwin.aarch64 --platform linux.x86_64`
3. `pyarmor gen key -e .1 -O obfpkg/mypkg/pyarmor_runtime_005114`
4. `cp testpkg/main.py obfpkg`
5. `python obfpkg/main.py`

Yields `RuntimeError: missing license key to run the script (1:10601)`

However, if I do `PYARMOR_RKEY=obfpkg/mypkg/pyarmor_runtime_005114 python obfpkg/main.py` then it runs fine.

This is on PyArmor 8.4.3 on M2 Mac. Python 3.10. Thanks

**Comment by jondy** [comment]
If enable `MultiPythonPlugin`, it need copy key file to each sub-folder. For example,
```
cp obfpkg/mypkg/pyarmor_runtime_005114/pyarmor.rkey obfpkg/mypkg/pyarmor_runtime_005114/py310
cp obfpkg/mypkg/pyarmor_runtime_005114/pyarmor.rkey obfpkg/mypkg/pyarmor_runtime_005114/py311
cp obfpkg/mypkg/pyarmor_runtime_005114/pyarmor.rkey obfpkg/mypkg/pyarmor_runtime_005114/py312
```

In future version, this may be fixed, that is to say, just place key file in the path `obfpkg/mypkg/pyarmor_runtime_005114`

**Comment by jondy** [comment]
The other solution is to customize keyname with prefix `../`, so the obfuscated scripts will search parent folder of `py310`. 

For example,
```bash
$ pyarmor cfg outer_keyname=../pyarmor.rkey

# It's better to use +, do not disable the default CodeSignPlugin
$ pyarmor cfg plugins + MultiPythonPlugin                          

$ pyarmor gen -i  -r --outer testpkg/mypkg -O obfpkg --platform darwin.aarch64 --platform linux.x86_64                             

# make sure keyfile is stored at runtime package
$ pyarmor gen key -e .1 -O obfpkg/mypkg/pyarmor_runtime_005114/py310

$  cp testpkg/main.py obfpkg                                      
$  python obfpkg/main.py  
```

**Comment by fadebek** [comment]
Thanks. The first method worked. The second method gave me `RuntimeError: unauthorized use of script`.
