### ISSUE TITLE
Build dynamic library for FreeBSD amd64

### ISSUE THREAD

**Issue by jondy** [dashingsoft/pyarmor#16]
Build _pytransform.so for the following platform in May:
```
FreeBSD  9.3-RELEASE FreeBSD 9.3-RELEASE #0 r268512: 
Thu Jul 10 23:44:39 UTC 2014     root@snap.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64 

FreeBSD trueos-1820.joonis.de 12.0-CURRENT FreeBSD 12.0-CURRENT #10 d26791952(trueos-stable-17.12): 
Sat Dec  9 18:10:09 UTC 2017     root@chimera:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64 
```

**Comment by joonis** [comment]
Any news on this issue?

**Comment by jondy** [comment]
Download from

http://pyarmor.dashingsoft.com/downloads/platforms/freebsd/_pytransform.so

But it can't get the serial number of hard disk, because in freebsd 9 `ioctl` doesn't support `HDIO_GET_IDENTITY`. I haven't found alternative way to solve this problem.

**Comment by joonis** [comment]
Could you create this library based on Pyarmor v3.8.10?

**Comment by joonis** [comment]
Thank you very much. Seems to work...
