### ISSUE TITLE
Excluding python scripts to be obfuscated

### ISSUE THREAD

**Issue by albertusk95** [dashingsoft/pyarmor#160]
I was trying to exclude python **files** from obfuscation with `--exclude` argument, such as the following.

`pyarmor obfuscate --recursive --exclude script_a.py,script_b.py main.py`

However, both `script_a.py` and `script_b.py` were obfuscated.

This `--exclude` argument works when the specified values are **directories**, however. It means that `--exclude folder_a,folder_b` works as expected.

Is this intended? Or is there a certain way to exclude files?

Thanks.

**Comment by jondy** [comment]
This is a bug, and it's fixed in v5.8.2, please upgrade to the latest version.
