### ISSUE TITLE
problem during to registration

### ISSUE THREAD

**Issue by sohaib929** [dashingsoft/pyarmor#1600]
I purchased a group license, and unfortunately every time I try to complete the registration process, an error occurs. I sent an email to the entity, and unfortunately I was informed that I should present the problem here.
Please help in solving this problem

![image](https://github.com/dashingsoft/pyarmor/assets/57887405/74ec1013-0dfe-43a4-ac6c-0d2cbda9cbfb)

**Comment by jondy** [comment]
Do not paste the snapshop image but paste the text directly.

**Comment by jondy** [comment]
Also search `group license` in issues, there are many related issues, one of them may fix your problem.

And also read this guide
https://pyarmor.readthedocs.io/en/latest/questions.html
