### ISSUE TITLE
[Feature request] Remove inline marker

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#1601]
I finally managed to understand and use Pyarmor 8, but it still doesn't provide me with enough functions to make the application available for production.

Regardless of the security context or the customer's knowledge of the VAX code, I would like to remove it from the final code that pyarmor generates.

All generated code has this signature on the first line, and I would like to remove it

> # Pyarmor 8.4.3 (pro), VAX, REGISTER NAME, 2023-11-20T22:45:07.852941

Furthermore, I could see that the beginning of the bytecode starts with VAX. Couldn't this represent a security flaw?

> __pyarmor__(__name__, __file__, b'PY00VAX.............')

Thanks.

**Comment by jondy** [comment]
There is no any security issue

Each Pyarmor license is bind to unique product, so this signature could make it clear.

And these information (pyarmor version, license type, license code) may be helpful to fix bugs in some cases.

So pyarmor won't remove them by itself.
