### ISSUE TITLE
[BUG] `Pyarmor 8.4.2 installation is failing FreeBSD/OneFS`

### ISSUE THREAD

**Issue by Soujanya459** [dashingsoft/pyarmor#1602]
Hi Jondy,
I see pyaromor==8.4.2 installaiton failing in FreeBSD/Onefs, I even installed setuptools=68.2.2 before installing pyarmor.. can you please let me know what might be the issue here.. 

```
ese_virtualenv) onefs-soujanya-46-1# python -m pip install pyarmor==8.4.2
Collecting pyarmor==8.4.2
  Obtaining dependency information for pyarmor==8.4.2 from https://files.pythonhosted.org/packages/ad/4b/3e4d2c07d75b296866995267f57ec670ba12d58b4c81d7a228d45ad18d30/pyarmor-8.4.2-py3-none-any.whl.metadata
  Using cached pyarmor-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting pyarmor.cli.core~=5.4.0 (from pyarmor==8.4.2)
  Using cached pyarmor.cli.core-5.4.0.zip (9.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      /tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:75: _MissingDynamic: `license` defined outside of `pyproject.toml` is ignored.
      !!

              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:

              `license = 'Free To Use But Restricted'`

              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `license` is listed as `dynamic`.

              https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

              To prevent this problem, you can list `license` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************

      !!
        _handle_missing_dynamic(dist, project_table)
      /tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:75: _MissingDynamic: `keywords` defined outside of `pyproject.toml` is ignored.
      !!

              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:

              `keywords = ['protect obfuscate encrypt obfuscation distribute']`

              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `keywords` is listed as `dynamic`.

              https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

              To prevent this problem, you can list `keywords` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************

      !!
        _handle_missing_dynamic(dist, project_table)
      /tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:75: _MissingDynamic: `dependencies` defined outside of `pyproject.toml` is ignored.
      !!

              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:

              `dependencies = ['pyarmor.cli.core.freebsd==5.4.0']`

              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `dependencies` is listed as `dynamic`.

              https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

              To prevent this problem, you can list `dependencies` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************

      !!
        _handle_missing_dynamic(dist, project_table)
      Traceback (most recent call last):
        File "/var/crash/ese/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/var/crash/ese/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/var/crash/ese/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
        File "/tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 627, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 67, in apply_configuration
          return _apply(dist, config, filepath)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 56, in apply
          _apply_project_table(dist, config, root_dir)
        File "/tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 82, in _apply_project_table
          corresp(dist, value, root_dir)
        File "/tmp/pip-build-env-p0_xbf3t/overlay/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 183, in _license
          _set_config(dist, "license", val["text"])
                                       ~~~^^^^^^^^
KeyError: 'text'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip3 install --upgrade pip
(ese_virtualenv) onefs-soujanya-46-1#
```

**Comment by jondy** [comment]
This will be fixed in next release.

Or download `pyarmor.cli.core-5.4.1.zip` from pypi.org, then unzip it, and edit `setup.py`, remove keyword `license` from `setup.py`, finally `python setup.py install`

**Comment by Soujanya459** [comment]
Hi Jondy,
I'm not able to find .zip file for pyarmor-cli-core-5.4.1 , I only see .whl files ..  Can you please provide link to download .zip file 

![image](https://github.com/dashingsoft/pyarmor/assets/84155017/3b8a87df-a928-4664-97f7-53d8627932c3)

**Comment by jondy** [comment]
It may be released in next week.

Please download source package for pyarmor-cli-core-5.4.0

**Comment by Soujanya459** [comment]
I'm getting below error when I try to install pyarmor-cli-core.5.4.0

`(ese_virtualenv) onefs-soujanya-46-1# pwd
/var/crash/ese/work/pyarmor.cli.core-5.4.0
(ese_virtualenv) onefs-soujanya-46-1# python setup.py install
/var/crash/ese/usr/local/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:73: _WouldIgnoreField: `keywords` defined outside of `pyproject.toml` would be ignored.
!!

        ********************************************************************************
        ##########################################################################
        # configuration would be ignored/result in error due to `pyproject.toml` #
        ##########################################################################

        The following seems to be defined outside of `pyproject.toml`:

        `keywords = ['protect obfuscate encrypt obfuscation distribute']`

        According to the spec (see the link below), however, setuptools CANNOT
        consider this value unless `keywords` is listed as `dynamic`.

        https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

        For the time being, `setuptools` will still consider the given value (as a
        **transitional** measure), but please note that future releases of setuptools will
        follow strictly the standard.

        To prevent this warning, you can list `keywords` under `dynamic` or alternatively
        remove the `[project]` table from your file and rely entirely on other means of
        configuration.

        This deprecation is overdue, please update your project and remove deprecated
        calls to avoid build errors in the future.
        ********************************************************************************

!!
  _handle_missing_dynamic(dist, project_table)
/var/crash/ese/usr/local/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:73: _WouldIgnoreField: `dependencies` defined outside of `pyproject.toml` would be ignored.
!!

        ********************************************************************************
        ##########################################################################
        # configuration would be ignored/result in error due to `pyproject.toml` #
        ##########################################################################

        The following seems to be defined outside of `pyproject.toml`:

        `dependencies = ['pyarmor.cli.core.freebsd==5.4.0']`

        According to the spec (see the link below), however, setuptools CANNOT
        consider this value unless `dependencies` is listed as `dynamic`.

        https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

        For the time being, `setuptools` will still consider the given value (as a
        **transitional** measure), but please note that future releases of setuptools will
        follow strictly the standard.

        To prevent this warning, you can list `dependencies` under `dynamic` or alternatively
        remove the `[project]` table from your file and rely entirely on other means of
        configuration.

        This deprecation is overdue, please update your project and remove deprecated
        calls to avoid build errors in the future.
        ********************************************************************************

!!
  _handle_missing_dynamic(dist, project_table)
running install
/var/crash/ese/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/var/crash/ese/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing pyarmor.cli.core.egg-info/PKG-INFO
writing dependency_links to pyarmor.cli.core.egg-info/dependency_links.txt
writing requirements to pyarmor.cli.core.egg-info/requires.txt
writing top-level names to pyarmor.cli.core.egg-info/top_level.txt
reading manifest file 'pyarmor.cli.core.egg-info/SOURCES.txt'
writing manifest file 'pyarmor.cli.core.egg-info/SOURCES.txt'
installing library code to build/bdist.freebsd-12.0-CURRENT-amd64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/pyarmor
creating build/lib/pyarmor/cli
creating build/lib/pyarmor/cli/core
copying pyarmor/cli/core/__init__.py -> build/lib/pyarmor/cli/core
copying pyarmor/cli/core/features.py -> build/lib/pyarmor/cli/core
copying pyarmor/cli/core/runtime.py -> build/lib/pyarmor/cli/core
creating build/bdist.freebsd-12.0-CURRENT-amd64
creating build/bdist.freebsd-12.0-CURRENT-amd64/egg
creating build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor
creating build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli
creating build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core
copying build/lib/pyarmor/cli/core/__init__.py -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core
copying build/lib/pyarmor/cli/core/features.py -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core
copying build/lib/pyarmor/cli/core/runtime.py -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core
byte-compiling build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core/__init__.py to __init__.cpython-312.pyc
byte-compiling build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core/features.py to features.cpython-312.pyc
byte-compiling build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core/runtime.py to runtime.cpython-312.pyc
creating build/bdist.freebsd-12.0-CURRENT-amd64/egg/EGG-INFO
copying pyarmor.cli.core.egg-info/PKG-INFO -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/EGG-INFO
copying pyarmor.cli.core.egg-info/SOURCES.txt -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/EGG-INFO
copying pyarmor.cli.core.egg-info/dependency_links.txt -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/EGG-INFO
copying pyarmor.cli.core.egg-info/requires.txt -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/EGG-INFO
copying pyarmor.cli.core.egg-info/top_level.txt -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
pyarmor.cli.core.__pycache__.__init__.cpython-312: module references __file__
pyarmor.cli.core.__pycache__.runtime.cpython-312: module references __file__
creating dist
creating 'dist/pyarmor.cli.core-5.4.0-py3.12.egg' and adding 'build/bdist.freebsd-12.0-CURRENT-amd64/egg' to it
removing 'build/bdist.freebsd-12.0-CURRENT-amd64/egg' (and everything under it)
Processing pyarmor.cli.core-5.4.0-py3.12.egg
creating /var/crash/ese/usr/local/lib/python3.12/site-packages/pyarmor.cli.core-5.4.0-py3.12.egg
Extracting pyarmor.cli.core-5.4.0-py3.12.egg to /var/crash/ese/usr/local/lib/python3.12/site-packages
Adding pyarmor.cli.core 5.4.0 to easy-install.pth file

Installed /var/crash/ese/usr/local/lib/python3.12/site-packages/pyarmor.cli.core-5.4.0-py3.12.egg
Processing dependencies for pyarmor.cli.core==5.4.0
Searching for pyarmor.cli.core.freebsd==5.4.0
Reading https://pypi.org/simple/pyarmor.cli.core.freebsd/
Download error on https://pypi.org/simple/pyarmor.cli.core.freebsd/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000) -- Some packages may not be found!
Couldn't find index page for 'pyarmor.cli.core.freebsd' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000) -- Some packages may not be found!
No local packages or working download links found for pyarmor.cli.core.freebsd==5.4.0
error: Could not find suitable distribution for Requirement.parse('pyarmor.cli.core.freebsd==5.4.0')
(ese_virtualenv) onefs-soujanya-46-1#
`

**Comment by Soujanya459** [comment]
Getting below error while registering the license

```
(ese_virtualenv) onefs-soujanya-46-1# pyarmor reg pyarmor-regfile-5098.zip
Traceback (most recent call last):
  File "/var/crash/ese/work/ese_virtualenv/bin/pyarmor", line 8, in <module>
    sys.exit(main_entry_8())
             ^^^^^^^^^^^^^^
  File "/var/crash/ese/work/ese_virtualenv/lib/python3.12/site-packages/pyarmor/pyarmor.py", line 1643, in main_entry_8
    call_pyarmor_cli()
  File "/var/crash/ese/work/ese_virtualenv/lib/python3.12/site-packages/pyarmor/pyarmor.py", line 1616, in call_pyarmor_cli
    from .cli.__main__ import main
  File "/var/crash/ese/work/ese_virtualenv/lib/python3.12/site-packages/pyarmor/cli/__main__.py", line 33, in <module>
    from .generate import Builder
  File "/var/crash/ese/work/ese_virtualenv/lib/python3.12/site-packages/pyarmor/cli/generate.py", line 26, in <module>
    from .core import Pytransform3
ImportError: cannot import name 'Pytransform3' from 'pyarmor.cli.core' (unknown location)
(ese_virtualenv) onefs-soujanya-46-1#
```

**Comment by jondy** [comment]
Please wait for 8.4.2 released

**Comment by jondy** [comment]
Fixed in v8.4.4, please install the latest version v8.4.4 directly.

**Comment by Soujanya459** [comment]
Hi Jondy,
when I install pyarmor 8.4.4, registration of license is failing...

(ese_virtualenv) onefs-soujanya-46-1# pyarmor reg pyarmor-regfile-5098.zip
INFO     Python 3.12.0
INFO     Pyarmor 8.4.4 (trial), 000000, non-profits
INFO     Platform isilon onefs.x86_64
INFO     register "pyarmor-regfile-5098.zip"
INFO     update license token
ERROR    No module named 'pyarmor.cli.core.freebsd'
(ese_virtualenv) onefs-soujanya-46-1#


(ese_virtualenv) onefs-soujanya-46-1# pip list | grep py
pyarmor          8.4.4
pyarmor.cli.core 5.4.2

**Comment by jondy** [comment]
Please install `pip install pyarmor.cli.core.freebsd` also
