### ISSUE TITLE
[Request] Add different time validation methods

### ISSUE THREAD

**Issue by Daniel451** [dashingsoft/pyarmor#1603]
Currently, time validation relies on a NTP server being reachable. I would like to propose to add additional flags (e.g. `--localtime`, `--httptime`, ...) to allow checking time via an HTTP request or, in case network is not available, against localtime.

When a NTP server is not reachable, at the moment, we will simply see:
```
RuntimeError: Resource temporarily unavailable
```
...as documented at https://pyarmor.readthedocs.io/en/latest/reference/errors.html#runtime-errors

As far as I can tell the suggested solution as of now is implementing a custom hook to check time otherwise:
```
def _pyarmor_check_worldtime(host, path):
    from http.client import HTTPSConnection
    expired = __pyarmor__(1, None, b'keyinfo', 1)
    conn = HTTPSConnection(host)
    conn.request("GET", path)
    res = conn.getresponse()
    if res.code == 200:
        data = res.read()
        s = data.find(b'"unixtime":')
        n = data.find(b',', s)
        current = int(data[s+11:n])
        if current > expire:
            raise RuntimeError('license is expired')
     else:
         raise RuntimeError('got network time failed')
_pyarmor_check_worldtime('worldtimeapi.org', '/api/timezone/Europe/Paris')
```
...as documented at https://pyarmor.readthedocs.io/en/latest/tutorial/customization.html#using-hook-to-check-network-time-by-other-service

It would be more convenient if PyArmor itself would allow to set constraints on time validation, e.g., via flags to set the "time validation mode":

1. NTP only
2. NTP + other http time validation methods
3. all of the above + localtime

**Comment by jondy** [comment]
Got it, I'll take it into accounts.

**Comment by jondy** [comment]
Please upgrade Pyarmor to 8.4.4+

Since v8.8.4, it supports HTTP server, and multiple servers. If the first server doesn't work, then uses the second, and so on. When using HTTP protocol, just provide one valid URL. For example::
```
    $ pyarmor cfg nts=http://worldtimeapi.org/api
```

The following example uses multiple servers, both NTP and HTTP::
```
    $ pyarmor cfg nts=pool.ntp.org,http://worldtimeapi.org/api
```

And special name `local` could be used to get local time. For exmaple::
```
    $ pyarmor cfg nts="http://worldtimeapi.org/api,local"
```

**Comment by Daniel451** [comment]
@jondy thank you very much, I will try it out tomorrow. Great customer support! I will continue to recommend PyArmor :)
