### ISSUE TITLE
[BUG] `Pyarmor 8.4.4 license registration is failing`

### ISSUE THREAD

**Issue by Soujanya459** [dashingsoft/pyarmor#1606]
Hi Jondy,
Pyarmor registration is failing when I install 8.4.4 version

(ese_virtualenv) onefs-soujanya-46-1# python -m pip install pyarmor==8.4.4 --no-binary pyarmor
Collecting pyarmor==8.4.4
  Downloading pyarmor-8.4.4.zip (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 493.0 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyarmor.cli.core~=5.4.2 (from pyarmor==8.4.4)
  Obtaining dependency information for pyarmor.cli.core~=5.4.2 from https://files.pythonhosted.org/packages/8c/fd/5fd283c4831ac228cf464d0b91d5aa0e9cf45f18504094f97e010b538806/pyarmor.cli.core-5.4.2-py3-none-any.whl.metadata
  Using cached pyarmor.cli.core-5.4.2-py3-none-any.whl.metadata (2.3 kB)
Using cached pyarmor.cli.core-5.4.2-py3-none-any.whl (5.2 kB)
Building wheels for collected packages: pyarmor
  Building wheel for pyarmor (pyproject.toml) ... done
  Created wheel for pyarmor: filename=pyarmor-8.4.4-py3-none-any.whl size=2714417 sha256=80a96ca6de1bd40c3b450b4e321cd740d5259fda1f9c78978459f123f222e48e
  Stored in directory: /root/.cache/pip/wheels/02/dc/d7/f5d19795cebc25b6b21543e05ae29d11cda44a9323ac3a6528
Successfully built pyarmor
Installing collected packages: pyarmor.cli.core, pyarmor
Successfully installed pyarmor-8.4.4 pyarmor.cli.core-5.4.2

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
(ese_virtualenv) onefs-soujanya-46-1#

ese_virtualenv) onefs-soujanya-46-1# pyarmor reg pyarmor-regfile-5098.zip
INFO     Python 3.12.0
INFO     Pyarmor 8.4.4 (trial), 000000, non-profits
INFO     Platform freebsd.x86_64
INFO     register "pyarmor-regfile-5098.zip"
INFO     update license token
ERROR    No module named 'pyarmor.cli.core.freebsd'

(ese_virtualenv) onefs-soujanya-46-1# pip list | grep py   ---> after pyarmor 8.4.4 installation
pyarmor          8.4.4
pyarmor.cli.core 5.4.2

-->
**But if I install explicitly pyarmor.cli.core.freebsd- 5.4.2 then registration is successful.**

**It should get installed during installation of pyarmor right ??**

**Comment by jondy** [comment]
What's the output of `sys.platform`?
```
$ python -c"import sys
print(sys.platform)"
```

**Comment by jondy** [comment]
Could you uninstall `pyarmor.cli.core` and `pyarmor.cli.core.freebsd` and reinstall `https://files.pythonhosted.org/packages/4d/11/11c1778764f251c4c173f868b02e0f1b26f65701e001124fa1fe19c8e1ad/pyarmor.cli.core-5.4.2.zip` directly?

**Comment by Soujanya459** [comment]
(ese_virtualenv) onefs-soujanya-50-1# python setup.py install
running install
/var/crash/ese/work/ese_virtualenv/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/var/crash/ese/work/ese_virtualenv/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing pyarmor.cli.core.egg-info/PKG-INFO
writing dependency_links to pyarmor.cli.core.egg-info/dependency_links.txt
writing requirements to pyarmor.cli.core.egg-info/requires.txt
writing top-level names to pyarmor.cli.core.egg-info/top_level.txt
reading manifest file 'pyarmor.cli.core.egg-info/SOURCES.txt'
writing manifest file 'pyarmor.cli.core.egg-info/SOURCES.txt'
installing library code to build/bdist.freebsd-12.0-CURRENT-amd64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/pyarmor
creating build/lib/pyarmor/cli
creating build/lib/pyarmor/cli/core
copying pyarmor/cli/core/__init__.py -> build/lib/pyarmor/cli/core
copying pyarmor/cli/core/features.py -> build/lib/pyarmor/cli/core
copying pyarmor/cli/core/runtime.py -> build/lib/pyarmor/cli/core
creating build/bdist.freebsd-12.0-CURRENT-amd64
creating build/bdist.freebsd-12.0-CURRENT-amd64/egg
creating build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor
creating build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli
creating build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core
copying build/lib/pyarmor/cli/core/__init__.py -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core
copying build/lib/pyarmor/cli/core/features.py -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core
copying build/lib/pyarmor/cli/core/runtime.py -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core
byte-compiling build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core/__init__.py to __init__.cpython-312.pyc
byte-compiling build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core/features.py to features.cpython-312.pyc
byte-compiling build/bdist.freebsd-12.0-CURRENT-amd64/egg/pyarmor/cli/core/runtime.py to runtime.cpython-312.pyc
creating build/bdist.freebsd-12.0-CURRENT-amd64/egg/EGG-INFO
copying pyarmor.cli.core.egg-info/PKG-INFO -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/EGG-INFO
copying pyarmor.cli.core.egg-info/SOURCES.txt -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/EGG-INFO
copying pyarmor.cli.core.egg-info/dependency_links.txt -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/EGG-INFO
copying pyarmor.cli.core.egg-info/requires.txt -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/EGG-INFO
copying pyarmor.cli.core.egg-info/top_level.txt -> build/bdist.freebsd-12.0-CURRENT-amd64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
pyarmor.cli.core.__pycache__.__init__.cpython-312: module references __file__
pyarmor.cli.core.__pycache__.runtime.cpython-312: module references __file__
creating dist
creating 'dist/pyarmor.cli.core-5.4.2-py3.12.egg' and adding 'build/bdist.freebsd-12.0-CURRENT-amd64/egg' to it
removing 'build/bdist.freebsd-12.0-CURRENT-amd64/egg' (and everything under it)
Processing pyarmor.cli.core-5.4.2-py3.12.egg
creating /var/crash/ese/work/ese_virtualenv/lib/python3.12/site-packages/pyarmor.cli.core-5.4.2-py3.12.egg
Extracting pyarmor.cli.core-5.4.2-py3.12.egg to /var/crash/ese/work/ese_virtualenv/lib/python3.12/site-packages
Adding pyarmor.cli.core 5.4.2 to easy-install.pth file

Installed /var/crash/ese/work/ese_virtualenv/lib/python3.12/site-packages/pyarmor.cli.core-5.4.2-py3.12.egg
Processing dependencies for pyarmor.cli.core==5.4.2
Searching for pyarmor.cli.core.freebsd==5.4.2
Reading https://pypi.org/simple/pyarmor.cli.core.freebsd/
Download error on https://pypi.org/simple/pyarmor.cli.core.freebsd/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000) -- Some packages may not be found!
Couldn't find index page for 'pyarmor.cli.core.freebsd' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000) -- Some packages may not be found!
No local packages or working download links found for pyarmor.cli.core.freebsd==5.4.2
error: Could not find suitable distribution for Requirement.parse('pyarmor.cli.core.freebsd==5.4.2')


(ese_virtualenv) onefs-soujanya-50-1# pip list | grep py
DEPRECATION: Loading egg at /var/crash/ese/work/ese_virtualenv/lib/python3.12/site-packages/pyarmor.cli.core-5.4.2-py3.12.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
pyarmor          8.4.4
pyarmor.cli.core 5.4.2
pyarmor.cli.core 5.4.2


(ese_virtualenv) onefs-soujanya-50-1# python -c "import sys ; print(sys.platform)"
freebsd12

**Comment by jondy** [comment]
> error: Could not find suitable distribution for Requirement.parse('pyarmor.cli.core.freebsd==5.4.2') 

This package has been uploaded to pypi.org, this is pypi cache issue.

**Comment by jondy** [comment]
Fixed in 8.4.6
