### ISSUE TITLE
[BUG] Private protected function can be used from plain scripts via __dict__.

### ISSUE THREAD

**Issue by irreg** [dashingsoft/pyarmor#1608]
### Environment
- Python 3.8.9
- Pyarmor 8.4.3
- Windows 10/11 x64

```
$ pyarmor gen -O dist --assert-call foo.py
INFO     Python 3.8.9
INFO     Pyarmor 8.4.3 (trial), 000000, non-profits
INFO     Platform windows.x86_64
```

#### File Structure

root
|- a.py
|- b.py

#### a.py
```py
import b
try:
    b.a()
except Exception as e:
    print(e)
try:
    b.__dict__["a"]()
except Exception as e:
    print(e)
```

#### b.py
```py
def a():
    print("protected")
```

1. Execute: pyarmor gen --private b.py
2. Copy a.py into the dist folder
3. Move to dist folder and execute: python a.py

#### Expected result
```
unauthorized use of script (1:5174)
unauthorized use of script (1:5174)
```

#### Actual result
```
unauthorized use of script (1:5174)
protected
```

**Comment by jondy** [comment]
There is a bug, but not regard to `__dict__`, I add new one for it, refer to issue #1610

**Comment by irreg** [comment]
Thanks for the reply.
I will make sure to reference #1610.
