### ISSUE TITLE
Responding to your LinkedIn connect request.

### ISSUE THREAD

**Issue by Eirikur** [dashingsoft/pyarmor#161]
Actually, I'm opposed to your product. As a Free Software person, I feel that obfuscation denies the rights that we want to give to the user. It also makes things less reliable and maintainable. This is very much a project to remove freedom. It appears to me that you don't respect and do fear the end user. I find that to be sad. I'm an idealist, which is hard and awkward, but I continue to feel this way.

My best to you,

Eirikur

**Comment by jondy** [comment]
I understand your feeling, and I'm also looking forward to one ideal world, leaving the house without lock the door, always peace, no nay war etc. However the reality is not, at least, I think it's not. Maybe in future all the softwares are open and free, but it may take many years. On the way to the ideal world, pyarmor may help some users.

Thanks for your feedback, and I also respect your point of view. After all the world is wide, it's better to tolerance something else which you don't like but it's not harmful.

Best Regards
Jondy
