### ISSUE TITLE
[BUG] `Value Error cause by numpy array comparison operation`

### ISSUE THREAD

**Issue by Sakura4036** [dashingsoft/pyarmor#1612]
## Test Code

main.py in pack_test package:
```
import numpy as np

def func(arr):
    threshold = 3
    indices = (arr > threshold).astype(int)
    return indices

if __name__ == '__main__':
    arr = np.array([1, 4, 6, 3, 2, 5, 7])
    indices = func(arr)
    print(indices)
```

## Platform

```
Python 3.9.18
Pyarmor 8.4.4 , 000xxx, xxxx
Windows10
```

```
pyarmor gen -O pack_test_py  -r pack_test --enable-jit --obf-code 2 --outer --mix-str  --no-wrap  --enable-bcc
```

after encrypted, run main.py:
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The funny thing is that when I move the function contents to main it works fine.
```
[0, 1, 1, 0, 0, 1, 1]
```

Why is it like that?

**Comment by jondy** [comment]
BCC mode may not work with some `np` operator, no `--enable-bcc` or ignore these modules which use `np` package.

**Comment by Sakura4036** [comment]
Or I can use a `for` loop instead of the `np` operator.

**Comment by jondy** [comment]
This issue will be fixed in next release.

Verify it by pre-release
http://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.4.5.zip
