### ISSUE TITLE
Timeout / network instability for pyarmor.dashingsoft.com

### ISSUE THREAD

**Issue by chickahoona** [dashingsoft/pyarmor#1622]
Hi Jondy,

We have mulitple licenses for pyarmor that we happily use, yet the network isntability of pyarmor.dashingsoft.com is driving me crazy. There is at the moment an 80% failure rate, and as I build with buildx multiple docker containers for various architectures there are multiple requests to pyarmor.dashingsoft.com in one buildstep. I am trying now for two days, constantly retrying yet I always get a timeout.

Looking at https://github.com/dashingsoft/pyarmor/issues?q=is%3Aissue+timeout I see multiple people complaining about that problem. Is there any chance to migrate pyarmor.dashingsoft.com to a stable CDN? Something like AWS or Cloudflare or ... 

This problem is a serious productivity blocker at the moment for me. Assume that you want to release weekly and you need to kick off the buiild pipeline 10 times to get a successful build and have to do that with 3 projects across two branches (develop and master). Thats 60 times re-triggering the build pipeline to get 3 projects released.

So I beg you, please migrate this to a stable provider.

**Comment by jondy** [comment]
pyarmor.dashingsoft.com is stable, but nginx is configured to allow only 3 times in 1 mintue to request token in order to some network attacks.

If the original pipe doesn't work, try to make a little change, for example, first create build container to obfuscate all the scripts, then copy the obfuscated scripts from this container. Pyarmor also supports cross-platform obfuscating.

The other solution is Pyarmor Group license, if docker host is stable, it should work fine. And it also work on something like `self-host runner` for CI pipeline.  

Pyarmor group license may support default runner in CI pipeline in future.

**Comment by jondy** [comment]
Or start each docker container every minute, it should work if no more than 100 docker containers is used to weekly build for Pro license.

If need more than 100 docker containers in one day, Pro license won't work.

**Comment by chickahoona** [comment]
Just to clarify that these errors are indeed your ratelimit blocking things:

```
93.06 INFO     Download dynamic library musl.x86_64.7 OK
97.03 INFO     PyArmor Version 7.4.3
97.03 INFO     Python 3.10.10
97.03 INFO     Downloading dynamic library for musl.aarch64.3
97.03 INFO     Search library for platform: musl.aarch64.3
97.06 INFO     Found available libraries: ['musl.aarch64.3']
97.06 INFO     Target path for musl.aarch64.3: /root/.pyarmor/platforms/musl/aarch64/3
97.06 INFO     Downloading library file for musl.aarch64.3 ...
97.06 INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r49.3/musl.aarch64.3/_pytransform.so
110.0 ERROR    <urlopen error _ssl.c:980: The handshake operation timed out>
```

```
14.65 INFO     Downloading dynamic library for musl.x86_64.7
14.66 INFO     Search library for platform: musl.x86_64.7
14.66 INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r49.3/index.json
19.51 INFO     Create platform path: /root/.pyarmor/platforms
19.51 INFO     Write cached platform list file /root/.pyarmor/platforms/index.json
19.80 INFO     Found available libraries: ['musl.x86_64.7']
19.80 INFO     Target path for musl.x86_64.7: /root/.pyarmor/platforms/musl/x86_64/7
19.80 INFO     Downloading library file for musl.x86_64.7 ...
19.80 INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r49.3/musl.x86_64.7/_pytransform.so
39.33 ERROR    The read operation timed out
```


```
62.38 INFO     Extracting .pyarmor_capsule.zip
62.38 INFO     This keyfile has been registered successfully.
65.34 INFO     PyArmor Version 7.4.3
65.34 INFO     Python 3.10.10
65.34 INFO     Downloading dynamic library for musl.x86_64.7
65.34 INFO     Search library for platform: musl.x86_64.7
65.34 INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r49.3/index.json
83.24 INFO     Create platform path: /root/.pyarmor/platforms
83.24 INFO     Write cached platform list file /root/.pyarmor/platforms/index.json
89.25 ERROR    The read operation timed out
```

Especially that handshare timeout looks quite odd for a rate limit. And I should be well below the 3 requests per minute per ip threshhold.

Usually people setup ratelimits and try not to interfere with regular users. Cant you increase the threshhold? to something like 30 requests per hour instead of 3 requests per minute? That would still keep bad guys out and allow regular users only to run into ratelimit issues in extreme cases. Or migrate to a CDN so you don't care about ratelimits?

**Comment by jondy** [comment]
If using PyArmor Version 7.4.3, please download this file to local machine, and then copy them to docker cointainer.

Please check Pyarmor 7 document, it should document how to run Pyarmor in offline device, and where to store the downloaded files.

**Comment by chickahoona** [comment]
I assume people only reach out when they complain, so I wanted to take the time but thank you very much @jondy for fixing the timeout problem. Things run now much more stable for the 6 months or so!
