### ISSUE TITLE
I can't activate my license! I sent mail but nobody answer!

### ISSUE THREAD

**Issue by arifkadigiloglu** [dashingsoft/pyarmor#1624]
Hello,

I can't activate my group license I paid almost $200 but get nothing!

**Comment by jondy** [comment]
Please read the link in the email, read the full section of
https://pyarmor.readthedocs.io/en/latest/how-to/register.html#using-group-license

Pyarmor is well documented, please first read the documentation to learn how to use it.

**Comment by arifkadigiloglu** [comment]
I already read and apply to that steps! But still no license activation and You are doesnt reply to e-mails... WHY?

**Comment by arifkadigiloglu** [comment]
![Uploading pyarmor.png…]()

I attached screenshot.

**Comment by arifkadigiloglu** [comment]
Why you are doesn't reply e-mails?
<img width="475" alt="pyarmor" src="https://github.com/dashingsoft/pyarmor/assets/149335456/d59d3d74-e493-4bbb-af15-fd58c29c7065">

**Comment by arifkadigiloglu** [comment]
<img width="621" alt="nonprofits" src="https://github.com/dashingsoft/pyarmor/assets/149335456/b4804c10-4e7a-41f9-84e6-c8abe553ceab">

and seems like that but still seems trial no activation..
