### ISSUE TITLE
Intermittent issue with the registered license token of Pyarmor-8.4.4  in Linux and  ARM7 docker container

### ISSUE THREAD

**Issue by prasanthAllu** [dashingsoft/pyarmor#1627]
while creation of docker image, for linux and arm7 platform pyarmor installation and registration is happening fine. 

<img width="455" alt="Pyarmor-reg-success" src="https://github.com/dashingsoft/pyarmor/assets/135308407/8acb39de-6862-477b-beb7-d4263b355a6e">

But while obfuscating python source code using pyarmor gen command (/usr/local/bin/pyarmor gen -r -O <output dir> <source dir>) getting the following error intermittently.

<img width="576" alt="Pyarmor-gen-error" src="https://github.com/dashingsoft/pyarmor/assets/135308407/fe13850c-f6e6-4173-88ac-d5da49a1170c">

we are facing this issue after upgrading our pyarmor version to 8.4.4. particularly in docker environment.

Platform:  Linux, ARMv7 docker container.
Pyarmor: 8.4.4
pyarmor.cli.core: 5.4.2

**Comment by prasanthAllu** [comment]
The below error message is not consistent for us:
**"ERROR    invalid license token, try to run `pyarmor reg` to register license again"**
 
And, we aren't registering Pyarmor more than 3 times in one minute from same IP address.
 
Our setup is like:
- We create one custom docker image for Linux (base image: centos:centos7) and ARMv7 (base image: arm32v7/ubuntu:xenial) platform
- During creation of above custom image, we are installing Pyarmor (8.4.4) and pyarmor.cli.core (5.4.2). 
  And, performing pyarmor registration step using registration file. Also, to add we are using the Pyarmor Pro License
- We are using above custom image in the GitLab CI/CD pipeline. 
  Our gitlab pipeline is creating a container out of the custom image and obfuscating the python source code using pyarmor generate command.
- As per this setup pyarmor registration is done once during creation of custom image. 
  But, we are getting the error invalid license token after obfuscating the code twice or thrice.
Queries:
- We wanted to know is there a threshold limit of obfuscating the code from a registered pyarmor license. 
  Is it like after a threshold limit is reached the license become expired and we need to perform the registration again. 
- We wanted to perform the registration step only once, but somehow this is not working after upgrading the version of pyarmor to 8.4.4
  Is there a way by which we can perform the registration step once and can perform the obfuscation multiple times.

**Comment by jondy** [comment]
I think it doesn't work to register pyarmor in the image 

It should register Pyarmor in the pipeline, because Pyarmor is bind to device, each runner is different device.

For Pyarmor Pro license, in 24 hours at least 100 runners (or devices) are available.

More information please check Pyarmor license type documentation

**Comment by jondy** [comment]
And please use the latest version Pyarmor 8.4.5, it fixed one register issue
