### ISSUE TITLE
[BUG] `RuntimeError: unauthorized use of script (1:1080)`

### ISSUE THREAD

**Issue by plebbyd** [dashingsoft/pyarmor#1630]
I am first obfuscating my code using Pyarmor with the command `python -m pyarmor.cli gen -r -O dist2 src/mypkg --enable-jit`.

At this point I am able to run my script with the `main.py` file and it works as intended.

I am then trying to take the Pyarmor obfuscated code and compile it with Cython to generate .so files using the following:
```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext
ext_modules = [
    Extension("core",  ["core.py"]),
    Extension("infer",  ["infer.py"]),
    Extension("interface",  ["interface.py"]),
    Extension("utils",  ["utils.py"]),
    Extension("pyarmor_runtime_000000.__init__",  ["pyarmor_runtime_000000/__init__.py"]),
]
setup(
    name = 'AppName',
    cmdclass = {'build_ext': build_ext},
    ext_modules = ext_modules
)
```

It compiles successfully and I remove all of the files except the .so's. From here, when I try to run my `main.py`, I get the following error:

```
python main.py
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen mypkg.main>", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1116, in exec_module
  File "<frozen core>", line 228, in _call_with_frames_removed
  File "core.py", line 3, in init core
RuntimeError: unauthorized use of script (1:1080)
```

I am using Versions:
Pyarmor: 8.4.4
Cython: 3.0.6

**Comment by printpal-io** [comment]
@jondy Would you be able to point me to where it is documented?

**Comment by jondy** [comment]
You can search "unauthorized use of script" in the documentation

And in the FAQ, 
https://pyarmor.readthedocs.io/en/latest/questions.html#asking-questions-in-github
```
Before ask question, please try these solutions:
...
- Check Error Messages
...
```

In this link it also explains this error

**Comment by Lzhang-hub** [comment]
@plebbyd @printpal-io  I encountered the same problem, have you solved it? thanks.
