### ISSUE TITLE
After change device, no registration code found in pyarmor-group-device.1

### ISSUE THREAD

**Issue by arifkadigiloglu** [dashingsoft/pyarmor#1633]
C:\Users\Administrator\Desktop\.pyarmor\group>pyarmor reg pyarmor-group-device.1

INFO     Python 3.8.0
INFO     Pyarmor 8.4.5 (trial), 000000, non-profits
INFO     Platform windows.x86_64
ERROR    no registration code found in pyarmor-group-device.1

C:\Users\Administrator\Desktop\.pyarmor\group>

I get this error.

**Comment by jondy** [comment]
Please read how-to register guide in online documentation.
