### ISSUE TITLE
[BUG] DLL load failed while importing pyarmor_runtime: The specified module could not be found.

### ISSUE THREAD

**Issue by gr-phs** [dashingsoft/pyarmor#1635]
tried everything, even reinstalling python packages and upgrading to the latest python version.
here's what I'm getting:

Exception has occurred: ImportError
DLL load failed while importing pyarmor_runtime: The specified module could not be found.
  File "C:\Users\graphs\Downloads\graphstesting\graphstesting\modules\dist\pyarmor_runtime_000000\__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
  File "C:\Users\graphs\Downloads\graphstesting\graphstesting\modules\dist\main.py", line 2, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
ImportError: DLL load failed while importing pyarmor_runtime: The specified module could not be found.

**Comment by jondy** [comment]
Please first read
http://pyarmor.readthedocs.io/en/latest/topic/obfuscated-script.html

And report issue following issue template.
