### ISSUE TITLE
[BUG] `pyarmor_runtime_005112.so` built on macos amd64 not loading on macos arm64

### ISSUE THREAD

**Issue by danzat** [dashingsoft/pyarmor#1636]
I'm packing a python project on a macos amd64 host, then obfuscating it with pyarmor=8.3.7.

When trying to run the resulting executable on an arm64 mac machine, the file fails to execute due to `pyarmor_runtime_005112.so`'s unsatisfied linker requirement - namely `/usr/local/opt/gettext/lib/libintl.8.dylib`.

The steps to reproduce are very simple. For the following `test.py`:
```py
print("test")
```

Run:

```
$ pyinstaller ./test.py
$ pyarmor gen --platform darwin.x86_64 -O obfdist --pack dist/test/test ./test.py
```

Then try to run `dist/test/test` on an M1 machine, which will result in the following error:

```
Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: REDACTED/pyarmor_runtime_005112/pyarmor_runtime.so
  Reason: tried:
    '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), 
    '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), 
    '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file),
    '/usr/local/lib/libintl.8.dylib' (no such file),
    '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache)
```

Requested versions dump:
```
$ pyarmor gen -O dist --assert-call test.py
INFO     Python 3.11.6
INFO     Pyarmor 8.3.7 (pro), ---REDACTED---
INFO     Platform darwin.x86_64
```

**Comment by jondy** [comment]
Please upgrade to latest pyarmor, and check how to cross platform obfuscation in the documentation.
