### ISSUE TITLE
windows平台加密Python代码包后，在pycharm中点击加密文件可以运行，在相同的conda环境中命令行无法运行，如何解决？

### ISSUE THREAD

**Issue by Jarye0612** [dashingsoft/pyarmor#1637]
你好，通过看文档进入project打包src目录下的mypackage后，利用pycharm直接打开加密后的文件夹dist6，运行api.py可以运行，但是在命令行运行api.py报错，错误信息为：
  File "dist6\mypackage\api.py", line 2, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
ModuleNotFoundError: No module named 'pyarmor_runtime_000000'
请问相同环境下加密后的文件pycharm可以运行，命令行无法运行是什么原因，如何解决？

补充：

1.未加密前命令行可以运行，pycharm打开src可以运行mypackage里面的api.py
2.已经尝试的解决方法有在加密后的api.py中添加：
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
但添加后报测错误信息如下：
Traceback (most recent call last):
  File "<frozen __main__>", line 8, in <module>
RuntimeError: unauthorized use of script (1:1073)

**Comment by jondy** [comment]
请参阅常见问题中的通用解决方案，以及深入了解中的加密脚本，还可以搜索错误信息`unauthorized use of script`

**Comment by Jarye0612** [comment]
> 请参阅常见问题中的通用解决方案，以及深入了解中的加密脚本，还可以搜索错误信息`unauthorized use of script`

你好，受限于有些专业词汇不理解，我在pyarmor8的文档中没有搜到类似问题的解决方法，想问下该问题原因及解决方法对应的具体链接和章节
pyarmor=8.2.9
执行的加密命令是：pyarmor gen -O dist6 src/mypackage
出现的问题是：加密后，windows conda env=a pycharm run api.py能运行，windows conda env=a命令行执行python api.py无法运行
尝试在该网址（https://pyarmor.readthedocs.io/zh/latest/reference/errors.html）搜索unauthorized use of script，该问题出现在3.5.2 error4，但没有对应的解决办法
