### ISSUE TITLE
Pyarmor EULA - product serials means...?

### ISSUE THREAD

**Issue by ayakow1024** [dashingsoft/pyarmor#164]
Hi, 
I recently purchased an enterprise license. To avoid breaking any rules, I would like the following sentence in the EULA clarified.
> A enterprise license for business users. The user purchases one license
>        to use the software for one product serials of an organization."

Does "one product serials" mean something like SoftwareA ver.1 through ver.5? I need to make customization to SoftwareA a bit before releasing it as a product for each customer. Would that customization be considered part of the "one product serials"?

Answers to above would be greatly appreciated.

**Comment by jondy** [comment]
Yes, it's absolutely taken as one product for a software from ver.1 to the later version under Pyarmor's EULA.

**Comment by ayakow1024** [comment]
thank you for the clarification!
