### ISSUE TITLE
[咨询]试用版使用外部密钥，任意机器生成密钥都可运行?

### ISSUE THREAD

**Issue by jakernel** [dashingsoft/pyarmor#1645]
暂时使用试用版测试，产品使用外部密钥许可运行，发现任意机器生成的密钥都可以许可运行。
请问是不是要至少升级到基础版许可证之后，做了初始登记绑定产品，生成注册文件后，
只有用同一注册文件注册的设备，生成的密钥，才可以对本产品授权许可运行？
```
$ pyarmor -v
Pyarmor 8.4.6 (trial), 000000, non-profits
```

**Comment by jondy** [comment]
是的，所有的试用版都使用相同的密钥，购买后的许可证使用的是各自私有密钥。
