### ISSUE TITLE
__wraparmor__ in current versions

### ISSUE THREAD

**Issue by joonis** [dashingsoft/pyarmor#165]
Is it correct that `__wraparmor__` decorator functions are not longer required in current versions of pyarmor?

https://github.com/dashingsoft/pyarmor/blob/master/src/user-guide.md#use-decorator-to-protect-code-object

Instead `__wraparmor__` we can use `wrap_mode=1`, right?

**Comment by jondy** [comment]
Yes. By this way PyArmor could wrap each code object in byte-code level now.

**Comment by joonis** [comment]
Ok, thanks.

Just out of interest: Is `__wraparmor__` still supported? Because the script runs well with `wrap_mode=1` but runs into a segfault when  `__wraparmor__` is used...

**Comment by jondy** [comment]
It still supports, the code of this part isn't changed since last year. But the scripts should be obfuscated with wrapmode=0 in new versions. Here it's one test case of `__wrap_armor__` in Pyarmor's system-test scripts, and it passes in each regression test.
```
csih_inform "Case T-1.2: obfuscate module with wraparmor"
PROPATH=projects/testmod_wrap
$PYARMOR init --src=examples/testmod --entry=hello.py $PROPATH >result.log 2>&1
$PYARMOR config --manifest="include queens.py" --disable-restrict-mode=1 \
              --wrap-mode=0 $PROPATH >result.log 2>&1
...
```

**Comment by joonis** [comment]
Yes, I tried with `--wrap-mode=0`. But complex scripts run into a segfault.

Whatever, `--wrap-mode=1` seems to do the job...
