### ISSUE TITLE
Error: No PyArmor Runtime Files Found

### ISSUE THREAD

**Issue by Fretless14** [dashingsoft/pyarmor#1651]
Hi,
I've been using a script I made to obfuscate my program in a deployment script. Recently I had to downgrade my Python interpreter from 3.10 to 3.9, and I also had to update my Mac OS to Monterey 12.7.2, so somewhere along the way, Pyarmor failed to work properly.

In downgrading Python for my venv and upgrading my OS, I had to adjust my computer's Python interpreter to match what my venv is running, so I had to download Pyarmor again via pip.
I then had to re-register my license, which I did, and correctly shows my license information.

However, now running my same old script, it goes and obfuscates everything, replaces the files (packing an already built Pyinstaller executable), then when it's done, it now shows an error:
`RuntimeError: no pyarmor runtime files found`

How can I fix this? Was there a dependency I might've missed?

Thanks!
-Michael

**Comment by jondy** [comment]
Please check `topic/understanding obfuscated scripts` in the online documentation

**Comment by Fretless14** [comment]
Hi Jondy, I've been trying to fix this for hours. I've re-read your documentation many times, and I've had this working before, but after an OS update and Python downgrade it's not working anymore, with the same commands used to pack the program from pyinstaller.

It's working on my Windows computer but not my Mac and I have no idea why. I understand the runtime files are auto-generated, and it is generating a folder 'pyarmor_runtime_...' but for some reason it isn't seeing it.

I've re-registered with my license multiple times and still no avail. I just don't understand why it's working on my Windows computer and not my Mac.

**Comment by Fretless14** [comment]
I found the issue, and it may be a bug? It was working on a previous release I'm almost positive.

I'm trying to make the app usable for both darwin.x86_64 and darwin.aarch64. It's creating the runtime folder that has a folder for each runtime file:
 * runtime folder
   * __init__.py
   * darwin_aarch64
     * pyarmor_runtime.so
   * darwin_x86_64
     * pyarmor_runtime.so 


This is causing pyarmor to not find the files since they are in a subdirectory. Here is the function it's failing, 'repack' in v8.3.1:

  
```
def repack(self, obfpath, rtname, entry=None):
        buildpath = self.buildpath
        executable = self.executable
        codesign = self.codesign
        logger.info('repacking bundle "%s"', executable)

        obfpath = os.path.normpath(obfpath)
        logger.info('obfuscated scripts at "%s"', obfpath)

        name, ext = os.path.splitext(os.path.basename(executable))
        entry = name if entry is None else entry
        logger.info('entry script name is "%s.py"', entry)

        rtpath = os.path.join(obfpath, rtname)
        for item in self.contents:
            if item.endswith(EXTRACT_SUFFIX):
                pyzpath = item[:-len(EXTRACT_SUFFIX)]
                logger.info('repacking "%s"', os.path.basename(pyzpath))
                repack_pyzarchive(pyzpath, self.pyztoc, obfpath, rtname)

        for x in os.listdir(rtpath):
            ext = os.path.splitext(x)[-1]
            if x.startswith('pyarmor_runtime') and ext in ('.so', '.pyd'):
                rtbinary = os.path.join(rtpath, x)
                rtbinname = os.path.join(rtname, x)
                break
        else:
            raise RuntimeError('no pyarmor runtime files found')

        if is_darwin:
            # Not required since 8.3.0
            # from PyInstaller.depend import dylib
            # self._fixup_darwin_rtbinary(rtbinary, self.pylib_name)
            # logger.debug('mac_set_relative_dylib_deps "%s"', rtbinname)
            # dylib.mac_set_relative_dylib_deps(rtbinary, rtbinname)

            import PyInstaller.utils.osx as osxutils
            # Since PyInstaller 4.4
            if hasattr(osxutils, 'sign_binary'):
                logger.info('re-signing "%s"', os.path.basename(rtbinary))
                osxutils.sign_binary(rtbinary, identity=codesign)

        rtentry = (rtbinname, rtbinary, 1, 'b') if self.one_file_mode else None
        if not self.one_file_mode:
            dest = os.path.join(os.path.dirname(executable), rtname)
            os.makedirs(dest, exist_ok=True)
            shutil.copy2(rtbinary, dest)

        repack_executable(executable, buildpath, obfpath, rtentry, codesign

```
  
replacing that for loop with this function and setting the correct variables fixes it:
```
 def find_pyarmor_runtime(rtpath, rtname):
            for root, dirs, files in os.walk(rtpath):
                for filename in files:
                    if filename.startswith('pyarmor_runtime') and filename.endswith(('.so', '.pyd')):
                        return os.path.join(root, filename), os.path.join(rtname, filename)

            raise RuntimeError('no pyarmor runtime files found')
```

However, it chooses the first one it sees.

Was it always like this and I've just always been erroring out without realizing?

I've been wanting to deploy one app for both intel and M1 architecture, am I not allowed to do that and can only make separate distributions? I swear I got that code from someone online who had it working.

My app was working on both intel and M1 before, but now I'm wondering if it was ever being obfuscated to begin with.
