### ISSUE TITLE
[BUG] ERROR message:  this group license is reviewing by Pyarmor team

### ISSUE THREAD

**Issue by mhall-openvault** [dashingsoft/pyarmor#1653]
We just purchased the Pyarmor-group license for Pyarmor 8.0+.  When I executed the command "pyarmor reg -p XXX pyarmor-regcode-6184.txt" with XXX replaced with our product name, it gave an error message:

INFO     Python 3.11.7
INFO     Pyarmor 8.4.6 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     prepare "pyarmor-regcode-6184.txt"
INFO     query key file from server

...

INFO     process activation file "pyarmor-regcode-6184.txt"
INFO     send request to server
ERROR    this group license is reviewing by Pyarmor team

Is this an issue or do we just need to wait?  If so, for how long?  Note, this is not mentioned in the FAQ if this is a common occurrence.

Thanks,
Michael

**Comment by rmrmg** [comment]
@mhall-openvault did you solve the problem? I have the same issue and this is the only relevant link in google.
@jondy could you elaborate why it is wrong usage? The command is mentioned in documentation (https://pyarmor.readthedocs.io/en/stable/how-to/register.html#id6) as a proper and only way for initial activation of group licence.

**Comment by mhall-openvault** [comment]
I had to wait for it to be activated by the Pyarmor team.  At the time, it took a couple of hours for it to be activated.
