### ISSUE TITLE
[BUG] Unexpected ImportError from pyarmor_runtime.so on Linux

### ISSUE THREAD

**Issue by aidan-airl** [dashingsoft/pyarmor#1655]
Hi! I'm not sure if this is obvious to those who have more experience with pyarmor, but the error I'm getting isn't in the FAQ and I can't find any info to fix it.

### TLDR: 
I'm using pyarmor 8 pro, obfuscating on macOS, enabling platforms `linux.x86_64` and `darwin.x86_64`, then my simple test script suceeds on macOS but errors in an Ubuntu 22.04 VM with `ImportError: /app/pyarmor_runtime_005467/linux_x86_64/pyarmor_runtime.so: undefined symbol: _PyCode_Validate`

### Steps to reproduce:
- Have latest pyarmor installed (8.4.6)
- Have a test script (included below)
- Run `pyarmor gen` (full command below)
- Execute my test script on macOS, it succeeds
- Execute same test script on Ubuntu 22.04, it fails

### Expected results:
- Script runs the same on both platforms as specified in my `pyarmor gen` command

### Actual results:
- Script errors on one platform but not the other

### Pyarmor gen command
```
$ pyarmor gen --platform=linux.x86_64 --platform=darwin.x86_64 pyarmortest.py
INFO     Python 3.11.2
INFO     Pyarmor 8.4.6 (pro), 005467, missioncontrol_ai/ml
INFO     Platform darwin.x86_64
INFO     use runtime platforms: ['linux.x86_64', 'darwin.x86_64']

```

### Test script
```
print("Hello world")
```

### Output when running the test script:
```
root@ip-172-91-10-16:/home/aidan/dist# python3 pyarmortest.py
Traceback (most recent call last):
  File "/home/aidan/dist/pyarmortest.py", line 2, in <module>
    from pyarmor_runtime_005467 import __pyarmor__
  File "/home/aidan/dist/pyarmor_runtime_005467/__init__.py", line 49, in <module>
    __pyarmor__ = __pyarmor__().__pyarmor__
  File "/home/aidan/dist/pyarmor_runtime_005467/__init__.py", line 48, in __pyarmor__
    return __import__(name, globals(), locals(), ['__pyarmor__'], level=1)
ImportError: /home/aidan/dist/pyarmor_runtime_005467/linux_x86_64/pyarmor_runtime.so: undefined symbol: _PyCode_Validate
```

**Comment by jondy** [comment]
What's the Python version in `root@ip-172-91-10-16`?

Please make sure it's Python 3.11, that is to say, make sure it's same as build machine.

Refer to topic `insight into obfuscated scripts` in the online documentation.
