### ISSUE TITLE
[LEAKAGE] pyarmor_runtime.so file includes english information about binding

### ISSUE THREAD

**Issue by jhamed-dp** [dashingsoft/pyarmor#1656]
As developers try to encrypt their codes with pyarmor (thanks for great package), also it's important to hide binding parameters. i mean pointing to specific words like "mac address" and "harddisk info".

below is a screenshot from our pyarmor_runtime.so file : 

![image](https://github.com/dashingsoft/pyarmor/assets/84216899/23a4c7db-af90-43ab-be1c-44d8371421ce)

it's better to hide this kind of information from others too!

**Comment by jondy** [comment]
Got it. The string constants in the binary file and runtime key may be obfuscated in future version, it has been added into release plan.

But I'm not sure the released date for this feature, please check change logs to track this.

At this time, use any binary protection tool to protect `pyarmor_runtime.so`
