### ISSUE TITLE
windows平台下 license无法绑定 Mac地址   和 ipv4 地址

### ISSUE THREAD

**Issue by newjoker2** [dashingsoft/pyarmor#166]
请教一下，在管理员模式下使用pyarmor hdinfo  命令 可以获得硬盘号，但是无法获取到mac地址和ip，提示 failed to get mac address  failed to get ip address。
然后我自己查询mac 地址 和ipv4地址后生成license，替换原license后无法运行，显示  Verify license failed 。

**Comment by jondy** [comment]
如果 `pyarmor hdinfo` 无法获取 Mac地址和 ip 地址的话，license是无法绑定到 mac地址和ip地址的。

从下面的链接里面下载对应的平台 `hdinfo`, 运行一下，看提示什么错误
https://github.com/dashingsoft/pyarmor-core#hdinfo
