### ISSUE TITLE
 `Error message` wrong usage for group license

### ISSUE THREAD

**Issue by f888bet** [dashingsoft/pyarmor#1665]
Hi,
I'm using Python 3.12. I purchased pyarmor-group, I received pyarmor-regcode-6189.txt. 
From this I sucessfully activate the group license (see attached). 
However when I check my instal version I'm still on trial. why has this not upgraded to a group licence?
I have also tried the code below, but i get ERROR    wrong usage for group license
Please help!
Thanks

Microsoft Windows [Version 10.0.22621.3007]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>pyarmor register C:\Users\scrin\.pyarmor\group\pyarmor-regfile-6189.zip
INFO     Python 3.9.13
INFO     Pyarmor 8.4.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     register "C:\Users\scrin\.pyarmor\group\pyarmor-regfile-6189.zip"
INFO     refer to http://pyarmor.readthedocs.io/en/stable/how-to/register.html#using-group-license
ERROR    wrong usage for group license

C:\Windows\System32>pyarmor register
INFO     Python 3.9.13
INFO     Pyarmor 8.4.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     Current license information:

License Type    : pyarmor-trial
License No.     : pyarmor-vax-000000
License To      :
License Product : non-profits

BCC Mode        : No
RFT Mode        : No

Notes
* Can't obfuscate big script and mix str

```

![pyarmor install](https://github.com/dashingsoft/pyarmor/assets/157284147/1b20f305-f9db-45f7-a350-a813f238e18c)

![pyarmor install 2](https://github.com/dashingsoft/pyarmor/assets/157284147/5ef84e3f-9c6e-41e7-8ca9-8e238c3771b3)

**Comment by jondy** [comment]
Please check the output log, it has told you the solution to read this link
http://pyarmor.readthedocs.io/en/stable/how-to/register.html#using-group-license

**Comment by f888bet** [comment]
I read the link, 100 times!!!

Why do I only see a trial licence when I run this command? Not the same as the documentation


$ pyarmor reg -g 1

INFO     Python 3.12.0
INFO     Pyarmor 8.4.2 (group), 006000,

Sent from my iPhone

On 22 Jan 2024, at 01:41, Jondy ***@***.***> wrote:

﻿

Please check the output log, it has told you the solution to read this link
http://pyarmor.readthedocs.io/en/stable/how-to/register.html#using-group-license

**Comment by jondy** [comment]
> $ pyarmor reg -g 1                                                 
  INFO     Python 3.12.0                                             
  INFO     Pyarmor 8.4.2 (group), 006000,

Sorry, this is doc error, it should be `INFO     Pyarmor 8.4.7 (trial), 000000, non-profits` when first run `pyarmor reg`

I'll update the doc soon, thanks.
