### ISSUE TITLE
Is there an easy way to add additional information to the license key?

### ISSUE THREAD

**Issue by fzumstein** [dashingsoft/pyarmor#167]
Let's say I'd like to embed additional information in the license key e.g. what plan the user bought (e.g. "starter", "pro") - is that possible?

**Comment by jondy** [comment]
Yes. You could pass any extra data by option `--bind-data` in the command `licenses`,  and got it in the obfuscated scripts by this way:
```
from pytransfrom import get_license_info
info = get_license_info()
print(info['DATA'])
```
Refer to https://pyarmor.readthedocs.io/en/latest/man.html#licenses

**Comment by fzumstein** [comment]
Gotcha, thanks!
