### ISSUE TITLE
[BUG] "pyarmor_runtime.so" is damaged and can't be opened. MacOS aarch64

### ISSUE THREAD

**Issue by EmberLightVFX** [dashingsoft/pyarmor#1673]
I'm trying to build my script to work on M1 mac computers.
I'm generating the script using `pyarmor gen --platform darwin.aarch64 -O obfdist ./test.py`
When I try to run the script on my M1 machine I'm getting a big error that the "pyarmor_runtime.so" is broken and can't be opened.

![image](https://github.com/dashingsoft/pyarmor/assets/49758407/dfcdf433-562d-4261-a81d-fccf10a48b79)

I'm guessing the MacOS aarch64 build is broken.

This is the full traceback I'm getting from the terminal:

```
Traceback (most recent call last):
  File "/Users/lloyd/Desktop/license/DEMO/obfdist/test.py", line 2, in <module>
    from pyarmor_runtime_006141 import __pyarmor__
  File "/Users/lloyd/Desktop/license/DEMO/obfdist/pyarmor_runtime_006141/__init__.py", line 50, in <module>
    __pyarmor__ = __pyarmor__().__pyarmor__
                  ^^^^^^^^^^^^^
  File "/Users/lloyd/Desktop/license/DEMO/obfdist/pyarmor_runtime_006141/__init__.py", line 49, in __pyarmor__
    return __import__(name, globals(), locals(), ['__pyarmor__'], level=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Users/lloyd/Desktop/license/DEMO/obfdist/pyarmor_runtime_006141/py312/darwin_aarch64/pyarmor_runtime.so, 0x0002): tried: '/Users/lloyd/Desktop/license/DEMO/obfdist/pyarmor_runtime_006141/py312/darwin_aarch64/pyarmor_runtime.so' (code signature in <84AB923E-2017-33FC-9555-FCF5650A1FD1> '/Users/lloyd/Desktop/license/DEMO/obfdist/pyarmor_runtime_006141/py312/darwin_aarch64/pyarmor_runtime.so' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/lloyd/Desktop/license/DEMO/obfdist/pyarmor_runtime_006141/py312/darwin_aarch64/pyarmor_runtime.so' (no such file), '/Users/lloyd/Desktop/license/DEMO/obfdist/pyarmor_runtime_006141/py312/darwin_aarch64/pyarmor_runtime.so' (code signature in <84AB923E-2017-33FC-9555-FCF5650A1FD1> '/Users/lloyd/Desktop/license/DEMO/obfdist/pyarmor_runtime_006141/py312/darwin_aarch64/pyarmor_runtime.so' not valid for use in process: library load disallowed by system policy)
lloyd@MacBook-Pro obfdist % 
```

After reading some more about the error `library load disallowed by system policy` it seems like the .so file isn't signed correctly

----

EDIT: I tried to re-sign the file myself and after I re-signed it it works as expected. So you'll need to re-sign the file

-----

```
INFO     Python 3.12.0
INFO     Pyarmor 8.4.6 (group), 006141, aesl
INFO     Platform windows.x86_64
```

**Comment by jondy** [comment]
Please make sure the default sign plugin is not changed, or write your own plugin to sign it

**Comment by mihirsaudagar** [comment]
>
> EDIT: I tried to re-sign the file myself and after I re-signed it it works as expected. So you'll need to re-sign the file
> 
> ```
> INFO     Python 3.12.0
> INFO     Pyarmor 8.4.6 (group), 006141, aesl
> INFO     Platform windows.x86_64
> ```

Hi Emberlight,

Can you help me with the code re-sign process? how did you re-sign the file?

**Comment by EmberLightVFX** [comment]
@jondy the bug still persist on your side, I just did my tests to figure out what was wrong.
Currently the pyarmor_runtime.so file that gets downloaded from your server when setting the platform to darwin.aarch64 is not correctly signed and the generated code won't run on arm64 macs.

@mihirsaudagar I can't help you sadly. It was a friend of mine that helped me resign the files. I have no idea how to do it myself.

**Comment by EmberLightVFX** [comment]
@jondy I want to ping you that this is still a bug on pyarmors side.
I can't run any script that's build with darwin.aarch64.
I really need this bug to be fixed.

**Comment by jondy** [comment]
It need code sign tool in build machine to sign binary, generally there is no such tool in Windows, this is not what Pyarmor could do, pelease refer to Apple Doc to learn about code sign.

**Comment by EmberLightVFX** [comment]
The binary file `pyarmor_runtime.so` that pyarmor automatically downloads when building for `darwin.aarch64` is not correctly signed. It has nothing to do with my own code and nothing to do with windows.
The file `pyarmor_runtime.so` that pyarmor downloads is wrongly signed and makes pyarmor-compiled code not being able to run on M1 mac computers.

**Comment by jondy** [comment]
Not exact.

The `pyarmor_runtime.so` will be patched by Pyarmor when generating runtime package, so it need be re-signed after building. In MacOS, it will be re-signed automatically by plugin with calling command line tool `codesign`

In future, Pyarmor may not patch `pyarmor_runtime.so` when enable some option so that it need not re-sign `pyarmor_runtime.so` after building.

**Comment by EmberLightVFX** [comment]
Oh ok. Why does darwin.x86_64 still work? Is it because it's x86?
What would it take to make it so there isn't any re-sign needed for pyarmor_runtime.so? I need to be able to build for darwin.aarch64 but we don't have a M1 mac ourself.

**Comment by ubmarco** [comment]
Maybe [zsign](https://github.com/zhlynn/zsign) is a cross OS option. Haven't tried it.

**Comment by robertcdickson** [comment]
Hi, I am also getting this when trying to sign my code on MacOS aarch64. I noticed in the release notes of 8.5.5 there is a configuration item `runtime:patch_extension` but there are no instructions on what value to set this to "solve code sign issue in Darwin". Is this config item the answer to this issue and if so how can I use it?

**Comment by jondy** [comment]
Just run `pyarmor cfg patch_extension = 0`, then generate the obfuscated scripts again.
