### ISSUE TITLE
Create license key witout writing to disk

### ISSUE THREAD

**Issue by fzumstein** [dashingsoft/pyarmor#168]
Is there a way to generate a license key in code without writing it to a file on disk? I want to create license keys on AWS Lambda and anything but `/tmp` is read-only so the following code fails even if I point `--output` to `/tmp`:

```
call_pyarmor(f'licenses --expired {expiry} --output /tmp trial'.split())
```

Error:

```
{
  "errorMessage": "[Errno 30] Read-only file system: '/var/task/pyarmor/license.lic'",
  "errorType": "OSError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 11, in lambda_handler\n    call_pyarmor(f'licenses --expired {expiry} --output /tmp trial'.split())\n",
    "  File \"/var/task/pyarmor/pyarmor.py\", line 1127, in main\n    pytransform_bootstrap(capsule=DEFAULT_CAPSULE)\n",
    "  File \"/var/task/pyarmor/utils.py\", line 80, in pytransform_bootstrap\n    shutil.copy(os.path.join(path, 'license.tri'), licfile)\n",
    "  File \"/var/lang/lib/python3.8/shutil.py\", line 409, in copy\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n",
    "  File \"/var/lang/lib/python3.8/shutil.py\", line 259, in copyfile\n    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:\n"
  ]
```

**Comment by jondy** [comment]
The problem is that pyarmor bootstrap fails. Could you create `/var/task/pyarmor/license.lic` before run command `pyarmor licenses`?  For example,
```
cd /var/task/pyarmor
cp license.tri license.lic
```
If this file exists, `pyarmor licenses` should work.

**Comment by fzumstein** [comment]
The file still needs to be writable even if it exists so I can't seem to make it work with aws lamda unfortunately. I switched to a different deployment mechanism now to fix this. Still, if somebody figures this out one day would be great.

**Comment by VeNoMouS** [comment]
I too was wondering the same... it seems stupid to force only to disk, why can’t we simply output it to a string or something so we can store into a database etc, generating to a flat file can create a race condition when in conjunction with an api for example, you would have to create a queuing system to run each job singular to create ... it doesn’t scale

**Comment by jondy** [comment]
It's not difficult to implement this, I'll add this feature next version (v5.9.0) by special option value `--output stdout`

**Comment by VeNoMouS** [comment]
is it possible to do this in native python?

ie 
```
import pyarmor

dict = pyarmour.licenses.generate(.....)
```

**Comment by VeNoMouS** [comment]
also @jondy , is it possible to change the licenses stuff to follow epoch , rather than the local timezone it was generated on? that way if you want to expire on say the 1st of the month, you dont need to +1 day if your local timezone is in the future.. (ie im in new zealand)

**Comment by jondy** [comment]
No problem, in the v5.9.0, it will provide a function `pyarmor.licenses` may like this
```
def licenses(name='reg-001', expired=None, bind_disk=None,
             bind_mac=None, bind_ipv4=None, bind_data=None):
    ...
```
And `expired` also could be a float as epoch

**Comment by VeNoMouS** [comment]
omg, that would be awesome, saves me working out your code and implementing my own functionality , thanks @jondy ❤️

**Comment by jondy** [comment]
It returns a str of the generated license. Use it in web API may like this:
```
from zipfile import ZipFile
from pyarmor.pyarmor import DEFAULT_CAPSULE, licenses as generate_licenses
key = ZipFile(DEFAULT_CAPSULE, 'r').read('private.key')

# Then generate license with this cached key
print('my license:' + generate_licenses(expired=xxxx, key=key)
```

**Comment by jondy** [comment]
pyarmor v5.9.0 is released

**Comment by VeNoMouS** [comment]
❤️ 'ing the quick turn around , thanks @jondy
