### ISSUE TITLE
Regarding registration problem

### ISSUE THREAD

**Issue by a4865g** [dashingsoft/pyarmor#1682]
Hi,

If I register device 1 offline (reg -g 1) and then this device 1 is not used anymore, is there any way to unregister or override (e.g. device 2 is also tied to reg -g 1)?

The only relevant part of this line is in the doc.
![image](https://github.com/dashingsoft/pyarmor/assets/43570004/56aa195c-0878-4163-bf72-2be2daed12d9)

Just wanted to double check that there is no such thing as "deregistration", thanks!

**Comment by jondy** [comment]
No, there is no `deregistering` feature.

For most of projects, 100 offline build machines should be OK.
