### ISSUE TITLE
Manually packing a pyarmor obfuscated file

### ISSUE THREAD

**Issue by ForlaxPy** [dashingsoft/pyarmor#169]
So I'm here with an obfuscated file that I'm trying to manually pack using pyinstaller. The documentation didnt really give details about it so I'm left with bunch of errors here and there, what files should I include the license.lic + pytransform.dll + pytransform.key using `--add-data` ? Also there was something about editing the .spec file, no clue what I gotta do there too. 
In other words, what steps should I be taking for a successfully packing this script and getting it to work properly.

**Comment by jondy** [comment]
> what files should I include the license.lic + pytransform.dll + pytransform.key using --add-data?
You need run the command `pyinstaller` to generate `hello.spec`, here `hello.py` should be replaced with your actual entry script. If it's `main.py`, the output file will be `main.spec`
```
pyinstaller --add-data dist/obf/license.lic;.
            --add-data dist/obf/pytransform.key;.
            --add-data dist/obf/_pytransform.*;.
            -p dist/obf --hidden-import pytransform
            hello.py
```
Then you need edit the `main.spec` as described in the document
https://pyarmor.readthedocs.io/en/latest/how-to-do.html#how-to-pack-obfuscated-scripts
```
src = os.path.abspath('.')
obf_src = os.path.abspath('dist/obf')
...
```
Note that if your scripts isn't in the current path, you should replace '.' with actual path.

**Comment by ForlaxPy** [comment]
@jondy the problem is that I don't have the unobfuscated version of the script I'm trying to pack. Can I still run the process using mainly the obfuscated script?

**Comment by jondy** [comment]
It's difficult to pack the obfuscated scripts without the original scripts, because all the dependent packages and modules couldn't be found any more after the the scripts have been obfuscated. The only way is to add these dependencies by `--hidden-import`, but I think it will spent a lot of time to find these missing packages.

**Comment by ForlaxPy** [comment]
Alright will try doing that! Thanks so much for your help and support ^^. Happy new year.
