### ISSUE TITLE
[BUG] `Unable to activate pyarmor group license for Python 3.10 version`

### ISSUE THREAD

**Issue by DeepTech7** [dashingsoft/pyarmor#1690]
I am unable to activate Pyarmor 8.0 in Python 3.10 environment. It was working as expected in Python 3.10. Due to few critical vulnerabilities we migrated our code base from Python 3.7 to Python3.10. After our code base update, I am not able activate pyarmor group license.  

![WhatsApp Image 2024-02-14 at 6 50 15 PM](https://github.com/dashingsoft/pyarmor/assets/140964509/6fe89c3d-cc80-4e49-bc3a-f14b33b9f16f)

**Comment by jondy** [comment]
Please check 
http://pyarmor.readthedocs.io/en/latest/how-to/register.html#using-group-license

And generate new device license for this machine.
