### ISSUE TITLE
[BUG] `Tuple index out of range using polars > 0.18.3`

### ISSUE THREAD

**Issue by gabrielmocanu** [dashingsoft/pyarmor#1693]
# Environment
```
pyarmor --version
Pyarmor 8.4.7 (pro)
```

# Reproduced steps:
I am using [polars] in one of my projects and encountered an issue. To be easier I will give an example:

```
import polars as pl
from dateutil import parser


def parse_datetime(datetime_str: str):
    return parser.parse(datetime_str)


dataframe = pl.DataFrame({
    'column_a': ['Apr 11, 2022 12:00:00 UTC', 'Apr 12, 2022 12:00:00 UTC', 'Apr 13, 2022 12:00:00 UTC'],
})


result = dataframe.select(pl.col('column_a').alias(
    'column_a_alias').apply(parse_datetime, skip_nulls=False))

print(result)
```

This works well if it's **not** obfuscated OR obfuscated and using polars <= 0.18.3. 
**After** obfuscating by using `pyarmor gen` command and update **polars** package to anything higher than **0.18.3**, I got this error:

```
  File "/usr/lib/python3.11/dis.py", line 467, in _get_instructions_bytes
    argval, argrepr = _get_name_info(arg, get_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dis.py", line 390, in _get_name_info
    argval = get_name(name_index, **extrainfo)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
```

| PyArmor Version  | Polars Version |  Obfuscated  | Works |
| --------------- | --------------- | --------------- | --------------- |
| -  | *.*.*  | No  | Yes  |
| 8.4.7  | 0.20.8  | Yes  | No  |
| 8.4.7  | 0.19.5  | Yes  | No  |
| 8.4.7  | 0.18.15  | Yes  | No  |
| 8.4.7  | 0.18.3  | Yes  | Yes  |

[polars]: https://pola.rs/

**Comment by jondy** [comment]
Using `dis.py` to inspect obfusated scripts may or may not work, it won't be fixed.
