### ISSUE TITLE
from .pyarmor_runtime_000000 import __pyarmor__ ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by Zhaofan2021** [dashingsoft/pyarmor#1694]
加密后的py文件，进行运行时，总是出现  from ..pyarmor_runtime_000000 import __pyarmor__
ImportError: attempted relative import with no known parent package,父路径错误。
把"."去掉，把引用模块，复制到目录下，才能运行。
这种情况怎么解决？

**Comment by jondy** [comment]
请参阅文档，深入了解加密脚本

**Comment by Mars626** [comment]
我也遇到这个问题了，整个工程加密，就是引用不到上级目录，查阅了文档没有找到解决方式。
我的解决方式是不使用递归方式-r创建加密,直接/data/test/. 对整个目录加密，这样加密后的引用是没有前面那个.的，然后单独写一个脚本，将辅助包复制到每个目录下，让每个文件能引用到自己目录下的辅助包。
