### ISSUE TITLE
License Automatically Downgraded to Trial Version

### ISSUE THREAD

**Issue by alcngzz** [dashingsoft/pyarmor#1696]
I encountered an issue where my working license was automatically downgraded to the trial version. When I attempted to reactivate it, I received an error message. I did not make any changes that would trigger this downgrade. Below are the steps I took and the error I encountered:

1. Initially, I encrypted my file using Pyarmor with the command pyarmor gen fileadi.py. This process completed successfully
2. When I tried to encrypt the file again using the same command, the operation failed, and I received a warning indicating that I was using a trial version.

It's worth noting that I did not reinstall Windows or make any significant changes to my system. This issue started occurring approximately one hour after the first encryption process.

**Terminal Logs**

```
C:\pyarmor reg -p "MAS" .\pyarmor-regcode-6066.txt
INFO     Python 3.11.4
INFO     Pyarmor 8.2.9 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     prepare ".\pyarmor-regcode-6066.txt"
INFO     query key file from server
This license registration information will be

License Type    : pyarmor-group
License To      : **********************
License Product : MAS

This license is about to be used for product "MAS"

Are you sure to continue? (yes/no) yes
INFO     process activation file ".\pyarmor-regcode-6066.txt"
INFO     send request to server
ERROR    This code has been activated, it can not be used again
```

**Comment by alcngzz** [comment]
++

I updated the version, the result is the same:

```
pyarmor reg -p MAS .\pyarmor-regcode-6066.txt
INFO Python 3.11.4
INFO Pyarmor 8.4.7 (trial), 000000, non-profits
INFO Platform windows.x86_64
INFO prepare ".\pyarmor-regcode-6066.txt"
INFO query key file from server
This license registration information will be

License Type: pyarmor-group
License To: M***************
License Product: MAS

This license is about to be used for product "MAS"

IMPORTANT: PRODUCT NAME CAN NOT BE CHANGED AFTER INITIAL REGISTRATION

Are you sure to continue? (yes/no) yes
INFO process activation file ".\pyarmor-regcode-6066.txt"
INFO send request to server
ERROR This code has been activated, it can not be used again
```

**Comment by jondy** [comment]
Please activation file `pyarmor-regfile-6066.zip` for second registration, do not use `pyarmor-regcode-6066.txt` again.

And try to make a new device file with new version.

About usage of group license, please check
https://pyarmor.readthedocs.io/en/latest/how-to/register.html#using-group-license
