### ISSUE TITLE
Debuggers don't respect breakpoints after importing obfuscated library

### ISSUE THREAD

**Issue by fzumstein** [dashingsoft/pyarmor#170]
When using debuggers in PyCharm or VSCode, they seem to ignore any breakpoints whenever  there is an import of an obfuscated library. E.g. 

```
import myobfuscated_package

print('test') # setting a breakpoint here won't be respected
```

Is that expected?

**Comment by jondy** [comment]
Yes, the obfuscated code could not be debugged.

**Comment by fzumstein** [comment]
That the obfuscated code itself cannot be debugged is clear, but that a non obfuscated script that imports obfuscated code can't be debugged neither was a bit surprising.
