### ISSUE TITLE
[BUG] `Encryption of variable names causes locals() to fail to obtain key values`

### ISSUE THREAD

**Issue by githubsavelib** [dashingsoft/pyarmor#1703]
Hello, I'm trying to encrypt a piece of code containing locals()['x'] by default in the latest version of pyarmor, but since pyarmor changes the names of all local variables, such as _var_var_0, locals() won't be found to my x key value will result in an error, what parameters can I use to turn this feature off, is turning it off more likely to introduce serious potential security risks? Here is my sample code, thanks for any help anyway.

test.py

def x():
    x=1
    print(locals())
    print(locals()['x'])
x()

pyarmor gen test.py

cd dist

python3 test.py

{'_var_var_0': 1}
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen test>", line 5, in <module>
  File "<frozen test>", line 4, in x
KeyError: 'x'

**Comment by jondy** [comment]
Use this configuration to disable this feature
```
pyarmor cfg mix_localnames=0
```

Then obfuscate the scripts again
