### ISSUE TITLE
`pyarmor hdinfo` fails

### ISSUE THREAD

**Issue by newbieh4cker** [dashingsoft/pyarmor#171]
OS : Ubuntu 18.04 x86
Pyamor : 5.8.9

pyarmor hdinfo
INFO     PyArmor Version 5.8.9
Faild to get harddisk information.
Mac address: "0c:9d:92:xx:xx:xx"
Faild to get ip address.
Domain name: "(none)"

**Comment by newbieh4cker** [comment]
[update]

using 'sudo' fixed harddisk information, but still getting ip addr failes

sudo ./hdinfo
HDIO_GET_IDENTITY: Inappropriate ioctl for device
ioctl SG_IO: Inappropriate ioctl for device
Serial number of first harddisk: "S467NXXXXXXXXX"
Mac address: "0c:9d:92:xx:xx:xx"
ioctl: Cannot assign requested address
Faild to get ip address.
Domain name: "(none)"

**Comment by jondy** [comment]
> ioctl: Cannot assign requested address

One possible reason is that there is no available ports.

**Comment by newbieh4cker** [comment]
what do you mean by 'available ports' ???

**Comment by jondy** [comment]
If there are so many temporary tcp or udp connections in the server,  and the ports aren't released in time, it will report this error.
