### ISSUE TITLE
也是蛮牛的，web-ui导出个单文件直接把我整个目标目录递归删除掉了

### ISSUE THREAD

**Issue by xander-wang** [dashingsoft/pyarmor#1725]
写这种危险的操作不加个判断或者提示吗？

**Comment by jondy** [comment]
能写的具体一点吗？

**Comment by xander-wang** [comment]
可以复现，pyarmor-webui配置一个任务，输出路径选一个非空的路径，打包后该路径会被清空。

**Comment by jondy** [comment]
后台是 pyarmor 7 还是 pyarmor 8?

原来的版本 webui 2.2 的话，pyarmor 8 会在控制台有提示的，是 pyinstaller 的提示

昨天发布了一个新版本 2.3，后台是 pyarmor 8 的话可以在界面选择是否清空输出目录，pyarmor 7 没有改动
