### ISSUE TITLE
package_name_format 好像无法重命名成独立的运行辅助包

### ISSUE THREAD

**Issue by wolf95985** [dashingsoft/pyarmor#1731]
![屏幕截图 2024-04-09 164619](https://github.com/dashingsoft/pyarmor/assets/32558696/fd202a0d-ec22-4827-900d-c4f262d1d872)
![屏幕截图 2024-04-09 164708](https://github.com/dashingsoft/pyarmor/assets/32558696/916cb617-60cc-4511-a30c-7d8d027bff98)
![屏幕截图 2024-04-09 165327](https://github.com/dashingsoft/pyarmor/assets/32558696/ea384836-4463-4970-a0bc-add15c124a2f)
无论我怎么设置，都会出现一个pyarmor_runtime_XXXXXX的包，我不知道是不是必然会如此？还是需要专家版？

**Comment by jondy** [comment]
试用版不可以修改运行辅助包的名称，其他都可以的

**Comment by wolf95985** [comment]
可能是我没有描述清楚，我的是基础版，从图片中可以看到，我的全局，本地都设置了package_name_format的值，但是除了生成package_name_format所设置的名称的包外（在这里名称是one），还是会生成一个pyarmor_runtime_XXXXXX的包（也就是说会生成两个包）。在我的理解里，如果我设置了package_name_format的值，pyarmor_runtime_XXXXXX这个包不应该出现了，只有one这一个包

**Comment by jondy** [comment]
先把输出目录全部删除了在测试一下

**Comment by wolf95985** [comment]
测试了一下，现在可以了。不过我明明记得之前是删除了输出目录的。非常感谢你的回答和耐心
