### ISSUE TITLE
Compatibility issue with darwin.x86_64 when packed python files on darwin.aarch64 

### ISSUE THREAD

**Issue by hamsaEVR** [dashingsoft/pyarmor#1737]
I am building a application on darwin.aarch64 using pyarmor and the command below 
pyarmor version - 7.7.4
python - 3.8.18

```pyarmor pack -e " --onefile" support_tool.py```
I can open this app on my m3 mac but I am facing issues while running the same build on Mac darwin.x86_64 laptop. 
below is the screenshot of the application run on darwin.x86_64
 
![Screenshot 2024-03-24 at 7 23 47 PM](https://github.com/dashingsoft/pyarmor/assets/160695386/6c731153-9380-42a0-8d7d-55a02d75acef)

I have tried `--platform darwin.x86_64` while packing but that errors out

**Comment by jondy** [comment]
Please check solution here
https://pyarmor.readthedocs.io/en/v7.7.4/questions.html#the-final-bundle-does-not-work

But i'm not sure pack could work for cross-platform
