### ISSUE TITLE
Symbol not found in flat namespace '_PyCode_GetCode'

### ISSUE THREAD

**Issue by manandey** [dashingsoft/pyarmor#1738]
I have obfuscated my package using PyArmor version (latest version), command `pyarmor gen -O dist package_name` and when I try to run the obfuscated version, I get the error: 

` from .pyarmor_runtime import __pyarmor__
ImportError: dlopen(/Users/****/Documents/GitHub/***/dist/pyarmor_runtime_000000/pyarmor_runtime.so, 0x0002): symbol not found in flat namespace '_PyCode_GetCode'
`
My current python version is: `Python 3.9.6`

**Comment by jondy** [comment]
Please first read getting-started tutorial documentation

**Comment by lijiaxing1997** [comment]
I also have this problem. The package I made on the mac m4 chip has this error on the m1.

**Comment by lijiaxing1997** [comment]
Sorry, there is indeed a difference in the version. There is no problem now.

**Comment by guayo** [comment]
I'm also getting the same error "symbol not found in flat namespace '_PyCode_NewWithPosOnlyArgs'"
M1 Sequoia
Python 3.13
