### ISSUE TITLE
[BUG] `ERROR    unsupported arch`

### ISSUE THREAD

**Issue by EVAUTOAI** [dashingsoft/pyarmor#1739]
We are getting 2 architecture related errors.

**_Error 1:_**
_Got below error on a RHEL machine:_
INFO     Python 3.11.5
INFO     Pyarmor 8.5.2 (trial), 000000, non-profits
ERROR    unsupported arch "ppc64le"
ERROR    somthing is wrong
*=============================================================*
*  Please enable debug option `-d` to run it again            *
*    pyarmor -d gen options ...                               *
*                                                             *
*  Then check console log to find more information            *
*                                                             *
*  Please also check                                          *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*  or run `pyarmor man` to find solutions quickly             *
*=============================================================*

**_Error 2:_**
In another Mac machine, the obfuscation is happening, but when we try to run the code, its throwing below error:
ImportError: dlopen(/Volumes/demo/pyarmor_runtime_000000/pyarmor_runtime.so, 0x0002): tried: '/Volumes/demo/pyarmor_runtime_000000/pyarmor_runtime.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Volumes/demo/pyarmor_runtime_000000/pyarmor_runtime.so' (no such file), '/Volumes/demo/pyarmor_runtime_000000/pyarmor_runtime.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))

Even though the file'/Volumes/demo/pyarmor_runtime_000000/pyarmor_runtime.so' exists

What do we do?

**Comment by jondy** [comment]
Just as log said
 
Please check 
https://pyarmor.readthedocs.io/en/latest/questions.html

BTW, arch `ppc64le` is still not supported by pyarmor, and cross-platform need use extra option `--platform`
