### ISSUE TITLE
[BUG]pyarmor-webui 2.3 Output "D:/wfl\dist" is not empty

### ISSUE THREAD

**Issue by hayingbs** [dashingsoft/pyarmor#1743]
pyarmor=8.5.2 pyinstall=5.8 pyarmor-webui=2.3 python =3.9
打包之前清空整个输出目录 不管勾不勾选 都是报错：
Traceback (most recent call last):
File "C:\Users\haihai.conda\envs\wfl\lib\site-packages\pyarmor\webui\server.py", line 81, in do_POST
result['data'] = self.root_handler.dispatch(self.path[1:], args)
File "C:\Users\haihai.conda\envs\wfl\lib\site-packages\pyarmor\webui\handler.py", line 49, in dispatch
return handler.dispatch(path[i+1:], args)
File "C:\Users\haihai.conda\envs\wfl\lib\site-packages\pyarmor\webui\handler.py", line 43, in dispatch
return getattr(self, 'do_' + path)(args)
File "C:\Users\haihai.conda\envs\wfl\lib\site-packages\pyarmor\webui\handler8.py", line 448, in do_build
return self._build_temp(args, debug=debug)
File "C:\Users\haihai.conda\envs\wfl\lib\site-packages\pyarmor\webui\handler8.py", line 388, in _build_temp
return self._build_target(path, args, debug=debug)
File "C:\Users\haihai.conda\envs\wfl\lib\site-packages\pyarmor\webui\handler8.py", line 354, in _build_target
raise RuntimeError('Output "%s" is not empty' % output)
RuntimeError: Output "D:/wfl\dist" is not empty
127.0.0.1 - - [18/Apr/2024 23:05:15] "POST /project/build HTTP/1.1" 200 -
不会用命令，能帮我写一下吗？
下面是我的代码结构：
![image](https://github.com/dashingsoft/pyarmor/assets/99177908/e1263861-1f3b-4b1c-a401-60bfb0543bfc)

**Comment by jondy** [comment]
很抱歉，请自己学习如何使用命令行

请先做一个简单测试，创建一个空目录，只放一个简单的 foo.py 文件，然后打包尝试一下。

**Comment by jondy** [comment]
另外，请提交选中清空输出目录之后的错误日志

**Comment by jondy** [comment]
对了，输出目录的长度至少要四个以上，尝试设置输出目录为 `dist2`

**Comment by jondy** [comment]
不熟悉命令行也可以使用 `pyarmor man` 是一个新的图形界面，可以直接选择选项执行

**Comment by hayingbs** [comment]
我这之前试过了用的&nbsp;dist1


希望在左上角
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 中午11:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG]pyarmor-webui 2.3 Output "D:/wfl\dist" is not empty (Issue #1743)





 
对了，输出目录的长度至少要四个以上，尝试设置输出目录为 dist2

**Comment by jondy** [comment]
不要设置 output 目录，设置为空，默认输出就是 $src/dist

如果填写了目录，会出现目录不为空的错误，这个问题会在下一个版本 pyarmor-webui 2.4 中解决

**Comment by hayingbs** [comment]
pyarmor man 失败， 版本不对吗？







希望在左上角
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 下午2:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG]pyarmor-webui 2.3 Output "D:/wfl\dist" is not empty (Issue #1743)





 
不熟悉命令行也可以使用 pyarmor man 是一个新的图形界面，可以直接选择选项执行

**Comment by hayingbs** [comment]
pyarmor man 失败， 版本不对吗？
或者 付费200，教教我命令。我的微信是15802198733






希望在左上角
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 下午2:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG]pyarmor-webui 2.3 Output "D:/wfl\dist" is not empty (Issue #1743)





 
不熟悉命令行也可以使用 pyarmor man 是一个新的图形界面，可以直接选择选项执行

**Comment by hayingbs** [comment]
log&nbsp; 没有找到&nbsp; from pyarmor.man.cli import main_entry&nbsp; &nbsp;我的版本太新了吗？&nbsp;&nbsp;


2820 MainProcess 2024-04-19 15:18:04,526
Traceback (most recent call last):
&nbsp; File "C:\Users\haihai\.conda\envs\wfl\lib\site-packages\pyarmor\cli\__main__.py", line 757, in main
&nbsp; &nbsp; main_entry(sys.argv[1:])
&nbsp; File "C:\Users\haihai\.conda\envs\wfl\lib\site-packages\pyarmor\cli\__main__.py", line 745, in main_entry
&nbsp; &nbsp; return args.func(ctx, args)
&nbsp; File "C:\Users\haihai\.conda\envs\wfl\lib\site-packages\pyarmor\cli\__main__.py", line 339, in cmd_man
&nbsp; &nbsp; from pyarmor.man.cli import main_entry
ModuleNotFoundError: No module named 'pyarmor.man'



希望在左上角
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 下午2:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG]pyarmor-webui 2.3 Output "D:/wfl\dist" is not empty (Issue #1743)





 
不熟悉命令行也可以使用 pyarmor man 是一个新的图形界面，可以直接选择选项执行

**Comment by jondy** [comment]
刚才不知道怎么操作的，填写了一个目录之后出现目录不为空的错误。

但是现在无论如何操作，都是好着的，没有出现错误。

很抱歉，目前不提供使用服务，因为 pyarmor 本身就是一个命令行工具，只要了解其选项，所有的功能都是通过选项实现的。

开发组主要是解决 bug 的，如果不是 bug，而是使用方面的问题，请自己参考文件进行学习。

目前这个问题我这边不能重现，我的操作步骤

1. 打开 pyarmor-webui
2. 点击 打包加密向导
3. 选择源路径 `c:/adminsitrator/test`
4. 选择主脚本 `foo.py`
5. 点击 打包按钮

提示打包成功，请按照以上步骤进行打包。

如果失败，请按照上面的步骤描述你的具体操作步骤。

如果是 bug，开发组会修改的。

另外，不建议你使用 pyarmor.man
