### ISSUE TITLE
[BUG] Unable to bundle binary when using pyinstaller options and pack

### ISSUE THREAD

**Issue by kyranops** [dashingsoft/pyarmor#1748]
AI am facing an issue where I am unable to successfully pack my script after adding binary via pack:pyi_options
Without the added options, I could pack successfully. I was also able to generate via pyinstaller using a spec file, hence unlikely and issue with my python files
![image](https://github.com/dashingsoft/pyarmor/assets/33344895/dcdf3937-a65f-4d61-b98a-5903477afd7f)

**Reproduction steps/commands executed:**
1. pyarmor cfg pack:pyi_options = "--add-binary src/rscore/gdi_capture/gdi_capture.dll:src/rscore/gdi_capture"
2. pyarmor gen --pack onefile main.py

**Error output:**
INFO     Python 3.10.1
INFO     Pyarmor 8.5.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     implicitly save obfuscated scripts to ".pyarmor\pack\dist"
INFO     search inputs ...
INFO     find script main.py
INFO     find 1 top resources
INFO     call PyInstaller to generate specfile
INFO     call PyInstaller to analysis, it may take several minutes ...
ERROR    Command '['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'PyInstaller', '--clean', '--workpath', '.pyarmor\\pack\\build', '--add-binary', 'src/rscore/gdi_capture/gdi_capture.dll:src/rscore/gdi_capture', '.pyarmor\\pack\\main.spec']' returned non-zero exit status 1.
ERROR    somthing is wrong
*=============================================================*
*  Please enable debug option `-d` to run it again            *
*    pyarmor -d gen options ...                               *
*                                                             *
*  Then check console log to find more information            *
*                                                             *
*  Please also check                                          *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*  or run `pyarmor man` to find solutions quickly             *
*=============================================================*

**Error output when debug enabled:**
INFO     Python 3.10.1
INFO     Pyarmor 8.5.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
DEBUG    native platform windows.amd64
DEBUG    home path: C:\Users\leona\.pyarmor
INFO     implicitly save obfuscated scripts to ".pyarmor\pack\dist"
DEBUG    command options: {'no_runtime': False, 'inputs': ['main.py'], 'output': '.pyarmor\\pack\\dist'}
DEBUG    install plugin: CodesignPlugin
DEBUG    install plugin: DarwinUniversalPlugin
DEBUG    Loaded ctypes backend
INFO     search inputs ...
INFO     find script main.py
INFO     find 1 top resources
DEBUG    C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe -m PyInstaller.utils.cliutils.makespec --specpath .pyarmor\pack --add-binary src/rscore/gdi_capture/gdi_capture.dll:src/rscore/gdi_capture main.py
INFO     call PyInstaller to generate specfile
DEBUG    C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe -m PyInstaller --clean --workpath .pyarmor\pack\build --add-binary src/rscore/gdi_capture/gdi_capture.dll:src/rscore/gdi_capture .pyarmor\pack\main.spec
INFO     call PyInstaller to analysis, it may take several minutes ...
DEBUG    unknown error, please check pyarmor.error.log
ERROR    Command '['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'PyInstaller', '--clean', '--workpath', '.pyarmor\\pack\\build', '--add-binary', 'src/rscore/gdi_capture/gdi_capture.dll:src/rscore/gdi_capture', '.pyarmor\\pack\\main.spec']' returned non-zero exit status 1.
ERROR    somthing is wrong
*=============================================================*
*  Please check                                               *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*  or run `pyarmor man` to find solutions quickly             *
*                                                             *
*  It's recommand to report issue by `pyarmor man` in order   *
*  to provide necessary information, and avoid dupcliated     *
*  issues or unclear question.                                *
*=============================================================*

**Comment by jondy** [comment]
Got it. The problem is that binary file doesn't exists within the path of the obfuscated scripts, it will be fixed in next release

**Comment by kyranops** [comment]
I have tested it and it works with the pre-release version. Thanks!
