### ISSUE TITLE
Coverage: Trace function changed

### ISSUE THREAD

**Issue by joonis** [dashingsoft/pyarmor#175]
Using *coverage* with code that imports an obfuscated module the measurement is disrupted, also for unobfuscated code.

This is the warning you get:
`Coverage.py warning: Trace function changed, measurement is likely wrong: None`

From the *coverage* docs:
> `Trace function changed, measurement is likely wrong: XXX (trace-changed)`
> Coverage measurement depends on a Python setting called the trace function. Other Python code in your product might change that function, which will disrupt coverage.py’s measurement. This warning indicates that has happened. The XXX in the message is the new trace function value, which might provide a clue to the cause.

Is that trace function changed by pyarmor?

**Comment by jondy** [comment]
Yes, the callback function set by sys.settrace, sys.setprofile, threading.settrace and threading.setprofile will be ignored by obfuscated scripts. All of these callback functions are cleared.

**Comment by joonis** [comment]
Is there any possibility to change this behaviour?

**Comment by jondy** [comment]
At this time there is no option to control this behavior.

**Comment by joonis** [comment]
It would be nice to see an alternative procedure in future versions when calling obfuscated code:

1. Clear trace functions
2. Decrypt code
3. Execute code
4. Encrypt code
5. Restore trace functions

**Comment by jondy** [comment]
I'll take it into account in the future version.

**Comment by fchennouf** [comment]
Hi guys, any idea in which version, this is gonna be corrected ?

**Comment by jondy** [comment]
About the end of this February

**Comment by jondy** [comment]
Fixed in v5.9.1.
