### ISSUE TITLE
[BUG] `request license token failed (101)`

### ISSUE THREAD

**Issue by smolinaatbyond** [dashingsoft/pyarmor#1750]
With no changes in our build procedure and using exactly the same pro license we were already using, we are getting now the error below when running `pyarmor reg <license zip file>`:
```
#17 8.303 INFO     register "pyarmor-regfile-5344.zip"
#17 8.305 INFO     update license token
#17 8.342 ERROR    request license token failed (101): Success
```

**Comment by jondy** [comment]
How about fix pyarmor version prior to 8.5.3, for example
```
pip install pyarmor==8.5.2
```
