### ISSUE TITLE
[BUG] `Error message`RFT模式打包的exe运行找不到模块

### ISSUE THREAD

**Issue by hugeman-wang** [dashingsoft/pyarmor#1757]
Please read this first before report any issue
https://pyarmor.readthedocs.io/en/latest/questions.html
RFT模式打包的exe运行找不到模块
If this issue has been documented and there is solution in FAQ, it will be marked as `documented` and be closed it immediately.

Do not ask questions here but in discussions, it will be closed immediately.

A good report should have

- A clear title
- Reproduced steps
- Expected results and actual results

Please also provide necessary log (but not full log), for example, the whole command options `pyarmor gen` and first 4 logs in the console, paste the text directly, DO NOT paste IMAGE

```
$ pyarmor gen -O dist --assert-call foo.py
INFO     Python 3.10.0
INFO     Pyarmor 8.4.0 (trial), 000000, non-profits
INFO     Platform darwin.x86_64

```

In order to save time for both of us, if the bug report is not clear or missing necessary information, it will be marked as `invalid` and be closed immediately.

**Comment by hugeman-wang** [comment]
下面是我的打包命令
pyarmor gen --enable-rft --pack onefile video_search_spider.py

**Comment by jondy** [comment]
问题收到了，开发组会进行检查的。
但是报告极不规范，会被直接关闭的。

**Comment by jondy** [comment]
下一个版本会解决这个问题，请参考 #1758

一个快速的解决方案是把相关的脚本都列在命令行，例如

```
pyarmor gen --pack onefile --enable-rft main.py util.py pkg1/ pkg2/
```

**Comment by hugeman-wang** [comment]
import os
import requests
import pandas as pd
from datetime import datetime
import json
from time import localtime, strftime, sleep
import urllib.parse

我的video_search_spider.py 中导入了以上包,我要将video_search_spider.py 以rft模式加密并打包为exe,打包命令应该是? 我买的专家版,只是对python知识懂得不够多,请指导.


月下狼独舞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月29日(星期一) 上午9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG] `Error message`RFT模式打包的exe运行找不到模块 (Issue #1757)





 
下一个版本会解决这个问题，请参考 #1758
 
一个快速的解决方案是把相关的脚本都列在命令行，例如
 pyarmor gen --pack onefile --enable-rft main.py util.py pkg1/ pkg2/

**Comment by jondy** [comment]
使用方法请查阅文档并根据项目需要选择适当的选项

对于提交的问题，请使用一个清晰的标题，提供运行环境和具体的重现步骤，以便于 Pyarmor 开发组能够重现问题。

如果开发组不能根据你的描述重现问题，那么有可能是配置和环境存在问题，并不一定是 bug

**Comment by hugeman-wang** [comment]
你说会在下个版本解决这个问题?我已经把pyarmor更新了一次 现在该如何解决这个问题?




月下狼独舞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月29日(星期一) 上午9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG] `Error message`RFT模式打包的exe运行找不到模块 (Issue #1757)





 
下一个版本会解决这个问题，请参考 #1758
 
一个快速的解决方案是把相关的脚本都列在命令行，例如
 pyarmor gen --pack onefile --enable-rft main.py util.py pkg1/ pkg2/

**Comment by jondy** [comment]
Pyarmor 是一个命令行工具，提供了丰富的选项来应对不同的情况。对于简单的应用，使用默认选项就可以工作，不需要学习如何使用 Pyarmor。但是对于一些高级的功能，或者比较复杂的应用，尤其是需要使用大型的第三方包来调用加密脚本，用户需要一定的时间去学习和使用各种选项，并组合这些选项去解决加密过程中问题。

当加密脚本出现问题的时候，这不一定是 Pyarmor 的 Bug，很可能是这个脚本使用默认的选项和配置无法工作。这种情况下需要分析问题并找到 Pyarmor 解决这个问题的选项和设置，这就需要用户参考 Pyarmor 的命令手册去找到合适的选项。

用户需要自己学习和了解 Pyarmor 的各个选项以及使用方法，并根据自己的需求选择正确的选项，Pyarmor 开发组不会去了解用户的项目结构和加密需求，然后告诉用户需要使用什么选项

Pyarmor 有完整的文档系统，所有的功能和选项都已经在文档中描述，Pyarmor 开发组能告诉你的，这些文档中都已经有说明。

请参阅
https://pyarmor.readthedocs.io/zh/latest/questions.html

以及其中关于 RFT 模式和 pack 的链接内容，首先确保没有 --pack 的时候加密脚本能正常运行

**Comment by hugeman-wang** [comment]
我的项目很简单,只有一个py,不是复杂的大型项目.我学习了你的文档,但根据你的文档提供的命令并不能打包成功.RFT加密打包正是我购买专家版的目的,对于这么重要的功能,你们为什么不能提供详细和直接的打包示例,而固执地希望用户自己去学习和总结出正确的打包命令?如果用户有这么强的能力,还需要购买你们的软件吗?






月下狼独舞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月19日(星期天) 中午12:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG] `Error message`RFT模式打包的exe运行找不到模块 (Issue #1757)





 
Pyarmor 是一个命令行工具，提供了丰富的选项来应对不同的情况。对于简单的应用，使用默认选项就可以工作，不需要学习如何使用 Pyarmor。但是对于一些高级的功能，或者比较复杂的应用，尤其是需要使用大型的第三方包来调用加密脚本，用户需要一定的时间去学习和使用各种选项，并组合这些选项去解决加密过程中问题。
 
当加密脚本出现问题的时候，这不一定是 Pyarmor 的 Bug，很可能是这个脚本使用默认的选项和配置无法工作。这种情况下需要分析问题并找到 Pyarmor 解决这个问题的选项和设置，这就需要用户参考 Pyarmor 的命令手册去找到合适的选项。
 
用户需要自己学习和了解 Pyarmor 的各个选项以及使用方法，并根据自己的需求选择正确的选项，Pyarmor 开发组不会去了解用户的项目结构和加密需求，然后告诉用户需要使用什么选项
 
Pyarmor 有完整的文档系统，所有的功能和选项都已经在文档中描述，Pyarmor 开发组能告诉你的，这些文档中都已经有说明。
 
请参阅
 https://pyarmor.readthedocs.io/zh/latest/questions.html
 
以及其中关于 RFT 模式和 pack 的链接内容，首先确保没有 --pack 的时候加密脚本能正常运行

**Comment by hugeman-wang** [comment]
你提到"确保没有 --pack 的时候加密脚本能正常运行",这个我试过了,只用RFT加密脚本后,可以运行.但是加密的同时打包,不论是onedir或者onefile 运行后都存在提示不能找到某个模块的问题.


月下狼独舞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月19日(星期天) 中午12:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG] `Error message`RFT模式打包的exe运行找不到模块 (Issue #1757)





 
Pyarmor 是一个命令行工具，提供了丰富的选项来应对不同的情况。对于简单的应用，使用默认选项就可以工作，不需要学习如何使用 Pyarmor。但是对于一些高级的功能，或者比较复杂的应用，尤其是需要使用大型的第三方包来调用加密脚本，用户需要一定的时间去学习和使用各种选项，并组合这些选项去解决加密过程中问题。
 
当加密脚本出现问题的时候，这不一定是 Pyarmor 的 Bug，很可能是这个脚本使用默认的选项和配置无法工作。这种情况下需要分析问题并找到 Pyarmor 解决这个问题的选项和设置，这就需要用户参考 Pyarmor 的命令手册去找到合适的选项。
 
用户需要自己学习和了解 Pyarmor 的各个选项以及使用方法，并根据自己的需求选择正确的选项，Pyarmor 开发组不会去了解用户的项目结构和加密需求，然后告诉用户需要使用什么选项
 
Pyarmor 有完整的文档系统，所有的功能和选项都已经在文档中描述，Pyarmor 开发组能告诉你的，这些文档中都已经有说明。
 
请参阅
 https://pyarmor.readthedocs.io/zh/latest/questions.html
 
以及其中关于 RFT 模式和 pack 的链接内容，首先确保没有 --pack 的时候加密脚本能正常运行

**Comment by jondy** [comment]
学习 Pyarmor 的选项是指用户需要知道 Pyarmor 还有那些选项和功能，例如，pyarmor 提供了 `-i` ，`--prefix` 这些选项，用来正确的生成导入运行辅助包的脚本脚本。如果用户使用过程中出现的问题可以使用这些选项得到解决，但是用户却不知道有这样的选项。你认为用户不需要查看文档学习这些选项，而是报告问题给 Pyarmor 开发组，让 Pyarmor 开发组告诉每一个用户如何去使用这些选项吗？

假设你购买了微软的 Excel，需要使用 Excel 的公式进行复杂的计算，或者写一个宏 执行复杂的计算，如果你写的宏或者公式出现错误，难道你不需要学习宏或者公式的使用方法，自己去修正宏或者公式？还是你会报告问题给给微软，让他们来告诉你怎么写这个宏或者公式

**Comment by hugeman-wang** [comment]
微软什么样，我不清楚。你尊贵的软件总共就3种加密模式，对应打包命令也就3种。你的文档只给了普通加密打包的示例。我现在请你给一个RFT模式的、基本的打包命令示例。这难道不是你文档中本来就应该给出的吗？这是什么不合理要求吗？现在RFT打包出现了bug，我已经按你指导的去调试，但还是不能解决。我需要打包的项目很简单，我已经给你截图看过了，所以应该是你pyarmor rft打包自身的bug。你们这种售后质量还不如考虑给我退款？




月下狼独舞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月20日(星期一) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG] `Error message`RFT模式打包的exe运行找不到模块 (Issue #1757)





 
学习 Pyarmor 的选项是指用户需要知道 Pyarmor 还有那些选项和功能，例如，pyarmor 提供了 -i ，--prefix 这些选项，用来正确的生成导入运行辅助包的脚本脚本。如果用户使用过程中出现的问题可以使用这些选项得到解决，但是用户却不知道有这样的选项。你认为用户不需要查看文档学习这些选项，而是报告问题给 Pyarmor 开发组，让 Pyarmor 开发组告诉每一个用户如何去使用这些选项吗？
 
假设你购买了微软的 Excel，需要使用 Excel 的公式进行复杂的计算，或者写一个宏 执行复杂的计算，如果你写的宏或者公式出现错误，难道你不需要学习宏或者公式的使用方法，自己去修正宏或者公式？还是你会报告问题给给微软，让他们来告诉你怎么写这个宏或者公式

**Comment by jondy** [comment]
4.3.1.4. 使用更多的加密选项

其他加密选项也都可以根据需要选用来增加安全性或者提高性能，例如:

$ pyarmor gen --pack onefile --private foo.py

https://pyarmor.readthedocs.io/zh/latest/topic/repack.html#id4

我认为这就是示例，我不认为文档需要把所有的选项都列出来，例如把 `--enable-bcc` 等等每一个选项都列出来

**Comment by jondy** [comment]
Pyarmor 肯定是有 bug 的，但是请按照规范的方式报告bug.

你提交的 bug 正文是 Pyarmor 的模版，没有重现步骤，没有加密使用的命令，没有完整的错误信息，有些 bug 可能和 Pyarmor 版本/PyInstaller 版本有关系，这些你都没有提供，只是说 RFT 模式错误了

对于一个简单的测试脚本，下面的命令是没有错误的
```
pyarmor gen --pack onefile --enable-rft foo.py
dist/foo
```

对于 PyInstaller 中的模块找不到问题，Pyarmor 提供的方案是使用 `pyarmor cfg pack:pyi_options = ...`

**Comment by jondy** [comment]
关于打包出现问题之后的解决方案，这里也有
https://pyarmor.readthedocs.io/zh/latest/topic/repack.html#id5

不知道你尝试过没有？

**Comment by hugeman-wang** [comment]
我认为你还是把简单问题复杂化了.我再重申一遍,我的项目很简单.只需要你给出一个rft模式的打包命令.这个打包命令,理应是由你来提供给用户的基本示例.而且应该是经过你本人验证可行的成功命令.你拿excel函数打比方.然而人家excel函数每个都有基本示例(或者叫"明确提示")好吗?我就会个xlookup函数,人家是有基本示例的.我就是照着基本示例试成功的.你的有吗?至于你说有些 bug 可能和 Pyarmor 版本/PyInstaller 版本有关系,那你何不给出一个打包成功的版本搭配呢?不需要多少种成功搭配,这确实是为难你.一个成功的就行.你总不会希望由购买用户来逐个试错吧?你是否对购买用户的能力要求过于苛刻?你软件目前应该提供的服务是否真的已经到位?




月下狼独舞
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月20日(星期一) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG] `Error message`RFT模式打包的exe运行找不到模块 (Issue #1757)





 
关于打包出现问题之后的解决方案，这里也有
 https://pyarmor.readthedocs.io/zh/latest/topic/repack.html#id5
 
不知道你尝试过没有？

**Comment by hugeman-wang** [comment]
py导包信息和项目结构



打包命令和打包成功提示





打包成exe,运行报错结果









月下狼独舞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月20日(星期一) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG] `Error message`RFT模式打包的exe运行找不到模块 (Issue #1757)





 
关于打包出现问题之后的解决方案，这里也有
 https://pyarmor.readthedocs.io/zh/latest/topic/repack.html#id5
 
不知道你尝试过没有？

**Comment by hugeman-wang** [comment]
现在rft打包能用了吗?为了让你的程序更简单好用一点卖得更好,你可以想办法更新一下吗?这RFT加密打包可是核心卖点啊,不然买专家版做什么?总共就三种加密,你每一种都给出成熟可用的打包示例,为什么就做不到呢?你做产品是面向市场面向用户的,怎么感觉你面向的是你自己?




月下狼独舞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月20日(星期一) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG] `Error message`RFT模式打包的exe运行找不到模块 (Issue #1757)





 
4.3.1.4. 使用更多的加密选项
 
其他加密选项也都可以根据需要选用来增加安全性或者提高性能，例如:
 
$ pyarmor gen --pack onefile --private foo.py
 
https://pyarmor.readthedocs.io/zh/latest/topic/repack.html#id4
 
我认为这就是示例，我不认为文档需要把所有的选项都列出来，例如把 --enable-bcc 等等每一个选项都列出来

**Comment by jondy** [comment]
现在正在开发 pyarmor.man ，主要就是提供快速解决方案，通过示例学习等功能，这个版本到 1.0 之后会有充分的示例的，Pyarmor.Man 1.0 计划发布时间是 10月份。

**Comment by hugeman-wang** [comment]
我知道有一些人是可以反编译pyinstaller打包的exe,网上也有相关教程.但是如果用pyarmor gen --pack onefile 未加密脚本&nbsp;
打包的exe,反编译的难度如何?




月下狼独舞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月20日(星期一) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG] `Error message`RFT模式打包的exe运行找不到模块 (Issue #1757)





 
4.3.1.4. 使用更多的加密选项
 
其他加密选项也都可以根据需要选用来增加安全性或者提高性能，例如:
 
$ pyarmor gen --pack onefile --private foo.py
 
https://pyarmor.readthedocs.io/zh/latest/topic/repack.html#id4
 
我认为这就是示例，我不认为文档需要把所有的选项都列出来，例如把 --enable-bcc 等等每一个选项都列出来

**Comment by hugeman-wang** [comment]
你好,请问进度如何了?一直非常期待能使用rft模式便捷打包.




月下狼独舞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dashingsoft/pyarmor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月18日(星期四) 下午3:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dashingsoft/pyarmor] [BUG] `Error message`RFT模式打包的exe运行找不到模块 (Issue #1757)





 
现在正在开发 pyarmor.man ，主要就是提供快速解决方案，通过示例学习等功能，这个版本到 1.0 之后会有充分的示例的，Pyarmor.Man 1.0 计划发布时间是 10月份。
