### ISSUE TITLE
pycache directory saves byte-compiled code

### ISSUE THREAD

**Issue by scottwsides** [dashingsoft/pyarmor#176]
When the byte-compiled code is saved in the __pycache__ directory... can't this be reverse engineered to reveal source code?

**Comment by jondy** [comment]
Don't worry about this. This byte-code is same as
```
__pyarmor__(__file__, __name__, b'\x0a....', 1)
```
The real code is still obfuscated in the string const.

**Comment by scottwsides** [comment]
Oh good! That simplifies my life a lot. Cheers,
