### ISSUE TITLE
[ERROR] `Error importing armored python package`

### ISSUE THREAD

**Issue by resulemreaygan** [dashingsoft/pyarmor#1762]
Hello, I am preparing a toolkit about image processing. But I want to armor the toolkit I prepared with pyarmor. I will give a whl that I produced through armored code to whomever I want.

The problem I'm having here is through armored code;

```python
from toolkit.my_package.image_processing import contrast
```

When I write the code, the contrast function is not imported. What is the correct armoring method for a Python library package? Or can it be done? Thank you.

```
$ tree  test_package

test_package
├── setup.py
├── setup.cfg
└── toolkit
    └── my_package
	    ├── image_processing
	    │   ├── filters
	    │   │	├── _filter.py
	    │   │	└── __init__.py
	    │   ├── _base.py	
	    │   └── __init__.py
            ├── __init__.py
            └── __version__.py
```
```
$ pyarmor gen -r --platform windows.x86_64 --platform windows.x86 --platform linux.x86_64 --platform linux.x86 C:\User\project_path\project_name

INFO     Python 3.11.6
INFO     Pyarmor 8.4.4 (basic)

```

**Comment by jondy** [comment]
Please check
http://pyarmor.readthedocs.io/en/latest/topic/obfuscated-script.html

And find common solutions
http://pyarmor.readthedocs.io/en/latest/questions.html

If there still not fixed, please provide necessary information.
