### ISSUE TITLE
[BUG] `SystemError: unknown opcode`

### ISSUE THREAD

**Issue by mayuresh-quartic** [dashingsoft/pyarmor#1763]
- Title:
Pyarmor 3.9 obfuscated script does not work on Python3.8 

- Reproduced steps:
Obfuscate a module and using Python3.9 version and install in Python3.8 running program

- Expected results
Program should work without any error

- Actual result
Program fails with the following error
SystemError: unknown opcode

**Comment by jondy** [comment]
Please first read the getting-started documentation
