### ISSUE TITLE
New Support - linux mipsel or mips32el

### ISSUE THREAD

**Issue by HomeAssistantActivation** [dashingsoft/pyarmor#1768]
Is possibile support linux mipsel or mips32el?

**Comment by jondy** [comment]
Maybe in future, but still no release plan now

**Comment by jondy** [comment]
Done in v8.5.9 with platform name `linux.mips32el` for glibc and `alpine.mips32el` for musl, the prebuilt extensions are published in the package `pyarmor.cli.core.linux==6.5.2` and `pyarmor.cli.core.alpine==6.5.2`
