### ISSUE TITLE
Is it possible to show info from pyinstaller when using pack command?

### ISSUE THREAD

**Issue by fgg1991** [dashingsoft/pyarmor#177]
Sometimes pack command just stuck there, and I hope if the script can display the info from pyinstaller so I can debug easier?

**Comment by jondy** [comment]
Pack the script with option `--debug`, all the `entry.spec` file and `entry-patched.spec` will be kept in the current path, then add any python code in these `.spec` files and run PyInstaller with it. For example,
```
pyarmor pack --debug foo.py
pyinstaller foo-patched.spec
```
