### ISSUE TITLE
Themida or Themedia? Is this word misspelled?

### ISSUE THREAD

**Issue by 17Reset** [dashingsoft/pyarmor#1771]
![image](https://github.com/dashingsoft/pyarmor/assets/122418720/b89ac792-dcf6-472e-8eaa-421dc2aee864)

**Comment by 17Reset** [comment]
May I ask, what is the difference between --enable-themida, which uses themida from pyarmor, and the official themida?

**Comment by jondy** [comment]
If `--enable-themida` is used, the extension `pyarmor_runtime.so` is protected by Themida

**Comment by 17Reset** [comment]
![image](https://github.com/dashingsoft/pyarmor/assets/122418720/2cd273f3-d57c-44e2-8ae3-7cfb7713487f)
Suggested update to incorrectly spelled word in manual: Themida

**Comment by 17Reset** [comment]
> If `--enable-themida` is used, the extension `pyarmor_runtime.so` is protected by Themida

I want to use bcc mode for performance, and themida for protection, can both be used at the same time?

**Comment by jondy** [comment]
`--enable-themida` could work with `--enable-bcc`, but `--enable-themida` may reduce the preformance too much.

**Comment by jondy** [comment]
These typos has been fixed in the online doc
