### ISSUE TITLE
[BUG] Module pyarmor_runtime_000000 not found if exe is created with cx_freeze, even if runtime is included

### ISSUE THREAD

**Issue by itsMGA** [dashingsoft/pyarmor#1774]
![Uploading Screenshot 2024-05-16 193745.png…]()
So i got this setup for cx_freeze

import sys
from cx_Freeze import setup, Executable

build_exe_options = {
    "packages": ["os", "sys", "hashlib", "json", "time", "logging", "subprocess", "traceback", "paramiko", "psutil", "PyQt5", "ctypes"],
    "include_files": ['dist/pyarmor_runtime_000000'],
    "excludes": []
}

base = None
if sys.platform == "win32":
    base = 

executables = [
    Executable("dist/patcher-source.py", base=base, target_name="Awakening2-Patcher.exe", icon='patcher-icon.ico')
]

setup(
    name="Awakening2-Patcher",
    version="1.0",
    description="Auto Patcher for Awakening2",
    options={"build_exe": build_exe_options},
    executables=executables
)

It raises module not found pyarmor_runtime_000000 not found, even if the dir is literally there in the same location as the exe

**Comment by itsMGA** [comment]
building with seq
`import os

if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)

    os.system('pyarmor gen .\patcher-source.py')
    os.system('python setup.py build')`

**Comment by jondy** [comment]
How about adding `pyarmor_runtime_000000` as `packages`, for example:
```
build_exe_options = {   
"packages": ["os", ..., "pyarmor_runtime_000000"]
...
```

Pyarmor supports PyInstaller well, but not test with cx_freeze for Pyarmor 8+.

Please check 
https://pyarmor.readthedocs.io/en/latest/topic/obfuscated-script.html

And take the obfuscated scripts as normal scripts to freeze it
