### ISSUE TITLE
[BUG] Impossible to pass pyinstaller flags while using --pack

### ISSUE THREAD

**Issue by RobertAzovski** [dashingsoft/pyarmor#1775]
Hi. I used to pack pyarmor in one executable. (pyisntaller==5.13.2)

In earlier versions(pyarmor < 8.5.7) was building executable with all required flags icons etc.
And then `pyarmor gen --pack dist/myapp.exe myapp.py`
But this approach is no longer working. It gives an error.
It doesnt work now and even doesnt work if previous pyarmor versions installed.

This works: `pyarmor gen --pack onefile myapp.py`

PROBLEM:
I need to build executable without console (desktop app) add icon to this and bind the executable to certain machine using MAC address.

How can I do this at this stage ??

`pyarmor gen -b 8d:9c:7a:6u:3e --pack onefile myapp.py` This one works but the console is presented and impossible to add icon. I didn't find in current docs how to add pyinstaller flags to `gen` command.

Thanks.

**Comment by jondy** [comment]
Please check
https://pyarmor.readthedocs.io/en/latest/topic/repack.html#using-more-pyinstaller-options
