### ISSUE TITLE
请问我的代码既有python2，又有python3，应该买版本7，能不能支持设备离线加密？（My code has both python2 and python3. I should buy version 7. Can I support offline encryption?）

### ISSUE THREAD

**Issue by PhilipWang34** [dashingsoft/pyarmor#1777]
请问我的代码既有python2，又有python3，看了文档只有版本7才支持，但是版本7好像没有集团认证模式，还能不能支持设备离线加密呢？

**Comment by PhilipWang34** [comment]
My code has both python2 and python3. I should buy version 7. Can I support offline encryption?

**Comment by jondy** [comment]
Pyarmor 7 支持 Python2.7~Python3.10，也支持离线加密
