### ISSUE TITLE
[BUG] pyarmor license using in python 3.7.6 (pyarmor 5.9.0) but can not reg license when update to python3.11.9 ( pyarmor 8.5.8)

### ISSUE THREAD

**Issue by quannhe18** [dashingsoft/pyarmor#1779]
i have one license in python3.7 with pyarmor5.9.0 with that i can obscate the script but since update to python3.11.9 (  newest pyarmor) , license can not be registed and alway show as below
runtimeerror request license token failed (102) 

im using license file like : pyarmor-regfile-xxxxxx.zip

i think my license is old but it is correctly and need to renew once ?

**Comment by jondy** [comment]
Pyarmor 7 doesn't support Python 3.11, please check README.md in the project home
