### ISSUE TITLE
[BUG] `ERROR    request license token failed (3): <h1>Server Error (500)</h1>` when running pyarmor reg

### ISSUE THREAD

**Issue by noahmuney** [dashingsoft/pyarmor#1780]
Error 500 when trying to register pyarmor
Happening on and off since this morning

```
$ pyarmor reg pyarmor-regfile-****.zip
INFO     Python 3.11.0
INFO     Pyarmor 8.5.1 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "pyarmor-regfile-****.zip"
INFO     update license token
ERROR    request license token failed (3): <h1>Server Error (500)</h1>
ERROR    somthing is wrong
```

**Comment by noahmuney** [comment]
https://pyarmor.dashingsoft.com//api/auth2/ returns `NO:missing parameter`

**Comment by noahmuney** [comment]
Seems to be stable now
@jondy was there a particular issue earlier?

**Comment by jondy** [comment]
Do not run `pyarmor reg xxx.zip` too many times in 1 minutes, the license server will return error if more than 3 runs `pyarmor reg xxx.zip` each minute.

**Comment by jondy** [comment]
Try to upgrade Pyarmor to latest version 8.5.8
