### ISSUE TITLE
[BUG] `Register Error message: request license token failed (4): NO:too long` 

### ISSUE THREAD

**Issue by ericedmund** [dashingsoft/pyarmor#1781]
Python 3.8.6
I register pro version, and one hour later, it become non-profit version;
and i can't use pyarmor-regfile-xxx.zip to register again, 
it says:

INFO     Python 3.8.6
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     register "pyarmor-regfile-xxxx.zip"
INFO     update license token
ERROR    request license token failed (4): NO:too long
ERROR    somthing is wrong

how to deal with it?

**Comment by ericedmund** [comment]
i change the date and it happend, change date to default is OK

**Comment by jondy** [comment]
The device date should be current date time.
