### ISSUE TITLE
[BUG] Support for PyInstaller >= 5.11.0

### ISSUE THREAD

**Issue by LuisHenri** [dashingsoft/pyarmor#1785]
I opened an Issue on PyInstaller as I thought it was a bug on their side. Please read it as it is further explained in there: https://github.com/pyinstaller/pyinstaller/issues/8562.

However, seems like PyArmor actually never modified itself to a change on their side: https://github.com/pyinstaller/pyinstaller/issues/8562#issuecomment-2129729514

In summary, running `pyarmor pack` with a PyInstaller >= 5.11.0 doesn't load PyArmor Plugins that are on inner packages.

## Reproduction Steps

See https://gist.github.com/LuisHenri/4e488c87648f10b518606d24da4a2447

**Comment by jondy** [comment]
Fixed by this patch
943b1cf4f46cc277463bd5e56324776bc9dacdfa

**Comment by jondy** [comment]
It's about next Mondy.
