### ISSUE TITLE
The disk serial number has spaces

### ISSUE THREAD

**Issue by Byxs20** [dashingsoft/pyarmor#1788]
Hi, after running hdinfo, Default Harddisk Serial Number: ‘YMA1512JA2245208F8 _00000001’
How should I go about binding the disk if there are spaces on this kind of disk?

**Comment by jondy** [comment]
This will be fixed in next release 8.5.9

If you're using Pyarmor-7, just quote the serial number

**Comment by jondy** [comment]
Fixed in v8.5.9

**Comment by jondy** [comment]
这个问题将在下一个 pyarmor.cli.core 发布的时候解决

命名的硬盘序列号中包含空格和尾部点

**Comment by jondy** [comment]
开发版本已经可以在这里下载
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor.cli.core.windows-6.5.3-cp310-none-any.whl    

请替换 cp310 为对应的 python 版本

正式发布请关注 #1815
