### ISSUE TITLE
Pydev debugging not working with Pyarmor

### ISSUE THREAD

**Issue by fchennouf** [dashingsoft/pyarmor#179]
Hi guys, I'm using a library that has been obfuscated  using Pyarmor, and I'm trying to debug a code that has no link with this library except that the main application import this obfuscated library at start up. I don't know why, once the obfuscated lib is imported breakpoints are not working anymore, the app is working correctly but debug and breakpoints are not functional anymore. I tried by setting breakpoints before the import, they are OK, but after the import my code doesn't stop. I'm using Pycharm which uses Pydev for debug. Thanks !

**Comment by jondy** [comment]
This is known issue, because the callback function set by sys.settrace, sys.setprofile, threading.settrace and threading.setprofile are ignored by obfuscated scripts, all of these callback functions are cleared. Refer to #175

**Comment by fchennouf** [comment]
Thanks !

**Comment by jondy** [comment]
Fixed in v5.9.1
