### ISSUE TITLE
No obfuscation being done to code after using spec file.

### ISSUE THREAD

**Issue by KDot227** [dashingsoft/pyarmor#1795]
I need to use a spec file for packing with pyinstaller due to how nicegui packages scripts and the data that needs to be included. With the following spec file:

```py
# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['test.py'],
    pathex=[],
    binaries=[],
    datas=[('C:\\Users\\this1\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\nicegui', 'nicegui')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='testKDOT',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```

It compiles correctly but with the command

```
pyarmor gen --enable-jit --enable-bcc --enable-themida --mix-str --pack main.spec test.py
```

None of the obfuscation is actually applied to the script in the exe. I believe this is because the target script is just test.py, but when I try targeting the following

```py
a = Analysis(
    ['.pyarmor\\pack\\dist\\test.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=['.pyarmor\\pack'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
```

I get an error saying the obfuscated script cannot be found. Is there a way around this? (Thank you btw)

**Comment by KDot227** [comment]
Ok I think I was wrong and it is still obfuscating but there is one issue I'm still coming across. It's still possible to get the pid of the process and inject it with tools like Hypno and I can pull important variables. Does pyarmor have any protection against this?

**Comment by KDot227** [comment]
Also I have themida turned on but I can still debug every part of the code with x64dbg.

![image](https://github.com/dashingsoft/pyarmor/assets/110929758/adfbc7fa-967f-4714-b33f-4d655affa9d5)

**Comment by jondy** [comment]
Please check
https://pyarmor.readthedocs.io/en/latest/topic/repack.html

**Comment by KDot227** [comment]
> Please check https://pyarmor.readthedocs.io/en/latest/topic/repack.html

even without packaging the scripts I can still inject the process and pull out any variables. This would let anyone who knows that the app is in python easily get sensitive information.

**Comment by KDot227** [comment]
"rft" mode atleast changes the variable name but in the end it doesn't matter since I can see the value in plain text.

**Comment by KDot227** [comment]
This is also with the following compiler flags

```py
pyarmor -d gen --enable-rft --enable-themida --enable-jit --enable-bcc --mix-str --assert-call --assert-import --private test.py
```

**Comment by jondy** [comment]
Pyarmor does not protect the inject attack, `--enable-bcc` could convert Python to C, the source code should not be reverted, `--enable-rft` could rename class/function/variables just like rewriting the script.

`--enable-themida` may only work when `pyarmor_runtime.pyd` has been imported, and try to use `pyarmor cfg check_debugger=1` to detect debugger.

**Comment by KDot227** [comment]
> Pyarmor does not protect the inject attack, `--enable-bcc` could convert Python to C, the source code should not be reverted, `--enable-rft` could rename class/function/variables just like rewriting the script.
> 
> `--enable-themida` may only work when `pyarmor_runtime.pyd` has been imported, and try to use `pyarmor cfg check_debugger=1` to detect debugger.
> 

I've tried all of that but have had little to no luck with it actually working against the attack. RFT mode is good but it doesn't work with nicegui otherwise I would use it.

**Comment by jondy** [comment]
Find RFT mode solutions here
https://pyarmor.readthedocs.io/en/latest/topic/rftmode.html

**Comment by KDot227** [comment]
> Find RFT mode solutions here https://pyarmor.readthedocs.io/en/latest/topic/rftmode.html

but doesn't the fact that you can easily inject the program and change any variable eliminate the entire use of the obfuscation rendering it useless.

**Comment by jondy** [comment]
Thanks.

The option `--private` should prevent injected python code reading the attributes of private module, but I forgot to document that the main script is always not private.

I update the doc and add one note for `--private`

Note that main script is always not private, otherwise the obfuscated script can't be executed by Python interpreter. If need protect the attributes of main script, move real code to one module. For example, suppose the original script is `foo.py`:

```
    def main():
        print('This is main code')

    if __name__ == '__main__':
        main()
```

Just copy it to `real_foo.py`, then create new `foo.py` like this:

```
    from real_foo import main

    if __name__ == '__main__':
        main()
```

And obfuscate them::

    $ pyarmor gen --private foo.py real_foo.py
