### ISSUE TITLE
[BUG] License stops working after a few days `RuntimeError: request license token failed (5): ER:wrong use group license`

### ISSUE THREAD

**Issue by john-altitude** [dashingsoft/pyarmor#1803]
My company has a group license for offline obfuscation and successfully got Pyarmor installed on a few of our machines, but on each of our machines, after a few days have passed, the license file stops working and we are unable to obfuscate code. If we re-register the device with a new device number, things work again for a few days. At this point my computer has been registered 3 times with different group numbers, which is wasting our available devices and is incredibly inconvenient.

**Comment by jondy** [comment]
`ER:wrong use group license` this error means you're using group license in wrong way.

Please first make sure the machine id is changed or not in offline machine after reboot
https://pyarmor.readthedocs.io/en/latest/licenses.html#check-device-for-group-license

Please check
https://pyarmor.readthedocs.io/en/latest/how-to/register.html#using-group-license

**Comment by jondy** [comment]
If not use the latest Pyarmor, try to upgrade to latest Pyarmor 8.5.9
