### ISSUE TITLE
Feature Request: Options to copy over non `.py` files for recursive obfuscation

### ISSUE THREAD

**Issue by sriduth** [dashingsoft/pyarmor#181]
For obfuscating a python package using the `-r` option, it might be useful to have an option to include non python files (maybe according to a MANIFEST.in file if present) into the target folder.

Currently a developer would have to write a shell command like this to copy over other files from `mypackage`:

```sh
find mypackage -type f | grep -v ".py" | cut -d"/" -f2- | xargs -I{} cp mypackage/{} mypackageobfuscated/{} --parents
```

If this is something that makes sense, i'd like to contribute the changes!

**Comment by jondy** [comment]
I have take it into account, it also could be achieved by this way.

First copy the whole package to output
```
cp -a mypackage dist/
```

Then obfuscate all the `.py` files to overwrite the original scripts. For examples,
```
cd mypackage
pyarmor obfuscate -r -O dist/mypackage __init__.py
```

How about this way?

**Comment by sriduth** [comment]
Sorry for the late reply! 

That is also a simpler solution - it would be nice though if we had a documentation mentioning that only the obfuscated versions of `.py` files will be written to the output directory in case of of using `-r`.

**Comment by jondy** [comment]
Got it, document it in the man page, https://pyarmor.readthedocs.io/en/latest/man.html#obfuscate

**Comment by sriduth** [comment]
Will open a PR!

**Comment by sriduth** [comment]
Oh looks like this is already mentioned in the description of the command:

> Note that only the .py files are touched by this command, all the other files aren’t copied to output path. If there are many data files in the package, first copy the whole package to the output path, then obfuscate the .py files, thus all the .py files in the output path are overwritten by the obfuscated ones.

I should have read the docs more thoroughly!

Closing this ticket - thanks for the help!
