### ISSUE TITLE
[Feature] Support Python 3.13

### ISSUE THREAD

**Issue by jondy** [dashingsoft/pyarmor#1814]
The first version to support Python 3.13 is v8.6.0

If there is no unknown technical problem, it will be released around 2024-11-01, one month after Python 3.13 final version is released

**Comment by Apprisco** [comment]
Will it be compatible with the freethreading library, aka bypass the GIL?
Gotta wonder if GIL still exists at all for BCC/RFT modes

**Comment by wjl130825** [comment]
3.13版本还没有支持吗

**Comment by jondy** [comment]
还在开发中，发布延迟了，这个月内应该会发布

**Comment by jondy** [comment]
Sorry because of some other urgent things, it's still developing to support Python 3.13, it will be delayed to publish in this month with Pyarmor 9.1.0

**Comment by jondy** [comment]
Pyarmor v9.0.5 is released to support Python 3.13

**Comment by wjl130825** [comment]
专家版也升级这个吗，原来是8.5.12

**Comment by wjl130825** [comment]
另外还有一个问题就是，捆绑序列号，在win11下总是失效

**Comment by Apprisco** [comment]
Does pyarmor now support python 3.13 Freethreading? And how does one upgrade the license?

**Comment by Apprisco** [comment]
Pyarmor 9.0.5 does not work, same issue as before #1955

**Comment by Apprisco** [comment]
@jondy is there any plan on supporting the freethreading branch? Is it necessary, as in does GIL still prevent full cpu usage when compiled in BCC mode?

**Comment by jondy** [comment]
In CPython 3.13 sources, I notice there is one macro Py_GIL_DISABLED

I think it need lot of work to support it for extension `pyarmor_runtime`, all of the sources need to check, I have no plan to support it now.

But there is one lightweight extension `pyarmor_mini` which is developing to support high performance obfuscated scripts, I may take it into accout if it's possible.

**Comment by Apprisco** [comment]
I see, the freethreading GIL is very tempting due to better performance all around, and using more than 1 cpu thread. Multiprocessing ProcessPoolExecutor is very high in overhead.

**Comment by wjl130825** [comment]
PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "pyarmor_runtime_005595\__init__.py", line 2, in <module>
RuntimeError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。 (1:11076)，现在打包软件，提示这个，啥原因。

**Comment by JiaPai12138** [comment]
> PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module File "pyarmor_runtime_005595__init__.py", line 2, in RuntimeError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。 (1:11076)，现在打包软件，提示这个，啥原因。

验证服务器出问题了吧？
