### ISSUE TITLE
Yocto setup for version 8

### ISSUE THREAD

**Issue by meowcakes** [dashingsoft/pyarmor#1816]
Hello, I saw there is a guide for setting up pyarmor v6 in Yocto here: https://github.com/dashingsoft/pyarmor/issues/588#issuecomment-936220607

Is there any guide for setting up pyarmor 8 in Yocto? Trying to use a similar approach I get `ModuleNotFoundError: No module named 'pyarmor.cli.core.pytransform3'` and `ModuleNotFoundError: No module named 'pyarmor.cli.core.linux'` errors.

**Comment by jondy** [comment]
I document it here
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#bootstrap-failed
