### ISSUE TITLE
Runtime crash on Mac

### ISSUE THREAD

**Issue by CoMelissant** [dashingsoft/pyarmor#1818]
Python process crashed while starting with -m <myfun>

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Python [11660]
Path:                  /Library/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.12.4 (3.12.4)
Code Type:             ARM-64 (Native)
Parent Process:        bash [11614]
Responsible:           Terminal [3778]
User ID:               501

Date/Time:             2024-06-10 08:49:45.1564 +0200
OS Version:            macOS 14.3.1 (23D60)
Report Version:        12
Anonymous UUID:        C7794638-2076-8C03-44C6-CD485BBDA611

Sleep/Wake UUID:       5FDD938C-9464-45B9-96AC-20BD55AFF906

Time Awake Since Boot: 74000 seconds
Time Since Wake:       204 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x000000010527c000
Exception Codes:       0x0000000000000032, 0x000000010527c000

Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page

VM Region Info: 0x10527c000 is in 0x10527c000-0x105284000;  bytes after start: 0  bytes before end: 32767
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      __DATA_CONST                105278000-10527c000    [   16K] rw-/rwx SM=COW  ...or_runtime.so
--->  __DATA                      10527c000-105284000    [   32K] rw-/rwx SM=COW  ...or_runtime.so
      __DATA                      105284000-105288000    [   16K] rw-/rwx SM=NUL  ...or_runtime.so

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   dyld                          	       0x184a015d0 invocation function for block in dyld4::Loader::applyFixupsGeneric(Diagnostics&, dyld4::RuntimeState&, unsigned long long, dyld3::Array<void const*> const&, dyld3::Array<void const*> const&, bool, dyld3::Array<dyld4::Loader::MissingFlatLazySymbol> const&) const + 28
1   dyld                          	       0x184a4f354 dyld3::MachOAnalyzer::forEachRebase_Opcodes(Diagnostics&, dyld3::MachOLoaded::LinkEditInfo const&, dyld3::MachOFile::SegmentInfo const*, void (char const*, dyld3::MachOLoaded::LinkEditInfo const&, dyld3::MachOFile::SegmentInfo const*, bool, unsigned int, unsigned char, unsigned long long, dyld3::MachOAnalyzer::Rebase, bool&) block_pointer) const + 660
2   dyld                          	       0x184a4f084 dyld3::MachOAnalyzer::forEachRebaseLocation_Opcodes(Diagnostics&, void (unsigned long long, bool&) block_pointer) const + 384
3   dyld                          	       0x184a01340 dyld4::Loader::applyFixupsGeneric(Diagnostics&, dyld4::RuntimeState&, unsigned long long, dyld3::Array<void const*> const&, dyld3::Array<void const*> const&, bool, dyld3::Array<dyld4::Loader::MissingFlatLazySymbol> const&) const + 408
4   dyld                          	       0x184a07780 dyld4::JustInTimeLoader::applyFixups(Diagnostics&, dyld4::RuntimeState&, dyld4::DyldCacheDataConstLazyScopedWriter&, bool) const + 616
5   dyld                          	       0x184a27da8 dyld4::APIs::dlopen_from(char const*, int, void*)::$_1::operator()() const + 868
6   dyld                          	       0x184a20558 dyld4::APIs::dlopen_from(char const*, int, void*) + 980
7   Python                        	       0x106343128 _PyImport_FindSharedFuncptr + 136
8   Python                        	       0x1062eb4b4 _PyImport_LoadDynamicModuleWithSpec + 512
9   Python                        	       0x1062ea4f4 _imp_create_dynamic + 168
10  Python                        	       0x1061cd21c cfunction_vectorcall_FASTCALL + 96
11  Python                        	       0x1062a52c4 _PyEval_EvalFrameDefault + 54548
12  Python                        	       0x10616227c object_vacall + 292
13  Python                        	       0x10616210c PyObject_CallMethodObjArgs + 104
14  Python                        	       0x1062e6ff4 PyImport_ImportModuleLevelObject + 1120
15  Python                        	       0x106291938 builtin___import__ + 172
16  Python                        	       0x1061cd324 cfunction_vectorcall_FASTCALL_KEYWORDS + 92
17  Python                        	       0x1062a343c _PyEval_EvalFrameDefault + 46732
18  Python                        	       0x106297a14 PyEval_EvalCode + 304
19  Python                        	       0x106293460 builtin_exec + 472
20  Python                        	       0x1061cd324 cfunction_vectorcall_FASTCALL_KEYWORDS + 92
21  Python                        	       0x1062a52c4 _PyEval_EvalFrameDefault + 54548
22  Python                        	       0x10616227c object_vacall + 292
23  Python                        	       0x10616210c PyObject_CallMethodObjArgs + 104
24  Python                        	       0x1062e6ff4 PyImport_ImportModuleLevelObject + 1120
25  Python                        	       0x1062a0210 _PyEval_EvalFrameDefault + 33888
26  Python                        	       0x106297a14 PyEval_EvalCode + 304
27  Python                        	       0x106293460 builtin_exec + 472
28  Python                        	       0x1061cd324 cfunction_vectorcall_FASTCALL_KEYWORDS + 92
29  Python                        	       0x1062a343c _PyEval_EvalFrameDefault + 46732
30  Python                        	       0x10634411c pymain_run_module + 280
31  Python                        	       0x106343534 Py_RunMain + 648
32  Python                        	       0x106343dc8 pymain_main + 500
33  Python                        	       0x106343ee4 Py_BytesMain + 40
34  dyld                          	       0x1849e90e0 start + 2360

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000016b0c0050   x1: 0x0000000000094000   x2: 0x000000016b0bfc57   x3: 0x000000016b0c0060
    x4: 0x0000000184a015b4   x5: 0x0000000000000008   x6: 0x0000000000000002   x7: 0x0000000000000000
    x8: 0x00000001051e8000   x9: 0x00000001051e8000  x10: 0x0000000105288034  x11: 0x0000000184a710c5
   x12: 0x0000000105288034  x13: 0x0000000000000002  x14: 0x0000000000006d50  x15: 0x000000016b0bfa08
   x16: 0x0000000184a4f2ec  x17: 0x0000000184a4f1c4  x18: 0x0000000000000000  x19: 0x000000010527c000
   x20: 0x0000000000000008  x21: 0x0000000000000001  x22: 0x000000016b0bfcc0  x23: 0x0000000000000103
   x24: 0x0000000000000002  x25: 0x0000000000000000  x26: 0x0000000184a73778  x27: 0x000000016b0bfdc8
   x28: 0x000000016b0bfe60   fp: 0x000000016b0bfbd0   lr: 0xf94e800184a4f354
    sp: 0x000000016b0bfbb0   pc: 0x0000000184a015d0 cpsr: 0x80001000
   far: 0x000000010527c000  esr: 0x92000007 (Data Abort) byte read Translation fault

Binary Images:
       0x1051e8000 -        0x105277fff pyarmor_runtime.so (*) <d517b800-9990-328e-b0e9-9712922619ea> /Users/Shared/*/pyarmor_runtime.so
       0x105090000 -        0x105097fff _struct.cpython-312-darwin.so (*) <43b99fc3-42c1-313d-8ac8-5c94dc28eaeb> /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/lib-dynload/_struct.cpython-312-darwin.so
       0x1060dc000 -        0x1064c3fff org.python.python (3.12.4, (c) 2001-2023 Python Software Foundation.) <4390f71a-f9cd-3981-8043-c8e067914d6b> /Library/Frameworks/Python.framework/Versions/3.12/Python
       0x104d3c000 -        0x104d3ffff org.python.python (3.12.4) <8b1f2b26-4a8b-37ec-93d1-9340b121525b> /Library/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python
       0x1849e3000 -        0x184a77387 dyld (*) <50746901-db0e-39a0-b391-baaa6b82ad0f> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=805.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=805.4M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                   32K        1 
MALLOC                           786.2M       15 
MALLOC guard page                   96K        6 
STACK GUARD                         16K        1 
Stack                             16.0M        1 
VM_ALLOCATE                       3088K        4 
__AUTH                             339K       65 
__AUTH_CONST                      4054K      145 
__DATA                            3199K      144 
__DATA_CONST                      4641K      150 
__DATA_DIRTY                       365K       58 
__LINKEDIT                       893.8M        5 
__OBJC_RO                         71.2M        1 
__OBJC_RW                         2171K        1 
__TEXT                           124.3M      158 
dyld private memory                272K        2 
shared memory                       32K        2 
===========                     =======  ======= 
TOTAL                              1.9G      759 

-----------
Full Report
-----------

{"app_name":"Python","timestamp":"2024-06-10 08:49:45.00 +0200","app_version":"3.12.4","slice_uuid":"8b1f2b26-4a8b-37ec-93d1-9340b121525b","build_version":"3.12.4","platform":1,"bundleID":"org.python.python","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.3.1 (23D60)","roots_installed":0,"name":"Python","incident_id":"2D0103A3-7871-4BFA-A5DB-04D5A2087315"}
{
  "uptime" : 74000,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "coalitionID" : 3140,
  "osVersion" : {
    "train" : "macOS 14.3.1",
    "build" : "23D60",
    "releaseType" : "User"
  },
  "captureTime" : "2024-06-10 08:49:45.1564 +0200",
  "codeSigningMonitor" : 1,
  "incident" : "2D0103A3-7871-4BFA-A5DB-04D5A2087315",
  "pid" : 11660,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-06-10 08:49:45.1047 +0200",
  "procStartAbsTime" : 1796011801303,
  "procExitAbsTime" : 1796013033786,
  "procName" : "Python",
  "procPath" : "\/Library\/Frameworks\/Python.framework\/Versions\/3.12\/Resources\/Python.app\/Contents\/MacOS\/Python",
  "bundleInfo" : {"CFBundleShortVersionString":"3.12.4","CFBundleVersion":"3.12.4","CFBundleIdentifier":"org.python.python"},
  "storeInfo" : {"deviceIdentifierForVendor":"2161C86F-9C99-55AD-8FF5-DC31C79E06D3","thirdParty":true},
  "parentProc" : "bash",
  "parentPid" : 11614,
  "coalitionName" : "com.apple.Terminal",
  "crashReporterKey" : "C7794638-2076-8C03-44C6-CD485BBDA611",
  "responsiblePid" : 3778,
  "responsibleProc" : "Terminal",
  "codeSigningID" : "org.python.python",
  "codeSigningTeamID" : "BMM5U3QVKW",
  "codeSigningFlags" : 587268608,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"9E9Bqf\/DAJH\/D1\/WfyMD1f\/DANH0TwGp\/XsCqf2DAJEIJEKpEwEBiw==","atPC":"aAJA+TQBCIsAGED5CARA+QjZQjmoAAA081MAqUEDANAhYDqRQL7\/lw=="},
  "wakeTime" : 204,
  "sleepWakeUUID" : "5FDD938C-9464-45B9-96AC-20BD55AFF906",
  "sip" : "enabled",
  "vmRegionInfo" : "0x10527c000 is in 0x10527c000-0x105284000;  bytes after start: 0  bytes before end: 32767\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      __DATA_CONST                105278000-10527c000    [   16K] rw-\/rwx SM=COW  ...or_runtime.so\n--->  __DATA                      10527c000-105284000    [   32K] rw-\/rwx SM=COW  ...or_runtime.so\n      __DATA                      105284000-105288000    [   16K] rw-\/rwx SM=NUL  ...or_runtime.so",
  "exception" : {"codes":"0x0000000000000032, 0x000000010527c000","rawCodes":[50,4381458432],"type":"EXC_BAD_ACCESS","signal":"SIGKILL (Code Signature Invalid)","subtype":"UNKNOWN_0x32 at 0x000000010527c000"},
  "termination" : {"flags":0,"code":2,"namespace":"CODESIGNING","indicator":"Invalid Page"},
  "vmregioninfo" : "0x10527c000 is in 0x10527c000-0x105284000;  bytes after start: 0  bytes before end: 32767\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      __DATA_CONST                105278000-10527c000    [   16K] rw-\/rwx SM=COW  ...or_runtime.so\n--->  __DATA                      10527c000-105284000    [   32K] rw-\/rwx SM=COW  ...or_runtime.so\n      __DATA                      105284000-105288000    [   16K] rw-\/rwx SM=NUL  ...or_runtime.so",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1169911,"threadState":{"x":[{"value":6090915920},{"value":606208},{"value":6090914903},{"value":6090915936},{"value":6520051124,"symbolLocation":0,"symbol":"invocation function for block in dyld4::Loader::applyFixupsGeneric(Diagnostics&, dyld4::RuntimeState&, unsigned long long, dyld3::Array<void const*> const&, dyld3::Array<void const*> const&, bool, dyld3::Array<dyld4::Loader::MissingFlatLazySymbol> const&) const"},{"value":8},{"value":2},{"value":0},{"value":4380852224},{"value":4380852224},{"value":4381507636},{"value":6520508613},{"value":4381507636},{"value":2},{"value":27984},{"value":6090914312},{"value":6520369900,"symbolLocation":556,"symbol":"dyld3::MachOAnalyzer::forEachRebase_Opcodes(Diagnostics&, dyld3::MachOLoaded::LinkEditInfo const&, dyld3::MachOFile::SegmentInfo const*, void (char const*, dyld3::MachOLoaded::LinkEditInfo const&, dyld3::MachOFile::SegmentInfo const*, bool, unsigned int, unsigned char, unsigned long long, dyld3::MachOAnalyzer::Rebase, bool&) block_pointer) const"},{"value":6520369604,"symbolLocation":260,"symbol":"dyld3::MachOAnalyzer::forEachRebase_Opcodes(Diagnostics&, dyld3::MachOLoaded::LinkEditInfo const&, dyld3::MachOFile::SegmentInfo const*, void (char const*, dyld3::MachOLoaded::LinkEditInfo const&, dyld3::MachOFile::SegmentInfo const*, bool, unsigned int, unsigned char, unsigned long long, dyld3::MachOAnalyzer::Rebase, bool&) block_pointer) const"},{"value":0},{"value":4381458432},{"value":8},{"value":1},{"value":6090915008},{"value":259},{"value":2},{"value":0},{"value":6520518520},{"value":6090915272},{"value":6090915424}],"flavor":"ARM_THREAD_STATE64","lr":{"value":17964436707636212564},"cpsr":{"value":2147487744},"fp":{"value":6090914768},"sp":{"value":6090914736},"esr":{"value":2449473543,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":6520051152,"matchesCrashFrame":1},"far":{"value":4381458432}},"queue":"com.apple.main-thread","frames":[{"imageOffset":124368,"symbol":"invocation function for block in dyld4::Loader::applyFixupsGeneric(Diagnostics&, dyld4::RuntimeState&, unsigned long long, dyld3::Array<void const*> const&, dyld3::Array<void const*> const&, bool, dyld3::Array<dyld4::Loader::MissingFlatLazySymbol> const&) const","symbolLocation":28,"imageIndex":4},{"imageOffset":443220,"symbol":"dyld3::MachOAnalyzer::forEachRebase_Opcodes(Diagnostics&, dyld3::MachOLoaded::LinkEditInfo const&, dyld3::MachOFile::SegmentInfo const*, void (char const*, dyld3::MachOLoaded::LinkEditInfo const&, dyld3::MachOFile::SegmentInfo const*, bool, unsigned int, unsigned char, unsigned long long, dyld3::MachOAnalyzer::Rebase, bool&) block_pointer) const","symbolLocation":660,"imageIndex":4},{"imageOffset":442500,"symbol":"dyld3::MachOAnalyzer::forEachRebaseLocation_Opcodes(Diagnostics&, void (unsigned long long, bool&) block_pointer) const","symbolLocation":384,"imageIndex":4},{"imageOffset":123712,"symbol":"dyld4::Loader::applyFixupsGeneric(Diagnostics&, dyld4::RuntimeState&, unsigned long long, dyld3::Array<void const*> const&, dyld3::Array<void const*> const&, bool, dyld3::Array<dyld4::Loader::MissingFlatLazySymbol> const&) const","symbolLocation":408,"imageIndex":4},{"imageOffset":149376,"symbol":"dyld4::JustInTimeLoader::applyFixups(Diagnostics&, dyld4::RuntimeState&, dyld4::DyldCacheDataConstLazyScopedWriter&, bool) const","symbolLocation":616,"imageIndex":4},{"imageOffset":282024,"symbol":"dyld4::APIs::dlopen_from(char const*, int, void*)::$_1::operator()() const","symbolLocation":868,"imageIndex":4},{"imageOffset":251224,"symbol":"dyld4::APIs::dlopen_from(char const*, int, void*)","symbolLocation":980,"imageIndex":4},{"imageOffset":2519336,"symbol":"_PyImport_FindSharedFuncptr","symbolLocation":136,"imageIndex":2},{"imageOffset":2159796,"symbol":"_PyImport_LoadDynamicModuleWithSpec","symbolLocation":512,"imageIndex":2},{"imageOffset":2155764,"symbol":"_imp_create_dynamic","symbolLocation":168,"imageIndex":2},{"imageOffset":987676,"symbol":"cfunction_vectorcall_FASTCALL","symbolLocation":96,"imageIndex":2},{"imageOffset":1872580,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":54548,"imageIndex":2},{"imageOffset":549500,"symbol":"object_vacall","symbolLocation":292,"imageIndex":2},{"imageOffset":549132,"symbol":"PyObject_CallMethodObjArgs","symbolLocation":104,"imageIndex":2},{"imageOffset":2142196,"symbol":"PyImport_ImportModuleLevelObject","symbolLocation":1120,"imageIndex":2},{"imageOffset":1792312,"symbol":"builtin___import__","symbolLocation":172,"imageIndex":2},{"imageOffset":987940,"symbol":"cfunction_vectorcall_FASTCALL_KEYWORDS","symbolLocation":92,"imageIndex":2},{"imageOffset":1864764,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":46732,"imageIndex":2},{"imageOffset":1817108,"symbol":"PyEval_EvalCode","symbolLocation":304,"imageIndex":2},{"imageOffset":1799264,"symbol":"builtin_exec","symbolLocation":472,"imageIndex":2},{"imageOffset":987940,"symbol":"cfunction_vectorcall_FASTCALL_KEYWORDS","symbolLocation":92,"imageIndex":2},{"imageOffset":1872580,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":54548,"imageIndex":2},{"imageOffset":549500,"symbol":"object_vacall","symbolLocation":292,"imageIndex":2},{"imageOffset":549132,"symbol":"PyObject_CallMethodObjArgs","symbolLocation":104,"imageIndex":2},{"imageOffset":2142196,"symbol":"PyImport_ImportModuleLevelObject","symbolLocation":1120,"imageIndex":2},{"imageOffset":1851920,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":33888,"imageIndex":2},{"imageOffset":1817108,"symbol":"PyEval_EvalCode","symbolLocation":304,"imageIndex":2},{"imageOffset":1799264,"symbol":"builtin_exec","symbolLocation":472,"imageIndex":2},{"imageOffset":987940,"symbol":"cfunction_vectorcall_FASTCALL_KEYWORDS","symbolLocation":92,"imageIndex":2},{"imageOffset":1864764,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":46732,"imageIndex":2},{"imageOffset":2523420,"symbol":"pymain_run_module","symbolLocation":280,"imageIndex":2},{"imageOffset":2520372,"symbol":"Py_RunMain","symbolLocation":648,"imageIndex":2},{"imageOffset":2522568,"symbol":"pymain_main","symbolLocation":500,"imageIndex":2},{"imageOffset":2522852,"symbol":"Py_BytesMain","symbolLocation":40,"imageIndex":2},{"imageOffset":24800,"symbol":"start","symbolLocation":2360,"imageIndex":4}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4380852224,
    "size" : 589824,
    "uuid" : "d517b800-9990-328e-b0e9-9712922619ea",
    "path" : "\/Users\/Shared\/*\/pyarmor_runtime.so",
    "name" : "pyarmor_runtime.so"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4379443200,
    "size" : 32768,
    "uuid" : "43b99fc3-42c1-313d-8ac8-5c94dc28eaeb",
    "path" : "\/Library\/Frameworks\/Python.framework\/Versions\/3.12\/lib\/python3.12\/lib-dynload\/_struct.cpython-312-darwin.so",
    "name" : "_struct.cpython-312-darwin.so"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4396531712,
    "CFBundleShortVersionString" : "3.12.4, (c) 2001-2023 Python Software Foundation.",
    "CFBundleIdentifier" : "org.python.python",
    "size" : 4096000,
    "uuid" : "4390f71a-f9cd-3981-8043-c8e067914d6b",
    "path" : "\/Library\/Frameworks\/Python.framework\/Versions\/3.12\/Python",
    "name" : "Python",
    "CFBundleVersion" : "3.12.4"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4375953408,
    "CFBundleShortVersionString" : "3.12.4",
    "CFBundleIdentifier" : "org.python.python",
    "size" : 16384,
    "uuid" : "8b1f2b26-4a8b-37ec-93d1-9340b121525b",
    "path" : "\/Library\/Frameworks\/Python.framework\/Versions\/3.12\/Resources\/Python.app\/Contents\/MacOS\/Python",
    "name" : "Python",
    "CFBundleVersion" : "3.12.4"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6519926784,
    "size" : 607112,
    "uuid" : "50746901-db0e-39a0-b391-baaa6b82ad0f",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6519177216,
  "size" : 4065345536,
  "uuid" : "c32b200e-cf99-3583-bc9f-b7fb11382e8f"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=805.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=805.4M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nKernel Alloc Once                   32K        1 \nMALLOC                           786.2M       15 \nMALLOC guard page                   96K        6 \nSTACK GUARD                         16K        1 \nStack                             16.0M        1 \nVM_ALLOCATE                       3088K        4 \n__AUTH                             339K       65 \n__AUTH_CONST                      4054K      145 \n__DATA                            3199K      144 \n__DATA_CONST                      4641K      150 \n__DATA_DIRTY                       365K       58 \n__LINKEDIT                       893.8M        5 \n__OBJC_RO                         71.2M        1 \n__OBJC_RW                         2171K        1 \n__TEXT                           124.3M      158 \ndyld private memory                272K        2 \nshared memory                       32K        2 \n===========                     =======  ======= \nTOTAL                              1.9G      759 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "2345ad6cdee31c66bff10f547af75b2dc8b160b2",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "64628732bf2f5257dedc8988",
      "factorPackIds" : {

      },
      "deploymentId" : 240000001
    },
    {
      "rolloutId" : "6297d96be2c9387df974efa4",
      "factorPackIds" : {

      },
      "deploymentId" : 240000025
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "3dff9c91-a8fb-424e-a656-c8d6e6037574",
      "experimentId" : "662152ede2d11d1408c4db33",
      "deploymentId" : 400000015
    },
    {
      "treatmentId" : "45f4e2a5-551b-4bc2-a2dc-19c244dda8f8",
      "experimentId" : "6643969b3099cf28e049862f",
      "deploymentId" : 400000004
    }
  ]
}
}

Model: MacBookAir10,1, BootROM 10151.81.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Aug 26 2023 17:55:53 version 18.20.439.0.7.8.163 FWID 01-f9b9247b
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: USB2.0 Hub
USB Device: Splash Black
USB Device: USB 2.0 BILLBOARD
USB Device: USB Optical Mouse
USB Device: USB Billboard Device
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by jondy** [comment]
Please check the guide 
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html

And report with useful information
