### ISSUE TITLE
Run pyarmor without encryption

### ISSUE THREAD

**Issue by chendu1993** [dashingsoft/pyarmor#1819]
I'm just running "pyarmor gen" but the output comes encrypted by default. Even running "pyarmor gen --enable-rft" produces encrypted output by default. I want to be able to run pyarmor without encryption turned on to see what it is doing similar to how it is described here:
<img width="1152" alt="pyarmor_no_encryption" src="https://github.com/dashingsoft/pyarmor/assets/9501975/e33d4b7c-4f29-46b4-8e83-c7ea299fe9f8">

**Comment by jondy** [comment]
Please check topic `inside into RFT mode` in the online doc.
