### ISSUE TITLE
Upgrade causing errors

### ISSUE THREAD

**Issue by TupelUK** [dashingsoft/pyarmor#182]
I could successfully obfuscate and pack using:

pyarmor pack C:\Work-xxx\python\xxx.spec

with version 4.6.1 of pyarmor, python3.6 (installed in c:\python\), windows 10 64 bit.

I then upgraded to python3.8 (installed in c:\Program Files\python38), and pyarmor 5.9.0, I got an error:

INFO     PyArmor Trial Version 5.9.0
ERROR    No project C:\Work-xxx\python\xxx.spec found

However I did copy license.lic into C:\Program Files\Python38\Lib\site-packages, and C:\Work-xxx\python\xxx.spec does exist.

Do you think this is a bug or user error? Help greatly appreciated.

**Comment by jondy** [comment]
In v5.9.0, it need extra steps to bundle obfuscated scripts with customized spec file, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#bundle-obfuscated-scripts-with-customized-spec-file

**Comment by TupelUK** [comment]
Here is my progress:

I received a new registration key for the pyarmor v5.9.0 so I could update my old license.lic file to the new style pyarmor-regfile-1.zip (thank you). Now my pyarmor is a registered version.

Following your advice above, I can successfully pack my code, and confirm that it runs with the license.lic file and not if the license.lic file is deleted, so all seems well.

However I am using Numba to make compiled code for some parts of the software and when it reaches this part of the code it crashes out with this error:

Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "<frozen scanPC>", line 89, in doScan
  File "<frozen shotCollector>", line 64, in doShotCollection
  File "<frozen shotCollector>", line 186, in processImages
  File "<frozen shotCollector>", line 195, in processImagePair
  File "<frozen triangulatorPC>", line 28, in triangulate
  File "<frozen disparityMapper>", line 135, in disparityMapperLR
  File "site-packages\numba\dispatcher.py", line 404, in _compile_for_args
  File "site-packages\numba\dispatcher.py", line 344, in error_rewrite
  File "site-packages\numba\six.py", line 668, in reraise
numba.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (LOAD_NAME) found

File "<frozen disparityMapper>", line 143:
<source missing, REPL/exec in use?>

This did not used to happen with numba 0.39.0 and pyarmor 4.6.1.
It is happening now with numba 0.48.0.1 and pyarmor 5.9.0.

Do you know how can I solve this?

**Comment by cmarin-cs** [comment]
From my experience, `unsupported opcode` is due to the change in Python version, more here: https://github.com/dashingsoft/pyarmor/issues/145

**Comment by TupelUK** [comment]
@cmarin-cs, yes since it was working I have changed python version too (I've edited the post to show this now).

However, I am doing the pyarmor pack with python3.8 and it should also be using python3.8 to run (because its python3.8 that was packaged into the dist folder).

Its hard to go back to python3.6 because I needed python 3.8 to get another tricky library to build.

**Comment by TupelUK** [comment]
I suspect the error is linked to this issue on numba:

#133 

Its odd that Numba worked ok in previous versions, but anyway, if I put all my numba functions in one py file I think I can skip obfuscation on them by doing this:

pyarmor pack -x " --exclude numbaFunctions.py"  -s main.spec main.py

This seems to be packing and executing ok.

I presume I lose security on the numba functions but the rest of the code is protected?  A second opinion would be welcome.

**Comment by jondy** [comment]
Yes, the `numbaFunctions.py` isn't obfuscated, and all the other scripts are obfuscated. numba should not work in latest version as described in #133

**Comment by TupelUK** [comment]
Excellent, so I think that's case closed from my point of view, pyarmor is working for me again.  Thanks for your quick help.

**Comment by TupelUK** [comment]
Excellent, so I'm back up and running again.  Thanks for your quick support.
