### ISSUE TITLE
[BUG] Pyarmor randomly mis-classifying license

### ISSUE THREAD

**Issue by fadebek** [dashingsoft/pyarmor#1825]
I have a pyarmor pro license. I notice that in my github actions, the `pyarmor reg` command only works half of the time. Sometimes it will activate my license to pro, but other times, it will show trial:

```
INFO     Python 3.10.14
INFO     Pyarmor 8.5.9 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     Current license information:

License Type    : pyarmor-trial
License No.     : pyarmor-vax-000000
License To      : 
License Product : non-profits

BCC Mode        : No
RFT Mode        : No

Notes
* Can't obfuscate big script and mix str
```

This is causing us to have unobfuscated code since pyarmor silently just copies the plain scripts for the trial version.

**Comment by jondy** [comment]
Please check 
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#registration-failed

I may disable this feature to copy plain script to output when out of license in next release

**Comment by fadebek** [comment]
I see, is the group license still subject to "3 registrations in 1 minute"?
