### ISSUE TITLE
[BUG] --assert-call doesn't work correctly with context managers

### ISSUE THREAD

**Issue by Thoufak** [dashingsoft/pyarmor#1827]
### Command
`pyarmor gen test.py --assert-call`

### Error
```
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen test>", line 9, in <module>
RuntimeError: protection exception (16777934)
```

### test.py file
```
from contextlib import contextmanager

@contextmanager
def manager():
    yield None

print("Start")

with manager():
    print("It works!")
```

**Comment by jondy** [comment]
Reproduced.

Because function `manager` is decorated by `contextmanager`, so it's not obfuscated.

I need find one solution for this case.

Thanks.

**Comment by jondy** [comment]
Now try to exclude it by this way
```
$ pyarmor cfg assert.call:excludes "manager"
```

It's a little complicated to auto-exclude this case, so just exclude it manually. In future, when RFT mode is refined, pyarmor may exclude this case automatically.
