### ISSUE TITLE
Multiple entry scripts

### ISSUE THREAD

**Issue by MathieuPierfitte** [dashingsoft/pyarmor#183]
Hi,

I am trying to use pyarmor on a group of scripts that doesn't have a single entry script, because those scripts are loaded by a program that uses reflection to discover them.

So, what I have is essentially:

```
src/
  script_1.py
  script_2.py
  libs/
    lib_1.py
    lib_2.py
```

In this scenario, I need the bootstrap code to be added to both `src/script_1.py` and `src/script_2.py`, because I'll never call `import script_1` or `import script_2` myself.

Using pyarmor 5.3.13, I used to be able to alter those two scripts after they have been generated by just adding `from pytransform import pyarmor_runtime; pyarmor_runtime()` as the first line.

My problem is, this hack doesn't work anymore: I fall into the ["Check restrict mode failed"](https://pyarmor.readthedocs.io/en/latest/questions.html#check-restrict-mode-failed) situation.

Is there a way for me to get this to work with the latest version?

Cheers.

**Comment by jondy** [comment]
In latest version,  a single entry script could be obfuscated by this command:
```
pyarmor obfuscate --no-runtime --exact script_2.py
```

**Comment by MathieuPierfitte** [comment]
Correct me if I'm wrong, but I don't think I can pass a _list_ of entry scripts to this command, right?

Also, I don't think there is an option for me to run the obfuscation on my list of entry scripts one by one using your command. `pyarmor obfuscate` isn't meant to be called multiple times, as far as I know.

**Comment by jondy** [comment]
For the latest version, a list of entry scripts can be accept with option `--exact`
```
pyarmor --exact --no-runtime a.py b.py c.py 
```

**Comment by MathieuPierfitte** [comment]
Thank you, the `--exact` flag appears to be what I was looking for.
