### ISSUE TITLE
[BUG] `Error in Docs`

### ISSUE THREAD

**Issue by ChangjunDAI** [dashingsoft/pyarmor#1830]
#1829 
https://pyarmor.readthedocs.io/zh/latest/tutorial/obfuscation.html#id12
![image](https://github.com/dashingsoft/pyarmor/assets/65420228/e57909af-662b-4295-a07b-4d7c3640d8c5)
示例代码中`vi .pyarmor/message.cf`的message后面少了s
搞半天问题在这里...文档有空更新一下吧

**Comment by jondy** [comment]
已经修改
