### ISSUE TITLE
[BUG] Unauthorized use of script when using --private with latest Pyarmor

### ISSUE THREAD

**Issue by fadebek** [dashingsoft/pyarmor#1831]
Based on the docs, it seems that after 8.5.3, `--private` allows you to import the module but but not access `__dict__`. However, I am still observing the old behavior. I ran `pyarmor gen -i -r --private` and when trying to run the script it says "unauthorized use of script"

**Comment by jondy** [comment]
Can't reproduced. Please describe it with shell command and show pyarmor version.
