### ISSUE TITLE
support for pyinstaller >= 6 

### ISSUE THREAD

**Issue by kletel** [dashingsoft/pyarmor#1834]
(venv) C:\Users\Sebastien\PycharmProjects\bkubedesktop>pyarmor gen -O obfdist --pack dist\bkube\bkube.exe bkube.py
INFO     Python 3.12.3
INFO     Pyarmor 8.5.9 (pro), 005076, bkube
INFO     Platform windows.x86_64
INFO     implicitly save obfuscated scripts to ".pyarmor\pack\dist"
INFO     extracting bundle "dist\bkube\bkube.exe"
INFO     Please check documentation `insight into pack command`to find solutions or downgrade PyInstaller to version 5
ERROR    PyInstaller 6.0.0 isn't supported
ERROR    something is wrong
*=============================================================*

_Originally posted by @kletel in https://github.com/dashingsoft/pyarmor/issues/1824#issuecomment-2165878749_

**Comment by jondy** [comment]
Please use `--pack onefile` or `--pack folder`, do not use `--pack executable file`.

This has been documented in the topic `inside into pack command`

**Comment by kletel** [comment]
Thank you jondy, it's working
