### ISSUE TITLE
Obfuscating 2 libs

### ISSUE THREAD

**Issue by MathieuPierfitte** [dashingsoft/pyarmor#184]
Hi,

I am using a dependency that was obfuscated using pyarmor. It is working great.

I can also use the non-obfuscated version of this dependency, and obfuscate my own code fine.

Problem is, when I try obfuscating both of these at the same time, I keep getting ["Marshal loads failed when running xxx.py"](https://pyarmor.readthedocs.io/en/latest/questions.html#marshal-loads-failed-when-running-xxx-py) errors.

1. Since I can obfuscate one of them at a time just fine, I'm fairly sure this is not a Python version mismatch problem.
2. Since I rely on a C program running my Python code, I don't think I can simulate running my code with `python -d` unfortunately.
3. I assume the problem has to do with the capsule then?

I was suspecting the problem might be that I am using the same license for both libs, so I tried obfuscating the 2nd one with the default license: same problem.

I am using pyarmor 5.3.13 for both of them, and I noticed the latest version offers a way to [solve conflicts with other obfuscated libraries](https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-package-no-conflict-with-others). So I tried updating to pyarmor 5.9.0 to see if that would solve my problem, but then I ran into another issue (see #183 ).

Is there any recommendation on how to deal with this kind of use case, if it's even possible?
Merging those code bases so that I can obfuscate both of them at once, thus generating a single capsule, isn't really an option for me unfortunately.

Cheers.

**Comment by MathieuPierfitte** [comment]
Hacking my way around a bit, I got this error (using v5.9.0):

```
Initialize python patcher failed (1534)
Python marshal loads failed
Pytransform Error: Marshal loads failed when running xxx.py
```

How can I know what `Initialize python patcher failed (1534)` means?

**Comment by jondy** [comment]
The new option `--enable-suffix` is just for this case. 
First remove all the old obfuscated files, then obfuscate the package with `--enable-suffix`, for example,
```
cd /path/to/src
pyarmor obfuscate -O dist/mypackage --enable-suffix mypackage/__init__.py
```
Then obfuscate the main script without `--enable-suffix`, make sure `dist/mypackage` isn't overwritten:
```
cd /path/to/src
pyarmor obfuscate --exclude mypackage main.py 
```

**Comment by jondy** [comment]
> How can I know what Initialize python patcher failed (1534) means?
This means that pyarmor fails to initialize the advanced mode. In this case, try to hack `pytransform.py` in the pyarmor package, uncomment line 277:
```
    # Disable advanced mode if required
    m.set_option(5, c_char_p(1))
``` 
Then obfuscate the package again

**Comment by MathieuPierfitte** [comment]
With this change, the first line is gone, but the error isn't

```
Python marshal loads failed
Pytransform Error: Marshal loads failed when running xxx.py
```

**Comment by jondy** [comment]
> The new option `--enable-suffix` is just for this case.
> First remove all the old obfuscated files, then obfuscate the package with `--enable-suffix`, for example,
> 
> ```
> cd /path/to/src
> pyarmor obfuscate -O dist/mypackage --enable-suffix mypackage/__init__.py
> ```
> 
> Then obfuscate the main script without `--enable-suffix`, make sure `dist/mypackage` isn't overwritten:
> 
> ```
> cd /path/to/src
> pyarmor obfuscate --exclude mypackage main.py 
> ```

Does it work?

**Comment by MathieuPierfitte** [comment]
I'm not there yet unfortunately, because I can't even get as far as I used to with 5.3.13, where obfuscating one lib was working as long as the other was not obfuscated with pyarmor.

I am still running into [this error](https://github.com/dashingsoft/pyarmor/issues/184#issuecomment-583209639).

**Comment by jondy** [comment]
Try to remove all the old obfuscated scripts, uninstall pyarmor completely and install the latest version
https://pyarmor.readthedocs.io/en/latest/installation.html#clean-uninstallation
Then obfuscate the scripts again
