### ISSUE TITLE
[Feature] obfuscate code for x86_64 on an ARM machine

### ISSUE THREAD

**Issue by Kaiyangshi-Ito** [dashingsoft/pyarmor#1840]
Now thanks to rosetta2 and prism, we can run x86_64 softwares on ARM machines. Can we obfuscate these codes as well since most servers don't use ARM and some of us want to use it to run things on computing servers? Thanks.

**Comment by jondy** [comment]
Please check option `--platform` and search cross platform obfuscation in the doc
