### ISSUE TITLE
[BUG] RuntimeError: request license token failed (101): Success

### ISSUE THREAD

**Issue by fadebek** [dashingsoft/pyarmor#1847]
Pyarmor version 8.5.8 on linux. I have a pro license. Im getting the following sometimes when running in a github action

```
DEBUG    unknown error, please check pyarmor.error.log
ERROR    request license token failed (101): Success
ERROR    something is wrong
*=============================================================*
*  Please check                                               *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*  or run `pyarmor man` to find solutions quickly             *
*                                                             *
*  It's recommand to report issue by `pyarmor man` in order   *
*  to provide necessary information, and avoid dupcliated     *
*  issues or unclear question.                                *
*=============================================================*
```

Upon checking `pyarmor.error.log` I see `RuntimeError: request license token failed (101): Success`. I cannot determine what this means.

**Comment by jondy** [comment]
Please check this first
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#registration-failed

**Comment by fadebek** [comment]
@jondy Why was this marked as invalid? The error code (101) is not mentioned anywhere in the docs. It is not clear what the cause of the error is nor how I can fix it

**Comment by jondy** [comment]
Because there is a check list about this kind of issue
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#registration-failed

Please first check this
