### ISSUE TITLE
No module named 'telegram'

### ISSUE THREAD

**Issue by Stealth-Sec** [dashingsoft/pyarmor#1848]
Problem: Module not found after creating and running the .exe

Reproduced steps:
- My code is a Telegram bot
- pyarmor gen --pack onefile bot.py
- I get my .exe

Actual results:
- .exe is created
- Running it throws an error

Error:
- Message: No module named 'telegram'

Please help me since I really need my .exe to work. Thanks

**Comment by jondy** [comment]
Please follow this guide
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#failed-to-run-the-packed-obfuscated-scripts
