### ISSUE TITLE
[BUG] `No free tokens for [URL]`

### ISSUE THREAD

**Issue by fadebek** [dashingsoft/pyarmor#1851]
Im using Pyarmor 8.5.8 and have a pro license. I'm getting the following error when trying to use pyarmor:

`RuntimeError: request license token failed (5): ER:no free tokens for 864791913PZ0XeYxCCswAajcWzhNBcvxmxbm6gx0LcxxQizffTg8laxGQRcJ7nRO8iXpoqWYtHstGwhjNOvpdda7mWLE0qTkcy90Kg7v4o0x7MpuO_BQtzu8kswxGUfKZ0hLqlJPHiQYYVv4o6-IruxLjjBprzpYM_UX6L9I9wx_ubUpS05DKoR5A2CowZHo912KsjKb6FcQDcBm9yJ3-eV-kd-LMzE6RajaNlZElrYsprjZxuamIuNUHWsDWB61nsZyPUUfs6QESGHH9AX7hp8TzoW3iBwTZ-IG6yrD_1Bu4KOZqCvydi1m3VoR2uGx825k1k5TQ9xIYZXUQ&timestamp=1719490615&rev=1&token=0&machine=b1a5f27b22c8681cd13524659f1775215`

There is no mention of this type of error from the docs. Is there a way to fix this?

**Comment by jondy** [comment]
In 24 hours, only 100 runs in different device or docker container.
