### ISSUE TITLE
[BUG] __pyarnor__ is not defined

### ISSUE THREAD

**Issue by RobertAzovski** [dashingsoft/pyarmor#1855]
`print('this is __pyarmor__', __pyarmor__)`

I don’t understand what happened, everything worked fine for several days. I didn't change anything in the project. But now I see this problem.

I use:
python 3.11.3
pyarmor==8.5.9
pyinstaller==5.13.2

This is a command how I build an executable:
`pyarmor gen -b 6E:D8:9A:3A:01:63 -e 7 --pack onefile myUiExample.py`

![image](https://github.com/dashingsoft/pyarmor/assets/111636889/0715d671-d4cd-4e83-8fb7-876d49c7a971)

**Comment by jondy** [comment]
Please check online doc `topics/insight into pack command` first.
