### ISSUE TITLE
[BUG] `argument "" doesn't exists`

### ISSUE THREAD

**Issue by Jeffrey2971** [dashingsoft/pyarmor#1857]
(pyarmor_env2) C:\Users\jeffrey\Desktop\gui2\gui>pyarmor -d gen --pack onefile run.py
INFO     Python 3.8.19
INFO     Pyarmor 8.5.10 (trial), 000000, non-profits
INFO     Platform windows.x86_64
DEBUG    native platform windows.amd64
DEBUG    home path: C:\Users\jeffrey\.pyarmor
INFO     implicitly save obfuscated scripts to ".pyarmor\pack\dist"
DEBUG    command options: {'no_runtime': False, 'inputs': ['run.py'], 'output': '.pyarmor\\pack\\dist'}
DEBUG    install plugin: CodesignPlugin
DEBUG    install plugin: DarwinUniversalPlugin
DEBUG    Loaded ctypes backend
INFO     search inputs ...
INFO     find script run.py
INFO     find 1 top resources
DEBUG    C:\Users\jeffrey\miniconda3\envs\pyarmor_env2\python.exe -m PyInstaller.utils.cliutils.makespec run.py
INFO     call PyInstaller to generate specfile
DEBUG    C:\Users\jeffrey\miniconda3\envs\pyarmor_env2\python.exe -m PyInstaller --clean --workpath .pyarmor\pack\build run.spec
INFO     call PyInstaller to analysis, it may take several minutes ...
INFO     find extra resources: ['']
ERROR    argument "" doesn't exists
INFO     generate bug file "pyarmor.report.bug"
ERROR    something is wrong
*=============================================================*
*  Please check console log to find out what's wrong          *
*                                                             *
*  If still not solved, please find solutions by              *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*=============================================================*

[pyarmor.report.bug.log](https://github.com/user-attachments/files/16062515/pyarmor.report.bug.log)

**Comment by jondy** [comment]
Could you edit `run.spec`, replace line `for name, path, kind in a.pure:` with the following lines
```python
print(nsrc, 'rsrc is ', repr(rsrc))
for name, path, kind in a.pure:
    print(name, path, kind)
```

And then run command 
```
C:\Users\jeffrey\miniconda3\envs\pyarmor_env2\python.exe -m PyInstaller --clean --workpath .pyarmor\pack\build run.spec  
```

And copy output log here
