### ISSUE TITLE
[BUG] Use --platform musl.x86_64 to use in Alpine Docker

### ISSUE THREAD

**Issue by michelmetran** [dashingsoft/pyarmor#1858]
I'm having trouble obfuscating code on different platforms.

I'm in a Windows environment, (python 3.11.9 and Pyarmor 8.5.10 - trial). I can generate the obfuscated package for Windows and Linux. Success!

When I also try with Alpine, to use in Docker, it gives an error.
````shell
(.venv) PS C:\Users\michel\outros> pyarmor -d gen --enable-jit --assert-import --assert-call --platform musl.x86_64 -O dist -r -i pkg
INFO     Python 3.11.9
INFO     Pyarmor 8.5.10 (trial), 000000, non-profits
INFO     Platform windows.x86_64
DEBUG    native platform windows.amd64
DEBUG    home path: C:\Users\michel\.pyarmor
INFO     use runtime platforms: ['musl.x86_64']
DEBUG    command options: {'recursive': True, 'output': 'dist', 'no_runtime': False, 'enable_jit': True, 'assert_import': True, 'assert_call': True, 'import_prefix': 1, 'restrict_module': 3, 'platforms': ['musl.x86_64'], 'inputs': ['pkg']}
INFO     install packages ['pyarmor.cli.core.musl==6.5.3'] for cross platforms
ERROR: Could not find a version that satisfies the requirement pyarmor.cli.core.musl==6.5.3 (from versions: none)
ERROR: No matching distribution found for pyarmor.cli.core.musl==6.5.3
ERROR    Command '['C:\\Users\\michel\\outros\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', '--disable-pip-version-check', 'pyarmor.cli.core.musl==6.5.3']' returned non-zero exit status 1.
````

<br>

It tries to install a package that apparently doesn't exist.

I try to install, manually,  `pyarmor.cli.core.musl`: error!!!!

````shell
pip install pyarmor.cli.core.musl
````

<br>

I saw references to `pyarmor.cli.core.alpine` and I even managed to install it. Success!
```
pip install pyarmor.cli.core.alpine
```

Where am I going wrong that it doesn't build for Alpine?
Is it correct for PyArmor to call `pyarmor.cli.core.musl`?! Wouldn't the correct option be `pyarmor.cli.core.alpine`?

... I read some issues and discussions (#1161 #1623 ), but I didn't find an answer.

**Comment by jondy** [comment]
Use `--platform alpine.x86_64` instead of `--platform --platform musl.x86_64`
