### ISSUE TITLE
[咨询] 7.x还安全吗？ 升级8版本后7.x版本还可以正常使用liscense注册和使用吗？

### ISSUE THREAD

**Issue by ykk648** [dashingsoft/pyarmor#1859]
1. 7.x还安全吗？ 
2. 升级8版本后7.x版本还可以正常使用liscense注册和使用吗？
3. 我没有txt文件，只有164位注册码可以升级到8吗？

**Comment by jondy** [comment]
在线文档中有 许可证类型 中有关于升级的说明，没有 .txt 是无法升级的。

老许可证只能用于 pyarmor < 8.0 的版本，详细说明请参考项目 README.md 中说明
