### ISSUE TITLE
SystemError: unknown opcode with advanced mode

### ISSUE THREAD

**Issue by RobinFrcd** [dashingsoft/pyarmor#186]
Hi
I'm using PyArmor **5.8.9** on MacOS and when I try to run obfuscated code, some functions yield a SystemError: `SystemError: unknown opcode`. 

If I disable the advanced mode, everything works fine, but I'd like to use this mode.

I'm on catalina 10.15.3, I've tried with both python 3.6.8 and 3.7.3, same issue.

Thanks

**Comment by jondy** [comment]
It seems that python dynamic library could not patched by pyarmor correctly, could you upload your python library `libpython3.6m.dylib` and `libpython3.7m.dylib` here? I need check them to fix this problem.

**Comment by RobinFrcd** [comment]
Hi, thanks for your answer.

Here are two dylib, dunno which one of them is used:
```
./3.6.8/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin/libpython3.6m.dylib
./3.6.8/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
```

[libs.zip](https://github.com/dashingsoft/pyarmor/files/4185307/libs.zip)

**Comment by jondy** [comment]
I check both of dynamic libraries, they could be patched by pyarmor. So try to obfuscate a simple script `foo.py`:
```
print('Hello')
```
Then run the obfuscate scripts with option `-d`
```
pyarmor obfuscate --advanced 1 --exact foo.py
cd dist
python -d foo.py
```
What's printed in the console?

**Comment by RobinFrcd** [comment]
`Hello` is well printed. 

The **SystemError** is not raised in every function of my script, but only a few of them. I've been trying to find what's different in these functions, but I couldn't figure it out.

**Comment by jondy** [comment]
Is there any extra message to run your obfuscated scripts with option `-d`?
