### ISSUE TITLE
Question: how to ignore a whole package in bcc mode when using "-r"

### ISSUE THREAD

**Issue by JiaPai12138** [dashingsoft/pyarmor#1863]
This is what i am using:

pyarmor gen -r --mix-str --enable-jit --enable-bcc --enable-themida .
however script will crash and exit immediately without any error msg

i tried
```
pyarmor cfg -p urllib bcc:disabled=1
```
but not working

**Comment by demon071** [comment]
When using --enable-themida is it necessary to install themida?

**Comment by jondy** [comment]
In next release, it will support ignore whole package by this way:

```
pyarmor cfg propagate_package_options=1
pyarmor cfg -p pkgname bcc:disabled=1
```

Here it's pre-release version
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.5.11.zip

For bcc crash issue, it's recommand to disable all scripts and try to enable modules one by one. For example

```
pyarmor cfg bcc:disabled=1

pyarmor cfg -p pkg1.mod1 bcc:disabled=0
pyarmor gen --enable-bcc src
python dist/main.py

  
pyarmor cfg -p pkg1.mod2 bcc:disabled=0
pyarmor gen --enable-bcc src
python dist/main.py
```

**Comment by jondy** [comment]
Please ask question in discussion area and it's better to try it before asking question.
