### ISSUE TITLE
[BUG] `After the Pyarmor encrypted file is compiled, it runs with an error message`

### ISSUE THREAD

**Issue by EMU-TIME** [dashingsoft/pyarmor#1871]
```
Traceback (most recent call last):
  File "mycode_pyarmor.py", line 2, in <module>
ModuleNotFoundError: No module named 'pyarmor_runtime_000000'
```
Packaging with Pyinstaller

**Comment by EMU-TIME** [comment]
As long as the program with a large number of reference packages is encrypted with Pyarmor and packaged with Pyinstaller, this situation will occur, which feels like the reference package is lost.

**Comment by jondy** [comment]
It's better to provide one smallest test scripts and reproduced steps
