### ISSUE TITLE
Use Javascript  to call the  obfuscated python file, is it right usage?

### ISSUE THREAD

**Issue by 6sixteen** [dashingsoft/pyarmor#1874]
1. I use pyarmor gen foo.py to obfuscate the file. 
2. Try to use a javascript to call the file. 
3. Throw runtimeError: unauthorized use of script
Can this be done, or is it not allowed？
Thanks！

**Comment by jondy** [comment]
I also have no idea about call .py from javascript.

Anyway, try to disable restrict mode by this way
```
pyarmor cfg restrict_module=0
pyarmor gen foo.py
```

Then call the obfuscated script again, if it still doesn't work, it may not work.
