### ISSUE TITLE
[BUG] `Pyarmor uses spec files to package encrypted scripts, and Pyinstaller analyzes too many imported packages.`

### ISSUE THREAD

**Issue by ningyungame** [dashingsoft/pyarmor#1879]
My English is not good, so I use Google Translate.

The Python version I am using is 3.11.1
Pyinstaller：5.11.0
Pyarmor：Pyarmor 8.5.10 (basic)

This is my directory
![image](https://github.com/user-attachments/assets/9a5bd9d9-309e-401d-89ef-8bb83fb0b56f)
I am using a virtual environment

I use Pyinstaller to package without Pyarmor encryption, using the command: `pyinstaller Twitch_MainWindow.spec`
The only libraries included in the package are these, and the size of the entire package is 119MB.

![image](https://github.com/user-attachments/assets/50998360-ccb2-47a4-90fc-ba38e30601a1)
![image](https://github.com/user-attachments/assets/63dceace-cde6-4146-b35d-a5e4f4d0e971)

Then I used Pyarmor to encrypt the packaging. The command is:
`pyarmor gen --pack Twitch_MainWindow.spec -r Twitch_MainWindow.py Ui_mainwindow.py Ui_settings.py`

![image](https://github.com/user-attachments/assets/d0e74198-b2c9-4963-a802-e4baab7fc12d)

It seems that the global Python is used to execute Pyinstaller to analyze the global library, instead of using the created virtual environment to execute Pyinstaller to analyze the virtual environment library.

Therefore, a lot of irrelevant or related ones were added. For example, I use Pyside6. Before I uninstalled PyQt5 and PyQt6, the encryption instructions using Pyarmor spec will be added, causing the packaged file to become more than 300 MB.

I don't know if this is a BUG or something, but I encountered it

**Comment by jondy** [comment]
Please install pyarmor in your virtual environments
