### ISSUE TITLE
Is license.lic tied to buyer?

### ISSUE THREAD

**Issue by x011** [dashingsoft/pyarmor#188]
If someone opens the `licence.lic` contained on the packed binary can they relate it to the `pyarmor` buyer? Are these 2 tied in any way?
I'm sorry, but I couldn't find a better place to put this question before purchasing armory.

**Comment by jondy** [comment]
The `license.lic` in the packed binary is signed by RAS private key, it doesn't contain any buyer information.

Each buyer will receive one exclusive private capsule from pyarmor author, which use 2048 bits RSA key. The `license.lic` of the obfuscated scripts are signed by this RSA key. 

More information, refer to https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#global-capsule

**Comment by x011** [comment]
Thanks for your fast reply.
"_The license.lic of the obfuscated scripts are signed by this RSA key._"

I'm sorry, but it still not clear to me the level of anonymity of the obfuscated files.

- If requested, are you able to provide information about the owner of a `license.lic` found inside an `exe`?
- Theoretically speaking, can `licence.lic` and buyer be connected in any way?
- Do you keep copies of Private RSA Keys distributed to clients?

Thank you.

**Comment by jondy** [comment]
> Do you keep copies of Private RSA Keys distributed to buyers?

Yes. Each buyer will received a file named `pyamor-regfile-1.zip`, which includes encode Private RSA key.

> If requested, are you able to provide information about the owner of a license.lic found inside a binary?

I could find the buyer only by iterating all of the buyer's `pyarmor-regfile-1.zip` to check whether the `license.lic` could be unsigned.

What do you mean "obfuscated files and buyer are connected"?

**Comment by x011** [comment]
What do you mean "_obfuscated files and buyer are connected_"?

You actually answered it already:

"_I could find the buyer only by iterating all of the buyer's pyarmor-regfile-1.zip to check whether the license.lic could be unsigned._"

Thank you very much.

**Comment by x011** [comment]
Would you accept btc or eth as payment?
PS: you should definitively create a sales contact form https://pyarmor.dashingsoft.com/ because github is not the place for this type of questions.

**Comment by jondy** [comment]
It seems Share*it doesn't support btc and eth payment.

There is a contact email "jondy.zhao@gmail.com" in the website, it may not be remarkable.  Thanks for your advice.
