### ISSUE TITLE
python 3.12.4  ipython 8.26.0 pandas 2.2.2 、Pyarmor 8.5.10 (trial) 情况下有些pandas 的异常导致ipython进程crash 崩溃掉

### ISSUE THREAD

**Issue by wrss01** [dashingsoft/pyarmor#1880]
如下代码：
```
def test_1():
    raise Exception('test')

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy import text
import pandas as pd

def test_2():
  engine = create_engine('mysql+pymysql://mguser:1111@127.0.0.1:63333/bi?charset=utf8')
  df = pd.read_sql_query(text('SELECT * FROM iris'), engine)
  print(df)

def test_3():
    df = pd.read_csv('test.csv')
    print(df)

def test_4():
  engine = create_engine('mysql+pymysql://mguser:1111@127.0.0.1:63333/bi?charset=utf8')
  with engine.connect() as conn:
      df = pd.read_sql_query(text('SELECT * FROM iris'), conn)
      print(df)


```

加密后在ipthon 里面调用执行，有些pandas 的异常导致ipython进程crash 崩溃掉，如下面代码：

```
os.chdir('/home/dist')
from test import test_1,test_2,test_3,test_4
try:
  test_1()
except Exception as e:
  print("Error : "+str(e))

try:
  test_3()
except Exception as e:
  print("Error : "+str(e))

try:
  test_4()
except Exception as e:
  print("Error : "+str(e))

try:
  test_2()
except Exception as e:
  print("Error : "+str(e))
test_1()
test_3()
test_4()
test_2()
```
test_2() 执行ipython 进程crash 崩溃掉（Segmentation fault (core dumped)），如下图：

![image](https://github.com/user-attachments/assets/0e96cd15-6e81-45f4-bd2c-37c8b1d0dbcf)

**Comment by jondy** [comment]
Pyarmor 组不支持对第三方库的问题支持，请参阅
https://pyarmor.readthedocs.io/zh/latest/how-to/third-party.html
https://pyarmor.readthedocs.io/zh/latest/topic/obfuscated-script.html#the-differences-of-obfuscated-scripts

**Comment by wrss01** [comment]
不加密的情况的是可以正常执行的，加密的情况就会崩溃、
















在 2024-07-26 12:07:07，"Jondy" ***@***.***> 写道：

Pyarmor 组不支持对第三方库的问题支持，请参阅
https://pyarmor.readthedocs.io/zh/latest/how-to/third-party.html
https://pyarmor.readthedocs.io/zh/latest/topic/obfuscated-script.html#the-differences-of-obfuscated-scripts
