### ISSUE TITLE
Bind Data don't encrypt string data

### ISSUE THREAD

**Issue by luigirovani** [dashingsoft/pyarmor#1881]
$ pyarmor gen --bind-data '34893' --enable-themida gen.py
When I open dist\pyarmor_runtime_000000\pyarmor_runtime.pyd in notepad

![image](https://github.com/user-attachments/assets/355e9e36-78aa-4d7b-a0a7-8dc73628bedf)

the data is present in the dll without any obfuscation or encryption

**Comment by jondy** [comment]
You can encode the bind data by yourself, and decode it in the script.

How to use bind data is all decided by you.

Besides, pyarmor also provides an option to encrypt the bind data
```
pyarmor cfg obf_key_mode=1
```
