### ISSUE TITLE
[BUG] `RuntimeError: this license key is not for this machine (1:10332)`

### ISSUE THREAD

**Issue by printpal-io** [dashingsoft/pyarmor#1883]
I am running the command: 

pyarmor gen --mix-str --obf-code 2 --assert-call --assert-import --private --pack onedir main.py authenticate.py

I get the output:

> Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pyarmor_runtime_005695/__init__.py", line 2, in <module>
RuntimeError: this license key is not for this machine (1:10332)
[26633] Failed to execute script 'main' due to unhandled exception!

I have a valid license:

$ pyarmor -v
Pyarmor 8.5.10 (pro), 005695, TEST

License Type    : pyarmor-pro
License No.     : pyarmor-vax-005695
License To      : printpal.io
License Product : TEST

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Need verify license online when obfuscating scripts

**Comment by jondy** [comment]
> RuntimeError: this license key is not for this machine (1:10332) 

It doesn't say Pyarmor License, it's runtime key.

Please search documentation to understand what's runtime key.

**Comment by printpal-io** [comment]
@jondy I am using the example code provided here: https://pyarmor.readthedocs.io/en/latest/how-to/protection.html#

There is nothing in this section about a runtime key.

**Comment by jondy** [comment]
This error menas the obfuscated script is bind to one machine which is not current machine. It's not about Pyarmor License at all.

Please make sure there is no local configuration or global configuration to bind scripts to some machine.
