### ISSUE TITLE
[BUG] 换了台服务器，无法重新注册

### ISSUE THREAD

**Issue by hanswang73** [dashingsoft/pyarmor#1884]
买的base版本，新换了台服务器，zip文件也拷贝过去了，就报错 out of license；
用 pyarmor reg pyarmor-regfile-xxxx.zip重新注册，报错：
ERROR request license token failed (101): Success
ERROR somthing is wrong

**Comment by jondy** [comment]
请参考这里注册失败的解决方案
https://pyarmor.readthedocs.io/zh/latest/reference/solutions.html
