### ISSUE TITLE
How to create encrypted exe file, when there are files and folders

### ISSUE THREAD

**Issue by nqthaivl** [dashingsoft/pyarmor#1888]
My application has many files and image folders attached. I currently do not know the command to create an encrypted file with files and folders as shown in the picture. Please help me.
![2024-07-31_205556](https://github.com/user-attachments/assets/4854c0a2-f075-4557-aa91-11c3cd22f9bc)

**Comment by jondy** [comment]
Please search PyInstaller and learn how to use it
