### ISSUE TITLE
Two different licenses same program

### ISSUE THREAD

**Issue by Rani-1234** [dashingsoft/pyarmor#189]
Hi,
We have purchased pyarmor license.

Our setting includes main script and SDK package.
The main is by company A , the SDK is by company B, so we need to separate licenses 
to run on the same program ( main script)
1.Running main script with license and SDK without license works.
2.Running main script without license and SDK with License works.
3.Running them both with the two licenses raise an error.

Please guide me how to setup it correctly.

**Comment by jondy** [comment]
Obfuscate SDK with extra option `--enable-suffix`, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-package-no-conflict-with-others
