### ISSUE TITLE
 [BUG] 'Error python3.11 not supported now ' 

### ISSUE THREAD

**Issue by rajaganapathyP** [dashingsoft/pyarmor#1890]
I have license for pyarmor  its working with python 3.10 V  and not able to use it in python3.11  
pyarmor version : 8.5.11

error message on terminal

 ubuntu@ip-10-101-12-180:~/Dqlabs-Server-2.0/src$ /home/ubuntu/.local/bin/pyarmor obfuscate --recursive --platform linux.x86_64
Python 3.11+ is not supported now</p>

**Comment by jondy** [comment]
Please check Pyarmor 8.0 documentation and use Pyarmor 8.0 command.

`pyarmor obfuscate` is Pyarmor 7.x command.
