### ISSUE TITLE
RuntimeError: unauthorized use of script (1:1080)[BUG] `Error message`

### ISSUE THREAD

**Issue by pradeep5561** [dashingsoft/pyarmor#1895]
Hi Team,

      I am able to run my python script directly using workflow job or note book. But I could not able to run through workflow jobs after it converted into wheel file. I am facing this issue 'unauthorized use of script (1:1080)'. Can you please help on this issue. How to resolve this issue.

**Comment by jondy** [comment]
I have no idea only by these information. 

Anyway, try to disable this option
```
pyarmor cfg clear_module_co=0
```
