### ISSUE TITLE
pyarmor加密工程问题

### ISSUE THREAD

**Issue by cnsunfocus** [dashingsoft/pyarmor#19]
您好. 
按照您的提示删除了一些无法编译的文件后, 执行build成功.
构建项目脚本如下:
pyarmor init --src=/root/server_automation --entry=run.py projects/server

但运行程序时报如下错误
![image](https://user-images.githubusercontent.com/3301715/39029677-a7b8bcac-448f-11e8-8c63-b5403beb39d1.png)

**Comment by jondy** [comment]
拷贝 dist 目录下面的所有文件到目录 server_automation
```
cd dist
cp *.key *.lic *.py server_automation/
```

然后在这个子目录下面运行
···
cd server_automation
python run.py
···

**Comment by jondy** [comment]
1. 加密密钥是保存在 .pyarmor_capsule.zip 里面的，这个文件会在创建工程的时候自动生成，保存在工程路径下面，试用版这个里面包含的密钥是一个固定的值，所有的试用版用的都是同一个。购买之后这个文件里面的密钥是随机生成的，每创建一个工程，都会创建一个随机的密钥
   
2. 这个产品在2008年就开始发布了，现在维护和升级都在 github 上面，有问题直接在这里提 issues
