### ISSUE TITLE
error on Pack&Obfuscate environment module folder on Django project

### ISSUE THREAD

**Issue by weiztech** [dashingsoft/pyarmor#190]
I got error using Pack&Obfuscate using command (`Paid version`)

`pyarmor pack -x " --recursive " manage.py`
`pyarmor obfuscate -r manage.py`

both command error on this line:
```
INFO     	env/lib/python2.7/site-packages/PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py -> dist/obf/env/lib/python2.7/site-packages/PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py
ERROR    invalid syntax (<frozen env.lib.python2.7.site-packages.PyInstaller.hooks.hook-PySide2.QtWebEngineWidgets>, line 33)
```

**Comment by jondy** [comment]
I think `pack` is not a good idea, please obfuscate with option `--exclude env`
```
 pyarmor obfuscate -r --exclude env manage.py
```
Refer to this real example for Django application
https://pyarmor.readthedocs.io/en/latest/examples.html#running-obfuscated-django-site-with-apache-and-mod-wsgi
