### ISSUE TITLE
[BUG] binding executable with -b flag and MAC-address often raises license error

### ISSUE THREAD

**Issue by RobertAzovski** [dashingsoft/pyarmor#1902]
Hello. Lately I often encounter such a problem that binding by MAC address causes an error when starting the program. 

`pyarmor gen -b 88:AE:DD:00:A3:F3 --pack onefile example.py`

This happened to several people i build program for, and it seems that I did everything very carefully, without making mistakes. And I had to abandon this method, although it was very convenient before, I encounter this from the version of Pyarmor 8.5.10

Could you pay attention to this, maybe this is really some kind of bug?

**Comment by jondy** [comment]
No idea only about these information.

Try no packing, only obfuscate the script with `-b`. And enable debug option to check output log
