### ISSUE TITLE
[BUG] `out of license only on python 3.11`

### ISSUE THREAD

**Issue by beliboba** [dashingsoft/pyarmor#1903]
When obfuscating for python 3.9, 3.10 and 3.11 first two get obfuscated perfectly, but python 3.11 says `out of license`

**Comment by jondy** [comment]
It's not bug. When pyarmor command says `out of license`, it's out of license.

**Comment by beliboba** [comment]
then why doesnt it happen on other versions with exact same files?

**Comment by beliboba** [comment]
Problem still present

**Comment by l4rm4nd** [comment]
I am seeing the same issue.

Pyarmor works flawlessly for Python 3.10 and 3.12. 

However, for Python 3.11 it just fails and returns `out of license`.

![image](https://github.com/user-attachments/assets/115ab45a-9f65-40dc-9cbb-5bfddd11b265)

**Comment by beliboba** [comment]
> It's not bug. When pyarmor command says `out of license`, it's out of license.

Brother, no one doubts that, but if it is really out of license why does it only happen with python 3.11?

**Comment by beliboba** [comment]
> Try to make this script smaller, or split it into 2 modules.

Not gonna believe me, i in fact did that!!!! 500 lines split into two files are not gonna be less than 500 lines for compilator💥💥💥💥💥💥
