### ISSUE TITLE
[BUG] `Error message` [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond"

### ISSUE THREAD

**Issue by Mewks** [dashingsoft/pyarmor#1904]
Hi

Ive tried to use some other resources and some have said that I can use offline activation but that only applies to the group license, ive purchased the pro license.

I've tried to use the command line as well as downloading the GUI and trying that but it seems to me that the API is down?

```
INFO     Python 3.11.9
INFO     Pyarmor 8.5.11 (trial), 000000, non-profits
INFO     Platform windows.x86_64
DEBUG    native platform windows.amd64
DEBUG    home path: C:\Users\[REDACTED]\.pyarmor
INFO     prepare "pyarmor-regcode-[redacted].txt"
DEBUG    url: https://api.dashingsoft.com/product/key/enter/[REDACTED]/?&prepare=1
INFO     query key file from server
DEBUG    direct request failed "[WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond"
DEBUG    unknown error, please check pyarmor.error.log
ERROR    <urlopen error timed out>
INFO     generate bug file "pyarmor.report.bug"
ERROR    something is wrong
```

I have tried to increase the timeout, but still getting the same error. any ideas?

Thanks

**Comment by jondy** [comment]
Please first take this check list
http://pyarmor.readthedocs.io/en/latest/reference/solutions.html

**Comment by Mewks** [comment]
![image](https://github.com/user-attachments/assets/def7821b-2c31-4ee0-b528-a6b3345b4b0f)

I have tried many of the suggestions at https://pyarmor.readthedocs.io/en/latest/reference/solutions.html

**Comment by jondy** [comment]
The license server is online, and works fine.

It should be international network issue, it's out of my control.

By the way, try to use this proxy by adding this line to `/etc/hosts`
```
pyarmor.dashingsoft.com 8.218.217.13
```

**Comment by Mewks** [comment]
Thank you that has worked. Please close this. <3
