### ISSUE TITLE
Understanding basic pyarmor working

### ISSUE THREAD

**Issue by luser350** [dashingsoft/pyarmor#1909]
Hi, I have some questions regarding pyarmor working (for my understanding). 

Q1. In -RFT mode the pyarmor renaming functions and other things, In -BCC  mode it converts possible functions to C. So what is done in basic mode? 

Q2. As stated in [FAQs](https://pyarmor.readthedocs.io/en/stable/questions.html#misc) pyarmor has encryption capabilities [(RSA 1024 trial and 2048 purchased)](https://pyarmor.readthedocs.io/en/v5.9.6/understand-obfuscated-scripts.html). So is the code encrypted every time after obfuscation? 

Q3. If the above is yes then pyarmor_runtime.so files contain a decryption key?

Q4. According to my understanding, pyarmor obfuscation has the following workflow, Correct me if I am wrong:
    
Basic: a.py -> to bytecode -> encryption -> a.py 
In-Runtime: pyarmor_runtime.so -> decrypts -> bytecode -> python interpreter

I am asking these questions after a detailed study of the documentation. I purchased  the PRO license recently, let me know if you want me to ask these questions via email

**Comment by jondy** [comment]
Do not aske questions here, it's intended to report bug here.

I have documented what I can say about the technical details. If not documented, it can't be opened.
