### ISSUE TITLE
pyarmor with celery in django project

### ISSUE THREAD

**Issue by weiztech** [dashingsoft/pyarmor#191]
i tried run celery command on my `obfuscate` django project
`celery -A myproject worker -l info`

and got error 
`NameError: name '__pyarmor__' is not defined`

any suggestion on case like this ?

**Comment by jondy** [comment]
When starts a fresh python interpreter process by multiprocssing.Process, os.exec, subprocess.Popen etc., make sure the bootstrap code are called in new process before running any obfuscated script.  

If there is `proj/proj/celery.py` module that defines the Celery instance, try to obfuscate it as an entry script
```
pyarmor obfuscate --no-runtime -O dist/proj/proj --exact proj/proj/celery
```

**Comment by weiztech** [comment]
on `celery.py` file, now have
```
from pytransform import pyarmor_runtime
pyarmor_runtime()
```

but when i called command above, still same

**Comment by weiztech** [comment]
i managed to make it work by `exact proj/proj/__init__.py`

thanks
