### ISSUE TITLE
undefined symbol: _PyRuntime

### ISSUE THREAD

**Issue by xuyingliang** [dashingsoft/pyarmor#1917]
使用pyarmor8.4.3混淆python代码后，在windows和centos7.9上运行正常，在统信操作系统上运行出错，详细情况如下：

系统版本：
统信UOS 1060服务器A版
Linux ampzking 4.19.0-91.82.152.uelc20.x86_64 #1 SMP Fri May 12 22:38:01 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

python文件：1.py
user_input = input("请输入IPV4：")
print(user_input)

混淆命令：pyarmor -d gen --use-runtime f:/pyarmor_runtime .\1.py -r --enable-jit --mix-str --private -O dist

运行时报错信息：

Traceback (most recent call last):
  File "1.py", line 2, in <module>
    from pyarmor_runtime_006064 import __pyarmor__
  File "/dist/pyarmor_runtime_006064/__init__.py", line 49, in <module>
    __pyarmor__ = __pyarmor__().__pyarmor__
  File "/dist/pyarmor_runtime_006064/__init__.py", line 48, in __pyarmor__
    return __import__(name, globals(), locals(), ['__pyarmor__'], level=1)
ImportError: /dist/pyarmor_runtime_006064/linux_x86_64/pyarmor_runtime.so: undefined symbol: _PyRuntime

**Comment by jondy** [comment]
确保目标平台的 Python 版本和构建服务器是一样的

参考下面的解决方案

https://pyarmor.readthedocs.io/zh/latest/reference/solutions.html#target-device
