### ISSUE TITLE
[BUG] `ERROR    this group license is reviewing by Pyarmor team`

### ISSUE THREAD

**Issue by SimplifytradingAI** [dashingsoft/pyarmor#1919]
I am getting "ERROR    this group license is reviewing by Pyarmor team" when trying to register my pyarmor group license.
what output do I have to provide you in order to fix the problem?

**Comment by SimplifytradingAI** [comment]
To provide more context, I ran "pyarmor reg -p XXX pyarmor-regcode-xxxx.txt" replacing the x for the license number and the product name, then said "yes" when prompted, then got:

INFO     process activation file "pyarmor-regcode-xxxx.txt"
INFO     send request to server
ERROR    this group license is reviewing by Pyarmor team
ERROR    please enable debug option `-d` to run it again

Also, tried to use the "pyarmor man" but says that this feature is still developing

**Comment by jondy** [comment]
If it still not resolved, please send order no to pyarmor@163.com.

**Comment by dhanwadeakshay1** [comment]
"this group license is reviewing by Pyarmor team" i got this issue during registration please guide
