### ISSUE TITLE
how to move html files to dist ?

### ISSUE THREAD

**Issue by weiztech** [dashingsoft/pyarmor#192]
i'm using django project and have many Html templates files.
when i successfully obfuscate. it didnt move/copy my html files to `dist`folder

is there any automatic way for moving the `html` files on obfuscate the *.py files ?

**Comment by jondy** [comment]
First copy all the files to `dist`, then obfuscate the scripts to `dist` either, so that all the `.py` files will bo overwritten by the obfuscated ones.
