### ISSUE TITLE
[BUG] `Error out of license` when building Docker image

### ISSUE THREAD

**Issue by JuniusLuo** [dashingsoft/pyarmor#1924]
bought the pyarmor basic license, but hit "out of license" error when building the docker image. 
docker file is like
```
FROM python:3.10-slim
RUN pip install xxx
COPY license.lic /usr/local/lib/python3.10/site-packages/pyarmor/license.lic
COPY license.lic /root/.pyarmor/
COPY license.lic /root/.pyarmor/pyarmor-license.lic
COPY .pyarmor_capsule.zip /root/.pyarmor_capsule.zip

RUN pyarmor gen -O . -r -i .
```

docker build -t image-name -f dockerfile .
output like:
```
 > [stage-1 16/25] RUN pyarmor gen -O . -r -i .:                                                                       
0.224 INFO     Python 3.10.14                                                                                          
0.224 INFO     Pyarmor 8.5.11 (trial), 000000, non-profits
0.224 INFO     Platform linux.aarch64
...
0.545 ERROR    out of license
```
ERROR: failed to solve: process "/bin/sh -c pyarmor gen -O . -r -i ." did not complete successfully: exit code: 2

directly run `pyarmor gen -O . -r -i .` in my macbook works. It looks pyarmor does not recognize the license inside docker?

**Comment by jondy** [comment]
You must run `pyarmor reg xxxx.zip` in docker container, it doesn't work by coping files to home path for Pyarmor new license.
