### ISSUE TITLE
[BUG] Impossible to register license

### ISSUE THREAD

**Issue by jr-k** [dashingsoft/pyarmor#1931]
Downloads pyarmor -d reg pyarmor-regcode-6380.txt -p xxxxxx
INFO     Python 3.9.10
INFO     Pyarmor 8.5.11 (trial), 000000, non-profits
INFO     Platform darwin.aarch64
DEBUG    native platform darwin.arm64
DEBUG    home path: /Users/xxxx/.pyarmor
INFO     prepare "pyarmor-regcode-6380.txt"
DEBUG    url: https://api.dashingsoft.com/product/key/enter/xxxxx/?&prepare=1
INFO     query key file from server
DEBUG    direct request failed "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)"
This license registration information will be

License Type    : pyarmor-group
License To      : xxxx
License Product : xxxxx

This license is about to be used for product "obscreen"

IMPORTANT: PRODUCT NAME CAN NOT BE CHANGED AFTER INITIAL REGISTRATION

Are you sure to continue? (yes/no) yes
INFO     process activation file "pyarmor-regcode-6380.txt"
DEBUG    url: https://api.dashingsoft.com/product/key/enter/xxxxxx/?&product=b2JzY3JlZW4=
INFO     send request to server
DEBUG    direct request failed "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)"
DEBUG    unknown error, please check pyarmor.error.log
ERROR    HTTP Error 400: Bad Request
INFO     generate bug file "pyarmor.report.bug"
ERROR    something is wrong
*=============================================================*
*  Please check console log to find out what's wrong          *
*                                                             *
*  If still not solved, please find solutions by              *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*=============================================================*

**Comment by jondy** [comment]
Try it now.

If it's still not work, find solution here
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html

**Comment by aditya-grover** [comment]
I just purchased a group license and am facing the same issue. Attaching the log.

> pyarmor -d reg -p xxxx pyarmor-regcode-6394.txt
INFO     Python 3.11.6
INFO     Pyarmor 8.5.12 (trial), 000000, non-profits
INFO     Platform darwin.aarch64
DEBUG    native platform darwin.arm64
DEBUG    home path: /Users/xxxxx/.pyarmor
INFO     prepare "pyarmor-regcode-6394.txt"
DEBUG    url: https://api.dashingsoft.com/product/key/enter/ldcwAbb5BDLsyRqgAlPPaCBrieo7qLbIN8pDJuQrZByiMR13o2NqX4gD0SzWrrXS8-cR5GKRkJY_dub-DVdOzI5RQtx3LaaZYWwemPt5RFty92WvleJShRJVApIdDlAN8PLoDJXjeG_XQX3uPyUg2t5awd-BsV5FQdODjja6IcJP0J5YGJuyEM6B_AWg9c4V/?&prepare=1
INFO     query key file from server
DEBUG    direct request failed "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)"
This license registration information will be

License Type    : pyarmor-group
License To      : xxxx
License Product : xxxx

This license is about to be used for product "xxxx"

IMPORTANT: PRODUCT NAME CAN NOT BE CHANGED AFTER INITIAL REGISTRATION

Are you sure to continue? (yes/no) yes
INFO     process activation file "pyarmor-regcode-xxxx.txt"
DEBUG    url: https://api.dashingsoft.com/product/key/enter/ldcwAbb5BDLsyRqgAlPPaCBrieo7qLbIN8pDJuQrZByiMR13o2NqX4gD0SzWrrXS8-cR5GKRkJY_dub-DVdOzI5RQtx3LaaZYWwemPt5RFty92WvleJShRJVApIdDlAN8PLoDJXjeG_XQX3uPyUg2t5awd-BsV5FQdODjja6IcJP0J5YGJuyEM6B_AWg9c4V/?&product=aW5jZXB0aW9u
INFO     send request to server
DEBUG    direct request failed "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)"
DEBUG    unknown error, please check pyarmor.error.log
ERROR    HTTP Error 400: Bad Request
INFO     generate bug file "pyarmor.report.bug"
ERROR    something is wrong
*=============================================================*
*  Please check console log to find out what's wrong          *
*                                                             *
*  If still not solved, please find solutions by              *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*=============================================================*

**Comment by jondy** [comment]
Please refer this check list first
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#registration-failed
