### ISSUE TITLE
[BUG] Wrong License

### ISSUE THREAD

**Issue by jr-k** [dashingsoft/pyarmor#1932]
Hi @jondy !

I made a mistake with the license; I bought a Group license (6380). To prove my good faith, I’ve just purchased a Pro license (5976). My refund request was declined, but I wanted to ask for a gesture of goodwill as I won’t need the Group license at all. I need to integrate PyArmor into my CI/CD. 

I also have a question about https://pyarmor.readthedocs.io/en/latest/how-to/ci.html. Should I push "pyarmor-regfile-5068.zip" into repository ? How github action runner can register itself without having zip file in repository ? Can I `pyarmor reg /path/to/pyarmor-regfile-5068.zip` multiple times into github actions without exceeding my registration limits ?

Thank you in advance !

**Comment by jr-k** [comment]
@jondy Yes but how I can try BCC and RFT without activating it ? It doesn't work for my project...

**Comment by jondy** [comment]
Please check
https://pyarmor.readthedocs.io/en/latest/topic/rftmode.html
https://pyarmor.readthedocs.io/en/latest/topic/bccmode.html

If there is any issue, please first check
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html

If it still not solved, report it in Github
