### ISSUE TITLE
[BUG] python 不同版本的python 解释器 加密出问题

### ISSUE THREAD

**Issue by hayingbs** [dashingsoft/pyarmor#1933]
window 64 位
我想在一个系统里编译  64和32位的项目

下载 python 解释器64位的  编译没问题

 下载 python 解释器32位的  编译报错：
RuntimeError: link bcc code failed

添加[windows.x42.bcc]cflags =  -DENABLE_BCC_MEMSET  或[windows.x86.bcc]cflags =  -DENABLE_BCC_MEMSET
也报错：
ERROR    Command '['clang.exe', '-DENABLE_BCC_MEMSET', '-o', '.pyarmor\\bcc\\configs.Initial_config.c.o', '.pyarmor\\bcc\\configs.Initial_config.c']' returned non-zero exit status 1.
ERROR    something is wrong

**Comment by jondy** [comment]
请使用 += 配置，而不是直接使用 =

```
$ pyarmor cfg windows.x86.bcc:cflags

Section: windows.x86.bcc

Current settings
  cflags = --target=i686-elf-linux -O3 -Wno-unsequenced -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-stack-protector -fPIC -mno-sse -std=c99 -c -DENABLE_BCC_MEMSET

Global settings

Local settings
```

最后的 cflags 应该是上面显示，请参考文档命令手册 `pyarmor cfg` 的用法，并且确保选项被正确设置
