### ISSUE TITLE
[BUG] Error when running PyArmor generated files `-1073741819`

### ISSUE THREAD

**Issue by NobleUpFront** [dashingsoft/pyarmor#1934]
I am having and error when trying to run the generated files from PyArmor. 
I have tried to read through the docs but can't seem to find a solution.

Files:
5 files (In total less than 300 lines)
1. main.py
2. c.py
3. fm.py
4. fp.py
5. mu.py

Libraries used: (json, os, time, logging, threading, PollingObserver, FileSystemEventHandler, datetime )
OS: 64 bit Windows 11 (But using 32bit to make PyInstaller Create a 32 exe)
Python: 3.11.0b2 32-bit

Works without PyArmor both locally and packaged with PyInstaller
Fails to run with PyArmor, both with and without PyInstaller

No error messages when running the Python files or running the EXE except "-1073741819"

The command used to create the files: (1.3.9.1 Packing to One file)
`pyarmor gen --pack onefile main.py`

**Comment by jondy** [comment]
Do you following this check list?
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#target-device

Does one hello script work or not? If not, try to upgrade to latest Python 3.11.x

**Comment by NobleUpFront** [comment]
@jondy Thanks for the answer:

I tried to do the following scripts:
`print("Hello, World!")`

Then: pyarmor gen --pack onefile hi.py

Results in:  -1073741819

**Tried upgrading to 3.11.9 from 3.11.0b2 32-bit.
Which solved the issues! :)**
I can also run the full program.
