### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'sourcedefender'

### ISSUE THREAD

**Issue by ksm0517** [dashingsoft/pyarmor#1935]
Issue Description:
---
I utilized PyArmor for packaging and obfuscation with the following command:
```
pyarmor -d gen --mix-str --enable-bcc --pack onedir main.py
```
During the packaging process, a warning appeared in the logs:
```
AttributeError: module 'lib' has no attribute 'CRYPTOGRAPHY_OPENSSL_300_OR_GREATER'
```
Nevertheless, the final message in the logs indicated success:
```
The final bundle has been generated to "dist" successfully.
```
When I attempted to run the packaged main file, I encountered the following runtime error in the terminal:
```
ModuleNotFoundError: No module named 'sourcedefender'
```
</br>
I suspect that some library files, such as sourcedefender and pynvml, are missing from the generated packaging file. </br>
(Path: dist/main/_internal) </br>
Previously, when I used PyArmor, the internal directory contained a greater number of library files. </br>
This leads me to believe that some necessary library files were not included in this packing.

Questions:
---
How can I resolve this issue and ensure that the missing libraries are included during packaging?
Could a recent Ubuntu update be causing this problem? I have noticed that the OpenSSL library files were updated recently, possibly due to an Ubuntu system update.

Environment Details:
---
CPU Architecture: x86
Python Version: 3.10.14
PyArmor Version: 8.5.10

**Comment by jondy** [comment]
Please check
https://pyarmor.readthedocs.io/en/latest/topic/repack.html

And
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html
