### ISSUE TITLE
[BUG] `I am not able to use pyarmor while it is begin installed`

### ISSUE THREAD

**Issue by gabi621** [dashingsoft/pyarmor#1937]
C:\Windows\System32>python -m pyarmor gen
C:\Users\User\AppData\Local\Programs\Python\Python311\python.exe: No module named pyarmor.__main__; 'pyarmor' is a package and cannot be directly executed

**Comment by jondy** [comment]
Please check
https://pyarmor.readthedocs.io/en/latest/tutorial/installation.html
