### ISSUE TITLE
Machine ID 是如何被计算

### ISSUE THREAD

**Issue by Byxs20** [dashingsoft/pyarmor#1938]
你好，我比较好奇 Machine ID 是如何计算出来的呢？

例如：
1.在虚拟机的情况下，磁盘序列号是好像可以轻松的修改，那我如何确定绑定这台虚拟机设备就是这台虚拟机设备？
2.会不会被他人复制虚拟机然后转发给他人使用？

**Comment by jondy** [comment]
为了安全，这个算法是不公开的

Pyarmor 对于设备绑定这一部分并没有做到很完备，因为这也不是 Pyarmor 的核心功能，只是一个辅助功能，对于这一部分要求比较高的用户，可以自己使用 运行时刻补丁 进行额外检查

另外，请在讨论区提交此类问题

**Comment by NamelessUzer** [comment]
官方文档说只需要在加密脚本的设备上安装pyarmor，而不需要运行加密后的脚本的用户设备上安装pyarmor，但是用户设备上不安装pyarmor，如何获取用户的Machine ID？运行此命令python -m pyarmor.cli.hdinfo可以得到用户的设备信息，但是记用户安装python再安装pyarmor，对用户来说是不是太难了？
此外，用户得到加密并打包后的exe文件时，该exe文件能够识别是否缺少key，以及key是否正确，也就是说加密后的脚本，能够计算出设备信息，该怎样显示给用户呢？开发者只有获得了用户的设备信息，才好生成与用户设备信息绑定的key文件。

**Comment by jondy** [comment]
搜索文档，查找 get_hd_info 函数的用法
