### ISSUE TITLE
Obfuscating Package No Conflict With Others

### ISSUE THREAD

**Issue by ptrivedi2610** [dashingsoft/pyarmor#194]
Hi @jondy ,

In section 3.2 of Obfuscating Package No Conflict With Others, the document mention below statement.
"""
Suppose there are 2 packages obfuscated by different developers, could they be imported in the same Python interpreter?
If both of them are obfuscated by trial version of pyarmor, no problem, the answer is yes. But if anyone is obfuscated by registered version, the answer is no.
"""

If I have obfuscated both packages with same registered version, will it work ?

**Comment by jondy** [comment]
It should work.

**Comment by ptrivedi2610** [comment]
@jondy Thanks
