### ISSUE TITLE
[BUG] RuntimeError: request license token failed (101): Success

### ISSUE THREAD

**Issue by PidgeyBE** [dashingsoft/pyarmor#1942]
Pyarmor 8.5.11

I'm trying to run `pyarmor -d reg pyarmor-regfile-xxx.zip `, but it doesnt work. It does work locally, but not in our CICD.
I've checked https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#registration-failed, but it's the first run of the day in our CICD, so I dont think any of the items apply.
Also
```
curl -s https://pyarmor.dashingsoft.com/api/auth2/
NO:missing parameter
```

On my local dev machine, I can register...
```
License No.     : pyarmor-vax-005286
```

**Comment by jondy** [comment]
As check list in the https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#registration-failed

please test it by python script directly.

**Comment by PidgeyBE** [comment]
After waiting a few more hours, it worked...
It also worked for months before, so I dont think a firewall was the problem...
