### ISSUE TITLE
[BUG] Pymem acts differently with pyArmor

### ISSUE THREAD

**Issue by Apprisco** [dashingsoft/pyarmor#1943]
PyArmor latest version used. Whenever pymem library is used with pyArmor, it doesn't seem to perform as original.
Something's different, leading it to read slower or not at all at times.
Tried adding  --hidden-import=win32ctypes to the pyinstaller config to no avail.

**Comment by jondy** [comment]
Please refer to
https://pyarmor.readthedocs.io/en/latest/how-to/third-party.html

Generally Pyarmor team doesn't research third-party libraries.
