### ISSUE TITLE
[BUG] RFT mode does not update class attribute usage in subclasses

### ISSUE THREAD

**Issue by porthole-ascend-cinnamon** [dashingsoft/pyarmor#1944]
As the title says, in RFT mode attributes in the base class are renamed, but their usage in the subclass aren't. 

Environment:
```
INFO     Python 3.12.6
INFO     Pyarmor 8.5.11 (pro)
INFO     Platform linux.x86_64
```

Steps to reproduce
1. Create a file main.py
```
class A:
    def __init__(self, x):
        self.x = x

class B(A):
    def get_x(self):
        return self.x

if __name__ == '__main__':
    b = B(1)
    print(b.get_x())
```

2. ```pyarmor cfg enable_rft=1 trace_rft=1```
3. ```pyarmor gen main.py```
4. ```python dist/main.py ```

Result:
```
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen main>", line 13, in <module>
  File "<frozen main>", line 8, in pyarmor__4
AttributeError: 'pyarmor__3' object has no attribute 'x'
```

RFT trace
```
pyarmor__6, = __assert_armored__(b'\x84d\xd4p\x94\xe1XhU\x07\xd1\xc5)#\x19\x9eS\xcd?\x90~[R\xe74\x9aj')

class pyarmor__1:

    def __init__(self, x):
        self.pyarmor__2 = x

class pyarmor__3(pyarmor__1):

    def pyarmor__4(self):
        return self.x
if __name__ == '__main__':
    pyarmor__5 = pyarmor__3(1)
    pyarmor__6(pyarmor__5.pyarmor__4())
```

Expected result:
`return self.x` is changed to `return self.pyarmor__2`

Additional notes:
Duplicating `__init__` in `class B` fixes the issue but isn't a great solution.
Same issue appears when calling methods defined in parent class, and adding them to exclude table kinda defeats the purpose.
It would be great if subclass support could be added.

**Comment by jondy** [comment]
Got it, thanks.

It will be fixed in next release (about in this month)

**Comment by jondy** [comment]
Fixed in v9.0.0, before upgrade to Pyarmor 9, please check upgrade notes #1958

**Comment by porthole-ascend-cinnamon** [comment]
I am using pyarmor pro in CI/CD.....Can this bugfix be backported to 8.x.x release?

**Comment by porthole-ascend-cinnamon** [comment]
Additional question / request about new CI/CD model. I have a pretty low volume usage, but CI/CD is convenient and provides access to different platforms, compared to building locally. Could you please consider instead of completely removing CI unless paying yearly fee (pretty large), limiting it to 100 runs per month (as opposed to per day currently) so it won't bother your server a lot?

**Comment by jondy** [comment]
Good advice, 100 runs per month should be no problem. In Pyarmor 9, Pro license could run in 100 different machines every 30 days. The machine token is free after 30 days.

**Comment by Apprisco** [comment]
This issue has returned in the latest pyarmor.

If you pass a class as a parameter, none of its member functions are being changed, leading to 

![Image](https://github.com/user-attachments/assets/5a03704f-b7f4-4c46-9a61-f7bd1be018fe)

**Comment by jondy** [comment]
Please try to use Pyarmor 9.1 RFT features
https://eke.dashingsoft.com/pyarmor/docs

**Comment by jondy** [comment]
I just test this example scripts with v9.1.3, it works as expected
```
pyarmor gen --enable-bcc bugs/t1944.py
```
