### ISSUE TITLE
"d.a.r.w.i.n...a.a.r.c.h.6.4" is still not supported by Pyarmor

### ISSUE THREAD

**Issue by hb-2017** [dashingsoft/pyarmor#1946]
(.venv) mark@Mark dnfm-yolo-tutorial % pyarmor gen .                         
INFO     Python 3.8.20
INFO     Pyarmor 8.5.12 (trial), 000000, non-profits
INFO     Platform darwin.aarch64
INFO     search inputs ...
INFO     find package at .
INFO     find 1 top resources
ERROR    "d.a.r.w.i.n...a.a.r.c.h.6.4" is still not supported by Pyarmor
ERROR    please enable debug option `-d` to run it again

**Comment by hb-2017** [comment]
How should I solve this problem? I have reviewed the document, but did not find any similar issues. I am a Mac computer with M3 chip

**Comment by jondy** [comment]
Sorry, darwin.arm64 only support Python 3.9+.

I'll documented it in the build environments.
