### ISSUE TITLE
 "l.i.n.u.x...a.a.r.c.h.6.4" is still not supported by Pyarmor

### ISSUE THREAD

**Issue by jiuyunxi** [dashingsoft/pyarmor#1947]
INFO     Python 3.7.5
INFO     Pyarmor 8.5.12 (trial), 000000, non-profits
INFO     Platform linux.aarch64
INFO     generating device file ".pyarmor/group/pyarmor-group-device.1"
ERROR    "l.i.n.u.x...a.a.r.c.h.6.4" is still not supported by Pyarmor
ERROR    please enable debug option `-d` to run it again

**Comment by jiuyunxi** [comment]
How should I solve this problem? I have reviewed the document, but did not find any similar issues.

**Comment by jiuyunxi** [comment]
pyarmor.report.bug
### Traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyarmor/cli/core/__init__.py", line 67, in _import_pytransform3
    fromlist=('__pyarmor__',), level=1
ModuleNotFoundError: No module named 'pyarmor.cli.core.pytransform3'

**Comment by jondy** [comment]
darwin.arm64 only supports Python 3.9+, not support Python 3.8

**Comment by jondy** [comment]
Sorry, I mada a mistake. linux.aarch64 is supported.

Please make sure you have installed package `pyarmor.cli.core` or `pyarmor.cli.core.linux` if this device is offline.

Refer to
https://pyarmor.readthedocs.io/en/latest/tutorial/installation.html
