### ISSUE TITLE
[BUG] `pyarmor.cli.hdinfo in Docker get different messages`

### ISSUE THREAD

**Issue by blacke97** [dashingsoft/pyarmor#1949]
Pyarmor Version : 8.5.12
pyarmor.cli.core Version : 6.5.3
Docker Base Image : Python:3.7.12
Cmd : python -m pyarmor.cli.hdinfo

When I use docker and input the Cmd sometimes, I got different Machine ID everytime. But I want get the same.

Please help.

**Comment by jondy** [comment]
It's the designed behaviour, machine id is changed in docker even it's same image.

**Comment by jondy** [comment]
Each run will generate new machine id in docker container.
