### ISSUE TITLE
pyarmor registration in WSL

### ISSUE THREAD

**Issue by jiuyunxi** [dashingsoft/pyarmor#1956]
I have registered a Pyarmor group license on Windows, but after installing Pyarmor on WSL, it's only a trial version. Do I need to register another license on WSL?

**Comment by jondy** [comment]
Yes. WSL is taken as new device from Pyarmor view.

**Comment by jiuyunxi** [comment]
The issue has been resolved,　please refer to the following link.  https://github.com/dashingsoft/pyarmor/issues/1544

**Comment by jiuyunxi** [comment]
I take WSL as docker container, and connect to docker host in Windows
