### ISSUE TITLE
[Bug] CalledProcessError: Command '['//count-tiles_env/bin/python3', '-m', 'PyInstaller', '--clean', '--workpath', '.pyarmor/pack/build', 'count-tiles.spec']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by jcantero-equip** [dashingsoft/pyarmor#1957]
### Full command options and console output
//count-tiles_env/bin/pyarmor -d gen --pack onefile count-tiles.py utils_v1.py

2024-10-18 10:26:21,973 Python 3.10.12
2024-10-18 10:26:21,973 Pyarmor 8.5.12 (trial), 000000, non-profits
2024-10-18 10:26:21,974 Platform linux.x86_64
2024-10-18 10:26:21,974 native platform linux.x86_64
2024-10-18 10:26:21,974 home path: /root/.pyarmor
2024-10-18 10:26:21,974 implicitly save obfuscated scripts to ".pyarmor/pack/dist"
2024-10-18 10:26:21,974 command options: {'no_runtime': False, 'inputs': ['count-tiles.py', 'utils_v1.py'], 'output': '.pyarmor/pack/dist'}
2024-10-18 10:26:21,974 install plugin: CodesignPlugin
2024-10-18 10:26:21,974 install plugin: DarwinUniversalPlugin
2024-10-18 10:26:21,984 search inputs ...
2024-10-18 10:26:21,984 find script count-tiles.py
2024-10-18 10:26:21,984 find script utils_v1.py
2024-10-18 10:26:21,984 find 2 top resources
2024-10-18 10:26:21,984 //count-tiles_env/bin/python3 -m PyInstaller.utils.cliutils.makespec -i Equip_electronics.ico count-tiles.py
2024-10-18 10:26:21,984 call PyInstaller to generate specfile
2024-10-18 10:26:22,025 //count-tiles_env/bin/python3 -m PyInstaller --clean --workpath .pyarmor/pack/build count-tiles.spec
2024-10-18 10:26:22,026 call PyInstaller to analysis, it may take several minutes ...
2024-10-18 10:26:23,701 unknown error, please check pyarmor.error.log
2024-10-18 10:26:23,702 Command '['//count-tiles_env/bin/python3', '-m', 'PyInstaller', '--clean', '--workpath', '.pyarmor/pack/build', 'count-tiles.spec']' returned non-zero exit status 1.
2024-10-18 10:26:23,702 generate bug file "pyarmor.report.bug"

### Traceback
Traceback (most recent call last):
  File "//count-tiles_env/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 754, in main
    main_entry(sys.argv[1:])
  File "//count-tiles_env/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 742, in main_entry
    return args.func(ctx, args)
  File "//count-tiles_env/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 240, in cmd_gen
    builder.process(options, packer=packer)
  File "//count-tiles_env/lib/python3.10/site-packages/pyarmor/cli/generate.py", line 175, in process
    auto_resources = packer.analysis()
  File "//count-tiles_env/lib/python3.10/site-packages/pyarmor/cli/repack.py", line 174, in analysis
    check_call(cmdlist, stdout=DEVNULL, stderr=DEVNULL)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['//count-tiles_env/bin/python3', '-m', 'PyInstaller', '--clean', '--workpath', '.pyarmor/pack/build', 'count-tiles.spec']' returned non-zero exit status 1.

I'm using the same setup with another project with different code and it works perfectly fine. However, when in the same environment I try to run pyarmor for this scripts, the packing fails.

**Comment by jcantero-equip** [comment]
### Update

I have tried to run the command, and I see the problem is specifically with the count-tiles.py file. I share the code:

#!/usr/bin/env python3
## IMPORTS ##

from utils_v1 import *
from camera_utils import *

## PATHS ##
#results_path = "../results"
model = YOLO("best.pt")
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
torch.backends.cudnn.benchmark = True

print(model.device)
# 1. We take the video and cut it in frame at 2 fps
stream = open("config.yaml", "r")
config = yaml.load(stream, Loader=yaml.FullLoader)

frame_rate = 60 # Desired frame rate (1 frame every 0.083 seconds)
frame_count = 0
lot_size = config["configuracion"]["lot_size"]
lote_flag = True
sum_fps = 0
min_fps = 1000

## INSERT PARAMETERS ##
host=config["configuracion"]["BDD"]["host"]
user=config["configuracion"]["BDD"]["user"]
password=config["configuracion"]["BDD"]["password"]
database=config["configuracion"]["BDD"]["database"]
id_dispositivo = config["configuracion"]["BDD"]["id_dispositivo"]
port=config["configuracion"]["BDD"]["port"]

# Conexión a la base de datos MySQL
conn = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
    port=port
)
try:
    cursor = conn.cursor()
except Exception as e:
    print(e)

## FLIR CAMERA SETTINGS
#We select Stream Mode
CHOSEN_STREAMMODE = StreamMode.STREAM_MODE_TELEDYNE_GIGE_VISION

# Retrieve singleton reference to system object
system = PySpin.System.GetInstance()

# Retrieve list of cameras from the system
cam_list = system.GetCameras()

cam = cam_list[0]  # We instantiate a cameraBase onject from PySpin from CameraList

num_cameras = cam_list.GetSize()

print('Number of cameras detected: %d' % num_cameras)

# Finish if there are no cameras
if num_cameras == 0:
    # Clear camera list before releasing system
    cam_list.Clear()

    # Release system instance
    system.ReleaseInstance()

    print('Not enough cameras!')
    input('Done! Press Enter to exit...')

else:
    try:
        result = True

        # Retrieve TL device nodemap and print device information
        nodemap_tldevice = cam.GetTLDeviceNodeMap()

        # Initialize camera
        cam.Init()

        # Retrieve GenICam nodemap
        nodemap = cam.GetNodeMap()

        # Set Stream Modes
        result = set_stream_mode(cam)
    except PySpin.SpinnakerException as ex:
        print('Error: %s' % ex)
        result = False

    try:
        result = True

        # Set acquisition mode to continuous
        #
        #  *** NOTES ***
        #  Because the example acquires and saves 10 images, setting acquisition
        #  mode to continuous lets the example finish. If set to single frame
        #  or multiframe (at a lower number of images), the example would just
        #  hang. This would happen because the example has been written to
        #  acquire 10 images while the camera would have been programmed to
        #  retrieve less than that.
        #
        #  Setting the value of an enumeration node is slightly more complicated
        #  than other node types. Two nodes must be retrieved: first, the
        #  enumeration node is retrieved from the nodemap; and second, the entry
        #  node is retrieved from the enumeration node. The integer value of the
        #  entry node is then set as the new value of the enumeration node.
        #
        #  Notice that both the enumeration and the entry nodes are checked for
        #  availability and readability/writability. Enumeration nodes are
        #  generally readable and writable whereas their entry nodes are only
        #  ever readable.
        #
        #  Retrieve enumeration node from nodemap

        # In order to access the node entries, they have to be casted to a pointer type (CEnumerationPtr here)
        node_acquisition_mode = PySpin.CEnumerationPtr(nodemap.GetNode('AcquisitionMode'))
        if not PySpin.IsReadable(node_acquisition_mode) or not PySpin.IsWritable(node_acquisition_mode):
            print('Unable to set acquisition mode to continuous (enum retrieval). Aborting...')

        # Retrieve entry node from enumeration node
        node_acquisition_mode_continuous = node_acquisition_mode.GetEntryByName('Continuous')
        if not PySpin.IsReadable(node_acquisition_mode_continuous):
            print('Unable to set acquisition mode to continuous (entry retrieval). Aborting...')

        # Retrieve integer value from entry node
        acquisition_mode_continuous = node_acquisition_mode_continuous.GetValue()

        # Set integer value from entry node as new value of enumeration node
        node_acquisition_mode.SetIntValue(acquisition_mode_continuous)

        print('Acquisition mode set to continuous...')

        #  Begin acquiring images
        #
        #  *** NOTES ***
        #  What happens when the camera begins acquiring images depends on the
        #  acquisition mode. Single frame captures only a single image, multi
        #  frame captures a set number of images, and continuous captures a
        #  continuous stream of images. Because the example calls for the
        #  retrieval of 10 images, continuous mode has been set.
        #
        #  *** LATER ***
        #  Image acquisition must be ended when no more images are needed.
        cam.BeginAcquisition()

        print('Acquiring images...')

        #  Retrieve device serial number for filename
        #
        #  *** NOTES ***
        #  The device serial number is retrieved in order to keep cameras from
        #  overwriting one another. Grabbing image IDs could also accomplish
        #  this.
        device_serial_number = ''
        node_device_serial_number = PySpin.CStringPtr(nodemap_tldevice.GetNode('DeviceSerialNumber'))
        if PySpin.IsReadable(node_device_serial_number):
            device_serial_number = node_device_serial_number.GetValue()
            print('Device serial number retrieved as %s...' % device_serial_number)

        # Retrieve, convert, and save images

        # Create ImageProcessor instance for post processing images
        processor = PySpin.ImageProcessor()

        # Set default image processor color processing method
        #
        # *** NOTES ***
        # By default, if no specific color processing algorithm is set, the image
        # processor will default to NEAREST_NEIGHBOR method.
        processor.SetColorProcessing(PySpin.SPINNAKER_COLOR_PROCESSING_ALGORITHM_HQ_LINEAR)

    except PySpin.SpinnakerException as ex:
        print('Error: %s' % ex)
        result = False

    # Crear una ventana con la opción de cambiar su tamaño
    cv2.namedWindow('Contador', cv2.WINDOW_NORMAL)

    # Establecer la ventana a pantalla completa
    cv2.resizeWindow('Contador', 2048, 1560)
    inference_result = []
    capture_time = time.time()
    ret, frame = acquire_images(cam, processor, nodemap, nodemap_tldevice)
    count_tile = get_count(cursor, id_dispositivo)
    prev_count_tile = count_tile
    while True:
        start_time = time.time()
        if frame_count%4 == 0:
            cv2.imshow("Contador", frame)
            cv2.waitKey(1)
            frame_count += 1
        else:
            ret, frame = acquire_images(cam, processor, nodemap, nodemap_tldevice)
            if not ret:
                print("Unable to retrieve frames from video")
            else:
                frame_count += 1
                frame = frame[300:, :]
                # Only extract frames at the desired frame rate
                #if frame_count % int(cap.get(5) / frame_rate) == 0:
                inference_result = model.predict(frame, half=True, iou=0.1, conf=0.1, device=device)
                count_tile, frame, last_detected_frame = yolo_count(inference_result, frame, frame_count, count_tile)
                # Lanzar la visualización del frame en otro hilo para no bloquear el procesamiento
                commit_thread = threading.Thread(target=commit_count,
                                                 #args=(cursor, conn, id_dispositivo, count_tile, prev_count_tile))
                commit_thread.start()
                # print(f'Frame: {frame_count}, Fps: {fps}, Count: {count_tile}')
                fps = 1 / (time.time() - start_time)

                sum_fps += fps
                if fps < min_fps and frame_count > 2:
                    min_fps = fps

                print("FPS: ", fps, "Min FPS: ", min_fps)
                # result.write(frame)
                prev_count_tile = count_tile


    print(f'Mean fps: {sum_fps/frame_count}, Min fps: {min_fps}, Num_tiles: {count_tile}')
    #  *** NOTES ***
    #  Ending acquisition appropriately helps ensure that devices clean up
    #  properly and do not need to be power-cycled to maintain integrity.
    cam.EndAcquisition()

    # Release reference to camera
    # NOTE: Unlike the C++ examples, we cannot rely on pointer objects being automatically
    # cleaned up when going out of scope.
    # The usage of del is preferred to assigning the variable to None.

    # Deinitialize camera
    cam.DeInit()
    del cam

    # Clear camera list before releasing system
    cam_list.Clear()

    # Release system instance
    system.ReleaseInstance()
    #result.release()
    cv2.destroyAllWindows()
    cursor.close()
    conn.close()

**Comment by JFuqX** [comment]
what was the actual fix to it ? :D

**Comment by jcantero-equip** [comment]
I'm sorry, it was already a long time ago and I don't remember any longer...


Jesús Cantero Ramis

EQUIP Electronics

Edificio CIES

C/ Lituania, 10 (Nave 1)

12006 Castellón de la Plana (España)



Tel.: +34 964 023 305

Móv.: +34 654 841 598

https://equipelectronics.com/

________________________________
De: John Reinecke ***@***.***>
Enviado: domingo, 15 de diciembre de 2024 1:09
Para: dashingsoft/pyarmor ***@***.***>
Cc: Jesús Ángel Cantero Ramis ***@***.***>; State change ***@***.***>
Asunto: Re: [dashingsoft/pyarmor] [Bug] CalledProcessError: Command '['//count-tiles_env/bin/python3', '-m', 'PyInstaller', '--clean', '--workpath', '.pyarmor/pack/build', 'count-tiles.spec']' returned non-zero exit status 1. (Issue #1957)


what was the actual fix to it ? :D
