### ISSUE TITLE
[Question] How to bind host machine within docker container?

### ISSUE THREAD

**Issue by hansroh** [dashingsoft/pyarmor#1959]
I want to bind host device (eth or machine ID of host) with pyarmor runtime key, but I cannot find the way.

```
pyarmor -v

Pyarmor 8.5.12

License Type    : pyarmor-basic
...
```

At my host,
```
python -m pyarmor.cli.hdinfo

Machine ID: 'm615eef28dd1e6541aeb4118a26df134d'
Default Harddisk Serial Number: Permission denied
Default Mac address: 'a0:8c:fd:db:f5:a8'
Default IPv4 address: '192.168.0.242'
Multiple Mac addresses: <a0:8c:fd:db:f2:f8,02:42:11:4a:04:b2,02:42:b3:50:86:3b,da:76:2d:6b:9c:74>
Domain: '(none)'
```

But in docker container,
```
Machine ID: 'm7848c0b361eafd9f02b34fffc706075e'
Default Harddisk Serial Number: failed to get hardware information
Default Mac address: '02:42:c0:a8:a0:03'
Default IPv4 address: '192.168.160.3'
Multiple Mac addresses: <>
Domain: '(none)'
```

I want to use use MAC (or machine ID) of host machine,
```
pyarmor gen key -e 30 -b "a0:8c:fd:db:f5:a8"
```

Is there any way to accomplish it?

**Comment by hansroh** [comment]
I figured out adding `network_mode: host` into my docker-compose.yml. But I paid for abandoning container port mapping.

Is there any other way to this?

**Comment by jondy** [comment]
Pyarmor doesn't support this directly, please write your own runtime patch for this case.

Besides, it's better to submit question in discussion areas.
