### ISSUE TITLE
Pyarmor 5.9.0 does not work on raspberry pi 3, Raspbian os

### ISSUE THREAD

**Issue by ArefAz** [dashingsoft/pyarmor#196]
Hello, 

A couple of months ago I used pyarmor to obfuscate and pack my project on raspberry and it went well; I appreciate what you do. Thank you.

However, today I wanted to do the same again; so first I updated pyarmor to 5.9.0. But I encountered an issue when using it. The error was:

`PyArmor does not work with this core library (r10), which reversion < 14`

I used this command: `pyarmor pack main.py --options "-p /usr/local/lib/python2.7/dist-packages/cv2/python-2.7 --onefile"`

I thought that it has something to do with the version. Then I reinstalled 5.6.7 and it worked fine.

os data:
cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l

**Comment by jondy** [comment]
Please make a clean uninstallation
```
pip uninstall pyarmor

rm -rf {pyarmor-folder}
rm -rf ~/.pyarmor_capsule.zip
rm -rf ~/.pyarmor
```

Refer to https://pyarmor.readthedocs.io/en/latest/installation.html#installed-commands
