### ISSUE TITLE
[BUG] Exe file not working when running: gen pyarmor --pack onefile

### ISSUE THREAD

**Issue by tvone** [dashingsoft/pyarmor#1967]
**Please remove this line and all the following lines when submit issue**

In order to solve your issue quickly, please read this page and try common solutions in the section `Asking questions in GitHub`
https://pyarmor.readthedocs.io/en/latest/questions.html

If it's really a bug, please following the guide in the section `Reporting issues`

为了快速解决你遇到的问题，请务必打开下面的链接并尝试其中关于常见问题的通用解决方案
https://pyarmor.readthedocs.io/en/latest/questions.html

如果确认是一个 Bug，建议按照上面链接中的章节 `报告问题` 的规范提交问题报告

**在提交报告时候请删除当前行以及上面的所有行**

Exe file not working when running: gen pyarmor --pack onefile build_exe.py, please help
![image](https://github.com/user-attachments/assets/93774160-8f2b-4f07-9cf0-dd187e959eb6)

if installed using pyintaller the exe file works normally

**Comment by jondy** [comment]
Please refer to
https://pyarmor.readthedocs.io/zh/latest/how-to/repack.html

Also please write clean bug description

**Comment by tvone** [comment]
> Please refer to https://pyarmor.readthedocs.io/zh/latest/how-to/repack.html
> 
> Also please write clean bug description

link not working
