### ISSUE TITLE
Very slight issue regarding characters..

### ISSUE THREAD

**Issue by mjoe67886** [dashingsoft/pyarmor#1971]
```
# def code_pre_remover(text):

#     scn = bpy.context.scene
#     # Unescape HTML entities
#     text = html.unescape(text)
    
#     # Remove <pre> and <code> tags but keep their content
#     text = re.sub(r'<\/?(pre|code)>', '', text)
    
#     # Remove all other HTML tags
#     clean_text = re.sub(r'<.*?>', '', text)
    
#     # Print the cleaned text
#     return clean_text
```

I really appreciate your software and I'm happy I bought it in order to help improve it I just wanted to let you know that it worked fine on 60,000 lines of code I threw at it except for this one function I had to rewrite this which was incredibly simple but I just thought you should know that and then if you try and run it on this function on your own system you should notice that it does get an issue..

.

**Comment by mjoe67886** [comment]
I'm actually having an issue using it um I'm trying to use it to obfuscate an INIT file that is the main file in a blender add-on... I import other other PIP libraries into that add on so I put the runtime folder that is generated when I do the opsification in that folder here's what my file looks like if you could give me any advice on this I followed all the instructions in the email to the letter and same with the get started................ blender uses python 11.7 so I installed that on my system and ran all the commands in your tutorial in the email for registration in the consolel and everything came back positive like I did it right..

```

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), "lib"))
# Pyarmor 9.0.3 (basic), 004830, basic, 2024-10-28T14:45:45.870084
from pyarmor_runtime_004830 import __pyarmor__
__pyarmor__(__name__, __file__, b'PY004830\x00\x03\x0b\x00\xa7\r\r\n\x80\x00\x01\x00\x08\x00\x00\x00\x04\x00\x00\x00@\x00\x00\x00\x15\x03\x1c\x00\x12\t\x05\x00\xa8\x19\x96\xd6\x96\x90\xdaR\x89\x0c\x92\xf5}\n\x87@\x00\x00\x00\x00\x00\x00\x00\x00\xecS\xd8\xedH\xc1\x93\x08\xcd\xf0\x1f\x9c\xa4\x957\n?)\xd7\xae~d\xfd\x9f6\xd5/w\xaeY\xf0\xcd\x85\xdby\xfbNk&i\xebU\xd0X7\xb4\xbb[\xcd\xcb\xb3\xd5N\xcb\xcc\x01S5\x0c\xf1\xe1\xdd8F\x1d\xaalU\x8a\xc1\xbe\xe9~\xc5\x12\x06\x18o\'=\t\x17(\xb69S\x02\xeb^\xa6\xd4\xba\x9e\xfa}\xf8\xb3\xcd:\x98\n\xb3\x9eT^\xdc\x04]w\xcaB08\xdene\x95\xeb\x81X\xcf\xf4\x82kE\xeb\x99z\x98\xc3]\x90]<^hv\xaf\x82\x8c\xd7\\2r:3\xd6\xc5\x99[X\x83Y\xcbH\x19[\xe6R\xcb}\x87\xd5\x19\x1c\x93\xc6\x1c\x15;\x86>\xa7\x17W\x12\xfe\xf3\x11ioS\x8c\x89\'\x0b\xa7\x92\x874\xa7Y\xb7S\x9d\xcd(z*\xa7\xd4\x17\x8f\x17\xd2\xcau\x96&@\xb9\xb8\xc6\x95\xf2\xa0\xc9\x91!\xcf\x0ey\xe2\x88\xb8\x00\x01\x88\xdd8\xf9\x04\x8e%\xe9\xfc7\x81\x1bAt\x90\xe6rU\x96\x91\xad\xa7#>^\x82`@\x06L\\#\x19\xba\x0b"\xb5B\x90\xdf\x1d"\x051\x85"\xb7\xec}+Z\x1e\x02#\xa8\xf2\xcf\x9d\xd8\x95{N\xef\x84\t\x10\xa1\xe5\x05g\x9eJ\xf2\xfe\xa0.\x87?\xa6$[\x1f\xf7\xc2\xae\xb4\'^\x14r\x13\xca\xa9\xb1\xcb\xcb9\xfc\x9b!\xd9@\xdab\xfa\xdaPG\xfc/\x1a+\xc4Z\xab=\xf7\xcci\xc9\xb2\x97\xc8\xf0X\xdc\xcf\xf6\x86)U\x86\xfb\x91_\xaf\x7f\x95\xee\x90\n\xe4\xb8]\x95\xb2 #\xff\x1c\x10\xf1\x11\xa9rY0\xf2H\xe1\xe1\x1a\x0fs\x91~4=\t\xc0M\x9da\x80\xcb\xdep\x02\x18\xa3\x92\xc3\x98(T\xe7\xf1\xeb\x10\x00\x10\xd9\x92\xc4\xcf\xce\x9a\x08\x00\x82\x8bO\xd0B;\xb6\x11\xc7\x0c^\xc0.K\x7f\xado\xed\x8e\xe2\x15\x13\x0f\x1e\xf2\xcf-\xf6\xc6\xdb(aN\xa4<aE\x9e6\xb6\xc2\x1d\x8d\xc3\xfb\x10\xe8w\x99\xd6\xf0m\x8b#\xa6\xfe6#\xe3p\xc4\x19\x15\x0c\xbaT\x15\\\xd3\xd2w\xd39GSh&\x00\xd6Wc\tX\xa9\x19Afk_\xe3\x87,\xa4t}g\xeeG\x11\xa1Yk\xe7\x1eD\x96\xe3\x08\\\xea\xe0\xc5\x85n\x9dk\x12\x06\xa3\xac\xe5\x1b\xe1\xec\x94;\xd3R\xa9e?.
```

**Comment by mjoe67886** [comment]
I was hoping that since this is a product that I purchased to get a timely response to this i'm trying to upload an update for my add on by tomorrow do you offer timely assistance on this product?. And if so is this the right avenue for that

**Comment by mjoe67886** [comment]
An addendum um I was trying other things and I tried running the script in the console and get the same error...
```

C:\Users\W\Desktop\dist>python __init__.py
Traceback (most recent call last):
  File "<frozen __main__>", line 8, in <module>
RuntimeError: unauthorized use of script (1:1102

C:\Users\W\Desktop\dist>





```

**Comment by jondy** [comment]
Thanks for purchasing Pyarmor.

But pyarmor fee doesn't include technical support.

Please check pyarmor technical policy
https://jondy.github.io/paypal/index.html#support

First following this guide to solve problem, if not, report issue with reproduced steps

Besides, you can search error message in the online documenent to find some solutions.

**Comment by mjoe67886** [comment]
Thank you very much!!.................one quick suggestion that would be
cool if you know if you guys wanted to make this a lot stronger if you
released a video maybe explaining people how to integrate their obfuscation
to gpl only environments like blender... They have an open source policy
that only allows GPL code to integrate with their functionality. I'm going
to come up with ideas on my own but for your end users that might be a good
idea..
