### ISSUE TITLE
[BUG] pyarmor 9.0.5 Int is not callable issue, Python 3.13 (not replicated in python3.11)

### ISSUE THREAD

**Issue by Apprisco** [dashingsoft/pyarmor#1984]
Tried all the stuff in https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#failed-to-run-obfuscated-scripts
![image](https://github.com/user-attachments/assets/14af410b-161b-434a-b80b-6d68f4d1b66e)

Issue replicated in python 3.12 and python 3.13 with 9.0.5.
Is stable with python 3.11.

Script compiles fine with just pyinstaller, but simply
`pyarmor gen --pack onefile main.py`
 fails.

**Comment by Apprisco** [comment]
Should add that package compiles successfully with pyinstaller. Default pyarmor setup does not.

**Comment by jondy** [comment]
So
1. only obfuscate main.py works or not?
2. pyarmor gen --pack onefile hellowrold.py works or not?

**Comment by Apprisco** [comment]
obfuscating main.py only does not work.

packing onefile helloworld where all it does is print('hello world') works

Unable to provide entire main.py as it is sensitive application, but is a tkinter gui app

**Comment by Apprisco** [comment]
Invalid my ass. Code won't run with pyarmor in 3.12 or 3.13, what's the reasoning for close?

**Comment by Apprisco** [comment]
![image](https://github.com/user-attachments/assets/3c090989-04fd-4317-a64e-7ed78fa16a9b)
issue isolated to declaring static dictionaries with string:int
