### ISSUE TITLE
pyarmor pack redundancy

### ISSUE THREAD

**Issue by ArefAz** [dashingsoft/pyarmor#199]
Hello,

`PyInstaller` provides `pyi-makespec` tool to generate `.spec` files; therefore, I think that in the second phase of `pyarmor pack` when you want to create the `spec` file to patch it afterwards you could just simply pass the `-e` arguments to the `pyi-makespec` tool and use its output instead of `pyinstaller` itself. And then run `pyinstaller -y --clean main-patched.spec`. This way packing time will get reduced a lot, especially in slow devices such as RaspberryPi which I am currently working on.

I hope I that I didn't miss anything.

Thank you, Best of luck.

**Comment by jondy** [comment]
It's almost right. But the best way to save time is to run `pyarmor pack` once with option `--debug`
```
pyarmor pack --debug main.py
```
By this way the patched `main-patched.spec` will be kept. After that just repeat the following steps:
```
pyarmor obfuscate ...
pynstaller -y --clean main-patched.spec
```
And all the arguments of `pyarmor obfuscate` could be got from the output of `pyarmor pack`
