### ISSUE TITLE
 按照这个步骤放入HOME%/.pyarmor 依旧报错 c compiler "clang.exe" return error: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by rocing** [dashingsoft/pyarmor#1996]
从 Pyarmor 官网下载 [clang-9.0.zip](https://pyarmor.dashingsoft.com/downloads/tools/clang-9.0.zip) ，压缩包大小约为 26M 左右，里面只有一个可执行文件，解压后存放在 [根目录](https://pyarmor.readthedocs.io/zh/latest/reference/concepts.html#term-1) 下面，默认是 %HOME%/.pyarmor

 按照这个步骤放入HOME%/.pyarmor 依旧报错 c compiler "clang.exe" return error: [WinError 2] 系统找不到指定的文件。

**Comment by jondy** [comment]
同时检查一下这个文件是否有执行权限，或者直接在命令行执行一下看可以运行不
