### ISSUE TITLE
[BUG] `Error message`

### ISSUE THREAD

**Issue by yaomoshen5200** [dashingsoft/pyarmor#1997]
pyarmor pack myscript.py  这么打包出来的exe 运行不么 一直报错__main__.py: error: The '--include-package' option requires an argument with '--include-package='.
 要如何打包呢

**Comment by jondy** [comment]
请首先参考这里
https://pyarmor.readthedocs.io/zh/latest/reference/solutions.html#id11

如果存在 bug，请使用 `pyarmor man` 提及规范的问题报告，以便有效的解决问题

**Comment by yaomoshen5200** [comment]
import requests
def mian():
    url ="https://www.baidu.com/?tn=57095150_10_oem_dg"
    r = requests.get(url)
    print(r.text)


if __name__ == '__main__':
    mian()我的代码很简单 pyarmor                   7.7.4我用的是这个版本的 pyarmor pack demo.py 这么打包的&nbsp; &nbsp;File "dist\obf\.venv\Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_inspect.py", line 1, in <module&gt;
NameError: name '__pyarmor__' is not defined
[PYI-10392:ERROR] Failed to execute script 'pyi_rth_inspect' due to unhandled exception! 报这个错 我如何解决呢 你有没有视频教程啊 我确实想用你这个软件如果要用9的版本从新购买也可以但是我现在就是打包一直保持 如何解决呢
这个


&nbsp;


冰秋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月2日(星期一) 中午12:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dashingsoft/pyarmor] [BUG] `Error message` (Issue #1997)














 
请首先参考这里
 https://pyarmor.readthedocs.io/zh/latest/reference/solutions.html#id11
 
如果存在 bug，请使用 pyarmor man 提及规范的问题报告，以便有效的解决问题
