### ISSUE TITLE
[BUG] `Error message`

### ISSUE THREAD

**Issue by brandy-xu** [dashingsoft/pyarmor#2003]
linux上使用docker创建的windows10，生成设备文件时报错

报错信息：
[BUG]: <built-in function get_hd_info> returned a result with an exception set

## Command Line
E:\miniconda\Scripts\pyarmor reg -g 1

## Environments
Python 3.10.15
Pyarmor 9.0.6 (trial), 000000, non-profits
Platform windows.x86_64
Native windows.amd64
Home C:\Users\tode\.pyarmor

## Traceback
RuntimeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\miniconda\lib\site-packages\pyarmor\cli\__main__.py", line 784, in main
    main_entry(sys.argv[1:])
  File "E:\miniconda\lib\site-packages\pyarmor\cli\__main__.py", line 777, in main_entry
    return args.func(ctx, args)
  File "E:\miniconda\lib\site-packages\pyarmor\cli\__main__.py", line 264, in cmd_reg
    reg.generate_group_device(args.device)
  File "E:\miniconda\lib\site-packages\pyarmor\cli\register.py", line 369, in generate_group_device
    machid = self._get_machine_id(devflag).decode('utf-8')
  File "E:\miniconda\lib\site-packages\pyarmor\cli\register.py", line 359, in _get_machine_id
    return Pytransform3.get_hd_info(devflag)
  File "E:\miniconda\lib\site-packages\pyarmor\cli\core\__init__.py", line 124, in get_hd_info
    else m.get_hd_info(hdtype)
SystemError: <built-in function get_hd_info> returned a result with an exception set

**Comment by jondy** [comment]
请勿在 docker 容器中直接使用集团版许可证

**Comment by brandy-xu** [comment]
你们是不支持在docker容器中使用集团许可证吗？

**Comment by jondy** [comment]
不能直接使用，需要通过 pyarmor-auth 间接使用，请参考文档中如何使用许可证的内容

**Comment by brandy-xu** [comment]
主机上的pyarmor-auth已经开启，端口也是ok的，我这边是进入docker创建的windows容器，执行pyarmor reg  xxxxxx.zip命令进行注册的，但是还是报Pytransform3.get_hd_info(devflag)这个函数的错误

**Comment by jondy** [comment]
可以暂时应用下面这个补丁到 pyarmor 包的源代码
```patch
diff --git a/src/cli/register.py b/src/cli/register.py
index b1f21194..b569d175 100644
--- a/src/cli/register.py
+++ b/src/cli/register.py
@@ -356,7 +356,10 @@ class Register(object):
 
     def _get_machine_id(self, devflag=11):
         from .core import Pytransform3
-        return Pytransform3.get_hd_info(devflag)
+        try:
+            return Pytransform3.get_hd_info(devflag)
+        except SystemError:
+            return b'unknown-machine'
 
     def generate_group_device(self, devid):
         from datetime import datetime
```

这个问题会在下一个版本发布的时候解决
