### ISSUE TITLE
[BUG] missing reg.info in regfile

### ISSUE THREAD

**Issue by bvanelli** [dashingsoft/pyarmor#2007]
Finally upgrading the CI for Python 3.12, but there are some issues. I followed https://pyarmor.readthedocs.io/en/latest/how-to/ci.html#using-pyarmor-in-ci-pipeline. I have the file `pyarmor-regfile-1.zip`, but cannot actually request a CI file for the new CI method, becase I run into an error:

```
$ pyarmor reg -C pyarmor-regfile-1.zip
INFO     Python 3.11.8
INFO     Pyarmor 9.0.6 (trial), 000000, non-profits
INFO     Platform darwin.aarch64
INFO     request ci regfile by "pyarmor-regfile-1.zip"
ERROR    missing reg.info in regfile
ERROR    can not request CI license
```

Could not find this same error message in any parts of the documentation, nor in the issues.

Thanks!

**Comment by jondy** [comment]
You licnese file is old, not ready for Pyarmor 8.

Please search `upgrade` in the doc `how-to/register`

**Comment by bvanelli** [comment]
I have read it, but I don't have those files. From the upgrade:

- The license no. starts with `pyarmor-vax-` - it does if I run pyarmor register
- The original activation file `pyarmor-regcode-xxxx.txt` exists and isn’t used more than 100 times - don't have this file
- The old license is purchased before June 1, 2023 - was purchased in May 2020

So it means my only option is to buy a new license?

> If failed to upgrade the old license, please purchase new license to use Pyarmor latest version.

I would expect that to show in the message if that was the case. Instead I get an error, which is confusing.

**Comment by jondy** [comment]
Sorry, I'll refine the error message in next release.
