### ISSUE TITLE
[BUG] pyarmor gen -O dist -r -i iios 打包相关问题

### ISSUE THREAD

**Issue by yupu1998** [dashingsoft/pyarmor#2008]
运行 pyarmor gen -O dist -r -i iios 加密包
加密完成后
执行 python dist/iios/manage.py 报错
D:\project\CoCo\package>python dist/iios/manage.py
Traceback (most recent call last):
  File "D:\project\CoCo\package\dist\iios\manage.py", line 3, in <module>
    from .pyarmor_runtime_004740 import __pyarmor__
ImportError: attempted relative import with no known parent package
手动将项目内所有文件的form .pyarmor_runtime_004740，form ..pyarmor_runtime_004740  等引入语句 改为 form pyarmor_runtime_004740
项目启动成功
这是设计问题还是未处理的bug？

**Comment by jondy** [comment]
请参考文档了解选项 `-i` 的使用方法
