### ISSUE TITLE
ERROR    No dynamic library found for alpine.x86_64

### ISSUE THREAD

**Issue by carlosmarin** [dashingsoft/pyarmor#201]
Reproduce:
`pyarmor runtime --platform alpine.x86_64`

Full trace:
```
$ pyarmor runtime --platform alpine.x86_64
INFO     PyArmor Version 5.9.0
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Extract license.lic
INFO     Load platforms information from /Users/cmarin/opt/miniconda3/lib/python3.7/site-packages/pyarmor/platforms/index.json
INFO     No dynamic library found for alpine.x86_64
INFO     Load platforms information from /Users/cmarin/opt/miniconda3/lib/python3.7/site-packages/pyarmor/platforms/index.json
INFO     Search library for platform: alpine.x86_64
INFO     Found available libraries: ['alpine.x86_64.0']
INFO     Downloading library file for alpine.x86_64.0 ...
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r14.8/platforms/alpine/_pytransform.so
INFO     Writing target file: /Users/cmarin/.pyarmor/platforms/alpine/x86_64/0/_pytransform.so
INFO     Download dynamic library alpine.x86_64.0 OK
ERROR    No dynamic library found for alpine.x86_64
```

**Comment by thinline72** [comment]
Faced the same issue for linux_x86_64, but found a workaround. It seems like it downloads to the wrong path or it tries to access the wrong path from the code.

The correct path for me turned out to be: `~/.pyarmor/platforms/linux_x86_64/_pytransform.so`. The same as in the URL.

@carlosmarin So I believe for you the correct one might be: 
`~/.pyarmor/platforms/alpine/_pytransform.so` or 
`~/.pyarmor/platforms/alpine_x86_64/_pytransform.so`

**Comment by carlosmarin** [comment]
Thanks for the tip @thinline72. You're right, I see it under: 
`~/.pyarmor/platforms/alpine/x86_64/0/_pytransform.so`
the issue is that the command failure disrupts the build automation.

**Comment by thinline72** [comment]
Yeah, for me too. So I'm using this workaround for now in my Makefile:

```
mkdir -p ~/.pyarmor/platforms/linux_x86_64/
curl -o ~/.pyarmor/platforms/linux_x86_64/_pytransform.so https://github.com/dashingsoft/pyarmor-core/raw/r15.9/platforms/linux_x86_64/_pytransform.so
```

**Comment by jondy** [comment]
@carlosmarin 
A quick workaround is specify the feature number `.0` for this platform
```
pyarmor runtime --platform alpine.x86_64.0
```
It will not raise the exception. But it should not raise exception even if the platform name is `alpine.x86_64`, I'll fix it next version.

About the feature number of platform, refer to
https://pyarmor.readthedocs.io/en/latest/platforms.html#support-platfroms
