### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named scipy

### ISSUE THREAD

**Issue by yrik** [dashingsoft/pyarmor#2011]
I obfuscate my python code in the docker container and then move it to a target device (raspberry pi).
There is scipy installed globally on raspberry pi. If I import scipy via python shell - it works fine.
However, obfuscated python script complains that scipy could not be found, the same error happens with pymavlink package, other dependencies work fine.

**Comment by jondy** [comment]
Please report issue with `pyarmor man` to provide enough information
