### ISSUE TITLE
[BUG] `Error message`cannot assign to expression here. Maybe you meant '==' instead of '='? 

### ISSUE THREAD

**Issue by richardwu0313** [dashingsoft/pyarmor#2018]
[BUG]: cannot assign to expression here. Maybe you meant '==' instead of '='? (<frozen pyproject>, line 5)

## Command Line
pyarmor gen -O src_sec --platform linux.x86_64 -r -i src/fvr_airflow src/pyproject.toml src/requirements.txt src/scripts src/supervisord.conf src/uv.lock

## Environments
Python 3.11.10
Pyarmor 9.0.6 (trial), 000000, non-profits
Platform darwin.x86_64
Native darwin.x86_64
Home /Users/apple/.pyarmor

pyproject.toml
[project]
name = "xxx"
version = "0.1"
description = "xxx"
requires-python = ">=3.11,<3.12"

**Comment by jondy** [comment]
Only list .py file in command lines, pyarmor can obfuscate the python scripts only.

**Comment by richardwu0313** [comment]
> Only list .py file in command lines, pyarmor can obfuscate the python scripts only.

thanks, Jondy. I did not expect pyarmor to obfuscate other file types, I would expect pyarmor ignore pyproject.toml and continue to obfuscate other py files, but now pyarmor would stop when meeting pyproject.toml.
I have tried pyarmor cfg finder:excludes + "*/pyproject.toml", but without luck. Do you have suggestion?

**Comment by jondy** [comment]
Please first read the tutorial in the online doc
