### ISSUE TITLE
Is it possible to pack *.pkl or *.npy?

### ISSUE THREAD

**Issue by abawchen** [dashingsoft/pyarmor#202]
Hi, thanks for this great lib 👍 

When trying to include *.pkl and *.npy file(s), I got following error message, and wondering is it possible to do it at this moment? Thanks.

```
ERROR    'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
```

**Comment by jondy** [comment]
What means include `*.pkl` and `*.npy` files? PyArmor now only obfuscates all the `*.py` files, doesn't touch anything else.

**Comment by abawchen** [comment]
@jondy : yes, I know it, and just wondering is it possible to obfuscates *.pkl *.npy as well, since they are machine learning models I want to obfuscate as well.
Maybe it's beyond this project, I guess.

**Comment by jondy** [comment]
No, PyArmor could not implement that now. It could only obfuscate the code object of Python.
