### ISSUE TITLE
[BUG] `continue dont work in while loop with enable-bcc`

### ISSUE THREAD

**Issue by njockfatmih** [dashingsoft/pyarmor#2023]
```
def generator():
    counter = 0
    while 1:
        print(f"Counter: {counter}")
        counter+=1
        if counter > 100: return "success"
        for i in range(5):
            if 1:
                try: pass
                except: pass
            else:
                try: pass
                except: pass
        print("CONTINUE")
        continue
result = generator()
print(f"Result: {result}")
```
I have simplified my code to the limit to make it clear. In this code, after continue the function terminates for some unknown reason (exactly if you use --enable-bcc) if you just run the script it will return "success"
If you remove the loop - everything works with pyarmor --enable-bcc.
If you remove one try block - everything works with pyarmor --enable-bcc
If you remove one else block - everything works with pyarmor --enable-bcc.
This particular code construction does not work. I really want to use bcc, but I'm afraid that the same problem may occur on other code sections of a large project.
p.s. I understand that continue is not needed at the end, in the original code it is triggered by a condition and if the condition is not triggered, the other code works.

pyarmor line: pyarmor generate "test.py" --enable-bcc --output "build"
pyarmor version 9.0.6 (pro)
python version 3.9.13

**Comment by jondy** [comment]
I'll check it

**Comment by jondy** [comment]
I can't reproduce this issue.

What I test is using this script `tsrc/bugs/t2023.py`
```python
def generator():
    counter = 0
    while 1:
        print(f"Counter: {counter}")
        counter+=1
        if counter > 100: return "success"
        for i in range(5):
            if 1:
                try: pass
                except: pass
            else:
                try: pass
                except: pass
        print("CONTINUE")
        continue

result = generator()
print(f"Result: {result}")
```

And test is with
```
python3.9 -m pyarmor.cli --enable-bcc tsrc/bugs/t2023.py
python3.9 dist/t2023.py
```

It works fine, print 
```
...
CONTINUE
Counter: 99
CONTINUE
Counter: 100
Result: success
```

**Comment by njockfatmih** [comment]
I did it on windows. I have tried clang 9.0 and clang latest version and the result is the same "Result: None". Can you tell me what other programs might have been involved at the time of obfuscation?

**Comment by njockfatmih** [comment]
I thought it was a windows problem. No, I installed a clean ubuntu 24 and pyarmor failed again. The script is the same, the line parameters are the same as yours. Tried different versions of pyarmor - same thing.

**Comment by njockfatmih** [comment]
I want to specify that I use pro license without ci/cd. Maybe on version 9 with "pro" license pyarmor-8 is used regardless of the library version

**Comment by jondy** [comment]
The test pass is in Darwin.x86_64.

Reproduced it in Ubuntu.

I'll check it.

**Comment by jondy** [comment]
This bug will be fixed in next release.

The pre-release could be downloaded from

https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-9.0.7.zip

**Comment by njockfatmih** [comment]
thanks!
