### ISSUE TITLE
Pack with cx_freeze

### ISSUE THREAD

**Issue by Numenorean** [dashingsoft/pyarmor#203]
How can i most compactly build a script with Cx_Freeze?
Now i got thats files http://prntscr.com/rdeokb/direct and thats in lib folder http://prntscr.com/rdep08/direct
Can I pack it files in lib.zip or just all additional files in one folder?

**Comment by jondy** [comment]
PyArmor supports to pack with cx_Freeze by option `-t cx_Freeze`, for example
```
pyarmor pack -t cx_Freeze foo.py
```
It's recommended to pack with Pyinstaller in latest version of PyArmor.

**Comment by Numenorean** [comment]
> PyArmor supports to pack with cx_Freeze by option `-t cx_Freeze`, for example
> 
> ```
> pyarmor pack -t cx_Freeze foo.py
> ```
> 
> It's recommended to pack with Pyinstaller in latest version of PyArmor.

i got this error

**Comment by jondy** [comment]
cx_Freeze isn't tested for the latest version, it's deprecated now. 

Here is guide to pack the obfuscated scripts manually in the old document 
https://pyarmor.readthedocs.io/en/v5.1.2/pack-obfuscated-scripts.html#work-with-cx-freeze-

Before that, obfuscate scripts to `dist/obf`:
`pyarmor obfuscate --output dist/obf hello.py`
