### ISSUE TITLE
Is it possible to make the created executable using "pyarmor pack" command, fetch runtime packages from Python Library ?

### ISSUE THREAD

**Issue by ptrivedi2610** [dashingsoft/pyarmor#204]
@jondy 

Recently I have a requirement where the executable created by "pyarmor pack "command, abc.exe, itself generates some package.
The abc.exe then runs a given setup.py and installs the generated package in Python system library path.

However, what I observed is that if a package is generated and installed after abc.exe is created from pack command, it doesn't go to search in Python system path.

To summarize.

1. abc.exe is created from pyarmor pack command.
2. abc.exe when executed creates a custom python package PackageA. It then installs PackageA using "python setup.py install --user".
3. When abc.exe is executed again with a difference mode to search for PackageA, it's unable to find PackageA
What I feel is that the executable doesn't search in Python library path during execution.

If PackageA is already present before pack command is executed, things work fine.
Is there any solution to the same ?

**Comment by jondy** [comment]
The executable `abc.exe` generated by PyInstaller is expected to run without installing a Python interpreter. So you have to append extra Python path by runtime hook. For example, create a hook file `extra_python_path.py`
```
import sys
# Please replace this path with the actual value, or something like os.path.expandvars('$PYTHONPATH')
sys.path.append('/usr/lib/python3.7')
```
Then pass extra option `--runtime-hook` when packing the abc.py, for example
```
pyarmor pack -e " --runtime-hook extra_python_path.py" abc.py
```
The runtime hook script `extra_python_path.py` will be executed before any other code or module to set up special features of the runtime environment.

**Comment by ptrivedi2610** [comment]
@jondy 
This solved the issue. Thanks
