### ISSUE TITLE
Package as onefile

### ISSUE THREAD

**Issue by jakestrouse00** [dashingsoft/pyarmor#205]
How would we package a script as one file? With Pyinstaller, I can do it like this `pyinstaller -F script.py`. Also, is there a way to pack the script with an icon for the exe as well?

**Comment by jondy** [comment]
Any PyInstaller option could be passed to pyarmor by the option `-e`, for example,
```
pyarmor pack -e " -F --icon logo.ico" foo.py
```

In the pyarmor-webui, fill these options in the field `Pcck Options` of the project page.
