### ISSUE TITLE
Include non-python files

### ISSUE THREAD

**Issue by Make42** [dashingsoft/pyarmor#208]
I am using Nuitka to create an `.so` and an `.pyi` file from my `.py` module. Let's say my module is called `mymodule.py`. Now I have the files `mymodule.pyi` and `mymodule.so`. I am able to load this C module simply my running `import mymodule`. I would like to have pyarmor also encrypt these files. Theoretically this should be simple: Just act as if `mymodule.pyi` and `mymodule.so` where other `.pyc`-files. Can this be done already? Could this be implemented? The question is not restricted to Nuitka in itself: It basically is the question how to have pyarmor protect the entire project, independent of whether it is Python code or not in the modules.

**Comment by jondy** [comment]
Now PyArmor could not obfuscate `mymodule.so` and `mymodule.pyi`, only the code object of CPython could be obfuscated.

Many users ask for how pyarmor could protect data files, I may add this feature later.

**Comment by jondy** [comment]
I document one solution here [How to protect data files by PyArmor](https://pyarmor.readthedocs.io/en/latest/advanced.html#how-to-protect-data-files)
