### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by stormbo488** [dashingsoft/pyarmor#210]
hello i have this error, can someone help me?

C:\Users\storm\Desktop\StormAIOV1>Pyarmor pack -x " -restrict=0" -e " -onefile" BSTN.py
INFO     PyArmor Version 5.9.3
INFO     Prepare to pack obfuscated scripts with PyInstaller...
INFO     entry script: BSTN.py
INFO     src for searching scripts: .
INFO     build path: dist\obf
INFO     Run PyArmor to obfuscate scripts...
INFO

c:\users\storm\appdata\local\programs\python\python38\python.exe c:\users\storm\appdata\local\programs\python\python38\lib\site-packages\pyarmor\pyarmor.py obfuscate -r -O dist\obf --exclude dist --package-runtime 0 -restrict=0 .\BSTN.py

INFO     Create temp path: dist\obf\temp
INFO     Generate hook script: dist\obf\temp\hook-pytransform.py
INFO     Run PyInstaller to generate .spec file...
INFO

p y i - m a k e s p e c --distpath dist -onefile -y -p dist\obf\temp --hidden-import pytransform --additional-hooks-dir dist\obf\temp .\BSTN.py

INFO

c:\users\storm\appdata\local\programs\python\python38\python.exe -m PyInstaller --distpath dist -onefile -y -p dist\obf\temp --hidden-import pytransform --additional-hooks-dir dist\obf\temp .\BSTN.py

ERROR

usage: __main__.py [-h] [-v] [-D] [-F] [--specpath DIR] [-n NAME]
                   [--add-data <SRC;DEST or SRC:DEST>]
                   [--add-binary <SRC;DEST or SRC:DEST>] [-p DIR]
                   [--hidden-import MODULENAME]
                   [--additional-hooks-dir HOOKSPATH]
                   [--runtime-hook RUNTIME_HOOKS] [--exclude-module EXCLUDES]
                   [--key KEY] [-d {all,imports,bootloader,noarchive}] [-s]
                   [--noupx] [--upx-exclude FILE] [-c] [-w]
                   [-i <FILE.ico or FILE.exe,ID or FILE.icns>]
                   [--version-file FILE] [-m <FILE or XML>] [-r RESOURCE]
                   [--uac-admin] [--uac-uiaccess] [--win-private-assemblies]
                   [--win-no-prefer-redirects]
                   [--osx-bundle-identifier BUNDLE_IDENTIFIER]
                   [--runtime-tmpdir PATH] [--bootloader-ignore-signals]
                   [--distpath DIR] [--workpath WORKPATH] [-y]
                   [--upx-dir UPX_DIR] [-a] [--clean] [--log-level LEVEL]
                   scriptname [scriptname ...]
__main__.py: error: unrecognized arguments: -onefile

ERROR    usage: __main__.py [-h] [-v] [-D] [-F] [--specpath DIR] [-n NAME]
                   [--add-data <SRC;DEST or SRC:DEST>]
                   [--add-binary <SRC;DEST or SRC:DEST>] [-p DIR]
                   [--hidden-import MODULENAME]
                   [--additional-hooks-dir HOOKSPATH]
                   [--runtime-hook RUNTIME_HOOKS] [--exclude-module EXCLUDES]
                   [--key KEY] [-d {all,imports,bootloader,noarchive}] [-s]
                   [--noupx] [--upx-exclude FILE] [-c] [-w]
                   [-i <FILE.ico or FILE.exe,ID or FILE.icns>]
                   [--version-file FILE] [-m <FILE or XML>] [-r RESOURCE]
                   [--uac-admin] [--uac-uiaccess] [--win-private-assemblies]
                   [--win-no-prefer-redirects]
                   [--osx-bundle-identifier BUNDLE_IDENTIFIER]
                   [--runtime-tmpdir PATH] [--bootloader-ignore-signals]
                   [--distpath DIR] [--workpath WORKPATH] [-y]
                   [--upx-dir UPX_DIR] [-a] [--clean] [--log-level LEVEL]
                   scriptname [scriptname ...]
__main__.py: error: unrecognized arguments: -onefile

C:\Users\storm\Desktop\StormAIOV1>

**Comment by jondy** [comment]
It should double dash before `onefile`, for example `--onefile`, there is only one dash `-` in your command.

**Comment by stormbo488** [comment]
Hello, everytime if i obfuscate with pyarmor i got a whole “lib” map that
is 4000kb. Without that file my program isn’t working. I don’t want that
whole map, do you know how i can avoid that?

Greetings from storm peters

**Comment by jondy** [comment]
@stormbo488 

Exclude any path by `--exclude`, for example
```
pyarmor pack -x " --restrict 0 --exclude lib" -e " --onefile" BSTN.py
```
