### ISSUE TITLE
Pyinstaller pytransform.PytransformError

### ISSUE THREAD

**Issue by asrabon** [dashingsoft/pyarmor#211]
I created an executable using pyarmor's pack command. This program works no issues during when it initially runs. However, the program is multiprocessing and it spawns a fair amount of processes through the run. I have ran it on 4 computers, 3 of which has had no issues. One of the computers will run the program without any issues but, will occasionally get pyinstaller's "Failed to execute" error message when it a new process begins. However, the "Failed to execute" error messages don't always happen or won't happen the exact same amount of times. Here is the error message I get when the executable has been created in console mode. 

Traceback (most recent call last):
  File "dist\obf\temp\pytransform.py", line 297, in pyarmor_runtime
pytransform.PytransformError: Check license failed, Invalid input packet.

**Comment by jondy** [comment]
When the obfuscated script starts, it will first check license. If it spend too much time to check license, for example, the machine is not fast enough, or it's too busy, it will report this error. I'm not sure, but you can verify it by packing the scripts with the less feature dynamic library `_pytransform.so`, it will check less. 

Just specify extra obfuscated option `--platform` with feature number `0` in pack command, for example,
```
pyarmor pack -x " --platform linux.x86_64.0" ...
```
The platform name should be your target machine platform, for example, in 32-bit windows, it's `windows.x86.0`. 

Besides, packing the scripts in 32-bit Windows, sometimes it will check license failed as running the final bundle in 64-bit Windows.
