### ISSUE TITLE
pack -e errors when specifying --name and -s specfile

### ISSUE THREAD

**Issue by zachOps** [dashingsoft/pyarmor#213]
When naming the file in the PyInstaller arguments using -e and --name I instantly get error saying foo.spec can't be found.

Running the PyInstaller command on it's own is fine and Not specifying --name nor -s works fine.

osx 10.15.4
python 3.8.2
pyarmor 5.9.4
pyinstaller 3.6

This works:
% pyinstaller -F -y main.py

This works:
% pyarmor pack --clean -e " -F -y "  main.py

This doesn't:
% pyarmor pack --clean -e " -F -y --name foo " -s foo.spec main.py
INFO     PyArmor Version 5.9.4
INFO     Prepare to pack obfuscated scripts with PyInstaller...
INFO     entry script: main_ingest.py
INFO     src for searching scripts: .
ERROR    No specfile foo.spec found

Also, getting a -y error during the build.  Even if I remove -y from the above command...

INFO     Create temp path: dist/obf/temp
INFO     Generate hook script: dist/obf/temp/hook-pytransform.py
INFO     Run PyInstaller to generate .spec file...
INFO     

pyi-makespec -y -p dist/obf/temp --hidden-import pytransform --additional-hooks-dir dist/obf/temp ./main_ingest.py

ERROR    

usage: pyi-makespec [-h] [-D] [-F] [--specpath DIR] [-n NAME]
                    [--add-data <SRC;DEST or SRC:DEST>]
                    [--add-binary <SRC;DEST or SRC:DEST>] [-p DIR]
                    [--hidden-import MODULENAME]
                    [--additional-hooks-dir HOOKSPATH]
                    [--runtime-hook RUNTIME_HOOKS] [--exclude-module EXCLUDES]
                    [--key KEY] [-d {all,imports,bootloader,noarchive}] [-s]
                    [--noupx] [--upx-exclude FILE] [-c] [-w]
                    [-i <FILE.ico or FILE.exe,ID or FILE.icns>]
                    [--version-file FILE] [-m <FILE or XML>] [-r RESOURCE]
                    [--uac-admin] [--uac-uiaccess] [--win-private-assemblies]
                    [--win-no-prefer-redirects]
                    [--osx-bundle-identifier BUNDLE_IDENTIFIER]
                    [--runtime-tmpdir PATH] [--bootloader-ignore-signals]
                    [--log-level LEVEL]
                    scriptname [scriptname ...]
pyi-makespec: error: unrecognized arguments: -y -y

**Comment by jondy** [comment]
Do not pass `-y` to pyinstaller by the option `-e`, it will be appended by `pack` command automatically.

Also not pass `--name` by `-e`, it need some special handling by pyarmor, so pass it out of `-e`, for example,
```
pyarmor pack --name MyApp -e " --onefile" foo.py
```

**Comment by zachOps** [comment]
Thank you.  Though if I omit -y from the command entirely I still get:
...
pyi-makespec: error: unrecognized arguments: -y

In what version did these change?  In 5.7.6 I was able to pass both -y and --name via -e, but I can't find it in the version change logs.

I see "Add new option –name in the command pack" in the change log for 5.9.0 but it's a single dash, not two as you've mentioned.  And in section 4.1 of the docs for 5.9.0 the example is:

pyarmor pack -e " --name easy-han --hidden-import comtypes --add-data 'config.json;.'
˓→" \
-x " --exclude vnev --exclude tests" -s "easy-han.spec" main.py

**Comment by jondy** [comment]
> pyi-makespec: error: unrecognized arguments: -y

It's a bug, I'll fixed in next version. As a quick workaround, edit `{pyarmor-folder}/packer.py` in the function `_pyi_makespec` about line 258, remove `-y` from the options.

> In what version did these change? In 5.7.6 I was able to pass both -y and --name via -e, but I can't find it in the version change logs.

This should be changed in the v5.9.0, maybe the example document isn't updated in that version, but these examples has been updated in latest version.

Now just specify `--name` to change the final bundle name, no `-s` required. And `-s` is mainly for packing the scripts with an exists spec file. I think it's more simple and clear.

**Comment by zachOps** [comment]
Ok, excellent!  Thank you for the quick and clear responses!

**Comment by zachOps** [comment]
... and thank you so much for the quick bug fix!

.z
