### ISSUE TITLE
ModuleNotFoundError: No module named '__main__.pytransform'; '__main__' is not a package

### ISSUE THREAD

**Issue by scullcandyz** [dashingsoft/pyarmor#214]
First off still very new to all of this so forgive if im simply doing something completely wrong here. 
Pyinstaller: 3.5
Python 3.7.4
Pyarmor: 5.9.4

Now as I first ran the pack command together with some pyinstaller commands, everything worked flawlessly. At this point I simply had my main.py wrapped into 
**if __name__ == '__main__':
     main()**

For some reason this worked, from my understanding now, it should not have as bootstrap code would be run on main.py, trying the 2nd time it returned the  **NameError __pyarmor__ can not be found** on the resulting .exe

So what I did was create a seperate __init__.py which I would run my command on. First off all is this correct do I run the pack command on __init__.py? Anyhow this would result on bootsrap being run on __init__.py and the 3 other .py files simply having the __pyarmor__ infront of it. The error im getting out of running this is: 

**ModuleNotFoundError: No module named '__main__.pytransform'; '__main__' is not a package**

The command im running is: **pyarmor pack -e "--onefile -i 'PathToIcon' --add-data 'pathToPyfiglet' --add-binary './driver/chromedriver.exe;./driver'"  __init__.py**

**Comment by jondy** [comment]
Please specify extra obfuscating option `--bootstrap 2` to fix issue, for example
```
pyarmor pack -x " --bootstrap 2" -e ...
```
If the entry script is `__init__.py`, the bootstrap code will make a relative import by using leading dots. By setting `--bootstrap` to 2, the bootstrap code always makes absolute import without leading dots.

**Comment by scullcandyz** [comment]
Thanks for the quick answer, worked like a charm.
