### ISSUE TITLE
Obfuscated python script gives Segmentation Fault on MAC machine

### ISSUE THREAD

**Issue by ptrivedi2610** [dashingsoft/pyarmor#215]
@jondy 

Hello, I am working on a project that uses "pyarmor pack" command. Using this I was successfully able to create installer on all 3 platforms - windows, linux  and MAC. The executable binary executed successfully on Linux and Windows, but gave segmentation fault on MAC. Please find details below

I tried separately both with pyinstaller and pyarmor. Seems it crashes in pyarmor, and not pyinstaller. Obfuscated code without executable also throws segmentation fault

1. MAC version - 10.15.3
2. Pyarmor version - 5.9.0
3. Python version - 3.7.0

Below is line in pytransform.log
**The core library version: r14, age: 8, features: 7**

Can you help me find the issue ?

**Comment by jondy** [comment]
Try to obfuscate the scripts with feature `0`, for example,
```
pyarmor obfuscate --platform darwin.x86_64.0 foo.py
```  
If it works, pass this option to `pack` by `-x`, for example,
```
pyarmor pack -x " --platform darwin.x86_64.0" foo.py
```

**Comment by ptrivedi2610** [comment]
@jondy 
Getting below error 

INFO     PyArmor Trial Version 5.9.0
INFO     Target platforms: ['darwin.x86_64.0']
INFO     ===========================================
INFO     Reboot PyArmor to obfuscate the scripts for platform darwin.x86_64.0
INFO     ===========================================
INFO     PYARMOR_PLATFORM is set to darwin.x86_64.0
INFO     Load platforms information from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyarmor/platforms/index.json
INFO     Search library for platform: darwin.x86_64.0
INFO     Found available libraries: ['darwin.x86_64.0']
INFO     Downloading library file for darwin.x86_64.0 ...
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r14.8/platforms/darwin.x86_64.0/_pytransform.dylib
INFO     Could not get file from https://github.com/dashingsoft/pyarmor-core/raw/r14.8/platforms: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
INFO     Getting remote file: https://pyarmor.dashingsoft.com/downloads/r14.8/darwin.x86_64.0/_pytransform.dylib
INFO     Could not get file from https://pyarmor.dashingsoft.com/downloads/r14.8: <urlopen error [Errno 8] nodename nor servname provided, or not known>
ERROR    Download library file failed

**Comment by jondy** [comment]
Could you download it directly and save it to `~/.pyarmor/platforms/darwin/x86_64/0`? For example
```
mkdir -p ~/.pyarmor/platforms/darwin/x86_64/0
cd ~/.pyarmor/platforms/darwin/x86_64/0
wget --no-check-certificate  https://github.com/dashingsoft/pyarmor-core/raw/r14.8/platforms/darwin.x86_64.0/_pytransform.dylib
```
Then obfuscate the scripts with this one.

**Comment by ptrivedi2610** [comment]
@jondy  This can be used with free version, nothing proprietary, correct ?

**Comment by jondy** [comment]
> This can be used with free version, nothing proprietary, correct ?

It's under the same EULA of pyarmor, refer to https://pyarmor.readthedocs.io/en/latest/license.html

> Also, will these need to be used static the same way you mentioned ?

It raises an SSL: CERTIFICATE_VERIFY_FAILED when pyarmor downloads it by itself.  Maybe it's a bug, maybe it's network problem, I'll check it.

> Why we need this in MAC separately?

Not all of MAC need this. The full features `_pytransform.dylib` will patch Python dynamic library, pyarmor maybe makes mistake if Python interpreter is compiled by old gcc or some other C compiles.

Could you upload the python library `libpython3.7m.dylib` here? I'll check it to find why it doesn't work.

**Comment by jondy** [comment]
About the download issue `ERROR Download library file failed`, try to install a package:
```
pip install certifi
```

**Comment by ptrivedi2610** [comment]
@jondy 
Here is the libpython3.7m.dylib

**Comment by jondy** [comment]
I think you can tell this by pyarmor EULA, I don't know how do you use pyarmor exactly.

**Comment by jondy** [comment]
@ptrivedi2610 You may send `libpython3.7m.dylib` to my email `jondy.zhao@gmail.com`

**Comment by VeNoMouS** [comment]
@jondy anything further on this, I had a user tonight that is having a similar issue

**Comment by jondy** [comment]
If it's running the obfuscated scripts, try to run it with extra option `-d`, for example,
```
python -d dist/foo.py
```
Then check the output.

If it's crashed when obfuscating the scripts, try to uncomment line 268 in the `pytransform.py` which locates in the pyarmor package path:
```
    # Disable advanced mode if required
    m.set_option(5, c_char_p(1))
```

**Comment by VeNoMouS** [comment]
thanks @jondy ill have the user check <3

**Comment by Seraphppy** [comment]
@jondy 

Hi, ive tried your example and disabled that line of code and still getting:
SystemError: unknown opcode

I tried running with the -d flag and it returned:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyarmor/__init__.py

**Comment by jondy** [comment]
@Seraphppy are you running the obfuscated scripts? If it is, you need not install pyarmor, and it should not report any error related to `pyarmor/__init__.py`.

**Comment by VeNoMouS** [comment]
@jondy hes runnign my code, its working for other os's just not his osx

**Comment by jondy** [comment]
@VeNoMouS So what's the real output of `python -d obf.py`? It should not be related to `pyarmor/__init__.py`

**Comment by Seraphppy** [comment]
@jondy This is the output when running with the -d flag:

XXX lineno: 2, opcode: 204
Traceback (most recent call last):
  File "obfscript.py", line 9, in <module>
    from module_ import (
  File "</Users/xxxx/xxx/xxx/xxx/__init__.py>", line 4, in <module>
  File "<frozen obfscript>", line 2, in <module>
SystemError: unknown opcode

**Comment by jondy** [comment]
In the current path to run the obfuscated scripts, is there any file like `license.lic`, `pytransform.key`, `pyshield.key`?

**Comment by VeNoMouS** [comment]
Yea I gave him license.lic and pytransform.key, the same package works with other users on different os's...

**Comment by Seraphppy** [comment]
@jondy what @VeNoMouS said!

**Comment by jondy** [comment]
@Seraphppy the obfuscated scripts must be run with the corresponding runtime package `pytransform` which is distributed with the obfuscated scripts. I guess in this machine the obfuscated scripts may import `pytransform` from other path.

**Comment by VeNoMouS** [comment]
I just had another Mac user try, and they cant load it either

**Comment by VeNoMouS** [comment]
@jondy when it asks for this ... under osx..

`pytransform/platforms/darwin/x86_64/_pytransform.dylib`

can users use `https://github.com/dashingsoft/pyarmor-core/tree/master/platforms/darwin.x86_64.0`?

**Comment by jondy** [comment]
@VeNoMouS  
If use `darwin.x86_64.0`, you need obfuscate scripts for it like this:
```
pyarmor obfuscate --platform darwin.x86_64.0 ...
```
The old obfuscated scripts don't work with `darwin.x86_64.0`

**Comment by VeNoMouS** [comment]
Ok let me test it for them via that way, but apart from putting the dynlib in the pytransform, is there anythign else htat happens specifying that?

**Comment by jondy** [comment]
It uses the different key to obfuscate the scripts, more information refer to https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-scripts-with-different-features

**Comment by VeNoMouS** [comment]
@jondy yea that was the problem, weird!! cheers
