### ISSUE TITLE
No module named 'xxxxx' 

### ISSUE THREAD

**Issue by BarryAl-Jawari** [dashingsoft/pyarmor#216]
Hello Mr Senpai!

I have been coding for a while and managed to create a main py file which includes many another py scripts that I have created (Like a key chain connection basically) and whenever I run the main.exe file, it runs fine. Then I have a sort Menu option to choose which "py file you want to run" - So the first main.py file works fine. No problems but then when I choose I want to run test2.py example by having import test2 and then run test2.main() is where is failing which gives me an error saying example "NO module named 'colorama'" example. 

My idea is to not have python installed on my second laptop to still be able to run the exe file but I am not managed to do it yet :(

What I am running when using py is:

pyarmor pack --clean -e "--onefile --add-data='C:\Users\Barry-PC\AppData\Roaming\Python\Python37\Lib\site-packages\cloudscraper\;cloudscraper' --i barrytest.ico" barrytest.py

Python 3.7.4
Latest Pyarmor, I believe 5.9.0? :D 

I hope you are able to help me with it :( Because im not sure if I am doing something incorrect.

**Comment by jondy** [comment]
Append `--hidden-import colorama` to the option `-e`, also add any other hidden import if it reports this error.

Refer to https://pyarmor.readthedocs.io/en/latest/man.html#pack

**Comment by BarryAl-Jawari** [comment]
> Append `--hidden-import colorama` to the option `-e`, also add any other hidden import if it reports this error.
> 
> Refer to https://pyarmor.readthedocs.io/en/latest/man.html#pack

You are an absolutely genius! Appreciate the help!
