### ISSUE TITLE
How to integrate private license with pyarmor pack

### ISSUE THREAD

**Issue by ptrivedi2610** [dashingsoft/pyarmor#218]
@jondy 

I am directly using "pyarmor pack" command
How to integrate private license.lic file received in pyarmor-regfile-1.zip with this command ?

Is there a way to test it that the generated files are with new private license ?

**Comment by jondy** [comment]
First run `pyarmor register` to take the key file effects,  after that, `pyarmor pack` will pack the private license into the bundle.

> Is there a way to test it that the generated files are with new private license ?
```
pyarmor pack foo.py
cp /path/to/other/license.lic dist/foo/license.lic
```

More information about `pack`, refer to https://pyarmor.readthedocs.io/en/latest/man.html#pack

**Comment by ptrivedi2610** [comment]
@jondy 
Does this means the content inside private license.lic shoul be same as the one generated in dist/myscript/license.lic ?

I see those are different

**Comment by jondy** [comment]
No. They're totally different. The former is for PyArmor, issued by me, the latter is generated by you. 

Refer to https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-license-file-for-obfuscated-script

**Comment by ptrivedi2610** [comment]
@jondy 
Ok completely got your point. Final queries from my end.

1. Is there a way to generate license for my script using Pyarmor ? Like a key without which the executable created by my using pyarmor cannot run ?
2. If I upgrade pyarmor to newer versions, the private license would still work, right ?
3. How to make sure that the obfuscation and packing generated by private key has no footprints of default free version in the distribution generated ?

**Comment by jondy** [comment]
> 1. Is there a way to generate license for my script using pyarmor ? Like a key without which the executable created by my pyarmor pack command cannot run ?

Refer to commands `licenses`, `hdinfo` and `pack` https://pyarmor.readthedocs.io/en/latest/man.html#licenses
https://pyarmor.readthedocs.io/en/latest/man.html#hdinfo
https://pyarmor.readthedocs.io/en/latest/man.html#pack

And if you pack one file bundle, this may be helpful
https://pyarmor.readthedocs.io/en/latest/advanced.html#bundle-obfuscated-scripts-to-one-executable-file
 
> 2. If I upgrade pyarmor to newer versions, the obtained private license would still work, right ?

Up to now it is, but I can't promise there is no upgrade fee forever. It may NOT work with new versions in future.

> 3. How to make sure that the obfuscation and packing distribution (dist/) generated by pyarmor using private key, has no footprints of default free version ?

Make sure both of files `~/.pyarmor_capsule.zip` and `~/.pyarmor/license.lic` are unzipped from the private key file `pyarmor-keyfile-1.zip`. And remove all the obfuscated scripts which are obfuscated by free version.
