### ISSUE TITLE
The obfuscated script can't run at another OS

### ISSUE THREAD

**Issue by actualyang** [dashingsoft/pyarmor#220]
I obfuscate the python script at window server 2016 which can't be run in Win10 or in Win server 2012.
What is wrong?
The trace back has a error : Protection Fault: unexpected pytransform.py
I use "pyarmor obfuscate --src= -r -O"

**Comment by jondy** [comment]
Make sure the python version are same in both of 2 machines, also run obfuscated script with `-d` to get more information:
```
python -d obfuscated_script.py
```
