### ISSUE TITLE
Runtime error with Docker alpine 3.8

### ISSUE THREAD

**Issue by anhhoangiot** [dashingsoft/pyarmor#221]
My application keeps failing to boot when running the Pyarmor obfuscated scripts in Docker alpine image. If I use the plain script or another linux image, it works without any problems. I tried to replace the .so file with the one downloaded from platform page, but it only fixes the issue **_pytransform.so: __snprintf_chk: symbol not found**, the application still failed to boot. Do you have any idea? I use supervisord and gunicorn to run my application.

**Comment by jondy** [comment]
If you replace the `.so` manually, make sure the obfuscated scripts are obfuscated with `--no-cross-protection`, or specify the right `--platform`.

**Comment by anhhoangiot** [comment]
Thank you very much, I got it work by using the following command:
pyarmor obfuscate --recursive --platform alpine.x86_64.0 --output ./dist main.py
