### ISSUE TITLE
Where does pyarmor+pyinstaller install custom python packages when I use python from executable?

### ISSUE THREAD

**Issue by ptrivedi2610** [dashingsoft/pyarmor#223]
Hi @jondy 
I have created dist/ folder on Windows, using "pyarmor pack". Python3.7 is bundled inside dist/.
Now I am taking this dist/ folder in separate machine where no Python in installed.

**I have my custom python package PKG, inside dist/ which I need to install in the system using executable, using "python setup.py install --user".**

When I run my executable, it shows the package is installed successfully.
My question is, normally in  a machine where Python is installed, such packages goes to "site-packages"
But in my case, where would the package have been installed ?

**Comment by jondy** [comment]
> When I run my executable, it shows the package is installed successfully.

If it's installed successfully, does it print the path where to install in the console?

As my understanding, the executable generated by Pyinstaller is totally different from Python, it's more like a binary file. So it doesn't make sense to install package for it, more information refer to [PyInstaller Run-time Information](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html)
