### ISSUE TITLE
cython

### ISSUE THREAD

**Issue by linqingfan** [dashingsoft/pyarmor#224]
Hi,
When we try to use together with Cython after pyamor obscufication, there is following error:

Cannot find the symbol __ pyarmor __

I have added the following in cython:

library_dirs = ['./pytransform'],libraries=[' _pytransform']

Did I miss out anything? Thanks

**Comment by jondy** [comment]
Make sure the bootstrap function [pyarmor_runtime](https://github.com/dashingsoft/pyarmor/blob/master/src/pytransform.py#L297) in the runtime package `pytransform` is executed before any obfuscated scripts are imported.

But I'm not sure PyArmor could work with Cython, I need to check the documentation of Cython to find the answer.

**Comment by linqingfan** [comment]
sorry, how to execute the pyarmo_runtime?
The obfuscated codes can run. However, when I try to cyhonised each obfuscated py file, it complains that cannot find the symbol  __ pyarmor __

**Comment by jondy** [comment]
This function is created in the runtime implicitly, I had thought this error occurs in the runtime, but it happened in build time. I need research Cython to solve this.

**Comment by jondy** [comment]
Hi guy, how about run `cythonize` with extra option `-k` to ignore this error if possible, I find this otion in [Cythonize.py#L170](https://github.com/cython/cython/blob/master/Cython/Build/Cythonize.py#L170)

Or do you know any way let Cython take this function `__pyarmor__` just as one builtin function , such as `open` etc. ?  Because it will be added in the runtime automatically, so long as the scripts could be compiled successfully, it should be no problem to run.

**Comment by jondy** [comment]
Here it's an example show how to `cythonize` a python script `foo.py` obfuscated by pyarmor with Python37:

    print('Hello Cython')

First obfuscate it with some extra options:

    pyarmor obfuscate --package-runtime 0 --no-cross-protection --restrict 0 foo.py

The obfuscated script and runtime files will be saved in the path `dist`, about the meaning of each options, refer to command :ref:`obfuscate`.

Next `cythonize` both `foo.py` and `pytransform.py` with extra options ``-k`` and ``--lenient`` to generate `foo.c` and `pytransform.c`:

    cd dist
    cythonize -3 -k --lenient foo.py pytransform.py

Without options ``-k`` and ``--lenient``, it will raise exception:

    undeclared name not builtin: __pyarmor__

Then compile `foo.c` and `pytransform.c` to the extension modules:

    gcc -shared $(python-config --cflags) $(python-config --ldflags) \
         -o foo$(python-config --extension-suffix) foo.c

    gcc -shared $(python-config --cflags) $(python-config --ldflags) \
        -o pytransform$(python-config --extension-suffix) pytransform.c

Finally test it, remove all the `.py` files and import the extension modules:

    mv foo.py pytransform.py /tmp
    python -c 'import foo'

It will print `Hello Cython` as expected.

**Comment by linqingfan** [comment]
Hi, I tried your example. But I cant make multiple py files in a project to work.
For example, how do you make main.py and submodules.py to work? where some functions in the submodules are called by main.py

**Comment by linqingfan** [comment]
This is the erro:

gcc -shared $(python-config --cflags) $(python-config --ldflags) -o foo$(python-config --extension-suffix) foo.c
/usr/bin/ld: error: /tmp/ccEIti4p.o: requires dynamic R_X86_64_PC32 reloc against '_PyThreadState_Current' which may overflow at runtime; recompile with -fPIC
collect2: error: ld returned 1 exit status

**Comment by jondy** [comment]
@linqingfan
> This is the erro:

> gcc -shared $(python-config --cflags) $(python-config --ldflags) -o foo$(python-config --extension-suffix) foo.c
> /usr/bin/ld: error: /tmp/ccEIti4p.o: requires dynamic R_X86_64_PC32 reloc against '_PyThreadState_Current' which may overflow at runtime; recompile with -fPIC
> collect2: error: ld returned 1 exit status

Why not try to append this cpfag`-fPIC` to run `gcc`, the error message has told you how to fix it. It's not required in my MacOS, but it's required in the Linux.

> Hi, I tried your example. But I cant make multiple py files in a project to work.
> For example, how do you make main.py and submodules.py to work? where some functions in the submodules are called by main.py

Just compile `submodules.py` to `*.c`, then to `*.so`. Each `.so` is an extension module which is same as `.py` module.

Please check Cython documentation for more information, now I'm sure pyarmor could work with Cython.
