### ISSUE TITLE
[QUESTION] PyArmor / PyUpdater? 

### ISSUE THREAD

**Issue by scullcandyz** [dashingsoft/pyarmor#225]
Less of an issue more of a question, couldnt really find anything on this so ill just ask here. Could I obfuscate my scripts with PyArmor and then pack them with PyUpdater? Id assume this works as PyUpdater is build upon PyInstaller, figured id rather ask first.

**Comment by jondy** [comment]
After looking through the package PyUpdater, I think pyarmor should work with PyUpdater by this way:

1. Generate a "foo.spec" by PyUpdater
2. Generate foo-patched.spec by pyarmor

pyarmor pack --debug -s foo.spec foo.py

The patched foo-patched.spec could be used by PyUpdater in build command

If your scripts are modified, just obfuscate them again, all the options for command "pyarmor obfuscate" could be got from the output of command pack.

Refer to command [pack](https://pyarmor.readthedocs.io/en/latest/man.html#pack) and [bundle-obfuscated-scripts-with-customized-spec-file](https://pyarmor.readthedocs.io/en/latest/advanced.html#bundle-obfuscated-scripts-with-customized-spec-file)

Feel free to let me know if there is any problem.

**Comment by scullcandyz** [comment]
Compiling seems to be no issue, resulting .exe is obfuscated aswell. Unfortunately im getting errors trying either way when running the resulting .exe

Running pyupdater build with foo-patched.spec: 

![image](https://user-images.githubusercontent.com/58109239/80283863-3322b200-871b-11ea-87f2-df0760cd8794.png)

Running pyarmor pack with foo.spec from pyupdater:

Cant find picture right now, ill edit in later.

**Comment by scullcandyz** [comment]
Alright so I couldnt really get it to work that way, always ended up with PyArmor related errors on the final executable. 

For future reference if anybody is having issues with the above. Just normally compiling it in PyArmor then zipping and putting it into "pyu-data/new" works. From there on you can just normally sign, process and upload your update.
