### ISSUE TITLE
How to create clickable executable using pyarmor pack, suth that created executable can take CLI arguments

### ISSUE THREAD

**Issue by ptrivedi2610** [dashingsoft/pyarmor#227]
@jondy 
My aim is to create a executable using "pyarmor pack" that can run by a single click, at the same take command-line arguments that my original python code had.
I need this for all 3 platforms Windows Linux MAC 

How to achieve this ?

**Comment by jondy** [comment]
If run an executable by a single click, there is no any command line arguments. In python scripts, sys.argv got nothing except the script name. 

`pyarmor pack` can build a single executable by this way
```
pyarmor pack -e " --onefile" foo.py
```

But you need build the corresponding executable for each platform,  it's impossible to build one works for 3 platforms.

**Comment by ptrivedi2610** [comment]
@jondy 
That means if my executable needs command-line arguments, its mandatory to run on command prompt and not on click. Is that right ?

**Comment by jondy** [comment]
Yes.
