### ISSUE TITLE
Someone could get all the strings of a Python application protected by PyArmor

### ISSUE THREAD

**Issue by eliost369** [dashingsoft/pyarmor#228]
Hello,

I was Googling around and found this https://forum.tuts4you.com/topic/41945-python-pyarmor-my-protector/?do=findComment&comment=203290

This guy showed all the steps to dump all the strings of a Pyarmor-protected application.

Can this be prevented?

**Comment by jondy** [comment]
Obfuscate the scripts with advanced mode to prevent this.

**Comment by jondy** [comment]
In latest version v6.1.0, it also could use this new feature [binding obfuscated scripts to Python interpreter](https://pyarmor.readthedocs.io/en/latest/advanced.html#binding-obfuscated-scripts-to-python-interpreter) to avoid this hole.

**Comment by e0lithic** [comment]
@jondy . Just out of curiosity, do we still need to bind the obfuscated scripts to the interpreter or advanced mode alone would suffice?

**Comment by jondy** [comment]
Advanced mode alone is suffice, and bind to the interpreter is more. Besides, some platforms don't support advanced mode now, the only way is bind the interpreter at this time.

**Comment by VeNoMouS** [comment]
In https://pyarmor.readthedocs.io/en/latest/mode.html?highlight=advanced%20mode it states `In next minor version, this mode may be enabled by default.` ... what version was that? do we need to enable this in 6.2.2?

**Comment by VeNoMouS** [comment]
> In latest version v6.1.0, it also could use this new feature [binding obfuscated scripts to Python interpreter](https://pyarmor.readthedocs.io/en/latest/advanced.html#binding-obfuscated-scripts-to-python-interpreter) to avoid this hole.

Please also refer #250

**Comment by jondy** [comment]
> In https://pyarmor.readthedocs.io/en/latest/mode.html?highlight=advanced%20mode
> 
> it states `In next minor version, this mode may be enabled by default.` ...
> 
> what version was that? how far back does this bypass go back to, with advanced mode 1 not enabled by default?

Because the advanced mode 1 only works for arch x86/x86_64, so I don't make it as default mode, otherwise all the other arches will not work.

**Comment by VeNoMouS** [comment]
Would `Super-Mode` stop this reverse engineering? 

I mean whats the safe option, advanced mode 1 or 2?

**Comment by jondy** [comment]
Yes, super mode could avoid this reverse engineering without fixed license, it's more safer. It's recommend to use super mode for Python2.7, 3.7 and 3.8. But you also can do fixed license with super mode.

**Comment by VeNoMouS** [comment]
orly? do you have the bind keys published for your fixed libraries? for super mode + fixed?

**Comment by jondy** [comment]
All of these features should work in the latest version 6.2.4.

However the fixed license doesn't work in 32-bit Windows, because the dynamic library isn't location independent. That is to say, the checksum of code segment may change if restart python.

**Comment by VeNoMouS** [comment]
Thanks for the heads up @jondy :)

**Comment by VeNoMouS** [comment]
@jondy is there any update on the supermode + fixed?

**Comment by jondy** [comment]
No. There is no significant changes on the super mode in recent weeks.
