### ISSUE TITLE
fatal error: zmq.h: No such file or directory

### ISSUE THREAD

**Issue by newbieh4cker** [dashingsoft/pyarmor#229]
OS : Ubuntu 18.04.4 LTS
Python : 3.5
PyArmor : 6.1.0 (registered version)

When I use `pack` command, below error occurs.
`~lib/python3.5/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:216:10: fatal error: zmq.h: No such file or directory`

**Comment by jondy** [comment]
Make sure the script could be packed by PyInstaller directly, for example
```
pyinstaller myscript.py
```
If not, check [PyInstaller usage](https://pyinstaller.readthedocs.io/en/stable/usage.html). Also check the package `zmq`, make sure it's ready for frozen.

If pyinstaller could pack `myscript.py`, then run `pack` command with `--debug`, for example
```
pyarmor pack --debug myscript.py
```

It will generated a .spec file `myscript-patched.spec` which could be used by pyinstaller to bundle the obfuscated script
```
pyinstaller -f --clean myscript-patched.spec
```

Compare this patched `.spec` with the original `myscript.spec`, change some options in the `myscript-patched.spec`. For example, `pack` command inserts an extra path like this
```
    pathex=[r"/path/to/obf"]+...
```
It may break some package to find the right file, try to move this path to the end, for example,
```
    pathex=... + [r"/path/to/obf"]
```

Then run 
```
pyinstaller -f --clean myscript-patched.spec
```
