### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by jackbayliss** [dashingsoft/pyarmor#230]
When trying to run an obfuscated script on a different machine i'm getting the following:
`[WinError 193] %1 is not a valid Win32 application`, all files have been copied across along with the pytransform folder.  Just wondering if it's perhaps missing some requirements.

See :

> [WinError 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "MissionChiefBot.py", line 2, in <module>
    pyarmor_runtime()
  File "C:\Users\caola\Desktop\Experimental 2 - Copy\pytransform__init.py", line 310, in pyarmor_runtime
    pyarmor_init(path, is_runtime=1, suffix=suffix)
  File "C:\Users\caola\Desktop\Experimental 2 - Copy\pytransform__init.py", line 305, in pyarmor_init
    _pytransform = _load_library(path, is_runtime, platid, suffix)
  File "C:\Users\caola\Desktop\Experimental 2 - Copy\pytransform__init.py", line 273, in _load_library
    m = cdll.LoadLibrary(filename)
  File "C:\Users\caola\AppData\Local\Programs\Python\Python38-32\lib\ctypes__init.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\caola\AppData\Local\Programs\Python\Python38-32\lib\ctypes__init.py", line 373, in init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application>

**Comment by jondy** [comment]
How about specify the platform name as obfuscating the scripts:
```
pyarmor obfuscate --platform windows.x86 foo.py
```

**Comment by jackbayliss** [comment]
Will give that a try! Thank you. 
Is there any way to automatically target each platform without specifying it? I.E one build for Linux & Win? I'll get back to you with the outcome of  ``--platform windows.x86``. 👍

**Comment by jondy** [comment]
Here describe how to [Running Obfuscated Scripts In Multiple Platforms](https://pyarmor.readthedocs.io/en/latest/advanced.html#running-obfuscated-scripts-in-multiple-platforms).

If you don't want type platforms in the command lines, just create project, then run `pyarmor build -B` to update your scripts.

**Comment by jackbayliss** [comment]
This has been fixed by running:
```
pyarmor obfuscate --platform windows.x86_64 \
                  --platform linux.x86_64 \
                  --platform darwin.x86_64 \
                  foo.py
```
For some reason I thought it would've been automatically done haha.

Thanks for the assistance.
