### ISSUE TITLE
ValueError: __mp_main__.__spec__

### ISSUE THREAD

**Issue by Rm1n90** [dashingsoft/pyarmor#232]
Hi @jondy, 

I've installed pyarmor and was able to obfuscate my scripts without any problem but when I'm trying to execute my obfuscate script I'm getting this error. Can you please help me to figure out the problem?

```
Traceback (most recent call last):
  File "C:\Users\anaconda3\lib\runpy.py", line 128, in _get_module_details
Process Process-1:
    spec = importlib.util.find_spec(mod_name)
  File "C:\Users\anaconda3\lib\importlib\util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: __mp_main__.__spec__ is None

Thanks,

**Comment by jondy** [comment]
Is there any extra error message to run the obfuscated scripts with option `-d`?
```
python -d dist/foo.py
```

**Comment by Rm1n90** [comment]
Hey @jondy, 
No, there is not any extra error message. Getting the same error after `python -d dist/foo.py`

This is how I obfuscated my scripts:  `pyarmor obfuscate --recursive xx.py`
```
INFO     PyArmor Trial Version 6.1.0
INFO     Source path is "xxxx "
INFO     Entry scripts are ['xxxx.py']
INFO     Use cached capsule C:\Users\xxx\.pyarmor_capsule.zip
INFO     Recursive mode is on
INFO     Auto exclude output path "dist"
no previously-included directories found matching 'dist'
INFO     Save obfuscated scripts to "dist"
INFO     Read public key from capsule
INFO     Obfuscate scripts with default mode
INFO     Advanced mode is 0
INFO     Restrict mode is 1
INFO            xx\xx.py -> dist\xx\xx.py
INFO            xx\xx.py -> dist\xx\xx.py
INFO            xx\xx.py -> dist\xx\xx.py
INFO            xx\xx.py -> dist\xx\xx.py
INFO            xx\xx.py -> dist\xx\xx.py
INFO            xx\xx.py -> dist\xx\xx.py
INFO            xx.py -> dist\xx.py
INFO     Patch this entry script with protection code
INFO     Use template: c:\users\xx\anaconda3\lib\site-packages\pyarmor\protect_code.pt
INFO     Insert bootstrap code to entry script dist\xx.py
INFO     7 scripts have been obfuscated
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Generate default license.lic
INFO     Copying c:\users\xx\anaconda3\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Generate runtime files OK
INFO     Obfuscate 7 scripts OK.

```

**Comment by jondy** [comment]
I build a temporary library for windows.x86_64 to fix this, download it from https://pyarmor.dashingsoft.com/download/temp/_pytransform.dll

Overwrite the old one which locates in the `/path/to/pyarmor/platforms/windows/x86_64/_pytransform.dll`

Then obfuscate the scripts again and run it.

**Comment by Rm1n90** [comment]
Hey @jondy, I cannot download the file 'Not Found'. Would you please upload it somewhere else?
I've tested my script without obfuscation and works fine.

Thanks!

**Comment by jondy** [comment]
Sorry, it misses one char, try this
https://pyarmor.dashingsoft.com/downloads/temp/_pytransform.dll

**Comment by Rm1n90** [comment]
Thanks, the obfuscated script is working now. Just one question how can I use `--recursive` for `pyarmor pack`?

**Comment by jondy** [comment]
Nice, this patch will be released with next version.

You don't need pass option `--recursive` to `pack , it's default. The other options may pass by `-x`, more usage about `pack`, refer to man page of [pack](https://pyarmor.readthedocs.io/en/latest/man.html#pack)
