### ISSUE TITLE
Multiple pyarmored packages conflicting

### ISSUE THREAD

**Issue by PidgeyBE** [dashingsoft/pyarmor#233]
Hi

I've been struggling the whole day with getting 2 code bases, which are both pyarmored, to work together.
Both repo's are using the same license. I've read https://pyarmor.readthedocs.io/en/latest/advanced.html#solve-conflicts-with-other-obfuscated-libraries and tried to apply the `--enable-suffix`. The error changes, but still the code does not work.
In both repositories we use:
* Pyarmor 6.1.0
* python 3.6.9

The first codebase uses `pyarmor init; config; build`, the second uses `pyarmor obfuscate`

The first codebase contains pyarmored python modules which use pyarmored python packages from the other repository.
If I don't use `--enable-suffix` or use `--enable-suffix` in both repositories, I get:
```
SystemError: ../Objects/dictobject.c:2483: bad argument to internal function
```

If I only use `--enable-suffix` in 1 place, I get (at a later time):
```
SystemError: unknown opcode
```

If 1 of both place is _not_ pyarmored, it works.
What can I do to make both pyarmored codebases to work together?

Best regards, Pieterjan

**Comment by jondy** [comment]
To figure out the problem, just create 2 simple package, both are obfuscated with `--enable-suffix`, test it work or not. If not, show the test scenario here, I'll check it.

If this works, make sure the real package is not mixed with some old obfuscated scripts.

**Comment by PidgeyBE** [comment]
I think it happens with inheritance.
So both packages are obfuscated with `--enable-suffix`. (If only one uses the suffix, the issue is not present)

So in the second package we do:
```
from first_package import TestA
class TestB(TestA):
    ...
```
`SystemError: /tmp/build/80754af9/python_1578429706181/work/Objects/dictobject.c:2483: bad argument to internal function`

does this make sense to you?

**Comment by jondy** [comment]
Try to use one same runtime packages. Although 2 packages are obfuscated with `--enable-suffix`, but the suffix should be same. So move the runtime package `pytransform_vax_xxxxxx` to any python path, and remove it from the obfuscated package. Does it work?

**Comment by PidgeyBE** [comment]
Indeed, the suffices are the same.
I've copied the runtime package from one place to the other, but the error remains the same...

**Comment by jondy** [comment]
What's the exact options to obfuscate scripts for 2 packages?

**Comment by PidgeyBE** [comment]
I've been testing whole day, I have stable setup now to test 100 cases.
I think the issue is in 1 place I use 
`--platform linux.x86_64 --platform linux.aarch64 --platform linux.ppc64` while in the other place I don't...
I'll try to verify

**Comment by PidgeyBE** [comment]
If I don't use `--platform linux.x86_64 --platform linux.aarch64 --platform linux.ppc64` in both places, it works. If I use it in one place or both places, it does not work!

**Comment by PidgeyBE** [comment]
The issue seems to be in the `--platform linux.ppc64`. Adding/using this one in one of the two sides makes it fail.

**Comment by PidgeyBE** [comment]
So to reproduce:

<details>
  <summary>testB/testB.py</summary>

```
class TestB():
    def __init__(self, x, y=300):
        self.x = x
        self.y = y
```

</details>

`pyarmor obfuscate testB.py --enable-suffix`


<details>
  <summary>testA/testA.py</summary>

```
from testB import TestB
class TestA(TestB):
    def __init__(self, x, y=300):
        super().__init__(x=x, y=y)
        print('ok')
```

</details>

`pyarmor obfuscate testA.py --enable-suffix --platform linux.x86_64 --platform linux.ppc64`

-> Copy `testB/testB.py` into `testA/dist`.
-> `python dist/testA.py`
-> returns either one of following errors, depending on where imports are done, or if a third script is used that imports TestA and creates an object TestA() etc...

```
SystemError: /tmp/build/80754af9/python_1578429706181/work/Objects/dictobject.c:2483: bad argument to internal function
SystemError: unknown opcode
```

**Comment by PidgeyBE** [comment]
I might have been wrong, because I was using a third package in my tests.
So I think there is no issue if the same platforms are used at all times... :/

**Comment by jondy** [comment]
Anyway cheers for the trouble gone, :)
