### ISSUE TITLE
Error after packaging

### ISSUE THREAD

**Issue by jakestrouse00** [dashingsoft/pyarmor#234]
I am getting this [error](https://gyazo.com/43996f736e9d5a8c1f6bd1da2faf240d) when trying to run my packaged script. To package my script, I used the command `pyarmor pack --name thetaTool  -e " --hidden-import comtypes -F "  theta.py` . My script uses Pyqt5. What does this issue mean?

**Comment by jondy** [comment]
Upgrade your pyinstaller version, I remember pyinstaller should fix this issue.
