### ISSUE TITLE
executing obfuscated file with different python version gives an error

### ISSUE THREAD

**Issue by AhsanSheraz** [dashingsoft/pyarmor#235]
pyarmor Version: 5.8.9
python Version: 3.5.2
OS: Ubuntu 16.04
compiling command: pyarmor obfuscate --exact install.py

i compile .py file in python version 3.5.2. And when i execute the obfuscated file with python version 3.6.9 on Ubuntu 18.04 it gives the following error:

XXX lineno: 1, opcode: 0
Traceback (most recent call last):
  File "<install.py>", line 3, in <module>
  File "<frozen install>", line 1, in <module>
SystemError: unknown opcode

**Comment by jondy** [comment]
That's expected behavior, refer to [Obfuscating Scripts By Other Python Version](https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-scripts-by-other-python-version)

**Comment by AhsanSheraz** [comment]
not that case i only want to ask if i obfuscate in python 3.5 on ubuntu 16.04, am i able to run run that obfuscated scripts on any other ubuntu version with any python version.

thanks

**Comment by AhsanSheraz** [comment]
in my case i want to run obfuscated files on different ubuntu(16,18,19,20) machines with their default python versions. 
is that possible?

**Comment by jondy** [comment]
The key point is that the major/minor version of Python in build machine should be same as in target machine. So if the default versions are same on different ubuntu machines, it's no problem. Otherwise you need obfuscate the scripts with the corresponding python versions.
