### ISSUE TITLE
Update lost code

### ISSUE THREAD

**Issue by charleywright** [dashingsoft/pyarmor#236]
I wrote a program a while ago, and compiled it with PyArmor and PyInstaller, then distributed it. Now I want to add a new feature, but I reset my PC and switched mainly to Linux. I no longer have the source code, although I have the obfuscated .py file. Is there any way I can add a new feature? Either by deobfuscating or appending to the end of the file? Any help would be greatly appreciated. Thank you.

**Comment by charleywright** [comment]
[discord_nitro.py.txt](https://github.com/dashingsoft/pyarmor/files/4623351/discord_nitro.py.txt)

**Comment by charleywright** [comment]
[program.py.txt](https://github.com/dashingsoft/pyarmor/files/4623359/program.py.txt)

**Comment by jondy** [comment]
Sorry, I have no ideas also.

**Comment by charleywright** [comment]
Is there no possible way to reverse it?

**Comment by jondy** [comment]
You may write a wrap script to import all the functions from this one. For example,
```
from your_program import *
...
```
