### ISSUE TITLE
PyArmor does not put bootstrapper into the entry script

### ISSUE THREAD

**Issue by the-vindicar** [dashingsoft/pyarmor#240]
I'm using the following command to launch pyarmor:
```
from pyarmor.pyarmor import main as call_pyarmor
call_pyarmor([
    'obfuscate',
    '--output', output_dir,
    '--bootstrap', '1',
    '--src', src_dir, 
    '--recursive',
    'main.py',
    ])
```
No matter what value I use for bootstrap parameter, obfuscated `main.py` immediately starts with `__pyarmor__(__name__, __file__, ...)` call, which understandably fails. 

`src_dir` is the absolute path to a dir that contains `main.py` and files referenced by it.
`output_dir` is an absolute path different from `src_dir`.
I'm using pyarmor 6.1 under python 3.8.2.

**Comment by jondy** [comment]
How about wrap the `src_dir` with `os.path.normpath(src_dir)`?
