### ISSUE TITLE
ERROR    No dynamic library found for windows.x86 with features [11]

### ISSUE THREAD

**Issue by Gagethe1** [dashingsoft/pyarmor#242]
I am using Super Mode and getting this error when running the command: pyarmor obfuscate --advanced 2 "My Script".py.

Logs: https://pastebin.com/5hTcsvHE

Many thanks,
Gage

**Comment by jondy** [comment]
In v6.2.0, only 64-bit windows are supported, the support for windows.x86 will be released in next version v6.2.1, it may be in a few of days.

**Comment by jondy** [comment]
Fixed v6.2.1
