### ISSUE TITLE
Can't pack a script with pyarmor

### ISSUE THREAD

**Issue by mevaere** [dashingsoft/pyarmor#246]
Here is my script :
`print("Hello World")`

Here is the command : 
> pyarmor pack loader2.py

but 

> ERROR    unknown encoding: iso-latin-1-unix
> INFO     ==================== End command ====================
> ERROR    Run command failed

You can see the all log [here https://justpaste.it/6lqgy](https://justpaste.it/6lqgy)

**Comment by mevaere** [comment]
Just after creating a new env with python 3.7
pip install pyinstaller
pip install pyarmor
pyarmor register pyarmor-regfile-1.zip
pyarmor pack loader2.py

which only contains print("Hello world")

**Comment by jondy** [comment]
How about adding one encoding line like this:
```
# -*- coding: utf-8 -*-
```

Refer to https://docs.python.org/2.7/tutorial/interpreter.html#source-code-encoding

**Comment by mevaere** [comment]
Exact same problem.
I add this to my hello world script
`# -*- coding: utf-8 -*-`

The problem occured only with pyinstaller

**Comment by jondy** [comment]
It's not your script problem, not to obfuscate the whole envs by this way:
```
pyarmor pack -x " --exclude envs" loaders.py
```

**Comment by mevaere** [comment]
Thanks it works.
