### ISSUE TITLE
how to create exe file without license?

### ISSUE THREAD

**Issue by boris8055** [dashingsoft/pyarmor#247]
i need to create exe file obsfuscate but without a license, that can be runned in every machine

**Comment by jondy** [comment]
You need do nothing,  the final exe could be run in any machine.

**Comment by boris8055** [comment]
give me this error : https://gyazo.com/f640df1753c043a2ea8d36281c80e6e2

**Comment by jondy** [comment]
It has the problem for windows 32-bit system.  Well, generating a common license file could fix this issue. For example

1. First generate a license file saved in the `mylicense/anywhere/license.lic` 
```
pyarmor licenses --output mylicense anywhere
```

2. Then create an exe with this license
```
pyarmor pack --with-license mylicense/anywhere/license.lic ...
```
