### ISSUE TITLE
Issue while packing with --onefile

### ISSUE THREAD

**Issue by FlorianREGAZ** [dashingsoft/pyarmor#248]
Hey, 

I want to pack my python script (with --onefile) but I'm always getting the following error:
![Screenshot_5](https://user-images.githubusercontent.com/54325655/83206404-21389280-a151-11ea-9b31-69a9b979a1a6.png)

and I was not able to solve it until now.
My programm is structured like this:
I got a main.py which imports and starts all scripts (nearly 50)

Hopefully someone can help

Best regards :)

**Comment by jondy** [comment]
Do not obfuscate the scripts in the path `venv`, exclude this path by this way:
```
pyarmor pack -x " --exclude venv" -e " --onefile" main.py
```

By default, all the `.py` files in the same path of the main script will be obfuscated recursively, so all the python system library in the path `venv` are obfuscated. Generally it's not necessary.

**Comment by FlorianREGAZ** [comment]
> Do not obfuscate the scripts in the path `venv`, exclude this path by this way:
> 
> ```
> pyarmor pack -x " --exclude venv" -e " --onefile" main.py
> ```
> 
> By default, all the `.py` files in the same path of the main script will be obfuscated recursively, so all the python system library in the path `venv` are obfuscated. Generally it's not necessary.

Thanks, that solved the problem! :)

**Comment by FlorianREGAZ** [comment]
Hey, I don't know if I can write into the same issue again, but it worked for me and now some hours later (didnt do anything) I'm getting this:
![Screenshot_7](https://user-images.githubusercontent.com/54325655/83326047-41f80980-a271-11ea-97d1-ae381371eb77.png)

hope you can help me again!

**Comment by jondy** [comment]
Refer to #247 to create a separated license file

**Comment by FlorianREGAZ** [comment]
> Refer to #247 to create a separated license file

Thanks again, helped again & works! :)
