### ISSUE TITLE
Error with binding encrypted script to one machine

### ISSUE THREAD

**Issue by gingerhead22** [dashingsoft/pyarmor#25]
Hi all, 
I was following the webapp tutorial and got the error "Invalid trial license file, size is 208 != 256" after replacing the license.lic with the one generated by hard disk serial number.

Any idea why this happened? (The hard disk serial number is correct). Does it have anything to do the number of digits of the serial number? I found the number in the tutorial has 20 digits, but mine has only 15 digits
I am running the code on Ubuntu 16.04 and python3..5.2.

Thank you very much

Yifan

**Comment by jondy** [comment]
It should be not the problem of hard disk serial number. 
First to be sure it's the right "license.lic" to be replaced:
Only replace one “license.lic" in the output path "dist" ( by default ) with the new one. Do not replace any others.

**Comment by jondy** [comment]
There is an issue in webui, I have fixed and release a new version 3.9.6
To get the correct serial number of harddisk, run the following command in pyarmor path
`python pyarmor.py hdinfo`
