### ISSUE TITLE
Windows7下运行加密后文件产生的问题

### ISSUE THREAD

**Issue by geekgao** [dashingsoft/pyarmor#252]
06\x0d\x2e\x62\xac\x00\x19\xc4\xfb\x96\x07\xaa\x0f\xc6\x52\xd3\x39\x75\x50\xc0\
7a\x54\x86\x63\xc1\x13\x26\xfb\x28\xcb\x5f\x9f\xb4\xb8\x51\x10\x33\xf8\xbd\x69\
11\x95\xdd\x2d\x74\x0d\x06\x4b\xda\xbb\x76\x42\x19\x77\x5d\xef\x49\xb2\xe6\x7d\
be\xdc\x0e\x1d\x01\x70\xa0\xd7\x52\xab\x0b\x15\x61\xe0\xab\x9b\x41\xce\x09\x45\
c5\x7b\x99\x39\x80\xb7\x28\xa3\x87\xff\x69\x2c\xff\xd1\x3c\x19\x7a\x55\xbb\x47\
e0\x78\x71\x23\x0c\x0b\xd0\x0a\x7c\x11\x96\x21\x5a\xbf\xc9\xfb\x39\x86\xab\xb3\
60\x72\xe2\xda\x6a\x67\x7c\x6a\x58\x38\x17\xcb\x3d\x37\xdb\x12\x1f\x29\xff', 1)
NameError: name '__pyarmor__' is not defined

**Comment by jondy** [comment]
引导代码运行了吗？参考 https://pyarmor.readthedocs.io/zh/latest/understand-obfuscated-scripts.html#id8

**Comment by geekgao** [comment]
加了，然后报错：
RuntimeError: Check restrict mode of module failed

**Comment by jondy** [comment]
引导代码是不能自己添加的，必须在加密的时候指定主脚本，引导代码会自动添加到主脚本里面的。可以参考命令[obfuscate](https://pyarmor.readthedocs.io/zh/latest/man.html#obfuscate)的手册

**Comment by geekgao** [comment]
非常感谢。
