### ISSUE TITLE
How to check which license was used to obfuscate package

### ISSUE THREAD

**Issue by mauvilsa** [dashingsoft/pyarmor#254]
Assume that I have obfuscated a package by running `pyarmor obfuscate -r -O abc_obfuscated abc/__init__.py`. After obfuscation in the output there would be a bunch of `*.py` files and a `pytransform` directory. If someone gives me a directory like `abc_obfuscated`, is there any way to check which (purchased) key was used to obfuscate it? Is there a way to see more information about this obfuscated package, like when it expires?

**Comment by jondy** [comment]
> is there any way to check which (purchased) key was used to obfuscate it? 

The `license.lic` includes the purchased key, for example, `pyarmor-vax-000001`, it could be got by unpublished functions. It's signed by RAS private key, others could not generate `license.lic` for the scripts which are obfuscated by the purchased pyarmor.

> Is there a way to see more information about this obfuscated package, like when it expires?

Yes, the license information could be got from the obfuscated scripts
```
from pytransform import get_license_info
print(get_license_info())
```

Or out of the obfuscated scripts, run the following python code in the path of `license.lic`
```
from pytransform import pyarmor_init, get_license_info
pyarmor_init()
print(get_license_info())
```

**Comment by mauvilsa** [comment]
@jondy thank you very much for the fast reply. From your feedback I can now see that if I run `cat license.lic | base64 -d | less` I do see the a transformed version of the purchased key, showing something like `<*VERSION:pyarmor-vax-sn-1.txt-000001.1...`. If I do the same for a package obfuscated using the pyarmor trial instead, the output starts with `$*VERSION:trial.1`. Is there a better way to show this information than the command that I used?

I think that it would nice new feature to have one more subcommand in the pyarmor tool to print this information from the command line. Something like `pyarmor obfuscated-info path/to/obfuscated/dir` which would print something like
```
License info:
  EXPIRED=None
  HARDDISK=None
  IFMAC=None
  IFIPV4=None
  DOMAIN=None
  DATA=None
  CODE=PyArmor-Project
Obfuscated using:
  Key=pyarmor-vax-000001
```
The format could be different, and probably there could be more information that could be included. The main point is to have a tool to easily get information about obfuscated files.

**Comment by jondy** [comment]
In the latest version 6.2.5, a new key `ISSUER` is added to the result of `get_license_info`, which includes the purchased key. 

So just create a script named `obf-info.py` like this

```python
from pytransform import pyarmor_init, get_license_info
pyarmor_init(is_runtime=1)

print('License information:')
for k, v in get_license_info().items():
  print('%-10s: %s' % (k, '' if v is None else v))
```

And run it in any obfuscated package, it will print all the license information, include the issuer id of this license.

I had thought it's not the function used frequently, so did not implement it in the cli of pyarmor.

**Comment by mauvilsa** [comment]
I have just installed version 6.2.5 and ran
```
from pytransform import pyarmor_init, get_license_info
pyarmor_init(is_runtime=1)
print(get_license_info())
```
It printed `{'EXPIRED': None, 'HARDDISK': None, 'IFMAC': None, 'IFIPV4': None, 'DOMAIN': None, 'DATA': None, 'CODE': 'PyArmor-Project'}`, not including ISSUER.

**Comment by jondy** [comment]
I think this package is obfuscated by old version of pyarmor.  It need to copy `pytransform.py` of the latest version pyarmor to this obfuscated package either. Generally there is a runtime package `pytransform` in the obfuscated package, copy `pytransform.py` and `obf-info.py` to this path, and run `off-info.py` in this path.

**Comment by mauvilsa** [comment]
After obfuscating the package with the new version the get_license_info no does have the ISSUER. Thank you!
