### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HideakiAtsuyo** [dashingsoft/pyarmor#255]
Windows 10 Pro

py -3.8 setup.py install

pyarmor pack -e script.py
=>

`C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pyarmor-6.2.6-py3.8.egg\\pyarmor\\platforms\\index.json`

platforms doesn't exist

**Comment by jondy** [comment]
It's better to install pyarmor by pip, or get the `index.json` from 
https://github.com/dashingsoft/pyarmor-core/raw/master/platforms/index.json

**Comment by HideakiAtsuyo** [comment]
Thanks resolved !
