### ISSUE TITLE
Super-Mode - Darwin

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#256]
One of my users is getting the following error, it appears its trying to look for a static path of the python library

```
Traceback (most recent call last):
  File "/Users/matt/Downloads/helheim-0.1.2-py38.darwin.x86_64/inject-example.py", line 3, in <module>
    from helheim import helheim
  File "/Users/matt/Downloads/helheim-0.1.2-py38.darwin.x86_64/helheim/init.py", line 2, in <module>
    from .pytransform import pyarmor
ImportError: dlopen(/Users/matt/Downloads/helheim-0.1.2-py38.darwin.x86_64/helheim/pytransform.cpython-38-darwin.so, 2): Library not loaded: /Users/jondy/workspace/pytransform/python/lib/libpython3.8.dylib
  Referenced from: /Users/matt/Downloads/helheim-0.1.2-py38.darwin.x86_64/helheim/pytransform.cpython-38-darwin.so
  Reason: image not found
```

**Comment by jondy** [comment]
Does this users use static python library? Super mode may work only with dynamic python library.

**Comment by VeNoMouS** [comment]
I think hes using standard osx python, is there a different package?

```
ImportError: dlopen(/Users/matt/Downloads/helheim-0.1.2-py38.darwin.x86_64/helheim/pytransform.cpython-38-darwin.so, 2): Library not loaded: /Users/jondy/workspace/pytransform/python/lib/libpython3.8.dylib
```

thats your home dir... just saying..

**Comment by jondy** [comment]
Well, I rebuild this library now it's linked to system library, download it from [here](https://pyarmor.dashingsoft.com/downloads/temp/pytransform.cpython-38-darwin.so)

Move it to `~/.pyarmor/platforms/darwin/x86_64/11/py38/`, overwrite the old one.

Then obfuscate the scripts again.

**Comment by VeNoMouS** [comment]
Thanks, once user wakes up ill get him to test

thanks for the awesome turn around time @jondy

**Comment by VeNoMouS** [comment]
@jondy upgrade to 6.2.7 and got another osx user having issues..

```
Traceback (most recent call last):
  File "inject-example.py", line 3, in <module>
    from helheim import helheim
  File "/Users/reformedot/Documents/helheim/helheim/__init__.py", line 2, in <module>
    from .pytransform import pyarmor
ImportError: dlopen(/Users/reformedot/Documents/helheim/helheim/pytransform.cpython-37m-darwin.so, 2): Library not loaded: @rpath/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Users/reformedot/Documents/helheim/helheim/pytransform.cpython-37m-darwin.so
  Reason: image not found```

**Comment by VeNoMouS** [comment]
fwiw, the original user on py3.8 is working ok

do you have to fix the py3.7 as well?

**Comment by jondy** [comment]
What's the output of this command in this machine?
```
python3.7-config --ldflags
```
It will print where the python3.7 installed. If it's installed in the `/System/Library` or `/Library`, it should work. But for the following example
```
-L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin
```
It need add extra runtime path by this command
```
install_name_tool -add_rpath /usr/local/opt/python pytransform.cpython-37m-darwin.so
```

**Comment by VeNoMouS** [comment]
Cheers @jondy , adapted it to his system and working

**Comment by RobinFrcd** [comment]
Hi, I've just got the same issue on macOS 11.6 (20G165) after an update.

```
ImportError: dlopen(.../pytransform/darwin_x86_64/pytransform.so, 2): Library not loaded: @rpath/Frameworks/Python.framework/Versions/3.7/Python
    Referenced from: .../pytransform/darwin_x86_64/pytransform.so
    Reason: image not found
```

I'm using pyenv and running `python3.7-config --ldflags` returns `-lpython3.7m -lintl -ldl -framework CoreFoundation`. Runnning `install_name_tool` didn't solve the issue. We have the same issue with all the recently updated macs in our company. Is this a known bug ?

Thanks !

**Comment by jondy** [comment]
If you have set `rpath` to `XXX` by `install_name_tool`, make sure `XXX/Frameworks/Python.framework/Versions/3.7/Python` exists.

It should be work if `rpath` is right and Python3.7 isn't built with only static library.

**Comment by RobinFrcd** [comment]
Oh, I guess I misunderstood how rpath works, thanks ! ([rpath-what](https://blog.krzyzanowskim.com/2018/12/05/rpath-what/) can help if you guys are not familiar with it).

So I just re-obfuscated my package with Python 3.7.12. I've installed Python@3.7 from Homebrew (which currently installs python 3.7.12):

I've run:

`install_name_tool -add_rpath /usr/local/Cellar/python@3.7/3.7.12/ pytransform.so`

So `otool -l pytransform.so` returns
```
cmd LC_RPATH
      cmdsize 56
         path /usr/local/Cellar/python@3.7/3.7.12/ (offset 12)
```

But now I get a segfault when running `import pytransform`. I've checked [the doc](https://pyarmor.readthedocs.io/en/latest/questions.html#segment-fault) but it doesn't seem to help here.

**Comment by jondy** [comment]
If there are many python3.7 in this machine, first make sure `rpath` is set to same one.
Second, make sure this Python is built with `--enable-shared`.

**Comment by RobinFrcd** [comment]
Oh, it's not the same python because I'm using pyenv to manage my virtualenvs, but these envs don't have a `Frameworks/Python.framework/Versions/3.7/Python` folder. That's why I had to install another one with `brew` just to get a Python with this folder.
So there's no solution right now if using pyenv ?

And yes, I'm using `PYTHON_CONFIGURE_OPTS="--enable-shared"` when building my env with pyenv.

**Comment by jondy** [comment]
Only if `pytransform.so` load the same python dynamic library used by Python interpreter to run the obfuscated scripts, it should work. `install_name_tool` could do more, not only add a path, but also set the full path dependencies directly, refer to this command
```bash
install_name_tool -change \
                  /System/Library/Frameworks/Python.framework/Versions/2.7/Python \
                  @rpath/Frameworks/Python.framework/Versions/2.7/Python \
                  -add_rpath @loader_path/.. -add_rpath /System/Library -add_rpath /Library \
                  -id pytransform.so \
                  $PLATFORM/darwin.x86_64.11.py27/pytransform.so
```

**Comment by jondy** [comment]
Only if `pytransform.so` load the same python dynamic library used by Python interpreter to run the obfuscated scripts, it should work. `install_name_tool` could do more, not only add rpath, but also set the full path dependencies directly, refer to this command
```bash
install_name_tool -change \
                  /System/Library/Frameworks/Python.framework/Versions/2.7/Python \
                  @rpath/Frameworks/Python.framework/Versions/2.7/Python \
                  -add_rpath @loader_path/.. -add_rpath /System/Library -add_rpath /Library \
                  -id pytransform.so \
                  $PLATFORM/darwin.x86_64.11.py27/pytransform.so
```

**Comment by jondy** [comment]
Only if `pytransform.so` load the same python dynamic library used by Python interpreter to run the obfuscated scripts, it should work. `install_name_tool` could do more, not only add rpath, but also set the full path dependencies directly, refer to this command
```bash
install_name_tool -change \
                  /System/Library/Frameworks/Python.framework/Versions/2.7/Python \
                  @rpath/Frameworks/Python.framework/Versions/2.7/Python \
                  -add_rpath @loader_path/.. -add_rpath /System/Library -add_rpath /Library \
                  -id pytransform.so \
                  $PLATFORM/darwin.x86_64.11.py27/pytransform.so
```
