### ISSUE TITLE
--noconsole argument

### ISSUE THREAD

**Issue by VedantBhalgama** [dashingsoft/pyarmor#257]
Is the Pyarmor having argument like the Pyinstaller has?
Because I have created my Python script which also needs to be obfuscated and packed into exe and also need to be noconsole.

Is there anythong like that?

**Comment by jondy** [comment]
Most of Pyinstaller arguments could be passed to `pack` command by `-e`, for example,
```
pyarmor pack -e " --noconsole" foo.py
```
Refer to man [pack](https://pyarmor.readthedocs.io/en/latest/man.html#pack)

**Comment by VedantBhalgama** [comment]
but what if i even wan t to add the --onefile argument?

**Comment by jondy** [comment]
Just do it.

**Comment by VedantBhalgama** [comment]
means can it work like this

pyarmor pack -e " --noconsole" " --onefile" foo.py

**Comment by jondy** [comment]
Like this instead:
```
pyarmor pack -e " --noconsole --onefile" foo.py
```

**Comment by VedantBhalgama** [comment]
Thank You So much for your help sir!
