### ISSUE TITLE
pyarmor not found

### ISSUE THREAD

**Issue by hghimanshu** [dashingsoft/pyarmor#258]
Just installed pyarmor on my machine, but while hitting "**pyarmor**" on the terminal gives me this error
"**pyarmor: not found**"

**Comment by jondy** [comment]
pyarmor is a command line tool, if you prefer to Gui, install pyarmor-webui
```
pip install pyarmor-webui
```
Then double click `pyarmor-webui`

**Comment by hghimanshu** [comment]
well, thanks was able to solved the issue. There was some python version conflict. Anyway thanks for your response :smile: 
Closing this issue now.
