### ISSUE TITLE
Icons are not visable after pack

### ISSUE THREAD

**Issue by jaylopez1045** [dashingsoft/pyarmor#260]
I recently purchased the enterprise version of your app.

When I run the pack wizard build it completes successfully but when the package is ran, the png files in the project are not visible. I have a project ready for release and this is holding up my entire project.

The png files are in the root of folder along with my entry script. When I run the python3 entry script after obfuscate it does work correctly and the png files are visible. Its only when I try to pack the script.

**Comment by jondy** [comment]
Do you add this png file to the final bundle by `--add-data`, for example,
```
pyarmor pack -e " --add-data x.png:." foo.py
```

More usage of pack, refer to
https://pyarmor.readthedocs.io/en/latest/man.html#pack

**Comment by jaylopez1045** [comment]
Yes I have done it via the command line as well as the webui. In both cases it doesn’t show when I double click the package. Although, when I run it simple via the python3 entry.py.. it works.

Also, via the web when you click no console, it still bring up a terminal window. Regardless of the slider position. It still presents the terminal window.

**Comment by jondy** [comment]
How do you reference this image file in your script?  When run the final exe file, this image file will be extract a temporary path which could be got by [`sys._MEIPASS`](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html), it may not in the current path. 

I'll check no console option in the webui.

**Comment by jondy** [comment]
About no console option doesn't work, try to remove the cache path `build` in the current path, which is created by pyinstaller as default work path.
