### ISSUE TITLE
Not Obfuscating correctly ?(problem with encode('utf8') function?)

### ISSUE THREAD

**Issue by 1day2die** [dashingsoft/pyarmor#261]
Hello Everyone,

i have serval scripts in my working folder which all work together.
I try to obfuscate them using pyarmor-webui and select them all using the "Only obfuscate the scripts in the list" option.

they all do get obfuscated, however my programm only seems to run to a certain point, which is this line 

`	with urllib.request.urlopen(VERSIONCHECK_WEBSITELINK + "/version.txt") as response:`
`		version = response.read().decode('utf-8')`

then it crashes.

When examining the obfuscated code i realised something.
![image](https://user-images.githubusercontent.com/8725848/84891838-d0a3bd80-b09c-11ea-8cca-8f470cd470d5.png)

![image](https://user-images.githubusercontent.com/8725848/84891879-e31df700-b09c-11ea-8909-674c02f29bbd.png)

Using sublime-text3.

First Picture is a simple GUI with a button. Works perfectly well when executed. Mind the coloured Syntax.

Second Picture is one of my actual important Scripts, including more code and the line i mentioned earlier. Mind the Non-Colored Syntax.

Its weird, that some Scripts do work and others dont, eventhough i obfuscated them all in one go.
I hope i was able to make my problem clear and would be glad to receive some help.

Thanks guys!

**Comment by jondy** [comment]
How about running the obfuscated scripts with `-d`, it will print extra error message, for example
```
python -d dist/foo.py
```

**Comment by 1day2die** [comment]
Weird. Unobfuscated my Programmruns smoothly.
Obfuscated it throws this error and exits

`Traceback (most recent call last):`
`  File "<gui_client.py>", line 3, in <module>`
`  File "<frozen gui_client>", line 282, in <module>`
`  File "<frozen gui_client>", line 74, in updatePics`
`  File "<frozen cl_errorhandler>", line 42, in errorhandler`
`AttributeError: 'NoneType' object has no attribute '__file__'`

However it seems to be a problem with the way i wrote my scripts.

pytransform.log
`The core library version: r24, age: 18, features: 7`


Guess ill have to be more carefull and rewrite some parts for pyarmor to work on my program

**Comment by jondy** [comment]
Yes, check line 42 in the script `cl_errorhandler.py` to find the problem.
