### ISSUE TITLE
Authorization can be hacked by Docker?

### ISSUE THREAD

**Issue by o0fatigue** [dashingsoft/pyarmor#263]
My use case is as below:
1. User **A** (non-trial user) obfuscated a project with private license
1. **A** sent the obfuscated project to one's customer (**B**)
1. **B** deployed the obfuscated project on one's machine (**C**)
1. **B** sent the mac address of **C** to **A** and asked for license
1. **A** generated a license (mac address bind) and sent it to **B**
1. **B** can successfully run the project on **C**

However, in my understanding, if **B** use Docker by specifying a runtime mac address (same as **C**), **B** is able to run **A**'s project on  any other machines, with only one license. Any solutions for this situation?

**Comment by jondy** [comment]
One solution is to bind license to hard disk, the other way is to extend the license by plugin to check the extra information.

**Comment by o0fatigue** [comment]
Thank you for your reply. I tried hard disk binding, `pyarmor hdinfo` failed to get hard disk information on my linux machines (ubuntu18.04).

**Comment by o0fatigue** [comment]
FYI: #31 binary with sudo did give the information.
