### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#266]
@jondy is it possible to load the license.lic via a string at all? or a io stream?

The reason i ask, what if one dev wants to pyarmor their code, but also include code by another dev's pyarmor... it exposes the license.lic since you have to --add-data and that adds it to a temp dir

**Comment by VeNoMouS** [comment]
or cffi? ... or something? ;P

**Comment by jondy** [comment]
In the super mode, the `license.lic` has been embedded to binary library by default, and in the next version, the other modes would be this.

To solve this conflicts, pyarmor provides an option `--enable-suffix`, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#solve-conflicts-with-other-obfuscated-libraries

**Comment by VeNoMouS** [comment]
it's not embbed if its set to `outer` though is it?

**Comment by VeNoMouS** [comment]
it's ok, i'll change my licensing model...

one last question, i noticed your using 3DES + ECB, doesnt this make for a bit of predictability if a 3rd party managed to some how generate enough licenses, since 3DES + ECB  is predictable by nature?

**Comment by jondy** [comment]
> it's not embbed if its set to `outer` though is it?

No. It's not embed if set license to `outer`

> one last question, i noticed your using 3DES + ECB, doesnt this make for a bit of predictability if a 3rd party managed to some how generate enough licenses, since ECB is predictable by nature?

The license is signed by RSA private key, it's stored in the private capsule, so others couldn't sign your licenses. 3DES is mainly used to obfuscate the byte code.

**Comment by VeNoMouS** [comment]
Time to upgrade to AES-GCM / xchacha-poly? ;P at least you got a tag that you verify agaist.

**Comment by jondy** [comment]
I'll check it.

**Comment by VeNoMouS** [comment]
❤️ , thanks for the info anyway @jondy have a good day / night
