### ISSUE TITLE
multiple mac address

### ISSUE THREAD

**Issue by Rani-1234** [dashingsoft/pyarmor#267]
Hi,

**We have purchased your software,and we need to bind the lic to mac address,
or other specific HW.**

Platform: NVIDIA jetson TX2,  ubuntu 18.04

**pyarmor hdinfo output:**
Faild to get harddisk information.
Mac address: "32:8f:2b:d3:a3:83"
Faild to get ip address.

**ifconfig -a command output:**

dummy0: flags=130<BROADCAST,NOARP>  mtu 1500
        ether 32:8f:2b:d3:a3:83  txqueuelen 1000  (Ethernet)

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 00:04:4b:8c:f7:18  txqueuelen 1000  (Ethernet)

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0

wlan0: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether 00:04:4b:8c:f7:16  txqueuelen 1000  (Ethernet)

1.Pyarmor hdinfo - recognizes only dummmy0 , and not eth0 ( the real network card,which we need)

2.Pyarmor hdinfo - doesn't recognizes , the HDD ( there isn't HDD ... ,only 32 GB eMMC)

It would be nice if you can have a quick fix hdinfo will recognize all available network adapters macs.

Any other suggestions ?

Thanks

**Comment by jondy** [comment]
Please refer to this plugin to check multiple mac address
https://github.com/dashingsoft/pyarmor/tree/master/plugins#example-1-check-all-the-mac-address

It could be extended to check any other machine information.

About the eMMC, pyarmor could recognize NVME interface. Others may not work,  BTW it need root privilege to get HDD serial number
