### ISSUE TITLE
[Query] Pytransform module not found for plugins.

### ISSUE THREAD

**Issue by e0lithic** [dashingsoft/pyarmor#268]
Hi, 
I am using the following [guide](https://pyarmor.readthedocs.io/en/latest/advanced.html?highlight=internet#using-plugin-to-extend-license-type) for using internet time for license check.If the plugins is not injected everything works fine. However as soon as the plugin is injected I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "</mnt/Data/Workspace/src_misc/xyz/src/dist/__init__.py>", line 3, in <module>
  File "<frozen src>", line 484, in <module>
  File "<frozen src>", line 477, in check_ntp_time
  File "<frozen src>", line 468, in _get_license_data
ModuleNotFoundError: No module named 'pytransform
```
I used the following commands for obfuscation
```
pyarmor obfuscate --exact __init__.py --plugin ~/.pyarmor/plugins/check_ntp_time
pyarmor obfuscate --restrict 4 --recursive --exclude __init__.py .
```
Please let me know where I am going wrong.

Thanks

**Comment by jondy** [comment]
How about changing the plugin script by relative import? For example
`from .pytransform import`

**Comment by e0lithic** [comment]
Sorry for the delayed response, that worked our flawlessly.

**Comment by e0lithic** [comment]
It seems that I had some errors previously. When I used the relative import the value in the `EXPIRED_DATA` variable seems to be 
```
*VERSION:pyarmor-vax-000270.1
PyArmor-Project*
```
instead of the data in the check_ntp_time.py function. Could you please let me know where I am going wrong?

**Comment by jondy** [comment]
This license code is default license which is generated by pyarmor if there is no license specified. 
So there is no license with customized data within obfuscated scripts, or it doesn't take effects.

**Comment by e0lithic** [comment]
However, following your guide I had used the following two commands to generate the customized data as well.
```
pyarmor licenses -x 20200701 rcode-001
cp licenses/rcode-001/license.lic dist/
```

Are there any additional steps required?

**Comment by jondy** [comment]
Since v6.3.0, the runtime file license.lic has been embeded to dynamic library. If you prefer to use outer license.lic, so it can be replaced with the others easily, just set option --with-license to special value `outer`, for example:
```
pyarmor obfuscate --with-license outer foo.py
```
Refer to https://pyarmor.readthedocs.io/en/latest/advanced.html#how-to-use-outer-license-file

**Comment by e0lithic** [comment]
Still not working for me. I updated to the latest version of Pyarmor : 6.3.2.Here are the steps for reproduction.

The commands used for obfucation : 
```
# Internet time check license # %y%m%d
pyarmor licenses -x 20200701 rcode-001

# Obfuscate
pyarmor obfuscate --exact __init__.py --wrap-mode 1 --advanced 1 --obf-code 2  --plugin ~/.pyarmor/plugins/check_ntp_time --with-license licenses/rcode-001/license.lic
pyarmor obfuscate --restrict 4 --recursive --exclude __init__.py --wrap-mode 1 --advanced 1 --obf-code 2  .
```

I have used this [check_ntp_time.py](https://github.com/dashingsoft/pyarmor/blob/master/plugins/check_ntp_time.py). The only modification are the following.
Line 463
`from .pytransform import _pytransform`
Line 472
`print(EXPIRED_DATE)`

The output I am getting on running the obfuscated library  : 
```
*VERSION:pyarmor-vax-000270.1
PyArmor-Project
Traceback (most recent call last):
  File "example_image.py", line 3, in <module>
    from footDet import detect_foot
  File "</mnt/xyzt/__init__.py>", line 3, in <module>
  File "<frozen src>", line 489, in <module>
  File "<frozen src>", line 483, in check_ntp_time
  File "/home/xyz/.pyenv/versions/3.7.7/lib/python3.7/_strptime.py", line 571, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/home/xyz/.pyenv/versions/3.7.7/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '*VERSION:pyarmor-vax-000270.1\nPyArmor-Project' does not match format '%Y%m%d'
```

**Comment by jondy** [comment]
The second `obfuscate` command will generate new runtime files, please set option `--no-runtime` in the second `obfuscate`, or move the option `--with-license` here, instead of the first `obfuscate`.

**Comment by e0lithic** [comment]
That fixed it. Thanks a lot.
