### ISSUE TITLE
Custom Expiration Message

### ISSUE THREAD

**Issue by pillows** [dashingsoft/pyarmor#269]
Hi there,

I was trying to compile and install PyArmor so that it can include a custom error message. I am trying to change the expiration message in `plugins/check_ntp_time.py` to something other than "License is expired". This is what I currently have for check_ntp_time() which I believe is responsible for checking whether the obfuscated has an expired license or not:
```python
def check_ntp_time(NTP_SERVER='europe.pool.ntp.org'):
    EXPIRED_DATE = _get_license_data()
    c = NTPClient()
    response = c.request(NTP_SERVER, version=3)
    if response.tx_time > time.mktime(time.strptime(EXPIRED_DATE, '%Y%m%d')):
        raise RuntimeError('sdfsfsfsfdsfsf License is expired sdffsdf')
```
 When I do `sudo pip3 install .` it will install successfully but, will not reflect the change to the error message: https://i.imgur.com/b7jN3L8.png If you can't see the image, it just shows that the error message is still "License is expired" after my modification. 

Thank you for your help! I've been trying to figure this out for at least 12 hours now :(

**Comment by jondy** [comment]
Make sure the license is generated with option `-x` to set expired date, not `-e`.
If the expired date is set by `-e`, it will be checked by dynamic library `_pytransform.so` and quit directly if it's expired.

**Comment by pillows** [comment]
I think that I may be misunderstood here. I'm not looking to add data to the license but I would like to modify the Runtime Error message if the script is run after the expiration date. (Not limited to expiration but IP and hardware as well)

In the image I provided at the op I wanted the error message to print `sdfsfsfsfdsfsf License is expired sdffsdf` but instead it still gave me the default message of `License is expired`. I was trying to do this by modifying the cloned source code and installing a modified build this way.

**Comment by jondy** [comment]
The problem is that the obfuscated scripts doesn't run.

And you could copy the default plugin script to `~/.pyarmor/plugins/check_ntp_time.py` and edit it here,  it will be used first.

PyArmor searches plug script by this way:

- If the plugin has absolute path, then find the corresponding .py file exactly.
- If it has relative path, search the .py file in:
     - The current path
     - $HOME/.pyarmor/plugins
     - {pyarmor_folder}/plugins
- Raise exception if not found
