### ISSUE TITLE
OSError: exception: access violation reading

### ISSUE THREAD

**Issue by leah-l** [dashingsoft/pyarmor#27]
hi,
I check pyarmor on 2 different computers both windows 10 , 3 different framework - python 3.5, 3.6 and annaconda .
in all of them i get this error:  **OSError: exception: access violation reading XXXX**

someone have idea why?
thank you

**Comment by jondy** [comment]
I need check this, because pyarmor is tested in windows 7.  

Could you show me the log file? First enable log file by uncommenting line 218 in file `pytransform.py` 
```
    m.set_option('enable_trace_log'.encode(), c_char_p(1))
```
Then run pyarmor. 
After that, `_pytransform.log` is generated in the current path.

**Comment by jondy** [comment]
Maybe it's the reason
https://github.com/python/cpython/commit/2f3ba27185a369bcb6b36b13aa3518ffcc970ffa

It seems something is wrong to load dynamic library `_pytransform.dll`, refer to
https://github.com/python/cpython/blob/3.6/Doc/library/ctypes.rst#calling-functions

**Comment by leah-l** [comment]
i will check your suggestion, meanwhile

i uncomment line 216 (there is reason why is not 218?)
![image](https://user-images.githubusercontent.com/33288290/43570466-1628425c-9643-11e8-9034-7eb8df24b86a.png)
and i did not get a log file i have no idea why.

but this what i get running in powershell:

PS <HOME>\Documents\for_exe\pythondev> pyarmor obfuscate --src . --entry .\main.py
INFO     Obfuscate scripts in path "." ...
INFO     Use cached capsule .\.pyarmor_capsule.zip
INFO     Obfuscate scripts with mode 8
INFO     Save obfuscated scripts to "dist"
INFO            .\filename.py -> dist\filename.py
INFO            .\filename.py -> dist\filename.py
INFO            .\__init__.py -> dist\__init__.py
INFO            .\filename.py -> dist\filename.py
INFO            .\main.py -> dist\main.py
INFO            .\filename.py -> dist\filename.py
INFO            .\filename.py -> dist\filename.py
INFO            .\filename.py -> dist\filename.py
INFO            .\filename.py -> dist\filename.py
ERROR    exception: access violation reading 0x0000019B00000000
Traceback (most recent call last):
  File "<HOME>\appdata\local\programs\python\python36\lib\site-packages\pyarmor\pyarmor2.py", line 56, in wrap
    return func(*args, **kwargs)
  File "<HOME>\appdata\local\programs\python\python36\lib\site-packages\pyarmor\pyarmor2.py", line 424, in _obfuscate
    obfuscate_scripts(filepairs, mode, capsule, output)
  File "<HOME>\appdata\local\programs\python\python36\lib\site-packages\pyarmor\utils.py", line 132, in obfuscate_scripts
    pytransform.encrypt_project_files(prokey, tuple(filepairs), mode)
  File "<HOME>\appdata\local\programs\python\python36\lib\site-packages\pyarmor\pytransform.py", line 69, in wrap
    result = func(*args, **kwargs)
  File "<HOME>\appdata\local\programs\python\python36\lib\site-packages\pyarmor\pytransform.py", line 114, in encrypt_project_files
    return dlfunc(proname, filelist, mode)
OSError: exception: access violation reading 0x0000019B00000000

**Comment by leah-l** [comment]
i change my python to 3.7 version its still not work but i get log file [_pytransform.log](https://github.com/dashingsoft/pyarmor/files/2252770/_pytransform.log)

**Comment by jondy** [comment]
I got it, thanks. I'll check it and fix it ASAP. Maybe the big trouble is that I need to install window 10, :)

**Comment by jondy** [comment]
From your log output, the capsule has been generated, so dynamic library has been loaded successfully, and some c function has been called. 

I guess the reason is that it return null when get the c pointer from PyString by calling `PyBytes_AsString` etc.  I have found the issus like this when I first run pyarmor in window 7. 

I'll check the code to find which python api results in this exception.

**Comment by jondy** [comment]
@leah-l
I have some questions need to be clear:

* Is the windows 10 in your machie 32-bits?

* After run `python pyarmor.py obfuscate...`, is there any script which has been obfuscated in the output path `./dist`?  If there are some scirpts have been obfuscated, which one results in this exception?

**Comment by leah-l** [comment]
hi, thank you very match for doing this

- no its 64-bit machine 
![image](https://user-images.githubusercontent.com/33288290/43580602-b0452b00-965e-11e8-9295-61460a185120.png)

- there is no file there except product.key and outside there is .pyarmor_capsule.zip folder with  license.lic, private.key, product.key, pyshield.key, pyshield.lic files.

**Comment by jondy** [comment]
Fixed in v3.9.7

**Comment by leah-l** [comment]
hi, 
i use python 3.6 work great thank you very much!
