### ISSUE TITLE
name __pyarmor__ not defined on 6.1.0 + 

### ISSUE THREAD

**Issue by scullcandyz** [dashingsoft/pyarmor#270]
Hey there, maybe I missed something but im getting the '__pyarmor__' is not defined error as soon as I update to any version higher then 6.1.0 

running with: 'pyarmor pack -x "--bootstrap 2" -e" --onefile
python 3.7.8
pyinstaller 4.0 dev build
pyarmor 6.2.9

**Comment by jondy** [comment]
Which script raises this error? If this script is not your own script, do not obfuscate it by option `--exclude`

Also try to clean the PyInstaller cached path `build` which locates in the current path

**Comment by scullcandyz** [comment]
The issue is being cause by init.py (entry) using --exclude wouldnt be an issue here I assume but it doesnt work unfortunately. Same for clearing cache path.

**Comment by jondy** [comment]
It seems no bootstrap code is inserted into the entry script. How about running `pack` with extra option `--debug`, for example
```
pyarmor pack --debug ...
```
The obfuscated scripts will be kept in the output path `dist/obf`, make sure the entry script include the bootstrap code.

**Comment by scullcandyz** [comment]
![pyarmorbootstraperr](https://user-images.githubusercontent.com/58109239/86522870-99872780-be64-11ea-8661-ac466594e13c.png)

_ _pyarmor_ _ has "Unresolved reference __pyarmor__ as error"  -tbh not sure if thats always like that, asside from that bootstrap present

**Comment by jondy** [comment]
The pack command works fine in my machine with latest pyarmor 6.2.9, so I have to find where is the problem by your error message.

In the traceback, the first frame of traceback is `File "__init__.py", line 1`, it try to import `main` at the line 1, so this `__init__.py` should be the original script. The obfuscated one isn't packed into the final bundle.

Could you show your other pack options?

**Comment by scullcandyz** [comment]
Found the issue, still a little confused why it worked on 6.1.0 and previous versions but whatever. 1 last question can I use the pack command together with --advanced 2? As it always seems to be throwing erros at me during obfuscation of the scripts

**Comment by jondy** [comment]
There is something changed in the `--advanced 2`, the dynamic library is changed to `pytransform.pyd`, other than `_pytransform.dll`, and there is no data files `pytranform.key`, `license.lic`, both of them are embedded to the dynamic library.

So the old build script may not work if it's customized.
