### ISSUE TITLE
Segmentation fault when running Django on Redhat Hat Enterprise Linux release 8.2 (Ootpa)

### ISSUE THREAD

**Issue by fananimi** [dashingsoft/pyarmor#272]
Hi I just build the Django project on Redhat Hat Enterprise Linux release 8.2 (Ootpa). But I can not execute the `manage.py` script. 
Here the log:
```
(env) [ec2-user@xx dist]$ python manage.py migrate
Segmentation fault
(env) [ec2-user@xx dist]$ 
```

Here some information:

Python Version: 3.7.5
Django Version:  Django==2.1.15

Step to Reproduce
1. Create a virtualenv and install Django==2.1.15 by using pip command
2. Create simple Django project
    `django-admin startproject app .`
3. Run pyarmor script
   `pyarmor obfuscate -r --advanced 1 --exact manage.py app/__init__.py -O dist --exclude env --platform linux.x86_64 --platform darwin.x86_64`
3. Migrate the django datatabse
    `cd dist && python manage.py migrate`

FYI, I have successfully run the steps on Ubuntu 20.04.

Highly appreciate if anyone can help the problem.

Regards,

Fanani M. Ihsan

**Comment by jondy** [comment]
How about obfuscating a simple script to test it in Redhat? For exmple,
```
pyarmor obfuscate --advanced 1 --exact foo.py
```

If it still doesn't work, it's recommend to use `--advanced 2` for Python 3.7
Refer to https://pyarmor.readthedocs.io/en/latest/advanced.html#using-super-mode

**Comment by fananimi** [comment]
Hi, @jondy  thanks for your feedback.

I have a new error after using `--advanced 2`. Do you have an idea?

```
(env) [ec2-user@xx dist]$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 2, in <module>
    from pytransform import pyarmor
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
(env) [ec2-user@xx dist]$ 
```

**Comment by jondy** [comment]
The Python interpreter should be compiled bye --enable-shared to work with super mode, it seems this Python interpreter is linked to static library
