### ISSUE TITLE
AttributeError: __enter__   Using obfuscate --advanced 2

### ISSUE THREAD

**Issue by Jamucy** [dashingsoft/pyarmor#273]
Hi,
i am trying to obfuscate my script, It is working well with default and --advanced 1. But when i use --advanced 2 i get the following error:
`Traceback (most recent call last):
  File "<Example.py>", line 2, in <module>
  File "<frozen Example>", line 2244, in protect_pytransform
AttributeError: __enter__
`

Pyarmor Version: 6.2.9
Python Version: 3.8.1

**Comment by jondy** [comment]
It seem there is something wrong with the default cross protection. How about disable cross protection
```
pyarmor obfuscate --no-cross-protection --advanced 2 foo.py
```

BTW, what's your platform? Windows or Linux

**Comment by Jamucy** [comment]
Thank you for the reply.

I am using Windows 10.

I have tried `pyarmor obfuscate --no-cross-protection --advanced 2 foo.py` to disable cross protection like you say but now the script will not run after obfuscation. Python has stopped working / Crashes

![image](https://user-images.githubusercontent.com/52129658/86545360-4675a900-bf26-11ea-9a1a-f5406c39fc18.png)

I only take this issue with --advanced 2, like i already mention default and advanced 1 are working perfectly but i would really like to use advanced 2 for added security.

**Comment by jondy** [comment]
Well,  I have fixed some super mode bugs, and the new version will be released in this week. Please try the new version later.

**Comment by Jamucy** [comment]
Ok thank you

**Comment by jondy** [comment]
Please upgrade to latest version v6.3.0

**Comment by Jamucy** [comment]
Hi, after the update i now get the following error with --advanced 2

`XXX lineno: 2246, opcode: 14
Traceback (most recent call last):
  File "<Example.py>", line 2, in <module>
  File "<frozen Example>", line 2246, in protect_pytransform
SystemError: unknown opcode`

so i tried again with disable cross protection and got this error:

`XXX lineno: 182, opcode: 38
Traceback (most recent call last):
  File "<Example.py>", line 2, in <module>
  File "<frozen Example>", line 182, in Start
SystemError: unknown opcode`

**Comment by jondy** [comment]
I'll first do more tests.

**Comment by Jamucy** [comment]
ok

**Comment by jondy** [comment]
Please upgrade to latest version v6.3.1, fix some asyncio issues.

**Comment by Jamucy** [comment]
I think there are some more problems with --advanced 2.
Please check below the error:

```
XXX lineno: 2246, opcode: 232
TypeError: print_exception(): Exception expected for value, str found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<Example.py>", line 2, in <module>
  File "<frozen Example>", line 3, in <module>
SystemError: unknown opcode
```

the problem must be with --advanced 2 because i can obfuscate my script with default and --advanced 1 and it is working perfect.

I really would like to use advanced 2 for security purposes because i have been told of people having there code compromised recently when using other mode.

**Comment by jondy** [comment]
I build a temp library, please download it from 
https://pyarmor.dashingsoft.com/downloads/temp/pytransform.pyd

Save it in the `$USERPROFILE/.pyarmor/platforms/windows/x86_64/11/py38/pytransform.pyd`, then obfuscate it again.

If you're not sure where is `$USERPROFILE`, just search `pytransform.pyd` in the path of `C:\Users`

**Comment by Jamucy** [comment]
Ok now python will crash when try to run the script obfuscated with advanced 2

![image](https://user-images.githubusercontent.com/52129658/87140691-d35b9200-c299-11ea-834c-4a0c497b5ec3.png)

**Comment by jondy** [comment]
@Jamucy could you send your sample script to "jondy.zhao@gmail.com"? Make it simple enough which could reproduce this issue.

**Comment by Jamucy** [comment]
Sure, I will send it over shortly

**Comment by jondy** [comment]
Duplicate of #279

**Comment by jondy** [comment]
Please upgrade v6.3.2, the command `pack` now could works with `--enable-suffix` by this way
```
pyarmor pack -x " --enable-suffix" ...
```

**Comment by Jamucy** [comment]
@jondy All working fine now.

You are a star, Thank you very much!
