### ISSUE TITLE
License after compromise

### ISSUE THREAD

**Issue by martyur** [dashingsoft/pyarmor#274]
Seems like recently there have been vulnerabilities found and shared for packages that did not use super (and advanced?) modes.
Since we have to assume all of the code in those packages is compromised and their key is found.
Does this also mean that the license itself is compromised, so that to be safe even when using super mode, we should buy a new license ?

**Comment by jondy** [comment]
Not required, just upgrade the latest version and obfuscate the scripts again, some of algorithms has been changed in the latest version.
