### ISSUE TITLE
Pyarmor 6.3.0: Cannot find outer license for non-super mode

### ISSUE THREAD

**Issue by dyronald** [dashingsoft/pyarmor#275]
Does 6.3.0 still support outer license for non-super mode obfuscate?

We need the outer license to update or cancel it easily. Documentation and changelog 6.3.0 seems to suggest outer license is now only in super mode with --with-license=outer option. But we can't use super mode because we are in python 3.6.

System info:
Docker; Centos 7; Python 3.6.8

**Comment by jondy** [comment]
Yes, the outer license is supported for non-super mode, but it need specify the option`--license=outer`, by default the outer license doesn't work.

**Comment by dyronald** [comment]
pyarmor obfuscate --with-license=outer --platform=linux.x86_64 --recursive --output=dist/app app/__init__.py

I tried the above command. But now the obfuscated code runs even without a license file. Is this the intended behavior? We need to block the code from running if license is not provided or expired.

**Comment by jondy** [comment]
In the console output, are there those lines ?
```
...
INFO     Use outer license file
...
INFO     Patch library dist/pytransform/_pytransform.so
```

**Comment by dyronald** [comment]
Yes. Those lines were included in the output. See excerpt below. 
But pytransform folder only has __init__.py and _pytransform.py after obfuscation. And app is able to run without a license.lic file.

INFO     Generating runtime files to dist/services/pytransform
INFO     Extract pytransform.key
INFO     Use outer license file
INFO     Copying /usr/local/lib/python3.6/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
INFO     Patch library dist/services/pytransform/_pytransform.so
INFO     Copying /usr/local/lib/python3.6/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK

**Comment by jondy** [comment]
How about obfuscate with -d, `pyarmor -d obfuscate ...`, in the console, after line `INFO Patch library`, it should be
```
DEBUG    Patching dist/pytransform/_pytransform.so
DEBUG    Found pattern at c1364
DEBUG    Patch 320 bytes from c1384
DEBUG    Patch 140 bytes from c14c4
DEBUG    Patch 216 bytes from c1550
```

**Comment by dyronald** [comment]
Yes. It does have that output

INFO     Generating runtime files to dist/services/pytransform
INFO     Extract pytransform.key
INFO     Generate default license file
DEBUG    Load platform list from /usr/local/lib/python3.6/site-packages/pyarmor/platforms/index.json
INFO     Create cross platforms path: /root/.pyarmor/platforms
DEBUG    Target dynamic library: ['/usr/local/lib/python3.6/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so']
INFO     Copying /usr/local/lib/python3.6/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
INFO     Patch library dist/services/pytransform/_pytransform.so
DEBUG    Patching dist/services/pytransform/_pytransform.so
DEBUG    Found pattern at c1364
DEBUG    Patch 261 bytes from c1384
DEBUG    Patch 270 bytes from c1489
DEBUG    Patch 404 bytes from c1597
INFO     Copying /usr/local/lib/python3.6/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK

**Comment by jondy** [comment]
Do you set `--with-license=outer` in your last command? I see the 3rd line is 
```
INFO Generate default license file
```

**Comment by dyronald** [comment]
You're right. Sorry. Forgot to set the flag. Here's the output with the flag.

INFO     Generating runtime files to dist/services/pytransform
INFO     Extract pytransform.key
INFO     Use outer license file
DEBUG    Load platform list from /usr/local/lib/python3.6/site-packages/pyarmor/platforms/index.json
INFO     Create cross platforms path: /root/.pyarmor/platforms
DEBUG    Target dynamic library: ['/usr/local/lib/python3.6/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so']
INFO     Copying /usr/local/lib/python3.6/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
INFO     Patch library dist/services/pytransform/_pytransform.so
DEBUG    Patching dist/services/pytransform/_pytransform.so
DEBUG    Found pattern at c1364
DEBUG    Patch 261 bytes from c1384
DEBUG    Patch 270 bytes from c1489
INFO     Copying /usr/local/lib/python3.6/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK

**Comment by jondy** [comment]
Is there any `license.lic` in the current path to run the obfuscated scripts? 

When the obfuscated scripts start, it will search license.lic in order:

- Check environment variable PYARMOR_LICENSE, if set, use this filename
- If it’s not set, search license.lic in the current path
- If not found, search the path of extension module pytransform
- Raise exception if there is still not found

If there is no license.lic, try to move `dist/services/pytransform` to any other place, check the obfuscated scripts could work or not.

**Comment by dyronald** [comment]
Ah. Yes. PYARMOR_LICENSE is set by sheer coincidence.
There is no issue then. Thank you so much.
