### ISSUE TITLE
Unable to bind license for executable

### ISSUE THREAD

**Issue by venkat-kittu** [dashingsoft/pyarmor#276]
I am trying to build executable for a simple project using below commands
**1) pyarmor init --entry=main.py
2) pyarmor config --with-license /licenses/expired/license.lic --advanced 1
3) pyarmor  pack -e " --onefile" .**

My license file was generated using below command
**pyarmor licenses --expired 2020-05-05**

After executing above commands, I was try to execute the executable  as **./dist/main**, I am not getting any error as License expired,
Please help me

**Comment by jondy** [comment]
In the console output when packing, are there these lines when obfuscating the scripts:
```
...
INFO     Generate license file from  licenses/expired/license.lic
...
INFO     Patch library dist/pytransform/_pytransform.so
```

**Comment by venkat-kittu** [comment]
I am able to find  **INFO     Generate license file from  licenses/expired/license.lic**  line in my log, but not able to find **INFO     Patch library dist/pytransform/_pytransform.so**

**Comment by jondy** [comment]
What's your platform? The last name may be different, in windows it may be `_pytransform.dll`. So is there any line like
```
INFO     Patch library dist/pytransform/
```

**Comment by venkat-kittu** [comment]
My os is Ubuntu 18.04. Below is the log i got

INFO     PyArmor Trial Version 6.2.9
INFO     Prepare to pack obfuscated scripts with PyInstaller...
INFO     entry script: main.py
INFO     src for searching scripts: .
INFO     build path: dist/obf
INFO     Run PyArmor to obfuscate scripts...
INFO     

/usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pyarmor/pyarmor.py build -O dist/obf --package-runtime 0 .


INFO     ==================== Run command ====================
INFO     PyArmor Trial Version 6.2.9
INFO     Build project . ...
INFO     Check project
INFO     Use capsule: /home/avenkat/.pyarmor/.pyarmor_capsule.zip
INFO     Output path is: dist/obf
INFO     Make path: dist/obf
INFO     Generating runtime files to dist/obf
INFO     Extract pytransform.key
INFO     Generate license file from  ../licenses/test2/license.lic
INFO     Write license file: dist/obf/license.lic
INFO     Copying /usr/local/lib/python3.6/dist-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
INFO     Generate runtime files OK
INFO     Save obfuscated scripts to "dist/obf"
INFO     Read public key from capsule
INFO     Enable increment build
INFO     Search scripts from /home/avenkat/venkat/Quantization/PyArmor/project/test_project
INFO     Obfuscate scripts with mode:
INFO     Obfuscating the whole module is on
INFO     Obfuscating each function is on
INFO     Autowrap each code object mode is on
INFO     Restrict mode is 1
INFO     Advanced mode is 1
INFO     	functions.py -> dist/obf/functions.py
INFO     	main.py -> dist/obf/main.py
INFO     2 scripts has been obfuscated
INFO     Insert bootstrap code to entry script dist/obf/main.py
INFO     Build project OK.
INFO     ==================== End command ====================

INFO     Create temp path: dist/obf/temp
INFO     Copy dist/obf/pytransform.py to temp path
INFO     Generate fixed license file
INFO     

/usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pyarmor/pyarmor.py licenses -O dist/obf/license.lic --fixed 1 pyarmor-packer


INFO     ==================== Run command ====================
INFO     PyArmor Trial Version 6.2.9
INFO     Generate licenses for project  ...
INFO     Output path of licenses: dist/obf
INFO     The license file is generated in restrict mode
INFO     The license file is generated in period mode disabled
INFO     Generate license: *FIXKEY:0123456789;*CODE:pyarmor-packer
INFO     Write license file: dist/obf/license.lic
INFO     Write information to dist/obf/license.lic.txt
INFO     Generate 1 licenses OK.
INFO     ==================== End command ====================

INFO     Run PyInstaller to generate .spec file...
INFO     

pyi-makespec --onefile --specpath . -p dist/obf/temp --hidden-import pytransform --additional-hooks-dir dist/obf/temp ./main.py


INFO     ==================== Run command ====================
wrote ./main.spec
now run pyinstaller.py to build the executable
INFO     ==================== End command ====================

INFO     Save .spec file to ./main.spec
INFO     Generate hook script: dist/obf/temp/hook-pytransform.py
INFO     Patching .spec file...
INFO     Save patched .spec file to main-patched.spec
INFO     Run PyInstaller with patched .spec file...
INFO     

/usr/bin/python3 -m PyInstaller --distpath dist --onefile --specpath . -y --clean main-patched.spec


INFO     ==================== Run command ====================
32 INFO: PyInstaller: 4.0.dev0
32 INFO: Python: 3.6.9
32 INFO: Platform: Linux-5.3.0-62-generic-x86_64-with-Ubuntu-18.04-bionic
33 INFO: UPX is not available.
34 INFO: Removing temporary files and cleaning cache in /home/avenkat/.cache/pyinstaller
34 INFO: Extending PYTHONPATH with paths
['/home/avenkat/venkat/Quantization/PyArmor/project/test_project',
 '/home/avenkat/venkat/Quantization/PyArmor/project/test_project/dist/obf/temp',
 '/home/avenkat/venkat/Quantization/PyArmor/project/test_project']
56 INFO: checking Analysis
56 INFO: Building Analysis because Analysis-00.toc is non existent
56 INFO: Initializing module dependency graph...
58 INFO: Caching module graph hooks...
64 INFO: Analyzing base_library.zip ...
2125 INFO: Caching module dependency graph...
2173 INFO: running Analysis Analysis-00.toc
2206 INFO: Analyzing main.py
2208 INFO: Analyzing hidden import 'pytransform'
2260 INFO: Processing module hooks...
2261 INFO: Loading module hook 'hook-pytransform.py' from '/home/avenkat/venkat/Quantization/PyArmor/project/test_project/dist/obf/temp'...
2261 INFO: Loading module hook 'hook-encodings.py' from '/usr/local/lib/python3.6/dist-packages/PyInstaller/hooks'...
2303 INFO: Loading module hook 'hook-xml.py' from '/usr/local/lib/python3.6/dist-packages/PyInstaller/hooks'...
2467 INFO: Looking for ctypes DLLs
2470 INFO: Analyzing run-time hooks ...
2473 INFO: Looking for dynamic libraries
2890 INFO: Looking for eggs
2891 INFO: Python library not in binary dependencies. Doing additional searching...
2983 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
2989 INFO: Warnings written to /home/avenkat/venkat/Quantization/PyArmor/project/test_project/build/main-patched/warn-main-patched.txt
3027 INFO: Graph cross-reference written to /home/avenkat/venkat/Quantization/PyArmor/project/test_project/build/main-patched/xref-main-patched.html
3037 INFO: checking PYZ
3037 INFO: Building PYZ because PYZ-00.toc is non existent
3037 INFO: Building PYZ (ZlibArchive) /home/avenkat/venkat/Quantization/PyArmor/project/test_project/build/main-patched/PYZ-00.pyz
3408 INFO: Building PYZ (ZlibArchive) /home/avenkat/venkat/Quantization/PyArmor/project/test_project/build/main-patched/PYZ-00.pyz completed successfully.
3410 INFO: checking PKG
3410 INFO: Building PKG because PKG-00.toc is non existent
3410 INFO: Building PKG (CArchive) PKG-00.pkg
5052 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
5053 INFO: Bootloader /usr/local/lib/python3.6/dist-packages/PyInstaller/bootloader/Linux-64bit/run
5053 INFO: checking EXE
5053 INFO: Building EXE because EXE-00.toc is non existent
5053 INFO: Building EXE from EXE-00.toc
5063 INFO: Appending archive to ELF section in EXE dist/main
5077 INFO: Building EXE from EXE-00.toc completed successfully.
INFO     ==================== End command ====================

INFO     Remove .spec file ./main.spec
INFO     Remove patched .spec file main-patched.spec
INFO     Remove build path dist/obf
INFO     Final output path: dist
INFO     Pack obfuscated scripts successfully.

**Comment by jondy** [comment]
How about upgrade pyarmor to the latest version 6.3.0, and try to pack it again?

**Comment by venkat-kittu** [comment]
okay i will try and let you know

**Comment by venkat-kittu** [comment]
No it's not working in 6.3.0

**Comment by jondy** [comment]
What if only obfuscate it with license?
```
pyarmor build -B
cd dist/
python main.py 
```
Make sure the following lines should be appear in the output of command `build` 
```
...
INFO     Generate license file from  licenses/expired/license.lic
...
INFO     Patch library dist/pytransform/_pytransform.so
```

**Comment by venkat-kittu** [comment]
It's working when i obfuscate the code
I,e, licensing is working

**Comment by jondy** [comment]
How about this command?
```
pyarmor pack --with-license /licenses/expired/license.lic -e " --onefile" .
```

**Comment by venkat-kittu** [comment]
Thanks, It's working now
