### ISSUE TITLE
NameError: name '__module__' is not defined

### ISSUE THREAD

**Issue by FlorianREGAZ** [dashingsoft/pyarmor#279]
Hey, 

thats my command:
pyarmor pack -x " --exclude tests --exclude helheim --exclude venv --advanced 2" -e " --onefile --icon=iconblau.ico --hidden-import=cloudscraper.reCaptcha.twocaptcha --hidden-import=pkg_resources.py2_warn --hidden-import=msgpack --hidden-import=lzstring --hidden-import=zerorpc --hidden-import=cryptography --hidden-import=cloudscraper  --add-data=venv/Lib/site-packages/cloudscraper;cloudscraper --add-data=helheim/license.lic;helheim/" --with-license pyarmor2/regcode-01/license.lic main.py

the error only happens when I use  --advanced 2
but I would really like to use it!

Python-Version: 3.8
Thanks already for your help! :)
![Screenshot_7](https://user-images.githubusercontent.com/54325655/86971138-efafdf80-c170-11ea-8592-d543cc0351d0.png)

**Comment by jondy** [comment]
Now I'm making a full test for super mode with Python 3.8, obfuscating all the scripts in Python test package and run it in super mode. Because someone else also reports Python3.8 super mode issues, but my test cases could not reproduce it.

After this test passes, I'll release a new version. I think of there should be some bugs.

**Comment by VeNoMouS** [comment]
👋 ... one of my packages @jondy ;P

**Comment by jondy** [comment]
@FlorianREGAZ Please upgrade to latest version v6.3.1, fix some asyncio issues.

**Comment by FlorianREGAZ** [comment]
Updated and did this:
> I build a temp library, please download it from
> https://pyarmor.dashingsoft.com/downloads/temp/pytransform.pyd
> 
> Save it in the `$USERPROFILE/.pyarmor/platforms/windows/x86_64/11/py38/pytransform.pyd`, then obfuscate it again.
> 
> If you're not sure where is `$USERPROFILE`, just search `pytransform.pyd` in the path of `C:\Users`

still getting: 
![Screenshot_8](https://user-images.githubusercontent.com/54325655/87140110-40265a80-c2a1-11ea-9877-a7084abd925b.png)

**Comment by jondy** [comment]
@FlorianREGAZ is the package `helheim` obfuscated by pyarmor either? In this case, it may conflict.

**Comment by VeNoMouS** [comment]
helheim is my package, and is obfuscated with supermode

**Comment by jondy** [comment]
I see. That's the problem.

@FlorianREGAZ  how about add an extra obfuscation parameter `--enable-suffix`, it could solve this conflict.

**Comment by VeNoMouS** [comment]
In future ill suffix as well as not to cause issue with ppl using my package if that is the case.

**Comment by jondy** [comment]
@VeNoMouS you should enable it. Otherwise, both of runtime module named `pytransform`, but they use different capsule, it  's really a problem.

Actually I don't think of this conflict before I notice there is a data file `helhelm/license.lic`, at that time I remember this package is yours, and may be obfuscated.

**Comment by VeNoMouS** [comment]
yea just in the middle of rewriting massive chunks, but due that otherwise of the restrict not taking hold... i cant release lol

**Comment by FlorianREGAZ** [comment]
> I see. That's the problem.
> 
> @FlorianREGAZ how about add an extra obfuscation parameter `--enable-suffix`, it could solve this conflict.

Added `--enable-suffix`
Getting this error now: 
![Screenshot_9](https://user-images.githubusercontent.com/54325655/87150344-24778000-c2b2-11ea-88d5-d1062461924e.png)

Sry, but idk what to do with this error.. :/
Maybe I should wait for VeNoMouS to add suffix, what do you think?

**Comment by jondy** [comment]
The `pack` command is not ready for `--enable-suffix`,  I'll fix it tomorrow.

**Comment by jondy** [comment]
Please upgrade v6.3.2, the command `pack` now could works with `--enable-suffix` by this way
```
pyarmor pack -x " --enable-suffix" ...
```

**Comment by FlorianREGAZ** [comment]
> Please upgrade v6.3.2, the command `pack` now could works with `--enable-suffix` by this way
> 
> ```
> pyarmor pack -x " --enable-suffix" ...
> ```

Works now! Ty so much
