### ISSUE TITLE
How to get hardware information as a return value from a function?

### ISSUE THREAD

**Issue by jondy** [dashingsoft/pyarmor#28]
Thank you for the response. I have an another query regarding that,

The issue is that we are using pyinstaller which will manage all this without installing pyarmor or python in the target machine by creating a bundled exe. As there are several machines, we have chosen this option.

I was able to get the hdinfo of pyarmor using the _pytransform.dll and pytransform.py but I wasn't able to catch it as a return value of the function show_hd_info and instead, it directly outputs to stdout. I want to get the output of hdinfo directly into a program. Even better if it happens with a single call, within the program itself without using subprocess calls to catch stdout.

 Can you help me with that or point to a resource where I could get exact deterministic outputs as hdinfo?

**Comment by jondy** [comment]
Besides, there is another tool `hdinfo` to get hardware information

http://pyarmor.dashingsoft.com/downloads/platforms/linux_x86_64/hdinfo
http://pyarmor.dashingsoft.com/downloads/platforms/win_amd64/hdinfo.exe
http://pyarmor.dashingsoft.com/downloads/platforms/macosx_intel/hdinfo
http://pyarmor.dashingsoft.com/downloads/platforms/win32/hdinfo.exe
http://pyarmor.dashingsoft.com/downloads/platforms/linux_i386/hdinfo

Download one of them according to your platform, then run `hdinfo`

**Comment by jondy** [comment]
From PyArmor v5.0.3, there is new function `get_hd_info` could be got hardware information as return value.
Refer to https://pyarmor.readthedocs.io/en/latest/pytransform.html#get_hd_info

**Comment by VeNoMouS** [comment]
@jondy are you going to add in cpu serial support?, since both mac and hd serial can be changed quite easily....

**Comment by jondy** [comment]
@VeNoMouS it could be implemented by plugins, here are 2 examples
https://github.com/dashingsoft/pyarmor/tree/master/plugins

I think it may be more security by plugins because the verify code is private, only the developer know how it works.

**Comment by VeNoMouS** [comment]
Roger that, will look into it, thanks
