### ISSUE TITLE
insert one redundant line '[None, None]' 

### ISSUE THREAD

**Issue by fananimi** [dashingsoft/pyarmor#281]
Hi @jondy 

What the meaning of this error?

```ERROR    The function 'create' could not be obufscated with advanced mode 2, insert one redundant line '[None, None]' at the beginning of this function to fix it```

This issue is related with #272 .

Thanks.

**Comment by jondy** [comment]
Because the code object includes some special instructions, Pyarmor could not obfuscate it directly. This has been fixed in v6.3.1 which will be released soon, most of those functions could be patched automatically.

**Comment by fananimi** [comment]
Thank you @jondy, I am waiting for the latest release soon because my company already purchase the license for some projects. 

Please let me know if the release is already available.

Cheers!

**Comment by jondy** [comment]
The new version is released, please upgrade to v6.3.2
