### ISSUE TITLE
6.3.1 causing `Block stack underflow`

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#282]
A user is experincing an issue with new pyarmor **6.3.1** , however older code obfuscated with **6.2.9** doesn't generate the error..

# Python Version
```
C:\Users\Administrator\Desktop\sp_killer>python
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

# Error
```
C:\Users\Administrator\Desktop\sp_killer>python inject-example.py
Fatal Python error: XXX block stack underflow

Current thread 0x000081fc (most recent call first):
  File "<frozen helheim_backup>", line 1003 in <listcomp>
  File "<frozen helheim_backup>", line 1006 in helheim
  File "inject-example.py", line 7 in injection
  File "C:\Program Files\Python37\lib\site-packages\cloudscraper__init__.py", line 277 in request
  File "C:\Program Files\Python37\lib\site-packages\requests\sessions.py", line 543 in get
  File "inject-example.py", line 13 in <module>
```

**Comment by jondy** [comment]
It indeed changes some codes about handling exception, I'll check it.

**Comment by VeNoMouS** [comment]
thanks dude :)

**Comment by BarryThrill** [comment]
Can confirm that I have the same issue! 😁

**Comment by THOOSJE2005** [comment]
Same issue here!

**Comment by younesdev1** [comment]
Same issue

**Comment by jondy** [comment]
Is there any special feature used near line 1006 in the `helheim_backup.helheim`? For example, `asyncio`, `with`, `try...finally`, `threading` etc. Besides, the last frame is `<listcomp>`, is your own function?

**Comment by VeNoMouS** [comment]
nope, that section is calling a sanity check and doing an all([callable(getattr() for sanity checking.. there is no asyncio, no threading, no finally ... it does do a raise if it fails.

**Comment by jondy** [comment]
@VeNoMouS I build one temp library for windows.x86_64.py37

https://pyarmor.dashingsoft.com/downloads/temp/pytransform.pyd

Please check it.

If it still doesn't work, please pick up the snapshot of the last frame `<listcomp>`, just obfuscate it with super mode, and run it. If it could reproduce this issue, send the sample code to my email.

**Comment by VeNoMouS** [comment]
rgr that sorry will do for you shortly, sorry been busy with some other work

**Comment by VeNoMouS** [comment]
Ok @jondy i tested, still blows up with that pyd... but i found the problem... its pretty easy to replicate...

# **__init__.py**
```python
def makeTest():
    if not all([True for fnct in ['foobar']]):
        print(f'Nope... {fnct} not there..')
```
# options...
```
python3.7 `which pyarmor` obfuscate -O ../dist/ --restrict 1 --advanced 2 --platform windows.x86_64  __init__.py
```

**Comment by jondy** [comment]
@VeNoMouS  unfortunately I could not reproduce this issue from this script, it works fine in my windows. Could you upload this obfuscated package with runtime file to https://tmpfiles.org?

**Comment by VeNoMouS** [comment]
@jondy just woke up, but sure mate, not a problem ill flick you details in an email ok?

**Comment by VeNoMouS** [comment]
@jondy done

**Comment by VeNoMouS** [comment]
@jondy did you get my email?

**Comment by jondy** [comment]
@VeNoMouS got it. And find the problem, I'm fixing it. Thanks.

**Comment by jondy** [comment]
Please upgrade v6.3.2, it should be fixed.

**Comment by VeNoMouS** [comment]
thanks @jondy will do and get the users to test, most of eu is just waking up so it'll be a little bit before they report back

**Comment by VeNoMouS** [comment]
@jondy 1 user reported it working

**Comment by VeNoMouS** [comment]
@jondy no one reporting issues anymore, i think if its cool by you ill close this ticket...

once again sir, thank you very much for your work in getting it resolved :) ❤️ 

Have a good morning / afternoon / evening)

**Comment by VeNoMouS** [comment]
hi @jondy , a user reported in that hes getting segfaults for this build in `armv7`, user is @fran008

**Comment by jondy** [comment]
I'll check it

**Comment by jondy** [comment]
Found the problem, it'll be fixed in next version

**Comment by VeNoMouS** [comment]
thanks @jondy <3, once new release out, ill re-package for him and get him to test and confirm and get back to you

**Comment by jondy** [comment]
Please upgrade to 6.3.3

**Comment by VeNoMouS** [comment]
thanks @jondy forgot to close this
