### ISSUE TITLE
pyarmor with Embeddable Python?

### ISSUE THREAD

**Issue by ManchesterWuer** [dashingsoft/pyarmor#283]
I am working on an embeddable python environment, downloaded from https://www.python.org/downloads/windows/, the version I am using is Windows x86-64 embeddable zip file. The obfuscation with Pyarmor was a success, however, when I was running codes with embeddable python, the embeddable python popped up an error message: 
```
from pytransform import pyarmor_runtime
ModuleNotFoundError: No module named 'pytransform'
```
So, I am wondering if Pyarmor just doesn't support embeddable python? Is there a solution for that?

**Comment by jondy** [comment]
This error means there is no runtime package `pytransform` found. Make sure there is `pytransform/__init__.py` within the obfuscated scripts.

**Comment by ManchesterWuer** [comment]
@jondy Actually there is `pytransform/__init__.py`. If I use my default python (Anaconda 3) to run the obfuscated codes, it's a success, whereas when using embeddable python, I got the error message `No module named 'pytransform'`. So, I guess there must be some difference between python and embeddable python. Do I have to change something in enbededable python?

**Comment by VeNoMouS** [comment]
@ManchesterWuer try add `--bootstrap 3`

**Comment by ManchesterWuer** [comment]
@VeNoMouS I got 
` from .pytransform import pyarmor_runtime
ImportError: attempted relative import with no known parent package`

**Comment by ManchesterWuer** [comment]
@VeNoMouS 
I got 
`from .pytransform import pyarmor_runtime

ImportError: attempted relative import with no known parent package`

**Comment by VeNoMouS** [comment]
is there a pytransform.pyd file in there?

**Comment by ManchesterWuer** [comment]
No, there are only ___init__, _pytransform.dll, license.lic and pytransform.key._

**Comment by VeNoMouS** [comment]
how are you importing?

**Comment by ManchesterWuer** [comment]
What do you mean importing?
In the main.py file, it is: `from .pytransform import pyarmor_runtime
pyarmor_runtime()
__pyarmor__(__name__, __file__,…………`
I generated the obfuscated codes by typing `pyarmor obfuscate --output path --recursive path1 --bootstrap 3` in powershell.
The point is I can run obfuscated codes with Anaconda 3, but can't run it with Embeddable Python, so I guess there might be something with embeddable python.

**Comment by VeNoMouS** [comment]
you load the module via `import`..... are you new to python or something?

**Comment by ManchesterWuer** [comment]
The `import` stuff is automatically generated by Pyarmor, I'm not new to python, but new to pyarmor. Anyway, thanks.

**Comment by jondy** [comment]
```
from pytransform import pyarmor_runtime ModuleNotFoundError: No module named 'pytransform'
```
This error message generally means that the package pytransform could not be found. As you see, this package is a normal Python package, so first make sure it locates in any Python path.

**Comment by jondy** [comment]
Have a test in python-embed, the problem is that there only 2 default Python path for embed Python, for example,
```
['C:\\Python-embed\\python37\\python37.zip', 'C:\\Python-embed\\python37']
```

So one solution is to copy the runtime package `pytransform` to same path of embed python.

**Comment by ManchesterWuer** [comment]
@jondy Thanks a lot! Tested with your solution and it works fine.

**Comment by ManchesterWuer** [comment]
@jondy There is another bug: with embeddable python, if I import my own module in main.py, like 
`import MyModule`,
there will be a bug: 
`ModuleNotFoundError: No module named 'MyModule'`,
is this bug still related to the default path problem?
BTW, I have already copied the runtime package pytransform to the same path of embed python, it works fine if I didn't import any of my own modules.

**Comment by jondy** [comment]
Yes, because the current path isn't in the embed Python path.

I think as the design of embed Python, all the .py files should be zipped into python.zip.

**Comment by ManchesterWuer** [comment]
@jondy Base on [this tutorial,](https://dev.to/fpim/setting-up-python-s-windows-embeddable-distribution-properly-1081) added current path into the embeddable python, I checked `sys.path` and got:
`['', 'C:\\python-3.7.8-embed-amd64\\python37.zip', 'C:\\python-3.7.8-embed-amd64\\Lib\\site-packages', 'C:\\python-3.7.8-embed-amd64']`
But I am still getting error `ModuleNotFoundError: No module named 'MyModule'`.
Is there something else I forgot to do?

**Comment by ManchesterWuer** [comment]
@jondy You think I should put all my modules into `python37.zip`?

**Comment by jondy** [comment]
As you distribute the final package, I think it's cool to put all the .py or .pyc files in the python.zip of embed Python.

**Comment by ManchesterWuer** [comment]
@jondy Thanks! Will try and see.
