### ISSUE TITLE
Trying to call --logo through Python code with Input

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [dashingsoft/pyarmor#284]
Hi!
I am trying to call Pyarmor from Python code.
Now I want to ask a input of logo in which we can add logo for the generated EXE.
Please help me 

Tnx
Vedant Bhalgama

**Comment by jondy** [comment]
If you use `pack` command to generate exe, add the icon by this way when calling pyarmor in the python code
```
cmd = ['pack', '-e', ' --icon app.icon --onefile', 'foo.py']
call_pyarmor(cmd)
```

**Comment by Vedant-Bhalgama** [comment]
But what if the icon is a user input? Because the user wants to generate his own icon?

**Comment by jondy** [comment]
If you could get the icon filename of user input, you can build the cmd:
```
cmd = ['pack', '-e', ' --icon %s --onefile' % icon_filename, 'foo.py']
call_pyarmor(cmd)
```

**Comment by Vedant-Bhalgama** [comment]
What is the %s? And yes If i can get the icon filename. Can I replace the percentage s with the raw_input?

**Comment by jondy** [comment]
No. `raw_input` should be used like this way
```
icon_filename = raw_input("Please input icon:")
cmd = ['pack', '-e', ' --icon %s --onefile' % icon_filename, 'foo.py']
call_pyarmor(cmd)
```

**Comment by Vedant-Bhalgama** [comment]
So why u have used %s and%?

**Comment by jondy** [comment]
Interesting, how do you build a string with variable in Python?

**Comment by Vedant-Bhalgama** [comment]
Ok! I got it sir!

**Comment by Vedant-Bhalgama** [comment]
And other thing I wanted to ask that can we convert .py to .ps1 scripts Powershell Sripts?

**Comment by jondy** [comment]
Sorry, I don't know well about Powershell.

**Comment by Vedant-Bhalgama** [comment]
So can we convert python script to XML file?

**Comment by Vedant-Bhalgama** [comment]
Hi!
I had another doubt that can use --add-data in PyInstaller and add .xml file?
Something like 
pyinstaller --onefile --noconsole --add-data C:\Data.xml foo.py

**Comment by jondy** [comment]
In Windows the format of `--add-data` may like this `--add-data C:\Data.xml;.`

**Comment by Vedant-Bhalgama** [comment]
I try this with pyarmor but it doesn't open a xml file or pdf file if settled to pdf

**Comment by jondy** [comment]
As my understanding, you pack a Python script to exe, then run it. What do you mean open a pdf file?

**Comment by Vedant-Bhalgama** [comment]
I mean something like that i am packing the py to exe, But i am also adding data to it using this command
--add-data. And In PyInstaller it shows me the added data whenever i execute the exe. So basically it opens up a pdf.

**Comment by jondy** [comment]
It's strange. How about try a new simple script `foo.py`:
```
print('Hello, test data file')
```
Then pack it
```
pyinstaller --add-data Data.xml;. --onefile foo.py
```
And run the final bundle
```
dist/foo
```

**Comment by Vedant-Bhalgama** [comment]
pyinstaller works but pyarmor doesnt works.I will try again and tell u
