### ISSUE TITLE
RuntimeError: The python version in runtime is different from the build time

### ISSUE THREAD

**Issue by NeroAdvents** [dashingsoft/pyarmor#287]
Hello, 

I'm using pyarmor on one of my django project and I encountered an issue while trying to run a simple script myscrit.py just like the tutorial. 

(venv) ➜  dist python3.8 -d myscript.py
Traceback (most recent call last):
  File "<myscript.py>", line 3, in <module>
RuntimeError: The python version in runtime is different from the build time

Can someone help me on this and tell me how to proceed ? Thank you very much

Sincerely,
Nordine

**Comment by jondy** [comment]
Please obfuscate your script with Python3.8.
