### ISSUE TITLE
How to decode extended --bind-data information from a .lic file

### ISSUE THREAD

**Issue by dabrowne** [dashingsoft/pyarmor#290]
Hi, we are using the `--bind-data` flag to add some extended parameters to our licenses. We also provide a tool for customers to add a new license to their system in case they have purchased a new one.

Currently to validate our extended license parameters when a new license is installed, we have to make a backup copy of the existing license, write the new license to disk, and call `get_license_info`. Then if the extended parameters for the new license do not pass validation, we restore the original backup file. There is some risk here though that if the process is interrupted, the original backup will not be restored and the customer is stuck with an unusable license.

Is there a method to decode the `DATA` field from a license file without `get_license_info`? This would allow us to 'pre-validate' the license data before writing it to disk. I have tried base64 decode, which mostly works but I'm not sure how reliable it is.

**Comment by jondy** [comment]
In this case I think it's better to store this extended parameters to any other place. For example, at the beginning of main script, just save data to a file `myapp/data/.pyarmor_extra_data`
```
cfgfile = 'myapp/data/. pyarmor_extra_data'
if not os.path.exists(cfgfile):
    from pytransform import get_user_data
    with open(cfgfile, 'w') as f:
        f.write(get_user_data()) 
```
After that get the extended parameters from configuration file.

The format of license file may be changed later, although now it could be got by base64 decode.

**Comment by dabrowne** [comment]
Thanks for the response. I understand this idea, but this will create a config file from the __installed__ license (one that is already saved to the filesystem).

I would like to read the user data from a new license file __before__ is is installed so that I can validate the user data section before overwriting the existing license on the filesystem.

**Comment by jondy** [comment]
At this time the extended data could be got by base64 decode, if I change the format of license file in future, I'll take this requirement into account.

**Comment by dabrowne** [comment]
Ok, thanks for the info
