### ISSUE TITLE
Not Generating EXE on Linux

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [dashingsoft/pyarmor#293]
Hi!

I am compiling a script to EXE using PyArmor on Kali Linux, It generates a exe which works in Linux environment but when transferred on Windows it doesnt works. And If we try to rename it, The whole program breaks. This kind of exe is generated on Kali Linux.

![Capture](https://user-images.githubusercontent.com/67494275/88178497-1cbbc200-cc48-11ea-9a72-21e72819a227.PNG)

**Comment by jondy** [comment]
The `pack` command doesn't support cross platform, you must build exe on Windows.

**Comment by Vedant-Bhalgama** [comment]
But what if I want to build on Linux platforms? Can PyInstaller work or not ?

**Comment by jondy** [comment]
PyInstaller also doesn't support cross platform.

**Comment by Vedant-Bhalgama** [comment]
So what should I do? Should I run this with wine?

**Comment by Vedant-Bhalgama** [comment]
I tried installing it with wine and it worked like a charm, But now what if i want to call the Pyarmor code using wine only?

**Comment by jondy** [comment]
I don't know `wine`. You can try it.

**Comment by Vedant-Bhalgama** [comment]
I tried wine and it worked with command line one Means this one 

wine pyarmor.exe pack -e "--onefile--noconsole" foo.py

Now how can I use this command in subprocess.call

**Comment by Vedant-Bhalgama** [comment]
isn't there any other way?

**Comment by jondy** [comment]
If `wine` work, the following code should work
```
subprocess.Popen(['wine', 'pyarmor.exe', 'pack', '-e', '--onefile--noconsole', 'foo.py'])
```
Please check python document about usage of `subprocess`, the `pack` command really doesn't support cross platform because it call pyinstaller in backend.

**Comment by Vedant-Bhalgama** [comment]
Ok Jondy!

Let's see if this works or not, Because i am making a framework rn, which only works on Linux Platforms

**Comment by Vedant-Bhalgama** [comment]
![Capture](https://user-images.githubusercontent.com/67494275/88248082-9772f480-ccbd-11ea-93ff-3652232b5b0a.PNG)

It gave me this error when i simply try to run it like this

```
import subprocess
subprocess.Popen(['pyarmor', 'pack', '-e', '--onefile--noconsole', 'foo.py'])
```

**Comment by Vedant-Bhalgama** [comment]
HI Jondy!
It worked like this
**```
import subprocess

subprocess.Popen(['pyarmor', 'pack', '-e', '"--onefile --noconsole"', 'foo.py'])
```**
Now can i use raw_input for path instead of the foo.py?

**Comment by Vedant-Bhalgama** [comment]
Hey Jondy!

I tried to modify the code and it works till here and gives me this error

![Capture](https://user-images.githubusercontent.com/67494275/88250739-21bf5680-ccc6-11ea-8ecf-e1422a64aa98.PNG)

This is the code i use

import subprocess

```
ask_path = raw_input("[+] Path >> ")
subprocess.Popen(['pyarmor', 'pack', '-e', '"--onefile --noconsole"', ask_path])
```

**Comment by jondy** [comment]
If you don't use pyarmor in cross platform, call pyarmor without subprocess by this way
```
from pyarmor.pyarmor import main as call_pyarmor
call_pyarmor(['pack', '-e', ' --onefile --noconsole',  'foo.py'])
```
Refer to https://pyarmor.readthedocs.io/en/latest/advanced.html#call-pyarmor-from-python-script

Besides do not pass extra option with double quotation marks `"--onefile --noconsole"`, just insert a leading blank like above.

**Comment by Vedant-Bhalgama** [comment]
I want to use pyarmor in cross platform, I know this method but this method doesnt support wine and it will not generate windows exe on linux

**Comment by Vedant-Bhalgama** [comment]
I tried the way u told and it worked good! But now what if i want to save the files to a specific place? 
And in the same code how can I add option for --icon?

**Comment by jondy** [comment]
```
from pyarmor.pyarmor import main as call_pyarmor
call_pyarmor(['pack', '-e', ' --onefile --noconsole --icon xxx.icon',  '-O', 'dist2', 'foo.py'])
```

**Comment by Vedant-Bhalgama** [comment]
No, How can I use the icon one in this command
`subprocess.Popen(['pyarmor', 'pack', '-e', '--onefile --noconsole', ask_path])`

**Comment by jondy** [comment]
Hi guy, this is the python basic knowledge, I have gave several examples about this, and I can't help your write all of python scripts. Please refer to the Python document to find the solution for using icon in one function call.

**Comment by Vedant-Bhalgama** [comment]
Also i wanted to ask that can e save our EXE to a specified path or not?

**Comment by Vedant-Bhalgama** [comment]
Also i got this error when i am running the command.
```
import subprocess
subprocess.Popen(['wine', '/root/.wine/drive_c/Python27/Scripts/pyarmor.exe', 'pack', '-e', '--onefile --noconsole', '/root/test.py'])
```
![Capture](https://user-images.githubusercontent.com/67494275/88296780-beacde80-cd1c-11ea-908b-f880c52090d2.PNG)

**Comment by jondy** [comment]
Use option `-O` to set output path, for more available options, please refer to man page of [pack](https://pyarmor.readthedocs.io/en/latest/man.html#pack)

About the wine error, please check the script in line 79, there is syntax error

**Comment by Vedant-Bhalgama** [comment]
Jondy
I am not having scripts such as the WebSocket Scan Template. I had another script which I had written in the code 
`subprocess.Popen(['wine', '/root/.wine/drive_c/Python27/Scripts/pyarmor.exe', 'pack', '-e', '--onefile --noconsole', '/root/test.py'])
`
It was this one above

**Comment by jondy** [comment]
You'd better make a separate directory for your script, for example, `/root/myapp/test.py`

**Comment by Vedant-Bhalgama** [comment]
So does this mean that this is directory error??

**Comment by jondy** [comment]
pack will obfuscate all the other .py files in the same path.

**Comment by Vedant-Bhalgama** [comment]
`subprocess.Popen(['wine', '/root/.wine/drive_c/Python27/Scripts/pyarmor.exe', 'pack', '-e', '--onefile --noconsole', '/root/Avyukt/Avyukt_Pays/Avyukt_rtcp.py'])`
I am trying this command in Python but i get this error.
