### ISSUE TITLE
Question: Strange error

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#295]
@jondy have you seen this error before? 

A user is getting it on two different systems.. but no one else is experiencing it...

```
 No name 'pyarmor' in module 'helheim.pytransform'
```

```
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from helheim import helheim
  File "xxxxxxxxxxxxxxxxx/helheim/__init__.py", line 2, in <module>
    from .pytransform import pyarmor
ModuleNotFoundError: No module named 'helheim.pytransform'
```

**Comment by jondy** [comment]
I think it may import the old runtime package `pytransform` other than extension `pytransform.pyd`. So find all the folder `pytransform` and remove them.

**Comment by VeNoMouS** [comment]
On the client or my build server?

**Comment by jondy** [comment]
On the client. It seems the first issue is importing old package, the second issues is no runtime module.

**Comment by VeNoMouS** [comment]
hrrmr client saying it was a fresh install?!

**Comment by jondy** [comment]
But I'm sure this problem
```
No name 'pyarmor' in module 'helheim.pytransform'
```
It absolutely imports the old runtime package.

**Comment by VeNoMouS** [comment]
your refering to the ~/.pyarmor runtime right, now the packaged run time?

**Comment by jondy** [comment]
In the runtime, `~/.pyarmor` is useless.

**Comment by VeNoMouS** [comment]
But multiple other ppl run the same package with no issues.

**Comment by jondy** [comment]
There should be something different in this machine. If possible, run this from Python interpreter
```
>>> import helhelm
>>> print(helhelm.__path__)
>>> import os
>>> print([os.listdir(x) for x in helhelm.__path__])
```

**Comment by VeNoMouS** [comment]
@jondy got another user with the same issue,... the last user ended up building a whole new server to resolve it...

**Comment by jondy** [comment]
The reason is that the right runtime package `pytransform` couldn't be imported, so there should be the old package is cached, that's why the refresh server works. But I don't know where it's cached in the customer machine, anyway, try to remove the path `__pycache__`

**Comment by VeNoMouS** [comment]
we found the issue, he neglected to tell me he was running it inside pm2....
