### ISSUE TITLE
Obfuscate and Overwrite Original Files

### ISSUE THREAD

**Issue by mdtlyf** [dashingsoft/pyarmor#296]
Just wondering - is it possible that I obfuscate all the python files and overwrite them at the same time? Just like `sed -i`, you don't need to copy and replace file by yourself.

Here is the scenario: I have a docker image, inside which everything is ready except the source code is not obfuscated. Now I just want to obfuscate every single python files. One possible solution is using a command like `find my_project_home -type f -name '*.py' -exec some_pyarmor_command {} \;`, and then everything should be ok for me - every python file is encrypted, lying exactly where it was , and I don't need to specify `.pyarmor_config` every time (I may have some non-python files inside my project dir and they are necessary). So any suggestions?

**Comment by jondy** [comment]
In the early version, it did supports this in-place behavior. It's removed later because it may be dangerous. And there is another solution I think it's also easy
```
pyarmor obfuscate -r /path/to/src/foo.py
cp -a dist/* /path/to/src
rm -rf dist
```

**Comment by mdtlyf** [comment]
Thanks for the suggestion but for my situation it could be more complex. Thanks anyway.
