### ISSUE TITLE
Calling PyInstaller from Python

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [dashingsoft/pyarmor#298]
Hey Jondy!
I am trying to use wine and PyInstaller for compiling Windows Executable on Linux, Now I am trying to call it's code in Python but it says this error, Also the script is in it's path, But still it says this error.

![Capture](https://user-images.githubusercontent.com/67494275/88752397-6ee47200-d177-11ea-86b1-6d6fc934795a.PNG)

This is the code which I am trying
ask_path = raw_input("\n[+] Please enter script path --> ")
subprocess.call(['wine', '/root/.wine/drive_c/Python27/Scripts/pyinstaller.exe', '--noconsole --onefile', ask_path])

**Comment by jondy** [comment]
If you use PyInstaller directly, you should pass options directly, for example
```
subprocess.call(['wine', '/root/.wine/drive_c/Python27/Scripts/pyinstaller.exe', '--noconsole',  '--onefile', ask_path])
```
