### ISSUE TITLE
XXX block stack underflow while threading

### ISSUE THREAD

**Issue by CharlieAIO** [dashingsoft/pyarmor#299]
Running 20 threads on windows

![image](https://user-images.githubusercontent.com/39866368/88867132-7dc53600-d204-11ea-916d-6a4658f97571.png)

`Fatal Python error: XXX block stack underflow` appears at the top of the error message

`Current thread 0x0000549c (most recent call first):
  File "<frozen helheim_backup>", line 1003 in <listcomp>
  File "<frozen helheim_backup>", line 1006 in helheim`

Helheim is using latest runtime and pyarmor 

`Thread 0x0000710c (most recent call first):
  File "E:\Breaker-Raffle\sites\nakedcph.py", line 331 in main
  File "E:\Breaker-Raffle\run.py", line 155 in run_from_console
  File "main.py", line 12 in <module>`

line 331 -> time.sleep(int(delay))

Tried adding in micro sleeps, but this didnt help resolve the issue.

**Comment by jondy** [comment]
How about reboot your Windows 10? It may use some cached dynamic library. If possible, try to install package `helheim` to other path.

**Comment by CharlieAIO** [comment]
Tried restarting my pc, didnt make any difference. Then tried moving helheim into different paths this still didnt make a difference.
I continue to get the same error.

**Comment by jondy** [comment]
Duplicate of #282 

This issue has been fixed, it is the most possible that the old cached library `pytransform.pyd` is used.

**Comment by VeNoMouS** [comment]
@jondy hes not using a docker or pm2, that is latest run time and latest pyarmor.. no other users are experincing this issue on windows however.

**Comment by jondy** [comment]
The traceback is same in both of these issues:
```
File "<frozen helheim_backup>", line 1003 in <listcomp> 
File "<frozen helheim_backup>", line 1006 in helheim
```

Though not 100%, but I don't think of this is a new issue.
