### ISSUE TITLE
Wine and PyArmo logo

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [dashingsoft/pyarmor#300]
Hi!

I wanted to know that I am calling pyarmor from Python from this and also use wine, Now how can I add a raw_input to icon path?

This is my code  ... 

`subprocess.call(['wine', '/root/.wine/drive_c/Python27/Scripts/pyarmor.exe', 'pack', '-e', '--onefile --noconsole', ask_path])`

**Comment by jondy** [comment]
```
ask_icon = raw_input()
subprocess.call(['wine', '/root/.wine/drive_c/Python27/Scripts/pyarmor.exe', 'pack', '-e', '--onefile --noconsole --icon %s' % ask_icon, ask_path])
```

**Comment by Vedant-Bhalgama** [comment]
Ok!
I will test this and tell you how it goes ...

**Comment by Vedant-Bhalgama** [comment]
WHat if i want this in PyInstaller? Same thing?

**Comment by jondy** [comment]
```
ask_icon = raw_input()
subprocess.call(['wine', '/root/.wine/drive_c/Python27/Scripts/pinstaller', '--onefile', '--noconsole', '--icon %s' % ask_icon, ask_path])
```

**Comment by jondy** [comment]
Hi guy, I close this issue because it's not related to pyarmor. What you ask is how to write Python script, I suggest you learning some basic examples from Python official tutorials.
