### ISSUE TITLE
How to package data files inside installed modules?

### ISSUE THREAD

**Issue by NoahCardoza** [dashingsoft/pyarmor#302]
Someone is having an issue with my module:

https://github.com/NoahCardoza/CaptchaHarvester/issues/18

We can't seem to figure out how to package the SSL cert files because pyarmor isn't including them. And we can't monkeypatch the open function because the core SSL lib is written in C.

Any ideas?

**Comment by jondy** [comment]
In `pack` command, pass extra PyInstaller options `--add-data`, `--add-binary` by `-e`, for example,
```
pyarmor pack -e " --add-data file1:. --add-binary lib1.so:." foo.py
```

For the usage of pyinstaller options, refer to  https://pyinstaller.readthedocs.io/en/stable/usage.html

For more usage of pack, refer to man page of [pack](https://pyarmor.readthedocs.io/en/latest/man.html#pack)

**Comment by NoahCardoza** [comment]
Does the problem seems to be that the module isn't in the project directory? We tried that but the `ssl` module isn't able to find the files.

**Comment by jondy** [comment]
It doesn't matter that the module isn't in the project directory.

If open a file in the PyInstaller bundle, the current path need to be fixed by this way:
```
if getattr(sys, 'frozen') and hasattr(sys, '_MEIPASS'):
    # running in a PyInstaller bundle
    filename = os.path.join(sys._MEIPASS, 'cert.data')
else:
    # running in a normal Python process
    filename = 'cert.data'
print('Found data file: %s' % os.path.exists(filename))
```
Refer to https://pyinstaller.readthedocs.io/en/stable/runtime-information.html

I think this is maybe the problem.
