### ISSUE TITLE
Remove docstrings

### ISSUE THREAD

**Issue by mauvilsa** [dashingsoft/pyarmor#303]
pyarmor is a great tool to obfuscate python code and prevent people to read it, understand it, reverse engineer it, etc. However, in python code normally includes docstrings intended to help people who legitimately need to understand the code and user and/or extend it. I have not seen any options in pyarmor to remove the docstrings. If the docstrings are not removed, from the obfuscated code it is possible to generate the documentation of the code which can give a rather clear understanding of the code. Is there an option in pyarmor to remove docstrings?

**Comment by jondy** [comment]
At this time there is no option to remove docstrings.

**Comment by mauvilsa** [comment]
@jondy I cloned the repository, checked out the v6.3.5 tag, built a wheel file and installed it. If I try to run `pyarmor obfuscate -r -O out pkg/__init__.py` I get an error `ERROR    [Errno 2] No such file or directory: '.../.local/lib/python3.6/site-packages/pyarmor/platforms/index.json`. This happens with and without the optimize change you suggested. If I install the package from pypi it works without problem. What do I have to do so that a locally built wheel works?

Since this feature seems rather simple, is there a plan to add this as a configurable option in a future version of pyarmor?

**Comment by jondy** [comment]
This file could be got from https://github.com/dashingsoft/pyarmor-core/raw/master/platforms/index.json, just download it 
to `.../.local/lib/python3.6/site-packages/pyarmor/platforms/index.json`. Or save it to `pyarmor/src/platforms`, and rebuilding the wheel.

It's not simple for Python < 3.3, because there is no keyword argument `optimize` for builtin function `compile`. If more users request this feature, I'll add it in new version.

**Comment by mauvilsa** [comment]
I managed to create a wheel file locally with the latest commit in master and I can confirm that it works correctly. Thank you very much! Now I am interested in upgrading pyarmor in the server where we have the purchased license, though I would prefer to not install a locally built package. Just for me to plan, more or less when would it be expected to have a new release in pypi?

Regarding closing this issue, even though the removal of docstrings works, there is one remaining thing to do. I think this feature is useful so it would be good to mention it in the pyarmor documentation so that other people are aware of it.

**Comment by jondy** [comment]
The new version with this patch will be released in a couple of weeks
 
Thanks for your advice, I have documented this feature here
https://pyarmor.readthedocs.io/en/latest/advanced.html#how-to-remove-docstrings
