### ISSUE TITLE
How to specify path for directory of saving EXE in pyarmor?

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [dashingsoft/pyarmor#304]
How to specify path for directory of saving EXE in pyarmor and pyinstaller both. Will -o work?

**Comment by jondy** [comment]
Please refer to https://pyarmor.readthedocs.io/en/latest/man.html#pack

**Comment by Vedant-Bhalgama** [comment]
Will --output work for pyinstaller?

**Comment by jondy** [comment]
Please refer to https://pyinstaller.readthedocs.io/en/stable/usage.html#options

**Comment by Vedant-Bhalgama** [comment]
I read the documentation but there is not such option like --option or -o for output in pyinstaller

**Comment by jondy** [comment]
PyInstaller uses option `--distpath`
```

--distpath DIR

Where to put the bundled app (default: ./dist)

```
