### ISSUE TITLE
Cannot figure out how to build an APP with Super Mode

### ISSUE THREAD

**Issue by lilyoungbug** [dashingsoft/pyarmor#305]
Hi, I'm trying to figure out how to build an app with Super Mode. 
What I do is:
`pyarmor obfuscate main.py --advanced 2`
`pyarmor init --src=. --entry=main.py`
`pyarmor build`
`...copy main.spec in /dist`
`pyinstaller main.spec (which gets _pytransform.dll from /pytransform)`
By this way it's being created a /pytransform folder in /dist folder. But if I look to .pyarmor_config the "advanced" parameter is set to 0 and not to 2. If i change the "advanced" parameter in .pyarmor_config no /pytransform folder is being created in /dist. Any solution on how to solve this? Thanks!

**Comment by jondy** [comment]
It's recommend to use `pack`, for example,
```
pyarmor pack -x " --advanced 2" main.py
```
For more information, refer to https://pyarmor.readthedocs.io/en/latest/man.html#pack

**Comment by lilyoungbug** [comment]
Thank you @jondy will give it a try soon and will let you know!

**Comment by lilyoungbug** [comment]
It worked but now I'm getting this exception when the program starts
`attempted relative import beyond top-level package`

**Comment by jondy** [comment]
Use option `--bootstrap 2` to fix this issue, for example,
```
pyarmor pack -x " --advanced 2 --bootstrap 2" main.py
```

**Comment by lilyoungbug** [comment]
Works and no error is show now. But the app immediately exit without showing errors.

**Comment by jondy** [comment]
First make sure the scripts could pack by PyInstaller directly and the final bundle works.

Then make sure the obfuscated scripts could work without packing.

If both of them OK, remove the output path `dist` and PyInstaller cached path `build`, then pack the script with ``--debug``

    pyarmor pack --debug foo.py

The build files will be kept, the patched `foo-patched.spec` could be used by pyinstaller to pack the obfuscated scripts directly, for example

    pyinstaller -y --clean foo-patched.spec

Check this patched `.spec` and change options in this `.spec` file, make sure the final bundle could work.

**Comment by lilyoungbug** [comment]
OK. I basically found out what the issue is.
Building with PyInstaller: `RuntimeError: Invalid product license file`
Running obfuscated script
```pyinstaller --onefile run.py => Script exits without error```
Running builded script
```pyarmor obfuscate --recursive --advanced 2 --bootstrap 2 run.py => APP exits without error```
But removing an import it works.
I think the issue is because PyInstaller gets the license.lic file from this module, which is in the module file.
Any way to bypass this? Thank you.

**Comment by jondy** [comment]
> Building with PyInstaller
> 
> ```
> pyinstaller --onefile run.py => RuntimeError: Invalid product license file
> ```
> 

I mean using Pyinstaller to pack original script to check it works or not. It seems that you're packing the obfuscated scripts.

**Comment by lilyoungbug** [comment]
I'm not packing the obfsucated scripts

**Comment by jondy** [comment]
But this exception is really raised by the obfuscated script:
```
RuntimeError: Invalid product license file
```

**Comment by lilyoungbug** [comment]
It's because there's an obfuscated module with a license.lic file in the build. That's what I'm trying to bypass

**Comment by jondy** [comment]
If you really want to pack the obfuscated scripts, please refer to this guide
https://pyarmor.readthedocs.io/en/latest/how-to-do.html#how-to-pack-obfuscated-scripts

**Comment by lilyoungbug** [comment]
I'm going to wait till the authentication flow changes for the obfuscated module. If it still doesn't work imma write here. Thanks for your help! ❤️

**Comment by lilyoungbug** [comment]
Hi, I'm back haha
```
Current thread 0x00005d8c (most recent call first):
  File "<frozen cloudscraper.exceptions>", line 14 in <module>
  File "cloudscraper\exceptions.py", line 2 in <module>
  File "C:\Users\polo\AppData\Roaming\Python\Python38\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen cloudscraper>", line 48 in <module>
  File "cloudscraper\__init__.py", line 2 in <module>
  File "C:\Users\polo\AppData\Roaming\Python\Python38\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen main>", line 6 in <module>
  File "main.py", line 2 in <module>
  File "C:\Users\polo\AppData\Roaming\Python\Python38\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen run>", line 78 in <module>
  File "dist\obf\run.py", line 2 in <module>
```
Getting this error after building now.

**Comment by lilyoungbug** [comment]
Ok I changed the advanced from 4 to 2 (lol) but it's still not starting.

**Comment by lilyoungbug** [comment]
Ok, I tried to pack the script with PyInstaller first and it worked. But when I pack with PyArmor it simply exits when the script starts. I'm going to do more testa when I get home.

**Comment by jondy** [comment]
I find the problem, you use `cloudscraper`, but this package is obfuscated by pyarmor also. Please obfuscate your script by this way to solve this conflict
```
pyarmor obfuscate -r --advanced 2 --bootstrap 2 --enable-suffix foo.py
```

Refer to https://pyarmor.readthedocs.io/en/latest/advanced.html#solve-conflicts-with-other-obfuscated-libraries

**Comment by lilyoungbug** [comment]
Thank you! It worked.
Have a good day! ❤️
