### ISSUE TITLE
Syntax Error at a location, without any errors

### ISSUE THREAD

**Issue by chwba** [dashingsoft/pyarmor#306]
I have one function a file, if I comment it out, it can obfuscate the project, if commented in it cannot and it will fail with "invalid syntax" but the syntax is correct. I sent you the source via Email.  For compiling I used pyarmor-webui.

**Comment by jondy** [comment]
How about upgrading pyarmor to latest version, it fixes one issue about this
```
pip install --upgrade pyarmor
```

**Comment by chwba** [comment]
Now pyarmor is already the latest version, can you try to reproduce with the source I sent via Email?
