### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by cnaferdie** [dashingsoft/pyarmor#307]
Hi,
I have distributed the whole dist folder after executing pyarmor obfuscate migrate_ap.py to a user but user is getting the error below when they run the obfuscated script. The script works fine on my computer where I obfuscated the script.
Can you please help on this? 

C:\Users\Bob\Desktop\New folder (2)\dist>python migrate_ap.py
Traceback (most recent call last):
  File "migrate_ap.py", line 2, in <module>
    pyarmor_runtime()
  File "C:\Users\Bob\Desktop\New folder (2)\dist\pytransform\__init__.py", l
ine 342, in pyarmor_runtime
    pyarmor_init(path, is_runtime=1, suffix=suffix)
  File "C:\Users\Bob\Desktop\New folder (2)\dist\pytransform\__init__.py", l
ine 337, in pyarmor_init
    _pytransform = _load_library(path, is_runtime, platid, suffix)
  File "C:\Users\Bob\Desktop\New folder (2)\dist\pytransform\__init__.py", l
ine 305, in _load_library
    m = cdll.LoadLibrary(filename)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__
init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Bob\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__
init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by jondy** [comment]
Please run the obfuscated script with 64-bit python in the customer machine, python37-32/python is 32-bit python.

Or you need obfuscate the script with `--platform windows.x86` for this customer, for example,
```
pyarmor obfuscate --platform windows.x86 foo.py
```

More information , refer to https://pyarmor.readthedocs.io/en/latest/advanced.html#distributing-obfuscated-scripts-to-other-platform

**Comment by cnaferdie** [comment]
Thanks a lot for your help!
