### ISSUE TITLE
Faild to get harddisk information.

### ISSUE THREAD

**Issue by yanjieee** [dashingsoft/pyarmor#31]
When I run "pyarmor hdinfo" in windows by administrator , I could get the hardisk information.
But I run the same command in linux , it shows:

`usr01@dovm2:~$ pyarmor hdinfo
/dev/nvme0n1p2: Permission denied
Faild to get harddisk information.

Mac address: '6c:0b:84:aa:c4:d9'

Ip address: '192.168.10.221'

Domain name: '(none)'
usr01@dovm2:~$ ^Carmor hdinfo
usr01@dovm2:~$ whereis pyarmor
pyarmor: /home/usr01/.local/bin/pyarmor
usr01@dovm2:~$ sudo /home/usr01/.local/bin/pyarmor hdinfo
Faild to get harddisk information.

Mac address: '6c:0b:84:aa:c4:d9'

Ip address: '192.168.10.221'

Domain name: '(none)'`

I couldn't get the harddisk info, even though I use sudo command.

**Comment by jondy** [comment]
Download this tool `hdinfo` according to your platform

http://pyarmor.dashingsoft.com/downloads/platforms/win_amd64/hdinfo.exe
http://pyarmor.dashingsoft.com/downloads/platforms/win32/hdinfo.exe
http://pyarmor.dashingsoft.com/downloads/platforms/linux_i386/hdinfo
http://pyarmor.dashingsoft.com/downloads/platforms/linux_x86_64/hdinfo

in windows run `./hdinfo.exe`
in linux run `sudo ./hdinfo`

Show me the error message you got.

**Comment by yanjieee** [comment]
this is the runtime log:
`
usr01@dovm2:~/yanjie/pyarmor$ sudo ./hdinfo 
HDIO_GET_IDENTITY: Inappropriate ioctl for device
Faild to get harddisk information.

Mac address: '6c:0b:84:aa:c4:d9'

Ip address: '192.168.10.221'

Domain name: '(none)'

`

**Comment by jondy** [comment]
It seems HDIO_GET_IDENTITY doesn't supported by your linux system. HDIO_GET_IDENTITY doesn't work in 
linux kernel 2.4, it's supported from linux kernel 2.6.

**Comment by yanjieee** [comment]
我试了一下发现在ubuntu16.04上，硬盘信息都是：“Faild to get harddisk information.”
作者可否更新一下你的hdinfo程序，希望支持ubuntu16.04，谢谢！很希望你这个工具，希望越做越好！

**Comment by jondy** [comment]
正好刚刚更新了一下， :) 主要是增加了对 SCSI 接口的硬盘的支持，原来的不支持 SCSI 接口的硬盘，下载地址:
http://pyarmor.dashingsoft.com/downloads/platforms/linux_x86_64/hdinfo
另外，如果在 docker 下面的运行的话，启动 docker 的时候要把硬盘挂上，另外在有的云服务器上也没有挂硬盘。首先检查一下这个目录 
`ls /dev/disk/by-id`
如果硬盘挂上，这里会显示硬盘的接口和序列号的。如果这里没有显示，那么是无法得到硬盘序列号的。
最后要注意的是获取硬盘序列号必须是超级用户，普通用户没有权限

**Comment by yanjieee** [comment]
刚刚在一台物理机和一台云服务器（腾讯云）试了一下还是不行，奇怪：
![2.png](https://i.loli.net/2019/07/05/5d1ef0c7f19fb50934.png)
![1.png](https://i.loli.net/2019/07/05/5d1ef0c81094e31553.png)

**Comment by jondy** [comment]
云服务器上没有硬盘设备，物理机上面是 usb 接口和NVMe固态硬盘，这两种接口目前都还不支持，后面我找时间把对这两个接口的支持加上

**Comment by yanjieee** [comment]
谢谢，希望可以尽快加入nvme的支持~

**Comment by jondy** [comment]
添加了对 NVME 硬盘的支持，请下载运行一下这个临时读取硬件信息的文件，如果能够读取到 NVME 硬盘的信息的话，那就把这个集成的新版本里面并发布
http://pyarmor.dashingsoft.com/downloads/platforms/linux_x86_64/temp/hdinfo

**Comment by yanjieee** [comment]
测试了新的hdinfo，发现在腾讯云上和一台公司的华为服务器上无法成功，在自己组装的PC上可以成功，请参考：
![华为](https://files.catbox.moe/ifwflc.png)
![组装](https://files.catbox.moe/do72jf.png)
![腾讯云](https://files.catbox.moe/da66ii.png)

**Comment by jondy** [comment]
我在阿里云服务器上也无法获取到硬盘序列号，云服务器上应该都是虚拟的硬盘，获取的意义也不大。

也可以尝试使用 `hdparm -i /dev/xxx` 看一下这些工具能不能获取到。

**Comment by yanjieee** [comment]
我刚刚又试了几台服务器和普通PC，都是ubuntu16.04的系统，发现服务器的都无法获取，PC都可以。

**Comment by yanjieee** [comment]
如果碰到一些云服务器或者其他服务器，您建议是如何做license，只对mac地址做授权，好像不是很稳妥。

**Comment by jondy** [comment]
1. 对于有物理硬盘的服务器，我认为是应该可以通过某种方式获取到硬盘序列号，也许是什么配置，也许是什么东西没有安装等等。
2. 对于云服务器来说，一种方式就是使用 Plugin 扩展认证机制，可以参考
https://github.com/dashingsoft/pyarmor/tree/master/plugins#example-2-check-docker-container-id
通过读取 `/proc` 里面的相关信息进行验证，可以根据自己的需要定制各种认证方式。
3. 对于云服务器来说，一般都会有公网 ip，也可以扩展网络认证方式。这需要能提供一个web方式的认证接口，接受客户端发送的请求认证的信息，并发送验证结果给客户端。

**Comment by yanjieee** [comment]
非常感谢您的建议，茅塞顿开。
希望pyarmor能为更多的python开发者创造价值。

**Comment by flaudanum** [comment]
Hi,
I'm facing a similar issue when running `pyarmor hdinfo` from within a *Docker container*:
```
# pyarmor hdinfo
INFO     PyArmor Trial Version 5.9.0
Faild to get harddisk information.
Mac address: "00:00:00:00:00:00"
Faild to get ip address.
Domain name: "(none)"
```
But I want to build a license including the information about the hard disk. I guess that `pyarmor hdinfo` relies on some Linux OS structure which differs in Docker containers. 

Is there any solution?

Actually I want to ensure that my python app in the container will run on a specific host in order to prevent copies.
Maybe, there was useful information in the previous posts but I unfortunately can't read Chinese symbols. I read that you propose a solution based on container IDs but I do not see how it could be a useful for binding the license to the host.

Thanks for your help.

**Comment by jondy** [comment]
@flaudanum 

First run this command in the docker
```
ls /dev/disk/by-id
```

If there is nothing, try to specify some extra options to mount the harddisk as starting the docker.

**Comment by flaudanum** [comment]
Thanks for your quick reply.

No `disk` nor `sd*` in `/dev`, indeed.
```
# ls -l /dev
total 0
crw--w---- 1 root tty  136, 0 Feb 18 12:41 console
lrwxrwxrwx 1 root root     11 Feb 18 10:21 core -> /proc/kcore
lrwxrwxrwx 1 root root     13 Feb 18 10:21 fd -> /proc/self/fd
crw-rw-rw- 1 root root   1, 7 Feb 18 10:21 full
drwxrwxrwt 2 root root     40 Feb 18 10:21 mqueue
crw-rw-rw- 1 root root   1, 3 Feb 18 10:21 null
lrwxrwxrwx 1 root root      8 Feb 18 10:21 ptmx -> pts/ptmx
drwxr-xr-x 2 root root      0 Feb 18 10:21 pts
crw-rw-rw- 1 root root   1, 8 Feb 18 10:21 random
drwxrwxrwt 2 root root     40 Feb 18 10:21 shm
lrwxrwxrwx 1 root root     15 Feb 18 10:21 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 root root     15 Feb 18 10:21 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 root root     15 Feb 18 10:21 stdout -> /proc/self/fd/1
crw-rw-rw- 1 root root   5, 0 Feb 18 10:21 tty
crw-rw-rw- 1 root root   1, 9 Feb 18 10:21 urandom
crw-rw-rw- 1 root root   1, 5 Feb 18 10:21 zero
```
As mounting volumes with `docker run -v` changes nothing to this issue I suppose that `docker run --device` might be the proper solution. Mounting a Linux host device like `/dev/sda` is quite straightforward but it is far less when it comes to a Windows one (my use case). For now, I will probably try a walkarround with `pyarmor licenses -x`.
Thanks.

**Comment by flaudanum** [comment]
Hi @jondy 

It is clearly not possible to mount a Windows drive (or any physical device) within a Linux container running with Docker desktop for Windows. The command `docker run --device` is inefficient in this context. As a consequence `hdinfo` cannot get this information from within the container.
I eventually developed a solution using `pyarmor license -x` and some basic cryptography.

**Comment by jakkwis** [comment]
Hi, 

I am trying to get a hard disk's SN in Ubuntu container. I have mounted the disk to the container so I can see files in the `/dev/disk/by-id` directory. Even so, it failed executing both pyarmor `hdinfo` and `./hdinfo`. My docker uses `overlay2` storage driver but according to the log, the error comes from `overlay`. Below you can see logs. 

Could you please describe how the script is getting disk's SN so I can solve the error?

```
root@...:/# pyarmor hdinfo
INFO     PyArmor Version 7.2.0
INFO     Python 3.6.9
Hardware informations got by PyArmor:

Failed to get harddisk information.

Default Mac address: "02:42:ac:11:00:02"

Multiple Mac addresses: "<>"

Ip address: "172.17.0.2"

Domain name: "(none)"

Change logs

	v6.2.0(r21): Remove trailing dot from harddisk serial number
	v6.4.2(r34): Support binding multiple mac addresses
	v6.5.3(r37): Support binding named harddisk
	v6.7.5(r45): Support mmc/sd card in Linux


root@...:/# ./hdinfo 
overlay: No such file or directory
Faild to get harddisk information.

Mac address: "02:42:ac:11:00:02"

Ip address: "172.17.0.2"

Domain name: "(none)" 
```
