### ISSUE TITLE
utf-8

### ISSUE THREAD

**Issue by feelingnothing** [dashingsoft/pyarmor#310]
i did add `# -*- coding: utf-8 -*-` to all my scripts but got 
```
РџРѕРјРѕС‰СЊ
Р‘РѕС‚ РґР»СЏ РїСЂРѕРґР°Р¶Рё СЂРѕР»РµР№
.products - РћС‚РїСЂР°РІР»СЏРµС‚ СЃРїРёСЃРѕРє РІСЃРµС… РїСЂРѕРґР°РІР°РµРјС‹С… СЂРѕР»РµР№ РІ Р»СЃ
.productx add - РћС‚РєСЂС‹РІР°РµС‚ РјРµРЅСЋ РґР»СЏ СЃРѕР·РґР°РЅРёСЏ СЂРѕР»Рё
.products buy - РћС‚РєСЂС‹РІР°РµС‚ РјРµРЅСЋ РїРѕРєСѓРїРєРё СЂРѕР»РµР№
```
(was in russian)

**Comment by jondy** [comment]
Make sure the scripts are also utf-8 encoded. Most of model editors could check and convert file encodings.

**Comment by feelingnothing** [comment]
@jondy 
![изображение](https://user-images.githubusercontent.com/47575622/90454595-67701300-e0fc-11ea-8334-299e6ab332f5.png)

**Comment by jondy** [comment]
For pyarmor < 6.3.7, there is a bug if the encoding line is in the second line. In this case, move it to first line or upgrade pyarmor.

If all the encoding lines is in the first line, obfuscate a simple script `foo.py` and run it
```python
# -*- coding: utf-8 -*-
print('РџРѕРјРѕС‰СЊ')
```
Check it work or not.

**Comment by feelingnothing** [comment]
foo.py
```python
# -*- coding: utf-8 -*-
print('Привет')
input()
```
Output:
```
╧ЁштхЄ
```
Command I used `pyarmor obfuscate foo.py`

**Comment by jondy** [comment]
What's the environment variable `LANG`, check it
```
echo $LANG

# For windows
echo %LANG%
```

If it's not `utf-8`, for example, `en_US.UTF-8`, change it to utf-8

**Comment by feelingnothing** [comment]
Im thinking about to move a text to `settings.py` and replacing that file with not obfuscated version of it
