### ISSUE TITLE
Problem with First execution !

### ISSUE THREAD

**Issue by s265925** [dashingsoft/pyarmor#314]
Hi, 
I successfully obfuscate my script with Pyarmor.
But when I move it to a new system when I run it for the first time it gives the error.
and **For second execution everything works fine.**
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from pytransform import pyarmor_runtime
ModuleNotFoundError: No module named 'pytransform'
```

Since in my scenario I need it to start successfully at first execution ! could you please help me?
What am I doing wrong?

**Comment by jondy** [comment]
Do not obfuscate system modules, if there is virtual environment in the current path, exclude this path by option `--exclude`, and also do not obfuscate `pytransform.py`

**Comment by s265925** [comment]
> Do not obfuscate system modules, if there is virtual environment in the current path, exclude this path by option `--exclude`, and also do not obfuscate `pytransform.py`

Thanks jondy,
I checked your suggestions, The `pytransform.py` and system modules is not obfuscated . And there is no virtual environment.

Also Strange thing happens:
I have two separate computer with fresh OS( Linux Debian ),in one of them working perfectly and in other one same problem!!

**Comment by jondy** [comment]
No idea why first execution fails only. When loading pytransform.py at first time, it will do some checks, it may fail in some cases, but it should not report `ModuleNotFoundError`.
