### ISSUE TITLE
Eventual bug if running on Windows Server 2019

### ISSUE THREAD

**Issue by chwba** [dashingsoft/pyarmor#316]
I am experiencing increasing weirdnesses, when trying to run the obfuscated code on Windows Server 2019. It does obfuscate find but when starting the app, the behaviour is weird, sometimes it works, sometimes completely broken, sometimes weird behaviour. I suggest you run some tests on this OS, to find out the cause for it.

I tested running the code directly from the IDE on this OS and it works fine. The problems do not seem to happen on Windows 10 Professional. 

If you want I can offer to provide debug logs or alike when trying to run/compile on Windows Server.

**Comment by jondy** [comment]
I really don't test on Windows 2019, I have no this platform on hand.  But if you pack a `.exe` in Windows 10, and run this `.exe` in Windows 2019, it may not work. In this case, try to pack the scripts in Windows 2019, because pack command put many system dynamic libraries into final bundle, they may not compatible in different platforms.

**Comment by chwba** [comment]
In my example app, I only obfuscate all scripts but not to exe, then run app with embedded python as in `python app.py`. In fact I tried packing on Windows 2019 itself and tried to run but it still caused weirdness, if you want we can use my machine for debugging, I have a RDP with Windows Server 2019.

**Comment by jondy** [comment]
Thanks, could you send me an user and available time, I'll do some tests.

**Comment by chwba** [comment]
Ill send you some details via mail.

**Comment by Seraphppy** [comment]
> Ill send you some details via mail.

Please keep us updated on this, we have the same issues

**Comment by jondy** [comment]
@Seraphppy are the scripts obfuscated by `--advanced 4` or `--advanced 2`?  And what' the error messages?

**Comment by Seraphppy** [comment]
> @Seraphppy are the scripts obfuscated by `--advanced 4` or `--advanced 2`? And what' the error messages?

Sorry for late reply Jondy

we use restrict mode 3 and advanced mode 2

Error is always: Failed to execute script Main on all servers

**Comment by jondy** [comment]
@Seraphppy how about only obfuscating the scripts without packing? If not work, is there any extra error message?

**Comment by Seraphppy** [comment]
We are suspecting that its not pyarmor actually that is causing this, might be pyinstaller not collecting everything it needs when being packed! Will try and obfuscate only and send to a server where its breaking and see if its pyarmor or pyisntaller!
