### ISSUE TITLE
I have more exes and more space( pyinstaller and pyarmor)

### ISSUE THREAD

**Issue by isdito** [dashingsoft/pyarmor#319]
I would like to know if you can help me with this problem.

I have an application based on 7 independent executables that I connect by sub-process

The application works well but each exe occupies 60 to 100 megs

```
pyarmor pack -e " --onefile --icon=logo2.ico" slider-photos-web.py
pyarmor pack -e " --onefile --icon=logo2.ico" slider-photos-presentacion.py
pyarmor pack -e " --onefile --icon=logo2.ico" ejecutor.py
pyarmor pack -e " --onefile --icon=logo2.ico" interface.py
pyarmor pack -e " --onefile --icon=logo2.ico" hot_folder.py
pyarmor pack -e " --onefile --icon=logo2.ico" postproduccion.py
pyarmor pack -e " --onefile --icon=logo2.ico" hot_folder.py
```

There is some possible way to optimize, just creating the exe of the py and the other standard and equal libraries are all together.

I have tried to compile without --onefile  and put everything in a folder but it does not work.

```
pyarmor pack -e " --icon=logo2.ico" slider-photos-web.py
pyarmor pack -e " --icon=logo2.ico" slider-photos-presentacion.py
pyarmor pack -e " --icon=logo2.ico" ejecutor.py
pyarmor pack -e " --icon=logo2.ico" interface.py
pyarmor pack -e " --icon=logo2.ico" hot_folder.py
pyarmor pack -e " --icon=logo2.ico" postproduccion.py
pyarmor pack -e " --icon=logo2.ico" hot_folder.py
```
If someone can help me to find a good solution.

**Comment by jondy** [comment]
First pack one main exe with all the dependencies of other scrips, for example, modules `a` and `b` are required by `hot_folder.py` but not required by `slider-photos-web.py` 
```
pyarmor pack -e " --icon=logo2.ico --hidden-import a --hidden-import b" slider-photos-web.py
```

Then obfuscate the other script, and copy only executable to main script folder, for example
```
pyarmor pack -e " --icon=logo2.ico" -x " --no-cross-protection" hot_folder.py
cp dist/hot_folder/hot_folder.exe dist/slider-photos-web/
```

**Comment by isdito** [comment]
Good morning thank you, Jondy I don't get much clearer 

You tell me that I have to root "interface.py" import all the modules from all the others "slider-photos-web.py" "ejecutor.py"
"hot_folder.py" "slider-photos-presentacion.py"


or just the ones they don't have in common? 

or just the ones that are not in any of the files 
 "slider-photos-web.py" "ejecutor.py" "hot_folder.py" "slider-photos-presentacion.py"

Translated with www.DeepL.com/Translator (free version)

**Comment by jondy** [comment]
The ideas is to first build one major exe with all required modules, for all the other scripts, just copy one executable file to main folder.

if you take `interface.py` as major script, it's good idea to import all the others  "slider-photos-web.py" "ejecutor.py"
"hot_folder.py" "slider-photos-presentacion.py" in it, thus no hidden import required.

**Comment by isdito** [comment]
Good morning,

I put all the imports in interface.py  but I don't compile with -onefile.

And what do I do next with "slider-photos-web.py" "ejecutor.py"
"hot_folder.py" "slider-photos-presentacion.py"

pyarmor pack -e " --icon=logo2.ico --hidden-import a --hidden-import b" slider-photos-web.py

 --hidden-import all modules that have been put in .py interface

The problem with this is that afterwards I can't keep working with those py... and I have to do this every time I want to compile it.

Translated with www.DeepL.com/Translator (free version)

**Comment by jondy** [comment]
> Good morning,
> 
> I put all the imports in interface.py but I don't compile with -onefile.
> 
> And what do I do next with "slider-photos-web.py" "ejecutor.py"
> "hot_folder.py" "slider-photos-presentacion.py"
> 
> pyarmor pack -e " --icon=logo2.ico --hidden-import a --hidden-import b" slider-photos-web.py
> 
> --hidden-import all modules that have been put in .py interface
> 

No any hidden import for other scripts,  just pack it with --no-cross-protection, for example,
```
pyarmor pack -e " --icon=logo2.ico" -x " --no-cross-protection" slider-photos-web.py
pyarmor pack -e " --icon=logo2.ico" -x " --no-cross-protection" slider-photos-presentacion.py
...
```

Then copy the final executable to `dist/interface`

**Comment by isdito** [comment]
Yes I am thinkin in import all interface.py   but the problem that I have it is control the state of the process and execute the python

```
def _slide_dos(self,event):
	
		if(licenciado):
			if(proceso_slide2=="1"):
				try:
					print ("Matando procesos de slider web")
					PROC_NAME = "slider-photos-web.exe"
					for proc in psutil.process_iter():
						if proc.name() == PROC_NAME:
								proc.kill()
				except:
					print ("proceso ya apagdo")
				self.slider_on_dos.SetBackgroundColour('ligth gray')
				self.slider_on_dos.SetLabel("slider web off")
				SetValueEx(key, "slider2", 0, REG_SZ, "0")
				CloseKey(key)
			else:
				self.slider_on_dos.SetBackgroundColour('red')
				self.slider_on_dos.SetLabel("slider web on")
				process3 =subprocess.Popen([ os.getcwd()+'\\'+"slider-photos-web.exe",str(globales.delay),str(globales.mute),str(globales.tipo_slide),str(globales.orden),str(globales.bucle),str(globales.limit_foto),str("1")],shell=False)
				SetValueEx(key, "slider2", 0, REG_SZ, "1")
				CloseKey(key)
```

I could change


`process3 =subprocess.Popen([ 'python', os.getcwd()+'\\'+"slider-photos-web.py",str(globales.delay),str(globales.mute),str(globales.tipo_slide),str(globales.orden),str(globales.bucle),str(globales.limit_foto),str("1")],shell=False)`

But 'pyhton'   ->> what do i do with python if the client doesn't have it?

**Comment by jondy** [comment]
You need insert these import statements in the `interface.py`, not call them by `Popen`
```
import slider_photos_web
import slider_photos_presentacion
import ejecutor
...
```
After that, pyinstaller could find the all the required dependent modules by other scripts. Because `slider-photos-web.py` include dash, copy it to `slider_photos_web.py`, so that it can be imported.

**Comment by isdito** [comment]
Yes I know that, but I need that stay in a subprocess because interface.py it is Tk  mainloop.

I need  control the process and if I like delete de process

I'll look to see how I solve it is that it doesn't give me the head
reggards

**Comment by jondy** [comment]
Remember this, in the runtime bundle of PyInstaller, the current path is not `os.getcwd()` but `sys._MEIPASS`, refer to https://pyinstaller.readthedocs.io/en/stable/runtime-information.html

**Comment by isdito** [comment]
![image](https://user-images.githubusercontent.com/602151/91274632-4a33e800-e77f-11ea-85db-45da8e771f7d.png)

I could import  hot_folder.py

and call

`process3 =subprocess.Popen([ 'python', slider ]),shell=False)
`
what i don't understand is what i'm doing with python on that call. How the client is going to find python if he doesn't have it installed.

I feel my English level Jondy I don't know if you are understanding me.

**Comment by isdito** [comment]
> Remember this, in the runtime bundle of PyInstaller, the current path is not `os.getcwd()` but `sys._MEIPASS`, refer to https://pyinstaller.readthedocs.io/en/stable/runtime-information.html

When I cange say me this

print("ruta que esta", sys._MEIPASS)
AttributeError: module 'sys' has no attribute '_MEIPASS'

**Comment by jondy** [comment]
About how to use `subprocess` in the PyInstaller, it's better to ask in the pyinstaller issues. Here is focused on obfuscated scripts problem.

**Comment by isdito** [comment]
thank you Jondy

**Comment by isdito** [comment]
Jondy please resolve me this, I know that it is not your functions but I hope you help me.

I will like send a task but with parameters, I not find the solution.

This lines not works

```
self._slider_presentacion = BackgroundTask(slider_presentacion(globales.delay))
self._slider_presentacion = BackgroundTask(lambda c=globales.delay:slider_presentacion(c))
```
Here are the class that I take of internet... any one could modify to take *args
```

class BackgroundTask():

    def __init__( self, taskFuncPointer ):
        self.__taskFuncPointer_ = taskFuncPointer
        self.__workerThread_ = None
        self.__isRunning_ = False

    def taskFuncPointer( self ) : return self.__taskFuncPointer_

    def isRunning( self ) : 
        return self.__isRunning_ and self.__workerThread_.isAlive()
    
    def start( self ): 
        if not self.__isRunning_ :
            self.__isRunning_ = True
            self.__workerThread_ = self.WorkerThread( self )
            self.__workerThread_.start()

    def stop( self ) : self.__isRunning_ = False

    class WorkerThread( threading.Thread ):
        def __init__( self, bgTask ):      
            threading.Thread.__init__( self )
            self.__bgTask_ = bgTask

        def run( self ):
            try :
                self.__bgTask_.taskFuncPointer()( self.__bgTask_.isRunning )
            except Exception as e: print (repr(e))
            self.__bgTask_.stop()
```
reggards

**Comment by jondy** [comment]
@isdito it's too complex, and `slider_presentacion` is unknown. Please check the traceback and add some print statement in your script to find where's problem.

**Comment by isdito** [comment]
ok thank you I finally eliminate vars and create global vars.
