### ISSUE TITLE
transfer python in windows to rasberry pi

### ISSUE THREAD

**Issue by isdito** [dashingsoft/pyarmor#320]
Hello,

The license of pyarmor "pyarmor-regfile-1.zip"  I could execute in a rasberry py

I am installing vmware and rasberry pi to past the 3 scripts and compille . 

it is posible the same license? if it is the same computer with diferent operating system

reggards

**Comment by jondy** [comment]
Yes, you can use same license in different machine and different os.

**Comment by isdito** [comment]
Hello, I see all the day past the code to Rasberry, but finally I think that only
