### ISSUE TITLE
Completely uninstall and unregister pyarmor

### ISSUE THREAD

**Issue by mdtlyf** [dashingsoft/pyarmor#321]
Hi,

Not sure how to completely uninstall and unregister pyarmor.

I've got several projects to obfuscate, and I release them via docker image. What I do is that I build the docker images following normal process, and at the end, install pyarmor inside the docker image, register it and obfuscate files. Once it is done, uninstall pyarmor and also remove `/root/.pyarmor_capsule.zip`, then tag the image and release it. I just want to make sure that my credentials SHALL NOT stay inside the docker image, so I'd like to confirm my steps are complete.

Or maybe there could be an uninstall and unregister guide in the documentation so we can refer for changes with version upgrade. I'm using version 6.2.1 currently.

Thanks

**Comment by jondy** [comment]
Here it is
https://pyarmor.readthedocs.io/en/latest/installation.html#clean-uninstallation

**Comment by mdtlyf** [comment]
My bad! Shall go over the doc first... Thank you
