### ISSUE TITLE
how to make execute exe in mac os

### ISSUE THREAD

**Issue by devlop7** [dashingsoft/pyarmor#327]
hell i was trying to run this command in mac
pyarmor pack -e " --onefile" foo.py

eveything is okey but the execute file is not exe
how to make it exe
i'm using mac os

**Comment by jondy** [comment]
Does it work to pack a simple script by Pyinstaller, for example,
```
pyinstaller --onefile foo.py
```

Also refer to https://pyinstaller.readthedocs.io/en/stable/usage.html#mac-os-x

**Comment by devlop7** [comment]
i wanna to mac it with the 
pyarmor pack -e " --onefile" foo.py
how

**Comment by jondy** [comment]
If `pyinstaller --onefile foo.py` works, `pyarmor pack -e " --onefile" foo.py` should work either. The output file should be executed directly.

**Comment by devlop7** [comment]
it work but the file comes out without .exe
when i try to run it in windows os
i rename it to foo.exe
and it doen't work it said
this app can't run on your pc
to find a version fr your pc , check with the software publisher.

**Comment by jondy** [comment]
The command pack does not support cross platform, it is impossible to build an executable for Windows in MacOS. The only way is, packing the script in Windows.
