### ISSUE TITLE
Python For Android Obfuscation

### ISSUE THREAD

**Issue by iagosantiago** [dashingsoft/pyarmor#328]
I'm trying to obfuscate a project that already runs well with PyArmor on Windows and Linux, it's cross platform and i'm trying to obfuscate the Android version, but without success, i checked other issues like #207 , but i always get this error when i run the app:

![Screenshot_20200911_163401](https://user-images.githubusercontent.com/58311733/92966483-294de100-f467-11ea-9fd7-a2d094e35a64.png)

OS Version: Arch Linux
Python Version: 3.8
PyArmor Version: 6.2.9 (Premium)
Android Version: 10
Build Tool: Buildozer

**Comment by jondy** [comment]
What's exact arch in this platform? For example, X86_64 or ARMv7. And Which libc is it built with? glibc, musl or static libc

**Comment by iagosantiago** [comment]
It's a ARMv7 build running on Android.

**Comment by jondy** [comment]
There are 3 platforms for armv7,  `android.armv7` for staic libc, `linux.armv7` for glibc and `uclibc.armv7` for uclibc. Which one are you used? How about obfuscating the scripts with others? For example,
```
pyarmor obfuscate --platfrom uclibc.armv7 foo.py
```

**Comment by iagosantiago** [comment]
Can linux.armv7 and uclibc.armv7 work on Android?

**Comment by jondy** [comment]
These dynamic libraries work in any linux platform, but linked to different libc. For example, `linux.armv7` is built with dynamic library `libc-6.so`, I don't know which libc used in your Android platform, so just try it.

**Comment by iagosantiago** [comment]
Okay, i'll test it, in a few hours i will return with the result.

**Comment by 47hxl-53r** [comment]
I created a python script, Trying to Obfuscate it for android platforms like Termux. How can i Obfuscate My script from Kali linux machine for android platforms

**Comment by jondy** [comment]
Please check the support platforms in the online documetation.
