### ISSUE TITLE
RuntimeError: PyArmor does not work with this core library (r31), which reversion < 32

### ISSUE THREAD

**Issue by newbieh4cker** [dashingsoft/pyarmor#331]
![image](https://user-images.githubusercontent.com/23703741/93034057-c0878400-f673-11ea-88bf-abc28c138cee.png)

after upgrading pyarmor to 6.4.0, above error occurs.

environment is..
python : 3.5
os : centos6.10 (official docker container)

**Comment by jondy** [comment]
Please upgrade platform library by this command
```
pyarmor download --upgrade
```

**Comment by newbieh4cker** [comment]
'pyarmor: error: unrecognized arguments: --upgrade'

**Comment by newbieh4cker** [comment]
₩pyarmor: error: unrecognized arguments: --upgrade₩

**Comment by newbieh4cker** [comment]
pyarmor: error: unrecognized arguments: --upgrade

**Comment by jondy** [comment]
Well, remove path `~/.pyarmor/platforms`, then obfuscate the scripts.
