### ISSUE TITLE
Segmentation fault/ImportError on entry scripts of obfuscated Django app

### ISSUE THREAD

**Issue by mancabizjak** [dashingsoft/pyarmor#332]
First, thank you for this amazing project! I'm testing pyarmor on a Django application, just trying to get the obfuscated app up and running with any of the two configured entry scripts.

### Pyarmor project configuration
Here's the output of `pyarmor info` for my project:

```
INFO     PyArmor Trial Version 6.4.0
INFO     Project  information
               version: 2.0
                  name: testproject
                 title: testproject
                   src: app
            is_package: 1
              manifest: global-include *.py, prune dist, prune test
                 entry: testproject/wsgi.py,manage.py
                output: dist
          runtime_path: None
         restrict_mode: 1
              obf_code: 1
               obf_mod: 2
             wrap_mode: 1
         advanced_mode: 0
        bootstrap_code: 1
      cross_protection: 1
               plugins: None
              platform: None
       package_runtime: 1
         enable_suffix: 0
          license_file: None
```
I successfully run `pyarmor build -B` from the directory containing the above `.pyarmor_config`.

### What I expected to happen
The resulting obfuscated entry scripts `manage.py` or `testproject/wsgi.py` scripts run normally.

### What actually happened
Both entry scripts produce errors - I get `Segmentation fault` when running obfuscated `manage.py`, and `ModuleNotFoundError` when running `testproject/wsgi.py`.

  #### Entry script manage.py
   ```
   [me@localhost testproject]$ cd dist
   [me@localhost dist]$ python manage.py migrate
   Segmentation fault
   ```
  Running `python -vd manage.py migrate` suggests that something breaks while importing the pyarmor runtime package (everything but last debug line omitted below):
    
    # omitted debug output for brevity
    import 'pytransform' # <_frozen_importlib_external.SourceFileLoader object at 0x7fab915dd898>
    Segmentation fault

 The generated `pytransform.log`  contains just the following line: `The core library version: r32, age: 6, features: 7`.

  #### Entry script wsgi.py
  ```
   [me@localhost dist]$ python testproject/wsgi.py
   Traceback (most recent call last):
     File "testproject/wsgi.py", line 1, in <module>
       from pytransform import pyarmor_runtime
   ModuleNotFoundError: No module named 'pytransform'
   ```

### Additional context
Pyarmor version: 6.4.0 (trial)
Python version:  3.6.8

`Segmentation fault` only occurs when I'm building and running the app on a CentOS 8 host. With exactly the same `.pyarmor_config`, I am able to build & run the `manage.py` entry script on a CentOS 7 host (running exactly the same version of Python), and on a Ubuntu 16.04 host running Python 3.7. However, the `ModuleNotFoundError` when running the `wsgi.py` entry script persists on all three hosts. 

I tried tweaking the config by setting different `bootstrap_code`, disabling cross-protection, modifying the `obf_mode`, and then re-running `pyarmor build -B`, but both issues persist regardless.

**Comment by jondy** [comment]
If there is any virtual python path, for example `venv` in the source path, please exclude this path. Obfuscating system library may result in `ModuleNotFoundError`.

About `Segmentation fault`, first run the obfuscated scripts with `-d` to check the error message, then check runtime file `_pytransform.so` by this command
```
ldd pytransform/_pytransform.so
```

Also refer to this example
https://pyarmor.readthedocs.io/en/latest/examples.html#running-obfuscated-django-site-with-apache-and-mod-wsgi

**Comment by mancabizjak** [comment]
Thanks, I double-checked and I can verify that I'm not obfuscating any system libraries. My virtual environment is outside the configured `src` path for the project, so it does not get picked up by `pyarmor`. Also, the output of `pyarmor build` suggests the same thing (i.e. that only the scripts that I want are getting obfuscated).

Here's the output of `ldd pytransform/_pytransform.so`:
```
linux-vdso.so.1 (0x00007ffd220db000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007fb640126000)
libc.so.6 => /lib64/libc.so.6 (0x00007fb63fd64000)
/lib64/ld-linux-x86-64.so.2 (0x00007fb640656000)
```
When I run the `ldd` command on the other two machines that are not giving me segmentation faults, the output looks pretty much the same.

Running the obfuscated entry script (the one that gives segmentation faults) produces no output beside `Segmentation fault`. The output is the same when I run it with `-d`, while `pytransform.log` says `The core library version: r32, age: 6, features: 7` and nothing else. 

Even if I bypass my `pyarmor` project configuration and follow the [pyarmor guide on running Django projects](https://pyarmor.readthedocs.io/en/latest/examples.html#running-obfuscated-django-site-with-apache-and-mod-wsgi) word by word, the outcome when I run obfuscated entry scripts is the same (`Segmentation fault` + `ModuleNotFoundError`).

Is there anything else I can check?

**Comment by jondy** [comment]
About `ModuleNotFoundError`, please copy the folder `dist/pytransform` to `dist/testproject/pytransform`, then run `dist/testproject/wsgi.py`, it seems `pytransform` is not in the python path.

About `Segmentation fault`, how about obfuscating a simple scripts and run it?
```
pyarmor obfuscate --exact foo.py
python dist/foo.py
```

**Comment by jondy** [comment]
And does other `manage.py` command `Segmentation fault`, for example,
```
cd dist
python manage.py runserver
```

**Comment by mancabizjak** [comment]
The obfuscated `manage.py` results in segmentation fault regardless of what arguments I provide (`--help`, `makemigrations`, `runserver`, ...).

I copied the runtime package as you suggested - the import now works, however I'm now getting `Segmentation fault` when I run `wsgi.py` script too.

And unfortunately, obfuscating any other python script (I tried several ones) does not seem to work either, as I always get the same error - segmentation fault.

Not sure if this is helpful, but I tried using `faulthandler` and it seems that the error occurs when `pyarmor_runtime` is called, before the obfuscated script starts executing.
```
>>> import faulthandler; faulthandler.enable()
>>> from pytransform import pyarmor_runtime
>>> pyarmor_runtime()
Fatal Python error: Segmentation fault

Current thread 0x00007fe9c80e8740 (most recent call first):
  File "/home/me/testproject/dist/testproject/pytransform/__init__.py", line 75 in init_pytransform
  File "/home/me/testproject/dist/testproject/pytransform/__init__.py", line 57 in wrap
  File "/home/me/testproject/dist/testproject/pytransform/__init__.py", line 338 in pyarmor_init
  File "/home/me/testproject/dist/testproject/pytransform/__init__.py", line 342 in pyarmor_runtime
  File "<stdin>", line 1 in <module>
Segmentation fault
```

**Comment by jondy** [comment]
Try to disable advanced mode by editing the file `pytransform.py` which locates in the installed path of pyarmor, in the function `_load_library`, uncomment about line 326. The final code looks like this:
```
# Disable advanced mode if required
m.set_option(5, c_char_p(1))
```

Then obfuscate a simple script and run it.

**Comment by maxclaey** [comment]
@jondy I have a setup where I get segmentation faults, similar to what's described here. When I disable the advanced mode, as described in you comment above, the issue disappears. Is there a way to achieve the same result by means of parameters, without having to change the pyarmor source code? Thanks in advance!

**Comment by jondy** [comment]
@maxclaey how about upgrading Pyarmor to latest version. Or obfuscate the scripts by super mode with option `--advanced 2`

**Comment by maxclaey** [comment]
Thanks for your quick response, @jondy. Updating pyarmor to the latest version (6.5.6) seems to solve the issue. Are there any reasons not to update? Are there risks involved when the obfuscated packages will be used in combination with other packages that are obfuscated with an older version (6.2.8 in this case)? Thanks in advance!

**Comment by jondy** [comment]
It couldn't be mixed with old versions < 6.3.0. All the scripts need to be obfuscated again.

**Comment by maxclaey** [comment]
@jondy Thanks for your response! I have one more issue left: with the new version it seem we can no longer obfuscate packages using `--platform linux.x86_64`, `--platform linux.aarch64` and `--platform linux.ppc64` simulateously. Do you have any solution for this? With pyarmor==6.2.8 this worked just fine, but with pyarmor==6.5.6 (needed to solve the issue above), we get the following in this scenario:
`RuntimeError: Multi platforms conflict, platform linux.ppc64.0 could not mixed with linux.x86_64.7`

**Comment by jondy** [comment]
@maxclaey try this option `--platform linux.x86_64.0, --platform linux.aarch64.0 and --platform linux.ppc64.0`

**Comment by maxclaey** [comment]
@jondy Thanks for your quick response. Adding the `.0` suffix to the platforms indeed seems to work. Could you inform me on the impact of updating pyarmor from 6.2.8 and 6.5.6, and adding the `.0` suffixes to the platforms? My initial problem (segmentation faults) is resolved now. Furthermore, after some initial tests, it turns out that packages obfuscated with 6.5.6 can still be used in combination with other packages that were obfuscated before with 6.2.8, in contrast to what was expected?

**Comment by jondy** [comment]
Please refer to
https://pyarmor.readthedocs.io/en/latest/platforms.html

And 
https://pyarmor.readthedocs.io/en/latest/change-logs.html
