### ISSUE TITLE
Is pyarmor suseptable to monkey patching?

### ISSUE THREAD

**Issue by NoahCardoza** [dashingsoft/pyarmor#335]
I'm looking into pyarmor to package a module (not as an app) and I was wondering if there was any protection against "monkey patching attacks"?

For example, if someone imports `urlopen` before I call it and replaces it with their own function which is able to snatch the request payload before it even hit's my servers?

Thanks for the awesome package!
Noah

**Comment by jondy** [comment]
pyarmor provides a solution by decorator `assert_armored`, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#checking-imported-function-is-obfuscated

**Comment by NoahCardoza** [comment]
By the looks of it, this wouldn't work for builtin library methods, right? It also occurred to me that people could straight up modify the library code before running Python so I decided to encrypt the payload I was sending as an extra precaution.

**Comment by jondy** [comment]
It works for any `.py` files, but not for any binary extension `.pyd`, `.so` etc.

**Comment by NoahCardoza** [comment]
Alright, I'll do some of my own testing but this looks promising!
