### ISSUE TITLE
Is it possible to set a password for a license?

### ISSUE THREAD

**Issue by Trizalio** [dashingsoft/pyarmor#34]
I want to protect code on a VM, so datetime and hardware information can be altered by customer. I think password with licence can solve this problem - customer still will be able to restore a VM state with my app running, but can not get or modify its source code. Its an acceptable result for me.
So is it possible to set a password for a license? I suggest, it should be requested only once and kept in some salted hash to reuse on each obfuscation
Other idea is to remove licence file from disc and pass it after start, it`s quite the same in usage.

**Comment by jondy** [comment]
Another example for linux vm

First get cpuinfo in vm
```
cat /proc/cpuinfo > vm_cpuinfo
```
Copy `vm_cpuinfo` to build machine `~/vm_cpuinfo`, generate a license file bind to this file
```
python pyarmor-deprecated.py license --with-capsule=projects/myproject/.pyarmor_capsule.zip \
            --output=fixed-license.lic --bind-file=~/vm_cpuinfo /proc/cpuinfo
```
Finally copy `fixed-license.lic` to vm machine, rename it as `license.lic`

**Comment by Trizalio** [comment]
Thanks for the answer!
Binding licence to cpuinfo is interesting, and can be useful for sure. 
However in my case cpuinfo and all disc contents(including keys) will be the same in both situations, legal and illegal use of my app. All hardware data can be copied and emulated, so i have to request some remote information on app start. Password is an easy way - I can start my app in a VM through ssh, so password is quite hard to capture in transmission. App can keep password in some salted hash state, so memory dump will be useless too. 
So i assume password is secure way to protect my code in VM.

**Comment by jondy** [comment]
How about this way:
```
# First generate a license file bind to fixed file ~/.ssh/id_rsa
python pyarmor-deprecated.py license --with-capsule=projects/myproject/.pyarmor_capsule.zip \
            --output=fixed-license.lic --bind-file=~/.ssh/id_rsa /path/to/obfuscated-scripts/id_rsa

# Then copy them to vm by scp
scp ~/.ssh/id_rsa fixed-license.lic user@vm.ip.addr:/path/to/obfuscated-scripts
```

Now log in vm by ssh, run the following command:
```
cd /path/to/obfuscated-scripts/id_rsa
mv fixed-license.lic license.lic

# Run obfuscated script
python main.py &

# Remove fixed file: id_rsa
rm id_rsa
```

Before run obfuscated scripts in vm, copy `~/.ssh/id_rsa` to vm, after that, remove this fixed file from vm.

**Comment by jondy** [comment]
For this issue, the best solution maybe is to implement this authentication in the obfuscated script by Python, because the end user can't change the obfuscated any more.
