### ISSUE TITLE
Numba fails in analyzing bytecode step

### ISSUE THREAD

**Issue by Daniel451** [dashingsoft/pyarmor#340]
I wanted to test if `pyarmor` works nicely with [numba](https://numba.pydata.org/), so I wrote some little test script:

```python
import argparse
from numba import jit
import timeit

@jit(nopython=True)
def fibonacci_jit(n: int):
    if n == 1:
        return 0
    elif n == 2:
        return 1
    elif n > 2:
        return fibonacci_jit(n-2) + fibonacci_jit(n-1)
    else:
        return -1


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('--fib_num', type=int, required=True, help='fibonacci number to compute')
    args = parser.parse_args()
    n = args.fib_num
    print("fibonacci number:", fibonacci_jit(n))
    iterations = 5
    t = timeit.timeit("fibonacci_jit(n)", setup="from __main__ import n, fibonacci_jit", number=iterations)
    print("time:", t / iterations)
```

When executing `fibonacci.py --fib_num 10` directly, it works without any problems.

Executing `dist/fibonacci.py --fib_num 10` however throws an exception:
```
Traceback (most recent call last):
  File "<dist/fibonacci.py>", line 3, in <module>
  File "<frozen fibonacci>", line 90, in <module>
  File ".../lib/python3.8/site-packages/numba/core/dispatcher.py", line 418, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File ".../lib/python3.8/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File ".../lib/python3.8/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (<237>) found

File "<frozen fibonacci>", line 12:
<source missing, REPL/exec in use?>
```

Any ideas?

**Comment by jondy** [comment]
What pyarmor does is hiding byte code in runtime, so any package which try to read byte code of obfuscated scripts doesn't work. Generally security conflicts with performance.

There are 2 solutions for this case
1. Do not obfuscate the related scripts
2. Obfuscate the related scripts with --obf-code=0 separately

**Comment by Daniel451** [comment]
@jondy thank you for the fast reply!

According to the [documentation](https://pyarmor.readthedocs.io/en/latest/mode.html#obfuscating-code-mode) `--obf-code=0` each code object will be kept "as is". However, the documentation does not give detailed information about the security level. It is just mentioned that, for example, `--obf-code=1`  -> `code object of each function will be obfuscated in different ways` or `--obf-code=2` -> ` obfuscating bytecode by more complex algorithm`.

Of course I am not expecting a formal description of the algorithms in use, but it would be very nice if you could clearify the level security each mode implies:
1. Does mode 0 (code object will be kept "as is") imply no security whatsoever?
2. I assume mode 1 is then the first mode that really obfuscates the code? Is "more complex algorithm" the only difference of mode 2? Or does mode 2 also incorporate, for example, more passes of encoding/decoding?

**Comment by jondy** [comment]
Yes, `--obf-code=0` means each code object (function) is not obfuscated, only the whole module is obfuscated. It's really less security. `--obf-code=1 or 2` would obfuscate each code object, but other package could not read the byte code.

**Comment by Daniel451** [comment]
@jondy thanks for the clarification. So `--obf-code=0` still involves obfuscation, but at module-level? Less secure, obviously, but it would still provide _some_ security and code still would _not_ be readable by someone else + license license could also be added to the distribution, right?

**Comment by jondy** [comment]
Yes. It's exactly as you understand.

**Comment by Daniel451** [comment]
Okay, thank you very much!
