### ISSUE TITLE
The expired license (the deadline remains) can be used with other obfuscated scripts

### ISSUE THREAD

**Issue by h1-ti** [dashingsoft/pyarmor#344]
Hi! I purchased a pyarmor license.
I'm currently distributing obfuscated code and issuing new outer licenses when my subscription is renewed by the server every month. 
And now I'm thinking of distributing a trial version of this app. There is a problem.  If I allow the server to automatically issue a trial license, they can copy the license to the paid version and use it for free. Do you have any good ideas to prevent this?
Thank you.

**Comment by jondy** [comment]
You may check license with your private policy by plugin.  Refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#using-plugin-to-extend-license-type

**Comment by h1-ti** [comment]
Thank you for your reply.
Yes, I read the plugins, but the license is the same, so they can copy it, right?

**Comment by jondy** [comment]
Yes, the license generated by same capsule are shared. 
For company user different product should purchase different license which use different private capsule. 
For personal user (solo developer), add some extra data to license file by `-x`, for example
```
pyarmor licenses -x "Trial" r001
```
Then check extra data in the license by plugin.

**Comment by h1-ti** [comment]
understood.  Thank you very much.  The latter method does not protect the scripts that have already been distributed.  I'm an personal user, but I would like to consider a new license.
btw, what should I do with the name to register?

**Comment by jondy** [comment]
It doesn't matter. Each private capsule has its own id, only this id is embeded into `license.lic` of obfuscated scripts.

**Comment by h1-ti** [comment]
I see!
Thank you for everything.
Best regards.
