### ISSUE TITLE
Exception when running python script through pyarmor OSError: exception: access violation reading 0x0000000000000000

### ISSUE THREAD

**Issue by anumshaikh** [dashingsoft/pyarmor#345]
I am trying to run my python script using python 3.8.6.
the script contains import such as skimage.metrics, cv2, imutils
the script is running well using python, but when i obfuscate the code using pyarmor im getting below error
Traceback (most recent call last):
File "hello.py", line 2, in
pyarmor_runtime()
File "C:\practicePython\dist\pytransform_init_.py", line 344, in pyarmor_runtime
pyarmor_init(path, is_runtime=1, suffix=suffix)
File "C:\practicePython\dist\pytransform_init_.py", line 340, in pyarmor_init
return init_pytransform()
File "C:\practicePython\dist\pytransform_init_.py", line 57, in wrap
return func(*args, **kwargs)
File "C:\practicePython\dist\pytransform_init_.py", line 75, in init_pytransform
ret = init_module(major, minor, pythonapi._handle)
OSError: exception: access violation reading 0x0000000000000000

The same code i have tried with anaconda, the obfuscated code run executes properly but it doesnot run with python installation. code obfuscated by "pyarmor obfuscate hello.py"
Please help me if im missing something

**Comment by Intair** [comment]
I am getting the same error lol, I cant find anything

**Comment by jondy** [comment]
How about obfuscate the script with super mode?
```
pyarmor obfuscate --advanced 2 hello.py
```
Also refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts

**Comment by anumshaikh** [comment]
> How about obfuscate the script with super mode?
> 
> ```
> pyarmor obfuscate --advanced 2 hello.py
> ```
> 
> Also refer to
> https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts

Hi Jondy, thanks for the help, the script is running when obfuscated with super mode,
Could you please give a little detail why it didnt work without super mode,

**Comment by jondy** [comment]
Without super mode, pyarmor will patch Python interpreter, if it's not compiled as pyarmor expected, for example, with Py_DEBUG set, it may crash.

**Comment by anumshaikh** [comment]
> In non-super mode, pyarmor will patch Python interpreter, if it's not compiled as pyarmor expected, for example, with Py_DEBUG set, it may crash.

Thanks  alot 👍
