### ISSUE TITLE
distribution to other companies of the obfuscated scripts with Enterprise License

### ISSUE THREAD

**Issue by jox79** [dashingsoft/pyarmor#346]
Dears, 
I have a question. If I obfuscate a script with an Enterprise License, can I distribute this obfuscated script and all the required files to another enterprise  that does not have the license? In other word if I sell the obfuscated script to another enterprise does the buyer have to buy a license pyarmor?
Thanks
Stefano

**Comment by jondy** [comment]
No. The buyer need not.
