### ISSUE TITLE
ImportError: cannot import name 'pyarmor' from 'pytransform' (C:\Users\<...>\__init__.py)

### ISSUE THREAD

**Issue by Y-Tian** [dashingsoft/pyarmor#348]
I'm on Windows 10 and I just ran (using command prompt):

```
pyarmor.exe obfuscate test.py
---
python dist/test.py


ImportError: cannot import name 'pyarmor' from 'pytransform' (C:\Users\<...>\__init__.py) 
```

Are there any known solutions for a ImportError like this one?

**Comment by jondy** [comment]
Does `test.py` import other packages which are obfuscated by pyarmor? And what's `<...>` in the traceback `C:\Users\<...>\__init__.py`?
