### ISSUE TITLE
pyarmor pack does not obfuscate

### ISSUE THREAD

**Issue by SergioG-M** [dashingsoft/pyarmor#349]
Hi,
I'm trying to use pyarmor pack to create a .exe file for my code. Although I see the dist/obf folder during execution, and the scripts are obfuscated, the final output has the normal --readable-- scripts. I don't see any error message during execution, and i get sucesfull messages in the end:

INFO     Final output path: dist
INFO     Pack obfuscated scripts successfully.

Any idea what may be the problem?

**Comment by jondy** [comment]
Do you use pyinstaller option `--add-data`? If that, make sure these readable scripts aren't packed as data files.

**Comment by SergioG-M** [comment]
> Do you use pyinstaller option `--add-data`? If that, make sure these readable scripts aren't packed as data files.

Yes I did. I tryed to use the pyinstaller spec file I had:

```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['C:/mypath/main.py'],
             pathex=['C:\\mypath'],
             binaries=[],
             datas=[('C:/mypath/module1.py', '.'), ('C:/mypath/module1.py', '.'), ('C:/mypath/module2.py', '.'), ('C:/mypath/module3.py', '.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='Classifier',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               upx_exclude=[],
               name='Classifier')
```
with pyarmor pack -s myspec.spec main.py

The result is that neither main, nor module1,2 and 3 are obfuscated. If I can't add them as add-data, how should I? and what about main.py?

**Comment by jondy** [comment]
You need not add main.py and modueX.py as data files, they're packed into one `.pyz` file by PyInstaller. If any module couldn't be found, use option `--hidden-import`.

**Comment by SergioG-M** [comment]
Your're right, it worked fine whithout data. Thanks!
