### ISSUE TITLE
exception: access violation reading 0x0000000000000000 in python 3.8.6

### ISSUE THREAD

**Issue by MikelAyani** [dashingsoft/pyarmor#350]
Hi,
I am having an issue with all obfuscated projects, both simple files or packages, after I migrated from python 3.7 to 3.8 (actually 3.8.6). The obfuscation process looks good but when I try to access any file I get an access violation error (see title).
I tried even updating to the latest version of pyarmor (6.4.2) but the error is the same.
I looked around and tried the solution mentioned on #126, so I uncommented the line 328 in pytransform.py and it seems to fix the issue.

    # Disable advanced mode if required
    m.set_option(5, c_char_p(1))

I guess you may want to find the root of the issue so I am happy to help if I can.

**Comment by jondy** [comment]
For non-super mode, pyarmor will patch Python interpreter, if it's not compiled as pyarmor compiled, it may crash.

So it's recommended to use super mode to obfuscate scripts for Python3.8 in latest pyarmor, it's more security, and doesn't crash. Refer to [using super mode](https://pyarmor.readthedocs.io/en/latest/advanced.html#using-super-mode)

**Comment by MikelAyani** [comment]
Thanks for your answer!
I tried with the next command but does not help if I comment back the line 328 in pytransform.py.
    pyarmor obfuscate --advanced 2 --recursive --output=outputdir mypackage/__init__.py"
Do you see something I do wrong?

**Comment by jondy** [comment]
Try to set option `--boostrap 2`
```
pyarmor obfuscate --advanced 2 --recursive --output=outputdir --bootstrap 2 mypackage/__init__.py
```
Refer to https://pyarmor.readthedocs.io/en/latest/man.html#obfuscate

**Comment by MikelAyani** [comment]
I get the same error with or without  --bootstrap 2. Sorry, this does not help.

**Comment by jondy** [comment]
Also copy runtime module `outputdir/pytransform.pyd` or `outputdir/pytransform.cpython*.so` to current path, make sure it's in any Python path.

**Comment by MikelAyani** [comment]
> Hi,
> I am having an issue with all obfuscated projects, both simple files or packages, after I migrated from python 3.7 to 3.8 (actually 3.8.6). The obfuscation process looks good but when I try to access any file I get an access violation error (see title).
> I tried even updating to the latest version of pyarmor (6.4.2) but the error is the same.
> I looked around and tried the solution mentioned on #126, so I uncommented the line 328 in pytransform.py and it seems to fix the issue.
> 
> ```
> # Disable advanced mode if required
> m.set_option(5, c_char_p(1))
> ```
> 
> I guess you may want to find the root of the issue so I am happy to help if I can.

I think it is more simple to uncomment the line above then. Thanks!
