### ISSUE TITLE
Marshall loads failed when using --platform option

### ISSUE THREAD

**Issue by DrTrojan** [dashingsoft/pyarmor#353]
Hey. 
I want to obfuscate my project and to make it work on **armv7** my system is linux.x86_64 when i use --platform linux.armv7 and test the obfuscated project on the armv7 it wont work i get "marshall loads failed" but when i obfuscate the same script on the armv7 device it works.

i use this command "pyarmor obfuscate --platform linux.armv7 --src='.' -r --output=/path/to/output"

**Comment by jondy** [comment]
Make sure the Python version in linux.x86_64 is same as the one in armv7.

**Comment by DrTrojan** [comment]
> Make sure the Python version in linux.x86_64 is same as the one in armv7.

Yes mostly the issue is fixed. But how can i use pyarmor with specific python version?

**Comment by jondy** [comment]
Refer to [Obfuscating Scripts By Other Python Version](https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-scripts-by-other-python-version)

**Comment by DrTrojan** [comment]
> Refer to [Obfuscating Scripts By Other Python Version](https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-scripts-by-other-python-version)

Perfect, I got it to work thanks alot
