### ISSUE TITLE
get_license_data() displays deprecation warning

### ISSUE THREAD

**Issue by neonbunny** [dashingsoft/pyarmor#355]
When calling `get_license_data()` from within my PyArmor plugin I get the following output to the console:

```
<frozen foo>:4: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
```

Tested with Python 3.8.1 on Windows 10.

**Comment by jondy** [comment]
Got it, all python 3.8 has this issue, I'll fix it soon.

**Comment by neonbunny** [comment]
Thanks for the very quick turn around. I can confirm this fixes the issue.
