### ISSUE TITLE
SystemError: unknown opcode when running obfuscated script

### ISSUE THREAD

**Issue by Amejame** [dashingsoft/pyarmor#357]
I've created a simple script `print("HELLO WORLD")` and obfuscated it using `pyarmor obfuscate main.py`. 
When running the obfuscated version of this code I got this error:

```
HELLO WORLD
XXX lineno: 1, opcode: 53
Traceback (most recent call last):
  File "<C:\Users\seblo\Desktop\Projects\dist\main.py>", line 3, in <module>
  File "<frozen main>", line 1, in <module>
SystemError: unknown opcode

```

**Comment by jondy** [comment]
How about run `main.py` in the `C:\Users\seblo\Desktop\Projects\dist\` with `-d`?
```
cd C:\Users\seblo\Desktop\Projects\dist\
python -d main.py
```

**Comment by Amejame** [comment]
What is strange that when I run obfuscated script in PyCharm using right click and `run ` I get the error shown above, but when I run it using `python main.py` or `python -d main.py` as you suggested even in PyCharm's terminal or CMD I'm getting this error:
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    pyarmor_runtime()
  File "C:\Users\seblo\PycharmProjects\pythonProject\dist\pytransform\__init__.py", line 344, in pyarmor_runtime
    pyarmor_init(path, is_runtime=1, suffix=suffix)
  File "C:\Users\seblo\PycharmProjects\pythonProject\dist\pytransform\__init__.py", line 340, in pyarmor_init
    return init_pytransform()
  File "C:\Users\seblo\PycharmProjects\pythonProject\dist\pytransform\__init__.py", line 57, in wrap
    return func(*args, **kwargs)
  File "C:\Users\seblo\PycharmProjects\pythonProject\dist\pytransform\__init__.py", line 75, in init_pytransform
    ret = init_module(major, minor, pythonapi._handle)
OSError: exception: access violation reading 0x0000000000000000
```

**Comment by jondy** [comment]
For Python3.8, how about disable advanced mode by patching `pytransform.py`? Refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#segment-fault

**Comment by jondy** [comment]
@Amejame I test pyarmor with Python3.9, I think now pyarmor doesn't work with Python 3.9. I'm fixing it, please waiting for new version released.

**Comment by jondy** [comment]
Please upgrade latest version v6.4.4, it supports Python 3.9.

**Comment by Amejame** [comment]
Yeah I figured it doesn't work. However moved to 3.8 and now it's okay

**Comment by Amejame** [comment]
I forgot to explain what I was doing wrong so I'll do it now.

The error `SystemError: unknown opcode` occured when I created a venv inside my project.

Other error appeared when I used Python 3.9 default interpreter for my project and as Jondy says it should be fixed now.

Switching to not creating venv inside my project and using Python 3.8 both for non- and obfuscated script worked.
