### ISSUE TITLE
Heroku does not accept use of pyarmor

### ISSUE THREAD

**Issue by bryanseah234** [dashingsoft/pyarmor#358]
Hi there, i recently created an app and tried to deploy it to heroku. but it kept rejecting it. when i emailed them they said it was because i was importing pyarmor in my script. i would like to know if pyarmor is anything illegal or dangerous, else why would heroku ban me from using it? imo pyarmor does not break any of heroku's regulations, but that's just w my limited, new knowledge of pyarmor. hope u can enlighten me. thanks.

**Comment by jondy** [comment]
I'm sure pyarmor is not harmful to any computer. But I know nothing about Heroku and don't know why Heroku rejects pyarmor, it's out of my control.

**Comment by jondy** [comment]
I suggest you first read the end user agreement of HeroKu, make sure it accepts un-open source application. The scripts by obfuscated pyarmor aren't open source.

**Comment by bryanseah234** [comment]
> I suggest you first read the end user agreement of Heroku, make sure it accepts un-open source application. The scripts obfuscated by pyarmor aren't open source.

ahhh alright, will do. thankyou!
