### ISSUE TITLE
ImportError: No module named dash

### ISSUE THREAD

**Issue by MWMouse** [dashingsoft/pyarmor#359]
Hello, I'm planning to buy Pyarmor and tested the trail on a Raspberry Pi 4. My py file runs with no problems, but after obfuscating, I get an error: ImportError: No module named dash. I make use of the dash-plotly module in my python code. How to solve this issue?
Thx

**Comment by jondy** [comment]
The obfuscated scripts can be taken as normal python scripts, make sure module `dash` in any python path when running the obfuscated scripts.
