### ISSUE TITLE
pyarmor + cython NameError: name '__file__' is not defined 

### ISSUE THREAD

**Issue by KittPhi** [dashingsoft/pyarmor#361]
Hello,
I've followed the instructions in the documentation, however when I get to the end and test it, I receive the error.

$ python -c 'import foo'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "foo.py", line 3, in init foo
NameError: name '__file__' is not defined

**3.18 Work with Cython**
[documentation](https://buildmedia.readthedocs.org/media/pdf/pyarmor/latest/pyarmor.pdf)
Here it’s an example show how to cythonize a python script foo.py obfuscated by pyarmor with Python37:
print('Hello Cython')

First obfuscate it with some extra options:
pyarmor obfuscate --package-runtime 0 --no-cross-protection --restrict 0 foo.py

The obfuscated script and runtime files will be saved in the path dist, about the meaning of each options, refer to
command obfuscate.
Next cythonize both foo.py and pytransform.py with extra options -k and --lenient to generate foo.c and pytransform.c:
cd dist
cythonize -3 -k --lenient foo.py pytransform.py

Without options -k and --lenient, it will raise exception:
undeclared name not builtin: __pyarmor__

Then compile foo.c and pytransform.c to the extension modules. In MacOS, just run the following commands, but in
Linux, with extra cflag -fPIC:
gcc -shared $(python-config --cflags) $(python-config --ldflags) \
     -o foo$(python-config --extension-suffix) foo.c -fPIC

gcc -shared $(python-config --cflags) $(python-config --ldflags) \
    -o pytransform$(python-config --extension-suffix) pytransform.c -fPIC

Finally test it, remove all the .py files and import the extension modules:
mv foo.py pytransform.py /tmp
python -c 'import foo'

I tried:
$ python -c 'import foo'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "foo.py", line 3, in init foo
NameError: name '__file__' is not defined

I've also tried creating test-foo.py
   import foo
   print(foo)

$ python test-foo.py
Traceback (most recent call last):
  File "test-foo.py", line 1, in <module>
    import foo
  File "foo.py", line 3, in init foo
NameError: name '__file__' is not defined

**Comment by jondy** [comment]
First check `cpython` could work with module attribute `__name__` and `__file__`, create a script `test.py`
```
print('module name is %s' % __name__)
print('module file is %s' % __file__)
```
Don't obfuscate it, directly cythonize it and build it, then import it by python.

If it doesn't work, check cpython documantation to make sure it works.

**Comment by KittPhi** [comment]
Hello,
I am not sure if this is exactly what you meant or did I need to add something else to the 'test.py'.

# test.py
print('module name is %s' % __name__)
print('module file is %s' % __file__)

# when I run this test:
$ python3 test.py
module name is __main__
module file is test.py

I am assuming that Is that what's expected.
Just to be clear, when you say "Don't obfuscate it", are you suggesting to skip Step1 and then proceed to Step2 (cythonize it and build it, then import it by python.).

My goal was to apply 2 layers of security, (pyarmor + cython). I have been able to successfully do them seperately but not together.

Thanks so much for your assistance,
Kitt

I followed the instructions in the documentation.
**Instructions from Documentation:**
Here it’s an example show how to cythonize a python script foo.py obfuscated by pyarmor with Python37:
print('Hello Cython')

**step 1. First obfuscate it with some extra options:**
pyarmor obfuscate --package-runtime 0 --no-cross-protection --restrict 0 foo.py
The obfuscated script and runtime files will be saved in the path dist, about the meaning of each options, refer to
command obfuscate.

**step 2. Next cythonize both foo.py and pytransform.py with extra options -k and --lenient to generate foo.c and pytransform.c:**
cd dist
cythonize -3 -k --lenient foo.py pytransform.py
Without options -k and --lenient, it will raise exception:
undeclared name not builtin: __pyarmor__

**step 3. Then compile foo.c and pytransform.c to the extension modules. In MacOS, just run the following commands, but in
Linux, with extra cflag -fPIC:**
gcc -shared $(python-config --cflags) $(python-config --ldflags) \
-o foo$(python-config --extension-suffix) foo.c

gcc -shared $(python-config --cflags) $(python-config --ldflags) \
-o pytransform$(python-config --extension-suffix) pytransform.c

**step 4. Finally test it, remove all the .py files and import the extension modules:**
mv foo.py pytransform.py /tmp
python -c 'import foo'

**Comment by jondy** [comment]
Because the traceback reports `NameError: name '__file__' is not defined`, I just want to verify cythonize could get the module attribute `__file__` correctly. It seems this is not problem.

Just for clarification, I notice you run the test with `python` in step 4. Is it python 3? If it's python2, you may need run `cythonize` without option `-3`

**Comment by KittPhi** [comment]
Hello, please disregard my last result since it was on a different machine. I was on Ubuntu 20 and python3 version = 3.8 (maybe the issue).

However, this issue that I am having is on this machine; Ubuntu 18. Here are the results:
Thank you for your assistance,
Kitt
--------------------------------------------------------------
test.py
import foo

print('module name is %s' % __name__)
print('module file is %s' % __file__)
--------------------------------------------------------------
> python
```python
$ python -V
Python 2.7.17

$ python3.7 -V
Python 3.7.9
```

> TEST 1:
```python
#TEST 1:
cythonize -k --lenient foo.py

gcc -shared $(python-config --cflags) $(python-config --ldflags) \
     -o foo$(python-config --extension-suffix) foo.c -fPIC

mv foo.py tmp && mv ~/Repos/dev-env-python/pyarmor-cython-helloworld/tmp/test.py ~/Repos/dev-env-python/pyarmor-cython-helloworld

ecg@ecg:~/Repos/dev-env-python/pyarmor-cython-helloworld$ python test.py
module name is foo
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import foo
  File "foo.py", line 4, in init foo
NameError: name '__file__' is not defined

ecg@ecg:~/Repos/dev-env-python/pyarmor-cython-helloworld$ python3.7 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import foo
ImportError: /home/ecg/Repos/dev-env-python/pyarmor-cython-helloworld/foo.so: undefined symbol: _Py_ZeroStruct

# reset test
rm -rf foo.c foo.so && mv test.py ~/Repos/dev-env-python/pyarmor-cython-helloworld/tmp && mv ~/Repos/dev-env-python/pyarmor-cython-helloworld/tmp/foo.py . && clear
```


> TEST 2:
```python
# TEST 2:
cythonize -3 -k --lenient foo.py

gcc -shared $(python-config --cflags) $(python-config --ldflags) \
     -o foo$(python-config --extension-suffix) foo.c -fPIC

mv foo.py tmp && mv ~/Repos/dev-env-python/pyarmor-cython-helloworld/tmp/test.py ~/Repos/dev-env-python/pyarmor-cython-helloworld

$ python test.py
module name is foo
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import foo
  File "foo.py", line 4, in init foo
NameError: name '__file__' is not defined

$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import foo
ImportError: /home/ecg/Repos/dev-env-python/pyarmor-cython-helloworld/foo.so: undefined symbol: _Py_ZeroStruct

# reset test
rm -rf foo.c foo.so && mv test.py ~/Repos/dev-env-python/pyarmor-cython-helloworld/tmp && mv ~/Repos/dev-env-python/pyarmor-cython-helloworld/tmp/foo.py . && clear

```

> TEST 3:
```python
pyarmor obfuscate --package-runtime 0 --no-cross-protection --restrict 0 foo.py

cd dist && cythonize -3 -k --lenient foo.py pytransform.py

gcc -shared $(python-config --cflags) $(python-config --ldflags) \
     -o foo$(python-config --extension-suffix) foo.c -fPIC

gcc -shared $(python-config --cflags) $(python-config --ldflags) \
    -o pytransform$(python-config --extension-suffix) pytransform.c -fPIC

cp ~/Repos/dev-env-python/pyarmor-cython-helloworld/tmp/test.py .

mkdir temp && mv foo.py pytransform.py ~/Repos/dev-env-python/pyarmor-cython-helloworld/dist/temp && ls

# run tests
$ python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import foo
  File "foo.py", line 3, in init foo
NameError: name '__file__' is not defined

$ python3.7 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import foo
ImportError: /home/ecg/Repos/dev-env-python/pyarmor-cython-helloworld/dist/foo.so: undefined symbol: _Py_ZeroStruct

# reset tests
cd .. && rm -rf dist && clear && ls
```

> TEST 4:
```python
pyarmor obfuscate --package-runtime 0 --no-cross-protection --restrict 0 foo.py

cd dist && cythonize -k --lenient foo.py pytransform.py

```

**Comment by jondy** [comment]
It seems cpythonize could not get module attribute `__file__` in Python2, but Python3 should work.

When using python3 to `cythonize -3`, use `python3-config` in command `gcc`:
```
gcc -shared $(python3-config --cflags) $(python3-config --ldflags) -o foo$(python3-config --extension-suffix) foo.c -fPIC
```

**Comment by KittPhi** [comment]
Hello jondy,
That was the fix to my problem. Thanks so much for all the help.
