### ISSUE TITLE
ERROR    DO NOT pack the obfuscated script, please pack the original script directly

### ISSUE THREAD

**Issue by Amejame** [dashingsoft/pyarmor#362]
Any other ways to pack into .exe file script obfuscated by PyArmor?

**Comment by jondy** [comment]
The command `pack` will obfuscate the scripts automatically, do not try to pack the obfuscated the scripts.

**Comment by Amejame** [comment]
Are you sure? I need to be 100% confident. 
Also why wouldn't we try to pack te obfuscated scripts?

**Comment by jondy** [comment]
I'm sure this, :) 
If the scripts are obfuscated, PyInstaller couldn't find any imported modules. Refer to
https://pyarmor.readthedocs.io/en/latest/how-to-do.html#how-to-pack-obfuscated-scripts

**Comment by Amejame** [comment]
However the link you sent explains how to pack obfuscated script

**Comment by jondy** [comment]
It also explains why could not pack the obfuscated scripts directly(at the beginning ofsection), and how to obfuscate and pack the scripts.
