### ISSUE TITLE
When trying to use pack it returns a error

### ISSUE THREAD

**Issue by Intair** [dashingsoft/pyarmor#364]
![image](https://user-images.githubusercontent.com/69704103/97086224-f2372780-15ef-11eb-9cf2-03647b27402f.png)

**Comment by Intair** [comment]
The command I am using is: pyarmor pack -e " --onefile --icon icon.ico" loader.py

**Comment by jondy** [comment]
Please first install pyinstaller
```
pip install pyinstaller
```
