### ISSUE TITLE
Pyinstaller fails to compile a Pyarmor script

### ISSUE THREAD

**Issue by krombopulosM** [dashingsoft/pyarmor#367]
a few days ago I compiled a obfuscated pyarmor script no problem, but today it fails. I checked the output of the .exe with cmd and found it can't locate a temp file.

https://imgur.com/a/oXfHMp6

**Comment by jondy** [comment]
I can't open this image. For file not problem, first refer to pyinstaller documentation 
https://pyinstaller.readthedocs.io/en/stable/runtime-information.html

And here is common solution for pyarmor `pack` command problem
https://pyarmor.readthedocs.io/en/latest/questions.html#packing-obfuscated-scripts-problem

**Comment by krombopulosM** [comment]
the image shows a command prompt as follows:

Traceback (most recent call last):
  File "diceware.py", line 2, in <module>
  File "pytransform\__init__.py", line 344, in pyarmor_runtime
  File "pytransform\__init__.py", line 339, in pyarmor_init
  File "pytransform\__init__.py", line 304, in _load_library
pytransform.PytransformError: Could not find "C:\Users\<removed>\AppData\Local\Temp\_MEI87122\pytransform\platforms\windows\x86_64\_pytransform.dll"
[9664] Failed to execute script diceware

**Comment by jondy** [comment]
In which platform you pack your script? Make sure it's 64-bit windows and python is not 32-bit, if both of them are 64-bit. Please `pack` your script without one file mode, check the output path `dist/xxx/pytranfrom`, is there `_pytransform.dll`?

**Comment by krombopulosM** [comment]
there isn't a folder within dist/xxx/ called pytransform, but there is a .dll in dist/xxx/ called _pytransform.dll

**Comment by jondy** [comment]
The command `pack` will obfuscate the scripts automatically, create one file bundle by this way
```
pyarmor pack -e " --onefile" foo.py
```

More usage refer to [pack](https://pyarmor.readthedocs.io/en/latest/man.html#pack) man page

**Comment by krombopulosM** [comment]
Is it possible to use super mode as well?

**Comment by jondy** [comment]
With super mode
```
pyarmor pack -e " --onefile" -x " --advanced 2" foo.py
```
