### ISSUE TITLE
ERROR:    PyArmor does not work with this core library (r30), which reversion < r32, please run "pyarmor download --update" to fix it

### ISSUE THREAD

**Issue by Jakar510** [dashingsoft/pyarmor#368]
When using any command on version 6.4.4:

	ERROR    PyArmor does not work with this core library (r30), which reversion < r32, please run "pyarmor download --update" to fix it
	pi@PiDev:~/$ pyarmor download --update
	ERROR    PyArmor does not work with this core library (r30), which reversion < r32, please run "pyarmor download --update" to fix it

Also tried reinstalling pyarmor, no change.

**Comment by jondy** [comment]
How about remove the whole path `~/.pyarmor/platforms`? 

If it still not work, run `pyarmor -d hdinfo`, check the log find the exact path of loaded core library `_pytransform.so`, then remove it.

**Comment by Jakar510** [comment]
pyarmor -d hdinfo
	DEBUG    PyArmor installation path: /home/pi/.local/lib/python3.7/site-packages/pyarmor
	DEBUG    PyArmor home path: /home/pi/.pyarmor
	DEBUG    Native platform is linux.armv7
	DEBUG    Search dynamic library in the path: /home/pi/.local/lib/python3.7/site-packages/pyarmor/platforms
	DEBUG    Search dynamic library in the path: /home/pi/.pyarmor/platforms
	DEBUG    Found available dynamic library linux/armv7/0
	DEBUG    Loaded dynamic library: /home/pi/.pyarmor/platforms/linux/armv7/0/_pytransform.so
	DEBUG    The version of core library is (30, 4, 0)
	Traceback (most recent call last):
	  File "/home/pi/.local/bin/pyarmor", line 8, in <module>
		sys.exit(main_entry())
	  File "/home/pi/.local/lib/python3.7/site-packages/pyarmor/pyarmor.py", line 1447, in main_entry
		main(sys.argv[1:])
	  File "/home/pi/.local/lib/python3.7/site-packages/pyarmor/pyarmor.py", line 1436, in main
		pytransform_bootstrap(capsule=DEFAULT_CAPSULE, force=args.boot)
	  File "/home/pi/.local/lib/python3.7/site-packages/pyarmor/utils.py", line 155, in pytransform_bootstrap
		'"pyarmor download --update" to fix it' % ver[0])
	RuntimeError: PyArmor does not work with this core library (r30), which reversion < r32, please run "pyarmor download --update" to fix it

**Comment by Jakar510** [comment]
I got it working. missed the "s" in "platforms". After removing the folder, *~/.pyarmor/platforms*, it worked.
