### ISSUE TITLE
[Query] Pyarmor module not found while using child project.

### ISSUE THREAD

**Issue by e0lithic** [dashingsoft/pyarmor#369]
Hi I am trying to use child project feature, however it throws the `ModuleNotFoundError: No module named 'pytransform'` error.

# Project Details.
```
.
├── .pyarmor_config
├── .pyarmor_config-1
└── testload
    ├── __init__.py
    └── load.py
```

This is a reproducible example representing the example where all other files need to be obfuscated with restrict mode 4 and only the `__init__.py` should be obfuscated with restrict mode 1
.pyarmor_config
```json
{
  "version": "2.0",
  "name": "temp",
  "title": "temp",
  "src": "testload",
  "is_package": 1,
  "manifest": "global-include *.py",
  "entry": "__init__.py",
  "output": "dist",
  "runtime_path": null,
  "restrict_mode": 4,
  "obf_code": 2,
  "obf_mod": 2,
  "wrap_mode": 1,
  "advanced_mode": 2,
  "bootstrap_code": 1,
  "cross_protection": 1,
  "plugins": null,
  "platform": null,
  "package_runtime": 1,
  "enable_suffix": 0,
  "license_file": null,
  "build_time": 1603790003.3028724
}
```
.pyarmor-config-1
```json
{
  "version": "2.0",
  "name": "temp",
  "title": "temp",
  "src": "testload",
  "is_package": 1,
  "manifest": "include __init__.py",
  "entry": "",
  "output": "dist",
  "runtime_path": null,
  "restrict_mode": 1,
  "obf_code": 2,
  "obf_mod": 2,
  "wrap_mode": 1,
  "advanced_mode": 2,
  "bootstrap_code": 1,
  "cross_protection": 1,
  "plugins": null,
  "platform": null,
  "package_runtime": 1,
  "enable_suffix": 0,
  "license_file": null,
  "build_time": 1603790012.9202883
}
```
After running the following commands:
```bash
pyarmor build -B 
pyarmor build --no-runtime -B .pyarmor_config-1
```
The commands run successfully and then we get the following output structure.
```bash
├── dist
│   └── testload
│       ├── __init__.py
│       ├── load.py
│       └── pytransform.cpython-37m-x86_64-linux-gnu.so
├── .pyarmor_config
├── .pyarmor_config-1
└── testload
    ├── __init__.py
    └── load.py
```

To test we use the following
```bash
cd dist
python -m testload
```
This gives us the error
```log
from pytransform import pyarmor
ModuleNotFoundError: No module named 'pytransform'
```

Can you please let me know , where I am going wrong.

Thanks.

**Comment by jondy** [comment]
How about set `bootstrap_mode` to `3` in the `.pyarmor-config-1`?

**Comment by e0lithic** [comment]
Did you mean `bootstrap_code`? The documentation doesn't specify the `bootstrap_mode` option for the config. Anyway I tried setting `bootstrap_code` to 3, but the same error persists.

**Comment by jondy** [comment]
Is there leading dot in the obfuscated scripts `dist/*.py`? The first line should be like this
```
from .pytransform import pyarmor
```

**Comment by e0lithic** [comment]
Yes that is exactly the line.

**Comment by e0lithic** [comment]
I added the `bootstrap_code` to 3 for both the main and the child config. Then the imports for both file become relative and things work out. Is this the ideal way to work with a package ?

**Comment by jondy** [comment]
Yes. For package, set `bootstrap_code` to 3, and `enable_suffix` to 1, so it will not conflict with other pyarmored package

**Comment by e0lithic** [comment]
Ok Thanks.

**Comment by e0lithic** [comment]
@jondy The scripts work all well with `bootstrap_code` set to `3`. However If I change the `advanced_mode` to `1`, I get the following error: `NameError: name '__pyarmor__' is not defined`

**Comment by jondy** [comment]
For super mode, all the obfuscated scripts include bootstrap code. But for others, the entry script must be set correctly.

Please set the entry script of child project to `__init__.py`, then
```
pyarmor build -B --no-runtime  
pyarmor build -B .pyarmor_config-1
```

**Comment by e0lithic** [comment]
Forgot to close the issue. Worked like a charm.
