### ISSUE TITLE
PyArmor on Maya 2018

### ISSUE THREAD

**Issue by jondy** [dashingsoft/pyarmor#37]
Hello,

We are very interested in PyArmor to distribute Python modules used in Maya 2018
and in order to be able to execute pyarmor in Maya it needs to be compiled with a
specific compiler, the one from Visual Studio 2015.

Is PyArmor 64bits dll compiled with VS2015?
Could you recompile it? We could then test pyarmor in Maya 2018.

Best regards,
David Deckeur
Lead Developer
Superprod Studio

**Comment by jondy** [comment]
Now PyArmor 64bit is built by gcc (cross compile in cygwin). The core functions of PyArmor is written by pure c. Here is an example show how to use it to run obfuscated python code in vs2008

First obfuscate a python script by pyarmor, suppose pyarmor is installed in `/path/to/pyarmor`
```
cd /path/to/pyarmor
python pyarmor.py obfuscate --src=example/simple queen.py

# Here it's the obfuscated script
cat dist/queen.py

# Here are runtime files required to run obfuscated scripts
ls dist/ 
```
Then download the following files:
    http://pyarmor.dashingsoft.com/downloads/platforms/win_amd64/_pytransform.dll
    http://pyarmor.dashingsoft.com/downloads/platforms/win_amd64/_pytransform.def

Next use vs2008 command line tool `lib` to generate .lib file
```
lib /DEF:_pytransform.def /OUT:_pytransform.lib
```
Create a project in vs2008, the content of `main.c` would be like
```c
#include 
#include "Python.h"
#progma comment (lib,"path/to/_pytransform.lib")

extern int init_module(int major, int minor, void *handle);
extern int init_runtime(int sys_trace, int sys_profile, int thread_trace, int thread_profile);

int
main(int argc, char **argv)
{
  Py_SetProgramName(argv[0]);
  Py_Initialize();
  PySys_SetArgvEx(argc, argv);
  
  /* Initialize _pytransform, it will add three funtions to python builtins module:
  __pyarmor__
  __armor_enter__
  __armor_exit__
  After that, obfuscated python code can be executed.
  */
  HANDLE pythonapi = GetCurrentProcess(); 
  init_module(PY_MAJOR_VERSION, PY_MINOR_VERSION, pythonapi);
  init_runtime(0, 0, 0, 0);
  
  /* Run obfuscated script */
  FILE *fp = fopen("/path/to/pyarmor/dist/queens.py");
  PyRun_File(fp, Py_file_input, PyEval_GetGlobals(), PyEval_GetLocals());
  fclose(fp);
  
  /* Or run obfuscated code directly */
  /* PyRun_SimpleString("__pyarmor__('queen', 'queen.py', '\x01\x02....', 1)"); */
  
  /* Exit, cleaning up the interpreter */
  Py_Exit(0); 
  return 0;
}
```
Finally copy runtime files to binary output path of this project and run it
```
cp /path/to/pyarmor/dist/* project/bin/path
```
I'm not sure if it works in vs2015, and if it's what you expected.

If `_pytransform.dll` could not be loaded by this way in vs2015, I'll build `_pytransform.dll` in vs2015.

Feel free to let me know if you have any question.

**Comment by koseiTakeda** [comment]
Hi, 

I tried the webapp to obfuscate a python module I wrote for Maya2018.4. But like you said, unfortunatelly it doesn't work, I get the message error : 
 "Could not load library _pytransform" 

I don't know much about C and how to compile module with Visual Studio, so do I have a way to make it work? Can you compile the _pytransform.dll in vs2015 ? 

Thank you very much!

**Comment by jondy** [comment]
Could you show me how do you import a python module in Maya 2018? 

For example, there is a module `foo.py`, how to import it from Maya 2018, and call some functions in this module.

As my understand, it will be import by `c` code like this
```
  PyObject *m = PyImport_Import('foo.py');
```

Is it that?

**Comment by koseiTakeda** [comment]
Hi, 
In Maya we have a Python shell called the script editor, we simply call it like like that in python : 
`import foo`

The way you described looks like if I had to import it with the Maya API (c++), which I don't know much about. 

So my problem here I think is _pytransform.dll should be compiled with VS2015 using the maya dev kit of Maya2018.

**Comment by koseiTakeda** [comment]
here is a link of the devkit (in the answer)
https://forums.autodesk.com/t5/maya-programming/autodesk-maya-2018-devkit-is-not-available-at-autodesk-app-store/m-p/7312551#M6249

**Comment by jondy** [comment]
I think the key is how the script editor of Maya find `_pytransform.dll`. 

Try this way first

* Obfuscate `foo.py`: `pyarmor obfuscate foo.py`,
* In the script editor of Maya, run
```
import sys

# Replace it with actual path of obfuscated script
obfpath = '/path/to/foo/dist'
sys.path.append(obfpath)

import pytransform
pytransform.init_pytransform(path=obfpath)
```
If it works, this `_pytransform.dll` should work with Maya 2018.
If it doesn't work, show me the error.

**Comment by koseiTakeda** [comment]
This is the error I get 
```
import pytransform
# Error: PytransformError: file [...]\pytransform.py line 183: Could not load library _pytransform. # 
```

**Comment by koseiTakeda** [comment]
I did some couple of test by harcoding the path for the loadLibrary in  _load_library() of pytransform.py :

```
path = r'C:\[...]\foo\_pytransform.dll'
m = cdll.LoadLibrary(path)
```
and I don't get any trouble to load, m return me this : 
`<CDLL 'C:\[...]\foo\_pytransform.dll', handle 70a00000 at 6db10748>`

but after I got an error there : 
```
# Error: PytransformError: file C:/[...]\foo\pytransform.py line 53: Open pyshield license file 'C:\[...]\foo\_pytransform.dll\pyshield.lic'
No such file or directory
Initialize license key failed
Initialize pytransform failed # 
```

**Comment by koseiTakeda** [comment]
I did some couple of test by harcoding path in _load_library() and using raw string as mentionned in this ticket: 
https://stackoverflow.com/questions/1940578/windowserror-error-126-the-specified-module-could-not-be-found

so it give me that : 
```
    path = r'C:\foo\_pytransform.dll'
    m = cdll.LoadLibrary(path)
    otherpath = 'C:\foo'
    if not os.path.abspath('.') == os.path.abspath(otherpath):
        m.set_option('pyshield_path'.encode(), otherpath.encode())
    return m
```

now I got an error with the license : 
```
# Error: PytransformError: file C:/foo\pytransform.py line 53: Open pyshield license file 'C:\foo\pyshield.lic'
Invalid argument
Initialize license key failed
Initialize pytransform failed # 
```

**Comment by jondy** [comment]
Good news! To fix license error, try this code
```
    path = os.path.normpath(r'C:\foo')
    m = cdll.LoadLibrary(os.path.join(path, '_pytransform.dll')
    m.set_option('pyshield_path'.encode(), path .encode())
    return m
```

Before that, copy the runtime files to `c:\foo`
```
pyshield.key
pyshield.lic
product.key
license.lic
```
They're in the same path of the obfuscated scripts.

Refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html

**Comment by koseiTakeda** [comment]
I forgot to mention the runtime files were already there by using global-include *.py in the webapp 
So I did the exact same code but it gives me an error : 
`# Error: SystemError: file C:/foo\__init__.py line 2: error return without exception set # `
note : In the __init__.py I had to add ` import pyimcore` on the first line otherwise `__pyarmor__` was not recognized

**Comment by koseiTakeda** [comment]
I deleted my previous comment because I think this is working except the code generated is like that : 
`__pyarmor__(__name__, __file__, b'\x6', 1) ` where it should be like that `__pyarmor__(__name__, b'\x6' ) ` 
So now I m gonna manually change all the .py in my package to verify this the issue and let you know

**Comment by koseiTakeda** [comment]
sooo it's imported it correctly after the change I did! no error at ` import foo` which is a great news !!
I developed a UI with PySide2 in Maya so I do have some .ui who has not been transfer over and when I transfer them manually it doesn't work so I guess I will have to convert the `.ui` into `.py` using `pyuic` because maybe I cannot attach external dependency like .ui ? 
The error I get is : 
`# Error: IOError: file C:\_pxo\rez_local_cache\ext\maya\2018.4.0\platform-windows\maya\bin\python27.zip\xml\etree\ElementTree.py line 647: 2 # `

**Comment by koseiTakeda** [comment]
sooo it's imported it correctly after the change I did! no error at ` import foo` which is a great news !!
I developed a UI with PySide2 in Maya so I do have some .ui who has not been transfer over and when I transfer them manually it doesn't work so I guess I will have to convert the `.ui` into `.py` using `pyuic` because maybe I cannot attach external dependency like .ui ? 
The error I get is : 
`# Error: IOError: file C:\[...]\maya\2018.4.0\platform-windows\maya\bin\python27.zip\xml\etree\ElementTree.py line 647: 2 # `

**Comment by jondy** [comment]
Yes, pyarmor only can obfuscate `.py` file, so you need convert `.ui` into `.py` before obfuscate them.  If the clear `.py` file works, the obfuscated one should work.  When do you get this error? obfuscating script, or importing obfuscated script

**Comment by jondy** [comment]
> I deleted my previous comment because I think this is working except the code generated is like that :
> `__pyarmor__(__name__, __file__, b'\x6', 1) ` where it should be like that `__pyarmor__(__name__, b'\x6' ) `
> So now I m gonna manually change all the .py in my package to verify this the issue and let you know

It surprises me. Does it mean that `__pyarmor__(__name__, b'\x6' ) ` works, but `__pyarmor__(__name__, __file__, b'\x6', 1) ` doesn't work?

**Comment by koseiTakeda** [comment]
> 
> 
> Yes, pyarmor only can obfuscate `.py` file, so you need convert `.ui` into `.py` before obfuscate them. If the clear `.py` file works, the obfuscated one should work. When do you get this error? obfuscating script, or importing obfuscated script

when importing obfuscated script. I think it's only because he cannot open/connect with the ui file. 

> 
> 
> It surprises me. Does it mean that `__pyarmor__(__name__, b'\x6' ) ` works, but `__pyarmor__(__name__, __file__, b'\x6', 1) ` doesn't work?

exactly, otherwise I have this error : 
`takes exactly 2 arguments (4 given)`

**Comment by Peter92** [comment]
Thanks for uploading the file, I did try it however (in both Maya 2017 and 2018) and still got the `[Error 126] The specified module could not be found` message.

I tried things from the other comments but just can't get past loading the DLL via `ctypes.cdll.LoadLibrary`/`ctypes.WinDLL`. I've copied in the runtime files too, would you happen to have any ideas?

**Comment by jondy** [comment]
First, download `vs2015/x64/_pytransform.dll` from this link, and copy `_pytransform.dll` to `\site-packages\pyarmor`, or overwrite `\site-packages\pyarmor\platforms\windows64\_pytransform.dll`, then run `pyarmor.pytransform_bootstrap(); pyarmor.main(('obfuscate', path_to_script, '--output', path_to_dist))` inside Maya

To solve the `Error: Check restrict mode failed`, add extra option `--restrict=0`, for example:
`pyarmor obfuscate --restrict=0 xx.py`

**Comment by Peter92** [comment]
Thanks for the reply, I've got it a little further, but I've hit a bug and it may take some time to find the cause.

Here's the bits that did/didn't work in case anyone else comes across this:

The download link DLL would always result in `The specified module could not be found` in Maya 2017.5 and 2018.4, but the one already provided in the `pyarmor` package is fine. If I generate the code from inside Maya, it will have the `Verify rsa key failed` error, which may potentially be something to do with the working directory as it's also not able to find `_pytransform.dll` in the same folder as the generated file (it looks in `\site-packages\pyarmor` instead, but perhaps that's only the fallback location). 

The only way I've been able to get it working is by generating it with standalone Python with the `--restrict=0` argument, and copying in `\site-packages\pyarmor\platforms\windows64\_pytransform.dll`.

Unfortunately all my actual scripts are getting this `struct` error during import: `Protection Fault: unpack requires a string argument of length 864256` - Unless you'd have some idea as why it might not be able to unpack, all of my stuff imports from the same code library so I'll need to do a bit of digging to find exactly what it doesn't like haha

**Comment by jondy** [comment]
From PyArmor 5.2.0, it will insert some extra code in the entry script to protect `_pytransformdll`, refer to

https://pyarmor.readthedocs.io/en/latest/how-to-do.html#special-handling-of-entry-script

Check this file `\site-packages\pyarmor\protect_code.pt`, something is wrong with this function `check_lib_pytransform`, it will call `struct.unpack` to check `_pytransformdll`

**Comment by jondy** [comment]
Please download the latest dll from

http://pyarmor.dashingsoft.com/downloads/platforms/vs2015/x64/_pytransform.dll
md5sum: db1d91f49b847cc8698dcce8456d28d7

The old one misses some export functions, it doesn't work with PyArmor 5.2+

**Comment by jetwang99** [comment]
> Here is `_pytransform.dll` built with vs2015:
> 
> http://pyarmor.dashingsoft.com/downloads/platforms/vs2015/x64/_pytransform.dll
> 
> Hope it works.

Could you please share x86 version of `_pytransform.dll` built with vs2015 here?

**Comment by jondy** [comment]
Here it is

http://pyarmor.dashingsoft.com/downloads/platforms/vs2015/x86/_pytransform.dll
md5sum: c1114ca0a9574bdbc8f9482fcbac7d91

**Comment by 2232549876** [comment]
I obfuscated a very simple maya plugin with pyarmor5.2.3 , then loaded it from the 'dist' directory by Maya2018 plugin manager, but an error occured:

`// Error: file: E:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 905: NameError: file D:/PythonProjects/Src/dist/pyHelloMaya.py line 1: name '__file__' is not defined //`

I wonder if I'm using it in the wrong way.

**Comment by jondy** [comment]
I have Maya installed, only some advices:
* To be sure bootstrap code is called 
       https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#bootstrap-code
* To be sure `_pytransform.dll` is the right one (built by VS2015, other than the default one)
* Replace pyHelloMaya.py with `print(__file__)`, check it works or not.

**Comment by 2232549876** [comment]
Thank you very much for your reply!

1. I replaced pyHelloMaya.py  with `print(__file__)` . 

2. Considering that maya18 uses python2.7 ,so I changed the python version  of the system into 2.7.

3. I overwrote the default version of the DLL (x64) with the DLL you shared to us.

In the CMD window,I changed directory into the "dist" folder and finally it successfully output the file name.

Everything worked fine, but I encountered the same error again when I tried to load the obfuscated.py file through Maya's plug-in manager.

`// Error: file: E:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 905: NameError: file E:/Python2.7/PyarmorTest-Py27/Src/dist/pyHelloMaya.py line 3: name '__file__' is not defined //`

I must have made a mistake, maybe I didn't use the md5sum sequence number (the one given below the DLL link), I don't know how that affects my current actions.

**Comment by jondy** [comment]
How about edit `E:/Python2.7/PyarmorTest-Py27/Src/dist/pyHelloMaya.py`, add one line at the begining:
`__file__ = 'E:/Python2.7/PyarmorTest-Py27/Src/dist/pyHelloMaya.py'`

**Comment by 2232549876** [comment]
Eventually I added the file's path to Maya's system path, and just imported it in my code, and it worked.
The code is like this:

`import sys;`
`sys.path.append("E:\\Python2.7\\PyarmorTest-Py27\\Src\\dist");`
`import HelloWorld as hello;`
`hello.Greet();`

I had been loading the encrypted py file as a plug-in (which was my mistake), but that didn't work, even though I implemented the necessary functions as a plug-in for Maya.

Still, as long as you could run the confused py code in Maya, that would be enough to keep the Maya python plugin you wrote protected by pyarmor!

I really appreciate your help!

**Comment by EzerbelCN** [comment]
> Here it is
> 
> http://pyarmor.dashingsoft.com/downloads/platforms/vs2015/x86/_pytransform.dll md5sum: c1114ca0a9574bdbc8f9482fcbac7d91

which pyarmor version match this _pytransform.dll.dll ?
