### ISSUE TITLE
[Query] Recommended approach for using Pyarmor with Github Actions

### ISSUE THREAD

**Issue by piyush-das** [dashingsoft/pyarmor#370]
Hi,

Since I am new to obfuscation. I was wondering what is the way to use licensed version of pyarmor with github actions so as to automate the encrypted builds for delivery.

Thanks

**Comment by jondy** [comment]
Just register pyarmor as general way in `gitHub-hosted runners` or `your own runners`. Maybe it could be achieved by inserting a step to register pyarmor in the GitHub action.

**Comment by piyush-das** [comment]
Thanks.
