### ISSUE TITLE
cannot locate symbol "getdomainname"

### ISSUE THREAD

**Issue by LOVEChen** [dashingsoft/pyarmor#372]
ERROR    dlopen failed: cannot locate symbol "getdomainname" referenced by "/system/love/home/.pyarmor/platforms/android/aarch64/0/_pytransform.so"...

Linux localhost 3.18.20 #36 SMP PREEMPT Tue Oct 20 11:56:13 PDT 2020 aarch64 Android

**Comment by LOVEChen** [comment]
root@localhost:/data/temp$ pyarmor -d obfuscate --recurisve slaver.py 
usage: pyarmor [-h] [-v] [-q] [-d] [--home HOME] [--boot BOOT]  ...
pyarmor: error: unrecognized arguments: --recurisve
root@localhost:/data/temp$ pyarmor -d obfuscate slaver.py 
DEBUG    PyArmor installation path: /data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor
DEBUG    PyArmor home path: /data/data/com.termux/files/home/.pyarmor
DEBUG    Native platform is android.aarch64
DEBUG    Search dynamic library in the path: /data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/platforms
DEBUG    Search dynamic library in the path: /data/data/com.termux/files/home/.pyarmor/platforms
DEBUG    Found available dynamic library android/aarch64/0
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pyarmor", line 8, in <module>
    sys.exit(main_entry())
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1487, in main_entry
    main(sys.argv[1:])
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1476, in main
    pytransform_bootstrap(capsule=DEFAULT_CAPSULE, force=args.boot)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/utils.py", line 148, in pytransform_bootstrap
    pytransform.pyarmor_init(platid=platid)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/pytransform.py", line 339, in pyarmor_init
    _pytransform = _load_library(path, is_runtime, platid, suffix, advanced)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/pytransform.py", line 307, in _load_library
    m = cdll.LoadLibrary(filename)
  File "/data/data/com.termux/files/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/data/data/com.termux/files/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen failed: cannot locate symbol "getdomainname" referenced by "/system/comma/home/.pyarmor/platforms/android/aarch64/0/_pytransform.so"...

**Comment by jondy** [comment]
It seems there is no `getdomainname` in the c library of this Android platform. What's the output of ldd?
```
ldd -d /system/comma/home/.pyarmor/platforms/android/aarch64/0/_pytransform.so
```

**Comment by LOVEChen** [comment]
> It seems there is no `getdomainname` in the c library of this Android platform. What's the output of ldd?
> 
> ```
> ldd -d /system/comma/home/.pyarmor/platforms/android/aarch64/0/_pytransform.so
> ```

root@localhost:/data/temp$ pyarmor -d obfuscate slaver.py
DEBUG    PyArmor installation path: /data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor
DEBUG    PyArmor home path: /data/data/com.termux/files/home/.pyarmor
INFO     Create pyarmor home path: /data/data/com.termux/files/home/.pyarmor
INFO     Create trial license file: /data/data/com.termux/files/home/.pyarmor/license.lic
DEBUG    Native platform is android.aarch64
DEBUG    Search dynamic library in the path: /data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/platforms
DEBUG    Search dynamic library in the path: /data/data/com.termux/files/home/.pyarmor/platforms
INFO     Create cross platform libraries path /data/data/com.termux/files/home/.pyarmor/platforms
INFO     Search library for platform: android.aarch64
DEBUG    Load platform list from /data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/platforms/index.json
INFO     Found available libraries: ['android.aarch64.0']
INFO     Downloading library file for android.aarch64.0 ...
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r36.10/platforms/android.aarch64/_pytransform.so
INFO     Create target path: /data/data/com.termux/files/home/.pyarmor/platforms/android/aarch64/0
INFO     Writing target file: /data/data/com.termux/files/home/.pyarmor/platforms/android/aarch64/0/_pytransform.so
INFO     Download dynamic library android.aarch64.0 OK
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pyarmor", line 8, in <module>
    sys.exit(main_entry())
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1487, in main_entry
    main(sys.argv[1:])
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1476, in main
    pytransform_bootstrap(capsule=DEFAULT_CAPSULE, force=args.boot)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/utils.py", line 148, in pytransform_bootstrap
    pytransform.pyarmor_init(platid=platid)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/pytransform.py", line 339, in pyarmor_init
    _pytransform = _load_library(path, is_runtime, platid, suffix, advanced)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/pytransform.py", line 307, in _load_library
    m = cdll.LoadLibrary(filename)
  File "/data/data/com.termux/files/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/data/data/com.termux/files/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen failed: cannot locate symbol "getdomainname" referenced by "/system/comma/home/.pyarmor/platforms/android/aarch64/0/_pytransform.so"...

root@localhost:/data/temp$ ldd -d /system/comma/home/.pyarmor/platforms/android/aarch64/0/_pytransform.so
libdl.so
libc.so

root@localhost:/data/temp$ find / -name "libdl.so"
find: /sys/kernel/slab/L2TP/IPv6: No such file or directory
find: /sys/kernel/slab/L2TP/IP: No such file or directory
/system/lib/libdl.so
/system/lib64/libdl.so

root@localhost:/data/temp$ find / -name "libc.so"
find: /sys/kernel/slab/L2TP/IPv6: No such file or directory
find: /sys/kernel/slab/L2TP/IP: No such file or directory
/system/lib/libc.so
/system/lib64/libc.so
root@localhost:/data/temp$

**Comment by jondy** [comment]
Please download [this one](https://pyarmor.dashingsoft.com/downloads/temp/android.aarch64/_pytransform.so), save it to `/system/comma/home/.pyarmor/platforms/android/aarch64/0/_pytransform.so`, `getdomainname` is removed.

But I don't know why there is no `getdomainname` in this platform, it's a common libc function.

**Comment by LOVEChen** [comment]
thanks for the help. it work like charm. for this reason i'll buy pyarmor.

DEBUG    PyArmor installation path: /data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor
DEBUG    PyArmor home path: /data/data/com.termux/files/home/.pyarmor
DEBUG    Native platform is android.aarch64
DEBUG    Search dynamic library in the path: /data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/platforms
DEBUG    Search dynamic library in the path: /data/data/com.termux/files/home/.pyarmor/platforms
DEBUG    Found available dynamic library android/aarch64/0
DEBUG    Loaded dynamic library: /data/data/com.termux/files/home/.pyarmor/platforms/android/aarch64/0/_pytransform.so
DEBUG    The version of core library is (36, 10, 0)
INFO     Generating public capsule ...
DEBUG    Copy /data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/public_capsule.zip to /data/data/com.termux/files/home/.pyarmor/.pyarmor_capsule.zip
DEBUG    Generate public capsule /data/data/com.termux/files/home/.pyarmor/.pyarmor_capsule.zip OK.
INFO     PyArmor Trial Version 6.5.1
INFO     Target platforms: Native
INFO     Source path is "/data/temp"
INFO     Entry scripts are ['test.py']
INFO     Use cached capsule /data/data/com.termux/files/home/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read public key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Copying /data/data/com.termux/files/home/.pyarmor/platforms/android/aarch64/0/_pytransform.so
INFO     Patch library dist/pytransform/_pytransform.so
DEBUG    Patching dist/pytransform/_pytransform.so
DEBUG    Found pattern at 8f040
DEBUG    Patch 320 bytes from 8f060
DEBUG    Patch 140 bytes from 8f1a0
DEBUG    Patch 216 bytes from 8f22c
INFO     Patch library file OK
INFO     Copying /data/data/com.termux/files/usr/lib/python3.8/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            test.py -> dist/test.py
INFO     Patch this entry script with protection code
INFO     Write patched script for debugging: /data/temp/test.py.pyarmor-patched
INFO     Insert shell line: #!/usr/bin/env python
INFO     Insert bootstrap code to entry script dist/test.py
INFO     Obfuscate 1 scripts OK.
