### ISSUE TITLE
pack with nuitka issues

### ISSUE THREAD

**Issue by LOVEChen** [dashingsoft/pyarmor#373]
this operation follow the docs.

pyarmor obfuscate --restrict 0 --no-cross-protection test.py
cd dist
python -m nuitka --include-package pytransform test.py
mv test.bin ..
mv dist/ del

root@localhost:/data/temp$ ./test.bin 
Traceback (most recent call last):
  File "/data/temp/dist/test.py", line 3, in <module>
    import sys
  File "/data/temp/dist/pytransform/__init__.py", line 344, in pyarmor_runtime
  File "/data/temp/dist/pytransform/__init__.py", line 339, in pyarmor_init
  File "/data/temp/dist/pytransform/__init__.py", line 304, in _load_library
pytransform.PytransformError: Could not find "/data/temp/dist/pytransform/platforms/android/aarch64/_pytransform.so"

seems binary can't running alone , can author help this?

**Comment by jondy** [comment]
Is there this file `/data/temp/dist/pytransform/_pytransform.so` and has the right access right?

**Comment by LOVEChen** [comment]
> Is there this file `/data/temp/dist/pytransform/_pytransform.so` and has the right access right?

it have right access to pack, when it done , i mv it out , and tested single file, it failed.

**Comment by jondy** [comment]
Please keep `_pytransform.so`, it's required to run the obfuscated scripts. And it's better to obfuscate script with `--package-runtime 0`, so that all the runtime files are in the same path.
```
pyarmor obfuscate --restrict 0 --no-cross-protection --package-runtime 0 foo.py
```
