### ISSUE TITLE
[Query] is it possible to extend hd-info related  license type (e.g,cpuid)

### ISSUE THREAD

**Issue by ChaochCN** [dashingsoft/pyarmor#376]
can i extend hd-info related  license type (e.g,cpuid) ?
first , bind cpuid( can not bind for now in version.6.5.1):
`pyarmor licenses --bind-cpu "xxxxxx" code-002`
then , custom a plugin to check it ?
in the plugin , i can get the cpuid from license , then check it, just like the example plugin which checks the docker`s id. 
if not correspond to local machine, raise an error : the license is not for this machine.

**Comment by jondy** [comment]
Use `--bind-data` to generate license
```
pyarmor licenses --bind-data "cpu id" code-002
```
Then use plugin to check it

Refer to https://github.com/dashingsoft/pyarmor/tree/master/plugins#example-2-check-docker-container-id

**Comment by ChaochCN** [comment]
the usage of `--bind-data` ,for instance ,my cpuid is `BFEBFBFF000934EX` , then bind it like below:
`pyarmor licenses --bind-data "cpuid  BFEBFBFF000934EX code-002"` ?
by the way , what is code-002 , is that just a random key we mannualy give or it`s meaningful?

**Comment by jondy** [comment]
The format of bind data is decided by yourself, it could be any string only if your plugin could parse it.

The last `code-002` is any identify string which is stored in the final `license.lic`. It also could be got in the plugin.

Refer to https://pyarmor.readthedocs.io/en/latest/pytransform.html

**Comment by ChaochCN** [comment]
tks  a lot !
