### ISSUE TITLE
error when  loading Python DLL

### ISSUE THREAD

**Issue by ChaochCN** [dashingsoft/pyarmor#378]
foo.py:
```
if __name__ == "__main__":
    print("Hello World !")
```

![1](https://user-images.githubusercontent.com/11241714/98520067-88d03d80-22ac-11eb-91f8-7b785d2e808c.png)
![2](https://user-images.githubusercontent.com/11241714/98520079-8bcb2e00-22ac-11eb-89a1-5ef6f3770240.png)
![3](https://user-images.githubusercontent.com/11241714/98520084-8e2d8800-22ac-11eb-9bf8-4536364fbb08.png)
![4](https://user-images.githubusercontent.com/11241714/98520094-8ff74b80-22ac-11eb-9384-4c6dd2c0fe1a.png)

**Comment by jondy** [comment]
Does it work to pack it by Pyinstaller directly?
```
rm -rf dist/
pyinstaller --clean foo.py
dist/foo/foo.exe
```

**Comment by ChaochCN** [comment]
next time , i`ll try it  if  meet this error again.
already solved by reinstall pyinstaller, tank u jondy.

it happened after i tried this cmd:
`pyarmor pack --clean -e "  --onefile --add-data HdinfoTool.dll;."  -O output  hdinfo.py`
but now i reinstalled pyinstaller, i packed with this cmd(above) successfully.
by the way, can u tell me how to seperate several dlls in this cmd?( I should try it out by myself, ≧◉◡◉≦)

**Comment by ChaochCN** [comment]
Finally I tried out:
`pyarmor pack --clean -e "  --onedir --add-data HdinfoTool.dll;.  --add-data Test.dll;."  -O output  hdinfo.py`
I checked the output dir, all dlls are packed together .
