### ISSUE TITLE
get notified after the process  of pyarmor`s cmd completed (in code)

### ISSUE THREAD

**Issue by ChaochCN** [dashingsoft/pyarmor#379]
for example:
`pyarmor pack --clean -e "  --onefile --window --add-data HdinfoTool.dll;.  --add-data Test.dll;."  -O output  hdinfo.py`
after this above finished, i want to get informed , maybe in  a callback . 
is it supported by pyarmor ?
can i wrap or decorate a pyarmor cmd? append a callback to the tail?

**Comment by ChaochCN** [comment]
periodically polling is the worst choice i can make.

**Comment by jondy** [comment]
You can call pyarmor from python script, then do anything after pyarmor command returns, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#call-pyarmor-from-python-script

**Comment by ChaochCN** [comment]
i am trying to pack/obfuscate the py files with network.
at morning, suddenly a new idea comes to me:

- write the cmd into a bat file

- write a  curl cmd to the the end of the bat file

- the curl`s  http request will carry the id of this bat(cmd) as parameter

- run this a bat

thank u all the same for you help.
