### ISSUE TITLE
How to build with custom packages

### ISSUE THREAD

**Issue by BrendanSimon** [dashingsoft/pyarmor#38]
How do I get pyarmor to include custom packages that are outside the main source directory.

e.g. I have various python modules in `/some/common/path/mypackage` and my application source code in `/my/app/path`, and my application imports `mypackage.foo` using `from mypacakge import foo`

`pyarmor obfuscate --recursive --src=/my/app/path --entry=myapp.py`

This command doesn't seem to add the package/modules, and the trying to run the app fails saying something like:

```
  File "<frozen Main_Frame_WXG>", line 11, in <module>
ModuleNotFoundError: No module named 'mypackage'
```

I've also tried setting `PYTHONPATH` but it doesn't make any difference.

`PYTHONPATH=/some/common/path pyarmor obfuscate --recursive --src=/my/app/path --entry=myapp.py`

I also tried adding multiple `--src=` lines, but it seems only the last one is used.

**Comment by jondy** [comment]
Pyarmor changes nothing about PYTHONPATH, it just obfuscates python source only.

Does it work?
```
pyarmor obfuscate --recursive --src=/my/app/path --entry=myapp.py
cd dist
PYTHONPATH=/some/common/path python myapp.py
```

**Comment by jondy** [comment]
If you use py2app or cx_Freeze to distribute obfuscated scripts, refer to this guide

https://github.com/dashingsoft/pyarmor/blob/master/src/user-guide.md#work-with-py2exe-and-cx_freeze
