### ISSUE TITLE
Pyarmor advanced mode [2] fails in certain scenarios.

### ISSUE THREAD

**Issue by piyush-das** [dashingsoft/pyarmor#380]
Hi,

Advanced mode 2 seems to fail with the following keras file.
https://gofile.io/d/CosYeZ

The following error comes up : 
```
INFO     Start obfuscating the scripts...
INFO            theano_backend.py -> dist/theano_backend.py
ERROR    Function does not end with "):"
ERROR    Patch function "_old_normalize_batch_in_training" failed
```
Thanks

**Comment by jondy** [comment]
Please move the trailing comment `# pragma: no cover` of function definition `def _old_normalize_batch_in_training` to any other line. If it can't be moved, refer to [Code object could not be obufscated with advanced mode 2](https://pyarmor.readthedocs.io/en/latest/questions.html#code-object-could-not-be-obufscated-with-advanced-mode-2) to refine this function

**Comment by piyush-das** [comment]
Ok Thanks.
