### ISSUE TITLE
[Query] how to combo pyarmor cmd with  sys cmd?

### ISSUE THREAD

**Issue by ChaochCN** [dashingsoft/pyarmor#381]
i am trying to pack/obfuscate the py files with network.
int the morning, suddenly a new idea comes to me:

- write the cmd into a bat file

- write a  curl cmd to the the end of the bat file

- the curl`s  http request will carry the id of this bat(cmd) as a parameter

- run this  bat file

thank u all the same for you help.

_Originally posted by @ChaochCN in https://github.com/dashingsoft/pyarmor/issues/379#issuecomment-724372222_

**Comment by ChaochCN** [comment]
how to combo  pyarmor cmd with system cmd?
is it possible to regist pyarmor cmd into system, so that, i can use below:
cd D:/test && pyarmor obfuscate foo.py && curl http://google.com && exit 
in this way,it will save time cost  spended in IO ops ,instead of writing cmds into a bat file.

**Comment by jondy** [comment]
Find the fullpath of `pyarmor.exe`, then call it with full path in Java.

**Comment by ChaochCN** [comment]
@jondy  I called pyarmor.exe with full path in java,  but it didnt work . i`ll continue to use bat file for now.
