### ISSUE TITLE
Error Validating License with Multiple Hard Drives

### ISSUE THREAD

**Issue by YouCantHandleMyOPness** [dashingsoft/pyarmor#384]
I have two hard drives on my machine.  One is for Windows 10 and one is for Linux Ubuntu 20.04.  When I make a license using the hard drive serial number of my Windows hard drive and try to run it on Windows, I get the following error: 
"RuntimeError: License is not for this machine"
This is because the command line: "pyarmor hdinfo" gives me the serial number of my Linux hard drive even if I run this command on my Windows machine.  I believe that Pyarmor is looking up the incorrect serial number to use to validate the Windows machine license.  Please advice me on how to make it properly discover which hard drive the Python script is running on.  

Since the two hard drives are totally separate, Python, Pyarmor and all Python files are entirely on the Windows hard drive.

Software information: Windows 10, Python 3.7.8, Pyarmor 6.5.2 .

**Comment by ChaochCN** [comment]
- my pc has two disks, system is installed on a SDD, the other one is a HDD.

- but pyarmor hadinfo just gives me  sn of the HDD.

- when i used  ` wmic diskdrive get serialnumber` ， both disks`  sn are reported  ,  the first is the HDD`s disk ,second is the SDD`s disk.

- perhaps, this maybe a little flaw of pyarmor: report the first disk only.

- i think you can custom a plugin for multi disksn check.

. first, --bind-data "disk1:disk1sn;disk2:disksn;disk3:disk3sn;" (you can parse these data under the guidance of the given examples/closed-issues  in github)

. next, get the  logical partition of current sysytem ，and then check out the physical disksn where the logical partition is on.

. last, check whether the disksn of the sys is in the list of disks` sn(the data that parsed from the binded data). if not, you can raise an error: 'the lic is not for this sys or machine';if it is one of the just let it pass.

these links may be helpful:
[https://github.com/dashingsoft/pyarmor/issues/376](url)
[https://github.com/dashingsoft/pyarmor/issues/377](url)
[https://github.com/dashingsoft/pyarmor/tree/master/plugins](url)

**Comment by jondy** [comment]
PyArmor now only checks the first hard disk found, so just bind disk to what `pyarmor hdinfo` prints. Or write your own plugin just as above comment.

**Comment by YouCantHandleMyOPness** [comment]
I can work with these responses to get a work around for the issue.  Thanks a bunch!
