### ISSUE TITLE
Conceptual Question

### ISSUE THREAD

**Issue by marvision-ai** [dashingsoft/pyarmor#388]
Hello! Thank you for such a cool project! It's fantastic. 

Before I purchase a license for my own personal use, I was wondering if you could advise me if I am doing the following correctly. 

I have a `main.py` that imports many different other scripts `a.py` and `b.py` . Each other these scripts have a class in charge of doing something.

I want to use pyarmor to obfiscate `a.py` and `b.py` but **not** `main.py` and import both of those scripts and use their methods. 

### How I do it:
First create one bootstrap package pytransform_bootstrap by command runtime (inside the camshaft folder with models etc:

```$pyarmor runtime -i```

This will create a dist/pytransform_bootstrap folder in the main directory

then in the main directory, this will obfuscate everything: 
``` $pyarmor obfuscate main.py ``` 

then replace the `main.py` (obfiscated) in the dist directory with a regular `main.py` and add the following to the top: 
```$ import pytransform_bootstrap``` 

In that `dist` folder I should then have 3 folders + `a.py` (obfiscated) + `b.py` (obfiscated) and a regular `main.py`

then call from the **main** directory, I will call:
```$python3 dist/main.py```
 

### Question:
This works, but I feel like I may not be doing the whole process correctly...

Is there a way that I can obfiscate specific scripts, and then just use a regular simple python script to call them?  Please let me know if there is a better way to use your library that I am not aware of 😄 

Thank you in advance!

**Comment by jondy** [comment]
Yes. What you do is exact as pyarmor desired.

But there's better solution with super mode
```
pyarmor o --advanced 2 --exact a.py b.py
```
Note that trial version doesn't work for big scripts with super mode.

**Comment by marvision-ai** [comment]
@jondy thanks for the reply! What's the point of using super mode? More obfuscation? 

Also what does '--exact' do? Only obfuscate the files I want?

**Comment by jondy** [comment]
Yes, super mode is more obfuscation.
Refer to
https://pyarmor.readthedocs.io/en/latest/mode.html#super-mode

And
https://pyarmor.readthedocs.io/en/latest/man.html#obfuscate
