### ISSUE TITLE
How to pack with my_module

### ISSUE THREAD

**Issue by IdearHui** [dashingsoft/pyarmor#39]
I have a py script named a.py, it has import anothor script named b.py
in a.py: from b import xxx
when I use cmd: pyarmor pack a.py, it can pack sucessfully
but when I run excutable script in a/a, it throw me a bug like 
Traceback (most recent call last):
  File "projects/pyinstaller/dist/a.py", line 1, in <module>
  File "<frozen pyarmor_dlpm.a>", line 1, in <module>
ImportError: No module named 'b'

how do I handle this situation?

**Comment by jondy** [comment]
Does this way work?
```
cd /path/to/src
pyarmor obfuscate --output dist/obf a.py

pyinstaller --add-data dist/obf/*.lic \
            --add-data dist/obf/*.key \
            --add-data dist/obf/_pytransform.* \
            a.py dist/obf/a.py
```
Edit `a.spec`, insert 2 lines after `Analysis` object
```
a.scripts[0] = 'a', 'dist/obf/a.py', 'PYSOURCE'
for i in range(len(a.pure)):
    if a.pure[i][1].startswith(a.pathex[0]):
        a.pure[i] = a.pure[i][0], a.pure[i][1].replace(a.pathex[0], os.path.abspath('dist/obf'), a.pure[i][2]
```
Then
```
pyinstaller a.spec
dist/a/a
```

**Comment by IdearHui** [comment]
> Does this way work?
> 
> ```
> cd /path/to/src
> pyarmor obfuscate --output dist/obf a.py
> 
> pyinstaller --add-data dist/obf/*.lic \
>             --add-data dist/obf/*.key \
>             --add-data dist/obf/_pytransform.* \
>             a.py dist/obf/a.py
> ```
> Edit `a.spec`, insert 2 lines after `Analysis` object
> 
> ```
> a.scripts[0] = 'a', 'dist/obf/a.py', 'PYSOURCE'
> for i in range(len(a.pure)):
>     if a.pure[i][1].startswith(a.pathex[0]):
>         a.pure[i] = a.pure[i][0], a.pure[i][1].replace(a.pathex[0], os.path.abspath('dist/obf'), a.pure[i][2]
> ```
> Then
> 
> ```
> pyinstaller a.spec
> dist/a/a
> ```

do as what you've suggested, then I got a new problem
![image](https://user-images.githubusercontent.com/14813460/48772168-7dba2680-ecfe-11e8-8d41-315d0775976d.png)

any suggestion about that?

**Comment by IdearHui** [comment]
the problem in that picture occured when I run the cmd "pyinstaller a.spec"

**Comment by jondy** [comment]
Does pyinstaller work without obfuscation?
```
cd /path/to/src
pyinstaller a.py
dist/a/a
```

**Comment by IdearHui** [comment]
> Does pyinstaller work without obfuscation?
> 
> ```
> cd /path/to/src
> pyinstaller a.py
> dist/a/a
> ```

yes， pyinstaller can work well without obfuscation

**Comment by jondy** [comment]
Could you show me the patched `a.spec` which results in pyinstaller failed?

**Comment by jondy** [comment]
And does this example work?
```
   cd /usr/local/anaconda3/lib/python3.5/site-packages/pyarmor/examples/py2exe
   pyarmor pack hello.py
   dist/hello/hello 
```
In this example, `hello.py` imports another module `queens`, it's similar as your case.

**Comment by IdearHui** [comment]
> And does this example work?
> 
> ```
>    cd /usr/local/anaconda3/lib/python3.5/site-packages/pyarmor/examples/py2exe
>    pyarmor pack hello.py
>    dist/hello/hello 
> ```
> In this example, `hello.py` imports another module `queens`, it's similar as your case.

it can work well

**Comment by IdearHui** [comment]
> Could you show me the patched `a.spec` which results in pyinstaller failed?

here is the a.spec
`
block_cipher = None

a = Analysis(['a.py'],
pathex=['/home/wh/pyarmor_test/dist/obf'],
binaries=[],
datas=[('/home/wh/pyarmor_test/dist/obf/.lic', '.'), ('/home/wh/pyarmor_test/dist/obf/.key', '.'), ('/home/wh/pyarmor_test/dist/obf/_pytransform.*', '.')],
hiddenimports=[],
hookspath=[],
runtime_hooks=[],
excludes=[],
win_no_prefer_redirects=False,
win_private_assemblies=False,
cipher=block_cipher)

a.scripts[0] = 'a', 'dist/obf/a.py', 'PYSOURCE'
for i in range(len(a.pure)):
if a.pure[i][1].startswith(a.pathex[0]):
a.pure[i] = a.pure[i][0], a.pure[i][1].replace(a.pathex[0], os.path.abspath('dist/obf')), a.pure[i][2]
pyz = PYZ(a.pure, a.zipped_data,
cipher=block_cipher)
exe = EXE(pyz,
a.scripts,
exclude_binaries=True,
name='a',
debug=False,
strip=False,
upx=True,
console=True )
coll = COLLECT(exe,
a.binaries,
a.zipfiles,
a.datas,
strip=False,
upx=True,
name='a')
`

**Comment by jondy** [comment]
It seems `a.spec` missing a script. Replace `a = Analysis(['a.py'],` with
```
a = Analysis(['a.py', 'dist/obf/a.py'],
```
Then run `pyinstaller a.spec`

**Comment by jondy** [comment]
Do you run this command?
```
pyarmor obfuscate --output dist/obf a.py
```
It will generate obfuscated script `dist/obf/a.py`.

**Comment by IdearHui** [comment]
> Do you run this command?
> 
> ```
> pyarmor obfuscate --output dist/obf a.py
> ```
> It will generate obfuscated script `dist/obf/a.py`.

yep, you are right.
when I add 'dist/obf/a.py' in Analysis, I can sucessfully pack my code without error.
thank you very much for helping me to resolve this problem.

would you like to push a commit to resolve the problem?

and then I will close the issue.

**Comment by IdearHui** [comment]
> Do you run this command?
> 
> ```
> pyarmor obfuscate --output dist/obf a.py
> ```
> It will generate obfuscated script `dist/obf/a.py`.

yep, when I add 'dist/obf/a.py' in Analysis, I can sucessfully pack my code without error.
but I found that if I replace a = Analysis(['a.py'] with a = Analysis(['a.py', 'dist/obf/a.py'], I'll get an excutable file which was not obfuscated (because I delete the license.lic file don't have impact with the excuting of the excutable file); 
and if I replace a = Analysis(['a.py'] with a = Analysis(['dist/obf/a.py', 'a.py'], then I ran the excutable file, it throw me a bug as blow
![image](https://user-images.githubusercontent.com/14813460/48834159-03e67380-edb8-11e8-8b8f-02a6985bbdbe.png)
which "obf/DLPM_Interface.py" means a.py

**Comment by jondy** [comment]
Not only replace `a = Analysis(['a.py']`, but also add extra lines after analysis:
```
a.scripts[0] = 'a', 'obf/a.py', 'PYSOURCE'
for i in range(len(a.pure)):
    if a.pure[i][1].startswith(a.pathex[0]):
        a.pure[i] = a.pure[i][0], a.pure[i][1].replace(a.pathex[0], os.path.abspath('obf'), a.pure[i][2]
```
Refer to 
https://github.com/dashingsoft/pyarmor/blob/master/docs/pack-obfuscated-scripts.rst#work-with-pyinstaller

That's what `pyarmor pack` does.

**Comment by IdearHui** [comment]
> Not only replace `a = Analysis(['a.py']`, but also add extra lines after analysis:
> 
> ```
> a.scripts[0] = 'a', 'obf/a.py', 'PYSOURCE'
> for i in range(len(a.pure)):
>     if a.pure[i][1].startswith(a.pathex[0]):
>         a.pure[i] = a.pure[i][0], a.pure[i][1].replace(a.pathex[0], os.path.abspath('obf'), a.pure[i][2]
> ```
> Refer to
> https://github.com/dashingsoft/pyarmor/blob/master/docs/pack-obfuscated-scripts.rst#work-with-pyinstaller
> 
> That's what `pyarmor pack` does.

It still doesn't work
here is my a.spec


block_cipher = None


a = Analysis(['a.py', 'dist/obf/a.py'],
             pathex=['/home/wh/pyarmor_test'],
             binaries=[],
             datas=[('/home/wh/pyarmor_test/dist/obf/*.lic','.'), ('/home/wh/pyarmor_test/dist/obf/*.key','.'), ('/home/wh/pyarmor_test/dist/obf/*.so','.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)

a.scripts[0] = 'a', 'dist/obf/a.py', 'PYSOURCE'
for i in range(len(a.pure)):
    if a.pure[i][1].startswith(a.pathex[0]):
        a.pure[i] = a.pure[i][0], a.pure[i][1].replace(a.pathex[0], os.path.abspath('dist/obf')), a.pure[i][2]

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='a',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='a')

**Comment by IdearHui** [comment]
still got the exception
![image](https://user-images.githubusercontent.com/14813460/48876060-397e7180-ee37-11e8-9051-ae4a8e390e9f.png)

**Comment by jondy** [comment]
Check the file `dist/obf/a.py`, does it include 2 lines at the beginning?
```
from pytransform import pyarmor_runtime
pyarmor_runtime()
```
And check file `dist/obf/pytransform.py` exists.

In your `a.spec`, it seems asterisk missed in this line
```
datas=[('/home/wh/pyarmor_test/dist/obf/*.lic','.'), ('/home/wh/pyarmor_test/dist/obf/*.key','.'), ('/home/wh/pyarmor_test/dist/obf/*.so','.')],
```

In the final output `dist/a`, check the following files exist
```
pyshield.lic pyshield.key license.lic product.key _pytransform.so
```

**Comment by IdearHui** [comment]
> Check the file `dist/obf/a.py`, does it include 2 lines at the beginning?
> 
> ```
> from pytransform import pyarmor_runtime
> pyarmor_runtime()
> ```
> And check file `dist/obf/pytransform.py` exists.
> 
> In your `a.spec`, it seems asterisk missed in this line
> 
> ```
> datas=[('/home/wh/pyarmor_test/dist/obf/*.lic','.'), ('/home/wh/pyarmor_test/dist/obf/*.key','.'), ('/home/wh/pyarmor_test/dist/obf/*.so','.')],
> ```
> In the final output `dist/a`, check the following files exist
> 
> ```
> pyshield.lic pyshield.key license.lic product.key _pytransform.so
> ```

the files you mentioned are all in the right dictionary.

**Comment by IdearHui** [comment]
> Check the file `dist/obf/a.py`, does it include 2 lines at the beginning?
> 
> ```
> from pytransform import pyarmor_runtime
> pyarmor_runtime()
> ```
> And check file `dist/obf/pytransform.py` exists.
> 
> In your `a.spec`, it seems asterisk missed in this line
> 
> ```
> datas=[('/home/wh/pyarmor_test/dist/obf/*.lic','.'), ('/home/wh/pyarmor_test/dist/obf/*.key','.'), ('/home/wh/pyarmor_test/dist/obf/*.so','.')],
> ```
> In the final output `dist/a`, check the following files exist
> 
> ```
> pyshield.lic pyshield.key license.lic product.key _pytransform.so
> ```

and a.py contains the two line at the beginning
`from pytransform import pyarmor_runtime`
`pyarmor_runtime()`

**Comment by jondy** [comment]
Insert a line after analysis in `a.spec`
```
for item in a.pure:
  if item[1].endswith('pytransform.py'):
    print('===========================')
    print('%s found' % item[1])
```
Run `pyinstaller a.spec`

Check whether `pyinstaller`  find the depend module `pytransform`

**Comment by jondy** [comment]
If it still doesn't work, edit `a.spec`, change `Analysis` keyword parameter `noarchive`  to `True`

    noarchive=True

Then run `pyinstaller --clean a.spec`

Check whether `hello/a/pytransform.pyc` exists.

**Comment by IdearHui** [comment]
> Insert a line after analysis in `a.spec`
> 
> ```
> for item in a.pure:
>   if item[1].endswith('pytransform.py'):
>     print('===========================')
>     print('%s found' % item[1])
> ```
> Run `pyinstaller a.spec`
> 
> Check whether `pyinstaller` find the depend module `pytransform`

It can't find the depend module pytransform

**Comment by IdearHui** [comment]
> If it still doesn't work, edit `a.spec`, change `Analysis` keyword parameter `noarchive` to `True`
> 
> ```
> noarchive=True
> ```
> Then run `pyinstaller --clean a.spec`
> 
> Check whether `hello/a/pytransform.pyc` exists.

It threw me an exception as blow
![image](https://user-images.githubusercontent.com/14813460/48883904-fa631700-ee5c-11e8-8b7d-8e17d97ce96a.png)

**Comment by IdearHui** [comment]
ok, I fixed the bug when I add pytransform.py in datas as below
```a = Analysis(['a.py', 'dist/obf/a.py'],
             pathex=['/home/wh/pyarmor_test'],
             binaries=[],
             datas=[('/home/wh/pyarmor_test/dist/obf/*.lic','.'), ('/home/wh/pyarmor_test/dist/obf/*.key','.'), ('/home/wh/pyarmor_test/dist/obf/_pytransform.*','.'), ('/home/wh/pyarmor_test/dist/obf/pytransform.py','.')],```
