### ISSUE TITLE
[QUESTION] How do I get HDInfo on a computer without pyarmor?

### ISSUE THREAD

**Issue by betepok13** [dashingsoft/pyarmor#391]
Windows 10
Python 3.7.8 (64)
PyArmor 6.5.4
PyInstaller 4.0

On my computer with pyarmor installed, I execute the code (GenerateKey.py):
```
import base64

from pyarmor.pytransform import get_hd_info, pyarmor_init

pyarmor_init()
disk_info = get_hd_info(0)
mac_info = get_hd_info(1)
```
and get HDInfo and MACInfo. After that, I collect this code into a file using PyInstaller:

`c:\Python378_64\Scripts\pyinstaller.exe -F GenerateKey.py`

I run the file and get the error:

![изображение](https://user-images.githubusercontent.com/40733196/99364991-c09c3e00-28c7-11eb-8d61-bad2605b2a43.png)

Next, I add the directory with pyarmor to the project assembly:

`c:\Python378_64\Scripts\pyinstaller.exe -F --add-data="c:\Python378_64\Lib\site-packages\pyarmor;pyarmor" GenerateKey.py`

And I run the GenerateKey.exe file. My hard drive and MAC information is displayed. But if, I try to run this file on another computer, where Python and PyArmor are not installed, then an error occurs:

![изображение](https://user-images.githubusercontent.com/40733196/99365663-a7e05800-28c8-11eb-8510-31d510c2a507.png)

**My goal: to find out information about the hard disk on another computer in order to bind to it (generate a separate license for this computer). How to do it?**

**Comment by jondy** [comment]
There is a tool [hdinfo](https://github.com/dashingsoft/pyarmor-core#hdinfo) for this case exactly.

**Comment by betepok13** [comment]
> 
> 
> There is a tool [hdinfo](https://github.com/dashingsoft/pyarmor-core#hdinfo) for this case exactly.

How can I use it in my GenerateKey.py application code?

**Comment by jondy** [comment]
If you prefer to get the hard information by Python scripts, you could distribute `_pytransform.dll` and `pytransform.py` with `GenerateKey.py`, and  get the hdinfo by this way:
```
import pytransform
pytransform._pytransform = _load_library(is_runtime=1)
disk_info = pytransform.get_hd_info(0)
mac_info = pytransform.get_hd_info(1)
```
And pack it 
```
c:\Python378_64\Scripts\pyinstaller.exe -F --add-data="c:\Python378_64\Lib\site-packages\pyarmor\pytransform.py;." --add-binary="c:\Python378_64\Lib\site-packages\pyarmor\platforms\windows.x86_64\_pytransform.dll;." GenerateKey.py

**Comment by betepok13** [comment]
Location of files to archive:

![изображение](https://user-images.githubusercontent.com/40733196/99416318-cadf2c00-2909-11eb-9759-1afe8f6ff569.png)

Parameters for adding files (PyInstaller):

`--add-data="c:/Python378_64/Scripts/scripts/GenKeyData/pytransform.py;." --add-binary="c:/Python378_64/Scripts/scripts/GenKeyData/_pytransform.dll;."`

My code:
```
import base64

import pytransform

pytransform._pytransform = pytransform._load_library(is_runtime=1)
disk_info = pytransform.get_hd_info(0)
mac_info = pytransform.get_hd_info(1)
```

Result:

![изображение](https://user-images.githubusercontent.com/40733196/99416380-d7638480-2909-11eb-9bd3-19b63dd0638c.png)

**Comment by jondy** [comment]
I don't think you'll obfuscate the script because you pack the script by PyInstaller directly. Well, I got an idea, it's more easy if you will obfuscate the script. Because `pytransform` could be imported directly in the obfuscated script.
 
First create `GenerateKey.py` in a empty path

```python
import base64
from pytransform import hdinfo

disk_info = get_hd_info(0)
mac_info = get_hd_info(1)
```

Then create an exe in this path
```
cd mytool/
pyarmor pack -e " --onefile" GenerateKey.py
dist/GenerateKey.exe
```
