### ISSUE TITLE
Special characters not known in the output of an obfuscated script pack

### ISSUE THREAD

**Issue by HamzaMays** [dashingsoft/pyarmor#392]
I'm trying to obfuscate and pack my script that has some special characters such as (é, ç, è, à...).
Trying to pack directly with Pyinstaller and auto-py-to-exe work just fine. But after obfuscate the script and packing it with Pyarmor I got © everywhere in the my GUI. I've tried to add extra command to be used by Pyarmor with Pyinstaller but obvesoly --ascii, -a are not known by Pyinstaller itself!!!

Any help would be appreciated :D

**Comment by HamzaMays** [comment]
I've fix the problem by using unicode character, but it would be helpful if you fix this issue. Thanks in advance😁

**Comment by jondy** [comment]
Generally set source encoding in the start of script could fix most of encoding issue, refer to [ Source Code Encoding](https://docs.python.org/2.7/tutorial/interpreter.html#source-code-encoding)
