### ISSUE TITLE
Is there a way to allow modifying the entry point file?

### ISSUE THREAD

**Issue by saidelike** [dashingsoft/pyarmor#393]
I've used Python 3.8 to obfuscate the script.

If we use a different Python version between obfuscation and running the script, we get an error like (e.g. running with Python 2.7):

```
$ python2 program.py -h
Traceback (most recent call last):
  File "program.py", line 2, in <module>
    from pytransform import pyarmor
ImportError: No module named pytransform
```

If the license has expired, we get an error like this:

```
$ python3.8 program.py -h
[...]
RuntimeError: License is expired
```

I have tried to modify the `program.py` obfuscated file after it has been obfuscated by pyarmor to e.g. change:

```py
from pytransform import pyarmor
```

into 

```py
try:
    from pytransform import pyarmor
except ImportError as e:
    import sys
    if str(e) == "No module named pytransform":
        print("[!] Python 3.8 64-bit is required")
        sys.exit(1)
    raise(e)
```

and it works fine to catch the exception:

```
program$ python2 program.py -h
[!] Python 3.8 64-bit is required
```

however then I can't run the script in a normal way:

with `--restrict 0`:

```py
$ python3.8 program.py -h
Traceback (most recent call last):
  File "<program.py>", line 21, in <module>
  File "<program.py>", line 12, in <module>
  File "<frozen program>", line 131, in <module>
  File "<frozen program>", line 125, in protect_pytransform
  File "<frozen program>", line 101, in check_obfuscated_script
RuntimeError: unexpected obfuscated script
```

with `--restrict 5`:

```py
$ python3.8 program.py -h
Traceback (most recent call last):
  File "<program.py>", line 21, in <module>
  File "<program.py>", line 12, in <module>
RuntimeError: Check restrict mode of module failed
```

Maybe related to https://github.com/dashingsoft/pyarmor/issues/280?

Any idea how to solve my problem?

**Comment by jondy** [comment]
The major/minor version of Python in build machine should be same as in target machine. Because the scripts will be compiled to byte-code before they’re obfuscated, so the obfuscated scripts can’t be run by all the Python versions as the original scripts could.

Here are [some other differences](https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts)

**Comment by jondy** [comment]
About restrict issue, also set `--no-cross-protection` and `--restrict 0` to ignore the protection code

**Comment by saidelike** [comment]
I know all that. But I want to be able to catch the exceptions triggered to clarify the problem. "ImportError: No module named pytransform" is not easy to understand so I want to replace it with "[!] Python 3.8 64-bit is required"

**Comment by jondy** [comment]
How about obfuscating the scripts with `--no-cross-protection` too? For example,
```
pyarmor obfuscate --no-cross-protection --restrict 0 --advanced 2 program.py
```
Then patch `dist/program.py` as you have shown. 

Option `--no-cross-protection` should fix this exception `RuntimeError: unexpected obfuscated script`

**Comment by saidelike** [comment]
Thanks.

Yes, adding `--no-cross-protection` to `--restrict 0` makes it work. I can now tweak `program.py` after pyarmor obfuscation.
