### ISSUE TITLE
代码中包含中文换行的情况下，加密失败的问题

### ISSUE THREAD

**Issue by xingwenchao** [dashingsoft/pyarmor#394]
作者你好。
如下代码
`msg = (u'''中文换行`
       ` 中文换行''')`
`print(msg)`
上面代码加密之后，会报如下错误：
RuntimeError: Marshal loads failed
希望作者能够帮助解答一下，谢谢。

**Comment by jondy** [comment]
请在文件头部指定正确 source encoding，例如
```
# -*- coding: utf-8 -*-
```
请参考这里
https://docs.python.org/2.7/tutorial/interpreter.html#source-code-encoding

**Comment by xingwenchao** [comment]
谢谢，已解决
