### ISSUE TITLE
Dlopen failed

### ISSUE THREAD

**Issue by worldvideos1203** [dashingsoft/pyarmor#396]
$ python add.py
dlopen failed: couldn't map "/storage/emulated/0/gramtool6/dist/pytransform/_pytransform.so" segment 1: Operation not permitted
$ python3 add.py
dlopen failed: couldn't map "/storage/emulated/0/gramtool6/dist/pytransform/_pytransform.so" segment 1: Operation not permitted

Android 10..using termux!.. Faced same using pydroid3.
Should i move some file to different folder??
I have root permissions i can do that... Plz guide

**Comment by jondy** [comment]
I know some linuxs don't allow to load dynamic library in data file, but I don't know where is allowed. But you can search any other `.so` which works to find which path is OK
