### ISSUE TITLE
Obfuscate dependencies

### ISSUE THREAD

**Issue by Jurij1337** [dashingsoft/pyarmor#397]
Hi want to obfuscate my code and everything what is in my venv too.

Is that possible? I tried a lot and it did not work

**Comment by jondy** [comment]
The Python system module `os`, `ctypes`  could not be obfuscated, and PyArmor runtime module `pytransform` also could not be obfuscated.

**Comment by Jurij1337** [comment]
And how about the rest? Is there an easy way to do it? Or do I have to develop my own solution?

**Comment by jondy** [comment]
Super mode may work, try to obfuscate script with `--advanced 2`, note that for trial version the big script can't be obfuscated by super mode.
