### ISSUE TITLE
关于异常捕获信息不统一的一个问题

### ISSUE THREAD

**Issue by xingwenchao** [dashingsoft/pyarmor#403]
作者你好，请看下面的代码，类似这种格式的代码，加密和未加密会抛出不同的异常。
```python
def bbb():
    raise AttributeError("zzz")


def get_log_identify():
    try:
        return bbb()
    except AttributeError:
        return None
    except Exception:
        return None

def ccc():
    raise Exception("zqb")

def aaa():
    try:
        ccc()
    except Exception as ex:
        get_log_identify()
        raise


aaa()
```

这个代码加密会抛出异常为：
```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    aaa()
  File "test.py", line 17, in aaa
    ccc()
  File "test.py", line 13, in ccc
    raise Exception("zqb")
Exception: zqb
```
不加密的情况下会抛出异常为：
```
Traceback (most recent call last):
  File "<test.py>", line 3, in <module>
  File "<frozen test>", line 22, in <module>
  File "<frozen test>", line 7, in get_log_identify
  File "<frozen test>", line 2, in bbb
AttributeError: zzz
```

我的环境是pyarmor-6.4.2版本;python-2.7.3版本;

**Comment by jondy** [comment]
我刚才跑了一下，的确有这个问题，这个需要修改核心库，下一个版本会修正。

可能的话，建议你使用超级模式来加密脚本，这个模式更安全，使用更简单，也没有这个问题，:)

参考这里 https://pyarmor.readthedocs.io/zh/latest/advanced.html

**Comment by xingwenchao** [comment]
嗯，按照你给出的提示，尝试执行pyarmor.py o --advanced 2 test.py
但是没有给出提示要下载哪个pytransform.so文件。提示信息吐下:
`INFO     PyArmor Version 6.4.2
INFO     Target platforms: Native
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r34.8/platforms/index.json
INFO     Could not get file from https://github.com/dashingsoft/pyarmor-core/raw/r34.8/platforms: <urlopen error timed out>
INFO     Getting remote file: https://pyarmor.dashingsoft.com/downloads/r34.8/index.json
INFO     Could not get file from https://pyarmor.dashingsoft.com/downloads/r34.8: <urlopen error timed out>
ERROR    No platform list file /data/user/.pyarmor/platforms/index.json found`

**Comment by xingwenchao** [comment]
我根据这个提示把index.json放到我的目录下，然后执行pyarmor.py o --advanced 2 test.py得到了一下结果
ERROR    No available dynamic library for centos6.x86_64.11.py27 with features ['11']
执行pyarmor -d hdinfo 信息为：
`DEBUG    PyArmor installation path: /sf/test/pyarmor/pyarmor-6.4.2/src
DEBUG    PyArmor home path: /root/.pyarmor
DEBUG    Native platform is centos6.x86_64
DEBUG    Search dynamic library in the path: /sf/test/pyarmor/pyarmor-6.4.2/src/platforms
DEBUG    Search dynamic library in the path: /root/.pyarmor/platforms
DEBUG    Loaded dynamic library: /root/.pyarmor/platforms/centos6/x86_64/_pytransform.so
DEBUG    The version of core library is (34, 8, 7)
INFO     PyArmor Version 6.4.2`

**Comment by jondy** [comment]
请参考文档[如何人工下载和配置动态库](https://pyarmor.readthedocs.io/zh/latest/platforms.html?aaaadd#id47)

**Comment by jondy** [comment]
另外一个小提示，程序的输出 前后都使用三个引号，这样显示的时候就会正确换行。只用一个引号，就只是显示为一行，看起来很不直观。

**Comment by jondy** [comment]
centos6 的确没有对应的超级模式动态库，不需要在试了。

**Comment by xingwenchao** [comment]
如果我现在要在centos6使用超级模式或者要解决此问题是否有解决的方法，或者这个会在后续的版本中修复这个问题吗

**Comment by jondy** [comment]
办法也是有的，就是使用 `linux.x86_64.11.py27` 对应的超级模式动态库来代替，但是要做一个补丁，因为 centos 使用的 GLIBC 版本太低了。首先下载 `linux.x86_64.11.py27` 对应的动态库，然后拷贝到 centos6 上面，但是目标路径要修改为 `~/.pyarmor/platforms/centos6/x86_64/11/py27`，然后打两个补丁

1. 对 `~/.pyarmor/platforms/centos6/x86_64/11/py27/pytransform.so` 打补丁，参考这里
    https://pyarmor.readthedocs.io/zh/latest/questions.html#lib64-libc-so-6-version-glibc-2-14-not-found

2. 对 `platforms/index.json` 打补丁，把平台名称 `linux.x86_64.11.py27` 修改为 `centos6.x86_64.11.py27`，把下面的 `sha256` 的值替换为打包后的值

这样就可以在 centos6 上使用超级模式加密了

**Comment by xingwenchao** [comment]
chroot外部 & libc-2.17.so可以解决问题，是但是我的chroot内是libc-2.13.so，打补丁之后出现了
'''ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /sf/test-lib/enc/dist/pytransform.so)'''
是否可以有方法兼容libc-2.13

**Comment by jondy** [comment]
小于 libc-2.14 都是一样的。

这个 bug 我已经修改好了，下一个版本中会发布的。

**Comment by xingwenchao** [comment]
好的，请问下一个版本的发布版本号以及发布时间

**Comment by xingwenchao** [comment]
我这里通过打补丁的方式修改了pytransform.so后 运行时，出现了报错信息如下：
```Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pytransform import pyarmor
ImportError: /sf/test-lib/enc/dist/pytransform.so: undefined symbol: PyUnicodeUCS4_AsUTF8String```

**Comment by xingwenchao** [comment]
打补丁时使用的so为https://github.com/dashingsoft/pyarmor-core/raw/r34.8/platforms/linux.x86_64.11.py27/pytransform.so

**Comment by jondy** [comment]
`PyUnicodeUCS4_AsUTF8String` 这个问题在最新的版本中已经解决了。

另外，这里有一个预发布的包，可以直接用 pip 或者直接下载下来安装，这个已经解决了 Python 2.7 异常不正确的问题

https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.5.6.zip

**Comment by xingwenchao** [comment]
好的，非常感谢，目前用最新的包已经解决了该问题。
顺便问一句，centos6给pytransform.so打补丁包的方式在6.5.6这个预发布的版本仍然会出现PyUnicodeUCS4_AsUTF8String这个问题。

**Comment by jondy** [comment]
> 顺便，centos6给pytransform.so打补丁包的方式在6.5.6这个预发布的版本仍然会出现PyUnicodeUCS4_AsUTF8String这个问题。

这个问题我搞错了，现在用的就是 `PyUnicodeUCS4_AsUTF8String` ，因为默认情况下 linux 下的 Python 都是使用 UCS4 的，你的这个 centos6 Python 应该使用的是 UCS2，所以没有这个 API。

**Comment by xingwenchao** [comment]
好的，请问后续会支持centos6使用超级模式吗

**Comment by jondy** [comment]
已经支持了，你把预发布包重新下载安装一下，就可以在 centos6 下面使用超级模式了。

**Comment by xingwenchao** [comment]
我还有一个问题想要了解：在我的软件包里有两个APP应用分别为app1,app2，第一次加密，生成的so库对对两个APP应用都能正常使用。过一段时间后app1更新了，重新对app1加密，第一次生成的的os包是否影响app1的正常运行。

**Comment by jondy** [comment]
使用命令 `runtime` 生成独立的运行辅助包，加密的时候指定运行辅助包，这样重新加密之后就可以只替换修改过的加密脚本。

请参考 https://pyarmor.readthedocs.io/zh/latest/man.html#runtime

但是如果 PyArmor 出现重大升级，那么就需要重新全部加密，并替换原来的运行辅助包，这种不兼容情况会在版本更新日志中有说明的。

**Comment by yq1320** [comment]
@jondy  使用命令 runtime 生成独立的运行辅助包，支持超级+工程模式嘛？

```pyarmor runtime -i``` 生成运行辅助包嘛？成的运行辅助使用这个```pytransform_bootstrap```？

需要修改site.py文件吗？

```
HOST01 ~/test/dist # ll
total 1132
drwxr-xr-x 3 root root    4096 Dec  5 10:38 log-use-debug-master/
-rw-r--r-- 1 root root    4801 Dec  5 10:38 main.py
drwxr-xr-x 3 root root    4096 Dec  5 10:38 pytransform_bootstrap/
-rw-r--r-- 1 root root    1905 Dec  5 10:38 test.py
```

**Comment by jondy** [comment]
@yq1320  支持工程模式的，使用命令 `build` 的时候指定 `--runtime` 选项就可以了，其他问题请参阅文档里面的相关说明。

**Comment by xingwenchao** [comment]
@jondy 使用预发布包6.5.6 在py27 centos6环境使用超级模式仍然报错，内容为：
```Traceback (most recent call last):
  File "__init__.py", line 1, in <module>
    from pytransform import pyarmor
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /sf/vs/lib/python-srv/dist/pytransform.so)```
是否仍然需要打补丁的方式解决

**Comment by jondy** [comment]
@xingwenchao 重新下载一下，我刚刚更新过，原来的是有问题。

**Comment by xingwenchao** [comment]
@jondy ok，超级模式目前是可用的，还有一个问题要确认一下，我的代码有一部分代码是是用pyarmor6.4.2版本进行加密的，如果我想用pyarmor6.5.6加密另一部分代码，而且这两部分代码是互相依赖的，那这种情况是否可用呢？是不是我要升级pyarmor的版本，就需要重新加密这部分互相依赖的全部代码

**Comment by jondy** [comment]
这个问题我前面解释过了吧，查看一下变更日志里面有没有不兼容的说明，没有的话就可以的，但是超级模式和非超级模式是不能混合使用的。

**Comment by xingwenchao** [comment]
是这样的，我是想描述的是模块A使用的是6.4.2版本加密，模块B使用6.5.6加密，两者都不使用超级模式，模块A依赖导入模块B，这种情况是否支持呢

**Comment by xingwenchao** [comment]
你说的变更日志是指的pyarmor版本更新时的日志是吗？

**Comment by jondy** [comment]
不同版本的兼容性说明请看参考这里
https://pyarmor.readthedocs.io/zh/latest/change-logs.html

**Comment by xingwenchao** [comment]
谢谢你的回答，关于这类问题已经得到解决。
