### ISSUE TITLE
building obfuscated code runnable with python37 and python38

### ISSUE THREAD

**Issue by lumpi101** [dashingsoft/pyarmor#404]
I've tried a bit obfuscating code und running it with other python versions and noticed that
- code which is obfuscated using python 3.7.xxx is runnable by python 3.7.xxx but not by python 3.8.xxx and vice versa
- code which is obfuscated using python 3.8.xxx is runnable by python 3.8.xxx but not by python 3.7.xxx

The error raised then is `RuntimeError: Marshal loads failed` (which may happen because the marshal package is not intended to be backwards compatible, according to https://docs.python.org/3/library/marshal.html)

Is there a way to overcome this drawback (meaning, how to obfuscate code so that it is runnable by python versions 3.7 **and** 3.8)?

**Comment by jondy** [comment]
No. It's impossible to run the obfuscated code by both python3.7 and 3.8.

Refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts
