### ISSUE TITLE
[Query] Getting caller information in obfuscated files.

### ISSUE THREAD

**Issue by piyush-das** [dashingsoft/pyarmor#406]
Hi,

I have a certain decorator which depends on `inspect.stack` to get information about the caller and hence act accordingly. Pyarmor for obvious security reasons disables the stack. As such could you please suggest me alternative ways to get information about the caller of the function without compromising with the security.

Thanks

**Comment by jondy** [comment]
The caller frame can be got by `sys._getframe(1)`, the function name of caller can be got by this way:
```
frame = sys._getframe(1)
print(frame.f_code.co_name)
```

**Comment by piyush-das** [comment]
Thanks
