### ISSUE TITLE
issue with runing the program after compile it

### ISSUE THREAD

**Issue by devlop7** [dashingsoft/pyarmor#407]
i have this issue 
pkg_resources.DistributionNotFound: The 'tendo' distribution was not found and is required by the application

even i install the lib

**Comment by jondy** [comment]
Please check `sys.path` in the source script where to import `tendo`, make sure `tendo` in the Python path.

If the obfuscated script adds some extra path based on `__file__` to `sys.path`, make sure it run in module level. In the function, `__file__` isn't the real script name, but like this `<frozen name>`

Refer to http://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts
