### ISSUE TITLE
aarch64 platforms: undefined symbol: `PyUnicodeUCS2_AsUTF8String

### ISSUE THREAD

**Issue by xingwenchao** [dashingsoft/pyarmor#408]
我的代码有些需要部署到aarch64平台，平台信息为
Linux dmoc-e00084ab5cd0 4.19.90-11.ky10.aarch64 #1 SMP Sat May 23 11:36:32 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

超级模式下加密之后执行加密代码的时候出现了如下信息:
```Traceback (most recent call last):
  File "genpkgmetadata.py", line 2, in <module>
    from pytransform import pyarmor
ImportError: /data/Indie/test/dist/pytransform.so: undefined symbol: `PyUnicodeUCS2_AsUTF8String```

**Comment by xingwenchao** [comment]
pyarmor使用的是最新的预发布6.5.6

**Comment by jondy** [comment]
已经解决，请重新下载预发布版本 [v6.5.6](https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.5.6.zip)

**Comment by xingwenchao** [comment]
ok，是否能提供与github结构一致的源码包（就是如果推送上github发布的结构，so文件另外放在pyarmor-core仓库的）或者，6.5.6有发布计划吗

**Comment by jondy** [comment]
上面不是有预发布包的下载链接地址吗？v6.5.6 可能在这个月底前后正式发布吧
