### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by fieu** [dashingsoft/pyarmor#409]
I am getting an M1 MacBook Air soon. I was wondering, does PyArmor work with the new M1 chip? I know Python 3.9.1 is supported but I know PyArmor has platform specific distributions.

**Comment by VeNoMouS** [comment]
it's not CPU specific, its OS build dependent ... so it really comes down to weather the M1 runs as "darwin"

**Comment by fieu** [comment]
@VeNoMouS The M1 macs do recognize as darwin, but are arm64/aarch64. PyArmor only has platform specific dependencies for the x86_64 Intel macs at the moment. That is why I am asking.

Source: https://github.com/dashingsoft/pyarmor-core/tree/master/platforms

**Comment by VeNoMouS** [comment]
ah, yea then @jondy will have to release new build

**Comment by jondy** [comment]
There is a platform `darwin.arm64` but is built with iPhoneOS9.3.sdk, please first try it works or not. 
```
pyarmor obfuscate --platform darwin.arm64 foo.py
```
And there is no supper mode for this platform.

**Comment by fieu** [comment]
@jondy  once I get it I will tell you

**Comment by VeNoMouS** [comment]
When are you buying @jondy one @fieu ? ;P

**Comment by fieu** [comment]
> When are you buying @jondy one @fieu ? ;P

It's coming the 21st-30th. :D

**Comment by VeNoMouS** [comment]
@jondy ... sorry for the piggy back on this ticket... but i figured it was easier use this one as its related

```
WARNING:root:This platform name `darwin.arm64` has been deprecated, use `darwin.aarch64` 
```

so switched over to `darwin.aarch64`

and get this error...

```
RuntimeError: No available dynamic library for darwin.aarch64 with features ['11']
```

**Comment by jondy** [comment]
py3.7 is not supported in this platform, refer to
https://pyarmor.readthedocs.io/en/latest/platforms.html#the-prebuilt-extensions-for-super-mode

**Comment by VeNoMouS** [comment]
Ah, cheers for that @jondy will let my users know if they inquire ❤️
