### ISSUE TITLE
Print encoding error

### ISSUE THREAD

**Issue by ANTRANCUSAUX** [dashingsoft/pyarmor#417]
I use this command to create a script (it is very important for me that there is only one file)
`pyarmor pack -e " --onefile" main.py`

main.py
`print("Привет мир!")`
(The text to be printed is encoded with Cyrillic windows-1251)

But in the console it prints "РџСЂРёРІРµС‚ РјРёСЂ!"
If I run a clean script without using a pyarmor, then everything is fine and prints in the correct encoding. If I use a pyinstaller, then everything is fine too, but it is with a pyarmor that incomprehensible symbols

Incomprehensible symbols appear not only in the console, but also when using a PyQt or Tkinter. Always if I use Cyrillic

**Comment by jondy** [comment]
Please set the corresponding source encoding in the first line of the python scripts, refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#xxx-codec-can-t-decode-byte-0xxx

**Comment by ANTRANCUSAUX** [comment]
> Please set the corresponding source encoding in the first line of the python scripts, refer to
> https://pyarmor.readthedocs.io/en/latest/questions.html#xxx-codec-can-t-decode-byte-0xxx

Thank you!
