### ISSUE TITLE
Exeption when using __del__ in a class

### ISSUE THREAD

**Issue by guyrose3** [dashingsoft/pyarmor#419]
Hi, I'm using pyarmor to obfuscate my code.
I have a class, which is not in a file of one of pyarmor's entry point.
When This class goes out of scope, I get the following exception:

Exception ignored in: <bound method CartContentHandler.__del__ of <cart_blocks.cart_content_handler.CartContentHandler object at 0x7f53aa05c0>>
Traceback (most recent call last):
File "<frozen cart_blocks.cart_content_handler>", line 97, in __del__
NameError: name '__armor_enter__' is not defined

I'm not getting any exception when running the code w/o pyarmor.
Any ideas?

**Comment by jondy** [comment]
If the scripts is obfuscated by restrict mode 4 or 5, try to obfuscate them with restrict mode 1.

**Comment by prapti1998** [comment]
did you solve this? i am still getting the error with restrict mode of 1

**Comment by jondy** [comment]
Try to use super mode to obfuscate the scripts.

**Comment by prapti1998** [comment]
I am new to pyarmor, and I tried looking at the documentations too, but when I try to obfuscate by supermode, the pytransform module which was getting built without using supermode is not getting built and i am getting an error of 
 ```    from pytransform import pyarmor
ModuleNotFoundError: No module named 'pytransform'```

any idea why?

**Comment by jondy** [comment]
Rename this `pytransform.xxx.so` to `pytransform.so`, then try it again.

**Comment by prapti1998** [comment]
Thanks for answering. Tried this and now it is able to find pytransform, but i am getting a new error:
```

**Comment by jondy** [comment]
@prapti1998 

Could you pick your code and make a minimum script to reproduce this issue? It may help find the problem
