### ISSUE TITLE
Question on Pyarmor Super Mode

### ISSUE THREAD

**Issue by saurabht16** [dashingsoft/pyarmor#420]
**Not an issue but more of a question,**

When obfuscating with pyarmor for platform: musl.x86_64 in Super mode, I am getting below error:
**ERROR    ('No feature %s for platform %s', ['11'], 'musl.x86_64')**

Seems super mode for Alpine is not supported. Can you please confirm

Command used to Obfuscate:
pyarmor obfuscate  --advanced 2 --platform musl.x86_64  main.py

[Output]
INFO     PyArmor Trial Version 6.5.5
INFO     Target platforms: ['musl.x86_64']
ERROR    ('No feature %s for platform %s', ['11'], 'musl.x86_64')

**Comment by jondy** [comment]
No, super mode for Alpine is not supported now.

**Comment by saurabht16** [comment]
Thank you for your response and confirmation.

Any idea when you will start supporting super mode in Alpine.

Regards,
Saurabh

**Comment by jondy** [comment]
I'll build them next month, if it works, it will be published with next release.

**Comment by jondy** [comment]
@saurabht16 
Here is a pre-release package which support super mode for Alpine (musl.x86_64)
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.5.6.zip

Download it or install it by `pip` directly

**Comment by saurabht16** [comment]
@jondy Thank you so much for sharing this. I will test and let you know in case of any issues. Thanks

**Comment by saurabht16** [comment]
@jondy
I am getting 404 not found error when downloading. Can you please check.

**Comment by jondy** [comment]
@saurabht16 
Sorry, try this link
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.0.zip

**Comment by saurabht16** [comment]
@jondy  Sorry but the new package is not working for Alpine based docker images. If I obfuscate the code and try importing the package in Docker, it comes out of Python prompt doing nothing. There is no error message as well.

I tried both super and normal mode, and both fails.

But with old package, it works with normal mode.

>>> import cnm_apis
bash-5.0# python3


Obfuscation logs generated for both
For new 6.6.0: Application fails in both super and normal mode.

INFO     PyArmor Trial Version 6.6.0
INFO     Target platforms: ['musl.x86_64']
INFO     Update target platforms to: ['musl.x86_64.7']
INFO     Source path is "/home/stewary/obfuscation/build/dist/cnm-apis/cnm_apis"
INFO     Entry scripts are ['main.py']
INFO     Use cached capsule /home/stewary/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Auto exclude output path "dist"
no previously-included directories found matching 'dist'
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Copying /home/stewary/.pyarmor/platforms/musl/x86_64/7/_pytransform.so
INFO     Patch library dist/pytransform/_pytransform.so
INFO     Patch library file OK
INFO     Copying /home/stewary/.local/lib/python3.7/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK

From Old: It works:

INFO     PyArmor Trial Version 6.5.6
INFO     Target platforms: ['musl.x86_64']
INFO     Update target platforms to: ['musl.x86_64.0']
INFO     ====================================================
INFO     Reload PyArmor with platform: linux.x86_64.0
INFO     ====================================================
INFO     PYARMOR_PLATFORM is linux.x86_64.0
INFO     Source path is "/home/stewary/obfuscation/build/dist/cnm-apis/cnm_apis"
INFO     Entry scripts are ['cnm_apis/__init__.py']
INFO     Use cached capsule /home/stewary/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Save obfuscated scripts to "dist/cnm_apis"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 0
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Generating runtime files to dist/cnm_apis/pytransform
INFO     Extract pytransform.key
INFO     Generate no restrict mode license file
INFO     The platform musl.x86_64.0 is out of date
INFO     Search library for platform: musl.x86_64.0
INFO     Found available libraries: ['musl.x86_64.0']
INFO     Target path for musl.x86_64.0: /home/stewary/.pyarmor/platforms/musl/x86_64/0
INFO     Downloading library file for musl.x86_64.0 ...
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r38.12/platforms/alpine/_pytransform.so
INFO     Writing target file: /home/stewary/.pyarmor/platforms/musl/x86_64/0/_pytransform.so
INFO     Download dynamic library musl.x86_64.0 OK
INFO     Copying /home/stewary/.pyarmor/platforms/musl/x86_64/0/_pytransform.so
INFO     Patch library dist/cnm_apis/pytransform/_pytransform.so
INFO     Patch library file OK
INFO     Copying /home/stewary/.local/lib/python3.7/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...

**Comment by jondy** [comment]
Is there any extra error message when run the obfuscated scripts with `-d`, for example,
```
python -d dist/main.py
```
It will generate a log file `pytransform.log`, what's the content of this log file?

**Comment by jondy** [comment]
I also upload 3 test binary files
https://pyarmor.dashingsoft.com/downloads/temp/foo
https://pyarmor.dashingsoft.com/downloads/temp/foo-1
https://pyarmor.dashingsoft.com/downloads/temp/foo-2

Check whether they could run in the docker, and what's the output of each one?

**Comment by saurabht16** [comment]
@jondy 
No errors when running main.py. I do not get any errors as well:
Content of pytransform.log
bash-5.0# cat pytransform.log
The core library version: r38, age: 12, features: 3
bash-5.0# python -d main.py
bash-5.0#

Output of 3 binary files:
bash-5.0# ./foo
carmor_set_key_iv at 0x0x401370
bash-5.0# ./foo-1
carmor_set_key_iv at 0x0x401370
bash-5.0# ./foo-2
carmor_set_key_iv at 0x0x401370


Let me if you need any more information. Please note that i haven't even tried supermode. It's not running in normal mode even with this new package.

**Comment by jondy** [comment]
How about run both of these files in docker?
https://pyarmor.dashingsoft.com/downloads/temp/incr
https://pyarmor.dashingsoft.com/downloads/temp/foo-3

The first one should print one line `5 + 1 = 6`

**Comment by saurabht16** [comment]
@jondy 
Results below:

bash-5.0# ./incr
5 + 1 = 6

bash-5.0# ./foo-3
carmor_set_key_iv at 0x0x401330
got carmor_set_key_iv
carmor_set_key_iv return 0x0
35 c2 4d 66 6d 42 35 16 c5 e2 5d 66 7d 62 45 56
15 02 ed e6 0d 02 15 16
c5 26 0d 32 fd 06 15 22
01 02 03 04 05 06 07 08 11 12 13 14 15 16 17 18
21 22 23 24 25 26 27 28 f1 f2 f3 f4 f5 f6 f7 f8

35 c2 4d 66 6d 42 35 16 c5 e2 5d 66 7d 62 45 56
15 02 ed e6 0d 02 15 16
c5 26 0d 32 fd 06 15 22
protected_foo return 70
Test performance: 1000 loops

**Comment by jondy** [comment]
Nice, it seems some features don't work in docker. Please verify the following files in the docker
https://pyarmor.dashingsoft.com/downloads/temp/foo-4
https://pyarmor.dashingsoft.com/downloads/temp/foo-5
https://pyarmor.dashingsoft.com/downloads/temp/foo-6

**Comment by saurabht16** [comment]
@jondy 
Please find below the output of three files:

**bash-5.0# ./foo-4**
carmor_set_key_iv at 0x0x401330
got carmro_set_key_iv
carmor_set_key_iv return 0x0
35 c2 4d 66 6d 42 35 16 c5 e2 5d 66 7d 62 45 56
15 02 ed e6 0d 02 15 16
c5 26 0d 32 fd 06 15 22
01 02 03 04 05 06 07 08 11 12 13 14 15 16 17 18
21 22 23 24 25 26 27 28 f1 f2 f3 f4 f5 f6 f7 f8

35 c2 4d 66 6d 42 35 16 c5 e2 5d 66 7d 62 45 56
15 02 ed e6 0d 02 15 16
c5 26 0d 32 fd 06 15 22
protected_foo return 70
Test performance: 1000 loops
Time elapsed at line 116   : 36865205L us, 36865 ms, total is 36865205L
bash-5.0#
bash-5.0#
bash-5.0#
**bash-5.0# ./foo-5**
carmor_set_key_iv at 0x0x401330
got carmro_set_key_iv
carmor_set_key_iv return 0x0
35 c2 4d 66 6d 42 35 16 c5 e2 5d 66 7d 62 45 56
15 02 ed e6 0d 02 15 16
c5 26 0d 32 fd 06 15 22
01 02 03 04 05 06 07 08 11 12 13 14 15 16 17 18
21 22 23 24 25 26 27 28 f1 f2 f3 f4 f5 f6 f7 f8

35 c2 4d 66 6d 42 35 16 c5 e2 5d 66 7d 62 45 56
15 02 ed e6 0d 02 15 16
c5 26 0d 32 fd 06 15 22
protected_foo return 70
Test performance: 1000 loops
Time elapsed at line 116   : 37434252L us, 37434 ms, total is 37434252L
bash-5.0#
bash-5.0#
bash-5.0#
**bash-5.0# ./foo-6**
carmor_set_key_iv at 0x0x401330
got carmro_set_key_iv
carmor_set_key_iv return 0x0
35 c2 4d 66 6d 42 35 16 c5 e2 5d 66 7d 62 45 56
15 02 ed e6 0d 02 15 16
c5 26 0d 32 fd 06 15 22
01 02 03 04 05 06 07 08 11 12 13 14 15 16 17 18
21 22 23 24 25 26 27 28 f1 f2 f3 f4 f5 f6 f7 f8

35 c2 4d 66 6d 42 35 16 c5 e2 5d 66 7d 62 45 56
15 02 ed e6 0d 02 15 16
c5 26 0d 32 fd 06 15 22
protected_foo return 70
Test performance: 1000 loops
Time elapsed at line 116   : 37360928L us, 37360 ms, total is 37360928L
bash-5.0#

**Comment by jondy** [comment]
Please download the updated pre-release v6.6.0 package
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.0.zip

Feel free to let me know if there is any issue

**Comment by saurabht16** [comment]
@jondy 
Thanks for the latest updated package. It works!!! 👍 

I will not try to obfuscate my actual app and run it in Docker. Will connect with you in case of any issues.

By the way, is there a way i can mention data files in Pyarmor so that the dist folder where obfuscated files are bieng copied, it adds those data files as well as it is. For example config files. 
My app needs the configuration files to run, and i add it manually after obfuscation in current setup.
Thanks in advance.

**Comment by jondy** [comment]
Use project and configure project attribute `manifest` to include the data files, all the `.py` files in project will be obfuscated, and the other files will be copied to output path.

Refer to
https://pyarmor.readthedocs.io/en/latest/project.html

**Comment by saurabht16** [comment]
Hi @jondy Found another issue. Seems the library for linux and musl is named the same, so when configuring a project that can support multiple platforms, i get a error:

INFO     Copying /home/stewary/.pyarmor/platforms/musl/x86_64/11/py37/pytransform.cpython-37m-x86_64-linux-gnu.so
INFO     Patch extension /home/stewary/obfuscation/build/cnb-db/dist/cnm_db/pytransform.cpython-37m-x86_64-linux-gnu.so
INFO     Patch library file OK
INFO     Copying /home/stewary/.pyarmor/platforms/linux/x86_64/11/py37/pytransform.cpython-37m-x86_64-linux-gnu.so
**_### ERROR    Multiple platforms confilt with same extension name "pytransform.cpython-37m-x86_64-linux-gnu.so"_**

Can you please help with a solution here

**Comment by jondy** [comment]
I suggest you build different package for each platform.

If you prefer to one unique package, one solution is to customize runtime package `pytransform` by this way

1. Generate runtime library for 2 platforms separately
```
pyarmor runtime --advanced 2 --platform linux.x86_64 -O pytransform/linux
pyarmor runtime --advanced 2 --platform musl.x86_64 -O pytransform/musl
```

2. Create script `pytransform/__init__.py`
```python
import platform
cname, cver = platform.libc_ver()

if cname == 'musl':
    from musl.pytransform import pyarmor
else:
    from linux.pytransform import pyarmor
```

Then obfuscate your scripts without runtime and no cross protection, and copy package `pytransform` to the output path

**Comment by saurabht16** [comment]
Thanks @jondy I will try above steps. I hope this will work for add_suffix option as well?

**Comment by saurabht16** [comment]
@jondy Thanks for all your support. I have successfully tested some of my scenarios and they are working well. 

When will you be publishing version 6.6.0 in pypi?

You can also close this issue if need be.

**Comment by jondy** [comment]
It. may be published in next week.
