### ISSUE TITLE
Segmentation Fault on Python 3.9 with Pyarmor 6.5.6, 6.5.5 and 6.4.4

### ISSUE THREAD

**Issue by jkleinerman** [dashingsoft/pyarmor#421]
I have experienced segmentation fault with python 3.9. I tested and saw the issue in the following versions of Pyarmor: 6.5.6, 6.5.5 and 6.4.4.
Of course the obfuscation and running is done using the same python version  (3.9)
With python 3.8, it seems to be working fine.
The issue is a little random. Sometimes it doesn't appears.
I saw the same issue in two platforms: x86_64 and arm32v7 (RPI 3)

**Comment by jondy** [comment]
How about obfuscating a simple script `foo.py` with only one line `print("Hello")`, and run it? segmentation fault or not.

**Comment by jkleinerman** [comment]
I have just tested a simple script foo.py with print("Hello") on python 3.9.1 and pyarmor 6.5.6.
No segmentation fault
My code is much more complicated. It uses threads, sockets, inter process communication libraries etc.
My project runs two application. One of them is a server running on a x86_64 architecture and the other, is the client running in an arm32v7 (RPI3).
Since I updated to python 3.9 I started to see this problem.
 In the server, since I have big files, for licences reasons, I'm not obfuscating all the directory.
I'm obfuscation doing:

pyarmor obfuscate  --exact main.py
pyarmor obfuscate  --no-runtime --exact purgeevents.py
pyarmor obfuscate  --no-runtime --no-bootstrap --exact crudresndr.py
pyarmor obfuscate  --no-runtime --no-bootstrap --exact ctrllermsger.py
pyarmor obfuscate  --no-runtime --no-bootstrap --exact lifechecker.py
pyarmor obfuscate  --no-runtime --no-bootstrap --exact msgheaders.py
pyarmor obfuscate  --no-runtime --no-bootstrap --exact msgreceiver.py
pyarmor obfuscate  --no-runtime --no-bootstrap --exact network.py
pyarmor obfuscate  --no-runtime --no-bootstrap --exact rtevent.py

In the client I'm obfuscating in the common way:

pyarmor obfuscate main.py inside the directory with all the .py files.

Let me know if you need any extra information

Thanks

**Comment by jkleinerman** [comment]
It's important to tell you that the segmentation fault may not appear under certain execution scenarios.

**Comment by jondy** [comment]
It's better to provide a simple snapshot code which will be segmentation fault, it's more complicated to find the problem if I can't reproduce this issue in my machine.

And try to obfuscate the scripts with super mode by option `--advanced 2`, does it crash or not?

**Comment by jkleinerman** [comment]
I will try to isolate a piece of code that generates the segmentation fault and I will send it to you
Also I will try option --advanced 2
Give me some time, I'm with a lot of work. I will try to have it ASAP

**Comment by jondy** [comment]
It's not easy to trace the bug by remote way. I'm doing a full test for Python 3.9, and module `asyncio` crashes, I'll first fix this and build a pre-release version.

**Comment by jkleinerman** [comment]
If you want I can test your pre release in my environment

Regards

-Jorge

**Comment by jkleinerman** [comment]
If you want, I can test your pre release in my environment

Regards

-Jorge

**Comment by jondy** [comment]
Well, that's what I think. But at first I need fix all the issues found in the full test, then I'll build a pre-release package, and show the download url here.

**Comment by jondy** [comment]
@jkleinerman 
I have fixed a crash issue for Python3.9, actually it's related to exception handler. Please download this pre-release package or install it by pip directly

https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.0.zip

Feel free to let me know if there is any issue

**Comment by jkleinerman** [comment]
Hey Jondy,

Could you tell me how I can install this pre-release with pip.
I tried using --pre option without success.

Regards

-Jorge

**Comment by jondy** [comment]
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.0.zip
```

**Comment by jkleinerman** [comment]
Hi Jondy,

I have just tested your last pre-release version 6.6.0 and it seems to
be working fine in my environment.
I run it in different scenarios, and at least there was no segmentation
fault
I will let you know if something happens.

Regards

-Jorge
