### ISSUE TITLE
Pyarmor does not run in lambda environment in AWS

### ISSUE THREAD

**Issue by prakashhiranandani** [dashingsoft/pyarmor#422]
Hey this tool is awesome, it works well on an ec2 and I was able to obfuscate all the code and make it work on the ec2.
But when I upload it to a Lambda function, it crashes with Runtime error.

<img width="1238" alt="Screen Shot 2020-12-29 at 8 35 41 AM" src="https://user-images.githubusercontent.com/917794/103299276-02350400-49b1-11eb-8e60-268a72c8be2b.png">

It crashes here on this line:

```
    init_module = prototype(('init_module', _pytransform))
    ret = init_module(major, minor, pythonapi._handle) 
```

This tool is really cool but when we upload to Lambda it just gave this issue I think the _pytransform.so is not working with the lambda image.

Also I tried via docker it works well, with the docker image for lambda: lambci/lambda:python3.7

**Comment by jondy** [comment]
How about obfuscating the scripts with feature `0` for lambda in AWS, for example,
```
pyarmor obfuscate --platform linux.x86_64.0 foo.py
```

**Comment by prakashhiranandani** [comment]
You rock man it worked like a charm!!!!

**Comment by prakashhiranandani** [comment]
Great tool!!!
