### ISSUE TITLE
关于加密时一些参数的提问

### ISSUE THREAD

**Issue by xingwenchao** [dashingsoft/pyarmor#423]
@jondy 你好，我看到文档中有关于obf-code和obf-mode的参数的配置，但是文档中对这两个参数只有一句描述，不是很理解这两个参数的含义。

--obf-mod <0,1,2> 是否加密整个模块对象
--obf-code <0,1,2>是否加密每一个函数
请问这两个参数是否有详细的描述或例子可以参考，以及这两个参数在性能方面的影响

**Comment by jondy** [comment]
`0` 就是不加密，非 `0` 是使用不同的加密算法，不加密的肯定比加密的性能要好，具体性能数据你可以使用 `pyarmor benchmark` 测试一下。

两个参数的含义请参阅文档中加密原理的说明，或者这个讲解加密原理的视频
https://v.youku.com/v_show/id_XNDk4NzAzOTg0MA==.html

**Comment by jondy** [comment]
加密模式的文档中也有对这两个参数的说明。

**Comment by xingwenchao** [comment]
好的

**Comment by xingwenchao** [comment]
通过设置--obf-mod 0 和--obf-code 0 后查看生成的文件，文件依然是加密的。请问obf-mode=0这个不加密是我理解的对整个文件(模块)不加密吗

**Comment by xingwenchao** [comment]
此问题已经得到解决
