### ISSUE TITLE
error: NameError: name '__pyarmor__' is not defined

### ISSUE THREAD

**Issue by amtsgv** [dashingsoft/pyarmor#424]
hello,  i am using "pyarmor pack -e " --onefile" myfile.py" and keep getting this error, i assume having the command do everything automatically i cant go wrong, so i don't know what i can do to fix this. thanks.
![image](https://user-images.githubusercontent.com/63860086/103466860-af14d580-4d51-11eb-8dfe-0c5ad754692a.png)

**Comment by jondy** [comment]
Refer to https://pyarmor.readthedocs.io/en/latest/questions.html#id1

**Comment by amtsgv** [comment]
okay, thanks for the response, i assume the issue is the os module, how do i make sure it's not obfuscated though?

**Comment by jondy** [comment]
Exclude the python system library path by option `--exclude`, for example, if there is a virtual python path `venv` in the current path, pack it by this way
```
pyarmor pack -x " --exclude venv" -e " --onefile" my file.py
```

**Comment by amtsgv** [comment]
Excluded C:\Users\username\AppData\Local\Programs\Python\Python38-32\Lib
and still had no luck. couldn't get the error message as the console instantly closes but i assume it is the same.

**Comment by jondy** [comment]
Please following this guide to fix the problem
https://pyarmor.readthedocs.io/en/latest/questions.html#the-final-bundle-does-not-work

**Comment by jondy** [comment]
The other solution is following this guide, it's more clear
https://pyarmor.readthedocs.io/en/latest/advanced.html#repack-pyinstaller-bundle-with-obfuscated-scripts

Please check the output log message carefully, make sure there is no `os` etc. system module replaced with obfuscated one.

**Comment by aviezab** [comment]
> -x " --exclude venv"

This is worked very well, but I think it is better to put it directly in here: https://pyarmor.readthedocs.io/en/latest/questions.html#id3
