### ISSUE TITLE
How to use obsfucated library project from obsfucated project?

### ISSUE THREAD

**Issue by davidwynter** [dashingsoft/pyarmor#426]
I went through the documentation and scanned the issues, closed and open to try to find how to achieve this.

I have 2 obsfucated projects, they both use 2 separate libraries I also developed.

It is not clear to me how the obsfucated libraries can expose the function names to the caller. When I obsfucated the libraries it looks like the original function names that would be called by my other projects are not defined in the obsfucated code. How do I leave the function entry points still accessible to my calling projects?

**Comment by jondy** [comment]
The obfuscated scripts are almost same as the original scripts, it can be used as if they're not obfuscated.

What's the exception raised when you import the function from the obfuscated scripts?

**Comment by davidwynter** [comment]
I abandoned that approach as it gets complex when you try to install the libraries inside your docket image during the build process. I decided to try the multiple packages obfuscation shown in the Advanced Topics section. But have run into an issue described below.

My projects are in this directory structure, not showing all utility and customer specific packages here:

projects
  I_product
    I_app
      I_ app.py
    |_runtime
      I_customer1
         I_run_cust1_schedule.py
      I_customer2
         I_run_cust2_schedule.py
      I_customer3
         I_run_cust3_schedule.py

  |_shell
    I_customer1
      build_customer1.sh
  |_library1
     I_library1
        I_ __init__.py
        I_package_1
          I_random_1.py
  |_library2
     I_library2
        I_ __init__.py
        I_package_a
          I_random_2.py

So instead of building the libraries and installing them I am attempting to bundle them inside the product application

My build_customer1.sh shell script look like this:

#!/usr/bin/env bash
source ~/anaconda3/etc/profile.d/conda.sh
conda activate myenv
rm -r ../../build_cust1
mkdir ../../build_cust1
cd ../../build_cust1
pyarmor init --src ../library1/library1 --entry __init__.py library1
pyarmor config --manifest "include library1/*.py, include library1/controller/*.py, include library1/util/*.py, \
prune build, prune config_files, prune dist, prune library1.egg-info, prune ini_files, prune notebooks, \
prune shell, prune deploy, prune testdata, prune venv, prune test"
pyarmor init --src ../library2/library2 --entry __init__.py library2
pyarmor config --manifest "include library2/*.py, include library2/controller/*.py, include library2/util/*.py, \
prune build, prune config_files, prune dist, prune library2.egg-info, prune ini_files, prune notebooks, \
prune shell, prune deploy, prune testdata, prune venv, prune test"
pyarmor init --src ../ --entry runtime/customer1/run_cust1_schedule.py product_cust1

pyarmor runtime --output dist
pyarmor build --output dist --no-runtime library1
pyarmor build --output dist --no-runtime library2
pyarmor build --output dist --no-runtime product_cust1

I have previously used individual shell scripts to build customer specific builds. e.g.

How do I get the pyarmor config entries to refer to the correct using pyarmor init output in each of the project and 2 libraries?

**Comment by jondy** [comment]
I think you can obfuscate all the `.py` files with super mode, for example,
```
cd projects
pyarmor obfuscate -r -O dist --advanced 2 ./
ls dist/
```
Then pick all the required files in the `dist` for different customers, for example, 
```
mkdir product_cust1
# Copy runtime module pytransform.so, the filename may be different in different platform
cp /path/to/projects/dist/pytransform.so product_cust1/

# Copy entry script
cp /path/to/projects/dist/app/app.py product_cust1/
cp /path/to/projects/dist/runtime/customer1/*.py product_cust1/

# Copy library1
cp /path/to/projects/dist/library1/library1 
...
```

**Comment by davidwynter** [comment]
The combination of ```pyarmor obsfucate -r -O dist --exclude lots_dir,more_dir advanced 2 ./``` controlled the macro level and the ```COPY ...``` commands in my dockerfile controlled at the customer specific builds.
But the file produce for the .so file was ```pytransform.cpython-37m-x86_64-linux-gnu.so``` so I copied that file to the dist directory. When I run the distributions I get:

```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/runtime/__init__.py", line 1, in <module>
    from pytransform import pyarmor
ModuleNotFoundError: No module named 'pytransform'
```
So it looks like it is not loading that .so file. Do I rename it?

**Comment by jondy** [comment]
Make sure this file `pytransform.cpython-37m-x86_64-linux-gnu.so` in any Python path, note that it's just a common Python extension, it can't be found if it's not in any python path.

**Comment by davidwynter** [comment]
I have the shared object file in LD_LIBRARY path, but it cannot find the so file?

```root@93b0e0f747c5:/# python3 -m app.runtime.cust1.run_schedule
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/__init__.py", line 1, in <module>
    from pytransform import pyarmor
ModuleNotFoundError: No module named 'pytransform'
root@93b0e0f747c5:/# echo $LD_LIBRARY_PATH
/app/runtime:
root@93b0e0f747c5:/# ls -l app/runtime
total 1120
drwxr-xr-x 2 root root    4096 Jan 13 18:17 cust1
-rw-rw-r-- 1 root root    1567 Jan 13 18:17 __init__.py
-rw-rw-r-- 1 root root 1132416 Jan 13 18:17 pytransform.cpython-37m-x86_64-linux-gnu.so
drwxr-xr-x 2 root root    4096 Jan 13 18:17 utils
```

**Comment by jondy** [comment]
You should set PYTHONPATH, not LD_LIBRARY_PATH.  For example,
```
PYTHONPATH=/app/runtime python3 -m app.runtime.cust1.run_schedule
```

**Comment by davidwynter** [comment]
Thank you now the docker CMD as follows works. 
```
CMD ["python3", "-m", "app.runtime.cust1.run_schedule"]
```

But if I enter the docker container running the bash shell and try this 

```
root@68961a62be88:/# PYTHONPATH=/app python3 -m app.runtime.cust1.run_cust1_file
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "</app/runtime/__init__.py>", line 2, in <module>
  File "<frozen etl.runtime>", line 3, in <module>
ImportError: cannot import name 'pyarmor_runtime' from 'app.pytransform' (/app/pytransform.cpython-37m-x86_64-linux-gnu.so)
```

Not clear what the difference would be between the docker container running the CMD and me running a similar command from the shell prompt.

**Comment by jondy** [comment]
`etl/runtime.py` is not obfuscated by super mode, because `pyarmor_runtime` is only for non-super mode. I suggest you first remove the whole `dist` path, then make a clean obfuscation.

**Comment by davidwynter** [comment]
I deleted everything under dist and ran my super mode again. All looks good. The dockerfile runs and produces a working docker image. But when I run the application I get the same error.

```
PYTHONPATH=/app python3 -m app.runtime.cust1.run_cust1_file
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "</app/runtime/__init__.py>", line 2, in <module>
  File "<frozen etl.runtime>", line 3, in <module>
ImportError: cannot import name 'pyarmor_runtime' from 'app.pytransform' (/app/pytransform.cpython-37m-x86_64-linux-gnu.so)
root@80465a0ae698:/# ls -l /app
total 1148
-rw-rw-r-- 1 root root     903 Jan 14 17:24 __init__.py
drwxr-xr-x 2 root root    4096 Jan 14 17:39 __pycache__
drwxr-xr-x 1 root root    4096 Jan 14 17:25 app
drwxr-xr-x 1 root root    4096 Jan 14 17:25 configfiles
drwxr-xr-x 2 root root    4096 Jan 14 17:25 errorfiles
drwxr-xr-x 5 root root    4096 Jan 14 17:25 library1
drwxr-xr-x 7 root root    4096 Jan 14 17:25 library2
drwxr-xr-x 2 root root    4096 Jan 14 17:25 logs
-rw-rw-r-- 1 root root 1132416 Jan 14 17:24 pytransform.cpython-37m-x86_64-linux-gnu.so
drwxr-xr-x 1 root root    4096 Jan 14 17:39 runtime
drwxr-xr-x 3 root root    4096 Jan 14 17:25 shell
```
Maybe it is a path issue?

```
root@80465a0ae698:/# ls -l app/app
total 16
drwxr-xr-x 2 root root 4096 Jan 14 17:25 core
drwxr-xr-x 3 root root 4096 Jan 14 17:25 customer
drwxr-xr-x 2 root root 4096 Jan 14 17:25 etl
drwxr-xr-x 2 root root 4096 Jan 14 17:25 utils
```
To eliminate

The ```__init__.py``` and so file are there. Not sure what I can do next to get it to run?

**Comment by jondy** [comment]
It seems the scripts in the `app/app/etl` are obfuscated without option `--advanced 2`, but the others like `app/library1` are obfuscated with option `--advanced 2`. The former scripts (non-super mode) can't mixed with the latter (super mode), you must obfuscate all the scripts include `app/app/etl` with `--advanced 2`. 

If `etl` is a third-party package which has been obfuscated by pyarmor, don't obfuscate it again. And obfuscate your scripts with `--enable-suffix 1`, for example,
```
pyarmor obfuscate -r --advanced 2 --exclude app/app/etl ...
```

**Comment by jondy** [comment]
You need understand the obfuscated scripts are normal Python scripts, and `pytransform.cpython-37m-x86_64-linux-gnu.so` is a normal Python extension, so just fix the import issues as in normal Python scripts.

**Comment by davidwynter** [comment]
I have to re-arrange my directory structure so that the imports for what was previously 2 libraries installed packages but now become packages within the product. I am setting the PYTHONPATH correctly but am getting the failure to import pytransform. As far as I can see I am doing everything according to the instructions. I am not packaging into a docker image now to eliminate that variable.

Can you point out what is wrong with my layout, etl is the product name?

```
$ PYTHONPATH=home/david/work/etl/dist/etl python3 -m runtime.cust1.run_cust1_file
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/david/work/etl/dist/etl/runtime/__init__.py", line 1, in <module>
    from pytransform import pyarmor
ModuleNotFoundError: No module named 'pytransform'
```
Directory layout:
```
david@david-desktop:~/work/etl/dist/etl$ ls -l
total 1156
drwxrwxr-x  8 david david    4096 Jan 14 18:20 app
drwxrwxr-x  5 david david    4096 Jan 14 18:20 library1
drwxrwxr-x  4 david david    4096 Jan 14 18:20 library2
-rw-rw-r--  1 david david     903 Jan 14 18:20 __init__.py
-rw-rw-r--  1 david david   19095 Jan 14 18:20 package.py
drwxrwxr-x  2 david david    4096 Jan 15 10:03 __pycache__
-rw-rw-r--  1 david david 1132416 Jan 14 18:20 pytransform.cpython-37m-x86_64-linux-gnu.so
drwxrwxr-x 10 david david    4096 Jan 15 10:03 runtime
-rw-rw-r--  1 david david    3427 Jan 14 18:20 run_workflow.py
```
As you can see the shared object file and generate __init__/py are in the directory specified in the PYTHONPATH.

runtime ls -l:

```
david@david-desktop:~/work/etl/dist/etl$ ls -l runtime
total 36
drwxrwxr-x 2 david david 4096 Jan 14 18:20 cust1
drwxrwxr-x 2 david david 4096 Jan 14 18:20 cust2
-rw-rw-r-- 1 david david 1567 Jan 14 18:20 __init__.py
drwxrwxr-x 2 david david 4096 Jan 15 10:03 __pycache__
drwxrwxr-x 2 david david 4096 Jan 14 18:20 utils

```

**Comment by jondy** [comment]
I forget one thing, docker uses `musl` other than `glibc`, the scripts should be obfuscated with `--platform musl.x86_64` for docker.

**Comment by davidwynter** [comment]
I am no longer using docker to eliminate that from the equation. But having found the https://pyarmor.readthedocs.io/en/latest/advanced.html#distributing-obfuscated-package-with-pip I am switching to use this method so will close this issue
