### ISSUE TITLE
Prevent monkey patching by verifying co_code?

### ISSUE THREAD

**Issue by NoahCardoza** [dashingsoft/pyarmor#427]
A while ago I opened https://github.com/dashingsoft/pyarmor/issues/335.

While `assert_armored` is close, it only verifies that the function is obfuscated, which in this case being a part of the standard library, it isn't. While trying to figure this out, it occurred to me that this could be done by saving the bytecode stored in `co_code` and then running a check similar to `assert_armored` except on the `co_code`.

First off, it would have to be dynamically generated since different versions of python would generate different bytecode. However, I'm not exactly sure where to start. Could you point me in the right direction?

Another issue that crossed my mind, if ensuring that all the functions within said function are secure... which seems like it would being extremely complex.

My main concern it securely sending communications to my main server. I'm packaging my CA and client ssl certificates, but I've done testing, and it seems as if someone could just import and monkey patch urllib to catch the ssl context and communications before they leave the script.

Maybe there is something that already covers this case?

```py
import hashlib

def md5(x):
    print('exposed:', x)
    exit()

hashlib.md5 = md5
import armored
```

`exposed: the secret`

For security reasons, I don't want to point people in the right direction so this isn't THE case I'm worried about but I think you get my drift.

Proud to have officially bought a license about an hour ago!

Thanks,
Noah

**Comment by jondy** [comment]
Thank you for purchasing pyarmor license

I suggest you obfuscate the related system library for example, `hashlib`, `urllib` with restrict mode 4, 
```
pyarmor obfuscate -r --advanced 2 --restrict 4 -O dist/urllib /path/to/urllib/__init__.py
```

By restrict mode 4, others can't import obfuscated `hashlib` or `urllib` from plain scripts.

Then in your script check these packages by `assert_armored` to make sure they're obfuscated.

**Comment by NoahCardoza** [comment]
Thanks for the tips! I'll do some of my own research and close this for now. Thanks for the insight and great support!
