### ISSUE TITLE
How to use obfuscated package with pip

### ISSUE THREAD

**Issue by Rictus** [dashingsoft/pyarmor#428]
Hello,

Thank you for this wonderful library. Already bought a license.

I'm trying to obfuscate a failry simple library that looks like this : 

``` raw
.
└── mylib
    ├── mylib
    │   ├── __init__.py   
    │   └── main.py       
    └── setup.py
```

I have the following config file 
``` json
{
  "version": "2.0",
  "name": "my_lib",
  "title": "my_lib",
  "src": ".",
  "is_package": 1,
  "manifest": "global-include *",
  "entry": "setup.py",
  "output": "obf",
  "runtime_path": null,
  "restrict_mode": 1,
  "obf_code": 1,
  "obf_mod": 2,
  "wrap_mode": 1,
  "advanced_mode": 2,
  "bootstrap_code": 1,
  "cross_protection": 1,
  "plugins": null,
  "platform": null,
  "package_runtime": 1,
  "enable_suffix": 0,
  "license_file": null,
  "build_time": 1610051748.208017
}
```

I just run `pyarmor build` to obfuscate my package. Then I need to install my obfuscated lib with `python setup.py install`. 
It correctly install but once I try `python -c 'import mylib'` it complains because `ModuleNotFoundError: No module named 'pytransform'`.

I understand pytransform is required to deobfuscate and run my lib but how does it should work when the lib is installed with pip ?  Where the `pytransform.cpython-37m-x86_64-linux-gnu.so` should go ?

Also, what happens if I need to install multiple (different) obfuscated library with pip ?

Thank you for your help!

EDIT: Just found this link from your documentation https://pyarmor.readthedocs.io/en/latest/questions.html?highlight=pip%20#pyarmor-is-not-recognized-issue 

So pyarmor is needed to deobfuscate when we use PIP ?

**Comment by jondy** [comment]
Thank you for purchasing PyArmor license.

pyarmor is not required to run the obfuscated scripts, the link you mentioned is only for special case.

Please edit `setup.py` to add file `pytransform.cpython-37m-x86_64-linux-gnu.so` as package data file, for example,
```python
setup(...
    package_data={
        'mylib': [ 'pytransform.cpython-37m-x86_64-linux-gnu.so' ]
    }
    ...
)
```

If you need to install multiple (different) obfuscated library with pip, first obfuscate the scripts with `--enable-suffix`. For project, configure it like this
```
cd my lib
pyarmor config --enable-suffix 1
pyarmor build
```
It will generate a unique runtime file like this `pytransform_vax_00xxxx.cpython-37m-x86_64-linux-gnu.so`, so it will not conflict with others.

And in the `setup.py`, install it in the root path of Python System Library, not inside the package, so all the others package can import this unique runtime package. For example, 
```
setup(...
    data_files=[('.', '/path/to/pytransform_vax_00xxxx.cpython-37m-x86_64-linux-gnu.so')]
    ...
)
```
About the usage of package_data and data file, refer to 
https://packaging.python.org/guides/distributing-packages-using-setuptools

**Comment by jondy** [comment]
It's recommended to always set option `enable_suffix` when distributing the obfuscated package.

**Comment by Rictus** [comment]
Ok I understand how it works. However I'm getting 
```
ImportError: dynamic module does not define module export function (PyInit_pytransform_vax_001041)
```
What do you suggest?
For reference, I'm working in WSL in my windows laptop, hope it is not a problem.

**Comment by jondy** [comment]
How do you generate the runtime extension `pytransform_vax_001041.pyd`? 
Not that it doesn't work only by renaming `pytransform.pyd` to `pytransform_vax_001041.pyd`, it must be generated by pyarmor command with option `--enable-suffix 1`.

**Comment by Rictus** [comment]
My config file 
``` json
{
  "version": "2.0",
  "name": "mylib",
  "title": "mylib",
  "src": ".",
  "is_package": 1,
  "manifest": "global-include *, exclude .pyarmor_config",
  "entry": "setup.py",
  "output": "obf",
  "runtime_path": "./mylib/",
  "restrict_mode": 1,
  "obf_code": 1,
  "obf_mod": 2,
  "wrap_mode": 1,
  "advanced_mode": 2,
  "bootstrap_code": 1,
  "cross_protection": 1,
  "plugins": null,
  "platform": null,
  "package_runtime": 0,
  "enable_suffix": 1,
  "license_file": null,
  "build_time": 1610098376.4644134
}
```

My setup.py
``` py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from setuptools import setup, find_packages


setup(
    name="mylib",
    version="0.0.2",
    packages=find_packages(),
    package_data={
        '': ['*.so'],
    },
    include_package_data=True,
)
```
Obfuscate with `pyarmor build -B`  gives me the following dir structure 

``` raw
obf/
└── mylib
    ├── mylib
    │   ├── __init__.py
    │   ├── __pycache__
    │   │   ├── __init__.cpython-37.pyc
    │   │   └── config.cpython-37.pyc
    │   └── config.py
    ├── pytransform_vax_001041.cpython-37m-x86_64-linux-gnu.so
    └── setup.py
``` 

I get a .so instead of a .pyd, I think it is fine ?

**Comment by jondy** [comment]
Do not obfuscate `setup.py`, overwrite it with the original `setup.py`

**Comment by Rictus** [comment]
I'm closing this as I have successfully used pyarmor to create "pip-installable" obfuscated packages. 

I had to do some manual things to make this work : 
* copy setup.py (not obfuscated) to the right location inside the obfuscated package
* create a directory structure pytransform_vax_XXXXXX/platforms/linux/x86_64/ with some __init__.py files and move the .so file in the x86_64 directory
* edit setup.py files to include .so files in the distribution
