### ISSUE TITLE
About the spam

### ISSUE THREAD

**Issue by evrmji** [dashingsoft/pyarmor#43]
Hello, I recently received an email which was suspected to have been sent from you.

In my opinion. The wording of this email is likely to recommend the commercial license for a software. I think you may have crawled the Python developer's mailbox on GitHub and sent the email. I received the email which has a clear address pointing to your project and relates website pages. And the sender's address and the name of your project are highly coincident. The language expression of the email is similar to selling your software commercial license and encourages the recipient to try the relevant software.

Due to my operational errors, the key evidence (the email) was deleted, so now I have no valid evidence to prove your behavior. If this is indeed done by yours. Firstly, I condemn it. And then, in my personality I think this behavior violates your ethics as a developer, harassing the developer, and disrupting the developer's development activities. I hope that you could send an apology letter to the users who were sent the email.

If it isn't done by you, I make a apologize here and apologize for what I had interfered the development activities and projects of yours.

I hope that you could be frank and honest with each other, which in order to create a better Internet and developer community environment. Best wish to you that the projects of yours will be developed better and better.

That would be all.

It seems that you are Chinese, and the following one is the Chinese version.

您好, 我最近收到疑似来自贵方发送的一封邮件.

这封邮件的措辞在我看来类似于推销软件商业用途许可. 我认为贵方可能爬取了 GitHub 上的 Python 开发者的邮箱, 并发送邮件. 我收到的邮件里面有明确的地址指向贵方的项目, 以及相关网页, 发件地址与贵方项目的名称高度重合. 语言表达类似于推销自己的软件商业许可, 并鼓励收件者试用相关软件. 

由于我的操作失误, 导致关键证据 (该邮件)被删除, 所以现在我没有有效证据证明贵方的行为. 如果此行为确实是贵方所为 ,我对此表示谴责, 并且我个人认为这种行为违反了贵方作为开发者的道德, 骚扰了开发者, 干扰了开发者的开发活动,  希望贵方可以对发送了该类邮件的用户发送道歉信.

如果不是贵方所为, 我在此提出道歉, 对干扰了贵方的开发行为以及项目表示道歉.

希望您可以坦诚相待, 以便塑造更良好的互联网和开发者社区环境. 同时祝愿您所开发的项目可以越来越好.

以上.

**Comment by jondy** [comment]
I have sent promotion email to some python developers in Github,  it's about ten days ago. I'm not sure if it's that you mentioned or not. Some people replay to me say that it's exactly that he need, some people say that it's not welcome. Anyway I have not sent this email several days ago. 

However I think many python developers must need a tool like pyarmor, I'll find other way to promote this project.

Thank for your replay.
