### ISSUE TITLE
授权注册码问题

### ISSUE THREAD

**Issue by nblog** [dashingsoft/pyarmor#431]
我购买了授权码后 注册后会绑定机器吗?
如果我有2台电脑 可以一起用吗?
还有一个问题就是 我重装系统会有影响吗?

**Comment by jondy** [comment]
授权码目前没有绑定到机器，可以装到多台机器，重装系统之后需要重新执行一下注册命令

关于 PyArmor 的最终用户使用协议的详情可以参考
https://pyarmor.readthedocs.io/zh/latest/license.html

**Comment by nblog** [comment]
感谢解惑 😄
