### ISSUE TITLE
ERROR    invalid syntax (<frozen Magic_Gen>, line 9)

### ISSUE THREAD

**Issue by JKKSI** [dashingsoft/pyarmor#432]
hello, i buy pyarmor and register the pyarmor correctly i guess, all my scripts run fine without any obfuscation, i tried to obfuscate some scripts with the pyarmor, and i'm getting those error (simillar error with all scripts)

C:\Users\Daishinkan\Downloads\pyarmor examples>pyarmor obfuscate Magic_Gen.py
INFO     PyArmor Version 6.6.0
INFO     Target platforms: Native
INFO     Source path is "C:\Users\Daishinkan\Downloads\pyarmor examples"
INFO     Entry scripts are ['Magic_Gen.py']
INFO     Use cached capsule C:\Users\Daishinkan\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying c:\python27\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Patch library dist\pytransform\_pytransform.dll
INFO     Patch library file OK
INFO     Copying c:\python27\lib\site-packages\pyarmor\pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            Magic_Gen.py -> dist\Magic_Gen.py
ERROR    invalid syntax (<frozen Magic_Gen>, line 9)

other script i get this error...

C:\Users\Daishinkan\Desktop\Beta>pyarmor obfuscate Destroyer.py
INFO     PyArmor Version 6.6.0
INFO     Target platforms: Native
INFO     Source path is "C:\Users\Daishinkan\Desktop\Beta"
INFO     Entry scripts are ['Destroyer.py']
INFO     Use cached capsule C:\Users\Daishinkan\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying c:\python27\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Patch library dist\pytransform\_pytransform.dll
INFO     Patch library file OK
INFO     Copying c:\python27\lib\site-packages\pyarmor\pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            Destroyer.py -> dist\Destroyer.py
ERROR    invalid syntax (<frozen Destroyer>, line 51)

**Comment by jondy** [comment]
I guess there are non-ascii characters in these lines, try to add source encoding line at the beginning of the script, refer to
https://docs.python.org/2.7/tutorial/interpreter.html#source-code-encoding

**Comment by JKKSI** [comment]
> I guess there are non-ascii characters in these lines, try to add source encoding line at the beginning of the script, refer to
> https://docs.python.org/2.7/tutorial/interpreter.html#source-code-encoding

Hello, in the first lines of my script Destroyer.py i have 

#!/usr/bin/env python3
#_*_ coding: utf8 _*_

, in a new script called "prueba.py" i have this next code...
#!/usr bin env python3
#_*_ coding: utf8 _*_
print("hola mundo")

and when i try to do "pyarmor obfuscate prueba.py" , i get this....

Microsoft Windows [Versión 10.0.18363.720]
(c) 2019 Microsoft Corporation. Todos los derechos reservados.

C:\Users\Daishinkan\Desktop\Beta>pyarmor obfuscate prueba.py
INFO     PyArmor Version 6.6.0
INFO     Target platforms: Native
INFO     Source path is "C:\Users\Daishinkan\Desktop\Beta"
INFO     Entry scripts are ['prueba.py']
INFO     Use cached capsule C:\Users\Daishinkan\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying c:\python27\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Patch library dist\pytransform\_pytransform.dll
INFO     Patch library file OK
INFO     Copying c:\python27\lib\site-packages\pyarmor\pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            Destroyer.py -> dist\Destroyer.py
ERROR    invalid syntax (<frozen Destroyer>, line 51)

C:\Users\Daishinkan\Desktop\Beta>cd dist

C:\Users\Daishinkan\Desktop\Beta\dist>py pr
C:\Program Files (x86)\Python38-32\python.exe: can't open file 'pr': [Errno 2] No such file or directory

C:\Users\Daishinkan\Desktop\Beta\dist>dir
 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 3481-7480

 Directorio de C:\Users\Daishinkan\Desktop\Beta\dist

13/01/2021  11:05 p. m.    <DIR>          .
13/01/2021  11:05 p. m.    <DIR>          ..
13/01/2021  11:05 p. m.    <DIR>          pytransform
               0 archivos              0 bytes
               3 dirs  238,310,510,592 bytes libres

C:\Users\Daishinkan\Desktop\Beta\dist>

**Comment by jondy** [comment]
Hi guy, please fix format error
```patch
- #_*_ coding: utf8 _*_
+ # -*- coding: utf-8 -*-
```

**Comment by JKKSI** [comment]
Hello, i change the Format how you tell me, i tried to obfuscate again in a new folder two scripts, and i get this...

C:\Users\Daishinkan\Desktop\Beta\pyarmortryone>pyarmor obfuscate --with-license licenses/r001/license.lic Destroyer.py
INFO     PyArmor Version 6.6.0
INFO     Target platforms: Native
INFO     Source path is "C:\Users\Daishinkan\Desktop\Beta\pyarmortryone"
INFO     Entry scripts are ['Destroyer.py']
INFO     Use cached capsule C:\Users\Daishinkan\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Generate license file from  licenses\r001\license.lic
INFO     Copying c:\python27\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Patch library dist\pytransform\_pytransform.dll
INFO     Patch library file OK
INFO     Copying c:\python27\lib\site-packages\pyarmor\pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            Destroyer.py -> dist\Destroyer.py
ERROR    invalid syntax (<frozen Destroyer>, line 51)

C:\Users\Daishinkan\Desktop\Beta\pyarmortryone>pyarmor obfuscate --with-license licenses/r001/license.lic Satelitte.py
INFO     PyArmor Version 6.6.0
INFO     Target platforms: Native
INFO     Source path is "C:\Users\Daishinkan\Desktop\Beta\pyarmortryone"
INFO     Entry scripts are ['Satelitte.py']
INFO     Use cached capsule C:\Users\Daishinkan\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Generate license file from  licenses\r001\license.lic
INFO     Copying c:\python27\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Patch library dist\pytransform\_pytransform.dll
INFO     Patch library file OK
INFO     Copying c:\python27\lib\site-packages\pyarmor\pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            Satelitte.py -> dist\Satelitte.py
INFO     Patch this entry script with protection code
ERROR    invalid syntax (<frozen Satelitte>, line 150)

C:\Users\Daishinkan\Desktop\Beta\pyarmortryone>

**Comment by JKKSI** [comment]
in line 150 in satellite.py the code is 
def getPage(page):
    # This is the prefixed Token
    global TOKEN
    if not args.save:
        print(Fore.WHITE + "[+] Target IP --> " + Fore.MAGENTA + str(page))
    else:
        # to keep the stdout clean
        print(Fore.GREEN + "[+] Target IP -->  " + Fore.CYAN + str(page), end='\r')

in Destroyer.py the line 51 is ....

try:
	if sys.platform.startswith("linux"):
		os.system("clear")
		print(Fore.LIGHTCYAN_EX)
		print(Fore.YELLOW+"[+] Se Recomienda poner Y cuando es la primera ves usando este script...")
		print(Fore.LIGHTGREEN_EX)
		op1 = input("[+] Instalar Herramientas Y/N -->: ")
		if op1 == ("Y"):
			try:
				os.system("cd /opt && git clone https://github.com/JKKSI/VIPER-X-Anonymous-Chaos.git") 
				os.system("cd /opt/VIPER-X-Anonymous-Chaos && sudo chmod +x ROX.sh && sudo bash ROX.sh") + print(Fore.RED+"[+] Se Ha Instalado Todo en --> cd /opt")
			except:
				print("[+] Ha Ocurrido un Error, puede que sea porque ya tiene todo instalado...")
				time.sleep(3)
				pass

**Comment by jondy** [comment]
It seems that your scripts work for Python3, but `pyarmor` is obfuscating your scripts with Python2.7.

Try to use python3 to compile and obfuscate the scripts, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-scripts-by-other-python-version

**Comment by jondy** [comment]
The other solution is to reinstall pyarmor with pip3, for example,
```
pip uninstall pyarmor
pip3 install pyarmor
pyarmor register your-register-file.txt
```

**Comment by JKKSI** [comment]
> The other solution is to reinstall pyarmor with pip3, for example,
> 
> ```
> pip uninstall pyarmor
> pip3 install pyarmor
> pyarmor register your-register-file.txt
> ```

Hello, this worked for me fine, but have a little question, if i put "pyarmor obfuscate --with-license licenses/r001/license.lic <my script> , this of course generate me obfuscated scripts in the folder dist, but my question is the next..., i just send the file encrypted and this will expire when the time done?, i mean if i create a licence with expired of 15/02/2021 for example , when time done, the script dont will work more?.

**Comment by jondy** [comment]
The obfuscated script will not work out of date, but it only checks local time. If you need check internet time, please use plugin `check_ntp_time`, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#using-plugin-to-extend-license-type

**Comment by JKKSI** [comment]
> The obfuscated script will not work out of date, but it only checks local time. If you need check internet time, please use plugin `check_ntp_time`, refer to
> https://pyarmor.readthedocs.io/en/latest/advanced.html#using-plugin-to-extend-license-type

ok, going to check it, thank you for your time and support 👍
