### ISSUE TITLE
Darwin Error

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#433]
The following error is being presented on a `MacBook Pro (16-inch, 2019)` running  `Catalina`

`Fatal Python error: _PyInterpreterState_Get(): no current thread state`

Using homebrew python 3.8.3

```
Python 3.8.3 (default, May 19 2020, 13:54:14) 
[Clang 10.0.0 ] on darwin
```

@jondy any thoughts on what is causing this?

**Comment by jondy** [comment]
If there is another Python3.8.3 installed in `/System/Library` or `/Library`, the core library of pyarmor `pytransform.cpython-38-darwin.so` will be linked to system python, other than home-brew python which locates `/usr/`.

Try to use command `install_name_tool` to modify the `rpath` of `pytransform.cpython-38-darwin.so`  to adapt this machine.

**Comment by VeNoMouS** [comment]
ok thanks i'll get the user to try
