### ISSUE TITLE
pyarmor obfuscation

### ISSUE THREAD

**Issue by JKKSI** [dashingsoft/pyarmor#435]
hello, i obfuscated already my file .py with pyarmor, all was going fine, but when i try to run it from linux (kali linux), i get this error ...

root💀kali)-[/home/kali/Desktop/Lightning_Destroyer]
└─# python3 Lightning_Destroyer.py 
Could not find "/home/kali/Desktop/Lightning_Destroyer/pytransform/platforms/linux/x86_64/_pytransform.so"

i sent the file to a friend for he try to execute my script and he get in linux same error, in windows he get this ....

C:\Users\barus\Desktop\Lightning_Destroyer>py Lightning_Destroyer.py
[WinError 193] %1 no es una aplicación Win32 válida

more in my windows the script run fine, why this happend ?

**Comment by jondy** [comment]
The obfuscated scripts are platform dependent, please use option `--platform` to obfuscate the scripts for different platforms, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#distributing-obfuscated-scripts-to-other-platform
https://pyarmor.readthedocs.io/en/latest/advanced.html#running-obfuscated-scripts-in-multiple-platforms

Note that the platform name of 32-windows is `windows.x86`, and 64-windows is `windows.x86_64`

**Comment by JKKSI** [comment]
Hello jondy, for obfuscate my script with all platforms is possible?, i mean for example pyarmor obfuscate --platform windows.x86_64.7 --platform linux.x86_64.7 --platform windows.x86.7 \ --platform linux.x86_64.7 --advanced 2 --with-license licenses/r001/license.lic Lightning_Destroyer.py (or something simillar) , can you give me maybe a command for obfuscate my script and this run in those platform that i select ? with the license

**Comment by jondy** [comment]
Please remove the feature number `.7`. For non-super mode, it's OK to build unique package for these platforms:
```
pyarmor obfuscate --platform windows.x86_64 --platform linux.x86_64 --platform windows.x86 --platform linux.x86 --with-license licenses/r001/license.lic Lightning_Destroyer.py
```
For super mode `--advanced 2`, it doesn't work because filenames conflicts. For example, the filename of runtime module is `pytransform.pyd` in `windows.x86` and `windows.x86_64`.

**Comment by JKKSI** [comment]
> pyarmor obfuscate --platform windows.x86_64 --platform linux.x86_64 --platform windows.x86 --platform linux.x86 --with-license licenses/r001/license.lic Lightning_Destroyer.py

thank you sir, a question more, is sufficient encryption only "obfuscate" mode with pyarmor?, i mean is possible someone decrypt my file ?, or you recommend me a better command to add how for example --advanced 1 , what do you recommend me for better encrypt?

**Comment by JKKSI** [comment]
> > pyarmor obfuscate --platform windows.x86_64 --platform linux.x86_64 --platform windows.x86 --platform linux.x86 --with-license licenses/r001/license.lic Lightning_Destroyer.py
> 
> thank you sir, a question more, is sufficient encryption only "obfuscate" mode with pyarmor?, i mean is possible someone decrypt my file ?, or you recommend me a better command to add how for example --advanced 1 , what do you recommend me for better encrypt?

or would be sufficient with obfuscate only ?

**Comment by jondy** [comment]
It's better with `--advanced 1`, and it's more security with super mode (`--advanced 2`).

**Comment by JKKSI** [comment]
> It's better with `--advanced 1`, and it's more security with super mode (`--advanced 2`).

ok , i used the command ### pyarmor obfuscate --platform windows.x86 --platform linux.x86_64 --with-license licenses/r001/license.lic --plugin check_ntp_time --advanced 1 Lightning_Destroyer.py

seems work fine for my windows and Linux, i Tried to use --advanced 2, but in linux dont work, say error from pytransform import pyarmor , but in windows work fine, so then i used --advanced 1, my error got for a bug i guess?

**Comment by jondy** [comment]
I have fixed filename conflict issue for multiple platforms in super mode, please install this pre-release version
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.1.zip
```

Then obfuscate the scripts with multiple platforms in super mode

**Comment by JKKSI** [comment]
> I have fixed filename conflict issue for multiple platforms in super mode, please install this pre-release version
> 
> ```
> pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.1.zip
> ```
> 
> Then obfuscate the scripts with multiple platforms in super mode

Hello, i installed this succefully, but have a little question, --advanced 2 is the best ofuscation of pyarmor?

**Comment by jondy** [comment]
Yes, `--advanced 2` is the best solution of Pyarmor at this time.

**Comment by JKKSI** [comment]
> Yes, `--advanced 2` is the best solution of Pyarmor at this time.

and would what whappend if me do --advanced 3 or --advanced 4?, this would be better ?, or is better --advanced 2?

**Comment by jondy** [comment]
`--advanced 3 or 4` uses vm protection, so it's more security and more difficult for reverse engineer, but it reduces the performance too much, and now only works in Windows.

**Comment by JKKSI** [comment]
> `--advanced 3 or 4` uses vm protection, so it's more security and more difficult for reverse engineer, but it reduces the performance too much, and now only works in Windows.

oh, ok, then now i would use --advanced 2, thank you for your support :), if i have any other question will tell you, and thanks for your time for answer me.
