### ISSUE TITLE
Exception: access violation reading

### ISSUE THREAD

**Issue by savage-eagle** [dashingsoft/pyarmor#436]
Hello, I'm packing a whole project with `pyarmor pack -e " --hidden-import=pkg_resources.py2_warn --onefile -c --icon gui/icon.ico --add-data 'gui;gui'" --name "Test" -x " --advanced 1" main.py` and when opens the generated file returns exception: access violation reading 0x00000000000000

Any ideas?

**Comment by jondy** [comment]
How about `-x " --advanced 2"`?

**Comment by savage-eagle** [comment]
By changing to `advanced 2` it works but many functions stop working. Don't know why.

**Comment by jondy** [comment]
Try to remove all the obfuscated files, and the build path `build` in the current path, then make a clean build.

**Comment by savage-eagle** [comment]
Already did that. 

Restarted the computer, deleted build folder.

**Comment by jondy** [comment]
Try to use helper script `repack.py` to build the bundle, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#repack-pyinstaller-bundle-with-obfuscated-scripts

Make sure each step works, it's more easy to find the problem.

**Comment by savage-eagle** [comment]
How I can use `repack.py` with recursive mode?

**Comment by jondy** [comment]
It will deal with all the obfuscated scripts recursively by default.

**Comment by savage-eagle** [comment]
In that link don't mentions how I could obfuscate folders as well. It should obfuscate `main.py` and three folders and with all their content. How I could do that?

**Comment by jondy** [comment]
Please refer to man page `obfuscate`
https://pyarmor.readthedocs.io/en/latest/man.html#obfuscate

**Comment by savage-eagle** [comment]
I gaved up to try understand, and downloaded Python 3.8.2 and PyArmor 6.3.7 and it was fixed the issue.
