### ISSUE TITLE
Check license failed: Invalid input packet

### ISSUE THREAD

**Issue by joonis** [dashingsoft/pyarmor#437]
Just updated pyarmor from v5.9.1 to v6.6.0.
Now when executing an obfuscated Python package I get the message:
_Check license failed: Invalid input packet._

There is no _license.lic_ nor _pytransform.key_ in the runtime folder.
I tried to copy these files manually from _pyarmor-regfile-1.zip_ without success, the error persists.

Any suggestions?

**Comment by jondy** [comment]
Please first check this link
https://pyarmor.readthedocs.io/en/latest/change-logs.html#incompatible-issues

And change logs of v6.3.0
https://pyarmor.readthedocs.io/en/latest/change-logs.html#id21

**Comment by joonis** [comment]
I get this error with completely new obfuscated scripts.
This is what I'm doing:
```
pyarmor register /path/to/pyarmor/pyarmor-regfile-1.zip
```
```
pyarmor init --src=/path/to/mypackage --entry=mypackage/__init__.py /build/path
```
```
pyarmor config
    --is-package=1
    --advanced-mode=0
    --obf-code=1
    --wrap-mode=1
    --obf-mod=1
    --restrict-mode=0
    --cross-protection=1
    --package-runtime=1
    --bootstrap=3
    --manifest=global-include *.py
    --output=/build/path/dist
    /build/path
```
```
pyarmor build --force /build/path
```
But finally there are no license files in `/build/path/dist/mypackage/pytransform`.

**Comment by joonis** [comment]
Ok, I missed that the license files are not longer required, right?
But there is still the error: _Check license failed: Invalid input packet._

**Comment by jondy** [comment]
If you prefer to use outer license like before, configure the project with outer license, `pyarmor config --with-license outer xxx`, refer to https://pyarmor.readthedocs.io/en/latest/advanced.html#how-to-use-outer-license-file

Does it work to obfuscate a simple script and run it?

**Comment by joonis** [comment]
Ok, I see. The binaries are patched with the license data.
I copied the raw binaries by myself, so it could not work...

One last question:
`Multi platforms conflict, platform freebsd.x86_64.0 could not mixed with linux.x86_64.7`
Why isn't it possiple to mix platforms with different feature numbers?

**Comment by jondy** [comment]
Because different features use different algorithm to obfuscate the scripts, so it's impossible to mix different features.
