### ISSUE TITLE
No module named 'pytransform' When using super mode

### ISSUE THREAD

**Issue by bashar-ait** [dashingsoft/pyarmor#438]
I'm trying to obfuscate a django project using the highest possible security options when im trying to use super mode i get
` ModuleNotFoundError: No module named 'pytransform'`
the command im using

`pyarmor obfuscate --advanced 2 --src="." -r --output=/var/www/django main/wsgi.py`

without `--advanced 2` option it works fine, but im trying to increase the code security and make it even harder to reverse.
Im working on armv7l arch

**Comment by jokeman332** [comment]
add python at system path.

**Comment by jondy** [comment]
First make sure the extension `pytransform` in any Python path, then make sure it's right for this platform. For example, for docker, the platform is `musl.x86_64`.

**Comment by bashar-ait** [comment]
Thanks guys. 
Changing the name of the generated pytransform fixed it.
Changed it from 
`pytransform.cpython-37m-arm-linux-gnu.so` to `pytransform.so`

I got another question will using the super mode affect the performance of the django app? and any other tips to increase the security of it before sharing it with other users?

**Comment by jondy** [comment]
The performance of super mode is almost same as the non-super mode's.

Refer to
https://pyarmor.readthedocs.io/en/latest/usage.html#improving-security-further

**Comment by bashar-ait** [comment]
Thank you! will take a look :)
