### ISSUE TITLE
Loading _pytransform.so failed

### ISSUE THREAD

**Issue by sureshpulsars** [dashingsoft/pyarmor#44]
i am try obfuscate my python script in raspberry pi but i had facing the below issue
**Load /home/pi/.local/lib/python3.5/site-packages/pyarmor/platforms/linux32/_pytransform.so failed:
/home/pi/.local/lib/python3.5/site-packages/pyarmor/platforms/linux32/_pytransform.so: cannot open shared object file: No such file or directory**
pyarmor version is 4.5.4

**Comment by jondy** [comment]
Please download `_pytransform.so` from

http://pyarmor.dashingsoft.com/downloads/platforms/raspberrypi/_pytransform.so

And save as `home/pi/.local/lib/python3.5/site-packages/pyarmor/_pytransform.so`

**Comment by Eastkap** [comment]
Had to redo this today with Python3.7
