### ISSUE TITLE
problem with popen

### ISSUE THREAD

**Issue by rmrmg** [dashingsoft/pyarmor#440]
I have two kinds of entry points:
normal_script.py and popen_starter.py

`#simplified idea of popen_starter.py`
`import sys, subprocess`
`args = ['python3'] + sys.argv[1:]`
`child = subprocess.Popen(args)`

after obfuscation of whole project with
pyarmor init --entry="normal_script.py,popen_starter.py"  --src="." 
pyarmor config --manifest "global-include *.py, prune dist, prune obfuscated_version, prune pytransform" 
pyarmor build --force
I cannot run obfuscated script using obfuscated script, id est:
`python popen_start.py normal_script.py `
when both are obfuscated does not work and not return any error msg (in docker I have "exited with code 0"). However when both are normal (plain-text) scripts everything is fine. 
There is no error message so I have no clue what's going on. Is this bug or it is intentionally not allowed?

**Comment by jondy** [comment]
For docker, the scripts need to be obfuscated with option `--platform musl.x86_64`.

**Comment by rmrmg** [comment]
@jondy: ok with add this but I have the same problem also without docker

**Comment by jondy** [comment]
It seems `Popen` uses Python3 to run the scripts obfuscated by Python2, it doesn't work. Refer to
http://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts

**Comment by rmrmg** [comment]
Not exactly in docker container indeed python refers to python2.7 but the same problem I have on host (in conda env) with python 3.7.9. Pyarmor instaled in conda, pkg obfuskated in conda and finally run in conda and does not work. Any idea how to debug this?

**Comment by jondy** [comment]
The ruler is simple, all the Python version (major, minor) must be same when obfuscating and running the scripts. In the other word, if the scripts is obfuscated by Python2.7, the obfuscated scripts work only for Python 2.7. It seems there are different Python versions in your case.
