### ISSUE TITLE
File "importlib\resources.py", line 97, in open_binary

### ISSUE THREAD

**Issue by devlop7** [dashingsoft/pyarmor#441]
hello i used NordVPN-switcher lib into my secript

i use this command to do the script the script name is  nord_rand.py
pyarmor pack -e "-F -i sn.ico" nord_rand.py

when i run the exe i get this error message 

Traceback (most recent call last):
  File "importlib\resources.py", line 97, in open_binary
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\moh\\AppData\\Local\\Temp\\_MEI100042\\nordvpn_switcher\\NordVPN_options\\countrylist.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<dist\obf\nord_rand.py>", line 3, in <module>
  File "<frozen nord_rand>", line 20, in <module>
  File "<frozen nord_rand>", line 6, in __init__
  File "nordvpn_switcher\nordvpn_switch.py", line 212, in initialize_VPN
  File "importlib\resources.py", line 121, in open_text
  File "importlib\resources.py", line 111, in open_binary
FileNotFoundError: 'countrylist.txt' resource not found in 'nordvpn_switcher.NordVPN_options'
[2560] Failed to execute script nord_rand

note the script work when i run the py file

**Comment by jondy** [comment]
This problem is related to PyInstaller, please following this guide to fix this problem
https://pyarmor.readthedocs.io/en/latest/advanced.html#repack-pyinstaller-bundle-with-obfuscated-scripts

**Comment by devlop7** [comment]
i'm not able to do it can u explane it 
this is the code that i have it  only this 

from nordvpn_switcher import initialize_VPN, rotate_VPN, terminate_VPN


class nord_vpn_changer:
    def __init__(self):
        self.settings = initialize_VPN(stored_settings=1)

    def get_new_ip(self):
        # print('here')
        try:
            rotate_VPN(self.settings)
        except Exception as e:
            print(e)


nvp = nord_vpn_changer()
nvp.get_new_ip()

**Comment by jondy** [comment]
So could you pack your script (no obfuscation) by PyInstaller directly? And run the final executable successfully.

**Comment by devlop7** [comment]
it show me this error message 

Error loading Python DLL 'C:\Users\moh\Desktop\New folder\New folder\abo_ahm\build\nord_rand\python39.dll'.
LoadLibrary: The specified module could not be found.

**Comment by jondy** [comment]
Please report this issue in PyInstaller, I mainly deal with the issues related to pyarmor.

**Comment by devlop7** [comment]
it's work with me in pyinstaller with this line
pyinstaller --onefile --add-data=""C:\Users\moh\AppData\Local\Programs\Python\Python39\Lib\site-packages\nordvpn_switcher\NordVPN_options\countrylist.txt";nordvpn_switcher\NordVPN_options" nord_rand.py

so how can i do the same in pyarmor

**Comment by jondy** [comment]
Pass any PyInstaller options by `-e` in the command `pack'
