### ISSUE TITLE
Restrict modes 1 and or 4 for modules that expose classes

### ISSUE THREAD

**Issue by NoahCardoza** [dashingsoft/pyarmor#443]
According to the [docs](https://pyarmor.readthedocs.io/en/latest/mode.html#restrict-mode)
> There are 5 restrict mode, mode 2 and 3 are only for standalone scripts, mode 4 is mainly for obfuscated packages, mode 5 for both.

It would seem that the correct way to armor a module for distribution would be to set the `__init__.py` file with restrict mode 1 and set it as the entry script and then all the other files with restrict mode 4. Then handle validation of the license key in the `__init__.py` and if all checks out import the functions/classes you want to expose and wrap them so they can be called from outside.

This *almost* works. The issue is I'm mostly exposing classes. After importing the package, I am able to instantiate classes, but I'm unable to call any of their methods from outside.

I started creating a wrapper class like:

```py
class Shrinkwrap:
    @staticmethod
    def __wrap__(obj):
        return Shrinkwrap(obj)

    def __init__(self, node):
        self.__node__ = node

    def __call__(self, *args, **kwds):
        return self.__wrap__(self.__node__(*args, **kwds))

    def __getattr__(self, name: str):
        return self.__wrap__(getattr(self.__node__, name))

    def __dir__(self):
        return dir(self.__node__)
```

But this seemed a little excessive and I felt like I was going about it the wrong way so I returned to the docs.

I noticed that with restrict mode 1:
> the obfuscated scripts can’t be changed at all

Am I right in assuming that means it would be safe to set `__init__.py` to restrict mode 1 and all other scripts with functions/classes I want to be made public with mode 1 as well, but include the `--no-bootstrap`?

I figure without the:
```py
from .pytransform import pyarmor_runtime
pyarmor_runtime()
```

That would mean it's impossible to import them on their own, right? If so that means the wouldn't be accessible without the `__init__.py` called first, right?

Note: the licensing logic I mentioned is being armored with restrict mode 4 and then imported into the `__init__.py`. Which I think is the right way to do it.

Thanks for your help so far!

**Comment by jondy** [comment]
> Am I right in assuming that means it would be safe to set __init__.py to restrict mode 1 and all other scripts with functions/classes I want to be made public with mode 1 as well, but include the --no-bootstrap?

Yes. Set `__init__.py` and all the other public scripts to mode 1

> That would mean it's impossible to import them on their own, right? If so that means the wouldn't be accessible without the __init__.py called first, right?

I suggest you obfuscate the scripts with super mode `--advanced 2`, so you need not care about bootstrap code. 
Refer to https://pyarmor.readthedocs.io/en/latest/mode.html#super-mode

**Comment by NoahCardoza** [comment]
> I suggest you obfuscate the scripts with super mode --advanced 2, so you need not care about bootstrap code.

All my scripts? Just the one's with APIs I want to expose? Or only the private scripts?

**Comment by NoahCardoza** [comment]
I tried using `--advanced 2` on all the scripts, but I am faced with this error:

```
ModuleNotFoundError: No module named 'pytransform'
```

The issue I'd assume is because it's a module so it should be `from .pytransform import pyarmor` but when changing it I recived:
```
Traceback (most recent call last):
  File "dist/TestIAO/example.py", line 1, in <module>
    import harvester
  File "/Users/vulcan/projects/CaptchaHarvester/server/factory/dist/TestIAO/harvester/__init__.py", line 1, in <module>
    from .pytransform import pyarmor
ImportError: dlopen(/Users/vulcan/projects/CaptchaHarvester/server/factory/dist/TestIAO/harvester/pytransform.cpython-37m-darwin.so, 2): Library not loaded: @rpath/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Users/vulcan/projects/CaptchaHarvester/server/factory/dist/TestIAO/harvester/pytransform.cpython-37m-darwin.so
  Reason: image not found
```

Additionally, I liked how I could package multiple runtimes for different machines before using advanced mode, which `ERROR    Multiple platforms confilt with same extension name "pytransform.pyd"` seems to indicate with `--advanced 2` this isn't possible?

**Comment by NoahCardoza** [comment]
Re: Multiple platforms confilt

I just read up on https://github.com/dashingsoft/pyarmor/issues/435 and it sounds like you are looking into that? Great!

**Comment by NoahCardoza** [comment]
Re: ImportError

I found https://github.com/dashingsoft/pyarmor/issues/433. I tried linking the rpath to brew's installation with no luck.

```
install_name_tool -change @rpath/Frameworks/Python.framework/Versions/3.7/Python @rpath/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Python pytransform.so
```
But all I got was:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pytransform import pyarmor
ImportError: dlopen(/private/tmp/socket/dist/pytransform.so, 2): Symbol not found: _PyAsyncGen_Type
  Referenced from: /private/tmp/socket/dist/pytransform.so
  Expected in: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
 in /private/tmp/socket/dist/pytransform.so
```

I assume this is part of the issue:

```
> ls /System/Library/Frameworks/Python.framework/Versions 
2.3     2.5     2.6     2.7     Current
```

I use pyenv, but before that I had `3.7` installed via `brew`. If it's this complicated to get working on my own computer, I fear having to figure all these issues out on clients machines.

**Comment by NoahCardoza** [comment]
Re: Re: ImportError

I just found https://github.com/dashingsoft/pyarmor/issues/256 and tried the fix you suggested, but I received:

```
> install_name_tool -add_rpath /usr/local/opt/python pytransform.cpython-37m-darwin.so

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: pytransform.cpython-37m-darwin.so
(for architecture x86_64) option "-add_rpath /usr/local/opt/python" would duplicate path, file already has LC_RPATH for: /usr/local/opt/python
```

**Comment by jondy** [comment]
> Re: ImportError
> 
> I found #433. I tried linking the rpath to brew's installation with no luck.
> 
> ```
> install_name_tool -change @rpath/Frameworks/Python.framework/Versions/3.7/Python @rpath/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Python pytransform.so
> ```
> 
> But all I got was:
> 
> ```
> Traceback (most recent call last):
>   File "test.py", line 1, in <module>
>     from pytransform import pyarmor
> ImportError: dlopen(/private/tmp/socket/dist/pytransform.so, 2): Symbol not found: _PyAsyncGen_Type
>   Referenced from: /private/tmp/socket/dist/pytransform.so
>   Expected in: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
>  in /private/tmp/socket/dist/pytransform.so
> ```

Do you note this error message?
```
Expected in: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
```

It means `/private/tmp/socket/dist/pytransform.so` is linked to Python 2.7, but you're using Python3.7 to run the obfuscated scripts.

Make sure you understand the meaning of `rpath`, and check rpath by `stool -L pytransform.so`, change `rpath` by `install_name_tool` to adapt this machine.

The `rpath` of `pytransform.so` is configured for most of cases, it may not work only for a few special cases.

And you must know if the obfuscated scripts is obfuscated by Python3.7, it only work in Python3.7, not work in any other Python version.

**Comment by NoahCardoza** [comment]
> It means /private/tmp/socket/dist/pytransform.so is linked to Python 2.7, but you're using Python3.7 to run the obfuscated scripts.

I thought that might be the case, which is even weirder I don't have pyarmor installed for 2.7 and I specifically called `python3.7 path/to/pyarmor.py` when armoring the code...

**Comment by jondy** [comment]
Check the extension suffix for python3.7 in this machine
```
python3.7-config --extension-suffix
```
Try to rename extension suffix as it is, I guess it should be not `pytransform.so`

**Comment by NoahCardoza** [comment]
Not sure how I was messing it up yesterday, but I was able to get it to work. I think the trick was aliasing the commands to a path to make sure my env wasn't using different versions willy-nilly.

I hope this helps someone else!

```bash
# hard code the paths so we don't mix things up
> alias python3.7=/usr/local/opt/python@3.7/bin/python3.7
> alias python3.7-config=/usr/local/opt/python@3.7/bin/python3.7-config
# obfuscate the code
> python3.7 -m pyarmor.pyarmor obfuscate --advanced 2 --exact test.py
> cd dist
> python3.7 test.py                     
Traceback (most recent call last):
  File "/private/tmp/socket/dist/test.py", line 1, in <module>
    from pytransform import pyarmor
ModuleNotFoundError: No module named 'pytransform'
> mv pytransform.cpython-37m-darwin.so pytransform.so
> python3.7 test.py                                     
Traceback (most recent call last):
  File "/private/tmp/socket/dist/test.py", line 1, in <module>
    from pytransform import pyarmor
ImportError: dlopen(/private/tmp/socket/dist/pytransform.so, 2): Library not loaded: @rpath/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /private/tmp/socket/dist/pytransform.so
  Reason: image not found
> otool -L  pytransform.so
pytransform.so:
 pytransform.cpython-37m-darwin.so (compatibility version 0.0.0, current version 32.6.0)
 @rpath/Frameworks/Python.framework/Versions/3.7/Python (compatibility version 3.7.0, current version 3.7.0)
 /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
 /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1575.17.0)
 /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
 /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 946.0.0)
> ls @rpath/Frameworks/Python.framework/Versions/3.7       
ls: @rpath/Frameworks/Python.framework/Versions/3.7: No such file or directory
> python3.7-config --prefix
/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7
> install_name_tool -change @rpath/Frameworks/Python.framework/Versions/3.7/Python /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/Python pytransform.so 
> python3.7 test.py
```

**Comment by NoahCardoza** [comment]
One last thing, I think this is somewhat of a feature request (unless I'm just doing it wrong):

But if I module like:
```
/module/__init__.py
/module/submodule/__init__.py
```

And I armor it with:
```
python3.7 -m pyarmor.pyarmor obfuscate --advanced 2 --restrict 1 --recursive --output dist/module --src module __init__.py
```
_then follow the steps I did above_
I get an output like this:

```
/dist/module/__init__.py
/dist/module/pytransform.so
/dist/module/submodule/__init__.py
```

But if I import the module I get import errors because the armored code expects `pytransform.so` to be in the base directory. I could use sed to change all the imports to `from module.pytransform import pyarmor` but it would be nice if was a flag in pyarmor that indicated it was packaging a module.

**Comment by NoahCardoza** [comment]
I added this to the end of my build script for now:
```sh
mv harvester/pytransform*so harvester/pytransform.so
if [[ -z "${DEVELOPMENT}" ]]; then
  install_name_tool -change @rpath/Frameworks/Python.framework/Versions/3.7/Python /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/Python harvester/pytransform.so
if
find harvester -iname "*.py" -print0 | xargs -0 sed -i '' "s:from pytransform import pyarmor:from harvester.pytransform import pyarmor:"
```
But now I'm getting these errors:

```
ImportError: cannot import name 'HT_DOMAIN' from 'harvester.pytransform' (/Users/vulcan/projects/CaptchaHarvester/server/factory/dist/TestIAO/harvester/pytransform.so)
```

I'm assuming this means I'd still need to package the bootstrap code? Or include some prebuilt plugin?

**Comment by NoahCardoza** [comment]
I'm going to close this since it's going a little off topic and open a new issue regarding the differing API and possible "module" flag to bootstrap files with when using `--advanced 2`.

**Comment by NoahCardoza** [comment]
After a little testing, unfortunately, I was able to bypass the licensing by removing the `__init__.py` from `/harvester` and replace it with an empty one. Then I could just import anything from the other files by hand...

Without Super Mode this wasn't possible because each file wasn't importing `pytransform`  so if you didn't import the init script then this wasn't possible.

Do you have any advice to keep this from happening?

**Comment by jondy** [comment]
Use restrict mode 4, refer to
http://pyarmor.readthedocs.io/en/latest/mode.html#restrict-mode

**Comment by NoahCardoza** [comment]
The only issue with restrict mode 4 is the fact that it gets messy when exposing classes because the methods throw errors when called because they aren't being called from an armored script.

Is there any way to ensure the entry point is armored and the module is being imported from an armored script but allow the function callers to not be armored?

**Comment by jondy** [comment]
It seems that it meets the conditions of pyarmor restrict mode if helper script is obfuscated by restrict mode 1.

**Comment by NoahCardoza** [comment]
That's exactly what I did. So far it's worked like a charm.

Thanks for all the help!
