### ISSUE TITLE
Unknown opcode when using numpy

### ISSUE THREAD

**Issue by rspena** [dashingsoft/pyarmor#444]
If I use numpy my script throughs the following error:

```
Traceback (most recent call last):
  File "<frozen logic.logic_debug>", line 49, in __init__
TypeError: bad operand type for unary -: 'dict'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 320, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/opt/project/webapp/resources/base.py", line 40, in on_get
    math_data = self.start_app()
  File "/opt/project/webapp/resources/app.py", line 202, in start_app
    self.params., None, self.view, self.num, self.parameters
  File "/opt/project/webapp/resources/base.py", line 81, in start_app
    result = logic_debug_module.app(*args)
  File "<frozen logic.logic_debug>", line 85, in __init__
AttributeError: __enter__
```

**NOTE:**
- It only happens sometimes
- The same script without PyArmor runs fine
- I have other scripts (very similar) running in the same environment with PyAmor but without numpy and they run fine

**Comment by jondy** [comment]
If the obfuscated scripts are obfuscated by restrict mode > 3, try to obfuscate them with restrict mode 1. 

Or make sure your scripts are adapted to restrict mode > 3.

**Comment by rspena** [comment]
Thank you for the quick feedback. I'll check and comeback to you asap.

**Comment by rspena** [comment]
I'm using pyarmor project with the default config:

{
  "version": "2.0",
  "name": "build",
  "title": "build",
  "src": "../logic",
  "is_package": null,
  "manifest": "global-include *.py",
  "entry": "__init__.py,logic.py, logic_debug.py, decoder.py",
  "output": "logic",
  "runtime_path": null,
  "restrict_mode": 1,
  "obf_code": 1,
  "obf_mod": 2,
  "wrap_mode": 1,
  "advanced_mode": 0,
  "bootstrap_code": 1,
  "cross_protection": 1,
  "plugins": null,
  "platform": null,
  "package_runtime": 1,
  "enable_suffix": 0,
  "license_file": null,
  "build_time": 0.0
}

**Comment by jondy** [comment]
Check the code near line 49 and 85 in the `logic/logic_debug/__init__.py`, make sure it doesn't visit `co.co_code` or use `inspect` to visit the code object.

**Comment by rspena** [comment]
No, nothing. I've completely reviewed the code, refactored the re-initialisation of an object calling "self.__init__()" dynamically, the only thing out or the ordinary.
The error only happens while using PyArmor... the diference from this script to others running in the same tests is "numpy".  Any clues?

`
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 320, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/opt/project/webapp/resources/base.py", line 40, in on_get
    math_data = self.start_app()
  File "/opt/project/webapp/resources/app.py", line 199, in start_app
    self.bets, self.parameters
  File "/opt/project/webapp/resources/base.py", line 89, in start_app
    result = logic_module.App(*args)
  File "<frozen logic.logic>", line 62, in __init__
SystemError: unknown opcode`

**Comment by jondy** [comment]
First make sure there is no third-party package which is also obfuscated by pyarmor. It may conflict with your obfuscated scripts.

Second make sure all the scripts are obfuscated by same command. For example, if some scripts are obfuscated by old version pyarmor, some by latest version. Note that `pyarmor build` only obfuscates the modified scripts since last build.

If still doesn't work, try to obfuscate the scripts with `--advanced 2`.

**Comment by rspena** [comment]
No 3rd party packages, only the scripts. I have a gitlab pipeline triggering the build every time a new commit is made so the files are always obfuscated by same command and with the same version. I've update the image with the last version of pyarmor but because I'm using Alpine I'm copying the "**SO**" from  
http://pyarmor.dashingsoft.com/downloads/latest/alpine/_pytransform.so and replacing. (Can this build be out of date?)

If I don't do this I get this error, every time I try to run the build:
`ERROR    Error relocating /usr/lib/python3.7/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so: __snprintf_chk: symbol not found`

I tried adding the flag --advanced 2 to the "pyarmor config" command but now I get the following error when I try to pyarmor build:

`ERROR    No available dynamic library for linux.x86_64.8.py37 with features ['8']`

**Comment by jondy** [comment]
The `_pytransform.so` of obfuscated scripts is platform dependent, and Alpine is different platform from general Linux, for example, ubuntu.

If you run obfuscated scripts in Docker, obfuscate it with option `--platform musl.x86_64`. Do not copy the download file to `dist` path directly, it doesn't work.

**Comment by chwba** [comment]
Pyarmor seems to be incompatible with numpy. If obfuscating numpy with python 3.9.1 the obfuscated script does not start with:

```
  File "<frozen python.numpy.core.overrides>", line 208, in decorator
  File "<frozen python.numpy.core.overrides>", line 179, in decorator
TypeError: add_docstring() argument 2 must be str, not None
```

**Comment by jondy** [comment]
@chwba 
Check the source line 178 in `numpy.core.overrides`, patch it like this
```patch
         try:
             if docs_from_dispatcher:
-                 add_docstring(implementation, dispatcher.__doc__)
+                 add_docstring(implementation, '' if dispatcher.__doc__ is None else dispatcher.__doc__)
         except:
             pass
```

**Comment by rspena** [comment]
> The `_pytransform.so` of obfuscated scripts is platform dependent, and Alpine is different platform from general Linux, for example, ubuntu.
> 
> If you run obfuscated scripts in Docker, obfuscate it with option `--platform musl.x86_64`. Do not copy the download file to `dist` path directly, it doesn't work.

Sorry for my bad English, I think I wasn't clear. I have to copy the file because if I install PyAmor with **pip install pyarmor** it won't run. It will throw the follwoing error:

`ERROR Error relocating /usr/lib/python3.7/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so: __snprintf_chk: symbol not found`

I've used this image to obfuscate other scripts without an issue but if I add the flag "--advanced 2" it will throw:

`ERROR No available dynamic library for linux.x86_64.8.py37 with features ['8']`

I'm wondering if the available SO to download for Alpine is out of date?

**Comment by jondy** [comment]
I think this is the right one for Alpine Linux in Pyarmor v6.6.0
https://github.com/dashingsoft/pyarmor-core/raw/r39.13/platforms/musl.x86_64.7/_pytransform.so

Each pyarmor version has its corresponding core library, download the latest version may not work for different pyarmor version
