### ISSUE TITLE
ModuleNotFoundError: No module named 'pytransform' after executing executable file .exe

### ISSUE THREAD

**Issue by mayank564** [dashingsoft/pyarmor#445]
Below is the our project structure,

![project](https://user-images.githubusercontent.com/77481730/105222189-2636d000-5b80-11eb-8cca-c454270cdd4d.jpg)

Our objective is to obfuscate the whole project and run pyinstaller command to wrap and finally we are bundling the files to obtain the EXE from running pyinstaller command against a spec file.

To achieve the first objective I’m following the below commands:

1. `pyarmor obfuscate --recursive --output C:\Test_Branch\ese\dist/obf/dreamcatcher/lib/pyDreamCatcher C:\Test_Branch\ese\dreamcatcher\lib\pyDreamCatcher`
2. `pyarmor obfuscate --recursive --output C:\Test_Branch\ese\dist/obf/dreamcatcher/libexec/ese C:\Test_Branch\ese\dreamcatcher\libexec\ese\__main__.py`
From these two Code is getting obfuscated successfully.

To achieve the second objective we wrap around the code using the custom .spec file:
`pyinstaller -y --clean pyinstaller_main.spec`

By this command i am able to make the installer file i.e "test.exe" but when i run this .exe (execute it) i get the following error:

> Traceback (most recent call last):
>   File "dreamcatcher\libexec\ese\__main__.py", line 1, in <module>
> ModuleNotFoundError: No module named 'pytransform'
> [29100] Failed to execute script __main__
> [29100] LOADER: OK.
> [29100] LOADER: Cleaning up Python interpreter.

I have seen other issues same as mine but was not able to deduce anything out of it any suggestions for the above error is welcomed.
Thanks in Advance !!

**Comment by jondy** [comment]
Please following this `repack` guide, do not custom `.spec` for pyarmor, `repack.py` will do everything related to pyarmor
http://pyarmor.readthedocs.io/en/latest/advanced.html#repack-pyinstaller-bundle-with-obfuscated-scripts

**Comment by mayank564** [comment]
Hi @jondy  ,

I have followed the link shared by you still i get some error.
My obfuscated scripts are in the folder : C:\Test_Branch\ese\dist\obf\dreamcatcher
And my installer file is created in the folder :  C:\Test_Branch\ese\dist\ese\ese.exe

I have successfully created the  ".exe" file from my spec file without any changes and it was running fine.
While repacking i get this error 
Command : 

> python repack.py -p C:\ESE-2491_lockbox\ese\dist\obf\dreamcatcher C:\ESE-2491_lockbox\ese\dist\ese\ese.exe

Error : 

> 1102 INFO: Repack PyInstaller bundle "C:\ESE-2491_lockbox\ese\dist\ese\ese.exe"
> 1102 INFO: Obfuscated scripts in the path "C:\ESE-2491_lockbox\ese\dist\obf\dreamcatcher"
> 1107 INFO: Entry script name is "ese.py"
> 1111 ERROR: No obfuscated script "C:\ESE-2491_lockbox\ese\dist\obf\dreamcatcher\ese.py" found

I think by default it searches for ese.py file but in my project there is no such thing, inside dreamcatcher folder i have two other subfolders lib and libexec here i have all the files of the project.

Any suggestions here?

**Comment by jondy** [comment]
The obfuscated scripts in the ``obfdist`` must be in the same path as it in the
PyInstaller bundle. That is to say, the main script ``foo.py`` must be in the
``obfdist``. The option ``-d`` is used to print the archive information, copy
the obfuscated scripts according to its path in the archive. For example::

    python repack.py -d -p obfdist dist/foo.exe

**Comment by jondy** [comment]
If the structure of obfuscated scripts are changed, run the main script by Python directly, make sure it still works.
