### ISSUE TITLE
Super Mode's pytransform API differs from the original

### ISSUE THREAD

**Issue by NoahCardoza** [dashingsoft/pyarmor#446]
https://pyarmor.readthedocs.io/en/latest/pytransform.html

There could be more differences but I noticed that `HT_DOMAIN` is missing and while `HT_IPV6` doesn't seem to be in the docs, it was available when not using Super Mode.

Also,

```py
>>> get_hd_info(HT_IFMAC, 'en0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_hd_info() takes exactly one argument (2 given)
```

However I am on macOS which isn't mentioned when giving examples of the `name=` param.

Non of these are issues for me, just wanted to make sure they got documented to save other people time later (unless they were documented and I just glossed over them).

**Comment by jondy** [comment]
`HT_IPV6` is not implemented now.

On macOS, no named device are support, so `name` is not mentioned in the document. Actually `name` only works in the cases list in the document.

**Comment by NoahCardoza** [comment]
Not sure if you want to keep this open for the sake of `HT_IPV6` but that answers my question.

Thanks!
