### ISSUE TITLE
_pytransform.dylib incompatible in OSX 10.14

### ISSUE THREAD

**Issue by V-E-O** [dashingsoft/pyarmor#45]
Prebuilt _pytransform.dylib is not compatible with OSX 10.14.2:

% pyarmor
Load /usr/local/lib/python2.7/site-packages/pyarmor/platforms/darwin64/_pytransform.dylib failed:
dlopen(/usr/local/lib/python2.7/site-packages/pyarmor/platforms/darwin64/_pytransform.dylib, 6): no suitable image found.  Did find:
  /usr/local/lib/python2.7/site-packages/pyarmor/platforms/darwin64/_pytransform.dylib: malformed mach-o image: __TEXT segment maps start of file but is writable
  /usr/local/lib/python2.7/site-packages/pyarmor/platforms/darwin64/_pytransform.dylib: malformed mach-o image: __TEXT segment maps start of file but is writable

**Comment by jondy** [comment]
Try this one, just replace the old with it
http://pyarmor.dashingsoft.com/downloads/platforms/macosx_x86_64/_pytransform.dylib

**Comment by V-E-O** [comment]
fixed, thanks
