### ISSUE TITLE
Preserve specific function names

### ISSUE THREAD

**Issue by Dariusz1989** [dashingsoft/pyarmor#451]
Hey

I'm using this to generate a "plugin" for my app

```
            spec = importlib.util.spec_from_file_location(name, path)
            plugin = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(plugin)
            obj = plugin.generatePluginObject()
```
This will not run as generatePluginObject() does not exist on my obfuscated plugin.py files.

Is there a way to add a "exclude" function name to the obfuscator so that this name remains unchanged? I noticed that if I take a normal plugin.py file that is unobfuscated and replace the obfuscated one with it, then everything works. 
Ideally I'd like to add file+function name to exclude the list so I can specify whats what.

Tia

**Comment by jondy** [comment]
The module `__dict__` will be changed after `spec.loader.exec_module` but `plugin.__dict__` seems not changed, check it by this way
```patch
            spec = importlib.util.spec_from_file_location(name, path)
            plugin = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(plugin)
+          import sys
+          print(dir(plugin))
+          print(dir(sys.modules[plugin.__name__]))
+          plugin = sys.modules[plugin.__name__]
            obj = plugin.generatePluginObject()
```

**Comment by Dariusz1989** [comment]
> The module `__dict__` will be changed after `spec.loader.exec_module` but `plugin.__dict__` seems not changed, check it by this way
> 
> ```diff
>             spec = importlib.util.spec_from_file_location(name, path)
>             plugin = importlib.util.module_from_spec(spec)
>             spec.loader.exec_module(plugin)
> +          import sys
> +          print(dir(plugin))
> +          print(dir(sys.modules[plugin.__name__]))
> +          plugin = sys.modules[plugin.__name__]
>             obj = plugin.generatePluginObject()
> ```

Worked like a dream, thank you!
