### ISSUE TITLE
Linux pyarmor + pyinstaller Error / Issue

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#452]
Hi @jondy ,

Got a weird problem...

If I pack some code with pyarmor && pyarmor under linux i'm getting the following error when attempting to execute...

```python
ImportError: dynamic module does not define module export function (PyInit_pytransform_vax_0000xxxx)
```
Have tested via python 3.7 && 3.8

* pyarmor 6.6.0 
* pyinstaller 4.2

Have cleaned the runtime's to download again as well...

Works if only use pyinstaller.... 

....also works fine with pyarmor && pyinstaller under windows python 3.8

My pack cmd under linux is 

```
pyarmor pack --clean -x " --advanced 2 --enable-suffix" -e " --onefile" --name xxxx xxxx.py
```

Any thoughts?

# Update

I tested with just `--advanced 1` under linux and this works... so def looks like something to do with the runtime @jondy 

# Update 2

Got this working by removing `--enable-suffix`

**Comment by jondy** [comment]
> ImportError: dynamic module does not define module export function (PyInit_pytransform_vax_0000xxxx)

Generally rename the runtime core library `pytransform.xxx.so` to `pytransform_vax_xxx.so`, copy it to `dist` directly, may raise this exception. This binary library must be generated by one of pyarmor commands `obfuscate`, `build` or `runtime`, it will be patched by pyarmor.

**Comment by VeNoMouS** [comment]
@jondy as i said, this was all automated, via the given cmd, it works fine in windows, was failing in linux **till** i removed the `enable-suffix`

**Comment by jondy** [comment]
How about obfuscate a simple helloworld script with `--enable-suffix` in Linux? No pack, only obfuscate it.

**Comment by VeNoMouS** [comment]
Yea I can test, let me get my morning coffee

**Comment by jondy** [comment]
@VeNoMouS here it is pre-release package, it works for super mode with suffix in Linux, please check it
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.1.zip

**Comment by VeNoMouS** [comment]
Will do boss :) just fixnig a bunch of code on various projects , i will test out for you tonight :)

**Comment by VeNoMouS** [comment]
@jondy 

Tested it ..... waaah waaah... **Failed**

# Pack command
```
pyarmor pack --clean -x " --advanced 2 --bootstrap 2 --enable-suffix" -e " --onefile" --name xxxx xxxx.py
```

# Pyarmor Packing..
```
/usr/local/bin/python3.8 /usr/local/lib/python3.8/site-packages/pyarmor-6.6.1-py3.8.egg/pyarmor/pyarmor.py obfuscate -O dist/obf --package-runtime 0 -r --exclude dist --advanced 2 --bootstrap 2 --enable-suffix ./xxxx.py
```
# Execution
```
Traceback (most recent call last):
  File "dist/obf/xxxx.py", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_pytransform_vax_0000xx)
```

![image](https://user-images.githubusercontent.com/597545/106233987-aafaab80-625c-11eb-9efc-387c1de505d2.png)

**Comment by jondy** [comment]
@VeNoMouS 
Fixed it, and uploaded a new pre-release package in same location, check it according to your time

**Comment by VeNoMouS** [comment]
Rgr , thanks, , will test out in a bit and let you know, just in middle of other work

**Comment by VeNoMouS** [comment]
@jondy i went to test, but 404 on the file

**Comment by VeNoMouS** [comment]
at just saw you released it 13mins ago, apologies about the delay in testing
