### ISSUE TITLE
Unexpected _pytransform.dylib

### ISSUE THREAD

**Issue by tomlarge** [dashingsoft/pyarmor#453]
Hi,  I made an app using PyInstaller and Pyarmor.
But I have some issues.
my app is made in pyqt5 so it's a windowed.
the app instant close, when I run the console it shows me the error: filenotfound error: _pytransform.dylib
so I place it in the main directory. then I have this issue:
`[75018] Traceback: ['Traceback (most recent call last):\n', '  File "<app.py>", line 3, in <module>\n', '  File "<frozen app>", line 289, in <module>\n', '  File "<frozen app>", line 284, in protect_pytransform\n', '  File "<frozen app>", line 276, in check_lib_pytransform\n', 'RuntimeError: unexpected /Users/tomlarge/Desktop/app/Ruby-AIO/_pytransform.dylib\n']`

if someone can help me pls.

**Comment by jondy** [comment]
Try this guide to build pyarmord bundle with pyinstaller in MacOS
http://pyarmor.readthedocs.io/en/latest/advanced.html#repack-pyinstaller-bundle-with-obfuscated-scripts
