### ISSUE TITLE
Pyarmor webui GUI cannot display large amount of files or folders

### ISSUE THREAD

**Issue by chwba** [dashingsoft/pyarmor#454]
In the selection to exclude scripts, one cannot select more than the "current screen can display", there is a scroller but sadly everything, that is not being displayed is just not available.
![image](https://user-images.githubusercontent.com/22568014/105714393-9183f780-5f1c-11eb-85f4-5d3466b458c9.png)

**Comment by jondy** [comment]
Generally fill the exclude with some directory like `venv`, `test` etc.

If there're lot of `.py` files need not to obfuscated, do not list here. Just obfuscate them, then copy the original scripts to output path to overwrite them

**Comment by chwba** [comment]
I am aware of how it works, what I am pointing out here is that your GUI has a bug.

**Comment by jondy** [comment]
Got it, thanks.
