### ISSUE TITLE
PyArmor -> Library incompatibility list

### ISSUE THREAD

**Issue by chwba** [dashingsoft/pyarmor#455]
numpy
pycparser
cffi
multiprocess

**Comment by jondy** [comment]
There are countless big packages in Python world, I also can't test each package to make sure it's compatitable with pyarmor.

I have list all the differences of obfuscated scripts in the document, if any package violates these rulers, it will not work with pyarmor. For example, use `inspect` to visit co_code of code objects is invalid for obfuscated scripts.

http://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts

It's also not easy for me to research a complex package to find which line conflicts with pyarmor, and it's difficult for me to run all of these complex packages in my local machine.

Generally in this case users provide the simple snapshot code around exception, or some running information, I analysis them to find where it may confilct with pyarmor and try to find the solution.

For example, NumPy raises this exception
```
   File "<frozen python.numpy.core.multiarray>", line 144, in <module>
   File "<frozen python.numpy.core.overrides>", line 207, in decorator
   File "<frozen python.numpy.core.overrides>", line 178, in decorator
 TypeError: add_docstring() argument 2 must be str, not None
```

Check the source line 178 in `numpy.core.overrides`, patch it like this
```patch
         try:
             if docs_from_dispatcher:
-                 add_docstring(implementation, dispatcher.__doc__)
+                 add_docstring(implementation, '' if dispatcher.__doc__ is None else dispatcher.__doc__)
         except:
             pass
```

**Comment by chwba** [comment]
There are many libs, that have to get patched, I will first try to go down the pyinstaller path

**Comment by chwba** [comment]
So, as it seems if using pyinstaller none of the libraries are obfuscated, which means an attacker could simply debug the libraries and will easily receive all information of the program it requires.

**Comment by jondy** [comment]
You think `pandas` and `numpy` are common cases, but I even don't know `pandas`. Python is used in very wide fields, many packages I never use. I'm also not planning to learn each of package and obfuscate them for end users. I'll add this to EULA because I'm not aware of this before. But I'm sure system package `multiprocessing` works with pyarmor if you use it in right way, it has been proved by a lot of users.
