### ISSUE TITLE
Type: Pack into one folder/file does not work in combination with advanced mode

### ISSUE THREAD

**Issue by chwba** [dashingsoft/pyarmor#456]
With (super) vm protection enabled: After packing, on starting the executable, it will hang forever and not start the application.
With  vm protection enabled: Error stating, it misses source files and thus cannot start the application.
With advanced mode: exception: access violation reading 0x0000000000000000

**Comment by jondy** [comment]
Please first following this guide to find the problem,
https://pyarmor.readthedocs.io/en/latest/questions.html#packing-obfuscated-scripts-problem

**Comment by chwba** [comment]
I followed that guide it did not solve the problem.

**Comment by jondy** [comment]
So does it work only obfuscate simple script with super mode in this Windows 10?
```
# foo.py is a simple script like this "print('hello')"
pyarmor obfuscate --advanced 2 --exact foo.py
python dist/foo.py
```
