### ISSUE TITLE
[Question] If type is set to Pack all in one folder/File, are the dependencies obfuscated as well?

### ISSUE THREAD

**Issue by chwba** [dashingsoft/pyarmor#457]
Because if not an attacker could simply debug the libraries and extract all relevant information...

**Comment by jondy** [comment]
No. PyArmor doesn't obfuscate the dependencies.

**Comment by NoahCardoza** [comment]
If you are referring to communications with your licensing server as "relevant information" I'd suggest not using dependencies for that. Just use the native socket/ssl modules but import straight from the binaries rather than the python wrappers. It takes a little reinvention of the wheel but it's probably the most secure way of doing it.

Or just include the wrappers in a utils folder and armor them.

**Comment by chwba** [comment]
Sure, lets reinvent everything and only use the standard library, that will make everything so much easier.

**Comment by jondy** [comment]
At this time, pyarmor doesn't obfuscate all the dependencies. The dependencies are unknown for pyarmor, some packages may not work after obfuscated. You can obfuscate them on demand as they're part of your application.

**Comment by chwba** [comment]
How do I force obfuscation of all dependency, when using 'Pack all into one folder'?

**Comment by jondy** [comment]
No option for this at this time.

**Comment by NoahCardoza** [comment]
Keep in mind no one is forcing you to use pyarmor. Pyarmor is fully capable of securing your code you just have to write it in a way that pyarmor can protect it. If you aren't willing to open a socket yourself, I'm not sure what to tell you. Python is a pretty high level language.

If you are worried about people changing the source files, you can always verify the bytecode of the functions you are employing, just keep in mind that those functions call functions which can get pretty messy to backtrack.

> Or just include the wrappers in a utils folder and armor them.

No reinvention of the wheel there anyways.

**Comment by chwba** [comment]
I don't want to get in a deep discussion about this now but I am of the oppinion, that a package, that offers obfuscation of an application should at least clearly point out, that the obfuscation is completely pointless if one does not obfuscate the applications dependencies as well.

**Comment by VeNoMouS** [comment]
but its not pyarmor putting those dependencies into the "one file" that's pyinstaller...

**Comment by jondy** [comment]
Even all the dependencies are obfuscated, it still can't prevent someone replacing the obfuscated script with their trick one. pyarmor provides 3 features to block this monkey trick attack:
1. Restrict mode
2. Decorator `assert_armored`
3. Plugin with private checkpoints
All of these are described in the last section in the basic usage page
https://pyarmor.readthedocs.io/en/latest/usage.html#improving-security-further
