### ISSUE TITLE
[BUG] Heavily inconsistent results

### ISSUE THREAD

**Issue by chwba** [dashingsoft/pyarmor#458]
Using the same settings, the obfuscated app works sometimes but sometimes not.
For instance at times we get `RuntimeError: unexpected C:\Users\user\PycharmProjects\project\dist\app\_pytransform.dll` or an error that the whoule `src` module is missing. Why is this happening?
We mainly use pyarmor-webui if thats relevant.

**Comment by jondy** [comment]
In windows 32, the default cross protection may not work, please disable `cross protection` for Windows 32.

**Comment by chwba** [comment]
Its been tested on Windows 10.

**Comment by jondy** [comment]
Please disable cross protection, or refer to the document to customize the cross protection script.

**Comment by jondy** [comment]
This is a known issue for 32-bit Python in any Windows platform, even in 64-bit Window.
