### ISSUE TITLE
Error on registering PyArmor in docker:dind image

### ISSUE THREAD

**Issue by spr732** [dashingsoft/pyarmor#459]
Hi,

In our jenkins automation we are using a `docker:dind` image of Docker. While registering PyArmor in that we are getting below error-
```[91mINFO     Create pyarmor home path: /root/.pyarmor
[0m[91mINFO     Create trial license file: /root/.pyarmor/license.lic
[0m[91mERROR    Error relocating /usr/lib/python3.6/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so: __snprintf_chk: symbol not found
[0mThe command '/bin/sh -c pyarmor register pyarmor-regcode-1.txt' returned a non-zero code: 1```

**Comment by jondy** [comment]
Pyarmor is platform-dependent, docker is another platform named `musl.x86_64`, not `linux.x86_64` in pyarmor.

Please download the corresponding core library from pyarmor-core, for example, tag `r39.13` is for pyarmor v6.6.0, 
https://github.com/dashingsoft/pyarmor-core/tree/r39.13/platforms/musl.x86_64.7

**Comment by VeNoMouS** [comment]
` docker is another platform named musl.x86_64`.... mmm not true... the `alpine` images are musl.x86_64 other packages such as "python3-slim" are linux.x86_64
