### ISSUE TITLE
[Query] Running multiple pyarmor_config on the same project.

### ISSUE THREAD

**Issue by piyush-das** [dashingsoft/pyarmor#460]
Hi,

I have a pyarmor project, where I am performing the following :
1. Encrypt all files with highest security. [pyarmor_config]
2. Relax obf_code=0 on certain files. [pyarmor_config-1]
3. Relax restriction level to 1 for certain entry scripts. [pyarmor_config-2]

Should I generate the run-time scripts only for the first config and not for the subsequent commands:
- pyarmor build -B
- pyarmor build --no-runtime -B .pyarmor_config-1
- pyarmor build --no-runtime -B .pyarmor_config-2

Is this the correct way to build, or --no-rutime can be specified in any one of the commands, and the order is not relevant ?

Thanks

**Comment by jondy** [comment]
The better way I think is to generate runtime separately, then use the same runtime package in different project, for example,
```
pyarmor runtime -O /path/to/runtime

pyarmor build --with-runtime /path/to/runtime -B
pyarmor build --with-runtime @/path/to/runtime -B .pyarmor_config-1
pyarmor build --with-runtime @/path/to/runtime -B .pyarmor_config-2
```

So all the projects are with same runtime files, refer to command `runtime` in the man page to understand how it works.

The order doesn't matter if there is no same files in different project.

**Comment by piyush-das** [comment]
I tried the following to generate runtime with super mode enabled.
`pyarmor runtime -O runtime --advanced 2`

Log
```log
INFO     PyArmor Version 6.6.0
INFO     Update target platforms to: ['linux.x86_64.11.py37']
INFO     Generating super runtime library to runtime
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Copying /home/xyz/.pyarmor/platforms/linux/x86_64/11/py37/pytransform.cpython-37m-x86_64-linux-gnu.so
INFO     Patch extension runtime/pytransform.cpython-37m-x86_64-linux-gnu.so
INFO     Patch library file OK
INFO     Generate runtime files OK
INFO     Generating protection script ...
INFO     Generating bootstrap script ...
INFO     Generating bootstrap script runtime/pytransform_bootstrap.py OK
```
Then when I tried to build the project. I am getting the following error.
`pyarmor build --with-runtime @runtime -B`

Log
```log
INFO     PyArmor Version 6.6.0
INFO     Build project  ...
INFO     Check project
INFO     Use capsule: /home/xyz/.pyarmor/.pyarmor_capsule.zip
INFO     Output path is: /home/xyz/test/pyarmor/encrypted
INFO     Got settings from --runtime: runtime
INFO         Platforms: linux.x86_64.11.py37
INFO         Advanced: 2
INFO         Suffix: 
INFO         License: embedded
INFO     Taget platforms: ['l', 'i', 'n', 'u', 'x', '.', 'x', '8', '6', '_', '6', '4', '.', '1', '1', '.', 'p', 'y', '3', '7']
ERROR    No available dynamic library for l with features ['11']
```
Please let me know where I am going wrong.

**Comment by jondy** [comment]
It's a bug,  a pre-release version can be installed to fix it
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.1.zip
```
The new version 6.6.1 will be released in a few days.

**Comment by piyush-das** [comment]
@jondy That resolved the previous issues, however I am getting a new one.

I have the following project structure
.
├── .pyarmor_config
├── pyarmor_config-1
├── pyarmor_config-2
└── test_pyarmor
    ├── hello.py
    ├── \_\_init\_\_.py
    └── new_hello.py

Contents of .pyarmor_config [ This is meant to encrypt everything with highest security ]
```json
{
  "version": "2.0",
  "name": "test_pyarmor",
  "title": "test_pyarmor",
  "src": "test_pyarmor",
  "is_package": 1,
  "manifest": "global-include *.py",
  "entry": "__init__.py",
  "output": "encrypted",
  "runtime_path": null,
  "restrict_mode": 4,
  "obf_code": 2,
  "obf_mod": 2,
  "wrap_mode": 1,
  "advanced_mode": 2,
  "bootstrap_code": 3,
  "cross_protection": 1,
  "plugins": null,
  "platform": null,
  "package_runtime": 1,
  "enable_suffix": 0,
  "license_file": null,
  "build_time": 1612009015.1462057
}
```
Contents of pyarmor_config-1 [This is meant to make "obf_code"=0 for "new_hello.py" as it would be used by a package which would utilize the bytecode like Tensorflow for autograph]
```json
{
  "version": "2.0",
  "name": "test_pyarmor",
  "title": "test_pyarmor",
  "src": "test_pyarmor",
  "is_package": 1,
  "manifest": "include new_hello.py",
  "entry": "",
  "output": "encrypted",
  "runtime_path": null,
  "restrict_mode": 4,
  "obf_code": 0,
  "obf_mod": 2,
  "wrap_mode": 1,
  "advanced_mode": 2,
  "bootstrap_code": 3,
  "cross_protection": 1,
  "plugins": null,
  "platform": null,
  "package_runtime": 1,
  "enable_suffix": 0,
  "license_file": null,
  "build_time": 1612009026.0660527
}
```
Contents of pyarmor-config-2 [This is meant to make the "test_armor" __init__.py importable]
```json
  "version": "2.0",
  "name": "test_pyarmor",
  "title": "test_pyarmor",
  "src": "test_pyarmor",
  "is_package": 1,
  "manifest": "include \_\_init\_\_.py",
  "entry": "",
  "output": "encrypted",
  "runtime_path": null,
  "restrict_mode": 1,
  "obf_code": 2,
  "obf_mod": 2,
  "wrap_mode": 1,
  "advanced_mode": 2,
  "bootstrap_code": 3,
  "cross_protection": 1,
  "plugins": null,
  "platform": null,
  "package_runtime": 1,
  "enable_suffix": 0,
  "license_file": null,
  "build_time": 1612009029.6165388
}
```
Then I am using the following commands : 
```bash
# Generate the runtime files
pyarmor runtime -O runtime --advanced 2

# Encrypt all files with max security
pyarmor build --with-runtime @runtime -B

# Relax obj_code = 0 on one file.
pyarmor build --with-runtime @runtime -B pyarmor_config-1

# Relax restrict_mode to make __init__.py importable as package
pyarmor build --with-runtime @runtime -B pyarmor_config-2
```

Everything works fine but when I try to import the encrypted package I get the following error : 
```bash
cd encrypted

➜ python -c "import test_pyarmor"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xyz/test/pyarmor/encrypted/test_pyarmor/__init__.py", line 1, in <module>
    from .pytransform import pyarmor
ModuleNotFoundError: No module named 'test_pyarmor.pytransform'
```

**Comment by jondy** [comment]
The obfuscated scripts can be taken as normal scripts, check the content of these obfuscated scripts, make sure the runtime package `pytransform` in the right place could be imported by Python.

Refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

There is option `--bootstrap` used to control how to generate the bootstrap code for obfuscated scripts, it's described here
https://pyarmor.readthedocs.io/en/latest/man.html#obfuscate

**Comment by piyush-das** [comment]
@jondy Is there an easier way to achieve the same without having to generate the runtime code separately ? My purpose is to use super mode, restrict_mode=4 and obf_code=2 for all the files in the project. For just one file I would like to reduce the obf_code=0. And then finally I would like to use restrict_mode=1 for the entry scripts.

Meanwhile, I will explore the reference links which you have shared?

**Comment by piyush-das** [comment]
I realized that the encrypted folder doesn't contain the runtime .so file and hence moved the same to it. On doing so I am getting the following error.
```
➜ python -c "import test_pyarmor"                  
[1]    36235 segmentation fault  python -c "import test_pyarmor"
```

**Comment by jondy** [comment]
> @jondy Is there an easier way to achieve the same without having to generate the runtime code separately ? My purpose is to use super mode, restrict_mode=4 and obf_code=2 for all the files in the project. For just one file I would like to reduce the obf_code=0. And then finally I would like to use restrict_mode=1 for the entry scripts.
> 
> Meanwhile, I will explore the reference links which you have shared?

The command `obfuscate` with option `--exact` is right for a few scripts.

> I realized that the encrypted folder doesn't contain the runtime .so file and hence moved the same to it. On doing so I am getting the following error.
> 
> ```
> ➜ python -c "import test_pyarmor"                  
> [1]    38048 segmentation fault  python -c "import test_pyarmor"
> ```

In the following cases, obfuscated scripts may crash

* Running obfuscated script by debug version Python
* Obfuscating scripts by Python X.Y but running the obfuscated scripts by
  different Python version M.N
* Running the scripts in different platform but obfuscate them without option
  ``--platform``

  - Docker, it's Alpine Linux, in PyArmor, the platform name is `musl.x86_64`,
    not `linux.x86_64`
  - In Windows, 32-bit Windows is different from 64-bit Windows
  - In 64-bit Windows, 32-bit Python is different from 64-bit Python

* Read ``co_code`` or other attributes of the obfuscated code object by any way,
  some third packages may analysis the byte code to do something.
* In MacOS, the core library of pyarmor is linked to standard system Python, for
  others, use ``install_name_tool`` to change ``rpath`` to adapt this machine.

Please first look through the common solutions if there is in trouble
https://pyarmor.readthedocs.io/en/latest/questions.html

Note that the basic usage of pyarmor is no longer supported, here it's technical support items of pyarmor EULA
https://pyarmor.readthedocs.io/en/latest/license.html#technical-support

**Comment by piyush-das** [comment]
@jondy Thanks for the detailed reference. I have gone through the common solutions and the following is my findings.
- Here is the basic settings I am using.
```json
{
  "version": "2.0",
  "name": "test_pyarmor",
  "title": "test_pyarmor",
  "src": "test_pyarmor",
  "is_package": 1,
  "manifest": "global-include *.py",
  "entry": "__init__.py",
  "output": "encrypted",
  "runtime_path": null,
  "restrict_mode": 4,
  "obf_code": 2,
  "obf_mod": 2,
  "wrap_mode": 1,
  "advanced_mode": 2,
  "bootstrap_code": 3,
  "cross_protection": 1,
  "plugins": null,
  "platform": null,
  "package_runtime": 1,
  "enable_suffix": 0,
  "license_file": null,
  "build_time": 1612065537.4174654
}
```
Ran `pyarmor build -B`
- The reason why I am not using `exact` command is that a lot of defaults have been changed, so I made a copy of this config and changed `manifest` to just 1 file and removed the `entry` field
Ran `pyarmor build --no-runtime -B pyarmor_config-1`
- Everything seems to run well, but as soon as `obf_code=0` is used, I get segmentation fault. However, if I use `obf_code=1` there are no segmentation faults. As mentioned in the common questions, none of the reasons for segmentation fault are present, and I believe this is a bug. It appears that `obf_code=0` is not compatible with the other security options, however there is no such limitations mentioned in the documentation.

**Comment by jondy** [comment]
Because `obf_code=0` means the code object is not obfuscated in runtime, so it's taken as plain script by restrict mode 4 scripts, and think it violates restrict mode ruler, so it crashes.

I'll add a note in the restrict mode documentation

**Comment by piyush-das** [comment]
@jondy I am trying to obfuscate a tensorflow based project. As a workaround to tensorflow's autograph feature's woa solution in #340 and #341 was to use `obf_code=0`. Is there any way to protect these files, since they would be part of a package and as per your package recommendation most files should have `restrict_mode=4` barring the entry scripts which need to have `restrict_mode=1`

**Comment by jondy** [comment]
You need learn how restrict mode 4 to work and may adapt your code to restrict mode 4, or use default restrict mode.

Refer to 
https://pyarmor.readthedocs.io/en/latest/mode.html#restrict-mode

**Comment by piyush-das** [comment]
@jondy After experimenting with the different modes, I can confirm that the change in `obf_code=0` fails even with default `restrict_mode=1` for all scripts.

**Comment by jondy** [comment]
It seems `--advanced 2` with `--obf-code=0` will crash even for a hello world script, I'll check this.

**Comment by jondy** [comment]
Fix `obf-code=0` doesn't work with `--advanced 2` issue in pre-release version
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.1.zip
```

**Comment by jondy** [comment]
pyarmor 6.6.1 has been released, please install it from PyPi.

**Comment by piyush-das** [comment]
@jondy I am still getting segmentation faults with the following configuration
```json
{
  "version": "2.0",
  "name": "test_pyarmor",
  "title": "test_pyarmor",
  "src": "test_pyarmor",
  "is_package": 1,
  "manifest": "global-include *.py",
  "entry": "__init__.py",
  "output": "encrypted",
  "runtime_path": null,
  "restrict_mode": 1,
  "obf_code": 0,
  "obf_mod": 2,
  "wrap_mode": 1,
  "advanced_mode": 2,
  "bootstrap_code": 3,
  "cross_protection": 1,
  "plugins": null,
  "platform": null,
  "package_runtime": 1,
  "enable_suffix": 0,
  "license_file": null,
  "build_time": 1612170250.638942
}
```

**Comment by jondy** [comment]
> Because `obf_code=0` means the code object is not obfuscated in runtime, it's taken as plain script by restrict mode 4 scripts, and think it violates restrict mode ruler, so it crashes.
>
What I fixed is combine `obf-mode=0` and `--advanced 2` issue. This script still violates the restrict mode.

**Comment by piyush-das** [comment]
> @jondy I am still getting segmentation faults with the following configuration. I have updated pyarmor to 6.6.1
> 
> ```json
> {
>   "version": "2.0",
>   "name": "test_pyarmor",
>   "title": "test_pyarmor",
>   "src": "test_pyarmor",
>   "is_package": 1,
>   "manifest": "global-include *.py",
>   "entry": "__init__.py",
>   "output": "encrypted",
>   "runtime_path": null,
>   "restrict_mode": 1,
>   "obf_code": 0,
>   "obf_mod": 2,
>   "wrap_mode": 1,
>   "advanced_mode": 2,
>   "bootstrap_code": 3,
>   "cross_protection": 1,
>   "plugins": null,
>   "platform": null,
>   "package_runtime": 1,
>   "enable_suffix": 0,
>   "license_file": null,
>   "build_time": 1612170250.638942
> }
> ```

This configuration is currently using `restrict_mode 1`. Is that also not supported?

**Comment by piyush-das** [comment]
> Fix `obf-code=0` doesn't work with `--advanced 2` issue in pre-release version
> 
> ```
> pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.1.zip
> ```

I am a little confused here. Did you mean `obf_code 0` or `obf_mode 0` here. And would `obf_code 0` still work with `restrict_mode 1`?

**Comment by jondy** [comment]
@piyush-das I found one issue
```
pyarmor obfuscate --advanced 2 --obf-code 0 foo.py

# It will crash
python dist/foo.py
```
What I fixed is that now `python dist/foo.py doesn't crash.

But your issue I think is that you obfuscate one script `a.py` with `--advanced 2` and `--obf-code 0`, and in the `a.py` try to import other scripts which are obfuscated with restrict mode 4.

**Comment by piyush-das** [comment]
> Because `obf_code=0` means the code object is not obfuscated in runtime, it's taken as plain script by restrict mode 4 scripts, and think it violates restrict mode ruler, so it crashes.
> 
> I'll add a note in the restrict mode documentation

Let's say I have three scripts in a package
1. \_\_init\_\_.py : [ restrict_mode : 1, obf-code 2] 
2. foo.py : [restrict_mode : 4, obf-code 2]
3. bar.py : [restrict_mode : 1, obf-code 0]

Now `bar.py` can be imported inside `foo.py` : Since `bar.py` has restrict_mode 1 and hence even if it would appear as plain script at runtime due to `obf-code=0` it would not violate the restriction due to restrict-mode 1.

However, `foo.py` cannot be imported inside `bar.py` since it would appear like a plain script and hence cannot import `foo.py`. But `foo.py` can be imported inside `__init__.py` since it has `obf-code=2` and hence would work.

Is my understanding correct?

**Comment by jondy** [comment]
Yes, it's exact what restrict mode does.

**Comment by piyush-das** [comment]
Great, I am able to achieve that with 6.6.1 fixes in that case. Thank you for your patience and helping me out. Much appreciated.
