### ISSUE TITLE
ERROR    'utf-8' codec can't decode byte 0xe4 in position 307: invalid continuation byte

### ISSUE THREAD

**Issue by MikkM** [dashingsoft/pyarmor#461]
Hi, wanted to try pyarmor, but when i run:

pyarmor obfuscate main.py

i get following error:
INFO     Start obfuscating the scripts...
INFO            main.py -> dist\main.py
INFO     Insert shell line: #!/usr/bin/env python3
INFO     Insert bootstrap code to entry script dist\main.py
INFO            updaterNEW.py -> dist\updaterNEW.py
ERROR    'utf-8' codec can't decode byte 0xe4 in position 307: invalid continuation byte

I tried adding:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

to main.py but no difference.

**Comment by jondy** [comment]
Does it work in the same terminal as pyarmor run?
```
python main.py
```

**Comment by MikkM** [comment]
I cannot test script in terminal as its an XBMC/KODI addon, wich runs in
XBMC/KODI fine , no errors.

https://pastebin.com/nHMd1dnV

**Comment by MikkM** [comment]
Ah sorry, updaterNEW.py was another file i had laying on desktop, didnt realize that when running: pyarmor obfuscate main.py   would include some other random python scripts also into its process.
