### ISSUE TITLE
could not find  /android/x86/_pytransform.so

### ISSUE THREAD

**Issue by yuceltoluyag** [dashingsoft/pyarmor#462]
Python Version(desktop)
```
python --version
Python 3.9.1
```

```
 pyarmor obfuscate --platform android.aarch64   --platform android.armv7  .\start.py
INFO     PyArmor Trial Version 6.6.0
INFO     Target platforms: ['android.aarch64', 'android.armv7']
INFO     Update target platforms to: ['android.aarch64.0', 'android.armv7.0']
INFO     ====================================================
INFO     Reload PyArmor with platform: windows.x86_64.0
INFO     ====================================================
INFO     PYARMOR_PLATFORM is windows.x86_64.0
INFO     Source path is "C:\Users\yucel\Desktop\sifre"
INFO     Entry scripts are ['.\\start.py']
INFO     Use cached capsule C:\Users\yucel\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Create library path to support multiple platforms: dist\pytransform\platforms
INFO     Copying C:\Users\yucel\.pyarmor\platforms\android\aarch64\0\_pytransform.so
INFO     To dist\pytransform\platforms\android\aarch64
INFO     Patch library dist\pytransform\platforms\android\aarch64\_pytransform.so
INFO     Patch library file OK
INFO     Copying C:\Users\yucel\.pyarmor\platforms\android\armv7\0\_pytransform.so
INFO     To dist\pytransform\platforms\android\armv7
INFO     Patch library dist\pytransform\platforms\android\armv7\_pytransform.so
INFO     Patch library file OK
INFO     Copying c:\users\yucel\appdata\local\programs\python\python39\lib\site-packages\pyarmor\pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            a.py -> dist\a.py
INFO            func.py -> dist\func.py
INFO            main.py -> dist\main.py
INFO            start.py -> dist\start.py
INFO     Insert bootstrap code to entry script dist\start.py
INFO     Obfuscate 4 scripts OK.
```

The programs I use Bluestacks,Termux
Termux Python version 
```
python --version
Python 3.9.1
```
termux linux version
```
uname -a                                               
Linux localhost 4.9.31 #1 SMP PREEMPT Wed Jan 13 07:17:31 IST 2021 i686 Android
```

python start.py
could not find "storage/emulated/0/download/1/pytransform/platforms/android/x86/_pytransform.so"

what is wrong, no x86 support?

**Comment by jondy** [comment]
I build it just now, please install this pre-release version
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.1.zip
```

**Comment by yuceltoluyag** [comment]
> I build it just now, please install this pre-release version
> 
> ```
> pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.1.zip
> ```

Let me wait for the process to finish, I installed the pre-release version, there was no change. Or do I need to add an extra new parameter?

`pyarmor obfuscate --platform android.aarch64   --platform android.armv7  .\start.py`

**Comment by jondy** [comment]
Refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#distributing-obfuscated-scripts-to-other-platform

**Comment by yuceltoluyag** [comment]
> Refer to
> https://pyarmor.readthedocs.io/en/latest/advanced.html#distributing-obfuscated-scripts-to-other-platform

sorry but no change 🥇  Do you have a chance to notification your change ?

**Comment by jondy** [comment]
Sorry, I miss index file. Try to install it again, I have upload new one to same location.

**Comment by yuceltoluyag** [comment]
> Sorry, I miss index file. Try to install it again, I have upload new one to same location.

 pyarmor download android.x86
```
INFO     PyArmor Trial Version 6.6.1
INFO     Downloading dynamic library for android.x86
INFO     Search library for platform: android.x86
INFO     Found available libraries: ['android.x86.0']
INFO     Target path for android.x86.0: C:\Users\yucel\.pyarmor\platforms\android\x86\0
INFO     Downloading library file for android.x86.0 ...
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r40.14/platforms/android.x86.0/_pytransform.so
INFO     Could not get file from https://github.com/dashingsoft/pyarmor-core/raw/r40.14/platforms: HTTP Error 404: Not Found
INFO     Getting remote file: https://pyarmor.dashingsoft.com/downloads/r40.14/android.x86.0/_pytransform.so
INFO     Writing target file: C:\Users\yucel\.pyarmor\platforms\android\x86\0\_pytransform.so
INFO     Download dynamic library android.x86.0 OK
```

thank you

**Comment by jondy** [comment]
> dlopen failed: couldn't map "/storage/emulated/0/work/pytransform/platforms/android/x86/_pytransform.so" segment 1: Operation not permitted

pyarmor can do nothing for this, please consult android development document

**Comment by worldvideos1203** [comment]
> > dlopen failed: couldn't map "/storage/emulated/0/work/pytransform/platforms/android/x86/_pytransform.so" segment 1: Operation not permitted
> 
> pyarmor can do nothing for this, please consult android development document

What can we do after consulting android development document?
Mobile termux users are in huge numbers..
Are u giving up on them??
I have exact same issue

**Comment by jondy** [comment]
>What can we do after consulting android development document?

@worldvideos1203 
Put pyarmor runtime package in right location. Android doesn't allow loading dynamic library in the data path, this is the problem.
