### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by JKKSI** [dashingsoft/pyarmor#464]
Hello, how 20 days ago you give me a new version of pyarmor because --advanced 2 dont was working fine, when i tried this time to obfuscate my script with the next command -->:
pyarmor obfuscate --platform windows.x86 --platform linux.x86_64 --with-license licenses/r001/license.lic --plugin check_ntp_time --advanced 2 Satellite.py

i Get this....

C:\Users\Daishinkan\Desktop\Beta\pyarmortryone\laboratorio>pyarmor obfuscate --platform windows.x86 --platform linux.x86_64 --with-license licenses/r001/license.lic --plugin check_ntp_time --advanced 2 Satelitte.py
INFO     PyArmor Version 6.6.1
INFO     Target platforms: ['windows.x86', 'linux.x86_64']
INFO     Update target platforms to: ['windows.x86.11.py38', 'linux.x86_64.11.py38']
INFO     Source path is "C:\Users\Daishinkan\Desktop\Beta\pyarmortryone\laboratorio"
INFO     Entry scripts are ['Satelitte.py']
INFO     Use cached capsule C:\Users\Daishinkan\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 2
INFO     Super mode is True
INFO     Generating super runtime library to dist
INFO     The platform windows.x86.11.py38 is out of date
INFO     Search library for platform: windows.x86.11.py38
INFO     Found available libraries: ['windows.x86.11.py38']
INFO     Target path for windows.x86.11.py38: C:\Users\Daishinkan\.pyarmor\platforms\windows\x86\11\py38
INFO     Downloading library file for windows.x86.11.py38 ...
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r40.14/platforms/windows.x86.11.py38/pytransform.pyd
ERROR    Verify dynamic library failed

But with --advanced 1 working

**Comment by jondy** [comment]
Please report issue as the bug template, and fill a clear title.

By the way, this is not a bug of pyarmor, if you read the hints in the bug template carefully, you can find the problem and solve it by yourself.

The technical support items of PyArmor EULA has been changed, please check it
https://pyarmor.readthedocs.io/en/latest/license.html#technical-support

I no longer handle the wrong usage issue.

**Comment by JKKSI** [comment]
Hello, i tried to find the problem but i didnt find the problem, can do you please help me or provide me a command for fix the problem?, i hope your answer soon.

________________________________
De: Jondy <notifications@github.com>
Enviado: domingo, 7 de febrero de 2021 12:07 a. m.
Para: dashingsoft/pyarmor <pyarmor@noreply.github.com>
CC: VIPER X Chaos <ben-fuerte2002@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [dashingsoft/pyarmor] [Bug] (#464)


Please report issue as the bug template, and fill a clear title.

By the way, this is not a bug of pyarmor, if you read the hints in the bug template carefully, you can find the problem and solve it by yourself.

The technical support items of PyArmor EULA has been changed, please check it
https://pyarmor.readthedocs.io/en/latest/license.html#technical-support

I no longer handle the wrong usage issue.

**Comment by jondy** [comment]
https://pyarmor.readthedocs.io/en/latest/questions.html#common-solutions
