### ISSUE TITLE
"Too big code object, the limitation is 32768 bytes in trial version" on file that is 32768  butes or less

### ISSUE THREAD

**Issue by Buster-2002** [dashingsoft/pyarmor#465]
It's more readable in the issue Preview mode for the hints

**Hints**
```
The core library version: r34, age: 8, features: 0
No such file or directory
license.c,360,0x0,Check license failed, Invalid input packet.
No such file or directory
license.c,360,0x0,Check license failed, Invalid input packet.
No such file or directory
license.c,360,0x0,Check license failed, Invalid input packet.
_pytransform.c,1116,0x0,Encrypt code object failed
```

**Describe the bug**
I am trying to obfuscate a file that is, according to Windows, 26 603 bytes big and 28 672 bytes on disk
![image](https://user-images.githubusercontent.com/56275687/107119357-502e0900-6887-11eb-9763-d81b745aaafa.png)
However when trying to obfuscate it, I get an error saying `Too big code object, the limitation is 32768 bytes in trial version`, 
which is interesting as the file clearly isn't that big. Other files do obfuscate, and they are a bigger size.

**To Reproduce**
Python 3.8.5
Windows 10 pro
options [here](https://mystb.in/NewbieVhsDepends.prolog)

**Comment by jondy** [comment]
The trial version will check the total size of byte code, not the file size of source script.
