### ISSUE TITLE
Pyarmor obfuscated code not able to identify alias name

### ISSUE THREAD

**Issue by mayank564** [dashingsoft/pyarmor#466]
This issue is an extension of https://github.com/dashingsoft/pyarmor/issues/445 in our code structure we have certain API's defined which uses alias name.
The code is built on cherryPy Framework of Python.
**Issue** : As we have totally obfuscated our Project code with pyarmor and the service is also up and  running successfully Whenever we call the API which has a alias name it throws 404 Not Found error.
Example :
 ```
@cherrypy.expose(alias='myapi')
    @cherrypy.tools.json_out()
    # pylint: disable=no-member
    @cherrypy.tools.authenticate()
    @cherrypy.tools.validateOptOut()
    @cherrypy.tools.validateHttpVerbs(allowedVerbs=['POST'])
    # pylint: enable=no-member
    def abc_xyz(self, arg1, arg2):
        """
        This is the doc string
        """
```
So if i call this API with alias name "myapi" it throws me 404 Error and the API's which do not have any alias name works perfectly.
Any suggestion on how to resolve this issue would be helpful.

Thanks in Advance

**Comment by jondy** [comment]
Please check the source of decorator function `cherrypy.expose`, check it how to handle keyword argument `alias`, make sure it doesn't use any feature changed by obfuscated scripts, refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts

**Comment by mayank564** [comment]
As Cherrypy is a third party inbuilt module of python and i can't change the code inside it and as far as my understanding Pyarmor obfuscation only obfuscates the local project not the python inbuilt library right?

**Comment by jondy** [comment]
Unless cherrypy is written by c extension, all the `.py` file should be readable even if it's a third party package.

Pyarmor only obfuscates files specified by command options, by default the command `pack` obfuscates all the .py files only in the entry script’s path recursively. It won’t obfuscate all the dependencies out of this path.

**Comment by spr732** [comment]
`cherrypy.expose` decorator uses `parents = sys._getframe(1).f_locals` internally. Can it be related to usage of  `f_locals` ?

**Comment by jondy** [comment]
Yes, `f_locals` is the exact problem. In order to protect local data, pyarmor hides real `frame.f_locals`.

**Comment by mayank564** [comment]
One querry related to obfuscation in Super mode in the docs it mentions that we can use Advanced mode in Python versions(2.7, 3.7, 3.8, 3.9)  but as our Project is using Python 3.6.10 version of Python is there any workaround for using Super mode in Python 3.6.10.
Source : [](https://pyarmor.readthedocs.io/en/latest/mode.html#super-mode)

@jondy  any suggestion for the above querry

**Comment by jondy** [comment]
@mayank564 upgrade Python 3.6 or use non-super mode.

**Comment by mayank564** [comment]
Yeah sure @jondy going with Python 3.7 as of now for Windows platform.
Is there any workaround for the `f_locals ` issue in cherrypy as it is big issue for us because many of our API uses alias name and as the cherrypy is a framework we can't change the code in `cherrypy.expose` decorator.

**Comment by jondy** [comment]
@mayank564 no solution for this in super mode. It should not be the problem in non-super mode.

In super mode, I can't reduce the security to open `frame.f_locals`, the only solution is to change `cherrypy.expose` to use other way export alias. If `cheerpy` can't be changed at all, I really have no idea about this.

**Comment by jondy** [comment]
@mayank564  well I find a way may solve this issue. Which python version and which platform used? I'll build a test version for it.

**Comment by jondy** [comment]
please install this pre-release version for windows.x86, windows.x86_64, linux.x86_64 and darwin.x86_64
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.2.zip
```
Note that the pre-release version may be changed from time to time to fix new bugs, please update it if it doesn't work. And once the new version is released in PyPI, please remove the pre-release version, install the latest pyarmor from PyPi.

**Comment by mayank564** [comment]
In non-super mode also the problem of `f_locals ` exists.
Python version - 3.6.8
Platform - Windows x86_64.
can i install the pre release version and the super mode in python 3.6.8?

**Comment by jondy** [comment]
> can i install the pre release version and the super mode in python 3.6.8?
No. Python 3.6 doesn't support super mode.

**Comment by mayank564** [comment]
Hi @jondy will the above pre release version provided by you will resolve the `f_locals` issue?

**Comment by jondy** [comment]
I'm not sure it could fix this issue. I just change a little to improve the super mode.

Note that you also need check the source around the traceback raised by calling alias api, make sure it doesn't use any other features changed by the obfuscated scripts.
