### ISSUE TITLE
macOS平台进行pack后报错

### ISSUE THREAD

**Issue by wp0qw** [dashingsoft/pyarmor#467]
macOS平台，使用 `pyarmor pack -e " --noconsole" main.py` 打包后无法运行，使用 `./main` 命令运行报错：

`Traceback (most recent call last):
  File "dist/obf/venv/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 1, in <module>`
`NameError: name '__pyarmor__' is not defined`
`[41194] Failed to execute script pyi_rth_multiprocessing`

我已经根据文档：[常见问题](https://pyarmor.readthedocs.io/zh/v5.6.0/questions.html) 进行检查，没有发现 "引导文件" 有问题，但我的确使用了 `subprocess.Popen()` , `threading.Thread()` , `class(QThread)` 等新进程的函数，我不知道该怎么去修改它，特此请教，我使用的是pyqt5，谢谢您。

**Comment by jondy** [comment]
请使用超级模式加密脚本，这样可以避免引导代码的问题，例如
```
pyarmor pack -e " --noconsole" -x " --advanced 2" main.py
```
请参考文档命令手册中的 `pack` 的说明

另外，在切换模式之前把原来的临时目录 `build`, `dist` 都删除了

**Comment by wp0qw** [comment]
已经按照您说的打包好了，但是还会报错：
`
Traceback (most recent call last):
  File "<dist/obf/Morck.py>", line 2, in <module>
  File "<frozen Morck>", line 49, in <module>
  File "<frozen Morck>", line 44, in protect_pytransform
  File "<frozen Morck>", line 37, in check_lib_pytransform
RuntimeError: unexpected /Users/cbdf1/Desktop/new_3/dist/Morck/pytransform.cpython-39-darwin.so
[42838] Failed to execute script Morck
`
麻烦您再给看一下。

**Comment by jondy** [comment]
请参考这里有这类问题的解决方案
http://pyarmor.readthedocs.io/zh/latest/questions.html

有问题的时候先看一下这里，很多常见问题都在这里，另外也要通过文档来了解 pyarmor 的功能，目前对这种基本使用问题已经不在提供支持。

**Comment by jondy** [comment]
Python3.9 在 MacOS 下打包的这个保护异常是个 Bug，在开发版本 v6.6.2 中已经解决，目前这个版本暂时使用 `--no-cross-protection` 来解决

**Comment by wp0qw** [comment]
谢谢大佬的回复，这个问题已经解决，感谢春节假期期间的回复。
