### ISSUE TITLE
NameError: name '__armor_wrap__' is not defined

### ISSUE THREAD

**Issue by bashar-ait** [dashingsoft/pyarmor#468]
Hey
I'm getting this error on my obfuscate django app using the super mode and apache2 server. 
its actually weird when i access my django app using my public server ip it works fine, but when i access it using "localhost" it shows 500 server error and i get that error in the apache2 logs "armor_wrap is not defined"

I'm using super mode on arm64 system

thanks

**Comment by jondy** [comment]
Make sure it works without obfuscation when accessing it by `localhost`?

Also refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#nameerror-name-armor-wrap-is-not-defined

**Comment by bashar-ait** [comment]
> Make sure it works without obfuscation when accessing it by `localhost`?
> 
> Also refer to
> https://pyarmor.readthedocs.io/en/latest/questions.html#nameerror-name-armor-wrap-is-not-defined

Yes it works without obfuscation, and im not using restrict mode.
this is the command im using
pyarmor3.7 obfuscate --platform linux.aarch64 --advanced 2 --src="." -r --output=$path Project/wsgi.py

**Comment by jondy** [comment]
If there is line number and script name in the traceback, check the source script around this line. Make sure it doesn’t use any features changed by obfuscated scripts.

**Comment by bashar-ait** [comment]
> If there is line number and script name in the traceback, check the source script around this line. Make sure it doesn’t use any features changed by obfuscated scripts.

[Mon Feb 15 07:31:07.121620 2021] [wsgi:error] [pid 18115:tid 281472896332176] [client ::1:56420] mod_wsgi (pid=18115): Failed to exec Python script file '/var/www/Project/Project/wsgi.py'.
[Mon Feb 15 07:31:07.121926 2021] [wsgi:error] [pid 18115:tid 281472896332176] [client ::1:56420] mod_wsgi (pid=18115): Exception occurred processing WSGI script '/var/www/Project/Project/wsgi.py'.
[Mon Feb 15 07:31:07.122453 2021] [wsgi:error] [pid 18115:tid 281472896332176] [client ::1:56420] Traceback (most recent call last):
[Mon Feb 15 07:31:07.122559 2021] [wsgi:error] [pid 18115:tid 281472896332176] [client ::1:56420]   File "</var/www/Project/Project/wsgi.py>", line 2, in <module>
[Mon Feb 15 07:31:07.122595 2021] [wsgi:error] [pid 18115:tid 281472896332176] [client ::1:56420]   File "<frozen Project.wsgi>", line 1, in <module>
[Mon Feb 15 07:31:07.122672 2021] [wsgi:error] [pid 18115:tid 281472896332176] [client ::1:56420] NameError: name '__armor_wrap__' is not defined
`

here is the traceback error from apache2 logs. it points to the pyarmor code in the wsgi.py (entry script)

`

**Comment by jondy** [comment]
How about replacing `/var/www/Project/Project/wsgi.py` with original script (no obfuscation)?

And check which Python interpreter used by  apache to call `wsgi` script?

**Comment by bashar-ait** [comment]
i'll update this when i get access to the device that faces this issue

**Comment by bashar-ait** [comment]
> How about replacing `/var/www/Project/Project/wsgi.py` with original script (no obfuscation)?
I tried it, it worked for like 2 min then it crashed and started returning server error 
> And check which Python interpreter used by apache to call `wsgi` script?
The same python version that was used to obfuscate the script

**Comment by jondy** [comment]
> > How about replacing `/var/www/Project/Project/wsgi.py` with original script (no obfuscation)?
> 
> I tried it, it worked for like 2 min then it crashed and started returning server error
>

So what's the full traceback?

> > And check which Python interpreter used by apache to call `wsgi` script?
> 
> The same python version that was used to obfuscate the script

Could you set environment variable PYTHONDEBUG to run `wsgi.py` to get more error message?


>its actually weird when i access my django app using my public server ip it works fine, but when i access it using "localhost" it shows 500 server error and i get that error in the apache2 logs "armor_wrap is not defined"

One thing I need make sure, you access the same server and same obfuscated scripts with public server ip and localhost, and only localhost raises 500 error. Both public server ip and localhost are severed by apache, not directly visit localhost port.

**Comment by bashar-ait** [comment]
> So what's the full traceback?
just one line pointing to the wsgi.py file (failed to execute python script)

> Could you set environment variable PYTHONDEBUG to run wsgi.py to get more error message?
I will try this once i have access to the devices that have the issue.


> One thing I need make sure, you access the same server and same obfuscated scripts with public server ip and localhost, and only localhost raises 500 error. Both public server ip and localhost are severed by apache, not directly visit localhost port.

Exactly the same scripts when accessed using the public server ip it works fine but when using localhost, 127.0.0.1 it shows 500 error. 
When i restart apache2 localhost works fine but once I send a request to my custom built API it raises 500 internal server error.

**Comment by jondy** [comment]
> > So what's the full traceback?
> 
> just one line pointing to the wsgi.py file (failed to execute python script)

Even if the wsgi.py file is replaced with original script (no obfuscatation), it still raises the same exception?

**Comment by bashar-ait** [comment]
> > > So what's the full traceback?
> > 
> > 
> > just one line pointing to the wsgi.py file (failed to execute python script)
> 
> Even if the wsgi.py file is replaced with original script (no obfuscatation), it still raises the same exception?

Yes, 
"Failed to execute python script wsgi.py" 

I have disabled super mode and its working fine now
