### ISSUE TITLE
Where do I debug the code in pytransform.log of Segmentation fault error

### ISSUE THREAD

**Issue by CKitisak** [dashingsoft/pyarmor#469]
I'm using PyArmor Version `5.6.8` and Python `3.8.0`. 

The obfuscating codes is done without any errors. but when I run the obfuscated script I got `Segmentation fault`
I also checked and tried these:
- Both of Obfuscating machine and running the obfuscated scripts are using the same Python version 3.8.0
- Obfuscate the code with option `--platform armv7` (Running machine platform)
- Try both Comment and Uncomment on this line `m.set_option(5, c_char_p(1))`

my `pytransform.log` file shows the following contents:
```
PT-IM-00
WR-PA-00
WR-PA-01
WR-PA-02
WR-PA-03
WR-PA-04
WR-PA-05.1
WR-PA-05.2
PT-IM-01
PT-ITC-00
PT-ITC-01
PT-ITC-02
PT-ITC-03
PT-ITC-04
PT-ITC-05
PT-ITC-06
PT-IM-02
LC-IV-01
LC-IV-02
LC-IV-03
LC-IV-04
LC-IV-05
PT-IM-03
PT-VL-00
```

What should I do or how do I find the description of those codes?

Thank you

**Comment by jondy** [comment]
Try to obfuscate scripts with `--platform linux.armv7.0`

**Comment by CKitisak** [comment]
Thank you @jondy for answering.
when I used `linux.armv7.0`. I got an error like below
```
INFO     Patch this entry script with protection code
ERROR    [Errno 2] No such file or directory: '/home/abc/.pyenv/versions/3.8.0/envs/venv_pyarmor/lib/python3.8/site-packages/pyarmor/platforms/linux.armv7.0'
```
then I tried to download `linux.armv7.0` but it's not supported on my pyarmor version.
```
(venv_pyarmor) $ pyarmor download linux.armv7.0
INFO     PyArmor Version 5.6.8
INFO     Download dynamic library for linux.armv7.0
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/v5.5.3/platforms/index.json
INFO     Search library for linux.armv7.0 and arch x86_64
INFO     Loading platforms information
ERROR    Unsupport platform linux.armv7.0
ERROR    No available library for this platform
```

p.s. I cannot use the newer pyarmor version because the register code I have doesn't work with. please suggest me.

Thank you.

**Comment by jondy** [comment]
When do you purchase the PyArmor License? If it's purchased after 2017-10-10, please send me your registration email or order no, it could be upgraded without fee.

**Comment by CKitisak** [comment]
@jondy I just sent you an email about the information you requested. thank you.
