### ISSUE TITLE
Pyarmor Restriction

### ISSUE THREAD

**Issue by BlackRouter** [dashingsoft/pyarmor#47]
hi
sry just i have a question

pyarmor Restriction for time use or tools limited?
i want know for this question

**Comment by jondy** [comment]
Tools limited. Free trial version never expires, the limitation is

[Global Capsule](https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#global-capsule)  in trial version is fixed.

**Comment by BlackRouter** [comment]
> Tools limited. Free trial version never expires, the limitation is
> 
> [Global Capsule](https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#global-capsule) in trial version is fixed.

thank you for answer i can buy with bitcoin?
license Purchase Permanently or expired?
