### ISSUE TITLE
Reread licence without restarting process.

### ISSUE THREAD

**Issue by registsys** [dashingsoft/pyarmor#471]
We are using python 3.8, pyarmor 6.6.1 and PySide2. For the convenience of our users, we want to provide the ability to update the license from the running application, but we faced the fact that after the runtime module pytransform is imported, the call to pytransform.get_license_info () will always return the same value, even if the license file is in the runtime folder module will be replaced with another one. Is it possible to read information from a new license file (or lines) without restarting the process?

**Comment by jondy** [comment]
First use outer license, second use `--enable-period-mode` to generate a license file, refer to
https://pyarmor.readthedocs.io/en/latest/man.html#licenses

**Comment by registsys** [comment]
Thanks for the quick response. Yes, we are using outer licence and --advanced 2, but when I generate licence, put it to folder with runtime module, run python console, then:

```
>>>import pytransform
>>>pytransform.get_license_info()
```

I get 

```
{'ISSUER': 'pyarmor-vax-....', 'EXPIRED': '*TIME:1614546000', 'FLAGS': 42, 'CODE': 'CODE:regcode-01'}
```

after that, I remove  licence.lic or replace with other licence.lic file, and call again

```
>>>pytransform.get_license_info()
```

I get again 

```
{'ISSUER': 'pyarmor-vax-....', 'EXPIRED': '*TIME:1614546000', 'FLAGS': 42, 'CODE': 'CODE:regcode-01'}
```

but expected info about new license or RuntimeError when it absent

**Comment by registsys** [comment]
The main goal is to enable the user to enter a new activation key (content of license.lic), check that it is valid, and continue the application with the new activation key without restarting the application.

**Comment by jondy** [comment]
This is a bug, I have fixed it in the pre-release version, please install this pre-release version
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.2.zip
```

Note that the pre-release version may be changed from time to time to fix new bugs, please update it if it doesn't work. And once the new version is released in PyPI, please remove the pre-release version, install the latest pyarmor from PyPi.

**Comment by registsys** [comment]
Thank you, I will to try pre-release version.

**Comment by registsys** [comment]
It works, thank you again.

**Comment by registsys** [comment]
Sorry for posting after issue closed, but I have one small question: can I retrieve licence_info from valid, but expired licence.lic file?

**Comment by jondy** [comment]
Please check this document https://pyarmor.readthedocs.io/en/latest/pytransform.html

And verify it by doing a test in 5 minutes.

**Comment by registsys** [comment]
Yes, I am familiar with the current behavior:
- If the obfuscated script has been expired, it will raise exception and quit directly
- Raise Exception if license is invalid
and so.....
I wanted to believe that there is a way to get additional information that will allow us to renew the license after its expiration or changed hd, for example.

**Comment by jondy** [comment]
At this time no api for this. Now one solution is to check the license file directly, refer to this issue #290

**Comment by registsys** [comment]
Yes, we came to the same decision (to store user data in other place) independently.
