### ISSUE TITLE
Cross-compatibility of Obfuscated Modules Across Python Versions

### ISSUE THREAD

**Issue by snakers4** [dashingsoft/pyarmor#473]
Dear team and @jondy,

We have purchased a `pyarmor` license and we are quite happy with it.
All the documented features seem to be working more or less fine.
We are using `pyarmor` to obfuscate single the more critical IP-heavy modules and so far just direct replacement of said modules with the `so` files works just fine. 

Let me describe our use case first, we use `pyarmor` under Linux (Ubuntu) the following way:

```
pyarmor obfuscate --with-license licenses/license.lic --advanced 2 --exact module1.py module2.py module3.py
```

And then we ship these binaries as a part of our dockerized set of distros, which works just fine.

**So I would like to ask a couple of questions:**

(0)
I run the obfuscation script under `python-3.7`.
When our build system is based off a build that produces a `python-3.8` environment, these `so` files do not work with some cryptic error (sorry, I have not recorded the exact error).

Do I understand correctly that obfuscated scripts are supposed to work only on the same python version as the machine that obfuscated them? This is a minor inconvenience since we have frozen dockerized builds, but probably adding something in the docs on the topic would be nice (sorry if I missed it, I did my searches).

(1)
I noticed that when I run the same script (below) for example now and in several minutes from now, the `md5sum` of the resulting `py` and `so` files remains the same.

But if I keep the `so` and `py` files and try the same command, say tomorrow - the `md5sum` of the `so` file changes. I am not very big expert in cryptography, but probably it means that you use some salt based off current date / time, which is fine. But when I am obfuscating several scripts (not a whole module, just 2 or 3 files) does it mean that these `so` files are not interchangeable? Across python versions? Will this hold in future?

To give some more background, we intend to keep the `so` files operational for 6-12 months, while our environments may update once a month maybe and sometimes newer libraries favor newer python versions.

```
pyarmor obfuscate --with-license licenses/license.lic --advanced 2 --exact module1.py module2.py module3.py
```

Best,
Alex

PS

A small suggestion.
You document how to obfuscate a single module, but you do not explicitly show how to obfuscate 2 single modules at the same time. Maybe it is worth adding this to the docs as well.

**Comment by jondy** [comment]
Thank you for purchasing pyarmor.

> (0)
> I run the obfuscation script under `python-3.7`.
> When our build system is based off a build that produces a `python-3.8` environment, these `so` files do not work with some cryptic error (sorry, I have not recorded the exact error).
> 
> Do I understand correctly that obfuscated scripts are supposed to work only on the same python version as the machine that obfuscated them? This is a minor inconvenience since we have frozen dockerized builds, but probably adding something in the docs on the topic would be nice 

Do you check this
https://pyarmor.readthedocs.io/en/latest/questions.html#common-solutions

And there is a link to **The Differences of Obfuscated Scripts** in this section
```
First make sure you have read the basic guide Using PyArmor.
Look through Understanding Obfuscated Scripts, especially the section The Differences of Obfuscated Scripts
```

> (1)
> I noticed that when I run the same script (below) for example now and in several minutes from now, the `md5sum` of the resulting `py` and `so` files remains the same.
> 
> But if I keep the `so` and `py` files and try the same command, say tomorrow - the `md5sum` of the `so` file changes. I am not very big expert in cryptography, but probably it means that you use some salt based off current date / time, which is fine. But when I am obfuscating several scripts (not a whole module, just 2 or 3 files) does it mean that these `so` files are not interchangeable? Across python versions? Will this hold in future?
> 
> To give some more background, we intend to keep the `so` files operational for 6-12 months, while our environments may update once a month maybe and sometimes newer libraries favor newer python versions.
> 
> ```
> pyarmor obfuscate --with-license licenses/license.lic --advanced 2 --exact module1.py module2.py module3.py
> ```
> 

I think you can use command `runtime` to generate runtime once, then obfuscate with this runtime, please refer to
https://pyarmor.readthedocs.io/en/latest/man.html#runtime

> A small suggestion.
> You document how to obfuscate a single module, but you do not explicitly show how to obfuscate 2 single modules at the same time. Maybe it is worth adding this to the docs as well.

In the example section of this command, there is one example to obfuscate 2 scripts with `--exact`
https://pyarmor.readthedocs.io/en/latest/man.html#obfuscate

As my thought, for basic usage, just check the guide of basic usage. If users need advanced features, man page should be read to understand how to use each options.

If you think anything not clear, could you submit a pull request in the source `docs/`?

**Comment by snakers4** [comment]
> As my thought, for basic usage, just check the guide of basic usage. If users need advanced features, man page should be read to understand how to use each options.

Many thanks.
I neglected reading the man pages under `Man Page` before.
As for other questions it is also clear.

**Comment by snakers4** [comment]
Hi @jondy 

Recently installed a new version of pyarmor from pip (`pyarmor==6.7.2`) and noticed that the `so` does not longer have a python version in it, i.e.

```
pytransform.cpython-37m-x86_64-linux-gnu.so => pytransform.so
```

Is it just a visual artefact, or starting from some version, binaries will not be python version specific?

**Comment by jondy** [comment]
@snakers4 The file is same, and still is python version specific. It's just a visual artifact to fix this extension module could be not found in some platforms.

**Comment by snakers4** [comment]
I see
Thanks!
