### ISSUE TITLE
GPU Licensing Best Practices

### ISSUE THREAD

**Issue by snakers4** [dashingsoft/pyarmor#474]
Hi again,

I have seen some [examples](https://github.com/dashingsoft/pyarmor/issues/376) showing the CPU license binding via the plugins. I was wondering if there was any known best practice for doing so with GPUs, and I would like to share my plugin code (hope this can be helpful for other people or docs maybe).

Basically what I am doing:

```
pyarmor licenses --expired 2022-02-21 -x gpu-70ef1701-4072-9722-cc0b-7c7e75ff76db gpu_test_license
pyarmor obfuscate --plugin check_gpu --with-license licenses/gpu_test_license/license.lic --advanced 2 --exact test_gpu_check.py
```

The plugin code:

```
# check_gpu.py
import re
import subprocess
from pytransform import get_expired_days, get_user_data


def get_expiration_info():
    try:
        # license_info = get_license_info()
        left_days = get_expired_days()
        if left_days == -1:
            print('This license for %s is never expired')
        else:
            print(f'This license for will be expired in {left_days} days')
    except Exception as e:
        print(e)


def check_gpu():
    gpu_uuids = get_gpu_list()
    assert len(gpu_uuids) == 1  # 1 GPU per instance
    if gpu_uuids:
        if len(gpu_uuids) > 1:
            raise RuntimeError(f'This license is issued for one particular GPU, {len(gpu_uuids)} GPUs detected')
        else:
            assert len(gpu_uuids) == 1
            gpu_uuid = gpu_uuids[0]
            if gpu_uuid != get_user_data().decode('utf-8').lower():
                print(f'User data {get_user_data()}')
                raise RuntimeError('A GPU matching the license is not found')
            else:
                print('A GPU license check is passed')
                get_expiration_info()
    else:
        raise RuntimeError('No GPUs detected, this license is issued to particular GPU')


def get_gpu_list():
    try:
        out = subprocess.run(["nvidia-smi", "-L"], check=True, capture_output=True)
        out.check_returncode()
        out = out.stdout.decode('utf-8').lower()
        # output example
        # gpu 0: geforce gtx 1080 ti (uuid: gpu-70ef1701-4072-9722-cc0b-7c7e75ff76db)
        # gpu 1: geforce gtx 1080 ti (uuid: gpu-5b8df9cc-3b3c-d07a-8bd1-e2a51af4cfa9)
        # ...
        uuid_list = re.findall(r'\(uuid: \S+\)', out)
        uuid_list = [uuid.replace('(uuid: ', '').replace(')', '')
                     for uuid in uuid_list]
        return uuid_list
    except:
        # any error means no GPUs available
        return None

```

Also, am I doing something wrong, because:

- [get_user_data](https://pyarmor.readthedocs.io/en/latest/pytransform.html#get_user_data) should return a string, but it returns a binary I have to decode with `.decode('utf-8')`

- When I tried following this [example](https://github.com/dashingsoft/pyarmor/blob/master/plugins/check_docker.py), this [line ](https://github.com/dashingsoft/pyarmor/blob/master/plugins/check_docker.py#L2) gave me a `cannot import _pytransform from pytransform` error, which I fixed just by using `from pytransform import get_user_data`

?

Many thanks for your quick and concise replies.

**Comment by jondy** [comment]
Thanks. There is no GPU binding feature for pyarmor self.

`import _pytransform from pytransfrom` works only in non-super mode. For super mode, use extension `pytransform` directly.

Now in super mode `get_user_data` returns bytes object, so the users could full control of it. I'll note it in the document.

**Comment by snakers4** [comment]
Should I maybe create a PR to some doc / example page to show this plugin?

**Comment by jondy** [comment]
You can add the script to `/plugins/`, and describe it in `/plugins/README.md`

**Comment by snakers4** [comment]
Created the PRs (did it on the go thru web interface, have not found a way to do in one PR):

- https://github.com/dashingsoft/pyarmor/pull/475
- https://github.com/dashingsoft/pyarmor/pull/476

Please take a look

**Comment by jondy** [comment]
Thanks for your contribution, I have checked them and merged both of PRs.

**Comment by snakers4** [comment]
Thank you for `pyarmor`, it just works and is well-documented
Compared to local older companies (from windows software era) with huge licensing suites, 3 tiers of resellers and huge fees `pyarmor` is just a no-brainer
Keep up good work!
Hope my plugins and example will help people

**Comment by snakers4** [comment]
Probably globally the only lacking instrument is some kind of hardware token integration.

I.e. maybe someone has some instructions based on readily available hardware on how to make ROM hardware tokens (in my case I just used a GPU as "token", but this is a niche case). I.e. you can write a plugin to check a ROM token. The issue is that commercially available ROM tokens always have strings attached.

Maybe someone from the community you know can lend a hand. 

Maybe I am just over-complicating things, but in case of shipping packaged dockerized code I do not know how to reliably use hardware information, as disk / network are kind of virtual, and shipping a physical key is always more reliable.

**Comment by VeNoMouS** [comment]
I saw this... i hated how you were executing unknown binaries...

so i wrote this quickly , kinda harvested it from nvidia code tbh ... enjoy...

```python
#!/usr/bin/python3.7
import os
import sys
from ctypes import *

# ------------------------------------------------------------------------------- #

class NVIDIA():
    def __init__(self):
        self.nvml = None
        self.uuids = []
    
    # ------------------------------------------------------------------------------- #
    
    def loadLibrary(self):
        if (sys.platform[:3] == "win"):
            try:
                self.nvml = CDLL(os.path.join(os.getenv("WINDIR", "C:/Windows"), "System32/nvml.dll"))
            except OSError as e:
                self.nvml = CDLL(os.path.join(os.getenv("ProgramFiles", "C:/Program Files"), "NVIDIA Corporation/NVSMI/nvml.dll"))
        else:
            self.nvml = CDLL("libnvidia-ml.so.1")
    
    # ------------------------------------------------------------------------------- #
    
    def nvmlInitWithFlags(self, flags):
        fn = self.nvml.nvmlInitWithFlags
        ret = fn(flags)
    
    # ------------------------------------------------------------------------------- #
    
    def getDeviceCount(self):
        c_count = c_uint()
        fn = self.nvml.nvmlDeviceGetCount_v2
        ret = fn(byref(c_count))
        return c_count.value
    
    # ------------------------------------------------------------------------------- #

    def getHandleByIndex(self, index):
        class struct_c_nvmlDevice_t(Structure):
            pass
        
        c_index = c_uint(index)
        device = POINTER(struct_c_nvmlDevice_t)()
        fn = self.nvml.nvmlDeviceGetHandleByIndex_v2
        ret = fn(c_index, byref(device))
        return device

    # ------------------------------------------------------------------------------- #
    
    def getUUID(self, handle):
        c_uuid = create_string_buffer(96)
        fn = self.nvml.nvmlDeviceGetUUID
        ret = fn(handle, c_uuid, c_uint(96))
        return c_uuid.value.decode()
    
    # ------------------------------------------------------------------------------- #
    
    def getUUIDs(self):
        self.loadLibrary()
        self.nvmlInitWithFlags(0)
        deviceCount = self.getDeviceCount()
        
        for i in range(0, deviceCount):
            self.uuids.append(self.getUUID(self.getHandleByIndex(i)))
        
        return self.uuids
    
    # ------------------------------------------------------------------------------- #
    
print(NVIDIA().getUUIDs())

```

**Comment by snakers4** [comment]
> I saw this... i hated how you were executing unknown binaries...

This looks nice, have you extracted it from some tool shipped by Nvidia? It works in my environment out of the box

I am not very acquainted with how to properly use C binaries in python and therefore I just used their standard tool
Whenever you have some GPU-accelerated workload, you have GPU drivers, and `nvidia-smi` is just a standard tool provided by Nvidia

**Comment by freeenergylab** [comment]
Hey there, I am using Pyarmor 8.2.9 (pro) version. What will I do if I want to bind to some specific GPU cards as above operation? As we know, Pyarmor 8.0+ did not have the pyarmor licenses & pyarmor obfuscate commands.

**Comment by jondy** [comment]
@freeenergylab

Pyarmor 8.0 also provides same feature, but use `runtime hook script` and built in function `__pyarmor__`

Refer to 
https://pyarmor.readthedocs.io/en/stable/reference/environments.html#hooks

About Pyarmor 8.0 usage, please refer to
https://pyarmor.readthedocs.io/

**Comment by freeenergylab** [comment]
@jondy Could you show the usage on binding to GPU cards during obfuscating my python package repo? Thanks!

**Comment by freeenergylab** [comment]
I can bind to one internet card as:
`pyarmor gen --platform linux.x86_64 -b "3c:ec:ef:28:61:32" ./my_package_repo
`
