### ISSUE TITLE
How to use cx_Freeze with PyArmor

### ISSUE THREAD

**Issue by Hunter2807** [dashingsoft/pyarmor#478]
Hi!! 

I was looking forward to obfuscate my Python code with PyArmor, and I wanted to know, what's the procedure if I wanna use cx_Freeze to freeze the obfuscated code to an exe, so that i can distribute it to other people...

**Comment by jondy** [comment]
It should work. Actually the old version Pyarmor supports cx_Freeze with command `pack`, but this feature is dropped in latest version. Please refer to section `Work with cx_Freeze 5` in this guide
https://pyarmor.readthedocs.io/en/v5.0.1/pack-obfuscated-scripts.html#how-to-pack-obfuscated-scripts

**Comment by Hunter2807** [comment]
oh, thanks for the help!! I will see that right now!
