### ISSUE TITLE
Can't run a executable file

### ISSUE THREAD

**Issue by Quessts** [dashingsoft/pyarmor#479]
It's more readable in the issue Preview mode for the hints

**Hints**
Every pyarmor command prints detail logs in the console, not only check the last error message, but also check each log to understand what pyarmor is doing. And `pyarmor -d subcommand ...` even prints more debug logs, it's very useful to find the problem.

When running the obfuscated scripts, if there is traceback, check the source script according to script name and line number in the traceback, make sure it doesn't use some features changed by pyarmor 

Before report a bug, please read these common questions and solutions first
https://pyarmor.readthedocs.io/en/latest/questions.html

And remove all the above hints.

**Describe the bug**
After running pyarmor I get an error stating
```
ImportError
[3468] Failed to execute script test
```

**To Reproduce**
Which pyarmor version is used, trial or purchased, and steps to reproduce the behavior: **Purchased**
1. Obfuscate the scripts by which Python version and in which platform: Windows using Python 3.7.9
2. What command options used: ```pyarmor pack -e " --onefile" test.py```
3. How to distribute the obfuscated scripts to target machine if it's different from build machine: I'm using the same PC
4. Run the obfuscated scripts in which platform by which Python version: 3.7.9
5. When see error, provide the full traceback and console output by text not snapshot, quote them like this

```
Traceback (most recent call last):
  File "<dist\obf\test.py>", line 3, in <module>
  File "<frozen test>", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "pynput\__init__.py", line 40, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "pynput\keyboard\__init__.py", line 31, in <module>
  File "pynput\_util\__init__.py", line 82, in backend
ImportError
[3468] Failed to execute script test... 
```

**Additional context**
The obfuscation system does in fact work but if I run the exe. I get the error I stated above. I used this command to obfuscate it: ```pyarmor pack -e " --onefile" test.py```. My code works if I run it without obfuscating it but it breaks after I do. Other scripts work perfectly but this one doesn't.

**Comment by jondy** [comment]
I'm sure it's not Pyarmor's defect, and there is solution in the **Hints**. I suppose you don't read the hints carefully, because this hint is ignored:

> Before report a bug, please read these common questions and solutions first
https://pyarmor.readthedocs.io/en/latest/questions.html
And remove all the above hints.

**Comment by Quessts** [comment]
Oh. do you know if it has anything to do with sockets? Since I'm using the sockets module does pyarmror somehow interfere with sending and receiving items through sockets?

**Comment by VeNoMouS** [comment]
a simgple google search showed https://stackoverflow.com/questions/63681770/getting-error-when-using-pynput-with-pyinstaller

**Comment by VeNoMouS** [comment]
and github issue tickets of https://github.com/moses-palmer/pynput/issues/312

**Comment by Quessts** [comment]
Apparently, the issue was from pynupt. I fixed it by using the following commands:
```
pip uninstall pynput
```
Then
```
pip install pynput==1.6.8
```
