### ISSUE TITLE
Pyarmor obfuscated code not able to identify alias name [Part 2]

### ISSUE THREAD

**Issue by mayank564** [dashingsoft/pyarmor#480]
**Alias name issue in cherry py**
This bug is an extension of https://github.com/dashingsoft/pyarmor/issues/466

As you suggested me i have tried the new Pyarmor version 6.6.2 (Released on March 1st), but the issue still exists.

If we call API with alias name  it throws me 404 Error and the API's which do not have any alias name works perfectly.

Any suggestion how to move forward without tweaking the cherrypy code as it is a third party module not written by our team.

Thanks in Advance

**Comment by jondy** [comment]
I have explained it in the #466

Please check the technical support items in [PyArmor's EULA](https://pyarmor.readthedocs.io/en/latest/license.html#technical-support), this issue belongs to known issues, because the obfuscated script uses the feature changed by Pyarmor.

If you provides the simple snapshot code around exception when calling the alias api, I can analysis them to find where it may conflict with pyarmor.

My suggestion is also report an issue to the team of package `cherrypy`

**Comment by mayank564** [comment]
Thanks for the reply @jondy  i willp put the snapshot of the code where it throws exception.

**Comment by mayank564** [comment]
Hi jondy,

Below is the code block of decorator  expose() which cherrypy uses to set the alias name.

```
def expose(func=None, alias=None):
    """Expose the function or class.

    Optionally provide an alias or set of aliases.
    """
    def expose_(func):
        func.exposed = True
        if alias is not None:
            if isinstance(alias, text_or_bytes):
                parents[alias.replace('.', '_')] = func
            else:
                for a in alias:
                    parents[a.replace('.', '_')] = func
        return func

    import sys
    import types
    decoratable_types = types.FunctionType, types.MethodType, type,
    if isinstance(func, decoratable_types):
        if alias is None:
            # @expose
            func.exposed = True
            return func
        else:
            # func = expose(func, alias)
            parents = sys._getframe(1).f_locals
            return expose_(func)
    elif func is None:
        if alias is None:
            # @expose()
            parents = sys._getframe(1).f_locals
            return expose_
        else:
            # @expose(alias="alias") or
            # @expose(alias=["alias1", "alias2"])
            parents = sys._getframe(1).f_locals
            return expose_
    else:
        # @expose("alias") or
        # @expose(["alias1", "alias2"])
        parents = sys._getframe(1).f_locals
        alias = func
        return expose_


```

**Comment by jondy** [comment]
In obfuscated scripts, if `expose` is patched by this way: 
```patch
- parents = sys._getframe(1).f_locals
+ parents = sys._getframe(2).f_locals
```

The following example works:
```python
# This is foo.py

# This is patched expose
def expose()
    ...

@expose(alias='hello_a')
def hello():
    print('Test cherrypy alias api')
```

```
# This is main.py
import foo
foo.hello_a()

from foo import hello_a
hello_a()
```

Obfuscate them by this way:
```
pyarmor obfuscate --advanced 2 --exact main.py foo.py
cd dist/
python main.py 
```

**Comment by jondy** [comment]
The solution I suggest is patching `expose`.

It also works for non super mode.

**Comment by mayank564** [comment]
Thnaks for the suggestion i will try out the solution and provide the feedback
