### ISSUE TITLE
python site package include

### ISSUE THREAD

**Issue by HenryKang1** [dashingsoft/pyarmor#481]
Hello. I am trying to add some code in the python system  site-packages.
The problem is that in the site packages pytransform folder can not  recognize.
Which is called no module name pytransform.

So I am trying to add the path like belwo  
import sys
sys.path.append("/opt/tljh/user/lib/python3.7/site-packages/sddnet_e/pytransform/")
 In this cases, pyarmor can not read the above code so it shows the error.
Does anyone has soluton for this situation?

**Comment by jondy** [comment]
Please refer to
https://pyarmor.readthedocs.io/en/latest/questions.html

Especially the section
https://pyarmor.readthedocs.io/en/latest/questions.html#python-import-system

**Comment by HenryKang1** [comment]
Actually I have already read your document and that is not working.
This is the site-package issue and only worked soulution was the sys.path.append.
However I can not add the extra code line in the obfuscated code.
I have also checked the python import system documentation. They do not give any solution for this. 
So I just make read only folder and connect this to my server. I am not sure you can understand my question.

**Comment by jondy** [comment]
Check  command `obfuscate` in the man page, understand the usage of option `--restrict`
