### ISSUE TITLE
issue with building wheel with obfuscated code

### ISSUE THREAD

**Issue by hwchase17** [dashingsoft/pyarmor#482]
**Describe the bug**
After obfuscating my package code (following steps https://pyarmor.readthedocs.io/en/latest/advanced.html#distributing-obfuscated-package-with-pip) I am unable to bundle into a wheel.

**To Reproduce**
Which pyarmor version is used, trial or purchased, and steps to reproduce the behavior:
1. Obfuscate the scripts by which Python version and in which platform: pyamor 6.6.2, python 3.7.6, MacOS
2. What command options used

After following all the commands at https://pyarmor.readthedocs.io/en/latest/advanced.html#distributing-obfuscated-package-with-pip (substituting mylib with `testing_pkg`, my package's name) I ran `python setup.py bdist_wheel`

3. How to distribute the obfuscated scripts to target machine if it's different from build machine
4. Run the obfuscated scripts in which platform by which Python version
5. When see error, provide the full traceback and console output by text not snapshot, quote them like this

```
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/testing_pkg
copying dist/__init__.py -> build/lib/testing_pkg
copying dist/helper.py -> build/lib/testing_pkg
installing to build/bdist.macosx-10.14-x86_64/wheel
running install
running install_lib
creating build/bdist.macosx-10.14-x86_64
creating build/bdist.macosx-10.14-x86_64/wheel
creating build/bdist.macosx-10.14-x86_64/wheel/testing_pkg
copying build/lib/testing_pkg/__init__.py -> build/bdist.macosx-10.14-x86_64/wheel/testing_pkg
copying build/lib/testing_pkg/helper.py -> build/bdist.macosx-10.14-x86_64/wheel/testing_pkg
running install_data
creating build/bdist.macosx-10.14-x86_64/wheel/testing_pkg-0.0.1.data
creating build/bdist.macosx-10.14-x86_64/wheel/testing_pkg-0.0.1.data/data
creating build/bdist.macosx-10.14-x86_64/wheel/testing_pkg-0.0.1.data/data/pytransform_vax
error: can't copy 'd': doesn't exist or not a regular file
```

**Additional context**
I am not using license - is license needed for this?

**Comment by jondy** [comment]
It's not related to license.

First make sure the obfuscated scripts work. If it works, it's not issue of pyarmor. The obfuscated scripts are normal python scripts, please refer to Python official document to understand how to build wheel.

The example in the document just show the idea how to build wheel, you must write you own `setup.py` according to your package.
