### ISSUE TITLE
Binary file not able to detect `_pytransform.dll` file

### ISSUE THREAD

**Issue by spr732** [dashingsoft/pyarmor#485]
I have built my project using pyinstaller and got binary file  `app.exe`.
when I try to execute that binary file from cmd line It gives me below error.
```
C:\codebase\project\app>dist\app\app.exe --launch
Traceback (most recent call last):
  File "<__main__.py>", line 3, in <module>
  File "<frozen app.lib.__main__>", line 394, in <module>
  File "<frozen app.lib.__main__>", line 389, in protect_pytransform
  File "<frozen app.lib.__main__>", line 372, in check_lib_pytransform
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\codebase\\project\\app\\dist\\app\\_pytransform.dll'
[24392] Failed to execute script __main__
```

But obfuscated scripts work perfectly in my PyCharm ide.

Here is the directory structure of dist -
```
...
app.exe
some/project/package
pytransform
*.dll
*.pyc
...
```

Should not it detect `_pytransform.dll` file from `pytransform` directory?

**Comment by jondy** [comment]
> Should not it detect _pytransform.dll file from pytransform directory?

It depends on the value of option `--package-runtime`, please refer to command `obfuscate` and `pack` in the man page, understand what it does.
https://pyarmor.readthedocs.io/en/latest/man.html#obfuscate

**Comment by spr732** [comment]
Thanks Jondy, I understood the option and able to fix my issue.
