### ISSUE TITLE
Illegal operations on a Raspberry Pi CM1 (ARMv6L)

### ISSUE THREAD

**Issue by zuxian97** [dashingsoft/pyarmor#486]
**Describe the bug**
Using a Raspberry Pi CM1 (armv6l) most commands will fail with "Illegal instruction" and terminate.

**To Reproduce**
1. Running latest pyarmor from pip using the trial version on a Raspberry Pi running Raspbian 8 (jessie) and python 2.7.9
2. Commands used obfuscate, pack, download, hdinfo and -v
```
uname -a
Linux 3DCounter 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux

pyarmor -d obfuscate main.py
DEBUG    PyArmor installation path: /usr/local/lib/python2.7/dist-packages/pyarmor
DEBUG    PyArmor home path: /home/pi/.pyarmor
DEBUG    Native platform is linux.armv6
DEBUG    Search dynamic library in the path: /usr/local/lib/python2.7/dist-packages/pyarmor/platforms
DEBUG    Search dynamic library in the path: /home/pi/.pyarmor/platforms
DEBUG    Found available dynamic library linux/armv6/3
Illegal instruction

```

**Comment by jondy** [comment]
The current solution is `linux.armv6.0`, duplicated issue of #483

Could you download this test app and run it in Pi?
https://pyarmor.dashingsoft.com/downloads/temp/foo-thumb-mode

If it crashes,  could you generate core dump file and upload it here?
https://tmpfiles.org

**Comment by zuxian97** [comment]
Confirmed the fix by replacing file at /home/pi/.pyarmor/platforms/linux/armv6/3/_pytransform.so with the one from https://github.com/dashingsoft/pyarmor-core/tree/r41.15/platforms/linux.armv6.0. Looking forward to an update soon. Thanks.
