### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by claudiuvintila** [dashingsoft/pyarmor#487]
It's more readable in the issue Preview mode for the hints

**Hints**
Every pyarmor command prints detail logs in the console, not only check the last error message, but also check each log to understand what pyarmor is doing. And `pyarmor -d subcommand ...` even prints more debug logs, it's very useful to find the problem.

When running the obfuscated scripts, if there is traceback, check the source script according to script name and line number in the traceback, make sure it doesn't use some features changed by pyarmor 

Before report a bug, please read these common questions and solutions first
https://pyarmor.readthedocs.io/en/latest/questions.html

And remove all the above hints.

**Describe the bug**
pyarmor obfuscate --exact /src/pre_start.py --output /dest
INFO     Clean volatile license file: /usr/local/lib/python3.7/site-packages/pyarmor/license.lic
ERROR    [Errno 16] Device or resource busy: '/usr/local/lib/python3.7/site-packages/pyarmor/license.lic'

**To Reproduce**
I use purchased pyarmor inside a docker image. I used python 3.6 with pyarmor 5.2.3 and worked fine. Now we use 3.7 with pyarmor 6.6.2 but get the above error.
I can print the license with cat in terminal so the path and file are ok.
I am trying to add another entry point to my code using --exact.

```
pyarmor obfuscate foo.py
... 
```

**Additional context**

**Comment by jondy** [comment]
The new license is required to run the latest version, if the old license is purchased after 2017-10-10, please send order information and registration email to me(jondy.zhao@gmail.com), I'll send new license file to registration email. If it's purchased before 2017-10-10, it doesn’t support to upgrade the latest version.

Refer to
https://pyarmor.readthedocs.io/en/latest/license.html#upgrade-notes

**Comment by chugunovyar** [comment]
`INFO     Set pyarmor home path: /code
INFO     Copy home license /code/license.lic
INFO     As volatile license to /opt/python3.8/lib/python3.8/site-packages/pyarmor
Traceback (most recent call last):
  File "/opt/python3.8/bin/pyarmor", line 8, in <module>
    sys.exit(main_entry())
  File "/opt/python3.8/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1612, in main_entry
    main(sys.argv[1:])
  File "/opt/python3.8/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1587, in main
    _set_volatile_home(args.home)
  File "/opt/python3.8/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1560, in _set_volatile_home
    shutil.copy(licfile, PYARMOR_PATH)
  File "/opt/python3.8/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/python3.8/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/opt/python3.8/lib/python3.8/site-packages/pyarmor/license.lic'
`

Problem still exist in  pyarmor==7.7.4 pyinstaller==5.8.0
