### ISSUE TITLE
Incompatible: playwright and pyarmor

### ISSUE THREAD

**Issue by Ocayy** [dashingsoft/pyarmor#488]
I have tried compiling some python scripts using pyarmor in which I am using Playwright.

Everything went well, but after compiling I get an error:
```
================================================= ===============================
"firefox" browser was not found.
Please complete Playwright installation via running

     "python -m playwright install"

================================================== ==============================
, retrying ... 
```
which mean that something is wrong with package (I've tried compiling it with --add-data and added manually whole package and still nothing)

### Packing commands i've tried:
```
pyarmor pack -x " --advanced 2 --bootstrap 2 --enable-suffix " -e "--icon logo.ico  -c --onefile" cli.py
```
```
pyarmor pack -x " --advanced 2 --bootstrap 2 --enable-suffix " -e "--icon logo.ico  -c --onefile --hidden-import playwright" cli.py
```
```
pyarmor pack -x " --advanced 2 --bootstrap 2 --enable-suffix " -e "--icon logo.ico  --add-data 'playwright;playwright' -c --onefile --hidden-import playwright" cli.py
```

Could you help me with it and explain what I'm doing wrong?

### Context information
- version of python: 3.8.6
- version of playwright-python:  1.9.2
- version of pyarmor: 6.6.2
- platform: Windows 10

**Comment by jondy** [comment]
It's not related to Pyarmor, but Pyinstaller. I don't handle the issue of PyInstaller, please first pack your original scripts by PyInstaller directly and make sure the final bundle works.
Refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#pyinstaller
