### ISSUE TITLE
[Question] Multiple pytransforms when using subdirs and manual restrict levels

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#491]
Hi @jondy,

Question for you,

When using manual restrict modes... how do you limit the number of pytransform's being created when using sub directories... 

If the directory is flat... that's fine , as it only generates one pytransform..

but when you start introducing sub directories into the mix it generates multiple pytransform libraries, one for each directory...

is there some way this can be addressed, so it only uses one pytransform library for the whole tree?

Hopefully I'm making myself clear..?

**Comment by jondy** [comment]
The obfuscated scripts can be taken as normal python scripts, and `pytransform` is a normal extension. If there are many pytransforms, the obfuscated scripts will import the corresponding pytransform according to Python Import System.

**Comment by VeNoMouS** [comment]
I get that.. but why would we need 5+ pytransforms... if we have 5 subdirs... etc..

can't we just have 1 pytransform? why increase the dist package size if we dont need to?

**Comment by jondy** [comment]
Please check the usage of command `runtime` in the man page.

**Comment by VeNoMouS** [comment]
aaah... rgr rgr, will give it a try , i personally dont have the issue, once my users does, but i'll test it out and come back to you

thanks as always 

<3
