### ISSUE TITLE
Trying to use --add-data argument from pyinstaller

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [dashingsoft/pyarmor#492]
Hi, i am trying to use the --add-data argument from pyinstaller while packing the exe, but it doesnt works.

`C:\Python27>pyarmor pack -e "--onefile --noconsole --add-data "sample.pdf"" compiled\foo.py`

this is the command which i am using to compile the code

**Comment by jondy** [comment]
It's not related to pyarmor, please refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#pyinstaller
