### ISSUE TITLE
OSError: could not get source code

### ISSUE THREAD

**Issue by eric-et** [dashingsoft/pyarmor#493]
![image](https://user-images.githubusercontent.com/48991139/114269571-8714cc80-9a3a-11eb-8d3b-869d9effffc3.png)

after pyarmored a project based on flask, when staring, it gives error as shown above. I googled, some say the error is because I am using importlib to dynamically import modules and attributes of them. Indeed I did this in my code but it not around lines in the trackback.

What shall I do?

update:
tried with minimum obf, the result was the same. attach with the pyarmor config:

{
  "cross_protection": 1,
  "build_time": 1588510101.021556,
  "obf_code": 0,
  "plugins": null,
  "advanced_mode": 0,
  "title": "avms_dist",
  "bootstrap_code": 1,
  "platform": null,
  "version": "2.0",
  "obf_mod": 0,
  "package_runtime": 1,
  "runtime_path": null,
  "restrict_mode": 1,
  "entry": "run.py, manage.py, __init__.py, app/__init__.py",
  "src": "../",
  "wrap_mode": 1,
  "name": "avms_dist",
  "manifest": "global-include *.py, prune dist, prune test, prune examples, prune .git",
  "is_package": null,
  "enable_suffix": 0,
  "output": ".",
  "license_file": null
}

**Comment by jondy** [comment]
模块 inspect 和其他任何第三方包如果试图访问加密脚本的 Byte Code 或者直接访 问代码对象的某些属性，也会崩溃，失败或者得到错误的数据

**Comment by eric-et** [comment]
请问有解决方案吗？降低加密程度？这个inspect应该是flask项目内的，加密这类型的项目需求应该非常常见。

**Comment by jondy** [comment]
这个解决方案和具体的第三方包有关，只要不使用加密脚本修改过的这些特性就可以，具体如何配置需要你自己去设置，我对第三方的包也不熟悉，另外，pyarmor 有好多用户都是用 flask 的，也没有报过类似问题。

**Comment by jondy** [comment]
使用选项 `--obf-code 0` 降低加密程度，`inspect` 模块可以访问 Code Object, 例如
```
pyarmor obfuscate --obf-code 0 foo.py
```
具体使用方法请参考文档中 man page 以及加密模式
