### ISSUE TITLE
How secure is PyArmor?

### ISSUE THREAD

**Issue by fieu** [dashingsoft/pyarmor#494]
I have been a PyArmor user for quite a while, though I was wondering how secure it is.

I was reading and found a thread on SpigotMC: https://www.spigotmc.org/threads/spigot-plugin-obfuscation-external-software-downloads-what-is-allowed-what-not.458236/page-2#post-3921834

One person says it's as simple as editing one function to dump code objects to a file: https://github.com/python/cpython/blob/3.8/Python/ceval.c#L745

Is this true, or can I use a special PyArmor mode to make sure this isn't an issue?

**Comment by jondy** [comment]
Obfuscating the scripts by super mode,  it will not be an issue.

**Comment by fieu** [comment]
Alright, thanks!
