### ISSUE TITLE
SystemError: unknown opcode (228)

### ISSUE THREAD

**Issue by RobinFrcd** [dashingsoft/pyarmor#495]
**Describe the bug**
I've been using PyArmor for a while now, thanks for the hard work!

I've updated from `6.4.4` to `6.6.2` recently, and I now face a `unknown opcode` issue (`XXX lineno: 4, opcode: 228`).

I'm running this to obfuscate my code:
```bash
pyarmor obfuscate --advanced 1 --restrict 0 --recursive --platform linux.x86_64 --platform darwin.x86_64
```

On the machine where I run PyArmor I have
```
Python 3.7.9 (default, Nov 15 2020, 21:16:15) 
[GCC 10.2.0] on linux
```

And on the one where I run the code:
```
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
```

Did I miss something with the latest release ? Everything still works fine if I downgrade to 6.4.4

**Comment by jondy** [comment]
I suggest you use super mode `--advanced 2` to obfuscate the scripts.

**Comment by RobinFrcd** [comment]
Alright I gave it a try but not when I try to import the obfuscated package I get:

```
    from pytransform import pyarmor
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

I have `pytransform.cpython-37m-x86_64-linux-gnu.so` available in my path.

**Comment by jondy** [comment]
First search `libpython3.7m.so*` in your virtual python path, if there is one file, make sure it's in the LIBRARY_PATH.
If not, then this python is built with static python library, so there is no python dynamic library. You need build the virtual python with `--enable-shared`

**Comment by RobinFrcd** [comment]
Alright,
So if I create a new virtualenv with `PYTHON_CONFIGURE_OPTS="--enable-shared"` and I run PyArmor in this env with `--advanced 2` everything works like a charm, thank you very much!
