### ISSUE TITLE
"name '__file__' is not defined" when using with PyOxidizer

### ISSUE THREAD

**Issue by Thoufak** [dashingsoft/pyarmor#496]
Hi there!

I've been trying to use PyArmor along with [PyOxidizer](https://github.com/indygreg/PyOxidizer) – a tool for creating an .exe out of python scripts (similar to PyInstaller). My pyarmored script works correctly if not packed into exe. Likewise, an exe made out of a plain pyhton script (without PyArmor) works fine. However, if I combine them, I get the following output on launching the exe: "name '\_\_file\_\_' is not defined". How can I debug/solve the issue?

### Details
- Python: 3.9
- PyArmor: 6.6.2
- PyArmor command: 'pyarmor o path/my_package/__init__.py'
- PyArmor command output:
[pyarmor_console_output.txt](https://github.com/dashingsoft/pyarmor/files/6302028/pyarmor_console_output.txt)

### Files
- Input files for PyArmor:
[into_pyarmor.zip](https://github.com/dashingsoft/pyarmor/files/6301998/into_pyarmor.zip)

- Output files from PyArmor (hence, input files for PyOxidizer):
[main_pkg.zip](https://github.com/dashingsoft/pyarmor/files/6302016/main_pkg.zip)

- The exe result:
[pyapp_armored.exe.zip](https://github.com/dashingsoft/pyarmor/files/6302024/pyapp_armored.exe.zip)

**Comment by jondy** [comment]
First make sure PyOxidizer could handle `__file__`, just create a simple `foo.py`
```python
print('File is %s' % __file)
```
Then generate an exe by PyOxidizer, check it works or not.

**Comment by Thoufak** [comment]
@jondy, PyOxidizer indeed doesn't work with scripts that rely of __file__ at all. Is there a workaround?

**Comment by jondy** [comment]
One solution is checking the man page of PyOxidizer, maybe some option could take `__file__` (built in variables) work.

If there is no any option work, 

First obfuscate scripts with `--restrict 0`, for example
```
pyarmor obfuscate --restrict 0 foo.py
```
Then replace `__file__` with `__name__` for all the obfuscate scripts.
Finally build it with PyOxidizer

**Comment by Thoufak** [comment]
Thank you.
