### ISSUE TITLE
Some keys are not being supported. ex.("ç", "ã", "é")

### ISSUE THREAD

**Issue by kamikazaliba01** [dashingsoft/pyarmor#499]
main.py
`print('test ç e é ~ e ã')`

obifuscating
`pyarmor pack --clean -e "--onefile " main.py`

output main.exe:
`test Ã§ e Ã© ~ e Ã£`

**Comment by jondy** [comment]
Refer to https://pyarmor.readthedocs.io/en/latest/questions.html#source-code-encoding
