### ISSUE TITLE
Check --expired license date on the internet.

### ISSUE THREAD

**Issue by tomaso909** [dashingsoft/pyarmor#50]
I think that the --expired license currently checks the date locally.

Would it be possible to check it over the internet instead?

**Comment by jondy** [comment]
PyArmor self does not check expired date over the internet, but it can be checked in python script. That is to say, add the extra code to check the internet date in the main script by Python. All the python scripts will be obfuscated before distributing to end user, so the end user can't change the obfuscated script any more.

**Comment by tomaso909** [comment]
That works for me. Thanks.

**Comment by mfeyzitas** [comment]
So user can use application after expiry date by simply changing local date on settings(It works). If so is there any meaning of using it without modifying?

**Comment by jondy** [comment]
This feature may be used by some server applications, for example, a django application runs on a cloud server.  In PyArmor the obfuscated scripts is designed to run even without internet connection, so it doesn't check internet time. But it's convince to extend license type by plugin, PyArmor let end users decide how to do that. Here is a sample plugin to check internet time
https://pyarmor.readthedocs.io/en/latest/advanced.html#using-plugin-to-extend-license-type
