### ISSUE TITLE
Intel MKL Fatal Error

### ISSUE THREAD

**Issue by danielhormigoruiz** [dashingsoft/pyarmor#500]
Hi! 

I have just begun to use PyArmor and I am getting the following error when trying to build up an application:

INTEL MKL ERROR: dlopen(/Users/danielhormigoruiz/Desktop/test_pyarmor/expai_test/app/libmkl_intel_thread.dylib, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/danielhormigoruiz/Desktop/test_pyarmor/expai_test/app/libmkl_intel_thread.dylib
  Reason: image not found.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.

My environment is as follows:

- python=3.6.12

altair==4.1.0
argon2-cffi==19.1.0
astor==0.8.1
backports.functools-lru-cache==1.6.1
bcrypt==3.2.0
brotlipy==0.7.0
build==0.3.0
cloudpickle==1.6.0
coverage==5.4
cython==0.29.22
cytoolz==0.11.0
dalex==1.0.1
dask==2021.1.1
expai==1.3.7.5
ez-setup==0.9
fairlearn==0.6.0
fairsearchcore==1.0.4
firebase-admin==4.5.3
flask-jwt-extended==3.25.0
flask-login==0.5.0
flask-sqlalchemy==2.4.4
imgkit==1.0.2
jupyter==1.0.0
jupyterlab==3.0.7
lime==0.2.0.1
marshmallow-sqlalchemy==0.24.1
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
mpld3==0.5.2
mysqlclient==2.0.3
olefile==0.46
passlib==1.7.4
pip-chill==1.0.1
py2app==0.23
pyarmor-webui==1.2.9
pyinstaller==4.3
pyopenssl==20.0.1
pysocks==1.7.1
raiwidgets==0.3.1.post1
seaborn==0.11.1
shap==0.37.0
simplejson==3.17.2
sourcedefender==6.0.50
tensorflow==2.4.1
torch==1.7.1
twine==3.3.0
vega-datasets==0.9.0
webkit2png==0.8.2
wkhtmltopdf==0.2
xgboost==1.3.0

**Comment by jondy** [comment]
`libiomp5.dylib` should be system library, it seems something is missed in this platform, please try to google `missing libiomap5.dylib` to find the solution.
