### ISSUE TITLE
Deobfuscating pyarmor code is possible, all protection methods not working with open source?

### ISSUE THREAD

**Issue by mexriddin-x** [dashingsoft/pyarmor#501]
### Greetings. 
I found this while searching how much pyarmor can protect code:
[Deobfuscating pyArmor code](https://forum.tuts4you.com/topic/41945-python-pyarmor-my-protector/?tab=comments#comment-203008)

### In short:
> 4. pyarmor encrypts the code objects on disk and they are only decrypted at runtime just before they are executed. The entire logic is implemented in _pytransform.dll. There are anti-debugging/timing checks to prevent us from using a debugger to dump code objects from memory. But there's no need to use a debugger at all when CPython itself is open source. :)

> 5. Compile Python 3.7 from source. Modify the _PyEval_EvalFrameDefault function such that it dumps the code object to disk. By doing so we do not need to bother about all the anti-debugging and encrypted stuff. This is because pyarmor decrypts the code object in memory before it hands it to the Python VM for execution

* Please check it and give answer, method they are talking about is really working?
* Than all the protection of pyarmor is nothing against that method?

**Comment by jondy** [comment]
duplicated of #494

**Comment by mexriddin-x** [comment]
thanks
