### ISSUE TITLE
Can't obfuscate in advanced or super mode

### ISSUE THREAD

**Issue by mexriddin-x** [dashingsoft/pyarmor#502]
### Can't obfuscate in *advanced* or *super* *mode* in trial version. 
> ### Need to buy licensed version?

**Comment by jondy** [comment]
The trial version can't obfuscate the big scripts, the license is required for big scripts. Refer to
https://pyarmor.readthedocs.io/en/latest/license.html

**Comment by mexriddin-x** [comment]
It's mean, if i turn on advanced or super mode the script which 8 kilobyts, the resulting code will be bigger than the limitation of trial version?

**Comment by jondy** [comment]
For super mode, the limitation of trial version is no more than 32 functions (code objects) in one script.
