### ISSUE TITLE
Insecure Protection

### ISSUE THREAD

**Issue by michaelschon** [dashingsoft/pyarmor#505]
One of the reasons that caught my attention was the fact that I could put an expiration by date, Hard Disk Serial or MAC Address.
Initially I would like to propose an option for the BIOS version, because my Hard Disk is of the NVME (M2) type and pyarmor is unable to collect the serial from it.
I found a security breach. I obfuscated code in python with no expiration and another code with expiration date and Mac Address.
Both worked as they should, however, if I take the contents of the "pytransform" directory from the directory where there is no license type and copy to the other code where there is a license to use it works without validating the date and Mac Address restrictions.
I believe that there must be some kind of tie in the obfuscated code that only works with your "pytransform", preventing me from replacing it and the code working again with the original restrictions.

Look about serial number issue:

$ pyarmor hdinfo
INFO     PyArmor Trial Version 6.7.0

Hardware informations got by PyArmor:

Failed to get harddisk information.

Default Mac address: "98:fa:9b:dd:d9:f2"

Multiple Mac addresses: "<98:fa:9b:dd:d9:f2,76:14:78:0d:39:1c>"

Ip address: "192.168.15.6"

Domain name: "(none)"

Change logs

        v6.2.0(r21): Remove trailing dot from harddisk serial number
        v6.4.2(r34): Support binding multiple mac addresses
        v6.5.3(r37): Support binding named harddisk

$ sudo smartctl -i /dev/nvme0
smartctl 7.2 2021-01-17 r5171 [x86_64-linux-5.11.17-200.fc33.x86_64] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       Force MP510
Serial Number:                      19448238000128884907
Firmware Version:                   ECFM22.5
PCI Vendor/Subsystem ID:            0x1987
IEEE OUI Identifier:                0x6479a7
Total NVM Capacity:                 960.197.124.096 [960 GB]
Unallocated NVM Capacity:           0
Controller ID:                      1
NVMe Version:                       1.3
Number of Namespaces:               1
Namespace 1 Size/Capacity:          960.197.124.096 [960 GB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            6479a7 29c2743037
Local Time is:                      Sat May  8 12:29:20 2021 -03

**Comment by jondy** [comment]
> Both worked as they should, however, if I take the contents of the "pytransform" directory from the directory where there is no license type and copy to the other code where there is a license to use it works without validating the date and Mac Address restrictions.
I believe that there must be some kind of tie in the obfuscated code that only works with your "pytransform", preventing me from replacing it and the code working again with the original restrictions.

This is the expected behavior of pyarmor. If you would like to protect different product, the best way is using another PyArmor license.

> Look about serial number issue:

Now pyarmor may not support all of nvme harddisk, in this case, use plugin to extend the license by yourself, refer to
https://github.com/dashingsoft/pyarmor/tree/master/plugins
