### ISSUE TITLE
[需求]pyarmor提供能指定glibc库路径的版本

### ISSUE THREAD

**Issue by jerrylee9** [dashingsoft/pyarmor#507]
运行环境由于遗留问题，glibc的库版本比较复杂。系统默认路径下的glibc版本与其他产品的运行有关，没办法随便升级。

pyarmor能否提供一种命令，让用户可以指定其运行时依赖的glibc库的路径？比如pyarmor可以访问自定义路径下的glibc库，这样就不会与系统自带的glibc库强相关。

PS：pyarmor除了glibc，还有其他依赖的底层库吗？

```
需求：
python版本：python 2.7
操作系统：目前所支持的全部系统
```

谢谢！如果您开发完成了这个需求，可以通过邮件与我联系。

**Comment by PrettyJerry** [comment]
我也遇到差不多同样的问题，建议作者改为静态链接glib库的方式，避免与部署环境glibc版本产生冲突和依赖。

**Comment by jondy** [comment]
pyarmor 唯一的依赖的动态库 glibc， 指定使用的那一个版本的 glibc 需要操作系统的支持，不是 pyarmor 可以提供的功能。例如 linux 下面可以使用环境变量 LD_LIBRARY 指定库装载的路径，或者其他相应的方法，请通过搜索引擎查找一下解决方案。

> 建议作者改为静态链接glib库的方式，避免与部署环境glibc版本产生冲突和依赖。

glibc 还有其他一些依赖库，如果静态链接，需要把所有的依赖库都链接进来，如果文件不会变的太大，以后会考虑使用静态链接的方式。

**Comment by jerrylee9** [comment]
可否提供较完整的pyarmor依赖的系统库列表。

**Comment by jondy** [comment]
> 可否提供较完整的pyarmor依赖的系统库列表。

pyarmor 只依赖于 glibc，但是 glibc 依赖那些动态库和具体的系统有关系。

**Comment by jondy** [comment]
在 Linux 系统，目前已知的有 centos 6 的 glibc 版本太低，如果是 x86_64 的 cpu，可以直接使用 `--platform centos6.x86_64` 进行加密，对于其他 cpu 框架，可以参考这里的方法对动态库打补丁
https://pyarmor.readthedocs.io/en/latest/questions.html#lib64-libc-so-6-version-glibc-2-14-not-found

**Comment by jondy** [comment]
> 我也遇到差不多同样的问题，建议作者改为静态链接glib库的方式，避免与部署环境glibc版本产生冲突和依赖。

如果静态链接 glibc 库的话，那么生成的动态库将和依赖于编译环境的 linux 内核版本。如果目标环境的 linux 内核和编译环境不一致，有可能会出现错误，所以目前 pyarmor 不会考虑使用静态链接 glibc 库的方式。
