### ISSUE TITLE
'gbk' codec can't decode byte 0xa1 in position 28: illegal multibyte sequence

### ISSUE THREAD

**Issue by bibeibei** [dashingsoft/pyarmor#51]
I encouter an issue when run below code, please advise, thanks!
pyarmor obfuscate xx.py

INFO     Obfuscate scripts in path "D:\Project\xx" ...
INFO     Use cached capsule C:\Users\admin\.pyarmor_capsule.zip
INFO     Patch entry script xx.py ...
'gbk' codec can't decode byte 0xa1 in position 28: illegal multibyte sequence

**Comment by jondy** [comment]
Could you upload this script, or just several lines? And What's python version used?

**Comment by bibeibei** [comment]
Thank u for your quickly response, below is the codes of the xx.py, it's the entry of a complex project which other self-defined modules are referenced. My python version is 3.7.2, thanks.

`#coding:utf-8
'''
定时执行任务，每隔N分钟
'''

import os,re,time,random,sys
from robot import RobotThread
import json
import psutil
import signal
from VPNHelper import VPNHelper

n=3	#控制频率，n越小频率越快刷量越大
print("定时任务已启动")
i=0
while 1:
	now = time.strftime('%H:%M:%S',time.localtime(time.time()))
	if now>'02' and now<'07':
		sleep = 410*n
	elif now>'07' and now<'09':
		sleep = 290*n #80
	else:
		sleep = 230*n #30
		
	#设置case
	with open("case/xx.json",'r', encoding='UTF-8') as jsonFile:
		case_dict = json.load(jsonFile)
		
	#vpn连接，必须先在电脑上创建VPN连接名称，创建时ip随便写
	vpn = VPNHelper()
	if vpn.connect()!=0:#VPN拨号返回码不是0（主要是756错误），表示无法连接，此时退出python进程，等待看守心跳程序重启
		print("主程序已退出")
		sys.exit()
		
	word_obj = random.choice(case_dict)
	mythread = RobotThread("thread-%s" % i, "xx",word_obj,"4")  
	mythread.start()
	print("定时任务已执行%s次，暂停%s秒" % (i+1,sleep))
	time.sleep(sleep)
	
	#关闭未完成的浏览器窗口
	for p in psutil.process_iter():
		try:			
			if (p.name()=='chrome.exe' or p.name()=='chromedriver2.42.exe') and time.time()-p.create_time()>sleep:
				os.kill(p.pid, signal.SIGTERM)
		except:
			continue
			
	vpn.disconnect()
	
	i+=1`

**Comment by jondy** [comment]
Fix it in v5.1.1, upgrade to latest version and try it again.

**Comment by bibeibei** [comment]
this solution works fine, thanks

**Comment by jetwang99** [comment]
I recently encountered this issue when I run `pyarmor obfuscate xxx.py,` it tells:  `ERROR    'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence`, I opend my xxx.py in notepad++ and remove every single non-english charater, I also double checked the file encoding is utf-8. I am using windows 10.

`Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
PyArmor Trial Version 5.2.3`

Any ideas?
Thanks.

**Comment by jondy** [comment]
How about add the following line at the beginning of `xxx.py`:
`# -*- coding: utf-8 -*-`

**Comment by JunyueLiu** [comment]
I encounter this ERROR too. I also add `# -*- coding: utf-8 -*-` in the first line of my script. Still, it reports `ERROR    'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence`. My pyarmor version is 5.2.5 and python version is 3.7.0 and my operating system is win10.

**Comment by jondy** [comment]
Try this command to print traceback, and show me the location of exception
```
set PYTHONDEBUG=y
pyarmor obfuscate hello.py
```

**Comment by JunyueLiu** [comment]
C:\pyProjects\testEntryted>pyarmor obfuscate C:\pyProjects\weibo\123.py
Trace log mode enabled and log to 'pytransform.log'
INFO     Obfuscate scripts in path "C:\pyProjects\weibo"
INFO     Use cached capsule C:\Users\liu jun yue\.pyarmor_capsule.zip
INFO     Save obfuscated scripts to "dist"
INFO     Read public key from capsule
INFO     Obfuscate scripts with default mode
INFO            service.py -> dist\service.py
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\pyarmor.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\pyarmor\pyarmor.py", line 778, in main_entry
    main(sys.argv[1:])
  File "c:\programdata\anaconda3\lib\site-packages\pyarmor\pyarmor.py", line 767, in main
    args.func(args)
  File "c:\programdata\anaconda3\lib\site-packages\pyarmor\pyarmor.py", line 446, in _obfuscate
    encrypt_script(prokey, a, b, protection=protection)
  File "c:\programdata\anaconda3\lib\site-packages\pyarmor\utils.py", line 282, in encrypt_script
    lines = f.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

**Comment by jondy** [comment]
It should work to convert this file to utf-8 without BOM. Now PyArmor doesn't take BOM into account, I'll fix it in next version v5.2.6

**Comment by JunyueLiu** [comment]
It works. Thanks.
