### ISSUE TITLE
pack .spec files using pyarmor

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [dashingsoft/pyarmor#510]
Hi, There is a command in pyinstaller which is used to pack from a spec file, `pyinstaller --onefile -w file.spec`, How can i do the same with pyarmor?

**Comment by jondy** [comment]
Please refer to the man page of command `pack`
https://pyarmor.readthedocs.io/en/latest/man.html#pack

The other solution is helper script `repack`
https://pyarmor.readthedocs.io/en/latest/advanced.html#repack-pyinstaller-bundle-with-obfuscated-scripts
