### ISSUE TITLE
Marshal Loads Failed 

### ISSUE THREAD

**Issue by AjAj1** [dashingsoft/pyarmor#511]
I just registered for the premium version due to surpassing the 32k byte limit. However, it's no longer obfuscating my script correctly.

I get `RuntimeError: Marshal loads failed` at run time. 

Command - `pyarmor obfuscate --exact Gmail.py`

---
PyArmor Version 6.6.2
Target platforms: Native

Obfuscate Module Mode - 2
Obfuscate Code Mode - 1
Wrap Mode - 1
Restrict Mode - 1
Advanced value - 0
Super Mode - False
Obfuscate 1 scripts OK.

**Comment by jondy** [comment]
If trial version works, I'm sure the purchased version also works. Please make a clean uninstallation, remove all the files (scripts, runtime files, license files) generated by the trial version, then try it again.

Also refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#marshal-loads-failed-when-running-xxx-py
