### ISSUE TITLE
How-to preserve the original line numbers when using Pyarmor?

### ISSUE THREAD

**Issue by data-harmonization** [dashingsoft/pyarmor#512]
Dear PyArmor,

I'm a big fan of the PyArmor features. One question I'd like to ask is if it is possible to preserve the original line numbers of the source code. 

When we get stack-traces of our obfuscated code, we notice that the line numbers are not matching the source code. Are there settings we could use to fix this? Your reply would be most helpful! 

In case no PyArmor settings are available, are there ways to change the source-code, so that line-numbers stay the same?

Looking forward to your reply,
Paul

**Comment by jondy** [comment]
Thanks.

It's a good question. Generally pyarmor doesn't change line number in the stack-trace, but there are several cases the line number will be changed:
* The script is patched by plugin script or cross protection code, refer to https://pyarmor.readthedocs.io/en/latest/how-to-do.html#special-handling-of-entry-script
* In super mode, some functions may be patched by pyarmor automatically, refer to https://pyarmor.readthedocs.io/en/latest/questions.html#code-object-could-not-be-obufscated-with-advanced-mode-2

The line number after these patched lines need to increase extra lines. If any scripts are patched, the script name will be printed in the console, and the debug option `-d` could be used to generate the patched scripts, for example,
```
pyarmor -d obfuscate --exact foo.py
```
This command will generate the patched script "foo.py.pyarmor-patched"

**Comment by data-harmonization** [comment]
Thanks for your quick reply Jondy!

If I understand you correctly, you advise me to obfuscate script by script (convert a source file foo.py into a foo.py.pyarmor-patched) and verify that the line numbers match. If not, I assume I should change my source to debug where the line-number comes from.

If I may pitch an idea; I believe it would be quite a valuable warning if PyArmor would inform me when line-numbers would be changed. Since PyArmor has access to the original source and the patched output, this idea should be technically feasible.

I will go on investigation the day after tomorrow. If I find something interesting, I will reply to this thread to share my findings.

**Comment by jondy** [comment]
But I think even print some logs like `foo.py:203, inserted 10 lines`, it's still not clear to find the right line number of original script if there are many patches.

**Comment by jondy** [comment]
Here are some ways to preserve the original line numbers in the obfuscated scripts:

1. In the entry script, add one comment `# {PyArmor Protection Code}` at the end of file, so that the protection code will be inserted into the bottom of the script.
2. If the scripts are obfuscated by super mode, check the logs like `Patch function "%s" at line %s`, then refine these functions
3.  If using plugin scripts,  convert it as inline plugin, by this way the line numbers will not be changed.

**Comment by data-harmonization** [comment]
Great suggestion! I will give it a go Tomorrow

**Comment by data-harmonization** [comment]
> Here are some ways to preserve the original line numbers in the obfuscated scripts:
> 
> 1. In the entry script, add one comment `# {PyArmor Protection Code}` at the end of file, so that the protection code will be inserted into the bottom of the script.
> 2. If the scripts are obfuscated by super mode, check the logs like `Patch function "%s" at line %s`, then refine these functions
> 3. If using plugin scripts,  convert it as inline plugin, by this way the line numbers will not be changed.

**Attempt to implement step 1**

I did not manage to find the line numbers using step one in combination with a Build.

Here are my detailed steps

One of my original entry files called "lint.py" looks like this:
```
def main(args):
    params, settings = get_settings_from_args(args)
    setup_logging(settings)

    # Assign the overwrites to the linter
    Linter(settings=settings).traverse_configs()


# Without a main-function, importing objects from this class will automatically trigger the application
if __name__ == "__main__":
    main(sys.argv[1:])
```

Applying your change, I get the following result:
def main(args):
    params, settings = get_settings_from_args(args)
    setup_logging(settings)

    # Assign the overwrites to the linter
    Linter(settings=settings).traverse_configs()


# Without a main-function, importing objects from this class will automatically trigger the application
if __name__ == "__main__":
    main(sys.argv[1:])

# {PyArmor Protection Code}

```

Next, I run 
```
pyarmor config --entry "execute.py, template.py, lint.py, setup.py" --manifest "global-include *.py, include application/license/*.pem, include MANIFEST.in, prune tests"
pyarmor -d build --platform linux.x86_64
```

As you can see, one of my entry files is lint.py.

After the build, I get a lint.py.pyarmor-patched, where the ending of the file looks like this:
```
protect_pytransform()
if __name__ == "__main__":
    main(sys.argv[1:])

# {PyArmor Protection Code}
```

In the confiscated code, I'm not finding a line numbers. Instead, I see:
```
from pytransform import pyarmor_runtime
pyarmor_runtime()
from pytransform import pyarmor_runtime
pyarmor_runtime()
__pyarmor__(__name__, __file__, b'\x50\x59\x41\x52\x4d\x4f\x52\
...
', 2)
```

**Comment by data-harmonization** [comment]
> Here are some ways to preserve the original line numbers in the obfuscated scripts:
> 
> 1. In the entry script, add one comment `# {PyArmor Protection Code}` at the end of file, so that the protection code will be inserted into the bottom of the script.
> 2. If the scripts are obfuscated by super mode, check the logs like `Patch function "%s" at line %s`, then refine these functions
> 3. If using plugin scripts,  convert it as inline plugin, by this way the line numbers will not be changed.

*Attempt to implement step 2*
Initially, I didn't know what "super mode" was. The logging of my build showed that "super mode is off", so I went to the [documentation](https://pyarmor.readthedocs.io/en/latest/mode.html#super-mode).

A small remark, after reading the documentation, I read "PyCode_Type is changed, and byte code or word code is mapped". For a new user like me, I don't understand the impact of this mode on the obfuscated code. (unclear to me what problem this mode solves)

Next, I tried to see if I can change my build-command to use "super mode". Reading the --help documentation, I could not find a way to trigger the build option in super mode.

Next, I save the results of my pyarmor build, and continue with pyarmor obfuscate.
```
pyarmor -d obfuscate --exact lint.py --platform linux.x86_64
```
I would expect that the obfuscated code would not change. However, it does!
![image](https://user-images.githubusercontent.com/9056360/119129613-6d9e7180-ba37-11eb-9583-891428e6ec84.png)

![image](https://user-images.githubusercontent.com/9056360/119129710-8eff5d80-ba37-11eb-9d3e-0bf816728866.png)

**Comment by jondy** [comment]
I think you need not care about these. So are the line numbers reserved when running the obfuscated scripts?

And I think I made a mistake for first step, if insert `# {PyArmor Protection Code}` at the end of the entry script, it will be execute after main, so it's meaningless. In your case, the main body is only one line, you can use the original script.

**Comment by data-harmonization** [comment]
Hi Jondy, sorry for not replying earlier. Coming Friday, I wil have time to investigate more. I hope it is still oke to share my findings.

Seeing your comment, I can try your suggestion to add # {PyArmor Protection Code} to the end of my script, but can you also tell me what it will do?

My situation is as follows. We have one script that will be executed, but it will call a lot of other scripts as well. I would appreciate it a lot of you can tell me what I need to search for and what followup options I have to debug the line number issue.

Looking forward to your reply. I will certainly share my results coming Friday.

**Comment by jondy** [comment]
Generally the original line numbers will not be changed by pyarmor, but there are 2 lines for each exception in the traceback. For example, `foo.py` raises an exception in line 20, the traceback may like
```
...
  File "<dist/foo.py>", line 1, in <module>
  File "<frozen foo>", line 20, in <module>
ZeroDivisionError: integer division or modulo by zero
```
 The real line number is in the second line with module name `<frozen zoo>`.

**Comment by data-harmonization** [comment]
My errors look pretty similar without the added line as you can see:
```
  File "</usr/local/lib/python3.8/site-packages/opt/acheron/execute.py>", line 3, in <module>
  File "<frozen execute>", line 204, in <module>
  File "<frozen execute>", line 134, in main
  File "<frozen application.execute>", line 210, in forward_execution_error
RuntimeError: Execution errors in files
```

This is a bad example, since the line numbers match with the source code. I will take a look tomorrow to find examples of errors where the line numbers don't match.

What will happen when I add your line?

**Comment by data-harmonization** [comment]
> ur case, the main body is only one line, you

re-reading your earlier reply, 

> I think you need not care about these. So are the line numbers reserved when running the obfuscated scripts?
> 
> And I think I made a mistake for first step, if insert `# {PyArmor Protection Code}` at the end of the entry script, it will be execute after main, so it's meaningless. In your case, the main body is only one line, you can use the original script.

Initially, I thought that the command was wrong. But re-reading your earlier message, I believe that you say that adding this line has no effect on what PyArmor does. Am I reading this correct?

**Comment by data-harmonization** [comment]
In order to retrieve a proper example where line numbers don't match, I will need an exception with a stack trace in order to see if there are line numbers mentioned that don't match the source code numbering. In order to find one, I will do the following:

- I change `.pyarmor_config` such that my `test` directory will be obfuscated as well
- I will need to change my entry scripts, to run my tests individually
- I will execute my unit-tests, and will go and search for an exception with not-matching line numbers

**Comment by jondy** [comment]
> > I think you need not care about these. So are the line numbers reserved when running the obfuscated scripts?
> > And I think I made a mistake for first step, if insert `# {PyArmor Protection Code}` at the end of the entry script, it will be execute after main, so it's meaningless. In your case, the main body is only one line, you can use the original script.
> 
> Reading your comment for the first time, I thought that the command that you wrote was wrong. But re-reading your earlier message, I believe that you say that adding this line has no effect on what PyArmor does. Am I reading this correct?

Yes. If main script looks like
```python
...
if __name__ == '__main__':
    main()
```

The line numbers will be kept even do nothing for it. Because only the lines after `if __name__ == '__main__':` are increased.

**Comment by data-harmonization** [comment]
Thanks for your quick reply. Than the next challenge... 

In order to retrieve a proper example where line numbers don't match, I will need an exception with a stack trace in order to see if there are line numbers mentioned that don't match the source code numbering. In order to find one, I will try the following:

- I change `.pyarmor_config` such that my `test` directory will be obfuscated as well
- I will need to change my entry scripts, to run my tests individually
- I will execute my unit-tests, and will go and search for an exception with not-matching line numbers
