### ISSUE TITLE
cli param to rename PYARMOR_LICENSE env name and option to set path to license in code at runtime

### ISSUE THREAD

**Issue by genachka** [dashingsoft/pyarmor#513]
Is there any way to set the environment variable name of `PYARMOR_LICENSE` to something else, like `MYAPPNAME_LICENSE` not to make it so obvious that it's PyArmor being used? It would be helpful to do that as perhaps a parameter like `--pyarmor_license_env_name=MYAPPNAME_LICENSE` or something like that.

Also I've encountered a few cases where setting the env var wouldn't work in a use case. Is there any way possible to programmatically set the path to where the license file should be found at runtime? i.e. I'd like to add a cli param to my code that tells it where to find the license file using something like `argparse` as one of my cli params and then pass that along to PyArmor to know where to find it.

**Comment by jondy** [comment]
It's not simple to configure environment variable name in the runtime, because it's hard code in the dynamic library.

In order to improve the security of license file, I think the better way is to write a plugin script with custom license data, then verify the license data by your own logic.

Refer to
https://github.com/dashingsoft/pyarmor/tree/master/plugins

The usage of option `-x` in the command `license`
https://pyarmor.readthedocs.io/en/latest/man.html#licenses
 
And the runtime module `pytransform`
https://pyarmor.readthedocs.io/en/latest/pytransform.html

**Comment by genachka** [comment]
@jondy thanks for your response, I'll review the links.

Two things I wanted to make sure to clarify:
>It's not simple to configure environment variable name in the runtime, because it's hard code in the dynamic library.
I was expecting that the name of the env variable could be statically passed at the time of the pack, so it's not necessarily dynamic in nature since it's not going to change after it's been obfuscated and a binary build.

>In order to improve the security of license file, I think the better way is to write a plugin script with custom license data, then verify the license data by your own logic.
Wanted to make sure that we are not using a custom license in that we are using outer license as we generate a unique license for each user. I assume your response is still the same on that, but wanted to clarify just in csae.

**Comment by jondy** [comment]
> > It's not simple to configure environment variable name in the runtime, because it's hard code in the dynamic library.
> 
> I was expecting that the name of the env variable could be statically passed at the time of the pack, so it's not necessarily dynamic in nature since it's not going to change after it's been obfuscated and a binary build.
>

The dynamic libraries is prebuilt in my build machine and env variable is hard code in this binary file. And there is only one dynamic libraries and a license file (if outer license is used) when running the obfuscated scripts. If env variable is different from building time, it need patch the dynamic library(binary file).
 
> > In order to improve the security of license file, I think the better way is to write a plugin script with custom license data, then verify the license data by your own logic.
> 
> Wanted to make sure it was clear that we are not using a custom license currently. We are using outer license which we generate a unique license for each user. I assume your response is still the same on that, but wanted to clarify just in case.

This method works for your case. For example, you could generate a license for tom bind to mac address "aa:bb:cc:ed:f2:32", the only difference is that extra data will be passed by `-x`
```
pyarmor licenses --bind-mac "aa:bb:cc:ed:f2:32" -x "encoded of this mac address" tom
```

In the plugin script, you can check the data passed by `-x`, decoded it and verify the MAC address by yourself.
