### ISSUE TITLE
Does PyArmor work for PyPy?

### ISSUE THREAD

**Issue by oddmario** [dashingsoft/pyarmor#514]
Hello,

I'm building a production application in Python and I'd like to use PyPy to make it run faster. So I was wondering if Pyarmor can protect a PyPy application

Kind regards

**Comment by jondy** [comment]
After I look through PyPy documentation, I'm afraid pyarmor doesn't work with PyPy. But I have no any experience on PyPy, you can try a simple hello world script.

**Comment by oddmario** [comment]
I have tested it. The pyarmor executable itself can't even run on PyPy (I tried the one in the "Scripts" folder)

It fails with `ImportError: cannot import name 'pythonapi'`

**Comment by oddmario** [comment]
Will there be an attempt to support PyPy one day?

**Comment by jondy** [comment]
At this time I have no plan to support PyPy, because it's totally different from CPython.
