### ISSUE TITLE
Flask and Pyarmor

### ISSUE THREAD

**Issue by ApurvaDani** [dashingsoft/pyarmor#515]
I used Pyarmor to obfuscate my code and it works perfectly. But then I used a flask API to expose the code functionality. I obfuscated both the flask file as well as the code. When I try to run the flask server, it throws an error while importing function from another obfuscated file.

NameError: name '__pyarmor__' is not defined

The server works without obfuscation. Is flask supported with Pyarmor?

**Comment by ApurvaDani** [comment]
I was using the wrong entry script to obfuscate the code. It works after using the flask server file as entry script.

**Comment by rc2007** [comment]
What was your folder structure? 
Are you using app.py or app.wsgi as an entry point?

**Comment by Dattebayooooo** [comment]
> I was using the wrong entry script to obfuscate the code. It works after using the flask server file as entry script.

Hi Can you share the script used for create obfuscated code
