### ISSUE TITLE
Multiple Entry Points

### ISSUE THREAD

**Issue by ApurvaDani** [dashingsoft/pyarmor#516]
Is there a way to have multiple entry scripts? 
The problem with single entry script is that I cannot run any other file directly. Is there a solution to this?

**Comment by jondy** [comment]
Please refer to man page of command `obfuscate`, pass multiple scripts in the command lines.

I suggest you use super mode if possible, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#using-super-mode
