### ISSUE TITLE
Pricing difference between enterprise and individual licence

### ISSUE THREAD

**Issue by kurtzace** [dashingsoft/pyarmor#517]
Hi when we try to procure your licence using order dot share it

And change the dropdown to enterprise licence

The pricing does not change. 

Can you please confirm whether there is any difference between the pricing of enterprise vs individual?

[License](https://pyarmor.readthedocs.io/en/latest/license.html)

**Comment by jondy** [comment]
Hi, there is no difference between the pricing of enterprise vs individual.

**Comment by kurtzace** [comment]
Thank you
