### ISSUE TITLE
PI pytransform filename incorrect

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#518]
Hi @jondy 

if you leave the standard filename for the transform (`pytransform.cpython-37m-arm-linux-gnu.so`) it produces the following error..

```
File "/home/pi/.local/lib/python3.7/site-packages/xxxxxx/init.py", line 1, in <module>
    from .pytransform import pyarmor
```

however if you rename or symlink it to the following

```
ln -s pytransform.cpython-37m-arm-linux-gnu.so pytransform.so
```

rasp pi python can then import...

Are we able to get this addressed permanently your end? 

thanks ❤️

**Comment by jondy** [comment]
What's printed to run this command in this rasp pi?
```
python3.7m-config --extension-suffix
```

**Comment by VeNoMouS** [comment]
@jondy have requested it from a user, will post here once he responds

**Comment by jondy** [comment]
In v6.7.2, the extension name of super mode has been changed to `.so` in Linux, this version has been released today.

**Comment by VeNoMouS** [comment]
Sorry about the delayed response

The user came back with

```
.cpython-37m-arm-linux-gnueabihf.so
```

**Comment by VeNoMouS** [comment]
> In v6.7.2, the extension name of super mode has been changed to `.so` in Linux, this version has been released today.

Ok, i will package and get it out to the user to test, might take a few days to get back to you

thanks for the hard work you do though mate :)

You can either leave this ticket open till i coem back, or i can respond to this ticket if you close it

**Comment by VeNoMouS** [comment]
Will be testing this out today with users.

**Comment by VeNoMouS** [comment]
All working thanks @jondy :)
