### ISSUE TITLE
Plugin is not working in bundled app, but works when run from dist\obf

### ISSUE THREAD

**Issue by jevgienij** [dashingsoft/pyarmor#519]
Hi, I'm trying to bundle my app with PyArmor + PyInstaller. It works flawlessly when bundling only with PyInstaller, but I haven't succeeded using `pyarmor pack` yet.

## INFO ##
Here's the info from `pyarmor register`:
```
pyarmor\platforms\windows\x86_64\_pytransform.dll
DEBUG    The version of core library is (42, 16, 7)
INFO     PyArmor Version 6.7.1
INFO     Python 3.8.5
```

Here's the structure of my project:
```
packagename
 |- src/
    |- packagename/
      |- baz/
      |- bar/
      |- __init__.py
      |- check_disk_and_date.py (my pyarmor plugin)
      |- main.py
 |- packagename.spec
```

The command I'm using now:
`pyarmor -d pack --clean -s packagename.spec -x "--advanced 2 --plugin src/packagename/check_disk_and_date" --with-license licenses/rcode-002/license.lic src/packagename/main.py --debug`

Here's the `main.py`:
```
>>>more code<<<

# {PyArmor Plugins}
if __name__ == '__main__':
    # PyArmor Plugin: print("Running plugin check_disk_and_date()")
    # PyArmor Plugin: check_disk_and_date()
    print('Running plugin completed. Running main()')
    main()
```
And it looks like it is patched correctly. This is the generated `main.py.pyarmor-patched`
```
>>>more code<<<

# {PyArmor Plugins}
>>> check_disk_and_date.py file contents <<<
>>> protect_pytransform() function <<<

protect_pytransform()
if __name__ == '__main__':
    print("Running plugin check_disk_and_date()")
    check_disk_and_date()
    print('Running plugin completed. Running main()')
    main()
```
And here's my `packagename.spec` file:
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['src\\packagename\\main.py'],
             pathex=['C:\\Users\\jegg\\PycharmProjects\\packagename'],
             binaries=[],
             datas=[ ('cfg\\*.*', 'cfg' ), ('cfg\\map\\*.*', 'cfg\\map'), ('cfg\\hud\\*.*', 'cfg\\hud') ],
             hiddenimports=['pythonjsonlogger.jsonlogger', 'loggly.handlers'],
             hookspath=[],
             runtime_hooks=[],
             excludes=['myotherpackage_1', 'myotherpackage_2'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='packagename',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='packagename')
```
## PROBLEM ##
When running generated packagename.exe it behaves like if the `# PyArmor Plugin` lines were still comments. It doesn't print `Running plugin check_disk_and_date()` to console and the `check_disk_and_date()` function is not executed. It simply outputs the next print `Running plugin completed. Running main()` and starts my program.

**However**, when I:
- take the code from `dist\obf`, 
- move it to a folder `packagename`, eg. to `dist\obf\packagename`, 
- add the parent folder to `PYTHONPATH`, ie. `obf` absolute path for the example above,

it starts as expected:
```
Running plugin check_disk_and_date()
Traceback (most recent call last):
  File "<packagename\main.py>", line 2, in <module>
  File "<frozen main>", line 579, in <module>
  File "<frozen main>", line 530, in check_disk_and_date
RuntimeError: This license is not valid for this PC.
Please buy the license for your hardware ID
XXXX_XXXX_XXXX_XXXX
```

**Comment by jondy** [comment]
Try to use `repack` script to pack your scripts, It's more clear and easy to find the problem. Refer to

https://pyarmor.readthedocs.io/en/latest/advanced.html#repack-pyinstaller-bundle-with-obfuscated-scripts

First make sure the obfuscated scripts works as expected, then repack the bundle with the obfuscated scripts

**Comment by jondy** [comment]
If it only doesn't work in the final bundle app, please add one `print` statement and one `return` statement in different lines in the function `check_disk_and_date`. I think something is wrong with this function.

**Comment by jondy** [comment]
Besides, make sure all the modules/packages used by plugin script are packed into the bundle, if not, use `--hidden-import` to pack them into the bundle.

**Comment by jevgienij** [comment]
> If it only doesn't work in the final bundle app, please add one `print` statement and one `return` statement in different lines in the function `check_disk_and_date`. I think something is wrong with this function.

Did you notice that line `    # PyArmor Plugin: print("Running plugin check_disk_and_date()")` is not printed too? I highly doubt the function `check_disk_and_date` is the source of the problems. It is based on your plugins `check_ntp_time.py` and `check_multiple_machine.py` and works perfectly when running from `dist\obf`.

Anyway, I added 1 `print` and 1 `return` statements and I it didn't change anything.

**Comment by jevgienij** [comment]
> Try to use `repack` script to pack your scripts, It's more clear and easy to find the problem. Refer to
> 
> https://pyarmor.readthedocs.io/en/latest/advanced.html#repack-pyinstaller-bundle-with-obfuscated-scripts
> 
> First make sure the obfuscated scripts works as expected, then repack the bundle with the obfuscated scripts

Trying to repack throws this error:
```
(venv) C:\Users\jegg\PycharmProjects\packagename>python -m pyarmor.helper.repack -d -p dist\obf dist\packagename\packagename.exe
136 INFO: Repack PyInstaller bundle "dist\packagename\packagename.exe"
136 INFO: Obfuscated scripts in the path "dist\obf"
136 INFO: Entry script name is "packagename.py"
Traceback (most recent call last):
  File "C:\Users\jegg\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jegg\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jegg\PycharmProjects\packagename\venv\lib\site-packages\pyarmor\helper\repack.py", line 334, in <module>
    main()
  File "C:\Users\jegg\PycharmProjects\packagename\venv\lib\site-packages\pyarmor\helper\repack.py", line 326, in main
    repacker(args.executable, args.obfpath)
  File "C:\Users\jegg\PycharmProjects\packagename\venv\lib\site-packages\pyarmor\helper\repack.py", line 265, in repacker
    raise RuntimeError('No obfuscated script "%s" found', obfentry)
RuntimeError: ('No obfuscated script "%s" found', 'dist\\obf\\packagename.py')

```
Hmm, does `pyarmor pack` or `pyarmor repack` expect the entry point to have the same name as the package/bundle name? Because `136 INFO: Entry script name is "packagename.py"` will never work, since my entry script name is `main.py`.

**Comment by jondy** [comment]
> > Try to use `repack` script to pack your scripts, It's more clear and easy to find the problem. Refer to
> > https://pyarmor.readthedocs.io/en/latest/advanced.html#repack-pyinstaller-bundle-with-obfuscated-scripts
> > First make sure the obfuscated scripts works as expected, then repack the bundle with the obfuscated scripts
> 
> Trying to `repack` throws this error:
> 
> ```
> (venv) C:\Users\jegg\PycharmProjects\packagename>python -m pyarmor.helper.repack -d -p dist\obf dist\packagename\packagename.exe
> 136 INFO: Repack PyInstaller bundle "dist\packagename\packagename.exe"
> 136 INFO: Obfuscated scripts in the path "dist\obf"
> 136 INFO: Entry script name is "packagename.py"
> Traceback (most recent call last):
>   File "C:\Users\jegg\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\jegg\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\jegg\PycharmProjects\packagename\venv\lib\site-packages\pyarmor\helper\repack.py", line 334, in <module>
>     main()
>   File "C:\Users\jegg\PycharmProjects\packagename\venv\lib\site-packages\pyarmor\helper\repack.py", line 326, in main
>     repacker(args.executable, args.obfpath)
>   File "C:\Users\jegg\PycharmProjects\packagename\venv\lib\site-packages\pyarmor\helper\repack.py", line 265, in repacker
>     raise RuntimeError('No obfuscated script "%s" found', obfentry)
> RuntimeError: ('No obfuscated script "%s" found', 'dist\\obf\\packagename.py')
> ```
> 
> Hmm, does `pyarmor pack` or `pyarmor repack` expect the entry point to have the same name as the package/bundle name? Because `136 INFO: Entry script name is "packagename.py"` will never work, since my entry script name is `main.py`.

Rename `dist/packagename/packagename.exe` to `dist/packagename/main.exe` before repack, restore the name after repack.

**Comment by jevgienij** [comment]
For the sake of testing, I renamed `main.py` to `packagename.py` and tried again.

`pyarmor -d pack --clean -s packagename.spec -x "--advanced 2 --plugin src/packagename/check_disk_and_date" --with-license licenses/rcode-002/license.lic src/packagename/packagename.py --debug` Exactly the same outcome as with `src/packagename/main.py` as the entry point.

`pyarmor pack` outputs this:
[repack_log.txt](https://github.com/dashingsoft/pyarmor/files/6608927/repack_log.txt)
This line is weird:
```
306 DEBUG: unhandled obfuscated items are ['check_disk_and_date', '__init__', 'gui.hud_global_settings', 'gui.hud_settings', 'gui.hud_settings_ctrl', 'gui.hud_site_settings', 'gui.hud_view', 'gui.main_window', '
gui.main_window_ctrl', 'gui.graph_diag', 'gui.graph_diag_ctrl', 'gui.players_map', 'gui.players_map_ctrl', 'gui.players_graph_diag', 'gui.players_graph_diag_ctrl', 'gui.save_load', 'gui.scraping_vis', 'gui.table_map', '
gui.table_map_ctrl', 'gui.table_widget', 'gui.table_widget_ctrl', 'gui.utils', 'gui.__init__', 'graph.scobtain', 'graph.__init__', 'game.game_flow_facade', 'game.__init__']
```
All my files, except the entry script, are marked as unhandled obfuscated items?

Anyways, when I overwritten the `.exe` file in the bundle, it didn't start at all:
```
Error loading Python DLL 'C:\Users\jegg\AppData\Local\Temp\_MEI225202\python38.dll'.
LoadLibrary: The specified module could not be found.
```

**Comment by jevgienij** [comment]
> Rename `dist/packagename/packagename.exe` to `dist/packagename/main.exe` before repack, restore the name after repack.

Similar result:
```
Error loading Python DLL 'C:\Users\jegg\AppData\Local\Temp\_MEI73522\python38.dll'.
LoadLibrary: The specified module could not be found.
```

**Comment by jondy** [comment]
Well, forget `repack` if there are so many errors.

Try this way:
1. First insert your plugin script into `main.py` directly
2. Obfuscate the scripts to make sure the plugin works.
3. Pack the scripts without plugin
```
pyarmor -d pack --clean -s packagename.spec -x "--advanced 2" --with-license licenses/rcode-002/license.lic src/packagename/main.py
```

If it doesn't work, check the `packagename-patched.spec`, and run this command to check all the files are packed into the bundle
```
pyInstaller --debug noarchive packagename-patched.spec
```

**Comment by jevgienij** [comment]
> Try this way:
> 
> 1. First insert your plugin script into `main.py` directly
> 2. Obfuscate the scripts to make sure the plugin works.
> 3. Pack the scripts without plugin

This way it works as expected!
```
Traceback (most recent call last):
  File "packagename\main.py", line 534, in <module>
  File "packagename\main.py", line 526, in check_disk_and_date
RuntimeError: This license is not valid for this PC.
Please buy the license for your hardware ID
XXXX_XXXX_XXXX_XXXX
[19084] Failed to execute script main
```

Unfortunalely, this makes the main.py unusable when it's not obfuscated :(

**Comment by jondy** [comment]
If this way works, I think the reason why it doesn't work with plugin is that some packages/modules used by plugin script are not packed into the bundle.

So try to add those extra modules as hidden import to `packagename.spec`, then pack it with plugin.

**Comment by jevgienij** [comment]
As I said, the plugin is based on your plugins `check_ntp_time.py` and `check_multiple_machine.py`, so these are the import lines:
```
import datetime
import socket
import struct
import time
from ctypes import c_char, py_object, PYFUNCTYPE
from pytransform import _pytransform
from pytransform import get_user_data
from pytransform import get_hd_info
```
So I modified the hidden import line in `packagename.spec`:
`hiddenimports=['pythonjsonlogger.jsonlogger', 'loggly.handlers', 'datetime', 'socket', 'struct', 'time', 'ctypes', 'pytransform'],`

Unfortunately, it didn't help.

**Comment by willwrong** [comment]
I've encountered the same issue - packing with super mode, including all various libararies it demands, and yet:
`ModuleNotFoundError: No module named 'pytransform'`

**Comment by jondy** [comment]
@willwrong
Please following this guide to find problem
https://pyarmor.readthedocs.io/en/latest/questions.html#the-final-bundle-does-not-work
