### ISSUE TITLE
Python2.7.5 something wrong in build-in function 'exec'

### ISSUE THREAD

**Issue by JimmyJay2015** [dashingsoft/pyarmor#522]
Hi @jondy 
I use pyarmor obfuscate  Django 1.11.29, and run error.

Django code(utils/six.py):

\# line 678
if PY3:

    exec_ = getattr(moves.builtins, "exec")

    def reraise(tp, value, tb=None):
        if value is None:
            value = tp()
        if value.__traceback__ is not tb:
            raise value.with_traceback(tb)
        raise value

else:

    def exec_(_code_, _globs_=None, _locs_=None):

        if _globs_ is None:
            frame = sys._getframe(1)
            _globs_ = frame.f_globals
            if _locs_ is None:
                _locs_ = frame.f_locals
            del frame
        elif _locs_ is None:
            _locs_ = _globs_`
        exec("""exec _code_ in _globs_, _locs_""")
    
    exec_("""def reraise(tp, value, tb=None):
    raise tp, value, tb""")

\# line 786
\# this code run error: NameError: name 'reraise' is not defined
_add_doc(reraise, """Reraise an exception.""")

My python is 2.7.5.
I used pytransform_bootstrap, and only this file wrong.
So, I  guess there must be something wrong in  'exec'.

What's wrong? And how can I fix it?

**Comment by jondy** [comment]
Replace `frame = sys._getframe(1)` with `frame = sys._getframe(2)`, the level of frame is changed by obfuscated scripts.

**Comment by JimmyJay2015** [comment]
thank you!   It works!

If the level of frame is changed by obfuscated scripts, can I still use `sys._getframe().f_back`?

**Comment by JimmyJay2015** [comment]
Hi @jondy 
There is another question in pecan module.

pecan code(configuration.py):
\# line 149
def conf_from_file(filepath):

    '''
    Creates a configuration dictionary from a file.

    :param filepath: The path to the file.
    '''

    abspath = os.path.abspath(os.path.expanduser(filepath))
    conf_dict = {}
    if not os.path.isfile(abspath):
        raise RuntimeError('`%s` is not a file.' % abspath)

    # First, make sure the code will actually compile (and has no SyntaxErrors)
    with open(abspath, 'rb') as f:
        compiled = compile(f.read(), abspath, 'exec')

    # Next, attempt to actually import the file as a module.
    # This provides more verbose import-related error reporting than exec()
    absname, _ = os.path.splitext(abspath)
    basepath, module_name = absname.rsplit(os.sep, 1)
    if sys.version_info >= (3, 3):
        SourceFileLoader(module_name, abspath).load_module(module_name)
    else:
        imp.load_module(
            module_name,
            *imp.find_module(module_name, [basepath])
        )

    # If we were able to import as a module, actually exec the compiled code
    # This code run error: RuntimeError: Marshal loads failed
    exec(compiled, globals(), conf_dict)
    conf_dict['__file__'] = abspath

    return conf_from_dict(conf_dict)

filepath code(config.py):

\#!/usr/bin/env python
\# coding=utf-8

\# Server Specific Configurations
server = {
    'port': '1111',
    'host': '0.0.0.0'
}

\# Pecan Application Configurations
app = {
    'root': 'xx.xx.controllers.root.RootController',
    'modules': ['xx.api'],
}


I have read https://pyarmor.readthedocs.io/zh/v5.8.0/questions.html#marshal-loads-failed-when-running-xxx-py.
I checked, but don't works. 
I still don't know why.
How can I fix it?

**Comment by jondy** [comment]
> But, if the level of frame is changed by obfuscated scripts, can I still use `sys._getframe().f_back`?

The frame attribute `f_back` still works, use `frame.f_back.f_back` to get the same outer frame in obfuscated scripts.

**Comment by jondy** [comment]
> Hi @jondy
> There is another question in pecan module.
> 
> pecan code(configuration.py):
> # line 149
> def conf_from_file(filepath):
> 
> ```
> '''
> Creates a configuration dictionary from a file.
> 
> :param filepath: The path to the file.
> '''
> 
> abspath = os.path.abspath(os.path.expanduser(filepath))
> conf_dict = {}
> if not os.path.isfile(abspath):
>     raise RuntimeError('`%s` is not a file.' % abspath)
> 
> # First, make sure the code will actually compile (and has no SyntaxErrors)
> with open(abspath, 'rb') as f:
>     compiled = compile(f.read(), abspath, 'exec')
> 
> # Next, attempt to actually import the file as a module.
> # This provides more verbose import-related error reporting than exec()
> absname, _ = os.path.splitext(abspath)
> basepath, module_name = absname.rsplit(os.sep, 1)
> if sys.version_info >= (3, 3):
>     SourceFileLoader(module_name, abspath).load_module(module_name)
> else:
>     imp.load_module(
>         module_name,
>         *imp.find_module(module_name, [basepath])
>     )
> 
> # If we were able to import as a module, actually exec the compiled code
> # This code run error: RuntimeError: Marshal loads failed
> exec(compiled, globals(), conf_dict)
> conf_dict['__file__'] = abspath
> 
> return conf_from_dict(conf_dict)
> ```
> 
> filepath code(config.py):
> 
> #!/usr/bin/env python
> # coding=utf-8
> 
> # Server Specific Configurations
> server = {
> 'port': '1111',
> 'host': '0.0.0.0'
> }
> 
> # Pecan Application Configurations
> app = {
> 'root': 'xx.xx.controllers.root.RootController',
> 'modules': ['xx.api'],
> }
> 
> I have read https://pyarmor.readthedocs.io/zh/v5.8.0/questions.html#marshal-loads-failed-when-running-xxx-py.
> I checked, but don't works.
> I still don't know why.
> How can I fix it?

Do not obfuscate `config.py` if there is no sensitive data. Just copy the original `cofig.py` to `dist` path to overwrite the obfuscated one.

**Comment by JimmyJay2015** [comment]
Thanks a lot! 
: )
