### ISSUE TITLE
Licenses generated via web API method don't deactivate properly

### ISSUE THREAD

**Issue by willwrong** [dashingsoft/pyarmor#523]
I'm encountering an issue where licenses generated by the Python API method successfully activate my software, but when the license is moved to another computer, or when the computer's date is beyond the expiry date, the license does not deactivate. When I generate a license via a Powershell terminal, my software correctly honors the HDD serial binds/MAC binds/expiry dates.

```
from zipfile import ZipFile
from pyarmor.pyarmor import DEFAULT_CAPSULE, licenses as generate_licenses

key = ZipFile(DEFAULT_CAPSULE, 'r').read('private.key')

lickey = licenses(name='test',
  expired='2021-12-24',
  bind_disk=get_hd_info(HT_HARDDISK),
  key=key)
print(lickey)
```

Operating system: Windows 10
Python 3.9

**Comment by jondy** [comment]
First make sure the outer license is enabled in another machine, then try to add some code like 
```
import pytransform
print('License info:', pytranform.get_license_info())
``` 
to  print the license information in your obfuscated scripts?
