### ISSUE TITLE
How to run obfuscated scripts via uvicorn cli 

### ISSUE THREAD

**Issue by Cwanyo** [dashingsoft/pyarmor#525]
Basically, I have web app build based on FastAPI. 
It require uvicorn (ASGI server) to run the script as production ready mode.

Somethings like this 
```
uvicorn run:app --host 0.0.0.0 --port 3000
```

The workaround right now is to call uvicorn.run(..) in `run.py` file as below,.
```
if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=3000)
```

Although there is no difference starting the service via cli or in-file code. Still I would like to known is it possible?

**Comment by jondy** [comment]
Please refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

**Comment by Cwanyo** [comment]
Cool it works now !

**Comment by jetray007** [comment]
@jondy and @Cwanyo : the documentation is removed. Can you repost the solution ?

**Comment by cikay** [comment]
> @jondy and @Cwanyo : the documentation is removed. Can you repost the solution ?

You can run the project [programmatically](https://www.uvicorn.org/#uvicornrun)
