### ISSUE TITLE
[Query] Project ignoring cross_protection config

### ISSUE THREAD

**Issue by piyush-das** [dashingsoft/pyarmor#526]
Hi,

I am trying to obfuscate 2 packages with the same runtime package. 

- To generate the common runtime package.
```python
pyarmor runtime --advanced 2 --output dist
```
Then when I am obfuscating the project using the command.
```python
pyarmor build -B --no-runtime
```
Here there are two possibilities : 
1. if `cross_protection=1` : Then we get the warning `WARNING  No cross protection because no runtime generated`. This makes sense since there was no runtime at the time of build.
2. Hence I instead set the following  `cross_protection="dist/pytransform_protection.py"`, there are no warnings but there are no info related to cross protection at all, infact if I gave a file which doesn't exist still I don't get any errors or info.

So I am uncertain whether the cross_protection template was even inserted or not.

I used the following [doc reference](https://pyarmor.readthedocs.io/en/latest/advanced.html#customizing-cross-protection-code). However the example was using the obfuscate command and doesn't work with the build command as described above.

Please let me know where I am going wrong.

Thanks

**Comment by jondy** [comment]
It's better to obfuscate the project by this command if there is outer runtime package, and it's better to save the runtime package to another path
```
pyarmor build -B --with-runtime=@dist
```

Please check man page to understand the meaning of option `--with-runtime`, and check the description of command `runtime` in the man page.

Also check this
https://pyarmor.readthedocs.io/en/latest/how-to-do.html#special-handling-of-entry-script

And use common option `-d` to generate patched scripts `xxx.py..pyarmor-patched` to check whether the cross protection code is inserted into it.
```
pyarmor -d build -B --with-runtime=@dist
```

**Comment by piyush-das** [comment]
Thanks
