### ISSUE TITLE
RuntimeError: sum() is not a builtin

### ISSUE THREAD

**Issue by rikoboy** [dashingsoft/pyarmor#527]
Hi,
When I use 
`pyarmor obfuscate --no-cross-protection myscript.py` script is working ok
But when I use:
`pyarmor obfuscate --no-cross-protection myscript.py` script is returning `RuntimeError: sum() is not a builtin`

Any clue?

Python 3.7.3
Raspberry Pi 4

Thanks in advance

**Comment by jondy** [comment]
The cross protection code will check the type of `sum`, if it's not builtin, it will raise this exception.

If `sum` is redefined, please customize the cross protection code. Refer to 
https://pyarmor.readthedocs.io/en/latest/advanced.html#customizing-cross-protection-code

**Comment by rikoboy** [comment]
Ok, thanks for your reply.
I wrote wrong on the halted code, this is the correct one:
`pyarmor obfuscate myscript.py` script is returning RuntimeError: sum() is not a builtin
So this is correct in default, that I need to add `--no-cross-protection`?

**Comment by jondy** [comment]
It's decided by you. If using cross protection, you need customize the cross protection code in this machine.

**Comment by rikoboy** [comment]
Ok, thanks for your help
