### ISSUE TITLE
Cannot get harddisk information with hdinfo

### ISSUE THREAD

**Issue by kaoh** [dashingsoft/pyarmor#529]
I'm running Ubuntu 20.04, my harddisks are:

> sda                      8:0    0 931,5G  0 disk  
> ├─sda1                   8:1    0   1,5G  0 part  
> ├─sda2                   8:2    0 879,5G  0 part  
> ├─sda3                   8:3    0  16,3G  0 part  
> └─sda4                   8:4    0  34,3G  0 part  
> sdb                      8:16   0   1,8T  0 disk  
> ├─sdb1                   8:17   0   1,3T  0 part  
> ├─sdb2                   8:18   0   731M  0 part  /boot
> ├─sdb3                   8:19   0     1K  0 part  
> └─sdb5                   8:21   0 536,4G  0 part  
>   └─newRoot            253:0    0 536,4G  0 crypt 
>     ├─ubuntu--vg1-root 253:1    0   520G  0 lvm   /
>     └─ubuntu--vg1-swap 253:2    0  16,4G  0 lvm   [SWAP]
> 

`hdinfo` gives:

> DEBUG    PyArmor installation path: /home/foo/projects/bar/venv/lib/python3.8/site-packages/pyarmor
> DEBUG    PyArmor home path: /home/foo/.pyarmor
> DEBUG    Native platform is linux.x86_64
> DEBUG    Search dynamic library in the path: /home/foo/projects/bar/venv/lib/python3.8/site-packages/pyarmor/platforms
> DEBUG    Loaded dynamic library: /home/foo/projects/bar/venv/lib/python3.8/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
> DEBUG    The version of core library is (43, 17, 7)
> INFO     PyArmor Trial Version 6.7.2
> INFO     Python 3.8.5
> 
> Hardware informations got by PyArmor:
> 
> Failed to get harddisk information.
> 
> Default Mac address: "xxxx"
> 
> Multiple Mac addresses: "<xxxxx,yyyyy,zzzzzz,aaaaaa>"
> 
> Ip address: "192.168.178.29"
> 
> Domain name: "(none)"
> 
> Change logs
> 
>         v6.2.0(r21): Remove trailing dot from harddisk serial number
>         v6.4.2(r34): Support binding multiple mac addresses
>         v6.5.3(r37): Support binding named harddisk

**Comment by jondy** [comment]
How about `sudo hdinfo`?

**Comment by Cwanyo** [comment]
Having the same issue as well, I couldn't get the harddisk info even running it with `sudo`.

BTW, I have a RAID setup in my system. I don't know whether is it supported by hdinfo or not.

**Comment by jondy** [comment]
RAID may not be supported by `hdinfo`, one solution is to use plugin to extend the license type for RAID, refer to
https://github.com/dashingsoft/pyarmor/tree/master/plugins

**Comment by kaoh** [comment]
Also sudo does not show the hard disks. I do not have a raid, but I'm using an encrypted LVM. Would calling `lsusb` in the implementation and take the result be a general solution for any Linux system?

**Comment by jondy** [comment]
I think it's not the better solution to read harddisk information by shell command.
There are too many harddisk types, now pyarmor supports ide, scsi, nvm etc and use `ioctl` to read harddisk information.  For all the other cases, the solution is plugin.

**Comment by kaoh** [comment]
The plugin approach looks easy, I will use it then.
