### ISSUE TITLE
Pyarmor on alpine image

### ISSUE THREAD

**Issue by PidgeyBE** [dashingsoft/pyarmor#53]
Dear 

We try to run pyarmored code in an Alpine docker image. But we get the following error:
```    Traceback (most recent call last):
      File "/xxxx/pytransform.py", line 237, in _load_library
        m = cdll.LoadLibrary(os.path.join(libpath, '_pytransform.so'))
      File "/usr/local/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
        return self._dlltype(name)
      File "/usr/local/lib/python3.6/ctypes/__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: Error relocating /xxxx/_pytransform.so: __snprintf_chk: symbol not found
```

Via Google we find similar issues pointing out that the error is related to the _pytransform.so the glibc toolchain instead of musl.
Is there a way to have the pytransform library build for musl?

Thanks a lot!

**Comment by jondy** [comment]
I start my holiday today and I'm not in the office now. I'll try to build `_pytransform.so` for `musl` as soon as I finish my holiday on Feb. 11.

**Comment by jondy** [comment]
Here it's `_pytransform.so` built for alpine (x86_64)
http://pyarmor.dashingsoft.com/downloads/platforms/alpine/_pytransform.so
md5sum: 3cbc88c1e969f37f9d6734d0461b6592

**Comment by PidgeyBE** [comment]
Thanks a lot! We'll try it out as soon as possible and report back if any issues occur!

**Comment by dsanchezseco** [comment]
I can confirm it works, just replace the _pytransform.so installed with pip with that one and good to go.

 Is there any plan to make it a more permanent fix?

**Comment by jondy** [comment]
From next version, maybe it could be upgraded by this way:
```
pip install --upgrade pyarmor
# This command will upgrade binary library by current platform
pip install --upgrade pyarmor-core
```
BTW, what's the output of `distutils.util.get_platform()` in docker container?

**Comment by jondy** [comment]
It seems this way doesn't work, because I can not upload special wheel for Alpine linux to pypi.  It seems only manylinux1 such as `pyarmor_core-5.2.6-py2.py3-none-manylinux1_x86_64.whl` can be accepted by pypi.

**Comment by dsanchezseco** [comment]
I'll test it on Monday. 

I have to do further testing/research but seems that using the pack option(pyinstaller) with the musl lib makes it not work on ubuntu at least. (I'm generating the bin in an alpine container on jenkins) but as i said i need further investigation to pinpoint the problem
