### ISSUE TITLE
Check bootstrap restrict mode failed

### ISSUE THREAD

**Issue by ramushetty** [dashingsoft/pyarmor#531]
I am getting 'Check bootstrap restrict mode failed' when is used --restrict=1 or any other mode except 0 
Using license one  and using mac id for obfuscation 
Also, any help, or is there any tutorial on using my license key in any pipeline in CI?

**Comment by jondy** [comment]
Refer to
https://pyarmor.readthedocs.io/en/latest/mode.html#restrict-mode

Especially the end part of this section. 

I suggest using super mode to obfuscate scripts if super mode is supported for your case. Refer to
https://pyarmor.readthedocs.io/en/latest/mode.html#super-mode

pyarmor is a normal python package, and obfuscated scripts are also normal python scripts, use it as any python script.

Please read the content of the registration text file `pyarmor-regfile-xxxx.txt`, register pyarmor by the second way, because it  need not download  extra reg-file.

**Comment by ramushetty** [comment]
Thank you Jondy, information helps
I have used super-mode 
now after obfuscation, I am getting this error 
Could not find "dist/pytransform/platforms/linux/x86_64/_pytransform.so"
any help?

**Comment by ramushetty** [comment]
ModuleNotFoundError: No module named 'pytransform'

also getting this error 

actually, I am using something like this not sure is it correct or not 

from pyarmor import pytransform
from pytransform import pyarmor_runtime
pyarmor_runtime('./dist')

if i comment 'from pyarmor import pytransform' 
getting this error
 ModuleNotFoundError: No module named 'pytransform'
 
if not is like this 
Could not find "dist/pytransform/platforms/linux/x86_64/_pytransform.so"

**Comment by jondy** [comment]
Please remove the whole path `dist` and try again.

And for any `ModuleNotFoundError` issue, please refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#python-import-system

**Comment by ramushetty** [comment]
.
├── algorithms
│   ├── __init__.py
│   ├── myalgo1.py
│   └── myalgo2.py
├── main.py
└── venv

my main.py 

from pyarmor import pytransform
from pytransform import pyarmor_runtime
pyarmor_runtime('./dist')


from dist.myalgo1 import hello1 
from dist.myalgo2 import hello2

print(hello1())
print(hello2())

using commands 

pyarmor licenses  --bind-mac "xx:xx:xx:xx:xx:xx" code-002
pyarmor obfuscate  --with-license licenses/code-002/license.lic  --advanced 2  *.py

obfuscating algorithms dir 

not sure where I am missing problem still persists 
when I am using super-mode means there is no pytransform dir is getting created in dist folder

any help?

**Comment by ramushetty** [comment]
Thanks @jondy it works 
but I have few doubt like when we obfuscate with macid a License dir  is getting created 
should we need to share that license while sharing our code or delete it after obfuscation?
can anyone deobfuscate my algorithm using that file in license dir?

Is there any doc for docker obfuscation?

**Comment by jondy** [comment]
You need share that license, the license file has been embedded into the runtime files of obfuscated scripts.

The file in license dir couldn't help deobfuscating the scripts at all.

The obfuscated scripts are normal python scripts, use them as other python scripts in docker, refer to
http://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

**Comment by ramushetty** [comment]
Thank you @Jondy 
I need more clarity on the following two questions
1. So, when I do MACID based obfuscation in docker the MACID is getting changed on every container creation and pull, what is the best way to do obfuscation in container-based environment. so that one code can not be copied to another machine.
2. Let us say I have two Pyarmor based registration licenses, I have obfuscated my code with licenses-1 now can I deobfuscate it with licenses-2?

Thanks in advance

**Comment by jondy** [comment]
> 1. So, when I do MACID based obfuscation in docker the MACID is getting changed on every container creation and pull, what is the best way to do obfuscation in container-based environment. so that one code can not be copied to another machine.

I don't know about docker well. Some users use plugin to check the docker id. There is an example in the github, check it in this path `pyarmor/src/plugin/`

> 2. Let us say I have two Pyarmor based registration licenses, I have obfuscated my code with licenses-1 now can I deobfuscate it with licenses-2?
> 

No.

**Comment by ramushetty** [comment]
Thanks @jondy your responses help a lot 
Regarding the plugin that you mentioned above 
Should I need to pass these two comment lines in the scripts that I am going to obfuscate or the main.py that I am going to call those obfuscated scripts?
# {PyArmor Plugins}
# PyArmor Plugin: check_docker()

and 
pyarmor licenses -x f56b1824e453126ab5426708dbbed41d0232f6f2ab21de1c40da934b68a5d8a2 CODE-0002
what is this f56b1824e453126ab5426708dbbed41d0232f6f2ab21de1c40da934b68a5d8a2? actually what i need to add in this place when i am obfuscating 


Thanks in advance 
Sorry Jondy new to pyarmor taking a little bit long to understand.
But, I am able to understand a lot from your responses.

**Comment by jondy** [comment]
> Should I need to pass these two comment lines in the scripts that I am going to obfuscate or the main.py that I am going to call those obfuscated scripts?
> 
> # {PyArmor Plugins}
> # PyArmor Plugin: check_docker()

Yes,  these 2 comment lines must be inserted into `main.py`.

Refer to
https://pyarmor.readthedocs.io/en/latest/how-to-do.html#how-to-deal-with-plugins

> pyarmor licenses -x f56b1824e453126ab5426708dbbed41d0232f6f2ab21de1c40da934b68a5d8a2 CODE-0002
> what is this f56b1824e453126ab5426708dbbed41d0232f6f2ab21de1c40da934b68a5d8a2? actually what i need to add in this place when i am obfuscating
> 

It's docker ID.

**Comment by ramushetty** [comment]
@jondy not sure where I am doing mistake this the repo that I am trying on [https://github.com/ramushetty/pyarmortest](https://github.com/ramushetty/pyarmortest)

In this, I am trying to obfuscate the myalgo1.py and myalgo2.py scripts present in the algorithms folder and trying to access them in main.py
I am using the check docker id commands 
but I am getting this error
INFO     Start obfuscating the scripts...
INFO     	__init__.py -> dist/__init__.py
INFO     Found plugin check_docker at: ./algorithms/check_docker.py
INFO     	check_docker.py -> dist/check_docker.py
INFO     Found plugin check_docker at: ./algorithms/check_docker.py
INFO     	myalgo1.py -> dist/myalgo1.py
INFO     Found plugin check_docker at: ./algorithms/check_docker.py
INFO     Patch this script with plugins
INFO     Apply plugin check_docker
ERROR    invalid syntax (<frozen myalgo1>, line 27)

Can you help where exactly I am doing wrong? like commands and so on

**Comment by jondy** [comment]
Please check your script `./algorithms/check_docker.py`, there is syntax error. I don't help users to fix the problem in their own script, please debug it by yourself.

**Comment by ramushetty** [comment]
@jondy do i need to obfuscate two time when i am using plugin?
pyarmor obfuscate --exact --advanced 2 myalgo1.py 
pyarmor obfuscate --plugin check_docker --exact main.py
pyarmor licenses -x f56b1824e453126ab5426708dbbed41d0232f6f2ab21de1c40da934b68a5d8a2 CODE-0002
pyarmor obfuscate --with-license licenses/CODE-0002/license.lic --plugin check_docker --exact main.py

**Comment by jondy** [comment]
No, once is enough.  But if one script is obfuscated by `--advanced 2`, all the others must be obfuscated by `--advanced 2` either. 

Please first do some **tests** to understand what command obfuscate will output, for example
```
rm -rf dist
pyarmor obfuscate ...
ls dist
```

Then read this to understand the obfuscated scripts.
http://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html
