### ISSUE TITLE
pyrmor wont run on armv7

### ISSUE THREAD

**Issue by medamin2017** [dashingsoft/pyarmor#535]
** i've compiled an apk with buildozer ( python, kivy) for armv7, and i used a purchased pyarmor to obfuscate the code. when run it on android device it crushs, i've followed the instructions of pyarmor help but always the same ting.
** here's the logcat after crushing
[logcat.txt](https://github.com/dashingsoft/pyarmor/files/6753014/logcat.txt)
** here's is the obfuscating command for armv7
![VirtualBox_20_02_07_2021_09_25_21](https://user-images.githubusercontent.com/86824749/124240858-79438480-db1b-11eb-959c-be3a83dd0478.png)
** here's the build process with buildozer 
![VirtualBox_20_02_07_2021_09_26_07](https://user-images.githubusercontent.com/86824749/124241329-f4a53600-db1b-11eb-8f28-2ad5505d313e.png)
** here's the obfuscated code of helloworld.py 
![VirtualBox_20_02_07_2021_09_27_13](https://user-images.githubusercontent.com/86824749/124242004-96c51e00-db1c-11eb-953c-9c85cace4871.png)

** here's the buildozer spec file used for compiling the apk with buildozer 
![1](https://user-images.githubusercontent.com/86824749/124242868-81042880-db1d-11eb-81b2-5c72dc86baa0.JPG)
![2](https://user-images.githubusercontent.com/86824749/124242885-86617300-db1d-11eb-95db-880915576411.JPG)
![3](https://user-images.githubusercontent.com/86824749/124242904-8bbebd80-db1d-11eb-852b-775c2de45a8b.JPG)
![4](https://user-images.githubusercontent.com/86824749/124242923-8feadb00-db1d-11eb-860a-ba6d65ffc1bd.JPG)

**Comment by jondy** [comment]
Hi guy, I don't know buildozer at all.

I just want to confirm one thing, after obfuscating the script in the linux, copy all the files in the `dist` to android.armv7, and run this in the android
```
ls dist/
python dist/foo.py
```
Does it work or not?

If it works, use the obfuscated scripts as normal python scripts in bulldozer, refer to this guide
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

**Comment by jondy** [comment]
I forget another thing, because android may only allow to load dynamic library from some special paths, the binary file `_pytransform.so` in the `dist` may be put to special path so that it could be loaded

Refer to #462

**Comment by medamin2017** [comment]
hi again
i did what you told me i've copied the content of dist in android phone and
run it with termux
i got this error message :
' dlopen failed : storage/emulated/0/dist/pytransform/_pytrasform.so is
32-bit instead of 64-bit '

**Comment by jondy** [comment]
armv7 is 32-bit processor, are you sure this platform is `android.armv7`?

Use `--platform android.aarch64` to obfuscate the scripts, and try it again.

**Comment by medamin2017** [comment]
hi
the arch i'm building for is ' armeabi-v7a ' so is there a prebuilt library
for it ?

**Comment by jondy** [comment]
> ' dlopen failed : storage/emulated/0/dist/pytransform/_pytrasform.so is
32-bit instead of 64-bit '

I'm curious that why dlopen requires 64-bit dll.

And does `--platform android.aarch64` work? Please test it first.

**Comment by medamin2017** [comment]
i've tried it and always the same crush
the architecture i'm building for is armeabi-v7a

**Comment by jondy** [comment]
What's the error message?  I don't think the error message is same that say it's 32-bit dll

And could you run these python statement in android?
``` python
from platform import *
print('system name: %s' % system())
print('machine: %s' % machine())
print('processor: %s' % processor())
```

**Comment by medamin2017** [comment]
hi
i've did what you told me last time
i've created an apk and to show the system name/machine name / processor
name , run it on 2 different phones  and got :
* first phone :
system name : linux
machine name : armv8l
processor :
* second phone :
system name : linux
machine name : armv7
processor :

i've tried to build an obfuscate apk with 2 different prebuild library :
linux.armv7 , android.armv7
and always it crushed.
the logcat i've got crushing always show that the apk cant load the library

**Comment by medamin2017** [comment]
Hi
I think the best way to resolve the issue is to test yourself an apk
generated by buildozer to see the behavior of pyarmor and buildozer.
You can get it by installing ubuntu 20.04 and buildozer ( you're gonna find
a complete guide about how to create apk via ubuntu/buildozer )
Best regards

Le ven. 9 juil. 2021 à 10:10, med amin ***@***.***> a
écrit :

> hi
> i've did what you told me last time
> i've created an apk and to show the system name/machine name / processor
> name , run it on 2 different phones  and got :
> * first phone :
> system name : linux
> machine name : armv8l
> processor :
> * second phone :
> system name : linux
> machine name : armv7
> processor :
>
> i've tried to build an obfuscate apk with 2 different prebuild library :
> linux.armv7 , android.armv7
> and always it crushed.
> the logcat i've got crushing always show that the apk cant load the library
>

**Comment by jondy** [comment]
For armv8l, please use platform `android.aarch64`.

For armv7, please check `sys.byteorder`, if it's little, use platform `android.armv7`. If it's big, there is still no core library for big endian in this platform now.

**Comment by medamin2017** [comment]
Hi
I've already told you that i tried android.aarch64 and it crushed ,the
crush message in the logcat is " cannot load the library " .
The best thing to do is building an apk with buildozer yourself to see the
compatibility of pyarmor with the apps created by python for android.
Best regards

**Comment by jondy** [comment]
I have no plan to learn how to build an apk, I don't think it's an easy thing to build an apk with bulldozer and build an android test environment by myself.

I'm sure `android.aarch64` and `android.armv7` works for android platform in the right machine, because some users use them and works fine.

You need know the obfuscated scripts require native dynamic library to work, as I know, pure java is platform independent, but with the obfuscated scripts, the apk must take the native binary file into account. I think it need extra works if the apk includes native dynamic library. If your apk do nothing about this, I think it will not work.

In order to let the obfuscated scripts work in multiple form, please refer to the advanced usages in the documentation.

What I can support is that make sure the obfuscated scripts could run in the target platform. That is to say, obfuscating a simple script `foo.py`, then run it in the target machine.

For this issue, what I care about is only one thing: armv7 is big endian or little endian. If it's little, it should work. If it's big, it should not work. It need build new core library.

If you report an issue, but even don't provide necessary platform information, I could not continue to support.

**Comment by medamin2017** [comment]
Thanks for the reply.
The machine i'm testing in is samsung A20  i've already create many little
projects with python for personal use and works fine. It seem's that
pyarmor is not compatible with all the platforms and need more work to
achieve the expectations of users. Next time test it on many target you can
use virtual emulator to test the compatibility of your work.
