### ISSUE TITLE
RuntimeError: Marshal loads failed

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [dashingsoft/pyarmor#537]
Hello, I don't know this was bug or I just not good enough to read your documentation.
Everytime I try to obfuscate my python3 script on Debian10 x86_64 it was not sucessfull, but it was difference on my Ubuntu machines. I need to change #!/usr/bin/env python3 to #!/usr/bin/env python on my Debian10. 
Pyarmor seems safes to protect my script, I just want to make sure it can use for all machines before purchase a license. 

![pyarmor_runtime_error](https://user-images.githubusercontent.com/73665622/124365742-8461f600-dc7c-11eb-9cf7-3d09a228618c.png)
![pyarmor_done](https://user-images.githubusercontent.com/73665622/124365743-862bb980-dc7c-11eb-8771-f90998f9c520.png)
 a license

**Comment by jondy** [comment]
It's better to read these
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

About marshal load fails issue, check this
https://pyarmor.readthedocs.io/en/latest/questions.html#marshal-loads-failed-when-running-xxx-py

**Comment by GreatestOfAllTimee** [comment]
Thank you for your reply! I already got the solution after trying several times.
I tried uninstall pyarmor and reinstall using `pip3 install pyarmor`, it still doesn't work for me.
The Solution is : `python3 -m pip install pyarmor` 
I don't why using pip3 install not working.
Thank you! One more thing, does Pyarmor have a payment method using PayPal ? If can, how ?

**Comment by jondy** [comment]
Check this link,
https://order.shareit.com/cart/add?vendorid=200089125&PRODUCT[300871197]=1

 if not found PayPal in payment method, try to switch language to English

**Comment by GreatestOfAllTimee** [comment]
Found it! Thank you. Solved
