### ISSUE TITLE
Pack project that uses obfuscated package

### ISSUE THREAD

**Issue by gospodima** [dashingsoft/pyarmor#538]
Hello,

I am having an obfuscated package that is used in other project.
Package has the following structure:
```
tsaf (package name)
├── submodule1
├── submodule2
├── pytransform_vax_******
|       ├ __init__.py
|       └_pytransform_vax_******.so
└── __init__.py
```

I can successfully install with pip from repo, import and use this pacakge inside the project.
But when I am trying to pack the (outer) project with `pyarmor pack` or directly with pyinstaller, I am getting this error:
`Could not find "<path to dist folder>/dist/tsaf/pytransform_vax_******/platforms/linux/x86_64/_pytransform_vax_******.so"`

I also tried to put manually .so file inside `/dist/tsaf/pytransform_vax_******/`. Then there is another error: `ImportError: cannot import name 'submodule1' from partially initialized module 'tsaf' (most likely due to a circular import) (<path to dist folder>/dist/tsaf/__init__.pyc)
[104976] Failed to execute script main`

Initially I thought that the problem is in imports in my code, but the thing is that with usage of non-obfuscated version of package, I don't receive this error. Also, when running my project not as executable but as a python script (with obfuscated package), I don't receive this error as well.

Could you suggest any fix for these problems?

**Comment by jondy** [comment]
I think all of these folder and files
```
├── pytransform_vax_******
|       ├ __init__.py
|       └_pytransform_vax_******.so
```
could be replaced with this one file
```
├── pytransform_vax_******.so
```

**Comment by jondy** [comment]
Is `task/__init__.py` obfuscated or not? If it's obfuscated, please check the content of this file, it's normal python script, make sure there is no circular import.

I suggest first look through this documentation
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

**Comment by gospodima** [comment]
`tsaf/__init__.py` is obfuscated and I don't see any circular imports there. Also, the obfuscated package is working fine inside the project. The problem occurs only when I am trying to pack the project inside executable (with pyarmor pack or pyinstaller). So, I also don't have an option to investigate scripts there, unfortunately.

**Comment by gospodima** [comment]
Sorry, I found out that with older package version it is working. So the issue regarding circular import is somewhere on my side.

But could you also clarify, whether it is somehow possible to automatically catch pytransform .so file during the executable generation?

**Comment by jondy** [comment]
PyInstaller has an option `--debug noarchive`, by this option all the collected files are stored in one folder, not in an archive.

pyarmor self doesn't cause any circular import issue.

**Comment by gospodima** [comment]
Thanks!

I see now that the problem is that pyinstaller doesn't catch any submodule that was not imported in non-obfuscateed code. Even if some submodule is imported, pyinstaller packs only `init` file of that module. (e.g, if I import `tsaf.submodule2` then in `dist/tsaf/submodule2` I will have only `__init__.pyc` file, even though in this init file I have imports for other files)

I see one option to add all package files to `hiddenimports`, but is there any automatic way to do that?

**Comment by jondy** [comment]
Refer to https://pyarmor.readthedocs.io/en/latest/man.html#pack

About the usage of `--additional-hooks-dir`

**Comment by gospodima** [comment]
Thank you

I have managed to run it after adding all submodules and dependency modules via hooks.
