### ISSUE TITLE
get_license_info error

### ISSUE THREAD

**Issue by allran** [dashingsoft/pyarmor#54]
```
from pyarmor.pytransform import get_license_info, get_expired_days
print(get_license_info())
```
### then get the follow error:

  File "/Users/allran/PycharmProjects/competition/authorization/utils.py", line 22, in auth_license_code
    print(get_license_info())
  File "/Users/allran/.local/share/virtualenvs/competition/lib/python3.6/site-packages/pyarmor/pytransform.py", line 114, in get_license_info
    rcode = get_registration_code().decode()
  File "/Users/allran/.local/share/virtualenvs/competition/lib/python3.6/site-packages/pyarmor/pytransform.py", line 31, in wrap
    result = func(*args, **kwargs)
  File "/Users/allran/.local/share/virtualenvs/competition/lib/python3.6/site-packages/pyarmor/pytransform.py", line 86, in get_registration_code
    dlfunc = prototype(('get_registration_code', _pytransform))
AttributeError: 'NoneType' object has no attribute '_handle'

### Note: the current version like this
```
MacBook-Pro:competition allran$ pyarmor --version
```
PyArmor Trial Version 5.1.2
PyArmor is a command line tool used to obfuscate python scripts, bind
obfuscated scripts to fixed machine or expire obfuscated scripts.

**Comment by jondy** [comment]
Generally `get_license_info` is used to query license information of the obfuscated script, refer to

https://pyarmor.readthedocs.io/en/latest/pytransform.html#examples

Copy those examples code to `foo.py`, obfuscate `foo.py`, then run obfuscated `foo.py`

**Comment by allran** [comment]
1. In the foo.py, i write this codes:
```
from pyarmor.pytransform import get_license_info, get_expired_days

def hello(msg):
  print('Hello! %s' % msg)
  print(get_license_info())

```
2. And then, i obfuscate the file like this:
```
pyarmor obfuscate --output=dist/mypkg src/examples/testpkg/mypkg/__init__.py
```
3. I create a file sff.py like this:
```
from dist.mypkg.foo import hello
hello('ssssss')
```
4.  I run the sff.py, and get the same error:

```
(competition) MacBook-Pro:pyarmor-master-2 allran$ python dist/mypkg/sff.py 
Hello! ssssss
Traceback (most recent call last):
  File "dist/mypkg/sff.py", line 3, in <module>
    hello('ssssss')
  File "<frozen mypkg.foo>", line 5, in hello
  File "/Users/allran/.local/share/virtualenvs/competition/lib/python3.6/site-packages/pyarmor/pytransform.py", line 114, in get_license_info
    rcode = get_registration_code().decode()
  File "/Users/allran/.local/share/virtualenvs/competition/lib/python3.6/site-packages/pyarmor/pytransform.py", line 31, in wrap
    result = func(*args, **kwargs)
  File "/Users/allran/.local/share/virtualenvs/competition/lib/python3.6/site-packages/pyarmor/pytransform.py", line 86, in get_registration_code
    dlfunc = prototype(('get_registration_code', _pytransform))
AttributeError: 'NoneType' object has no attribute '_handle'

```

**Comment by allran** [comment]
I have another question:
if the expired timeout, when i run the project and then it cann't start like this:

```
/Users/allran/.virtualenvs/competition/bin/python /Users/allran/PycharmProjects/competition/manage.py runserver 8000
b'License is expired\nInitialize pytransform failed'

Process finished with exit code 1
```
I want start the project, and then auth the code inside some where. So how to get it, thank you?

**Comment by jondy** [comment]
In the foo.py, replace
```from pyarmor.pytransform import get_license_info, get_expired_days```
with
```from pytransform import get_license_info, get_expired_days```

In the obfuscated scripts, the module `pytransform` should be imported from `dist/mypkg/pytransfrom.py`, not from package `pyarmor`.

Image the obfuscated scripts could be copied to another machine in which there is no pyarmor installed, refer to
https://pyarmor.readthedocs.io/en/latest/usage.html#distributing-obfuscated-scripts

**Comment by jondy** [comment]
> I want start the project, and then auth the code inside some where. So how to get it, thank you?

There is a solution for this case:
1. Do not generate expired license for obfuscated scripts, use the default `license.lic`
2. Add any auth code in your python script, do what ever you want to do

For example, 
```
from ntplib import NTPClient
from time import mktime, strptime

NTP_SERVER = 'europe.pool.ntp.org'
EXPIRED_DATE = '20190202'

c = NTPClient()
response = c.request(NTP_SERVER, version=3)
if response.tx_time > mktime(strptime(EXPIRED_DATE, '%Y%m%d')):
    sys.exit(1)
```

**Comment by allran** [comment]
Hi. It now not allowed the project start when expired out. I just want with a custom page to verify the license code in the project

The file 'license.lic' of expired is never. How to add auth code with pyarmor. Your mean is the auth code is not use pyarmor?
Thanks.

**Comment by jondy** [comment]
Yes, do not check expired date by pyarmor. But verify the date in your own python scipts.
