### ISSUE TITLE
Traceback (most recent call last):   File "obfuscated.py", line 1, in <module> ModuleNotFoundError: No module named 'pytransform'

### ISSUE THREAD

**Issue by ViceDaMan69** [dashingsoft/pyarmor#540]
I use pyarmor to obfuscated my code, compiled used py2exe it I open it with cmd it gives the the following error:

Traceback (most recent call last):   File "obfuscated.py", line 1, in <module> ModuleNotFoundError: No module named 'pytransform'

pip installing pytransform doesnt work, while trying to pip install pytransform I get the following error:

https://hastebin.com/dugikadida.rust

pytransform.py is in site-packages/pyarmor/pytransform.py

anyone know why? I installed vsredist

I added the print(sys.path) for debugging and it gave the following output

```
['D:\\projects\\Project Tissue', 'C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip', 'C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python39\\DLLs', 'C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python39\\lib', 'C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python39', 'C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages', 'C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\win32', 'C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\win32\\lib', 'C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\Pythonwin']
Traceback (most recent call last):
  File "D:\projects\Project Tissue\obfuscated.py", line 3, in <module>
    from pytransform import pyarmor_runtime
ModuleNotFoundError: No module named 'pytransform'
```

**Comment by jondy** [comment]
Please first understand what's the obfuscated scripts, refer to
http://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

Then pack all the runtime files to final package
