### ISSUE TITLE
how to let others encrypt for me with my license safely

### ISSUE THREAD

**Issue by eric-et** [dashingsoft/pyarmor#542]
I want my colleague to encrypt my project for me with my license. What registration files shall I share to him? I have the license.lic and the capsule.zip. He needs a license because the trial version limits file size.

I can run the final encrypting command myself but before that he needs to figure out the right .pyarmor_config for the project.

What's the proper way to do this?

Thanks

**Comment by jondy** [comment]
The only way is to share your reg file to others, but the latest version uses txt reg file, it may not work only copying license.lic.

Refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#global-capsule
https://pyarmor.readthedocs.io/en/latest/license.html#purchase
