### ISSUE TITLE
'utf-8' codec can't decode byte 0xe2 in position 1: invalid continuation byte

### ISSUE THREAD

**Issue by chimokosmo** [dashingsoft/pyarmor#543]
Hey I'm having error after packing script with pyarmor.

Command that im using: ```pyarmor pack -x "--recursive --bootstrap 2 --advanced 2 --enable-suffix --no-cross-protection " -e "--onefile --icon=ICON.ico"  --clean --name=NAME __init__.py```

Traceback: 'utf-8' codec can't decode byte 0xe2 in position 1: invalid continuation byte

This may be caused by russian signs that are in api response that im printing, everything works until its exported to exe, with pyinstaller only error is there as well.

Can you guys help me?

**Comment by jondy** [comment]
How about using repack script?
https://pyarmor.readthedocs.io/en/latest/advanced.html#repack-pyinstaller-bundle-with-obfuscated-scripts

The other way is use `-s` to specify spec file, and set right source encoding in the spec file. Refer to
https://pyarmor.readthedocs.io/en/latest/man.html#pack
https://pyarmor.readthedocs.io/en/latest/questions.html#source-code-encoding
