### ISSUE TITLE
pyarmor supermode

### ISSUE THREAD

**Issue by JKKSI** [dashingsoft/pyarmor#548]
Hello there
i encrypt my python file with https://development-tools.net/python-obfuscator/ for encrypt code with base64 and magic

later i encrypt my python file with pyarmor 
the command is ... pyarmor obfuscate --platform windows.x86 --platform linux.x86_64 --with-license licenses/r001/license.lic --plugin check_ntp_time --advanced 2 file.py

(the file got encrypted with pyarmor version  6.6.2 and later of encrypt i updated my pyarmor to Version 6.7.3 , but my question is if i encrypted the file in pyarmor 6.6.2 version, and later i update to 6.7.3, the encrypted file updates?, or i need to encrypt again?

the 2 question i have with the --advanced 2 is sufficient for including a proffessional person on "criptography" decrypt the pyarmor with --advanced 2? talking abour 5 - 10 % of chance of decrypt it (i encrypted the file with version 6.6.2) ?, i hope your answer soon

I ask because am worried my file get decrypted because i share it already with license hehe

**Comment by jondy** [comment]
> (the file got encrypted with pyarmor version 6.6.2 and later of encrypt i updated my pyarmor to Version 6.7.3 , but my question is if i encrypted the file in pyarmor 6.6.2 version, and later i update to 6.7.3, the encrypted file updates?, or i need to encrypt again?
>

Please refer to
https://pyarmor.readthedocs.io/en/latest/change-logs.html#incompatible-issues
 
> the 2 question i have with the --advanced 2 is sufficient for including a proffessional person on "criptography" decrypt the pyarmor with --advanced 2? talking abour 5 - 10 % of chance of decrypt it (i encrypted the file with version 6.6.2) ?, i hope your answer soon
> 

About 1% I think.

**Comment by JKKSI** [comment]
> > (the file got encrypted with pyarmor version 6.6.2 and later of encrypt i updated my pyarmor to Version 6.7.3 , but my question is if i encrypted the file in pyarmor 6.6.2 version, and later i update to 6.7.3, the encrypted file updates?, or i need to encrypt again?
> 
> Please refer to
> https://pyarmor.readthedocs.io/en/latest/change-logs.html#incompatible-issues
> 
> > the 2 question i have with the --advanced 2 is sufficient for including a proffessional person on "criptography" decrypt the pyarmor with --advanced 2? talking abour 5 - 10 % of chance of decrypt it (i encrypted the file with version 6.6.2) ?, i hope your answer soon
> 
> About 1% I think.

ok thanks :)
