### ISSUE TITLE
Calling objcopy on Linux in repack.py should wait for the process to terminate before proceeding further

### ISSUE THREAD

**Issue by ntamas** [dashingsoft/pyarmor#549]
`repack.py` uses `Popen` to call `objdump` in order to update the `pydata` section in the executable. However, calling `Popen()` does not wait for the process to terminate; it simply forks the process and continues the execution of the Python code. This can lead to subtle bugs when someone imports `repacker` from `repack.py` as part of a larger toolchain as it may happen that `objdump` has not finished doing its thing by the time `repacker` returns.

`Popen` returns a process object; you should call `wait()` on the process object to wait for termination, or simply use `check_call()` from the `subprocess` module. The latter has the added bonus of raising an exception if `objdump` returns with a non-zero error code.

**Comment by jondy** [comment]
Thanks, not all python versions support `check_call`, so I prefer to call `wait`

**Comment by ntamas** [comment]
Sure, no problem (although `check_call()` was added in Python 2.5 so it's pretty much everywhere now). If you use `wait()`, you need to check the `returncode` property of the process on your own, though, to notice when `objdump` failed for any reason.

**Comment by jondy** [comment]
You're right, I made a mistake, :) I'll refine the code with `check_call`.

**Comment by jondy** [comment]
Fix it in v6.7.4
