### ISSUE TITLE
About hard disk serial numbers.

### ISSUE THREAD

**Issue by 2232549876** [dashingsoft/pyarmor#55]
My OS is _Win10_.

When I manually looked up the serial number of my hard drive, I was given an 8-digit number: `'WDEVZK62'`.

And what I showed when I looked it up on the pyarmor command line was `'WDEVZK62    WDEVZK62'` (20-digit,four spaces in between).

Different brands have different sequence Numbers (usually 8-digit or 14-digit), so does pyarmor always use 20-digit sequence Numbers for binding (for unified formats)?

When I use the figure pyarmor gives, I get an error:

`E:\Python2.7\PyarmorTest-Py27\Src\dist>pyarmor licenses --bind-disk 'WDEVZK62    WDEVZK62' --bind-mac '8c:16:45:2b:04:ba' code002`
`usage: pyarmor [-h] [-v] [-q] <command> ...`
`pyarmor: error: unrecognized arguments: code002`

Before I used the serial number I found manually, I reobfuscated the code and then successfully bound it. 
I manually copied license.lic to the dist folder again, but when py file was run later, pyarmor did not think that the serial number was corresponding to this computer.

`E: Python2.7\ pyarmortest-py27 \Src>pyarmor licenses --bind-disk 'WDEVZK62' --bind-mac '8c:16:45:2b:04:ba' code002`
`INFO Generate licenses with capsule C:\Users\22325\. Pyarmor_capsule. Zip...`
`INFO Make output path of licenses: licenses`
`INFO The license files generated is in restrict mode`
`The INFO Make path: licenses \ code002`
`The INFO the Generate license: * HARDDISK: 'WDEVZK62' * IFMAC: '8 c: 16:45:2 b: 04: ba' * CODE: code002`
`INFO Write license file: licenses\code002\license.lic`
`INFO Write information to licenses\code002\license.lic. TXT`
`INFO Generate 1 licenses OK.`

`E: \ Python2.7 \ PyarmorTest - Py27 \ Src > CD dist`
`E: \ Python2.7 \ PyarmorTest - Py27 \ Src \ dist > python code002. Py`
`License is not for this machine`

Now I'm so confused.

**Comment by 2232549876** [comment]
This is what I got when I used the query drive disk in the CMD window:

`E: \ Python2.7 \ PyarmorTest - Py27 \ Src \ dist > wmic diskdrive get serialnumber`
`SerialNumber`
`0025 _38b1_81bf_f024.`
`WDEVZK62`

This was a little strange, so I used a professional tool to look up the details of both disks at the same time.

One of the serial Numbers is: WDEVZK62
The other serial number is: S35FNX1k100570

I think pyarmor should be able to properly identify the first SN, or when I use the command "hdinfo" to give that SN.

**Comment by jondy** [comment]
First, replace `'` with `"` in the command line, run this commd:
```
E:\Python2.7\PyarmorTest-Py27\Src\dist>pyarmor licenses --bind-disk "WDEVZK62 WDEVZK62'' --bind-mac "8c:16:45:2b:04:ba" code002
```

What PyArmor get double serial numbers, :) I need to check it. It should get the same value as other tools.

**Comment by 2232549876** [comment]
Thank you for your advice, finally passed!
