### ISSUE TITLE
Including files to a package, even if they are not to be obfuscated

### ISSUE THREAD

**Issue by luizbarcelos** [dashingsoft/pyarmor#552]
I have a PyArmor project in place for obfuscating a certain percentage of a Python package's `.py` files. I add the files that I don't want obfuscated to the manifest inside `.pyarmor_config`. I would expect those files that were not obfuscated to be copied to the output as-is for the case of a package (`is_package` = 1), but that is not the case, they are not copied at all. Is there a configuration that makes PyArmor copy files that were excluded in MANIFEST as-is to the resulting package (i.e. after PyArmor's build)?

If there is not a way, I'll need to post-process the result of PyArmor's package obfuscation to reassemble the package again, not a pain but nonoptimal. This reasoning considers that PyArmor's build is in place one step before building the package's `whl`, and that all files inside a package are necessary for it to work, even those that were not obfuscated.

**Comment by jondy** [comment]
The data files include in the manifest could be copied to the output path, for `.py` files , all of them will be obfuscated. 

After building, you need copy the original plain scripts to `dist` path to overwrite the obfuscated ones.

**Comment by luizbarcelos** [comment]
That's the solution I was going for @jondy , thanks for the reply, although the Python version issue related to #553 is a showstopper for my project. Thank you very much for your attention.
