### ISSUE TITLE
RuntimeError: unexpected /project/path/pytransform/_pytransform.so

### ISSUE THREAD

**Issue by shubham-quartic** [dashingsoft/pyarmor#554]
I have multiple modules in a directory which I am trying to obfuscate with pyarmor using ` 'pyarmor obfuscate --restrict 0 --recursive` in pyarmor version `6.7.3` individually for each of these modules. Code is successfully obfuscated.
Running the python program (file has bootstrap code), I get this exception:

```
Traceback (most recent call last):
  File "</home/project/dir/script.py>", line 3, in <module>
  File "<frozen script>", line 70, in <module>
  File "<frozen script>", line 65, in protect_pytransform
  File "<frozen script>", line 57, in check_lib_pytransform
RuntimeError: unexpected /home/project/dir/pytransform/_pytransform.so
```

**Comment by jondy** [comment]
Please refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#protection-fault-unexpected-xxx

**Comment by jondy** [comment]
> I have multiple modules in a directory which I am trying to obfuscate with
> pyarmor using 'pyarmor obfuscate --restrict 0 --recursive in pyarmor version
> 6.7.3 individually for each of these modules. Code is successfully
> obfuscated.
> Running the python program (file has bootstrap code), I get this exception:
>
> Traceback (most recent call last):
>   File "</home/project/dir/script.py>", line 3, in <module>
>   File "<frozen script>", line 70, in <module>
>   File "<frozen script>", line 65, in protect_pytransform
>   File "<frozen script>", line 57, in check_lib_pytransform
> RuntimeError: unexpected /home/project/dir/pytransform/_pytransform.so
>

Please refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#protection-fault-unexpected-xxx

**Comment by shubham-quartic** [comment]
This was solved using `pyarmor build` instead of `pyarmor obfuscate` for some reason.
