### ISSUE TITLE
VM mode with Pyarmor pack?

### ISSUE THREAD

**Issue by Spencer-0003** [dashingsoft/pyarmor#556]
At the moment I'm using
```
pyarmor pack --clean -e "--onefile --icon icon.ico " file_name.py
```
to pack, is there a way to choose the obfuscation (preferably VM mode) mode using pack too?

**Comment by jondy** [comment]
Refer to http://pyarmor.readthedocs.io/en/latest/man.html#pack

**Comment by Spencer-0003** [comment]
Thanks, I'll take a look at it now :)
