### ISSUE TITLE
Invalid platform name for VM mode?

### ISSUE THREAD

**Issue by tonglei100** [dashingsoft/pyarmor#557]
想用 pip 发布加密包，使用 --advanced 4  模式
C:\Users\leo\hello>pyarmor runtime --enable-suffix -O dist/share --advanced 4  
INFO     PyArmor Version 6.7.3
INFO     Python 3.9.6
INFO     Update target platforms to: ['windows.x86_64.25.py39']
INFO     ====================================================
INFO     Reload PyArmor with platform: windows.x86_64.21
INFO     ====================================================
INFO     PYARMOR_PLATFORM is windows.x86_64.21
INFO     Generating super runtime library to "dist\share"
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying C:\Users\leo\.pyarmor\platforms\windows\x86_64\25\py39\pytransform.pyd
INFO     Rename extension to pytransform_vax_00xxxx.pyd
INFO     Patch extension dist/share\pytransform_vax_00xxxx.pyd
INFO     Patch library file OK
INFO     Generate runtime files OK
INFO     Generating protection script ...
INFO     Generate protection script "dist/share\pytransform_protection.py" OK
INFO     Generating bootstrap script ...
INFO     Generate bootstrap script "dist/share\pytransform_bootstrap.py" OK

使用这个运行辅助文件来加密包
C:\Users\leo\hello>pyarmor obfuscate --with-license outer --with-runtime @dist/share --advanced 4 --recursive --exclude lib --plugin check_ntp_time --output hello  src/__init__.py 
INFO     PyArmor Version 6.7.3
INFO     Python 3.9.6
INFO     Got settings from prebuilt runtime path "dist/share"
INFO         Platforms: windows.x86_64.25.py39
INFO         Advanced: 4
INFO         Suffix: _vax_00xxxx
INFO         License: embedded
INFO     Target platforms: ['windows.x86_64.25.py39']
ERROR    Invalid platform name for VM mode

报错了

**Comment by jondy** [comment]
This is a bug, please apply this patch 2816aa9c4583123ba306c449e3815c8a70980a45

Or install the pre-release version 6.7.5
https://pyarmor.readthedocs.io/en/latest/change-logs.html#pre-release

**Comment by jondy** [comment]
One more thing, please specify `--with-license outer` in the command `runtime`. It's useless in the command `obfuscate` if `--with-runtime` is used.

**Comment by tonglei100** [comment]
OK，使用6.7.5可以了
另外，我想问一下，直接生成的 pytransform.pyd 和 pytransform _vax_00xxxx.pyd 有什么区别？
我试了一下

假设 pytransform.pyd 加密的代码为 A
pytransform _vax_00xxxx.pyd 加密的代码为 B

那么我把 pytransform _vax_00xxxx.pyd  改名为 pytransform.pyd 给 A 使用，A也是可以正常运行的
但是，把 pytransform.pyd 改名为 pytransform _vax_00xxxx.pyd，B 无法正常运行

请问这里有什么区别呢

**Comment by tonglei100** [comment]
OK，使用6.7.5可以了
另外，我想问一下，直接生成的 pytransform.pyd 和 pytransform _vax_00xxxx.pyd 有什么区别？
我试了一下

假设 pytransform.pyd 加密的代码为 A
pytransform _vax_00xxxx.pyd 加密的代码为 B

那么我把 pytransform _vax_00xxxx.pyd  改名为 pytransform.pyd 给 A 使用，A也是可以正常运行的
但是，把 pytransform.pyd 改名为 pytransform _vax_00xxxx.pyd，B 无法正常运行

请问这里有什么区别呢

**Comment by tonglei100** [comment]
OK，使用6.7.5可以了
另外，我想问一下，直接生成的 pytransform.pyd 和 pytransform _vax_00xxxx.pyd 有什么区别？
我试了一下

假设 pytransform.pyd 加密的代码为 A
pytransform _vax_00xxxx.pyd 加密的代码为 B

那么我把 pytransform _vax_00xxxx.pyd  改名为 pytransform.pyd 给 A 使用，A也是可以正常运行的
但是，把 pytransform.pyd 改名为 pytransform _vax_00xxxx.pyd，B 无法正常运行

请问这里有什么区别呢

**Comment by jondy** [comment]
请参考这里
https://pyarmor.readthedocs.io/zh/latest/man.html#obfuscate

**Comment by jondy** [comment]
Fix in v6.8.0
