### ISSUE TITLE
多个脚本相互调用如何加密被调用脚本

### ISSUE THREAD

**Issue by shgefu** [dashingsoft/pyarmor#558]
我现在是 python 3.6 环境， 程序有多个文件， 界面程序A会生成一个非加密python脚本B，然后A会使用 subprocess.Popen函数启动cmd运行B，B会调用程序C的逻辑， 现在我想对C进行加密，因为C里面含有想保护的逻辑。困难在于B不是加密的， 而我想对C进行加密，如何解决？

**Comment by jondy** [comment]
请参考这里
https://pyarmor.readthedocs.io/zh/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

pyarmor 有完整的文档，把这部分的内容仔细读一下，并浏览一下里面提到的相关章节，至多花费半个小时，可以解决你的所有问题
https://pyarmor.readthedocs.io/zh/latest/questions.html#id8

**Comment by jondy** [comment]
另外，Pyarmor 不提供即时技术支持，这里的问题基本是每天定时进行处理
