### ISSUE TITLE
Problems assert_armored

### ISSUE THREAD

**Issue by FlorianREGAZ** [dashingsoft/pyarmor#559]
Hey, 

I'm currently trying to prevent monkey patching by trying to use the "assert_armored" decorator.

Thats how my function looks like:
```
# PyArmor Plugin: from pytransform import assert_armored
# PyArmor Plugin: @assert_armored(library1, library2, library3, library4)
def check_armored():
    return True
```

Thats the command, I'm using:
```
python "C:\Program Files\Python38\Lib\site-packages\pyarmor\pyarmor.py" pack -x " --advanced 2 --bootstrap 2 --enable-suffix  --exclude tests --exclude load --exclude venv --plugin on" -e " -c --onefile " --icon iconblau.ico" --with-license licenses/regcode-01/license.lic main.py
```

Thats the error I get: 
```
Traceback (most recent call last):
  File "<dist\obf\main.py>", line 2, in <module>
  File "<frozen main>", line 11, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "<general\security.py>", line 2, in <module>
  File "<frozen general.security>", line 32, in <module>
ModuleNotFoundError: No module named 'pytransform'
[3752] Failed to execute script 'main' due to unhandled exception
```

Thanks in advance, and I'm very sorry for wasting your time, I'm pretty sure it is a dump mistake, however I wasn't able to find the issue.

**Comment by FlorianREGAZ** [comment]
I just found out that it is most likely due to the `--advanced 2` option. 
I'm not an expert with pyarmor, however I would like to keep the advanced protection. 
Is there anything I can do to use both?

**Comment by jondy** [comment]
It's not related to `--advanced 2`, but `--enable-suffix`. Please check the runtime module name in the output path `dist`, it should be like `pytransform_vax_xxxxxxx`, then fix the plugin with right module name
``` patch
- # PyArmor Plugin: from pytransform import assert_armored
+ # PyArmor Plugin: from pytransform_vax_xxxxxx import assert_armored
```

**Comment by FlorianREGAZ** [comment]
Thank you very much, I'll give it a try and let you know!

**Comment by FlorianREGAZ** [comment]
Worked perfectly, thank you very much!
