### ISSUE TITLE
pyarmor obfuscate 命令执行不了

### ISSUE THREAD

**Issue by dcxAccuRad** [dashingsoft/pyarmor#56]
pyarmor obfuscate examples/simple/queens.py
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 27, in <module>
    from CommandNotFound.util import crash_guard
ModuleNotFoundError: No module named 'CommandNotFound'

已经执行了pip install  pyarmor，也安装成功了；然后cd pyarmor/src/ 运行pyarmor obfuscate examples/simple/queens.py 找不到命令

**Comment by jondy** [comment]
如果使用 `pip install pyarmor` 应该没有 `pyarmor/src/` 这个目录吧，:)

首先看一下 pip 执行完成之后提示的安装路径在哪里，在一堆输出信息里面，应该有可执行文件 pyarmor 的安装路径，确认安装路径在环境变量 PATH 里面

另外一种方法，执行下面的命令，直接查找
`find /usr -name pyarmor`
看看究竟装在哪里，直接切换到该目录执行
