### ISSUE TITLE
Failed to get harddisk information.

### ISSUE THREAD

**Issue by jkl375** [dashingsoft/pyarmor#561]
我用centos和ubuntu的docker容器里运行pyarmor hdinfo，出现以下情况：

![图片](https://user-images.githubusercontent.com/54523287/129174346-548a5a29-97a3-41f4-a276-769309dda6c8.png)

**Comment by jondy** [comment]
请参考 docker 的文档，在启动的时候把硬盘挂上。另外 pyarmor 不是支持所有的硬盘接口，对不支持的硬盘类型，请编写插件自己实现。
