### ISSUE TITLE
Os Error

### ISSUE THREAD

**Issue by T-Dynamos** [dashingsoft/pyarmor#564]
It's more readable in the issue Preview mode for the hints

When running the obfuscated scripts, if there is traceback, check the source script according to script name and line number in the traceback, make sure it doesn't use some features changed by pyarmor 

Before report a bug, please read these common questions and solutions first
https://pyarmor.readthedocs.io/en/latest/questions.html

And remove all the above hints.

**Describe the bug**

```
~ $ pyarmor obfuscate  /data/data/com.termux/file/usr/bin/mbot
ERROR    dlopen failed: cannot locate symbol "getdomainname" referenced by "/data/data/com.termux/files/home/.pyarmor/platforms/android/aarch64/0/_pytransform.so"...
~ $
... 
```

**Comment by jondy** [comment]
Please upgrade pyarmor to latest version, duplicated issue of #372
