### ISSUE TITLE
请问用pyarmor进行加密和运行加密脚本的python版本可以不一样吗？

### ISSUE THREAD

**Issue by bytedynamic** [dashingsoft/pyarmor#565]
我通过用python3.8的版本对pyarmor进行加密，在python3.7版本的平台上会报告“Marshal loads failed”。查看文档说“检查运行加密脚本的 Python 的版本和加密脚本的 Python 版本是否一致“。
请问如何在不同python版本的平台上运行加密的脚本？

**Comment by jondy** [comment]
使用相同的 python 版本进行加密。

**Comment by bytedynamic** [comment]
> 使用相同的 python 版本进行加密。

那如何批量生成不同版本python适用的加密后py脚本呢？只能通过python虚拟环境做吗？

**Comment by jondy** [comment]
请参考文档中高级用法里面的”使用不同的Python版本加密脚本“

**Comment by zmister2016** [comment]
@jondy 你好，请问一下，「高级用法」中的[《通过其他 Python 版本混淆脚本》](https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-scripts-by-other-python-version)是否只是针对不同 Python 版本分别加密脚本。

如果需要「一份加密后的脚本，支持在多个 Python 版本下运行」，需要怎么做呢？

**Comment by jondy** [comment]
@zmister2016 刚刚实现这个功能，请从这里下载开发版本

https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.7.5.zip

并使用辅助脚本 `pyarmor.helper.merge`
https://github.com/dashingsoft/pyarmor/blob/master/src/helper/merge.py
