### ISSUE TITLE
pyarmor execute

### ISSUE THREAD

**Issue by JKKSI** [dashingsoft/pyarmor#566]
hello there, is possible to make that my file cant be executed double time in same time, i mean i want that when any person execute my script he be abble to execute it 1  time at the same time, and he dont be abble to execute it multipple times, if is possible can you give me the command maybe? hehe i hope your answer soon

**Comment by JKKSI** [comment]
and have other question, is there a command for convert my .py encrypted with pyarmor to a exe file?, if is there can you please provide me the command?, i ask because auto-py-to-exe dont working with pyarmor , i hope your answer soon

**Comment by jondy** [comment]
> hello there, is possible to make that my file cant be executed double time in same time, i mean i want that when any person execute my script he be abble to execute it 1 time at the same time, and he dont be abble to execute it multipple times, if is possible can you give me the command maybe? hehe i hope your answer soon

The obfuscated scripts are normal python scripts, it could be run as the normal python scripts




> and have other question, is there a command for convert my .py encrypted with pyarmor to a exe file?, if is there can you please provide me the command?, i ask because auto-py-to-exe dont working with pyarmor , i hope your answer soon


The pack command is right for this, please read the man page in the documentation. If you have any question about pack, find the solution here
http://pyarmor.readthedocs.io/en/latest/questions.html
