### ISSUE TITLE
Jetson Nano Use SD Card:  Failed to get hard disk information

### ISSUE THREAD

**Issue by blakenguyen97** [dashingsoft/pyarmor#567]
Hi, I tried to use SN binding but PyArmor can not find my SD card information. I use Jetson NANO with an SD card attached to it. Thank you

<img width="321" alt="image" src="https://user-images.githubusercontent.com/52020800/130437584-307ef404-b6f0-43bc-9150-d74657338cc2.png">

**Comment by jondy** [comment]
Not all the harddisk types are supported by pyarmor, if pyarmor could not get the harddisk information, please write your plugin to query hardware information. Refer to
https://github.com/dashingsoft/pyarmor/tree/master/plugins
