### ISSUE TITLE
Apple Silicon Pyarmor Stuck at registration

### ISSUE THREAD

**Issue by manisharora** [dashingsoft/pyarmor#568]
I am unable to register pyarmor on Apple M1 Macbook, terminal just keep running and nothing happens 

Python : 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:00:30) 
Pyarmor version 6.7.4

Output of:
**pyarmor -d download**     

DEBUG    PyArmor installation path: /Users/manisharora/miniforge3/lib/python3.9/site-packages/pyarmor
DEBUG    PyArmor home path: /Users/manisharora/.pyarmor
DEBUG    Native platform is darwin.aarch64
DEBUG    Search dynamic library in the path: /Users/manisharora/miniforge3/lib/python3.9/site-packages/pyarmor/platforms
DEBUG    Search dynamic library in the path: /Users/manisharora/.pyarmor/platforms
DEBUG    Found available dynamic library darwin/aarch64/3

**Comment by willwrong** [comment]
Hi Jondy,

I'm running into a similar issue, not able to register or do anything else on Apple Silicon:

```user@Mac-2 root % export PYARMOR_PLATFORM=darwin.aarch64
user@Mac-2 root % pip3 install pyarmor
Collecting pyarmor
  Using cached pyarmor-6.7.4-py2.py3-none-any.whl (2.3 MB)
Installing collected packages: pyarmor
Successfully installed pyarmor-6.7.4
WARNING: You are using pip version 20.2.3; however, version 21.2.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.
user@Mac-2 root % export PYARMOR_PLATFORM=darwin.aarch64.0
user@Mac-2 root % pyarmor register /Volumes/USB/pyarmor-regcode-1589.txt
INFO     PYARMOR_PLATFORM is darwin.aarch64.0
ERROR    dlopen(/Users/user/.pyarmor/platforms/darwin/aarch64/0/_pytransform.dylib, 6): no suitable image found.  Did find:
	/Users/user/.pyarmor/platforms/darwin/aarch64/0/_pytransform.dylib: mach-o, but wrong architecture
	/Users/user/.pyarmor/platforms/darwin/aarch64/0/_pytransform.dylib: mach-o, but wrong architecture
```

Any suggestions? Thank you.

**Comment by jondy** [comment]
What's the output of this script in this machine?
```python
import platform
print(platform.system(), platform.machine())
```

**Comment by jondy** [comment]
@willwrong Please also try this pre-release version, I rebuild the dynamic library for Apple Silicon
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.7.5.zip
```

**Comment by willwrong** [comment]
@jondy Hi Jondy, tried that, and successfully registered the license. However when attempting to pack, I encounter the following:

```INFO     ==================== Run command ====================
INFO     PyArmor Version 6.7.5
INFO     Python 3.9.6
INFO     Target platforms: Native
ERROR    No available dynamic library for darwin.aarch64.8.py39 with features ['8']
INFO     ==================== End command ====================

ERROR    Run command failed
```

Running `PYARMOR_PLATFORM=darwin.aarch64.0 pyarmor --version` results in the following:

```PYARMOR_PLATFORM=darwin.aarch64.0 pyarmor --version
INFO     PYARMOR_PLATFORM is darwin.aarch64.0
PyArmor Version 6.7.5
Registration Code: pyarmor-vax-001589

Error: <urlopen error timed out>

PyArmor is a command line tool used to obfuscate python scripts, bind
obfuscated scripts to fixed machine or expire obfuscated scripts.

For more information, refer to https://pyarmor.readthedocs.io
```

Let me know if you have any ideas -- thank you!

**Comment by jondy** [comment]
@willwrong the platform `darwin.aarch64.0` doesn't work with super mode. Please clear environment `export PYARMOR_PLATFORM=` or set it to `export PYARMOR_PLATFORM=darwin.aarch64.3`, check it works or not.

**Comment by willwrong** [comment]
After clearing I receive `[Errno 1] Operation not permitted`, and once I set to darwin.aarch64.3 I get a `verify dynamic library failed, try to reinstall` response.

**Comment by jondy** [comment]
@willwrong it seems the new libraries isn't downloaded completed, please remove cached platform files, then run it again
```
rm -rf ~/.pyarmor/platforms
PYARMOR_PLATFORM=darwin.aarch64.3 pyarmor ...
```

**Comment by willwrong** [comment]
Hi Jondy,

Sorry, taken a while for me to get back around to this.

At the moment I can't access your pyarmor.dashingsoft.com domain -- is it offline at the moment?

Thanks.

**Comment by jondy** [comment]
willwrong ***@***.***> writes:

> Hi Jondy,
>
> Sorry, taken a while for me to get back around to this.
>
> At the moment I can't access your pyarmor.dashingsoft.com domain -- is it
> offline at the moment?
>

It works fine. Try to add this ip to /etc/hosts

pyarmor.dashingsoft.com 119.23.58.77


> Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 
Best Regards
Jondy Zhao

**Comment by onekiloparsec** [comment]
Hello. I stil have this exact same issue. I followed your advices:

```bash
rm -rf ~/.pyarmor/platforms
PYARMOR_PLATFORM=darwin.aarch64.3 pyarmor --version
```

which gives:

```bash
INFO     PYARMOR_PLATFORM is darwin.aarch64.3
INFO     Create cross platform libraries path /Users/onekiloparsec/.pyarmor/platforms
INFO     Search library for platform: darwin.aarch64.3
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/index.json
INFO     Write cached platform list file /Users/onekiloparsec/.pyarmor/platforms/index.json
WARNING  The trial version could not download the latest core libraries, tag r41.15a is always used
WARNING  The core library excepted version is r46.20, but got r41.15a from platform list file /Users/onekiloparsec/.pyarmor/platforms/index.json
INFO     Found available libraries: ['darwin.aarch64.3']
INFO     Target path for darwin.aarch64.3: /Users/onekiloparsec/.pyarmor/platforms/darwin/aarch64/3
INFO     Downloading library file for darwin.aarch64.3 ...
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/darwin.arm64.3/_pytransform.dylib
INFO     Writing target file: /Users/onekiloparsec/.pyarmor/platforms/darwin/aarch64/3/_pytransform.dylib
INFO     Download dynamic library darwin.aarch64.3 OK
```

and it is stuck there. I can't even make a `Ctrl-C`. I've bought a licence, and I have the same problem when registering.

**Comment by onekiloparsec** [comment]
It works with `PYARMOR_PLATFORM=darwin.aarch64.0` (i.e. `.0`, not `.3`)

**Comment by fdv1** [comment]
I am also experiencing the same issue (registration hangs forever on Apple silicon). Jondy are you working on it?

**Comment by jondy** [comment]
How about the latest version 7.3.0?

**Comment by fdv1** [comment]
That's the one I am using. I tried to specify the platform as suggested above but I get the following error:
 PyArmor installation path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor
DEBUG    PyArmor home path: /Users/francois/.pyarmor
DEBUG    Native platform is darwin.x86_64
INFO     PYARMOR_PLATFORM is darwin.aarch64.0
DEBUG    Build platform is darwin.aarch64.0
DEBUG    Search dynamic library in the path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/platforms
DEBUG    Search dynamic library in the path: /Users/francois/.pyarmor/platforms
INFO     Search library for platform: darwin.aarch64.0
DEBUG    Load platform list from /Users/francois/.pyarmor/platforms/index.json
INFO     Found available libraries: ['darwin.aarch64.0']
INFO     Target path for darwin.aarch64.0: /Users/francois/.pyarmor/platforms/darwin/aarch64/0
INFO     Downloading library file for darwin.aarch64.0 ...
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/darwin.arm64.0/_pytransform.dylib
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pyarmor", line 8, in <module>
    sys.exit(main_entry())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/pyarmor.py", line 1599, in main_entry
    main(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/pyarmor.py", line 1587, in main
    pytransform_bootstrap(capsule=DEFAULT_CAPSULE, force=args.boot)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/utils.py", line 153, in pytransform_bootstrap
    rid = download_pytransform(platid, libpath, firstonly=1)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/utils.py", line 311, in download_pytransform
    raise RuntimeError('Verify dynamic library failed, try to '
RuntimeError: Verify dynamic library failed, try to reinstall the latest pyarmor and run "pyarmor download -u" to fix it

[1]  + 26562 exit 1     PYARMOR_PLATFORM=darwin.aarch64.0 pyarmor -d register pyarmor-regcode-2337.tx

**Comment by jondy** [comment]
Please try this pre-release version
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-7.3.1.zip
```

**Comment by fdv1** [comment]
Still no joy…

(3.10) ➜  3.10 python -c "import platform; print(platform.system(), platform.machine())"                         
Darwin arm64
(3.10) ➜  3.10 pip install -e pyarmor-7.3.1
Obtaining file:///Users/francois/Projects/reflect_dist/3.10/pyarmor-7.3.1
  Preparing metadata (setup.py) ... done
Installing collected packages: pyarmor
  Running setup.py develop for pyarmor
Successfully installed pyarmor-7.3.1
(3.10) ➜  3.10 pyarmor register ../../reflect-3.7/infra/pyarmor-regcode-2337.txt
34270 killed     pyarmor register ../../reflect-3.7/infra/pyarmor-regcode-2337.txt
(3.10) ➜  3.10 pyarmor -d register ../../reflect-3.7/infra/pyarmor-regcode-2337.txt &
[1] 34366
DEBUG    PyArmor installation path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor
DEBUG    PyArmor home path: /Users/francois/.pyarmor
DEBUG    Native platform is darwin.aarch64
DEBUG    Search dynamic library in the path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/platforms
DEBUG    Search dynamic library in the path: /Users/francois/.pyarmor/platforms
DEBUG    Found available dynamic library darwin/aarch64/3
(3.10) ➜  3.10 PYARMOR_PLATFORM=darwin.aarch64.0 pyarmor -d register ../../reflect-3.7/infra/pyarmor-regcode-2337.txt 
DEBUG    PyArmor installation path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor
DEBUG    PyArmor home path: /Users/francois/.pyarmor
DEBUG    Native platform is darwin.aarch64
INFO     PYARMOR_PLATFORM is darwin.aarch64.0
DEBUG    Build platform is darwin.aarch64.0
DEBUG    Search dynamic library in the path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/platforms
DEBUG    Search dynamic library in the path: /Users/francois/.pyarmor/platforms
INFO     Search library for platform: darwin.aarch64.0
DEBUG    Load platform list from /Users/francois/.pyarmor/platforms/index.json
INFO     Found available libraries: ['darwin.aarch64.0']
INFO     Target path for darwin.aarch64.0: /Users/francois/.pyarmor/platforms/darwin/aarch64/0
INFO     Downloading library file for darwin.aarch64.0 ...
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/darwin.arm64.0/_pytransform.dylib
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pyarmor", line 8, in <module>
    sys.exit(main_entry())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/pyarmor.py", line 1599, in main_entry
    main(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/pyarmor.py", line 1587, in main
    pytransform_bootstrap(capsule=DEFAULT_CAPSULE, force=args.boot)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/utils.py", line 153, in pytransform_bootstrap
    rid = download_pytransform(platid, libpath, firstonly=1)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/utils.py", line 311, in download_pytransform
    raise RuntimeError('Verify dynamic library failed, try to '
RuntimeError: Verify dynamic library failed, try to reinstall the latest pyarmor and run "pyarmor download -u" to fix it

**Comment by jondy** [comment]
Please remove the whole folder "/Users/francois/.pyarmor/platforms", then try it again.

**Comment by fdv1** [comment]
Sorry for my delayed answer I confirm it does work with this version. Running pyarmor in x86_64 mode in the meantime...

(3.10) ➜  3.10 python -c "import platform; print(platform.system(), platform.machine())"
Darwin arm64
(3.10) ➜  3.10 pip install -e pyarmor-7.3.1
Obtaining file:///Users/francois/Projects/reflect_dist/3.10/pyarmor-7.3.1
  Preparing metadata (setup.py) ... done
Installing collected packages: pyarmor
  Attempting uninstall: pyarmor
    Found existing installation: pyarmor 7.3.1
    Uninstalling pyarmor-7.3.1:
      Successfully uninstalled pyarmor-7.3.1
  Running setup.py develop for pyarmor
Successfully installed pyarmor-7.3.1

**Comment by yp-oerp** [comment]
This is still not working for me.. I'm using Apple m1(Darwin arm64)..  I have tried each and every solution which was given here. @fdv1 how did you resolve it?
@jondy please advise. Thank you.

**Comment by fdv1** [comment]
Hi Yash,

I think jondy send me a bcorrected version.

Best, 
François

**Comment by agutierrez78** [comment]
I just ran into this problem and this solution does not work for me. Using 7.3.1 and getting the error below. Any help, please?

<img width="1440" alt="Screen Shot 2022-09-15 at 1 35 57 PM" src="https://user-images.githubusercontent.com/113640762/190506806-6d7c445f-dba2-4156-a61e-8850760da515.png">

**Comment by agutierrez78** [comment]
> Hi Yash, I think Jondy send me a corrected version. Best, François
> […](#)
> On 11 Apr 2022, at 23:40, Yash Pathak ***@***.***> wrote: ﻿ This is still not working for me.. I'm using Apple m1(Darwin arm64).. I have tried each and every solution which was given here. @fdv1 how did you resolve it? @jondy please advise. Thank you. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

Could you please share this corrected version? I'm a bit confused about which version has the fix...

**Comment by ChristianMarchetta** [comment]
I've tried every solution listed above but nothing works on Macbook Air M1.

As it seams someone managed to get it working, could anyone please share a working version?
