### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_pytransform_vax_0000xx)

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#571]
Linux python 3.7, 3.8, 3.9 with latest pyarmor is giving the error (running pyarmor 6.8.0)

 `ImportError: dynamic module does not define module export function (PyInit_pytransform_vax_0000xx)` 
 
Is the runtime broken?

Windows is running fine...

**Comment by VeNoMouS** [comment]
I purged the runtime's and rebuilt and appear to be working now.. weird as i had purged them already..

**Comment by VeNoMouS** [comment]
its kind of like the same bug we had in #442 but disabling suffix doesnt resolve it

**Comment by VeNoMouS** [comment]
Downgrading to 6.7.4. resolved the issue.

**Comment by jondy** [comment]
It works fine in my test machines with `--enable-suffix`. Please make sure the libraries are downloaded successfully.

**Comment by VeNoMouS** [comment]
Yea, I tried several times... the only thing that worked for rolling back to 6.7.4, i have py 3.7, 3.8 and 3.9 installed on my dev system, i removed platforms/* several times... the only thing that worked was rolling back to 6.7.4

I can... test again, but i doubt it will change.. as i spent 3hrs looking into it

**Comment by VeNoMouS** [comment]
Does the runtime downloader verify the hash of the download, is that something you could implement if the download is indeed incorrect?

**Comment by jondy** [comment]
downloader will verify the hash, but if the downloading process is broken by `Ctrl+C' or something else, it may leave uncompleted file.

**Comment by jondy** [comment]
Please run pyarmor with debug option `-d`, then check there is a debug log like this
```
pyarmor -d obfuscate ...

...
DEBUG: Found marker at xxxxxx
```

**Comment by jondy** [comment]
@VeNoMouS I found the problem, I'm checking it now.

**Comment by jondy** [comment]
Please try this pre-release version
```
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.8.1.zip
```

**Comment by VeNoMouS** [comment]
confirmed, works

**Comment by VeNoMouS** [comment]
@jondy i noticed this

```
    call_pyarmor(
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/pyarmor.py", line 1560, in main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/pyarmor.py", line 688, in _obfuscate
    checklist = make_runtime(capsule, output, platforms=platforms,
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/utils.py", line 572, in make_runtime
    return _make_super_runtime(capsule, output, platforms, licfile=licfile,
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/utils.py", line 1513, in _make_super_runtime
    data = _patch_extension(target, keylist, suffix)
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/utils.py", line 1445, in _patch_extension
    raise RuntimeError('Failed to add symbol suffix for library %s'
RuntimeError: Failed to add symbol suffix for library dist//xxxxx/pytransform_vax_xxxx.so
```

for darwin 3.9

**Comment by VeNoMouS** [comment]
Not sure what is up but users are getting the same issue as last time... 

`NameError: name '__armor_wrap_vax_0000xx__' is not defined`

even re-installing your temp... and clearing out the runtimes.. i';m going to ahve to downgrade to 6.7.4... ;(

**Comment by jondy** [comment]
It's reproduced, I'm checking it.

**Comment by jondy** [comment]
Please try temp version, I update it now
```
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.8.1.zip
```

But it seems v6.7.4 should not work either for Darwin py39 if  `--enable-suffix` is set.

**Comment by VeNoMouS** [comment]
pretty sure I was on the temp already, unless you have updated that again?

i'll re-test and let you know

**Comment by VeNoMouS** [comment]
Rgr Rgr, will test the temp and let you know
