### ISSUE TITLE
fail in macOs

### ISSUE THREAD

**Issue by jiangdydy** [dashingsoft/pyarmor#572]
I used pyarmor 6.8.0 and python 3.9.6 to pack my pyqt5 program at macos which using m1 chip.
And the program flash back when I try to open it.
I use this command pyarmor pack --name  ***.app  -e "-F --key *** -w --icon ./****.ico" main.py
How can I do?

**Comment by jondy** [comment]
Refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#the-final-bundle-does-not-work
