### ISSUE TITLE
c:\users\xxx\.pyarmor\.pyarmor_capsule.zip 文件做什么用的？

### ISSUE THREAD

**Issue by shgefu** [dashingsoft/pyarmor#574]
软件加密发布给用户后，发现c:\users\xxx\.pyarmor目录下有.pyarmor_capsule.zip文件解压缩打开含有private.key之类敏感字眼的文件，难道是私钥 ？

**Comment by jondy** [comment]
pyarmor 不会把这个文件发布出去的，请检查自己的发布代码，这个文件不能发布给客户，请参考
https://pyarmor.readthedocs.io/zh/latest/understand-obfuscated-scripts.html

**Comment by shgefu** [comment]
说的我有点怕了，我是在测试机器上安装Pyarmor然后发现这个文件的，我反复确认好像没有从加密机发布这个文件给测试机， 是不是pyarmor安装后默认有此文件，用于试用版？

**Comment by jondy** [comment]
运行环境是不需要安装 pyarmor 的，第一次运行 pyarmor 会生成这个文件，不过是试用版的。
