### ISSUE TITLE
MacOS cannot pack simple flask app

### ISSUE THREAD

**Issue by Mitsu-4419** [dashingsoft/pyarmor#575]
Hello, i just try to pakage simple flask app by pyarmor. On windows, it works fine, but on Mac OS, it does not.

My environment is,

macOS Big Sur, v11.2.3
python 3.8.7 (pyenv)
pyarmor 6.8.0
pyinstaller 4.5.1
Flask 2.0.1
Flask-Cors 3.0.10

Directory
├── helloworld.py
├── poetry.lock
└── pyproject.toml

helloworld.py

![スクリーンショット 2021-09-13 10 35 26](https://user-images.githubusercontent.com/40463798/133011486-b3c9b7a7-9c7f-48b4-bcc3-39722b8f2d1a.png)

I put command  ```pyarmor pack --clean -e "--onefile " helloworld.py```
then, get dist/helloworld file.
![スクリーンショット 2021-09-13 10 37 17](https://user-images.githubusercontent.com/40463798/133011617-e36b2cb8-0d0a-463b-a4f8-64eeb912dac6.png)

However, when I run ``` dist/helloworld```
the error message below always comes up, 

![スクリーンショット 2021-09-13 10 39 01](https://user-images.githubusercontent.com/40463798/133011719-1b2576e1-d79c-42f9-ae7f-cd9bdab4d625.png)

I already check (https://pyarmor.readthedocs.io/en/latest/questions.html#the-final-bundle-does-not-work)
but could not solve this issue.

Please give me some advices, thank you!!

**Comment by jondy** [comment]
Please do not obfuscate system library, exclude the path `.venv` when obfuscating the scripts. Refer to man page found all the options of command `pack`

**Comment by Mitsu-4419** [comment]
Dear jondy,

Thank you for reply!
I tried ```pyarmor pack -e " --onefile" -x " --exclude venv" helloworld.py``` and ```pyarmor pack -e " --onefile" -x " --exclude .venv" helloworld.py``` but still could not run the app.

<img width="834" alt="スクリーンショット 2021-09-13 13 56 49" src="https://user-images.githubusercontent.com/40463798/133026315-70743660-bfaf-4672-8e2f-675c8347d0be.png">

The above error occur.
Do you have any ideas?

**Comment by jondy** [comment]
Pass extra option `--no-cross-protection' to `-x`
