### ISSUE TITLE
NameError: name '__pyarmor__' is not defined

### ISSUE THREAD

**Issue by xennygrimmato** [dashingsoft/pyarmor#58]
I am unable to run my obfuscated scripts. I am using `Pyarmor 5.2.3` and Python 2.7.15.
If it matters, I also compile .py files to .pyc using python's `compileall` option _after_ obfuscation.

I am using the linux_x86_64 version of _pytransform.so. When I run `import pytransform` in the Python shell, I get this error:

```
>>> import pytransform
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<local_path>/pytransform.py", line 1, in <module>
NameError: name '__pyarmor__' is not defined
```

Output of the `file` program on _pytransform.so:

```
_pytransform.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=1021b1f5a19aa67584b87e61812d749be8c533db, stripped
```

Running `import pyarmor` in the Python shell works fine though.

What could possibly be the issue?

**Comment by jondy** [comment]
No bootstrap code in the obfuscated script, refer to 
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#bootstrap-code

**Comment by xennygrimmato** [comment]
Bootstrap code is indeed present in the obfuscated script.

**Comment by jondy** [comment]
It seems that you obfuscated `pytransorm.py` too, is it?  This is the only file could not be obfuscated. It's a key to open the door of obfuscated scripts, but you put the key in the room, :)
