### ISSUE TITLE
RuntimeError: The runtime library doesn't support Advanced Mode

### ISSUE THREAD

**Issue by mabuyun** [dashingsoft/pyarmor#580]
**Hints**

**Describe the bug**
运行脚本 `python3 app.py`
直接运行加密后的脚本，输出 `Segmentation fault`
加 -d 运行后， `RuntimeError: The runtime library doesn't support Advanced Mode`

**To Reproduce**
Which pyarmor version is used, trial or purchased, and steps to reproduce the behavior:
1. Obfuscate the scripts by which Python version and in which platform
   * PyArmor Version 6.5.4
   * python 3.6.9
   * ubuntu
2. What command options used
   * --advanced 1  --recursive 
3. How to distribute the obfuscated scripts to target machine if it's different from build machine
   * 加密完的包直接拷贝过去
4. Run the obfuscated scripts in which platform by which Python version
   * 目标平台是 redhat, python 3.6.9
5. When see error, provide the full traceback and console output by text not snapshot, quote them like this
```
python3 -d app.py
Initialize python patcher failed (66964)
Traceback (most recent call last):
  File "<pulsar.py>", line 4, in <module>
RuntimeError: The runtime library doesn't support Advanced Mode
```

**Additional context**
直接在 ubuntu 平台上运行无报错

**Comment by mabuyun** [comment]
加密时去掉 --advanced 1 ， 在 redhat 上也正常了，我希望有更通用的解决方法，这样不用为两个平台维护

**Comment by jondy** [comment]
`--advanced 1` 是在汇编层对 Python 解释器进行打补丁的，所以这种方式通用性会差一些。
现在推荐使用的是 `--advanced 2`，这就需要升级 Python 到3.7 或者更高版本，如果一定要使用 Python3.6，那解决方案就是都不用 `--advanced 1`，因为这种模式目前已经不在去更新。
