### ISSUE TITLE
Restrict mode when obfuscating many packages

### ISSUE THREAD

**Issue by RobinFrcd** [dashingsoft/pyarmor#582]
Hello,
I'm trying to obfuscate many packages at one using: https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-many-packages.

My packages have this structure:

```
company/
├── __init__.py
├── pkg1/
│   ├── __init__.py
│   └── files.py
├── pkg2/
│   ├── __init__.py
│   └── files.py
```

With `company/__init__.py` being `__path__ = __import__("pkgutil").extend_path(__path__, __name__)`.

I'm running

```
pyarmor init --src company/pkg1 --entry __init__.py pkg1
pyarmor init --src company/pkg2 --entry __init__.py pkg2

pyarmor runtime --output dist --advanced 2 --platform linux.x86_64 --platform darwin.x86_64

pyarmor build --output dist --no-runtime pkg1
pyarmor build --output dist --no-runtime pkg2
```

But I'd like to also use the 4th restrict mode https://pyarmor.readthedocs.io/en/latest/mode.html?highlight=restrict#restrict-mode, but I don't see this parameter in any of the commands (init, runtime or build). Is it possible to do it ?

Thanks

**Comment by jondy** [comment]
Refer to command `config` in the man page, or `pyarmor config -h`

**Comment by RobinFrcd** [comment]
Oh, I didn't see this command, my bad.

Thank you very much and have a nice day !
