### ISSUE TITLE
Can't files that are obfuscated with pyarmor be used in cygwin64 environment?

### ISSUE THREAD

**Issue by JangKyumin** [dashingsoft/pyarmor#584]
I am conducting a test by applying Django to nginx and uwsgi in cygwin64 environment.

I was going to obfuscate it with pyarmor to distribute the source.

However, the following phrase occurs and cannot be implemented.

```
Platform cygwin_nt-10.0-19043 not supported
```
https://pyarmor.readthedocs.io/en/v5.6.1/platforms.html
If you look at the link, it seems to be a platform that is not supported.

Does pyarmor not support the cygwin platform?
I'd appreciate it if you could answer. :)

**Comment by jondy** [comment]
How about specify the option `--platform windows.x86_64` when obfuscating the scripts?

**Comment by JangKyumin** [comment]
@jondy I tried obfuscating with the options you mentioned in Windows. However, when applied to Cygwin, the same platform "cygwin_nt-10.0-19043 not supported" phrase appears and does not run.

**Comment by jondy** [comment]
I test it using windows.x86_64 in the Cygwin, but find an issue. It may fix in next major version (v5.9.0).

At this time, the work way is to obfuscate the scripts in other platform and set `--platform windows.x86_64`, then copy them to Cygwin, also rename `pytransform/_pytransform.dll` to `pytransform/_pytransfrom.so`

**Comment by JangKyumin** [comment]
@jondy 

Thank you for your answer.

Based on what you said, the contents I understood are as follows.

1. Currently, files obfuscated to `window.x86_64` are not available in cygwin
2. When it is updated to version 6.9.0 in the future, it is obfuscated to `window.x86_64` on another platform and copied to cygwin
3. It can be used by modifying `pytransform/_pytransform.dll` to `pytransform/_pytransform.so`

If there is an update schedule for the 6.9.0 version you mentioned additionally, I would appreciate it if you could share it.

**Comment by jondy** [comment]
In v6.9.0, Pyarmor should use in the Cygwin normally if there is no other issues. It's just an alias of windows. 

As my plan, v6.9.0 may be released in next month someday. There is another big feature introduced in this version, I need more tests and not sure the exact day.

**Comment by jondy** [comment]
And at this time, it need not rename `pytransform/_pytansform.dll`, obfuscating with extra option `--no-cross-protection` should work.

**Comment by JangKyumin** [comment]
@jondy 

I fully understand about the meticulous test. I look forward to the update next month.

Thank you for your kind reply :)

**Comment by jondy** [comment]
I have fixed the Cygwin issue in the v6.8.1, and it's released today. Please upgrade pyarmor to v6.8.1, it should work in the Cygwin. Before start pyarmor, remove the whole pyarmor home path in the Cygwin: `rm -rf ~/.pyarmor`

**Comment by JangKyumin** [comment]
@jondy 

Hello

After purchasing the license, we are conducting a test to apply the same to cygwin.

There was an additional problem, so the issue was reopened.

Prior to applying the license, the obfuscated project with the instructions below ran normally in nginx and uwsgi environments.

```
pyarmor obfuscate --platform windows.x86_64 --src="C:\test" -r --output=C:\obf_test test\base\__init__.py
```

However, if you register a license using 'pyarmor register' and proceed with obfuscation, the process will not run normally.

```
pyarmor obfuscate --with-license C:\test\license.lic --platform windows.x86_64 --src="C:\test" -r --output=C:\obf_test test\base\__init__.py
```

I wonder if I should work separately on the applied platform if I proceed with obfuscation after registering the license.

For your information, a simple output.If you obfuscate the py file, it ran normally without any extra work.

**Comment by jondy** [comment]
If the trial version work, please make a clean uninstallation to make sure there is no any thing generated by trial version,
refer to
https://pyarmor.readthedocs.io/en/latest/installation.html#clean-uninstallation

**Comment by JangKyumin** [comment]
@jondy 

Thank you for your answers.   

However, we tried to proceed in the way you told us, but the process did not go up the same way. 
Just in case, I searched all directories, deleted all files related to pyarmor, and proceeded.

Since Windows obfuscates and proceeds, I erased the pyarmor installed on the pip, erased all registered license information, and installed it again.

As a reference, I will explain the environment and method I have conducted.

First, the development environment is as follows.

- Windows is the OS for obfuscation.
- Use python version 3.5.4.
- Use pyarmor version 7.0.2.
- Use obfuscated projects for nginx and uwsgi in cygwin environments.
 
The methods of obfuscation are as follows.

1. I installed the latest version of pyarmor with 'ip install pyarmor' in a Windows environment.
2. You have registered a license with 'pip register my_license' in a Windows environment.
3. In the Windows environment, 'pyarmorobfuscate --platform window.x86_64 --src="C:\test" -r --output=C:\obf_test\base\__init_' and copied the files created on output to the home directory under the cygwin environment.
4. When starting the uwsgi service in cygwin, the process usually starts normally when the phrase 'Djangol load checks...' appears, but obfuscated files do not start the process settlementally.

If my method is wrong or there is a problem with the recent update of cygwin, please give me feedback.

I always express my gratitude for your efforts. Thank you :)

**Comment by jondy** [comment]
So does the trial version still work?

**Comment by JangKyumin** [comment]
@jondy 

Hello

When obfuscated to pyarmor 7.0.2 version trial and applied to cygwin, the phrase `Check license failed, Invalid input packet.` occurs.

**Comment by jondy** [comment]
Please refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

Make sure the entry script has bootstrap code.

**Comment by JangKyumin** [comment]
@jondy 

Yes, I already checked it.
__init__.The py has a bootstrap code as follows.
```
from .pytransform import pyarmor_runtime
pyarmor_runtime()
```

**Comment by JangKyumin** [comment]
> Please refer to https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts
> 
> Make sure the entry script has bootstrap code.

The bootstrap code is in the __init__ as follows.
```
from .pytransform import pyarmor_runtime
pyarmor_runtime()
```

However, as a result of calling and checking 'pytransform._load_library' by referring to the contents written in the document,

1. 'mysite.pytransform.pytransformError: Could not find' ./mysite/pytransform/platforms/windows/x86_64/_pytransform.dll' result came out and created it on that path.
2. As a result of re-executing after creation, the phrase 'Check bootstrap restrict mode failed' occurs.

**Comment by jondy** [comment]
It doesn't work to insert bootstrap code into `__init__.py` manually, please obfuscate `__init__.py` as entry script.

Refer to the last section
https://pyarmor.readthedocs.io/en/latest/mode.html#restrict-mode

> For your information, I use the limited mode as --restrict=0
If the license is generated by command `licenses`, pass option `--restrict 0` to `licenses`, not to command `obfuscate`

**Comment by JangKyumin** [comment]
> It doesn't work to insert bootstrap code into `__init__.py` manually, please obfuscate `__init__.py` as entry script.
> 
> If the license is generated by command `licenses`, pass option `--restrict 0` to `licenses`, not to command `obfuscate`

I proceeded with obfuscation with the command below, but the same phrase `Check bootstrap restrict mode failed` is occurring. 

```
pyarmor obfuscate --with-license C:\licenses\test\license.lic --platform windows.x86_64 --restrict 0 --src="C:\mysite" -r --output=C:\obf_site mysite\__init__.py
```

I designated it as an entry script through `mysite\_init__.py` and changed the option from `--restrict=0` to `--restrict 0` to proceed with obfuscation.

**Comment by jondy** [comment]
If the obfuscates scripts uses the license generated by :ref:`licenses`, in order to disable all the restricts, pass option ``--disable-restrict-mode`` to command :ref:`licenses`. For example
```
    pyarmor licenses --disable-restrict-mode r001

    pyarmor obfuscate --with-license=licenses/r001/license.lic foo.py

    # For project
    pyarmor config --with-license=licenses/r001/license.lic
    pyarmor build -B
```

**Comment by JangKyumin** [comment]
Thank you for your answers.   

I did it in the way you just told me.

Now, the phrase 'Check bootstrap restrict mode failed' does not come out.

However, symptoms that do not run in uwsgi are the same.

```
Tue Nov 16 13:40:24 2021 - machine: x86_64
Tue Nov 16 13:40:24 2021 - clock source: unix
Tue Nov 16 13:40:24 2021 - detected number of CPU cores: 6
Tue Nov 16 13:40:24 2021 - current working directory: /cygdrive/c/windows/system32
Tue Nov 16 13:40:24 2021 - writing pidfile to /var/run/uwsgi/uwsgi_obf_site.pid
Tue Nov 16 13:40:24 2021 - detected binary path: /usr/bin/uwsgi
Tue Nov 16 13:40:24 2021 - !!! no internal routing support, rebuild with pcre support !!!
Tue Nov 16 13:40:24 2021 - chdir() to /home/obf_site
Tue Nov 16 13:40:24 2021 - your memory page size is 4096 bytes
Tue Nov 16 13:40:24 2021 - detected max file descriptor number: 3200
Tue Nov 16 13:40:24 2021 - lock engine: windows mutexes
Tue Nov 16 13:40:24 2021 - thunder lock: enabled
Tue Nov 16 13:40:24 2021 - uwsgi socket 0 bound to TCP address 127.0.0.1:8100 fd 3
Tue Nov 16 13:40:24 2021 - Python version: 3.5.7 (default, Jul 21 2019, 14:28:55)  [GCC 7.4.0]
Tue Nov 16 13:40:24 2021 - *** Python threads support is disabled. You can enable it with --enable-threads ***
Tue Nov 16 13:40:24 2021 - Python main interpreter initialized at 0x80009eb40
Tue Nov 16 13:40:24 2021 - your server socket listen backlog is limited to 5000 connections
Tue Nov 16 13:40:24 2021 - your mercy for graceful operations on workers is 60 seconds
Tue Nov 16 13:40:24 2021 - mapped 145840 bytes (142 KB) for 1 cores
Tue Nov 16 13:40:24 2021 - *** Operational MODE: single process ***
Tue Nov 16 13:40:24 2021 - *** uWSGI is running in multiple interpreter mode ***
Tue Nov 16 13:40:24 2021 - spawned uWSGI master process (pid: 3416)
Tue Nov 16 13:40:24 2021 - spawned uWSGI worker 1 (pid: 3421, cores: 1)
Tue Nov 16 13:40:25 2021 - !!! uWSGI process 3421 got Segmentation Fault !!!
Tue Nov 16 13:40:25 2021 - DAMN ! worker 1 (pid: 3421) died :( trying respawn ...
Tue Nov 16 13:40:25 2021 - Respawned uWSGI worker 1 (new pid: 3449)
```
I want to solve this problem, but it's heartbreaking that it can't be solved even if I try many ways.

**Comment by JangKyumin** [comment]
@jondy 

Is there any way to solve a problem that doesn't start normally in uwsgi?

**Comment by jondy** [comment]
If the obfuscate scripts could work in Cygwin, it should work in uwsgi.

But it's out of my support, please take the obfuscated scripts as normal script, and check uwsgi document to solve it. It need not change Pyarmor anything.

**Comment by JangKyumin** [comment]
Yes, I checked the answer.

As you said, we will judge that there is no problem with Pyarmor.

Of course, the normal script is running normally on uwsgi, but I'll try to run it as a obfuscated script.

If there is an additional problem, we will contact you.
Thank you.
