### ISSUE TITLE
[Feature Request] Python 3.10

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#590]
Hi @jondy,

Sorry if you have already, but could you do / add runtimes for py 3.10?

https://www.python.org/downloads/release/python-3100/

thank you sir :)

**Comment by jondy** [comment]
v7.1.0 has been released to support Python 3.10

**Comment by VeNoMouS** [comment]
thanks @jondy will test over next couple days ❤️
