### ISSUE TITLE
Download mirrors for runtime package in Europe?

### ISSUE THREAD

**Issue by rtechencheng** [dashingsoft/pyarmor#592]
Hi, sometimes I have faced such issue:
```
| INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/linux.aarch64.11.py39/pytransform.cpython-39-aarch64-linux-gnu.so
| INFO     Could not get file from https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms: HTTP Error 404: Not Found
| INFO     Getting remote file: https://pyarmor.dashingsoft.com/downloads/r41.15a/linux.aarch64.11.py39/pytransform.cpython-39-aarch64-linux-gnu.so
| INFO     Could not get file from https://pyarmor.dashingsoft.com/downloads/r41.15a: <urlopen error timed out>
| ERROR    Download library file failed
```
Is it possible to make a new mirror which is more stable to use for EU customers?
I am working with CI which I hope I could have a smooth automated flow without being blocked by an unreachable URL.

**Comment by jondy** [comment]
I have no plan to make new mirror download servers, please download the necessary libraries to local machine by manual, do not download them from remote server every time. Refer to
https://pyarmor.readthedocs.io/en/latest/platforms.html#downloading-dynamic-library-by-manual

**Comment by rtechencheng** [comment]
I see. Thanks.
Could it be a nice feature to have with this option to specify the platform library path?
The reason is that we are running fakeroot or pseudo, which might be a little too much overhead to pass in `~/.pyarmor` or setup `PYARMOR_HOME`.

**Comment by rtechencheng** [comment]
OK, thanks a lot!
