### ISSUE TITLE
"from pytransform import pyarmor_runtime" failing in Maya-Python

### ISSUE THREAD

**Issue by AKEric** [dashingsoft/pyarmor#594]
**Describe the bug**
The first line in my obfuscated code is failing:
`from pytransform import pyarmor_runtime import`
`# ModuleNotFoundError: No module named 'pytransform' # `

**To Reproduce**
Happens on any obfuscated module I run in Maya-Python

**Additional context**
Very new PyArmor user, but long time Python coder.  
I'm on Win10 using : 
`3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]`
Running inside the DCC app Autodesk Maya :  Similar to other major DCC apps (Max, Houdini, MotionBuilder, etc) they each have their own custom cut of Python running in their own REPL editors/interpreters.  
I first tried reading obfuscated modules generated via a previously installed system-level (Anaconda) version of PyArmor, and was getting Maya-Python `marshal` errors trying to read the bytecode.  
So I used Maya's custom mayapy.exe &  \Scripts\pip.exe to install pyarmor.exe into Maya-Python \Scripts dir, which worked a-ok.  So it's good to know that one can install a specific version of PyArmor that works in Maya-Python.

Doing tests, if I obfuscate 'system-level' (non-DCC app related, via Anaconda) modules:
`Python 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32`
The above `ModuleNotFoundError` _doesn't_ happen.  So "That's good".

But, the relative import code as-is appears to be an older style (Python2): In Python3 I (and modules ported via scripts like 2to3) do this:
`from .pytransform import pyarmor_runtime import`
If I manually edit it as such, everything starts to work in Maya-Python.

Am very interested in using / paying for the tool, but I can't be manually editing import lnies every time I re-obfuscate the code :)

Thoughts on how to address?  Appreciated!

**Comment by AKEric** [comment]
FYI, interesting/varying behavior:  Above I was obfuscating a single module via:
`pyarmor obfuscate --exact myModule.py` 
Which gives me this style relative import (causing me issues):
`from pytransform import pyarmor_runtime import`

If I try instead obfuscating the entire package via:
`pyarmor obfuscate --recursive --output dist/myPackage myPackage/__init__.py`
I get the import-style I'd expect
`from .pytransform import pyarmor_runtime`
And it all works.

**Comment by rudraksh1997** [comment]
Traceback (most recent call last):
  File "analysis_service_v9/app.py", line 1, in <module>
    from .pytransform import pyarmor_runtime
ImportError: attempted relative import with no known parent package
