### ISSUE TITLE
Unable to execute any plugin examples successfully: "invalid syntax (<frozen foo>, line 38)"

### ISSUE THREAD

**Issue by AKEric** [dashingsoft/pyarmor#595]
New user, probably missing something obvious.  Appreciate the help.

I ran across this example:
https://github.com/dashingsoft/pyarmor/tree/master/plugins#example-4-create-license-for-multiple-machines
(Plus tried to find/read every other plugin-related doc, but none addressed the issue I'm experiencing below.)

This is something I'm interested in: I need to allow a single tool distribution to run across multiple licensed machines without needing to make a unique distro for each machine (too time consuming).  I'm following the above example, using all the example code 1:1 copied off github:
- https://github.com/dashingsoft/pyarmor/blob/master/plugins/foo.py
- https://github.com/dashingsoft/pyarmor/blob/master/plugins/check_multiple_machine.py

And inject `foo.py` with the plugin code lines according to the docs.

When I go to execute this:
`pyarmor obfuscate --plugin check_multiple_machine foo.py`

Everything works fine until the error very last line:

```
INFO     PyArmor Trial Version 6.8.1
INFO     Python 3.9.5
INFO     Target platforms: Native
INFO     Source path is "C:\temp\python\pyarmor_test"
INFO     Entry scripts are ['foo.py']
INFO     Use cached capsule C:\Users\Eric\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying c:\users\eric\miniconda3\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Patch library dist\pytransform\_pytransform.dll
INFO     Patch library file OK
INFO     Copying c:\users\eric\miniconda3\lib\site-packages\pyarmor\pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            check_multiple_machine.py -> dist\check_multiple_machine.py
INFO     Found plugin check_multiple_machine at: check_multiple_machine.py
INFO            foo.py -> dist\foo.py
INFO     Found plugin check_multiple_machine at: check_multiple_machine.py
INFO     Patch this script with plugins
INFO     Apply plugin check_multiple_machine
INFO     Patch this entry script with protection code
ERROR    invalid syntax (<frozen foo>, line 38)
```
I've repeated this process using other example plugins, and even my own sample code (just a basic hello world python module):  All of it gives the same error and line.  I've also tried executing it from different Python interpreters each with their own version of PyArmor installed, and get the same error.

I did more tests... trying to see if `foo.py` was the module with the issue, or if it was `check_multiple_machine.py`:
It's `check_multiple_machine.py` :  The last two lines look like this:
```
    if _get_hd_info() not in _get_license_data().split(';'):
        raise RuntimeError('This license is not for this machine')
```
If I edit it as such:
```
    if _get_hd_info() not in _get_license_data().split(';'):
        #raise RuntimeError('This license is not for this machine')
        pass
```
The above obfuscation code works, but clearly this won't be a very helpful plugin ;)   

lol, I must be doing something wrong, any ideas?

**Comment by jondy** [comment]
I'm curious why `raise RuntimeError('This license is not for this machine')` doesn't work.

The plugin example is just used to help the users understand how plugin work, please change it on your demand.

**Comment by AKEric** [comment]
And the plot thickens : If I change the plugin code to this:
```
def check_test():
    theReturnFromSomeCheckCode = True
    if not theReturnFromSomeCheckCode:
        # This should never run
        raise RuntimeError("Failed to pass the test")
```
`ERROR    invalid syntax (<frozen spam_check_test>, line 5)`
It still fails.  HMMM...
try this:
```
def check_test():
    theReturnFromSomeCheckCode = False
    if not theReturnFromSomeCheckCode:
        print("test")
```
`ERROR    invalid syntax (<frozen spam_check_test>, line 5)`
Same error.  Huh?
How about this:
```
def check_test():
    theReturnFromSomeCheckCode = False
    if not theReturnFromSomeCheckCode:
        pass
```
`INFO     Obfuscate 1 scripts OK.`
????
```
def check_test():
    theReturnFromSomeCheckCode = False
    if not theReturnFromSomeCheckCode:
        print("asdf")
```
`ERROR    invalid syntax (<frozen spam_check_test>, line 5)`
???

But... is there something secret about `pass`?
```
def check_test():
    theReturnFromSomeCheckCode = False
    if not theReturnFromSomeCheckCode:
        print("asdf")
        pass
```
`INFO     Obfuscate 1 scripts OK.`
Which means:
```
def check_test():
    theReturnFromSomeCheckCode = False
    if not theReturnFromSomeCheckCode:
        raise RuntimeError("Failed to pass the check!")
        pass
```
`INFO     Obfuscate 1 scripts OK.`

As it turns out, you can do this too:  Add an extra line after the last line:

```
def check_test():
    theReturnFromSomeCheckCode = False
    if not theReturnFromSomeCheckCode:
        raise RuntimeError("Failed to pass the check!")
        
        
```
`INFO     Obfuscate 1 scripts OK.`

Which means, if I edit the `check_multiple_machines.py` example to have an extra line at the bottom of the script, like so:

```
    if _get_hd_info() not in _get_license_data().split(';'):
        raise RuntimeError('This license is not for this machine')
        
        

```
And run it:
`pyarmor obfuscate --exact --plugin ../pyarmor_plugins/check_multiple_machine.py foo_check_multiple_machine.py`
Victory:
`INFO     Obfuscate 1 scripts OK.`

So it appears the lexer/parser that's reading the plugin scripts is having  really hard time if there isn't a `pass `or empty line at the bottom of the module(?)

**Comment by jondy** [comment]
First do not obfuscate the plugin script, option `--exclude xxxx.py` could be used to exclude plugin script if it's in the same path of main script. 

And generate the patched script, then check this script, for example
```python
pyarmor -d obfuscate --plugin check_multiple_machines foo.py
```
It will generate a script `foo.py.pyarmor-patched`,  check the plugin code in this file

**Comment by AKEric** [comment]
"First do not obfuscate the plugin script,..."
I'm not (right?), you can see from the above code my plugin script lives in a different directory from the obfuscated module: I'm passing in a relative path to it : I'm only obfuscating the _one_ module with the `--exact` flag (right? This is all still pretty new to me).

I've written several of my own plugins now successfully with licenses and obfuscated them:  All of them need the 'extra line' / `pass` statement / `# comment` as the last line of the plugin module, or I get the error listed above.  It's consistent / repeatable, even using different PyArmor installs in different Python interpreters. 

I'm unblocked now that I understand what I need to do to get around the error, but, from my 'very new user' point of view, this feels like a bug?  For your consideration.

**Comment by AKEric** [comment]
I've been doing all the above tests on my home PC:  Tried the same thing at work (Win 10, Python 3.7.10 ) : _and it works fine_ using your example code.

`#shrug` ?   How annoying, lol.  As someone who writes tools for people all day myself, stuff like this can be a little infuriating. 

No explanation why this is, but at least I can confirm it's apparently 'me'.

**Comment by FuckingToasters** [comment]
I get a simmilar issue, but in my case, it indicate the line with following text: `if __name__ == '__main__' which however works fine when running the not obfuscated script.
