### ISSUE TITLE
Is there a way to 'modify' a license once the user has the obfuscated code?

### ISSUE THREAD

**Issue by AKEric** [dashingsoft/pyarmor#597]
Read the docs / checked existing issues, didn't see this come up.

Say I generate a license tied to a specific hard drive ID, and obfuscate that into a module : Send that code to the user.
Later, they tell me 'they have a new PC, with a new hard drive', thus need a new license for that new hard drive ID.

- Option A: They're telling the truth:  I issue them new obfuscated code with a new license for that new hard drive. 
- Option B : They're lying, and just want to install it on another PC, while still running it on the original PC.

Is there some way to provide an 'updated license file' (presuming the old one was embedded in the obfuscated code) that can somehow modify/addendum to the existing license in the obfuscated code (if placed in the right directory?), that PyArmor would automatically check for?  So as to (for example) invalidate the old HD address and allow the new one?

**Comment by jondy** [comment]
It's difficult to implement this feature offline.

The simple solution is to write a plugin to send license info to your remote server, and check the license information by server side.
