### ISSUE TITLE
about compeatable issue

### ISSUE THREAD

**Issue by h1-ti** [dashingsoft/pyarmor#599]
>Incompatible of the license.lic

>v6.0.1

>The license file generated by this version doesn't work with the old obfuscated scripts. There are 2 solutions for this case, still >generating the license file with old version pyarmor, or obfuscating the scrips again by new version pyarmor.

>However license.lic generated by old version still works. That is to say, even all the scripts are obfuscated by new version, you >need not issue new license file to customers, because the previous license file still works.

>Incompatible of the obfuscated scripts

>Generally obfuscate part of scripts by new version, then overwrite the old scripts obfuscated by other version, it still works.

>Except the following versions:

>v6.3.0

>The scripts are obfuscated by this version and later, can not mixed with the ones obfuscated by ealier version. All the scripts must be obfuscated again and replace the old runtime files with new ones.

nothing...

**Comment by jondy** [comment]
I have reproduced it, it's really a bad bug. But the old versions could not be withdrawn, so the solution is, in the next version 5.9.0, the license will not be used in the old versions.
