### ISSUE TITLE
TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by extralaces** [dashingsoft/pyarmor#60]
Hello, 

I have followed all steps leading up to the final step of compiling with pyinstaller. I have done 

pyarmor obfuscate --output dist/obf hello.py

and from there done the 

pyinstaller --add-data dist/obf/*.lic
--add-data dist/obf/*.key
--add-data dist/obf/_pytransform.*
hello.py dist/obf/hello.py

but after that, when i paste in 

a.scripts[0] = 'hello', 'dist/obf/hello.py', 'PYSOURCE'
for i in range(len(a.pure)):
if a.pure[i][1].startswith(a.pathex[0]):
a.pure[i] = a.pure[i][0], a.pure[i][1].replace(a.pathex[0], os.path.abspath('dist/obf'), a.pure[i][2])

(with my correct script names and directory of course)

i get hit with this error

    exec(text, spec_namespace)
  File "<string>", line 21, in <module>
TypeError: 'str' object cannot be interpreted as an integer

any help is appreciated.

**Comment by jondy** [comment]
Comment all of  these lines in your `.spec` file, then run `pyinstall` to check it works or not. Then uncomment one line by one to find the exact error.

**Comment by jondy** [comment]
I reproduced this issue. To fix it, just replace
`a.pure[i] = a.pure[i][0], a.pure[i][1].replace(a.pathex[0], os.path.abspath('dist/obf'), a.pure[i][2])`
with
`a.pure[i] = a.pure[i][0], a.pure[i][1].replace(a.pathex[0], os.path.abspath('dist/obf')), a.pure[i][2]`
Notice the last parentheses is moved. from the end to ahead of last comma
