### ISSUE TITLE
Unable to access obfuscated Maya plugin code: thoughts?

### ISSUE THREAD

**Issue by AKEric** [dashingsoft/pyarmor#600]
Just paid for the full license so I can use it on my production tools.   I feel this is a bit of an edge-case issue I'm encountering, and looking for any suggestions here.  I'm not sure if this is a PyArmor issue, an issue with the API of the DCC app I'm using, or a combination thereof.

I'm writing custom 'plugins' in the DCC app Maya.  This is through their 'Maya Python API2.0'.  The plugin architecture is based on subclassing one of the core Maya plugin classes and modifying it as needed.  I have all of this running successfully in non-obfuscated code.  I'm subclassing [this specifically.](https://help.autodesk.com/view/MAYAUL/2020/ENU/?guid=__py_ref_class_open_maya_1_1_m_px_command_html)

The issue I'm encountering is when I try to 'load' a PyArmor obfuscated Maya plugin via the Maya command '[loadPlugin](https://help.autodesk.com/cloudhelp/2020/ENU/Maya-Tech-Docs/CommandsPython/loadPlugin.html)' :  It's a fairly straightfoward call via their commands api:
```
import maya.cmds as mc
pluginPath = r"C:\path\to\my\obfuscated\plugin\module.py"
mc.loadPlugin(pluginPath)
```
The above signature works a-ok on the _non_-obfuscated code.  But when I call the same thing on the obfuscated code, I get this error:
```
# Error: name '__file__' is not defined
# Traceback (most recent call last):
#   File "C:/path/to/my/obfuscated/plugin/module.py", line 1, in <module>
#     __pyarmor__(__name__, __file__, b'\x50\x59\x41\etc...', 2)
# NameError: name '__file__' is not defined # 
```
When the Maya loadPlugin command goes to load the obfuscated file, it appears the obfuscate file is erroring on it's own `__file__` arg pass?

I'm guessing this may be an issue outside the scope of PyArmor, but I figured it couldn't help to ask if you had any thoughts.  The whole point of me buying this was to specifically obfucsate this file, but it was too big to test on the free version.

**Comment by AKEric** [comment]
I can confirm that changing it to this:
`__pyarmor__(__name__, __name__, b'\x50\x59\x41\etc...', 2)`
does get me past the `loadPlugin `command error I was having above, it ends up causing _another_ error, since `__file__` inside that module now prints `package.path.to.obfuscated.module`, (aka, `__name__`) not the absolute path on myHD that `__file__` normally does, which I need to know to pass to the `loadPlugin`command.

I've reached out to my Maya developer resources as well.

But appreciate any other thoughts you may have.

**Comment by jondy** [comment]
I guess Maya plugin uses Python2, if it's possible to use Python3, the module attribute `__file__` should work.

**Comment by AKEric** [comment]
I'm using the Maya 2023 beta which is on Python 3.7

**Comment by EzerbelCN** [comment]
I'm experiencing nearly the exact same issue with Maya 2022, Python 3.7, and PyArmor 7.7.4. 
Could you kindly share any other possible solutions? 
Thank you so much!
@AKEric  @jondy

**Comment by EzerbelCN** [comment]
It seems that Maya's plugin loading mechanism does not load modules from files, which results in the absence of the `__file__`attribute?

Because when Python loads a module, the interpreter automatically writes the`__file__` variable into the module's global namespace, right?

**Comment by EzerbelCN** [comment]
`from pytransform import pyarmor_runtime`


`pyarmor_runtime()`


`__pyarmor__`(`__name__`, 'F:\\akf_publish\\dist\\37\\akf\\apiUndo.py', b'\x50\x59\...) 

I directly hardcoded the specific value of `__file__` in this file, and it seems the plugin loading has made some progress.

This time, the error is: /pluginWin.mel line 934: No initializePlugin() function

However, the initializePlugin() function actually exists and has been declared.

**Comment by EzerbelCN** [comment]
```
mod = sys.modules[name]
def initializePlugin(mobject): pass
def uninitializePlugin(mobject): pass
mod.initializePlugin = initializePlugin
mod.uninitializePlugin = uninitializePlugin
```

I directly injected these two functions into the module, and this time the plugin loading has progressed further.

It now throws:

`SystemExit: file ....akf\pytransform_init_.py line 370: 1`


```
def pyarmor_runtime(path=None, suffix='', advanced=0):
    if _pytransform is not None:
        return

    try:
        pyarmor_init(path, is_runtime=1, suffix=suffix, advanced=advanced)
        init_runtime()
    except Exception as e:
        if sys.flags.debug or hasattr(sys, '_catch_pyarmor'):
            raise
        sys.stderr.write("%s\n" % str(e))
        sys.exit(1) # line370
```



Is it because PyArmor detected that I tampered with the code and thus exited automatically?

**Comment by EzerbelCN** [comment]
Hello, I understand this is a relatively niche and complex use case, but I hope my feedback can serve as a reference for potential support of Maya plugin loading in the future. 
I have roughly provided the reproduction steps and attempts, hoping it might inspire some ideas for improvement. 
Thank you very much for taking the time to review and consider.

**Comment by jondy** [comment]
Maya is a big application, and Pyarmor team won't install it to verify this case.

Anyway, it seems you're still using Pyarmor 7.x, please try to test the latest Pyarmor 9.x, and check this guide
https://pyarmor.readthedocs.io/en/latest/topic/obfuscated-script.html
https://pyarmor.readthedocs.io/en/latest/how-to/third-party.html

**Comment by masqu3rad3** [comment]
Hello,

I managed to obfuscate a python plugin by separating it into sections.

plugin.py -> the core bare bones such as maya_userNewAPI(), initializePlugin, unitializePlugin
source.py -> Anything that needs to be obfuscated.

initialize and unitialize method lazy import the source.py and execute the 'actual' initialize/unitialize methods.

Additionally, Maya plugins doesn't like __file__ .
Put the obfuscated source.py into one of the scripts folder, and avoid using `__file__` in the plugin.py
