### ISSUE TITLE
Super Plus Mode

### ISSUE THREAD

**Issue by Sarahaox** [dashingsoft/pyarmor#601]
I have followed the steps of installing LLVM and the clang exe in my .pyarmor directory. I cannot seem to get spp to work on my scripts. I get 0 errors when obfuscating with advanced mode 5. Is there any specific requirements to doing so? And how would i check i installed the c compiler correctly? I am doing this on windows with python 3.8 (also does it matter what version of LLVM)

**Comment by jondy** [comment]
Here it is
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-webui-1.3.2.zip

**Comment by Sarahaox** [comment]
![image](https://user-images.githubusercontent.com/92609718/137627015-5e1a012a-18bc-4f2f-963f-6b92b50dce91.png)
This is an issue i keep having even with the new pyarmor webui. It only happens when using super plus mode everything else is okay.

**Comment by jondy** [comment]
Please show logs and detail errors. And if the error message is not exact, following the line information in the traceback, add some print statement in the pyarmor source to get exact error messages.
