### ISSUE TITLE
Integrating with CI/CD

### ISSUE THREAD

**Issue by miralayipouya** [dashingsoft/pyarmor#603]
Hi there! We are using Pyarmor a while and here are some questions which I would appreciate if you can help me with them:
**Scenario**
We have a Django project and we need some development to be done on some modules of the source code; We don't want to expose the whole source code to our team members. Here are some of our requirements:
1. Is there a way that we can de-obfuscate our modules on demand? For instance I want module `X.py` to be exposed, I can run `deobfuscate.py X.py` and deliver the plain module to my developer.
2. Is there a way that I can integrate CI/CD with the project which is obfuscated by Pyarmor? Is there any similar cases which I can be inspired on how other teams manage their VCS alongside Pyarmor? For instance my developer commits the modified version of `X.py` to our git repository, and the commit will be obfuscated by an automated action of our CI/CD pipelines and placed on our VCS which is holding the obfuscated modules.
Cheers!

**Comment by jondy** [comment]
> 1. Is there a way that we can de-obfuscate our modules on demand? For instance I want module `X.py` to be exposed, I can run `deobfuscate.py X.py` and deliver the plain module to my developer.

No. pyarmor will never provide this kind of feature.

> 2. Is there a way that I can integrate CI/CD with the project which is obfuscated by Pyarmor? Is there any similar cases which I can be inspired on how other teams manage their VCS alongside Pyarmor? For instance my developer commits the modified version of `X.py` to our git repository, and the commit will be obfuscated by an automated action of our CI/CD pipelines and placed on our VCS which is holding the obfuscated modules.

pyarmor is a simple command line tool, it can be easily integrated into CI/CD pipelines, it seems many users do this, but I have no example for this. You can search "CI/CD" in the issues, may find something useful.

And the obfuscated scripts are normal python scripts, so they can be seamless to replace original scripts. How to use Python plain scripts, then how to use obfuscated scripts

Refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

**Comment by miralayipouya** [comment]
@jondy I appreciate your kind and thorough answer! for the on demand de-obfuscation problem I will use separate repositories which are holding just the modules we want the team to work with them, and we instruct our CI/CD to merge them to the main repo after each commit.
Cheers!
