### ISSUE TITLE
Apple M1 Monterey Pyarmor script killed issue

### ISSUE THREAD

**Issue by unnativentures** [dashingsoft/pyarmor#609]
After upgrading Mac to Monterey, the encrypted scripts are being killed when started,i have re-encrypted and result is same.

**Error when running in spyder ide**
/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/scripts/conda‑activate.sh: line 14: 3134 Killed: 9 $CONDA_ENV_PYTHON ‑m spyder_kernels.console ‑f $SPYDER_KERNEL_SPEC

**Error when running in terminal**
zsh: killed

Hardware:
MAC mini Apple M1 16GB

Software:
OS: Monterey 
mambaforge
spyder ide

**Comment by jondy** [comment]
First run the plain script, make sure it's not killed by Apple M1

Then try to obfuscate a simple hello world script in an empty path, and run this obfuscated script.

If it's still killed, try to obfuscate the script with feature `0`, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-scripts-with-different-features
