### ISSUE TITLE
Can PyArmor be deobfuscated? And can it being shared on GitHub help more in de obfuscating?

### ISSUE THREAD

**Issue by mariolatiffathy** [dashingsoft/pyarmor#61]

**Comment by mariolatiffathy** [comment]
Also can scripts obfuscated in the free version be deobfuscated as the capsule file is the same?

**Comment by mariolatiffathy** [comment]
Also can scripts obfuscated in the free version be deobfuscated as the capsule file is the same? (I hope no because I've already shared a project obfuscated with the free one xD)

**Comment by jondy** [comment]
It's not an easy thing to de-obfuscate the scripts which are obfuscated by PyArmor, even in free version. The capsule is same in free version, it mostly means that the new license generated for the obfuscated scripts in free version works for all the other obfuscated scripts. For example, you obfuscate your scripts in free version, and generate a expired license for these obfuscated scripts.  When you distribute all the files to your customer, these obfuscated script should not work on some day. But the customer may generate another license which is never expired by free version of PyArmor, and overwrite your expired license by the one generated by himself.

**Comment by mariolatiffathy** [comment]
Thank you very much for your hard work and awesome brain! Thank you for explaining that too :-)

**Comment by serg06** [comment]
@jondy This is really confusing me:

> these obfuscated script should not work on some day. But the customer may generate another license which is never expired by free version of PyArmor, and overwrite your expired license by the one generated by himself.

Are you saying that in the free version, licenses are pointless because customers can generate a new license for themselves?

**Comment by jondy** [comment]
@serg06 Yes. If the scripts are obfuscated by free version, anyone could generate the license for them, because free version shares one same capsule.

Refer to http://pyarmor.readthedocs.io/en/latest/license.html

**Comment by serg06** [comment]
> @serg06 Yes. If the scripts are obfuscated by free version, anyone could generate the license for them, because free version shares one same capsule.
> 
> Refer to http://pyarmor.readthedocs.io/en/latest/license.html

I see, thank you!

**Comment by moongkool** [comment]
but they can deobfuscate  
https://forum.tuts4you.com/topic/41945-python-pyarmor-my-protector/?tab=comments#comment-203008

**Comment by oddmario** [comment]
> but they can deobfuscate
> https://forum.tuts4you.com/topic/41945-python-pyarmor-my-protector/?tab=comments#comment-203008

The person who was able to deobfuscate this said that the newer versions of Pyarmor can't be unpacked the same way.
Reference: https://forum.tuts4you.com/topic/41945-python-pyarmor-my-protector/?do=findComment&comment=206260

**Comment by jondy** [comment]
duplicated of #494 and #501

**Comment by oddmario** [comment]
I really opened this issue in 2019 wow-
