### ISSUE TITLE
 HTTP Error 503: Service Temporarily Unavailable when several parallel requests

### ISSUE THREAD

**Issue by tkornuta-nvidia** [dashingsoft/pyarmor#613]
**Description**

I am building obfuscated wheels in CI (parallel build for several platforms).

For some of the builds  the registration fails and I have to manually rerun those jobs.

Example - code run in CI:
```
echo "Registering pyarmor"
pyarmor register scripts/wheel/pyarmor-keycode-xxx.txt || exit $?
```
Result:
```
Registering pyarmor
INFO     Create pyarmor home path: /root/.pyarmor
INFO     Create trial license file: /root/.pyarmor/license.lic
INFO     Generating public capsule ...
INFO     PyArmor Trial Version 6.8.1
INFO     Python 3.8.12
INFO     Read registration code file: scripts/wheel/pyarmor-keycode-xxx.txt
INFO     Start to activate this code
ERROR    HTTP Error 503: Service Temporarily Unavailable
```

**Comment by jondy** [comment]
One client ip could send 3 register request per minute, this is server setting for security.

Please check the registration file `pyarmor-keycode-xxx.txt`, and register it offline.

**Comment by tkornuta-nvidia** [comment]
ok, thanks! 

Read once again the `pyarmor-keycode-xxx.txt` file, do I get it right that "offline" means registration using path 2 that involves generation of 'pyarmor-regfile-xxx.zip' file, correct?

**Comment by tkornuta-nvidia** [comment]
Nice, this just worked. Thanks!
