### ISSUE TITLE
go back to .py file

### ISSUE THREAD

**Issue by borderline23** [dashingsoft/pyarmor#617]
Hello, I bought a pyarmor license and I am very satisfied. I created a project and used pyarmor without problems .. the point now is that I have an old file --onefile .exe packed with pyarmor and having lost the original .py project I would like to be able to do the reverse work is it possible? considering that I am the owner of the license?

**Comment by jondy** [comment]
No.

**Comment by borderline23** [comment]
on the one hand I am happy (security) on the other a little sad! (I lost my project) !
Thanks for the answer
