### ISSUE TITLE
Does pyarmor support interactive python shell? I get RuntimeError: Python interpreter is debug version

### ISSUE THREAD

**Issue by JurgenHissen** [dashingsoft/pyarmor#619]
I'd like to be able to use an obfuscated module in an interactive python shell (**python -i**)
Is this possible? I get an error when I try.

A trial obfuscated module ('Chimp') runs in a batch script:
```
import chimp as cp
a = cp.Chimp()
a.vocalize()
```
```
$ python test_chimp.py
a chimp is born
woop woop
$
```
But if I try to run in interactive mode, I get this error:
```
$ python -i test_chimp.py
Traceback (most recent call last):
  File "test_chimp.py", line 1, in <module>
    import chimp as cp
  File "</proj/jurgen/chimp/dist/chimp.py>", line 3, in <module>
RuntimeError: Python interpreter is debug version
```

Is interactive version supported for obfuscated modules? I could not find mention of it in the documentation either way. And I can't find any mention even anywhere on the web of that particular error message.

I am obfuscating a module using pyarmor 7.0.2 and running in python 3.6.8

Thanks for reading (and for this cool project)

**Comment by jondy** [comment]
Python interpreter built with Py_Debug could not run the obfuscated scripts, more information refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts

**Comment by JurgenHissen** [comment]
Thanks, Jondy. But this is strange.. Is the same interpreter binary not used for batch (python) and interactive (python -i)? Why does it only break with '-i'? And I think this is a default python install.. is there no way to get it to run with -i?

We are hoping to use pyarmor to deliver code to a customer, but if they cannot use the default python binary, that will make it harder to use.

**Comment by JurgenHissen** [comment]
Is it possible that the pyarmor runtime is mis-detecting the 'debug' somehow when we run python -i?

Some more info:
I have checked the build flags for the python binary with sysconfig, and it looks like there are no debug flags set:
```
$ python -m sysconfig | grep -i debug
	CFLAGS = "-Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv"
	OPT = "-DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv"
	PY_CFLAGS = "-Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv"
	PY_CORE_CFLAGS = "-Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -fprofile-use -fprofile-correction -IObjects -IInclude -IPython -I. -I/builddir/build/BUILD/Python-3.6.8/Include  -DPy_BUILD_CORE"
	Py_DEBUG = "0"
```
I've also run with python's __ debug __ off using the -O flag, but still see the same thing:
```
$ python -i print_debug.py 
('__debug__', True)
>>> 
$ python -Oi print_debug.py 
('__debug__', False)
>>> 
$ python -Oi test_chimp.py 
Traceback (most recent call last):
  File "test_chimp.py", line 1, in <module>
    import chimp as cp
  File "</proj/azalea/jurgen/work/dist/chimp.py>", line 3, in <module>
RuntimeError: Python interpreter is debug version
>>> 
```

Your help would be greatly appreciated.

**Comment by jondy** [comment]
It's impossible to run pyarmor for Python debug version, and no run obfuscated script interactively.

**Comment by JurgenHissen** [comment]
I think I am hearing from you that interactive (python -i) and 'debug version' are the same thing.
So it is not possible to run obfuscated modules with python -i.
Is that correct?

**Comment by jondy** [comment]
The obfuscated scripts can't be run interactively.

**Comment by JurgenHissen** [comment]
Okay, understood.  Thank you.
