### ISSUE TITLE
support on OpenBSD?

### ISSUE THREAD

**Issue by plavcik** [dashingsoft/pyarmor#62]
Could you add support for OpenBSD?

```shell
pyarmor obfuscate file.py                    
INFO     Searching _pytransform.dll for openbsd_amd64 ...                        
ERROR    No available library for this platform    
```

**Comment by jondy** [comment]
There is a built library for FreeBSD, 

http://pyarmor.dashingsoft.com/downloads/platforms/freebsd/_pytransform.so

download it and put it in the installed path of PyArmor.

I'm not sure whether it works in OpenBSD. If not, I'll build one for OpenBSD
