### ISSUE TITLE
Segmentation Fault with Python 3.10.0

### ISSUE THREAD

**Issue by jkleinerman** [dashingsoft/pyarmor#620]
Trying to run an obfuscated code with Python 3.10.0, I get a Segmentation Fault
Of course the obfuscation was done with the same version of Python (3.10.0)
I had the same problem time ago when moving from python 3.8.x to 3.9.x
I'm uisng the last version of Pyarmor (7.0.2)

Output
---------

root@ce94427ef6e6:/dobie-venv/dobie-server# python --version
Python 3.10.0

root@ce94427ef6e6:/dobie-venv/dobie-server# pyarmor --version
PyArmor Trial Version 7.0.2

PyArmor is a command line tool used to obfuscate python scripts, bind
obfuscated scripts to fixed machine or expire obfuscated scripts.

For more information, refer to https://pyarmor.readthedocs.io

root@ce94427ef6e6:/dobie-venv/dobie-server# python main.py 
Segmentation fault

**Comment by jondy** [comment]
Python3.10 is not still supported by pyarmor now. It will be supported by version `v7.1.0` which is about to be released next month.

**Comment by jkleinerman** [comment]
Thanks Jondy

Regards

**Comment by jondy** [comment]
v7.1.0 has been released to support Python 3.10
