### ISSUE TITLE
How to add multiple Hardisk serial number in pyarmor web-ui

### ISSUE THREAD

**Issue by AmarAkmal** [dashingsoft/pyarmor#621]
i want to add multiple serial number hard disk throw pyarmor-webui, but failed, only 1 serial no can,can you help me ,
thx

**Comment by jondy** [comment]
pyarmor-webui doesn't support this, you may need use pyarmor with plugin to implement it.

**Comment by AmarAkmal** [comment]
what you mean " you may need use pyarmor with plugin to implement it." , so use pyarmor plugin can add multiple Hardisk serial number?if can how i do that, only multiple i see only mac adresses <abc,def>.

**Comment by jondy** [comment]
Plugin is written by yourself, it can do anything you want to do, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#using-plugin-to-extend-license-type
