### ISSUE TITLE
'Check license failed, Invalid input packet.' when using --platform

### ISSUE THREAD

**Issue by vgaury** [dashingsoft/pyarmor#623]
Hello, thank you for this great repo ! 
However I faced an issue with the last version (7.0.2) of pyarmor:

I tried obfuscating a package with the  `--platform windows.x86_64,linux.x86_64,darwin.x86_64` argument. The obfuscation process has no issue: 
`INFO     Obfuscate 33 scripts OK.`
, but when I try to import the obfuscated package in a python interpreter, I get the error 
`Check license failed, Invalid input packet.`.

I checked the platform i'm using to import the obfuscated package (with the script proposed in pyarmor's documentation https://github.com/dashingsoft/pyarmor/raw/master/src/helper/get_platform_name.py) which corresponds to one of the platforms I'm giving as parameter of the function : 
`platform.system is "Linux"
platform.machine is "x86_64"
sys.byteorder is "little"
The standard platform name is "linux.x86_64"`

I tried re-installing pyarmor after a clean uninstallation (as advised in the documentation), which led to the same result. 
I then tried with a former version of the algorithm (6.8.0), which ended up working, I could load the obfuscated package without trouble. 

Finally, I tried running pyarmor obfuscate without the platform option (with pyarmor 7.0.2), which ended up working. It creates a unique working _pytransform.so file. I copied this file in pytransform/linux/x86_64 folder to replace the previously generated _pytransform.so, allowing me to load the package successfully. 

It seems there is an issue with the generation of the _pytransform.so file with the --platform parameter in pyarmor 7.0.2, any idea on the problem's cause ? 

Thank you !

**Comment by jondy** [comment]
I think you're using the trial version. 

When obfuscate the scripts with `--platform`, it will download the old core version `r41.15a` not the latest core version, please check the output log carefully.

And since v7.0.1, the license format is changed so that the old version could not work with new version.

If no option `--platform`, it uses the latest libraries in the source package, so it works.

**Comment by vgaury** [comment]
Indeed I am using the trial version, thank you for your response !
