### ISSUE TITLE
Small Bug

### ISSUE THREAD

**Issue by Serozoid** [dashingsoft/pyarmor#626]
While using restrict modes, Every version of pyarmor before 7.0.3 has been fine but runtime errors are shown for importing plain scripts.

(i have certain parts of my code running off threads, and pyarmor is mistaking these threads as a plain script so its throwing a runtime error)

Could you look into this? Try using restrict modes in pyarmor 7.0.3 and having an application running certain parts of the code using threading. This was never an issue before 7.0.2

**Comment by jondy** [comment]
The only difference between 7.0.2 and 7.0.3 is to check the core version if pyarmor is trial version, it should not the version upgrading issue.

If you think it's really an issue, please following the bug template and provide the necessary information.
