### ISSUE TITLE
Segmentation Fault with Super Plus Mode

### ISSUE THREAD

**Issue by SeongDongHyun** [dashingsoft/pyarmor#628]
Trying to run an obfuscated code with Python super plus mode, I get a Segmentation Fault
And INFO gives "Patch function "get_subsample" at line 401".
Even after adding '# pyarmor options: no-spp-mode' to the file in question, it is still not ignored and a 'segmentation fault' occurs.
But, In other files super plus mode works.
I'm using the last version of Pyarmor (7.0.3), and python version 3.8

## OUTPUT
root$ python3 --version
Python 3.8.0

root$ pyarmor --version
PyArmor Version 7.0.3

root$ pyarmor obfuscate --advanced 5 -r .
INFO            Patch function "get_subsample" at line 401
Segmentation fault

**Comment by jondy** [comment]
Please refer to document to ignore this script or only the failed function by inline option `--no-spp-mode`.

BTW, if there is no sense data, could you send this file or function to jondy.zhao@gmail.com

**Comment by jondy** [comment]
Fixed in v7.1.0
