### ISSUE TITLE
Super plus mode fail , segment fault (already purchase)

### ISSUE THREAD

**Issue by ykk648** [dashingsoft/pyarmor#629]
My command: 

`../python ../pyarmor.py -d obfuscate -O dist/obf --package-runtime 0 -r --exclude dist --advanced 5 ./DUMB.py`

when I mod advanced=2, it works well.
when I use advanced=5 to test single file like `foo.py` or some other file in my project, it works well.

here is my fail log, I mod some file name to DUMB:

<details>
<summary>Details</summary>

DEBUG    PyArmor installation path: /opt/anaconda3/envs/base_py38_torch18_tf2/lib/python3.8/site-packages/pyarmor
DEBUG    PyArmor home path: /home/tyler/.pyarmor
DEBUG    Native platform is linux.x86_64
DEBUG    Search dynamic library in the path: /opt/anaconda3/envs/base_py38_torch18_tf2/lib/python3.8/site-packages/pyarmor/platforms
DEBUG    Loaded dynamic library: /opt/anaconda3/envs/base_py38_torch18_tf2/lib/python3.8/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
DEBUG    The version of core library is (46, 20, 7)
INFO     PyArmor Version 7.0.3
INFO     Python 3.8.0
INFO     Target platforms: Native
DEBUG    Load platform list from /home/tyler/.pyarmor/platforms/index.json
INFO     Update target platforms to: ['linux.x86_64.11.py38']
INFO     Source path is "/workspace/codes/DUMB"
INFO     Entry scripts are ['./DUMB.py']
INFO     Use cached capsule /home/tyler/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Exclude path "tmp"
INFO     Auto exclude output path "dist"
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 2
INFO     Super mode is True
INFO     Super plus mode is enabled
INFO     Generating super runtime library to "dist"
DEBUG    Load platform list from /home/tyler/.pyarmor/platforms/index.json
DEBUG    Target dynamic library: ['/home/tyler/.pyarmor/platforms/linux/x86_64/11/py38/pytransform.cpython-38-x86_64-linux-gnu.so']
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying /home/tyler/.pyarmor/platforms/linux/x86_64/11/py38/pytransform.cpython-38-x86_64-linux-gnu.so
INFO     Patch extension dist/pytransform.so
DEBUG    Patching dist/pytransform.so
DEBUG    Found pattern at b9904
DEBUG    Patch 261 bytes from b9924
DEBUG    Patch 270 bytes from b9a29
DEBUG    Patch 412 bytes from b9b37
INFO     Patch library file OK
INFO     Generate runtime files OK
INFO     Use protection template: /opt/anaconda3/envs/base_py38_torch18_tf2/lib/python3.8/site-packages/pyarmor/protect_code2.pt
INFO     Start obfuscating the scripts...
INFO     	DUMB.py -> dist/DUMB.py
INFO     Patch this entry script with protection code
INFO     Write patched script for debugging: /workspace/codes/DUMB/DUMB.py.pyarmor-patched
INFO     Set PYARMOR_CC to "gcc"
DEBUG    Check license file "/home/tyler/.pyarmor/license.lic"
INFO     Generating spp code for <frozen DUMB> ...
DEBUG    Traverse syntax tree
DEBUG    Node Call at line 17: ignored by function "super"
DEBUG    Node Call at line 52: ignored by function "super"
DEBUG    Node Call at line 76: ignored by function "super"
DEBUG    Node ImportFrom at line 92: ignore by {'_getframe'} in module "sys"
DEBUG    Find 5 available functions
DEBUG    Got spp code for function "check_lib_pytransform"
DEBUG    Got spp code for function "assert_builtin"
DEBUG    Got spp code for function "run"
DEBUG    Got spp code for function "run"
DEBUG    Got spp code for function "run"
DEBUG    Find 5 top functions
DEBUG    Check code objects for super mode
DEBUG    Compile syntax tree to code object
DEBUG    Check code objects for spp mode
INFO     Generate module spp code successfully
INFO     Compiling spp code ...
DEBUG    CC: gcc
DEBUG    cflags: -O3 -c -fPIC
INFO     Compile spp code successfully
INFO     	DUMB_parallel_trt_roi_DUMB.py -> dist/DUMB_parallel_trt_roi_DUMB.py
INFO     Generating spp code for <frozen DUMB_parallel_trt_roi_DUMB> ...
DEBUG    Traverse syntax tree
DEBUG    Node Call at line 27: ignored by function "super"
DEBUG    Node Call at line 127: ignored by function "super"
DEBUG    Node Call at line 221: ignored by function "super"
DEBUG    Node Call at line 333: ignored by function "super"
DEBUG    Find 15 available functions
DEBUG    Got spp code for function "__save_video"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=0, kind=None))
DEBUG    Ignore function "__generate_output_dir"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=0, kind=None))
DEBUG    Ignore function "forward"
DEBUG    Got spp code for function "__init__"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=0, kind=None))
DEBUG    Ignore function "run"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=1, kind=None))
DEBUG    Ignore function "forward_func"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=0, kind=None))
DEBUG    Ignore function "run"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Name(id='i', ctx=Load()))
DEBUG    Ignore function "predict"
DEBUG    Assert false at line 171:
DEBUG    FunctionDef(name='np_norm', args=arguments(posonlyargs=[], args=[arg(arg='x', annotation=None, type_comment=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=[Return(value=BinOp(left=BinOp(left=Name(id='x', ctx=Load()), op=Sub(), right=Call(func=Attribute(value=Name(id='np', ctx=Load()), attr='average', ctx=Load()), args=[Name(id='x', ctx=Load())], keywords=[])), op=Div(), right=Call(func=Attribute(value=Name(id='np', ctx=Load()), attr='std', ctx=Load()), args=[Name(id='x', ctx=Load())], keywords=[])))], decorator_list=[], returns=None, type_comment=None)
DEBUG    Ignore function "run"
DEBUG    Got spp code for function "np_norm"
DEBUG    Got spp code for function "img_forward"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=0, kind=None))
DEBUG    Ignore function "__process_image"
DEBUG    Got spp code for function "on_release"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Attribute(value=Name(id='key', ctx=Load()), attr='char', ctx=Load()))
DEBUG    Ignore function "on_press"
DEBUG    Got spp code for function "run"
DEBUG    Find 6 top functions
DEBUG    Check code objects for super mode
DEBUG    Compile syntax tree to code object
DEBUG    Check code objects for spp mode
INFO     Generate module spp code successfully
INFO     Compiling spp code ...
DEBUG    CC: gcc
DEBUG    cflags: -O3 -c -fPIC
INFO     Compile spp code successfully
INFO     	DUMB_parallel_trt_roi_DUMB_api.py -> dist/DUMB_parallel_trt_roi_DUMB_api.py
INFO     Generating spp code for <frozen DUMB_parallel_trt_roi_DUMB_api> ...
DEBUG    Traverse syntax tree
DEBUG    Node Call at line 25: ignored by function "super"
DEBUG    Node Call at line 110: ignored by function "super"
DEBUG    Node Call at line 236: ignored by function "super"
DEBUG    Find 8 available functions
DEBUG    Got spp code for function "forward"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value='CUDA_VISIBLE_DEVICES', kind=None))
DEBUG    Ignore function "__init__"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=0, kind=None))
DEBUG    Ignore function "run"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=1, kind=None))
DEBUG    Ignore function "forward_func"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=0, kind=None))
DEBUG    Ignore function "run"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Name(id='i', ctx=Load()))
DEBUG    Ignore function "predict"
DEBUG    Assert false at line 62:
DEBUG    FunctionDef(name='np_norm', args=arguments(posonlyargs=[], args=[arg(arg='x', annotation=None, type_comment=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=[Return(value=BinOp(left=BinOp(left=Name(id='x', ctx=Load()), op=Sub(), right=Call(func=Attribute(value=Name(id='np', ctx=Load()), attr='average', ctx=Load()), args=[Name(id='x', ctx=Load())], keywords=[])), op=Div(), right=Call(func=Attribute(value=Name(id='np', ctx=Load()), attr='std', ctx=Load()), args=[Name(id='x', ctx=Load())], keywords=[])))], decorator_list=[], returns=None, type_comment=None)
DEBUG    Ignore function "run"
DEBUG    Got spp code for function "np_norm"
DEBUG    Find 2 top functions
DEBUG    Check code objects for super mode
DEBUG    Compile syntax tree to code object
DEBUG    Check code objects for spp mode
INFO     Generate module spp code successfully
INFO     Compiling spp code ...
DEBUG    CC: gcc
DEBUG    cflags: -O3 -c -fPIC
INFO     Compile spp code successfully
INFO     	api.py -> dist/api.py
INFO     Generating spp code for <frozen api> ...
DEBUG    Traverse syntax tree
DEBUG    Find 7 available functions
DEBUG    Got spp code for function "sender"
DEBUG    Got spp code for function "stop"
DEBUG    Got spp code for function "PicOut"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=0, kind=None))
DEBUG    Ignore function "PicIn"
DEBUG    Got spp code for function "ChangeFaces"
DEBUG    Got spp code for function "Faces"
DEBUG    Got spp code for function "__init__"
DEBUG    Find 6 top functions
DEBUG    Check code objects for super mode
DEBUG    Compile syntax tree to code object
DEBUG    Check code objects for spp mode
INFO     Generate module spp code successfully
INFO     Compiling spp code ...
DEBUG    CC: gcc
DEBUG    cflags: -O3 -c -fPIC
INFO     Compile spp code successfully
INFO     	face_detect/face_detect.py -> dist/face_detect/face_detect.py
INFO     Generating spp code for <frozen face_detect.face_detect> ...
DEBUG    Traverse syntax tree
DEBUG    Node ImportFrom at line 8: relative import is not implemented
DEBUG    Find 2 available functions
DEBUG    Got spp code for function "get_bboxes"
DEBUG    Got spp code for function "__init__"
DEBUG    Find 2 top functions
DEBUG    Check code objects for super mode
DEBUG    Compile syntax tree to code object
DEBUG    Check code objects for spp mode
INFO     Generate module spp code successfully
INFO     Compiling spp code ...
DEBUG    CC: gcc
DEBUG    cflags: -O3 -c -fPIC
INFO     Compile spp code successfully
INFO     	face_detect/scrfd_insightface/__init__.py -> dist/face_detect/scrfd_insightface/__init__.py
INFO     Generating spp code for <frozen face_detect.scrfd_insightface> ...
DEBUG    Traverse syntax tree
DEBUG    Node ImportFrom at line 5: relative import is not implemented
DEBUG    Find 0 available functions
INFO     Ignore this module because of no any function available for sppmode
INFO     	face_detect/scrfd_insightface/scrfd.py -> dist/face_detect/scrfd_insightface/scrfd.py
INFO     Generating spp code for <frozen face_detect.scrfd_insightface.scrfd> ...
DEBUG    Traverse syntax tree
DEBUG    Find 9 available functions
DEBUG    Assert false at line -1:
DEBUG    ExtSlice(dims=[Slice(lower=None, upper=None, step=None), Index(value=Constant(value=0, kind=None))])
DEBUG    Ignore function "nms"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=0, kind=None))
DEBUG    Ignore function "detect"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=2, kind=None))
DEBUG    Ignore function "forward"
DEBUG    Got spp code for function "prepare"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=0, kind=None))
DEBUG    Ignore function "_init_vars"
DEBUG    Got spp code for function "__init__"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=1, kind=None))
DEBUG    Ignore function "distance2kps"
DEBUG    Assert false at line -1:
DEBUG    ExtSlice(dims=[Slice(lower=None, upper=None, step=None), Index(value=Constant(value=0, kind=None))])
DEBUG    Ignore function "distance2bbox"
DEBUG    Assert false at line -1:
DEBUG    ExtSlice(dims=[Slice(lower=None, upper=None, step=None), Index(value=Attribute(value=Name(id='np', ctx=Load()), attr='newaxis', ctx=Load()))])
DEBUG    Ignore function "softmax"
DEBUG    Find 2 top functions
DEBUG    Check code objects for super mode
DEBUG    Compile syntax tree to code object
DEBUG    Check code objects for spp mode
INFO     Generate module spp code successfully
INFO     Compiling spp code ...
DEBUG    CC: gcc
DEBUG    cflags: -O3 -c -fPIC
INFO     Compile spp code successfully
INFO     	face_feature/__init__.py -> dist/face_feature/__init__.py
INFO     Generating spp code for <frozen face_feature> ...
DEBUG    Traverse syntax tree
DEBUG    Node ImportFrom at line 2: relative import is not implemented
DEBUG    Node ImportFrom at line 3: relative import is not implemented
DEBUG    Find 0 available functions
INFO     Ignore this module because of no any function available for sppmode
INFO     	face_feature/face_embedding.py -> dist/face_feature/face_embedding.py
INFO     Generating spp code for <frozen face_feature.face_embedding> ...
DEBUG    Traverse syntax tree
DEBUG    Find 3 available functions
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=0, kind=None))
DEBUG    Ignore function "latent_from_image"
DEBUG    Assert false at line -1:
DEBUG    Index(value=Constant(value=0, kind=None))
DEBUG    Ignore function "__init__"
DEBUG    Got spp code for function "down_sample"
DEBUG    Find 1 top functions
DEBUG    Check code objects for super mode
DEBUG    Compile syntax tree to code object
DEBUG    Check code objects for spp mode
INFO     Generate module spp code successfully
INFO     Compiling spp code ...
DEBUG    CC: gcc
DEBUG    cflags: -O3 -c -fPIC
INFO     Compile spp code successfully
INFO     	Patch function "__init__" at line 16
INFO     	face_feature/mtcnn_insightface/__init__.py -> dist/face_feature/mtcnn_insightface/__init__.py
INFO     Generating spp code for <frozen face_feature.mtcnn_insightface> ...
DEBUG    Traverse syntax tree
DEBUG    Find 0 available functions
INFO     Ignore this module because of no any function available for sppmode
INFO     	face_feature/mtcnn_insightface/face_align_func.py -> dist/face_feature/mtcnn_insightface/face_align_func.py
raise segment fault
</details>

**Comment by jondy** [comment]
Please refer to document to ignore this script `face_feature/mtcnn_insightface/face_align_func.py` or only the failed function by inline option `--no-spp-mode`.

BTW, if there is no sense data, could you send this file to jondy.zhao@gmail.com

**Comment by ykk648** [comment]
thanks, jump some codes works.
