### ISSUE TITLE
run obfuscated python file wrong in rk3399

### ISSUE THREAD

**Issue by hxcai** [dashingsoft/pyarmor#63]
I used pip to install pyarmor successfully in rk3399, after that I used 'pyarmor obfuscate --recursive test.py' to obfuscate my code and the dist dir was generated. But when I run test.py in dist dir, there was something wrong. Wrong message:
b'Invalid input packet.\nVerify rsa key failed'

**Comment by jondy** [comment]
Download this file

http://pyarmor.dashingsoft.com/downloads/platforms/armv8.64-bit/_pytransform.so

Overrite the old one in the `dist` path.  check it works or not?

**Comment by hxcai** [comment]
It couldn't work, and the wrong message is same.
b'Invalid input packet.\nVerify rsa key failed'

**Comment by jondy** [comment]
Try to remove old capsule and do a fresh test
```
  rm ~/.pyarmor_capsule.zip
  rm -rf dist
  pyarmor obfuscate --recursive test.py
  cd dist
  python test.py
```

**Comment by hxcai** [comment]
Follow your way, and here is some info.
`rm ~/.pyarmor_capsule.zip`
`rm -rf dist`
`pyarmor obfuscate --recursive test.py`
INFO     Generate capsule /root/.pyarmor_capsule.zip
INFO     PyArmor install path: /root/.pyenv/versions/3.5.5/lib/python3.5/site-packages/pyarmor
INFO     Generating project key ...
INFO     Generate project key OK.
INFO     Writing capsule to /root/.pyarmor_capsule.zip ...
INFO     Write capsule OK.
no previously-included directories found matching 'build'
no previously-included directories found matching 'dist'
INFO     Save obfuscated scripts to "dist"
INFO     Read public key from capsule
INFO     Obfuscate scripts with default mode
INFO     	test.py -> dist/test.py
INFO     Patch this entry script with protection code
INFO     1 scripts have been obfuscated
INFO     Make runtime files
INFO     Insert bootstrap code to entry script dist/test.py
INFO     Obfuscate 1 scripts OK.
`cd dist`
`python test.py`
b'Invalid input packet.\nVerify rsa key failed'

**Comment by jondy** [comment]
How about generating a new license for obfuscated scripts:
```
pyarmor licenses mycode
cp licenses/mycode/license.lic dist
cd dist
python test.py
```

**Comment by hxcai** [comment]
It couldn't work either, and wrong message is same.
b'Invalid input packet.\nVerify rsa key failed'

**Comment by jondy** [comment]
Could you pack all the files in the path `dist` and upload it here?

**Comment by hxcai** [comment]
[dist.zip](https://github.com/dashingsoft/pyarmor/files/3036950/dist.zip)
here is the zip.

**Comment by jondy** [comment]
Fix it in v5.2.4, remove the old capsule and upgrade the new versiion:
```
rm ~/.pyarmor_capsule.zip
pip install --upgrade pyarmor
```

**Comment by hxcai** [comment]
I removed the old capsule, and upgrade pyarmor in rk3399. But it couldn't work for me.
`pyarmor --version`
PyArmor Trial Version 5.2.4

PyArmor is a command line tool used to obfuscate python scripts, bind
obfuscated scripts to fixed machine or expire obfuscated scripts.
`pyarmor obfuscate --recursive test.py`
INFO     Obfuscate scripts in path "/home/pi/test"
INFO     Generate capsule /root/.pyarmor_capsule.zip
INFO     PyArmor install path: /root/.pyenv/versions/3.5.5/lib/python3.5/site-packages/pyarmor
INFO     Generating project key ...
INFO     Generate project key OK.
INFO     Writing capsule to /root/.pyarmor_capsule.zip ...
INFO     Write capsule OK.
no previously-included directories found matching 'build'
no previously-included directories found matching 'dist'
INFO     Save obfuscated scripts to "dist"
INFO     Read public key from capsule
INFO     Obfuscate scripts with default mode
INFO     	test.py -> dist/test.py
INFO     Patch this entry script with protection code
INFO     1 scripts have been obfuscated
INFO     Make runtime files
INFO     Insert bootstrap code to entry script dist/test.py
INFO     Obfuscate 1 scripts OK.
`cd dist`
`python test.py`
b'Invalid input packet.\nVerify rsa key failed'
[dist.zip](https://github.com/dashingsoft/pyarmor/files/3041291/dist.zip)
here is the dist.

**Comment by jondy** [comment]
The "_pytransform.so" in your dist is old, please remove this "_pytransform.so" 
`rm /root/.pyenv/versions/3.5.5/lib/python3.5/site-packages/pyarmor/_pytransform.so`
and  `rm ~/.pyarmor_capsule.zip`, then obfuscate the script again.

To be sure the md5sum of `dist/_pytransform.so` is
90b2f32789d2f48d921ab2908ecd05f4

Which should be same as `/root/.pyenv/versions/3.5.5/lib/python3.5/site-packages/pyarmor/platforms/linux64/arm/_pytransform.so` in rk3399

**Comment by hxcai** [comment]
It works for me, thanks very much!!!
