### ISSUE TITLE
This function could not be called from the plain script

### ISSUE THREAD

**Issue by Serozoid** [dashingsoft/pyarmor#630]
Script is fully obfuscated okay, No errors were shown. When running the script I am getting this

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "<frozen testproject>", line 250, in Thread1
RuntimeError: This function could not be called from the plain script

This will happen with anything in my project using threading. I never had these shown while using 7.0.2 but upgrading to 7.0.3 They are now shown. I don't understand what could've messed that up cause everything seemed almost the same as 7.0.2?

**Comment by jondy** [comment]
I check the source and I think your scripts are obfuscated by restrict mode 5.

Yes, it does changed for restrict mode 5 to check more.

Refer to this to fix the issue
https://pyarmor.readthedocs.io/en/latest/advanced.html#using-restrict-mode-with-threading-and-multiprocessing

**Comment by Serozoid** [comment]
Thanks jondy, Issues all fixed with the first solution!
