### ISSUE TITLE
Pyarmor best practice docker license

### ISSUE THREAD

**Issue by adampassword** [dashingsoft/pyarmor#631]
I wanted to ask if you have any best practice recommendations to generate and secure licenses for obfuscated code within a docker.
Our issue is that MAC/IP binding in the docker is easy to go around (you just change it) and we dont find a way to pull and bind such info to host machine.
Also the dockerID is hard to use, because every time clients restarts docker the docker ID changes.

We wish to make sure clients cant just run multiple copies of the code on multiple servers.
Any suggestions?

**Comment by jondy** [comment]
Someone starts docker with harddisk, and bind license to this harddisk.

**Comment by adampassword** [comment]
And this can not be manipulated with? 
Is there a possible "killswitch" or call back home "plugin" you guys ever seen? Say if the internet connection is off and it can not communicate/ping our servers the license will stop working?

**Comment by jondy** [comment]
Sorry, I have no more experience on docker.

Plugin can do anything that Python could do, but I have no example code.
