### ISSUE TITLE
Help pyarmor pack not working

### ISSUE THREAD

**Issue by itzguno** [dashingsoft/pyarmor#633]
My pyarmor pack is no longer working i keep getting Too many runtime module found
![image_2021-11-27_095435](https://user-images.githubusercontent.com/53296939/143659899-49c80631-a954-4f82-a05d-fdc8c0611040.png)
i am running pyarmor pack -x" --advanced 4" -e" --onefile --console" file.py

**Comment by itzguno** [comment]
im using python 3.9.2 and pyarmor 6.8.1

**Comment by RaggyRagRagBackup** [comment]
i keep getting this aswell ive tried a complete clean re install and updating the platforms and everything

**Comment by jondy** [comment]
Please remove the output path then try it again.

**Comment by 1trackprojects1** [comment]
I am getting this as well

`WARNING  The trial version could not download the latest core libraries, tag r41.15a is always used`
