### ISSUE TITLE
macOS M1  registration

### ISSUE THREAD

**Issue by 176314841** [dashingsoft/pyarmor#634]
I'm a novice. 
I've installed pyarmor,pip list on macOS and I can see it. 
But I will report an error when I register. My computer is the latest M1 max this year.

The following is the registration information

Last login: Mon Nov 29 08:35:24 on ttys000
wanglei@wangleideMBP ~ % python

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.18 (default, Oct  2 2021, 04:20:38) 
[GCC Apple LLVM 13.0.0 (clang-1300.0.29.1) [+internal-os, ptrauth-isa=deploymen on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> cd /Users/wanglei/Library/Python/2.7/lib/python/site-packages
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cd' is not defined
>>>  /Users/wanglei/Library/Python/2.7/lib/python/site-packages
  File "<stdin>", line 1
    /Users/wanglei/Library/Python/2.7/lib/python/site-packages
    ^
IndentationError: unexpected indent
>>> path
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'path' is not defined
>>> import pyarmor
>>> pyarmor register /Users/wanglei/Library/Python/2.7/lib/python/site-packages/pyarmor-regcode-2074.txt 
  File "<stdin>", line 1
    pyarmor register /Users/wanglei/Library/Python/2.7/lib/python/site-packages/pyarmor-regcode-2074.txt 
                   ^
SyntaxError: invalid syntax

**Comment by jondy** [comment]
pyarmor is well document, please read installation / uninstallation, and basic usage documentation.
