### ISSUE TITLE
encrypted tests fail

### ISSUE THREAD

**Issue by halicloud** [dashingsoft/pyarmor#635]
[admin@]$ ls
boot  calculate  run.py
[admin@]$ chmod 777 boot/armor_code.sh
 [admin@]$ ./boot/armor_code.sh
INFO     PyArmor Trial Version 7.1.0
INFO     Python 3.9.7
INFO     Target platforms: Native
INFO     Source path is "/home/encrypted_code_testing_demo/source/calculate"
INFO     Entry scripts are ['calculate/__init__.py']
INFO     Use cached capsule /home/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Save obfuscated scripts to "encrypted_calculate/"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to encrypted_calculate/pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying /home/encrypted_code_testing_demo/env/lib/python3.9/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
INFO     Patch library encrypted_calculate/pytransform/_pytransform.so
INFO     Patch library file OK
INFO     Copying /home/encrypted_code_testing_demo/env/lib/python3.9/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            __init__.py -> encrypted_calculate/__init__.py
INFO     Insert bootstrap code to entry script encrypted_calculate/__init__.py
INFO            calculate.py -> encrypted_calculate/calculate.py
INFO            tests/cal_test.py -> encrypted_calculate/tests/cal_test.py
INFO     Obfuscate 3 scripts OK.
[]$ python -m pytest calculate/
================================================== test session starts ===================================================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/encrypted_code_testing_demo/source
collected 0 items / 1 error

========================================================= ERRORS =========================================================
______________________________________ ERROR collecting calculate/tests/cal_test.py ______________________________________
calculate/tests/cal_test.py:1: in <module>
    __pyarmor__(__name__, __file__, b'\x50\...\x65', 2)
E   NameError: name '__pyarmor__' is not defined
================================================ short test summary info =================================================
ERROR calculate/tests/cal_test.py - NameError: name '__pyarmor__' is not defined
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================== 1 error in 0.09s ====================================================

参考官方文档，问题应该是test文件没有引导文件，不是加密主文件，我们如果想加密模块后运行pytest，应该怎么做，使用超级模式可行吗，但是服务器没有外网

[]$ sh boot/armor_code.sh
INFO     PyArmor Version 6.2.3
INFO     Source path is "/home/encrypted_code_testing_demo/source/calculate"
INFO     Entry scripts are ['calculate/__init__.py']
INFO     Use cached capsule /home/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Save obfuscated scripts to "dist/encrypted_calculate"
INFO     Read public key from capsule
INFO     Obfuscate module mode is 1
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced mode is 2
INFO     Generating super runtime library to dist/encrypted_calculate
INFO     Search library for platform: linux.x86_64
INFO     Found available libraries: [u'linux.x86_64.7', u'linux.x86_64.0', u'linux.x86_64.11.py38', u'linux.x86_64.11.py37', u'linux.x86_64.11.py27']
INFO     Downloading library file for linux.x86_64.7 ...
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r22.16/platforms/linux_x86_64/_pytransform.so

**Comment by jondy** [comment]
请参考高级用法中相关章节，已经支持平台里面关于离线使用核心库的方法

**Comment by halicloud** [comment]
你好，我这边就是希望加密后的代码可以执行pytest，正常加密后tests文件是没有引导文件，我这边需要怎么操作？
阅读文档，使用超级模式好像可以实现，但是执行就需要链接外网，但是高级用法没有找到如何离线使用超级模式的说明，还希望告知一下了，感谢了！

**Comment by jondy** [comment]
运行加密文件是不需要链接外网的，如何离线加密的时候请参考文档 <支持的平台> 这章里面的内容。
