### ISSUE TITLE
Could not find _pytransform?

### ISSUE THREAD

**Issue by EzerbelCN** [dashingsoft/pyarmor#636]
## win10 and the interpreter is mayapy.exe
![image](https://user-images.githubusercontent.com/66873183/144992724-8c09087d-7016-448c-9500-be22ab937fe1.png)

## obfuscate recursively
![image](https://user-images.githubusercontent.com/66873183/144988517-dd953d67-40fb-4525-9a6e-54c3f6320a10.png)
## main.py
![image](https://user-images.githubusercontent.com/66873183/144988675-4baa8e4f-4ae2-4f15-bace-ce95ae93ff56.png)

## foo.py will call obfuscated code main.py
![image](https://user-images.githubusercontent.com/66873183/144987757-3238a4e9-253f-4500-ad90-c51259466c06.png)
## the __init__ file is cleaned manually
![image](https://user-images.githubusercontent.com/66873183/144987823-6f0dbeec-e6d7-437e-a172-dd10e0dfbaba.png)
![image](https://user-images.githubusercontent.com/66873183/144987461-74e47bba-8dd4-4d3e-82e8-aa1ccbf62e35.png)

## followed 'when things go wrong'
![image](https://user-images.githubusercontent.com/66873183/144989948-2864f98c-0b73-4034-9e07-d24bf9b1154d.png)

## still do not work
![image](https://user-images.githubusercontent.com/66873183/144991276-603d3078-600c-458f-bd90-162fa02d32e4.png)

![image](https://user-images.githubusercontent.com/66873183/144991487-cf5bb07f-a48d-4198-b535-6e5772a637e0.png)

##  made the directory, but it did not help, ` __pyarmor__ ` is still not defined 
![image](https://user-images.githubusercontent.com/66873183/144992344-2e5706ab-72ae-4e89-a587-aa406f2d7b95.png)

**Comment by EzerbelCN** [comment]
## replaceed the .dll file from below
https://github.com/dashingsoft/pyarmor/issues/37
but maya crashed everytime

**Comment by jondy** [comment]
Please refer to the chapter `When thing is going wrong` in the documentation first.
