### ISSUE TITLE
Darwin aarch

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#637]
Hi @jondy,

Have you tested the aarch on an m1 because I have heaps of users that can't get it working .. i use the platform `darwin.aarch64`

an error report from a user on an m1

```
Python 3.9.9 (v3.9.9:ccb0e6a345, Nov 15 2021, 13:06:05) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import helheim
zsh: killed     python3
 with following message in konsole.app:
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Python [32181]
Path:                  /Library/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.9.9 (3.9.9)
Code Type:             ARM-64 (Native)
Parent Process:        zsh [700]
Responsible:           Terminal [600]
User ID:               501

Date/Time:             2021-12-07 11:27:17.0010 +0100
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Anonymous UUID:        19A58368-9482-25EA-34EF-3613149C3632


Time Awake Since Boot: 140000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x0000000102ed4000
Exception Codes:       0x0000000000000032, 0x0000000102ed4000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 2 

VM Region Info: 0x102ed4000 is in 0x102ed4000-0x102f74000;  bytes after start: 0  bytes before end: 655359
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      mapped file                 102dc4000-102ed4000    [ 1088K] r--/rwx SM=COW  ...t_id=9beac511
--->  mapped file                 102ed4000-102f74000    [  640K] r-x/rwx SM=COW  ...t_id=9beac511
      VM_ALLOCATE (reserved)      102f74000-102fe8000    [  464K] rw-/rwx SM=NUL  ...(unallocated)
```

Users are fine if they use rosetta && intel releases.... but no one seems to be able to darwin.aarch

i also notice that https://pyarmor.readthedocs.io/en/latest/platforms.html states that aarch does not have py310 support yet? is this documentation update to date?

**Comment by jondy** [comment]
Pyarmor killed by m1 `System Integrity Protection: enabled`, there are same issue reports in GitHub. Disable it or use platform `darwin.aarch.0`.

The document is updated, at this time, still no super library for python3.10 in darwin.aarch

**Comment by VeNoMouS** [comment]
Can you explain the different between darwin.aarch.0 and darwin.aarch.11 (11 is current standard if im correct?)

**Comment by jondy** [comment]
Please check the chapter `Support platforms` in the documentation.

**Comment by VeNoMouS** [comment]
ah right, think you mean https://pyarmor.readthedocs.io/en/latest/platforms.html?highlight=Support%20platforms#features

**Comment by cheinelt** [comment]
I'm one of the users of VeNoMouS and disabling GateKeeper is a really bad solution. What I see when I look at the library that has been generated with pyarmor is the following:
`codesign --verify --deep --verbose=2 env-arm/lib/python3.9/site-packages/helheim/pytransform_vax_000061.so
env-arm/lib/python3.9/site-packages/helheim/pytransform_vax_000061.so: invalid signature (code or signature have been modified)`
Thus, pyarmor seems to generate the shared object files and then modifies them after it has signed them. Can you please look into this and fix it? The real problem is the incorrect signing.

**Comment by VeNoMouS** [comment]
@jondy any comment on this?

**Comment by jondy** [comment]
Disable cross-protection by `--no-cross-protecton` when obfuscating the scripts, then sign the runtime file `pytransform_vax_000061.so` by command `codesign`

**Comment by VeNoMouS** [comment]
dont that significantly degrade the security by disabling cross protection tho?

**Comment by jondy** [comment]
No. The goal of signature and cross protection ase same.

VeNoMouS ***@***.***> writes:

> dont that significantly degrade the security by disabling cross protection
> tho?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.
>

-- 
Best Regards
Jondy Zhao
