### ISSUE TITLE
Only "--advanced 2" is available for Python 3.10

### ISSUE THREAD

**Issue by saeidshirazi** [dashingsoft/pyarmor#639]
INFO     ==================== Run command ====================
INFO     PyArmor Trial Version 7.1.1
INFO     Python 3.10.1
ERROR    Only "--advanced 2" is available for Python 3.10
ERROR    Run command failed

I have this issue with this command:
 Pyarmor pack -e"--onefile"
 how can fix it?

**Comment by jondy** [comment]
Fixed in v7.1.2, please install the latest version.

**Comment by saeidshirazi** [comment]
there is no update with pip sir,
how can I update this version?

**Comment by jondy** [comment]
Sorry. I have uploaded 7.1.2 now, please try it again.
