### ISSUE TITLE
How do I obfuscate unicode-containing script?

### ISSUE THREAD

**Issue by Veinz** [dashingsoft/pyarmor#64]
I have following code in my script:

`print('⏱')`

When I obfuscate, it gave me this error:

`ERROR    'charmap' codec can't decode byte 0x8f in position 8: character maps to <undefined>`

Look like pyarmor using wrong codec when decoding.
Is there any parameters or something that I should set?

[Reference](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character)

**Comment by jondy** [comment]
Try to add the codec line at the beginning of script like this
```
# -*- coding: utf-8 -*-
```

**Comment by Veinz** [comment]
That's works, thanks man.
