### ISSUE TITLE
preserve interface after obfuscation

### ISSUE THREAD

**Issue by nschloe** [dashingsoft/pyarmor#643]
When obfuscating a script, something like
```python
def fun(x: float, y: float) -> float:
    return x + y
```
will be translated to
```python
__pyarmor__(__name__, __file__, b'...', 2)
```
When importing the latter, editors are not longer able to inspect the interface and, e.g., display typing imformation.

I've like to suggest to restrict the obfuscation to function _contents_, i.e.,
```python
def fun(x: float, y: float) -> float:
    __pyarmor__(...)
```

**Comment by jondy** [comment]
It's interesting, but it's totally different from the current obfuscation method. And the obfuscated scripts aren't intend to be edited or debugged, the idea is that edit or debug the plain scripts, the obfuscate them to publish. So I'll not implement this feature now.

**Comment by nschloe** [comment]
Got it, thanks for the feedback!

> And the obfuscated scripts aren't intend to be edited or debugged, the idea is that edit or debug the plain scripts, the obfuscate them to publish.

Just to be clear, the function interfaces are needed for usability in the published code, too. I suppose this will get more important going forward as people get used to type hinting etc., but I understand that the pyarmor approach is different. Closing for now.
