### ISSUE TITLE
pyproject.toml: Platform-independent wheels are build

### ISSUE THREAD

**Issue by nschloe** [dashingsoft/pyarmor#644]
If I understand correctly, pyarmor-built wheels are platform-specific, e.g., you can't run a wheel build on Linux-Python3.7 on Windows-Python3.8. Nevertheless, with the new `pyproject.toml` workflow, the standard build process
```
python3 -m build --wheel
```
will produce a _seemingly_ platform-independent wheel, e.g., `foobar-1.0.0-py3-none-any.whl`. This is probably because it sees only Python files; see [here](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#platform-wheels). Perhaps there's a way to tell the builder that the wheels are really platform-dependent.

**Comment by jondy** [comment]
Fix in v7.2.3, set the right python version tag and platform tag in the wheel.

**Comment by nschloe** [comment]
After the change, the wheel
```
foobar-1.0.0-cp39-none-linux_x86_64.whl
```
is build. With some C-sources mixed in, it's
```
foobar-1.0.0-cp39-cp39-linux_x86_64.whl
```
Note sure what difference the `none` vs. `cp39` makes.

**Comment by nschloe** [comment]
Anyway, seems to work!
