### ISSUE TITLE
Check different hardware in dockerized code

### ISSUE THREAD

**Issue by taka-wang** [dashingsoft/pyarmor#645]
Hi @jondy

您好，想請教您一個使用情境，不知道怎麼處理比較合適。

我想透過 `check_gpu.py` 這種方式去綁定硬體資訊，發送不同的 license 檔案給不同客戶。
ex. `pyarmor obfuscate --plugin check_gpu --with-license=outer --src "." --recursive main.py`
但我的 Source Code 是透過 Docker 封裝的，也就是不同客戶都是 Pull 同一個 Docker Image。
在不針對每一個客戶都分別 obfuscate source code 的情況下，您有沒有什麼使用上的建議？

感謝您的軟體！

**Comment by jondy** [comment]
我对 docker 也不了解，有的客户在启动 docker 的时候把物理硬盘挂上，然后绑定加密脚本到物理硬盘上。

**Comment by taka-wang** [comment]
Thanks
