### ISSUE TITLE
PyArmor returns segmentation faultin 3.9 python version

### ISSUE THREAD

**Issue by gsraocisco** [dashingsoft/pyarmor#646]
Hi,

We did install PyArmor on the Alpine container and we are seeing segmentation fault in the 3.9 version. 

Initially, we noticed "snprintf_chk" in the 3.9 version and downloaded "_pytransform.so" and now we are seeing segmentation fault. Could you please help check this?

**(venv) [root@docker testflask]# docker logs errorpycont
Segmentation fault (core dumped)
(v**

**Comment by jondy** [comment]
Pyarmor is platform-dependent, please check the chapter `support platforms` in the documentation.
