### ISSUE TITLE
My pyarmor program got cracked...

### ISSUE THREAD

**Issue by cedrik31tlse** [dashingsoft/pyarmor#648]
**Bad news.. My pyarmor program got cracked...**
I am licensed user, source is Py 3.8 and used Pyarmor 6.7.2.
All was fine until yesterday, someone deobuscated it and then easily cracked it from source.

I will delay my future updates, but need to know the new versions of Pyarmor are protecting from deobfuscators we start to find on Git or do i have to change completely method ? Do i have to move to Python 3.10 for security concerns ?

Team is aware about deobfucators available ?

I love pyarmor, but i took a headache when i saw my baby soft cracked...

**Comment by jondy** [comment]
Do you use option  `--advanced` to obfuscate the scripts?

And refer to
https://pyarmor.readthedocs.io/en/latest/usage.html#improving-security-further

**Comment by cedrik31tlse** [comment]
Yes, i was using the "--advance 2" and also "--with-license" cause i wanted limit versions in time ( but this one was too easy to bypass, just changing computer time).

I dont mind much about the -with-license problen. cause my program needs correct machine time to work

But my big concern is about encryption and access to source code. This have to find a solution

**Comment by jondy** [comment]
Use `--advanced 5` to obfuscate the scripts
