### ISSUE TITLE
About hdinfo

### ISSUE THREAD

**Issue by h1-ti** [dashingsoft/pyarmor#650]
Let me ask you a question.

I want to issue a license that binds the customer's mac address from the server after getting the mac address for the bind in the customer's local environment.

I tried this method (https://pyarmor.readthedocs.io/en/latest/pytransform.html#runtime-module-pytransform), but pytransform.pyd in super plus mode is
It does not work because it was before the license was issued.

Or if I use hdinfo.exe (https://github.com/dashingsoft/pyarmor-core/) to get hard disk information, how can I pass it to python?

**Comment by h1-ti** [comment]
Oh, I'm sorry.
I should just include pytransform.py in the distribution code.

**Comment by h1-ti** [comment]
pytransform.py need _pytransform.dll.

Please tell me how to pass from hdinfo.exe to Python

**Comment by jondy** [comment]
Learn how to use `subprocess.check_output`
