### ISSUE TITLE
Runtime command line argument passing on obfuscated script

### ISSUE THREAD

**Issue by VijayRameshkumar** [dashingsoft/pyarmor#653]
I don't know how to pass command line arguments (runtime) on obfuscated script. (pyarmor) 

Example:

python script.py --arg1 val1 --arg2 val2

I want to implement the same on obfuscated file ...

If it's already available, can you share me the reference.

Thanks in advance.

**Comment by jondy** [comment]
The obfuscated scripts are normal python script, please find the answer in the Python documentation or by google.
