### ISSUE TITLE
Privileged Instruction

### ISSUE THREAD

**Issue by Dxjq** [dashingsoft/pyarmor#656]
I just tried to compile my code with the command: 'pyarmor pack --clean -e" --onefile  --noconsole --icon icon.ico" -x"--advanced 4 --obf-code 2 --restrict=2" main.py'.

I am getting an error with pyarmor which stops the code from compiling and packing to an exe. 
![image](https://user-images.githubusercontent.com/69914882/147575301-07891b8d-2081-4575-9de4-8e580e7c7f46.png)

This code is an anti-debugger which checks for known debuggers in a while true statement.
Line 162 is a "While True:" statement
However I am getting this error in pyarmor meaning that the code doesn't compile.

Please let me know if there is a fix for this,

Thanks

**Comment by jondy** [comment]
Try to insert some redundant statements at the beginning of this function, refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#code-object-could-not-be-obufscated-with-advanced-mode-2
