### ISSUE TITLE
ERROR    No available c compiler found

### ISSUE THREAD

**Issue by itzguno** [dashingsoft/pyarmor#658]
how do i fix this ???

**Comment by jondy** [comment]
Pyarmor is well documented, please read section `super plus mode` first.

**Comment by kr1tx** [comment]
This should help! [](https://pyarmor.readthedocs.io/en/latest/mode.html)
![image](https://user-images.githubusercontent.com/64534388/210930134-70ecab8b-00c8-45b4-9bec-c1baf36c8436.png)
