### ISSUE TITLE
pyarmor, pyinstaller error on m1 macos -RuntimeError: unexpected /var/folders/1z/12fw39h92571xp8c4kz9j6100000gn/T/_MEIz2RfmO/_pytransform.dylib [6234]

### ISSUE THREAD

**Issue by JFuqX** [dashingsoft/pyarmor#659]
I switched from windows to mac and i wanted to compile and obfusticate my script over there, i rewrote it and made sure that it runs under macos. When i pack it with pyinstaller it works, when i compiled it with pyinstaller and pyarmor it doesnt work anymore, under windows it worked with the same command, this is the command i used:

sudo pyarmor pack -e "--onefile --icon /assets/Test.ico" Test.py

This is the output from the packed and obfusticated runnable file when i start it. Without pyarmor it works great ...

Traceback (most recent call last):
  File "<dist/obf/Test.py>", line 3, in <module>
  File "<frozen Test>", line 1379, in <module>
  File "<frozen Test>", line -1, in protect_pytransform
  File "<frozen Test>", line 1356, in check_lib_pytransform
RuntimeError: unexpected /var/folders/1z/12fw39h92571xp8c4kz9j6100000gn/T/_MEIz2RfmO/_pytransform.dylib
[6234] Failed to execute script 'Test' due to unhandled exception!

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

PYINSTALLER VERSION 4.7 
PyArmor Version 7.2.3
Python version 3.9.9

**Comment by Dry05** [comment]
Hey, did you fix this? If yes, can you tell me how?

**Comment by JFuqX** [comment]
Hey sir i fixed it it was cause of the Main Definition if Name = __main__
something, it didnt found the entry point on Mac so i launched it directly.
Anyways thanks for your reply!
Kind regards
John

Dry05 ***@***.***> schrieb am Mo., 10. Jan. 2022, 12:10:

**Comment by Dry05** [comment]
Oh nice find! How did you launch it directly? Rename the main function?

**Comment by JFuqX** [comment]
if __name__ == "__main__“:
Start_Script()
Just removed the ```if __name__ == "__main__“:```
And have done
Start_Script()
Somehow it doesn’t work with pyarmor, when I debug the script before it got obfuscated it works tho, but It was thank god a simple fix

> Am 10.01.2022 um 12:23 schrieb Dry05 ***@***.***>:
> 
> d! How did you launch it directl

**Comment by Dry05** [comment]
Thx a million!! Just fixed it

**Comment by JFuqX** [comment]
I thank you sir <3
