### ISSUE TITLE
Faulty OS detection during obfuscation under WSL

### ISSUE THREAD

**Issue by bbarn3y** [dashingsoft/pyarmor#66]
I have a use case where pyarmor has to be used under Windows Subsystem for Linux (WSL). In this case, however, I think the wrong OS is detected and because of that, the wrong _pytransform file is generated.

What I do:
- Enter WSL in powershell using Windows 10:
`bash`
- Obfuscate my python code:
`pyarmor.exe obfuscate ./Run.py`
- Check dist folder
`ls dist`
> Run.py  Words.py  __pycache__  _pytransform.dll  license.lic  pytransform.key  pytransform.py

As you can see the Windows version of the file was generated: _pytransform.dll
- Run the obfuscated python code
`python3 ./dist/Run.py`
> Could not find "/mnt/d/IdeaProjects/python-samples/test/dist/_pytransform.so"

When trying to run the obfuscated code it expects to find _pytransform.so, which is of course not there.

This seems like a bug. A configuration option or parameter for obfuscation command to force OS would be enough to solve this, but I couldn't find a solution in the docs or the CLI help.
Is there a way to solve this?

Thanks for the help in advance!

**Comment by jondy** [comment]
A quick workaround is to edit the file `dist/pytransform.py`, in the function `_load_library` replace this line `plat = platform.system().lower()` with `plat = "windows"`.

By the way, what's the output this command:
```
python3 -c "import platform
print(platform.system())
```

**Comment by bbarn3y** [comment]
Thanks, I tried to change that. This is the error I'm getting (in WSL):

> /mnt/d/IdeaProjects/python-samples/test/dist/_pytransform.dll: invalid ELF header

If I exit bash and run it in powershell, it works (even without changing the script).

`python3 -c "import platform
print(platform.system())"`

in WSL results in:

> Linux

**Comment by jondy** [comment]
First restore `dist/pytransform.py`, then copy `/path/to/pyarmor/installed/platforms/linux64/_pytransform.so' to `dist/`, and try to run the obfuscated scripts.

If it's not lucky, is it that the obfuscated scripts must be run in the WSL? How about run it by native python3?

If WSL is required and `_pytransform.so` for linux doesn't work, I need build new one for WSL.

**Comment by bbarn3y** [comment]
This is where I found this, file, I'm not sure if it's the correct one?

> D:\ProgramFiles\Python34\Lib\site-packages\pyarmor\platforms\linux64\arm\\_pytransform.so

I copied it into the dist folder, this is the error I'm getting (even though the file is there):

> Load /mnt/d/IdeaProjects/python-samples/test/dist/_pytransform.so failed:
/mnt/d/IdeaProjects/python-samples/test/dist/_pytransform.so: cannot open shared object file: No such file or directory

Yes, sadly we have to run everything under WSL. The environments are separate, we can't guarantee that under windows there will be a version of Python3 in path.

**Comment by jondy** [comment]
Not this one, it's for aarch64 cpu, not x86_64, it should be this
`D:\ProgramFiles\Python34\Lib\site-packages\pyarmor\platforms\linux64\_pytransform.so`

**Comment by bbarn3y** [comment]
Thanks, I just tried that one.
Still an error, although a different one:

> XXX lineno: 1, opcode: 0
Traceback (most recent call last):
  File "dist/Run.py", line 3, in <module>
    __pyarmor__(__name__, __file__, b'{long_encrypted_string}', 1)
  File "<frozen Run>", line 1, in <module>
SystemError: unknown opcode

**Comment by jondy** [comment]
It seems you install `pyarmor` in native windows other than in the WSL. 

You should install `pyarmor` in the WSL, or in the WSH, run `pyarmor` like this:
```
export PYARMOR="python3 D:/ProgramFiles/Python34/Lib/site-packages/pyarmor/pyarmor.py"
$PYARMOR obfuscate Run.py
cd dist
python3 Run.py
```
Here, `python3` should be an application in WSL, not the link to `D:\ProgramFiles\Python34\python.exe`

**Comment by bbarn3y** [comment]
Thanks, reinstalling pyarmor under WSL solved this issue!
