### ISSUE TITLE
--advance bugs code

### ISSUE THREAD

**Issue by itzguno** [dashingsoft/pyarmor#662]
hi i am running 
pyarmor o --exact --platform linux.x86 --platform linux.x86_64 --advanced 2 --obf-code 2 --obf-mod 2

and will get 
```
root@bigboi:~# python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pytransform import pyarmor
  File "/root/pytransform/__init__.py", line 58, in <module>
    import_names()
  File "/root/pytransform/__init__.py", line 54, in import_names
    m = __import__(name, globals(), locals(), ['*'])
ImportError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```
but if i run

pyarmor o --exact --platform linux.x86 --platform linux.x86_64 --obf-code 2 --obf-mod 2

script works fine

contents of script

import time
print("test")
time.sleep(10)

i am running python 3.9.9 and pyarmor 7.4.2. and yes i am uploading the pytransform folder

![Screenshot_2](https://user-images.githubusercontent.com/53296939/148025081-feed953e-1d37-454d-9ca7-7deee117d4a1.png)
![Screenshot_1](https://user-images.githubusercontent.com/53296939/148025085-e6f3e8bf-196b-40e6-b054-d1093dd4092f.png)

im running the test on Ubuntu 20.04.3 LTS (GNU/Linux 5.13.19-2-pve x86_64)

**Comment by jondy** [comment]
Make sure this python interpreter is built with `--enable-shared` and `libpython3.9.so` could be found in this machine.

**Comment by itzguno** [comment]
by doing apt install python3.9-dev it fixed my issue
