### ISSUE TITLE
How is it possible !!!!??

### ISSUE THREAD

**Issue by xurenam** [dashingsoft/pyarmor#664]
this guy is literally reversing pyarmor 😨
https://www.youtube.com/watch?v=1idhXNeluCc

**Comment by jondy** [comment]
Refer to
https://pyarmor.readthedocs.io/en/latest/usage.html#improving-security-further

YouTube is blocked from my location, but I don't think it can reverser `super plus mode`

**Comment by zeyad-mansour** [comment]
> this guy is literally reversing pyarmor 😨 https://www.youtube.com/watch?v=1idhXNeluCc

This is a snake oil product. I can reverse "super plus mode" less than an hour.
