### ISSUE TITLE
Obfuscation super-plus question

### ISSUE THREAD

**Issue by AcierP** [dashingsoft/pyarmor#667]
Hi there.
I was wondering how to access your $HOME/.pyarmor directory to save clang to for obfuscating with super plus mode 5 and whether or not I can use super plus mode 5 to pack (exe) my scripts.

**Comment by AcierP** [comment]
Also I was wondering how you can use a .ico when packing files

**Comment by jondy** [comment]
Learning what's environment variable on Windows to understand `$HOME`, see man page of command `pack` to know how to pass Pyinstaller option
