### ISSUE TITLE
Difficulties while fixing license to runtime.

### ISSUE THREAD

**Issue by whiteowl3** [dashingsoft/pyarmor#668]
Example code from the documentation site fails on all version of python 3.8
```
from ctypes import CFUNCTYPE, cdll, pythonapi, string_at, c_void_p, c_char_p
from sys import platform


def get_bind_key():

    if platform.startswith('win'):
        from ctypes import windll
        dlsym = windll.kernel32.GetProcAddressA
    else:
        prototype = CFUNCTYPE(c_void_p, c_void_p, c_char_p)
        dlsym = prototype(('dlsym', cdll.LoadLibrary(None)))

    refunc1 = dlsym(pythonapi._handle, b'PyEval_EvalCode')
    refunc2 = dlsym(pythonapi._handle, b'PyEval_GetFrame')

    size = refunc2 - refunc1
    code = string_at(refunc1, size)

    print('Get bind key: %s' % sum(bytearray(code)))


if __name__ == '__main__':
    get_bind_key()
```

with the error `SystemError: Negative size passed to PyBytes_FromStringAndSize`

I've seen the issue regarding extending license type to check sum of the library, but I notice that when I use special value "--fixed 1"
Then pyarmor gives no complaints and generates a license with *FIXKEY:0123456789
How is it that this example code fails but pyarmor licenses is happy?
Is runtime fixing actually functioning in this build? 
Can you provide example code to get the runtime key in python 3.8/3.9?
Thank you.

**Comment by jondy** [comment]
Please understand this example, and write your own private check point. It's not a good idea to use a public check point.

Use `objdump` to find the symbol address of `python38.dll`, and change the symbol in both of lines
```
    refunc1 = dlsym(pythonapi._handle, b'PyEval_EvalCode')
    refunc2 = dlsym(pythonapi._handle, b'PyEval_GetFrame')
```

**Comment by whiteowl3** [comment]
> Please understand this example, and write your own private check point. It's not a good idea to use a public check point.

my hope is to use the built-in functionality for binding to a particular runtime.  I use ```pack --onefile``` in my environment so it is extremely conventient.   I conclude from looking at recent issues that perhaps this is less stable on 3.8 and 3.9 than is desirable.  Should I consider the ```--fixed``` flag to be unsupported for python 3.8 and 3.9? Will I need to resort to extending the license to check the runtime? If so, can you please clarify 

> Use objdump to find the symbol address of python38.dll, and change the symbol in both of lines

perhaps with example syntax?  how do I use objdump on ubuntu to find the symbol address of the runtime?  in what way do I change the lines?
I apologize for the inconvenient question.  I am a license holder, and hopefully the instruction will be useful to others.
Thanks.

**Comment by jondy** [comment]
Well for this case, just change 2 lines
```patch
-    refunc1 = dlsym(pythonapi._handle, b'PyEval_EvalCode')
-    refunc2 = dlsym(pythonapi._handle, b'PyEval_GetFrame')
+    refunc1 = dlsym(pythonapi._handle, b'PyEval_GetFrame')
+    refunc2 = dlsym(pythonapi._handle, b'PyEval_EvalCode')
```

**Comment by whiteowl3** [comment]
Alternatively, could you confirm that this has the same level of security?
I am generating a runtime with a license that has bind-mac enabled using
```pyarmor licences --bind-mac {macaddress}```
and then use that to generate a runtime
```pyarmor runtime --advanced 2 --with-license {the license}```

I then take the blake2 hash of the resulting pyarmor.so file and add inline plugin to before import statement:

```#!/usr/bin/python3
# PyArmor Plugin: import os, hashlib
# PyArmor Plugin: libname = os.path.join( os.path.dirname( __file__ ), 'pytransform.so' )
# PyArmor Plugin: hasher = hashlib.blake2b(digest_size=32)
# PyArmor Plugin: with open(libname, "rb") as f:
# PyArmor Plugin: 	hasher.update(f.read())
# PyArmor Plugin: if not hasher.hexdigest() == {the hash}:
# PyArmor Plugin:     raise RuntimeError('Invalid package element. Exiting.')
```

and pack with

```pyarmor pack -e " --onefile" -x " --advanced 2 --restrict 3 --recursive --plugin on --runtime {runtime}" script.py```

Is this sufficient?

**Comment by whiteowl3** [comment]
looks like jondy has already explained how to use modified fix-key login via plugin in this comment
https://github.com/dashingsoft/pyarmor/issues/250#issuecomment-714217635
