### ISSUE TITLE
Multiprocessing issues with SuperMode & Restrict Mode >1

### ISSUE THREAD

**Issue by younesdev1** [dashingsoft/pyarmor#669]
Hello,
Im trying to obfuscate a package with supermode and restrict mode 3, multiprocessing (which is obfuscated with restrict mode 1) cause issues, more precisely because `self._Popen(self)` is calling a restrict-3 obfuscated module and that raises `RuntimeError: Check restrict mode of module failed`

I tried with restrict mode 1 and this issue is not happening. I suppose multiprocessing triggers the restrict check by importing the obfuscated module from a plain scripts or something like that

Anyway to get around this using restrict mode 3?

Traceback

```  File "<frozen multiprocessing.spawn>", line 118, in _main
  File "<frozen multiprocessing.process>", line 116, in start
  File "<REDACTED\__init__.py>", line 2, in <module>
  File "<frozen multiprocessing.context>", line 223, in _Popen
RuntimeError: Check restrict mode of module failed```

**Comment by jondy** [comment]
Please first read the section `restrict mode` in the documentation
