### ISSUE TITLE
Is PyArmor protected against Mysterium?

### ISSUE THREAD

**Issue by fieu** [dashingsoft/pyarmor#671]
Hello,

Is PyArmor protected against Mysterium?

Project link: https://github.com/venaxyt/mysterium

**Comment by jondy** [comment]
You can verify it by a simple test, I don't think it can reverse `super plus mode`.

**Comment by venaxyt** [comment]
> Hello,
> 
> Is PyArmor protected against Mysterium?
> 
> Project link: https://github.com/venaxyt/mysterium

What a pleasure, seems that I'm gettint famous, search pyarmor logo and the mine is before pyarmor's one, it's the first 🤣

**Comment by venaxyt** [comment]
And I already said to @jondy about this I even sent to him a tutorial I made, and a forum but nothing changed.
