### ISSUE TITLE
加密django项目,项目中使用到了celery

### ISSUE THREAD

**Issue by sxiaoy** [dashingsoft/pyarmor#672]
mkdir /code/developer_backend_bak
cp -a /code/developer_backend/* /code/developer_backend_bak
cd /code/developer_backend
pyarmor obfuscate --src="." -r --output=/code/test/developer_backend_bak application/wsgi.py application/celery.py manage.py
在我加密后我无法在使用celery -A application worker -B --loglevel=info来运行celery任务

**Comment by jondy** [comment]
请参考这里
https://pyarmor.readthedocs.io/zh/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

sxiaoy ***@***.***> writes:

> mkdir /code/developer_backend_bak
> cp -a /code/developer_backend/* /code/developer_backend_bak
> cd /code/developer_backend
> pyarmor obfuscate --src="." -r --output=/code/test/developer_backend_bak
> application/wsgi.py application/celery.py manage.py
> 在我加密后我无法在使用celery -A application worker -B --loglevel=info来运行
> celery任务
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were assigned.
>

-- 
Best Regards
Jondy Zhao
