### ISSUE TITLE
Obfuscate such that only one script can be called

### ISSUE THREAD

**Issue by CharlieCheckpt** [dashingsoft/pyarmor#674]
Hello, thank you for this nice and useful library. 

I would like to obfuscate my code in a certain way but I have trouble to make it work.
I looked at the documentation, especially restrict modes, but I still can't figure it out. 

The architecture of the code I want to obfuscate is the following : 

```
exec
    launch.py
    utils.py
pkg1
pkg2
```

`pkg1` and `pkg2` are two packages and `pkg1` calls some functions of `pkg2`.
`exec` is a folder which contains the two scripts `launch.py` and `utils.py`.
`launch.py` is the only script that will be called (`python launch.py`), that calls function/modules from `utils.py`, `pkg1` and `pkg2`.

I would like to obfuscate the code such that the user can't call any functions/modules from pkg1, pkg2 utils, or launch.py, and can only run `python launch.py`.

How can I do this with pyarmor ?

**Comment by jondy** [comment]
Obfuscate the entry script by restrict mode 2, for all the others with restrict mode 4, for example
```
cd /path/to/src
pyarmor obfuscate --src . --restrict 4 exec/launch.py
pyarmor obfuscate --exact --restrict 2 exec/launch.py
```
