### ISSUE TITLE
import pyarmor error

### ISSUE THREAD

**Issue by JKKSI** [dashingsoft/pyarmor#675]
hello there...

i used this command for my python script....

1.- pyarmor licenses --expired 2022-01-20 r001
2.- pyarmor obfuscate --platform linux.x86_64 --with-license licenses/r001/license.lic --plugin check_ntp_time --advanced 2 hello.py
output....
INFO     PyArmor Version 7.3.0
INFO     Python 3.10.1
INFO     Target platforms: ['linux.x86_64']
INFO     Remove cached platform list file C:\Users\Daishinkan\.pyarmor\platforms\index.json
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r48.2/index.json
INFO     Write cached platform list file C:\Users\Daishinkan\.pyarmor\platforms\index.json
INFO     Update target platforms to: ['linux.x86_64.11.py310']
INFO     Source path is "C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio"
INFO     Entry scripts are ['hello.py']
INFO     Use cached capsule C:\Users\Daishinkan\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 2
INFO     Super mode is True
INFO     Super plus mode is not enabled
INFO     Generating super runtime library to "dist"
INFO     Search library for platform: linux.x86_64.11.py310
INFO     Found available libraries: ['linux.x86_64.11.py310']
INFO     Target path for linux.x86_64.11.py310: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86_64\11\py310
INFO     Downloading library file for linux.x86_64.11.py310 ...
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r48.2/linux.x86_64.11.py310/pytransform.cpython-310-x86_64-linux-gnu.so
INFO     Writing target file: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86_64\11\py310\pytransform.cpython-310-x86_64-linux-gnu.so
INFO     Download dynamic library linux.x86_64.11.py310 OK
INFO     Extract pytransform.key
INFO     Generate license file from  licenses\r001\license.lic
INFO     Copying C:\Users\Daishinkan\.pyarmor\platforms\linux\x86_64\11\py310\pytransform.cpython-310-x86_64-linux-gnu.so
INFO     Patch extension dist\pytransform.so
INFO     Patch library file OK
INFO     Generate runtime files OK
INFO     Use protection template: C:\Python3\lib\site-packages\pyarmor\protect_code2.pt
INFO     Start obfuscating the scripts...
INFO            hello.py -> dist\hello.py
INFO     Found plugin check_ntp_time at: C:\Python3\lib\site-packages\pyarmor\plugins\check_ntp_time.py
INFO     Obfuscate 1 scripts OK.

3.- sudo chmod 777 *
4.- sudo python3 hello.py
output ....

──(root💀kali)-[/home/kali/Desktop/hola]
└─# sudo python3 hola.py     
Traceback (most recent call last):
  File "/home/kali/Desktop/hola/hola.py", line 1, in <module>
    from pytransform import pyarmor
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

how to fix?

**Comment by jondy** [comment]
Please refer to documentation "When things go wrong".

**Comment by JKKSI** [comment]
> Please refer to documentation "When things go wrong".

hi, the encryption dont tell me any error , but when i execute my pythonfile in linux give me the output
──(root💀kali)-[/home/kali/Desktop/hola]
└─# sudo python3 hola.py
Traceback (most recent call last):
File "/home/kali/Desktop/hola/hola.py", line 1, in
from pytransform import pyarmor
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

**Comment by jondy** [comment]
There is same question and answer in the documentation.

**Comment by JKKSI** [comment]
> There is same question and answer in the documentation.

sorry i didnt saw the documentation, i checked the documentation as you said, i tried the steps but still dont working, all steps realized...

```

**Comment by JKKSI** [comment]
> There is same question and answer in the documentation.

hello , sorry i didnt read the documentation, now i read and followed the steps, i tried the solution in pyarmor documentation "when things go wrong", steps i tried...

```
C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio>pyarmor -d obfuscate --platform linux.x86_64 --advanced 2 --exact berserker.py
DEBUG    PyArmor installation path: C:\Python3\lib\site-packages\pyarmor
DEBUG    PyArmor home path: C:\Users\Daishinkan\.pyarmor
DEBUG    Native platform is windows.x86_64
DEBUG    Search dynamic library in the path: C:\Python3\lib\site-packages\pyarmor\platforms
DEBUG    Loaded dynamic library: C:\Python3\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
DEBUG    The version of core library is (48, 2, 7)
INFO     PyArmor Version 7.3.0
INFO     Python 3.10.1
INFO     Target platforms: ['linux.x86_64']
DEBUG    Load platform list from C:\Users\Daishinkan\.pyarmor\platforms\index.json
INFO     Update target platforms to: ['linux.x86_64.11.py310']
INFO     Source path is "C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio"
INFO     Entry scripts are ['berserker.py']
INFO     Use cached capsule C:\Users\Daishinkan\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Exact
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 2
INFO     Super mode is True
INFO     Super plus mode is not enabled
INFO     Generating super runtime library to "dist"
DEBUG    Load platform list from C:\Users\Daishinkan\.pyarmor\platforms\index.json
DEBUG    Target dynamic library: ['C:\\Users\\Daishinkan\\.pyarmor\\platforms\\linux\\x86_64\\11\\py310\\pytransform.cpython-310-x86_64-linux-gnu.so']
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying C:\Users\Daishinkan\.pyarmor\platforms\linux\x86_64\11\py310\pytransform.cpython-310-x86_64-linux-gnu.so
INFO     Patch extension dist\pytransform.so
DEBUG    Patching dist\pytransform.so
DEBUG    Found pattern at b8924
DEBUG    Patch 261 bytes from b8944
DEBUG    Patch 270 bytes from b8a49
DEBUG    Patch 412 bytes from b8b57
INFO     Patch library file OK
INFO     Generate runtime files OK
INFO     Use protection template: C:\Python3\lib\site-packages\pyarmor\protect_code2.pt
INFO     Start obfuscating the scripts...
INFO            C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio\berserker.py -> dist\berserker.py
INFO     Write patched script for debugging: C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio\berserker.py.pyarmor-patched
INFO     Obfuscate 1 scripts OK.
```
2.- $ I copy whole folder dist to my Kali Linux
3.- $ sudo chmod 777 * && sudo python3 berserker.py

```
Traceback (most recent call last):
  File "/home/kali/Desktop/hola/berserker.py", line 1, in <module>
    from pytransform import pyarmor
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

```
