### ISSUE TITLE
Obfuscate python script not running in Cloudera Server with Helios UI

### ISSUE THREAD

**Issue by zonnalobo** [dashingsoft/pyarmor#679]
Hi,

I created an `obfuscate` python script `with-license` and `disable-restriction` to run on `python`  in `Cloudera-server` using `Helios`. So I copied `pytransform` folder to `/python3.6/site-packages` in all master and driver nodes. However when I try to import the script it is not working without any log. To know in which line it stops, I put `print` after each line like below:

```
print(1)
from pytransform import pyarmor_runtime
print(2)
pyarmor_runtime()
print(3)
__pyarmor__(__name__, __file__, b'\xxxx',2)
print(4)

```
The result showing `print(2)` in log and stop. So, I guess the problem in `pyarmor_runtime()`.
If I use the same script in my `Jupyter-Notebook` running in the same system then it's work.

How to solve it? Do I miss something?
Please help.

Notes: Python: 3.6, Pyarmor: 7.3, and OS: RHEL 7.

**Comment by jondy** [comment]
Please first test a hello world script and run it by python interpreter directly, check it work or not.

And read the documentation chapter "understand the obfuscate scripts"

**Comment by zonnalobo** [comment]
Hi @jondy, this is not my first time working with obfuscate and I already read it and test the obfuscate script in python directly and jupyter-notebook. Thanks

**Comment by jondy** [comment]
It seems it's related to jupiter-notebook, I never use Jupter-notebook and have no more idea only by `pyarmor_runtime` does not work.

**Comment by jondy** [comment]
I have no idea about Helios UI on Cloudera too.

**Comment by zonnalobo** [comment]
Hi @jondy, I'm afraid the issue in running `pyarmor_runtime()` due to the path of the `_pytransform.so`. Because when run the the script in Helios, Helios will copy all running files to a temporary files include the pytransform folder and obfuscate script. We also already put a line in python main script to set the temporary path as python path: `sys.path.append(os.path.abspath(''))`, that's why it is success to import pytransform. The temporary folder location can be got by using `os.path.abspath('')`.
I see in the `pyarmor_runtime()`, there is a parameter `path`, how to use it? Perhaps by setting the path, it can help. Thanks

**Comment by jondy** [comment]
Great, pyarmor_runtime is defined in the pytransform.py, check the function definition in this file.
