### ISSUE TITLE
`pyarmor register` incorrect return value in Pyarmor 7.3.1 

### ISSUE THREAD

**Issue by Peddle** [dashingsoft/pyarmor#680]
`pyarmor register` claims I'm running in trial mode while `pyarmor --version` correctly recognizes my license key.

License key set in environment var `PYARMOR_KEY`.

Downgrading to 7.3.0 seems to fix this issue

**Comment by jondy** [comment]
In the latest version, if register code is not start with "pyarmor-vax-", "pyarmor register" will show trial version.
