### ISSUE TITLE
Super Plus Mode - Windows, Linux etc

### ISSUE THREAD

**Issue by jackbayliss** [dashingsoft/pyarmor#681]
Hello, I would like to know if it's possible for `super plus mode` to work on `windows.x86_64`, `linux.x86_64`, `darwin.x86_64` + `linux.armv7`

My issue is that I need to encrypt my application to the maximum - to prevent decryption, etc, but, also allow it to work on all platforms. Not sure what you recommend, I usually use `pyarmor pack` for Windows and `pyarmor obfuscate` for all other OS'. Would you suggest using `--advanced 2`?  Not sure what's the **most secure** option.

The problem is, I'm using functions like `eval` - so I'm not sure what is the best and most secure method in this case.

**Comment by jondy** [comment]
Jack ***@***.***> writes:

> Hello, I would like to know if it's possible for super plus mode to work on
> windows.x86_64, linux.x86_64, darwin.x86_64 + linux.armv7
>

The first 3 platforms should be ok. linux.armv7 is not supported by spp mode now.

> My issue is that I need to encrypt my application to the maximum - but also
> allow it to work on all platforms. Not sure what you recommend, I usually use
> pyarmor pack for Windows and pyarmor obfuscate for all other OS'. Would you
> suggest using --advanced 2? Not sure what's the most secure option.
>

My suggestion is super plus mode (--advaned 5) as far as possible.

**Comment by jackbayliss** [comment]
Thanks for the quick reply, is the eval function available to use for advanced 5? I remember reading something :) 

>

**Comment by jondy** [comment]
No problem, use super plus mode `--advanced 5`, the unsupported functions will be obfuscated by super mode automatically, I have document it.

**Comment by jackbayliss** [comment]
@jondy  Thanks! I'll give it a try, I'll leave this open to report back 👍🏻

**Comment by jackbayliss** [comment]
@jondy  Just an update, spp seems to work- but I get the following for one file:
```INFO            Updater.py -> dist\Updater.py
INFO     Generating spp code for <frozen Updater> ...
ERROR    outfile
```

**Comment by jackbayliss** [comment]
Will create a separate thread for this issue 💯
