### ISSUE TITLE
ERROR    The latest pyarmor could not work with core library r41.15a, pyarmor register no work correctly

### ISSUE THREAD

**Issue by JKKSI** [dashingsoft/pyarmor#683]
Hello, 
$ I'm trying to download windows.x86 platform from my Kali Linux by pyarmor 7.3.1 
$ Those got the step i executed
```
┌──(root💀kali)-[/home/kali]
└─# pip3 install pyarmor                                               127 ⨯
Collecting pyarmor
  Downloading pyarmor-7.3.1-py2.py3-none-any.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 490 kB/s 
Installing collected packages: pyarmor
Successfully installed pyarmor-7.3.1
┌──(root💀kali)-[/home/kali]
└─# pyarmor download    
INFO     PyArmor Trial Version 7.3.1
INFO     Python 3.9.8
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/index.json
INFO     Create platform path: /root/.pyarmor/platforms
INFO     Write cached platform list file /root/.pyarmor/platforms/index.json
WARNING  The trial version could not download the latest core libraries, tag r41.15a is always used
ERROR    The latest pyarmor could not work with core library r41.15a, please use pyarmor < v7.0.0
```
$ So Then i register my pyarmor with the next command
```
┌──(root💀kali)-[/home/kali/Desktop]
└─# pyarmor register pyarmor-regcode-1110.txt 
INFO     PyArmor Trial Version 7.3.1
INFO     Python 3.9.8
INFO     Read registration code file: pyarmor-regcode-1110.txt
INFO     Start to activate this code
INFO     Got keyfile of this code, this code is activated
INFO     Start to register PyArmor with keyfile
INFO     Save registration data to: /root/.pyarmor
INFO     Extracting license.lic
INFO     Extracting .pyarmor_capsule.zip
INFO     This keyfile has been registered successfully.
INFO     Run "pyarmor register" to check registration information.
```
$ I Run pyarmor register for check my reg information
```
┌──(root💀kali)-[/home/kali/Desktop]
└─# pyarmor register                         
INFO     PyArmor Trial Version 7.3.1
INFO     Python 3.9.8
PyArmor Trial Version 7.3.1


If there is no registration code yet, please purchase one by command

    pyarmor register --buy

Or open the following url in any webbrowser directly

https://order.shareit.com/cart/add?vendorid=200089125&PRODUCT[300871197]=1

````
$ I Try to obfuscate my script with --advanced 2 for check if is pyarmor register bug or something simillar
```
┌──(root💀kali)-[/home/kali/Desktop]
└─# pyarmor obfuscate --exact --advanced 2 berserkeraes256.py 
INFO     PyArmor Version 7.3.1
INFO     Python 3.9.8
INFO     Target platforms: Native
INFO     Remove cached platform list file /root/.pyarmor/platforms/index.json
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r48.2a/index.json
INFO     Write cached platform list file /root/.pyarmor/platforms/index.json
INFO     Update target platforms to: ['linux.x86_64.11.py39']
INFO     Source path is "/home/kali/Desktop"
INFO     Entry scripts are ['berserkeraes256.py']
INFO     Use cached capsule /root/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Exact
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 2
INFO     Super mode is True
INFO     Super plus mode is not enabled
INFO     Generating super runtime library to "dist"
INFO     Search library for platform: linux.x86_64.11.py39
INFO     Found available libraries: ['linux.x86_64.11.py39']
INFO     Target path for linux.x86_64.11.py39: /root/.pyarmor/platforms/linux/x86_64/11/py39
INFO     Downloading library file for linux.x86_64.11.py39 ...
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r48.2a/linux.x86_64.11.py39/pytransform.cpython-39-x86_64-linux-gnu.so
INFO     Writing target file: /root/.pyarmor/platforms/linux/x86_64/11/py39/pytransform.cpython-39-x86_64-linux-gnu.so
INFO     Download dynamic library linux.x86_64.11.py39 OK
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Update capsule to add default license file
INFO     Copying /root/.pyarmor/platforms/linux/x86_64/11/py39/pytransform.cpython-39-x86_64-linux-gnu.so
INFO     Patch extension dist/pytransform.so
INFO     Patch library file OK
INFO     Generate runtime files OK
INFO     Use protection template: /usr/local/lib/python3.9/dist-packages/pyarmor/protect_code2.pt
INFO     Start obfuscating the scripts...
INFO            /home/kali/Desktop/berserkeraes256.py -> dist/berserkeraes256.py
INFO     Obfuscate 1 scripts OK.
```
$ Pyarmor obfuscate correctly my script with --advanced 2 and script executed succefully correctly, but continue showing "Free Trial"
$ I Dont have my regcode in any other dispositive , I Uninstalled 100 % and checked there is no any pyarmor file in my windows.
$ I Run the next commands for try download windows.x86 library 
```
┌──(root💀kali)-[/home/kali/Desktop/dist]
└─# pyarmor download windows.x86                                     2 ⨯ 1 ⚙
INFO     PyArmor Trial Version 7.3.1
INFO     Python 3.9.8
INFO     Downloading dynamic library for windows.x86
INFO     Search library for platform: windows.x86
INFO     Found available libraries: ['windows.x86.7', 'windows.x86.0', 'windows.x86.11.py39', 'windows.x86.11.py38', 'windows.x86.11.py37', 'windows.x86.11.py27', 'windows.x86.21', 'windows.x86.25.py39', 'windows.x86.25.py38', 'windows.x86.25.py37', 'windows.x86.25.py27']
INFO     Target path for windows.x86.7: /root/.pyarmor/platforms/windows/x86/7
INFO     Downloading library file for windows.x86.7 ...
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/win32/_pytransform.dll
ERROR    Verify dynamic library failed, try to reinstall the latest pyarmor and run "pyarmor download -u" to fix it
                                                                             
┌──(root💀kali)-[/home/kali/Desktop/dist]
└─# pyarmor download -u                                              1 ⨯ 1 ⚙
INFO     PyArmor Trial Version 7.3.1
INFO     Python 3.9.8
INFO     Removed cached platform index file /root/.pyarmor/platforms/index.json
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/index.json
INFO     Write cached platform list file /root/.pyarmor/platforms/index.json
WARNING  The trial version could not download the latest core libraries, tag r41.15a is always used
ERROR    The latest pyarmor could not work with core library r41.15a, please use pyarmor < v7.0.0
                                                                             
┌──(root💀kali)-[/home/kali/Desktop/dist]
└─# pyarmor download windows.x86                                     1 ⨯ 1 ⚙
INFO     PyArmor Trial Version 7.3.1
INFO     Python 3.9.8
INFO     Downloading dynamic library for windows.x86
INFO     Search library for platform: windows.x86
WARNING  The trial version could not download the latest core libraries, tag r41.15a is always used
ERROR    The latest pyarmor could not work with core library r41.15a, please use pyarmor < v7.0.0
```
$ I Tried reboot the system later i Register but is the same result, Python version 3.9.8
$ I Tried Delete the VM and reinstall other and is the same
$ Do you can help me to fix this or maybe provide me a link in the documentation for fix this?
$ I Have search already library r41.15a in Pyarmor Documentation, but there is none results found
$ Thanks for reading and i hope you answer soon

**Comment by jondy** [comment]
The license issued before about 2020 year may show trial version in the latest version.

**Comment by ThomasTrovon** [comment]
> The license issued before about 2020 year may show trial version in the latest version.

I bought my license, right now, and I'm having the same problem. I can't register my pyarmor. What do I do?
When I use the pack command, it works! But my pyarmor keeps saying it's a trial, and I bought it today, 01/26/2022

**Comment by JKKSI** [comment]
> The license issued before about 2020 year may show trial version in the latest version.

what i can do for i be abble to download more platforms?, because i cant download with pyarmor download

**Comment by jondy** [comment]
VIPER X Chaos ***@***.***> writes:

>  The license issued before about 2020 year may show trial version in the
>  latest version.
>
> what i can do for i be abble to download more platforms?, because i cant
> download with pyarmor download
>

Purchase a new license or use old version.

**Comment by jondy** [comment]
Thomas Nilton de Carvalho Vanini ***@***.***> writes:

> I bought my license, right now, and I'm having the same problem. I can't
> register my pyarmor. What do I do?

What's the output when running "pyarmor register pyarmor-xxxxxx.txt"?

**Comment by JKKSI** [comment]
> VIPER X Chaos ***@***.***> writes:
> The license issued before about 2020 year may show trial version in the latest version. what i can do for i be abble to download more platforms?, because i cant download with pyarmor download
> Purchase a new license or use old version.

if i use pyarmor old version i dont would loss the last updates and bugs correction?, there is no a way for maybe update my license to last version?, when i bought pyarmor i thought i was going to have free update forever because before buy license the pyarmor page said was is lifetime

**Comment by ThomasTrovon** [comment]
> Thomas Nilton de Carvalho Vanini ***@***.***> writes:
> I bought my license, right now, and I'm having the same problem. I can't register my pyarmor. What do I do?
> What's the output when running "pyarmor register pyarmor-xxxxxx.txt"?

Here in annex...

![Captura de tela 2022-01-27 111037](https://user-images.githubusercontent.com/10778234/151386556-bab5df37-2c4b-4485-9951-0d5b27c6fb72.png)

**Comment by jondy** [comment]
VIPER X Chaos ***@***.***> writes:

>  VIPER X Chaos @.***> writes:
>  The license issued before about 2020 year may show trial version in the
>  latest version. what i can do for i be abble to download more platforms?,
>  because i cant download with pyarmor download
>  Purchase a new license or use old version.
>
> if i use pyarmor old version i dont would loss the last updates and bugs
> correction?, there is no a way for maybe update my license to last version?,
> when i bought pyarmor i thought i was going to have free update forever
> because before buy license the pyarmor page said was is lifetime
>
I never promise the license will be valid for the future version, please check the EULA of pyarmor online.

**Comment by jondy** [comment]
@ThomasTrovon
How about run the command `pyarmor --version'?

**Comment by JKKSI** [comment]
> 

i checked, i didnt saw it before but i saw it now, i understand, if i purchase new license how much versions would work 100 % fine ?, for example from 7.3.1 to 8.0.1 , or something simillar, i ask for calculate the interval of the time in where i will have the new license working before purchase a new again

**Comment by jondy** [comment]
VIPER X Chaos ***@***.***> writes:

> i checked, i didnt saw it before but i saw it now, i understand, if i
> purchase new license how much versions would work 100 % fine ?, for example
> from 7.3.1 to 8.0.1 , or something simillar, i ask for calculate the interval
> of the time in where i will have the new license working before purchase a
> new again
>

pyarmor keeps in improving the scecurity, there is no plan in which version pyarmor will no change and everything is fine.

Some new features may be added by user's demand, and old license may not work in future version.

**Comment by jondy** [comment]
Thomas Nilton de Carvalho Vanini ***@***.***> writes:

>  The license issued before about 2020 year may show trial version in the
>  latest version.
>
> I bought my license, right now, and I'm having the same problem. I can't
> register my pyarmor. What do I do?
> When I use the pack command, it works! But my pyarmor keeps saying it's a
> trial, and I bought it today, 01/26/2022
>
Please upgrade the latest version v7.3.2, this issue has been fixed.

**Comment by ThomasTrovon** [comment]
> @ThomasTrovon How about run the command `pyarmor --version'?

I think it's a visual bug...

![image](https://user-images.githubusercontent.com/10778234/151656907-008a8996-1a33-4edf-a420-bcc4488a35c2.png)

One command says that I have licence, and the other says that I don't..

As you can see, after updating the error has changed...

**Comment by jondy** [comment]
@ThomasTrovon no discussion place for pyarmor. pyarmor is well documented, the common questions will be updated into the documentation continously.

**Comment by ThomasTrovon** [comment]
> @ThomasTrovon no discussion place for pyarmor. pyarmor is well documented, the common questions will be updated into the documentation continously.

And if my question was not documented? How can I solve my problem?

**Comment by jondy** [comment]
Thomas Nilton de Carvalho Vanini ***@***.***> writes:

>  @ThomasTrovon no discussion place for pyarmor. pyarmor is well
>  documented, the common questions will be updated into the documentation
>  continously.
>
> And if my question was not documented? How can I solve my problem?
>

Here it is to ask and answer the new question.

**Comment by ThomasTrovon** [comment]
> Thomas Nilton de Carvalho Vanini ***@***.***> writes:
> @ThomasTrovon no discussion place for pyarmor. pyarmor is well documented, the common questions will be updated into the documentation continously. And if my question was not documented? How can I solve my problem?
> Here it is to ask and answer the new question.

As my projects grow, so do my installed public libraries (of those that we install from the internet with normal `pip install`). However, I don't use all my libraries in all my projects. I noticed that when I use `pyarmor pack` it processes all my installed libraries. Even the ones I'm not using in the project. For example, in the following image I am compiling a simple print('Hello World!') 

![image](https://user-images.githubusercontent.com/10778234/151686216-4ea4f9ac-991d-4f83-a0f9-a079a889c14d.png)

And as you can see, pyarmor even processes PyQt6, which I'm not even using in this project! 

![image](https://user-images.githubusercontent.com/10778234/151686328-e823913c-d174-45ac-8529-45a1b70d780a.png)

Among other libraries that are not being used. And this gets worse as more libraries installed I have in my environment, even without using them.

My main concern in having bought pyarmor was to protect only my code, which I made myself. I have no interest in protecting public libraries, which are easily found freely and freely on the internet, and because of that, it's a waste of time for me to have to wait for them to be processed. I don't want to encrypt them, so, just copy them like pyinstaller does, resolves the problem, and make the process more faster.

So my question, which I haven't found an answer anywhere is: is there anyway, in the pyarmor pack command, to encrypt only my code, and ignore the encryption of all the codes of the "venv libraries", just copying them as does the pyinstaller? If this is already possible, could you explain to me how to do it? If this is still not possible, will you ever be able to add in future this functionality to pyarmor?

Thank You for the patience...

**Comment by jondy** [comment]
Pleare refer to man page of each command to understand the usage of each option.
