### ISSUE TITLE
Problems building pyarmored wheel

### ISSUE THREAD

**Issue by hectorambit** [dashingsoft/pyarmor#684]
I'm following the guide in the official documentation about ['Build Pyarmored Wheel'.](https://pyarmor.readthedocs.io/en/latest/build-wheel.html#build-pyarmored-wheel) I have this [config file](https://github.com/dashingsoft/pyarmor/files/7949925/config.toml.txt)
 but when I run `pip wheel .`  with pyarmor I get the error: `ModuleNotFoundError: No module named 'pip'` (you could find more details [here](https://github.com/dashingsoft/pyarmor/files/7949833/error_trace.txt)) and obviously I have installed pip. Therefore, when I run the same command without pyarmor is the config file (as official documentation shows in the first step) it works properly.

In order to help you to find the best solution, I have also attached a screenshot of my project structure, the [requirements file](https://github.com/dashingsoft/pyarmor/files/7949841/requirements.txt), and the results of the [pip list](https://github.com/dashingsoft/pyarmor/files/7949838/pip_list.txt). As you can see, the results show that pip in version is 21.3.1 is installed in my venv.

Looking for other alternatives, I have also tried to do it in two steps: obfuscate with pyarmor and then build the wheel with setuptools and a setup.py. First, I have pyarmored the project with `pyarmor build -B` using this [.pyarmor_config](https://github.com/dashingsoft/pyarmor/files/7949882/pyarmor_config.txt)
and it seems to generates correctly the pyarmored package in the dist folder (screenshot attached) and adds correctly the bootstrap code to the `__main__.py` file:

`from pytransform import pyarmor_runtime`
`pyarmor_runtime()`
`__pyarmor__(__name__, __file__, b'\x50\x59\x41\x52\x4d\x4f\x52\x00...` 

But when I try to run pyarmored code via `python -m tempo_report`, I get the error `NameError: name '__pyarmor__' is not defined` for the `__init__.py` (more details [here](https://github.com/dashingsoft/pyarmor/files/7949837/execution_error_trace.txt)). 

Could you help me to solve any of these problems in order to be able to build the pyarmored wheel?

Thank you so much in advance.

![project_structure_screenshot](https://user-images.githubusercontent.com/34648461/151346706-e80e16e8-4fec-4950-8271-11aa63720044.png)
![dist_screenshot](https://user-images.githubusercontent.com/34648461/151346281-36338b12-e091-456a-85ba-3b2fe7c0e8c6.png)

**Comment by hectorambit** [comment]
Hi again, 

I have forgotten some important information. 

Python 3.7.4 on a MacOS Monterey 12.1 but we have also tried in a Macos BigSur 11.5.2

Thanks again

**Comment by jondy** [comment]
Please refer to this section and the note
https://pyarmor.readthedocs.io/en/latest/build-wheel.html#how-does-it-work

**Comment by hectorambit** [comment]
Thanks @jondy, but pyarmoring the project with `pyarmor obfuscate`, I have the same problem that I already described in my previous message when I have tried with `pyarmor build -B`and there `.pyarmor_config`. 

I ran: 
`pyarmor obfuscate --enable-suffix --recursive --bootstrap 3 -O dist/tempo_report tempo_report/__main__.py`

And when I tray to execute the pyarmored module with `python -m tempo_report` I get this error:

> Traceback (most recent call last):
  File "/Users/hambit/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/hambit/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/hambit/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/hambit/dev/tempo_report/dist/tempo_report/__init__.py", line 1, in <module>
    __pyarmor__(__name__, __file__, b'\x50\x59\x41\x52\x4d\x4f\x52\x00\x00\x03\x07\x00\x42\x0d\x0d\x0a\x09\x30\xe0\x02\x00\x00\x00\x00\x01\x00\x00\x00\x40\x00\x00\x00\xaa\x00\x00\x00\x00\x00\x00\x10\x25\xc3\x9d\xf3\xb9\x0d\x6a\x63\xf7\x4e\xcf\xcc\xac\x7c\x63\xbd\x00\x00\x00\x00\x00\x00\x00\x00\x0f\xe9\x3e\x11\x09\x03\xe0\x20\xa9\xf2\x8f\x09\x17\x59\xc7\x0f\x5a\x0f\x6f\xbd\x10\x72\x17\x98\xe3\x84\xf4\x23\x7b\xfa\x10\xa8\x08\x29\xab\x79\x60\xab\x3a\xb4\xcb\xb9\xbf\x95\x78\xf8\xed\x21\xcc\x94\xc4\x8e\xa6\x76\xd8\x30\x4f\xf9\x71\x89\x79\xbc\x13\x7b\xc2\x8f\xb0\x27\xaa\x48\xdd\x47\x45\x3a\xb5\xd6\x5b\x5a\x7f\xe7\x4b\xb8\x8c\x8b\x46\x55\x8f\x77\xf3\x59\x4f\x06\x90\x60\xd9\x92\xa6\x7e\x6f\xdb\x33\xe4\x67\xdb\xca\x9a\x73\x7d\x08\x2c\xbf\x20\x8b\x45\x10\x68\xac\xbf\xf1\x20\x5b\x73\xac\x9d\x61\xab\x5d\x7b\x57\x30\x0d\xea\xca\xba\x2a\xb3\x2a\x6d\xf0\x02\x18\x5c\xb5\xa3\x5a\x6e\xcf\x6d\x94\x81\xb1\xbd\x9e\xb6\x67\x68\xda\xbf\xa3\x2a\x14\xb0\xf4\xae\x14\x49\x2d\xb4\xde\x4a', 2)
NameError: name '__pyarmor__' is not defined

**Comment by jondy** [comment]
Héctor Ambit ***@***.***> writes:

> Thanks @jondy, but pyarmoring the project with pyarmor obfuscate, I have the
> same problem that I already described in my previous message when I have
> tried with pyarmor build -Band there .pyarmor_config.
>
> I ran:
> pyarmor obfuscate --enable-suffix --recursive --bootstrap 3 -O
> dist/tempo_report tempo_report/__main__.py
>
> And when I tray to execute the pyarmored module with python -m tempo_report I
> get this error:
>
>  Traceback (most recent call last):
>  File "/Users/hambit/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line
>  183, in _run_module_as_main
>  mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>  File "/Users/hambit/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line
>  142, in _get_module_details
>  return _get_module_details(pkg_main_name, error)
>  File "/Users/hambit/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line
>  109, in _get_module_details
>  import(pkg_name)
>  File "/Users/hambit/dev/tempo_report/dist/tempo_report/init.py", line 1,
>  in 
>  pyarmor(name, file,
>  b'\x50\x59\x41\x52\x4d\x4f\x52\x00\x00\x03\x07\x00\x42\x0d\x0d\x0a\x09\x30\xe0\x02\x00\x00\x00\x00\x01\x00\x00\x00\x40\x00\x00\x00\xaa\x00\x00\x00\x00\x00\x00\x10\x25\xc3\x9d\xf3\xb9\x0d\x6a\x63\xf7\x4e\xcf\xcc\xac\x7c\x63\xbd\x00\x00\x00\x00\x00\x00\x00\x00\x0f\xe9\x3e\x11\x09\x03\xe0\x20\xa9\xf2\x8f\x09\x17\x59\xc7\x0f\x5a\x0f\x6f\xbd\x10\x72\x17\x98\xe3\x84\xf4\x23\x7b\xfa\x10\xa8\x08\x29\xab\x79\x60\xab\x3a\xb4\xcb\xb9\xbf\x95\x78\xf8\xed\x21\xcc\x94\xc4\x8e\xa6\x76\xd8\x30\x4f\xf9\x71\x89\x79\xbc\x13\x7b\xc2\x8f\xb0\x27\xaa\x48\xdd\x47\x45\x3a\xb5\xd6\x5b\x5a\x7f\xe7\x4b\xb8\x8c\x8b\x46\x55\x8f\x77\xf3\x59\x4f\x06\x90\x60\xd9\x92\xa6\x7e\x6f\xdb\x33\xe4\x67\xdb\xca\x9a\x73\x7d\x08\x2c\xbf\x20\x8b\x45\x10\x68\xac\xbf\xf1\x20\x5b\x73\xac\x9d\x61\xab\x5d\x7b\x57\x30\x0d\xea\xca\xba\x2a\xb3\x2a\x6d\xf0\x02\x18\x5c\xb5\xa3\x5a\x6e\xcf\x6d\x94\x81\xb1\xbd\x9e\xb6\x67\x68\xda\xbf\xa3\x2a\x14\xb0\xf4\xae\x14\x49\x2d\xb4\xde\x4a',
>  2)
>  NameError: name 'pyarmor' is not defined
>
About this issue, please check the document "When things go wrong".
