### ISSUE TITLE
Cannot run script compiled with Super Plus Mode - c0000005

### ISSUE THREAD

**Issue by jackbayliss** [dashingsoft/pyarmor#685]
**pyarmor version:**  7.3.1 
**python version:** 3.9.0
**OS:** `Windows 10`, 
**Processor:**  `AMD Ryzen 5 5600X 6-Core Processor 3.70 GHz`

**Description:**
When compiling a script with `--advanced 5`  it compiles fine and I get `INFO     Obfuscate 19 scripts OK.`  
I have LLVM13.0.0-win64 installed, and clang.exe exists in my python home dir. I have installed  C++ Redistributable too.

When I run the main script, I get the following:
1. A windows reporting problem in `taskmgr.exe`
2. A report log in `EventViewer` specifying the below:
 
![image](https://user-images.githubusercontent.com/13621738/151462847-3089e25f-a2cd-4c0c-9d51-4bb319484d7f.png)

3. Crash log in EventViewer ( I believe the error is c0000005 )
```
Fault bucket 2041838138000172048, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: python.exe
P2: 3.9.150.1013
P3: 5f7b3dcb
P4: StackHash_c0b4
P5: 0.0.0.0
P6: 00000000
P7: c0000005
P8: PCH_98_FROM_unknown+0x0000000000000000
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER63C9.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6418.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6428.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6436.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6456.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_python.exe_d9cfac3a29e37dfe84248ce9caac5f84c30925a_9e62ca23_0bf3a43d-30cf-4eb1-ac03-adb3381e78e5

Analysis symbol: 
Rechecking for solution: 0
Report Id: ce00c70a-ec37-4958-8c40-180ee5dfc501
Report Status: 268435456
Hashed bucket: fab623553621a2b06c5610f7e8586410
Cab Guid: 0
```

I believe it may be the Data Execution Prevention on Windows- from what I have seen from other reports of this error.

**Comment by jondy** [comment]
Try to `--advanced 2` check it work or not. If it works, use online option `no-spp-mode` to ignore some scripts or functions, please refer to documentation about how to use online option.

**Comment by jackbayliss** [comment]
@jondy Thanks! I'll try it, will report back.

**Comment by jackbayliss** [comment]
`--advanced 2` is fine, I emailed you a file I'm having issue with.
It has issues if I:
```
import os
import json
import time

```

(If I comment it out, it compiles fine, very strange) - I'm thinking this file may be why it's crashing - as it only compiles without the import.

**Comment by jondy** [comment]
Do you mean that it's crashed to obfuscate the script which only include 3 imports lines by `--advanced 5`? Or obfuscating ok, but run it crashed?

**Comment by jackbayliss** [comment]
When obfuscating the script it says ERROR.

If I comment out the imports and then compile it works fine.

This file is imported by another file. So, I’m guessing this error could be why it’s crashing on runtime?

I’ve emailed you the full file, I’m curious why it says ERROR

>

**Comment by jackbayliss** [comment]
So, if I compile it without the imports the main script doesn't run. (It crashes)

If I leave the imports in, the main script doesn't compile.

Hope that makes more sense?

**Comment by jackbayliss** [comment]
@jondy  

So there's two things:

1) The updater script:
So, if I obfuscate the script with the imports, I get the following: (script is in your email for you to see)
![image](https://user-images.githubusercontent.com/13621738/151715418-e96bdab0-214d-40cd-96fb-268c3d6d4c92.png)
If I comment out the import it compiles fine.


2) The main script, when I try and run it - I get an instant app crash and event viewer with the following 
![image](https://user-images.githubusercontent.com/13621738/151715572-6b075a24-92f2-4acb-9dee-e6ac908d9206.png)

I've added the no-spp option to all of the scripts on the first line, but they don't seem to be ignored (not sure if I'm missing something, but it works fine in a smaller test file) : 
![image](https://user-images.githubusercontent.com/13621738/151715601-2558dc12-8047-4ce4-ace4-ec36f4bf469c.png)


Not sure what else I can do to get advanced 5 working, I may just go back to advanced 2, but my worry is security :)

**Comment by jondy** [comment]
Would you send a few example scripts which obfuscated failed? It's difficult if I could reproduce it.

**Comment by jackbayliss** [comment]
@jondy  I have done so with the subject `File failing in --advanced 5 mode` for the `Updater.py` script. 
If I add the no-spp-mode it's just ignored.

**Comment by jackbayliss** [comment]
Could there perhaps be a cli option such as `-x"no-spp-mode"`, so that it doesn't read each file and rely on the `# pyarmor options:`?

**Comment by jondy** [comment]
Jack ***@***.***> writes:

> Could there perhaps be a cli option such as -x"no-spp-mode", so that it
> doesn't read each file and rely on the # pyarmor options:?
>

In this case use `--advanced 2` instead.

**Comment by jackbayliss** [comment]
Cool. I will close this and use `--advanced 2` :)
