### ISSUE TITLE
raising exception causes seg fault

### ISSUE THREAD

**Issue by lennardwalter** [dashingsoft/pyarmor#686]
**Pyarmor version**: 7.3.1
**Python version**: 3.10.1
**Platform**: Linux 5.10.88-1-lts

**Problem**: 
Raising an exception in the obfuscated script causes a segmentation fault instead of the expected traceback. It is also not possible to catch the error from a script which imports the obfuscated one. This only happens when `--advanced 2` is set. 

**How to reproduce**:
`echo "raise Exception()" > test.py`
`pyarmor obfuscate test.py --exact --enable-suffix --advanced 2`
`python dist/test.py`

**Comment by jondy** [comment]
Got it, thanks for your greet report, I have reproduced this issue, and fixing it.

**Comment by lennardwalter** [comment]
Hey @jondy. No rush, but is this something which will be fixed soon? Just so I know if I have to search for some kind of solution in the meantime (this is quite annoying for my customers)

**Comment by jondy** [comment]
It may be fixed a week later, because I start my holiday.

And I think this issue is only related to python3.10, if possible, use other version like python3.8/3.8 which work fine.

**Comment by jondy** [comment]
Please verify it in the pre-release version v7.3.7
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-7.3.7.zip
