### ISSUE TITLE
Linux (windows too) py3.10 super mode causing segfault

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#687]
(just exits on windows 3.10)

```
Python 3.10.2 (main, Jan 29 2022, 20:02:00) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import helheim
Segmentation fault
```

same build same options.. works fine in 3.9, 3.8, 3.7

```
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import helheim
>>>
```

**Comment by jondy** [comment]
Maybe same reason as #686, I'll fix this when my holiday is over about a week later.

**Comment by jondy** [comment]
Please verify it in the pre-release version v7.3.7
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-7.3.7.zip

**Comment by VeNoMouS** [comment]
Ah sorry didn't see this, will test in the next day or so and let you know the outcome

**Comment by VeNoMouS** [comment]
Can confirm, this appears to work without segfaulting... at least under linux

I will test under windows and let you know

**Comment by VeNoMouS** [comment]
@jondy can confirm working on windows as well with py 3.10.2

thank for your effort :) its appreciated

**Comment by jondy** [comment]
Great, thanks.
