### ISSUE TITLE
libpython3.9.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jackbayliss** [dashingsoft/pyarmor#689]
Using Windows 10: 

When doing the following : `pyarmor obfuscate  --advanced 2 --platform windows.x86_64 --platform linux.x86_64 --platform darwin.x86_64 --platform linux.armv7 --platform linux.armv6 Script.py`

It works fine in Windows, though when testing in Linux I get:
```
line 54, in import_names
    m = import(name, globals(), locals(), ['*'])
ImportError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by VeNoMouS** [comment]
install on your system libpython3.9

**Comment by VeNoMouS** [comment]
On your linux box, install `libpython3.9`

**Comment by jackbayliss** [comment]
@VeNoMouS  I believe this worked, thanks 👍🏻
