### ISSUE TITLE
SystemError: unknown opcode

### ISSUE THREAD

**Issue by xennygrimmato** [dashingsoft/pyarmor#69]
I am getting this error `SystemError: unknown opcode` for opcode 122 while running a obfuscated file. I am running Python 2.7.15.

Any workaround for this?

I am using Pyarmor version 3.2.3

**Comment by jondy** [comment]
How about upgrading to latest version 5.2.9?

**Comment by xennygrimmato** [comment]
How do I ensure that my current setup won't break on upgrading? I use `--src` option in the script to obfuscate but it seems it has been deprecated. What is the alternative for it?

**Comment by jondy** [comment]
First upgrade capsule:
```
# From v4.42, the default capsule locates in the user home other than the source path of pyarmor
cp /path/to/installed/pyarmor/.pyarmor_capsule.zip ~/
pyarmor capsule --upgrade
```
Then obfuscate scripts like this:
```
pyarmor obfuscate --output dist /path/to/src/entry.py
```
`/path/to/src` is the value of `--src` in the old version, `entry.py` is the old value of `--entry` in the old version.

About more information of `obfuscate`, refer to 
https://pyarmor.readthedocs.io/en/latest/man.html#obfuscate

**Comment by xennygrimmato** [comment]
I am using the following commands currently:
```
$PYARMOR init --src=$SOURCE --entry=${ENTRY_SCRIPT} $PROJECT || exit 1
```
for a project
and
```
$PYARMOR init --src=$SOURCE --type=pkg --entry=${ENTRY_SCRIPT} $PROJECT || exit 1
```
for a python package.
`$PYARMOR build` is called after that.
On upgrading to 5.2.9, when I run `pyarmor init -h`, I see that `--src` and `--entry` are still available for the `init` option. Are they deprecated only for the `obfuscate` option?

**Comment by jondy** [comment]
Yes, `--init` and `--entry` are only deprecated for command `obfuscate`.

However for project, you need remove old project file `.pyarmor_config` in the project path and create new project again.

**Comment by xennygrimmato** [comment]
Thanks for your help, I was able to make the required changes.

**Comment by rgarofalo** [comment]
same problem with last version

**Comment by jondy** [comment]
Python Version used to obfuscate scripts should be same as the Python Version used to run obfuscated scripts.
The bytecode are changed totally from Python 3.6, so if you obfuscate the scripts by python3.5 or before, it couldn't run by python3.6 or later.

**Comment by LittleDoggy** [comment]
Just now, I have met the same error in Maya , but after I restarted my computer ,  the error has gone , it`s a little wierd .

**Comment by jondy** [comment]
Generally the different python version results in this issue.

**Comment by vamshikrishnaakula** [comment]
hello all-am facing a problem with this system error: unknown opcode while tried load the Keras model, please help me out anyone thankyou 

here both python version build and load ==python 3.6
Tenserflow & Keras =2.6

**Comment by acz-a** [comment]
@vamshikrishnaakula  - i had the same problem, when i compiled the source code with the same version i was trying to run it the problem solved. (ie compile with 3.8 and run with 3.8)

**Comment by juliensalinas** [comment]
Thanks @acz-a  that helped me solve my problem

**Comment by KomarovAlea** [comment]
> pyarmor capsule --upgrade

I run this command, but got:
```
usage: pyarmor [-h] [-v] [-q] [-d] [--home HOME] [--boot BOOT]  ...
pyarmor: error: unrecognized arguments: --upgrade
```
