### ISSUE TITLE
typo in new 7.3.5 release - unable to activate PyArmor

### ISSUE THREAD

**Issue by fergusmclellan** [dashingsoft/pyarmor#690]
We have been running a build pipeline with no issues until today. When running our pipeline, we are now seeing the following error

INFO     PyArmor Trial Version 7.3.5
INFO     Python 3.7.9
INFO     Read registration code file: D:\a\_temp\pyarmor-keycode-1876.txt
INFO     Start to activate this code
INFO     Got keyfile of this code, this code is activated
ERROR    'Namespace' object has no attribute 'upgrage'

Looking at the source code, I believe that there is a typo in the src/pyarmor.py file, on line 867 
`register_keyfile(filename, args.upgrage, legency=args.legency)`

This should read
`register_keyfile(filename, args.upgrade, legency=args.legency)`

The error was not seen in previous versions of PyArmor (< 7.3.4).

**Comment by jondy** [comment]
Thanks, fixed it in v7.3.6
