### ISSUE TITLE
aarch64 support with musl libc for pytranform

### ISSUE THREAD

**Issue by ismhong** [dashingsoft/pyarmor#694]
**Is your feature request related to a problem? Please describe.**
Hi, thank you all making such great project. :)
Currently, I use pyarmor with alpine rootfs (busybox+musl libc) on armv8l platform (cortex-a55), it seems pyarmor lack musl.aarch64 runtime support for pytransform.

https://pyarmor.readthedocs.io/en/latest/platforms.html
- musl.x86_64
- musl.arm
- musl.mips32

**Describe the solution you'd like**
Is it possible to add new platform support "musl.aarch64" for pytransform? Thank you.

If request for new platform, first check all the supported platforms by `pyarmor download`. If it's really not in the list, run the following script in this platform and provide the output by text not snapshot image

Unfortunately, it seems the libc_ver() of python on my alpine 3.15 arm64v8 rootfs is not shown correctly.
```python
python version.py
system name: Linux
machine: armv8l
processor:
aliased terse platform: Linux-5.4.80-geec5f34899c0-armv8l-with
Traceback (most recent call last):
  File "version.py", line 8, in <module>
    print('libc: %s' % libc_ver())
TypeError: not all arguments converted during string formatting
```
Thanks for help.

**Comment by jondy** [comment]
There is no musl.aarch64 at this time. It may be built in next month.

**Comment by ismhong** [comment]
Hi @jondy 
Verified with PyArmor Version 7.4.0 on alpine@aarch64 platform, everything works fine.
Thanks for your help. :)

**Comment by LisaGotzian** [comment]
Dear @ismhong, could you briefly share the command you used? It would help me a lot.

Inside my docker container, I use
```
RUN pip install pyarmor==7.4.0
RUN pyarmor register /app/pyarmor-regcode-xxx.txt

RUN PYARMOR_PLATFORM=musl.aarch64 pyarmor obfuscate --recursive --advanced 2 /app/main.py
```

I currently get `/lib64/libc.so: invalid ELF header` with all combinations of `pyarmor 7.4.0` / `pyarmor 7.4.1` and `python 3.8.10` / `python 3.9.12`. I was somehow sure this has to do with the libraries for aarch64 still in development.

**Comment by ismhong** [comment]
Hi @LisaGotzian 
Here is how I use musl.aarch64 runtime to obfuscate my python file.
```
pyarmor obfuscate --platform musl.aarch64 <your python files>
```
For more information for obfuscate python script for cross platform, you can reference https://pyarmor.readthedocs.io/en/latest/man.html#obfuscate.

In the meantime, you also need to download or deploy pytransform dynamic library for your target platform.
You can use download(https://pyarmor.readthedocs.io/en/latest/man.html#download) or just copy the the runtime library located in `<obfuscated folder>/dist/pytransform` to path `/usr/lib/<python version>/site-packages/` in your container image manually.

**Comment by LisaGotzian** [comment]
Hi @ all who might be reading this, 
thank you for your well-written comments @ismhong.

To share with anyone facing similar problems, I would like to share what the problem was on our end: I ended up needing to link to the latest libc installation in the obfuscation stage because we were building on very "sparse" stages as per system requirements.

`RUN ln -s /usr/lib64/libc-2.28.so /usr/lib/libc.so`
