### ISSUE TITLE
Bought a license and registered it but still getting "PyArmor Trial"

### ISSUE THREAD

**Issue by bashar-ait** [dashingsoft/pyarmor#695]
Like the title says

I bought a license and registered it 

INFO     PyArmor Version 6.4.3
INFO     Start to register keyfile: pyarmor-regfile-XXXXX.zip
INFO     Save registration data to: /home/XXXXXX/.pyarmor
INFO     Extracting license.lic
INFO     Extracting .pyarmor_capsule.zip
INFO     This keyfile has been registered successfully.
INFO     Run "pyarmor register" to check registration information.

but when i run any obfuscation script it says "PyArmor Trial Version 6.4.3"

EDIT: I forgot to mention i have multiple python3 versions installed and each has pyarmor installed in

**Comment by bashar-ait** [comment]
> Please check the change log, make sure the license is not expired. Then try to upgrade the latest version.

i just updated pyarmor to 7.3 on all my python3 versions and i still get that "trial version" when i ran pyarmor obfuscate

**Comment by jondy** [comment]
The latest version is v7.3.6

**Comment by bashar-ait** [comment]
> The latest version is v7.3.6

Fixed it by applying the license using sudo and the normal user
