### ISSUE TITLE
Do I benefit from using PyArmor + Nuitka?

### ISSUE THREAD

**Issue by lipowskm** [dashingsoft/pyarmor#697]
Hi, first of all sorry if this is the wrong place to ask.

Probably that is trivial, but still confusing to me. Do I get any additional layer of protection when using Nuitka? I am working on a piece of software right now which I plan to sell, but I don't know if I should even bother with Nuitka since the build process gets pretty complicated with both PyArmor and Nuitka.

**Comment by jondy** [comment]
lipowskm ***@***.***> writes:

> Hi, first of all sorry if this is the wrong place to ask.
>
> Probably that is trivial, but still confusing to me. Do I get any additional
> layer of protection when using Nuitka? I am working on a piece of software
> right now which I plan to sell, but I don't know if I should even bother with
> Nuitka since the build process gets pretty complicated with both PyArmor and
> Nuitka.
>

Nuitka only protect a simple function call in the pyarmor obfuscted scripts, i think it's only a little help.

My suggestion is use pyarmor super plus mode "--advanced 5" if possible, because it's only supported by a few platforms.
