### ISSUE TITLE
pyarmor.helper.merge can't merge obfuscated folders in different python versions for multiple platforms

### ISSUE THREAD

**Issue by jdominguezg89** [dashingsoft/pyarmor#699]
Hi @jondy, in this time I am facing a problem similar to the one raised in this question: [pyarmor.helper.merge #573](https://github.com/dashingsoft/pyarmor/issues/573). The thing is that it is not clear to me what was the solution for the inconvenience raised in that post. 

In any case, I will explain to you what I need to do so that you can help me with a possible solution.

I am trying to obfuscate my code on a Mac M1 with an arm64 processor. The code must work for various versions of python and for multiple platforms and I am doing it in the following way.

### Obfuscating

I created a virtual python environment for versions 3.8, 3.9 and 3.10 which run on the `arm64` platform. Then I ran the following scripts:

#### Virtual env 3.8
```command line
pyarmor -d obfuscate --platform darwin.aarch64,darwin.x86_64,ios.aarch64,linux.aarch32,linux.aarch64,linux.armv6,linux.armv7,linux.x86,linux.x86_64,musl.x86_64,windows.x86,windows.x86_64 --no-cross-protection --recursive -O ./obfuscated_env38 ./myproject/module/__init__.py
```

#### Virtual env 3.9
```command line
pyarmor -d obfuscate --platform darwin.aarch64,darwin.x86_64,ios.aarch64,linux.aarch32,linux.aarch64,linux.armv6,linux.armv7,linux.x86,linux.x86_64,musl.x86_64,windows.x86,windows.x86_64 --no-cross-protection --recursive -O ./obfuscated_env39 ./myproject/module/__init__.py
```

#### Virtual env 3.10
```command line
pyarmor -d obfuscate --platform darwin.aarch64,darwin.x86_64,ios.aarch64,linux.aarch32,linux.aarch64,linux.armv6,linux.armv7,linux.x86,linux.x86_64,musl.x86_64,windows.x86,windows.x86_64 --no-cross-protection --recursive -O ./obfuscated_env310 ./myproject/module/__init__.py
```
> Note: the pyarmor runtime file that the obfuscation process copied for x86_64 platforms was the one that is located in the folder `.../0/_pytransform.dylib`

Then I created two Python virtual environments in Anaconda, emulating on the x86_64 architecture, one for python 3.6 and one for 3.7. And then I ran the following commands:

#### Virtual env 3.6
```command line
pyarmor -d obfuscate --platform darwin.aarch64,darwin.x86_64,ios.aarch64,linux.aarch32,linux.aarch64,linux.armv6,linux.armv7,linux.x86,linux.x86_64,musl.x86_64,windows.x86,windows.x86_64 --no-cross-protection --recursive -O ./obfuscated_env36 ./myproject/module/__init__.py
```

#### Virtual env 3.7
```command line
pyarmor -d obfuscate --platform darwin.aarch64,darwin.x86_64,ios.aarch64,linux.aarch32,linux.aarch64,linux.armv6,linux.armv7,linux.x86,linux.x86_64,musl.x86_64,windows.x86,windows.x86_64 --no-cross-protection --recursive -O ./obfuscated_env37 ./myproject/module/__init__.py
```

> Note: In this case, the pyarmor runtime file that the obfuscation process copied for x86_64 platforms was the one that is located in the folder `.../7/_pytransform.dylib`

### Merging

To merge the folders I am running the following command:

```commandline
python -m pyarmor.helper.merge -d -O ./merged_files ./obfuscated_env36/ ./obfuscated_env37/ ./obfuscated_env38/ ./obfuscated_env39/ ./obfuscated_env310/
```

### Executing the package

After that, when i try to run the package in python 3.8, 3.9 and 3.10 over both platforms `arm64` and `x86_64` everything works well, but when i run the package in python 3.6 and 3.7 over the `x86_64` platform i get this error: `RuntimeError: Marshal loads failed`.

I already have the latest runtime files, read the documentation several times, and tried every possible solution that has come to mi mind, but nothing solve this requirement.

Please help me with a possible solution for this, thank you in advance!

**Comment by jondy** [comment]
Some platforms has only feature 0, it can't mixed with other platforms which may use feature > 0.

Please check the documentation in the support platform to understand what's the features of core libraries.

And also read the advanced usage about cross platform obfuscating.

**Comment by jdominguezg89** [comment]
Hi @jondy, for everyone's benefit, I was able to achieve this by adding `.0` to the end of all platforms for python versions 3.6 and 3.7, the code looks like this:

### Virtual envs 3.6 y 3.7
```commandline
pyarmor -d obfuscate --platform darwin.aarch64.0,darwin.x86_64.0,ios.aarch64.0,linux.aarch32.0,linux.aarch64.0,linux.armv6.0,linux.armv7.0,linux.x86.0,linux.x86_64.0,musl.x86_64.0,windows.x86.0,windows.x86_64.0 --no-cross-protection --recursive -O ./obfuscated_env[36|37] ./myproject/module/__init__.py
```commandline
