### ISSUE TITLE
ERROR    'return' outside function (<frozen pytransform>, line 271)

### ISSUE THREAD

**Issue by squirr3l-ex** [dashingsoft/pyarmor#70]
```
C:\Users\Jon\Desktop\test> pyarmor obfuscate cunt.py
INFO     PyArmor Trial Version 5.2.9

INFO     Source path is "C:\Users\Jon\Desktop\test"
INFO     Entry script is cunt.py
INFO     Use cached capsule C:\Users\Jon\.pyarmor_capsule.zip
INFO     Normal mode is on
INFO     Save obfuscated scripts to "dist"
INFO     Read public key from capsule
INFO     Obfuscate scripts with default mode
INFO            test.py -> dist\test.py
INFO            pytransform.py -> dist\pytransform.py
ERROR    'return' outside function (<frozen pytransform>, line 271)
```

**Comment by jondy** [comment]
Do not obfuscate `pytransform.py`

**Comment by JKKSI** [comment]
C:\Users\Daishinkan\Downloads\pyarmor examples>pyarmor obfuscate Magic_Gen.py
INFO     PyArmor Version 6.6.0
INFO     Target platforms: Native
INFO     Source path is "C:\Users\Daishinkan\Downloads\pyarmor examples"
INFO     Entry scripts are ['Magic_Gen.py']
INFO     Use cached capsule C:\Users\Daishinkan\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying c:\python27\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Patch library dist\pytransform\_pytransform.dll
INFO     Patch library file OK
INFO     Copying c:\python27\lib\site-packages\pyarmor\pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            Magic_Gen.py -> dist\Magic_Gen.py
ERROR    invalid syntax (<frozen Magic_Gen>, line 9)

i get this same error with all my other scripts, simillar error, how i can solve this?, i buy pyarmor already.
