### ISSUE TITLE
动态库下载

### ISSUE THREAD

**Issue by halicloud** [dashingsoft/pyarmor#702]
https://pyarmor.dashingsoft.com/files/r47.1/index.json

这个链接需要用户名和密码，我们已经购买过license ，但是用户名密码是什么？

**Comment by halicloud** [comment]
付费版本怎么下载动态库？

**Comment by jondy** [comment]
使用 `pyarmor download` 下载

**Comment by halicloud** [comment]
内网离线服务器怎么办，网络有限制没法download

**Comment by jondy** [comment]
halicloud ***@***.***> writes:

> 内网离线服务器怎么办，网络有限制没法download
>

请参考文档中支持的平台中的说明
