### ISSUE TITLE
--disable-restrict-mode on license means we can't use different restrict modes anymore when obfuscating files?

### ISSUE THREAD

**Issue by saidelike** [dashingsoft/pyarmor#707]
It used to be possible with old pyarmor like 6.5.2 to generate a license and then use that license for both the entry script and all the other files, and still using different restrict modes for the entry script and the other files.

generate a license:

```
pyarmor licenses
```

so for the entry script, according to https://pyarmor.readthedocs.io/en/latest/advanced.html#work-with-nuitka:

```
pyarmor obfuscate --with-license license.lic --restrict 0 --no-cross-protection --exact entry.py
```

and the other files:

```
pyarmor obfuscate --with-license license.lic --restrict 5 --exclude entry.py --recursive entry.py
```

With latest pyarmor 7.3.6, when we run the first one to obfuscate the entry script, we get:

```
ERROR    Option "--restrict 0" is conflicted with outer license, do not use this option but generate the outer license with option "--disable-restrict-mode"
```

If we set `--disable-restrict-mode` on the license and remove `--restrict 0` from the first obfuscation (entry script), it obfuscates without errors and we can run the obfuscated `entry.py`. 

```
pyarmor licenses --disable-restrict-mode
pyarmor obfuscate --with-license license.lic --no-cross-protection --exact entry.py
pyarmor obfuscate --with-license license.lic --restrict 5 --exclude entry.py --recursive entry.py
```

However then the `--disable-restrict-mode` is enforced for the other files (in the 2nd obfuscation command, the `--restrict 5` is ignored right?) too which we don't necessarily want?

If instead we use 2 licenses, then it obfuscates fine but then fails to execute:

```
# generate license1.lic
pyarmor licenses --disable-restrict-mode
pyarmor obfuscate --with-license license1.lic --no-cross-protection --exact entry.py
# generate license2.lic
pyarmor licenses
pyarmor obfuscate --with-license license2.lic --restrict 5 --exclude entry.py --recursive entry.py
```

Execution of obfuscated `entry.py` gives the following error:

```
RuntimeError: Check restrict mode of module failed
```

What's the right way for doing what I want with latest pyarmor?

**Comment by saidelike** [comment]
I've updated the above with more details

**Comment by jondy** [comment]
> --disable-restrict-mode on license means we can't use different restrict modes anymore when obfuscating files

Yes.
