### ISSUE TITLE
EXE file stops right after start

### ISSUE THREAD

**Issue by Thyman01** [dashingsoft/pyarmor#708]
After compiling my files into an exe and starting it, it stops without error...
Only after compiling it gets broken. The raw python code works perfectly.
the command I'm running is: `pyarmor pack -e " --onefile --icon "logo.ico" -F" --name Alpha main.py`

I don't know how to fix it because there is no error message.

Any help will be highly appreciated.

**Comment by Thyman01** [comment]
I looked into it a bit more and apparently it crashes on import of this module https://pypi.org/project/anchorpy/

It doesn't print any errors so I'm not sure what the problem is. Anyway you could look into it?

**Comment by jondy** [comment]
There are common solutions in the online documentation about pack problem.

And read the related links in this section, especially the differences of the obfuscated scritps.
