### ISSUE TITLE
Regarding passing arguments to pyinstaller when using pack cmd

### ISSUE THREAD

**Issue by ohk2kt3t4** [dashingsoft/pyarmor#71]
Right now there does not seem to be a way to pass arguments to pyinstaller when using the `pack` command.

In my case I wanted to pass the `--onefile` and `icon=...` args, so I resorted to modifying the pyarmor code ([options list](https://github.com/dashingsoft/pyarmor/blob/15aa2ec9bad72e7fadd81c8e23cf4800cf75d3f7/src/packer.py#L212) in `run_pyi_makespec`) and hard-coding in the above arguments.

Questions:
1) Am I missing another way to achieve this?
2) Would a PR that allows arguments to be passed through to pyinstaller when using pack be welcome?
   (or maybe a command that saves the patches spec file so one can use it manually with pyinstaller later?)

**Comment by jondy** [comment]
There is an un-document option `--options`` which could achieve this:
```
pyarmor pack --options '--onefile xxx --icon xxx` foo.py
```
By this option, any extra options could be passed to `PyInstaller`

PR is welcome, :)

**Comment by ohk2kt3t4** [comment]
Cheers that worked! If only I had seen that [line](https://github.com/dashingsoft/pyarmor/blob/15aa2ec9bad72e7fadd81c8e23cf4800cf75d3f7/src/packer.py#L288) yesterday...
