### ISSUE TITLE
Is it possible to generate an .exe from a linux machine?

### ISSUE THREAD

**Issue by jppdpf** [dashingsoft/pyarmor#710]
My purpose is to build one windows OS executable file, while using a Linux machine.

I have been testing the Pyarmor on a Ubuntu 20.04. 

I downloaded the platform files.
**pyarmor download windows.x86_64**

One of the commands I have been testing is the following.
**pyarmor pack my-script.py -x " --platform windows.x86_64" -e " --onefile"**

I had the impression that by running this, my-script would be bundled into a single executable file runnable on the windows OSs, but no .exe was generated.

Is it possible to generate an windows OS executable while running the pyarmor on a Linux? Is there any way?

I'm sorry, for perhaps a very newbie question.
Thanks in advance, really appreciate it.

**Comment by jondy** [comment]
No. Not support.

**Comment by jppdpf** [comment]
Thank you for the reply. 👍
