### ISSUE TITLE
How to include pyarmor in nuitka

### ISSUE THREAD

**Issue by SadLandscape** [dashingsoft/pyarmor#711]
Let's say we have 2 files: 
mainfile.py
```
from modulefile import x
x()
```
modulefile.py
```
def x():
    print("Working!")
```
how can I obfuscate these two files and include it in nuitka as a onefile executable?

I tried it once but it told things like name '__pyarmor__' is not defined or no module named modulefile

**Comment by jondy** [comment]
pyarmor is well documentation, please first read the documentation.

**Comment by SadLandscape** [comment]
> 

I tried doing this (https://pyarmor.readthedocs.io/en/latest/advanced.html#work-with-nuitka) but it looks like it's for older nuitka versions, and I didn't fully understand that
