### ISSUE TITLE
Only one path is allowed

### ISSUE THREAD

**Issue by nevoine** [dashingsoft/pyarmor#713]
I use Python 3.8 on windows10

Base script `obfuscate-app.bat` is not working, returns error
```
INFO     PyArmor Version 7.4.0
INFO     Python 3.8.2
INFO     Target platforms: Native
ERROR    Only one path is allowed
```

I've researched that the problem is with that line
```
  SET WITH_LICENSE="--with-license licenses\%LICENSE_CODE%\license.lic"
```

Changing it to 
```
  SET WITH_LICENSE= --with-license licenses\%LICENSE_CODE%\license.lic
```
solved the proble, and the example works properly.

**Comment by nevoine** [comment]
I see the same but and solution in this file: `https://github.com/dashingsoft/pyarmor/blob/master/src/examples/obfuscate-pkg.bat`

This line:
`  SET WITH_LICENSE="--with-license licenses\%LICENSE_CODE%\license.lic`

should be changed to
`  SET WITH_LICENSE=--with-license licenses\%LICENSE_CODE%\license.lic
`

**Comment by jondy** [comment]
Thank you very much, this patch has been applied, aa8a4bfc2027fdd1eb9f554559ab6385bb818ad0

**Comment by nevoine** [comment]
Thanks for the quick patch!

I'm having another core issue (solving it second day): 
My `script.py` use `\external directory` with modules. Pyinstaller creates successfully `.exe` using the command 
`pyinstaller --onefile -p "\external_directory" script.py`

but pyarmor can't create .exe, fails after the command 
`pyarmor pack -e " --onefile -p \external_directory" script.py`

Pyarmor fails with error:
```
Traceback (most recent call last):
  File "s:\python3.8\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "s:\python3.8\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "s:\python3.8\lib\site-packages\PyInstaller\__main__.py", line 124, in <module>
    run()
  File "s:\python3.8\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "s:\python3.8\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "s:\python3.8\lib\site-packages\PyInstaller\building\build_main.py", line 725, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "s:\python3.8\lib\site-packages\PyInstaller\building\build_main.py", line 672, in build
    exec(code, spec_namespace)
  File "no_war-patched.spec", line 29, in <module>
    raise RuntimeError('No obfuscated script found')
RuntimeError: No obfuscated script found
ERROR    Run command failed
```

That's why I've decided to go through all examples\tutorials to understand how pyarmor is working.

Have no idea why, still exploring the issue. 
Later I'll create simple example to demonstrate that.
