### ISSUE TITLE
pyarmor simplest pack not working

### ISSUE THREAD

**Issue by nevoine** [dashingsoft/pyarmor#714]
Using windows10, python3.8

I try to make .exe from the simplest `examples\simple\queens.py` file

Pyinstaller creates it successfully with the command
`pyinstaller --onefile queens.py`

But the same command for pyarmor
`pyarmor pack -e" --onefile " queens.py`

**fails** with `raise RuntimeError('No obfuscated script found')`. 
See the full log in the attached [fail_log.txt](https://github.com/dashingsoft/pyarmor/files/8227231/fail_log.txt)

**Comment by nevoine** [comment]
And for example, obfuscate + pyinstaller works successfully:
```
pyarmor.exe obfuscate --advanced 2 --recursive queens.py
pyinstaller.exe --onefile --name queens_obfuscated.exe dist\queens.py
```

**Comment by jondy** [comment]
I don't think pyarmor doesn't work to pack a simple script. If it really doesn't work, please try to use repack method in the advanced usage of documentation.

**Comment by nevoine** [comment]
I did not find repack method here https://pyarmor.readthedocs.io/en/latest/usage.html - what do you mean?
By the way, I've emailed you at jondyo...@gmail.com about the license z...ka@gmail.com. Can you please answer me?

**Comment by jondy** [comment]
Here it's the link about repack method, try to use this way
https://pyarmor.readthedocs.io/en/latest/advanced.html#repack-pyinstaller-bundle-with-obfuscated-scripts

Also check this link
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

Just think the obfuscated scripts as normal python scripts with extra extension, then use repack method.

And for the high security, use spp mode as far as possible
https://pyarmor.readthedocs.io/en/latest/mode.html#super-plus-mode

**Comment by jondy** [comment]
In advanced usage search repack, not usage.

And email now doesn't support any technical issue, it only handles security issue.
