### ISSUE TITLE
How to include the modules from other directories than app?

### ISSUE THREAD

**Issue by nevoine** [dashingsoft/pyarmor#715]
Suppose my script `main_external.py` use the module from your `examples\testpkg` at `s:\python3.8\Lib\site-packages\pyarmor\examples\testpkg`

main_external.py:
```
# encoding: utf-8
from mypkg import title
from mypkg.foo import hello

hello(title)

x = str(input('Your name: '))
```

I can create exe using pyinstaller easily with
`pyinstaller.exe --onefile -p "s:\python3.8\Lib\site-packages\pyarmor\examples\testpkg" --name main_external.exe main_external.py`

But how to create such .exe protected with pyarmor?
Command `pyarmor pack -e" --onefile -p s:\\python3.8\\Lib\\site-packages\\pyarmor\\examples\\testpkg" main_external.py`
fails with `    raise RuntimeError('No obfuscated script found')`.

**Comment by jondy** [comment]
Try to use project to obfuscated scripts.
