### ISSUE TITLE
Is there any difference in obfuscation between trial version and license registration?

### ISSUE THREAD

**Issue by JangKyumin** [dashingsoft/pyarmor#716]
Hello :)

I am using pyarmor 6.8.1 version. 

After obfuscation in the TRIAL version, the service starts normally when applied to uwsgi, but if you register a license and proceed with obfuscation, the uwsgi service will not start normally.

The same is true if you delete the licensed pyarmor directory and re-register the license as described in the guide.

Is there a part that needs to be set differently from the trial version when registering a license?

For your information, no additional error message is captured in the log.

**Comment by jondy** [comment]
I think there should be some old files are used. The normal version uses the same way as trial version.

**Comment by JangKyumin** [comment]
> I think there should be some old files are used. The normal version uses the same way as trial version.

I didn't understand what it meant to say that old files should be used.

I bought a license and made it obfuscated, but it doesn't apply even though it's the same way as the trial version, so I can't figure out how to solve it. :(

**Comment by jondy** [comment]
Do you check the common solution in the documentation? I have documented it.

By the way, if possible, try the registerred version in a clean machine, check the log, it will print which files are generated.

**Comment by JangKyumin** [comment]
> Do you check the common solution in the documentation? I have documented it. By the way, if possible, try the registerred version in a clean machine, check the log, it will print which files are generated.

I am conducting a test by checking the official documents. 

I will apply it more and contact you again if I get a specific error message.

**Comment by JangKyumin** [comment]
When I registered the license in python 3.5 and made it obfuscated, the uwsgi did not start normally.

I changed it to python 3.8 version for testing, registered license, and made it obfuscated, and it worked properly in uwsgi.

Is it a problem if I proceed the python version to 3.5 version for obfuscation?

**Comment by JangKyumin** [comment]
@jondy 

I tried to obfuscate and test the python 3.5 version, but it didn't work, so I took a point and checked the log.

I saw the source of the file `__init__` that exists in `pytransform`.

```
@dllmethod
def init_runtime():
    prototype = PYFUNCTYPE(c_int, c_int, c_int, c_int, c_int)
    _init_runtime = prototype(('init_runtime', _pytransform))
    return _init_runtime(0, 0, 0, 0)
```

Is there any problem with the function without the partial return?
I don't know what kind of problem is happening in dll, so I can't find a solution.

**Comment by jondy** [comment]
kmjang ***@***.***> writes:

> @jondy
>
> I tried to obfuscate and test the python 3.5 version, but it didn't work, so
> I took a point and checked the log.
>
> I saw the source of the file __init__ that exists in pytransform.
>
> @dllmethod
> def init_runtime():
>     prototype = PYFUNCTYPE(c_int, c_int, c_int, c_int, c_int)
>     _init_runtime = prototype(('init_runtime', _pytransform))
>     return _init_runtime(0, 0, 0, 0)
>
> Is there any problem with the function without the partial return?
> I don't know what kind of problem is happening in dll, so I can't find a
> solution.
>

To verify pyarmor works or not by doing a simple test, just obfuscate a hellowork script and run it by Python 3.5. If it works, it should not pyarmor's problem.

**Comment by JangKyumin** [comment]
> kmjang ***@***.***> writes:
> @jondy I tried to obfuscate and test the python 3.5 version, but it didn't work, so I took a point and checked the log. I saw the source of the file __init__ that exists in pytransform. @dllmethod def init_runtime(): prototype = PYFUNCTYPE(c_int, c_int, c_int, c_int, c_int) _init_runtime = prototype(('init_runtime', _pytransform)) return _init_runtime(0, 0, 0, 0) Is there any problem with the function without the partial return? I don't know what kind of problem is happening in dll, so I can't find a solution.
> To verify pyarmor works or not by doing a simple test, just obfuscate a hellowork script and run it by Python 3.5. If it works, it should not pyarmor's problem.

Simply obfuscate a script such as `print("Hello Word")` and it runs well.

However, the problem is that I tested it with a project created with the `django-admin start project mysite` command supported by Django, and python 3.8 is normal and 3.5 is abnormal in uwsgi.

So this part is uwsgi problem regardless of pyarmor?

**Comment by jondy** [comment]
kmjang ***@***.***> writes:

>  kmjang @.***> writes:
>  @jondy I tried to obfuscate and test the python 3.5 version, but it
>  didn't work, so I took a point and checked the log. I saw the source of
>  the file init that exists in pytransform. @dllmethod def init_runtime():
>  prototype = PYFUNCTYPE(c_int, c_int, c_int, c_int, c_int) _init_runtime =
>  prototype(('init_runtime', _pytransform)) return _init_runtime(0, 0, 0,
>  0) Is there any problem with the function without the partial return? I
>  don't know what kind of problem is happening in dll, so I can't find a
>  solution.
>  To verify pyarmor works or not by doing a simple test, just obfuscate a
>  hellowork script and run it by Python 3.5. If it works, it should not
>  pyarmor's problem.
>
> Simply obfuscate a script such as print("Hello Word") and it runs well.
>
> However, the problem is that I tested it with a project created with the
> django-admin start project mysite command supported by Django, and python 3.8
> is normal and 3.5 is abnormal in uwsgi.
>
> So this part is uwsgi problem regardless of pyarmor?

Just as described in the documentation, if the third package doesn't use any feature changed by pyarmor, it should work with pyarmor. But I can't give any hint if there is no error log.

**Comment by JangKyumin** [comment]
> Just as described in the documentation, if the third package doesn't use any feature changed by pyarmor, it should work with pyarmor. But I can't give any hint if there is no error log.

I'm also frustrated with that part. 

I'm sure uwsgi is working and I read pytransform, but there's no error log for the problem.

Then, if there is no error log that can be a clue, I can't get help...

**Comment by jondy** [comment]
I think you need to learn how to debug uwgi application.

**Comment by JangKyumin** [comment]
> I think you need to learn how to debug uwgi application.

What I'm still concerned about is that in the tiral version, if you obfuscate the project, it will work fine with uwsgi. 

By the way, how do I understand that uwsgi doesn't work if I register my purchased license and obfuscate the same project?

If it doesn't work with uwsgi, I think it should not work with trial version, but I don't understand this part, so I have a question.

**Comment by jondy** [comment]
The trial version always uses core library r41.15 (with pyarmor 6.6.2), the purchased version uses the latest core library (now it's r49.3).

Try to install pyarmor 6.6.2 which uses core library r41.15, it should be same as the trial version.

**Comment by JangKyumin** [comment]
The 6.6.2 version you mentioned is unavailable due to the problem with the cywin patch that I previously requested (6.8.1 patch).

`Platform cygwin_nt-10.0 not supported`

Link to question: https://github.com/dashingsoft/pyarmor/issues/584

**Comment by JangKyumin** [comment]
> The trial version always uses core library r41.15 (with pyarmor 6.6.2), the purchased version uses the latest core library (now it's r49.3). Try to install pyarmor 6.6.2 which uses core library r41.15, it should be same as the trial version.

The 6.6.2 version you mentioned is unavailable due to the problem with the cygwin patch that I previously requested (6.8.1 patch).

`Platform cygwin_nt-10.0 not supported`

Link to question: https://github.com/dashingsoft/pyarmor/issues/584

**Comment by LucasGitDev** [comment]
@JangKyumin are you using Apache or something similar? I'm getting the same error: No error log about WSGI but the service http isnt starting. Before, I had used the TRIAL version by a long time and never get errors, in the last days I needed to upgrade my TRIAL version to Licensed Version and then, my project cant run in Apache.

**Comment by JangKyumin** [comment]
> @JangKyumin are you using Apache or something similar? I'm getting the same error: No error log about WSGI but the service http isnt starting. Before, I had used the TRIAL version by a long time and never get errors, in the last days I needed to upgrade my TRIAL version to Licensed Version and then, my project cant run in Apache.

@LucasGitDev 

I use nginx and uwsgi in a cygwin environment.

When obfuscating to Trial version, it normally runs on uwsgi, but when I register and obfuscate the license I purchased, it does not run.

**Comment by LucasGitDev** [comment]
Did Nginx generate a log file? Apache does this, but the content is not useful.

**Comment by JangKyumin** [comment]
> Did Nginx generate a log file? Apache does this, but the content is not useful.

I have been building nginx and uwsgi logs, but I haven't seen any other error logs.

**Comment by LucasGitDev** [comment]
So... In my case, I use wsgi in Django with Python 3.7.2 and Apache24. I don't know why, but after using the purchased license, when I obfuscate my project, it doesn't work, it doesn't start. Maybe we have the same problem.

**Comment by JangKyumin** [comment]
> So... In my case, I use wsgi in Django with Python 3.7.2 and Apache24. I don't know why, but after using the purchased license, when I obfuscate my project, it doesn't work, it doesn't start. Maybe we have the same problem.

Considering that the phenomenon is similar, I think it is highly likely. What version of pyarmor do you use?

**Comment by jondy** [comment]
Here are common debug ways, not related to pyarmor only
1. obfuscate a very simple wsgi script, run it by python interpreter directly
2. if there is no exception, run it in the wsgi framework
3. if possible, add some print statement in this script to check the script is executed or not

**Comment by JangKyumin** [comment]
First of all, my simple project is as follows.

```
├─obf_site
│  └─mysite
│      │  settings.py
│      │  urls.py
│      │  wsgi.py
│      │  __init__.py        
```

In the above structure, uwsgi reads and loads the wsgi file.

We conducted the test in the way you told us.

> 1. obfuscate a very simple wsgi script, run it by python interpreter directly 

As I mentioned in number 1, I made sure that there was no problem when I obfuscated the wsgi file and ran it immediately with python interpreter.

> 2. if there is no exception, run it in the wsgi framework 

However, when I read the wsgi file from uwsgi, the server did not go up normally.

> 3. if possible, add some print statement in this script to check the script is executed or not

I also printed the wsgi script and tested it, but it was not printed because the process was not uploaded in uwsgi.

**Comment by LucasGitDev** [comment]
> Considering that the phenomenon is similar, I think it is highly likely. What version of pyarmor do you use?

@JangKyumin  I'm using some, 6.6.2 and 7.4.1 mostly

**Comment by LucasGitDev** [comment]
> 1. obfuscate a very simple wsgi script, run it by python interpreter directly

This works well, I can run wsgi.py normally. Using print before the content (bootstrap and obfuscated code) works fine too, but after that, it returns `'Check bootstrap restrict mode failed'` as expected.

> 2. if there is no exception, run it in the wsgi framework

Running the project Django using Apache I only get this log:

> [wsgi:info] [pid 15320:tid 580] mod_wsgi (pid=15320): Python home C:\\Path\\to\\python.
> [wsgi:info] [pid 15320:tid 580] mod_wsgi (pid=15320): Initializing Python.
> [wsgi:info] [pid 15320:tid 580] mod_wsgi (pid=15320): Attach interpreter ''.
> [wsgi:info] [pid 15320:tid 580] mod_wsgi (pid=15320): Imported 'mod_wsgi'.
> [wsgi:info] [pid 15320:tid 580] mod_wsgi (pid=15320, process='', application=''): Loading Python script file 'C:path\\to\\python\\Lib\\site-packages/backend/wsgi.py'.
> [mpm_winnt:crit] [pid 10744:tid 864] AH00419: master_main: create child process failed. Exiting.
> [core:info] [pid 10744:tid 864] AH00096: removed PID file C:path\\to\\python\\Apache24/logs/httpd.pid (pid=10744)

> 3. if possible, add some print statement in this script to check the script is executed or not

adding print before the content:

> [wsgi:info] [pid 15220:tid 584] mod_wsgi (pid=15220): Python home C:\\Path\\to\\python.
> [wsgi:info] [pid 15220:tid 584] mod_wsgi (pid=15220): Initializing Python.
> [wsgi:info] [pid 15220:tid 584] mod_wsgi (pid=15220): Attach interpreter ''.
> [wsgi:info] [pid 15220:tid 584] mod_wsgi (pid=15220): Imported 'mod_wsgi'.
> [wsgi:info] [pid 15220:tid 584] mod_wsgi (pid=15220, process='', application=''): Loading Python script file 'C:path\\to\\python\\Lib\\site-packages/backend/wsgi.py'.
> [wsgi:error] [pid 15220:tid 584] hello, here is a print\r
> [wsgi:error] [pid 15220:tid 584] Check bootstrap restrict mode failed\r
> [wsgi:error] [pid 15220:tid 584] mod_wsgi (pid=15220): SystemExit exception raised when doing exec of Python script file 'C:path\\to\\python\\Lib\\site-packages/backend/wsgi.py'.
> [mpm_winnt:notice] [pid 15220:tid 584] AH00354: Child: Starting 64 worker threads.
>

**Comment by jondy** [comment]
Lucas Teles de Souza ***@***.***> writes:

>  1 obfuscate a very simple wsgi script, run it by python interpreter
>  directly
>
> This works well, I can run wsgi.py normally. Using print before the content
> (bootstrap and obfuscated code) works fine too, but after that, it returns
> 'Check bootstrap restrict mode failed' as expected.
>
>  1 if there is no exception, run it in the wsgi framework
>
> Running the project Django using Apache I only get this log:
>
>  [wsgi:info] [pid 15320:tid 580] mod_wsgi (pid=15320): Python home
>  C:\Path\to\python.
>  [wsgi:info] [pid 15320:tid 580] mod_wsgi (pid=15320): Initializing
>  Python.
>  [wsgi:info] [pid 15320:tid 580] mod_wsgi (pid=15320): Attach interpreter
>  ''.
>  [wsgi:info] [pid 15320:tid 580] mod_wsgi (pid=15320): Imported
>  'mod_wsgi'.
>  [wsgi:info] [pid 15320:tid 580] mod_wsgi (pid=15320, process='',
>  application=''): Loading Python script file
>  'C:path\to\python\Lib\site-packages/backend/wsgi.py'.
>  [mpm_winnt:crit] [pid 10744:tid 864] AH00419: master_main: create child
>  process failed. Exiting.
>  [core:info] [pid 10744:tid 864] AH00096: removed PID file
>  C:path\to\python\Apache24/logs/httpd.pid (pid=10744)
>
>  1 if possible, add some print statement in this script to check the
>  script is executed or not
>
> adding print before the content:
>
>  [wsgi:info] [pid 15220:tid 584] mod_wsgi (pid=15220): Python home
>  C:\Path\to\python.
>  [wsgi:info] [pid 15220:tid 584] mod_wsgi (pid=15220): Initializing
>  Python.
>  [wsgi:info] [pid 15220:tid 584] mod_wsgi (pid=15220): Attach interpreter
>  ''.
>  [wsgi:info] [pid 15220:tid 584] mod_wsgi (pid=15220): Imported
>  'mod_wsgi'.
>  [wsgi:info] [pid 15220:tid 584] mod_wsgi (pid=15220, process='',
>  application=''): Loading Python script file
>  'C:path\to\python\Lib\site-packages/backend/wsgi.py'.
>  [wsgi:error] [pid 15220:tid 584] hello, here is a print\r
>  [wsgi:error] [pid 15220:tid 584] Check bootstrap restrict mode failed\r
>  [wsgi:error] [pid 15220:tid 584] mod_wsgi (pid=15220): SystemExit
>  exception raised when doing exec of Python script file
>  'C:path\to\python\Lib\site-packages/backend/wsgi.py'.
>  [mpm_winnt:notice] [pid 15220:tid 584] AH00354: Child: Starting 64 worker
>  threads.
>

For this case, try to obfuscate the scripts with `--restrict 0`

**Comment by JangKyumin** [comment]
> First of all, my simple project is as follows.
> 
> ```
> ├─obf_site
> │  └─mysite
> │      │  settings.py
> │      │  urls.py
> │      │  wsgi.py
> │      │  __init__.py        
> ```
> 
> In the above structure, uwsgi reads and loads the wsgi file.
> 
> We conducted the test in the way you told us.
> 
> > 1. obfuscate a very simple wsgi script, run it by python interpreter directly
> 
> I made sure that there was no problem when I obfuscated the wsgi file and ran it immediately with python interpreter.
> 
> > 2. if there is no exception, run it in the wsgi framework
> 
> However, when I read the wsgi file from uwsgi, the server did not go up normally.
> 
> > 3. if possible, add some print statement in this script to check the script is executed or not
> 
> I also printed the wsgi script and tested it, but it was not printed because the process was not uploaded in uwsgi.
> 
> By the way, is there any problem with the core library you mentioned above?
> 
> You recommended 6.6.1 version, but I can use it from 6.8.1 version when the cygwin environment issue is resolved.

@jondy 

I also want to know what the problem is.

**Comment by LucasGitDev** [comment]
The application that we are working on used to use pyarmor 5.5.3 trial version, and it was obfuscating all the files and after the obfuscation everything was working well. After some tests with different versions, we realized that any version after 5.5.3 (trial or paid) wasn’t  working, even when all the archives were obfuscated with these different versions, the application wasn’t working. It only works without obfuscation and with pyarmor 5.5.3 trial version obfuscation. The question that I have is: What changed after the 5.5.3 version that could possibly cause this problem?

**Comment by JangKyumin** [comment]
> The application that we are working on used to use pyarmor 5.5.3 trial version, and it was obfuscating all the files and after the obfuscation everything was working well. After some tests with different versions, we realized that any version after 5.5.3 (trial or paid) wasn’t working, even when all the archives were obfuscated with these different versions, the application wasn’t working. It only works without obfuscation and with pyarmor 5.5.3 trial version obfuscation. The question that I have is: What changed after the 5.5.3 version that could possibly cause this problem?

@LucasGitDev 

Does pyarmor 5.5.3 work normally even after registering the license you purchased?

I envy you if it works. I can only use it after the 6.8.1 version, so I haven't even tested it.

**Comment by LucasGitDev** [comment]
@JangKyumin  so...

Pyarmor worked for me in version 5.5.3 without using the paid license. The purchased license only works for versions above 6.6.2 (if I'm not wrong) according to the license manual.

My company's project has always run on Pyarmor 5.5.3 without the license, but for internal reasons it will need to be updated.

I need to switch to the paid license, so I need to make it work with Pyarmor on a version more current than 6.6.2

**Comment by JangKyumin** [comment]
@LucasGitDev 

I agree with what you said.

At the time of license application, I think it should be possible in the latest version rather than matching the old version.

I hope the problem is solved and applied to the product as soon as possible.

**Comment by LucasGitDev** [comment]
@jondy , have you studied our problem? None of your suggestions worked for us. I think the error is about Pyarmor, purely because without obfuscation we can run the project in Apache normally. If obfuscated after v6.6.2 the web service cannot start, whether or not we apply the paid license. So the problem is not about the trial version or the paid version.

**Comment by JangKyumin** [comment]
@jondy 
Are you looking for a solution?
I purchased the license after confirming that it works in the trial version.
I'm trying to apply it to the company's products, but it's a difficult situation
I believe you are trying to solve our problem.

**Comment by jondy** [comment]
kmjang ***@***.***> writes:

> @jondy
> Are you looking for a solution?
> I purchased the license after confirming that it works in the trial version.
> I'm trying to apply it to the company's products, but it's a difficult
> situation
> I believe you are trying to solve our problem.
>

I think this issue could be fixed by using the right pyarmor options.

The default option may only works for common cases, but for complex cases, please read the man page of pyarmor to understand usage of each option and find the right option.

Note that pyarmor provides a lot of options just for different cases, each option stands for a special function to handle different cases. The end user of pyarmor should learn each option of the pyarmor, tt's not my due to learn each user's case and tell them using which option.

**Comment by JangKyumin** [comment]
@jondy 

I didn't mean to ask you to study and solve the problem. I'm sorry if I offended you.

By the way, if it's a problem caused by my inexperience in using the option, why does the trial version and the license version work with the same option in Python 3.8 version?

I think you need to answer this. Why does python 3.8 work normally, but not in python 3.5.

Is the part that doesn't work according to the python version that the user has to learn and handle?

**Comment by jondy** [comment]
So obfuscating a simple hello world script by python 3.5 and python 3.8, run the obfuscated by python 3.5 and python3.8.

Does it work or not? If not, I'll check and fix it.

But if run the obfuscated scripts by the third party tool, for example, apache wsgi. I'll not install apache to verify and fix it.

If report this kind of bug, please providing more information, I have no idea only by this information: python3.8 works, but python3.5 not.

I would happy to help to fix this problem if there is more help information.

One hint, for wsgi application, `__inti__.py` should be as main script to be obfuscated.

**Comment by jondy** [comment]
One possible reason, if the python version used by apache wsgi is different from the python version to obfuscate the scripts,  the wsgi script will not work.

Also @LucasGitDev

**Comment by JangKyumin** [comment]
> The trial version always uses core library r41.15 (with pyarmor 6.6.2), the purchased version uses the latest core library (now it's r49.3). Try to install pyarmor 6.6.2 which uses core library r41.15, it should be same as the trial version.

@jondy 

Hello. 

I tested it because I remembered the part mentioned above recently.

I don't know if it's a python version problem or a core library problem, but when I conducted the test as below, the uwsgi was running normally.

1. Remove the pyarmor completely and install it in version 6.6.2.
2. Register license with register command.
3. Test project obfuscation progress.
4. Overwrite script __init__.py of pytransform changed by cygwin application issue.
5. Check normal after uwsgi is driven.

Lowering the core library version resolved the issue. 

Then, is the problem with the change from r41.15 to r49.3 when the version was raised?

I don't think it's a good idea to use the old version from the point of purchasing a license, including security issues.

What additional information should I provide for the latest version?

**Comment by jondy** [comment]
I don't support to debug the obfuscated scripts with any third party package.

There is no error log, I cann't support more as described in the EULA.

Besides, for "check bootstrap mode failed" issue, make sure you understand what's the restrict mode, and obfuscate the right script as entry script.

Though not 100% sure, but I don't think I do need fix some code of pyarmor, the problem is how to use pyarmor in the right way. Obviously from the report you don't know some basic concepts of pyarmor which are described in the documentation.

**Comment by jondy** [comment]
And make sure no old "license.lic" of obfuscated scripts is used, check is there environment variable "PYARMOR_LICENSE"? Or search "license.lic" in the whole computer.
