### ISSUE TITLE
Deobfuscate pyarmor

### ISSUE THREAD

**Issue by sunnyfarfetch** [dashingsoft/pyarmor#718]
Hello,
I have purchased a license of pyarmor to test with big scripts. I have only 1 question. Can the script obfuscated using pyarmor can be reverse-engineered to get back the original python code?

I will be very happy to have an answer since I am planning to use pyarmor in production.

**Comment by jondy** [comment]
It depends on how to use pyarmor. Now spp mode is an irreversible mode to obfuscate the python scripts, and pyarmor is well documented, please check the documentation to get the right way.

**Comment by sunnyfarfetch** [comment]
Hi Jondy,
Thanks a lot for the information. Can you kindly elaborate on what is " spp mode " ?

**Comment by jondy** [comment]
sunnyfarfetch ***@***.***> writes:

> Hi Jondy,
> Thanks a lot for the information. Can you kindly elaborate on what is " spp
> mode " ?
>

Check the last section in the usage page of online documentation.

**Comment by sunnyfarfetch** [comment]
I am running on Windows 11. I have put the "clang.exe" in "C:\Users\tanvi" directory which is my home directory of currently logged on user. Now I am running 
pyarmor obfuscate --advanced 5 my_crawler.py
this command in command prompt. But I am getting:
ERROR    No available c compiler found

Can you help me on this issue?

**Comment by JiaPai12138** [comment]
Hello, I also purchased a license.
My question emmmmm, comes from this [post](https://forum.tuts4you.com/topic/41945-python-pyarmor-my-protector/
). So, in order to protect my str content, will it work if i replace all my str with bytearray?

**Comment by jondy** [comment]
@JiaPai12138 please do not paste any hack pyarmor link here, it's better to send private email for any hack link.

If you'd like to replace str with bytearray, why not replace str with a custom type? bytearry could not increase security more.

**Comment by sunnyfarfetch** [comment]
Hi @jondy ,
Using super plus mode, with clang.exe, I convereted .py files into unreadable py files. Also, there is a .pyd file generated which is something like a library that pyarmor uses. I am greatly relying on this tool. 

Wondering if you share any risk of reverse engineering / deobfuscation ? I used --advance 5 option.

**Comment by jondy** [comment]
Hi Sunny, spp mode converts python script to c code, so it's irreversible. And I think I have documented all what I could say in the online documentation.

**Comment by pyunpack** [comment]
> 

Hi, @jondy 

Could you please share where exactly the `spp mode` in online docu? 
Just checked https://pyarmor.readthedocs.io/en/latest/usage.html, but not found it. Just found Super Plus Mode, which I guess it's SP or SPM, not SPP?

**Comment by tanviranik** [comment]
> > 
> 
> Hi, @jondy
> 
> Could you please share where exactly the `spp mode` in online docu? Just checked https://pyarmor.readthedocs.io/en/latest/usage.html, but not found it. Just found Super Plus Mode, which I guess it's SP or SPM, not SPP?

https://pyarmor.readthedocs.io/en/latest/mode.html
Details here: --advance 5
to use spp, use this command.

**Comment by jondy** [comment]
Hi all, I decide to close this issue, and do not discuss any deobfuscate issues here. About security issue, please discuss by email.

**Comment by jondy** [comment]
> Well that is an old one, 2 years ago and even the pro coders can barely hack
> pyarmor, which is why i purchased the license. And also could you provide an
> example or link about how to code a custom type in storing string? What i
> know is just store in butearray and then xor
>

I think it's ok to store string in bytearray and then xor.
