### ISSUE TITLE
[ERROR] Not working core lib

### ISSUE THREAD

**Issue by Soi9x** [dashingsoft/pyarmor#719]
INFO     PyArmor Trial Version 7.4.1
INFO     Python 3.10.3
INFO     Target platforms: Native
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/index.json
INFO     Create platform path: C:\Users\MYPC-HOME\.pyarmor\platforms
INFO     Write cached platform list file C:\Users\MYPC-HOME\.pyarmor\platforms\index.json
WARNING  The trial version could not download the latest core libraries, tag r41.15a is always used
ERROR    The latest pyarmor could not work with core library r41.15a, please use pyarmor < v7.0.0

**Comment by yanyahu** [comment]
我遇到了相同的问题，请问怎么解决呢
