### ISSUE TITLE
ModuleNotFoundError: No module named 'pytransform'

### ISSUE THREAD

**Issue by thecowmilk** [dashingsoft/pyarmor#720]
**Title**
ModuleNotFoundError: No module named 'pytransform'

**Description**
I get to obfuscate my python file using `pyarmor` but whenever I make it executable using `pyinstaller -F test.py` it always throw me the `ModuleNotFoundError: No module named 'pytransform'` error and it is driving me crazy because I have tried many solutions but they didn't work.

The output log could be redirected to a file by this way. For example,

Logs:
[log.txt](https://github.com/dashingsoft/pyarmor/files/8355847/log.txt)

Here is an issue instance
I try to run when it is on `.exe` it and it always gives me the `ModuleNotFoundError: No module named 'pytransform' error. Idk how to solve this

**Comment by jondy** [comment]
Please find the solution in the online documentation.
