### ISSUE TITLE
Is my way of obfuscating weak?

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#721]
I bought the paid pyarmor license, I've been using it for a few months now to protect my desktop application.

This application is distributed for the Windows operating system, starting with seven.

To distribute and facilitate the logistics of updates I created a launcher that checks for versions on the server, and this **launcher** is encrypted with the following flags:
_pyarmor obfuscate main.py --recursive --restrict 5 --advanced 2 --obf-code=2 --wrap-mode 1_

For the application, I don't generate a bootstrap and runtime, since the launcher itself will contain the bootstrap and runtime, so the launcher itself will import the source code.

For the **source code** I use the flags:
_pyarmor obfuscate main.py --no-runtime --recursive --restrict 2 --advanced 2 --obf-code=2 --wrap-mode 1_

OBS: Reforcing that source code will use pyd file of launcher. Launcher will append to sys path the path of source code before import main.py of source code

Am I leaving any security holes?
I have no intention of upgrading to advanced 5 at the moment.

**Comment by jondy** [comment]
pyarmor is well documented, I don't help to check the user command.
