### ISSUE TITLE
Updating PyArmor version using paid license

### ISSUE THREAD

**Issue by LucasGitDev** [dashingsoft/pyarmor#722]
My company has an application built with Django Rest Framework that has always been obfuscated with PyArmor 5.5.3 trial version. Now, we received a new request to update the license to the paid version.

To execute the obfuscation process we have an automated script that successfully obfuscates the scripts using the old version(5.5.3).

I have Scripts and Lib folders, inside Scripts I have manage.py(from Django) and inside Lib there are the Apps.

The obfuscation process follows the following steps( in * new steps that I added):

-> add all apps’  __init__.py as entry’s, besides manage.py and wsgi.py
-> * use licenses command to create a license.lic archive
-> * use config command to bootstrap 2 and with-license
-> use build command (without options)
-> * use build command with -B and windows 32bits platform 
-> wait process and set up bootstrap importing to the right paths

**It’s important to say that:**

Every time that the automated script runs, all the project is restarted, in other words, dist folder is cleaned;
It’s used a python own executable in 3.7.2 version;

After obfuscation proces, I have the following folders:

- Lib
- Scritps
- - `platforms`
- - `pytranform`
- - - `__init__.py`
- - - `_pytransform.dll`
- - `manage.py`

manage.py’s bootstrap:

#!/usr/bin/env python
from Scripts.pytransform import pyarmor_runtime
pyarmor_runtime('C:\\Users\\my\\path\\to\\dist\\Scripts\\')

My problem is that when I try to use manage.py, I receive the following error:

`Check license failed, Invalid input packet.`

I searched in PyArmor documentation and in GitHub issues but nothing solved the problem.

Obs.: I’ve already had several problems before, with pytransform’s import errors, DLL path errors etc. I used PyArmor documentation to solve all of these problems.

**Comment by jondy** [comment]
> Check license failed, Invalid input packet.

Generatelly, it means some files are generated by old version. Please make sure all the files are generated by new version, check the output log of pyarmor to find which files are generated.

Also check the change logs in the online documentation, the license file format isn't compatiable in some versions.

**Comment by LucasGitDev** [comment]
Every time that I tested the process that I described above I removed all older pyarmor content, and still have the same error:

> File "Scripts\incontrol_backend_manage.py", line 3, in <module>
>     pyarmor_runtime('C:\\Users\\path\\to\\dist\\Scripts\\')
>   File "C:\\Users\\path\\to\\dist\\Scripts\pytransform\__init__.py", line 344, in pyarmor_runtime
>     pyarmor_init(path, is_runtime=1, suffix=suffix, advanced=advanced)
>   File "C:\Users\path\to\dist\Scripts\pytransform\__init__.py", line 340, in pyarmor_init
>     return init_pytransform()
>   File "C:\Users\path\to\dist\Scripts\pytransform\__init__.py", line 57, in wrap
>     return func(*args, **kwargs)
>   File "C:\Users\path\to\dist\Scripts\pytransform\__init__.py", line 75, in init_pytransform
>     ret = init_module(major, minor, pythonapi._handle)
> RuntimeError: Check license failed, Invalid input packet.

I performed the process using PyArmor v6.5.2 and v7.4.1 (always deleting `~/.pyarmor`).

My project build process always clones again all the repositories that I need, so all the folders are always clean. Besides that, it installs Python Embedded.

 A question that I have is: the error “Check license failed” refers to the bought license or the license generated by the command `licenses --expired 2099-12-31`?

**Comment by jondy** [comment]
> A question that I have is: the error “Check license failed” refers to the
> bought license or the license generated by the command licenses --expired
> 2099-12-31?
>

It refer to the license generated by command "licenses".
