### ISSUE TITLE
child pid XXX exit signal Segmentation fault (11) | Apache mod_wsgi

### ISSUE THREAD

**Issue by Pablo849** [dashingsoft/pyarmor#727]
I can't deploy a Django project with Apache mod_wsgi. It returns "child pid XXX exit signal Segmentation fault (11)" error.
```
Apache/2.4.6 (CentOS) 
OpenSSL/1.0.1e-fips 
mod_fcgid/2.3.9 
PHP/8.1.5RC1 
mod_wsgi/4.9.0 
Python/3.6
```
Without obfuscation, it works correctly. I have used the settings indicated in the documentation for Apache, even though I normally deploy it as a Daemon. Neither way works and I don't get a clear error in the Apache log.

**Comment by jondy** [comment]
I have no ideas by these information.

**Comment by LucasGitDev** [comment]
@Pablo849  did you look at #716?
We are getting a problem like it.
