### ISSUE TITLE
[SPP] Nonetype object has no attribute stt

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#731]
Tried to run command: 

_pyarmor obfuscate main.py --advanced 5 --recursive --no-runtime --platform windows.x86 --output C:\Users\User\Desktop\obfuscated_

I got this exception when compiling:

_INFO     PyArmor Version 7.4.1
INFO     Python 3.7.3
INFO     Target platforms: ['windows.x86']
INFO     Update target platforms to: ['windows.x86.11.py37']
INFO     Source path is "******"
INFO     Entry scripts are ['main.py']
INFO     Use cached capsule C:\Users\User\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Save obfuscated scripts to "C:\Users\User\Desktop\obfuscated"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2

INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 2
INFO     Super mode is True
INFO     Super plus mode is enabled
INFO     Generating spp code for <frozen folder.module_name.py> ...
ERROR    'NoneType' object has no attribute 'stt'_

I am using python 3.7.3 x86_64, there is anything am I missing?

Full log content anexed
[log.txt](https://github.com/dashingsoft/pyarmor/files/8483380/log.txt)

**Comment by jondy** [comment]
Not all the features are supported by spp mode, in this case, use inline option `--no-spp-mode` to ignore the related functions or modules.

Please refer to the chapter Mode to find how to ignore functions or modules.

**Comment by pauloswear** [comment]
I saw to insert at the top of module:
# pyarmor options: no-spp-mode

 or inside function:
'''pyarmor options: no-spp-mode'''

But in doc, there is no flag to "--no-spp-mode", i tried run but:
**pyarmor: error: unrecognized arguments: --no-spp-mode**

**Comment by jondy** [comment]
Paulo Henrique ***@***.***> writes:

> I saw to insert at the top of module:
>
> pyarmor options: no-spp-mode
>
> or inside function:
> '''pyarmor options: no-spp-mode'''
>
> But in doc, there is no flag to "--no-spp-mode", i tried run but:
> pyarmor: error: unrecognized arguments: --no-spp-mode
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were assigned.
>

Please search "no-spp-mode" in the online documention, you'll find the right example.
