### ISSUE TITLE
Script runs if computer date is set to past date even though obfuscated with "check_ntp_time.py" option.

### ISSUE THREAD

**Issue by AndreCape** [dashingsoft/pyarmor#734]
Hello.

Obfuscated script with expiry date 2 days in to the future.
When I set the computer date 3 days in future the error comes up "License expired". - That works.

But I can set the date to any date in the past and I don't get an error and the script runs fine.

So, expiry works for future dates but not for dates set in the past.

What is the solution here?
Thank you.

LICENSE FILE:
"Expired:2022-04-17*FLAGS: *HARDDISK:0023_0451_1000_4AGB*IFMAC:28:F1:0F:31:65:09*CODE:Win10_laptop"

STEPS:
`pyarmor -d obfuscate --plugin check_ntp_time --platform windows.x86 --advanced 4 --output dist/import_64_gts/__init__.py --exact import_64_gts.py`

```
cd dist
python -c "import import_64_gts"
cd..
```

`pyarmor pack -x " --advanced 4" --with-license licenses\Win10_laptop\license.lic import_64_gts.py`

**Comment by jondy** [comment]
Refer to check_ntp_time.py, and write your own plugin.

**Comment by AndreCape** [comment]
Hello.

I posted this just to be sure I use the correct setup. I'm certainly not saying the code is not good enough. On the contrary I think the code is on a professional level.

I'm not not that good with Python to write my own plugin.

Thank you.

**Comment by feschenkovladimir** [comment]
Can you fix it? I ran into similar issue. Maybe there is possibility to display error if module does not work as it should? How to understand why plugin is not working?

**Comment by AndreCape** [comment]
The reason why this is a problem for me is the user can easily backdate the computer's date and still use my software for free past it's expiry date.

A fix would be great :-)

**Comment by jondy** [comment]
Plug in `check_ntp_time` need custom data when generating license, it works fine. 

The problem is that the license you generated is not expected by this plugin.

Please find the example in the advanced usage of online document, or search "check_ntp_time" in the online documentation.

**Comment by AndreCape** [comment]
> @jondy Can you fix it? I ran into similar issue. Maybe there is possibility to display error if module does not work as it should? How to understand why plugin is not working?

Vladimir.
Have you managed to get a solution for this?
I read through the manual so many times but can't find a solution. May be I'm missing something ....

**Comment by feschenkovladimir** [comment]
> > @jondy Can you fix it? I ran into similar issue. Maybe there is possibility to display error if module does not work as it should? How to understand why plugin is not working?
> 
> Vladimir. Have you managed to get a solution for this? I read through the manual so many times but can't find a solution. May be I'm missing something ....

You should try inserting following code at beginning of file you want to encode:

```
# {PyArmor Plugins}
# PyArmor Plugin: check_ntp_time()
```

Found it here: https://pyarmor.readthedocs.io/en/latest/advanced.html#using-plugin-to-extend-license-type
Maybe this will solve problem. I haven't had a chance to test this yet.

**Comment by AndreCape** [comment]
I do have the lines inserted
# {PyArmor Plugins}
# PyArmor Plugin: check_ntp_time()

Ran obfuscation with and without it. No change.
Obfuscated (to folder) .exe still runs when backdating the computer's date/time.

I just wonder if there are anybody else who actually tested to change the computer's date backwards..?

**Comment by jondy** [comment]
The plugin is a normal python script, it only need you to learn some knowledges about pyarmor runtime package 'pytransform' which is well documented.

**Comment by AndreCape** [comment]
So if it's just about knowing more about pytransform package and so easy then why can't you fix it?
No it's not about learning or knowing Python.
It's a level 1 bug in the code.
The code can stop a script running at a date but can't do the same when I set the date to past date. This makes the software useless for what it's promoted and documented for and for what one pays for.

If you say in your documentation that Pyarmor then people won't pay for this.
Seems to me you can't get this part to work.

**Comment by kr1tx** [comment]
> So if it's just about knowing more about pytransform package and so easy then why can't you fix it? No it's not about learning or knowing Python. It's a level 1 bug in the code. The code can stop a script running at a date but can't do the same when I set the date to past date. This makes the software useless for what it's promoted and documented for and for what one pays for.
> 
> If you say in your documentation that Pyarmor then people won't pay for this. Seems to me you can't get this part to work.

I have tried this, and worked just fine for me even If I changed the date back to 2019 or forward to 2024

pyarmor obfuscate --with-license licenses\xd\license.lic --plugin check_ntp_time foo.py
inserted those lines at the begging of my script
**# -*- coding: utf-8 -*-
# {PyArmor Plugins}
# PyArmor Plugin: check_ntp_time()**
Please note that _check_ntp_time_ is a file with no extension.
Hopefully this would work for you.
