### ISSUE TITLE
No obfuscated script found

### ISSUE THREAD

**Issue by andynppn** [dashingsoft/pyarmor#736]
On Windows 10 21H2, when I run this:
pyarmor pack test.py

INFO     ==================== Run command ====================
INFO     PyArmor Version 7.4.2
INFO     Python 3.10.4
INFO     Target platforms: Native
......

File "test-patched.spec", line 33, in <module>
    raise RuntimeError('No obfuscated script found')
RuntimeError: No obfuscated script found
ERROR    Run command failed

Content of test.py:

print("hello world")

How to deal with this problem?

**Comment by jondy** [comment]
Please refer to "When things go wrong" in the documentation first. It introduces some methods to debug this kind of issue.

**Comment by andynppn** [comment]
Thank you @jondy. I followed this https://pyarmor.readthedocs.io/en/latest/how-to-do.html#how-to-pack-obfuscated-scripts and problem is resolved.
