### ISSUE TITLE
加密多个脚本每个脚本都是主脚本 不想一个一个脚本输入怎么办呢

### ISSUE THREAD

**Issue by aclemon** [dashingsoft/pyarmor#738]
加密多个脚本每个脚本都是主脚本 不想一个一个脚本输入怎么办呢

比如说 a.py b.py c.py ......xxx  y.py
我加密的时候 bootstrap  模式输入 没办法更改所有的py文件都为主脚本

**Comment by jondy** [comment]
先去看看文档吧
