### ISSUE TITLE
Pyamor not working with playwright

### ISSUE THREAD

**Issue by Martin-rhs** [dashingsoft/pyarmor#739]
**Title**

playwright._impl._api_types.Error: stack[1].line: expected number, got object

**Description**
pyarmor pack -e" -F  --icon icon.ico" .\main.py

code:

```
browser = p.firefox.launch(
    headless=True,
    devtools=False,
    executable_path=sys._MEIPASS+"\playwright\driver\package\.local-browsers\\firefox-1319\\firefox\\firefox.exe",
    proxy={
        "server": f"{self.ip}:{self.port}",
        "username": self.user,
        "password": self.pw,
    }
)
```

Full Error:
```
Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "<frozen zalando_email_changer>", line -1, in __run
  File "threading.py", line 946, in run
  File "<frozen zalando_email_changer>", line -1, in __init__
  File "<frozen zalando_email_changer>", line 59, in all
  File "playwright\sync_api\_generated.py", line 11511, in launch
  File "playwright\_impl\_sync_base.py", line 88, in _sync
  File "playwright\_impl\_browser_type.py", line 90, in launch
  File "playwright\_impl\_connection.py", line 39, in send
  File "playwright\_impl\_connection.py", line 63, in inner_send
playwright._impl._api_types.Error: stack[1].line: expected number, got object
```

I packed it with pyinstaller and everything work well but when i do it with pyamror i have this error.

**Comment by jondy** [comment]
Martin-rhs ***@***.***> writes:

> Title
>
> playwright._impl._api_types.Error: stack[1].line: expected number, got object
>
> Description
> pyarmor pack -e" -F --icon icon.ico" .\main.py
>
> code:
>
> browser = p.firefox.launch(
>     headless=True,
>     devtools=False,
>     executable_path=sys._MEIPASS+"\playwright\driver\package\.local-browsers\\firefox-1319\\firefox\\firefox.exe",
>     proxy={
>         "server": f"{self.ip}:{self.port}",
>         "username": self.user,
>         "password": self.pw,
>     }
> )
>
> Full Error:
>
> Traceback (most recent call last):
>   File "threading.py", line 1009, in _bootstrap_inner
>   File "<frozen zalando_email_changer>", line -1, in __run
>   File "threading.py", line 946, in run
>   File "<frozen zalando_email_changer>", line -1, in __init__
>   File "<frozen zalando_email_changer>", line 59, in all
>   File "playwright\sync_api\_generated.py", line 11511, in launch
>   File "playwright\_impl\_sync_base.py", line 88, in _sync
>   File "playwright\_impl\_browser_type.py", line 90, in launch
>   File "playwright\_impl\_connection.py", line 39, in send
>   File "playwright\_impl\_connection.py", line 63, in inner_send
> playwright._impl._api_types.Error: stack[1].line: expected number, got object
>
> I packed it with pyinstaller and everything work well but when i do it with
> pyamror i have this error.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were assigned.
>

One solution, hack "playwright\_impl\_connection.py" at line 63.

**Comment by Martin-rhs** [comment]
Wdym by hack "playwright\_impl\_connection.py" at line 63?

**Comment by jondy** [comment]
Check the trace back

**Comment by Martin-rhs** [comment]
`result = next(iter(done)).result()` this the code at "playwright\_impl\_connection.py" line 63

**Comment by jondy** [comment]
```
playwright._impl._api_types.Error: stack[1].line: expected number, got object
```
Check which variable results in this exception, convert it to number
