### ISSUE TITLE
Second build don't rebuild files

### ISSUE THREAD

**Issue by KomarovAlea** [dashingsoft/pyarmor#74]
https://github.com/dashingsoft/pyarmor/blob/af120b7f9d2dcd07bca868c72ab326f7fbf2ff60/src/project.py#L166

Make build. Then change code. **Remove** dist-folder! Build - get **empty** dist.
It's because in this code check buildtime of py-file in source folder, and if it less then file are don't generated. This is logical. 
But it also need to check: is obfuscated file exist in dist-dir. And if it don't exist - then it need to reobfuscated them again.

I am python developer and I can read py-code. But other users of pyArmor may encounter difficulties if they remove dist-folder and try to build project again.

**Comment by jondy** [comment]
There is an option to force rebuild all files:
```
pyarmor build -B
pyarmor build --force
```
