### ISSUE TITLE
PyArmor File is Abnormally Large

### ISSUE THREAD

**Issue by Gowixx** [dashingsoft/pyarmor#742]
It's more readable in the issue Preview mode for the hints

**Read the Title**
Title explains the issue very clearly

**Description**
Full PyArmor Output: https://www.toptal.com/developers/hastebin/lujesixuko.sql
It seems to give an error at the end, however, the file is fully compiled and still runs.

The size of the file created is ~132mb for a project that is ~12kb

**Comment by jondy** [comment]
Please compare the original .py and the obfuscated .py separately, generally it's about 4 times of original size.

If you're using command `pack`, the final executable size may be large, it's not related to pyarmor but PyInstaller. Please check the documentation of PyInstaller.

**Comment by Gowixx** [comment]
Hey, I found the issue. PyArmor or PyInstaller (not sure) packs every module that you have installed. To fix this, I just use a venv when obfuscating.
