### ISSUE TITLE
obfuscated module hanging at import time on mac

### ISSUE THREAD

**Issue by fdv1** [dashingsoft/pyarmor#744]
The command below causes Python to spin (ie: use 100% CPU).

python -c "import reflect" 

You can find the faulty module under:

https://pytek.io/data/archives/0.2.3/reflect-mac.3.10-0.2.3.tar.gz

INFO     PyArmor Version 7.4.3
INFO     Python 3.10.0
INFO     Target platforms: ['darwin.aarch64', 'darwin.x86_64']
INFO     Update target platforms to: ['darwin.aarch64.3', 'darwin.x86_64.7']
INFO     Source path is "/Users/francois/Projects/reflect/reflect/reflect/reflect"
INFO     Entry scripts are ['/Users/francois/Projects/reflect/reflect/reflect/reflect/__init__.py']
INFO     Use cached capsule /Users/francois/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Patch extension dist/pytransform/darwin.aarch64.3._pytransform.dylib
INFO     Signing file dist/pytransform/darwin.aarch64.3._pytransform.dylib
INFO     Patch library file OK
INFO     Patch extension dist/pytransform/darwin.x86_64.7._pytransform.dylib
INFO     Signing file dist/pytransform/darwin.x86_64.7._pytransform.dylib
INFO     Patch library file OK
INFO     Generate universal binary dist/pytransform/_pytransform.dylib
INFO     Copying /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            __init__.py -> dist/__init__.py
INFO     Insert bootstrap code to entry script dist/__init__.py
INFO            abc.py -> dist/abc.py
INFO            app_runner.py -> dist/app_runner.py
INFO            common.py -> dist/common.py
INFO            components.py -> dist/components.py
INFO            connection.py -> dist/connection.py
INFO            controller.py -> dist/controller.py
INFO            dashboard.py -> dist/dashboard.py
INFO            html.py -> dist/html.py
INFO            kernel.py -> dist/kernel.py
INFO            kernel_manager.py -> dist/kernel_manager.py
INFO            props.py -> dist/props.py
INFO            reg_test.py -> dist/reg_test.py
INFO            supervisor.py -> dist/supervisor.py
INFO            utils.py -> dist/utils.py
INFO            value.py -> dist/value.py
INFO            window.py -> dist/window.py
INFO     Obfuscate 17 scripts OK.

**Comment by jondy** [comment]
How about obfuscate the scripts without multiple platform?

**Comment by fdv1** [comment]
still no joy...

**Comment by jondy** [comment]
How about testing with a simple hello world script? Also check the documentation "When thing to wrong", there are some common solutions for different kind of issues.

Generally I don't debut user's scripts, also check the documentation "understanding the obfuscated scripts" to make sure the scripts don't use any feature changed by pyarmor.

If possible, please provide a simple scripts which could reproduce this issue.

**Comment by jondy** [comment]
Really? I'll check it.

**Comment by fdv1** [comment]
Just add "arch -arm64" in front of your command. Are you sure you don't want to force the command to run on x86_64?

**Comment by jondy** [comment]
I haven't check it because my Mac is x86_64 not M1. But as my understand, the universal `_pytransform.so` should work both x86_64 and arm64 mode.

**Comment by fdv1** [comment]
I would highly recommand getting your hands on of those new macs (even the entry model is amazing!). 
Feel free to send me a sample to assert whether my assumption is correct (ie: universal binaries produced by x86_64 are buggy).

**Comment by jondy** [comment]
In my Mac-os (only x86_64 mode), I test this
```
$ python3 pyarmor.py o --platform darwin.aarch64,darwin.x86_64 examples/simple/queens.py 
INFO     PyArmor Version 7.5.0
INFO     Python 3.7.10
INFO     Target platforms: ['darwin.aarch64', 'darwin.x86_64']
INFO     Update target platforms to: ['darwin.aarch64.3', 'darwin.x86_64.7']
INFO     Source path is "/Users/jondy/workspace/pyarmor/tests/pyarmor-7.5.0/src/examples/simple"
INFO     Entry scripts are ['examples/simple/queens.py']
INFO     Use cached capsule /Users/jondy/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Patch extension dist/pytransform/darwin.aarch64.3._pytransform.dylib
INFO     Signing file dist/pytransform/darwin.aarch64.3._pytransform.dylib
INFO     Patch library file OK
INFO     Patch extension dist/pytransform/darwin.x86_64.7._pytransform.dylib
INFO     Signing file dist/pytransform/darwin.x86_64.7._pytransform.dylib
INFO     Patch library file OK
INFO     Generate universal binary dist/pytransform/_pytransform.dylib
INFO     Copying /Users/jondy/workspace/pyarmor/tests/pyarmor-7.5.0/src/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO     	queens.py -> dist/queens.py
INFO     Patch this entry script with protection code
INFO     Insert shell line: #!/usr/bin/env python3
INFO     Insert bootstrap code to entry script dist/queens.py
INFO     Obfuscate 1 scripts OK.

$ python3 dist/queens.py
```
It works fine.

**Comment by fdv1** [comment]
@imeliran great! (I don't know why I suggested using x86_64...)  
@jondy I can reproduce the bug fairly easily as follows

➜  pyarmor /Library/Frameworks/Python.framework/Versions/3.10/bin/pyarmor o --platform darwin.aarch64,darwin.x86_64 hello_world.py 
INFO     PyArmor Version 7.4.3
INFO     Python 3.10.0
INFO     Target platforms: ['darwin.aarch64', 'darwin.x86_64']
INFO     Update target platforms to: ['darwin.aarch64.0', 'darwin.x86_64.0']
INFO     Source path is "/Users/francois/Projects/pyarmor"
INFO     Entry scripts are ['hello_world.py']
INFO     Use cached capsule /Users/francois/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Patch extension dist/pytransform/darwin.aarch64.0._pytransform.dylib
INFO     Signing file dist/pytransform/darwin.aarch64.0._pytransform.dylib
INFO     Patch library file OK
INFO     Patch extension dist/pytransform/darwin.x86_64.0._pytransform.dylib
INFO     Signing file dist/pytransform/darwin.x86_64.0._pytransform.dylib
INFO     Patch library file OK
INFO     Generate universal binary dist/pytransform/_pytransform.dylib
INFO     Copying /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO     	hello_world.py -> dist/hello_world.py
INFO     Insert bootstrap code to entry script dist/hello_world.py
INFO     Obfuscate 1 scripts OK.
➜  pyarmor python3.10 dist/hello_world.py 
Hello world!
➜  pyarmor arch -x86_64 /Library/Frameworks/Python.framework/Versions/3.10/bin/pyarmor o --platform darwin.aarch64,darwin.x86_64 hello_world.py
INFO     PyArmor Version 7.4.3
INFO     Python 3.10.0
INFO     Target platforms: ['darwin.aarch64', 'darwin.x86_64']
INFO     Update target platforms to: ['darwin.aarch64.3', 'darwin.x86_64.7']
INFO     Source path is "/Users/francois/Projects/pyarmor"
INFO     Entry scripts are ['hello_world.py']
INFO     Use cached capsule /Users/francois/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Patch extension dist/pytransform/darwin.aarch64.3._pytransform.dylib
INFO     Signing file dist/pytransform/darwin.aarch64.3._pytransform.dylib
INFO     Patch library file OK
INFO     Patch extension dist/pytransform/darwin.x86_64.7._pytransform.dylib
INFO     Signing file dist/pytransform/darwin.x86_64.7._pytransform.dylib
INFO     Patch library file OK
INFO     Generate universal binary dist/pytransform/_pytransform.dylib
INFO     Copying /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO     	hello_world.py -> dist/hello_world.py
INFO     Insert bootstrap code to entry script dist/hello_world.py
INFO     Obfuscate 1 scripts OK.
➜  pyarmor python3.10 dist/hello_world.py
^Cq^C^C[1]    56354 killed     python3.10 dist/hello_world.py

**Comment by jondy** [comment]
I find the problem. It's not related to `arch -x86_64`, but the feature of `_pytransform.so`.

I think this command should work
```
arch -x86_64 /Library/Frameworks/Python.framework/Versions/3.10/bin/pyarmor o --platform darwin.aarch64.0,darwin.x86_64.0 hello_world.py
```

Refer to
https://pyarmor.readthedocs.io/en/latest/platforms.html#features

**Comment by fdv1** [comment]
yes that's right! It would be great to warn users or change the default encryption features in that case. The only way I can see to detect that a Python process is running in emulated mode is through the uname root attributes, it is undistinguishable from a standard x86_64 process otherwise.
>>> platform.uname().version
'Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101'

**Comment by jondy** [comment]
I add warning message for this case.
