### ISSUE TITLE
Questions about applying the core library.

### ISSUE THREAD

**Issue by JangKyumin** [dashingsoft/pyarmor#747]
Hello.

https://github.com/dashingsoft/pyarmor/issues/716

An extension to that question.

> The trial version always uses core library r41.15 (with pyarmor 6.6.2), the purchased version uses the latest core library (now it's r49.3). Try to install pyarmor 6.6.2 which uses core library r41.15, it should be same as the trial version.

I tested it because I remembered the part you mentioned above.

I don't know if it's a python version problem or a core library problem, but when I conducted the test as below, the uwsgi was running normally.

1. Remove the pyarmor completely and install it in version 6.6.2.
2. Register license with register command.
3. Test project obfuscation progress.
4. Overwrite script `__init__.py` of pytransform changed by cygwin application issue.
5. Check normal after uwsgi is driven.

Lowering the core library version resolved the issue.

Then, is the problem with the change from r41.15 to r49.3 when the version was raised?

I don't think it's a good idea to use the old version from the point of purchasing a license, including security issues.

What additional information should I provide for the latest version?

**Comment by jondy** [comment]
Could you check this example work or not with latest pyarmor version?

https://pyarmor.readthedocs.io/en/latest/examples.html#running-obfuscated-django-site-with-apache-and-mod-wsgi

**Comment by JangKyumin** [comment]
@jondy 

If nginx and uwsgi were used in cygwin environment, obfuscating Django's simple project mysite from the latest version of pyarmor would not work.

I don't know if Apache and mod_wsgi can be applied to cygwin.

I'll test it and tell you again.

**Comment by jondy** [comment]
@JangKyumin 
If you don't use apache, could you do a test like this:
1. Deploy django site without obfuscating, make sure it works.
2. Obfuscate a simple script "hello.py" which only includes a print statement
3. Copy "dist/hello.py" and "dist/pytransform" to django site
4. Add some test statements in one of dingo site script
```python
def mytest():
    import sys
    print('Python version:', sys.version_info[:2])
    import hello
```
5. Make sure this function `mytest` is called only when sending a request from client. That is to say, not call `mytest` in model level
6. Make a request from client to call this `mytest`, check the obfuscated script `hello.py` works or not.

**Comment by JangKyumin** [comment]
@jondy 
I tested it as you told me.

1. Deploying django project `mysite` without obfuscating will run normally.
2. Obfuscated `hello.py` with print only.
3. Copy `dist/hello.py` and `dist/pyt transform` to `mysite`.
4. Added to invoke function `mytest` in index function in pols package views.
5. Annotating `import hello` in `mytest` function will normally call the index function when the client calls polls.
6. However, if the call is made reflecting `import hello`, it will not be called normally.

**Comment by jondy** [comment]
What's the output of this statement `print('Python version:', sys.version_info[:2])` in the function `mytest`?

**Comment by JangKyumin** [comment]
If `import hello` is annotated and executed normally, the output is `Python version:(3,5)`.

**Comment by jondy** [comment]
Is there any traceback or error message when importing `hello`?

**Comment by JangKyumin** [comment]
There is no error message, and the uwsgi log shows the following output.

```
Python version: (3, 5)
Wed May 18 08:58:10 2022 - !!! uWSGI process 1912 got Segmentation Fault !!!
Wed May 18 17:58:11 2022 - DAMN ! worker 1 (pid: 1912) died :( trying respawn ...
Wed May 18 17:58:11 2022 - Respawned uWSGI worker 1 (new pid: 1919)
Wed May 18 08:58:13 2022 - WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x8000ae720 pid: 1919 (default app)
```

**Comment by jondy** [comment]
1. How about run the obfuscated `hello.py` by python interpreter directly?
2. How about obfuscate `hello.py` with feature `0`?  Then run it like above in Django site. For example, in linux.x86_64 with feature `0`
```
pyarmor obfuscate --platform linux.x86_64.0 foo.py
```

**Comment by JangKyumin** [comment]
1. Run it right away with the Python interpreter and it runs well.
2. The option `--platform windows.x86_64.0` is obfuscated and applied, but it does not run the same.

**Comment by jondy** [comment]
Do you know which Python interpreter is used by uwsgi? Try to test uwsgi application by Python interpreter directly

Here an example about how to run uwsgi application in the command line directly
https://hostpresto.com/community/tutorials/how-to-serve-python-apps-using-uwsgi-and-nginx-on-centos-7/

I think Cygwin should be same as this, could you obfuscate a simple uwsgi application `wsgi.py`

```python
def application(environ, start_response):
        start_response('200 OK', [('Content-Type', 'text/html')])
        return ["<h1 style='color:blue'>Testing Success!</h1>"]
```

And run it in Cygwin
```
uwsgi --socket 0.0.0.0:8080 --protocol=http -w wsgi
```

Before testing the obfuscated script, make sure the plain script works fine.

**Comment by JangKyumin** [comment]
uwsgi is looking at the Python interpreter installed in cygwin.

I tested to run uwsgi directly on the python interpreter in the way you told me.

``` python
def application(environ, start_response):
	start_response('200 OK', [('Content-Type', 'text/html')])
	return "<h1 style='color:blue'>Testing Success!</h1>".encode('utf-8')
```

I wrote the script as above, and uwsgi worked normally with the command below.
'Testing Success!' was output normally even when called from the web.

```
/bin/uwsgi.exe --socket 0.0.0.0:8080 --protocol=http -w wsgi
```

However, if you proceed with obfuscation and run uwsgi with python interpreter, it will not work.

Success Log: 
```
*** *** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8000acac0 pid: 1963 (default app)
*** *** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 1963, cores: 1)
[pid: 1963|app: 0|req: 1/1] 127.0.0.1 () {50 vars in 1038 bytes} [Thu May 19 13:46:34 2022] GET / => generated 44 bytes in 1 msecs (HTTP/1.1 200) 1 headers in 44 bytes (1 switches on core 0)
[pid: 1963|app: 0|req: 2/2] 127.0.0.1 () {46 vars in 939 bytes} [Thu May 19 13:46:34 2022] GET /favicon.ico => generated 44 bytes in 61 msecs (HTTP/1.1 200) 1 headers in 44 bytes (1 switches on core 0
```

Failure Log:
```
*** *** Operational MODE: single process ***
!!! !!! uWSGI process 1964 got Segmentation Fault !!!
```

**Comment by jondy** [comment]
Run obfuscated scripts with debug mode, for example
```
export PYTHONDEBUG=y
/bin/uwsgi.exe --socket 0.0.0.0:8080 --protocol=http -w wsgi
```
Is there `pytranform.log` generated? If there is, what's the content?

**Comment by jondy** [comment]
After I read the documentation of `uwsgi`
https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html#bonus-multiple-python-versions-for-the-same-uwsgi-binary

I think the python interpreter used by uwsgi application is either embedded to `uwsgi.exe` or as a plugin like `pythonXY_plugin.so` in somewhere. This may be problem for pyarmor, I'm not sure the obfuscated scripts could work.

**Comment by JangKyumin** [comment]
When I took a picture of the log in debugging mode, it was taken as follows.

```
The core library version: r48, age: 2, features: 7
```

I think we need to find out more about the part where the Python interpreter used in uwsgi is built in.

If this problem exists, could there be a problem in applying pyarmor obfuscation? Can it be improved?

**Comment by jondy** [comment]
I have no plan to fix this. It's python 3.5, and it's not official Python interpreter.

**Comment by jondy** [comment]
Actually from the beginning the pyarmor core library version is related to the python interpreter version. For example, super mode only supported by Python2.7, and Python 3.7 and later. I have documented most of the difference between obfuscated scripts and original plain scripts. It's clear that pyarmor is not 100% compatible with original Python scripts.

I have spend extra time researching `uwsgi` and make decision to not support Cygwin `uwsgi` for Python 3.5. It means I don't want to continue researching `uwsgi` and why it doesn't work with latest pyarmor core library.

There are 2 solutions for this issue:
1. use old version 6.6.2
2. upgrade python to 3.8 or other work version.

**Comment by JangKyumin** [comment]
Yes, I respect your decision.

We will go in the direction of handling it in the way you suggested.

Thank you.
