### ISSUE TITLE
Is it possible to bind multipul mac from different machine?

### ISSUE THREAD

**Issue by BrightXiaoHan** [dashingsoft/pyarmor#748]
I found a releated command in the document.
```
pyarmor licenses --bind-mac "<2a:33:50:46:8f,f0:28:69:c0:24:3a>" r003
```
But it seems that the `Multiple Mac addresses` `<2a:33:50:46:8f,f0:28:69:c0:24:3a>` comes from single machine. 
Is it possible to bind two mac addr  from two different machine into one license. So that the code can be run on the two machines at the same time.

**Comment by jondy** [comment]
No default behavior for binding different machine, refer to document and write the plugin to extend this feature.

**Comment by BrightXiaoHan** [comment]
Ok, thanks.
