### ISSUE TITLE
Only "--advanced 2" is available for Python 3.10

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#750]
Error:
ERROR    Only "--advanced 2" is available for Python 3.10

Command runned: 
**pyarmor obfuscate --advanced 5 script.py**

Versions:
PyArmor Version 7.4.3
Python 3.10.4
Windows 10 x64

Is there anything I can do or just use older version of python?

**Comment by jondy** [comment]
Python3.10 doesn't support `--advanced 5`, use older version of python when using `--advanced 5`

**Comment by pauloswear** [comment]
Thanks @jondy. Is --advanced 4 safe enough to distribute or you still recommend distribute with advanced 5 using older versions ?

**Comment by jondy** [comment]
I recommend advanced 5 with older version.
