### ISSUE TITLE
Obfuscated script can run after setting computer's date to past date.

### ISSUE THREAD

**Issue by AndreCape** [dashingsoft/pyarmor#753]
Scenario:
Obfuscate script with license expiry date set.
When the computer's date gets to expiry date set, according to license file and one runs your obfuscated script one gets 'license expired' warning. (this works)
But changing the computer's date/time to some day/week/month in the past the same script runs without any license warning even though licensed use has expired.

This makes it very easy for a user to run any script even after the license has expired.
I've tried various obfuscating options but all with the same results. The basic test was then to obfuscate with minimal options used.
Basic example of test ran below.

Steps followed from manual PyArmor Documentation 6.7.4.pdf
Chapter 2.3: Generating License For Obfuscated Scripts.

```
pyarmor licenses --expired 2022-05-30 L1
pyarmor obfuscate --with-license licenses/L1/license.lic imp64.py
cd dist
python imp64.py

```

**Comment by jondy** [comment]
Please use plugin to extend license, there is an example in advanced usage, search `check_ntp_time` in the documentation

**Comment by AndreCape** [comment]
Thank you for the reply.

TEST-02:
Same results as previous test.
Setting time to date to future date past license expiry date - Do get license expired warning
Setting time to past date - No license expired warning.
(no errors during build)

```
pyarmor licenses --expired 2022-06-06 L1
pyarmor obfuscate --plugin check_ntp_time --output dist/imp64/__init__.py imp64.py
cd dist
python -c "import imp64"
cd..
pyarmor pack --clean --with-license licenses/L1/license.lic imp64.py


```

**Comment by jondy** [comment]
Please check the example carefully, generate license with option `-x`, do not use `--expired`.

**Comment by AndreCape** [comment]
When I use just the -x option the license does not work at all.
Then I can set the date to any date in the past or future and the obfuscated exe still runs.

Used the same script as above in this thread.

Thank you

**Comment by jondy** [comment]
Could you test the example in the document?

**Comment by jondy** [comment]
No, thanks. I suggest you reading the documentation carefully, I'm sure the example works as expected.

**Comment by AndreCape** [comment]
I ran the code below but the results are all the same.
The obfuscated script runs when the computer's date/time is set to pas date and no 'License expired' warning.
The same script gives 'License expired' warning when the computer's date is set to a future date.

The code below I used are all almost the same as examples in the manual.


```
# TEST-01
pyarmor licenses --expired 2022-06-10 L1
pyarmor obfuscate --with-license licenses/L1/license.lic imp64.py
cd dist
python imp64.py


# TEST-02
pyarmor licenses -e 2022-06-10 L1
pyarmor obfuscate --with-license licenses/L1/license.lic imp64.py
cd dist
python imp64.py


# TEST-03
pyarmor licenses --expired 2022-06-10 L1

pyarmor obfuscate --plugin check_ntp_time --output dist/imp64/__init__.py imp64.py
cd dist
python -c "import imp64"
cd..
pyarmor pack --clean --with-license licenses/L1/license.lic imp64.py


# TEST-04
pyarmor licenses -e 2022-06-10 L1

pyarmor obfuscate --plugin check_ntp_time --output dist/imp64/__init__.py imp64.py
cd dist
python -c "import imp64"
cd..
pyarmor pack --clean --with-license licenses/L1/license.lic imp64.py


# TEST-05
pyarmor licenses -d "0023_0356_1000_4AEB" -m "28:F1:0E:37:75:96" -e 2022-06-10 L1

pyarmor -d obfuscate --plugin check_ntp_time --platform windows.x86 --advanced 2 --output dist/imp64/__init__.py --exact imp64.py
cd dist
python -c "import imp64"
cd..
pyarmor pack --clean -x " --advanced 2" --with-license licenses\L1\license.lic imp64.py

```

Thank you.

**Comment by jondy** [comment]
Do you really read this example?
https://pyarmor.readthedocs.io/en/latest/advanced.html#using-plugin-to-extend-license-type

I have told you using `-x` not `--expired` to generate license, but you still do as yourself understanding. 

Please read the man page of command `license` to understand the differences between `-x` and `--expired`

And read the man page of command `pack` to understand what it does, it's also required to pass `--plugin check_ntp_time` to obfuscate the scripts when packing the script.

**Comment by AndreCape** [comment]
I see you closed the case.

You say I have to use -x option when generating the license file.
-x option does not enable a license. Can set date past expiry date - code still runs.
-e then license shows expired warning.
This as per manual: Page 6, 2.3 Generating License For Obfuscated Scripts

I still don't have a solution to the ntp issue.
All I want is an solution for this to show that Pyarmor can handle changed date/time.

I tried your suggested:

```
pyarmor obfuscate --platform windows.x86_64 --with-license licenses\L1\license.lic --plugin check_ntp_time --output dist/imp64/__init__.py --exact imp64.py
cd dist
python -c "import imp64"
cd ..
pyarmor pack --with-license licenses\L1\license.lic -x " --plugin check_ntp_time" imp64.py

```
Now suddenly I get ERROR
(which I never got before - This is very strange that the same script on the same platform would give errors that's never been there.)

> Traceback (most recent call last):
>   File "<dist\obf\imp64.py>", line 4, in <module>
>   File "<frozen imp64>", line 17, in <module>
>   File "pytransform.py", line 355, in pyarmor_init
>   File "pytransform.py", line 317, in _load_library
> pytransform.PytransformError: Could not find "X:\Temp\dist\imp64\platforms\windows\x86_64\_pytransform.dll"
> [10080] Failed to execute script 'imp64' due to unhandled exception!
>
