### ISSUE TITLE
How can I have `pyarmor pack` to also obfuscate certain dependency libraries?

### ISSUE THREAD

**Issue by namoshizun** [dashingsoft/pyarmor#759]
Hiii,
I've been able to use the `pyarmor pack` to generate the bundled executable for my project. However, there doesn't seem to be instructions on how to **_also obfuscate dependency libraries_** during the package process. The reason being is that some of those dependencies are company assets as well, and I'd like to make sure that their source codes are obfuscated....

**Comment by jondy** [comment]
pyarmor will not do this automatically, you must obfuscate them by some extra options.

**Comment by namoshizun** [comment]
> pyarmor will not do this automatically, you must obfuscate them by some extra options.

Hmmmm could you point me a possible way doing this?

I have tried obfuscating those internal packages **before** building the pyarmored executable. But then Pyinstaller failed to package dependency libraries of those pre-obfuscated internal libraries, which is understandable because the obfuscation made it impossible for Pyinstaller to analyse the source code to guess what'd be also needed.... 

So I guess the more plausible solution is to somehow customize the `pyarmor pack` behaviour, and replace my internal libraries in the bundle with their obfuscated code, **after** Pyinstaller has already added them to the bundle. But still yet, I am unsure of the right way going about this...

**Comment by jondy** [comment]
pyarmor is well documentation, please read the documentation to find the solution.

**Comment by namoshizun** [comment]
> pyarmor is well documentation, please read the documentation to find the solution.

I did have read through the document, a couple of times, with several experimentations done because we are evaluating if it can be used by the company. Still yet there doesn't seem to be clear instructions that may help the question here.. So it'd be great if you could give some pointers here.. By the way, I do believe the Pyarmor is *not that well documented* to include answers to everything

**Comment by namoshizun** [comment]
> It's clear that the documentation could not answer every question directly, but all the features are documented in the man page of each commands. For this example, pyarmor does not provide any feature to obfuscate the dependencies automatically. You need read the documentation of Pyinstaller to find the dependencies and obfuscate them by combining some pyarmor commands. pyarmor also provide a feature `repack` (search `repack` in the documentation), it may helpful to obfuscate the dependencies.

Thx, now that's what I was looking for ---- just a simple confirmation that I do need to customize the build process in Pyinstaller instead of relying on pyarmor, not a condescending tone that "just read the (who-knows-what-it-refers-to) doc"..
