### ISSUE TITLE
导入混淆后的脚本，无法识别该脚本中的函数名

### ISSUE THREAD

**Issue by zone-hai** [dashingsoft/pyarmor#764]
将加密后的脚本作为第三方库导入：
from pygdsencode.c_custom.cell import cell
会出现报错：Cannot find reference 'cell' in 'cell.py'
但是如果忽略这个错误直接运行，可以成功运行。
请问有办法让IDE不报错吗？

**Comment by jondy** [comment]
我也不知道。
