### ISSUE TITLE
Having issues with an error that I cant seem to fix

### ISSUE THREAD

**Issue by GodFather227** [dashingsoft/pyarmor#765]
This is the code that isnt working ```def block_debugger():
    while True:
        time.sleep(3)
        for proc in psutil.process_iter():
            try:
                processName = proc.name()
                if processName == "HTTPDebuggerUI.exe":
                    print("Blacklisted program found! HTTPDebuggerUI.exe")
                    time.sleep(0)
                    os._exit(1)
                if processName == "HTTPDebuggerSvc.exe":
                    print("Blacklisted program found! HTTPDebuggerSvc.exe")
                    time.sleep(0)
                    os._exit(1)
                if processName == "Taskmgr.exe":
                    print("Blacklisted program found! Task Manager")
                    time.sleep(0)
                    os._exit(1)
                if processName == "ProcessHacker.exe":
                    print("Blacklisted program found! ProcessHacker")
                    time.sleep(0)
                    os._exit(1)
                if processName == "Wireshark.exe":
                    print("Blacklisted program found! Wireshark")
                    time.sleep(0)
                    os._exit(1)
                if processName == "OLLYDBG.EXE":
                    print("Blacklisted program found! OLLYDBG")
                    time.sleep(0)
                    os._exit(1)
                if processName == "x64dbg.exe":
                    print("Blacklisted program found! x64dbg")
                    time.sleep(0)
                    os._exit(1)   
                if processName == "x32dbg.exe":
                    print("Blacklisted program found! x32dbg")
                    time.sleep(0)
                    os._exit(1)     
                if processName == "x96dbg.exe":
                    print("Blacklisted program found! x96dbg")
                    time.sleep(0)
                    os._exit(1)
                if processName == "ida64.exe":
                    print("Blacklisted program found! ida64")
                    time.sleep(0)
                    os._exit(1)   
                if processName == "KsDumperClient.exe":
                    print("Blacklisted program found! KsDumperClient")
                    time.sleep(0)
                    os._exit(1) 
                if processName == "KsDumper.exe":
                    print("Blacklisted program found! KsDumper")
                    time.sleep(0)
                    os._exit(1) 
                if processName == "pestudio.exe ":
                    print("Blacklisted program found! pestudio")
                    time.sleep(0)
                    os._exit(1)                                                   
            except:
                pass ```

This is my pyarmor command pyarmor obfuscate --advanced 2 anti.py

I have tried basically everything to get this to work and idk what I have to do

**Comment by jondy** [comment]
Sorry, it's hard to read. And please report the issue according to the template.
