### ISSUE TITLE
No available dynamic library for windows.x86_64 with features ['25']

### ISSUE THREAD

**Issue by XMQZ** [dashingsoft/pyarmor#767]
I am having this issue

      pyarmor obfuscate --advanced 4 bot.py

      INFO     PyArmor Version 7.5.0
      INFO     Python 3.10.5
      INFO     Target platforms: Native
      ERROR    No available dynamic library for windows.x86_64 with features ['25']

**Comment by jondy** [comment]
python3.10 doesn't support `--advanced 4`
