### ISSUE TITLE
ModuleNotFoundError: No module named 'pytransform'

### ISSUE THREAD

**Issue by anonymousDeveloper10** [dashingsoft/pyarmor#768]
Hello, 

Python 3.8

Installed like this : 
`pip install pyarmor`

Ran this command 
`pyarmor obfuscate pulp_functions.py`

The dist directory is correctly created with .py files and the pytransform directory (__init__.py and _pytransform.dll are present).

Error : 
```
 File "c:\www\myapp\dist\pulp_functions.py", line 1, in <module>
    from pytransform import pyarmor_runtime
ModuleNotFoundError: No module named 'pytransform'
```

I don't know what to do.

**Comment by jondy** [comment]
pyarmor is well documented, please first check the chapter `When thing go wrong` to find the solution.
