### ISSUE TITLE
Pyarmor on alpine linux

### ISSUE THREAD

**Issue by BerniEthon** [dashingsoft/pyarmor#769]
I am having a similar issue as in https://github.com/dashingsoft/pyarmor/issues/53

So I tired to download the file that is mentioned as a solution there and replace it with the _pytransform.so file as bellow:
```
 mv _pytransform.so /usr/local/lib/python3.9/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so 
```
but then I get the following error:

```
ERROR    PyArmor does not work with this core library (r5), which reversion < r32, please remove "linux/x86_64" then run command again
```
Is there an explanation how to get it running in alpine linux containers? 

Thanks a lot!

_Originally posted by @BerniEthon in https://github.com/dashingsoft/pyarmor/issues/53#issuecomment-1157359086_

**Comment by jondy** [comment]
please search `alpine` in the issues to find the solution.

**Comment by zgjavi** [comment]
The same happens to me and I could not find any solution yet.
