### ISSUE TITLE
Invalid input packet. Verify rsa key failed 

### ISSUE THREAD

**Issue by lfchuan** [dashingsoft/pyarmor#77]
Hi jondy,
I used pyarmor + pyinstaller to obfuscate and package my python project and sent executable to another user, but the executable runs with an error 'Invalid input packet. Verify rsa key failed ' on the user's PC, it's works fine on my own PC,. I really don't know what's wrong with it and how to fix it even after a lot of google search. hope you can give me some advice.
I absolutely followed the flow in the Docs » How To Pack Obfuscated Scripts >>Work with PyInstaller

**Comment by jondy** [comment]
Maybe it's that the dynamic library `_pytransform.so` doesn't work in the end user's machine.  For example, if your machine is windows/x86, however the end user's machine is windows/x64. So first to be sure the arch of the end user's machine is same as yours. Just check the output of 
```
python -c'import platform
print(platform.machine())'
```
If it's same, try to run executable in another machine with PYTHONDEBUG=y, for example
`PYTHONDEBUG=y main.exe`
A log file "pytranform.log" should be generated in the current path, upload it here.

**Comment by lfchuan** [comment]
Sorry for update late, after a lot of debug,  i found it's not a pyamor issue but an environment issue, the `_ctypes.pyd` and `_elementtree.pyd` in the pyinstaller output folder are not suit for target PC, after replacing these 2 pyd files with the files on target pc, the obfuscated code works fine. But i still don't know the root cause.

**Comment by jondy** [comment]
Maybe something is wrong when passing the value of arguments from python to c by unsuitable `_ctypes.pyd`.
