### ISSUE TITLE
Obfuscated codebase running 10x slower

### ISSUE THREAD

**Issue by priyadarshi9** [dashingsoft/pyarmor#773]
I have obfuscated my python code base with a purchased licence. I obfuscated my code using the below modes:

MODE = 0
obf-mode = 0
wrap-mode = 0

The performance after obfuscation has reduced by 10x. The same code that used to take around 8 seconds is taking ~85 seconds.
The code is running inside an UWSGI app and the platform is linux. Could you please provide a resolution for this?

**Comment by jondy** [comment]
It need some initial time when loading module `pytransform`, if UWSGI load `pytransform` from the begging for each request, it will spend more time. I don't know more about UWSGI app, but if it could load `pytransform` once, it will improve the performance.

**Comment by jondy** [comment]
Do not using `--advanced 4` if the performance is important. And another hint, using feature `0` to obfuscate the script could improve the loading performance. Search `feature` in advanced usage of documentation to know more.
