### ISSUE TITLE
Publishing and installing obfuscated package from pip

### ISSUE THREAD

**Issue by Ankit098** [dashingsoft/pyarmor#774]
Hey, I am trying to publish an obfuscated package to pip and then install it.
I am following this doc: https://pyarmor.readthedocs.io/en/latest/advanced.html#distributing-obfuscated-package-with-pip

I have kept a similar project structure to the one mentioned in the docs above, but on the step:
`pyarmor runtime -O dist/share --enable-suffix 1`
it does not generate a unique named folder (like `pytransform_vax_xxxxxx`). It generated a structure as follows:

```
.
|____ share
| |____ pytransform
| | |____ __init__.py
| | |____ _pytransform.dylib
| |____ pytransform_bootstrap.py
| |____ pytransform_protection.py
```

included it in setup.py as:
```
data_files=[('pytransform', ['dist/share/pytransform/__init__.py',
                 'dist/share/pytransform/_pytransform.dylib',
                                         'dist/share/pytransform_bootstrap.py',
                                         'dist/share/pytransform_protection.py'])]
```
And then ran `pythom -m build` using the above setup.py.

The above files which are required to de-obfuscate are not available to the pip package on download. I found this in the docs: https://pyarmor.readthedocs.io/en/latest/questions.html#python-import-system, since I had included the files in `data_files` field it should be available after installing from pip.. could you help with understanding what I am missing here. Thanks!

**Comment by jondy** [comment]
The trial version could not generate unique package.

**Comment by Ankit098** [comment]
So is it not possible to publish an obfuscated package to pip with the trial version of pyarmor?
