### ISSUE TITLE
encrypt string values in python

### ISSUE THREAD

**Issue by deeplearnerali** [dashingsoft/pyarmor#775]
**Is your feature request related to a problem? Please describe.**
When decompyling with uncompyle or similar tools on string values and API strings can be seen in pyarmor

**Describe the solution you'd like**
must be a way to encrypt anything between ' " ' and ' " ' and then decrypt during run time

**Comment by jondy** [comment]
pyarmor will add the feature to obfuscate the string constant in the expression, this feature may be released in a few months.

But all the other string, for example, the function name, the variable name, will leave as it is. Obfuscating them may cause unexpected errors.

**Comment by lolhesap** [comment]
that would be really nice

**Comment by jondy** [comment]
Here it's a pre-release v7.6.0 for this feature, refer to
https://pyarmor.readthedocs.io/en/latest/change-logs.html#dev

**Comment by lolhesap** [comment]
> Here it's a pre-release v7.6.0 for this feature, refer to https://pyarmor.readthedocs.io/en/latest/change-logs.html#dev
thanks for for quick update,  also can be added rename classes, functions, variables ?  i know this may break some scripts, but maybe it can be added as an optional in the future?

**Comment by jondy** [comment]
I'll take this into account. Just as you said, it may break some scripts.

**Comment by jondy** [comment]
Renaming function/class has been implemented in Pyarmor 8.0 by RFT mode.
