### ISSUE TITLE
ERROR    The option "-n" could not be used as the extra options

### ISSUE THREAD

**Issue by emoto-yasushi** [dashingsoft/pyarmor#776]
I ran the following command and got an error.

`pyarmor pack -e " --onedir --noconsole --icon icon.ico -n MyAppName" main.py
`
The error message is this,

`ERROR    The option "-n" could not be used as the extra options
`
It worked in previous versions but not in version 7.5.1.

I do not understand which version of PyArmor it worked on as my previous PC is broken.
How can I specify my app name?

**Comment by jondy** [comment]
Please check the man page of command `pack`
