### ISSUE TITLE
离线环境下加密失败

### ISSUE THREAD

**Issue by wyjksyjs** [dashingsoft/pyarmor#778]
![image](https://user-images.githubusercontent.com/40057436/176816501-4bed1791-77ba-457f-a5c3-4ddbc2f13a19.png)

**Comment by jondy** [comment]
使用的是不正确的动态库，请参考在线文档 支持的平台，里面有关于如何人工下载动态库的说明。

**Comment by wyjksyjs** [comment]
我是从外面好的环境下好并且验证可以后，拷贝进去的。同一台机器下python3.7可以，3.8、3.9都不行

**Comment by wyjksyjs** [comment]
按照你的方法我要下载r50.4的动态库从哪里下呢，pyarmor-core只更新到41.5

**Comment by jondy** [comment]
在联网的情况下，PyArmor 可以自动下载和配置需要的动态库，在不联网的机器上则需要把 预先下载的动态库放置在相应的目录下面。请通过命令 download 在联网的机子下 载，默认情况下，下载的所有文件存放在 ~/.pyarmor/platforms 下面，下载好之后把整 个目录拷贝到目标机器。

以上是文档的内容

**Comment by wyjksyjs** [comment]
我就是整个拷贝进去的，不行

**Comment by wyjksyjs** [comment]
在有网络的机器上都可以正常运行，没有网络的就不行。
![image](https://user-images.githubusercontent.com/40057436/176871247-4717948e-5101-4226-9be3-b4d6906a4f6b.png)
这是有网的机器
![image](https://user-images.githubusercontent.com/40057436/176871296-b1968fda-66d6-4ece-848f-297b29d41f67.png)
这是没网的机器

**Comment by jondy** [comment]
请仔细比较两者的输出日志和参考文档进行解决，使用方法上的问题不提供更多支持。

**Comment by jondy** [comment]
请仔细比较两者的输出日志和参考文档进行解决，使用方法上的问题不提供更多支持。
