### ISSUE TITLE
离线环境下spp模式无法运行

### ISSUE THREAD

**Issue by wyjksyjs** [dashingsoft/pyarmor#779]
![image](https://user-images.githubusercontent.com/40057436/176817193-a6e995c5-a73e-4c6b-b85b-55a4bec50e82.png)
![image](https://user-images.githubusercontent.com/40057436/176817281-f7f190cc-c9fb-49c4-9c7e-ff76522f44d8.png)
已经有sppmode.so文件了，为啥还是不行

**Comment by jondy** [comment]
sppmode 加密过程需要在线验证许可证的。
