### ISSUE TITLE
Obfuscated code fails to run with Python 3.6 and 3.7

### ISSUE THREAD

**Issue by bbarn3y** [dashingsoft/pyarmor#78]
We have a use case where the obfuscated code has to be run in a dockerized ubuntu environment where we don't have control over the Python version. The Python version installed in this environment is Python 3.6.
We do the obfuscation in a different machine and create a docker image that contains this obfuscated model. We tried multiple environments to do the obfuscation on, namely ubuntu 14.04, and Windows Subsystem for Linux under Windows 10 (ubuntu 18.04). The issue was the same in both cases.

After we try to run the code in this dockerized environment we get the following error:

```
XXX lineno: 1, opcode: 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "..../dist/MyModel.py", line 3, in <module>
    __pyarmor__(__name__, __file__, b'\xec\x50.....', 1)
  File "<frozen MyModel>", line 1, in <module>
SystemError: unknown opcode
```

We managed to reproduce this issue on our local PCs as well. It doesn't seem to matter what Python version we use to obfuscate the code, only the Python version we use to run it.
We tested this with version 3.4, 3.5, 3.6 and 3.7. The same error was given when running the obfuscated code with Python 3.6 and 3.7, however, it worked fine with 3.4 and 3.5.

Any idea what could cause this issue? Does pyarmor support Python 3.6/3.7?

**Comment by jondy** [comment]
If you want to run obfuscated scripts by Python3.6 and later, you must obfuscated the scripts by Python3.6 and later. 

Because Python3.6 introduces word size instruction, it's totally different from Python3.5 and before.

**Comment by jondy** [comment]
Refer to https://pyarmor.readthedocs.io/en/latest/differences.html#the-differences-of-obfuscated-scripts

**Comment by bbarn3y** [comment]
First off, thanks for your answer!

I guess what I'm not seeing right now, is the way I could tell pyarmor which python version to use during obfuscation. I have 5 different python versions installed. In my current terminal I set an alias to point to python version 3.6.7, so if I execute the following command:

`python --version`

the result is: Python 3.6.7

I tried playing around with this, obfuscated a simple model that works on both Python 2 and 3. After obfuscation, it only works with Python 2, not 3 (_Pytransform Error: Marshal loads failed when running dist/Run.py_), which probably means that pyarmor still uses Python 2.

What's the most surefire way to tell pyarmor which Python version to use?

I went through the documentation, couldn't find anything about this, but sorry if I missed something.

**Comment by jondy** [comment]
It seems you install pyarmor by pip2, so the scripts are obfuscated by python2.7, and only works for python2.
 
If you want to obfuscate the scripts with other python version, first find where pyarmor installed. For example
```
find /usr/local/lib -name pyarmor.py
```
Generally it should be in the `/usr/local/lib/python2.7/dist-packages/pyarmor` in most of linux.

Then run pyarmor as the following way:
```
/usr/bin/python3.6 /usr/local/lib/python2.7/dist-packages/pyarmor/pyarmor.py
```
Or you can install pyarmor by pip3, but the command `pyarmor` which is installed by pip2 may be overwritten.

**Comment by bbarn3y** [comment]
Thanks, running explicitly with the desired Python version solved this issue.
