### ISSUE TITLE
RuntimeError: Check restrict mode of module failed

### ISSUE THREAD

**Issue by mohammadmoazum** [dashingsoft/pyarmor#781]
I am trying to obfuscate the two folders having python files. folder  2 is dependent on folder  1 . Folder 2 contains two shell scripts that I want to run, the shell script run the two different python files present in folder 2. The main aim of the shell scripts is to copy data from one folder to another. I have written an obfuscation.sh  to obfuscate the scripts. I have tried every restrict mode but it is showing the same error in the log folder after trying to run the shell scripts. Please help me resolve this issue. I am paid pyarmor user.
Please help me resolve this issue ASAP

The error that I am getting in the logs 
```
**Traceback (most recent call last):
  File "<copy_f.py>", line 3, in <module>
RuntimeError: Check restrict mode of module failed**
```

 ./obfuscation.sh
INFO     PyArmor Version 7.4.3
INFO     Python 3.7.11
INFO     Generate licenses with capsule /home/mo/.pyarmor/.pyarmor_capsule.zip ...
INFO     Make output path of licenses: licenses
INFO     The license file is generated in restrict mode
INFO     The license file is generated in period mode disabled
INFO     Make path: licenses/zhengshu

INFO     Write license file: licenses/zhengshu/license.lic
INFO     Write information to licenses/zhengshu/license.lic.txt
INFO     Generate 1 licenses OK.
INFO     PyArmor Version 7.4.3
INFO     Python 3.7.11
INFO     Target platforms: Native
INFO     Source path is "/mnt/c/Users/moazum.wani/Desktop/revenue-ai/revenue-ai-backend/Product"
INFO     Entry scripts are []
INFO     Use cached capsule /home/moazum/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Save obfuscated scripts to "dist/revenue-ai-backend/Product"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 3
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled

last line on  the command line
Obfuscate 3 scripts OK.

**Comment by jondy** [comment]
pyarmor is well documentation, please first read the related sections to understand restrict mode, https://pyarmor.readthedocs.io/en/latest/mode.html#restrict-mode

**Comment by jondy** [comment]
pyarmor is well documentation, please first read the related sections to understand restrict mode, https://pyarmor.readthedocs.io/en/latest/mode.html#restrict-mode

**Comment by mohammadmoazum** [comment]
@jondy  I have understood the restrict mode, but still, the code is not working.

**Comment by jondy** [comment]
Do you use `--restrict 0`? Note that if using outer license, the license must be generated with `--restrict 0` too.
