### ISSUE TITLE
Failing to load _pytransform.so on Kivy (python-for-android / buildozer) android.aarch64

### ISSUE THREAD

**Issue by bc31164b-cfd5-4a63-8144-875100622b2d** [dashingsoft/pyarmor#783]
Version: vx.x.x

Repro Steps:
    - obfuscate simple hello world program with:
    - `pyarmor obfuscate --platform android.aarch64 --with-license licenses/calc/license.lic --recursive main.py`
    - run buildozer with dist as source directory
    - load APK
    - *crash*

Expected Result:

APK should load

Actual Result:

Fails to load .so

Error Message:

```
2022-07-06 08:58:52.499 16508-16666/? I/python: PYTRANSFORM PLATFORM: linux
2022-07-06 08:58:52.499 16508-16666/? I/python: PYTRANSFORM ABSPATH: /data/user/0/com.calc.calc/files/app/pytransform/_pytransform.so
2022-07-06 08:58:52.499 16508-16666/? I/python: PYTRANSFORM platid: /data/user/0/com.calc.calc/files/app/pytransform/_pytransform.so
2022-07-06 08:58:52.755 16508-16666/? I/python: Traceback (most recent call last):
2022-07-06 08:58:52.755 16508-16666/? I/python:   File "/home/ubuntu/calc/.buildozer/android/app/main.py", line 2, in <module>
2022-07-06 08:58:52.755 16508-16666/? I/python:   File "/home/ubuntu/calc/.buildozer/android/app/pytransform/__init__.py", line 375, in pyarmor_runtime
2022-07-06 08:58:52.755 16508-16666/? I/python:   File "/home/ubuntu/calc/.buildozer/android/app/pytransform/__init__.py", line 368, in pyarmor_init
2022-07-06 08:58:52.755 16508-16666/? I/python:   File "/home/ubuntu/calc/.buildozer/android/app/pytransform/__init__.py", line 73, in wrap
2022-07-06 08:58:52.755 16508-16666/? I/python:   File "/home/ubuntu/calc/.buildozer/android/app/pytransform/__init__.py", line 94, in init_pytransform
2022-07-06 08:58:52.755 16508-16666/? I/python: pytransform.PytransformError: Initialize python wrapper failed (2)
2022-07-06 08:58:52.755 16508-16666/? I/python: Python for android ended.
2022-07-06 08:58:53.109 16508-16641/? W/System.err: java.lang.NoSuchMethodError: no static method "Lorg/apache/harmony/dalvik/ddmc/DdmVmInternal;.threadNotify(Z)V"
```

Further Info:

Seems able to load the .so file, however fails init of wrapper. This doesn't seem to hit any exception:

```
    try:
        m = cdll.LoadLibrary(filename)
    except Exception as e:
        print("PYTRANSFORM Load %s failed:\n%s" % (filename, e))
        raise
```

So it seems library loads fine...

but the problem comes from here:

```
    if (ret & 0xF000) == 0x1000:
        raise PytransformError("Initialize python wrapper failed (%d)" % (ret & 0xFFF))
```

NOW. There are two ways (that i know of) for including .so files in an APK. One is for it to be bundled into the assets (private.tar in the APK). In this case pytransform/__init__.py are in the same directory.

Another way is to create a recipe in python-for-android. This bundles the python code into libpybundle.so, which is actually a tar ball. The tarball contains `modules` which looks like cpython modules, `site-packages` and `stdlib.zip` with standard lib python .pyc files.

I came across some old issues from 2019 where you said _pytransform.so need to be installed properly in the lib directory (implies writing a python-for-android recipe) however it seems the .so loads fine (just that the wrapper doesn't bind).

I've come across many instances of developers who were able to bundle .so files in their assets, so again that points of Android supporting that no problem.

Do you think it could be due to an NDK / SDK version mismatch between my project and the settings you used to build the _pytransform.so ?

I'm writing a [recipe](https://github.com/bc31164b-cfd5-4a63-8144-875100622b2d/python-for-android/blob/master/pythonforandroid/recipes/pyarmortransform/__init__.py) anyway in case this is the problem, but some thoughts, pointers and help would be great.

FWIW we've just started with development on Android, and it's such a great and popular platform, seems like a shame to ignore some docs on making this process easy.

If the answer is the recipe, i'll make sure to get it included in the python-for-android module to make this easier for everyone going forward.

Thanks.

**Comment by bc31164b-cfd5-4a63-8144-875100622b2d** [comment]
Follow up: i'm now installing the lib correctly, as well as the __init__.py for pytransform, but still no luck.

**Comment by jondy** [comment]
First use latest version of pyarmor, note that the trial version of pyarmor could not get the latest version of `_pytransform.so`

Use option `-d` to run the obfuscated script, it will generate error log `pytransform.log`, check the content of this log to find more information
```
python -d dist/main.py
cat pytransform.log
```

**Comment by bc31164b-cfd5-4a63-8144-875100622b2d** [comment]
Thanks. By the way i managed to obfuscate and run using Termux. So that's a big sign of hope! Will continue investigating.

**Comment by bc31164b-cfd5-4a63-8144-875100622b2d** [comment]
I gave up trying to deploy my obfuscated app, and instead I tried running pyarmor in the target app:

![image](https://user-images.githubusercontent.com/24770400/177933320-db5b0c68-1fda-45ca-8121-b2f46bf180ca.png)

Sadly even running inside the target environment, installing the license, and trying to run pyarmor it fails to load the wrapper.

So the environment must be incompatible with the .so for some reason. To be clear it's built with buildozer, python is loaded as a library, and the environment uses SDL2.

**Comment by jondy** [comment]
pyarmor need CPython APIs, if there is no standard CPython share library in the environment, it will be failed to initialize.

**Comment by bc31164b-cfd5-4a63-8144-875100622b2d** [comment]
I'm pretty sure they're all there. I can run arbitrary Python in my target app. Let me know if there are any commands i can run to further diagnose the issue.

![telegram-cloud-photo-size-5-6217700257953853644-y](https://user-images.githubusercontent.com/24770400/178085900-f92dad99-9328-45d3-a43a-f824be681d1a.jpg)
![telegram-cloud-photo-size-5-6217700257953853645-y](https://user-images.githubusercontent.com/24770400/178085912-2567b589-692a-445b-8dae-f05bb18347a2.jpg)

**Comment by bc31164b-cfd5-4a63-8144-875100622b2d** [comment]
In the environment, if I do something like this: 

```
import os
from ctypes import cdll
os.environ["PATH"] += ':../app/_python_bundle/modules'
cdll.LoadLibrary('cmath.cpython-38.so')
```

It works and the .so file loads without any complaints. My understanding is that cdll.LoadLibrary() calls the system's `dlopen(3)` which clearly isn't aware that the CPython libs are inside `':../app/_python_bundle/modules'`. But setting the 'PATH' environment variable seems to solve the problem of not finding these libraries.

So I'm still not clear why the _pytransform.so library isn't loading correctly, given that the PATH env var is properly set.

**Comment by bc31164b-cfd5-4a63-8144-875100622b2d** [comment]
P.S

In Termux if I do: `ldd _pytransform.so` I see:

```
libdl.so
libc.so
```

But that's it. What libs is it trying to load?

**Comment by jondy** [comment]
It will get CPython api by `dlsym`, it can be verified by the following python code:
```python
from ctypes import CFUNCTYPE, cdll, pythonapi, string_at, c_void_p, c_char_p

def query_capi(name):
    prototype = CFUNCTYPE(c_void_p, c_void_p, c_char_p)
    dlsym = prototype(('dlsym', cdll.LoadLibrary(None)))

    print('Got api %s at %s' % (name, dlsym(pythonapi._handle, name))

query_capi(b'PyBytes_AsString')
```

**Comment by bc31164b-cfd5-4a63-8144-875100622b2d** [comment]
I got 'CFUNCTYPE' is not defined (i'm not sure why, it's declared in the scope). So edited the code and ran:

```
from ctypes import CFUNCTYPE, cdll, pythonapi, string_at, c_void_p, c_char_p
name = b'PyBytes_AsString'
prototype = CFUNCTYPE(c_void_p, c_void_p, c_char_p)
dlsym = prototype(('dlsym', cdll.LoadLibrary(None)))
print('Got api %s at %s' % (name, dlsym(pythonapi._handle, name)))
```

Result:

```
Got api b'PyBytes_AsString' at None
```

 I guess that's supposed to return a pointer to memory. I'll speak with the python for android devs.

**Comment by bc31164b-cfd5-4a63-8144-875100622b2d** [comment]
From the kivy discord:

"""
you need to dlopen libpython.so with absolute path not proc/self
ctypes and cffi works perfectly on android since 3.7
and if the vendor .so lacks reference to libpython.so just add it with patchelf
"""

**Comment by jondy** [comment]
Since dlsym could not get CPython api, one possible reason is that `libpython.so` is not dlopened with RTLD_GLOBAL
https://docs.python.org/3/library/sys.html#sys.setdlopenflags

So try to add the following line in the `pytransform.py` before load library
```python
    sys.setdlopenflags(os.RTLD_GLOBAL)
```

**Comment by pmp-p** [comment]
sorry to intrude, but _pytransform.so lacks reference to libpython3.8.so namespace
a quick fix is `patchelf --add-needed libpython3.8.so ~/.pyarmor/platforms/android/aarch64/0/_pytransform.so` with recent patchelf from https://github.com/NixOS/patchelf/releases

**Comment by jondy** [comment]
`_pytransform.so` works for both python2 and 3, so it could not be linked to libpythonXY.so staticly. But query necessary api  by itself.

I think `pythonapi._handle` should work if RTLD_GLOBAL flag is set when loading libpython8.so, but it may not work if this flag is not set.

Anyway, verify it by the following python code
```python
from ctypes import CFUNCTYPE, cdll, pythonapi, c_void_p, c_char_p, c_int

libc = cdll.LoadLibrary(None)

libpython = b'/path/to/libpythonXY.so'
prototype = CFUNCTYPE(c_void_p, c_char_p, c_int)
dlopen = prototype(('dlopen', libc))
handle = dlopen(libpython, 0)

# handle = pythonapi._handle,
name = b'PyBytes_AsString'
prototype = CFUNCTYPE(c_void_p, c_void_p, c_char_p)
dlsym = prototype(('dlsym', libc))
print('Got api %s at %s' % (name, dlsym(handle, name)))
```

**Comment by pmp-p** [comment]
also your 32 bits armv7  _pytransform.so is using an ndk api > 19,   it's looking for `rand` instead of `lrand48`

**Comment by jondy** [comment]
How about the last script which uses `dlopen` to load libpython by itself? Could it get the address of api `PyBytes_AsString`?

I'm out of office, and could not visit the build machine. I forget which ndk api is used, the build scripts hasn't been changed for a long time, but I could rebuild it with other minSdkVersion when I'm back about one week later.

**Comment by jondy** [comment]
I checked the build script, it uses gcc in ndk r20 to build `_pytransform.so` directly, and I could not find any option to set `minSdkVersion` 
```
/path/to/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi-gcc --help 
```

Do you have any idea to set minSdkVersion by command line option for `armv7a-linux-androideabi-gcc`?

**Comment by pmp-p** [comment]
have a look here https://github.com/pmp-p/pydk/blob/master/pydk-all.sh#L579

or just start a pydk build hit cltr+c and then use env shell 
shell.arm64-v8a.sh shell.armeabi-v7a.sh shell.x86_64.sh shell.x86.sh to do run the build,  it may work out of the box for overriding values in classic ndk builds

**Comment by jondy** [comment]
It's great! But it bases on cmake to build app, `_pytransform.so` is built by `armv7a-linux-androideabi-gcc` directly.

It seems there is `armv7a-linux-androideabi19-clang` which should use api 19 in the ndk-r20.
``` 
/path/to/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi19-clang 
```

Or define macro `-D __ANDROID_API__=19` in the CFLAGS

I'll try the latter

**Comment by pmp-p** [comment]
for cmake it's "acmake" in the venv shell it will add the android toolchain with those parameter https://github.com/pmp-p/pydk/blob/9aeec40679e26c1fac74a6bd4c9db985a9363258/pydk-all.sh#L684. I think you'd need those 
```
set(ANDROID_NATIVE_API_LEVEL ${API})
set(ANDROID_PLATFORM_LEVEL ${API})
set(ANDROID_PLATFORM "android-${API}")
set(ANDROID_ARCH ${ABI_NAME})
set(ANDROID_ABI ${ABI_NAME})
```

**Comment by jondy** [comment]
There is a temporary release v7.6.0 which uses Android API 19 to build android.armv7
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-7.6.0.zip
```
Refer to
