### ISSUE TITLE
OSError: exception: privileged instruction怎么解决

### ISSUE THREAD

**Issue by sanzhangzui** [dashingsoft/pyarmor#785]
你好 我使用 pyarmor  -b obfuscate --advanced 2 main.py可以正常加密
![image](https://user-images.githubusercontent.com/34833210/177738057-34d38087-9801-4b24-97be-0707ba0fa938.png)
使用pyarmor  -b obfuscate --advanced 4 main.py就会报这个错误
![image](https://user-images.githubusercontent.com/34833210/177737410-746e7a6c-f0b8-4195-a634-e0b90bb75342.png)
尝试了在函数开头加[None, None]但依然会报错
![image](https://user-images.githubusercontent.com/34833210/177737662-2576b671-0721-4d3a-a7da-1b9a121d75ff.png)
这是1212行的代码
![image](https://user-images.githubusercontent.com/34833210/177743863-00ed9b7c-e161-42a5-9b3a-b8d754ddf551.png)

**Comment by jondy** [comment]
请尝试使用最新的 v7.5.1, 如果还存在问题，请提供详细的日志

**Comment by sanzhangzui** [comment]
升级了之后还是没用，错误跟这个一模一样
![image](https://user-images.githubusercontent.com/34833210/178100685-76596a36-23b2-4116-9e53-909b00c27c4b.png)

**Comment by jondy** [comment]
现在在外地，没有 Windows 环境，等回到办公室之后我再看看（大约一周之后），另外请提供详细的日志，包含执行的命令和所有相关的日志，使用调试选项 `pyarmor -d obfuscate ...`，不要使用截图，拷贝所有的文本日志。

**Comment by jondy** [comment]
本地测试了一下可以正常加密。

如果是离线环境，请首先确认在线环境是否可以正常加密。如果还有问题，请提供详细的操作步骤和详细的日志。
