### ISSUE TITLE
pytransform.pyd报Win32/Pearfoos.B!ml病毒

### ISSUE THREAD

**Issue by derekhe** [dashingsoft/pyarmor#786]
我使用以下命令加密我的代码

```
pyarmor obfuscate server.py --advanced 4 --restrict=4 --with-license outer -O ../dist/
pyarmor obfuscate licence_check.py --advanced 4 --restrict=4 --with-license outer -O ../dist
```

PyArmor Version 7.5.0

在某些客户的msdefender下会报：Win32/Pearfoos.B!ml

https://github.com/derekhe/msfs2020-map-enhancement/issues/197

请帮忙看下是什么问题：[pytransform.zip](https://github.com/dashingsoft/pyarmor/files/9062764/pytransform.zip)

**Comment by jondy** [comment]
在  msdefender 中设置例外，`--advanced 4` 使用了 Themida 进行保护，可能被误认为是病毒。
