### ISSUE TITLE
Cross platform license in 'paid' version

### ISSUE THREAD

**Issue by scottwsides** [dashingsoft/pyarmor#787]
I just want to make sure that if I obfuscate code with 'registered' pyarmor on windows... that a license generated on windows will work

**Comment by jondy** [comment]
The license generated by command `obfuscate` and `licenses` is platform-independent.

**Comment by scottwsides** [comment]
Thanks for the quick response! So I guess this is something else that I must be screwing up in my build workflow. Just to be clear... this is the 'paid' version and I'm using the --outer option when obfuscating. I thought I made it all work cross-platform with the free version... so I wanted to double-check that there wasn't something fundamentally different about the paid one.
