### ISSUE TITLE
wrong output identify Serial number of  harddisk

### ISSUE THREAD

**Issue by joelurtubia** [dashingsoft/pyarmor#79]
hello , i need your help please....
when i use this command appears the serial number but with a blank space on final of serial...

[root@xxx ~]# pyarmor hdinfo
INFO     PyArmor Trial Version 5.3.8
Serial number of first harddisk: "50026B723501BD0F    "
Mac address: "00:ec:ac:cf:44:55"
Ip address: "190.13.1xx.233"

Domain name: "(none)"

and when i try to create a license , appears an error relationship with this hdinfo, but if i will created the same license with  blank space it's working without any problem

also i check the linux command :

sudo hdparm -I /dev/sda

appears the correctly serial number

[root@Sonda ~]# sudo hdparm -I /dev/sda

/dev/sda:

ATA device, with non-removable media
        Model Number:       KINGSTON SKC300S37A240G                 
        Serial Number:      50026B723501BD0F    
        Firmware Revision:  507ABBF0
        Transport:          Serial, ATA8-AST, SATA 1.0a, SATA II Extensions, SATA Rev 2.5, SATA Rev 2.6, SATA Rev 3.0
Standards:
        Used: unknown (minor revision code 0x0110) 
        Supported: 8 7 6 5 
        Likely used: 8
Configuration:
        Logical         max     current
        cylinders       16383   16383
        heads           16      16
        sectors/track   63      63
       
please can you help me to fix it?

this is the version of SO and python

CentOS Linux release 7.6.1810 (Core) 
[root@Sonda ~]# 
[root@Sonda ~]# python
Python 2.7.5 (default, Oct 30 2018, 23:45:53) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 

thanks for your advice

**Comment by jondy** [comment]
Fixed it in v5.3.9, the leading and trailing whitespace are removed, please upgrade the latest version.

**Comment by joelurtubia** [comment]
Great !!! its working 

[root@Sonda ~]# pyarmor hdinfo
INFO     PyArmor Trial Version 5.3.9
Serial number of first harddisk: "50026B723501BD0F"
Mac address: "00:ec:ac:cf:44:55"
Ip address: "190.13.xxx.23x"
Domain name: "(none)"
[root@Sonda ~]# 

very faster ...thanks for your help!!

**Comment by joelurtubia** [comment]
Hello Jondy...Sorry...but I need to reponed again, I've tested the latest version and  now appears without blank space

#########################################################################

[root@Sonda ~]# pyarmor hdinfo
INFO     PyArmor Trial Version 5.3.9
Serial number of first harddisk: "50026B723501BD0F"
Mac address: "00:ec:ac:cf:44:55"
Ip address: "190.13.1xx.xxx"


#########################################################################
but when i try to test it, doesn't work as I expect...

Domain name: "(none)"
[root@Sonda ~]# 
[root@Sonda ~]# 
[root@Sonda ~]# 
[root@Sonda ~]# 
[root@Sonda ~]# pyarmor licenses --expired 2019-05-25 --bind-disk "50026B723501BD0F" code-003
INFO     PyArmor Trial Version 5.3.9

INFO     Generate licenses with capsule /root/.pyarmor_capsule.zip ...
INFO     Output path of licenses: licenses
INFO     The license file generated is in restrict mode
INFO     Generate license: "Expired:2019-05-25*HARDDISK:50026B723501BD0F*CODE:code-003"
INFO     Write license file: licenses/code-003/license.lic
INFO     Write information to licenses/code-003/license.lic.txt
INFO     Generate 1 licenses OK.
[root@Sonda ~]# cp licenses/code-003/license.lic /home/sonda/daemon/classes/
cp: overwrite â€˜/home/sonda/daemon/classes/license.licâ€™? y
[root@Sonda ~]# /usr/bin/python /home/sonda/daemon/daemonPmt.py restart
License is not for this machine

#########################################################################
but when i use only date expired... it's works!!
###################

[root@Sonda ~]# pyarmor licenses --expired 2019-05-25  code-003
INFO     PyArmor Trial Version 5.3.9

INFO     Generate licenses with capsule /root/.pyarmor_capsule.zip ...
INFO     Output path of licenses: licenses
INFO     The license file generated is in restrict mode
INFO     Generate license: "Expired:2019-05-25*CODE:code-003"
INFO     Write license file: licenses/code-003/license.lic
INFO     Write information to licenses/code-003/license.lic.txt
INFO     Generate 1 licenses OK.
[root@Sonda ~]# cp licenses/code-003/license.lic /home/sonda/daemon/classes/
cp: overwrite â€˜/home/sonda/daemon/classes/license.licâ€™? y
[root@Sonda ~]# /usr/bin/python /home/sonda
#########################################################################
if i use the serial ...... it's doesn't works
###################

[root@Sonda ~]# pyarmor licenses --bind-disk "50026B723501BD0F" code-003
INFO     PyArmor Trial Version 5.3.9

INFO     Generate licenses with capsule /root/.pyarmor_capsule.zip ...
INFO     Output path of licenses: licenses
INFO     The license file generated is in restrict mode
INFO     Generate license: *HARDDISK:50026B723501BD0F*CODE:code-003
INFO     Write license file: licenses/code-003/license.lic
INFO     Write information to licenses/code-003/license.lic.txt
INFO     Generate 1 licenses OK.
[root@Sonda ~]# cp licenses/code-003/license.lic /home/sonda/daemon/classes/
cp: overwrite â€˜/home/sonda/daemon/classes/license.licâ€™? y
[root@Sonda ~]# /usr/bin/python /home/sonda/daemon/daemonPmt.py restart
License is not for this machine


#########################################################################

PD: also what mean :
code-001
code-002
code-003

PD2: this kind of obfuscate not affect the performance of script running??,
thanks for your help!!!/daemon/daemonPmt.py restart

**Comment by jondy** [comment]
Just obfuscate the scripts by v5.3.9 again, then try the new license. Because the scripts obfuscated by old version couldn't get the right serial number.

**Comment by joelurtubia** [comment]
it's works...great..., I'll buy it, very good code....., sorry please latest question please

1-  what mean :
code-001
code-002
code-003

2 - this kind of obfuscate not affect the performance of script running??,

3- how can I include the errors code  into my script for send a message in my own logs about the license, something like this:

- you have a 5 days for end of license.
- you canot install this software into this machine.
- etc.

thanks for your help!!

**Comment by jondy** [comment]
1. The code could be any identify string, it could be retrieved from the obfuscated scripts by `get_license_info` , also refer to the answer of question 3

2. About performance, refer to 
https://pyarmor.readthedocs.io/en/latest/performance.html

3. Here are some examples
https://pyarmor.readthedocs.io/en/latest/pytransform.html

**Comment by joelurtubia** [comment]
great..thanks for your help!!!
