### ISSUE TITLE
Python 3.10 usage with a trial license

### ISSUE THREAD

**Issue by dvkovner** [dashingsoft/pyarmor#794]
Hello. I'm trying to obfuscate a program which is written in Python 3.10 using the next command:

pyarmor obfuscate --src <path1> --output <path2> --bootstrap 2 --platform linux.x86_64.0 __init__.py __main__.py

During the obfuscation process the next log messages appear:
INFO     Create pyarmor home path: /home/AzDevOps/.pyarmor
INFO     Create trial license file: /home/AzDevOps/.pyarmor/license.lic
INFO     Generating public capsule ...
INFO     PyArmor Trial Version 7.5.1
INFO     Python 3.10.1
INFO     Target platforms: ['linux.x86_64.0']
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/index.json
INFO     Create platform path: /home/AzDevOps/.pyarmor/platforms
INFO     Write cached platform list file /home/AzDevOps/.pyarmor/platforms/index.json
ERROR    The trial version pyarmor could not work, please use pyarmor < v7.0.0. For example, install latest work version by this command: pip install pyarmor=6.8.1

Do I understand right that there is no opportunity at the moment to test pyarmor with Python 3.10 using trial license and I must buy a commercial one?

**Comment by jondy** [comment]
Do not use `--platform linux.x86_64.0`, just run `pyarmor obfuscate foo.py`, it should work in native platform `linux.x86_64` to test Python 3.10
