### ISSUE TITLE
generate obfuscated scripts to other platform

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#796]
Hello maintainers, actually i have one question about migrate from windows to macOS (it's not m1)
I am pretending to generate obfuscated script with --no-runtime flag and --platform=windows.x86_x64 flag. Previously I tried it using Linux, but i had no success. Will I have problems generating obfuscated scripts with macOS to distribute for Windows OS?

**Comment by jondy** [comment]
Please read the documentation by searching cross platform to fix this problem, there is a lot of example about cross platform.
