### ISSUE TITLE
Invalid license file when the license is generated on a x86_64 machine and uploaded to arm based machine

### ISSUE THREAD

**Issue by pikonek** [dashingsoft/pyarmor#799]
So I have a system that supports x86_64 and ARM. I obfuscated my script using an outer license. I generated a license file on my x86_64 machine and uploaded it to my ARM-based machine, but I got an error Check license failed, Invalid input packet.

Does the generation of a license, platform specific?

Thank you.

**Comment by jondy** [comment]
The generated license is platform independent. Make sure the same pyarmor version and same PyArmor License  is used in both of 2 platforms.

**Comment by pikonek** [comment]
Yes I have same pyarmor on x86-64 and arm64 hardware, but when i generate an outer license on my x86-64 machine and copy the generated outer license to my arm64 machine it fails, says Invalid License, invalid packet.

**Comment by pikonek** [comment]
Or because I run pyarmor register <Regcode> on both machine?

**Comment by jondy** [comment]
Check the output log carefully to find the problem.

**Comment by pikonek** [comment]
Here is the log:

Check license failed, Invalid input packet.

**Comment by pikonek** [comment]
That's all the log, after using the license generated from my laptop
It's a hassle when you support two different architectures and you need to generate both licenses in each architecture.

**Comment by jondy** [comment]
I'm sure the license file generated by pyarmor is platform-independent.

**Comment by jondy** [comment]
Make sure arm64 scripts are obfuscated by feature 3. I said checking the log means the output log of pyarmor command. It will show which feature dll is used and more other informations. About the feature of each platform, please refer to the online document in chapter `support platforms`

**Comment by pikonek** [comment]
Here is the logs:

INFO     PyArmor Version 7.5.1
INFO     Python 3.6.9
INFO     Target platforms: Native
INFO     Source path is "/root/test"
INFO     Entry scripts are ['test.py']
INFO     Use cached capsule /root/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Use outer license file
INFO     Copying /root/.pyarmor/platforms/linux/aarch64/3/_pytransform.so
INFO     Patch library dist/pytransform/_pytransform.so
INFO     Patch library file OK
INFO     Copying /usr/local/lib/python3.6/dist-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO     	test.py -> dist/test.py
INFO     Insert bootstrap code to entry script dist/test.py
INFO     Obfuscate 1 scripts OK.

**Comment by pikonek** [comment]
This is the log when I generate the license on arm64

INFO     PyArmor Version 7.5.1
INFO     Python 3.6.9
INFO     Generate licenses with capsule /root/.pyarmor/.pyarmor_capsule.zip ...
INFO     Output path of licenses: /home/licenses/
INFO     The license file is generated in restrict mode
INFO     The license file is generated in period mode disabled
INFO     Generate license: *CODE:TESTACTIVE;*;*;0;*;*;*
INFO     Write license file: /home/licenses/TESTACTIVE/license.lic
INFO     Write information to /home/licenses/TESTACTIVE/license.lic.txt
INFO     Generate 1 licenses OK.


This is the log when I generate the license on amd64

 INFO     PyArmor Version 7.5.1
INFO     Python 3.6.9
INFO     Generate licenses for ...
INFO     Output path of licenses: /home/licenses/
INFO     The license file is generated in restrict mode
INFO     The license file is generated in period mode disabled
INFO     Generate license: *CODE:TESTACTIVE;*;*;0;*;*;*
INFO     Write license file: /home/licenses/TESTACTIVE/license.lic
INFO     Write information to /home/licenses/TESTACTIVE/license.lic.txt
INFO     Generate 1 licenses OK.

The difference is on amd64 the line says "Generate licenses for ..." not "Generate licenses with capsule /root/.pyarmor/.pyarmor_capsule.zip ..."

**Comment by jondy** [comment]
Use option `-d`, for example, `pyarmor -d licenses r001`

The key is that feature `0` isn't compatible with other features not zero.

**Comment by jondy** [comment]
Please refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-scripts-with-different-features

**Comment by pikonek** [comment]
Specifying --platform linux.aarch64 solved my problem even on native linux.aarch64 machine
