### ISSUE TITLE
pyarmor.py: error: unrecognized arguments: exclude

### ISSUE THREAD

**Issue by KomarovAlea** [dashingsoft/pyarmor#8]
I give this tutorial https://github.com/dashingsoft/pyarmor/blob/master/src/user-guide.md
part: "**obfuscate odoo module**"
make git clone v3.6.1
last commit a736bdc from Feb 27, 2018 
command:
```
    ./pyarmor config --output=dist/web-login --disable-restrict-mode=1 \
                     --manifest "global-include *.py, exclude __manifest__.py"
```
and get this error:

` pyarmor.py: error: unrecognized arguments: exclude  __manifest__.py`

I also try:
` --manifest "global-include *.py; exclude __manifest__.py"`
` --manifest "global-include *.py exclude *__manifest__.py"`
` --manifest "global-include *.py, global-exclude __manifest__.py"`

(As you can see "exclude" here https://pypi.python.org/pypi/pyarmor/1.7.1)
` --manifest "global-include *.py" --exclude "__manifest__.py"`
` --manifest "global-include *.py" -exclude="__manifest__.py"`
` --manifest "global-include *.py" -exclude=__manifest__.py`

**Comment by jondy** [comment]
I got it, the reason is that quote mark lost when pass arguments to shell script. I'll fix it soon.

**Comment by jondy** [comment]
Quick workaround before v3.6.2:

Edit shell script "pyarmor" in the project path, replace `$*` with `"$@"`. The final script looks like this:

`/home/jacon/anaconda2/envs/pyarmor3.6/bin/python /opt/pyarmor/v3.6.1/pyarmor/src/pyarmor.py "$@"`
