### ISSUE TITLE
 File "<frozen main>", line 13, in <module>

### ISSUE THREAD

**Issue by ALok280** [dashingsoft/pyarmor#802]
Hello so i tried using pyarmor to obf one of my python files and it all worked but when i try to run it it closed immediatley and it shows this before it closes

Traceback (most recent call last):
  File "<C:\Users\user\Downloads\Dart gen\dist\main.py>", line 3, in <module>
  File "<frozen main>", line 13, in <module>
ImportError: cannot import name 'Botter' from 'src' (C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\src\__init__.py)

please help me with this issue

**Comment by jondy** [comment]
Please refer to http://pyarmor.readthedocs.io/en/latest/questions.html

**Comment by rolkoztm** [comment]
> Please refer to http://pyarmor.readthedocs.io/en/latest/questions.html

can you help 😳

**Comment by jondy** [comment]
It's not related to pyarmor, no more support for this. Please learn Python' import knowledge to fix any import issue.
