### ISSUE TITLE
Could not find "/Backend/api/pytransform/platforms/linux/aarch64/_pytransform.so"

### ISSUE THREAD

**Issue by muhammadmahad-debug** [dashingsoft/pyarmor#805]
<img width="905" alt="Screenshot 2022-08-06 at 8 43 34 PM" src="https://user-images.githubusercontent.com/62625370/183256057-9308b1f0-1d84-4c46-b984-95dda66ec277.png">

Getting this error when running the docker Image

Any solution

**Comment by jondy** [comment]
docker should use platform `musl.aarch64`, please check the chapter `Support Platform` in the documentation.

**Comment by muhammadmahad-debug** [comment]
@jondy can you please send the link .... from where I can get some info more

**Comment by jondy** [comment]
Run this command `pyarmor help` will open the online documentation
