### ISSUE TITLE
Cannot change OBF_MODE WRAP_MODE or MIX_STR

### ISSUE THREAD

**Issue by Gowixx** [dashingsoft/pyarmor#806]
**Title**
Title explains it all

**Reproduction**
1. Create entrypoint: `pyarmor init --entry main.py`
2. Run commands such as --advanced 4
3. Errors on other commands

Logs

    C:\Users\usr>pyarmor config --obf_code 2
    usage: pyarmor [-h] [-v] [-q] [-d] [--home HOME] [--boot BOOT]  ...
    pyarmor: error: unrecognized arguments: --obf_code
    
    C:\Users\usr>pyarmor config --wrap_mode 2
    usage: pyarmor [-h] [-v] [-q] [-d] [--home HOME] [--boot BOOT]  ...
    pyarmor: error: unrecognized arguments: --wrap_mode

    C:\Users\usr>pyarmor config --mix-str 1
    usage: pyarmor [-h] [-v] [-q] [-d] [--home HOME] [--boot BOOT]  ...
    pyarmor: error: unrecognized arguments: --mix-str

**Comment by jondy** [comment]
Please check the man page of command `config`

**Comment by Gowixx** [comment]
Shouldn't it be called "Main Page?" Also, do you guys need help with the documentation, there are lots of grammatical errors on it.
