### ISSUE TITLE
'New' get_license_info() error

### ISSUE THREAD

**Issue by scottwsides** [dashingsoft/pyarmor#807]
This is the paid license of pyarmor PyArmor Version 6.8.1 Registration Code: pyarmor-vax-002794
I can no longer get info from license (this worked within last few weeks)

<img width="783" alt="Screen Shot 2022-08-10 at 12 16 10 PM" src="https://user-images.githubusercontent.com/13578795/183987807-c0264b3f-1fa7-49f5-9024-a4f94dadfd3c.png">

Is this known?

**Comment by scottwsides** [comment]
Sorry... here's some more error info. Its dying on registration code call. Do I have to specify that somewhere. Keep in mind this is on an installed version of an app that has obfuscated codes included.... but not pyarmor itself installed. 

<img width="953" alt="Screen Shot 2022-08-10 at 12 33 58 PM" src="https://user-images.githubusercontent.com/13578795/183990337-9c807cd3-1d19-4fa3-8b65-4e44ff88bcad.png">

**Comment by jondy** [comment]
You can't not run it directly, it must be runned in the obfuscated scripts. Try to obfuscate this script and run it again.

The license format has been changed in the Pyarmor v7.0.1, if the license is generated by latest Pyarmor, please generate the runtime files with latest Pyarmor. Or use Pyarmor < v7.0.1.

Please check this 
https://pyarmor.readthedocs.io/en/latest/change-logs.html#incompatible-issues

**Comment by scottwsides** [comment]
I bought license for 6.8.1. Will my registration file still work?

Just to re-emphasize... this has to run on a machine that does *NOT* have pyarmor installed. I want a user to be able to see license info.

**Comment by jondy** [comment]
The registration file still works.

You need not install pyarmor install on the target machine, just copy all the runtime files and this obfuscated script to target machine, it's the easy way to run `get_license_info`.

Refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#runtime-package

**Comment by scottwsides** [comment]
I think I'm doing that. I copy pytransform directory into the same location as the obfuscated scripts. The docs in your link above is also describing linux I think... not macos. Although I cant imagine that making a difference. I'm using 6.8.1 to obfuscate and generate license. I just tried again and no luck. I've already done everything (i think) that you've suggested and its what I've always done. Perhaps I'm not describing the problem well.

**Comment by jondy** [comment]
By the error message, the root cause is that `pytransform._pytransform` is not set. It should be initialized by `pytransform.pyarmor_runtime`, and this function will be called by obfuscated script's `bootstrap code` generally. Obviously `pyarmor_runtime` isn't called, I don't know why. Please hack the function `payrmor_runtime` in the `pytransform.py` or `pytransform/__init__.py` to know more if you uses Pyarmor not in normal way

**Comment by scottwsides** [comment]
I dont quite understand your comment... but I'll keep looking. I just know that a month or so ago this worked and now it doesnt. My dependency chain could have subtle differences... its always hard to know for 100%. I dont know what 'using Pyarmor not in normal way' means. I distribute the obfuscated packages, the pytransform directory, and the license.lic file to a user. The scripts themselves decrypt and work just fine BTW. 

One thing I'm trying is upgrading from 6.8.1 to 7.0.1. Hopefully that will fix or give additional clues.

**Comment by scottwsides** [comment]
Well.... upgrading to 7.6.0 did the trick. I did notice the following with the new version

INFO     Create cross platform libraries path /Users/swsides/.pyarmor/platforms
INFO     Search library for platform: darwin.x86_64
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r51.5/index.json
INFO     Write cached platform list file /Users/swsides/.pyarmor/platforms/index.json
INFO     Found available libraries: ['darwin.x86_64.7']
INFO     Target path for darwin.x86_64.7: /Users/swsides/.pyarmor/platforms/darwin/x86_64/7
INFO     Downloading library file for darwin.x86_64.7 ...
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r51.5/macosx_x86_64/_pytransform.dylib <------------

So this new file was being downloaded from a remote location. I forget exactly what 6.8.1 did... but if there was some external dependency that changed for new versions.... that would break older ones, even though nothing in their code base changed. 

I think I would mention to users that backward compatibility might be gone... at least for <=6.81.

**Comment by scottwsides** [comment]
You can comment and then close if you like
