### ISSUE TITLE
ModuleNotFoundError: No module named 'pytransform' and ImportError: dynamic module does not define module export function (PyInit__pytransform)

### ISSUE THREAD

**Issue by ramanathan831** [dashingsoft/pyarmor#808]
OS: Ubuntu 20.04
Py version: Python 3.8
```
pyarmor register path_tozip
pyarmor init --src path_to_original_scripts path_to_obfuscated_scripts 
cd path_to_obfuscated_scripts 
pyarmor config --restrict 0
pyarmor config --entry "__init__.py, evaluate.py, train.py" (both files have main functions)
pyarmor config --manifest "global-include *.py, prune configs" (don't want configs dir under path_to_original_scripts to be obfuscated)
pyarmor build
cp -r dist/* path_to_original_scripts
```
Directory structure:

- setup.py
- speech_recognition
  - entry_point
    - \_\_init__.py
    - speech_recognition.py
  - scripts
    - \_\_init__.py
    - train.py
    - evaluate.py
    - configs/
      - \_\_init__.py
      - somefile.py

The scripts are obfuscated, and I have a setup.py which generates a whl file, the pytransform folder is correctly packed within the whl file

When I install the package using whl file and trigger the tasks of evaluate and train like:

1. speech_recognition train
2. speech_recognition evaluate

then I'm getting the error of **ModuleNotFoundError: No module named 'pytransform'**.
But if I run the obfuscated script directly like python train.py there are no issues

If I set PYTHONPATH to the directory which holds the pytransform folder, then I get **ImportError: dynamic module does not define module export function (PyInit__pytransform)**

How can I solve this?

**Comment by jondy** [comment]
Please remove all `pytransform.*` files, leave path `pytransform` only in the output path.

**Comment by ramanathan831** [comment]
remove all pytransform.* files - you mean the pytransform folder containing __init__ and _pytransform.so?
Couldn't understand correctly, can you please rephrase it

**Comment by jondy** [comment]
No.
 
Please check this section
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

I don't know why this happen:

```ImportError: dynamic module does not define module export function (PyInit__pytransform)```

`pytransform` is a package, but this error message means the obfuscated scripts are importing an extension (dynamic library).

I think there should be missed something in the bug reproduced steps.

**Comment by ramanathan831** [comment]
Initial error was ModuleNotFoundError: No module named 'pytransform'
To solve that, on seeing other issues: I tried copying the pytransform folder which is generated to lib/python3.8/site-packages/ or Add the path of the generated pytransform folder to PYTHONPATH - when I do either one of these then only I can the error of dynamic module

**Comment by jondy** [comment]
Please read the online documentation first. You're using pyarmor in the wrong way.
