### ISSUE TITLE
[BUG]The encrypted whl file cannot be used normally after it is installed in the M1 (darwin.aarch64) python environment

### ISSUE THREAD

**Issue by Xiaozhenrenjia** [dashingsoft/pyarmor#809]
The encrypted whl file cannot be used normally after it is installed in the M1 (darwin.aarch64) python environment， This is bug？

**Comment by jondy** [comment]
Please refer to
https://pyarmor.readthedocs.io/en/latest/build-wheel.html

Especially the important note at the end.
