### ISSUE TITLE
[Question] PyArmor Unpacker, we will be safe on latest version?

### ISSUE THREAD

**Issue by ChronoBrake** [dashingsoft/pyarmor#818]
Hey mate,
In the last time i found something weird:
https://github.com/Svenskithesource/PyArmor-Unpacker
We using PyArmor in many projects, we can start be little worrying or it's be patched already?

Best Regards

**Comment by Spindermoon1** [comment]
no 😈

**Comment by pauloswear** [comment]
Guess that there is no way to reverse spp mode using this methods.
I can be wrong, but this package only works with advanced 1 (simple) wich generates pytransform.dll
Super mode has own implementation of ceval
VM mode has themida encapsulating objects
SPP mode takes the code to C code objects, so, is hardest to reassembly code

**Comment by Spindermoon1** [comment]
wait until method 4 😈

**Comment by Svenskithesource** [comment]
@pauloswear correct, my unpacker is made for the free modes of PyArmor, any other mode like Super Mode, Super Plus Mode and VM mode won't work.

**Comment by pauloswear** [comment]
> wait until method 4 😈

you even`t contributed with super mode, wich not exists unpacker yet using concepts showed in this repo. Even if you can dump using versions > super mode, does not exists any decompyler for python 3.9 +, then you will be stuck on pyc bytecode.

**Comment by ChronoBrake** [comment]
@jondy any statement Sir? I know money is important, but free version need fix for this :(

**Comment by Spindermoon1** [comment]
@pauloswear Python 3.9, 3.10 decompiler does exist lol, and im just memeing, all my messages are trolls.

**Comment by jondy** [comment]
Do not discuss security issue here.
