### ISSUE TITLE
pyarmor gives subtle disk serial number

### ISSUE THREAD

**Issue by LittleDoggy** [dashingsoft/pyarmor#82]
I used cmd lines "wmic drivedisk get serialnumber" to check out my PC disk SN, it is given:
WD-WCC6Y1CN5311

But the report that "pyarmor hdinfo" gives me is a little different:
WD-WCC6Y1CN5311N5311

As you can see,extra number "N5311" is appended to the origin disk serial number.

After a license file  generated, only the SN that given by Pyarmor can be recognized by decode procedure.

I dont know how to fix this , when it comes to check many disks` serial number.

Could anyone give me some suggestion please .

**Comment by jondy** [comment]
If the obfuscated scripts run in the Windows and pyarmor version isn't v5.3.10, try to upgrade to the 5.3.10, it retrieves the serial number by new way.

**Comment by LittleDoggy** [comment]
Fortunately it just fit me.
However,after "pip install upgrade Pyarmor",the latest version does not work well.
The given SN  is:
W
Only single "W".
But,I think your effort must fixed something.
I bind disk SN (WD-WCC6Y1CN5311,the origin SN)  ,finally it is recognied.

I doubted that perhaps any other wrong SN with head of "W" may pass decode procedure.
I tested my guess ,and so it is!
Any other wrong SN with head of "W" passed decode procedure.

Perhaps,It needs to take more time.
Best wish for this to be fixed in future days.

**Comment by jondy** [comment]
I'll fix it soon, but need your help, :)
Could you download 
http://pyarmor.dashingsoft.com/downloads/hdinfo-debug.exe
run it and paste the output here? It will print hardware information and some extra information which would help me to find the problem.

**Comment by LittleDoggy** [comment]
I downloaded the debug exe and run it,but where is the output info log?

**Comment by LittleDoggy** [comment]
I can not find the output info log, so I typed it manually:
-----START-----

E:\Browserdownload\GoogleDownload>hdinfo-debug.exe
The original data:
     WD-WCC6Y1CN5311
Got sn by new way: W -DCW6C1YNC3511
The system could not find the specified file.
Got sn by IDE: WD-WCC6Y1CN5311
Serial number of first harddisk: "WD-WCC6Y1CN5311"
Mac address: "xx:xx:xx:xx:xx:xx"
Ip address: "xxx.xxx.x.xx"
Domain name: " "

-----END-----

I confirmed the copy for times to make sure this is the exactly copy. 

There seems to be a flaw in the new way to get SN.

**Comment by jondy** [comment]
There is no log, what I want to see is the console output as you have done.

Yes, something is wrong to get SN by new way. It seems there is a special char at the leading of the original data.

Could you download a new one
http://pyarmor.dashingsoft.com/downloads/hdinfo-debug.exe
and paste the console output here?

**Comment by LittleDoggy** [comment]
console output is here:
first char is 20
Version is 28
Device Type is 0
Device Type Modifier is 0
Serial number of first hard disk: "WD-WCC6Y1CN5311"

**Comment by jondy** [comment]
Fix it in v5.3.11, please upgrade the latest version.

**Comment by LittleDoggy** [comment]
The latest version gives me the correct SN now.
I tried to bind disk to wrong SN, and the *.lic is not valid for my computer.
So,you have fixed the problem now.
Congratulations!
And thank u for your help.
