### ISSUE TITLE
How to obfuscate and run a flask application with apache web server?

### ISSUE THREAD

**Issue by rc2007** [dashingsoft/pyarmor#827]
Hi ,

I have a flask application with app.py and app.wsgi files with app.wsgi as an entry point for apache web server deployment.
Could you please help me with the procedure to obfuscate and deploy?

Thank!

**Comment by jondy** [comment]
Search `flask` in the issues, and refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts
