### ISSUE TITLE
Restrict Mode 0 with outer license not working (Cython)

### ISSUE THREAD

**Issue by leond08** [dashingsoft/pyarmor#829]
I was trying to cythonize the obfuscated script. I read your guide on how to do it.

But when i use restrict 0 with --with-license outer it give me an error.

Cannot use Restrict Mode 0 with outer license

**Comment by leond08** [comment]
I use --disable-restrict-mode when generating license and it works but what are the security issues disabling restrict mode in license? Is this a good practice?

**Comment by jondy** [comment]
Please search `restrict mode` in the online documentation to understand restrict mode.
