### ISSUE TITLE
Errors when using PyInstaller by a custom way (not "pyarmor pack")

### ISSUE THREAD

**Issue by eliost369** [dashingsoft/pyarmor#83]
Hello,

first of all, I have pyarmor v5.3.11 and pyinstaller v3.4

I want to use pyinstaller to pack my application that has been obfuscated with pyarmor..

but i dont want to use `pyarmor pack script.py` because it is not customizable and I want to use `--onefile`

So.. i have tried `pyarmor obfuscate script.py` to obfuscate my script, after that I ran pyinstaller on the file that got obfuscated with this .SPEC file:

```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['myscript.py'],
             pathex=['D:\\dist'],
             binaries=[],
             datas=[ ("_pytransform.dll", "."), ("license.lic", "."), ("pytransform.key", ".") ],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='myscript',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )
```

but before running PyInstaller on this SPEC file, I've edited the file that got obfuscated with PyArmor and added my `import` lines above the `from pytransform import pyarmor_runtime` line - I did that so PyInstaller can know my modules and pack them in the EXE

And finally, i have ran PyInstaller using this SPEC file.

then I tried opening the output EXE file and I got this error:

**Check restrict mode failed**

I fixed this by reading https://pyarmor.readthedocs.io/en/latest/questions.html#check-restrict-mode-failed .. so I've re-obfuscated my script using pyarmor again using this command now: `pyarmor obfuscate --restrict=0 script.py`

and again I've edited the file that got obfuscated with PyArmor and added my `import` lines above the `from pytransform import pyarmor_runtime` line, then I've ran PyInstaller with the same SPEC file on the new pyarmor obfuscated file

but now I got this error when I tried to open the EXE file:

**unexpected obfuscated script**

I fixed that by reading https://pyarmor.readthedocs.io/en/latest/how-to-do.html#special-handling-of-entry-script .. I've did all that again but now my pyarmor command is like that: `pyarmor obfuscate --restrict=0 --no-cross-protection script.py`

and finally my EXE file worked!

But I have a feeling that all those options that I've disabled on pyarmor had lessen the security of pyarmor on my script.. is there's a solution to let PyInstaller read all my modules without adding the `import` lines above `from pytransform import pyarmor_runtime` - or is there's any other solution for my problem?

thanks!

EDIT: the EXE file works fine if i didnt add my `import` lines above `from pytransform import pyarmor_runtime`

**Comment by jondy** [comment]
The better way is to use command `pack` as the following way:
```
pyarmor pack -e " --onefile" myscript.py
```
You can pass any options required by PyInstaller by `-e`. So long as PyInstaller works with these options, the command `pack` should work either.

Here it's a really example which is used to pack my pyqt project by PyArmor:
```
HIDDEN_IMPORTS=" --hidden-import chardet --hidden-import comtypes"
DATA_FILES=" --add-data 'config.json;.' --add-data 'docs/_build/html;docs'"
OBFOPTIONS=" --exclude py34,dist,obf --plugin check_expired"

$(PYARMOR) pack -e " -y --name easy-han ${HIDDEN_IMPORTS} ${DATA_FILES}" -x "${OBFOPTIONS}" -s "easy-han.spec" main.py

$(PYARMOR) licenses -O dist -e 2019-09-01 trial
cp dist/licenses/trial/license.lic dist/easy-han/	
```
In this example many extra options required by PyInstaller passed to command `pack`.

Refer to
https://pyarmor.readthedocs.io/en/latest/man.html#pack

**Comment by eliost369** [comment]
Thank you very much ! it worked fine.. but I got this error:

**Protection Fault: _pytransform.dll is missing**

I had to add `_pytransform.dll` as a data file in the Pyinstaller parameters, doesn't `pyarmor pack` already do that?

**Comment by jondy** [comment]
It should be picked by `pyarmor pack` automatically.  Could you check the patched spec file, the name would be `script-patched.spec`?  Is the file `_pytransform.dll` inserted this patched spec as data file?

**Comment by eliost369** [comment]
Yes the data parameter of `_pytransform.*` is there in the patched SPEC file..

I've tried a clean pack and same problem.

**Comment by eliost369** [comment]
I've just noticed that this problem of `Protection Fault: _pytransform.dll is missing` occurs with this script only. I've tried another simple Hello World script and it worked fine.

But I can't figure the problem of my script that gets the error.. it is a Flask application - and my Flask app init line is like:
```
app = Flask(__name__, static_url_path='', static_folder='./static')
```
so, does `__name__` change the current working directory of PyInstaller and then PyArmor won't find the `_pytransform.dll` file?

Also, when I start my EXE and go to %temp% open find the temporary folder of PyInstaller for my EXE.. I find `_pytransform.dll` there.

This is really confusing :/

**Comment by jondy** [comment]
Maybe the big output EXE is problem. If it is, maybe using option `--add-binary` other than `--add-data` could fix it. 

Could you edit the patched spec file, move `_pytransform.dll` from list `datas` to list `binaries` in the parameters of `Analysis`, and run pyinstaller with this patched spec file directly.

If the error is gone, I'll change the `packer.py` by this way to fix this problem.

**Comment by eliost369** [comment]
I did that. I've edited the patched SPEC file and removed `('dist\\obf\\dist\\_pytransform.*', '.')` from datas and added it to `binaries` then I ran PyInstaller on the patched SPEC file.

Now when I run the output EXE, `_pytransform.dll` gets copied to the PyInstaller temporary folder immediately.. but the same problem still occurs. :/

**Comment by eliost369** [comment]
Ok, so I've tried to pack my script like that: `pyarmor pack -e " --onefile" -x " --restrict=0 --no-cross-protection" script.py` and my EXE worked without the `Protection Fault: _pytransform.dll is missing` error.

I really don't know what's wrong :/

**Comment by eliost369** [comment]
Important Edit:

It's Flask problem! Even this hello world flask application have the same problem (Protection Fault: _pytransform.dll is missing):
```
from flask import Flask

app = Flask(__name__, static_url_path='', static_folder='./static')

@app.route('/')
def main():
	return "Hello World!"
	
if __name__ == '__main__':
	app.run(host='0.0.0.0',port=9305,debug=False)
```

Is there's a solution to use PyArmor + PyInstaller + Flask?

**Comment by jondy** [comment]
One solution is to add this comment line before the Flask init line changed the current work path. For example,
```
# {PyArmor Protection Code}
app = Flask(__name__, static_url_path='', static_folder='./static')
```
And `pyarmor pack -e " --onefile" script.py`

By default, `pyarmor` inserts the protection code before the line `if __name__ == '__main__':`, but here the current path is changed. Inserting this comment line, the protection code will be inserted here so that the current path isn't changed as protection code checks the file `_pytransform.dll`.

Refer to 
https://pyarmor.readthedocs.io/en/latest/how-to-do.html#special-handling-of-entry-script

**Comment by eliost369** [comment]
> One solution is to add this comment line before the Flask init line changed the current work path. For example,
> 
> ```
> # {PyArmor Protection Code}
> app = Flask(__name__, static_url_path='', static_folder='./static')
> ```
> 
> And `pyarmor pack -e " --onefile" script.py`
> 
> By default, `pyarmor` inserts the protection code before the line `if __name__ == '__main__':`, but here the current path is changed. Inserting this comment line, the protection code will be inserted here so that the current path isn't changed as protection code checks the file `_pytransform.dll`.
> 
> Refer to
> https://pyarmor.readthedocs.io/en/latest/how-to-do.html#special-handling-of-entry-script

yes this solution looks to be better.. but i have a question

what will pyarmor do if my script doesnt have `if __name__ == '__main__':` ?

**Comment by jondy** [comment]
If both of `if __name__  == '__main__':` and `# {PyArmor Protection Code}` aren't in the entry script, pyarmor won't insert protection code into the script.
