### ISSUE TITLE
pyarmor shows tkinter window multiple times

### ISSUE THREAD

**Issue by DaliaMokhtar** [dashingsoft/pyarmor#830]
below tool.py code script, while running that code using cmd<br>
**tool.py** command, it runs successfully 100%<br>
when I try to pack the code using pyarmor by below command in cmd<br>
**pyarmor pack -e "--onefile " tool.py**<br> and then I run exe file, it shows win00 window 
when I press submit button, first it starts to run code.<br> but at the middle of running it, it shows tkinter win00 window again, which stops the first code running<br>
Func00 and Func01 include multiprocessing processes, each Func includes 5 processes.<br>
*tool.py*

    import tkinter as tk
    from deployedFunc00 import *
    from deployedFunc01 import *
    
    def button_fn():
        if clicked.get() == 'func00':
            if __name__ == '__main__':
                Func00()
        else:
            if __name__ == '__main__':
                Func01()
                
    def show():
        label_.config(text=clicked.get())
        
    if __name__ == '__main__':
        win00 = tk.Tk()
        win00.geometry("300x300")
        win00.eval('tk::PlaceWindow . center')
    
        frame00 = tk.Frame(win00)
        frame00.pack_propagate(0)
        frame00.pack(fill=tk.BOTH, expand=1)
    
        options = ['func00','func01']
        clicked = tk.StringVar()
        clicked.set('func00')
    
        drop = tk.OptionMenu(frame00, clicked, *options)
        drop.pack()
        
        label_ = tk.Label(frame00, text=" ")
        label_.pack()
        
        button0 = tk.Button(frame00,text="choose",command=show).pack()
    
        button1 = tk.Button(frame00,text='submit',command= button_fn)
        button1.pack(side=tk.BOTTOM,pady=(0,10))
    
        win00.mainloop()

*deployedFunc00.py*

    import multiprocessing
    from func05 import *
    
    
    def Func00():
        LENGTH = 5
    
    
        jobs = []         
        for n in range(LENGTH):
            globals()['p_%s' %n] = multiprocessing.Process(target = Func05)
            
        for n in range(LENGTH):
            jobs.append(globals()['p_%s' %n])
            
        for n in range(LENGTH):
            globals()['p_%s' %n].start()
            
        for proc in jobs:
            proc.join()

*deployedFunc01.py*

    import multiprocessing

    from func06 import *

    def Func01():
        LENGTH = 5
    
    
        jobs = []         
        for n in range(LENGTH):
            globals()['p_%s' %n] = multiprocessing.Process(target = Func06)
            
        for n in range(LENGTH):
            jobs.append(globals()['p_%s' %n])
            
        for n in range(LENGTH):
            globals()['p_%s' %n].start()
            
        for proc in jobs:
            proc.join()

**Comment by jondy** [comment]
How about pack it by PyInstaller directly? For example
```
pyinstaller --onefile tool.py
```

**Comment by DaliaMokhtar** [comment]
same problem, with PyInstaller, pyarmor, or py2exe

**Comment by jondy** [comment]
That's pyinstaller's problem, pyarmor just obfuscates the scripts, then call pyinstaller to pack the obfuscated scripts.

**Comment by DaliaMokhtar** [comment]
if use pyonstaller only directly, using command
**pyinstaller --onefile tool.py** 
and then I run exe file, it shows win00 window
when I press submit button, first it starts to run code.
but at the middle of running it, it shows tkinter win00 window again, which stops the first code runnin

and if I obfuscate it by pyarmor using command **pyarmor obfuscate tool.py** and then using pyinstaller 
it shows can not find _pytransform.dll error, this error is only shown in codes that used multiprocessing 

below is the used spec file of pyinstaller:

```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['tool.py'],
    pathex=['C:\dist'],
    binaries=[('pytransform\\_pytransform.*', '.')],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='tool',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
	runtime_tmpdir=None,
    console=True,
)
```

**Comment by DaliaMokhtar** [comment]
Could not find "C:\Users\Iuser\AppData\Local\Temp\_MEI47962\pytransform\platforms\windows\x86_64\_pytransform.dll"

**Comment by jondy** [comment]
Refer to
https://pyarmor.readthedocs.io/en/latest/how-to-do.html#how-to-pack-obfuscated-scripts

**Comment by DaliaMokhtar** [comment]
still shows same issue
I notice that after obfuscation only it runs well, but after it turns to exe file, it doesn't understand multiprocessing, so it keep repeat 
I run it on python code on windows 11

**Comment by DaliaMokhtar** [comment]
finally I found a solution:
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing
