### ISSUE TITLE
Is restrict mode actually applied to just one script?

### ISSUE THREAD

**Issue by Kreonid** [dashingsoft/pyarmor#833]
I'm using this command:
`pyarmor pack main.py -x="--advanced 2 --restrict=3"`

[This page](https://pyarmor.readthedocs.io/en/latest/mode.html?highlight=restrict#restrict-mode) in the docs says:
`Restrict mode is applied to one single script, different scripts could be obfuscated by different restrict mode.`

Does it mean that the restrict mode is only applied to the entry script (main.py)? Or does it actually apply to all the .py files that will be obfuscated?

Thanks.

**Comment by jondy** [comment]
It applies to all the .py files that will be obfuscated.
