### ISSUE TITLE
[BUG] load dll failed since to import pytransform from UNC path

### ISSUE THREAD

**Issue by loonghao** [dashingsoft/pyarmor#836]
Hi Jondy,

When we use pyarmor to obfuscate Python scripts make a bundle and copy this bundle to a server that wants to share this bundle in internal

when we launch this tool will get like below errors
![image](https://user-images.githubusercontent.com/13111745/189061674-7704344e-8aa8-40e1-b2dc-3741831dc150.png)

If it's a local drive everything works perfectly

**Comment by jondy** [comment]
Could you import any python module in the unc path? If not, Pyarmor could not.

**Comment by loonghao** [comment]
> Could you import any python module in the unc path? If not, Pyarmor could not.

I have double-checked this issue from https://github.com/indygreg/PyOxidizer/issues/224#issuecomment-602720219, closing the issue
