### ISSUE TITLE
Prevent macOS with hardened runtime to kill obfuscated scripts

### ISSUE THREAD

**Issue by SEngelnkemper** [dashingsoft/pyarmor#837]
Hi,

I am trying to obfuscate a package for the darwin.arm64 architecture. It seems that I run into this known issue when trying to import something from the package (--advance 2):

[Doc - Supported Platforms - Features](https://pyarmor.readthedocs.io/en/latest/platforms.html?highlight=jit#features)
[Doc - When Things Go Wrong - Apple M1 Hangs Issue](https://pyarmor.readthedocs.io/en/latest/questions.html?highlight=jit#apple-m1-hangs-issue)

Is there any good workaround for this, if I want to use super or super plus mode? The Info given in the documentation isn't very helpful tbh.

Thanks!

**Comment by jondy** [comment]
Do you use pyarmor trial version?

**Comment by SEngelnkemper** [comment]
No, I have a paid license.

**Comment by SEngelnkemper** [comment]
Btw., these are the commands I use:

`pyarmor licenses --disable-restrict-mode --expired 2022-09-12 r001`

`pyarmor obfuscate --platform darwin.aarch64 --advanced 2 --with-license licenses/r001/license.lic --recursive --output path_to_output input`

**Comment by jondy** [comment]
Do you use the latest version of pyarmor?

**Comment by SEngelnkemper** [comment]
Yep, here is the version info:
INFO     PyArmor Version 7.6.1
INFO     Python 3.10.6

**Comment by VeNoMouS** [comment]
https://eclecticlight.co/2020/08/22/apple-silicon-macs-will-require-signed-code/

**Comment by SEngelnkemper** [comment]
I know about the features of Apple Silicon. The question is, how to work around this to get an obfuscated package running?

**Comment by VeNoMouS** [comment]
codesign the dylib

**Comment by SEngelnkemper** [comment]
When using "--advance 2" it's a .so rather than a dylib, but I already tried that with no effect.

**Comment by VeNoMouS** [comment]
> When using "--advance 2" it's a .so rather than a dylib, but I already tried that with no effect.

https://pyarmor.readthedocs.io/en/latest/change-logs.html#id13

```
In Darwin codesign the runtime binary file to avoid the obfuscated scripts killed by Apple M1
```

**Comment by SEngelnkemper** [comment]
So, I now managed to get around this by running the obfuscation on a aarch64 system rather than a x86_64 system. However, the ability to cross-compile between the two systems should definitely be fixed.

The python runtime does not get killed anymore, but now I get an error 

`SystemError: /Users/sysadmin/build/v3.10.6/Objects/listobject.c:330: bad argument to internal function`

This is only the case when compiling and importing my package on aarch64, where feature number 8 is used rather than feature number 11. 

Any idea how to tackle this?

**Comment by jondy** [comment]
I have fixed a bug in darwin.aarch64.8, it will be released in this month.

**Comment by VeNoMouS** [comment]
> I have fixed a bug in darwin.aarch64.8, it will be released in this month.

Do we still need to disable cross compile etc etc? can you please give an example of how we should be doing this correctly

**Comment by jondy** [comment]
It's a crash bug. After upgrading the latest version, it should work.

**Comment by SEngelnkemper** [comment]
Okay, looking forwards to get this fixed. However, this means that we still are restricted to feature number "8" for aarch64 systems, which has less security features than, e.g. "11", right?

**Comment by jondy** [comment]
Yes. There is no anti-debug in feature `8` , but Mac OS could protect the binary file by code sign.

**Comment by jondy** [comment]
Super mode and app mode for darwin.aarch64 works in v7.7.0

**Comment by SEngelnkemper** [comment]
Not quite. I just upgraded pyarmor to 7.7.0 on both systems, darwin x64 and darwin aarch64. The behavior is as follows:

When I **obfuscate the package on darwin x64** (same is for linux x64), the obfuscation process works just fine. However, when deploying the package to a darwin aarch64 system, the interpreter still gets killed. I then did a `codesign --verify --deep --verbose=2 pytransform.so` which gives `invalid signature`. I then signed the lib with `codesign -s - pytransform`. After this I get `valid on disk` when re-checking the codesign. However, if I then re-try the import of my package the interpreter doesn't get killed, but simply freezes. 

When I try to **obfuscate the package on darwin aarch64** directly, I cannot even create the runtime package. Running `pyarmor runtime --advanced 2` immediately gives:

```
INFO     PyArmor Version 7.7.0
INFO     Python 3.10.6
ERROR    Expecting value: line 1 column 1 (char 0)
```

Any suggestions ?

**Comment by jondy** [comment]
In Apple M1, use darwin.aarch64.0 or 8, not darwin.aarch64.3 or 11

**Comment by SEngelnkemper** [comment]
> For `pyarmor runtime` issue, remove the whole folder `~/.pyarmor/platforms`, then try it again.

Yep, thanks I just figured this out myself and was about to edit my comment! :)

**Comment by SEngelnkemper** [comment]
Okay, so now I am able to build a package for, e.g. platforms darwin.x86_64,linux.x86_64,windows.x86_64, by using pyarmor on one of these platforms, all with feature number 11. And another separate package for the darwin.aarch64 platform by using pyarmor on the darwin.aarch64 platform, with feature number 8. In addition, I was able to get cross protection running in all cases by implementing a custom protection code. So far so good .. this is better than having no Apple ARM support at all.

However, it would be great to have preferably **one single package with feature number 11 for all 4 platforms** together or at least one single package with feature number 11 for except Apple ARM and 8 for Apple ARM, which can be built in one shot on a single system. Is this possible? Because right now I would need to do two separate obfuscation runs on two different systems and provide two different packages to the users do cover all 4 platforms.

**Comment by VeNoMouS** [comment]
I know from discussions with @jondy that is one of his goals @SEngelnkemper

**Comment by SEngelnkemper** [comment]
Thanks for the info @VeNoMouS ! That would be great in the future. Also, I think this stuff and workarounds should be somehow a bit clearer reflected in the documentation tbh.

**Comment by VeNoMouS** [comment]
Since personally have never got darwin aarch working, can you post param examples?

**Comment by SEngelnkemper** [comment]
On a high level, I currently do the following for darwin aarch:

1. Create runtime files in temp folder ` pyarmor runtime --platform "$darwin.aarch64" --advanced 2 --output temp_pyarmor`. This only gets me the corresponding `pytransform.so`. 
2. Re-Create the pytransform package folder structure (`pytransform/darwin_aarch64/pytransform.so` and also the standard" `pytransform/__init__.py`), so that I can use it as a package, just as if I had build the runtime for multiple platforms.
3. Read the checksum from the pytransform and put it into some protection code template.
4. Obfuscate my own package with `--no-runtime` and `--cross-protection` pointing to the filled template.
5. Move the pytransform folder to the src folder of the output.
6. Install the whole package by adding the pytransform package as an additional package besides my own package and also including the `pytransform.so` file to `package_data`

If I do all this on a Apple ARM machine, I can use my package as expected, currently only tested on the same machine.

**Comment by jondy** [comment]
> Is this possible? Because right now I would need to do two separate obfuscation runs on two different systems and provide two different packages to the users do cover all 4 platforms.

It should work with feature `0`, in Apple intel, enable feature `0` by environment var `PYARMOR_PLATFORM`
```
export PYARMOR_PLATFORM=darwin.x86_64.0
pyarmor obfuscate ...
```

>I would prefer the mentioned folder structure together with the __init__.py to be always created, no matter if I create the runtime for a single platform or for multiple platforms. Just saying ..

If you prefer to single `pytranform.py`, using `--no-package` to create the runtime files.
