### ISSUE TITLE
[BUG]Win11 64bit Python 3.9.13无法导入pytransform.pyd

### ISSUE THREAD

**Issue by hyang57** [dashingsoft/pyarmor#838]
在使用命令
`pyarmor obfuscate --platform windows.x86_64.11.py39 --advanced 2 .` 加密代码的时候会提示：`Update target platforms to: ['windows.x86_64.11.py310']`
但是得到的pytransform.pyd不能在Python 3.9被导入。

使用环境：Win 11 x64
Anaconda base: Python 3.10
Anaconda venv "pyarmor": Python 3.9.13

```
pyarmor --version
PyArmor Version 7.6.1
Registration Code: pyarmor-vax-xxxxxx
```

```
> conda activate pyarmor
> cd ~\.pyarmor\platforms\windows\x86_64\11\py310
> python --version
Python 3.9.13
> python -c "import pytransform"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed while importing pytransform: 找不到指定的模块。
```

```
> conda activate base
> python --version
Python 3.10.6
> python -c "import pytransform"
[no output]
```

**Comment by jondy** [comment]
你使用的 python 3.10 在加密代码，请使用 python 3.9 加密代码。
具体方法请参考文档中安装说明
https://pyarmor.readthedocs.io/zh/latest/installation.html
