### ISSUE TITLE
[BUG] "Unmatched paren in format" when using --advanced 5 on aarch64

### ISSUE THREAD

**Issue by whiteowl3** [dashingsoft/pyarmor#839]
I've been using --advanced 2 and onefile mode, building this particular code successfully for some time.  I was excited to use the new "advanced 5" feature on my platform, but there is this bug.
PyArmor completes sucessfully with "--advanced 5", but this is the output of running my obfuscated program:
```
Traceback (most recent call last):
  File "<dist/obf/dit.py>", line 2, in <module>
  File "<frozen dit>", line 99, in <module>
  File "<frozen dit>", line 94, in protect_pytransform
  File "<frozen dit>", line 35, in spp_caller
SystemError: Unmatched paren in format
```
This exact same cross protection code works with "--advanced 2"

**Comment by jondy** [comment]
Sorry, I can't reproduce this issue in Mac. Do you customize the function `protect_pytransform`?

**Comment by whiteowl3** [comment]
i do customize the function protect_pytransform, yes.

I am on ubuntu 21 long-term release, not Mac.

Thank you for your support.

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Sep 14, 2022, 21:21 by ***@***.***:
