### ISSUE TITLE
Does PyArmor protect (obfuscate) the strings? And can the Bootstrap code be deobfuscated?

### ISSUE THREAD

**Issue by eliost369** [dashingsoft/pyarmor#84]
Hi,

i was wondering if it is safe to use pyarmor for a project that has sensitive strings that should be obfuscated.

does pyarmor obfuscate the strings? 

Also can the pyarmor bootstrap code be deobfuscated?

I am really sorry for using GitHub issues to ask this question but i couldn't found another way for support xD

Thanks!

**Comment by eliost369** [comment]
also I tried opening http://pyarmor.dashingsoft.com/downloads/platforms/vs2015/x86/_pytransform.dll with a DLL debugger and i found the following:

https://i.vgy.me/7p2Nrh.png

also same for "All The Others Prebuilt Libraries For PyArmor" ..
in this page http://pyarmor.dashingsoft.com/platforms.html they dont have the "Anti-Debug" and "JIT" texts next to them.. is that safe?

**Comment by jondy** [comment]
The string and all the other constants in the python scripts are protected by PyArmor.

The bootstrap code, I means these lines
```
from pytransform import pyarmor_runtime
pyarmor_runtime()
```
are plain, they aren't obfuscated.

**Comment by jondy** [comment]
Here describe the security of Pyarmor, https://pyarmor.readthedocs.io/en/latest/security.html#the-security-of-pyarmor

Now only the prebuilt libraries in the main platforms are protected by ANTI-DEBUG and JIT, the others aren't. But all of them still are protected by cross-protection and couldn't be changed by someone else. Even without ANTI-DEBUG and JIT, the hack need be an expert in reverse-engineer field, and understand 
the structure of code object and how Python interpreter executes each byte code, then step thousand of instructions to research the algorithm of PyArmor. I think it's not easy.

I still work on self protection of dynamic library `_pytransform`,  the final solution would be to provide many prebuilt libraries in same platform, for example
* win32/high-security/_pytransform.dll
* win32/middle-security/_pytransform.dll
* win32/low-security/_pytransform.dll
* ...
In most of cases, high security means more time. The developer could select one of them by balancing the security and performance as obfuscating the scripts.

As my plan, it should be completed in this year.

**Comment by eliost369** [comment]
ok thank you very much and good luck on doing that :)
but will all the security levels be for the trial and the purchased versions of pyarmor?

**Comment by jondy** [comment]
The security level is same for the trial and the purchased version.

Only the dynamic library can understand the obfuscated string `\x2c\x38\xe0\x86\xfb\`.

**Comment by eliost369** [comment]
ok thanks once again and sorry for disturbing a lot.
