### ISSUE TITLE
[Question] Usage of the trial version on Mac M1 (darwin.aarch64) to obfuscate a Python 3.10 application

### ISSUE THREAD

**Issue by dvkovner** [dashingsoft/pyarmor#841]
Hello. I'm trying to obfuscate an application which is written in Python 3.10 and built on Mac M1 (darwin.aarch64). I've tried to use options --platform darwin.arm64.0 and --platform darwin.arm64.3, but In both cases I'm getting an error like that: 

INFO     PyArmor Trial Version 7.5.1
INFO     Python 3.10.1
INFO     Target platforms: ['darwin.arm64.3']
WARNING  The trial version could not download the latest core libraries, tag r41.15a is always used. Some bugs fixed in the latest version may not be fixed in the trial version
WARNING  The core library excepted version is r50.4, but got r41.15a from platform list file /Users/m1/.pyarmor/platforms/index.json
ERROR    No available dynamic library for darwin.arm64.3 with features default

There is a list of platforms which pyarmor supports here: https://pyarmor.readthedocs.io/en/latest/platforms.html.

Mac M1 is darwin.aarch64, so it is not distributed with pyarmor and pyarmor “will download the corresponding dynamic library from the remote server automatically“.

According to the license agreement (https://pyarmor.readthedocs.io/en/v6.7.0/license.html) “The trial version could not download the latest dynamic library of extra platforms, the old versions still are available.“

According to the Release Notes (https://pyarmor.readthedocs.io/en/latest/change-logs.html#id31) starting from the version 6.7.0 “Except the core libraries distributed with soure package, for trial version all the other core libraries will always use the ones same as v6.6.2 (tag: r41.15).“.

Conclusion: the trial version of pyarmor can’t be used on darwin.aarch64 to obfuscate an application which is written using Python 3.10.

Am I right?

**Comment by jondy** [comment]
There are some new platforms in the latest version, which are missed in the trial version (tag: r41.15).

**Comment by dvkovner** [comment]
I'm not sure I understand why the message in the output is "ERROR No available dynamic library for darwin.arm64.3 with features default" then. According to the [list of platforms in r41.15a](https://github.com/dashingsoft/pyarmor-core/tree/r41.15a/platforms) darwin.arm64.3 or darwin.arm64.0 should be downloaded as a minimum. Does it check additionally that the language is Python 3.10 and this version of the language is not supported by darwin.arm64.3 or darwin.arm64.0 in r41.15a?

**Comment by jondy** [comment]
Python 3.10 should not be supported by r41.15.
