### ISSUE TITLE
相比于 pyconcrete， pyarmor 的优势是什么？

### ISSUE THREAD

**Issue by KennyLeung** [dashingsoft/pyarmor#842]
pyarmor 免费版有文件长度限制；商业版不贵，但不开源，如果与我要加密的系统有冲突，就不知道如何处理。https://github.com/Falldog/pyconcrete 开源，但使用起来比较麻烦。pyarmor 会比 pyconcrete 更安全吗？

**Comment by jondy** [comment]
对 pyconcrete 不太了解，关于 pyarmor ，其工作原理在文档中有详细说明。

**Comment by KennyLeung** [comment]
购买时，有两栏不确定如何填写。公司是国外的英文名称，产品也不确定叫什么，就是基于一个叫[odoo](https://github.com/odoo/odoo)的开源系统开发的模块，这些模块可以用在不同的系统中，类似搭积木。要加密的模块也是那些自己开发的odoo模块。如果你能确定pyarmor是支持加密 odoo模块那更好。
![图片](https://user-images.githubusercontent.com/4188953/190370243-0567bc94-5027-4e75-9826-64cf978885bc.png)

**Comment by jondy** [comment]
注册名称就填公司名称，产品名称就填下 “odoo 功能模块组”

**Comment by jondy** [comment]
注册名称就填公司名称，产品名称就填下 “odoo 功能模块组”
