### ISSUE TITLE
[Question] When obfuscating the entire project, can the files other than python files not be removed?

### ISSUE THREAD

**Issue by Seung-Uk-Park** [dashingsoft/pyarmor#843]
When I obfuscate the entire package, files such as .txt, .sql are excluded and an obfuscated project folder is created.
I want those files to remain intact.
Can I add options to obfuscation commands?

I'd appreciate it if you could answer :)

**Comment by jondy** [comment]
Before obfuscating the scripts, copying the whole package to the obfuscated folder. In linux, it may one shell command like
```
cp -a /path/to/pkgname dist/pkgname
```

**Comment by Seung-Uk-Park** [comment]
Thank you for your reply.
