### ISSUE TITLE
[BUG] Dynamic import of obfuscated file fails

### ISSUE THREAD

**Issue by emileindik** [dashingsoft/pyarmor#846]
Dynamically importing an obfuscated file using importlib fails to find global method on obfuscated file.

```
# obfuscated_file.py
def run_task():
    print('foo')
```

```
# index.py
spec = importlib.util.spec_from_file_location('module_name, '/my/obfuscated_file.py')
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
module.run_task()
```
Returns
```
AttributeError: module 'module_name' has no attribute 'run_task'
```

Both solutions from [here](https://stackoverflow.com/questions/63928324/import-pyarmor-obfuscated-code-using-importlib) worked for me. 

I ended up using [this solution](https://stackoverflow.com/a/70141599/5199310) because it was easier to implement.

Is this something that will be fixed?

**Comment by jondy** [comment]
I'll check it first.

**Comment by jondy** [comment]
I'll check it.

**Comment by jondy** [comment]
The problem is that when `spec.loader.exec_module(module)` is called, the obfuscated script could not get the instance of the module passed by `spec.loader.exec_module`.

I have not find how to fix it directly, but there are 2 extra solutions

1. Save module instance to `sys.modules` before exec_module
```python
# index.py
import importlib.util
import sys
spec = importlib.util.spec_from_file_location(module_name, '/my/obfuscated_file.py')
module = importlib.util.module_from_spec(spec)

sys.modules[module_name] = module

spec.loader.exec_module(module)
module.run_task()
```
2. Update module after exec_module
 ```python
# index.py
import importlib.util
import sys
spec = importlib.util.spec_from_file_location(module_name, '/my/obfuscated_file.py')
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

module = sys.modules[module_name]

module.run_task()
```
