### ISSUE TITLE
[Question] Cross protection test

### ISSUE THREAD

**Issue by SEngelnkemper** [dashingsoft/pyarmor#847]
I just tried to test the cross-protection feature by changing the checksum of the pytransform.so, but I cannot prevent the pytransform lib from being accepted by the entry script. These are the steps I did:

1. Add `# {PyArmor Protection Code}` to entry script (at the very beginning)
2. Obfuscated code with `--advanced 2`. PyArmor states `Patch this entry script with protection code` during the process
3. Read checksum with `md5 pytransform.so`
4. Change the checksum with, e.g. `install_name_tool -add_rpath /foo/bar/ pytransform.so`
5. Verify change of checksum with `md5 pytransform.so`
6. Test import and usage of the obfuscated code without any errors

If I understand the cross-protection process correctly, ANY change in the checksum of the pytransform library should prevent the library from being accepted by the cross-protection code inside the entry script. Is that correct? If you restrict the checksum test to the actual code of the library, the above behavior is fine. But can you provide a quick test to check that the cross-protection is actually working? Thanks!

**Comment by jondy** [comment]
You can use `pyarmor -d obfuscate ... foo.py`, it will generate a debug script named `foo.py-pyarmor-patched`. Check the function `protect_pytransform` in this debug script.

**Comment by SEngelnkemper** [comment]
Thanks, that hint is very helpful. But now I'm curious about these lines:
```
        from sys import platform
        if platform == 'darwin':
            return
```
So the libraries aren't check at all on macOS systems?

**Comment by jondy** [comment]
Yes, by default codesign will protect the binary file in MacOs, but the protection code could be customized as you need.

**Comment by SEngelnkemper** [comment]
If I understand correctly, the library can be "codesigned" on the user system, so macOS will accept it. Thats at least what you suggest to do when macOS does not accept the library. So how does this prevent an attack from (i) modifying the library to e.g. print out the decrypted code (ii) codesign it again and (iii) load/execute it?
