### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Khubaibahmed-dev** [dashingsoft/pyarmor#848]
can you please help me out to run obfuscated **streamlit_app** script.
my app scripts namely is "frsapp22.py"
i m running following command to obfuscate the script
>>pyarmor obfuscate --restrict=0 frsapp22.py
above mentioned command working fine and making dist folder and their require content.

when i want to run my app using following command 
>>python -m streamlit run frsapp22.py

it is giving me this error:
![image](https://user-images.githubusercontent.com/61181683/192084936-b60b4dba-51b7-464c-9e6b-bb82baf54c7a.png)

can you help me fixing this error.

**Comment by jondy** [comment]
Run obfuscate command with `--no-cross-protection'
