### ISSUE TITLE
Add integrity checks for the downloaded binaries

### ISSUE THREAD

**Issue by fxthomas** [dashingsoft/pyarmor#85]
Hello,

We've started investigating the use of PyArmor at work. The `download_pytransform` (in `src/utils.py`) function bothers me, in that it downloads binary packages over the internet without any integrity check at all.

Is it possible to add such a check, for example by adding a SHA-256 hash for each package in `src/platforms/index.json`? (MD5 should not be used, as it now has known vulnerabilities.)

**Comment by jondy** [comment]
Fix it  0702560
