### ISSUE TITLE
How can I call functions that are inside a obfuscated file?

### ISSUE THREAD

**Issue by tanzerlana** [dashingsoft/pyarmor#850]
Hello! 

First off, thanks for this amazing work.

next, if I have one obfuscated file, (dist/myfile.py) and inside this file, I have the function that originally was called "print_hello", how can I call this function from main.py? and what if I have another function that returns a value?

thank you very much!!

**Comment by jondy** [comment]
Just use the obfuscated script as plain script, more information, please run `pyarmor help` to open online documentation.

**Comment by tanzerlana** [comment]
Thank you! got that one working
