### ISSUE TITLE
[Question] Locally unregister python package

### ISSUE THREAD

**Issue by gianfa** [dashingsoft/pyarmor#851]
Hi,
I would like to know if it is possible to locally cancel a registration for a repo.

I give an example.
Currently,
If I register a package
```pyarmor register /path/to/pyarmor-regcode-xxxx.txt```.
when I run ``pyarmor register`` I get all the dev license info.

But if I delete pyarmor from the environment and reinstall it, doing `pyarmor register` (without any license) I get the same info as above.

How could I unregister in the package?

I expected something like `pyarmor register --cancel` or the like

**Comment by jondy** [comment]
Please remove the whole folder `~/.pyarmor`, more information please refer to 
https://pyarmor.readthedocs.io/en/latest/installation.html

**Comment by gianfa** [comment]
It worked. Thank you
