### ISSUE TITLE
cannot obfuscate a single file

### ISSUE THREAD

**Issue by tanzerlana** [dashingsoft/pyarmor#852]
Hello!

i have a project with many files, but would like to obfuscate a single, small file. 

I run the comand "pyarmor obfuscate myfile.py" but it starts obfuscating all files, not just this one, and then goes in error that it is too big due to the number of files. what am I missing?

also, one thing is not entirely clear to me: am I right that the unlicensed trial version is bossible to be unobfuscated with any license file, whilst the licensed version can be unobfuscated only with the correct license file?

**Comment by jondy** [comment]
Pease read the documentation.

**Comment by tanzerlana** [comment]
well. that is what I did, but I did not understand those two points.. else i wouldnt have asked and marked it as a question..
