### ISSUE TITLE
[BUG] pack command fails when passing the --upx-dir command to PyInstaller

### ISSUE THREAD

**Issue by klooto** [dashingsoft/pyarmor#853]
When calling the command

```
pyarmor pack
```

and passing the PyInstaller command ***--upx-dir***  via the ***-e*** argument, the packer will fail with the following error: 

```
makespec.py: error: unrecognized arguments: --upx-dir
```

This only happens specifically when using the ***--upx-dir*** command, other commands are fine.

I have already found this [answer](https://issueantenna.com/repo/dashingsoft/pyarmor/issues/700#comments) (which I can completely relate to), but still it would be way more convenient so be able to use the ***--upx-dir*** argument directly when calling pyarmor

**Comment by jondy** [comment]
First run `pyinstaller` with this option directly, make sure it works.
