### ISSUE TITLE
After Upgrading to Python3.9 from Python3.8, the obfuscated scripts are failing with License error

### ISSUE THREAD

**Issue by saurabht85** [dashingsoft/pyarmor#856]
Hi @jondy,

I have a running application that is obfuscated with Pyarmor. Have a valid Pyarmor license.

We upgraded the Python version from 3.8 to 3.9 and also updated the pytransform .so lib file.

After that, we obfuscated the scripts again, but not they are filing with the below error:

Step 42/46 : RUN /usr/bin/python3 /script/backup_util.py -c backup_policy.cfg --sched
 ---> Running in e32be17b8ed0
Traceback (most recent call last):
  File "/script/backup_util.py", line 2, in <module>
    from pytransform import pyarmor
  File "/cnm/cnm_db/src/pytransform/__init__.py", line 1, in <module>
    from .pytransform import pyarmor
RuntimeError: Initialize license failed

please help to resolve this issue. The same works well on python3.8.

**Comment by saurabht85** [comment]
@jondy kindly look into the issue above. It has impacted our production deployment

**Comment by jondy** [comment]
Do you check the common solutions in the online documentation?

**Comment by saurabht85** [comment]
> Do you check the common solutions in the online documentation?

Yes and the error I am getting is nit present there. I have tried lots of steps but none solves the problem

**Comment by jondy** [comment]
Could you obfuscate a simple hello world script in the fresh folder to test it work or not? If not, please provide the reproduced steps.

**Comment by jondy** [comment]
And which OS and cpu type in this machine? If not use latest pyarmor, try to upgrade pyarmor, before upgrading pyarmor, it's better to check the change logs, especially the incompatible issues.
