### ISSUE TITLE
Check Restrict Mode of Module Failed - After compilation with Nuitka

### ISSUE THREAD

**Issue by Grinchio** [dashingsoft/pyarmor#858]
Hey Jondy

Below is my nuitka build.bat script, trying to build an exe with Nuitka which includes a pyarmor obfuscated module, Helheim. I have the Helheim tar.gz file, how would I include that into my nuitka without getting the "Check restrict mode of module failed" ?

```@echo off

set ENTRY=main.py

python -m nuitka ^
    %ENTRY% ^
    --standalone ^
    --follow-imports ^
    --windows-icon-from-ico=g.ico ^
    --enable-plugin=numpy ^
    --include-module=helheim.pytransform_vax_000061 ^
    --include-package-data=helheim ^
    --include-package-data=cloudscaper ^```
    
         ```
        import helheim
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<C:\Users\ADMINI~1\AppData\Local\Temp\2\ONEFIL~2\helheim__init__.py>", line 2, in <module helheim>
RuntimeError: Check restrict mode of module failed```

**Comment by jondy** [comment]
Please search Nuitka in the online documentation to find solution.

**Comment by Grinchio** [comment]
Would it be possible to repack pyarmor (double pyarmor it basically) with the flags --restrict 0 and --no-cross-protection or would I have to get venom to send me it (would be a lot harder)
