### ISSUE TITLE
Files that are needed after obfuscate txt,yaml,md [Question]

### ISSUE THREAD

**Issue by newaria** [dashingsoft/pyarmor#859]
Some project files are lost after obfuscating.
Like :  yaml, txt, md, html

But I need them. For example, some simple configurations or software implementation guides or html files related to email templates

Note that I do not need to obfuscate these files. I just want these files to remain in the relevant paths in the project after building the project and not be deleted
what's the solution ?

**Comment by jondy** [comment]
Before copy the whole folder to output path, then obfuscate the scripts to overwrite the .py files.
