### ISSUE TITLE
Remove Dashingsoft as a dependency for downloading binaries

### ISSUE THREAD

**Issue by blechatellier** [dashingsoft/pyarmor#86]
Is it possible to move away from dashingsoft.com for downloading binaries? The site is down at the moment and we can't release any obfuscated code.

**Comment by jondy** [comment]
PyArmor will download the binary library once only If there's no desired file found.  It does nothing If the file has been existed. 

This binary file is required to run Pyarmor, and it is different for different platform. There are so many platforms, Pyarmor could not pack all of them into one package.

**Comment by blechatellier** [comment]
I understand how this works, but the file is currently unavailable as
dashingsoft is down. Can you have the binaries hosted on a reliable source?

**Comment by jondy** [comment]
OK, I'll upload them in github soon.

**Comment by jondy** [comment]
Here it is
https://github.com/dashingsoft/pyarmor/releases/download/v5.3.12/platforms.zip

**Comment by blechatellier** [comment]
@jondy awesome thanks!

**Comment by blechatellier** [comment]
@jondy fyi https://downloads.dashingsoft.com/pyarmor/latest/index.json is still down.

**Comment by jondy** [comment]
But the server is on, I try to download it just now
```
wget  https://downloads.dashingsoft.com/pyarmor/latest/index.json --no-check-certificate

--2019-06-07 13:46:31--  https://downloads.dashingsoft.com/pyarmor/latest/index.json
Resolving downloads.dashingsoft.com (downloads.dashingsoft.com)... 119.23.58.77
Connecting to downloads.dashingsoft.com (downloads.dashingsoft.com)|119.23.58.77|:443... connected.
WARNING: The certificate of `downloads.dashingsoft.com' is not trusted.
WARNING: The certificate of `downloads.dashingsoft.com' hasn't got a known issuer.
The certificate's owner does not match hostname `downloads.dashingsoft.com'
HTTP request sent, awaiting response... 200 OK
Length: 5878 (5.7K) [application/json]
Saving to: `index.json'

100%[======================================>] 5,878       --.-K/s   in 0s

2019-06-07 13:46:31 (48.5 MB/s) - `index.json' saved [5878/5878]
```
How about with http schema? 
http://downloads.dashingsoft.com/pyarmor/latest/index.json

**Comment by blechatellier** [comment]
@jondy https://downforeveryoneorjustme.com/downloads.dashingsoft.com

**Comment by jondy** [comment]
Try this url:
```
https://pyarmor.dashingsoft.com/downloads/platforms/index.json
```
` https://downforeveryoneorjustme.com` reports `pyarmor.dashingsoft.com` is up.

**Comment by blechatellier** [comment]
@jondy the url `https://downloads.dashingsoft.com/pyarmor/latest/index.json` is baked in the pyarmor package when running `pyarmor download linux_x86_64`, is there a way to change and release a new version or make the url configurable?

**Comment by jondy** [comment]
Please upgrade v5.3.13, there is a new option `--url` for command `download`, the sample usage for linux x86_64:
```
pyarmor download --url https://pyarmor.dashingsoft.com/downloads/platforms --output linux64 linux_x86_64
```

**Comment by blechatellier** [comment]
@jondy thanks again for the help in making that change, for some reasons we still can't access that URL from within our network but using the custom url pointing to a copy of the binaries on our server.
