### ISSUE TITLE
[Question] Packing one file using pack

### ISSUE THREAD

**Issue by blird** [dashingsoft/pyarmor#860]
My goal is to only pack a single .py file. Looking at the documetation that's done using the --exact flag.

My resulting command looks like this `pyarmor pack -x "--exact updater.py" -e " --onefile" --name Updater updater.py`

But it does not seem to respect the --exact flag and starts to obfuscate all files present in the folder.

**Comment by jondy** [comment]
This is a bug, it will be fixed next version.
