### ISSUE TITLE
[BUG] Syntax Error

### ISSUE THREAD

**Issue by WieszakWare** [dashingsoft/pyarmor#861]
# [ := ] Syntax Error

**Syntax error when obfuscating script**

> Python Version: 3.7.0

![image](https://user-images.githubusercontent.com/111588764/194060674-4ea09fd9-37e0-4860-a09f-fae4da992a71.png)
![image](https://user-images.githubusercontent.com/111588764/194060573-037d49c3-e56c-4824-968a-de6505f88f0b.png)

# EDIT
I replaced this syntax and tried to obfuscate again but it shows:

![image](https://user-images.githubusercontent.com/111588764/194068315-8708ad1a-e698-4fe8-8891-fbdba339f82e.png)

**Comment by jondy** [comment]
Use python3.7 to run the plain script directly, does it work or not?

**Comment by WieszakWare** [comment]
![image](https://user-images.githubusercontent.com/111588764/194612914-ecc5cc17-0415-42b9-8ce3-c428e6f1dd9a.png)

**Comment by WieszakWare** [comment]
![image](https://user-images.githubusercontent.com/111588764/194613288-a1c4aaff-11f0-4b7f-a882-79eaa2d805de.png)
![image](https://user-images.githubusercontent.com/111588764/194613398-d5c9ebfa-2bfb-4f12-8e2e-076ba19364e9.png)
![image](https://user-images.githubusercontent.com/111588764/194613457-9056a7ca-c98a-4bba-a821-0c7e7eabaa0e.png)

**Comment by WieszakWare** [comment]
**I also tried to obfuscate on python3.9 but it's not working too.**
![image](https://user-images.githubusercontent.com/111588764/194616244-88eef378-b7a3-40e0-88ef-de8263545dab.png)
![image](https://user-images.githubusercontent.com/111588764/194616325-ca63ea46-5106-4cd1-abd5-8d3445409c62.png)

**Comment by jondy** [comment]
First check this common solution
https://pyarmor.readthedocs.io/en/latest/questions.html#common-solutions

**Comment by VeNoMouS** [comment]
walrus was not implemented in 3.7 it was only added in 3.8+
