### ISSUE TITLE
[BUG] Python decorator not recognized

### ISSUE THREAD

**Issue by ramanathan831** [dashingsoft/pyarmor#864]
I have a tf python decorator for my function:
Example
```
    @tf.function
    def func(self, step: tf.Tensor):

```
When I obfuscate the code using pyarmor, at runtime, my code behaves as if the decorator was not present. Is this a known issue? How do I circumvent them

**Comment by jondy** [comment]
Pyarmor could work with decorator, you can test it by a simple decorator. 
Please check this
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts

Make sure the decorator `tf.function` doesn't use any feature changed by pyarmor.

**Comment by jondy** [comment]
Pyarmor could work with decorator, you can test it by a simple decorator. 
Please check this
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts

Make sure the decorator `tf.function` doesn't use any feature changed by pyarmor.

**Comment by jacktang** [comment]
I am facing the same problem now. I used python-rq decorator (https://python-rq.org/docs/#the-job-decorator) to submit job and the obfuscated codes would not submit the job at all.
