### ISSUE TITLE
[BUG] _pytransform.dylib of M1 mac asks for code signing when running obfuscated python scripts

### ISSUE THREAD

**Issue by DarisaSupraja** [dashingsoft/pyarmor#865]
I have some python files, which I obfuscated using pyarmor using the below command

**pyarmor obfuscate --no-cross-protection --recursive --platform darwin.x86_64, darwin.aarch64** 

Once the obfuscated scripts are generated, I was able to run the scripts fine in Intel Macs.

When I run the same obfuscated script in M1 mac, I got the below error.

**zsh killed: python3 pythonFileName**

On further researching, found that the _pytransform.dylib of M1 mac(aarch64 version) is expecting a code signing.

Did the code sign using the below command,(in zsh executable file)

**sudo codesign --force --deep --sign - /pathTo _pytransform.dylib**

After Code Signing, running the obfuscated script on M1 mac is going to an infinite run and need to terminate the running process

**pyarmor - version 6.7.2
python - version 3.9.6
Machine - M1 and M1 Pro mac**

**Comment by jondy** [comment]
Please use feature `0` in the Apple M1, in your case, just exchange platform name in option `--platform`, for example
```
pyarmor obfuscate --no-cross-protection --recursive --platform darwin.aarch64,darwin.x86_64
```

For more information, read the cross-platform usage in the chapter "advanced usage" in the online documentation

**Comment by jondy** [comment]
Duplicated of #837
