### ISSUE TITLE
[BUG] Segmentation fault (Core dump) some times

### ISSUE THREAD

**Issue by socyno** [dashingsoft/pyarmor#867]
Python: 3.8.10
Pyarmor: 6.7.2
Encrypt on CentOS Linux 7.9 (target platform linux.x86_64.0, advanced mode 2, restrict mode 0)
Runtime device with Ubuntu Linux  20.04

Lot of encrypted script occurs segmentation fault (Core dump) error some times,  after re-do encrypt and run success.

logs screenshot：
https://github.com/socyno/common-resources/blob/pyarmor-core-dump-log/pyarmor-core-dump-log01.png

 segmentation fault analysis：
https://github.com/socyno/common-resources/blob/pyarmor-core-dump-log/pyarmor-core-dump-log.png

**Comment by jondy** [comment]
It's not correct to combine `--platform linux.x86_64.0` and `--advanced 2`, use `--platform linux.x86_64 --advanced 2`
