### ISSUE TITLE
使用注册码注册之后，加密命令运行失败

### ISSUE THREAD

**Issue by SongyiGao** [dashingsoft/pyarmor#868]
pyarmor版本 : 7.3.0 

注册：

![image](https://user-images.githubusercontent.com/17947507/195769680-918f0aba-a301-4101-8bef-112d2219da76.png)

注册成功验证：

![image](https://user-images.githubusercontent.com/17947507/195769892-37b1f034-f6cc-44cb-859b-8c5f719e4260.png)

加密失败：

![image](https://user-images.githubusercontent.com/17947507/195770166-d96d90fe-ee7e-49ed-9e28-e0d532e83a7b.png)

之前运行是正常的，最近迁移了新的服务器，在新的服务器上不能正常运行了。

**Comment by jondy** [comment]
加密失败的日志显示没有注册成功，请查看在线文档的安装和卸载章节。

**Comment by SongyiGao** [comment]
> 加密失败的日志显示没有注册成功，请查看在线文档的安装和卸载章节。

但是使用pyarmor --version已经显示注册成功了。

![image](https://user-images.githubusercontent.com/17947507/196842451-7115054b-75b7-4b16-9df9-e767f7a0bef6.png)

**Comment by SongyiGao** [comment]
> 加密失败的日志显示没有注册成功，请查看在线文档的安装和卸载章节。

查询注册信息时经常失败，修改DNS解析仍无效：

![image](https://user-images.githubusercontent.com/17947507/196843979-23c0a502-5f1d-4614-a846-56e1b91fb7cd.png)

**Comment by jondy** [comment]
加密的时候也会显示版本信息的，是否有 "trial"？好像你加密的时候不是使用 `pyarmor` 命令，而是直接运行 `pyarmor.py`

**Comment by SongyiGao** [comment]
谢谢，已解决，使用pyarmor download手动下载即可。
