### ISSUE TITLE
Can't exclude a file or path when obfuscating

### ISSUE THREAD

**Issue by blechatellier** [dashingsoft/pyarmor#87]
Running `pyarmor obfuscate --exclude foo/bar --recursive --no-bootstrap  --output bar foo` still obfuscates files in that folder.

`PyArmor Version 5.3.8`

**Comment by jondy** [comment]
Generally, the arguments in command `obfuscate` should be a script filename other than a path. If you would obfuscate a path without entry script, it's better by the option `--src`
```
pyarmor obfuscate --exclude bar --recursive --output bar --src foo
```
It will obfuscate all the `.py` files in the path `foo` recursively, exclude the path `foo/bar`, and save the obfuscated scripts in the path `bar`

The common usage for `obfuscate` is like this, assume entry script is `/path/to/src/foo.py` and the path `/path/to/src/tests', `/path/to/src/bar` need to be exclude
···
cd /path/to/src
pyarmor obfuscate --recursive --exclude "tests,bar" --output obf foo.py
···

This command will obfuscate all the `.py` files in the `/path/to/src` and exclude `tests` and `bar`, note that the output path will be excluded automatically.

**Comment by blechatellier** [comment]
@jondy I must be doing some wrong but I can't seem to run:
`pyarmor obfuscate --exclude bar --recursive --output bar --src foo`

This still obfuscates the files in the bar folder.

**Comment by jondy** [comment]
Suppose the source folder like this:
```
foo/
foo/script.py
foo/bar
```
This command `pyarmor obfuscate --recursive --exclude bar --output obf foo/script.py` should obfuscate all the `.py` files in the path `foo` except `foo/bar`, the obfuscated scripts will be saved in the path `./obf`.

Nothe that the exclude path is relative the path of entry script, not relative to the current path.

Does it work in your case? If it still doesn't work, could you show the output of this command in the console?

**Comment by mohammad-aqajani** [comment]
how can I use "--exclude venv" with "pyarmor build" command?

**Comment by jondy** [comment]
@mohammad-aqajani 
Config project with `pyarmor config --manifest "global-include *.py, prune venv`, then build the project

Refer to the examples in the https://pyarmor.readthedocs.io/en/latest/man.html#config
