### ISSUE TITLE
[BUG] Script execution may fail when importing modules under the folder with __init__.py in a specific order

### ISSUE THREAD

**Issue by irreg** [dashingsoft/pyarmor#870]
## File structure:
root
- main.py
- a
  - \_\_init\_\_.py
  - b.py
  - c.py
  - d
    - e.py

### Description of main.py
import a.d.e

### Description of e.py
import a.b
import a.c

### Other files(__init__py, b.py, c.py)
empty file (or may have arbitrary description)

## Encryption command
pyarmor obfuscate --restrict=101 --recursive main.py

## Execution result of main.py
Traceback (most recent call last):
  File "<main.py>", line 3, in <module>
  File "<frozen main>", line 1, in <module>
  File "<C:\pyarmor_test\dist\a\d\e.py>", line 1, in <module>
  File "<frozen a.d.e>", line 2, in <module>
ModuleNotFoundError: No module named 'a.c'; 'a' is not a package

## Other conditions for occurrence
- __init__.py must exist
- Restrict Mode 100+ must be specified
- e.py is placed in a deeper hierarchy than b.py and c.py.
- e.py imports multiple modules in the hierarchy below a

## Environment
Windows10/11
python 3.8
pyarmor 7.7.0

**Comment by jondy** [comment]
I'll check it.

**Comment by heibaidaolx123** [comment]
I have the same problem.
Any update?

**Comment by heibaidaolx123** [comment]
@irreg 
Hi, have you found  a walkaround?

**Comment by irreg** [comment]
> @irreg Hi, have you found a walkaround?

Currently, no other method has been found except to delete everything in the __init__ file. All statements in the __init__ file have been moved to a file other than __init__ and all imports have been followed.

**Comment by jondy** [comment]
The restrict mode 100+ changes the behaviors of `__dict__` of module, it may result in some unexpected errors. I have checked the source, but still not found the reason, and it may not be fixed in restrict mode 100+.
