### ISSUE TITLE
Please ADD X86 Support

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#872]
Hello Jondy. 
I am using Windows + Python 3.7 version (x86) and clang compiler. It requires x64 python.
Please add support to compile and run with python 3.7 x86 version using spp mode. 
( https://pyarmor.readthedocs.io/en/latest/mode.html#super-plus-mode )

Thanks!

**Comment by jondy** [comment]
spp mode for armv7 and x86 is in plan, but it may be implemented next year.

**Comment by pauloswear** [comment]
Thanks jondy! I will be waiting to upgrade to SPP. It will work with python 3.7 versions or only with most recent versions ? (3.9+)

**Comment by jondy** [comment]
spp mode will work with Python 3.7+

**Comment by pauloswear** [comment]
Thanks, i'll be waiting

**Comment by pauloswear** [comment]
Hello Jondy, this still on the plans for 2023?

**Comment by jondy** [comment]
There is a little change, SPP mode may not support X86,  and only fix bugs from pyarmor 8.0.

There is new BCC mode, which is an enhancement of SPP mode, is introducted in next major version 8.0. It will support X86 and armv7.

**Comment by pauloswear** [comment]
It`s ok. Is there a forecast to release the BCC mode?

**Comment by jondy** [comment]
Here it is a simple release plan
https://github.com/dashingsoft/pyarmor#release-plan
