### ISSUE TITLE
[BUG] __name__ attribute of some modules disappears when calling a function that changes global variables in another file

### ISSUE THREAD

**Issue by irreg** [dashingsoft/pyarmor#874]
### File structure:
root
- main.py
- a.py

### Description of main.py
```py
import sys
from a import test

test()

for module in sys.modules.values():
    module.__name__
```

### Description of a.py
```py
def test():
    global b
    b = 0
```

### Encryption command
pyarmor obfuscate --restrict=101 --recursive main.py

### Execution result of main.py
```
Traceback (most recent call last):
  File "<main.py>", line 3, in <module>
  File "<frozen main>", line 7, in <module>
AttributeError: module has no attribute '__name__'
```

### Other conditions for occurrence
Restrict Mode 100+ must be specified
main.py calls a function in another file that changes global variables

### Environment
Windows10/11
python 3.8
pyarmor 7.7.0

**Comment by jondy** [comment]
I have reproduced the issue #870, both of them is related to restrict mode 100+. I need some time to find the reason.

**Comment by jondy** [comment]
Do not fixed restrict mode 100+ now, please upgrade to Pyarmor 8.0+ for highest security.
