### ISSUE TITLE
（--advanced 2）

### ISSUE THREAD

**Issue by yunkai-jia** [dashingsoft/pyarmor#875]
我使用--advanced 2，但是获取了pytransform.so，报了这个错误。
       ImportError: cannot import name 'pyarmor' from 'pytransform' (/Users/jiayunkai/Desktop/sh-railway-911-algo-a/pytransform/__init__.py)

**Comment by jondy** [comment]
删除整个的输出目录, 然后重新加密脚本。

**Comment by yunkai-jia** [comment]
好的老师，已经删除了！
       现在是加密到M1电脑上，启动脚本是没有反应













在 2022-10-27 19:45:58，"Jondy" ***@***.***> 写道：

删除整个的输出目录, 然后重新加密脚本。

**Comment by yunkai-jia** [comment]
如果我在mac的x86_64加密了aarch64的，但是发现在m1上面启动是没有反应的是怎么回事呀

**Comment by jondy** [comment]
使用 feature 0 进行加密，在高级用法里面查找跨平台发布的使用方法。
