### ISSUE TITLE
[BUG]ERROR    Extra data: line 26 column 1 (char 590)

### ISSUE THREAD

**Issue by George191** [dashingsoft/pyarmor#876]
(.venv) George@MacBook-Pro octopus-interface % pyarmor licenses --expired 2019-01-01 r001
INFO     PyArmor Version 7.7.0
INFO     Python 3.7.0
INFO     Generate licenses for project  ...
ERROR    Extra data: line 26 column 1 (char 590)

(.venv) George@MacBook-Pro octopus-interface % pyarmor licenses --expired "2019-01-01" r001
INFO     PyArmor Version 7.7.0
INFO     Python 3.7.0
INFO     Generate licenses for project  ...
ERROR    Extra data: line 26 column 1 (char 590)

**Comment by jondy** [comment]
What's the output with debug flag?
```
pyarmor -d licenses --expired 2019-01-01 r001
```
