### ISSUE TITLE
Cant compile py file[BUG]

### ISSUE THREAD

**Issue by guno1928** [dashingsoft/pyarmor#877]
im trying to compile a script and getting a error for windows

INFO     ==================== Run command ====================
INFO     PyArmor Version 7.7.0
INFO     Python 3.10.8
INFO     Target platforms: ['windows.x86_64']
ERROR    No available dynamic library for windows.x86_64 with features ['25']
ERROR    Run command failed

i have never had this problem before ???

![image](https://user-images.githubusercontent.com/44768683/200488617-922a10f5-fc9e-4c6d-8c47-16f3c473b1a5.png)

**Comment by jondy** [comment]
Python3.10 doesn't work with `--advanced 4`
