### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by heibaidaolx123** [dashingsoft/pyarmor#879]
Hi, 
I tried to use pyarmor to obfuscate my python code,
The command I used is:
`pyarmor obfuscate --recursive --output dist/ xxxxx/__init__.py`,
and the obfuscated code is in dist/ as expected.

But after I imported the modules, I could check all the name of classes, 
instantiate all the classes, see all the data members and call all functions of the class,
if I release the obfuscated code, it seems most information of the code will not be hidden by pyarmor.

Did I use pyarmor correctly? How to hide the code while keep it runable?

**Comment by heibaidaolx123** [comment]
Sorry, I forgot the title...

**Comment by jondy** [comment]
Please search `restrict mode` in the online documentation.

**Comment by heibaidaolx123** [comment]
@jondy Thanks, that's exactly what I want.
But, I cann't make it by taking the steps described in doc.
My code in the dir is like:
`
__init__.py
lib.py
utils/
|----a.py
|----b.py
dependencies/
|----c.py
`
the __init__,py is empty, and lib.py is the functions and classess that I want to release, which can be impoted.
When I use `pyarmor obfuscate --recursive --output dist/ ./__init__.py` to obf the code and test it by `from dist.lib import Solver`, everything is OK.
But when I try the command with restrict mode for a lib as described in the [doc](https://pyarmor.readthedocs.io/en/latest/advanced.html#improving-the-security-by-restrict-mode):
`
pyarmor obfuscate --output dist/ --exact __init__.py lib.py
pyarmor obfuscate --output dist/ --restrict 4 --recursive --exclude __init__.py --exclude lib.py .
`
and run `from dist.lib import Solver`, I got this:
`
    from pytransform import pyarmor_runtime
ModuleNotFoundError: No module named 'pytransform'
`
How can i fix this?

**Comment by jondy** [comment]
Refer to
https://pyarmor.readthedocs.io/en/latest/questions.html

**Comment by heibaidaolx123** [comment]
> Refer to https://pyarmor.readthedocs.io/en/latest/questions.html

@jondy Thanks for you quick reply.

**Comment by jondy** [comment]
I think it's not restrict mode problem. You can do a test with a simple script in an empty path.

**Comment by heibaidaolx123** [comment]
> I think it's not restrict mode problem. You can do a test with a simple script in an empty path.

I did a test in an empty path, and the problem still existed.
The structure of the dir:
```
~/test1
|----__init__.py
|----lib.py
|----utils.py
```
__init__.py is empty, and blow are lib.py and utils.py:
```
# lib.py
from utils import Util

class Solver():
 def __init__(self):
  self.util = Util("Solver")
  self.util.print("init")
 def solve(self):
  self.util.print("solve")
```
```
# utils.py
class Util():
 def __init__(self, name="name"):
  self.name=name

 def print(self, msg):
  print("{}: {}".format(self.name, msg))
```
and the test code is :
```
from dist.lib import Solver
solver=Solver()
solver.solve()
```

## Test without restrict mode
The obf cmd with no restrict mode:
```
pyarmor obfuscate --recursive --output dist/ ./__init__.py
```
and the output of the test code :
```
Solver: init
Solver: solve
```

## Test with restrict mode
The obf cmd with restrict mode:
```
pyarmor obfuscate --output dist/ --exact __init__.py lib.py
pyarmor obfuscate --output dist/ --restrict 4 --recursive --exclude __init__.py --exclude lib.py .
```
and the output of the test code :
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from dist.lib import Solver
  File "/home/xxx/test1/dist/lib.py", line 1, in <module>
    from pytransform import pyarmor_runtime
ModuleNotFoundError: No module named 'pytransform'

```

**Comment by heibaidaolx123** [comment]
My fault. The problem is solved, and it's path related.
Thanks a lot.

**Comment by jondy** [comment]
Refer to man page of command `obfuscate`, try to using option `--bootstrap` for package
