### ISSUE TITLE
maybe _pytransform.dll for maya is outdated

### ISSUE THREAD

**Issue by LittleDoggy** [dashingsoft/pyarmor#88]
I am trying to bind hdinfo for maya python scripts.

When I import the script in the cmd window,it works well:

`python -c "import ezAnim"`

When I import the scripts in maya , it always throws an error:

`License is not for this machine
Error: SystemExit: file C:/Users/USER/Documents/maya/scripts\ezAnim\dist\pytransform.py line 214: 1 ` 

It's been bothering me for a long time.
When import ezAnim in maya , I will replace the _pytransform.dll with the special dll for maya,it was downloaded from :

[https://github.com/dashingsoft/pyarmor/issues/37](url)

I can not figure out this problem for now.
Maybe _pytransform.dll for maya is outdated?

If so it is,would you please spare a little time to build a maya`s  _pytransform.dll for latest pyarmor version ?

**Comment by jondy** [comment]
The dll is latest, but maybe you need generate a new license if the license is bind to hard disk. Something is changed to get the serial number of hard disk in latest `_pytransform.dll`.

And if the obfuscated scripts are used by Maya, it's better obfuscate the script with 
http://pyarmor.dashingsoft.com/downloads/platforms/vs2015/x86/_pytransform.dll 
or
http://pyarmor.dashingsoft.com/downloads/platforms/vs2015/x64/_pytransform.dll 

Just download it to the installed path of PyArmor, then obfuscate the scripts.

**Comment by LittleDoggy** [comment]
I replaced these dlls.

`python -c "import ezAnim"` in the cmd window works well.

When import "ezAnim" in Maya, every license can still be distinguished correctly ,even if these hdinfos are 
very similar.

I will keep this Pyarmor version ,since it is stable for me for now.

At last, I really appreciate your help!
