### ISSUE TITLE
[Question] Multiple packages

### ISSUE THREAD

**Issue by heibaidaolx123** [dashingsoft/pyarmor#881]
Hi, 
I hava 2 python pakcages,say, A and B, and A uses code in B.
I want to obf A with default mode and obf B with restrict mode 104.
And I want the 2 package to use the same run time package.
How can I do it? I didn't find a detailed solution in  the doc.
Thanks.

**Comment by heibaidaolx123** [comment]
Let's say I have 2 dirs: A and B.
The command I used is:
pyarmor obfuscate --recursive --output dist/A A/__init__.py
pyarmor obfuscate --recursive --no-runtime --output dist/B B/__init__.py
pyarmor obfuscate --no-runtime --recursive --restrict 104 --output dist/B --exclude __init__.py --exclude interface.py B/
As you can see, not all the files in B need to be obf by 104 mode, some of them are interface, which will be used by users.
The commands generate pytransform in A, but B needed it too.
I tried copying pytransform dir from A to B, and the code will complain.
Any idea?

**Comment by jondy** [comment]
Refer to
http://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts
