### ISSUE TITLE
单文件加密打包报错

### ISSUE THREAD

**Issue by lucky-zwx** [dashingsoft/pyarmor#882]
`PS D:\kali测试\hunxiao> pyarmor pack -e " --onefile" -x " --advanced 5" main.py
INFO     PyArmor Version 7.7.1
INFO     Python 3.7.9
INFO     Prepare to pack obfuscated scripts with PyInstaller...
INFO     entry script: main.py
INFO     src for searching scripts: .
INFO     build path: dist\obf
INFO     Run PyArmor to obfuscate scripts...
INFO

"d:\program files\python37\python.exe" C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\pyarmor\pyarmor.py obfuscate -O dist\obf --package-runtime 0 --exclude dist -r --advanced 5 .\main.py    

INFO     ==================== Run command ====================
INFO     PyArmor Version 7.7.1
INFO     Python 3.7.9
INFO     Target platforms: Native
INFO     Remove cached platform list file C:\Users\lenovo\.pyarmor\platforms\index.json
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r52.6/index.json
INFO     Write cached platform list file C:\Users\lenovo\.pyarmor\platforms\index.json
INFO     Update target platforms to: ['windows.x86_64.11.py37']
INFO     Source path is "D:\kali测试\hunxiao"
INFO     Entry scripts are ['.\\main.py']
INFO     Use cached capsule C:\Users\lenovo\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Exclude path "dist"
INFO     Auto exclude output path "dist\obf"
WARNING  no previously-included directories found matching 'dist'
WARNING  no previously-included directories found matching 'dist\obf'
INFO     Save obfuscated scripts to "dist\obf"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Obfuscate string value is False
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 2
INFO     Super mode is True
INFO     Super plus mode is enabled
INFO     Generating super runtime library to "dist\obf"
INFO     The platform windows.x86_64.11.py37 is out of date
INFO     Search library for platform: windows.x86_64.11.py37
INFO     Found available libraries: ['windows.x86_64.11.py37']
INFO     Target path for windows.x86_64.11.py37: C:\Users\lenovo\.pyarmor\platforms\windows\x86_64\11\py37
INFO     Downloading library file for windows.x86_64.11.py37 ...
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r52.6/windows.x86_64.11.py37/pytransform.pyd
INFO     Writing target file: C:\Users\lenovo\.pyarmor\platforms\windows\x86_64\11\py37\pytransform.pyd
INFO     Download dynamic library windows.x86_64.11.py37 OK
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Update capsule to add default license file
INFO     Copying C:\Users\lenovo\.pyarmor\platforms\windows\x86_64\11\py37\pytransform.pyd
INFO     Patch extension dist\obf\pytransform.pyd
INFO     Patch library file OK
INFO     Generate runtime files OK
INFO     Use protection template: C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\pyarmor\protect_code2.pt
INFO     Start obfuscating the scripts...
INFO            main.py -> dist\obf\main.py
INFO     Patch this entry script with protection code
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/spp/r4/windows.x86_64/sppmode.dll
INFO     Downloading sppmode library for "windows.x86_64" ...
INFO     Writing target file: C:\Users\lenovo\.pyarmor\sppmode.dll
INFO     Writing version file: C:\Users\lenovo\.pyarmor\.sppver
INFO     Download sppmode library "windows.x86_64" OK
INFO     Generating spp code for <frozen main> ...
INFO     Generate module spp code successfully
INFO     Compiling spp code ...
INFO     Compile spp code successfully
INFO     Obfuscate 1 scripts OK.
INFO     ==================== End command ====================

INFO     Create temp path: dist\obf\temp
INFO     Found runtime module pytransform.pyd
INFO     Copy dist\obf\pytransform.pyd to temp path
                   [--hidden-import MODULENAME]
                   [--collect-submodules MODULENAME]
                   [--collect-data MODULENAME] [--collect-binaries MODULENAME]
                   [--collect-all MODULENAME] [--copy-metadata PACKAGENAME]
                   [--recursive-copy-metadata PACKAGENAME]
                   [--additional-hooks-dir HOOKSPATH]
                   [--runtime-hook RUNTIME_HOOKS] [--exclude-module EXCLUDES]
                   [--key KEY] [--splash IMAGE_FILE]
                   [-d {all,imports,bootloader,noarchive}]
                   [--python-option PYTHON_OPTION] [-s] [--noupx]
                   [--upx-exclude FILE] [-c] [-w]
                   [-i <FILE.ico or FILE.exe,ID or FILE.icns or Image or "NONE">]
                   [--disable-windowed-traceback] [--version-file FILE]
                   [-m <FILE or XML>] [--no-embed-manifest] [-r RESOURCE]
                   [--uac-admin] [--uac-uiaccess] [--win-private-assemblies]
                   [--win-no-prefer-redirects] [--argv-emulation]
                   [--osx-bundle-identifier BUNDLE_IDENTIFIER]
                   [--target-architecture ARCH] [--codesign-identity IDENTITY]
                   [--osx-entitlements-file FILENAME] [--runtime-tmpdir PATH]
                   [--bootloader-ignore-signals] [--log-level LEVEL]
                   scriptname [scriptname ...]
makespec.py: error: unrecognized arguments: .\main.py
ERROR    Run command failed
`

**Comment by lucky-zwx** [comment]
`pyarmor pack -x " --advanced 5" main.py`可以正常工作

**Comment by jondy** [comment]
这是命令行参数的使用问题，注意 `-e` 后面的参数前要有空格，并且双引号必须是英文的引号

**Comment by lucky-zwx** [comment]
> 

参数空格和双引号都是没有问题的

**Comment by jondy** [comment]
已经解决，预发布版在这里
`pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-7.7.2.zip`

**Comment by lucky-zwx** [comment]
虽然不报错，但是单文件生成并不管用，生成的是目录模式
`G:\oop>pyarmor pack -e " --onefile" -x " --advanced 5" main.py
INFO     PyArmor Version 7.7.2
INFO     Python 3.7.9
INFO     Prepare to pack obfuscated scripts with PyInstaller...
INFO     entry script: main.py
INFO     src for searching scripts: .
INFO     build path: dist\obf
INFO     Run PyArmor to obfuscate scripts...
INFO

"d:\program files\python37\python.exe" C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\pyarmor\pyarmor.py obfuscate -O dist\obf --package-runtime 0 --exclude dist -r --advanced 5 .\main.py


INFO     ==================== Run command ====================
INFO     PyArmor Version 7.7.2
INFO     Python 3.7.9
INFO     Target platforms: Native
INFO     Update target platforms to: ['windows.x86_64.11.py37']
INFO     Source path is "G:\oop"
INFO     Entry scripts are ['.\\main.py']
INFO     Use cached capsule C:\Users\lenovo\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Exclude path "dist"
INFO     Auto exclude output path "dist\obf"
WARNING  no previously-included directories found matching 'dist'
WARNING  no previously-included directories found matching 'dist\obf'
INFO     Save obfuscated scripts to "dist\obf"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Obfuscate string value is False
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 2
INFO     Super mode is True
INFO     Super plus mode is enabled
INFO     Generating super runtime library to "dist\obf"
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying C:\Users\lenovo\.pyarmor\platforms\windows\x86_64\11\py37\pytransform.pyd
INFO     Patch extension dist\obf\pytransform.pyd
INFO     Patch library file OK
INFO     Generate runtime files OK
INFO     Use protection template: C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\pyarmor\protect_code2.pt
INFO     Start obfuscating the scripts...
INFO            main.py -> dist\obf\main.py
INFO     Patch this entry script with protection code
INFO     Generating spp code for <frozen main> ...
INFO     Generate module spp code successfully
INFO     Compiling spp code ...
INFO     Compile spp code successfully
INFO     Obfuscate 1 scripts OK.
INFO     ==================== End command ====================

INFO     Create temp path: dist\obf\temp
INFO     Found runtime module pytransform.pyd
INFO     Copy dist\obf\pytransform.pyd to temp path
INFO     Run PyInstaller to generate .spec file...
INFO

"d:\program files\python37\python.exe" -m PyInstaller.utils.cliutils.makespec --hidden-import pytransform --additional-hooks-dir dist\obf\temp .\main.py


INFO     ==================== Run command ====================
Wrote G:\oop\main.spec.
Now run pyinstaller.py to build the executable.
INFO     ==================== End command ====================

INFO     Save .spec file to main.spec
INFO     Generate hook script: dist\obf\temp\hook-pytransform.py
INFO     Patching .spec file...
INFO     Save patched .spec file to main-patched.spec
INFO     Run PyInstaller with patched .spec file...
INFO

"d:\program files\python37\python.exe" -m PyInstaller --distpath dist -y --clean main-patched.spec


INFO     ==================== Run command ====================
316 INFO: PyInstaller: 5.6.2
316 INFO: Python: 3.7.9
316 INFO: Platform: Windows-10-10.0.22621-SP0
316 INFO: UPX is not available.
316 INFO: Removing temporary files and cleaning cache in C:\Users\lenovo\AppData\Local\pyinstaller
331 INFO: Extending PYTHONPATH with paths
['G:\\oop']
824 INFO: checking Analysis
824 INFO: Building Analysis because Analysis-00.toc is non existent
824 INFO: Initializing module dependency graph...
824 INFO: Caching module graph hooks...
867 INFO: Analyzing base_library.zip ...
2939 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\lenovo\\AppData\\Roaming\\Python\\Python37\\site-packages\\PyInstaller\\hooks'...
3771 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\lenovo\\AppData\\Roaming\\Python\\Python37\\site-packages\\PyInstaller\\hooks'...
3813 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\lenovo\\AppData\\Roaming\\Python\\Python37\\site-packages\\PyInstaller\\hooks'...
4743 INFO: Caching module dependency graph...
4870 INFO: running Analysis Analysis-00.toc
4870 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by d:\program files\python37\python.exe
4996 INFO: Analyzing G:\oop\main.py
5025 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\lenovo\\AppData\\Roaming\\Python\\Python37\\site-packages\\PyInstaller\\hooks'...
5109 INFO: Analyzing hidden import 'pytransform'
5137 INFO: Processing module hooks...
5166 INFO: checking Tree
5166 INFO: Building Tree because Tree-00.toc is non existent
5166 INFO: Building Tree Tree-00.toc
5166 INFO: Looking for ctypes DLLs
5166 INFO: Analyzing run-time hooks ...
5166 INFO: Including run-time hook 'C:\\Users\\lenovo\\AppData\\Roaming\\Python\\Python37\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
5166 INFO: Looking for dynamic libraries
281 INFO: Extra DLL search directories (PATH): ['C:\\Users\\lenovo\\AppData\\Roaming\\Python\\Python37\\site-packages\\pywin32_system32', 'D:\\Program Files\\Python37\\Scripts\\', 'D:\\Program Files\\Python37\\', 'D:\\Program Files (x86)\\VMware\\VMware Workstation\\bin\\', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\libnvvp', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3\\libnvvp', 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'C:\\Program Files\\Go\\bin', 'C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin', 'C:\\Program Files\\dotnet\\', 'C:\\Program Files (x86)\\ZeroTier\\One\\', 'C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.2.0\\', 'D:\\Download\\COLMAP-3.7-windows-cuda\\COLMAP-3.7-windows-cuda', 'D:\\Download\\ffmpeg-2022-06-12-git-4d45f5acbd-full_build\\bin', 'D:\\Program Files\\010 Editor', 'C:\\Program Files\\Git\\cmd', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\WINDOWS\\System32\\OpenSSH\\', 'D:\\Go\\bin', 'C:\\Program Files\\PowerShell\\7\\', 'C:\\Users\\lenovo\\AppData\\Roaming\\Python\\Python37\\Scripts', 'C:\\Users\\lenovo\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\lenovo\\AppData\\Local\\Programs\\Fiddler', 'C:\\Users\\lenovo\\AppData\\Local\\Programs\\Microsoft VS Code\\bin', 'C:\\Users\\lenovo\\go\\bin', 'C:\\Users\\lenovo\\.dotnet\\tools', 'D:\\Program Files\\CMake\\bin', 'C:\\Users\\lenovo\\AppData\\Local\\JetBrains\\Toolbox\\scripts', '%USERPROFILE%\\AppData\\Local\\Microsoft\\WindowsApps']
6352 INFO: Looking for eggs
6352 INFO: Using Python library d:\program files\python37\python37.dll
6352 INFO: Found binding redirects:
[]
6352 INFO: Warnings written to G:\oop\build\main-patched\warn-main-patched.txt
6366 INFO: Graph cross-reference written to G:\oop\build\main-patched\xref-main-patched.html
6395 INFO: checking PYZ
6395 INFO: Building PYZ because PYZ-00.toc is non existent
6395 INFO: Building PYZ (ZlibArchive) G:\oop\build\main-patched\PYZ-00.pyz
6622 INFO: Building PYZ (ZlibArchive) G:\oop\build\main-patched\PYZ-00.pyz completed successfully.
6622 INFO: checking PKG
6622 INFO: Building PKG because PKG-00.toc is non existent
6622 INFO: Building PKG (CArchive) main.pkg
6649 INFO: Building PKG (CArchive) main.pkg completed successfully.
6649 INFO: Bootloader C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
6649 INFO: checking EXE
6649 INFO: Building EXE because EXE-00.toc is non existent
6649 INFO: Building EXE from EXE-00.toc
6649 INFO: Copying bootloader EXE to G:\oop\build\main-patched\main.exe.notanexecutable
6706 INFO: Copying icon to EXE
6706 INFO: Copying icons from ['C:\\Users\\lenovo\\AppData\\Roaming\\Python\\Python37\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
6749 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
6749 INFO: Writing RT_ICON 1 resource with 3752 bytes
6749 INFO: Writing RT_ICON 2 resource with 2216 bytes
6749 INFO: Writing RT_ICON 3 resource with 1384 bytes
6749 INFO: Writing RT_ICON 4 resource with 37019 bytes
6749 INFO: Writing RT_ICON 5 resource with 9640 bytes
6749 INFO: Writing RT_ICON 6 resource with 4264 bytes
6749 INFO: Writing RT_ICON 7 resource with 1128 bytes
6763 INFO: Copying 0 resources to EXE
6763 INFO: Embedding manifest in EXE
6763 INFO: Updating manifest in G:\oop\build\main-patched\main.exe.notanexecutable
6805 INFO: Updating resource type 24 name 1 language 0
6805 INFO: Appending PKG archive to EXE
6834 INFO: Fixing EXE headers
7032 INFO: Building EXE from EXE-00.toc completed successfully.
7032 INFO: checking COLLECT
7032 INFO: Building COLLECT because COLLECT-00.toc is non existent
7032 INFO: Building COLLECT COLLECT-00.toc
7414 INFO: Building COLLECT COLLECT-00.toc completed successfully.
INFO     ==================== End command ====================

INFO     Remove .spec file main.spec
INFO     Remove patched .spec file main-patched.spec
INFO     Remove build path dist\obf
INFO     Final output path: dist
INFO     Pack obfuscated scripts successfully.`

**Comment by jondy** [comment]
下面的这个命令能成功执行吗？
```
"d:\program files\python37\python.exe" -m PyInstaller.utils.cliutils.makespec --onefile main.py
```

**Comment by jondy** [comment]
在最新版本 7.7.3 中解决
