### ISSUE TITLE
[Question] In the licensed version is there a limit to the file size that pyarmor can obfuscate and pack?

### ISSUE THREAD

**Issue by DoNoRe** [dashingsoft/pyarmor#887]
In the licensed version is there a limit to the file size that pyarmor can obfuscate and pack (using the following command):

pyarmor pack --clean --without-license -x " --advanced 2 --exclude tests --exclude copy_license.py" -e " --onefile --noconsole --icon favicon.ico --add-data 'splash.png;.' --runtime-hook copy_license.py" main.py

I know there is a hard limit of ~30kB per file in the trial version. It is not clear if there is such a limitation on the licensed version.

**Comment by jondy** [comment]
There is no size limitation in the licensed version. More information refer to
http://pyarmor.readthedocs.io/en/latest/license.html

**Comment by DoNoRe** [comment]
Thank you Jondy.
