### ISSUE TITLE
Pyarmor for two entries?

### ISSUE THREAD

**Issue by jacktang** [dashingsoft/pyarmor#888]
Hi, 

Pyarmor 支持2个入口的项目或者程序吗？我的项目组成是flask app，加上一个job worker。目录结构如下

```
lib
+---- foo.py
|----- bar.py
app.py
worker.py
```

`app.py` 和 `worker.py` 会共用lib下面的内容。
在生产环境中会分别去运行
`python3 app.py` 和 `python3 worker.py`

**Comment by jondy** [comment]
支持的，命令行列出的所有的脚本都会被作为入口脚本的，更多信息请参考文档
http://pyarmor.readthedocs.io/zh/latest/understand-obfuscate…

**Comment by jacktang** [comment]
@jondy 上面的链接打不开，能更新下吗？

**Comment by jondy** [comment]
试一下不就知道了。

**Comment by jondy** [comment]
readthedocs.io 是第三方网站，多试几次应该能打开，或者把下面的解析地址增加到 `/etc/hosts` 里面
`104.17.32.82 pyarmor.readthedocs.io`

**Comment by jacktang** [comment]
我这边看到的链接是 http://pyarmor.readthedocs.io/zh/latest/understand-obfuscate… 。麻烦您检查下，您可能没有把正确的url填写进comment里面

**Comment by jondy** [comment]
抱歉，应该是 https://pyarmor.readthedocs.io/zh/latest/understand-obfuscated-scripts.html

这个是其中的一章的链接，全部的文档都在这里
