### ISSUE TITLE
too long serial number not be recognized

### ISSUE THREAD

**Issue by LittleDoggy** [dashingsoft/pyarmor#89]
I bound a machine info , the disk`s SN is very long(40digits):

`2020202057202d4443573443354e555a4b445339`

It cannot be recognized by the corresponding machine.

So,I need your confirmation:

if this SN is beyond the range of Pyarmor`s valid disk SN length or not?

**Comment by jondy** [comment]
This SN is not like the real SN of hard disk. How does it get?

**Comment by LittleDoggy** [comment]
Got it from cmd window: 

`wmic diskdrive get serialnumber`

Maybe it`s not official original(purchased from TMALL).

The real official product`s SN should be  "WD-xxxxxxxx".

So,latter I will install Python and Pyarmor on that machine, to check out the SN with Pyarmor, and it will take some time.

**Comment by LittleDoggy** [comment]
> This SN is not like the real SN of hard disk. How does it get?

Do you have any tool to check out the SN quickly in the Pyarmor`s way without installing Python and Pyarmor?

**Comment by jondy** [comment]
For windows,

https://pyarmor.dashingsoft.com/downloads/platforms/win32/hdinfo.exe

It should work in 64-bit windows either.

**Comment by LittleDoggy** [comment]
The tool gives me the SN:

`WD-WCC4N5ZUDK9S`

Amazing!

The tool you made is better than windows cmd lines!

I'm sorry to have bothered you so long.

Thank u again!
