### ISSUE TITLE
[Question] Can I use pyarmor's pack with pyinstaller's encryption option safely - i.e. will it cause any code to deobfuscate?

### ISSUE THREAD

**Issue by DoNoRe** [dashingsoft/pyarmor#890]
This is the command I'm working with. It seems to execute fine.

pyarmor pack --clean --without-license -x " --advanced 2 --exclude tests --exclude copy_license.py" -e " --onefile --noconsole --icon icon.ico --add-data 'splash.png;.' --runtime-hook copy_license.py **--key='keystring'** " main.py

As in do you foresee any issues?

My understanding is that pyarmor obfuscates the scripts and pyinstaller will pack them and during packing we can add in pyinstaller options - so in essence the pyarmor obfuscation is separate from packing..am I understanding this correctly from "https://pyarmor.readthedocs.io/en/v7.6.1/man.html#pack"?

**Comment by jondy** [comment]
I don't test pack command with pyinstaller option `--key`, if it works, it's fine. In most of case, the obfuscated scripts could be taken as the original scripts.

**Comment by DoNoRe** [comment]
1. It exits fine. 

2. Is my understanding of the process accurate? Obfuscation and then followed by the pyinstaller packing?

"In most of case, the obfuscated scripts could be taken as the original scripts." to confirm this should I look in the spec file? Or is there a test function? There are no notes on testing the obfuscation in the manual, but the obf/ folder's py files are unreadable - so I'm assuming they are obfuscated.

Thanks Jondy - I appreciate your feedback.

**Comment by jondy** [comment]
This page may be helpful to understand the obfuscated scripts
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html
