### ISSUE TITLE
[BUG] ERROR    exception: access violation reading 0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by KeevoDev** [dashingsoft/pyarmor#891]
when i do
pyarmor obfuscate myfile.py

INFO     PyArmor Trial Version 7.7.3
INFO     Python 3.11.0
INFO     Target platforms: Native
INFO     Source path is "C:\Users\Keevo\Desktop\West TokenGen"
INFO     Entry scripts are ['WestGen.py']
INFO     Use cached capsule C:\Users\Keevo\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Obfuscate string value is False
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying C:\Users\Keevo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Patch library dist\pytransform\_pytransform.dll
INFO     Patch library file OK
INFO     Copying C:\Users\Keevo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            ProxyScraper.py -> dist\ProxyScraper.py
ERROR    exception: access violation reading 0xFFFFFFFFFFFFFFFF

**Comment by jondy** [comment]
python3.11 is still not supported, refer to #873
