### ISSUE TITLE
[BUG]使用约束模式 1和约束模式 4 的加密方式时在Linux.aarch64平台上报错

### ISSUE THREAD

**Issue by LVguomin** [dashingsoft/pyarmor#897]
跨平台使用约束模式1和约束模式4进行加密时，在Linux.aarch64平台上编译完成后，运行报错，但编译后的代码在windows.x86_64 和 linux.x86_64平台上可以正常运行。

以下时加密步骤：
执行加密命令1：
pyarmor obfuscate -O waterFlow_proj/waterFlow --platform windows.x86_64 --platform linux.x86_64 --platform linux.aarch64 --advanced 1 --restrict 1 --exact __init__.py

INFO     PyArmor Version 7.7.0
INFO     Python 3.8.10
WARNING  "--advanced 1" is deprecated for Python 3.8, use "--advanced 2" instead
INFO     Target platforms: ['windows.x86_64', 'linux.x86_64', 'linux.aarch64']
INFO     Update target platforms to: ['windows.x86_64.7', 'linux.x86_64.7', 'linux.aarch64.3']
INFO     Source path is "/mnt/hdisk/opt/watersystem/waterFlow_src"
INFO     Entry scripts are ['__init__.py']
INFO     Use cached capsule /home/khadas/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Exact
INFO     Save obfuscated scripts to "waterFlow_proj/waterFlow"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Obfuscate string value is False
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 1
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to waterFlow_proj/waterFlow/pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Create library path to support multiple platforms: waterFlow_proj/waterFlow/pytransform/platforms
INFO     Copying /home/khadas/.pyarmor/platforms/windows/x86_64/7/_pytransform.dll
INFO     To waterFlow_proj/waterFlow/pytransform/platforms/windows/x86_64
INFO     Patch library waterFlow_proj/waterFlow/pytransform/platforms/windows/x86_64/_pytransform.dll
INFO     Patch library file OK
INFO     Copying /home/khadas/.pyarmor/platforms/linux/x86_64/7/_pytransform.so
INFO     To waterFlow_proj/waterFlow/pytransform/platforms/linux/x86_64
INFO     Patch library waterFlow_proj/waterFlow/pytransform/platforms/linux/x86_64/_pytransform.so
INFO     Patch library file OK
INFO     Copying /home/khadas/.pyarmor/platforms/linux/aarch64/3/_pytransform.so
INFO     To waterFlow_proj/waterFlow/pytransform/platforms/linux/aarch64
INFO     Patch library waterFlow_proj/waterFlow/pytransform/platforms/linux/aarch64/_pytransform.so
INFO     Patch library file OK
INFO     Copying /home/khadas/.local/lib/python3.8/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            /mnt/hdisk/opt/watersystem/waterFlow_src/__init__.py -> waterFlow_proj/waterFlow/__init__.py
INFO     Insert bootstrap code to entry script waterFlow_proj/waterFlow/__init__.py
INFO     Obfuscate 1 scripts OK.

执行加密命令2：
pyarmor obfuscate -O waterFlow_proj/waterFlow --platform windows.x86_64 --platform linux.x86_64 --platform linux.aarch64 --advanced 1 --restrict 4 -recursive --exclude __init__.py .

INFO     PyArmor Version 7.7.0
INFO     Python 3.8.10
WARNING  "--advanced 1" is deprecated for Python 3.8, use "--advanced 2" instead
INFO     Target platforms: ['windows.x86_64', 'linux.x86_64', 'linux.aarch64']
INFO     Update target platforms to: ['windows.x86_64.7', 'linux.x86_64.7', 'linux.aarch64.3']
WARNING  Option --entry has been deprecated
INFO     Source path is "/mnt/hdisk/opt/watersystem/waterFlow_src"
INFO     Entry scripts are ['cursive']
INFO     Use cached capsule /home/khadas/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Exclude pattern "__init__.py"
INFO     Auto exclude output path "waterFlow_proj/waterFlow"
INFO     Save obfuscated scripts to "waterFlow_proj/waterFlow"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Obfuscate string value is False
INFO     Wrap mode is 1
INFO     Restrict mode is 4
INFO     Advanced value is 1
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to waterFlow_proj/waterFlow/pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Create library path to support multiple platforms: waterFlow_proj/waterFlow/pytransform/platforms
INFO     Copying /home/khadas/.pyarmor/platforms/windows/x86_64/7/_pytransform.dll
INFO     To waterFlow_proj/waterFlow/pytransform/platforms/windows/x86_64
INFO     Patch library waterFlow_proj/waterFlow/pytransform/platforms/windows/x86_64/_pytransform.dll
INFO     Patch library file OK
INFO     Copying /home/khadas/.pyarmor/platforms/linux/x86_64/7/_pytransform.so
INFO     To waterFlow_proj/waterFlow/pytransform/platforms/linux/x86_64
INFO     Patch library waterFlow_proj/waterFlow/pytransform/platforms/linux/x86_64/_pytransform.so
INFO     Patch library file OK
INFO     Copying /home/khadas/.pyarmor/platforms/linux/aarch64/3/_pytransform.so
INFO     To waterFlow_proj/waterFlow/pytransform/platforms/linux/aarch64
INFO     Patch library waterFlow_proj/waterFlow/pytransform/platforms/linux/aarch64/_pytransform.so
INFO     Patch library file OK
INFO     Copying /home/khadas/.local/lib/python3.8/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            json2py_Key.py -> waterFlow_proj/waterFlow/json2py_Key.py
INFO            json2token.py -> waterFlow_proj/waterFlow/json2token.py
INFO            main.py -> waterFlow_proj/waterFlow/main.py
INFO            qua_monitor.py -> waterFlow_proj/waterFlow/qua_monitor.py
INFO            utils.py -> waterFlow_proj/waterFlow/utils.py
INFO            vel_monitor.py -> waterFlow_proj/waterFlow/vel_monitor.py
INFO            wl_monitor.py -> waterFlow_proj/waterFlow/wl_monitor.py
INFO            xjjj.py -> waterFlow_proj/waterFlow/xjjj.py
INFO     Obfuscate 8 scripts OK.

加密完成后在linux.aarch64平台上，cd xxx/waterFlow_proj，执行python -c "import waterFlow" 报错：
XXX lineno: 3, opcode: 228
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "</mnt/hdisk/opt/watersystem/waterFlow_src/waterFlow_proj/waterFlow/__init__.py>", line 3, in <module>
  File "<frozen waterFlow_src>", line 3, in <module>
SystemError: unknown opcode

运行环境
python3.8.13
pyarmor 7.7.0

期盼得到您的答复！！

**Comment by jondy** [comment]
不要使用 --advanced 1, 使用 2试试

**Comment by LVguomin** [comment]
使用2会报其他错误，在windows平台上也一样报错
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/hdisk/opt/watersystem/waterFlow_src/waterFlow_proj/waterFlow/__init__.py", line 1, in <module>
    from pytransform import pyarmor
ModuleNotFoundError: No module named 'pytransform'
