### ISSUE TITLE
error on build project

### ISSUE THREAD

**Issue by KomarovAlea** [dashingsoft/pyarmor#9]
I give this tutorial https://github.com/dashingsoft/pyarmor/blob/master/src/user-guide.md
part: "obfuscate odoo module"
make git clone v3.6.1
last commit a736bdc from Feb 27, 2018

I created project by command:
python pyarmor.py init --src=/opt/odoo/addons/my_mod --entry=__init__.py projects/my_mod

my .pyarmor_config:
`{`
`  "version": "1.0.1",`
`  "name": "my_mod",`
`  "title": "my_mod",`
`  "src": "/opt/odoo/addons/my_mod",`
`  "manifest": "global-include *.py, exclude __manifest__.py",`
`  "entry": "__init__.py",`
`  "output": "dist",`
`  "capsule": ".pyarmor_capsule.zip",`
`  "runtime_path": null,`
`  "disable_restrict_mode": true,`
`  "obf_module_mode": "des",`
`  "obf_code_mode": "des",`
`  "build_time": 1519829413.5447803`
`}`
I corrected by hand this config: set up "disable_restrict_mode": true 
and add ", exclude __manifest__.py" to manifest.

Then I build project by command:
`./pyarmor build`
Any errors ,but in building log: INFO     Obfuscate **0** scripts with mode 8
In the 'dist' directory there were **only** files: __init__.py, _pytransform.so, license.lic, product.key, pyshield.key, pyshield.lic and pytransform.py

I went to projects/my_mod and add DEBUG in pyarmor:
/home/jacon/anaconda2/envs/pyarmor3.6/bin/python -d /opt/pyarmor/v3.6.1/pyarmor/src/pyarmor.py $*

Then run build again: ./pyarmor build
(pyarmor3.6) jacon@uut:/opt/pyarmor/v3.6.1/pyarmor/src/projects/my_mod$ ./pyarmor build
  File "/opt/pyarmor/v3.6.1/pyarmor/src/pyarmor.py", line 739, in <module>
    main2(sys.argv[1:])
  File "/opt/pyarmor/v3.6.1/pyarmor/src/pyarmor2.py", line 444, in main
    version=_version_info())
  File "/opt/pyarmor/v3.6.1/pyarmor/src/pyarmor2.py", line 431, in _version_info
    if get_registration_code() == '':
  File "/opt/pyarmor/v3.6.1/pyarmor/src/utils.py", line 172, in get_registration_code
    code = pytransform.get_registration_code()
  File "/opt/pyarmor/v3.6.1/pyarmor/src/pytransform.py", line 71, in wrap
    raise PytransformError(format_message(errmsg, *args, **kwargs))
  File "/opt/pyarmor/v3.6.1/pyarmor/src/pytransform.py", line 44, in __init__
    self._print_stack()
  File "/opt/pyarmor/v3.6.1/pyarmor/src/pytransform.py", line 54, in _print_stack
    print_stack()
INFO     Build project  ...
INFO     Enable increment build
INFO     Search scripts from /opt/odoo/addons/my_mod
INFO     Obfuscate **0** scripts with mode 8
INFO     Save obfuscated scripts to dist
INFO     Make runtime files to dist
INFO     Generate no restrict mode license file: dist/license.lic
INFO     Insert bootstrap code to entry script dist/__init__.py
INFO     Build project OK.

Then I went to pytransform.py -> dllmethod -> wrap 
and add print(errmsg) to line 70
build and get errmgs = b'Invalid input packet.\nDecode rsa key failed\nGet registration code failed'

Resume:
1. error in project building 
2. this error generate new error while printing error on display
3. my *.py files not obfuscated

**Comment by jondy** [comment]
By default command 'build' only obfuscates the scripts which have been updated since last build, so add -B to force pyarmor to obfuscate all the scripts:
    ./pyarmor build -B
