### ISSUE TITLE
[Question] pyarmor : ERROR Check license failed, Invalid input packet.

### ISSUE THREAD

**Issue by rahulpp891994** [dashingsoft/pyarmor#907]
Hi ,

I have purchased pyarmor commercial version
I was able to obfuscate above scipt using trial version earlier

I am trying to install above setup in new gcp ubuntu server 
I am trying to obfuscate single hello.py file which only prints "hello world"

below setup:

python = 3.7.16
pyarmor = 7.7.4

I have followed following steps 

**pyarmor register pyarmor-regfile-XXXX.txt**
_INFO     PyArmor Trial Version 7.7.4
INFO     Python 3.7.16
INFO     Read registration code file: pyarmor-regcode-XXXX.txt
INFO     Start to activate this code
INFO     Got keyfile of this code, this code is activated
INFO     Start to register keyfile: pyarmor-regfile-XXXX.zip
INFO     Create path: /home/ubuntu/.pyarmor
INFO     Save registration data to: /home/ubuntu/.pyarmor
INFO     Extracting license.lic
INFO     Extracting .pyarmor_capsule.zip
INFO     This keyfile has been registered successfully.
INFO     Run "pyarmor register" to check registration information._

**pyarmor register**

_INFO     PyArmor Version 7.7.4
INFO     Python 3.7.16
PyArmor Version 7.7.4
Registration Code: pyarmor-vax-XXXXXX
This code is authorized to <NAME>

Note: the registration name and email got from remote server is shown here only, they will not be used anywhere else. But the code "pyarmor-vax-XXXXXX" will be distributed with obfusated scripts.

Please send request to "pyarmor@163.com" from the registration email if you would like to change the typos of registration information._

**pyarmor obfuscate  --with-license /home/ubuntu/.pyarmor/license.lic  hello.py**
_INFO     PyArmor Version 7.7.4
INFO     Python 3.7.16
INFO     Target platforms: Native
INFO     Source path is "/home/ubuntu"
INFO     Entry scripts are ['hello.py']
INFO     Use cached capsule /home/ubuntu/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Obfuscate string value is False
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Generate license file from  .pyarmor/license.lic
INFO     Copying /home/ubuntu/vi_prod/lib/python3.7/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
INFO     Patch library dist/pytransform/_pytransform.so
INFO     Patch library file OK
INFO     Copying /home/ubuntu/vi_prod/lib/python3.7/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO     	hello.py -> dist/hello.py
INFO     Insert bootstrap code to entry script dist/hello.py
INFO     Obfuscate 1 scripts OK._

**cd dist/**
**python3 hello.py**
_Check license failed, Invalid input packet._

**ALSO TRIED following things but didn't work**
change pyarmor version to 6.8.1 ,7.0.1,  7.6.0
used --platform linux.x86_64 
used --advanced 2 
removed /home/ubuntu/.pyarmor folder
removed orignal hello.py file

Please help me to solve this issue

**Comment by jondy** [comment]
You're using `--with-license` in the wrong way. Do not use this option, please check the man page of command `obfuscate` in the online documentation to understand this option
