### ISSUE TITLE
Error: No module named pytransform

### ISSUE THREAD

**Issue by ltc1996** [dashingsoft/pyarmor#91]
python version: 2.7.12
My obfuscated *.py is in the same folder as the pytransform.py in the dist folder, with 
```python
from pytransform import pyarmor_runtime 
pyarmor_runtime()
``` 
on the top .
However, when i ran my *.py, it showed "ImportError: No module named pytransform".
How did this happen and how could i fix it?
Thanks :)

**Comment by jondy** [comment]
Is the file `pytransform.py` is obfuscated? If it's, do not obfuscate `pytransform.py`.

**Comment by jondy** [comment]
To be sure `pytransform.py` in the any Python path, you can check the python python by inserting some debug lines before bootstrap code:
```
import sys
print(sys.path)
```

**Comment by ltc1996** [comment]
Duplicate of #

> To be sure pytransform.py in the any Python path, you can check the python python by inserting some debug lines before bootstrap code:
> import sys
> print(sys.path)

I'm here to let you know that the problem has been solved. But I am walled by gfw for 2 days, so I can't reply you via Gmail. Thanks again for all your effort and patience.

**Comment by jondy** [comment]
Got it.

**Comment by sudars1980** [comment]
My python file is in "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\Lib\site-packages\pyarmor\" and pytransform file is also in the same location. However it still says the following exception when i run the python file after obfuscation. Can you please help me on this issue?

  File "Test.py", line 4, in <module>
    import pytransfrom
ModuleNotFoundError: No module named 'pytransfrom'

**Comment by ltc1996** [comment]
> My python file is in "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\Lib\site-packages\pyarmor" and pytransform file is also in the same location. However it still says the following exception when i run the python file after obfuscation. Can you please help me on this issue?
> File "Test.py", line 4, in 
> import pytransfrom
> ModuleNotFoundError: No module named 'pytransfrom'

did you use `pip install PyArmor` to get it installed?

**Comment by sudars1980** [comment]
Sorry i got it working. There was some minor issue with the location. It works now. Thanks for your quick response. I do have a clarification regarding this:

All my python files are in windows box. For instance if i want my python scripts to run on both windows and linux, is there a way to select the target platform and obfuscate it and then package the files for both?

**Comment by jondy** [comment]
After v5.7.5, run obfuscated scripts in multiple platforms by this command:
```
pyarmor obfuscate --platform windows.x86_64 --platform windows.x86 --platform linux.x86_64 --platform linux.x86 foo.py
```

**Comment by sudars1980** [comment]
Thanks

**Comment by sudars1980** [comment]
once it is obfuscated, is it possible to decode using the key and license file using some command? also my assumption is that for each license you will be providing a new key file and license file. Please confirm.

**Comment by jondy** [comment]
@sudars1980 the obfuscated scripts couldn't be decoded by using key file and license file.

About the second question, yes, every purchased user will receive an unique key file and license code. More information, refer to https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#global-capsule

**Comment by pritam-gembali** [comment]
> Sorry i got it working. There was some minor issue with the location. It works now. Thanks for your quick response. I do have a clarification regarding this:
> 
> All my python files are in windows box. For instance if i want my python scripts to run on both windows and linux, is there a way to select the target platform and obfuscate it and then package the files for both?

@sudars1980 I'm getting the same error. How did you fix it?

**Comment by iserranoe** [comment]
In my case, the entry file (app/\_\_init\_\_.py) is inside a folder:
```
project
|__ app
     |__ \_\_init\_\_.py
|__ other folders
```
With the config file as follows:
```
{
  "version": "2.1",
  "name": "app",
  "title": "app",
  "src": ".",
  "is_package": null,
  "manifest": "global-include *.py",
  "entry": "app/__init__.py",
  "output": "pyarmor",
  "runtime_path": null,
  "restrict_mode": 1,
  "obf_code": 1,
  "obf_mod": 2,
  "wrap_mode": 1,
  "advanced_mode": 0,
  "bootstrap_code": 1,
  "cross_protection": 1,
  "mixins": null,
  "plugins": null,
  "platform": null,
  "package_runtime": 1,
  "enable_suffix": 0,
  "license_file": null,
  "build_time": 1664872641.839701
}
```
After `pyarmor build` the obfuscated folder is saved in the folder pyarmor with the following distribution:
```
project
|__ app
     |__ \_\_init\_\_.py
|__ other folders
|__ pyarmor
    |__ app
         |__ \_\_init\_\_.py
    |__ other_folders
    |__ pytransform
```
And the obfuscated file \_\_init\_\_.py is the following:
```
from .pytransform import pyarmor_runtime
pyarmor_runtime()
__pyarmor__(__name__, __file__, b())
```
however, it can't find .pytransform because it's not in the same folder. Changing the import from pytransform solves the problem:
```
from pytransform import pyarmor_runtime
pyarmor_runtime()
__pyarmor__(__name__, __file__, b())
```

**Comment by ltc1996** [comment]
已经收到了您的邮件，我会尽快回复的。
