### ISSUE TITLE
终极模式混淆的范围[Question]

### ISSUE THREAD

**Issue by wdlhit** [dashingsoft/pyarmor#917]
您好，我想大致了解一下终极模式。如使用终极模式，是否混淆：

1 - 字符串
2 - 函数名称
3 - 变量名称
4 - 代码逻辑

我只是想使用终极模式加密一个py文件，内容为一个class + 若干函数，且并无双下划线的变量和函数，以及静态函数。谢谢！

**Comment by jondy** [comment]
不混淆，只是把 .py 转换成为 c 代码
