### ISSUE TITLE
[Question] Should I pack or just obfuscate for more security?

### ISSUE THREAD

**Issue by kr1tx** [dashingsoft/pyarmor#919]
Which is more secure, Packing with **pyarmor/pyinstaller** into EXE or Just obfuscating the script?

**Comment by jondy** [comment]
It's almost same.

**Comment by kr1tx** [comment]
Thanks, Which could be a more secure approach? To make the script even harder to be cracked?

**Comment by jondy** [comment]
Refer to https://pyarmor.readthedocs.io/en/latest/usage.html#improving-security-further
