### ISSUE TITLE
Not return `0` while license is expired

### ISSUE THREAD

**Issue by whenyd** [dashingsoft/pyarmor#92]
Function `get_expired_days()` should return `0` while license is expired according to the document, but now it raise `PytransformError`.

**Comment by jondy** [comment]
In the startup of the obfuscated script, the license will be checked. If it is expired, `PytransformError` is raised and quit. Actually `get_expired_days` has no chance to run.

To show some useful information even if the obfuscated scripts is expired, one solution is to write your own license type, here it's an example
https://pyarmor.readthedocs.io/en/latest/advanced.html#using-plugin-to-extend-license-type

**Comment by whenyd** [comment]
Using plugins is a good solution, but raise `PytransformError` directly will break the consistence between the document and the function behavior, it is ambiguous.

**Comment by jondy** [comment]
You're right, I'll document this behavior soon. It's somewhat complicated to let the obfuscated script still to run as the license has been expired.
