### ISSUE TITLE
[Question] Obfuscating Cross-Platform

### ISSUE THREAD

**Issue by Gowixx** [dashingsoft/pyarmor#920]
Hey there,

I was reading the docs and was trying to obfuscate cross-platform. Ex. I have Windows OS and want to obfuscate for Windows, Mac, and Linux. I tried the docs and did everything there, but it just automatically reverts to windows versions, how can I fix this?

**Comment by Gowixx** [comment]
Also, how do I make pyarmor only use the imports inside of the current project? When I try it always does ALL the packages on my local machine.

**Comment by jondy** [comment]
https://pyarmor.readthedocs.io/en/v7.7/advanced.html#distributing-obfuscated-scripts-to-other-platform

And 
https://pyarmor.readthedocs.io/en/v7.7/man.html#obfuscate
