### ISSUE TITLE
How to release a obfuscated tool that runs with different versions of Python?

### ISSUE THREAD

**Issue by AKEric** [dashingsoft/pyarmor#924]
I've released a tool via PyArmor that 'works for some people, but not others'.  They get this error:

https://pyarmor.readthedocs.io/en/latest/questions.html#marshal-loads-failed-when-running-xxx-py

Which appears to be:  If their version of the Python interpreter is different than my version PyArmor used to obfuscate the tool, they can't access the tool.  

If this is true, and I understand it correctly, it's incredibly limiting to tool release.

For example, the tool I'm using is authored in 'Maya 2022', and obfuscated via that DCC's Python interpreter.
But if someone in 'Maya 2023' tries to access my tool, they get the above error.   
They're both Python 3, just a few '.versions' different (for example, one is Python 3.7, one is Python 3.9).

Is there a way to get around this?
thanks

**Comment by jondy** [comment]
Find the solution in the advanced usage in the online documentation

**Comment by AKEric** [comment]
Can you be more specific/give me a section or link?

FYI, I've read the docs, if I understood how they answered this for me I wouldn't be asking :)

Thanks

**Comment by jondy** [comment]
This is the solution
https://pyarmor.readthedocs.io/en/v7.7/advanced.html#run-obfuscated-scripts-by-different-python-versions
