### ISSUE TITLE
Trouble to pack my module with pyarmor  

### ISSUE THREAD

**Issue by mbadinga1** [dashingsoft/pyarmor#926]
Hello, 
I have a issue with packing my module. I use the command pyarmor pack --clean -e "--onefile " file.py it correctly packed.
But the trouble comes when i run dist/file/file, i have this bug : 

Traceback (most recent call last):
  File "file.py", line 54, in <module>
    keypad_default = init_fonction.init()
  File "/opt/test/definition/init_fonction.py", line 81, in init
    default=definition.KEY
AttributeError: module 'definition' has no attribute 'KEY'
[10478] Failed to execute script 'file' due to unhandled exception!

But KEY is found in definition.  I add this for another module (smbus) but I hide inside of hiddenimports in my file.spec. 
I try to follow this issue : https://github.com/dashingsoft/pyarmor/issues/39  but the problem remains. 

How can I handle the issue ?

**Comment by jondy** [comment]
Please refer to 
https://pyarmor.readthedocs.io/en/latest/questions.html
