### ISSUE TITLE
Add a license to already obfuscated code

### ISSUE THREAD

**Issue by NadavLisovtsev** [dashingsoft/pyarmor#928]
Hi, is it possible add a license to already obfuscated code?

I have several machines that runs my python code, and are not connected to the internet. 
Due to the lack of web connection, any software updates are delivered on a flash drive. 

I want to protect my code so it could run only in the target machine (which could be easily done by adding a license to the machines MAC address for example), but it also should be protected on the flash drive.
Could I obfuscate the code, put it on the flash drive and  add the license during the version update on the target machine?
Thank you!

**Comment by jondy** [comment]
Use outer license, search "outer license" in the documentation to find the solution.
