### ISSUE TITLE
ERROR    Verify downloaded library failed

### ISSUE THREAD

**Issue by aulloa** [dashingsoft/pyarmor#93]
The Problem
----
pyarmor download win_amd64 fails with ERROR    Verify downloaded library failed.
**logs also say I'm using the trial version even though I registered**

Configuration
----
pyarmor 5.4.0
python 3.5.6
Ubuntu amd64

Logs
----
INFO     PyArmor Trial Version 5.4.0

INFO     Download dynamic library for win_amd64
INFO     Reading data from https://pyarmor.dashingsoft.com/downloads/platforms/index.json
INFO     Search library for win_amd64 and arch x86_64
INFO     Loading platforms information
INFO     Find library at https://pyarmor.dashingsoft.com/downloads/platforms/win_amd64/_pytransform.dll
INFO     Downloading library file ...
ERROR    Verify downloaded library failed

**Comment by jondy** [comment]
I have fixed it, please run pyarmor again.

If you upgrade from old version (<5.3.3), you need register with registration code again after upgraded.

**Comment by aulloa** [comment]
It worked thanks.
