### ISSUE TITLE
[BUG] Error while downloading dynamic library for cross platform encrypt

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#935]
Hello! I am trying to encrypt using SPP mode with flags:

>     --no-runtime \
>     --platform windows.x86_64.11.py310 \
>     --recursive \
>     --restrict 2 \
>     --advanced 5 \
>     --obf-code=2 \
>     --wrap-mode 1 \

Also, I added to ENVIRON PATH

> PYARMOR_PLATFORM = "windows.x86_64.11.py310"

Got this error:

> INFO     PYARMOR_PLATFORM is windows.x86_64.11.py310
> INFO     Search library for platform: windows.x86_64.11.py310
> INFO     Remove cached platform list file /Users/paulo/.pyarmor/platforms/index.json
> INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r52.6/index.json
> INFO     Write cached platform list file /Users/paulo/.pyarmor/platforms/index.json
> INFO     Found available libraries: ['windows.x86_64.11.py310']
> INFO     Target path for windows.x86_64.11.py310: /Users/paulo/.pyarmor/platforms/windows/x86_64/11/py310
> INFO     Downloading library file for windows.x86_64.11.py310 ...
> INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r52.6/windows.x86_64.11.py310/pytransform.pyd
> INFO     Writing target file: /Users/paulo/.pyarmor/platforms/windows/x86_64/11/py310/pytransform.pyd
> INFO     Download dynamic library windows.x86_64.11.py310 OK
> ERROR    Could not find "/Users/paulo/.pyarmor/platforms/windows/x86_64/11/py310/_pytransform.dylib"

I am using MacOS and I will distribute for Windows Machines

**Comment by jondy** [comment]
SPP mode doesn't support cross platform now. Run this in Windows, and do not set `PYARMOR_PLATFORM`

**Comment by pauloswear** [comment]
@jondy actually the best way is installing windows on macbook?
BCC mode will support Cross Platform?

**Comment by jondy** [comment]
BCC mode supports cross platform is in-plan, after new features are stable.

**Comment by jondy** [comment]
The first implementation is using cross compile tool, for example, in linux.x86_64 it need install `aarch64-linux-gnu-gcc` to generate BCC code for linux.aarch64.

In Macos, `clang` supports cross platform natively, it's Ok to compile BCC code for other platforms.

**Comment by pauloswear** [comment]
I'll close topic and wait for BCC mode
