### ISSUE TITLE
No available dynamic library for windows.x86_64 with features ['25'] for python 3.10

### ISSUE THREAD

**Issue by JiaPai12138** [dashingsoft/pyarmor#938]
```
pyarmor obfuscate --advanced 4 --plugin check_ntp_time --plugin assert_armored main.py
INFO     PyArmor Version 7.7.4
INFO     Python 3.10.10
INFO     Target platforms: Native
ERROR    No available dynamic library for windows.x86_64 with features ['25']
```

Will there be dynamic library for vm mode for python 3.10 in the future?

**Comment by jondy** [comment]
I'm afraid there is no vm mode for python 3.10 in future.

In next major version 8.0, the core libraries are rewritten, and provides new modes to obfuscate the scripts.

For the old modes, it still works, but I have no plan to build new libraries. No new features for old modes, only bug fix.

**Comment by JiaPai12138** [comment]
> I'm afraid there is no vm mode for python 3.10 in future.
> 
> In next major version 8.0, the core libraries are rewritten, and provides new modes to obfuscate the scripts.
> 
> For the old modes, it still works, but I have no plan to build new libraries. No new features for old modes, only bug fix.

Got you, looking forward to this
