### ISSUE TITLE
[Question] 关于安全性的问题 (--advanced 4 & 5)

### ISSUE THREAD

**Issue by elstrm** [dashingsoft/pyarmor#941]
亲爱的朋友，我道歉，如果这个问题是愚蠢的。

我花了很多时间解决它，分析了你所有的开源代码，但没有找到答案。 什么更好，什么更"不可逆"-Python3.9上的高级4（super+vm模式）或python3.10上的高级5（仅限super plus模式）？

PyArmor7.7.4在这两种情况下。

我一直在尝试很长一段时间来弄清楚什么是最适合安全的。 这对我很重要。 我会感激你的，朋友。

**Comment by jondy** [comment]
最适合安全的请升级到最新版本 Pyarmor 8.0, 它将在近期 2 个星期内发布，并且会有详细的文档说明。
