### ISSUE TITLE
[Question] Pickle error

### ISSUE THREAD

**Issue by heibaidaolx123** [dashingsoft/pyarmor#945]
Hi, jondy,
I used multiprocessing in my code, after obfuscating it by restrict mode 4, when running it, pickle error was raised:
`AttributeError: Can't get attribute 'MyClass' on <module '?'>`
Is there a walkaround?

**Comment by jondy** [comment]
pickle may not work with obfuscated scripts.

**Comment by scottwsides** [comment]
I can confirm...pickling does not work with obfuscation. Its a problem with certain packages like Ray which wants to pickle modules.
