### ISSUE TITLE
[Question] 一个注册码只能用十次？

### ISSUE THREAD

**Issue by jekoie** [dashingsoft/pyarmor#946]
![image](https://user-images.githubusercontent.com/6836400/223301784-2e011a75-08ab-4e2c-b298-9cccdd10662e.png)

这个新版本说注册码只能用十次；但是我需要经常换机装python，不到一年可能就需要重新买注册码？

**Comment by jondy** [comment]
在新版本里面，注册码文件也称之为初始登记的激活文件，只推荐用一次， 之后使用登记的时候生成 `.zip` 文件进行注册，`.txt` 文件只能使用十次， `.zip` 文件没有限制。

对于老用户的话，请一定查看 gihub 里面 README.md 中最后的升级说明
