### ISSUE TITLE
[BUG] No matching distribution found for pyarmor.cli.core~=1.0 with pyarmor 8.0

### ISSUE THREAD

**Issue by SamComber** [dashingsoft/pyarmor#950]
Attempting install of pyarmor 8.0

`pip install pyarmor==8.0`

Yields, `ERROR: No matching distribution found for pyarmor.cli.core~=1.0`

Expected: installed successfully 

OS darwin22.0

**Comment by brokoler** [comment]
I also can't install it, following error is shown:

```
pip install pyarmor
Collecting pyarmor
  Downloading pyarmor-8.0-py2.py3-none-any.whl (207 kB)
     ---------------------------------------- 207.2/207.2 kB 4.2 MB/s eta 0:00:00
Requirement already satisfied: pyarmor.cli.core~=1.0 in c:\users\seidelp\appdata\local\programs\python\python311\lib\site-packages (from pyarmor) (1.0)
Installing collected packages: pyarmor
ERROR: For req: pyarmor. Invalid script entry point: <ExportEntry pyarmor = pyarmor:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
```

The previous versions could be installed without any errors on my system.

**Comment by JiaPai12138** [comment]
> I also can't install pyarmor 8.0, following error is shown:
> 
> ```
> pip install pyarmor
> Collecting pyarmor
>   Downloading pyarmor-8.0-py2.py3-none-any.whl (207 kB)
>      ---------------------------------------- 207.2/207.2 kB 4.2 MB/s eta 0:00:00
> Requirement already satisfied: pyarmor.cli.core~=1.0 in c:\users\seidelp\appdata\local\programs\python\python311\lib\site-packages (from pyarmor) (1.0)
> Installing collected packages: pyarmor
> ERROR: For req: pyarmor. Invalid script entry point: <ExportEntry pyarmor = pyarmor:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
> ```
> 
> The previous versions could be installed without any errors on my system.

Check [this](https://github.com/dashingsoft/pyarmor/issues/949#issuecomment-1459367929)

**Comment by JiaPai12138** [comment]
The new update fixed this

**Comment by Shawn-Shan** [comment]
The error is still persist for me. How do I get the new update? 

M1, python3.9

**Comment by SamComber** [comment]
I can't actually get to the next error everyone else is reporting, `ERROR: For req: pyarmor. Invalid script entry point: <ExportEntry pyarmor = pyarmor:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.` 

How are you guys installing pyarmor.cli.core~=1.0 ? @JiaPai12138 @jondy

**Comment by SamComber** [comment]
I think this is a problem with M1 chip, @jondy  when can we get an arm architecture release? I just ran `pip install -vvv pyarmor` and can see x86_64 only 

cp311-none-macosx_10_14_x86_64

**Comment by jondy** [comment]
I'm not sure the exact date. When I'm back to office, I'll build aarch64 platforms.

**Comment by JiaPai12138** [comment]
Try latest version

**Comment by hiddify1** [comment]
The  new version say this:
```
No matching distribution found for pyarmor.cli.core~=1.0.5

```

**Comment by hiddify1** [comment]
It does not have any release for aarch64
:(

**Comment by jondy** [comment]
The other platforms will be supported later. Please check the pinned issue #980

**Comment by Kaiyangshi-Ito** [comment]
> The other platforms will be supported later. Please check the pinned issue #980

As of today, I was trying to install PyArmor 8 on my M1 Mac, and it reports an error:
```
ERROR: Could not find a version that satisfies the requirement pyarmor.cli.core~=1.0.15 (from pyarmor) (from versions: none)
ERROR: No matching distribution found for pyarmor.cli.core~=1.0.15
```
Any solution for this? Any updates on the dates M1 Mac will be supported?

**Comment by jondy** [comment]
Please check pyarmor in pypi for latest version
