### ISSUE TITLE
[BUG] Error registering a new pyarmor8 license

### ISSUE THREAD

**Issue by sergionuc** [dashingsoft/pyarmor#951]
Hi pyarmor team!

I have tried to register a new pyarmor8 license but I get the following error:

pyarmor reg -p 'XXX' pyarmor-regcode-xxxx.txt 
usage: pyarmor [-h] [-v] [-q] [-d] [--home HOME] [--boot BOOT]  ...
pyarmor: error: argument : invalid choice: 'reg' (choose from 'obfuscate', 'o', 'licenses', 'l', 'pack', 'p', 'init', 'i', 'config', 'c', 'build', 'b', 'info', 'check', 'hdinfo', 'benchmark', 'capsule', 'register', 'download', 'runtime', 'help')

The 'gen' option is also missing in the previous list. 

Besides, I had problems installing pyarmor8 with pip so I had to modify the setup.py file, line 121.

I am using darwin.x86_64 and Python 3.9.16.

Thx!

**Comment by JiaPai12138** [comment]
Same
Even i completely removed pyarmor

**Comment by pauloswear** [comment]
Use old pyarmor register, it will register for now
Seems that new commands for pyarmor 8.0 i`ts not working wet

**Comment by jondy** [comment]
please upgrade pyarmor to 8.0

**Comment by pauloswear** [comment]
@jondy we are talking about 8.0 version, there are some bugs included with 8.0 ver. The new commands "gen", "reg" and others it`s not working, but old commands like "obfuscate", "register" it`s working. 

There are a bug with 8.0 setup.py script, please refer to: #950 
Please also refer to #952 #949

**Comment by sergionuc** [comment]
@pauloswear thank you for the tip but it doesn't work.  I have registered the pyarmor8 license with the old command, but when I try to download the runtime package, I get a 401 error: 

INFO     PyArmor Version 7.7.4
INFO     Python 3.9.16
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r52.6/index.json
ERROR    HTTP Error 401: Unauthorized

Any suggestions? I need to release a new version this week.

Any help will be appreciated. Thx!!

**Comment by sergionuc** [comment]
> new license is not designed for old pyarmor.

@jondy I have tried to register my pyarmor pro 8 license but I get the following error: 

INFO     Python 3.9.5
INFO     Pyarmor 8.0 (trial), 000000, non-profits
INFO     prepare "pyarmor-regcode-5000.txt"
INFO     query key file from server
CRITICAL unknown error, please check pyarmor.error.log
ERROR    product name has been set to "non-profits"

However, I have used the following command: pyarmor reg -p "XXXXX" pyarmor-regcode-5000.txt. 

Any help will be appreciated. Thx!!

**Comment by jondy** [comment]
@sergionuc 

Please use the latest pyarmor 8.0.6, and try it again. Also read the content `pyarmor-regcode-5000.txt`

**Comment by SandroBR** [comment]
INFO     Python 3.10.10
INFO     Pyarmor 8.0.6 (trial), 000000, non-profits
INFO     prepare "pyarmor-regcode-4010.txt"
INFO     query key file from server
This license registration information will be

License Type    : pyarmor-basic
License Owner   : Alexandro A Souza
Bind Product    : non-profits

This license is about to be ussd for non-profits

Are you sure to continue? (yes/no) yes
INFO     process activation file "pyarmor-regcode-4010.txt"
INFO     send register request to server
INFO     write registration file "pyarmor-regfile-4010.zip"
INFO     register "pyarmor-regfile-4010.zip"
INFO     update license token
CRITICAL unknown error, please check pyarmor.error.log
ERROR    request license token faild (16)

**Comment by jondy** [comment]
> ERROR request license token faild (16)

This has been fixed in latest pyarmor 8.0.7 with pyarmor.cli.core == 1.0.2, please update pyarmor

**Comment by otbafrica** [comment]
Hello pyarmor team,

Have tried to register pyarmor with a newly purchased group license but get the following error:

INFO     process activation file "/pyarmor-regcode-6056.txt"
INFO     send request to server
ERROR    this group license is reviewing by Pyarmor team
