### ISSUE TITLE
[BUG] Pyarmor 8.0 does not support Python 3.11

### ISSUE THREAD

**Issue by brokoler** [dashingsoft/pyarmor#952]
Hello,

I installed pyarmor 8.0 on my system and tried to obfuscate a Python script written in 3.11.

When choosing the "gen" command, I get the error already mentioned:
https://github.com/dashingsoft/pyarmor/issues/951
The "gen" command seems to be missing completely in pyarmor 8.0

When choosing the "obfuscate" command:
`pyarmor obfuscate program.py`
I get following error:
`ERROR    Python 3.11+ is not supported now`

Per my understanding pyarmor 8.0 should support the "gen" command and should support Python code written in 3.11.
These seem to be two bugs not fixed yet.

**Comment by Blank-c** [comment]
same thing happens

**Comment by jondy** [comment]
Use `gen` for Python 3.11. Please wait for 8.0 bugs fixed

**Comment by ZQlby** [comment]
"ERROR    Python 3.11+ is not supported now"

**Comment by jondy** [comment]
Only command `gen` supports Python 3.11+.

All the old commands doesn't support Python 3.11+, they're only for backward compatibility
