### ISSUE TITLE
[BUG] Pack not working on Mac, works perfectly on PC

### ISSUE THREAD

**Issue by DaveyUS** [dashingsoft/pyarmor#957]
Running 7.7.4 on 3.10.10 -- Mac Ventura with the M2 chip.

`pyarmor pack -x " --advanced 2 --exclude tests --recursive" -s main.spec main.py`

This command runs flawlessly on Windows 11, but on Mac nothing happens. The terminal acts as though something is happening, but after a half hour of waiting, no files or folders are created. Even if I strip the command down to the most basic command `pyarmor pack main.py` for testing purposes, it still just sits there and doesn't do anything.

Any ideas?

**Comment by DaveyUS** [comment]
Also there is no output in the terminal when it's running, no info. It just sits there until I terminate the terminal.

**Comment by jondy** [comment]
Use `PYARMOR_PLATOMR=darwin.aarch64.0`, or search `PYARMOR_PLATOMR` in 7.x documentation.
