### ISSUE TITLE
[Question] about obfuscation __init__.py.

### ISSUE THREAD

**Issue by Omar-AE** [dashingsoft/pyarmor#958]
I have a script (on a server) that automatically obfuscates python scripts (if any) whenever a new commit is pushed to a certain repo. It's been there for around two years.
The first time I include _\_\_init\_\_.py_ file in the repo was yesterday and I faced an issue running the file after obfuscation, because it has `from .pytransform...` instead of `from pytransform...`.
I have _pytranform_ directory located far from the repo.

My questions:
1. Why do you add the dot prefex in _\_\_init\_\_.py_ import statements? In other words: Why do you assume that pytransform is located within the repo?
2. Is there any option or argument to ignore this feature (other than modifying the file manually)?

Thank you.

**Comment by VeNoMouS** [comment]
@Omar-AE look at https://pyarmor.readthedocs.io/en/v7.7.4/man.html?highlight=bootstrap#obfuscate

try `--bootstrap 2`
