### ISSUE TITLE
[BUG] Can't install version 8.0.0

### ISSUE THREAD

**Issue by alexeyproskuryakov** [dashingsoft/pyarmor#959]
Hi I try install pyarmor: 

`pip install pyarmor==8.0.0`

and have a problem:
`
ERROR: For req: pyarmor==8.0. Invalid script entry point: <ExportEntry pyarmor = pyarmor:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
`
When installing v7.7.4 all ok.

At linux: ubuntu:22.04, centos:6, all python 3.7.13, python 3.10.6

**Comment by carrotNort** [comment]
it seemed like the .dist_info dir lost，so that the entry point of pyarmor is unknown, so the installation failed.

**Comment by FabioLuporini** [comment]
same issue here

**Comment by yuseffathi** [comment]
same in macOS m1

**Comment by ggorman** [comment]
Does this mean the bug is fixed?

**Comment by jondy** [comment]
The latest version is 8.0.9, 8.0.10 will be released soon. But not all platforms are supported now, please refer to pinned issue #980
