### ISSUE TITLE
Project src as relative path

### ISSUE THREAD

**Issue by blechatellier** [dashingsoft/pyarmor#96]
When using a project can the `src` use a relative path please? That would be helpful to run on CI machines.

`ERROR    The src of this project is not absolute path`

**Comment by jondy** [comment]
If `src` is relative to the current path, it will not work to build project in different path. 
For examples, case 1
```
cd /path/to/project
pyarmor build
```
case 2
```
cd /other/path
pyarmor build /path/to/project
```
If `src` is a relative path, it may be relative to the project path. Does it work in your case?
