### ISSUE TITLE
[BUG]python3.9安装pyarmor 8.0版本失败

### ISSUE THREAD

**Issue by wsxhd7881** [dashingsoft/pyarmor#961]
使用python3.9安装pyarmor 8.0版本失败，报错如下：
D:\Program Files\Python\Python39\Scripts>pip3.9 install -U pyarmor
Collecting pyarmor
  Using cached pyarmor-8.0-py2.py3-none-any.whl (207 kB)
Requirement already satisfied: pyarmor.cli.core~=1.0 in d:\program files\python\python39\lib\site-packages (from pyarmor) (1.0)
Installing collected packages: pyarmor
ERROR: For req: pyarmor. Invalid script entry point: <ExportEntry pyarmor = pyarmor:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.

这个怎么解决呢？
windows 11
python3.9.13

**Comment by jondy** [comment]
Entry point 的问题已经在 8.0.1 中解决。
