### ISSUE TITLE
[BUG]Pyarmor无法register，提示Service Temporarily Unavailable

### ISSUE THREAD

**Issue by crasyjoel** [dashingsoft/pyarmor#962]
普通版升级专家版，持续好几天一直无法注册：
(venv) PS C:\Users\xx\Documents\xx> pyarmor register -u pyarmor-regcode-to-pro.txt
INFO     PyArmor Version 8.0
INFO     Python 3.7.9
INFO     Read registration code file: pyarmor-regcode-to-pro.txt
INFO     Start to activate this code
ERROR    HTTP Error 503: Service Temporarily Unavailable

**Comment by marktohark** [comment]
i've the same error.

**Comment by wsxhd7881** [comment]
这个怎么解决？

**Comment by marktohark** [comment]
我把pyarmor降級成7的版本去註冊就可以了

**Comment by jondy** [comment]
升级到 8.0.8 以上的版本，注册问题已经解决
