### ISSUE TITLE
[Question] upgrade license

### ISSUE THREAD

**Issue by nblog** [dashingsoft/pyarmor#964]
你好, 
我无法从[文档](https://pyarmor.readthedocs.io/en/latest/licenses.html#upgrading-old-license)中明确得知我是否是应该重新购买新的授权, 或是购买Upgrade来升级到pyarmor 8 pro.

如我的编号为 `pyarmor-regcode-1112`, 且确定我激活次数未超过100次. 我该如何选购来升级到pyarmor 8 pro

**Comment by jondy** [comment]
> If it’s not matched, please purchase new license to use Pyarmor latest version.

这是文档里面的写的内容，不满足条件就需要购买新的专家版许可证
