### ISSUE TITLE
ERROR: DLL load failed while importing pytransform3: The specified module could not be found.

### ISSUE THREAD

**Issue by JiaPai12138** [dashingsoft/pyarmor#966]
Python 3.10.10 (64 bit)
Windows 10 LTSC 21H2 x64
Installed C++ Redistributable Runtimes from [here](https://github.com/abbodi1406/vcredist)
License Type    : pyarmor-trial (Waiting to upgrade)

Command:
```
pyarmor gen -O newdist --assert-import main.py
```

**Comment by jondy** [comment]
@AI-M-BOT 
I have uploaded all the runtime files of windows.x86_64 to

http://pyarmor.dashingsoft.com/downloads/temp/windows_x86_64/libs/cp3.10/pytransform3.pyd

cp3.10 could be replaced with `cp3.7` ~ `cp3.11`

You can download one to verify which is right for python 3.10
