### ISSUE TITLE
[Question] Why does ordering a license take 4 - 24hrs?? 

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#968]
`Your order will most likely be processed within the next 4 hours, but in no case will it take more than 24 hours.`

It's 2023... it should not take that long to process an order...
![image](https://user-images.githubusercontent.com/597545/224580437-6c925d60-c3a5-4f4b-ae7f-36449c413f52.png)

**Comment by VeNoMouS** [comment]
License finally arrived 6 hours after purchase , way to long imho

**Comment by jondy** [comment]
This is out of my control, I can ask for MyCommerce to find better solution later.

**Comment by jondy** [comment]
MyCommerce says most of orders are handled immediately, only a few need to be reviewed so it spent more time.
