### ISSUE TITLE
[BUG] Registration error

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#970]
Hello, there is a bug in registration.

> 1119 MainProcess 2023-03-13 12:58:21,982
> Traceback (most recent call last):
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 559, in main
>     main_entry(sys.argv[1:])
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 547, in main_entry
>     args.func(ctx, args)
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 178, in cmd_reg
>     msg = regsvr.prepare(regfile, args.product, upgrade=args.upgrade)
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/register.py", line 238, in prepare
>     info = json_loads(res.read(), encoding='utf-8')
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/json/__init__.py", line 359, in loads
>     return cls(**kw).decode(s)
> TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

**Comment by jondy** [comment]
got it, thanks

**Comment by pauloswear** [comment]
Can I close?

**Comment by pauloswear** [comment]
Still got error after 8.0.2 version

> 
> 1787 MainProcess 2023-03-14 10:28:37,652
> Traceback (most recent call last):
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 559, in main
>     main_entry(sys.argv[1:])
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 547, in main_entry
>     args.func(ctx, args)
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 178, in cmd_reg
>     msg = regsvr.prepare(regfile, args.product, upgrade=args.upgrade)
>   File "/Users/paulo/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pyarmor/cli/register.py", line 240, in prepare
>     raise RuntimeError(
> RuntimeError: product name has been set to "******"
>

**Comment by jondy** [comment]
Yes. #ec7ffd034f0c26628b1e36994a29d0bf9c56edfd

**Comment by jondy** [comment]
Do not use `-p` if product name has been set.

**Comment by pauloswear** [comment]
I am not using -p, just pyarmor reg reg-vax****.txt

**Comment by jondy** [comment]
I'll check it.

**Comment by jondy** [comment]
> RuntimeError: product name has been set to

This has been fixed in 8.0.5
