### ISSUE TITLE
[BUG] unknown license type OLD

### ISSUE THREAD

**Issue by kzuo03** [dashingsoft/pyarmor#978]
I tried follow the license instructions:

```
pyarmor reg -p "Kusaka" pyarmor-regcode-3699.txt 

```
and I also tried 

```
pyarmor reg -p Kusaka pyarmor-regcode-3699.txt 

```
But It's gererate:

```
INFO     Python 3.9.12
INFO     Pyarmor 8.0 (trial), 000000, non-profits
INFO     prepare "pyarmor-regcode-3699.txt"
INFO     query key file from server
CRITICAL unknown error, please check pyarmor.error.log
ERROR    unknown license type OLD

```
And the log:

```
2740 MainProcess 2023-03-15 15:18:01,214
Traceback (most recent call last):
  File "C:\Users\chris\anaconda3\envs\all\lib\site-packages\pyarmor\cli\__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "C:\Users\chris\anaconda3\envs\all\lib\site-packages\pyarmor\cli\__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "C:\Users\chris\anaconda3\envs\all\lib\site-packages\pyarmor\cli\__main__.py", line 178, in cmd_reg
    msg = regsvr.prepare(regfile, args.product, upgrade=args.upgrade)
  File "C:\Users\chris\anaconda3\envs\all\lib\site-packages\pyarmor\cli\register.py", line 253, in prepare
    raise RuntimeError('unknown license type %s' % info['lictype'])
RuntimeError: unknown license type OLD

```

I bought the license today and follow the txt steps many times. I also re-install the pyarmor, reset the machine, add the pyarmor path on PATH, but nothing work.

**Comment by jondy** [comment]
Do you check this new EULA and purchase new license?
[readthedocs.io/en/latest/licenses.html](https://pyarmor.readthedocs.io/en/latest/licenses.html)

**Comment by kzuo03** [comment]
I use this link: 

```
https://pyarmor.dashingsoft.com/index.html
```
and click here in Purchase 
![image](https://user-images.githubusercontent.com/107141106/225511481-6f191086-09dc-40eb-85a2-8ebe294f6db9.png)

It is in the documentation:
![image](https://user-images.githubusercontent.com/107141106/225511728-c41f85c3-892f-470f-92b1-fabc39898d28.png)

**Comment by jondy** [comment]
You didn't purchase new license. Please send refund request for this order and then purchase Pyarmor Basic or Pro license.
