### ISSUE TITLE
[BUG] Error in pyarmor pack in win 10 pro

### ISSUE THREAD

**Issue by laszloferenczi** [dashingsoft/pyarmor#979]
Dear Pyarmour!

Some day ago we bought a Pyarmour licence. But the first time we want to use we found an error.

Our environment:

-	Windows 10 Pro workstation, not VM or Docker, not wine hq, pure Windows 10 Pro
-	Python 3.9.13
-	Pyinstaller 5.8.0
-	Pyarmor latest (7.7.4)
-	using Python virtual environment

Try an very simple pythons „Hello word!” for test reason.

main.py:
print(’Hello world!’)

Command:
pyarmor pack -e " --onedir" main.py

Result:
..
..
14513 INFO: Looking for eggs
14513 INFO: Using Python library C:\99_Tools\Python39\python39.dll
14516 INFO: Found binding redirects:
[]
14529 INFO: Warnings written to c:\95_Releases\Builder\bug\build\main-patched\warn-main-patched.txt
14589 INFO: Graph cross-reference written to c:\95_Releases\Builder\bug\build\main-patched\xref-main-patched.html
Traceback (most recent call last):
  File "C:\99_Tools\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\99_Tools\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\95_Releases\Builder\venv\lib\site-packages\PyInstaller\__main__.py", line 198, in <module>
    run()
  File "c:\95_Releases\Builder\venv\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\95_Releases\Builder\venv\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\95_Releases\Builder\venv\lib\site-packages\PyInstaller\building\build_main.py", line 977, in main
    build(specfile, distpath, workpath, clean_build)
  File "c:\95_Releases\Builder\venv\lib\site-packages\PyInstaller\building\build_main.py", line 899, in build
    exec(code, spec_namespace)
  File "main-patched.spec", line 33, in <module>
    raise RuntimeError('No obfuscated script found')
RuntimeError: No obfuscated script found
ERROR    Run command failed

Please help me, want can we do. Under linux is work correctly, but we want to use them on windows.

Attaching full set of code.

Waiting for your reply

Best regards,

Ferenczi László

**Comment by laszloferenczi** [comment]
Full logs:
(venv) c:\95_Releases\Builder\bug>pyarmor pack -e " --onedir" main.py
INFO     PyArmor Version 7.7.4
INFO     Python 3.9.13
INFO     Prepare to pack obfuscated scripts with PyInstaller...
INFO     entry script: main.py
INFO     src for searching scripts: .
INFO     build path: dist\obf
INFO     Run PyArmor to obfuscate scripts...
INFO

c:\95_Releases\Builder\venv\Scripts\python.exe c:\95_Releases\Builder\venv\lib\site-packages\pyarmor\pyarmor.py obfuscate -O dist\obf --package-runtime 0 --exclude dist -r .\main.py


INFO     ==================== Run command ====================
INFO     PyArmor Version 7.7.4
INFO     Python 3.9.13
INFO     Target platforms: Native
INFO     Source path is "c:\95_Releases\Builder\bug"
INFO     Entry scripts are ['.\\main.py']
INFO     Use cached capsule C:\Users\laci\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Exclude path "dist"
INFO     Auto exclude output path "dist\obf"
no previously-included directories found matching 'dist'
no previously-included directories found matching 'dist\obf'
INFO     Save obfuscated scripts to "dist\obf"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Obfuscate string value is False
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist\obf
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying c:\95_Releases\Builder\venv\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Patch library dist\obf\_pytransform.dll
INFO     Patch library file OK
INFO     Copying c:\95_Releases\Builder\venv\lib\site-packages\pyarmor\pytransform.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            main.py -> dist\obf\main.py
INFO     Insert bootstrap code to entry script dist\obf\main.py
INFO     Obfuscate 1 scripts OK.
INFO     ==================== End command ====================

INFO     Create temp path: dist\obf\temp
INFO     Found runtime module pytransform.py
INFO     Copy dist\obf\pytransform.py to temp path
INFO     Run PyInstaller to generate .spec file...
INFO

c:\95_Releases\Builder\venv\Scripts\python.exe -m PyInstaller.utils.cliutils.makespec --onedir -p dist\obf\temp --hidden-import pytransform --additional-hooks-dir dist\obf\temp .\main.py


INFO     ==================== Run command ====================
Wrote c:\95_Releases\Builder\bug\main.spec.
Now run pyinstaller.py to build the executable.
INFO     ==================== End command ====================

INFO     Save .spec file to main.spec
INFO     Generate hook script: dist\obf\temp\hook-pytransform.py
INFO     Patching .spec file...
INFO     Save patched .spec file to main-patched.spec
INFO     Run PyInstaller with patched .spec file...
INFO

c:\95_Releases\Builder\venv\Scripts\python.exe -m PyInstaller --distpath dist -y --clean main-patched.spec


INFO     ==================== Run command ====================
403 INFO: PyInstaller: 5.8.0
403 INFO: Python: 3.9.13
433 INFO: Platform: Windows-10-10.0.19044-SP0
440 INFO: UPX is not available.
442 INFO: Removing temporary files and cleaning cache in C:\Users\laci\AppData\Local\pyinstaller
449 INFO: Extending PYTHONPATH with paths
['c:\\95_Releases\\Builder\\bug',
 'c:\\95_Releases\\Builder\\bug\\dist\\obf\\temp']
1752 INFO: checking Analysis
1753 INFO: Building Analysis because Analysis-00.toc is non existent
1755 INFO: Initializing module dependency graph...
1766 INFO: Caching module graph hooks...
1790 WARNING: Several hooks defined for module 'numpy'. Please take care they do not conflict.
1809 INFO: Analyzing base_library.zip ...
5478 INFO: Loading module hook 'hook-encodings.py' from 'c:\\95_Releases\\Builder\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
8488 INFO: Loading module hook 'hook-pickle.py' from 'c:\\95_Releases\\Builder\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
10011 INFO: Loading module hook 'hook-heapq.py' from 'c:\\95_Releases\\Builder\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
11315 INFO: Caching module dependency graph...
11680 INFO: running Analysis Analysis-00.toc
11723 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\99_Tools\Python39\python.exe
12238 INFO: Analyzing c:\95_Releases\Builder\bug\main.py
12244 INFO: Analyzing hidden import 'pytransform'
12287 INFO: Loading module hook 'hook-pytransform.py' from 'c:\\95_Releases\\Builder\\bug\\dist\\obf\\temp'...
12339 INFO: Loading module hook 'hook-platform.py' from 'c:\\95_Releases\\Builder\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
12444 INFO: Processing module hooks...
12472 INFO: Looking for ctypes DLLs
12482 INFO: Analyzing run-time hooks ...
12495 INFO: Looking for dynamic libraries
391 INFO: Extra DLL search directories (AddDllDirectory): []
392 INFO: Extra DLL search directories (PATH): ['c:\\95_Releases\\Builder\\venv\\Scripts', 'C:\\99_Tools\\Python39\\Scripts\\', 'C:\\99_Tools\\Python39\\', 'C:\\99_Tools\\java\\jdk-8.0.342.07-hotspot\\bin', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\WINDOWS\\System32\\OpenSSH\\', 'C:\\Program Files\\TortoiseGit\\bin', 'C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\', 'C:\\Program Files\\Azure Data Studio\\bin', 'C:\\Program Files\\nodejs\\', 'C:\\Program Files\\Docker\\Docker\\resources\\bin', 'C:\\Users\\laci\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\99_Tools\\Git\\cmd', 'C:\\Users\\laci\\AppData\\Roaming\\npm']
14513 INFO: Looking for eggs
14513 INFO: Using Python library C:\99_Tools\Python39\python39.dll
14516 INFO: Found binding redirects:
[]
14529 INFO: Warnings written to c:\95_Releases\Builder\bug\build\main-patched\warn-main-patched.txt
14589 INFO: Graph cross-reference written to c:\95_Releases\Builder\bug\build\main-patched\xref-main-patched.html
Traceback (most recent call last):
  File "C:\99_Tools\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\99_Tools\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\95_Releases\Builder\venv\lib\site-packages\PyInstaller\__main__.py", line 198, in <module>
    run()
  File "c:\95_Releases\Builder\venv\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\95_Releases\Builder\venv\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\95_Releases\Builder\venv\lib\site-packages\PyInstaller\building\build_main.py", line 977, in main
    build(specfile, distpath, workpath, clean_build)
  File "c:\95_Releases\Builder\venv\lib\site-packages\PyInstaller\building\build_main.py", line 899, in build
    exec(code, spec_namespace)
  File "main-patched.spec", line 33, in <module>
    raise RuntimeError('No obfuscated script found')
RuntimeError: No obfuscated script found
ERROR    Run command failed

**Comment by jondy** [comment]
Refer to
https://pyarmor.readthedocs.io/en/v7.7/advanced.html#repack-pyinstaller-bundle-with-obfuscated-scripts
