### ISSUE TITLE
MacOs: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by simonetoscano** [dashingsoft/pyarmor#98]
Hi, I'm on MacOs and I keep getting this error everytime I try to execute my main with `./main`

`[Errno 2] No such file or directory: '/var/folders/81/zgg3srks7_l0ytf4ljkhdkg80000gn/T/_MEIIci0I7/cloudscraper/user_agent/browsers.json'`

I thought it was some licenses issues so I bought license and correctly registered it, also double checked with `pyarmor --version` and everything looks fine.

That's how I builded my python file with pyarmor, maybe there's something wrong there:
`pyarmor obfuscate main.py`
`pyarmor init --src=. --entry=main.py .`
`pyarmor build`
`cd dist`
`pyinstaller main.spec`

and then I created a new folder with my `_pytransform.dylib` and `main` file but it didn't work.

**Comment by jondy** [comment]
Does this command work?
```
pyinstaller main.py
cd dist/main
./main
```
This error `No found browsers.json` seems not the issue of pyarmor.

And you'd better use command `pack` to bundle the obfuscated scripts to executable file, for example
```
pyarmor pack main.py
cd dist/main
./main
```
Here main.py is the plain script, the command `pack` will obfuscate all the py files and call pyinstaller to bundle all required files to one folder.

**Comment by simonetoscano** [comment]
I managed to fix that issue but at the same time, I got a new problem:

> ERROR:root:Unable to load js2py interpreter
An exception occured: 'ModuleNotFoundError' object has no attribute 'message'

Which is related to this imported part of code:
https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/interpreters/__init__.py#L29

It only occurs when I run the exe builded with pyarmor

**Comment by jondy** [comment]
How about not obfuscating script `js2py` like this:
```
pyarmor pack -x " --exclude /path/to/js2py.py" main.py
```

**Comment by simonetoscano** [comment]
@jondy it didn't work.

I made it working simply modifying modules i used to import and now perfectly works when obfuscated. Closing the issue.
