### ISSUE TITLE
[BUG] licence activation error

### ISSUE THREAD

**Issue by hellcodes** [dashingsoft/pyarmor#983]
I bought a pro licence and tried to activate with the key file.
The result is shown below:

![image](https://user-images.githubusercontent.com/17784640/225824575-906efe25-1521-4eee-8553-caf008a44f56.png)

This is the content of 'pyarmor.error.log':

![image](https://user-images.githubusercontent.com/17784640/225825069-1b973aec-7647-46ff-880e-d7f5b3e6d3e7.png)

Any suggestions?
For reference, pyarmor was installed via `pip install pyarmor`.
(pyarmor version: 8.0.5, ubuntu 20.04, conda env, x86_64)

**Comment by shexty1** [comment]
im also getting pretty much this same issue
![image](https://user-images.githubusercontent.com/128191057/226060644-4632892c-3e9f-4704-849d-30e721f2d45b.png)
ERROR    request license token faild (3)

**Comment by Mich-ele** [comment]
> im also getting pretty much this same issue ![image](https://user-images.githubusercontent.com/128191057/226060644-4632892c-3e9f-4704-849d-30e721f2d45b.png) ERROR request license token faild (3)

I have the same problem

**Comment by aewens** [comment]
There was an issue pinned yesterday about the changes made in 8.x:
https://github.com/dashingsoft/pyarmor/issues/980

This looks to be related to those changes where a license from before 8.x needs to be upgraded to work with 8.0+, the steps for which are outlined here:
https://pyarmor.readthedocs.io/en/latest/licenses.html#upgrading-old-license

**Comment by Mich-ele** [comment]
> to be related to those changes wh

I just bought the license

**Comment by shexty1** [comment]
> There was an issue pinned yesterday about the changes made in 8.x: #980
> 
> This looks to be related to those changes where a license from before 8.x needs to be upgraded to work with 8.0+, the steps for which are outlined here: https://pyarmor.readthedocs.io/en/latest/licenses.html#upgrading-old-license

i just bought my license about 1hr ago and have been getting this error trying to bind

**Comment by shexty1** [comment]
if anyone could help would be greatly appreciated really need

**Comment by aewens** [comment]
> if anyone could help would be greatly appreciated really need 

There's an email linked on the documentation website (see above), may try that if your new license still isn't working: pyarmor at 163.com

**Comment by shexty1** [comment]
> > if anyone could help would be greatly appreciated really need 
> 
> There's an email linked on the documentation website (see above), may try that if your new license still isn't working: pyarmor at 163.com

yeah i've emailed waiting on a response hopefully soon do you know how long usually take to reply?

**Comment by shexty1** [comment]
anymore info on this please?

**Comment by jondy** [comment]
@shexty1 try the latest version 8.0.6, also check #980 and the content of `pyarmor-regcode-xxxx.txt`

**Comment by fO-000** [comment]
My license is eligible for the upgrade, but it still reports `ERROR    request license token faild (16)` in 8.0.6.

```txt
$ pyarmor reg --upgrade assets/pyarmor-regcode-xxxx.txt
INFO     Python 3.11.2
INFO     Pyarmor 8.0.6 (trial), 000000, non-profits
INFO     prepare "assets/pyarmor-regcode-xxxx.txt"
INFO     query key file from server

You are about to upgrade old Pyarmor license to Pyarmor Basic
License for Pyarmor 8.0+

The original license no: pyarmor-vax-00xxxx

The upgraded license information will be

License Type    : pyarmor-old
License Owner   : xxx
Bind Product    : non-profits

This license is about to be ussd for non-profits

Are you sure to continue? (yes/no) yes
INFO     process upgrading file "assets/pyarmor-regcode-xxxx.txt"
INFO     old license no: pyarmor-vax-00xxxx
INFO     send upgrade request to server
INFO     update license token
CRITICAL unknown error, please check pyarmor.error.log
ERROR    request license token faild (16)
```

**Comment by shexty1** [comment]
> @shexty1 try the latest version 8.0.6, also check #980 and the content of `pyarmor-regcode-xxxx.txt`

![image](https://user-images.githubusercontent.com/128191057/226305074-ec26a2b3-247c-486d-9e7b-b38184c73c76.png)
i am on 8.0.6 and still getting this error

**Comment by Mich-ele** [comment]
> > @shexty1 try the latest version 8.0.6, also check #980 and the content of `pyarmor-regcode-xxxx.txt`
> 
> ![image](https://user-images.githubusercontent.com/128191057/226305074-ec26a2b3-247c-486d-9e7b-b38184c73c76.png) i am on 8.0.6 and still getting this error

Me too, still can't activate PRO license...

**Comment by jondy** [comment]
I have found the problem. There is a bug in `pytransform3.so` for updating license token, I have fixed it in MacOS (not released).

But for Linux and Windows, because I'm not in the office and the build server is in the office. I'll rebuild them when I'm back in a week.

Meanwhile new license doesn't work.

Sorry for this inconvenient.

**Comment by jondy** [comment]
In short, this week registration doesn't work.

I'll fix it when I'm back office because it need rebuild core libraries, but the build server is not on hand.

**Comment by shexty1** [comment]
> In short, this week registration doesn't work.
> 
> 
> 
> I'll fix it when I'm back office because it need rebuild core libraries, but the build server is not on hand.

no worries keep us updated

**Comment by jondy** [comment]
> ERROR request license token faild (16)

This has been fixed in latest pyarmor 8.0.7 with pyarmor.cli.core == 1.0.2, please update pyarmor

**Comment by shexty1** [comment]
> > ERROR request license token faild (16)
> 
> 
> 
> This has been fixed in latest pyarmor 8.0.7 with pyarmor.cli.core == 1.0.2, please update pyarmor

i've uninstalled the old one and installed new and when installing it says installing 8.0.7 but when i run pyarmor -v it still displays 8.0.6 is this normal ?

**Comment by jondy** [comment]
Sorry, it's a bug. I'll fix it in 8.0.8.

Anyway, registration is OK?

**Comment by shexty1** [comment]
> Sorry, it's a bug. I'll fix it in 8.0.8.
> 
> 
> 
> Anyway, registration is OK?

i'm getting request license token 3 failed now instead of 16

**Comment by jondy** [comment]
@AI-M-BOT
I disable this limitation, please try it again.

**Comment by hellcodes** [comment]
After updating Pyarmor, the registration works.
Then, to do registration in another machine, I used the generated regfile, but there is another error.

**Comment by hellcodes** [comment]
After upgrading Pyarmor, the registration works. Thanks!
Since my issue is resolved, I close this issue.

**Comment by xunonxyz** [comment]
python 3.9
windows10 x64
刚买的专家版
request license token faild (1)
切换Pyarmor多个版本仍然同样问题

**Comment by jondy** [comment]
@xunonxyz 

太早的注册码（不是以 `pyarmor-vax-` 开头的）是不支持升级的，请参考许可证文档中关于升级的说明

不能升级的订单如果是微信和支付宝支付的 email to pyarmor@163.com 退款，如果是 MyCommerce 上购买的，

Email to [Ordersupport@mycommerce.com](mailto:Ordersupport%40mycommerce.com) with order information and ask for refund.
Or click [FindMyOrder page](https://www.findmyorder.com/store?Action=DisplayEmailCustomerServicePage&Env=BASE&Locale=en_US&SiteID=findmyor) to submit refund request
