### ISSUE TITLE
[BUG]: pyarmor register is getting 503 error

### ISSUE THREAD

**Issue by scottwsides** [dashingsoft/pyarmor#989]
(base) phoenix:chemistream-all swsides$ pyarmor register pyarmor-regcode-2794.txt 
INFO     PyArmor Trial Version 7.6.0
INFO     Python 3.10.8
INFO     Read registration code file: pyarmor-regcode-2794.txt
INFO     Start to activate this code
ERROR    HTTP Error 503: Service Temporarily Unavailable

This is seen on linux, mac and windows. However, this has been happening no-stop for at least a day. This is breaking several app pipelines. Please help with this paid version. Thanks

**Comment by jondy** [comment]
Refer to #985

**Comment by DeboBurro** [comment]
have the same error with pyarmor 7.7.4

**Comment by jondy** [comment]
@DeboBurro 

> ERROR HTTP Error 503: Service Temporarily Unavailable

This cause of this error is that running too many `register` command in 1 minute.

The server is configured to allow 3 times for one ip in 1 minutes.

If the first request is OK, it should not be problem.

**Comment by jondy** [comment]
@DeboBurro email your order no to pyarmor@163.com
