### ISSUE TITLE
Are standalone hdinfo.exe still supported?

### ISSUE THREAD

**Issue by SIVLEOL** [dashingsoft/pyarmor#99]
I noticed in the [v4 documentation](https://github.com/dashingsoft/pyarmor/blob/master/src/user-guide.md#get-hardware-information) there are standalone hdinfo.exe, and that this section is not present in the new v5 documentation.

These standalone hdinfo.exe are useful for us, since we'd prefer to not have to install python on the customer computers.

From reading the issues, it sounds like there are some changes to the "pyarmor hdinfo" functionality in newer versions, will the hdinfo.exe be updated accordingly or are they no longer supported?

**Comment by jondy** [comment]
It still supports on some platforms:
https://github.com/dashingsoft/pyarmor-core/raw/master/platforms/win32/hdinfo.exe
https://github.com/dashingsoft/pyarmor-core/raw/master/platforms/win_adm64/hdinfo.exe
https://github.com/dashingsoft/pyarmor-core/raw/master/platforms/linux_i386/hdinfo.exe
https://github.com/dashingsoft/pyarmor-core/raw/master/platforms/linux_x86_64/hdinfo.exe
https://github.com/dashingsoft/pyarmor-core/raw/master/platforms/macosx_x86_64/hdinfo.exe
