### ISSUE TITLE
[Question] Error while running obfuscated scripts in pyarmor v8.x

### ISSUE THREAD

**Issue by CrisV1** [dashingsoft/pyarmor#991]
Hello,

After upgrading pyarmor to version 8.0.6 running certain scripts after obfuscation throw out following error:
```
Traceback (most recent call last):
  File "<dist/translator.py>", line 3, in <module>
  File "<translator>", line 6, in
  File "<translator>", line 7, in
 **TypeError: <**lambda**>() takes 0 positional arguments but 1 was given**
```
different script
```
Traceback (most recent call last):
  File "<dist/_crypto.py>", line 3, in <module>
  File "<_crypto>", line 9, in
  File "<_crypto>", line 10, in
**TypeError: <**lambda**>() takes 0 positional arguments but 1 was given**

```

On previous version of pyarmor  for example :7.7.4; scripts were working fine.  not sure if this is some sort of bug or something changed from v7 to v8 of how pyarmor works.

common thing in scripts that throw errors i found are lines with classes/objects: 
translator.py:
```

1. import json
2. from datetime import datetime
3. 
4. config = None
5. 
6. class tr:
7.   def set_config_file(self, cfg_file):
8. 

```
_crypto.py:
```

1. from cryptography.fernet import Fernet
2. import re
3. import ctypes
4. import time
5. import os
6. import sys
7. 
8. 
9. class Credentials():
10. 	def __ init__(self):
11. 		self.__username = ''
12. 		self.__key = ''
13. 		self.__password = ''
14. 		self.__key_file = 'key.key'
15. 		self.__time_of_exp = -1

```

obfuscation commands:
pyarmor -d gen translator.py
INFO     Python 3.8.12
INFO     Pyarmor 8.0.6 (trial), 000000, non-profits
DEBUG    native platform linux.x86_64
DEBUG    home path: /home/netapp/.pyarmor
DEBUG    command options: {'inputs': ['translator.py'], 'no_runtime': False}
INFO     search inputs ...
INFO     find script translator.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'linux.x86_64'}
INFO     write dist/pyarmor_runtime_000000/pyarmor_runtime.so
INFO     patch runtime file
DEBUG    patching runtime data at 759968
DEBUG    patch runtime file OK
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "translator"
INFO     obfuscating file translator.py
DEBUG    process inline marker
DEBUG    ignore co ""
INFO     write dist/translator.py
INFO     obfuscate scripts OK
///
pyarmor -d gen _crypto.py
INFO     Python 3.8.12
INFO     Pyarmor 8.0.6 (trial), 000000, non-profits
DEBUG    native platform linux.x86_64
DEBUG    home path: /home/netapp/.pyarmor
DEBUG    command options: {'inputs': ['_crypto.py'], 'no_runtime': False}
INFO     search inputs ...
INFO     find script _crypto.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'linux.x86_64'}
INFO     write dist/pyarmor_runtime_000000/pyarmor_runtime.so
INFO     patch runtime file
DEBUG    patching runtime data at 759968
DEBUG    patch runtime file OK
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "_crypto"
INFO     obfuscating file _crypto.py
DEBUG    process inline marker
DEBUG    ignore co ""
INFO     write dist/_crypto.py
INFO     obfuscate scripts OK

while checking configured default parameters in section builder found entries for v8.0.6, while in v7.7.4 were no such parameters.
```
  exclude_restrict_modules = __init__
  exclude_co_names = <lambda> <listcomp> <setcomp> ...

```
could this be the cause of the errors ?

Thanks in advance!

**Comment by jondy** [comment]
Got it, thanks.

I'll check it soon.

**Comment by CrisV1** [comment]
Hello Jondy , thanks for the quick reply and fix.

indeed after upgrading to v8.0.8 initial error disappeared but the following one surfaced  : **No module named 'pyarmor.cli.ruler'**
cat pyarmor.debug.log
```
2023-03-23 10:01:45,459 Python 3.8.12
2023-03-23 10:01:45,459 Pyarmor 8.0.8 (trial), 000000, non-profits
2023-03-23 10:01:45,459 native platform linux.x86_64
2023-03-23 10:01:45,459 home path: /home/../.pyarmor
2023-03-23 10:01:45,468 command options: {'inputs': ['_crypto.py'], 'no_runtime': False}
2023-03-23 10:01:45,468 search inputs ...
2023-03-23 10:01:45,468 find script _crypto.py
2023-03-23 10:01:45,468 find 1 top resources
2023-03-23 10:01:45,498 unknown error, please check pyarmor.error.log
2023-03-23 10:01:45,502 No module named 'pyarmor.cli.ruler'

```
cat pyarmor.error.log
```
31908 MainProcess 2023-03-23 10:01:45,499
Traceback (most recent call last):
  File "/../../py/.venv/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "/../../py/.venv/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "/../../py/.venv/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 144, in cmd_gen
    builder.process(options, pack=args.pack)
  File "/../../py/.venv/lib/python3.8/site-packages/pyarmor/cli/generate.py", line 143, in process
    Pytransform3.pre_build(self.ctx)
  File "/../../py/.venv/lib/python3.8/site-packages/pyarmor/cli/core/__init__.py", line 62, in pre_build
    m = Pytransform3.init(ctx)
  File "/../../py/.venv/lib/python3.8/site-packages/pyarmor/cli/core/__init__.py", line 39, in init
    from . import pytransform3 as m
  File "<maker>", line 744, in <module>
ModuleNotFoundError: No module named 'pyarmor.cli.ruler'
```

was able to fix this error by updating **pyarmor.cli.core** from version **1.0.1** to  **1.0.3.** 

Thanks again!

**Comment by JiaPai12138** [comment]
> Hello Jondy , thanks for the quick reply and fix.
> 
> indeed after upgrading to v8.0.8 initial error disappeared but the following one surfaced : **No module named 'pyarmor.cli.ruler'** cat pyarmor.debug.log
> 
> ```
> 2023-03-23 10:01:45,459 Python 3.8.12
> 2023-03-23 10:01:45,459 Pyarmor 8.0.8 (trial), 000000, non-profits
> 2023-03-23 10:01:45,459 native platform linux.x86_64
> 2023-03-23 10:01:45,459 home path: /home/../.pyarmor
> 2023-03-23 10:01:45,468 command options: {'inputs': ['_crypto.py'], 'no_runtime': False}
> 2023-03-23 10:01:45,468 search inputs ...
> 2023-03-23 10:01:45,468 find script _crypto.py
> 2023-03-23 10:01:45,468 find 1 top resources
> 2023-03-23 10:01:45,498 unknown error, please check pyarmor.error.log
> 2023-03-23 10:01:45,502 No module named 'pyarmor.cli.ruler'
> ```
> 
> cat pyarmor.error.log
> 
> ```
> 31908 MainProcess 2023-03-23 10:01:45,499
> Traceback (most recent call last):
>   File "/../../py/.venv/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 559, in main
>     main_entry(sys.argv[1:])
>   File "/../../py/.venv/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 547, in main_entry
>     args.func(ctx, args)
>   File "/../../py/.venv/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 144, in cmd_gen
>     builder.process(options, pack=args.pack)
>   File "/../../py/.venv/lib/python3.8/site-packages/pyarmor/cli/generate.py", line 143, in process
>     Pytransform3.pre_build(self.ctx)
>   File "/../../py/.venv/lib/python3.8/site-packages/pyarmor/cli/core/__init__.py", line 62, in pre_build
>     m = Pytransform3.init(ctx)
>   File "/../../py/.venv/lib/python3.8/site-packages/pyarmor/cli/core/__init__.py", line 39, in init
>     from . import pytransform3 as m
>   File "<maker>", line 744, in <module>
> ModuleNotFoundError: No module named 'pyarmor.cli.ruler'
> ```
> 
> was able to fix this error by updating **pyarmor.cli.core** from version **1.0.1** to **1.0.3.**
> 
> Thanks again!

Fixed by latest version of pyarmor.cli.core
