### ISSUE TITLE
[BUG] Error while running pyarmor gen v8.0.7

### ISSUE THREAD

**Issue by hyns7** [dashingsoft/pyarmor#992]
I get an error when i try to obfuscate a python code in pyarmor v8.0.7

pyarmor gen main.py
ERROR [Errno 2] No such file or directory: 'C:\\Users\\Dima Ursachi\\.pyarmor\\.pyarmor_capsule.zip'

![image](https://user-images.githubusercontent.com/38110323/227009107-675066ed-4a12-4941-b96c-ff889f24177a.png)

**Comment by jondy** [comment]
What's the content of `pyarmor.error.log`?

**Comment by hyns7** [comment]
![image](https://user-images.githubusercontent.com/38110323/227057206-093a8cef-56e9-4605-a803-3644b3f9db7a.png)

**Comment by jondy** [comment]
Thanks, got it. A quick workaround 
ca7545f15ca124c70017d96f7457f989dc899de3

**Comment by jondy** [comment]
Fixed in 8.0.8

**Comment by cdeeran** [comment]
Hello, I am receiving the same error in version 8.0.17

![image](https://user-images.githubusercontent.com/11359965/227845616-c1ceae9d-6682-42dd-a27b-85668c689f69.png)


![image](https://user-images.githubusercontent.com/11359965/227845704-791cbbba-0aa3-41e1-a6ae-04fedba682e9.png)

**Comment by jondy** [comment]
Fixed in 8.0.19
