### ISSUE TITLE
[BUG] not machine id error

### ISSUE THREAD

**Issue by shexty1** [dashingsoft/pyarmor#995]
hi i have a issue with registering my key i have upgraded to newest version 8.0.7 but i'm getting the error not machine id

**Comment by jondy** [comment]
I have fixed this bug, but the new version isn't released.

The new version will be released about in. 8 hours once I finish smoke test.

**Comment by jondy** [comment]
BTW, please report issue with a clear title.

**Comment by shexty1** [comment]
> I have fixed this bug, but the new version isn't released.
> 
> 
> 
> The new version will be released about in. 8 hours once I finish smoke test.

thanks keep me updated

**Comment by shexty1** [comment]
> BTW, please report issue with a clear title.

sorry about that

**Comment by shexty1** [comment]
> Fixed in 8.0.8, it's released.

that's great it's working now and i have registered thanks i'll close this now
