### ISSUE TITLE
[BUG]  No module named 'pyarmor.cli.ruler'

### ISSUE THREAD

**Issue by baooab2** [dashingsoft/pyarmor#996]
I bought the key and got unknown license type OLD error,
then I bought a new key and got an error ERROR No module named 'pyarmor.cli.ruler'. please help me fix it, I spent $104 for 2 keys but it doesn't work.

![image](https://user-images.githubusercontent.com/84269509/227146934-0af49306-e10a-4319-9d6f-4a2e2c351e23.png)

**Comment by null-routed** [comment]
Experiencing the same on Pyarmor 8.0.8, both on MacOS (Python 3.8.8) and Windows (Python 3.9.10)

**Comment by baooab2** [comment]
> Experiencing the same on Pyarmor 8.0.8, both on MacOS (Python 3.8.8) and Windows (Python 3.9.10)
 i am using python 3.9.9 windows, now have a error ERROR    query machine id failed

**Comment by null-routed** [comment]
> Experiencing the same on Pyarmor 8.0.8, both on MacOS (Python 3.8.8) and Windows (Python 3.9.10)
> i am using python 3.9.9 windows, now have a error ERROR    query machine id failed

Do you mind describing what you did to fix the previous error?

**Comment by jondy** [comment]
Please make sure pyarmor.cli.core==1.0.3

**Comment by baooab2** [comment]
> pyarmor.cli.core=

![image](https://user-images.githubusercontent.com/84269509/227161518-7957e510-babb-4278-b556-e554b4a1b68d.png)

this 1.0.3 
CRITICAL unknown error, please check pyarmor.error.log
ERROR    query machine id failed
error now, please help me.

**Comment by jondy** [comment]
@baooab2 what's the output of command `pyarmor hdinfo`?

**Comment by baooab2** [comment]
> @baooab2 what's the output of command `pyarmor hdinfo`?
![image](https://user-images.githubusercontent.com/84269509/227163775-c2936773-faf0-4f10-b616-29221ea81393.png)

this error now

**Comment by jondy** [comment]
@baooab2 I mean run command `pyarmor hdinfo`

**Comment by baooab2** [comment]
> pyarmor hdinfo

![image](https://user-images.githubusercontent.com/84269509/227166338-9ec74ed3-fb1c-4825-aa14-1cfe7b1499d1.png)

**Comment by jondy** [comment]
@baooab2 I see you purchases an old license, you can ask refund in MyCommerce for that order.

**Comment by baooab2** [comment]
> @baooab2 I see you purchased an old license, you can ask refund in MyCommerce for that order.

give me link to refund, i will refund and buy new license

**Comment by jondy** [comment]
@baooab2  how about this command `pyarmor -d hdinfo`?

**Comment by baooab2** [comment]
> pyarmor -d hdinfo

![image](https://user-images.githubusercontent.com/84269509/227179449-c2740db9-9a95-429b-8549-8dc6c2f3185c.png)

**Comment by null-routed** [comment]
> Please make sure pyarmor.cli.core==1.0.3

This fixed it for me. Thank you.

**Comment by JohnChedder** [comment]
Hi, I got the same problem
![image](https://user-images.githubusercontent.com/111640405/227730574-7d31429a-5328-448e-a44f-1dbd31d53ee0.png)
![image](https://user-images.githubusercontent.com/111640405/227730585-59041342-3d6e-4d85-81c5-591c033f1190.png)

**Comment by jondy** [comment]
@JohnChedder

What's the output of command `pyarmor-7 hdinfo`?

**Comment by jondy** [comment]
For this issue `query machine id failed`, trace it in #1010
