### ISSUE TITLE
[Question] Reset product name from "non-profits" to "TBD"

### ISSUE THREAD

**Issue by fO-000** [dashingsoft/pyarmor#998]
Before pyarmor 8.0.8, there were various bugs when upgrading the old license. At that time, I made a lot of attempts to upgrade the license without problems, including trying to set the product name to "non-profits" to see the effect.

After the release of pyarmor 8.0.8, the issue with old license upgrades was resolved (thanks a lot for your work). But my product name is also bound as "non-profits". Is there any way to change it back to the "TBD"?

**Comment by jondy** [comment]
@fO-000 @AI-M-BOT email to pyarmor@163.com with your order no.
